### ISSUE TITLE
Tracks should explicitly remember last colour used.

### ISSUE THREAD

**Issue by mikobuntu** [LMMS/lmms#1006]
In older versions of LMMS e.g 0.4.15 if i changed the colour on a track in the song_Editor they would be remembered when building blocks on various tracks, but now whichever colour is last assigned will be applied to all other tracks worked in.

**Comment by Spekular** [comment]
@tresf to be consolidated into #1665.

**Comment by tresf** [comment]
This bug report has been consolidated (at least for now) into a placeholder #1665 for better color handling in general.  Feel free to update this bug report or the parent bug as needed.

**Comment by tresf** [comment]
> @tresf to be consolidated into #1665 as this has to do with user definable colors.

A bit torn on this one as it's a regression.  Since it's been open so long, I'm going to consolidate it but I feel that it did deserve the label `bug` when it was written.

As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.
