### ISSUE TITLE
Button to add 5 FX channels

### ISSUE THREAD

**Issue by Sti2nd** [LMMS/lmms#1009]
@diizy It would make it easier than pressing the big + button 5 times... And it is plenty of space. You could perhaps have one button which add 1, one 3 and one 5. And would you care to do it for 1.1?

**Comment by badosu** [comment]
@tresf @diizy @Sti2nd 

What do you think of closing this feature request in favour of https://github.com/LMMS/lmms/pull/1572?

**Comment by tresf** [comment]
Agreed.  Reopen or reference if needed.

**Comment by Sti2nd** [comment]
We'll see
