### ISSUE TITLE
1.0.92 AFP behavior with reverse sample-selections

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#1012]
win32xp
Selected part is not the part that is reversed:'

Insert a wave and select a small part of the complete sound, with START -END
Observe the length information in the sample-window!
Press the reverse-sample button
The START -END markers will now not cover the selected part, and the length is not the same as with the un-reversed selection.
(The same issue also exists, if a selection is made on a full sample that initially is reversed)
AFP need some attention. Wasent all this completely ok in 0.4.15? I remember at lot of work was done on AFP before the last release of the 0.9 series, and as i remeber it, all issues was fixed?

**Comment by Umcaruje** [comment]
@musikBear this is the behaviour of AFP in current master:
![gifrecord_2015-07-02_224652](https://cloud.githubusercontent.com/assets/6282045/8487460/98bcd7d2-210c-11e5-97a7-12b39379b7ed.gif)

I think this issue should be closed.

**Comment by Spekular** [comment]
@Umcaruje Just gotta say, nice sample you got there!

**Comment by musikBear** [comment]
yes this looks fixed - especially if you look at the logic information -eg the *'Sample-length:..'* line. That value does not change at all, when the wave is moved! So it is not important that the display is a tiny wobbely. The size if fixed!
Good work!
Closed
