### ISSUE TITLE
No sound on OS X/Gentoo | Always Preferences on start

### ISSUE THREAD

**Issue by FroznMine** [LMMS/lmms#1021]
Everytime I start the program it opens the audio preferences and has "Dummy" selected. When I choose something else, save these settings and restart LMMS it shows up the audio preferences again with "Dummy".

**Comment by FroznMine** [comment]
Sorry for opening a ticket and then completely ignoring any try to fix the issue. I uninstalled LMMS and forgot about it... Today I got back to it on OS X El Capitan and everything works fine now :+1: 

Thanks for the awesome work you are doing!

**Comment by tresf** [comment]
:+1:
