### ISSUE TITLE
Volume <1% is muted

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#1044]
winXP32
the VOL dial on preset and on song-editor-button, does not control any sound below 1 %
At 1 % the sound kicks in as if it was an on/off button. It's audiable at normal master vol. 100%.
I think this is an old issue, so all versions could be with this. (or it could be my soundcard:)
(mixer is different, lovest setting IS 1%)

**Comment by zonkmachine** [comment]
As of f99aee97cdc748aa5d56a9c2e60ea27834eaff35 this has been fixed. The only odd thing I find about the volume is the master volume which is an IntModel and probably should be a FloatModel. But that's a separate issue. Closing.
