### ISSUE TITLE
All versions -More precise Definition of: "An edit event has taken place"

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#1045]
win32xp  ( -but this must be for all versions
When a user 'edited' project is being closed, a warning 
"current project was modified -save now (y n c)
is shown, but this is not at all the case with a lot of real editing situations:
Adding BB-tracks
Expanding a BB-track
Adding note-blocks
Ajusting a VOL
and propl more (some i havent found 
So , what should an 'edited project' be defined as?
Should 'edited' be exclusive for edits in piano-roll? I dont think thats ok. I would actually sugest a very rigid definition:
Only replay in SE, should be considered 'not edited'. Any other keypress, should spawn an 'edit-event' -I also think that would be rather simple to code?

**Comment by musikBear** [comment]
sorry to bump this up the chain, but This needs attention.
It has been brought forward in forum:
http://lmms.io/forum/viewtopic.php?f=7&t=3269
Just to mention one: If you move a block in song-editor, it is not recognized as a change, and that is a significant difference in a project!
Even copying in song-editor is not recognized, whereas *removing* a block *does* trick 'edited'  
How about that 'replay-only' definition, as 'not-edited' ?
Guess this is a question between:
Will it be most annoying to see this safety dialog *ones too often*, or to loose some of your work as the OP in forum apparently has?

**Comment by musikBear** [comment]
@tresf I would like to have this in 1.2 milestone
I have just found out, that even removing an effect plugin, is not recognized as an 'edited-event'
Would it be very difficult to have any other keypress than song-editor-play, cause an 'edited-event' ?
imo, this is important, because it could lead to loss of projects.

**Comment by tresf** [comment]
> @tresf I would like to have this in 1.2 milestone

Then fix it yourself, otherwise you're trying to set priority on something that has been around for quite some time and no one willing to fix it. 

-Tres

**Comment by Umcaruje** [comment]
Ok, lets try this. I will close this Issue. Once you edit it to be readable and up to standard, you may make a comment about it, and if its ok, I'll reopen it properly label it. 

You have the guidelines here: [`CONTRIBUTING.md`](https://github.com/Umcaruje/lmms/wiki/CONTRIBUTING.md)

I currently can't understand what this issue is about, and I'm tired of trying to decipher it.
