### ISSUE TITLE
VST knobs won't remember settings

### ISSUE THREAD

**Issue by LocoMatt** [LMMS/lmms#1049]
I have recently updated LMMS to 1.0.3 (W7 x64), and started making new project. At all I'm using lot of VST plugins, but in previous versions they worked perfectly and i NEVER had problems with them (Synth1, TyrellN6, EasyQ).
For eg
-lmms don't want to open EasyQ (after reopening project)
-resets all parameter of plugins (all knobs, etc. turned to 0)
Problem is bigger every time when project is opened again.

---

**Edited 2014-12-18 @tresf, added details**

Thanks for the detailed information.  Confirmed.  

It appears EasyQ does not have VST knobs and does not store its settings as parameters within the MMP file (but rather a chunk of Bas64 data).

EasyQ raw data format (encoded/Base64):

``` base64
VkMyIdYAAAA8RXF1YWxpemVyIFBhdGNoRm9ybWF0PSIyIj48QmFuZCBNb2RlPSJQZWFrL0RpcCIgRnJlcXVlbmN5PSI1Mi43MTMyODI2IiBHYWluPSItNy43NTc1NzU3NiIgQmFuZHdpZHRoPSIxLjg5OTk2ODYzIi8+PEJhbmQgTW9kZT0iUGVhay9EaXAiIEZyZXF1ZW5jeT0iNzA1Ni41NjIyNiIgR2Fpbj0iMTEuNjM2MzYzNiIgQmFuZHdpZHRoPSIxLjg5OTk2ODYzIi8+PC9FcXVhbGl6ZXI+AAA="
```

EasyQ decoded data format (XML):

``` xml
VC2!<Equalizer PatchFormat="2"><Band Mode="Peak/Dip" Frequency="52.7132826" Gain="-7.75757576" Bandwidth="1.89996863"/><Band Mode="Peak/Dip" Frequency="7056.56226" Gain="11.6363636" Bandwidth="1.89996863"/></Equalizer>
```

GComp raw data format (already XML):

``` xml
<vsteffectcontrols param8="8:L/R Link:0" param9="9:Output:0" program="0" guivisible="0" plugin="GComp.dll" numparams="10" param0="0:Gain:0" param1="1:RMS/Peak:0" param2="2:Attack:0" param3="3:Release:0" param4="4:Thresh:0" param5="5:Ratio:0" param6="6:Limit:0" param7="7:Softness:0"/>
```

So I compared these findings to a known working VST(i) instrument, the Mini_DiZi plugin.   The working instrument has many knobs just like GComp, but doesn't have the separate "param" section.

If I edit the GComp.dll `vsteffectcontrols` section to say `program="1"` then it moves the knobs, but not to the correct positions.

So sorry to offer more questions than answers:  (@tobydox, @vesa help appreciated here)
1. How is the software is supposed to be remembering these settings?
1. Are these parameters being parsed properly?  Is a value of `param4="4:Thresh:0"` acceptable?

**Comment by miketurn** [comment]
I apologize for opening up this discussion again, but I am a little confused if this issue was totally fixed or not?  I am currently testing out LMMS version 1.1.3 (32Bit) on Windows 7 (64Bit) and it appears that some VST effects save their settings and some don't, but it seems that this issue was closed as in fixed?
An example of a plugin that does not remember its knob parameters is a very popular free vst known as Kjaerhus Audio Classic Chorus.
Is this another issue, where the solution is to find an alternative plugin that works?

Thank You

**Comment by Umcaruje** [comment]
@miketurn this fix happened after that release. does this happen in the RC1 version?

**Comment by miketurn** [comment]
Thank you for getting back to me so quickly, I really didn't think anyone was going to see this.
Ahh good to hear that it is fixed, unfortunately I am one of the people that experiences an instant shut down of LMMS upon opening with the beta version 1.2.0 RC1, so I guess I will have to wait for a future release.  Like I said just good to hear that something like this was fixed.
Again Thank You for your quick response.
