### ISSUE TITLE
Tempo of the track is slower than what is displayed

### ISSUE THREAD

**Issue by unfa** [LMMS/lmms#1050]
**To reproduce:**

0. Grab this project file: http://unfamusic.com/5h1+/unfa-HighOrbit-05.mmpz
1. Play the track;
2. Jump to 50th bar to hear the beat;
3. Hover your mouse over the tempo field (should display 70);
4. Move it 1 up and 1 back down (70→ 71→70);
5. Hear the drastic change;
6. Move the playhead to bar 70 while playing by using the LMB on the timeline;
7. Hear the tempo gone down again.

Looks like for some reason LMMS plays twice slower tempo in this track, until the tempo widget updates it to what it should really be. Something executed when user moves the played updates the tempo to a wrong value. I've never seen this in any other project.

What's stranger: the tempo changes to a wrong value only in certain regions of the timeline. For example clicking of bar 40 doesn't slow the track down, but clicking on bar 70 does.

If I leave the tempo at 71, the problem goes away, but as soon as I switch back to 70 BPM, it returns.

Removing global automation of the tempo box doesn't do anything.

I'm running LMMS 1.0.3 from KX Studio repos.
Can you reproduce this?

**Comment by Umcaruje** [comment]
@unfa can you reproduce this issue on the current master branch?

**Comment by Umcaruje** [comment]
No response in almost 2 months. Closing.
