### ISSUE TITLE
Automation editor cursor redraw

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#1052]
This is not the known 'theme problem' 
It occurs if the mouse is moved *together* with a smaller window *over* the automation-editor ate, and is immediately gone, when the ate get focus.
Looks like it caused by lmms trying to draw the red cross-positioned bars, in are, but the screen are at the same time working on foreground updating.
It is more than likely that this glitch will be different on different hw! 
IMO -Insignificant, but now its at least known

*Edited @tref 2014-12-04, added screenshots, fixed typos :)*
![image](https://cloud.githubusercontent.com/assets/6345473/3797802/c8a8fb0e-1bdd-11e4-9fe1-3fda147086d7.png)

![image](https://cloud.githubusercontent.com/assets/6345473/5299080/39dcbc8a-7b91-11e4-884c-c17b8e7db40a.png)

**Comment by curlymorphic** [comment]
Ive looked at this a few times now. to no avail...

**Comment by tresf** [comment]
For the automation side (I'm guessing):
https://github.com/LMMS/lmms/blob/master/src/gui/editors/AutomationEditor.cpp#L967

For the piano roll side (same bug, much less obvious):
https://github.com/LMMS/lmms/blob/master/src/gui/editors/PianoRoll.cpp#L3064

**Comment by tresf** [comment]
From what I can see, QT is firing the `paintEvent()` code because a window is moving over the top, but it probably should pause any cursor detection/drawing/crosshair/horizonal bar highlighting logic if a different window has focus.

**Comment by curlymorphic** [comment]
> pause any cursor detection/drawing/crosshair/horizonal bar highlighting logic if a different window has focus.

That does solve the problem, I done  that on my first attempt, but though that would be undesirable. I will do that now.
