### ISSUE TITLE
Triple Oscillator waveform/osc mixing control input unavailable (0.9.90+)

### ISSUE THREAD

**Issue by pauljs75** [LMMS/lmms#1055]
In older versions of LMMS, it was possible to hook controller inputs to waveform type and oscillator bank mixing on the 3XO synth. This was quite useful for producing "glitchy" synth sounds with a repetitive pattern. Trying to do the same via right-click now gives an "unavailable" icon, instead of the controller input dropdown.

To achieve the same effect now requires an automation track in the beat/bassline editor, and that beat/bassline pattern track must be continous in the song editor in order to keep driving the repeating pattern. Extra steps vs. just using an LFO to drive waveform and oscillator bank mixing. Essentially it's manually re-creating an LFO, but via an automation track.

Oddly enough, songs made in older versions of LMMS where the LFO controller input could be used with 3XO waveforms and mix modes still seem to work in newer versions of LMMS.

Removing this (useful?) capability which worked in old versions seems like a step backwards in my opinion. Any chance it could be re-implemented?

I think this is also true for any MIDI inputs for the 3XO as well, limits some usefulness of 3XO as a softsynth if played live.

**Comment by Umcaruje** [comment]
@pauljs75 can you reproduce this issue on 1.1.3? 

I can't seem to reproduce this on ubuntu 15.04 x64, with both the master and stable-1.1 branches.

**Comment by Umcaruje** [comment]
No response for over a month. Closing.
