### ISSUE TITLE
Plugin ENV/LFO lfo unexpected behavior

### ISSUE THREAD

**Issue by enrydj** [LMMS/lmms#1062]
LMMS 1.0.3
Linux 3.13.0-24-generic

In some specific conditions sound plays also if no notes are currently played, if volume lfo is enabled. To reproduce please follow these steps:
- Open a new project;
- Open TripleOscillator UI and select ENV/LFO tab;
- Set volume lfo modulation quantity to 1;
- Set volume envelope modulation quantity to 1;
- Set the release envelope value to more than 1;
- Play some random notes;
- Decrease release envelope value to 0.

The sound modulated by LFO continues playing. Is that a wanted behavior or an issue? I would expect that it follows the modified release envelope value.

**Comment by Umcaruje** [comment]
@enrydj can you still reproduce this on the current master branch? I can't seem to reproduce this issue, when I put the release to 0 all sound goes away.

**Comment by musikBear** [comment]
@Umcaruje i can reproduce it om your Master 
Do you want 
*the file?
*a video?

**Comment by Umcaruje** [comment]
Could you make a gif? I'm on limited internet rn, so I don't really have bandwidth to look at videos.

**Comment by musikBear** [comment]
@Umcaruje -dont have any windows software that can make those nice animated gifs, i will see if i can setup a file where automation can initiate that strange thing

**Comment by Umcaruje** [comment]
@musikBear https://gyazo.com/ is very useful and easy to use for gifs.

**Comment by Umcaruje** [comment]
@musikBear please add proof that you can reproduce this issue or it will be closed as invalid.

**Comment by Umcaruje** [comment]
Ok, well both OP and @musikBear haven't responded in 2 months, closing.
