### ISSUE TITLE
Rack LFO controller problem related to LFO period

### ISSUE THREAD

**Issue by enrydj** [LMMS/lmms#1066]
LMMS 1.0.3
Linux 3.13.0-24-generic

Rack LFO controller parameters don't work always correctly. Please follow these steps as an example modulating a plugin filter cutoff:

- add a plugin supporting env/lfo
- set any type of filter and enable it in env/lfo tab
- add a Rack LFO controller and connect the filter cutoff to it

With default settings modulation is correct.

- try different period values, both synchronized and not in sync (X1 mode selected). If period is ≤ 1 beat modulation is correct;
If period is synchronized to 8 beats or > 1 beat modulation is no more correct; it looks like base or other parameters are affected. The issue is also present if ÷100 mode is selected, probably only because period is longer.

**Comment by tresf** [comment]
Sounds similar to #1124.  Can anyone reproduce this on latest master?

**Comment by curlymorphic** [comment]
> The LFO and other controller mechanisms get rewritten in 1.2 so not much to be done here...

What is the current status with this? anything i can do to help?

**Comment by diizy** [comment]
Should already be fixed in master

**Comment by tresf** [comment]
Thanks @diizy.  @enrydj please reopen if this resurfaces.  Closing. :+1:
