### ISSUE TITLE
bug with 8x oversampling

### ISSUE THREAD

**Issue by rawthought** [LMMS/lmms#1068]
Hello,

I can't explain why but I have noticed that the "8x oversampling rendering" render only the left channel.
The right one begin normally but crash after a few second.

In 4x rendering mode, things seems to work well.

**Comment by Umcaruje** [comment]
@rawthought can you still reproduce this issue on the master branch?

**Comment by rawthought** [comment]
@Umcaruje 
Hi, I've made a little test and things seems to work well.
But I'm not using the same OS anymore, I have migrated on Debian 8 Jessie 64 bits...

**Comment by Umcaruje** [comment]
Ok then, I'll close this. If you ever encounter the same problem, and have a reliable way of reproducing it, feel free to reopen this issue :)
