### ISSUE TITLE
Accessing "edit menu | settings" freezes program (1.0.3)

### ISSUE THREAD

**Issue by pauljs75** [LMMS/lmms#1069]
It might not specifically be a problem with LMMS code, but I do suspect a problem with a dependency on some library file not included with the program in the Win32 build. (Program looking for something not there and getting stuck when it needs it. Also would explain why this happens for some people and not others.)

I'm not a programmer, but shouldn't there be error trapping for cases like this? (Return error message "such and such .dll not found", stop trying to use whatever it was looking for, and let user get on with business.)

Oldest version I had where this freezing wasn't a problem was 0.4.13. (Which is why I've held onto it for so long.)

**Comment by badosu** [comment]
@pauljs75 A long time has passed since this issue was reported...

Could you try this on the most recent version of lmms (1.1.0)?

**Comment by tresf** [comment]
Agreed.  Closing.  He can reopen if needed.  Thanks for the bump @badosu .
