### ISSUE TITLE
LMMS needs a startup sound!!

### ISSUE THREAD

**Issue by mikobuntu** [LMMS/lmms#107]
this would be one way of saying "wow, this is definitely an audio workstation!"  .. i have tried to code this in the past, but could never figure out how to call an audio file without either a keyboard press etc. I believe it could be called as a Sample_Play_handle just as main.cpp has loaded the gui and all components, and naturally found the soundcard.

I can supply an audio file in .wav or .ogg format that i have created using LMMS native plugins.

like in FL the StartUpSound can be configured on/off in user settings. [enhancement]

**Comment by tresf** [comment]
Closing as won't-fix since @grindhold never followed up but feel free to reference or reopen in the future.
