### ISSUE TITLE
git master: crash on MIDI import

### ISSUE THREAD

**Issue by davidgerard** [LMMS/lmms#1090]
Crashes whenever importing a .mid, I tried several. git master, compiled from source on Xubuntu 14.04 amd64.

To reproduce:

1. Open LMMS.
2. File->Import ...
3. Select any .mid.

gdb output:

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffcb9ae700 (LWP 19673)]
0x00007fffcdea20d1 in fluid_synth_api_enter () from /usr/lib/x86_64-linux-gnu/libfluidsynth.so.1
(gdb) backtrace
#0  0x00007fffcdea20d1 in fluid_synth_api_enter () from /usr/lib/x86_64-linux-gnu/libfluidsynth.so.1
#1  0x00007fffcdeaa068 in fluid_synth_pitch_bend () from /usr/lib/x86_64-linux-gnu/libfluidsynth.so.1
#2  0x00007fffce14fc56 in sf2Instrument::play (this=0xb1fcaf0, _working_buffer=0xc61d40) at /home/fun/lmms-git-debug/plugins/sf2_player/sf2_player.cpp:649
#3  0x00007fffce155adf in InstrumentPlayHandle::play (this=0xb5d6000, _working_buffer=0xc61d40) at /home/fun/lmms-git-debug/include/InstrumentPlayHandle.h:75
#4  0x00000000004e7867 in process (workingBuffer=0xc61d40, this=<optimised out>) at /home/fun/lmms-git-debug/include/ThreadableJob.h:69
#5  MixerWorkerThread::JobQueue::run (this=this@entry=0x85ffa0 <MixerWorkerThread::globalJobQueue>, _buffer=0xc61d40)
    at /home/fun/lmms-git-debug/src/core/MixerWorkerThread.cpp:70
#6  0x00000000004e78f7 in MixerWorkerThread::run (this=0xb4eb20) at /home/fun/lmms-git-debug/src/core/MixerWorkerThread.cpp:160
#7  0x00007ffff685a32f in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#8  0x00007ffff7bc4182 in start_thread (arg=0x7fffcb9ae700) at pthread_create.c:312
#9  0x00007ffff41d238d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

**Comment by tresf** [comment]
Closed via #1555.
