### ISSUE TITLE
RemoteVstPlugin fails to build

### ISSUE THREAD

**Issue by xoich** [LMMS/lmms#1097]
I download the source from git just like an hour ago, I got g++ 4.9.1 on debian testing.

[ 83%] Generating RemoteVstPlugin
/bin/sh: 1: WINE_CXX-NOTFOUND: not found
plugins/vst_base/CMakeFiles/vstbase.dir/build.make:53: recipe for target 'plugins/vst_base/RemoteVstPlugin' failed
make[2]: **\* [plugins/vst_base/RemoteVstPlugin] Error 127
CMakeFiles/Makefile2:7611: recipe for target 'plugins/vst_base/CMakeFiles/vstbase.dir/all' failed
make[1]: **\* [plugins/vst_base/CMakeFiles/vstbase.dir/all] Error 2
Makefile:133: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by DeathHammer000** [comment]
I'm having trouble with this, no matter what dependencies I install and uninstall. I get the same errors.
