### ISSUE TITLE
Difficult to explore effects

### ISSUE THREAD

**Issue by repsej** [LMMS/lmms#1120]
I find it difficult to find the right effect - there are simply too many to choose from :D

From what I read (*) there are these categories of audio effects:
- Dynamics (compressors, limiters and noise gates)
- Distortion 
- Time Based (reverb, delay and echo)
- Filter (Wah Wah, equalizers, Low-pass and Hi-pass)
- Modulation (chorus, flanger, phaser, ring modulator, tremolo, and vibrato)
- Pitch / Frequency (Pitch-shifters and harmonizers)

I suggest to either:

a) Present the effects in a folder structure based on the category (only works if each effect always belong to just one)

 b) If this is not possible, then instead: tag each effect with the categories it belong to and have toggle buttons for what you want to see.

(*) here http://blog.dubspot.com/understanding-audio-effects-an-overview/

**Comment by tresf** [comment]
I find the effects quite easy to navigate especially after 5c0b359 was merged.  There's still room for improvement from a category perspective but the plugins don't necessarily contain categorical information and they're nearly all provided by 3rd parties.  Closing.
