### ISSUE TITLE
1.0.990 rack LFO inconsistent with chords

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#1124]
Difficult to explain so here is a video:
https://www.youtube.com/watch?v=pTNLtpl4KJA

> Edit: here's a sample track it can be reproduced with -tresf
https://gist.github.com/tresf/cb2f05157fc72623978b

Btwc -The two blocks are *identical* eg block 2 is a carbon-copy of block one, and then the two lower notes was removed, so the notes are not 'different', nor the posistions.

**Comment by tresf** [comment]
Tried to reproduce on Apple to no avail.  This may be a windows-only bug or it may be fixed.  @musikBear I'm closing it out for now, but please reopen if you can still reproduce.
