### ISSUE TITLE
Make "My Home" user definable in settings

### ISSUE THREAD

**Issue by StakeoutPunch** [LMMS/lmms#1130]
I have a two drive setup, an SSD for the OS and a file slave. LMMS only looks at the defined user's folder, which is a problem since my user folder is completely empty (being on the OS drive and not the file donkey).

So, what if the location of "My Home" was definable in the config? The running directory is, so I don't see why this couldn't be.

**Comment by tresf** [comment]
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.
