### ISSUE TITLE
~/lmms in our build tutorials

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms#1135]
Does anyone else have a problem with the fact that our build tutorials all but encourage building in the same directory that the software defaults to?

i.e. `git clone` in the home directory (which is default Terminal landing location for most flavors of Linux/Unix) puts the source code in the same folder that the software uses as its working directory.

I thought of this when @eagles051387 had to do a fresh pull of the github source.  Telling him to blow away `~/lmms` could have unintended consequences. :)

There's not an easy way to prevent this other than changing our default working directory, or making our build instructions specifically move the person from that directory prior to issuing the `git clone` command.

I never use `~/lmms` as the default working directory as I store my samples on a cloud service so I've never blown away any projects or samples, but it seems like it has the potential to mess stuff up.

Thoughts?

-Tres

**Comment by zonkmachine** [comment]
I'm one of those unfortunate persons who actually have managed to accidentally mix the source and working directory up. That was a bit messy, yes.

**Comment by zonkmachine** [comment]
Couldn't we have cmake warn the user if building from `~/`?

**Comment by tresf** [comment]
```
Couldn't we have cmake warn the user if building from ~/?
```

I think it's too late at that point.  I'm not sure how to handle this except perhaps move the default `LMMS WORKING DIRECTORY` to something like `~\Documents\lmms` or something more sane.  This approach would also make it easier for users to locate the directory, since most OSs (e.g. Mac, Windows) don't have a navigation to the user's home directory by default any more.

**Comment by zonkmachine** [comment]
> I think it's too late at that point.

Right. The damage is already done.

This is what the build instructions look like now.
https://github.com/LMMS/lmms/wiki/Accessing-git-repository

> 
> 
> Assuming you have git installed, you first have to get a copy of the Git repository:
> 
> `git clone --recursive https://github.com/LMMS/lmms.git`
> 
> This will clone the master branch, which can be unstable and have bugs.
> 
> If you wish to switch to the current stable branch (for the purpose of compiling LMMS by yourself):

No suggestion on where to clone the source. I use a didrectory, `~/builds`, where I clone stuff but I don't know how people generally do this.

**Comment by tresf** [comment]
> No suggestion on where to clone the source. I use a didrectory, ~/builds, where I clone stuff but I don't know how people generally do this.

Yeah, I've written a lot of tutorials against lmms and they always assume `~/lmms` and it's what I use for all projects `~/foo`.   I'll use this for c, node, java, etc. so that home directory is common for me, I assume it's common for others.

This is a throwback to how old Linux build tutorials were written where they'd have you untar into `~` and then run the various make commands.  I think it's easier to change our default folder than it is to change the way the average Linux user builds software.  If there's no objections to `~/Documents/lmms`, that's where we'll start creating the `LMMS WORKING DIRECTORY` in 1.3.0.  Note, this won't have backwards compatibility issues as it will only be for new LMMS instances.  There will be a bit of a support uptick though with people asking "where are my projects/presets saving to now?" after a clean install.

**Comment by tresf** [comment]
What about changing the default "LMMS WORKING DIRECTORY" to `~/Documents/lmms`.  Reasoning... by default Windows and MacOS make the `$HOME` directory hard to navigate to.  What I mean is, the default Finder/Explorer window doesn't have a shortcut to the `$HOME` directory so finding a project you just made or adding a custom sample isn't all that intuitive.

I understand Linux still treats the `$HOME` directory as a proper home for all files, but I don't see a harm in moving this as our default location.  It would allow the build folder to remain exactly where it is, which is where most of my other code projects are cloned to anyway.

**Comment by midi-pascal** [comment]
@tresf :+1: Linux has a ~/Documents anyways so, why not conciliate OS's the same way?

**Comment by tresf** [comment]
PR submitted at #4288 ready for review/testing.
