### ISSUE TITLE
Mixer playback shortcuts

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#1140]
Currently pressing _space_ when fx-mixer has focus, will not work. I would like to be able to start pause, and stop playback, when i work in mixer. Especially _start_ and _pause_, but a method to 'jump' back one bar (eg 're-listen' to a section) could be very useful.
So this request include playback-control through key /combos, and a 'replay' feature, prefereably with a user controlled distance (could be a setting in _edit_)

**Comment by tresf** [comment]
Consolidated into #3740.
