### ISSUE TITLE
Global transport shortcuts

### ISSUE THREAD

**Issue by unfa** [LMMS/lmms#1144]
_This is based on concept presented here: https://github.com/LMMS/lmms/issues/1140_

The idea is to allow user to control the Song transport without using mouse in the Song window.
I suggest the following hotkeys:
-  Spacebar - play/pause toggle²
- ← - go back one measure²
- → - go forward one measure²
- ↑ - go back four measures
- ↓ - go forward four measures
- Page Up - go back 16 measures
- Page Down - go forward 16 measures
- Home - go to the Song's start (before first measure)²
- End - go to Song's end (after last measure)

² these keys are implemented right now, but work only if Song window is in focus.

**Comment by tresf** [comment]
Consolidated into #3740.
