### ISSUE TITLE
Preset Browser: division between factory and user files fails if factory has folders

### ISSUE THREAD

**Issue by DeRobyJ** [LMMS/lmms#1150]
If you try to create a ZynAddSubFX preset, and you place it in the user folder, it will be shown in the browser at the end of the list, and the "--- Factory files ---" line will be after the first folder, wich is actually a factory folder.

This seems to happen because folders are always on top.
If you create a subfolder in another plugin user-preset directory (for example 3-OSC), there will be no problem. But if you create a subfolder in the factory-preset directory (lmms/data/presets/<plugin>), then you will see that folder on top of the list (as it was a user subfolder), and the last of your presets right under "--- Factory files ---"

*(edited 2014-10-03 @tresf to shrink screenshot to standard size)*
![image](https://cloud.githubusercontent.com/assets/6345473/4505732/dc8398fa-4af9-11e4-9ff0-a0a6ab24febd.png)

**Comment by tresf** [comment]
Closed via #1505
