### ISSUE TITLE
(Apple) MIDI Support

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms#1153]
Per Google+ page:

> **Slapp Major**:  Is connecting a midi keyboard to LMMS not supported at this time? I can not get LMMS to recognize my Akai MPK mini. ﻿

@eagles051387, do you have a midi device you can test with?  Can you help troubleshoot this?

**Comment by mattdeckard** [comment]
Is anyone still working on this? I'd be happy to help if needed.

**Comment by tresf** [comment]
@mattdeckard, no one is actively working on this.  Help would be greatly appreciated.

**Comment by mattdeckard** [comment]
Okay, I'm taking a look at it. I may have questions since I'm new to this codebase.

**Comment by tresf** [comment]
Great. You'll have a lot of help.  We have a great team to assist.

**Comment by Wallacoloo** [comment]
Feel free to hop on IRC if you have any questions: #lmms on freenode.
Though it's not always very active, so it's a bit of a hit or miss as to
whether someone knowledgeable will be online.

**Comment by mattdeckard** [comment]
Awesome, that will be very helpful. Thanks @Wallacoloo

**Comment by rageboge** [comment]
If someone is interested, I'm writing a direct midi adapter (similar to WinMM) from lmms to Mac OS X CoreMidi.framework. As of now, I receive midi events from my Yamaha keyboard and feed them to lmms.
The code is very rough, but promising.

**Comment by tresf** [comment]
>  I'm writing a direct midi adapter (similar to WinMM) from lmms to Mac OS X CoreMidi.framework

From the feedback we receive on Facebook, many people will be interested! :)

**Comment by tresf** [comment]
Also, feel free to start the Pull Request now if you want feedback from developers.  You can add to your own personal repository and it will continue to feed into the Pull Request so that you can ask code-specific questions mid-development.

**Comment by tresf** [comment]
Furthermore, @mattdeckard said he was starting this feature too, so you may want to collaborate with him (such as give him access to your personal repo or vice versa).  This will ensure we don't have unnecessary redundancies in terms of work effort.

**Comment by rageboge** [comment]
thanks for the info @tresf , I could test only my configuration and some feedback from other developers is more than welcome! 
I'll try to clean it up a bit and have a look to the pull request procedure, the code is currently on my private git server cloned from github.

**Comment by rageboge** [comment]
created pull request for the feedback

**Comment by tresf** [comment]
@rageboge terrific!  I've edited your post with a link to the PR.  I'll also edit the PR title with `Closes #1153` to link them from a merge perspective.

**Comment by rageboge** [comment]
thanks @tresf

**Comment by mattdeckard** [comment]
@rageboge Thanks for working on this! I had started looking into it a few weeks back but then life got in the way and I wasn't able to get very far. If I have time this week I'll test a build with your pull request branch with my MIDI controller to see how it works.

**Comment by tresf** [comment]
> I'll test a build with your pull request branch with my MIDI controller to see how it works.

:+1:

**Comment by rageboge** [comment]
@mattdeckard you are welcome! That's life, I also try too many things, but then I have to focus on what is more important in that moment. It would be great if you have time for a test. I'm adjusting the code, but the main part is is already in. Any welcome would be really appreciated :+1:

**Comment by tresf** [comment]
I vote we get the commits squashed and merge this.  This is minimally impacting and we can make patches as we go along.

**Comment by rageboge** [comment]
> I vote we get the commits squashed and merge this. This is minimally impacting and we can make patches as we go along.

:+1: 
some testing would be nice to have, but I'm fine to get it merged and work with patches in case of issues or for improvements. 
In case of updates (lmms was already installed), I think the value for midi interface should already be set to "dummy" as it was the normal value for mac, so the users have to explicitly select "apple midi". The feature could be set as experimental and eventually they can always disable it by setting again the value "dummy" as midi interface.

**Comment by tresf** [comment]
@rageboge before you squash your commits, can you touch up the formatting as mentioned in the PR?  Once that's done, we can merge it in.  We create a release candidate prior to adding major features, so this will be downloadable as a DMG for a while prior to its official release, so hopefully that will bring in the testing needed to get any patches out the door prior to the official 1.2 release.

**Comment by rageboge** [comment]
@tresf  I just pushed a commit which I should solve the formatting issues. One point is still pending (from your comment) but the other comments should be fixed now. I'll then squash the commits
The release plan you described looks very good, thanks for explaining.
Do you have a standard commit message that you want me to use?

**Comment by tresf** [comment]
Responded via https://github.com/LMMS/lmms/pull/2228#discussion_r36578355, thanks.

As far as a commit message, your judgement is as good as ours.  Your initial commit message "Add basic apple midi support" is just as good as any. :+1:

**Comment by rageboge** [comment]
great! Thanks.
