### ISSUE TITLE
Note automation in pianoroll is over Panning/Volume bar

### ISSUE THREAD

**Issue by DeRobyJ** [LMMS/lmms#1156]
![note automation graphic gbug](https://cloud.githubusercontent.com/assets/6437521/4242058/0359ac14-39fa-11e4-9ee3-b40ebdb2c570.png)
Actually I'm not sure if it is a new bug or an old one, because I probably never used strong automations in piano-roll.
Here is 1.0.95

**Comment by Umcaruje** [comment]
Reproduced in Ubuntu 15.04 x64

**Comment by SecondFlight** [comment]
Reminder for myself to reproduce when I get home.

**Comment by SecondFlight** [comment]
As part of a pruning effort, this bug report is archived into a dedicated "Better Workflow" checklist here #4877.
