### ISSUE TITLE
Block size processing issue? Sine wave glitches

### ISSUE THREAD

**Issue by harryhaaren** [LMMS/lmms#1162]
Hey,

I'm chatting with LtRiplet on irc #lmms, and there seems to be a block-size issue with Triple-Osc:
As described in IRC:

```
<LtRipley> i click on the triple oscillator and turn the knobs for sine 2 and 3 to 0
<LtRipley> the bug still happens without turning any knob, it is just more obvious. Then play any note.
```

Screenshots of what should be a sine wave look like this:
![lmms_sine](https://cloud.githubusercontent.com/assets/106664/4278961/02d21184-3d1d-11e4-939c-692ab385cd61.png)
Based on the periodic nature of the glitch, i'd guess its a block-size processing issue somehow: either parameters aren't updated as they should be, or some samples are being skipped.

Update:
Just been informed that Linux/JACK was being used, and Linux/ALSA doesn't have the same issue.

Cheers, -Harry

**Comment by serdnab** [comment]
It is not a problem of lmms, but it is a normal jack behavior when an xrun occurs, try to increase the latency in the jack server and you will see how the artifacts disappear.
