### ISSUE TITLE
Percussive notes ignored and seem to produce empty clips  in Song Editor

### ISSUE THREAD

**Issue by unfa** [LMMS/lmms#1164]
I've noticed that percussive notes (only Note-ON) are not treated the same way as regular notes (Note-ON + Note-OFF). Specifically - they seem to ignored when drawing clips in Song Editor.

As we know, empty clips are gray.
But clips with percussive notes only are also drawn as gray - meanng empty - and that's misleading!

To reproduce:
1. Run LMMS;
2. Create an empty instrument clip in the Song Editor (left click on a bar);
3. Zoom in until you see the rhytmic editor;
4. Insert some notes with LMB or mousewheel-up;
5. Zoom out until the rhythmic editor dissapears;
6. It's gray.

If you rightclick on the clip and select "Add notes" you can create two-bar-long empty-looking clip. Funny, isn't it?

**Comment by Rossmaxx** [comment]
Step notes in song editor has been removed. Close?

**Comment by tresf** [comment]
> Step notes in song editor has been removed. Close?

Sure, was there a particular PR or commit that can be referenced?

**Comment by Rossmaxx** [comment]
#5988
