### ISSUE TITLE
Enhancement: Song-editor note-on-bars as focus-changers

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#1167]
Since the '14' series the 'note-on' bars has been mandatory (diiz felt that there was no cpu-hits involved) I wonder if this feature couldent have a more obvious usefull function.
Changing to an istrument now, mean that the instrument need to have focus. Eg you need to bring that instrument forward, and then *it* will play, when you hit a key.
What if this focus could be *set* with a *click on* then note-on-bar, then it would be much simpler to change instrument for the user, and the note-on-bar would have a more prominant feature, than just playing one single sound.

**Comment by tresf** [comment]
Marking as wont-fix.  Clicking a preview button isn't the same as clicking a "show dialog" button and if we ever settle on a single-window interface, many of these "bring instrument forward" bugs will go away.
