### ISSUE TITLE
Improving Colored Tracks

### ISSUE THREAD

**Issue by Spekular** [LMMS/lmms#1176]
Colored tracks are a very useful feature, and most DAWs have them, but in LMMS, they don't quite fit with the rest of the ui. Ideally the user could use any colors for their tracks and it would still fit with the rest of the program, which is a difficult issue, especially with the current color palette/tints. Here are screenshots showing some other programs colored tracks:
![fl](http://www.djproductor.com/wp-content/uploads/fl-studio-12-descargar-alpha-650x460.jpg)
![logic](http://media.gizmodo.co.uk/wp-content/uploads/2013/10/logicprox.jpg)
![dbglitch](http://illformed.com/img/glitch2-screenshot.png)
With a "rainbow" of tracks in LMMs, it looks like this:
![full color](https://cloud.githubusercontent.com/assets/8918426/4431817/87aa8218-467a-11e4-8a29-8312733ae452.png)
The most clashing colors seem to be reddish. The other programs have grayer colors though. If you grayscale most parts in LMMS, you get this, which is pretty ugly:
![full grayscale](https://cloud.githubusercontent.com/assets/8918426/4431820/953eb3fe-467a-11e4-9916-deee7a5a5c41.png)
It looks a bit brown and lacks contrast. If you tint it slightly blue it's better, but still not great (and removes the point of making it gray in the first place):
![tinted](https://cloud.githubusercontent.com/assets/8918426/4431812/30add9d8-467a-11e4-8c28-cefc3fac7833.png)

These are all only mockups, and really fixing this issue would require quite a bit of GUI work to add more bright/dark contrast rather than color contrast. This may or may not be worth the time and effort, so I'm putting this up to get some opinions. What do you think?

**Comment by Spekular** [comment]
@tresf to be consolidated into #1665.

**Comment by tresf** [comment]
:+1: 

Just make sure to explicitly explain why.
