### ISSUE TITLE
No right channel (LMMS 1.0.3)

### ISSUE THREAD

**Issue by unfa** [LMMS/lmms#1177]
I've got a new issue lately with LMMS version 1.0.3 (can't build 1.1).

Certail projects seem to sometimes "break down" and when I load them LMMS kills the right master channel. It's plain silent and LMMS doesn't auto-connect it in JACK to system output:
![lmms](https://cloud.githubusercontent.com/assets/491704/4431797/5996d990-4679-11e4-9e55-0ba00fe60cf9.png)
I've used JACK Bitmeter to check both channels:
![bitmeters](https://cloud.githubusercontent.com/assets/491704/4431802/76062450-4679-11e4-8514-de25f40c5a99.png)
As you can see, the left channel is fine, but the right is silent. There are no NaNs however, so it's a different issue (not Infinitely Loud Silence bug I reported earlier). I'm routng the L channel to both system output channels to be able to work in mono, but it's kind of hard...

Frequently I see this message after loading a project is done (it also appears when I open or close ZynAddSubFX GUI), don't know if it gives any clue, but here it goes:
![warning](https://cloud.githubusercontent.com/assets/491704/4432037/5827ee14-4683-11e4-8c96-c88c7956aae7.png)

What's important is that this issue __does not__ affect render. Exported WAV files are fine.

I can deliver three project files affected by this - for me they always load in this way in LMMS. Earlier version of the same projects load fine - I guess something must be saved in the project file that triggers this, or maybe it's LMMS itself remembering "whitch projects does it hate"? ;)

Download them here: http://unfamusic.com/5h1+/LMMS-issue-1177.zip

What can I do more to help pinpoint the problem?

**Comment by badosu** [comment]
@unfa Are you able to reproduce this bug on 1.1.0?

**Comment by unfa** [comment]
I still get this (one channel mute, or both) in 1.1.1 in projects that use zita-rev (reverb plugin). Muting a mixer strip that uses this solves it temporarily, removing the plugin, restarting LMMS and reloading the project sorts ti out for good.

**Comment by Umcaruje** [comment]
@unfa do you get this bug when you are not using `zita-rev`? If you are experiencing this with that plugin only, then this is not our bug.

**Comment by tresf** [comment]
No response in two months, and plugin-specific.  Closing.
