### ISSUE TITLE
RemoteVst still running after LMMS exit

### ISSUE THREAD

**Issue by DaAwesomeP** [LMMS/lmms#1182]
They were taking up RAM. I noticed this in Task Manager. There were quite a few of them - one for each of the VSTs I had open in vestige in the most recent project. I had to force quit them.

Windows 8 Pro 32-bit

**Comment by zonkmachine** [comment]
I close this bug as a duplicate of https://github.com/LMMS/lmms/issues/2774

**Comment by lukas-w** [comment]
@zonkmachine I think these are separate issues. #2774 is about `lmms.exe` still running after exit, while this one is about `RemoteVstPlugin.exe` still running.

**Comment by DomClark** [comment]
I'm closing this as a duplicate of #4408 as that issue has more recent discussion and a proposed fix.
