### ISSUE TITLE
VSTs crash sometimes when parameters are changed

### ISSUE THREAD

**Issue by SecondFlight** [LMMS/lmms#1183]
This happens to me with Synth1 and the Syelnth1 demo, to name a couple. After about 5 - 10 minutes of tweaking knobs, LMMS freezes up. It happens when I change a parameter, and I don't think it matters which. It loads fine though, and if I don't change any parameters, it doesn't crash.

Some notes:
The five minutes isn't exact. That's about how long it takes for it to crash, but it has nothing to do with the time.

When I went to test this today, it crashed synth1 when starting and then didn't crash at all after that. I'm sure I didn't change anything except possibly my behavior. (I started synth1, opened up the parameter list and tweaked knobs, then switched to the GUI, then switched to sylenth1 demo without restarting or making a new vestige instance and repeated the same thing - this took at least half an hour.)

I can do further testing if anybody would like me to. This crashing after 5 minutes happened at least 4 times last time I was trying this (same LMMS version and plugin versions).

I'm running Windows 7, 64 bit, but I'm using 32 bit VSTs as far as I know. I can check this if it's important

**Comment by tresf** [comment]
Duplicate report, but on our forums:  [`t1609`](https://lmms.io/forum/viewtopic.php?f=7&t=1609)
