### ISSUE TITLE
Undo copy selection in song editor causes segfault

### ISSUE THREAD

**Issue by friedemann-** [LMMS/lmms#1188]
repoduce:
- open song editor
- select multiple segments
- copy them (click-drag with control pressed)
- undo
crashes with segmentation fault.

EDIT:
seems to happen in special occasions only, I try to figure out.
What I also found:
When undo works, it removes only one of the copied segments

**Comment by Umcaruje** [comment]
@friedemann- can you still reproduce this issue? If you do, please provide a backtrace of the segfault.

**Comment by zonkmachine** [comment]
I'm closing this bug. It's old and no one else seem to experience this. I've tried to reproduce it too but failed.
@friedemann- If you see this crash again, please reopen this issue.
