### ISSUE TITLE
Automation improvement request

### ISSUE THREAD

**Issue by mikobuntu** [LMMS/lmms#119]
LMMS automation could be greatly improved by 2 things

(1) the ability to load and save automations ( opens the possibility for preset automations that can be packed with LMMS

(2) the abiltiy to be able to drop any knob etc onto an existing automation and have it use the automation ( this will probably cause a major rewrite in the source ).
*currently automation is automatically reset/wiped by dropping for example a volume knob onto an existing automation track

thanks Mikobuntu

**Comment by tresf** [comment]
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.
