### ISSUE TITLE
Render from beginning (not play head)

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#1194]
Simple thhing. If the playhead is 'parked' after the last note-block, there will be no render. Its relatively logical, but for a new user, it may be confusing.
Sugest :
first event in render -Park play-head at bar0 beat0
That would fix this (render between loopmarkers is a coming thing, so perhaps this implemented is not nessesary .. dont know ?)

**Comment by tresf** [comment]
Closed via #1476.

**Comment by badosu** [comment]
Nice @curlymorphic! :-)
