### ISSUE TITLE
New FX-Mixer: faders don't work on second screen

### ISSUE THREAD

**Issue by KloppsKopp** [LMMS/lmms#1200]
I use a multi-screen-setup (windows 7 x64, LMMS 1.1.0-RC4 x64)

When LMMS is not located on the primary screen, the volume-faders in the fx-mixer cannot be moved, though the popup displaying the current volume appears. 

All other Controls seem to work properly, so it's not really a game-breaking issue if you're aware of it.

**Comment by Umcaruje** [comment]
@KloppsKopp can you reproduce this issue on lmms 1.1.3?

**Comment by Umcaruje** [comment]
No response for over a month. Closing.
