### ISSUE TITLE
FX-Mixer: "Remove unused channels" / "Cleanup" function

### ISSUE THREAD

**Issue by unfa** [LMMS/lmms#1206]
I've got an idea - if the user wants to remove all unused channels quickly, he needs to do it manually now.

What if a special "Remove unused" function was added? Since moving the channels left and right is possible, changing their order while removing unused ones from between the used ones is not a problem.

How could it work?

   for i in mixer_strips do
      if mixer_strips[i].assigned_inputs.isEmpty() do
      mixer_strips[i].remove()

**Comment by DanWin** [comment]
@tresf Can we close this issue? The feature got merged.

**Comment by tresf** [comment]
@DanWin thanks for the diligence. :+1:
