### ISSUE TITLE
FX-mixer strip color indicating it's type

### ISSUE THREAD

**Issue by unfa** [LMMS/lmms#1214]
![mockup](https://cloud.githubusercontent.com/assets/491704/4647361/f75fe52c-547a-11e4-9a2c-3ecb94cb2cd6.png)

The idea is to make the mixer aware of some strip categories, and colour the strips accordingly to make it easier for the user to see what is what.

Rules for colouring:

1. Color as submix (yellow) if the strip has more than 1 instruments or sends assigned;
2. Color as B+B instrument (violet) if has an instrument assigned that belongs to B+B space;
3. Color as Song instrument (green) if has an instrument assigned that belongs to Song space;
4. Color with default if none above criteria is met (unassigned strips, master strip)

**Comment by Spekular** [comment]
@tresf to be consolidated into #1665.

**Comment by tresf** [comment]
This bug report has been consolidated (at least for now) into a placeholder #1665 for better color handling in general.  Feel free to update this bug report or the parent bug as needed.
