### ISSUE TITLE
Indicator on FX channels with no route to master

### ISSUE THREAD

**Issue by unfa** [LMMS/lmms#1224]
![no output](https://cloud.githubusercontent.com/assets/491704/4691186/1529336e-570b-11e4-80e9-433386d72f77.png)

If you reroute channel A to another channel B (disabling the send to mixer) and you delete the "submix" channel B, the channel A is left with no output. One idea was to automatically re-route such channels to master again, another is to not do that, but show a warning in the mixer so the user knows that removing channel B made channel A unable to sound.

I consider this a related issue to this one: #1219

Both could be implemented with a combobox in the preferences window to choose what LMMS should do if "orphan channels" come into existance.

**Comment by badosu** [comment]
If @unfa or someone else is able to create an artwork for this, with the same geometry of send/receive arrows, I should be able to tackle this.

**Comment by diizy** [comment]
How exactly is "no output" determined?

**Comment by tresf** [comment]
Yeah "no output" is a bit vague.  I would guess unfa means "No route to master".

-Tres

**Comment by badosu** [comment]
Yeah, this is what he describes on his original Feature Request, what would be the possible amibiguity? Or is just the name that annoys you?

**Comment by tresf** [comment]
> Yeah, this is what he describes on his original Feature Request,

:+1:

> If @unfa or someone else is able to create an artwork for this, with the same geometry of send/receive arrows, I should be able to implement it.

I have some reservations about this as the send arrows are covered by the vol knob in some instances where the "no route to master" would need to be displayed.

Should we instead leverage a different part of the UI?  Perhaps make the LED Spinbox an alternate color with some tooltip text?

**Comment by badosu** [comment]
> I have some reservations about this as the send arrows are covered by the vol knob in some instances where the "no route to master" would need to be displayed.

You're right, this is a problem, another possibility would be to change this FxLine widget's border to red-ish glow.

**Comment by Umcaruje** [comment]
But channels that do not send to master are different, as they do not have the send indicator when you select master. I'm not sure what benefits a no output indicator would bring.
![ohwowlook](https://cloud.githubusercontent.com/assets/6282045/5877609/f9674ee2-a320-11e4-8866-94bfb2bcc501.PNG)

**Comment by tresf** [comment]
@Umcaruje that's not a consistent indicator because it only shows when master is selected (or whatever it sends to).

-Tres

**Comment by badosu** [comment]
Yeah, from what I understand, this feature request is probably because on big projects it can get messy after you re-route mixers and add/delete a lot of instruments.

@unfa probably wants better tooling to keep the project sane.

**Comment by tresf** [comment]
> FxLine widget's border to red-ish glow.

Let's prototype that and see how many people complain. :)

**Comment by diizy** [comment]
On 01/23/2015 04:01 PM, Tres Finocchiaro wrote:
>
> Yeah "no output" is a bit vague. I would guess unfa means "No route to
> master".
>

That's still a bit vague... what about sends with 0 gain? Remembering
also that send gains can be automated? What about mutes? And mute
automation?

Lots of small ambiguities there...

**Comment by diizy** [comment]
On 01/23/2015 05:55 PM, Amadeus Folego wrote:
>
> another possibility would be to change this FxLine widget's border to
> red-ish glow.
>

Ewww... maybe something less intrusive.

Performance concerns are also something to consider. We can't keep
checking the connections of all channels constantly, it's lots of wasted
CPU, so the check should be only performed when the connections are changed.

**Comment by badosu** [comment]
> We can't keep checking the connections of all channels constantly, it's lots of wasted CPU, so the check should be only performed when the connections are changed.

That's the plan :-).

But this feature requests needs refinement until we have a proposal that adds quality to the software and solve the usability problem that is posed.

**Comment by tresf** [comment]
> "No route to master".
> > That's still a bit vague... 

In the context of channel routing, it is not vague at all.

**Comment by tresf** [comment]
If it does not, please send us a copy of your desktop installer
