### ISSUE TITLE
Piano Roll pan/volume area note selection

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#1231]
Was this mentioned already?
If it was possible to ctrl+drag a rubber rectangle over the volume-bars, and select all notes inside that area, then the earlier suggested time-slot-selection( #446), would not be necessary. It would be perfectly possible to select everything inside a discrete user defined time-slot.
Could perhaps be dead simple to implement?

*Edit @tresf: Edited body of bug report for spelling mistakes, added mockup*

![image](https://cloud.githubusercontent.com/assets/6345473/4735996/a99e5a54-59e7-11e4-8340-a96f6d565c9f.png)

**Comment by badosu** [comment]
We already have selection by timeline on piano rolls, which already fix this issue's usability concern.

I vote for closing this issue. /cc @tresf

**Comment by musikBear** [comment]
i agree - i close this

**Comment by tresf** [comment]
Wasn't this more of a rubber band tool proposal that could be used in the volume slash pan area? (We have that?)

**Comment by badosu** [comment]
@tresf Yes. No.

The feature request was different in the implementation, but the usability concern was addressed with the Timeline selection (I hope).
