### ISSUE TITLE
song-editor, muted blocks not different when selected (glitch)

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#1239]
all versions. 
If a muted block is selected with *select-tool*, it is not visibly enhanced as *selected*. All other blocks are shown with a differen shading when selected, muted blocks are not.

**Comment by Sti2nd** [comment]
No, he means TCO/segment/pattern in Song Editor

**Comment by badosu** [comment]
Oh, ok, sorry.

**Comment by Sti2nd** [comment]
musikBear in combination with stuff with no names, I can see why you were confused :bear:

**Comment by badosu** [comment]
Confirmed, pasting accurate image: the black patterns touched by selection should present some kind of highlighting.

![2015-01-07-134937_1920x1080_scrot](https://cloud.githubusercontent.com/assets/347552/5648346/f85c7bc0-9674-11e4-85cb-dee37c19edb1.png)

**Comment by badosu** [comment]
@musikBear @Sti2nd I submitted a PR that should fix this issue, see above.

**Comment by Sti2nd** [comment]
I saw it, it looks perfect :)
