### ISSUE TITLE
song editor window doesn't redraw properly at time of maximising

### ISSUE THREAD

**Issue by Lx** [LMMS/lmms#1249]
When maximising the song editor sub-window of LMMS, only the blocks visible before the maximise are redrawn.  In order to cause all of the blocks to become visible, the window must be manually scrolled.  Please refer to the two attached screen shots.

$ lmms --version
Linux MultiMedia Studio 1.0.3
(Linux x86_64, Qt 4.8.6, GCC 4.8.2)

$ dpkg -s lmms | grep Version:
Version: 1.0.3-src-0ubuntu1~ubuntu14.04.1

$ lsb_release -a
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 17 Qiana
Release:	17
Codename:	qiana

Linux Mint 17 is a derivative of Ubuntu Trusty.  Original Ubuntu bug report made [here](https://bugs.launchpad.net/ubuntu/+source/lmms/+bug/1386544).

![image](https://cloud.githubusercontent.com/assets/160164/4854257/839d30b0-608f-11e4-8f73-ba9e2b39688b.png)

![image](https://cloud.githubusercontent.com/assets/160164/4854259/8ed2db9c-608f-11e4-978a-ede7d0434116.png)

**Comment by tresf** [comment]
Closing per #1490.  Please reopen if you feel this bug was closed in error.
