### ISSUE TITLE
NOTES TOO MANY (> POLIPHONY)  - FREEZE 

### ISSUE THREAD

**Issue by oeai** [LMMS/lmms#1251]
i got some Zyna Instrument and added Arp+Octave+Up&Down with pretty fast timings
when i'm playing midi - it's alright, but each time i'm starting record on the second chord lmms goes in frozen mode and then closes up, got this in terminal

  NOTES TOO MANY (> POLIPHONY) - (Part.cpp::NoteOn(..))
  NOTES TOO MANY (> POLIPHONY) - (Part.cpp::NoteOn(..))

**Comment by badosu** [comment]
@softrabbit @oeai Is any of you able to create and share a project that presents this issue?

**Comment by tresf** [comment]
Closing due to lack of response and lack of steps to reproduce by OP.  @oeai Please reopen when you've taken the time to supply both of these. :)

**Comment by unfa** [comment]
I guess we should add the "POLIPHONY" as a separate liguistic bug...
