### ISSUE TITLE
Segment/clip not showing whole last note in Song Editor

### ISSUE THREAD

**Issue by Sti2nd** [LMMS/lmms#1255]
I think it is because of the "outline"/borderline which is really an inline leaves less space for viewing the notes.
![image](https://cloud.githubusercontent.com/assets/6373430/4870409/8f941734-6167-11e4-8e0d-d375c0d0fa60.png)
vs. how LMMS 0.4.15 shows it
![image](https://cloud.githubusercontent.com/assets/6373430/4870369/0d5cbaac-6165-11e4-935e-2842b1db605b.png)
0.4.15 is a little bit better. From the last segment it seems like the note is actually drawn on top of the black outline? Is the first note not drawn from the first pixel? You still have the problem of cutting of the last note (visually) in 0.4.15 when a new segment follows immediately after. 

I guess the code is still the same, thus with less space for the actual note view because of the outline. The fact that the last note was already cut off in 0.4.15, makes the last note look like a tiny pixel from version 1.0.0. So I guess the box the notes is allowed to draw in should be reduced with one pixel in all directions? This would still cut off the last note as in 0.4.15, though.

**Comment by badosu** [comment]
@tresf Can we close this one? #1506 was merged.

**Comment by tresf** [comment]
:+1:
