### ISSUE TITLE
Would it be ok to have this preset in the official release?

### ISSUE THREAD

**Issue by DeRobyJ** [LMMS/lmms#1261]
http://lmms.io/lsp/?action=show&file=6060

Just done a strong organ preset with 3OS. I want it to be featured in the program: should I firstly try to remove dirtiness from it?

**Comment by tresf** [comment]
I'm closing this since @DeRobyJ is fine with just doing a pull request instead.  Feel free to submit a pull request with presets you feel should go in.  I'll tag a few testers in it for feedback prior to merging.

-Tres
