### ISSUE TITLE
Merging Cools Songs and Demos?

### ISSUE THREAD

**Issue by unfa** [LMMS/lmms#1274]
I don't understand what's the difference. Shouldn't we merge the two?

**Comment by rubiefawn** [comment]
...Didn't I merge them, and get rid of OldStuff?

_Checks LMMS Install_

Um, I don't think my branch was ever merged...

**Comment by rubiefawn** [comment]
Nevermind. It was merged. I only organized CoolSongs and OldStuff.

**Comment by tresf** [comment]
@cubician, still want to work on this?

-Tres

**Comment by tresf** [comment]
@cubician can you tackle this for the 1.2 milestone?

**Comment by Umcaruje** [comment]
If @cubician is unavailable, I can tackle this task.

**Comment by tresf** [comment]
:+1:
