### ISSUE TITLE
enhancement: automation, add option 'Mirror pattern'

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#1289]
im sure all have had/ done this task.
you make a smooth pattern that works well. Then you think - oh, it would have been nice if i could 'flip' this for the oposit transistion. I sugest to add a button 'Mirror pattern' So a user will get 2 automation blocks, one with the pattern user drawed, and one exactly oposit, or mirrored of the pattern.

**Comment by tresf** [comment]
Closed per #1486
