### ISSUE TITLE
No unit tests

### ISSUE THREAD

**Issue by gzankevich** [LMMS/lmms#13]
Guys, it's 2014 and the project doesn't have a test suite. You can't expect to prevent regressions or be able to refactor safely without the basics in place.

**Comment by badosu** [comment]
@Lukas-W Added a test suite infrastructure to LMMS right?

The only problem is that this issue will never be closed unless we define an objective goal here, I vote to close this.

**Comment by Lukas-W** [comment]
Agreed.
