### ISSUE TITLE
QMap vs. QHash or QList in tabBar Class

### ISSUE THREAD

**Issue by phansen73** [LMMS/lmms#1320]
Hi, 

I am working on an assignment for a data structures class where I work on an open source project (I chose LMMS!). The assignment is to experiment with a data structure to improve time complexity or fix an issue. Basically, it is a foray into open source programming and a way to see some data structures used in real applications.

I picked the QMap used in the [tabBar class](http://fossies.org/dox/lmms-1.0.3-src/classtabBar.html) to store which tabs are open. It is not a major issue, but I am curious about why a QMap was chosen over either a QHash or simply a QList. So I will be looking into Qt's structures and how they fit in with the tabBar class.

Any suggestions or comments you all have are absolutely welcome, as interacting with the LMMS community is also a part of the assignment!

Thanks.

**Comment by badosu** [comment]
@phansen73 Any improvement can be sent as a PR. If you are making modifications and want some review to polish it you can send a work-in-progress as a PR as well.

But if we don't have any objective issue here we should close this issue.

You can post questions about LMMS to the lmms devel mailing list, see [here](http://sourceforge.net/p/lmms/mailman/lmms-devel/).
