### ISSUE TITLE
Sample Track has no "number" area for FX Mixer

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms#133]
As described, most tracks can have an FX channel from the mixer added to them.

This is useful, as two similar sounds may borrow from the same reverb, delay, distortion, etc.

When adding Sample Tracks, the FX added must be added directly to the Sample Track effects chain, which prevents composers from borrowing from the FX Mixer.

The recommendation is to allow Sample Track to be assigned to an FX channel similar to how other LMMS tracks are handled.

Mock-up screenshot provided for reference:

Current options:
![image](https://f.cloud.github.com/assets/6345473/1997582/58e96508-8527-11e3-9cb3-dd6130813d5f.png)

Proposed option(s):
![image](https://f.cloud.github.com/assets/6345473/1997619/c9b71654-8527-11e3-8564-f1410aaf34e3.png)

**Comment by Reaper10** [comment]
I love the pitch knob on the mocup
