### ISSUE TITLE
Qmaps!

### ISSUE THREAD

**Issue by kloughra** [LMMS/lmms#1336]
Hello!

I am working on a project for a Data Structures course, and the assignment is to find a data structure in an open source project, experiment with it, and hopefully improve the time complexity or correct a predefined issue. The goal is to get some experience with real applications of data structures. One of my project partners, Patrick Hansen, has already posted and introduced himself. 

I am currently exploring a map data structure called infoMap which keeps baseline tracks as values, used in the bb_tracks class. I am hoping to learn about your Qmaps data structure and how it handles collisions. 

I would love to hear any comments or suggestions!

Thanks!

**Comment by zonkmachine** [comment]
> and make a proposal.

No proposal... :cry:  closing
