### ISSUE TITLE
Qvector questions

### ISSUE THREAD

**Issue by hfredric** [LMMS/lmms#1337]
Hello!

I am working on a project for a Data Structures course (Katie and Patrick have already posted in here, sorry for the redundancy), and the assignment is to find a data structure in an open source project, experiment with it, and hopefully improve the time complexity or correct a predefined issue. 

I am currently looking at a Qvector in your graph.h file in the include directory. I am wondering if there are any edits you would suggest I make to this structure to enhance it and I am curious to see why a vector was chosen for this. I was considering implementing a possible sort option, however I am not sure how this affect the output of the wave forms as I am not very familiar with the widget. I am also curious to see if you have any suggestions of other data structures I could explore more. Please let me know what your thoughts are!

Thank you!

**Comment by badosu** [comment]
@hfredric You can post questions about LMMS to the lmms devel mailing list, see [here[(http://sourceforge.net/p/lmms/mailman/lmms-devel/).

@tresf Can we close this issue?
