### ISSUE TITLE
Exclude tracks from master pitch

### ISSUE THREAD

**Issue by kpone33** [LMMS/lmms#1345]
It would be nice to be able to exclude specific tracks from being transposed by the master transpose slider on top of LMMS. Drum samples or Drumloops don't necessarily need to be transposed, so it would be very nice if one could say that a track will not be transposed by the global transpose.

**Comment by curlymorphic** [comment]
> If and when our Sample Track gets the instrument track widget, we could simply have a break inheritance icon next to pitch (apologies for the terrible mockup)

How about an LedCheckBox, or do we already have link/unlink icons. in thinking about ui consistency?

**Comment by Sti2nd** [comment]
> How about an LedCheckBox

Depends where you want it? I think it could become very little space in the instrument track if both a new LED and indention is going to be a reality https://github.com/LMMS/lmms/issues/735
![image](https://cloud.githubusercontent.com/assets/6373430/5691731/6ea0cab8-98d5-11e4-819f-a74abd8e23f9.png)

**Comment by curlymorphic** [comment]
I was more refering to this mock up from tres , sorry should have said that

![image](https://cloud.githubusercontent.com/assets/7412852/5691736/6f76fc62-98cd-11e4-9e71-7067a06383fe.png)

**Comment by softrabbit** [comment]
Can't say I have a better place for it, but a button next to (and grouped with) the pitch knob and range selector looks to me like it would turn off the instrument pitch bending and not just ignore master pitch.

**Comment by tresf** [comment]
> Can't say I have a better place for it, but a button next to (and grouped with) the pitch knob and range selector looks to me like it would turn off the instrument pitch bending and not just ignore master pitch.

Good point.  Can we have Green (inherited) Yellow (non inherited) and Off/Red (disabled) ?

**Comment by curlymorphic** [comment]
> Good point. Can we have Green (inherited) Yellow (non inherited) and Off/Red (disabled) ?

Im confused, i dont understand the inherited state.  

I though an instrument was to follow global pitch or not, I obviously am missing something?

**Comment by tresf** [comment]
> I though an instrument was to follow global pitch or not, I obviously am missing something?

Yes it should.  @softrabbit's point is that such an LED may be suggestive of enabling/disabling pitch entirely.  I was simply proposing a way to help although we don't really have 3-state LEDs yet... :confused:

**Comment by curlymorphic** [comment]
But i simply dont understand the 3 states? sorry

anyway a quick screenie of what I have

![image](https://cloud.githubusercontent.com/assets/7412852/5691944/c2d98ad8-98d6-11e4-9eca-1de3bfc585fc.png)

Do we need txt? the Led control has no label
Is it in the right place?

**Comment by tresf** [comment]
State 1 - Pitch is enabled and inherited from master pitch
State 2 - Pitch is enabled but inheritance is broken from master pitch
State 3 - Pitch is disabled completely

**Comment by curlymorphic** [comment]
Now I understand. 

Is this a real need though, the disabling of pitch, as pitch is applied on a track by track basis. 
I feel a tri state could be confusing, and inconsistent.

**Comment by Spekular** [comment]
I think a led next to the pitch knob or somewhere in that area is clear
enough as long as it has a hover text explaining it. There also seems to be
room for two leds (vertically), so there could be one for "inherit master
pitch" and one for "enable pitching", both on by default.

**Comment by tresf** [comment]
> Is this a real need though, the disabling of pitch, as pitch is applied on a track by track basis. 
I feel a tri state could be confusing, and inconsistent.

Good point.  Shall we do green/yellow then?  I still tend to agree with @softrabbit that the "off" indicator is misleading when directly besides those components.

**Comment by curlymorphic** [comment]
> Shall we do green/yellow then?

The only problem with that, iirc is our LedCheckBox's only use 1 color.

**Comment by tresf** [comment]
Yes good point... it appears to be hard-coded with the off pixmap.  We can worry about aesthetics later I suppose.

https://github.com/LMMS/lmms/blob/master/src/gui/widgets/LedCheckbox.cpp#L119

**Comment by curlymorphic** [comment]
Wll this was done ages ago, except for labeling. 

LedCheckBox has no label, or hint text.

If i place a label below the checkbox, there is insufficent space for any meaningful text.

**Comment by softrabbit** [comment]
There's room for one more tab in the instrument settings, maybe that should be created and this pitch switch thing could go there?

**Comment by curlymorphic** [comment]
> LedCheckBox has no label, or hint text.

well making silly claims like that publicly jolted my brain

![image](https://cloud.githubusercontent.com/assets/7412852/5692351/2a3eea34-98ea-11e4-8738-6b0ad355e61f.png)

thats with mouse over the check box, (sorry screen shot dont show cursor)

> There's room for one more tab in the instrument settings, maybe that should be created and this pitch switch thing could go there?

A tab just for a checkbox?

**Comment by softrabbit** [comment]
> A tab just for a checkbox?

It may sound like overkill, but sooner or later there'll be something else that needs a checkbox or knob that doesn't fit in the other tabs, so why not stake out some territory for expansion. Call it "MISC" or something like that.

**Comment by curlymorphic** [comment]
sure

**Comment by tresf** [comment]
> It may sound like overkill, but sooner or later there'll be something else that needs a checkbox or knob that doesn't fit in the other tabs, so why not stake out some territory for expansion. Call it "MISC" or something like that.

Sorry, late to the convo, but I think this is cleaner and less confusing. :+1:

**Comment by tresf** [comment]
Closed via #1593
