### ISSUE TITLE
Minimized Song_Editor & BB_Editor tracks should not allow graphics to be cut off.

### ISSUE THREAD

**Issue by mikobuntu** [LMMS/lmms#1350]
Whenever I use Shift+LMB+Drag to minimize the vertical height of a song editor track to its minimum height there will be parts of the knobs and leds showing. ( see image )

I expect that whenever we drag to anything < the standard height in pixels of a track that the gui elements i.e knobs, leds and friends will disappear, leaving an overall cleaner looking GUI.

So basically if we drag > the standard instrument track height nothing gets effected, the GUI elements work as expected here, but once we decrease the track size below the current standard height then the knobs etc should disappear until dragged to the standard size again.

This also applies to the BB_Editor tracks, we might want to just remove the knobs etc with minimal height but perhaps scale the step leds?

![screenshot from 2014-11-25 14 45 57](https://cloud.githubusercontent.com/assets/335217/5185036/03df9bae-74b4-11e4-9ceb-7d2e143b32dc.png)

**Comment by curlymorphic** [comment]
@tresf is there any chance of a summary of what's wanted here please?

sorry after reading this im confused to what is required.

**Comment by Sti2nd** [comment]
Increase the min height allowed, to the height of a newly added track. So that you can only increase the height of a track in the future and not discover the bad GUI. Please implement track grouping at the same time, jk, but not really.

**Comment by curlymorphic** [comment]
> Increase the min height allowed, to the height of a newly added track.

cool, thats sounds simple.



> Please implement track grouping at the same time

is there a discussion on this yet?

It would need to know how this should be implemented, what is required, gui decisions, is this just for visuals or is audio grouped. Im sure there are plenty of more details to work out. 

I would be up for doing this.

**Comment by tresf** [comment]
> Please implement track grouping at the same time

And the moon and the stars?  Don't be preposterous! :)

**Comment by Sti2nd** [comment]
I was just asking, someone has to implement it...

Here it is @curlymorphic https://github.com/LMMS/lmms/issues/735 This might be serious shit, good job so far, and you decide if you want to have a go at it or not. :)

**Comment by tresf** [comment]
> I was just asking, someone has to implement it...

Well, I see you changed the tone of your original question, but let's please be mindful not to look a gift horse in the mouth, so to speak.

**Comment by tresf** [comment]
Closed per #1560, thanks Dave!

**Comment by curlymorphic** [comment]
:)

**Comment by diizy** [comment]
On 01/06/2015 01:10 AM, Dave wrote:
>
>     Please implement track grouping at the same time
>
> is there a discussion on this yet?
>
> It would need to know how this should be implemented, what is
> required, gui decisions, is this just for visuals or is audio grouped.
> Im sure there are plenty of more details to work out.
>
> I would be up for doing this.
>

This should be postponed for 2.0.
