### ISSUE TITLE
A Better Transport

### ISSUE THREAD

**Issue by Reaper10** [LMMS/lmms#1357]
![a better transport](https://cloud.githubusercontent.com/assets/8137561/5231918/cca6ab2c-7707-11e4-8ed2-1726b04cb936.jpg)
You should add a transport panel next to timer, beat and bar, BPM panel or an all in one panel with a play, stop, fast forward, rewind, record, loop and a metronome, and the audio scrubbing buttons so you don't need them in song editor. The record button should be all in one recording for audio and midi. You can keep the play, stop buttons on beat and base line editor I like that. On the metronome add a pre count button and a way to set the pre count linkth, and a metronome on/off switch or button and a knob or slider to controll metronome volume. a blinking metronome led icon linked to the BPM
![a better transport](https://cloud.githubusercontent.com/assets/8137561/5231922/e0236316-7707-11e4-8bcd-991c0e7f01af.jpg)
keyboard shortcut for metronome on could be ctrl m. keyboard shortcut for metronome off could be alt m 
The blinking metronome led icon could also be the tap tempo button for the song bpm.
Record on/off keyboard shortcut could be CTRL R.
All tracks needs a viable blinking LED record button  next to the mute and solo buttons to act as a ready to record button, the main record button starts recording on all of the record ready tracks got the idea from ardour.  The record while playing song button/ icon could be used as a record mode called Monitor Record mode. When it's on you will see the record while playing song button/ icon and not just record.  To turn this mod on right click the record button/ icon and click the option or CTRL R & the spacebar.. I thought it all so be good idea to have a midi learn button somewhere on the transport.
Adding a midi learn button is here #2283

**Comment by Reaper10** [comment]
Should there be a tap tempo button for the song Bpm?

**Comment by Sti2nd** [comment]
Yes, should you make it?

**Comment by Reaper10** [comment]
sorry I don't know how to program, wish I did:(

**Comment by softrabbit** [comment]
Is the metronome really something that has to be visible all the time or is it only useful when recording? I'd suggest a window of its own for it, or maybe a new tab at the left side of the main window.

**Comment by tresf** [comment]
> Is the metronome really something that has to be visible all the time or is it only useful when recording? 

I guess this depends on your definition of "useful" as well as "recording".  I feel the metronome can be useful in almost all contexts of composing, especially considering not all composers really know what an increase in -- say 10 -- BPM actually sounds like audibly.

I think the metronome has quite a bit of value as a permanent part of the GUI, wherever it ends up fitting.

**Comment by Reaper10** [comment]
The blinking metronome led icon could also be the tap tempo button for the song bpm.

**Comment by Reaper10** [comment]
All tracks needs a viable blinking LED record button  next to the mute and solo buttons to act as a ready to record button, the main record button starts recording on all of the record ready tracks got the idea from ardour.

**Comment by Reaper10** [comment]
The record while playing song button/ icon could be used as a record mode called Monitor Record mode. When it's on you will see the record while playing song button/ icon and not just record.  To turn this mod on right click the record button/ icon and click the option or CTRL R & spacebar..

**Comment by Reaper10** [comment]
This had some good ideas Better metronome #475

**Comment by Reaper10** [comment]
I thought it all so be good idea to have a midi learn button somewhere on the transport
mockup
![midi icon learn](https://cloud.githubusercontent.com/assets/8137561/9413831/146f36ea-47fa-11e5-8874-a9a753879f4a.jpg)

**Comment by tresf** [comment]
If this is a future feature it should be better explained in a separate bug report.

**Comment by Reaper10** [comment]
no prob just trying not to flood  tracker

**Comment by tresf** [comment]
@Reaper10 your enthusiasm for the improvement of LMMS is terrific, but sometimes we have to build the walls before we chose which color we're going to paint them.  Your idea should be brought into a master bug report that you maintain and constantly update called "Reaper10's wishlist" because some of these items are years out, and we're trying to get things working with what we have today.

For example, "Better transport" is a well defined and needed GUI enhancement that we plan to implement.  "MIDI Learn" however is something which isn't well defined and is entirely unrelated to fixing the toolbar we already have.

**Comment by Reaper10** [comment]
Adding a midi learn button is here #2283

**Comment by tresf** [comment]
Consolidated into #3740.
