### ISSUE TITLE
changing sample track to audio tack

### ISSUE THREAD

**Issue by Reaper10** [LMMS/lmms#1360]
the sample track is so close to being a audio track all you need to add is, after you change the name of the track:

1 a pan knob to track in song editor.
2 a record button next to the mute and solo buttons in song editor. 
3 in the gear menu add audio input  menu.
4 add a slider, pam knob,send button and knob to fx box you already have.
5 a fx chanel select box like you have for instruments and have it be same chanel in fx mixer and fx's in fx box that way if you don't want to mas with the fx mixer you don't have to.
6 have all buttons, knobs, and sliders move together with the fx's chanel buttons, knobs, and sliders.
7 add synic between the volume knob in the track in song editor and synic between the volume slider in fx chanel and add synic between  pan knob in fx chanel and pan knob to track in song editor.
8 add a light like you have in the instrument channels to show audio input.
9 being able to change the audio clip color to any color you want to.

**Comment by Reaper10** [comment]
maybe add a record button to the track.

**Comment by Reaper10** [comment]
one thing I forgot is being able to change the audio clip color to any color you want to.

**Comment by tresf** [comment]
@Reaper10, merged with #1471.  Marking as duplicate.  Please click "Watch" at the top toolbar on that topic to receive update notifications. :+1:

**Comment by Reaper10** [comment]
Sample Track Routing Box

![sample track routing box](https://cloud.githubusercontent.com/assets/8137561/7106987/c4ee0b4c-e119-11e4-9929-5ef4506e0ae3.png)
