### ISSUE TITLE
Native Eq plugin

### ISSUE THREAD

**Issue by curlymorphic** [LMMS/lmms#1376]
Im planning a parametric  eq plugin, 

below is my initial layout, mainly to get the controls onto the screen. layouts, colours, fonts, backgrounds were not of priority.

![Image of Initial UI]
(http://studio6plus1.com/images/eqmk1.png)

The large black box in the middle, with be a dual spectrum analyser, showing before/ after in different colours, There will also be drag-able handles for each of the filters. The Fader to the left and right are input and output gain.
   Below this is the old school knobs (undecided if this is needed at all, but will leave in until testing ).
The Hp and Lp bands only have frequency and resonance controls, all the other eqs, have there gain controlled by the fader. My goal is for the meters on each fader show the spectrum data for the filter frequency.

Now i have an initial concept, I would be grateful for any feedback.

**Comment by rubiefawn** [comment]
I like this! You even did the whole 'hide knobs' thing... As far as the small UI goes, it is fantastic! I do have a couple suggestions, though...

- Make the band indicator circles have a smaller outline
- Have a curve representing the actual modification of the spectrtum
- Label the In and Out gain faders
- Modify the background and stuff to match the rest of LMMS a bit

Besides that, the UI is perfect, as far as I'm concerned. :D Keep up the great work! I am so excited for this to be released!

**Comment by rubiefawn** [comment]
As far as the spectrum analyzer goes, having both before/after transparently filled might look better. That way you can see the contrast better.

**Comment by rubiefawn** [comment]
YESSSS I LOVE IT

**Comment by Umcaruje** [comment]
The EQ plugin has been accepted into master, should this be closed?

**Comment by tresf** [comment]
Dave, is there a reason this has all of the channels disabled by default?  I'd expect the opposite when I add this to an instrument or FX channel :) 

(@Umcaruje @Sti2nd, etc opinions welcome)

![screen shot 2015-04-06 at 10 21 12 am](https://cloud.githubusercontent.com/assets/6345473/7005541/c16e6d0e-dc46-11e4-8cb8-9ffbbe149ed5.png)

**Comment by curlymorphic** [comment]
> Dave, is there a reason this has all of the sliders disabled by default?

There are 2 reasons, both of questionable validity

1. It was the way i was taught to use an eq.
2. performance, each band being used requires processing power. This was very important years ago, im unsure of the importance, when compared to usability on modern hardware.

I guess what I am saying is im happy to go with what ever is decided :)

What format / where should I write up the documentation for this?

**Comment by tresf** [comment]
> What format / where should I write up the documentation for this?

Tagging a few users is probably a good start.  I expect plugins to be enabled by default.  When all sliders are disabled, it is quite confusing why my sound isn't changing.

**Comment by Umcaruje** [comment]
I think at least one band should be enabled. 

>What format / where should I write up the documentation for this? 

I can provide you with a wiki account and you can add the EQ and any other new effects over at http://lmms.io/wiki/index.php?title=Effect_Plugins

**Comment by curlymorphic** [comment]
> I can provide you with a wiki account and you can add the EQ and any other new effects over at http://lmms.io/wiki/index.php?title=Effect_Plugins

thanks :)

**Comment by Umcaruje** [comment]
Just PM me your desired username and your mail and you'll be good to go :)

**Comment by Wallacoloo** [comment]
I'd say either all bands should be enabled or all should be disabled, but definitely not a mix of the two. 

Personally, I prefer to start with all bands disabled and enable them on-demand. This saves a lot of trouble especially when it comes to automating them - if you default to all bands enabled and some of them *look* like they aren't doing anything, you can't be sure if they're safe to use for something else unless you check their automation. But if you only enable them on-demand, then you know the ones that look like they aren't doing anything must just be idle at this part of the song and you shouldn't mess with them.

Perhaps the solution is to make it more obvious (to newcomers) when a band is disabled.

**Comment by tresf** [comment]
The other EQ plugins have the knobs/bands enabled by default.  I vote we remain consistent.

![image](https://cloud.githubusercontent.com/assets/6345473/7081057/44a17a20-df0a-11e4-900f-9d1de6d35db7.png)

**Comment by Wallacoloo** [comment]
Ok, that's a valid point - I change my vote ;-)

**Comment by tresf** [comment]
>  I change my vote ;-)

:)

**Comment by curlymorphic** [comment]
> The other EQ plugins have the knobs/bands enabled by default. I vote we remain consistent.

That wins me over.I will change to all on by default.

> Perhaps the solution is to make it more obvious (to newcomers) when a band is disabled.

Would it be advantageous to turn off the vu meters on disabled bands?

**Comment by Umcaruje** [comment]
>The other EQ plugins have the knobs/bands enabled by default. I vote we remain consistent.

You can't disable any band on the other EQ plugins. The buttons next to the knobs are for linking the Right and Left channel, not for enabling/disabling the bands

**Comment by Sti2nd** [comment]
Yeah, it is a difference there... ^
