### ISSUE TITLE
add hold key button to the AudioFileProcessor plugin

### ISSUE THREAD

**Issue by Reaper10** [LMMS/lmms#1379]
add hold key button so you can play all of the sample without any changing the volume no matter how long it is. this way you can use lfo,filters,cutoff all loop mode buttons and reverse button,envelopes  or anything you want so you don't need to the hold the keys donw yourself. without needing a midi clip to do it. the would be great for live keyboard players to make live soundscapes using samples.

**Comment by Reaper10** [comment]
I tried to use to the Envelope in all setting to try to play long samples and it didn't work.  So just add hold key button so you can play all of the sample without any changing the volume no matter how long it is. this way you can use lfo, filters, cutoff all loop mode buttons and reverse button, Envelope or anything you want so you don't need to the hold the keys down yourself. without needing a midi clip to do it. the would be great for live keyboard players to make live soundscapes using samples.

**Comment by Sti2nd** [comment]
> I tried to use to the Envelope in all setting to try to play long samples and it didn't work.

Why didn't you say that??? You are supposed to use SampleTrack to play long sample, but you can use AFP and make really long notes instead.
