### ISSUE TITLE
Playback Should Not Halt when 'Open Project' Dialog is Opened

### ISSUE THREAD

**Issue by csimons** [LMMS/lmms#1384]
As of latest commit (1d929d6ce7b5426b2ad3d0f56bf559d7e717f099 at the time of writing), opening the 'Open project' dialog causes playback to stop.  This does not happen when the 'Save project' or other similar dialogs are opened.

**Comment by curlymorphic** [comment]
What was the out come of this. I can find the initial pull request that was canceled, i cant seem to locate any follow up.

**Comment by csimons** [comment]
I got sidetracked with other things and then forgot about this.  I still have the patch, so I'll try to create a fresh pull request this evening to the latest branch.

**Comment by badosu** [comment]
:+1: Please do it :-).

**Comment by csimons** [comment]
The new PR ticket is #1852.
