### ISSUE TITLE
(Apple) Travis-CI Mac build support

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms#1391]
[Travis-CI](https://travis-ci.org/LMMS/lmms) generously enabled OSX build support for our software today!

**Some minor obstacles:**
 * They use [homebrew](http://brew.sh/) for building (we currently use [MacPorts](https://www.macports.org/))
 * The use [XCode 6.1](https://itunes.apple.com/us/app/xcode/id497799835) (we currently use XCode/Clang 5.1)

**Some goals:**
 * Test our [Apple build instructions](https://github.com/LMMS/lmms/wiki/Compiling-lmms-(Apple)) against homebrew
 * Add/update our wiki to support [homebrew](http://brew.sh/)
 * Enable/configure our [Travis-CI build environment](https://travis-ci.org/LMMS/lmms) to report on Apple build errors

**Some longer-term goals:**
 * Leverage the same auto-upload process we're currently use for win32/win64 for GitHub Apple dmg releases
     * Possible Issue:  We use a custom shell script for creating the Apple bundles which is fired as part of the cmake `install` process, but we should create a cmake `package` process which incorporates install and DMG steps (or switch to the built-in cmake tools for this) 
     * Possible Issue:  We a DMG script which relies on AppleScript and Finder macros which may break on a console.  Alternate DMG build process may be necessary.

**Comment by tresf** [comment]
@Lukas-W there may be some macports and homebrew support built into the travis environments already... Here's a project that appears to use them... 

https://github.com/matplotlib/mpl_mac_testing/blob/master/.travis.yml#L34

**Comment by Lukas-W** [comment]
@tresf I guess I'm one step ahead :) https://github.com/LMMS/lmms/blob/travis-osx/.travis.yml

Will take forever to compile Qt form sources every single build though…
