### ISSUE TITLE
Preset preview segfaults when clicking an .xml file

### ISSUE THREAD

**Issue by mikobuntu** [LMMS/lmms#1404]
To reproduce, goto sidebar-widget >My Home > lmms > data > lmms.xml , now left mouse click to play preview audio. The result will be a segfault ( see full backtrace here ):- http://paste.ubuntu.com/9372983/

I presume the same outcome for all .xml files. They show the " star " icon which is/should only be allowed for actual preset files, so perhaps .xml can be blacklisted for now?

**Comment by curlymorphic** [comment]
Do we currently have any validation checks on our xml, Not just plugins, the same code is used to produce the same xml, for projects files as well?

**Comment by tresf** [comment]
Well, the built-in DOM parser does have some  standard XML validation, but as you can see from the comments above,  the whole process could use some improvements.

IIRC, In this case, I believe we have well-formatted XML with non-project data, creating some null references.

To do tis proper would likely accommodate both malformed DOM handling as well as basic LMMS data structures.

**Comment by curlymorphic** [comment]
Ok, this looks like a good opportunity to brush up on my XML skills. This one might take me a while, but I am looking for something i can get my teeth into.

**Comment by tresf** [comment]
Closed via #1838.

**Comment by mikobuntu** [comment]
:+1:   good work on fixing this one @curlymorphic @tresf

**Comment by curlymorphic** [comment]
:)
