### ISSUE TITLE
Automation Track UI Recommendation

### ISSUE THREAD

**Issue by Reaper10** [LMMS/lmms#1405]
to make a butter automation track:
1 remove the mute and solo buttons and them replace with a  blinking record led button and take the record on off out of the gear menu..

automation track
![dropped_plugin_1 0 0 1](https://cloud.githubusercontent.com/assets/8137561/5308673/4259747c-7bdf-11e4-9073-804a3689378e.png)

blinking led record button 
![record-button5](https://cloud.githubusercontent.com/assets/8137561/5308674/4acd617c-7bdf-11e4-973a-84e406bdb06e.png)

2 change the default automation track name to blank automation track.
3 change the add automation track buttons to add to blank automation track button.
4 make it so you can right click all buttons, knobs or sliders and in the right click menu has a automation option then there is a sub menu you see connect to blank automation track if you have one, if you don't this option is grayed out. the edit global song automation and remove  global song automation options is also in this sub menu. the last option in this sub menu is create automation track.
5 the automation tracks and automation clips should autoname themselves. this way you can use the VSTI's knobs, sliders, buttons  for writing automation.

**Comment by Reaper10** [comment]
why is this closed

**Comment by Sti2nd** [comment]
Cause we are out of butter
