### ISSUE TITLE
Shortcut key; move to next or previous pattern in track

### ISSUE THREAD

**Issue by Sti2nd** [LMMS/lmms#1429]
Proposal: Shortcut key to move to next or previous pattern in track. 
Useful when you have to go back and edit several patterns, and useful if you don't want to go in and out from full screen. I am talking about opening the next existing pattern in the Piano Roll when you click a shortcut key. For the sake of consistency this should probably work with automation tracks too, though, I don't see it as important.

**Comment by tresf** [comment]
Closed via #1553

**Comment by tresf** [comment]
It appears this is now possible via `ALT+Left`, `ALT+Right`.
