### ISSUE TITLE
(SF2) Build warning - Invalid windowIcon

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms#1452]
I don't remember seeing this on 12.04, so I'm opening a new bug report... 

This is very minor, but wanted to open discussion as a learning point... I'd like to know more about how QT Designer files are handled in LMMS... 

Warning:

```
lmms/plugins/sf2_player/patches_dialog.ui: Warning: An invalid icon property 'windowIcon' was encountered.
```

Offending line of code is here ([`patches_dialog.ui#L41`](https://github.com/LMMS/lmms/blob/master/plugins/sf2_player/patches_dialog.ui#L41))

``` xml
<iconset/>
```

I recommend we change to this:

``` xml
<iconset>
    <normaloff>:logo.png</normaloff>:logo.png
</iconset>
```

I'm not entirely sure how to test this though as no all OSs even show the windowIcon.  In Windows, the patches dialog seems to use the SF2 icon naturally... can we suppress this build warning?

-Tres

**Comment by zonkmachine** [comment]
>I recommend we change to this:
>```xml
><iconset>
>   <normaloff>:logo.png</normaloff>:logo.png
></iconset>
>```

This works on LinuxMint 17.3 for both sf2 and GigPlayer

**Comment by jasp00** [comment]
Dialog's `windowIcon` is inherited from the instrument window, which is the logo. `windowIcon` should be removed from ui files. By the way, you can test this on Linux by setting a proper window decorator, such as "Simple".
