### ISSUE TITLE
Undo feature

### ISSUE THREAD

**Issue by rioforce** [LMMS/lmms#1463]
**Edited 2014-12-18 @tresf changed title, simplified summary** 

There needs to be an undo and redo function. I messed up my track on more than one occasion, and I was unable to undo, so I have to start over from my last save, which was very frustrating.

---

*Original post*

Hi there, your program is great, but there are a few things that are driving my crazy. First, there needs to be an undo and redo function. I messed up my track on more than one occasion, and I was unable to undo, so I have to start over from my last save, which was very frustrating. Second, you need to add a pause function so that when I hit the spacebar, it won't kick the marker all the way back to beginning of the track, it will actually stop it there so I can tweak a note and play from the place I stopped at.

Thanks.

EDIT: Sorry, please forget about the pause button, I found a very strange button that allows the cursor to go back to the position instead of the beginning. For all those who are interested, it looks like this:
![crazy pause buttons](https://cloud.githubusercontent.com/assets/3674297/5496552/400c34d2-86d6-11e4-86df-809a624545d8.png)

**Comment by tresf** [comment]
Related #1699 (needs testing).

**Comment by Wallacoloo** [comment]
Are there still any operations for which undo/redo need to be implemented?

**Comment by tresf** [comment]
@Wallacoloo I'm not sure, but here's @curlymorphic's last write-up from https://github.com/LMMS/lmms/pull/1699 that I can remember on the topic:

> From yesterdays tests, journals in there current state are good at saving changed data, not so good when adding  or deleting. for example if an instrument track is deleted, you cant simply write it's xml data back. you would have to recreate the track, load the instrument, then restore the xml, on the other hand, if a tco is moved, it is simply just a cast of restoring it's old position.

> What i have done  here is by no means a complete solution. Its the start of something that may take along time to complete.



> > Do we/should we have multiple journals (bb journal/se journal etc.
> > Similar to blender where edit mode changes are separate from object mode)

> atm the undo is done thru a global journal. Multiple journals is a possibility, but does add another layer of complexity and if we decide to go that route, a fair bit of designing. Would it be 1 for every window, what happens to linked controllers, data concurrency across journals, etc.

**Comment by tresf** [comment]
Closing per #2235, which is more specific and therefore more likely to be fixed. :+1:
