### ISSUE TITLE
Piano roll will not record from midi input

### ISSUE THREAD

**Issue by CombustibleLemonade** [LMMS/lmms#1464]
**Master branch**

My Acorn Masterkey 49 will not record any notes in the piano roll on my compiled-from-source `master branch lmms` ~~1.0.100~~ installation. The sound does play in lmms, and the GUI shows the keys being pressed. However, pressing the piano keys while recording still does make the notes record and appear in the piano roll.
I have tested it in 1.0.3 on the same machine and OS, and it still works there.

**Comment by ryukusu** [comment]
It affects me too. :'(
For 1.1 release i've found, that vmpk doesn't record notes! I even lost my played melody! 
Xubuntu 12.04.5. Tried different midi channels - still no effect. I remember, that for 0.4 there was the same bug, but only zynaddsubfx wasn't recorded notes, but now it affects all synthesizers! 
I'm very sad. There so much banks and other stuff, but I have to return to previous version. :(

**Comment by musikBear** [comment]
sorry i never saw the @me Q
I will look into this later, and report back
It went under the radar
.. HNY to all :tada:

**Comment by tresf** [comment]
@ryukusu, the original bug report turned our to be for our unstable branch.  

If you encounter this issue, please confirm you are running from the stable-1.1 branch, not master.

**Comment by ryukusu** [comment]
tresf, thank you very much!
i've downloaded lmms sources from tar.gz, not via clonegit and now everything works! :+1: :)

btw, i created my own instrument, but they are not counts as complete pack. Where should i write to submit my own pack with electronic and space ambient oriented instruments?

**Comment by Sti2nd** [comment]
> pack with electronic and space ambient oriented instruments?

Pack? Native LMMS instruments? :D

**Comment by ryukusu** [comment]
Yes. Zynaddsubfx instruments.

**Comment by Sti2nd** [comment]
Oh presets. Well we do have a lot of Zyn presets from before, but you can make a pull request so we can hear them.

**Comment by tresf** [comment]
> Where should i write to submit my own pack with electronic and space ambient oriented instruments?

Normally, send them to us, we prefer the use of a "Pull Request" via GitHub, it's a tremendously powerful way to review changes to our code or our samples/project/presets.

However, Zyn is a special use case because we don't make our own, we use the ones that are provided "upstream" by the Zyn team.  In your case, you should first recommend the pack to them, and if they are accepted, we'll get them eventually (we can merge them in advance for 1.2 if we fear delays from upstream).

On the contrary, if you have done this for non-Zyn instruments, submitting them directly to us via the "Pull Request" channel is the best option currently.

On that topic (off-topic from the OPs request) we are in dire need of Presets from some of our instruments, we would be grateful to receive anything worthy of inclusion to our software (and that goes for anyone!)

**Comment by diizy** [comment]
On 01/02/2015 06:11 PM, Tres Finocchiaro wrote:
>
> On that topic (off-topic from the OPs request) we are in dire need of
> Presets from some of our instruments, we would be grateful to receive
> anything worthy of inclusion to our software (and that goes for anyone!)
>

Frankly, I don't think we need any more presets for Zyn or Triple Osc.
We have those particular instruments well covered. If someone wants to
create presets for LMMS, they should concentrate on instruments that
have very few if any of them. Monstro, Kicker, AFP, Vibed, SID, etc...

**Comment by tresf** [comment]
> they should concentrate on instruments that have very few if any of them. Monstro, Kicker, AFP, Vibed, SID, etc...

:+1:

**Comment by oeai** [comment]
i found one more error while trying to debug

QObject::connect: Cannot queue arguments of type 'Note'
(Make sure 'Note' is registered using qRegisterMetaType().)

**Comment by Lukas-W** [comment]
I just fixed a small issue in `PianoRoll::finishRecordNode` that may be the cause of this: e63bd848d083697fc3f245b5d5d592b78d228cbe

**Comment by oeai** [comment]
getting same error qRegisterMetaType()
not recording

**Comment by Lukas-W** [comment]
@oeai Thanks for testing. Fix incoming.

**Comment by badosu** [comment]
Thanks @Lukas-W!

**Comment by oeai** [comment]
thanks! it works with Zyna!
