### ISSUE TITLE
Nescaline crash when playing very high note

### ISSUE THREAD

**Issue by Moth-Tolias** [LMMS/lmms#1492]
**edit @tref 2014-12-24, added steps to reproduce**

Steps to reproduce:
 * Open a blank project
 * Add Nescaline instrument to project
 * Open Nescaline instrument window, set "base note" to far left:<br>
  ![screen shot 2014-12-24 at 4 04 28 pm](https://cloud.githubusercontent.com/assets/6345473/5551040/8fbc6402-8b86-11e4-9fea-98f93a8ec611.png)
 * Open a new Piano Roll for same instrument
 * Click on the top most note:<br>
  ![screen shot 2014-12-24 at 4 06 18 pm](https://cloud.githubusercontent.com/assets/6345473/5551046/d58142b4-8b86-11e4-86eb-50e7414d5905.png)
 * LMMS crashes:<br>
  ![screen shot 2014-12-24 at 4 07 19 pm](https://cloud.githubusercontent.com/assets/6345473/5551051/f4e48120-8b86-11e4-8b4e-7d6641252cc7.png)

---

Found on 64-bit windows (1.1.0, latest release).
The affected presets are:

Chomp
Mega_weapon

Rather bizarrely, duplicating the preset settings did not duplicate the issue. My recreation of Mega_weapon was noticeably louder (this was the only difference I could perceive, however) than the original, so I may have been neglecting some component. I can't think what it might be, though.

EDIT: Just tested 32-bit windows (1.1.0-RC11), and the crash-inducing notes are G8 and above. Affected presets are the same as before. I'll dl 1.1.0 and check whether anything changes.

Edit 2: Just tested 32-bit windows (1.1.0, latest release). Same as before (i.e, notes equal to and greater than G8 crash the program.)

**Comment by tresf** [comment]
Closed via #1601.
