### ISSUE TITLE
@ PGib , song editor graphics.

### ISSUE THREAD

**Issue by mikobuntu** [LMMS/lmms#150]
Hi Paul, i can remember some time ago i believe you had hard coded new graphics for the "blocks" into the song_editor. they had curved corners and a gradient. I think these would look great for the next release, i cant seem to find them at the moment tho to show the other devs, and i could prob dig out my CSS manual and have a go at doing them, but it would be easier if you still had the code..

thanks Mikobuntu :)

**Comment by tresf** [comment]
Marking as duplicate of the "Cusis Theme" effort #1839 and closing to consolidate bug reports.
