### ISSUE TITLE
Wrong Slash in Windows.

### ISSUE THREAD

**Issue by crank123** [LMMS/lmms#1502]
In the Windows version the slash before the lmms dir should be \ not /. However, it's /.

**Comment by curlymorphic** [comment]
@crank123 

Where abouts do you see this? , im on linux so trying to do this blind :)

**Comment by tresf** [comment]
Here you are: :)

![image](https://cloud.githubusercontent.com/assets/6345473/5691829/cf5992f0-98a7-11e4-8858-fcff4b396d0a.png)

**Comment by tresf** [comment]
P.S. @curlymorphic some of these bug reporters don't sign back in or the email goes gets flagged as promotional/spam and they simply don't see it, or not for a while at least.

For the windows-only bugs, feel free to tag **`@Sti2nd @StakeoutPunch @Umcaruje`** or **`@SecondFlight`**.  I know I missed a few here, but you get the point. :snowman:

**Comment by tresf** [comment]
Closed per #1609

**Comment by tresf** [comment]
Unrelated, but Dave is our 7th most active committer already. 

![image](https://cloud.githubusercontent.com/assets/6345473/5709529/a31271ae-9a68-11e4-82b9-cb3d7f68bc48.png)
