### ISSUE TITLE
ZynAddSubFX windows attack!

### ISSUE THREAD

**Issue by unfa** [LMMS/lmms#1515]
http://youtu.be/FX3LY0VkS2Q

There's an issue with ZynAddSubFX windows and project rendering in LMMS.

When the rendering finishes, all previously opened ZynAddSubFX instances steal my focus. That is - they pop on my screen if they were minimized or just pushed to the bottom of the window stack. But not all at once - they do that one by one in one-second interval or so. It's really annoying, especially if you use Zyn a lot, and I use it for everything! So I try to get productive, but suddenly this happens and I need to wait until the windows stop popping, because I can't help it - they keep stealing my focus, sometimes for 30 seconds or so.

Is there a way to get rid of this? I never brought this up, because I didn't think it was a showstopper, but it's very inconvinient., and summing it up - takes up a lot of users's time for nothing - just watching windows pop up.

It only happens for Zyn instances that have these windows shown. If I hide (close) them with the "Show GUI" button, they won't be acting out after rendering finishes. It also happens on the start of rendering process.

What can be done about this?

**Comment by tresf** [comment]
@unfa I finally watched the video.  This is quite comical (sorry!).

But Amadeus offered to look into this and you never gave him instructions to reproduce.   It is also the only report of this happening.  This will be closed in a few days if no one else can reproduce it.
