### ISSUE TITLE
Noise at the end of Sample previews

### ISSUE THREAD

**Issue by badosu** [LMMS/lmms#1522]
Steps to reproduce:

1. Start a new project
2. Open the my samples section on the left
3. Open the basses folder
4. Click and hold on `bass01.ogg` until the noise gets audible.

I am filing this issue because I could not fix it myself using the instructions on the mailing list (by @diizy):

> This should be a very easy fix, simply locate the code in SamplePlayHandle where the buffer is filled, add a check to see if the sample has ended, and memset the rest of the buffer to zero in that case.

**Comment by tresf** [comment]
Closed via #1558
