### ISSUE TITLE
Bug: Watsyn shows wrong Osc

### ISSUE THREAD

**Issue by BaraMGB** [LMMS/lmms#1526]
I'm using LMMS in One-Window-Mode for Instruments. If I switch the instrument and then get back to watsyn then it shows the waveform A1 though B2 is selected.

![lmms1](https://cloud.githubusercontent.com/assets/6502580/5568270/b178b720-8f56-11e4-9fce-f224a8ed09ed.png)

**Comment by tresf** [comment]
Closed via #1599

**Comment by badosu** [comment]
Great work @curlymorphic !
