### ISSUE TITLE
More PPQN?

### ISSUE THREAD

**Issue by softrabbit** [LMMS/lmms#1530]
Right now LMMS is running 192 ticks/whole note = 48 PPQN (parts per quarter note). It might be a bit on the low side for recorded MIDI and things like that, and it looks like something like 960 PPQN is a pretty common number in other software. 

Now, what would changing this mean? Some speculation:
- Project files wouldn't be backwards compatible unless some "save for LMMS 1.1" feature is implemented. Older projects would of course be converted on load.
- Non-integer tempo could become easier to implement, still counting in integers behind the scenes (960 PPQN should get close enough to 0.01 BPM resolution)
- Swing should as well be simpler in integer ticks. 
- @diizy, any deep issues you can think of right away, or other reasons to shoot this down?

**Comment by SecondFlight** [comment]
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.

**Comment by noahb01** [comment]
IMO this should be a setting in Preferences, defaulting to 192 to preserve backwards compatibility.

**Comment by SecondFlight** [comment]
[FL Studio saves this on a per-project basis](https://www.image-line.com/support/flstudio_online_manual/html/songsettings_settings.htm), and defaults to 96 if I remember correctly. Raising this number has a fairly significant effect on performance.

**Comment by Spekular** [comment]
As a note to anyone who decides to tackle this, this line is based the current PPQN:

https://github.com/LMMS/lmms/blob/e1ef5fad0d5d8ce9b74b0c970c128cb90d695783/src/gui/editors/SongEditor.cpp#L297

A doubled PPQN value should give `max(val, -7)` instead.

<guesswork> If PPQN is configurable, this needs to be updated whenever PPQN is, and that change needs to propagate down to whoever has called the function. Otherwise the user could cause a crash by lowering the PPQN while snapping to 1/128th bars </guesswork>.

**Comment by softrabbit** [comment]
Just changing the `DefaultTicksPerTact` value in `MidiTime.h` works surprisingly well, with no glaringly obvious problems in playing or rendering, and MIDI import seems fine, too. 

This allowed me to do a little unscientific render benchmark, using a MIDI file of close to 7 minutes with 10 SF2 player tracks. I toyed around with the ticks and rendered using default settings, 3 runs each, average user time:

```
1x      53 seconds
5x      65 seconds
20x     91 seconds
```

So, there is a bit of a performance hit, but it might be acceptable?

Spots that would need further attention before this being ready for prime time are loading (and saving) of projects, and the song position display, which is way off. Probably a few other places as well.

**Comment by teknopaul** [comment]
I have an alternative to increasing PPQ that seems to resolve "a bit on the low side for recorded MIDI and things like that"

In Note.cpp add   f_cnt_t m_noteOffset;   which is a sample frames offset/delay for starting the note.

When creating a  NotePlayHandle add the note's offset.

    PlayHandle( PlayHandle::Type::NotePlayHandle, _offset + n.getNoteOffset()),

This essentially means a note's start point is sample precise, we can play a note at any position in the track not limited in any way.

Once this simple change is made setting a  note's  offset is a lot fun.

Naturally, you can record with close to this precision, CPU delay impacts the recorded offset, but if you know it, you can compensate. On my PC this seems fast enough to record piano being played with no quantizing at all.  roughly milisecond precise at 127bpm

code for recording is somethign like this

	double offsetSeconds = ((double)Engine::getSong()->getMilliseconds() - n1.pos().getTimeInMilliseconds(Engine::getSong()->getTempo())) / 1000.0;
	n1.setNoteOffset(Engine::audioEngine()->processingSampleRate() * offsetSeconds);
				

You can also nudge notes around, so you have fine grained control of start position if that helps.

You can also apply fine grained groove quantizing to make "funky"  (swing)  rhythms without having to program notes at the ppq level.

Humanizing not timings is easy when offset is there, its just adding  some random frames to the offset

This branch 
[allmystuff](https://github.com/teknopaul/lmms/tree/allmystuff)

has it working if anyone want to try it out

**Comment by teknopaul** [comment]
![quantize-screenshot](https://github.com/LMMS/lmms/assets/812666/cd0b89f9-29a4-4cca-a6a8-7d91affebf05)

You have to turn off completly quantizing for it to record offsets. Any of the existing quantizing functions will naturally set all the offsets to zero

**Comment by teknopaul** [comment]
[groove-quanitized.zip](https://github.com/LMMS/lmms/files/13492906/groove-quanitized.zip)

example of groove quantizing on and off

**Comment by DomClark** [comment]
The trouble with storing note positions as a sample offset from a tick is that samples and ticks can change in relative size. There are three main units of time we have to deal with in LMMS: ticks, samples, and seconds. Ticks and seconds are related to each other by the tempo, and samples and seconds by the sample rate. Thus ticks and samples are related both by the tempo (which can vary within a single project) and the sample rate (which can vary across machines, and even across sessions on the same machine). I think for consistency and simplicity it would be best not to mix units like this.

**Comment by teknopaul** [comment]
It works tho, and is cheap and easy and enables types of music currently not possible in Lmms. Other daws do ti's too. 
If it doesn't work with bpm changes all that needed is documentation and perhaps a validation verification. 
An alternative is to store the offset in parts of a tick é.g a float and calculate the frames offset in samples as the noteplayhandle is created. This would be a small amount of math, not free perf wise but very cheap, and would support dynamic bpm changes. Accuracy would be within a sample or two.

**Comment by teknopaul** [comment]
On production chat we have

Fijiwada!* — *Today at 12:20 AM

Any tips for making house music?


I find it a bit strange you are looking for a way to *not* implement swing, its a pretty core feature.
