### ISSUE TITLE
Add a message pane - no more error dialog spam on project loading

### ISSUE THREAD

**Issue by unfa** [LMMS/lmms#1534]
This idea was brought up years ago.

Instead of showing an error window for each missing plugin, display a closable, non-view-blocking yet obvious pane that would hold each message in one line.

Additionally, this could also display info about missing samples, or other files external to the project.

**Comment by Umcaruje** [comment]
@unfa since #1285 and #1525 were merged, can this issue be closed as fixed, or do you think there is still some room for improvement?
