### ISSUE TITLE
Clicking title bar for toggleable features in instrument views toggles them

### ISSUE THREAD

**Issue by Spekular** [LMMS/lmms#1536]
That title is pretty horrid but I can't think of a better one, feel free to suggest something. 

In the instrument view there are many toggleable features, such as the filter in the ENV/LFO tab. 
When the title bar for these is pressed they are toggled. (The user can click anywhere in this area: 
![filter](https://cloud.githubusercontent.com/assets/8918426/5588796/ef2cef12-9110-11e4-91fa-dfe667034c55.png) ). 

This could be intended bu it is inconsistent with other parts of the program where the user is required to press the led itself to toggle features, so I propose limiting the clickable area to the LED itself.

This affects every toggle of this kind AFAIK (in every instrument) for example: 
*Filter Button Under ENV/LFO
*Stacking and Arpeggio under FUNC
*Effects Chain under FX
*Enable Midi Input, Enable Midi Output, and Custom Base Velocity under MIDI
It also affects the Effects Chain toggle in Sample Track and may affect other areas.
Tested in 1.0.93 and 1.1

If we decide to change this I'm sure I could do so myself, so as to let our more capable coders work on more difficult and important issues. :yum:

**Comment by diizy** [comment]
On 12/31/2014 06:27 PM, Spekular wrote:
>
> @diizy <https://github.com/diizy> I wouldn't call it worsened. It
> makes sense that the user should press the led to toggle a feature.
>

No it doesn't. It's basic GUI design, the text beside a checkbox should
always toggle the checkbox. It's convention and standard pretty much
everywhere with well-designed GUIs.

**Comment by diizy** [comment]
On 12/31/2014 08:34 PM, Tres Finocchiaro wrote:
>
> Title: Inconsistent LED click behavior
> Expected behavior: [...]
> Actual behavior: [...]
>
> Should this be consistent for the sake of consistency? Yes, probably.
>

Yes: all LED checkboxes should react to label clicks. Someone should get
on that.
