### ISSUE TITLE
Adding sampletrack in bassline editor with 2 kickers error

### ISSUE THREAD

**Issue by oeai** [LMMS/lmms#1537]
just pressed twice .ogg file while playing kickers and got freeze

called Track::getTCO( 0 ), but TCO 0 doesn't exist
QObject: Cannot create children for a parent that is in a different thread.
(Parent is InstrumentTrack(0x7f13ecb745a0), parent's thread is QThread(0x23b3950), current thread is QThread(0x2f25450)

**Comment by badosu** [comment]
Was able to reproduce on master, you only need 1 kicker to trigger it.

**Comment by diizy** [comment]
Yeah, sampletracks in bb-editor isn't really supported functionality
yet, that's why there is no "add sampletrack" button in bb-editor.
Probably this will be fixed when sampletracks get finished.

**Comment by tresf** [comment]
I believe this to be a duplicate of #2378.  Marking as such.
