### ISSUE TITLE
Update copyright info?

### ISSUE THREAD

**Issue by Spekular** [LMMS/lmms#1539]
At the beginning of every file I've seen is some copyright info. Usually it's just
"Copyright (c) 2005-*Whenever* Tobias Doerffel <tobydox/at/users.sourceforge.net>", but the last year varies. Should these be updated to 2015 now? DummyEffect.h for example is 2006-2014 and was updated during @tobydox 's last commit to it [here](https://github.com/LMMS/lmms/commit/465aa1afbc107d7bd57769e4c68347ea28437d63).

**Comment by Umcaruje** [comment]
Yeah, that should be fixed. I can probably do another global search-replace in the texts :) Will get on it ASAP

**Comment by grejppi** [comment]
Aren't they supposed to reflect the last year when it was modified?

**Comment by Sti2nd** [comment]
^

**Comment by tresf** [comment]
IMO, the dates are mostly meaningless and almost immediately outdated.  Furthermore, these things fall more under a copyleft IMO.   I vote we keep them untouched and let the 2.0 initiative update them on those files which get drastically changed, but not on files which remain in the same basic shape as they did when they were written.

**Comment by Umcaruje** [comment]
>I vote we keep them untouched

Oh well, time to ditch my commit then. Should this be closed as a wontfix?

**Comment by tresf** [comment]
> Oh well, time to ditch my commit then. Should this be closed as a wontfix?

:confused:

**Comment by Umcaruje** [comment]
Well I made a PR after all: #1540

**Comment by tresf** [comment]
Closing as wontfix per popular vote in #1540 due to the time needed to do this and the value (or lack there of) it would add to the project.  Feel free to reopen or reference at a later time.
