### ISSUE TITLE
1.1 wrong version labels in OpenSuse 13.1 (checks of labels in general)

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#1547]
From forum i got this info: 
*LMMS_1.1.0 in OpenSuse (13.1), but LMMS still indicates version 1.0.100 in the about box and in the application title bar* 
Are other releases also labeled incorrect
I checked my win32 -That is correct 1.1.0 but is still also marked as a 'pre-release'

**Comment by tresf** [comment]
This needs to be filed upstream.  We don't maintain any linux packages currently, so we can't fix this.
