### ISSUE TITLE
Build with debug symbols

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms#1552]
We need a better way to enable Debug symbols for our developers, better explained below.

Quoted per the lmms-devel mailing list:

---

 **2015-01-04 @badosu wrote:**

> So, I am trying to track the cause of the bug that DanWin describes on his PR[0]. Tres showed me a page on the wiki on how to compile LMMS with debugging symbols [1], but it still compiles with the O2 setting.

> When I try to print some value with GDB it prints "optimized out" probably because of this.

> I tried to figure out how to make the compilation instructions the most "debug friendly" as possible but I fear my knowledge of C++ tooling is not sufficient for this.

> Could someone help me?

> 0: https://github.com/LMMS/lmms/pull/1545
> 1: https://github.com/LMMS/lmms/wiki/Compiling-lmms-%28Apple%29#debugging-lmms-osx

**2015-01-04 @Lukas-W wrote:**
> Take a look at [`CMakeLists.txt:L371`](https://github.com/LMMS/lmms/blob/master/CMakeLists.txt#L371) and L372. That's where -O2 is added. No idea why, probably best to remove -O2 and -g from both lines.

**Comment by softrabbit** [comment]
What about:
* change line 373 to: `SET(CMAKE_C_FLAGS_DEBUG "-DLMMS_DEBUG -O0 -g")`
* add similar `CMAKE_CXX_FLAGS_DEBUG` settings (`-DLMMS_DEBUG` in it seems to break the build ATM, but the rest seems OK, at least on GCC)
* inform more about how to build debug versions, as of now the `-DCMAKE_BUILD_TYPE=Debug` option is only mentioned in the Apple-specific compile instructions. Maybe a dedicated Wiki page for all things debug?

**Comment by Lukas-W** [comment]
Ooops, accidentally assigned myself...

As I wrote on the mailing list, it should be enough to remove `-O2´ and ´-g´ from lines 371 and 372. As far as I know, CMake automatically adds the `-g` option for debug builds. I don't know about what optimization flag CMake chooses for release builds though.

**Comment by tresf** [comment]
> Maybe a dedicated Wiki page for all things debug?

Or we just fix this debug flag as Lukas outlined?  We should be able to query a CMAKE variable and set these at configure time.

**Comment by softrabbit** [comment]
I'm reading the favored proposal as "disable optimization in the default build settings, but don't add debug info unless explicitly asked". What I'm aiming for is "optimize as before by default, but disable optimization if debug is selected".

(I had a look, and it seems like CMake (2.8.12.2) really doesn't add any `-O` on its own (i.e. no optimization by default if the `-O2` is dropped). And the `_DEBUG` variants of the variables involved get appended at a later point in the command line if the build type is set to `Debug`, so anything in them overrides the plain ones.)

**Comment by badosu** [comment]
@softrabbit I agree with you.

**Comment by tresf** [comment]
> disable optimization in the default build settings

I think that was only an interim solution until we've fixed CMakeLists.txt, no?

**Comment by Lukas-W** [comment]
I tested it and CMake does select `-03` for release builds, and `-g` and no optimization for debug builds. Everything fine the way I suggested it.

**Comment by softrabbit** [comment]
I'm not talking about release builds, I'm talking about the defaults you get when not selecting any build. That's how e.g. Ubuntu builds LMMS, quite a few `-O2 -g` lines in there:
https://launchpadlibrarian.net/185589092/buildlog_ubuntu-trusty-amd64.lmms_1.0.0%2Bstable-0ubuntu1_UPLOADING.txt.gz 

OK, no problem if the info gets out well in advance that the default settings will become a lot worse (very unscientific benchmark gives 3x longer runtime for a commandline render) and packagers should adjust and start doing release builds.

**Comment by badosu** [comment]
@Lukas-W If it's working we may send a PR.

Do you wanna make it?

**Comment by tresf** [comment]
I agree with @softrabbit, I feel we should expect people are building for release and optimize those defaults and have debug reverse those optimizations (If I'm reading this all correctly, feel free to tell me to shut up at any time) :)

**Comment by Lukas-W** [comment]
> quite a few -O2 -g lines in there

Of course there are, because with our current CMakeLists.txt you can't even turn them off. That's the main problem I see.

> I'm talking about the defaults you get when not selecting any build.

Then let's make release the default build type. ;)
