### ISSUE TITLE
Odd behavior when clicking and dragging out of visible range on the left side of the instrument keyboard

### ISSUE THREAD

**Issue by SecondFlight** [LMMS/lmms#1556]
When you click and drag on the keyboard for a synth and you go move your mouse beyond the visible keyboard, it doesn't act the same as when the mouse is on the visible part.

When you have your mouse lined up with the white keys and move it back and forth, it plays a chromatic scale (all notes, including black keys):
![image](https://cloud.githubusercontent.com/assets/6700184/5616965/7748c35c-94d7-11e4-9a20-d49b1bd34fb7.png)

When you move it back and forth with your mouse lined up with the black keys, it plays only the following notes:
![image](https://cloud.githubusercontent.com/assets/6700184/5617037/214d481e-94d8-11e4-8f9b-7b9757d40fab.png)

What's really strange is that this only works on the left side of the keyboard. If you try it on the right side, it behaves as you would expect.

**Comment by tresf** [comment]
I would like to see an auto-scroll feature happen in this (as well as some other) context(s).

I'll mark it as a bug for now, although tracking usability of components we can't see ranks pretty low on the priority list. :)

**Comment by tresf** [comment]
Fixed via  #4265  thanks for @PhysSong.  This will be available in 1.2.0-RC6 and higher.
