### ISSUE TITLE
Store lmmssrc outside user folder?

### ISSUE THREAD

**Issue by Sti2nd** [LMMS/lmms#1564]
Wouldn't it be better to store it inside the user folder?
![image](https://cloud.githubusercontent.com/assets/6373430/5638630/f66f4150-9609-11e4-8fc1-22f935433d18.png)

**Comment by tresf** [comment]
I don't like this because I want `lmms` to be portable, and carrying around a platform-specific config file everywhere my folder goes is bad news.

**Comment by tresf** [comment]
Actually, can you explain what single thing you feel is better about this proposal?

**Comment by Sti2nd** [comment]
> I don't like this because I want lmms to be portable, and carrying around a platform-specific config file everywhere my folder goes is bad news.

Oh, that makes sense. I should probably asked about this on the mailing list instead, I wanted to know why it is stored outside.
