### ISSUE TITLE
Travis build fails on Nescaline

### ISSUE THREAD

**Issue by Lukas-W** [LMMS/lmms#1565]
```
/home/travis/build/LMMS/lmms/plugins/nes/Nes.cpp:379:50: error: array subscript is above array bounds [-Werror=array-bounds]

m_wlen4 = wavelength( NOISE_FREQS[ ++freqN ] );
```

Surrounding code in [`Nes.cpp`](https://github.com/LMMS/lmms/blob/master/plugins/nes/Nes.cpp#L379):
```c++
371    int freqN = nearestNoiseFreq( static_cast<float>( m_samplerate ) / m_wlen4 );
372    freqN = qBound( 0, freqN + ch4Sweep, 15 );
373    m_wlen4 = wavelength( NOISE_FREQS[ freqN ] );
374 
375    if( m_wlen4 == 0 && ch4Sweep == 1 ) // a workaround for sweep getting stuck on 0 wavelength
376    {
377    while( m_wlen4 == 0 )
378    {
379        m_wlen4 = wavelength( NOISE_FREQS[ ++freqN ] );
380    }
```

`NOISE_FREQS` is an array of length 16.

**Comment by curlymorphic** [comment]
Nice to see travis catch this one.

it is possible that line 379 is accessing the 17 element;

the bound in ln 372 clamps the index to 15, the 16 element.

the ++freqN increments before using, so using the value of 16 as the index, that would be the 17th element;

i'm being nosy, what's changed for travis to pick up on this now?

**Comment by tresf** [comment]
Seems to be some code differences between master and stable-1.1, perhaps the cause?

For example, this offset seems to be missing from stable.  Perhaps @diizy hasn't synced some changes?
https://github.com/LMMS/lmms/blob/master/plugins/nes/Nes.cpp#L573

**Comment by diizy** [comment]
On 01/07/2015 04:32 AM, Tres Finocchiaro wrote:
>
> Seems to be some code differences between master and stable-1.1,
> perhaps the cause?
>
> For example, this offset seems to be missing from stable. Perhaps
> @diizy <https://github.com/diizy> hasn't synced some changes?
> https://github.com/LMMS/lmms/blob/master/plugins/nes/Nes.cpp#L573
>
> —
>

No, that's not supposed to be in stable.

**Comment by diizy** [comment]
Ok I really don't see why this is suddenly failing - there hasn't been changes in the code for a while, especially not in that part of the codebase. Have we changed some settings or compiler flags in Travis?

FYI - there's no way for the array to actually be out of bounds here (that I can see) since the pointer is incremented only when wlen == 0, and wlen can't be 0 if freqN is last because wlen depends on freqN.

Btw didn't we disable the array-bound error flag already?

**Comment by curlymorphic** [comment]
Not sure if this is related, but i just done a rebase on master, and travis passes it fine on my fork.

**Comment by badosu** [comment]
@curlymorphic Mine is up to date as well and is failing.

```
~/C/lmms ❯❯❯ gpu --rebase origin master                                                                                                ⏎
From https://github.com/LMMS/lmms
 * branch            master     -> FETCH_HEAD
Current branch master is up to date.
```

See: https://github.com/LMMS/lmms/pull/1568

Maybe it's something related to this commit? https://github.com/LMMS/lmms/commit/13357e57c43644cb82413da2d2abac3da1fe4f51

**Comment by tresf** [comment]
> Btw didn't we disable the array-bound error flag already?

Yes, but it is version specific per:
https://github.com/LMMS/lmms/blob/master/CMakeLists.txt#L366

Travis shows it only failing for Windows though, perhaps we just need to add it to [`./build_mingwXX`]( https://github.com/LMMS/lmms/blob/master/build_mingw32#L6)

-Tres

**Comment by tresf** [comment]
I would guess there is slightly different mingw32/64 behavior processing the build parameters between the old method versus the new in terms of `Release` and `Debug` flags.  So for now, I just force the `-Wno-array-bounds` on all Windows builds, which seems to get us past the array out of bounds optimizer checks.
