### ISSUE TITLE
Completely wrong sound

### ISSUE THREAD

**Issue by M374LX** [LMMS/lmms#1571]
After loading a project, the sound output is sometimes completely wrong. The tempo also seems to be higher than what is set in the song editor. When this happens, even trying to restart LMMS does not fix the problem.

Unpredictably, everything sometimes goes back to normal. In other cases, the program crashes.

May this be caused by an uninitialized variable?

The tests were done in a x64 system.

**Comment by tresf** [comment]
Yes, I've experienced this too, but it's too random and unpredictable to know the cause.  In my case, changing the sound driver and/or rebooting seems to fix it.  If we can reproduce it, we can certainly start debugging it. :confused:

**Comment by musikBear** [comment]
never seen that on win32
perhaps that is first excluder -eg this could be a x64 only ??

**Comment by tresf** [comment]
>  -eg this could be a x64 only ??

There could be 1,000 causes.  This is why bug reports shouldn't be vague.  Please reopen this when someone has steps to reproduce and feel free to mention this bug report #1571 in other that you feel may be related.

**Comment by Sti2nd** [comment]
> never seen that on win32

or Windows at all?

**Comment by M374LX** [comment]
I experinenced those problems on Linux.

**Comment by M374LX** [comment]
During playback, how and where is timing done?

**Comment by M374LX** [comment]
Inside `AudioAlsa::run()`, `snd_pcm_writei()` sometimes returns the error code -32, whose message is `Broken pipe`. This, as well as @musikBear commenting that the problem does not happen on Win32, suggests that the problem is with ALSA.
