### ISSUE TITLE
LFO speed

### ISSUE THREAD

**Issue by mqbaka02** [LMMS/lmms#1576]
in the LFO controllers it is not really handy to set the speed we aim, its just like a lack of accuracy . It will be quite good if you can fix this

**Comment by musikBear** [comment]
ambigious
*LFO controllers*
Do you mean the dial on the LFO-tab, or the actual LFO widget?

*to set the speed we aim*
What would that be, LFO can be synchronized to speed

(btw i found a method for any dial synchronization, and made a vid on it
https://www.youtube.com/watch?v=cyMroQY31NU

btw2 tech questions are better placed in forum
http://lmms.io/forum/viewforum.php?f=7

**Comment by Spekular** [comment]
@mqbaka02

>It will be quite good if you can fix this

What would you like instead? Also, this isn't really a "fix" since it's working fine, it's more a matter of personal preference.

**Comment by tresf** [comment]
> in the LFO controllers it is not really handy to set the speed we aim, its just like a lack of accuracy . It will be quite good if you can fix this

Please clarify your bug report and reopen.  This sentence doesn't help us fix bugs or add enhancements to the project.

http://www.chiark.greenend.org.uk/~sgtatham/bugs.html

https://developer.mozilla.org/en-US/docs/Mozilla/QA/Bug_writing_guidelines

http://www.softwaretestinghelp.com/how-to-write-good-bug-report/

-Tres

**Comment by tresf** [comment]
@musikBear thanks for the reference material BTW. :+1:

**Comment by LandonPowell** [comment]
I believe he's saying the knobs rotate too quickly. They're much too sensitive when using the mouse. About three pixels of mouse-movement would jerk the knob from one extreme to the other. Personally, I've resorted to double-clicking on the knobs and typing in an exact amount.

**Comment by tresf** [comment]
> I believe he's saying the knobs rotate too quickly. They're much too sensitive when using the mouse.

I have this same problem when recording automations myself, the wheel is not accurate enough... Although automation recording is a relatively new feature, so I wouldn't have has such a problem previously. 

I think we need a modifier key on the keyboard which allows finer knob adjustments, or a pop-up widget slider that can be used to fine-tune these things...

**Comment by Sti2nd** [comment]
I think that is a great idea. When connected to an automation track and recording the knob could go through two decimals for example, and else only one or none. Ideally both cases could be user definable. I am for example really annoyed about having to use a lot more time to set volume to 50.0/51.0 percent than before when dragging, because of the decimals.

**Comment by klopsi** [comment]
you can double click the SPD dial and enter an exact value, whatever value you want.

However the LFO drifts out of sync with the track. I have opened a new issue for this.
