### ISSUE TITLE
Replace art without source with remade versions

### ISSUE THREAD

**Issue by Spekular** [LMMS/lmms#1577]
The LMMS/Artwork directory is missing sources for a lot of icons, perhaps these could be replaced with remade versions so that we can have a source for them? I've tried recreating the "add_track" icons as an example (The plus is a lot sharper but I can "fix" that if necessary):
![icon grid](https://cloud.githubusercontent.com/assets/8918426/5662165/f1071a6c-9735-11e4-8200-30c5b108cb05.png)

**Comment by tresf** [comment]
Very nice work!  Wrong project tho, we have LMMS/Artwork for these bug reports.  Please coordinate this with @diizy as he made the majority of the artwork.

Please reopen this on the right project repository! :+1: :+1: :+1:

**Comment by Spekular** [comment]
@tresf well it applies here too, since it would require the icons to be
updated. I was also thinking the people here would want to review the
icons. I'll open it in /artwork instead I guess.

**Comment by Lukas-W** [comment]
Actually, the SVG source files are already in the artwork repository.
We could however have Qt load the SVGs instead of the rendered PNG files, that'd make icons scale better.

**Comment by tresf** [comment]
> @tresf well it applies here too, since it would require the icons to be updated.

Well, yes, every bug report really applies to LMMS/lmms because that's our main project.  Everything we do revolves around the desktop software, but your request is 99.9% about our Artwork repository and 1% about the software.

> I was also thinking the people here would want to review the icons. I'll open it in /artwork instead I guess.

That's a valid point, but since Vesa made all of these, you should be able to tag him and anyone else you feel needs notification in the other Repo.  I guess this isn't the WRONG place, but the other place is better. :)

Lukas says the SVGs are already there tho, so perhaps you just missed them?

**Comment by Spekular** [comment]
@Lukas-W mind linking me to these three? I can't find them in src (where they should be) and I even checked rendered. Searching doesn't show them either...

**Comment by Lukas-W** [comment]
They are in those files: 
icons1.svg, icons2b.svg, icons3.svg, icons3b.svg, icons4.svg, icons22.svg

Each of those files contains several layers with different icons. For instance `icons2b.svg` contains the BB icon.

**Comment by Spekular** [comment]
@Lukas-w ok. I was just checking to see if any files in
lmms/data/themes/default were missing identically named svg equivalents in
lmms/artwork/src, so I missed that. Any reason they're stored that way?
Wouldn't separat files make more sense and allow for svg diff checking if
they were to get updated/pull requests made?

**Comment by tresf** [comment]
> Wouldn't separat files make more sense and allow for svg diff checking if they were to get updated/pull requests made?

Perhaps, depends on how Vesa originally created and edited them.  We could probably put text files in their place if its not obvious.  There's also a chance he planned to make similar buttons all a single pixmap down the road, which is very common for theme engines.

**Comment by diizy** [comment]
On 01/08/2015 01:58 PM, Spekular wrote:
>
> The LMMS/Artwork directory is missing sources for a lot of icons,
>

No it's not. All the icons you claimed missing are included. They're in
some of the "iconsxx.svg" files.

**Comment by diizy** [comment]
On 01/08/2015 05:18 PM, Lukas W wrote:
>
> Actually, the SVG source files are already in the artwork repository.
> We could however have Qt load the SVGs instead of the rendered PNG
> files, that'd make icons scale better.
>

Yeah, we already have the ability to use SVGs in LMMS, just it hasn't
been really utilized yet. It probably won't matter with most of the
icons (I've scaled/rendered them in a way that makes the bitmaps not
need to be scaled when used) but could be useful in some things, like
the BB-editor steps.

**Comment by diizy** [comment]
On 01/08/2015 05:55 PM, Tres Finocchiaro wrote:
>
>     Wouldn't separat files make more sense and allow for svg diff
>     checking if they were to get updated/pull requests made?
>
> Perhaps, depends on how Vesa originally created and edited them. We
> could probably put text files in their place if its not obvious.
> There's also a chance he planned to make similar buttons all a single
> pixmap down the road, which is very common for theme engines.
>

I was just lazy and uploaded the original SVGs to the repo as-is...

**Comment by tresf** [comment]
So @Spekular if you wish to rename them or put some note about them, feel free. :+1:
