### ISSUE TITLE
Dynamics processor causes waveshaping, even with the highest possible attack and decay values

### ISSUE THREAD

**Issue by SecondFlight** [LMMS/lmms#1581]
I could be wrong about how the dynamics processor is supposed to work, but as I understand, it should work like a compressor with a custom curve. If you have experience with compressors, you probably know that a compressor will start doing strange things if the attack (or decay) is set to a value that is too short. If you have an attack that is too short, the compressor will change the shape of the wave because it is changing the volume so fast. Here's an example of a sine wave (roughly 50 hz) that has been run through C\* Compress with the attack and decay set to 1.2 ms:

![image](https://cloud.githubusercontent.com/assets/6700184/5671586/18d4904e-9757-11e4-99e7-56007bfb3396.png)

And here it is without:

![image](https://cloud.githubusercontent.com/assets/6700184/5671923/e491fb8e-9759-11e4-9ec4-625d979e6eec.png)

Even with the low attack, there is still interpolation of some sort to keep the edges smooth.

The dynamics processor is doing something with roughly the same effect. Here are the settings I'm using to test this:

![image](https://cloud.githubusercontent.com/assets/6700184/5671823/053bea26-9759-11e4-9709-57775bf7a0b1.png)

And here is the waveform it generates, along with the harmonics (each line represents a sine wave at that frequency - the original input was a single sine wave):

![image](https://cloud.githubusercontent.com/assets/6700184/5671866/6eda7a6a-9759-11e4-8963-5c2fa6e61ccc.png)

![image](https://cloud.githubusercontent.com/assets/6700184/5671904/b41529fe-9759-11e4-9acd-d8d3a51fa417.png)

Am I wrong about how it's supposed to work, or is this a flaw in the algorithm?

**Comment by diizy** [comment]
On 01/09/2015 12:14 AM, SecondFlight wrote:
>
> Am I wrong about how it's supposed to work, or is this a flaw in the
> algorithm?
>

Flaw, just one of many in the DP design. Others including the linear
scale of the wavegraph (but that requires compat-break to fix so must be
done in 2.0).

This particular problem however is caused by the envelope-following
code... I sort of know how to get it right, I just haven't had the time
to fix it properly.

**Comment by SecondFlight** [comment]
Ah, okay. I guess I won't use them in this project then. I'm trying to do multiband compression with dynamics processors, and they really mess up the sound. :3

**Comment by SecondFlight** [comment]
It does seem to work alright for straight lines though.

**Comment by SecondFlight** [comment]
This is something that could reasonably be solved with a (hopefully) small modification to the waveshaper plugin I'm working on. Once that plugin is done, I may be able to duplicate it and add attack and release to make a really nice compressor.

Or, like everything else in software engineering, it might be harder than it seems.

/shrug
