### ISSUE TITLE
Crash when moving mixer channels to left/right

### ISSUE THREAD

**Issue by badosu** [LMMS/lmms#1584]
Sometimes you are able to cause a Segmentation Fault when using the "Move Right"/"Move Left" functionality on mixer channels.

I was not able to identify how to reproduce this error deterministically, but you should be able to trigger this just moving nearby channels at the rightmost part of the mixer.

The backtrace shows that this is the offending line: https://github.com/LMMS/lmms/blob/40438689922e843fcf07d22dd52378cb7e5237d5/src/gui/widgets/FxLine.cpp#L208

Full backtrace here: https://gist.github.com/badosu/54bf4c6cd2d504daaab0

**Comment by tresf** [comment]
#1545

**Comment by badosu** [comment]
@tresf I don't know if this is exactly the same bug. But may be

**Comment by tresf** [comment]
> @tresf I don't know if this is exactly the same bug. But may be related.

Yeah, I just wanted to link them in case they are.  I should have put a contextual message with that tag. :rooster:

**Comment by Lukas-W** [comment]
Same issue as #872
