### ISSUE TITLE
Update On The New Sample Library Project

### ISSUE THREAD

**Issue by HDDigitizerMusic** [LMMS/lmms#1589]
Hello All,

Popular artists, Markus Hakala, Subaqueous and Deficio have recently replied in email. They have confirmed that the samples they are letting LMMS use in its upcoming sample library are 100% free. They will let anyone use the samples in the library as long as we give them credit in the program's about area. I asked the artists if we could put the samples under CC0, and I linked to the licensing information in my email to them. They fully understand what will be happening with the samples.

I just wanted to clear some things up.
The free samples I collected from online sources was a task other users and myself took on. These samples with the exception of Deficio's samples are already free for anyone to use without giving any credit to the owners. 
For Deficio, if you were to use his samples outside of LMMS, you would have to credit him for each of your works.

The only reason, I contacted each of the artists, was to get their permission to put their samples specifically in LMMS’s sample library, something that was not specified yet in their licensing. Due to some misunderstandings about this, all collaboration was stopped in the Sample repository here on Git Hub.

The Good News
Now that we have the final confirmation in writing, we can pick up right where we left off. Here are the samples they are letting us use: https://soundcloud.com/markushakala/sets/kicks-2 http://subaqueousmusic.com/category/production-articles/c26-free-music-tools/ and http://www18.zippyshare.com/v/5464113/file.html

I placed a selection their samples in the Samples repo just to jump start the creation of the new LMMS sample library. 

I have told all three respective artists that their samples will be under review.

As of now, we have a repository for contributors to collaborate on LMMS’s sample library or sample packs and the collected sample's licensing is confirmed. Once we find out a method and criteria for accepting samples, anyone will be able to head over to the LMMS Sample repo and start adding their samples. Since I have finished a long lasting project, and now have Native Instruments Massive, I plan on contributing samples for consideration myself.

With this roadblock now in the past, I think we should get started. Thanks to everyone that has helped LMMS get this far.

**Comment by Spekular** [comment]
Excellent news!

**Comment by Sti2nd** [comment]
And provide proof please. I don't see why these answers cannot be public :)

**Comment by grejppi** [comment]
Good to see you back. They have been waiting for you.

* https://github.com/LMMS/Samples/issues/10
* https://github.com/LMMS/Samples/issues/15

**Comment by Umcaruje** [comment]
Some Bad news for you though:

Due to your inactivity, your push access to the repo was revoked. If you have a valuable explanation on why you avoided any kind of communication for 5 months, I'd vote you perhaps get it back (Not sure what are @StakeoutPunch's and @Sti2nd's thoughts on this). 

Also please provide proof that these emails exist, its not that I don't trust you, but I really don't.

**Comment by tresf** [comment]
Welcome back.  Looking forward to regaining the momentum we had before.

**Comment by StakeoutPunch** [comment]
I second @Umcaruje. I'm awaiting both the messages you sent and received, verbatim, before I form an opinion.

As @Sti2nd said, we will need to cut these packs down to size. Reviewing and selecting the samples should be carried out by two people for ease of communication (6 people at once is a mess, even with a G doc), with peer review afterwards.

**Comment by HDDigitizerMusic** [comment]
Hello all,

Here was my message to the producers:

Hello,

I just wanted to confirm that the samples you have let us put in the library and or sample packs will be CC0. (https://creativecommons.org/publicdomain/zero/1.0/) If you could reply with your confirmation of this, that would be great.

The samples that you have kindly contributed to LMMS will be under review by the developers so they may or may not make it into the final library.

Once approved, we will gladly give you credit (your name and or email) to show the great work you have done.

Thank you for your contribution to the LMMS community.

Digitizer out.


Here are their confirmations:
https://drive.google.com/file/d/0B3YpcUuL5rOCRnpBV2owSWczN1U/view?usp=sharing


To Markus Hakala's confirmation, I replied:
Hey Markus,

That's exactly what we needed. Thank you. :)

**Comment by tresf** [comment]
So we are still promising accreditation for CC0 samples.  This was our original problem.  Do you see the problem with this?  We want to make sure no one is being misled and when you go off on your own drafting these emails, it silos your efforts, don't you think?

We want this to work out... But we also want to be clear about our intentions. :confused:

**Comment by sgtGarcia** [comment]
@tresf I think accreditation will be only within LMMS scope, not in produced music, so it is not a bad situation. Or do You think it will be still a problem?

**Comment by Sti2nd** [comment]
> So we are still promising accreditation for CC0 samples. This was our original problem.

Actually, HDD has somehow come up with accreditation, but neither we nor the artists we are contacting have claimed they need it.. That is so strange, but I can agree on having them credited in the about section.

@HDDigitizerMusic It would be so much better if you simply had them respond, "yes I agree that my samples is CC0" -_- The only one I am unsure about now, though, is Markus Hakkala

Nevermind, this site says they are royalty free http://howtomakeelectronicmusic.com/markus-hakalas-kicks-all-in-one-500-free-kicks-in-total

OK, then we got our kickdrums, and sweepers/uplifters/whatevs (if we want that).

**Comment by Sti2nd** [comment]
> I think accreditation will be only within LMMS scope

Yes of course, the samples are now CC0, no accreditation is demanded whatsoever.

**Comment by tresf** [comment]
> @tresf I think accreditation will be only within LMMS scope, not in produced music, so it is not a bad situation. Or do You think it will be still a problem?


It is less of a matter of if we can (permissive, courtesy) and more of a matter if we have to (legal, obligatory).  CC0 means we don't legaly have to.  This conflicts with the obligatory promise.  We can make no such promise, we can only offer accreditation as a courtesy.

**Comment by StakeoutPunch** [comment]
If I recall correctly, this was the exact reason this project slowed to a crawl last time. We are aware that the artists responded positively - we have known that for months. However, unless you (@HDDigitizerMusic) are saying that you sent additional emails that clarified what exactly CC0 meant to the artist, and that it could potentially mean NO accreditation later on down the road, then you are just repeating old news, unfortunately.

While I am playing bad cop, why did you disappear with no response for so long?

**Comment by HDDigitizerMusic** [comment]
The samples are CC0 for LMMS users, who will be able to do whatever they want with them and not be legally bound to give credit. However, since there is an existing practice in LMMS of providing credit in the ‘Authors Area’ to contributors it is a matter of providing credit where credit is due. Providing credit could potentially open the doors to a whole new group of people who have not used LMMS who respect the popular artists that have contributed their samples. I don’t see how providing credit is an issue to begin with, especially when you consider the precedence which was established well before my time contributing to LMMS and it could help promote LMMS to a whole new group of artists. 

>I think accreditation will be only within LMMS scope, not in produced music, so it is not a bad situation.
Exactly.

>While I am playing bad cop, why did you disappear with no response for so long
In all honesty, I am not sure where you are coming from in general with your assumption of having the authoritative power over my time to be able to police my time in any fashion. May I remind you, I am a volunteer, not a paid employee. I choose when to volunteer my time and contribute when I am able. That being said I will attempt to humor you. ;) I’m a full-time student, when not doing schoolwork I intern at my families marketing agency. I received the go ahead to contribute to LMMS for a portion of my overall intern tasks last year. All of the other time I contributed was done so on my free time during breaks throughout the day. I am, in general, a very busy person. When all of the drama started to be injected into this process, it caused the time I was allotted in my internship to run over. I chose to contribute to LMMS because I use it as my primary music production and because I like to help other producers.

While this has definitely been an amazing learning experience for me. :D I am not going to be actively contributing to LMMS anytime soon. That means since I have finished what I originally committed to contributing on this community project. I will no longer be following any of these threads for the time being. I will still lurk from time to time and if I may get the inclination to contribute in the future. I wish everyone the best of luck with this project. :)

**Comment by Sti2nd** [comment]
Thank you, keep up __making__ music :) We'll be right here if you need us, and hopefully the samples will get along too eventually.

**Comment by tresf** [comment]
> That means since I have finished what I originally committed to contributing on this community project. I will no longer be following any of these threads for the time being.

I think that is the problem here....  Your first post on this tracker had your album art plastered with some anped up ambitions of re-theming our software and coordinating with an artist yet.  A year later we wait three weeks for updates to much smaller ambitions and overall dismissal of involvement.

> providing credit where credit is due

Have you read nothing that has been posted?  CC0 waves these rights.  Should != Must.

You have sent emails on behalf of the project as an individual and you've done so multiple times with no checks or balances in terms of quality and without any other project members involvement as to the wording.

Now you have the nerve to say "take it or leave it".  I don't like your attitude.   These people posting here have only the best interests for the project and community in mind.  I'm not sensing that from you.

**Comment by HDDigitizerMusic** [comment]
I have always had only the best intentions for all of my attempts to contribute to LMMS. In any collaborative project, it has been my experience that mistakes are made, and toes inadvertently get stepped on, this experience has just reinforced this for me. I apologize for any mistakes or missteps I might have made and truly wish you all the best. It is unfortunate that you and others have clearly misunderstood, misquoted and taken my many attempts to provide a positive contribution out of context. The records reflect that every failed attempt to clarify and clearly communicate my ideas thoughts and good intentions were done so with the utmost respect and courtesy.

That being said, I want to thank all of those who created and maintained LMMS. It is an amazing digital audio workstation. closed #1589

**Comment by badosu** [comment]
@HDDigitizerMusic 

It's hard to collaborate with people on projects even when you're paid to do it. On Free Software this issue is much more apparent since we are always remote, with different backgrounds and intentions and trying to put our stuff to improve the software.

That requires a lot of effort, and frustration is really commonplace with a lot of people.

**Comment by tresf** [comment]
> I apologize for any mistakes or missteps I might have made and truly wish you all the best. It is unfortunate that you and others have clearly misunderstood, misquoted and taken my many attempts to provide a positive contribution out of context. 

Well, I think we took them directly in-context.  Perhaps we misquoted a few times, but we have the emotionless internet and our own word between us.  Here's some examples where the team tried to add emotion:

> **@tresf wrote** Welcome back!

> **@Specular wrote** Excellent news!

> **@grejppi wrote** Good to see you back. They have been waiting for you.

I hope this shows our welcoming feeling on this topic.

> The records reflect that every failed attempt to clarify and clearly communicate my ideas thoughts and good intentions were done so with the utmost respect and courtesy.

Well, I think your humble apology starts to clarify this, but it seems to be adding compromise, lessons learned and resolve at a time which you are leaving.

> I want to thank all of those who created and maintained LMMS. It is an amazing digital audio workstation.  closed #1589

And we would like to offer the same thanks once we push over this hill.  I'm quite saddened for the project as a whole that you're leaving.  This is something you had originally decided to take a lead on and now with your absence it is in a state of disrepair.  If you decide to see it through please feel free to chime in.  Otherwise, we'll likely have renaming members jump on this task sometime down the road once some energy and availability around it resurfaces.

**Comment by Umcaruje** [comment]
@tresf Are we gonna take the samples as they are now (CC0 with promised credit in the about dialog) or I should go an wipe them all out from the samples repo? Since @HDDigitizerMusic appearently left and won't be comming back, I believe I can't see a third solution to this problem. This brings me to the second thing I wanted to say.
______


If anyone here is willing to put some time in the samples library that'd be awesome. (This is a great way for non-coders to help out) We are really short on people, since Evan and HDD left, so any help is appreciated. I wouldn't want the new samples library effort to completely vanish :)

**Comment by tresf** [comment]
> @tresf Are we gonna take the samples as they are now (CC0 with promised credit in the about dialog)

I think each sample pack contribution needs to be evaluated.  I haven't done this, but IIRC, Stian said some of these were already CC0 before we even asked the authors.

> or I should go an wipe them all out from the samples repo?

I trust your judgement on these.  It's just a lot of quality control and crossing T's and dotting I's (so to speak).  Whoever is up for that task, great.  If unsure please feel free to reach out to the authors on behalf of the project. :+1:

**Comment by HDDigitizerMusic** [comment]
I know I said I was not going to respond. However, your comment deserves a response.

>And we would like to offer the same thanks once we push over this hill. 

Please, do not take this the wrong way but I did not do any of this to receive thanks, I did it in an attempt to demonstrate my appreciation for LMMS with action rather than just words. 

>I'm quite saddened for the project as a whole that you're leaving. 

I was quite saddened, shocked and disappointed at the treatment I received from a few in this community that prompted my decision to leave. I have included screenshots that demonstrate the treatment I received while continuing to move forward the best I could.

>This is something you had originally decided to take a lead on and now with your absence it is in a state of disrepair.
 
This is one of the key misunderstandings that has misunderstood over and over. I never decided to take the lead or even claimed to. This all started with a forum post unfa started, and I joined in with the rest of the team they had collected to help out. The state of disrepair is a result of a few in the LMMS community who inject ridiculous infighting, bikeshedding, and childish name calling.

![lmmschat2](https://cloud.githubusercontent.com/assets/6778944/6242588/2cd41524-b6e7-11e4-95c1-12a1a1005483.png)

![lmmschatstian](https://cloud.githubusercontent.com/assets/6778944/6242590/31ad6d34-b6e7-11e4-8b44-6060c469ed91.png)

![forumpoststakeoutpunch](https://cloud.githubusercontent.com/assets/6778944/6242593/379dea48-b6e7-11e4-946e-3b80cbb63ba1.png)

![lmmschat](https://cloud.githubusercontent.com/assets/6778944/6242600/4f7c7724-b6e7-11e4-915f-cb4a244555d3.png)

>If you decide to see it through, please feel free to chime in. Otherwise, we'll likely have remaining members jump on this task sometime down the road once some energy and availability around it resurfaces.

I’ve completed everything I committed to which is the very essence of "seeing it through". Previously you mentioned your displeasure in my "take it or leave it" attitude. Yet, this is one of the underlying foundational elements of open source development, to imply otherwise is to infer that I had entered into a state of employment with LMMS which I have not.

In spite of all the negativity, there were quite a few people in this community that I am glad to have worked with. My leaving really boils down to me having to pick and choose my battles, as I am a very busy person, by my own choice. That aside, I wish you all the best luck on this project. All said and done, I don’t have any bitter feelings, I just prefer not to collaborate with people who are... that negative. The only reason I endured this ill treatment is because, I follow through with what I start. :)

**Comment by Umcaruje** [comment]
Well, after re-reading this thread yet another time,

I just personally want to apologize to @HDDigitizerMusic for my insults on hangouts. I was younger back then, and it was unprofessional and childish of me. The reaction came as a result of my frustration with the state of the samples project, but that's when one needs to be at his calmest, and not start ad hominem attacks.

Now, I know this might look like beating over a dead horse, but after seeing the new theme project that @HDDigitizerMusic initially started with @RebeccaDeField on the tracker successfully near completion (some minor changes left), I just needed to say that his contributions to the project were valuable, no matter how the relationship ended, and if he ever chooses to come back to the project, I think we all would be very open to it. 

From a freezing cold Belgrade, 
but with a warm heart
- Uroš | Umcaruje

**Comment by musikBear** [comment]
It is back once more:
http://lmms.io/forum/viewtopic.php?f=17&t=8380&p=26950#p26950
Look, this issue is not going away on its own. A descission need to be taken
Imo, omit *everything* that isent 100% crystal clear c0, and do it already for 1.2.0
The issue is 'not' what users make, but the project it self
Delete this if needed, but **DO** something
Ship with hydrogen only if so needed, but *DO* something! @tresf

**Comment by tresf** [comment]
Most of our samples have been around for 9 years so getting CC0 permission is impossible at this point.

> This issue is not going away on its own.  [...] DO something! @tresf

I'm not sure why you're tagging me in this.  The samples repository is a work-in progress.  It's intended to replace what we have today with CC0 cleared samples.  This is a huge undertaking and non-coders like yourself and others can really step in and help.  @SirBothersome has already put a considerable amount of time into the samples repo and @Umcaruje has reached back out to some artists to explain CC0 and make sure they agree without false pretence.

**Comment by jasp00** [comment]
As stated at SourceForge, from [AUTHORS](https://github.com/LMMS/lmms/blob/master/doc/AUTHORS#L41):
```
Sebastian Tilsch
	<djcompilation/at/gmx/dot/de>
	Recording of many samples
```
Did anyone ask him?

**Comment by SirBothersome** [comment]
@jasp00 I don't recall, I believe the email listed is inactive, but I don't
remember. At any rate, if he recorded the samples then we technically own
the rights to them. If they came from a ssmpler/beat machine... that's a
grey area. as for new samples, if anyone, especially @Umcaruje or
@musikbear wants to look at #29 <https://github.com/LMMS/samples/pull/29>
or #30 <https://github.com/LMMS/samples/pull/30> and give me some feedback
I'd appreciate it
