### ISSUE TITLE
Instrument track activity LED lights when muted

### ISSUE THREAD

**Issue by Sti2nd** [LMMS/lmms#1595]
Shouldn't the LED stay off, and more important, does this means LMMS is actually processing muted tracks?
![image](https://cloud.githubusercontent.com/assets/6373430/5695246/d073ffe0-9997-11e4-80a1-ee3e1b498a24.png)

LMMS 1.1.0

**Comment by Spekular** [comment]
I think the led should still flash but in a different color, like light
blue? Disabling processing of muted tracks could perhaps be a checkbox
under the performace options (I like seeing the muted tracks' leds flashing)

**Comment by Sti2nd** [comment]
> I think the led should still flash but in a different color, like light
blue?

Why? And that implies still processing each note...?

**Comment by tresf** [comment]
Probably a valid request.  Interested to see some more opinions....

**Comment by diizy** [comment]
On 01/11/2015 02:47 PM, Stian Jørgensrud wrote:
>
> Shouldn't the LED stay off, and more important, does this means LMMS
> is actually processing muted tracks?
>

Yes muted tracks are processed, their FX chains are not though.

**Comment by tresf** [comment]
IIRC, what we do now with muted patterns is visually remove the color saturation from them (grayscale-ish).  Would it be reasonable to change the fading LED color when muted?

**Comment by curlymorphic** [comment]
> Would it be reasonable to change the fading LED color when muted?

Technically yes, aslong as it's one of the predefined colors red, yellow, green.

**Comment by diizy** [comment]
On 01/14/2015 08:25 PM, Dave wrote:
>
>     Would it be reasonable to change the fading LED color when muted?
>
> Technically yes, aslong as it's one of the predefined colors red,
> yellow, green.
>

No, it doesn't need to be predefined. It would need a new qproperty that
can be defined in CSS so that the colour can be defined in the theme, as
the fadebutton's colour currently already is (IIRC).

**Comment by Sti2nd** [comment]
> Yes muted tracks are processed, their FX chains are not though.

So I guess there is no reason for it, do you use that functionality for something @Spekular? I have been thinking about how one could reduce rendering time of a project, and not processing muted tracks could be added to that list.

**Comment by Spekular** [comment]
@Sti2nd well yes. The indicator serves the same purpose as it normally
does, it alerts me when sound plays. In fact it might be even more useful
with muted tracks because you can't hear the sound. I'm still all for
allowing leds to be disabled on muted tracks (or maybe having that be
default), but I'd like the ability to still show leds kept. Either way they
should blink a different color when they do blink. Perhaps I could do this
myself, or perhaps I'm too busy (I'm sure I have plenty of obligations and
things to do, but I can't think of them now).

**Comment by Sti2nd** [comment]
> The indicator serves the same purpose as it normally
does, it alerts me when sound plays. In fact it might be even more useful
with muted tracks because you can't hear the sound.

I don't understand this logic? Maybe now when they are actually are processed it is useful to see where the resources go, like into a muted Zyn track. When a track is muted I would say it isn't played (when a track is played and not muted it makes sound, at least from a user perspective), and then it could might as well not be processed, and then it should of course blink no indicators.

**Comment by tresf** [comment]
Closed via #1710
