### ISSUE TITLE
CMake doesn't generate lmms manual page

### ISSUE THREAD

**Issue by teeberg** [LMMS/lmms#1603]
I pulled the latest cmake refactoring and tried to compile with the new code. I however get the following during a make install:

    -- Installing: /home/jonas/code/lmms/build/bin/lmms
    CMake Error at src/cmake_install.cmake:60 (FILE):
      file INSTALL cannot find "/home/jonas/code/lmms/build/lmms.1.gz".
    Call Stack (most recent call first):
      cmake_install.cmake:255 (INCLUDE)

I also don't see "Generating lmms.1.gz" in the log.
Simply gzipping `./lmms.1` to `build/lmms.1.gz` fixes the error in following runs.

**Comment by Lukas-W** [comment]
Closed via #1604
