### ISSUE TITLE
Detune mode broken

### ISSUE THREAD

**Issue by teeberg** [LMMS/lmms#1605]
Commit 02006f98557526add0dc8f555b9b7cd68ab2fb41 broke the "Detune mode" in the piano roll. You can open the dialog, but it's empty.

**Comment by Lukas-W** [comment]
Oh, I thought I'd tested that.

**Comment by Lukas-W** [comment]
Nope, works for me. Or are you describing something different?

![untitled](https://cloud.githubusercontent.com/assets/2879917/5701271/09b1e16c-9a49-11e4-8b1d-6492f04ac07a.png)

**Comment by Lukas-W** [comment]
Please check if commit 58507c28ecc73469ec37c073c6321124a99a2f85 fixes the issue for you.

**Comment by teeberg** [comment]
Commit 58507c2 dit not fix it, but a94ccb851592e12f3f8f9cc355159388bb5e3c0b did. :-) Either way, it's fixed now, thanks very much!
