### ISSUE TITLE
(P)roject menu vs (F)ile menu

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms#1608]
This is a minor thing, but does anyone feel the word "File" would be more consistent with a standard menu in the main menu instead of the word "Project"?

![image](https://cloud.githubusercontent.com/assets/6345473/5705796/dea283fe-9a49-11e4-857b-d281da5f226b.png)

Most Linux software I use registers the first item as "File" (Gimp, Audacity, QT Linguist, VirtualBox, KeePass, etc).  Even Chrome invokes the main menu when `ALT+F` is pressed.

The one piece of software I use daily that is an exception to this is Pidgin, which uses `Buddies` instead, but is rarely used to actually open or save anything, making it fairly reasonable menu name for Pidgin, IMO.

**Comment by M374LX** [comment]
One more detail is that most software have the "Sabe As..." option right after "Save".

**Comment by Lukas-W** [comment]
> most software have the "Sabe As..." option right after "Save".

Because most software doesn't have such a cool "Save as new version" feature :smirk:

**Comment by Sti2nd** [comment]
I don't mind changing it.

**Comment by tresf** [comment]
> One more detail is that most software have the "Sabe As..." option right after "Save".

Yeah we could probably rearrange those. :)

**Comment by Spekular** [comment]
Save as should definitely come before Save as new version imo.

**Comment by Lukas-W** [comment]
> This is a minor thing

What do you think of introducing GitHub labels like `severity:minor` `serverity:major`?

**Comment by tresf** [comment]
> labels like severity:minor severity:major? 

Enhancements are generally all minor whereas bugs are split about 50/50.  I think prioritization is important, but I'm not sure if a severity tag is the way to do it... 

We may consider doing this with milestones too... *shrug*
