### ISSUE TITLE
Crash when rendering project via CLI

### ISSUE THREAD

**Issue by badosu** [LMMS/lmms#1614]
This was probably introduced on the recent application/gui refactorings.

I was rebasing https://github.com/LMMS/lmms/pull/1525 when I noticed that exporting was not working anymore, it looks like some kind of gui check was removed on the recent changes.

Backtrace:

```
#0  0x000000000053a48e in GuiApplication::getBBEditor (this=0x0) at /home/badosu/Code/lmms/include/GuiApplication.h:50
#1  0x000000000053728c in Song::clearProject (this=0xeb3530) at /home/badosu/Code/lmms/src/core/Song.cpp:761
#2  0x0000000000537a11 in Song::loadProject (this=0xeb3530, _file_name=...) at /home/badosu/Code/lmms/src/core/Song.cpp:933
#3  0x0000000000511c2f in main (argc=3, argv=0x7fffffffdad8) at /home/badosu/Code/lmms/src/core/main.cpp:496
```

**Comment by tresf** [comment]
Thanks.  IIRC @Lukas-W is still doing some re-factoring so this doesn't come as a surprise.  I'll leave this open as a WIP.

Lukas is starting some testing libraries which are really depending on CLI, so this stuff should get sorted out soon enough.  Feel free to debug if you wish, but don't kill yourself on it.

-Tres

**Comment by badosu** [comment]
@tresf Thanks for the input, I'll wait until this gets sorted out.
