### ISSUE TITLE
Menu separators are not visible

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms#1615]
In our style sheet, `QMenu::separator` shares the same color as the `QMenu` class.  

I tried tweaking it to make it visible... Here's what `background: #8d8d8d;` looks like... (not sure if all platforms display this correctly tho).

https://github.com/LMMS/lmms/blob/master/data/themes/default/style.css#L71

Since @diizy made this theme, I'll give him a chance to chime in before making any changes. :smirk: 

![image](https://cloud.githubusercontent.com/assets/6345473/5715379/eda12174-9aa5-11e4-9f0f-a5690f24de1d.png)

**Comment by diizy** [comment]
On 01/13/2015 04:57 AM, Tres Finocchiaro wrote:
>
> In our style sheet, |QMenu::separator| shares the same color as the
> |QMenu| class.
>
> I tried tweaking it to make it visible... Here's what |background:
> #8d8d8d;| looks like... (not sure if all platforms display this
> correctly tho).
>
> https://github.com/LMMS/lmms/blob/master/data/themes/default/style.css#L71
>
> Since @diizy <https://github.com/diizy> made this theme, I'll give him
> a chance to chime in before making any changes. :smirk:
>

It's fine :)
