### ISSUE TITLE
Issues with BB Editor on project load

### ISSUE THREAD

**Issue by badosu** [LMMS/lmms#1621]
So, the BB Editor simply disappears after loading a different project:

![2015-01-13-132528_1211x343_scrot](https://cloud.githubusercontent.com/assets/347552/5723068/5f0dd4b0-9b28-11e4-9a9e-37e212d3c740.png)

You should be able to reproduce this by simply loading a project that has as many BB Tracks as enough to overflow the BB window vertically, something like 10 tracks should be enough.

You can use this project as a reference: [Sidechain](https://lmms.io/lsp/download_file.php?file=3587&name=sidechain.mmpz). Load the project and click on the BB Editor button to show it. Notice how the BB Editor does not show anything inside the container, and you can't add or edit tracks.

**Comment by tresf** [comment]
Recent changes are here.

https://github.com/LMMS/lmms/commits/master/src/gui/editors/SongEditor.cpp

P.S.   @Lukas-W is already looking into this.

**Comment by romabysen** [comment]
I have the same problem except I can't get the Beat+Bassline editor window working, no matter how much a click on it or resize it.

**Comment by badosu** [comment]
@romabysen Even after clicking play?

**Comment by romabysen** [comment]
Oh wait, I do but only after I have loaded a few songs. After making a new project and then load a song it's back to not working and then I load a few songs and I can get it working by resizing the window.

**Comment by musikBear** [comment]
is this graphic glitch on all platforms -?  Never saw it on win 32  (?)
However sometimes some of the gui sliders are 'obscured' (1.1)
'windowing' and back to full-screen fix it, but theee are of the type i like to call 'glitch' or bug2, annoying, but not critical

**Comment by badosu** [comment]
@musikBear @romabysen This was introduced recently and should not be present on any stable version.

I am going to take a look at it.

**Comment by romabysen** [comment]
Yep, it was introduced after the 1.1.0 release. I've only built from git source on Linux but I presume it also happen on Windows.

**Comment by tresf** [comment]
Partly closed with #1657.  Will leave open for BBEditor.

**Comment by badosu** [comment]
Ok, so used [git bisect]() to try find out which commit introduced the bug on the B/B Editor but I wasn't able determined if some commits were **good** or **bad** due to the fact that a change on the Timeline source file introduced compiling issues, so I had to skip these. One of these commits is the offending bug:

> git bisect skip
> There are only 'skip'ped commits left to test.
> The first bad commit could be any of:
> 86f2c866b6749e5e7eb5c9e8ea110e1c624a77aa
> d8db8948a80513106572a87d5d7437c6fa7d9355
> 3e9cc61042d753ba73d0e0786ae7ecb618e68b18
> ec9158cda9f85a97b4830a1520aec6fc4d0ff0f9
> 02006f98557526add0dc8f555b9b7cd68ab2fb41
> e9d841dec134b6b38774443af0716ef56ec0f825
> 4b275693b6af977d9e4cdfbc746a432e52abb591
> c6ee6140120967f00b05d4144cfdf17e4e723a7c
> 44b52ebd99b614dcc28cc4da284ac583dcbdc216
> d029c8513a9ccfc60716cf1d5f5927aed7704df5
> 11898a5162f32b49431ab4df121cb01f868e040d
> We cannot bisect more!

**Comment by badosu** [comment]
So, I really want this issue fixed because it affects the most basic usage of LMMS, and I can't move on to other issues while this is present.

I have a strong feeling that this problem was introduced on https://github.com/LMMS/lmms/commit/d029c8513a9ccfc60716cf1d5f5927aed7704df5 . @Lukas-W Any idea on what should I be looking for to fix this?

**Comment by Lukas-W** [comment]
Hm… What exactly is the issue here? Is the BBEditor's content just not showing up at all or is it misplaced like it was in the song editor? What steps fix the issue when it occurs?

**Comment by badosu** [comment]
@Lukas-W Just updated the description, just load a different project with many BB Instruments, if the quantity is enough so that it overflows the window vertically the BB Editor becomes unusable.

**Comment by badosu** [comment]
@Lukas-W Here is a project that presents this problem: https://lmms.io/lsp/download_file.php?file=3587&name=sidechain.mmpz

**Comment by badosu** [comment]
@romabysen I discovered the reason this bug seems random, read the updated description of this issue.

**Comment by Lukas-W** [comment]
@badosu Thanks for the detailed research :)

**Comment by badosu** [comment]
Thanks @Lukas-W, I am sorry I could not find it by myself. I am still trying to get the hang of the code. :-)

**Comment by Lukas-W** [comment]
Huh? No worries. :) I'm the one who introduced the bug so I'm quite happy with me being the one who cleans up the mess.
Also note that those `parentWidget()` calls in `saveSettings` and `loadSettings` are more of a hack and we actually shouldn't have them there.

**Comment by badosu** [comment]
Thanks for the description @Lukas-W. Let me just ask how did this commit fix the overflow issue, was it by fixing the `closeEvent` override?

**Comment by Lukas-W** [comment]
The `closeEvent` thing is just a clean-up. @DanWin introduced this in #1495 while I took a different approach to solving the issue in a different branch in d8db8948a80513106572a87d5d7437c6fa7d9355. 

The `saveSettings` and `loadSettings` override fixes it (at least I hope it does, have you tested it?). The bad commit was indeed d029c8513a9ccfc60716cf1d5f5927aed7704df5. In #1426 (Editor Refactoring) I split all editors in two classes, one for the window+toolbar, and one for the actual inner widget (that's `BBEditor` and `BBTrackContainerView` here). 
The `saveSettings` and `loadSettings` methods were supposed to save and restore the editor window's position, size and visibility on project load. They still reside in `BBTrackContainerView`, the inner widget, though, so when loading a project, the saved data would be applied on the inner widget instead of the actual MDI window. This happened here with hiding the track container widget instead of the window.
I fixed this by overriding  the two methods to apply saved settings to the `parentWidget()`. The right solution (architecturally) would have been to move thm up to `BBEditor`, but I'll save that for another time.

**Comment by badosu** [comment]
@Lukas-W thanks for the detailed explanation, I'll take a look and study it to understand the codebase better. :-)

> The saveSettings and loadSettings override fixes it (at least I hope it does, have you tested it?).

Yes it works. Thanks!
