### ISSUE TITLE
Muted automation patterns is not saved

### ISSUE THREAD

**Issue by Sti2nd** [LMMS/lmms#1631]
Steps to reproduce:
- Make automation
- Mute it
- Reopen project, remember to save first!

Win7 64bit, LMMS 1.1.0

**Comment by Spekular** [comment]
@sti2an by "reopen" i suppose you mean save, close, open lmms, load? Just
clarifying because I wouldn't consider saving to be part of the process of
reopening.

**Comment by Sti2nd** [comment]
Neither would I, but to test if mute can be saved you kind of want to try saving. Thanks for the comment, updated.

**Comment by Sti2nd** [comment]
@tresf Wouldn't this qualify for a bug fix release? Instead of waiting for 1.2, I mean.

**Comment by softrabbit** [comment]
Tested on stable-1.1 and what I see could be described more like "muting of automation pattern is not saved". Tracks seem to save and load just like they should.

**Comment by tresf** [comment]
@Sti2nd, yes it could.  GitHub hides those because the milestone has been reached (should tag it 1.1.1 or something).  But from a priority standpoint, I'm not sure how much demand there is for this. :confused:

**Comment by Sti2nd** [comment]
More demand than any of the features you can throw at me. No point in a mute feature if you cannot save it?

**Comment by tresf** [comment]
Excuse me? We don't throw features at you.  Dont be rude.

**Comment by Sti2nd** [comment]
Oh god, my English. I meant that I rather want the existing features to work than new features, mostly at least.

You work hard on new features, I appreciate it a lot :)

**Comment by tresf** [comment]
"We" do.  And that should include you too.  We need help on these bugs and I hope we are all marching in the same direction.

**Comment by Sti2nd** [comment]
> I hope we are all marching in the same direction.

I think LMMS2 is hard to gather around when I know so little about what it is. Apart from LMMS2 I guess bug fixing is the direction?

**Comment by tresf** [comment]
This is milestoned for 1.2.  What are you talking about?

**Comment by Sti2nd** [comment]
I thought you were talking about the whole project. Yes, direction LMMS 1.2 I am totally in for.

**Comment by tresf** [comment]
And I thought you were on topic.  This bug is staged for 1.2.  If you have problems with that vent elsewhere.
