### ISSUE TITLE
Allow drag-and-drop of project files

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms#1634]
As the title suggests, it may be intuitive to a user to be able to drag a project file into the Song Editor like most other items are, rather than double-clicking it.

**Comment by Spekular** [comment]
@tresf Would you consider this something that could be part of the drag n
drop/touch enhancements consolidation issue? I haven't had the time to go
through github and check the other issues yet, but i should be able to soon.

**Comment by tresf** [comment]
I'm not sure what this has to do with touch?  It could go towards general usability, but it is likely a pretty quick fix that could be targeted at 1.2.

**Comment by Spekular** [comment]
@tresf hasn't this been implemented?

**Comment by tresf** [comment]
Was waiting for #1671, which has since been merged.  Closing. 
:+1:

**Comment by curlymorphic** [comment]
Looks like i tagged the incorrect issue on the pull request, edited now.  #1643 was closed because of my error and needs reopening, sorry about that.

**Comment by tresf** [comment]
> #1643 was closed

Reopened.  Thanks for the attention to detail, that would have slipped through the cracks.
