### ISSUE TITLE
Don't work export in audio formats

### ISSUE THREAD

**Issue by drrammstein** [LMMS/lmms#1636]
If i try export any file - program freeze on 0%, after closing export window - it crashes.

**Comment by tresf** [comment]
@drrammstein, which LMMS version and OS version?  Please be as specific as possible.

**Comment by drrammstein** [comment]
Sorry that i not told this. LMMS 1.1.0 (trying 64 and 32 bit versions)  OS Windows 7 SP1 64bit.

**Comment by DanWin** [comment]
@drrammstein I assume your locale is Russian? #1496 This got fixed in source code, but no new builds for stable were made since then.

**Comment by tresf** [comment]
@DanWin good call.  We should release a patch release `1.1.1` for this as well as a few other fixes.  I'll get on that.

**Comment by drrammstein** [comment]
Yes, Russian. Thanks, i will try this method. And sorry for my English)

**Comment by drrammstein** [comment]
Thank You! All works.
