### ISSUE TITLE
calcSlope1 was not declared

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms#1638]
@diizy, for some reason `stable-1.1` travis is failing with the following message:
```
/home/travis/build/LMMS/lmms/plugins/monstro/Monstro.cpp: In member function ‘void MonstroSynth::updateModulators(float*, float*, float*, float*, int)’:
/home/travis/build/LMMS/lmms/plugins/monstro/Monstro.cpp:787:56: error: ‘calcSlope1’ was not declared in this scope
/home/travis/build/LMMS/lmms/plugins/monstro/Monstro.cpp:797:70: error: ‘calcSlope1’ was not declared in this scope
/home/travis/build/LMMS/lmms/plugins/monstro/Monstro.cpp:811:63: error: ‘calcSlope1’ was not declared in this scope
/usr/bin/cmake -E cmake_progress_report /home/travis/build/LMMS/lmms/build/CMakeFiles 
```

Not sure if this is Travis upset or if it is an actual bug... The commit says it failed too... https://github.com/LMMS/lmms/commit/e33645f9aba8dc4e007dc02f94c8084bfc4eba74
https://travis-ci.org/LMMS/lmms/builds/47164992

**Comment by DanWin** [comment]
I just created a pull request that should fix these issues, caused by changes that were added to master, but only partly to stable-1.1

**Comment by tresf** [comment]
Thanks!!

**Comment by badosu** [comment]
Good one! :+1:
