### ISSUE TITLE
VST & x64

### ISSUE THREAD

**Issue by oeai** [LMMS/lmms#1640]
git pull
CmakeLists.txt ->WANT_VST=OFF
cmake / make /make install
/usr/local/bin/lmms ->
VST sync support disabled in your configuration
VST_PATH not set, defaulting to /home/user/vst
segmentation fault
was there a version change for 1.1.1 at splash screen? i got 1.1.0

**Comment by tresf** [comment]
> was there a version change for 1.1.1 at splash screen?

If CMakeLists says 1.1.1 the splash will too.  Try cleaning up your cmake cache.... So.e thing sounds off.

**Comment by oeai** [comment]
deleted lmmsrc.xml
got setup screen, trying to change alsa \ pulseaudio
restart and again segmentation fault
cmakeLists got 1.1.0 version branch master

**Comment by tresf** [comment]
> deleted lmmsrc.xml
got setup screen, trying to change alsa \ pulseaudio
restart and again segmentation fault
cmakeLists got 1.1.0 version branch master
> 
with pulseaudio
Connection established.
Stream successfully created
segmentation fault

Are you running it or building it?  Please don't be vague.  We expect higher quality bug reports from the experienced submitter such as yourself. :)

**Comment by oeai** [comment]
i'm building
then running that was a kind of what i get in terminal

**Comment by tresf** [comment]
```
deleted /usr/local/share/lmms and make install again 
```

Well before installing it permanently to your system, I would recommend installing it in user space to `/target/` to make sure everything is working.

But if you are building  you should please tell me if you did a clean build as originally asked.

 * Git pull the latest version
 * Remove CMakeCache.txt
 * make clean
 * configure and build to `/target/`
 * If it runs from `/target/`, install to system.

-Tres

**Comment by oeai** [comment]
i'm doing 
git pull
mkdir build
cd build
cmake .. etc
i did twice with copy of lmms git-dir to /tmp it's not working from /build

**Comment by DanWin** [comment]
I was able to reproduce this. This seams to happen since yesterday. I made a pull request that should fix this: #1645
It got introduced in c7e3ab3d46cc083dd2946b749416ac754ba295ae committed about one hour before your report, so I assume you reported this immediately after trying out?
Note: git pull fetches from the master branch, as it is the default now. If you want to use the stable branch, you will have to do
git checkout stable-1.1
git pull origin stable-1.1

**Comment by oeai** [comment]
ok thanks, i'll wait for merge

**Comment by tresf** [comment]
> I was able to reproduce this. This seams to happen since yesterday. I made a pull request that should fix this: #1645

Sure, but that's not `1.1.1`, that's `master`.  `1.1.1` looks like this:
https://github.com/LMMS/lmms/blob/stable-1.1/src/gui/MainWindow.cpp#L533

-Tres
