### ISSUE TITLE
Allow "select all" in Song Editor

### ISSUE THREAD

**Issue by romabysen** [LMMS/lmms#1641]
It would be nice if Ctrl+a in the Song Editor would select everything. This makes things a lot easier if you need to add something to the start of your song. Sure, you could zoom out really far and probably select everything manually and then zoom back in but it would be much nicer if you could just select all.

**Comment by musikBear** [comment]
In fact you do not need to select anything, in iorder to move everything!
Place you playhead at the wanted posistion. It can be any pos, also in middle of your project
Hold sh, and tab either : 
* insert : All blocks to the right of playhead wil move to the right
* delete  All blocks to the right of playhead wil move to the left -mat result in overlapping!!
For more smart keys: https://lmms.io/documentation/Key_Mappings

**Comment by romabysen** [comment]
Hah! Totally missed those keyboard shortcuts. Nice to know.

**Comment by tresf** [comment]
> Hah! Totally missed those keyboard shortcuts. Nice to know.

No worries... Most of us didn't know about these either until recently. :+1:

**Comment by Sti2nd** [comment]
Already proposed as a shortcut in the new shortcut table :-) Read the wiki, the only place to learn LMMS(?) Did you know about it? Is reading boring? I am not kidding, answer as truthful ad possible.

**Comment by tresf** [comment]
> Read the wiki, the only place to learn LMMS(?) Did you know about it? Is reading boring? I am not kidding, answer as honest as possible please.


You have to really shut up.  I am not kidding.

**Comment by Sti2nd** [comment]
>I am not kidding

Is it this that offended you? I am asking questions to find out about the users relationship to our resources. You mean I shouldn't have asked here on github?

**Comment by tresf** [comment]
Fine, I'll be blunt..... The next RTFM comment to our users is getting deleted.

**Comment by Sti2nd** [comment]
I understand explicit. Great that you tell me, hard to guess what to do and not to do when you are fresh. This is probably normal etiquette for developers with work experience. Are there guidelines on how to assist users on a tracker? If so I would love to learn them.

**Comment by Sawuare** [comment]
Implemented in `master` via #3649.
