### ISSUE TITLE
"Set Linear" not saving properly

### ISSUE THREAD

**Issue by Gps2010** [LMMS/lmms#1642]
**Edited 2015-01-16 @tresf**

The `Set Linear` function in some plugins doesn't seem to be saving properly.  Steps to reproduce:

 1. Open a new project
 2. Add `Calf Reverb` effect to master channel
 3. Change `Bass Cut` knob to `Set linear`
 4. Save project.
 5. Reopen project, examine `Bass Cut` `Set linear` knob settings was not saved

**Note:**  If this is done on both `Bass Cut` as well as `Treble Cut`, the `Set linear` setting will be saved Bass Cut, not Treble Cut.

-Tres

---

**Original bug report**

Hi guys

I am not sure if the issue I had is the same, but to me it looks like it.

I had made a song with the previous version. After loading it in lmms, I had issues with two automation tracks. The sound was distorted. Redoing those automation tracks worked for me.
On the lmms forum however there is a topic with the same title as this one.
Some one is having an issue with the calf filter.
http://lmms.io/forum/viewtopic.php?f=7&t=1557

**Comment by tresf** [comment]
@Gps2010 since the automation track can control a lot of different components, we'll need to know exactly how to reproduce this issue.

Please provide step-by-step instructions to reproduce.

-Tres

**Comment by Gps2010** [comment]
I just checked my pc, I stil have an older file with this issue.
Will uploading the project file help ? 

The only thing I did update lmms, and load the project made with the previous version.
Then some distortion happens on a track were I used the automation editor.

**Comment by tresf** [comment]
@Gps2010 at least tell us what the automation track is connected to.  Screenshots usually help too.

**Comment by BetoVickers** [comment]
Hi, I'm the guy who started the forum topic, this happens when you load an old project, but... to "reproduce" it from scratch in 1.1.0 you need to add an effect, for example Calf Reverb, set Bass Cut and Treble Cut to linear, add and set an automation track for ONE of the knobs (Treble Cut for example), save, restart and load the project.
You will see that one of the knobs switch back.
![lmms values differences](https://cloud.githubusercontent.com/assets/10542453/5778864/1c621e9e-9d7d-11e4-8c70-ec9f4ccf3ed5.png)

**Comment by musikBear** [comment]
yes i think a mmp would be a good thing -please upload

**Comment by BetoVickers** [comment]
(V2 is a fix attempt)
https://www.dropbox.com/s/151og3e4fz0qb0k/LMMS%20Banned%20From%20BCH%20ProjFiles.zip?dl=0

**Comment by tresf** [comment]
> yes i think a mmp would be a good thing -please upload

@musikBear If we can reproduce it without downloading someone's mmpz, that is better and @BetoVickers is doing just that.

@BetoVickers,

Is it a visual problem with the automation editor, or are the values actually wrong?  The OP says "redoing automation" fixes this, but I'm still a bit confused as to the exact bug that is occurring here.

Thanks for the patience.

-Tres

**Comment by Gps2010** [comment]
Here is as screenshot ( if needed) http://s1158.photobucket.com/user/Guus_Poort/media/desktop4_zps06f24556.png.html?sort=9&o=0
The two autoamtion track contraol the track snare.
One to fade it in, one the pan the sound from left to right.
And here is the file:
https://www.dropbox.com/s/64i3qgnrdxygvkb/biscaya5.mmpz.bak?dl=0

**Comment by Gps2010** [comment]
@tresf I am not sure if its the same problem as BetoVickers is having, The one thing I did noticed we both used an automation track. That why I added my reply to his topic on the lmms forum.

**Comment by BetoVickers** [comment]
@Gps2010 I have a scale problem with knobs, but somehow it seems that affects the automation track too.

**Comment by Gps2010** [comment]
I dont have a clue what happens at the start of the project I uploaded.

From the first time I used the newer lmms, there is some distortion in beginning of the project I uploaded, at the start.
It seems to go away when the songs playes on, and the knobs, pan and volume, change from, Left to centre, to right, and the volume from 0 to 100.

Because there was no distortion, when I muted the automation tracks, I just deleting them, and then and made two new automation tracks. One for pan one for the volume.
For me problem solved. I am just starting to use the automation editor.
Why I replied though, it did not seem to matter if I deleted one of the two automation tracks.
Only after I deleted both, automation tracks and started over the problem was gone.

Not in just one file btw, when I create something i usal have atleast two very recent versions.
I use computers for some time now, and although in my profession its about cad drawings, having only one copy is asking for problems. No, I dont trust computers.

**Comment by tresf** [comment]
> No, I dont trust computers.

:smile: 

Well... we do trust them.  We trust them to do exactly as told, and they're pretty good at that.

We should be able to reproduce this with the information provided.  Thanks for the information.  We'll post here when we have an update to this specific bug.

**Comment by tresf** [comment]
Ok, unless someone can clarify, automation has nothing to do with this.  This is what I observe:

The `Set Linear` function in some plugins doesn't seem to be saving properly.  Steps to reproduce:

 1. Open a new project
 2. Add `Calf Reverb` effect to master channel
 3. Change `Bass Cut` knob to `Set linear`
 4. Save project.
 5. Reopen project, examine `Bass Cut` knob settings were not saved

**Note:**  If this is done on both `Bass Cut` as well as `Treble Cut`, the `Set linear` setting will be saved Bass Cut, not Treble Cut.

**Comment by diizy** [comment]
On 01/16/2015 11:06 PM, Tres Finocchiaro wrote:
>
> Ok, unless someone can clarify, automation has nothing to do with
> this. This is what I observe:
>
> The |Set Linear| function in some plugins doesn't seem to be saving
> properly. Steps to reproduce:
>
>  1. Open a new project
>  2. Add |Calf Reverb| effect to master channel
>  3. Change |Bass Cut| knob to |Set linear|
>  4. Save project.
>  5. Reopen project, examine |Bass Cut| knob settings were not saved
>
> *Note:* If this is done on both |Bass Cut| as well as |Treble Cut|,
> the |Set linear| setting will be saved Bass Cut, not Treble Cut.
>

That's odd, I distinctly remember fixing this bug before. Can you take a
look at how the relevant .mmp looks with both settings (linear/log)?

For me, at least knobs that are linear by default get properly saved as
log when set as such. Maybe it just doesn't work the other way around
for some reason...

**Comment by tresf** [comment]
> For me, at least knobs that are linear by default get properly saved as
log when set as such. Maybe it just doesn't work the other way around
for some reason...

Thanks for the feedback.  Yeah, it works for me too, but it might be some strange off-by-one problem, because one knob is saved whereas the other is not.

> Can you take a look at how the relevant .mmp looks with both settings (linear/log)?

Will do this now.

**Comment by tresf** [comment]
Hmmm... different results on Apple from the testing earlier... 

I'll fire up 12.04 and see how that compares... 

![screen shot 2015-01-16 at 5 04 27 pm](https://cloud.githubusercontent.com/assets/6345473/5785206/cec07d0a-9da1-11e4-9acc-1f9760eda82d.png)

```xml
<port07>
   <data scale_type="log" value="0.98915" id="3191917"/>
</port07>
<port08>
   <data scale_type="log" value="6324.75" id="3874972"/>
</port08>
```

**Comment by tresf** [comment]
Sorry, that was bad data... deleting... here's something better:

![image](https://cloud.githubusercontent.com/assets/6345473/5785321/4449c3c8-9da3-11e4-9638-98f7d4ce16e6.png)


![screen shot 2015-01-16 at 5 12 44 pm](https://cloud.githubusercontent.com/assets/6345473/5785298/029a5c62-9da3-11e4-8261-3ce62fe59a85.png)

**Comment by tresf** [comment]
@diizy is the problem that the knobs are explicitly logarithmic in code, but never overriden in the xml?  Is seems the preference is wiped out when set to linear.

**Comment by diizy** [comment]
On 01/17/2015 12:06 AM, Tres Finocchiaro wrote:
>
> Hmmm... different results on Apple from the testing earlier...
>
> I'll fire up 12.04 and see how that compares...
>
> screen shot 2015-01-16 at 5 04 27 pm
> <https://cloud.githubusercontent.com/assets/6345473/5785206/cec07d0a-9da1-11e4-9acc-1f9760eda82d.png>
>
> <port07>
>    <data scale_type="log" value="0.98915" id="3191917"/>
> </port07>
> <port08>
>    <data scale_type="log" value="6324.75" id="3874972"/>
> </port08>
>
> —
>

Ah, yeah, I think this might be a problem in LadspaControl... I'll take
a look at it when I have the chance.

**Comment by diizy** [comment]
On 01/17/2015 12:16 AM, Tres Finocchiaro wrote:
>
> @diizy <https://github.com/diizy> is the problem that the knobs are
> explicitly logarithmic in code, but never overriden in the xml? Is
> seems the preference is wiped out when set to linear.
>

They're set to logarithmic because the LADSPA plugin gives a hint to do
so. The override should set the same variable from log to linear. For
some reason the saveSettings() call, either in AutomatableModel or
LadspaControl (not sure yet which is the problem) doesn't respect this.

**Comment by unfa** [comment]
Oh this gave me real headache recently. I started using Dual Filter for
fikter sweeps because if this problem. I'm using 1.0.100
17 sty 2015 12:23 "Vesa V" <notifications@github.com> napisał(a):

**Comment by Sti2nd** [comment]
Don't use that Unfa. Derp. If it is because of Kx Studio ppa, you have my condolences

**Comment by BetoVickers** [comment]
> Ok, unless someone can clarify, automation has nothing to do with this.

No, but there is one more thing... when you change the scale, the automation track doesn't update the "position" of the points, that affects the values.
The picture corroborates that in some way. On the left is set to linear and the right to "log", points are in the same position but having different values.
![lmms values differences](https://cloud.githubusercontent.com/assets/10542453/5792092/3cf3f588-9ee5-11e4-9725-66e207cc0dac.png)
If you want to reproduce it you need to adjust some points in the automation track, remember their values and change the scale of the knob.

**Comment by Umcaruje** [comment]
>Don't use that Unfa. Derp. If it is because of Kx Studio ppa, you have my condolences

Do you honestly have a clue about what you are talking about? The KXStudio version isn't broken, it just has a misleading version number. Last time I checked, you were a windows user. How do you know if the  ppa is bad?

**Comment by Sti2nd** [comment]
Tres said they weren't identical, he built those versions. They are almost equal, though, I shouldn't claim it is the version's fault. 

Isn't it strange that KX hasn't updated to the latest?

Check again, Uros. And one really must be a linux user to know? Sorry, I didn't knew that.

**Comment by tresf** [comment]
@Sti2nd if you have nothing further to offer, please let this thread progress on its own.

This bug exists in any build with Logarithmic knobs.  

As far as the KXStudio build number... Thst is mostly cosmetic and mostly my fault (minir version release without CMakeLists.txt version bump).

**Comment by tresf** [comment]
@diizy, could this be causing it https://github.com/LMMS/lmms/commit/1cd3c9be2c4cddc0bdc7acef5d2fe6254293c06e ?

It seems like if `isAutomated()` returns false, then it can have strange side effects.

This would also explain the inconsistencies in our test results, right?  Originally it was saving one control but not the other, but that was reproducing the automation track per original bug description.

-Tres

**Comment by BetoVickers** [comment]
*cough cough* amm, this also happens when you connect it to the LFO (or even when isn't connected to anything)

**Comment by tresf** [comment]
I'm going to tag @curlymorphic and @badosu on this one for some help.

**Comment by serdnab** [comment]
this sets if the control is logarithmic or linear when you load the plugin:

https://github.com/LMMS/lmms/blob/9a44eaf3c7fc7cf18bf278191c89017a1f3f0240/plugins/LadspaEffect/LadspaEffect.cpp#L457


There are three ways of saving the state of a knob in the .mmpz:
```
<port07>
<data scale_type="log" value="0.98915" id="3663828"/>
</port07>
<port08>
<data scale_type="linear" value="2000.25" id="7104297"/>
</port08>
<port09 data="2"/>
```
if you don't automate a linear knob it saves like the third way, then when you load the file it runs:

https://github.com/LMMS/lmms/blob/9a44eaf3c7fc7cf18bf278191c89017a1f3f0240/src/core/AutomatableModel.cpp#L179-L200

if the control state is saved like the third way it enters the else block in the code above, so it doesn't run setScaleType() and it lets the state of the knob as detected by LadspaEffect.cpp

i'dont know the correct way to fix this, force non-automated linear knobs to save like the second way, or add setScaleType(Linear) to the else block

Suggestions?

**Comment by tresf** [comment]
@serdnab yeah, I had suspected https://github.com/LMMS/lmms/commit/1cd3c9be2c4cddc0bdc7acef5d2fe6254293c06e as the culprit last I looked at this (about a year ago).

The logic is plain wrong to me... IIRC, it makes some bad assumptions...

Whenever I see an if statement that says `if (!foo) { bar = foo ? lorem : ipsum; }`  it's usually a clear sign a mistake was made.
