### ISSUE TITLE
cannot write midi input

### ISSUE THREAD

**Issue by oeai** [LMMS/lmms#1647]
i can play music with ZYna +midi connected, but when i push record in note editor midi input is not recording or dispalyed, while music still goes and i see  green light blinking when sound is on
in the same time i can play with keyboard that is recording normally

before this issue was for Zyna only and i was able to record midi with another instrument
now it does not work at all

also notes playing with keyboard don't support longitude, the longer i press the longer note should be

the only terminal output of that session
NOTES TOO MANY (> POLIPHONY) - (Part.cpp::NoteOn(..))

**Comment by tresf** [comment]
Which branch?

**Comment by oeai** [comment]
master

**Comment by tresf** [comment]
Duplicate of #1464.
