### ISSUE TITLE
Stretch/Shrink/Shorten Patterns via SongEditor

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms#1658]
For some time we've had the ability to stretch a piano roll pattern in the piano roll editor via `Select All` and the `Shift` modifier key when dragging a note.

![image](https://cloud.githubusercontent.com/assets/6345473/5978859/07693cf8-a871-11e4-92ad-a3f899efcda2.png)

Possible functionality:
1. Open Song Editor
2. Create a new Piano Roll pattern
3. Draw some notes
4. Go back to Song Editor
5. Hold shift and resize Piano Roll pattern
6. Piano roll pattern shrinks in size and notes shrink to scale with pattern.

**Similar to this current functionality:**   (animation courtesy of Uros).
![0.4.15](http://i.gyazo.com/cb2336a9e4950f27c3cb554dd08a7683.gif)

This is an enhancement request to add the same functionality to the Song Editor window, including shortening capabilities. :)

**Comment by badosu** [comment]
@tresf Could you develop this feature request a little more?

How should this functionality behave/be like?

**Comment by tresf** [comment]
I'll quote @Sti2nd here as this was extracted from another closed bug report:

> You could potentially extend the stretch/shrink functionality from Piano Roll so that resizing a pattern in Song Editor will make use of the Shift shortcut and also stretch the notes.

-Tres

**Comment by tresf** [comment]
In terms of functionality, I don't know exactly (haven't thought of it much to be honest) but I would assume it would have the same exact effect as doing this in the Piano Roll and it would probably only work for piano roll patterns out of the gate.

Possible functionality:
 1. Open Song Editor
 2. Create a new Piano Roll pattern
 3. Draw some notes
 4. Go back to Song Editor
 5. Hold shift and resize Piano Roll pattern

![image](https://cloud.githubusercontent.com/assets/6345473/5978859/07693cf8-a871-11e4-92ad-a3f899efcda2.png)

Piano roll pattern shrinks in size and notes shrink to scale with pattern.

**Comment by badosu** [comment]
@tresf @Sti2nd I just want to really understand if this is something that's really useful and missed, because it's feasible.

**Comment by Sti2nd** [comment]
> Hold shift and resize Piano Roll pattern

Or without Shift. Can someone think of another feature which could make use of resizing a instrument pattern? I think I remember diizy perhaps having a plan, maybe I should tag him and ask?

> really useful and missed

Not sure :p If more simple note editing like this feature could be done from the Song Editor I guess it could be really useful and time saving.

**Comment by tresf** [comment]
> Or without Shift. Can someone think of another feature which could make use of resizing a instrument pattern? I think I remember diizy perhaps having a plan, maybe I should tag him and ask?

I suppose "without shift" depends on how intuitive stretching our patterns is.

For example... in an automation pattern and BBEditor pattern, you can make them bigger, but they certainly don't stretch.  Why would we allow the same shortcut to have a completely different behavior?  Shift seems to be consistent with the Piano Roll and also prevent the confusions that a non-shift shortcut could potentially create.

-Tres

**Comment by tresf** [comment]
> I just want to really understand if this is something that's really useful and missed, because it's feasible.

I think it can be somewhat valuable as melodies/drums patterns can slow down and speed up in an arrangement.  This could be a very quick shortcut for doubling or halfing the note frequency of an arrangement.

I can't say I've ever thought of this prior to the OP's suggestion in 1648 though. :smile:

**Comment by Sti2nd** [comment]
You are right, Tres, and simply dragging in and out an instrument pattern should add and remove space normally just as the others. I didn't think that would be useful, but it is.

**Comment by unfa** [comment]
If this piano roll trick is what I think it is, it works correctly only for
note streaks where every note has the same length. It doesn't work by
multiplying note values by a given fraction (scaling them proportionally),
but by adding a given length to each note and shifting the notes so they
don't overlap. Also the mouse position change is interpreted as a length
increment/decrement for every note, not as the new position of the right
wall of a bounding box containing all selected notes. Is this correct?
31 sty 2015 00:59 "Stian Jørgensrud" <notifications@github.com> napisał(a):

**Comment by badosu** [comment]
@unfa This gif that is referenced by @tresf is not really related to this issue.

In fact the functionality denoted there already exists: select notes on Piano Roll and use `<Shift+Drag>` on the resize handle.

The functionality that is wanted in this issue actually is about stretching/shrinking patterns on the Song Editor instead of the Piano Roll. The only similarity with the gif denoted here is that it should make notes faster/slower like it is being shown.

**Comment by unfa** [comment]
Oh, I've gone offtopic again - sorry!
4 lut 2015 22:30 "Amadeus Folego" <notifications@github.com> napisał(a):

**Comment by tresf** [comment]
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.
