### ISSUE TITLE
Bad/old wiki links issue with DuckDuckGo

### ISSUE THREAD

**Issue by pbella** [LMMS/lmms#1664]
There have been several times when I have searched for 'lmms <whatever>' and the top results that come back don't appear to be the most current / relevant for LMMS.  Most of these issues have been occurring with DuckDuckGo and when I attempted to replicate via Google, it did not have this issue so it appears to be search engine specific.

For example,  when searching for 'lmms piano roll' (without quotes), duckduckgo.com returns the following top 3 links:
https://lmms.io/wiki/index.php?title=Main_Page
http://www.youtube.com/watch?v=7ZHM__Q1bkE
http://lmms.sourceforge.net/wiki/index.php/0.4:Key_Mappings

where performing the same search via Google returns (after redirect):
https://www.youtube.com/watch?v=7ZHM__Q1bkE
https://www.youtube.com/watch?v=4dYxV3tqTUc
https://lmms.io/wiki/index.php?title=Piano_Roll_Editor

The main point here is that the first LMMS 'owned' link in Google results appears to be exactly what someone would expect to be returned, while the first two in DuckDuckGo (wiki home page, old sourceforge wiki) are probably not what one wants.  I've tried this type of search with numerous other search terms and it appears to be consistently wrong with DuckDuckGo.  Not sure how easy this is to get corrected, but wanted to report it in case there's anything that can be done on the LMMS end...

**Comment by Sti2nd** [comment]
Probably not. Search engines have algorithms that tries to find the best link for you, usually popularity seems to be the most important consideration, so if 100 000 have clicked the old link you must perhaps click the new link 100 000 times before it will be on top.

I can only guess google has a better algorithm which perhaps consider the age of the site and/or how many visitors the site got too.

**Comment by tresf** [comment]
> http://lmms.sourceforge.net/wiki/index.php/0.4:Key_Mappings

Yes, this is a bug.  We should be redirecting to:

**Valid:**
https://lmms.io/wiki/index.php?title=0.4:Key_Mappings

But instead it is probably trying:

**Invalid:**
https://lmms.io/wiki/index.php/0.4:Key_Mappings

Thanks for the information.  There may be other links like this out in the wild.

@Umcaruje  @Lukas-W thoughts appreciated here.  I don't know why some links use one format over the other but if we can either fix our redirects or process the URLs on our side, this could fix some old links from improperly redirecting...

**Comment by badosu** [comment]
I don't understang why this bug is filed in this repository. Where should a possible fix apply? Isn't it on https://github.com/LMMS/lmms.io ?

**Comment by pbella** [comment]
Newbie ignorance on my part... I wasn't aware of the other repo for the site.  I'll be sure to use that for  future issues as appropriate.

**Comment by badosu** [comment]
@pbella Don't worry, I was just trying to understand if this was something that could be addressed here. :-)

**Comment by tresf** [comment]
Moved to https://github.com/LMMS/lmms.io/issues/139
