### ISSUE TITLE
Piano roll shift-drag stretch/shrink is illogical

### ISSUE THREAD

**Issue by softrabbit** [LMMS/lmms#1666]
IMO the stretch/shrink mode in piano roll works in a pretty illogical way. If I select e.g. 5 notes and shrink them to fit 4 beats, I'd expect only the selected notes to be affected. Now all notes move that are simultaneous with the selected ones or later.

NB. I'm not saying the feature in itself is broken, just that the UI for it could use some rethinking.

**Comment by Sti2nd** [comment]
If you think about how it works, adjust the size and move the notes after move a corresponding amount , I think it is somewhat logical. Now it has two purposes.
- if you find out that one (or more) note should be longer you can drag that out easily and the rest makes room for it
- if you find out that several notes should be longer or shorter you can make that happen

Your suggestion makes sense, then the last note wouldn't follow the logic of moving the notes after? Maybe Shift + Ctrl + left drag can be used.

**Comment by musikBear** [comment]
just to 'pin' the "stretch/shrink mode" - we are here talking about **sh+mouse-drag** on selections.
@softrabbit 
No, its important that it works like it does
You need to look at *note-stacks* (chords) to understand the importance.
imagine you have a 
* 2 tick note in c4
* 4 tick note in a3
You like the 'attacks' from the small plucky c4, but realize, that the 'hum' from a3, must be at least 2 beats (8 tick)
If the not selected notes diddent move with the selections, then you would have to manually ajust each of the c4s, after you have extended the a3s. As it is now, this is not nescessary. Everything fits, after the extention of the chords a3 notes. The c4s will still be in attack pos of the a3s

**Comment by Sti2nd** [comment]
> No, its important that it works like it doe

Cause it is useful, yes, but what softrabbit is suggesting is also useful. Consider that you have some notes 
![image](https://cloud.githubusercontent.com/assets/6373430/5836036/e9e7556e-a16f-11e4-97ec-29c9fda5422b.png)
and want to make the two first play faster.
![image](https://cloud.githubusercontent.com/assets/6373430/5836045/13e9371a-a170-11e4-82f4-8c1553192c32.png)

**Comment by Spekular** [comment]
I don't see why the user can't select all the notes if they want all the notes to scale. It's more logical (imo) and also more flexible if only the selected notes are scaled.

**Comment by Sti2nd** [comment]
> It's more logical (imo) and also more flexible if only the selected notes are scaled

? But it is only the selected ones who are resized? The reason this feature works is because it moves all of the notes after itself with the same amount it is being resized, what you and softrabbit want is an exception for the last note. I think both logic makes equally sense, or maybe it makes more sense now.

**Comment by tresf** [comment]
Agree with @softrabbit.  The software shouldn't assume we want those moved and it is inconsistent with the non-`Shift+Drag` behavior, which does not move the non-selected items.

If we want this "sticky" feature, we add a modifier key to keep it.

**Comment by Sti2nd** [comment]
ok, then Shift + Ctrl for the old behavior

**Comment by badosu** [comment]
@tresf @Sti2nd So the consolidation of this discussion is that the behaviour should change to the **non sticky** behaviour.

Should we delete or mantain the **sticky** behaviour? `<Shift-Ctrl>` is fine as the new modifier for it?

**Comment by tresf** [comment]
I have no objections with keeping it if the modifier key is available and @Sti2nd says it makes sense to use in this context.

**Comment by badosu** [comment]
Ok, just a nitpick, I don't feel this is a bug since the feature was designed intentionally to behave how it behaves today. We are actually enhancing it.

**Comment by tresf** [comment]
> I don't feel this is a bug since the feature was designed intentionally to behave how it behaves today. We are actually enhancing it.

Perhaps, but I've never seen this behavior in other DAWs or any selection/shrink in general (not in video editors or in image editors) which is how it got its classification.  You're absolutely right though, it's not really a bug most interpretations.

**Comment by badosu** [comment]
@tresf @Sti2nd I just implemented this functionality, but found an issue:

The `Alt` modifier is already used on the piano roll to skip the quantization of notes, i.e. skipping the snapping to the lesser known note length.

**Comment by tresf** [comment]
Yes.  Confirmed.  Shift makes them stretch adjacently so it should be a modifier on top of that shortcut if we want to keep it.

**Comment by Sti2nd** [comment]
> Oh, just noticed you actually want <Shift-Ctrl> as the new modifier

For the old or new behavior? It doesn't matter for me, but quote Tres
> If we want to keep this "sticky" feature, we add a modifier key to keep it.

**Comment by tresf** [comment]
Fixed per @badosu's #1716.  @Sti2nd the old behavior is working terrifically w/ the Ctrl modifier.  Probably overkill, but that way we don't lose functionality.  Please feel free to put this in the treasure chest of 1.2 shortcuts or whatever your organization plan is. :+1:
