### ISSUE TITLE
Add an uninstall target for make

### ISSUE THREAD

**Issue by unfa** [LMMS/lmms#1676]
Currently there's no way to automatically remove a manual installation of LMMS (done with make install command).

**Comment by lukas-w** [comment]
From the [CMake FAQ](https://cmake.org/Wiki/CMake_FAQ#Can_I_do_.22make_uninstall.22_with_CMake.3F):

> By default, CMake does not provide the "make uninstall" target, so you cannot do this. We do not want "make uninstall" to remove useful files from the system.
> 
> If you want an "uninstall" target in your project, then nobody prevents you from providing one. You need to delete the files listed in install_manifest.txt file. Here is how to do it. First create file cmake_uninstall.cmake.in in the top-level directory of the project:
> 
> ```cmake
> if(NOT EXISTS "@CMAKE_BINARY_DIR@/install_manifest.txt")
>   message(FATAL_ERROR "Cannot find install manifest: @CMAKE_BINARY_DIR@/install_manifest.txt")
> endif(NOT EXISTS "@CMAKE_BINARY_DIR@/install_manifest.txt")
> 
> file(READ "@CMAKE_BINARY_DIR@/install_manifest.txt" files)
> string(REGEX REPLACE "\n" ";" files "${files}")
> foreach(file ${files})
>   message(STATUS "Uninstalling $ENV{DESTDIR}${file}")
>   if(IS_SYMLINK "$ENV{DESTDIR}${file}" OR EXISTS "$ENV{DESTDIR}${file}")
>     exec_program(
>       "@CMAKE_COMMAND@" ARGS "-E remove \"$ENV{DESTDIR}${file}\""
>       OUTPUT_VARIABLE rm_out
>       RETURN_VALUE rm_retval
>       )
>     if(NOT "${rm_retval}" STREQUAL 0)
>       message(FATAL_ERROR "Problem when removing $ENV{DESTDIR}${file}")
>     endif(NOT "${rm_retval}" STREQUAL 0)
>   else(IS_SYMLINK "$ENV{DESTDIR}${file}" OR EXISTS "$ENV{DESTDIR}${file}")
>     message(STATUS "File $ENV{DESTDIR}${file} does not exist.")
>   endif(IS_SYMLINK "$ENV{DESTDIR}${file}" OR EXISTS "$ENV{DESTDIR}${file}")
> endforeach(file)
> ```
> 
> Then in the top-level CMakeLists.txt add the following logic:
> 
> ```cmake
> # uninstall target
> if(NOT TARGET uninstall)
>     configure_file(
>         "${CMAKE_CURRENT_SOURCE_DIR}/cmake_uninstall.cmake.in"
>         "${CMAKE_CURRENT_BINARY_DIR}/cmake_uninstall.cmake"
>         IMMEDIATE @ONLY)
> 
>     add_custom_target(uninstall
>         COMMAND ${CMAKE_COMMAND} -P ${CMAKE_CURRENT_BINARY_DIR}/cmake_uninstall.cmake)
> endif()
> ```
>

**Comment by PJ-Finlay** [comment]
Does anyone mind if I try to take this issue?

**Comment by PJ-Finlay** [comment]
I made a pull request that should fix this issue #4448.

**Comment by PhysSong** [comment]
Closed via #4448.
