### ISSUE TITLE
Record MIDI sustain pedal

### ISSUE THREAD

**Issue by teeberg** [LMMS/lmms#168]
I would like to record what I'm playing on my MIDI keyboard. However the pianoroll does not record the sustain pedal, i.e. all tones that I bind with the pedal come out extremely short. This makes the recording with the piano quite useless to me, as the recorded audio sounds completely different than what I intended to record.

**Comment by ssaavedra** [comment]
Hi, I'm having this problem with v1.1.3; I record from a MIDI keyboard, but as soon as I stop playing the note they stop recording, when if I have the sustain pedal pressed.

**Comment by evansimonross** [comment]
@tobydox, I'm sorry I have the same problem and I didn't understand your explanation.

**Comment by tresf** [comment]
@evansimonross the commit in this bug was closed 2 1/2 years ago.  If this issue came back, we should track it in a separate issue.

**Comment by tresf** [comment]
Actually we do have an issue for it: https://github.com/LMMS/lmms/issues/1700
