### ISSUE TITLE
FX Presets

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#1680]
In some circumstances the settings for a FX-insert, can be as valubable as a good preset (f.i. compressor sidechain-settings)
In current version, user can save a template-project, but i believe it would be nice if user could import a setting-file.

**Comment by tresf** [comment]
Agreed.  We should honor this preset in both the Instrument windows as well as the FX Mixer window.

**Comment by Reaper10** [comment]
something that would cool to see is a preset reset button & a default setting button.

**Comment by tresf** [comment]
Agreed but what is the difference exactly?

**Comment by Reaper10** [comment]
The preset reset button resets the preset to where started.
 The  default setting button will reset the plugin to the setting they have now ie zeroed out
<img width="840" alt="capture" src="https://cloud.githubusercontent.com/assets/8137561/9833958/9ed112e2-596e-11e5-8694-5a7452fdccd4.PNG">

**Comment by Wallacoloo** [comment]
@Reaper10 where should this button go? (Keep in mind that it must not be placed anywhere in which the user could accidentally click it. FL Studio at one point placed quick preset-switching buttons right by the effect window's close button, and that caused me quite a bit of grief on multiple occasions).

**Comment by Reaper10** [comment]
not sure

**Comment by musikBear** [comment]
i would suggest a *general right-click context-menu*, if a thing like that should be implemented. It is logical, since right-click usually address  settings (at least in win

**Comment by Reaper10** [comment]
VSTs need a preset reset button resets the preset to where started because, I don't know how meny times in other DAWs I've tried a plugin and doing so broke the preset, ie the setting of the vst was forever changed.

**Comment by tresf** [comment]
Yes, FX plugins as well as Instrument plugins could benefit from a reset button.  VSTs would fall into the Instruments plugins area.

**Comment by Reaper10** [comment]
Should I open the vsti part in a  new bug? Even thoe it's the same idea.

**Comment by tresf** [comment]
@Reaper10 it's not a VST enhancement is is an instrument enhancement, and I would strongly advise to stop opening the nice-to-have enhancement requests for some time as you've been placed in a warning status on our bug tracker for abuse of creating too many poor quality requests.

**Comment by Reaper10** [comment]
ok can I say thanks for putting up with me, bye  bye.

**Comment by Reaper10** [comment]
<img width="481" alt="plugin preset toolbar gui idea" src="https://cloud.githubusercontent.com/assets/8137561/10181848/bfa8698a-66e2-11e5-82d7-4c09349e0cef.png">
Plugin Preset Toolbar GUI Idea........ thoughts.

**Comment by tresf** [comment]
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.

**Comment by CaBachhav** [comment]
These same plugins have Preset save load support in ARDOUR DAW.
our lmms definitely needs this facility.
