### ISSUE TITLE
Automation Copy/Paste from Context Menu

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#1685]
win32 1.1.
To reproduce
 1. Insert automation-track 
 1. Ctrl + Drag a control (a dial) into it
 1. Open automation-track and draw a random pattern
 1. Close automation-track editor
 1. Right-click automation-track, choose 'copy'
 1. point to any place on automation-track
 1. Right-click automation-track, choose 'paste'

an automation-track is pasted, but it is maxed out, and the copied pattern cant be used (not copied).
Eg only thing that is copied is the connection to the dial, not the actual pattern

**Comment by tresf** [comment]
I do this quite often.  Does Ctrl + Drag work?

**Comment by musikBear** [comment]
ctrl + drag work perfectly, but it is the contex-menu copy (as described) that does not work, and perhaps more important: Works different than when user copies a note-block. That works correctly from context, so this is a incensistent behavior
We can either 
make it consistent, (eg work as expected)
or 
remove the 'copy / paste' from autotrack centext-meny

**Comment by Sti2nd** [comment]
Got this
![image](https://cloud.githubusercontent.com/assets/6373430/5888362/4297bbd4-a3fc-11e4-871b-3e54d648d4a6.png)

Which looks suspeciously like https://github.com/LMMS/lmms/pull/1677#issuecomment-71247421

**Comment by tresf** [comment]
@Sti2nd in support of your observation... the underlying model seems to be there... 

If you copy/paste via context menu, it appears wrong... but if you CTRL+Copy that new bad segment, it fixes the parent... Example below:


![screen shot 2015-01-25 at 9 18 28 am](https://cloud.githubusercontent.com/assets/6345473/5891726/3971940e-a473-11e4-9279-ac92e032ce24.png)

**Comment by tresf** [comment]
@curlymorphic perhaps this is similar enough to the automation refresh in #1677?

**Comment by curlymorphic** [comment]
looking into this now.

**Comment by tresf** [comment]
Closed via #1689.  Thanks Dave!
