### ISSUE TITLE
Option to open last used project

### ISSUE THREAD

**Issue by Sti2nd** [LMMS/lmms#1694]
http://linux-multimedia-studio-lmms.996328.n3.nabble.com/Changing-default-start-up-project-td4715.html#a4737
On 01/17/2014 11:30 AM, Jonathan Aquilina wrote: 
> I think it would be just easier to implement a user profile. It saves your 
> settings plus it will open up the last project you had open. 

Well this is already implemented to an extent. The settings and the list 
of recenctly opened projects are saved in a file in the user's home 
directory, in the file .lmmsrc.xml. If you switch to a different user 
and open LMMS, the settings will be different. We'd just have to add 
export settings into this file. - Vesa

**Comment by tresf** [comment]
Yeah, a lot of DAWs have the ability to open up to where they left off.

**Comment by Sti2nd** [comment]
Oh, darnit, so sorry, didn't find this when searching last time https://github.com/LMMS/lmms/issues/503

**Comment by unfa** [comment]
This reminds me of Blender's welcome screen.  Blender shows a window where
you can quickly load recent projects, open project load dialog or get some
help. I can see a link to LMMS.io , LSP and a user manual / reference guide
there along with list of templates to load. The window is closed by
clicking anywhere outside it - there's no close button - and you're ready
to start working on a new project.

I guess this should be a new issue.
31 sty 2015 01:49 "Stian Jørgensrud" <notifications@github.com> napisał(a):

**Comment by Sti2nd** [comment]
Could be, Unfa :+1: Could also just be a setting taken into consideration the resistance against pop up menus.

**Comment by tresf** [comment]
Closed via #2140
