### ISSUE TITLE
Cannot save templates

### ISSUE THREAD

**Issue by Sti2nd** [LMMS/lmms#1695]
Just tried to save a template several times, it saved as mmpz.

Steps to reproduce
- Do something with a project
- Go to save as
- "Save as template" in the dropdown menu
- Watch that the pop up box in the bottom left tells you that .mmpz has been saved, confirm it by browsing to the file.

**Comment by Sti2nd** [comment]
I found out that if you append .mpt to the file name in the save dialogue, it works. So the code when you select from the dropdown menu aren't successfully appending the file extension.

**Comment by tresf** [comment]
:+1:

**Comment by tresf** [comment]
:+1: 

Related: #386

**Comment by tresf** [comment]
Closed via #1709
