### ISSUE TITLE
user defined default-project

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#1702]
From forum:
http://lmms.io/forum/viewtopic.php?f=4&t=1621
so the user would like to set his own *default-project* -eg the *empty-project*
Looks like many users has access to same account (?) and that this is the reason for this request.

**Comment by grejppi** [comment]
LMMS uses the file `projects/templates/default.mpt` as the default template if it exists.

**Comment by musikBear** [comment]
and you already told the orr opp - super!

**Comment by tresf** [comment]
Still a bug IMO. :+1: hunting down `projects/templates/default.mpt` is not acceptable as a usability standard IMO. :)

**Comment by tresf** [comment]
Implementation will be tricky because many platform/distros can't write to `projects/templates/default.mpt` without admin.  We'll need to put some time into this one. :+1:

**Comment by Sti2nd** [comment]
Written here in the mean time https://lmms.io/documentation/Main_Menu_Bar

**Comment by grejppi** [comment]
It can be in the user directory too.

**Comment by tresf** [comment]
> It can be in the user directory too.

The default can?  Can you explain?

**Comment by tresf** [comment]
Nevermind, figured it out (thanks).  Yeah, we probably should create a `$LMMS_HOME/projects/templates/` folder there by default and consider making a copy of `default.mpt` so it is obvious.

**Comment by grejppi** [comment]
In fact it first looks at your home dir, then the factory projects dir. If neither exists it creates a new project from scratch.

**Comment by Sti2nd** [comment]
So this is partly related to https://github.com/LMMS/lmms/issues/1541 if you think about populating a user folder called templates with default.mpt.

**Comment by Sti2nd** [comment]
And I updated the wiki with user directory instead. Thanks grejppi!

**Comment by unfa** [comment]
I finally ogt this working, but I had to use

/usr/share/lmms/projects/templates/default.mpt

not

~/LMMS/projects/Templates/default.mpt

I find it sad that LMMS ignored the latter whatsoever, even though it shows files present there in the "New project from template" list.

**Comment by Sti2nd** [comment]
try changing to lowercase t

**Comment by tresf** [comment]
> try changing to lowercase t

It's clearly a typo.

> I find it sad that LMMS ignored the latter whatsoever, even though it shows files present there in the "New project from template" list.

@unfa Is this an order of operations thing?  Can you delete the one in `/usr/share/...` and get it working?

**Comment by tresf** [comment]
> In fact it first looks at your home dir, then the factory projects dir. If neither exists it creates a new project from scratch.

@unfa, @grejppi states this is not true.  Can either of you clarify?

**Comment by grejppi** [comment]
From [Song.cpp](https://github.com/LMMS/lmms/blob/b1a007b41b3f4b6a5561161d8305896e2a59b1a4/src/core/Song.cpp#L830):
```c++
void Song::createNewProject()
{
        QString default_template = ConfigManager::inst()->userProjectsDir()
                                                + "templates/default.mpt";

        if( QFile::exists( default_template ) )
        {
                createNewProjectFromTemplate( default_template );
                return;
        }

        default_template = ConfigManager::inst()->factoryProjectsDir()
                                                + "templates/default.mpt";

        if( QFile::exists( default_template ) )
        {
                createNewProjectFromTemplate( default_template );
                return;
        }
```

So yes, first home, then system directories.

**Comment by tresf** [comment]
> So yes, first home, then system directories.

@grejppi thanks kindly for investigating this... 

@unfa @musikBear can you confirm this?  I'd like to make sure we identify the problem properly.

I think making the directory is a good start.  Copying the template there perhaps an ideal scenario.

**Comment by Sti2nd** [comment]
> Copying the template there perhaps an ideal scenario.

Yes indeed, cause LMMS don't save any template in 1.1.0, only mmpz's https://github.com/LMMS/lmms/issues/1695

**Comment by badosu** [comment]
Wasn't this solved in master?

**Comment by curlymorphic** [comment]
yes #1695

**Comment by tresf** [comment]
> Wasn't this solved in master? /cc @curlymorphic

Yes, I was tempted to butt in and say something and decided not to... That's what I get... This is not related at all to #1695. 

This is more of an enhancement to the existing functionality.  Today we load templates from `user path` then `install path`.

The problem is, the `user path` (i.e. /home/lmms/templates) doesn't exist by default -- that means nor does the `default.mpt` file, so overriding the file is possible and works fine (according to @grejppi's review) but is not very intuitive.

A fix for this issue is to do a `mkdir` on the user's template directory and do a file copy of `default.mpt` as part of the home directory creation process.

**Comment by curlymorphic** [comment]
> A fix for this issue is to do a mkdir on the user's template directory and do a file copy of default.mpt as part of the home directory creation process.

sorry, totally miss understood this one. Im unsure if someones working on this, if not i will get it done

**Comment by tresf** [comment]
> sorry, totally miss understood this one. Im unsure if someones working on this, if not i will get it done

Great.  Nobody has started this one. I didn't even look for the code yet.  Thanks!

**Comment by curlymorphic** [comment]
We dont seem to have a default.mpt. I cant find a single copy on my machine. I have a few installs of lmms. Should I just make one, using our current new project?

**Comment by Sti2nd** [comment]
yes https://github.com/LMMS/lmms/issues/1541

**Comment by curlymorphic** [comment]
> yes #1541

cool, I can easy do that at the same time.

**Comment by tresf** [comment]
Related: #434
