### ISSUE TITLE
recording audio from Instrument tracks

### ISSUE THREAD

**Issue by Reaper10** [LMMS/lmms#1705]
After changing the sample track to audio track it be nice to be able to record audio from a Instrument track this would be great when collaborating with others when they don't have all of the same plugins.

**Comment by badosu** [comment]
Hi @Reaper10 thanks for submitting an issue.

Can you describe better what is your suggestion? It's hard to understand with the current description. What do you want? To export a single track to `wav`?

If this is the case we have a similar feature request where we would export designated mixer channels: see https://github.com/LMMS/lmms/issues/414. This would solve the problem in a more general way, without it being related to an instrument or sample.

**Comment by Reaper10** [comment]
Implement per-FX channel export sounds better
