### ISSUE TITLE
Failure to open a VST along with a project causes freezing/hanging.

### ISSUE THREAD

**Issue by TonyFtescht** [LMMS/lmms#1706]
Steps to reproduce:
1. Install Versilian Upright piano 1 VSTi (x64). That is a free of charge instrument available for download at [  http://vis.versilstudios.net/upright-1.html  ].
2. Create a new project in LMMS.
3. Create a track for a VeSTige host and open the instrument in it.
4. Put some notes on the track using the piano roll.
5. Save the project.
6. Optionally restart LMMS. Open the project.

Actual results: LMMS starts loading the project and gets stuck forever when it comes to load the instrument. The whole application becomes unresponsive leaving the only choice to kill its process using the task manager. This also makes the project file useless as there are no obvious ways to open it again, thus resulting in a loss of work.

Expected results: There are multiple ways to handle this situation. For sure, the interface must always be responsive. It would be a good idea to give each instrument/effect some reasonable time to load that once expired throws a question to user if they want to keep trying or load the project without the instrument.

**Comment by badosu** [comment]
This is a duplicate of #607 and #1008. Actually we should close one of those issues marking it as a duplicate of the other as well.

**Comment by badosu** [comment]
@TonyFtescht What's your OS?

**Comment by tresf** [comment]
@badosu I'm leaving them as separate for now since they reference different plugins and still require a bit of reproducing to confirm and consider duplicates.  Feel free to correct me if you feel this decision is in error.

**Comment by TonyFtescht** [comment]
Apologies about the duplicates. My system is Windows 7, 64 bit.

**Comment by TonyFtescht** [comment]
A temporary workaround is to move the culprit instrument somewhere. Then load the project. LMMS will figure the instrument is missing and load the project without it. Then the instrument can be moved back and reattached to the VeSTige host. A bit of a hassle though it helps.

**Comment by badosu** [comment]
@tonychee7000 
> Apologies about the duplicates. My system is Windows 7, 64 bit.

Don't worry, as @tresf pointed out: each of these VST cases may have different causes. I doubt it, but who knows? :-)

**Comment by musikBear** [comment]
doubt any daw can use *any and all* vst's, and that will also be the case for lmms. Vsts are just not always build to standard -There are kits that builds working vsts for fls, but the saved presets are just ..weird
I cant remember the char count in the save-string, but it is HUGE -absurdly huge 
BlueCat plugins has *that* issue, but i have seen others too

**Comment by Sti2nd** [comment]
> and gets stuck forever

Yes, sometimes forever, sometimes just a really long time.

**Comment by badosu** [comment]
@TonyFtescht Would you mind replacing "instrument" in favour of "VST" on this issue's title? Just to make it clear.

**Comment by tresf** [comment]
> This is a duplicate of #607 and #1008. 

Treating as such.  Closing, marking as duplicate.  Please reopen if you believe this was closed in error, or if you are able to reproduce with the latest 1.1.3 build from our [https://lmms.io/download](downloads page).

**Comment by TonyFtescht** [comment]
Works smoothly now. Thank you!
