### ISSUE TITLE
Move tracks between song editor / bb-editor

### ISSUE THREAD

**Issue by diizy** [LMMS/lmms#171]
This is a functionality I sometimes miss. I start making an instrument preset, fiddle with everything until I stumble to something awesome, then I find out it's something that works better as a bass/fx/perc instrument and it's on the song editor... and the only way to get it there is to save the preset and reload it there, but it'd be more convenient if you could just move it directly.

This could be implemented as an additional menu item on the trackoperations menu.

**Comment by badosu** [comment]
@tresf Can you help understand if there's still an issue here?

**Comment by serdnab** [comment]
> Sti2nd commented on 26 Jan 2014
> 
> IT DOESN'T WORK ENOUGH.
> 
> When dragging a drum pattern from B&B to Song Editor it places all your patterns at the beginning, and a maximum of 6 patterns.... It should place the patterns where the blue B&B pattern was, and correct number of patterns and correct length would be nice too.

Is that the desired behavior?
If it is, I start working on it.

**Comment by tresf** [comment]
@serdnab I'm having a hard time understanding @Sti2nd's test results, but if you understand what he's saying, go for it. :+1:

**Comment by serdnab** [comment]
The original issue reported by @diizy (more a new feature than a bug) is working, it's from Song Editor to BB Editor.
The point made by @Sti2nd is, conversely, from BB editor to Song Editor (again a new feature).
As I said before, I will be glad to implement it.

**Comment by serdnab** [comment]
I think this issue could be closed.
The original request made by @diizy is already implemented and working.
From what I understand from @Sti2nd, refers to another scenario (when you drag a track from BB editor to Song Editor, the reverse of what @dizzy is saying, that is from Song Editor to BB editor) and deserves another new feature issue.

**Comment by DeRobyJ** [comment]
I think the problem mentioned by @Sti2nd is similar to the MIDI export BBtrack problem: #2384 
That is: to transfer a track that was used in BB editor to the Song Editor and place its notes where the BB track was, probably using a pseudo-recording function.

**Comment by PhysSong** [comment]
I believe dragging from any of both sides works correctly since #4652.
