### ISSUE TITLE
LMMS could use track layers

### ISSUE THREAD

**Issue by Reaper10** [LMMS/lmms#1714]
LMMS could use track layers a lot of others have them they call them comping tracks. Ie a track within a track.

Pro Tools
![playlists 1](https://cloud.githubusercontent.com/assets/8137561/5946599/ac531d22-a6fc-11e4-91a3-f5909babfb3a.jpg)

Studio One
![presonus-studio-one-2-producer-364227 1](https://cloud.githubusercontent.com/assets/8137561/5946746/c95cadb0-a6fd-11e4-82fb-3448a1030517.jpg)

LMMS
![audio layer](https://cloud.githubusercontent.com/assets/8137561/5949079/f5eada66-a70f-11e4-9b86-37ef4ecdae09.png)
![midi layer](https://cloud.githubusercontent.com/assets/8137561/5949115/2fc3c626-a710-11e4-83e9-2f60f91bcabd.png)

To show or hide then that's in gear menu and so is make layer.

**Comment by Sti2nd** [comment]
Identical to https://github.com/LMMS/lmms/issues/735

**Comment by badosu** [comment]
@Sti2nd I am not sure if this is the same than #735

**Comment by Sti2nd** [comment]
Me neither, but that is the only sense I can make of this.

**Comment by curlymorphic** [comment]
It does sound the same to me.

**Comment by badosu** [comment]
Ok :-)
