### ISSUE TITLE
Lmms song editor slice clip tool

### ISSUE THREAD

**Issue by Reaper10** [LMMS/lmms#1715]
Lmms song editor slice clip tool that can cut one midi or audio into two.

**Comment by Sti2nd** [comment]
identical to https://github.com/LMMS/lmms/issues/746 , though the headline explicitly says Piano Roll, that is a tool that can and should be used in Song Editor as well.

**Comment by badosu** [comment]
@Sti2nd I guess he's referring to sample slicing, we have some discussion on it here: https://github.com/LMMS/lmms/issues/1471

@Reaper10 You can try using AudioFileProcessor, it can slice samples in a limited way.

**Comment by Reaper10** [comment]
like Piano Roll Razor/Glue Tool #746

**Comment by badosu** [comment]
Ok, so you can close this one as duplicate.

**Comment by Sti2nd** [comment]
> I guess he's referring to sample slicing

Ideally we should have one tool for slicing across the Editors and across different patterns?

**Comment by tresf** [comment]
> Ideally we should have one tool for slicing across the Editors and across different patterns?

I tend to agree.  We can reopen this at a later time.
