### ISSUE TITLE
Copying notes does not respect fine size adjustments

### ISSUE THREAD

**Issue by badosu** [LMMS/lmms#1720]
Disclaimer: By fine size adjustment I mean resizing the note while pressing alt and not using a size that's used on the current time signature.

Suppose you have a pattern of notes with some fine size adjustments, this is zoomed in at 800%, 4/4 time signature:

![2015-01-29-173822_406x108_scrot](https://cloud.githubusercontent.com/assets/347552/5964833/790c87d6-a7de-11e4-96ba-b0d759c70eab.png)

If you select them and Shift drag to copy, something weird will happen: the copy will be done correctly, but the original pattern is modified:

![2015-01-29-173839_389x106_scrot](https://cloud.githubusercontent.com/assets/347552/5964851/9db52c50-a7de-11e4-868f-c7ccaf380d14.png)

My bet is that when the pattern's last note is fine size adjusted it gets snapped to the grid again.

**Comment by tresf** [comment]
> My bet is that when the pattern's last note is fine size adjusted it gets snapped to the grid again.

Yeah I'd guess the same thing, a quantization honoring bug.
