### ISSUE TITLE
Project Version check when loading presets

### ISSUE THREAD

**Issue by badosu** [LMMS/lmms#1723]
There's a project version check going on when you preview a preset, after you click on it, a message box appears (notice the selected monstro preset):

![2015-01-30-110238_1920x1080_scrot](https://cloud.githubusercontent.com/assets/347552/5976031/45b0f696-a870-11e4-813d-e19cf128c286.png)

This is also preventing presets from being included as instruments by double click.

**Comment by tresf** [comment]
Caused by #1667.  @Spekular please fix.

-Tres

**Comment by Spekular** [comment]
@tresf oops. Will do.

**Comment by tresf** [comment]
> @Spekular please fix.

I was told by a respected colleague this may have come off as harsh.  So, pretty please with a :cherries: on top. :+1:

**Comment by Spekular** [comment]
@tresf I was wondering what I'd done to bother you ;P

**Comment by badosu** [comment]
@Spekular @tresf :laughing:
