### ISSUE TITLE
Timeline marker graphic glitch

### ISSUE THREAD

**Issue by badosu** [LMMS/lmms#1724]
See the image below:

![2015-01-30-162917_73x107_scrot](https://cloud.githubusercontent.com/assets/347552/5981048/d262ff76-a89d-11e4-8090-e6774463cff6.png)

The marker is always being hidden over the first track.

**Comment by Sti2nd** [comment]
Master I suppose

**Comment by badosu** [comment]
Yes, sorry. Does this happen on 1.1.0?

**Comment by Sti2nd** [comment]
No

**Comment by musikBear** [comment]
not on 1.1 win32
Linux anyone?

**Comment by badosu** [comment]
@musikBear This just happens on master.

**Comment by badosu** [comment]
Props to @curlymorphic :balloon:
