### ISSUE TITLE
LMMS needs default guis for vsts

### ISSUE THREAD

**Issue by Reaper10** [LMMS/lmms#1725]
LMMS needs default guis for because I have plugins with a lot of controls but there is no way to get to them.
Ie when I load them in a fx box there is no controls button to click on.  LMMS all so needs default gui for Instrument plugins.

**Comment by Spekular** [comment]
@Reaper10 instrument or fx plugins? You say instrumebts, but mention fx
boxes. Isn't this also the same as an earlier report?

**Comment by badosu** [comment]
I can't understand anything in this bug report.

**Comment by Umcaruje** [comment]
>I can't understand anything in this bug report.

@badosu you are not alone :)

@Reaper10 could you please be more clear in your issues?
