### ISSUE TITLE
Custom working directory not honored for recover.mmp

### ISSUE THREAD

**Issue by Umcaruje** [LMMS/lmms#1726]
So, I just tried out the master branch, and I get this error every 5 minutes:

![screenshot from 2015-01-30 21 38 42](https://cloud.githubusercontent.com/assets/6282045/5982911/868bbcde-a8c8-11e4-9b19-508d0da52a1c.png)

LMMS is trying to save the recover file to the default directory (which doesn't exist on my PC) rather than my defined user directory which is `/home/umcaruje/f/lmms`. I don't get the error on the `stable-1.1` branch.

**Comment by jack126guy** [comment]
I suspect this is related to 2e66c88edf33d571b15a3fc395772f0eb0f5a397. The recovery file path is set before the configuration is loaded.

**Comment by Umcaruje** [comment]
Can anyone reproduce this?

**Comment by tresf** [comment]
> Can anyone reproduce this?

I doubt you'll find that many people who've changed this value.  It must be rare because no one else has reported it since the change made in November.

We'll take your word for it. :)

-Tres

**Comment by tresf** [comment]
I'm assigning Lukas for now, since he made some considerable changes in this area, but I haven't done enough investigation to know for sure where the problem is.

@Umcaruje if you find anything else on this, please let us know.

**Comment by Lukas-W** [comment]
@Umcaruje 0a48b2f7bc3bce6eb88b02d6984029440b314582 should fix this. If not, please reopen. :)

**Comment by tresf** [comment]
:+1:

**Comment by Umcaruje** [comment]
Yup, this is fixed, thanks @Lukas-W :D
