### ISSUE TITLE
VST mda Detune: not able to show controls

### ISSUE THREAD

**Issue by Reaper10** [LMMS/lmms#1727]
LMMS needs default guis for because I have plugins with a lot of controls but there is no way to get to them.
 Ie when I load them in a fx box there is no controls button to click on
![capture 1](https://cloud.githubusercontent.com/assets/8137561/5985773/bbe08b9c-a8ac-11e4-97bb-0adc15eaceac.PNG)

![capture 2](https://cloud.githubusercontent.com/assets/8137561/5985786/ed405c76-a8ac-11e4-891c-72144cb4d058.PNG)

![capture3](https://cloud.githubusercontent.com/assets/8137561/5985794/0403941e-a8ad-11e4-8d58-7b9bb55b0430.PNG)

that's why LMMS needs default guis for fx vsts  when I use these in fl they use a needs default gui.
![capture](https://cloud.githubusercontent.com/assets/8137561/5986443/8771d1a2-a8bd-11e4-9ced-5dfb4625e96c.PNG)

**Comment by tresf** [comment]
You need to provide better bug reports.  This is three in a row that are bad and you've been warned at least 5 times before today.

If you cannot provide exact steps to reproduce the problem, we will close it out as invalid.

**Comment by badosu** [comment]
Please send us a screenshot, describe better the problem and do not open duplicate issues.

You can use the previous bug report you submitted, even if it was closed.

**Comment by Reaper10** [comment]
don't have a way to take a  screenshot....sorry:(

**Comment by badosu** [comment]
@tresf Please close this one, further discussion should be directed at #1727.

**Comment by badosu** [comment]
@Reaper10 If you are a novice at LMMS please try some tutorials before submitting bugs.

See:

- http://brycecoulson.com/lmms-tutorial-on-where-to-get-vst-instruments-or-effects-and-how-to-add-them/
- http://lmms.io/wiki/index.php?title=0.4:Working_with_VSTs

If you are stil unable to use them and think you have a bug, please describe better step by step what you're doing and what you expected to happen. Also, you'll have to learn how to take screenshots so that we can see what you're doing with detail.

**Comment by tresf** [comment]
> don't have a way to take a screenshot....sorry:(

Use the PrintScreen button and then paste it into this window.  It can't be much easier.

**Comment by Reaper10** [comment]
LMMS needs default guis for because I have plugins with a lot of controls but there is no way to get to them.
 Ie when I load them in a fx box there is no controls button to click on
![capture 1](https://cloud.githubusercontent.com/assets/8137561/5985773/bbe08b9c-a8ac-11e4-97bb-0adc15eaceac.PNG)

![capture 2](https://cloud.githubusercontent.com/assets/8137561/5985786/ed405c76-a8ac-11e4-891c-72144cb4d058.PNG)

![capture3](https://cloud.githubusercontent.com/assets/8137561/5985794/0403941e-a8ad-11e4-8d58-7b9bb55b0430.PNG)

**Comment by badosu** [comment]
Weird, I tested a lot of VSTs and `mda Detune` is the only one which presents this issue.

**Comment by badosu** [comment]
@Reaper10 Please replace your issue title with "VST mda Detune: not able to show controls"

**Comment by Reaper10** [comment]
it's more them just mda Detune that's just the one I tried.

**Comment by badosu** [comment]
> it's more them just mda Detune that's just the one I tried.

That's what I call bad luck.

**Comment by Reaper10** [comment]
that's why LMMS needs default guis for fx vsts

**Comment by tresf** [comment]
Perhaps it does, please do as asked. :+1:

**Comment by curlymorphic** [comment]
There is a simple reason for for this. The mda plugins dont have a user interface. They rely on the host to expose the controls for them, We do have this functionality but to access it you need to open the controls first (in this case we dont have that option)


![image](https://cloud.githubusercontent.com/assets/7412852/5987834/c43214ea-a939-11e4-9c20-eafb62270d6a.png)

I propose we move it here some how

![image](https://cloud.githubusercontent.com/assets/7412852/5987847/9ff0e29a-a93a-11e4-85f8-d503fe5b1e41.png)

We could place the spanner button here, but the ui is crowed already, or in the context menu, we would have to check that the effect is a vst first before presenting this option.

an alternative would be to open the vst effect gui window, with no context, showing the preset controls save and controls window button.

**Comment by curlymorphic** [comment]
> an alternative would be to open the vst effect gui window, with no context, showing the preset controls save and controls window button.

The more i think about it, the more i prefer this option, It covers the presets, and keeps continuity.

**Comment by musikBear** [comment]
just want to chime in with one rather important thing
*Showing* an GUI for MDAs would be a marvolous thing, but it is with no value, if the user made settings are not *saved*!
Almost all VSTs **effects** that i have tried in lmms, does *not* save their settings, so if the MDA collection actually caould get GUI, it is really important that they also are saved, and not just revert all controllers to default, or 0. or results in a hang during project-loading (#864) Both can happen.

**Comment by Sti2nd** [comment]
> Almost all VSTs effects that i have tried in lmms, does not save their settings

Almost all VST __effects__ that I have tried, saved their setting. It is VST intruments that I have problems with.

**Comment by badosu** [comment]
@curlymorphic Great investigation. This is hard, we need to figure out how to deal with these cases on the GUI...

**Comment by Reaper10** [comment]
there is more then mda Detune that need a default guis.

**Comment by tresf** [comment]
> there is more then mda Detune that need a default guis.

We know, stop bumping your own posts

**Comment by miketurn** [comment]
Just wondering if anyone has come up with a solution for this issue, and or is it still being considered?
I know there are alternatives to effects with no GUIs but it would be nice to use some of them if desired.
Couldn't a "dummy" effect window just be added so you can access the gear icon to show its controls?
