### ISSUE TITLE
LMMS needs default guis for Instrument  vsts

### ISSUE THREAD

**Issue by Reaper10** [LMMS/lmms#1728]
LMMS could use default gui for Instrument plugins that don't have a default gui .

**Comment by tresf** [comment]
Please clean this post up or it will be closed like the rest.  This is how it reads:

> Reaper10 needs better bug reports so we have better default bug reports.

**Comment by badosu** [comment]
This is the 3rd repeated issue, please stop doing that or else we'll have to block you: https://help.github.com/articles/blocking-a-user/.
