### ISSUE TITLE
Better Instrument picker

### ISSUE THREAD

**Issue by Reaper10** [LMMS/lmms#1729]
LMMS needs Better Instrument picker like the fx picker where it can see vst so you can open like lmms Instruments so you don't need the VeSTige. pluginin to open a vsti ie they open just like limms Instrument  .
![capture](https://cloud.githubusercontent.com/assets/8137561/5986514/f2866676-a8c0-11e4-8b62-fecf14f22640.PNG)

Chage the VeSTige plugin tab to key rage & preset manager and add env lfo tab and keep all other tabs like you have.

FL Studio
![capture](https://cloud.githubusercontent.com/assets/8137561/5986626/e94453c6-a8c4-11e4-8521-c097bce23697.PNG) 

![capture2](https://cloud.githubusercontent.com/assets/8137561/5986628/249d7308-a8c5-11e4-8079-a4bf836dde24.PNG)

you can keep the vst icon for tracks.

**Comment by tresf** [comment]
Just use the sidebar and drag the `V` icon in.  That is about as easy as it gets.

**Comment by tresf** [comment]
> Chage the VeSTige plugin tab to key rage & preset manager and add env lfo tab and keep all other tabs like you have.

That is what we have.  The stuff you crossed off is just space which all the plugins use.

**Comment by tresf** [comment]
Since VSTs install to various locations, AFAIK there's no easy way to simply import them all like we do for the FX plugins.  If you are aware of a centralized location, please enlighten us and reopen this bug report.

Thanks for the better details.  If we can keep the FLStudio screenshots to a minimum, that would be nice too.

**Comment by tresf** [comment]
Again, to add a vestige instrument, just browse your computer files on the left and drag in the `V` icon.  It should be much quicker than adding the VeSTige instrument every time. :+1:

**Comment by Reaper10** [comment]
Here is a better Instrument picker
![better instrument picker](https://cloud.githubusercontent.com/assets/8137561/6092769/7c92cdb2-aeb3-11e4-9fba-931f44a6cb34.PNG)

when you need to Search for a vst click Search .

Search Box
![search box](https://cloud.githubusercontent.com/assets/8137561/6092777/405fb228-aeb4-11e4-8202-0d9c8fd3e757.PNG)

If you do this you can have all Instrument plugins in one place, and it seams silly to me to have to load a plugin to load a plugin.

**Comment by Reaper10** [comment]
If you do this you can have all Instrument plugins in one place, and it seams silly to me to have to load a plugin to load a plugin.

**Comment by Sti2nd** [comment]
Ok, so you want to have your VST instruments listed like the VST effects and LADSPA effects, basically. Also a good idea :)

**Comment by Reaper10** [comment]
yeah

**Comment by tresf** [comment]
> Also a good idea :)

But again..  How do we populate this list?  The FX listing uses static locations.  VSTs can be located anywhere.

**Comment by Sti2nd** [comment]
They must be added manually, that was how I pictured it

**Comment by Reaper10** [comment]
But again.. How do we populate this list? The FX listing uses static locations. VST instruments can be located anywhere. 
that why there  this a Search .
 It seams silly to me to have to load a plugin to load a plugin.

**Comment by tresf** [comment]
> It seams silly to me to have to load a plugin to load a plugin.

Agreed which is why we allow the drag-and-drop addition of VSTs and SF2S in 1.1 and higher.  This can be done via sidebar file browser.  This was already explained 8 days ago in my previous comment.    Do you need help using this feature?
