### ISSUE TITLE
Exported file has incorrect length

### ISSUE THREAD

**Issue by ShurikMur** [LMMS/lmms#1733]
V 1.1.0, win 32

The length of exported sound file = length from 0 to the end of last part in a song editor, even if the last part(s) is muted and do not renders into actual sound.

**Comment by tresf** [comment]
Related #1688 (closed)

---

I'll copy/paste my findings from previously:

I don't see anything hard-coded to use the song length versus the rendered length... 

Export is the same as playing except the flag `m_exporting` is set to true per [`Song.cpp#L643`](https://github.com/LMMS/lmms/blob/master/src/core/Song.cpp#L643) and written via [`AudioFileDevice::writeDate(...)`](https://github.com/LMMS/lmms/blob/master/src/core/audio/AudioFileDevice.cpp#L78) interface.

This is the only place I see the song length calculated:
[`ProjectRenderer.cpp#L169`](https://github.com/LMMS/lmms/blob/master/src/core/ProjectRenderer.cpp#L169)

But the rendering doesn't see to even use that value, it is initialized via [`ProjectRenderer.cpp#L82`](https://github.com/LMMS/lmms/blob/master/src/core/ProjectRenderer.cpp#L82) and just processes until done from what I can see in [`Song::processNextBuffer()`](https://github.com/LMMS/lmms/blob/master/src/core/Song.cpp#L198) (right?)

**Comment by zonkmachine** [comment]
I had a go at fixing this in #3390 .
