### ISSUE TITLE
AudioFileProcessor Pitch Bend

### ISSUE THREAD

**Issue by thore00** [LMMS/lmms#1734]
I don't really know where to post this, this is the original post:
https://lmms.io/forum/viewtopic.php?f=15&t=1601

Anyway,
Pitch bend in AudioFileProcessor without changing the speed of the clip, similar to a feature you can find in Audacity.

Tell me if I should move this issue!

**Comment by badosu** [comment]
This would be really an amazing improvement!

**Comment by Umcaruje** [comment]
+1 I'd really look forward to this.

**Comment by Sti2nd** [comment]
Librubberband anyone? https://github.com/LMMS/lmms/issues/495

**Comment by tresf** [comment]
@Sti2nd I was wondering where I'd seen this.... Good find.  P.S. you should really quote Paul when quoting Paul. :)

**Comment by Sti2nd** [comment]
> you should really quote Paul when quoting Paul. :)

indeed!

**Comment by tresf** [comment]
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.
