### ISSUE TITLE
LMMS crashing, vst related prob.

### ISSUE THREAD

**Issue by Gps2010** [LMMS/lmms#1736]
Hi guys.

tresf advised me to start a bug report on this.
LMMS is working but its unstable, when I use vst's on openSUSE 13.1 64 bit.

I compiled as you guys prob already know, lmms my self.
When I have a problem on linux, I always start programs from the command line, to see if there is some use full info.

I got rit of one message as you can see in the topic on the lmms forum. 
 http://lmms.io/forum/viewtopic.php?f=7&t=1640&p=7200#p7189

The problem is, lmms crashing with a segmentation error.

From what I found out and what tresf explained to me, its shared memory related.
I was pointed to this issue:  https://github.com/LMMS/lmms/issues/1468

What I found from looking around the net, was this convo, between a wine dev and a lmms dev (toby) 

https://bugs.winehq.org/show_bug.cgi?id=35347

Because at the end it says closed and fixed, I tried to install a newer wine version.
But that broke the vst all together. On the start of lmms it complained it could not load the vst.
When I reverted back to the wine version I was using before, they worked again, but still there is this message when I start lmms.

guus@linux-n62z:~> target/bin/lmms
bash: target/bin/lmms: No such file or directory
guus@linux-n62z:~> cd lmms
guus@linux-n62z:~/lmms> target/bin/lmms
Notice: could not set realtime priority.
VST sync support disabled in your configuration
RemotePluginClient::shmget: No such file or directory
RemoteVstPlugin.cpp::shmget: No such file or directory
RemoteVstPlugin.cpp: Failed to initialize shared memory for VST synchronization.
 (VST-host synchronization will be disabled)

( here I open a project which uses vst )  

unique ID: SMAC
RemotePlugin::DebugMessage: inputs: 0  output: 2
RemotePlugin::DebugMessage: creating editor
RemotePlugin::DebugMessage: editor successfully created
RemotePlugin::DebugMessage: failed getting shared memory
RemotePluginClient::shmget: No such file or directory
RemoteVstPlugin.cpp::shmget: No such file or directory
RemoteVstPlugin.cpp: Failed to initialize shared memory for VST synchronization.
 (VST-host synchronization will be disabled)
unique ID: SMAC
RemotePlugin::DebugMessage: inputs: 0  output: 2
RemotePlugin::DebugMessage: creating editor
RemotePlugin::DebugMessage: editor successfully created
RemotePlugin::DebugMessage: failed getting shared memory
RemotePluginClient::shmget: No such file or directory
RemoteVstPlugin.cpp::shmget: No such file or directory
RemoteVstPlugin.cpp: Failed to initialize shared memory for VST synchronization.
 (VST-host synchronization will be disabled)
unique ID: SMAC
RemotePlugin::DebugMessage: inputs: 0  output: 2
RemotePlugin::DebugMessage: creating editor
RemotePlugin::DebugMessage: editor successfully created
RemotePlugin::DebugMessage: failed getting shared memory

The vst do work though, but lmms becomes unstable, saving a lot keeps me from loosing much.

I will keep looking for a solution myself, but I fear I am in over my head on that. 
If you guys want more info or want me to run some commands just ask.

I wonder if I ( we? ) should talk to the wine devs ?

used wine version, with which the vst do work: 1.7.2

**Comment by tresf** [comment]
Since most our tutorials are written for Debian flavors, can you outline the commands you used to meet the build dependencies on that platform (from your command history perhaps?)

These command will simplify it for someone to install openSUSE 13.1 x64 and reproduce the issue you are experiencing.

I also assume you've tried with multiple known-good VSTs?

P.S. My comments on the forum in regards to sharedmemory were meant to be more broadly read as my investigation/trial and error, and also my lack of knowledge on the topic.  It was not meant to be suggestive as to the cause of your crash. :+1:

**Comment by Gps2010** [comment]
I used the package manager to install the stuff I needed, by just copy pasting, the list from the compile wiki into yast. ( one by one of course) and then selected the devel files too.

I will do some testing with other vst, and I installed gdb, but that gives me an enormous list of debug packages I seem to be missing. A lot about ladspa. I don't have an issue with ladspa so I asume I dont need these, 

Can you maybe point me to the debug package I do need for this ?

When I start lmms, the default project opens without vst, but already it says:

Notice: could not set realtime priority.
VST sync support disabled in your configuration

(still it works though)
I will have a look if I can find some yast history file.
But if there is one, I fear it will be a hudge list, but maybe we can do some filtering by date.

**Comment by Gps2010** [comment]
I just did some testing with synth 1, and lmms did boom.
Maybe important to mention, the gui of synth 1 was still showing, but lmms was gone.

I also posted on the openSUSE forum. If some one can confirm this issue on openSUSE.
I am not in a hurry, but 43 views, and zero replies.

I start to wonder if I am the only lmms users on openSUSE. That could explain, why the packman version has issues. If nobody tells packman its not working right, they wont change it.

The last time I installed lmms through the official repo ( thats packman for openSUSE, if you want a newer version) midi recording did not work.

I might also give jack audio a try, to see if that changes anything.
I already have it installed, but have only tried alsa and pulse yet.

I am also gonna install the wine debugging tools.

**Comment by Gps2010** [comment]
Maybe this is of interest? 
http://ubuntuforums.org/showthread.php?t=1414174

I tried running sudo ldconfig
which seemed to work, but changed nothing

**Comment by Gps2010** [comment]
I tried to make a list of installed libs and devel files, as I promised.
I did not copy paste blindly the out put from the command line. (rpm -qa --last | less )
But still the list is quite long. 

I cant seem to attach an odt file though ? 

I remember uploading data to the github when beta testing steam.
Lets see if I can remember how. ;)

**Comment by Gps2010** [comment]
I am gonna reinstall lmms again, with some feedback from the openSUSE forum.
I now have everything under a default target directory, created by cmake.
That not the place were openSUSE normally installs stuff. 
Lets see if that get rit of the smhget message.

**Comment by tresf** [comment]
> Edit: I think I got it.
https://gist.github.com/Gps2010/b9f07c27c430d5ad50a2

Thanks.  That list is quite long so I'll likely just search the yast database for the compile dependencies manually.

> I am gonna reinstall lmms again, with some feedback from the openSUSE forum.

Ok, I'll wait for feedback before attempting this myself.  We love to hear LMMS running on other platforms so please keep us posted and let me know if you want someone like myself to reproduce.  I'd be happy to setup a PC to help troubleshoot this.

**Comment by Gps2010** [comment]
Off topic:
Well just an observation from my site, about Ubuntu and steam(beta) on Linux.
Steam will work on one version of Ubuntu but not on another without issues. 
If there is a solution for Arch it works for openSUSE and Fedora too.
According to a an openSUSE friend, ubuntu even has arguments met debian devs.
They seemed to do things their way, and in general ignoring some rules, to which a lot of the other distro's do listen. Its not all bad though, I have fixed openSUSE issues with Ubuntu solutions too.

On topic, I will keep you guys informed on any progress or regress. :P 
Further more I was confusing two messages. The first message about a real time kernel has, nothing to do with the message about smhget.
I am not using a real time kernel, so its nothing special lmms points this out.
Years ago there was an openSUSE version for music production. The only real difference was a real time kernel. That project has stopped though, and it seems real time kernels are becoming something of the past.

**Comment by badosu** [comment]
@Gps2010 Just about your off-topic discussion on how RT Kernel tuning is uncommon these days, it's related with this change if I am not mistaken: http://kernelnewbies.org/Linux_2_6_38#head-59575a6aeafa38490226a560ee02de89829a5b20

See this video at 4:40 for a nice explanation: https://www.youtube.com/watch?feature=player_detailpage&v=Kbjmlbehh8M#t=280

**Comment by Gps2010** [comment]
Thank you, I am not gonna pretend I understand what is written, on the commit pages though.

The vid I did understand enough to know, I should be fine, with the kernel I am using.
3.11.6

**Comment by Gps2010** [comment]
Because I am a bit superstition, I am almost afraid to tell you guys this. ;) 

Today installed lmms the easy way, to see if that version also gives the shmget message and it does.
Futher more midi recording does not work. ( I will email packman about this)

But......
Yesterday openSUSE wanted to update, but complained about 4 debug packages I had installed.
Today I opened yast to see if I could fix this.
Updating through yast, instead of automatic updating has the advantage, you can see why it wont update, and or change things.

I decided to let yast remove these 4 packages, and let it update openSUSE.
After this update, and the removal of these packages, lmms refuses to crash.

I am still in shock. I was messing with midi input and synth one for over 2 hours.
no crash.
At this moment I have lmms open, skype open, and two web browsers. ( chrome and firefox)
Before today, this was enough, although I was not using lmms, to have it crash. 

So the update prob fixed something. ( newer lib version, or something like that)

Don't get me wrong, I had lmms crashing when it was the only program running, other wise I would not be posting here.
But now LMMS (openSUSE,  linux) seems to be as rock stable as I am used too.
I hope this wont be continued.

**Comment by Gps2010** [comment]
Thinking about my previous reply, I hope not to confuse anybody, but I have at the moment, two version of lmms installed.
The one I build myself, which is working fine, and one from the openSUSE repositories, which has issues.

**Comment by Gps2010** [comment]
The libs that got updated:
#### YaST2 conflicts list - generated 2015-02-05 15:49:54 ####

patch:openSUSE-2013-981-1.noarch conflicts with glibc-debuginfo-32bit.x86_64 < 2.18-4.7.1 provided by glibc-debuginfo-32bit-2.18-4.4.1.x86_64

patch:openSUSE-2014-25-1.noarch conflicts with glibc-debuginfo.x86_64 < 2.18-4.11.1 provided by glibc-debuginfo-2.18-4.4.1.x86_64

patch:openSUSE-2014-79-1.noarch conflicts with libqt4-debuginfo.x86_64 < 4.8.5-5.9.2 provided by libqt4-debuginfo-4.8.5-5.6.1.x86_64

patch:openSUSE-2014-569-1.noarch conflicts with libqt4-debuginfo-32bit.x86_64 < 4.8.5-5.13.1 provided by libqt4-debuginfo-32bit-4.8.5-5.6.1.x86_64

**Comment by Sti2nd** [comment]
LMMS uses qt4, and there my knowledge stops

**Comment by Gps2010** [comment]
Yeah I am pretty sure I installed those qt4 debug files, because of the issues I had, and this webpage:
https://lmms.io/wiki/index.php?title=Troubleshooting

Which states: Use the GNU Debugger:
When I started that program the first time, it complained about not being able to find a lot of debug files, so I installed some.

But how I understand, what happened with that update, it wanted to updated qt4, but for some reason could not update those debug files, so yast offered to remove them.
At first I was like, omg qt4, this is gonna break lmms, but then calmed down, and saw it were debug files, not the actual libs.

**Comment by tresf** [comment]
> So the update prob fixed something. ( newer lib version, or something like that)
> [...] now LMMS (openSUSE, linux) seems to be as rock stable as I am used too.
> I hope this wont be continued.

Thanks for the update.  If you find out more, please feel free to post it here.  Closing the support request as resolved.

**Comment by Gps2010** [comment]
I will, but to me its clear that either qt-32bit-4.8.5-5.6.1.x86_64 /  libqt4-4.8.5-5.6.1.x86_64 lib, and or glibc-2.18-4.4.1.x86_64 / glibc-32bit-2.18-4.4.1.x86_64 lib, were not playing nice with other libs on openSUSE. But I don't want to put time and effort into something that's fixed.
Yesterday created a piece with 4 synth1 tracks, and only had lmms crash ones.
One crash in about 4-5 hours, with a lot of other programs open too.  :) 

Its not something I can reproduce, but sometimes when I drag things, and the keyword here is sometimes, lmms goes boom. ( also when not using vst's  )

To other openSUSE lmms users, check out the obs. Add a link from there, as a repository in yast.
( If you don't know how, just ask on the openSUSE forum  https://forums.opensuse.org/forum.php )

https://build.opensuse.org/search
