### ISSUE TITLE
Better AFP reverse button performance during playback

### ISSUE THREAD

**Issue by Reaper10** [LMMS/lmms#1739]
I tried to automate the reversing button on/off on the AFP and LMMS crashed when I to play the song.
step1
![capture2](https://cloud.githubusercontent.com/assets/8137561/6053322/9a9a24c0-aca3-11e4-88a8-477c53debf8c.PNG)

step2
![capture3](https://cloud.githubusercontent.com/assets/8137561/6053395/6a3ce9b0-aca4-11e4-8f6b-a25c830c1082.PNG)

step3
![capture4](https://cloud.githubusercontent.com/assets/8137561/6053413/940f2e42-aca4-11e4-96a6-71320856c47e.PNG)

when LMMS tries to do, do it froze.

**Comment by tresf** [comment]
Thanks for the bug report.  Please fix your title to reflect the actual bug and provide detailed steps to reproduce. :+1:

**Comment by badosu** [comment]
@Reaper10 Also, if you are able to send a screenshot like you did in the prevous one, that wiould help a lot.

**Comment by Reaper10** [comment]
I'll work on a list of steps to reproduce.
Is the title better?

**Comment by badosu** [comment]
We still need to understand what exactly is happening with you, but it is more clear now.

**Comment by Reaper10** [comment]
step1
![capture1](https://cloud.githubusercontent.com/assets/8137561/6053342/bf26d946-aca3-11e4-8abd-8c8305fd9a0b.PNG)

step2
![capture2](https://cloud.githubusercontent.com/assets/8137561/6053322/9a9a24c0-aca3-11e4-88a8-477c53debf8c.PNG)

step3
![capture3](https://cloud.githubusercontent.com/assets/8137561/6053395/6a3ce9b0-aca4-11e4-8f6b-a25c830c1082.PNG)

step4
![capture4](https://cloud.githubusercontent.com/assets/8137561/6053413/940f2e42-aca4-11e4-96a6-71320856c47e.PNG)

when LMMS tries to do, do it froze.

**Comment by tresf** [comment]
Thanks :+1:

**Comment by tresf** [comment]
Just tried to reproduce this... no crash... Can you provide a sample track for us to reproduce this on?


![screen shot 2015-02-06 at 6 46 52 pm](https://cloud.githubusercontent.com/assets/6345473/6089436/96df2388-ae30-11e4-8447-9aebc8eaf1f9.png)

**Comment by Reaper10** [comment]
how do I that/

**Comment by tresf** [comment]
Save as `.mmp` extension, upload to gist, paste link here.

**Comment by Reaper10** [comment]
can't feger out how to upload

**Comment by tresf** [comment]
Upload to gist.  Then link.

**Comment by Reaper10** [comment]
how do I Upload a jzip file to gist with the mmp and the sample in it..
I'm stupid

**Comment by tresf** [comment]
Oh... Can you reproduce with a stock wav/ogg file?  If not, you may need to host the project on something like Dropbox, google drive, etc.

**Comment by Reaper10** [comment]
https://drive.google.com/file/d/0B0Ar66xX6aiReGhfaFNja3k2WkE/view?usp=sharing

**Comment by Reaper10** [comment]
hope that helps:)

**Comment by tresf** [comment]
Thanks.  This hangs the software for about 1 second each time it switches, but doesn't crash it.  Seems like large samples are quite timely to reverse which is likely causing this delay.

![screen shot 2015-02-07 at 2 24 15 pm](https://cloud.githubusercontent.com/assets/6345473/6093631/1a08666c-aed5-11e4-9d79-7bebf232df6e.png)

**Comment by tresf** [comment]
I don't consider this a 1.2 milestone unless we can get confirmation of an actual crash.  This is really a nice-to-have enhancement in my opinion.

**Comment by Sti2nd** [comment]
> This is really a nice-to-have enhancement in my opinion.

Doing it live is ambitious. Would require a really strong machine. I think I have heard that one usually render out the changes? Maybe Audacity can help us

**Comment by Reaper10** [comment]
fl can do it live.

**Comment by Sti2nd** [comment]
Live and precomputed https://answers.yahoo.com/question/index?qid=20091029071012AAS7lhe

**Comment by tresf** [comment]
> fl can do it live it's slow.

Please stop comparing LMMS to commercial software.

**Comment by Reaper10** [comment]
Sorry it's only other music software I know.

**Comment by musikBear** [comment]
just a tiny input
this could be achived with two wave-tracks, one reversed, and alternated automation of *mute-this-track* in both tracks..

**Comment by diizy** [comment]
I think the problem is that we're reloading the sample every time it's reversed, and in cases where the samplerate of the sample != playback samplerate, this means also resampling the sample every time.

A good solution would be going to Samplebuffer.c, and adding the ability to play buffers in reverse, so the reversing can be done on-the-fly. Playing in reverse that way shouldn't be any more cpu-consuming than playing forwards, after all it's just a matter of reversing some indices and counters...

Then, the actual samplebuffer wouldn't have to be reversed and reloaded, it could just be played forwards/backwards.

**Comment by Sti2nd** [comment]
Wow, I would never though about that. Sounds genious

**Comment by badosu** [comment]
This can be my opportunity to tinker with some sound processing code, I'll take a look at it.

**Comment by sakertooth** [comment]
> I think the problem is that we're reloading the sample every time it's reversed, and in cases where the samplerate of the sample != playback samplerate, this means also resampling the sample every time.
> 
> A good solution would be going to Samplebuffer.c, and adding the ability to play buffers in reverse, so the reversing can be done on-the-fly. Playing in reverse that way shouldn't be any more cpu-consuming than playing forwards, after all it's just a matter of reversing some indices and counters...
> 
> Then, the actual samplebuffer wouldn't have to be reversed and reloaded, it could just be played forwards/backwards.

This is exactly what I had done in #6610. Instead of actually reversing the entire buffer in memory with ``std::reverse``, it is now simply played forwards and backwards, which should've been the default behavior from the start.
