### ISSUE TITLE
The split keyboard plugin and split keyboard track GUI

### ISSUE THREAD

**Issue by Reaper10** [LMMS/lmms#1743]
In #1381 curlymorphic was not sure what to do to implement this from a GUI perspective, so I stopped and thought about it.  Then I saw the mockups for Group Tracks thanks StakeoutPunch & Spekular. 

Right Click on the Layer Keyboard track to rename the layer.

The only Tracks that can be in the Keyboard Layer track are Automation tracks and Instrument tracks and other Keyboard Layer tracks.

Full Layer Keyboard Track
![full layer keyboard track](https://cloud.githubusercontent.com/assets/8137561/6082791/7abbf52e-ade9-11e4-91ff-b38b550e4261.png)

Click on the Layer Keyboard track to open the Layer Keyboard plugin.  Clicking on the show layers button will show layer parts the hide layer will fold up the layer.

Showen Keyboard Layer Parts
![showen keyboard layer parts](https://cloud.githubusercontent.com/assets/8137561/6083156/3adcb440-adec-11e4-8ef6-165352981157.png)

The info screen shows you  the  Instrument tracks and other Keyboard Layer tracks in the  Keyboard Layer you have pulled up, the key range of the Instrument and the FX channel the Instrument is on now.  You can all so seartch for a Instrument in the layer with the seartch  box.
Info Screen
![info screen](https://cloud.githubusercontent.com/assets/8137561/6082866/fafc0a08-ade9-11e4-9dca-40df8c16fc07.PNG)

The Layer Keyboard plugin and the Layer Keyboard track can all so be used in the beat and bassline editor.

How to setup

1 Set the key range with the key range tab on the Instrument plugin.
The reason for it to be this way is so you can connect the buttons and knobs to your hardwair keyboard.
Key Mapping Tab
![key mapping tab](https://cloud.githubusercontent.com/assets/8137561/6082657/acc3e500-ade8-11e4-926e-cf76c3fa6129.png)

2 Make a layer keyboard track.
Empty Layer Keyboard Track
![empty layer keyboard track](https://cloud.githubusercontent.com/assets/8137561/6082727/17d7cdf2-ade9-11e4-8835-495b4ad9bd42.png)

Layer Keyboard Track Icon
![layer keyboard track icon](https://cloud.githubusercontent.com/assets/8137561/6082897/3815cf28-adea-11e4-937c-40ab2c5fd4b0.png)

3 Go to the gear menu and click select this track for layering.

4 Open the layer keyboard plugin and click the set layer button.
Keyboard Layer Plugin
![keyboard layer plugin](https://cloud.githubusercontent.com/assets/8137561/6082952/d4b1b54a-adea-11e4-8e4d-d6ce34d2a9b1.png)
![layble](https://cloud.githubusercontent.com/assets/8137561/6082963/eaa26e80-adea-11e4-8c06-6c582b9a8821.png)

Your Done

To remove a part from the layer keyboard track, go to the Instrument track in the layer, go to the gear menu of and click remove this track from the layer.

**Comment by Sti2nd** [comment]
Thanks for all the mock ups, but as I read the other issue they found a way to implement this through the GUI

> On 12/03/2014 12:41 PM, Raine M. Ekman wrote:
 IMO the range should be simple enough to set by clicking above the
 keyboard, like the root note already is.

And the reason the issue was closed was because it was moved here. https://github.com/LMMS/lmms/issues/1472

**Comment by Reaper10** [comment]
what the track mock?

**Comment by Reaper10** [comment]
Better MIDI support #1472

**Comment by Reaper10** [comment]
what the track mocks?

**Comment by tresf** [comment]
@Reaper10, I've linked to #1472.  This can stay closed to simplify our tracker, but it will remain as a reference point in the other thread.  Please close it back out at your leisure.

**Comment by Reaper10** [comment]
In the Info Screen you can change the FX # and name of a Instrument. If you want to save a layer keyboard setup you should be able save is a preset file.

**Comment by Reaper10** [comment]
I've been thinking this maybe be better as a new track type and not a plugin, what do you think?

**Comment by tresf** [comment]
This has been partially implemented via https://github.com/LMMS/lmms/pull/2185.

From an instrument perspective, semi-related (note based rather than range based). https://github.com/LMMS/lmms/issues/1460

**Comment by Reaper10** [comment]
The assignable controller tab
<img width="481" alt="untitled" src="https://cloud.githubusercontent.com/assets/8137561/10270124/4ed34020-6aae-11e5-947a-e887e161be16.png">
The assignable controller tab it's like the macros of live, ie a user has no limit to how many assignments a user can make to the buttons or knobs as needed. The macro buttons and knobs can assigned to a hardware controller. The user can add as many macro pages as needed.

To assign a right click it when a it's part of the split keyboard track. then click the ready to assign option. Then go to the knob or button you want to assign  the controller to.

To unassign a controll right click it when a it's part of the split keyboard track. then click the unassign option . Then go to the knob or button you want to unassign  the controller right click the macro knob or button then click the unassign option.
what do you think about this?

**Comment by Reaper10** [comment]
The more I think about it I think this is best as a new track type. when the New UI Concept - Single Window #1911 is implemented I think the best GUI is something like live's instrument rack.

**Comment by tresf** [comment]
> when the New UI Concept - Single Window #1911 is implemented

What does that have to do with this request?

> I think the best GUI for instrument split keyboard track is something like live's instrument rack.

"Live" as in Ableton Live?  Agreed, their drum machine and instrument racks fit this need perfectly IMO, but this is still saying closed.

**Comment by Reaper10** [comment]
I know it's a part of Better MIDI support #1472, I was just trying update the  UI Concept.

**Comment by Reaper10** [comment]
The knob info tab is like midi assign tab of ableton live.

**Comment by tresf** [comment]
Just edit your posts and move on please.  No need to bump your own posts each time you get an idea.
