### ISSUE TITLE
Remove "(bad latency!)" warning from PulseAudio interface option

### ISSUE THREAD

**Issue by pbella** [LMMS/lmms#1749]
As others have reported, this warning is misleading on at least some widely used Linux distros.  In fact, without JACK installed, it is the only option that 'just works' by default on my systems with Debian 7 & 8.

![screenshot from 2015-02-07 14 40 16](https://cloud.githubusercontent.com/assets/1817202/6093684/4122036e-aed7-11e4-973a-9c171c2900c7.png)

Arguments pro/con about PulseAudio aside, it is the default reality on most distros these days and this warning may cause confusion for those it does work for.

**Comment by tresf** [comment]
I agree... Other back ends can have problems too in certain configurations and we don't warn against those...

**Comment by badosu** [comment]
I don't like this warning, but Pulseaudio is not exactly still a good choice.

I find that using PulseAudio as backend is the source of most complaints of garbled sound after some kind of trigger is activated.

**Comment by pbella** [comment]
@badosu I don't disagree: pulse has its problems.  However, it does seem to be the most usable default option for some number of users and don't underestimate the importance of having something that works with the users existing configuration.  They'll switch to something else (JACK, in my case) if LMMS hooks them and they hit the limits of what PA can do for them.  As @tresf said, every back end will have problems in specific situations...

**Comment by tresf** [comment]
> I find that using PulseAudio as backend is the source of most complaints of garbled sound after some kind of trigger is activated.

Perhaps on Linux this is true.  When Windows users complain it tends to be caused by **Port**Audio in my experiences.

As far a Linux performance with PulseAudio, when I did my testing on Ubuntu 14.04 32-bit, I observed comparable performance on PulseAudio as I did on SDL and it was completely usable.

Reverting this change will be some work.  We have translation files which reference it and we also will break old projects because this "Bad Latency" is actually stored as part of the `.mmpz` file.

I'm working on a patch now.  I'll link the PR when it is ready for review.

**Comment by diizy** [comment]
Pulseaudio is not available on windows so it's a moot point... 

I'm not really sure what it would accomplish to remove the warning? As long as pulseaudio keeps sucking, we should probably keep recommending people not to use it...

**Comment by tresf** [comment]
> I'm not really sure what it would accomplish to remove the warning? As long as pulseaudio keeps sucking, we should probably keep recommending people not to use it...

As many have illustrated it doesn't always suck.  This is just a cleanup effort.  Storing that text in the project file is bad design.  If we want to explain the backends in the settings dialog, we should decide a better way to do it.

**Comment by tresf** [comment]
> Pulseaudio is not available on windows so it's a moot point...

I don't think it is a moot point because his statement used the term "source of most complaints".  I think we can all agree that the most complains don't come from Linux.

-Tres

**Comment by Sti2nd** [comment]
> Storing that text in the project file is bad design.

Are there other cases like this? One should perhaps look through the mmp and see what kind of information should not be there for LMMS 2.0

**Comment by tresf** [comment]
> One should perhaps look through the mmp and see what kind of information should not be there for LMMS 2.0

Easier said then done, but yes, there are likely other locations that should be cleaned up.

I have the logic working but the problem I'm seeing right now is we have no `upgrade()` function for our settings file from what I can see...

```cpp
	// Remove trailing " (bad latency!)" strings which were once saved in configurations for PulseAudio
	if( version < "1.1.89" )
	{
		QDomNodeList list = elementsByTagName( "mixer" );
		for( int i = 0; !list.item( i ).isNull(); ++i )
		{
			QDomElement el = list.item( i ).toElement();
			QString s = el.attribute( "audiodev" );
			if( s.startsWith( "PulseAudio (" ) )
			{
				el.setAttribute( "audiodev", "PulseAudio" );
			}
		}
	}
```

The `upgrade()` function really was designed to apply to projects and presets, not the settings.  That means this compat code above has no home currently.

**Comment by tresf** [comment]
@Sti2nd sorry, I mispoke when I said "project file", this is stored in the settings file.

**Comment by Sti2nd** [comment]
Oh yeah, cause project file sounded really weird, lol.

**Comment by tresf** [comment]
I created a pull request for this here: #1751. If someone can take a look and review, please do. :+1: 

-Tres
