### ISSUE TITLE
X-Y Pad Delay GUI

### ISSUE THREAD

**Issue by Reaper10** [LMMS/lmms#1752]
I don't know how to make a plugin but I have a idea for one so can someone make it? It's a XY Pad Delay for LMMS.

mockup
![xy pad](https://cloud.githubusercontent.com/assets/8137561/6110544/10fd8998-b048-11e4-99b8-d0390b53345b.png)

**Comment by tresf** [comment]
We have many LADSPA controls with no easy way to programatically wrap a GUI around them.  Thanks for the request.  I'll let those more capable of creating FX plugins chime in here, but I think what you are requesting is possible and within a reasonable amount of effort. :+1:

**Comment by curlymorphic** [comment]
I can have a look at this, Its basically another ui for the current delay plugin.

**Comment by pbella** [comment]
Would it make more sense to get LV2 plugins working (complete with vastly improved GUI) than putting more effort into LV1 plugins?

**Comment by Umcaruje** [comment]
>Would it make more sense to get LV2 plugins working (complete with vastly improved GUI) than putting more effort into LV1 plugins?

But this would not be a LADSPA plugin, it would be a default LMMS plugin

**Comment by pbella** [comment]
OK... I misunderstood based on @tresf comment

**Comment by Reaper10** [comment]
it would be a new plugin.

**Comment by curlymorphic** [comment]
I think this would be best implemented, buy upgrading the gui of the current delay plugin. As there are no new parameters introduced by this, there will be backward compatibility. Another delay plugin would just bring more code to maintain.

**Comment by Reaper10** [comment]
ok I just want add to the plugins you all ready have

**Comment by curlymorphic** [comment]
I have just made a pull request for this 

![image](https://cloud.githubusercontent.com/assets/7412852/6128408/6e693e8e-b12d-11e4-9341-72790fd2816c.png)

**Comment by tresf** [comment]
> I have just made a pull request for this #1754

:tada: 

Terrific!  Can we create a preset with the old `Delay` plugin and test against the new `Delay` plugin to make sure the `m_outGainModel` starts with a sane value? (I assume this would work fine, but worth testing)

**Comment by tresf** [comment]
> "- Tested for backward compatibility."

Whoops.  Should have read the PR.  Looks like you have have this covered as well.

**Comment by curlymorphic** [comment]
Tested both presets and old project files, it defaults to unity gain, so the sound is unchanged.

**Comment by tresf** [comment]
Closed via #1754.  @Reaper10 expect to see this feature in the early 1.2 beta builds.
