### ISSUE TITLE
Mallets, midi volume problem.

### ISSUE THREAD

**Issue by LocoMatt** [LMMS/lmms#1753]
Hello, so I found problem that looks like this
Note volume 100% - sounds normal
Note volume 50% - it quieter (thats logical)
Note volume 25% - even more quieter 
Note volume 17X% (around this value, for sure more than 150%) - quieter than 100%
Note volume 200% - very quiet 
LMMS 1.1 x64 Windows 7 x64

**Comment by Sti2nd** [comment]
Confirmed on same OS with default preset

**Comment by tresf** [comment]
Can someone determine if this is new with 1.0 or 1.1 so we can milestone it properly?

**Comment by Sti2nd** [comment]
Exists in 1.0.3.

**Comment by zonkmachine** [comment]
The problem is only in the ModalBar part of mallets( instruments over Tubular Bells )and we need to limit the velocity, halve it to be precise, in order to avoid errors when we go out of the range and also suppress command line messages.
