### ISSUE TITLE
Stuck notes on Dialog Open

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms#1755]
When using the typing keyboard for input, the Song Editor as well as the BB Editor allows keystrokes to continue sending to the last opened instrument (this is a nice feature).

However, the focus-lost logic seems to have a loophole where the note can get stuck.
1. Open a new project
2. Open the default TripleOscillator instrument track Instrument window by clicking on its button
3. Start playing notes via Typing Keyboard (observe behavior)
4. While holding down a note, click Edit, Settings
5. Notice the note is automatically stopped.
6. Click the TripleOscillator instrument window again.
7. Start playing notes via Typing Keyboard (observe behavior)
8. Click Song-Editor
9. Continue typing notes via Typing Keyboard (observe behavior)
10. While holding down a note, click Edit, Settings
11. Notice the note is stuck "on".

If the above steps are repeated without focusing to Song Editor (just steps 1-5), the focus lost event stops the note from being played.  This behavior is ideal but only seems to work on the Instrument Window.

For other components which listen for keystrokes **on behalf of the instrument** including but not limited to Song Editor, BB Editor, Controller Rack, the above bug exists.

**Comment by SecondFlight** [comment]
I would be surprised if this bug *doesn't* still happen, but here's my reminder to try to reproduce since it's been almost 4 years.

**Comment by SecondFlight** [comment]
Huh, I can't reproduce this in either 1.2.0 RC8 or master. Good job to whoever fixed this!
