### ISSUE TITLE
VST instruments don't work in LMMS 1.1.2

### ISSUE THREAD

**Issue by Sti2nd** [LMMS/lmms#1757]
Steps to reproduce
* Try to add a VST you know works with LMMS through VeSTige.

It doesn't load, just pops the usual error message "The VST plugin NAME could not be loaded for some reason. If it runs with other VST-software under Linux, please contact a LMMS developer!"

LMMS 64 bit, Windows 8.1

Also reported on the forum
https://lmms.io/forum/viewtopic.php?f=7&t=1664

**Comment by Umcaruje** [comment]
https://github.com/LMMS/lmms/compare/v1.1.0...v1.1.2

I can't see any commits affecting VST code...

Wierd, or I am missing something...

**Comment by tresf** [comment]
Did we not have positive test results for 1.1.2 or was that just for effects?  Please someone confirm and well revert the download link.

**Comment by Sti2nd** [comment]
> Wierd, or I am missing something...

Nope, it's weird. At first I didn't believe the guy. And I don't remember any VST code either.

**Comment by Sti2nd** [comment]
Picture sent in message from a user on FB = reported by three so far

![image](https://cloud.githubusercontent.com/assets/6373430/6139280/ed36324c-b189-11e4-8039-5acbcee6bec0.png)

**Comment by tresf** [comment]
Confirmed.  It seems there are problems with `RemoteVSTPlugin.exe` on both 64-bit and 32-bit platforms.  Reverting the download link now.  Will investigate.

-Tres

**Comment by tresf** [comment]
I created a build which was still configured with the old mingw PPA and it loads a VST just fine suggesting this is mingw related.  I've also emailed Toby to let him know.

Below is a screenshot of 1.1.2 built locally for Windows 32-bit.  It is running in Wine which was not possible with the Travis-built version.

![image](https://cloud.githubusercontent.com/assets/6345473/6142022/b230cb6a-b17c-11e4-9cff-5d75f62cf614.png)

**Comment by Sti2nd** [comment]
Nice find :+1:

**Comment by musikBear** [comment]
i can dl and install -*if* it make sense? just give me a peep

**Comment by tresf** [comment]
> i can dl and install -if it make sense? just give me a peep

No peep needed.  We'll post here when we have an update.

![image](https://cloud.githubusercontent.com/assets/6345473/6149216/1e01d12e-b1d5-11e4-888d-26eddc289293.png)

**Comment by musikBear** [comment]
cute peep :rabbit:

**Comment by tresf** [comment]
@tobydox any insight on this one?

**Comment by tresf** [comment]
@Lukas-W we're 5 days without word from Toby on this.  Is this something you may be able to help narrow down?  Should I just build from scratch against 14.04?

**Comment by tobydox** [comment]
I did not have a chance to test it but uploaded the latest version of GCC 4.9.x to the PPA.

**Comment by tresf** [comment]
Thanks @tobydox will try it out.

-Tres

**Comment by tresf** [comment]
Ok... so I have a build problem.  I tried to remove all of the mingw-x packages (because they simply wouldn't update to use the new ppa for me) 

This is what I'm getting:

```
CPack: - Install project: lmms
CMake Error at /home/tres/lmms/build/cmake_install.cmake:41 (FILE):
  file INSTALL cannot find "/opt/mingw64/lib/libfltk.dll".


CPack Error: Error when generating package: lmms
make: *** [package] Error 1
```

It seems to be looking in `/opt/mingw64/lib/` instead of `/opt/mingw64/bin/`.

For now, I've copied the DLL over.  Will begin testing shortly.

**Comment by tresf** [comment]
Testing (win64) seems to fail with the same error... 

![image](https://cloud.githubusercontent.com/assets/6345473/6204476/f5e74748-b51a-11e4-8338-ba59976352e2.png)

**Comment by tobydox** [comment]
FLTK issue is fixed in stable-1.1 and master branch. I'll have a look at the VST issue tomorrow.

**Comment by tresf** [comment]
> FLTK issue is fixed in stable-1.1 and master branch (via https://github.com/LMMS/lmms/commit/7bd5317499a9f8f97fe464c88364860981870c00). I'll have a look at the VST issue tomorrow.

:+1:

**Comment by tresf** [comment]
FYI, this issues is also present on builds made with trusty (Ubuntu 14.04).  Just did a clean mingw build environment on 14.04 x64 and same issue, so this is not limited to builds created with precise.

![image](https://cloud.githubusercontent.com/assets/6345473/6204719/07ee8f12-b522-11e4-91f4-1efd616567eb.png)

**Comment by jobothemojo** [comment]
A quick fix for this issue with vestige would be to rename your  Qt4Core.dll in System32 because LMMS creates one to run with RemoteVSTPlugin.exe in the LMMS program file, allowing for two Qt4Core.dll's to be on your pc, and to clash.

**Comment by tresf** [comment]
> rename or delete your Qt4Core.dll in System32

LMMS installer shouldn't be placing `Qt4Core.dll` is anyone's System32's.  Are you sure you aren't describing a different issue? (i.e. similar symptoms but not related to 1.1.2?)

**Comment by jobothemojo** [comment]
If you already have Qt4Core.dll in your System32 already (for whatever reason which doesn't concern LMMS) then the one in LMMS program file will cause problems, if you don't already have one then this shouldn't be an issue. I found I had the problem no matter what version I used (I started with 1.0.3 then moved on to 1.1.2, same problems. I then tried 1.1.0 and then figured out what to do. I assume this fix would have applied to all versions, but may be a different issue with the same error message) Anyway renaming the System32 one worked for me.

**Comment by Sti2nd** [comment]
Renaming system32???

**Comment by badosu** [comment]
@Sti2nd I think he meant the dll located at system32 folder

**Comment by Sti2nd** [comment]
Ok. In my System32 folder it is 3200 elements, probably 1000 of them are dll's

**Comment by badosu** [comment]
> If you already have Qt4Core.dll in your System32 already

**Comment by tresf** [comment]
> Ok. In my System32 folder it is 3200 elements, probably 1000 of them are dll's

Yeah, delete them all... :laughing:

**Comment by badosu** [comment]
@tresf Since a proper 1.1.2 was released, can't we close this issue and make sure everyone knows that it is fixed?

**Comment by tresf** [comment]
> @tresf Since a proper 1.1.2 was released

It was never released.  Still waiting on @tobydox to figure out what is wrong with mingw binaries (both 12.04 and 14.04, both 32-bit and 64-bit.).

-Tres

**Comment by badosu** [comment]
Oh, sorry about that.

**Comment by tresf** [comment]
> Oh, sorry about that.

No worries.  If people are eager to use it, they can grab it here:  https://github.com/tresf/lmms/releases/tag/v1.1.2-1 (built from the old PPA) but I'd like the issue to be resolved upstream and be rebuilt by Travis-CI before putting them on our downloads page (or else we'll have this issue again on 1.2.0, etc).

**Comment by badosu** [comment]
I just assumed it because this release fixed this issue for some users.

**Comment by tresf** [comment]
> In this case, it would be very nice if we could include @curlymorphic's latest fixes to 1.1.2. :-)

Sure... they'll need to be cherry-picked in and we can roll them out with 1.1.3 (assuming they are release-worthy).

**Comment by curlymorphic** [comment]
not sure they have been tested properly , other than my ten mins of tinkering. I would prefer they are tested properly first

**Comment by musikBear** [comment]
following the link:
> 1.1.2-1Tres Finocchiaro tresf released this on **13 Dec 2014**
What does *that* mean ?
version-ctrl mess or?

**Comment by tresf** [comment]
It means you are reading too much into it. :)

**Comment by musikBear** [comment]
:p i will stop reading that much
Sanity test?

**Comment by tresf** [comment]
@tobydox the 1.1 release is still waiting on the mingw stuff being fixed.  :)

**Comment by tobydox** [comment]
I'm sorry but I don't have solution yet. GCC 4.9 is built like any other previous releases so if they changed something, I don't know what do do. One could start debugging where the exe crashes. Maybe a stack align issue? Try passing "-mstackrealign" to the compiler:

 SET_TARGET_PROPERTIES(RemoteVstPlugin .... -mstackrealign)

Maybe replacing -O3 with -O2 also helps?

**Comment by tresf** [comment]
I haven't tried the suggested recommendations yet... but have some errors through Dependency Walker:

The first that I find interesting is the strange linkings I'm seeing here.  Dependency Walker has some known limitations in this regard so it is difficult to figure out if these are legitimate problems or not... namely that `VESTIGE.DLL.DLL` double extension that is in the list.... 

I compared it to a working LMMS version and the same linking warnings occurs there... 

![image](https://cloud.githubusercontent.com/assets/6345473/6433037/ce02130c-c032-11e4-966b-82e1fa35e378.png)

But Dependency Walker is having a hard time with `1.1.0`.  It crashes while loading the vesteffect.dll, so I don't really have any basis for comparison when trying to investigate the `1.1.2` crash... 

Here's the output of Dependency Walker when trying to load a VST instrument in `1.1.2`.

**Windows 8 x64:**
```
00:00:05.469: LoadLibraryA("C:/Users/Tres/Desktop\DSK Music Box.dll") returned NULL by thread 1.  Error: %1 is not a valid Win32 application (193).
```

Detailed log can be found [here (gist)](https://gist.github.com/tresf/3497b5e1650d1da3d73a).

**Comment by curlymorphic** [comment]
> Try passing "-mstackrealign" to the compiler:
> 
> SET_TARGET_PROPERTIES(RemoteVstPlugin .... -mstackrealign)
> 
> Maybe replacing -O3 with -O2 also helps?

I have tried the above to no avail. I will investigate further when i get time

**Comment by curlymorphic** [comment]
Ive been looking at this again. I am unable to make any progress. 

I was unable to locate the code that produces the dialog box shown in above post.

**Comment by tresf** [comment]
> I was unable to locate the code that produces the dialog box shown in above post.

The Error Reporting doesn't always display.  This depends on OS version and the settings of whether or not to create error reports when a problem occurs.

Are you able to reproduce the crash though?

-Tres

**Comment by curlymorphic** [comment]
Not a crash as such, I do get to this dialog box

![image](https://cloud.githubusercontent.com/assets/7412852/6509261/21084e24-c356-11e4-971a-8d0f8f8931b5.png)

then I can return and use lmms as normal, but the vst has not loaded.

im doing this on win 7 in a vm.  When i search our code base for the following string or part of, I cant find it. Ive checked the translations files as well 

````If it runs with other VST-software under Linux, please contact an LMMS-developer!````

**Comment by badosu** [comment]
@curlymorphic You could not find it because it was removed in this commit: 85fb0aca82379b51287855f770300d2eb63e5c8d

I don't know why it was removed.

**Comment by tresf** [comment]
I'm glad it was removed.  There's not much reason for that dialog to tell people to contact us when the other error dialogs don't.

I believe the error is derived from here:  [`vestige.cpp#L266`](https://github.com/LMMS/lmms/blob/master/plugins/vestige/).

**Comment by tresf** [comment]
I think @tobydox was right... This crash is related to the optimization setting... Possibly caused upstream here: [`gcc/57003`](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=57003), Dupe: [`winehq/33307`](https://bugs.winehq.org/show_bug.cgi?id=33307), Dupe: [`redhat/926972`](https://bugzilla.redhat.com/show_bug.cgi?id=926972)

Below is a VST running with `-O0`, Toby's latest mingw, a fresh build from `stable-1.1` branch, and all system updates applied.

To be effective, the `-03` needs to be changed in both `vst_base/CMakeLists.txt` **as well as** `vst_base/Win64/CMakeLists.txt`.

![screen shot 2015-03-06 at 12 27 59 am](https://cloud.githubusercontent.com/assets/6345473/6520657/adb5c644-c397-11e4-96f6-cfa3a846dffd.png)

**Comment by curlymorphic** [comment]
@tresf I have tested this using a fresh VM with 14.10 to build on. The Vsts work in both 32/64 bit version, on win 7 in a vm

**Comment by tobydox** [comment]
FYI: I updated the mingw-x-gcc package yesterday (latest version from Git (4.9 branch)) so the working plugins might be related to it as well.

**Comment by tresf** [comment]
> FYI: I updated the mingw-x-gcc package yesterday (latest version from Git (4.9 branch)) so the working plugins might be related to it as well.

Yes, I saw that however the issue is still present with the latest version.

Only after changing from `-O3` to `-O0` am I able to get the Win32 VST functionality to work.

I don't know the impact of changing this in our source or even exactly what the cause is, mostly due to my lack of understanding of what gcc versions are affected by this optimization bug versus which ones we're using when doing a build versus which ones were used to make the mingw ppa packages.

So I can switch the`CMakeLists` to use `-O0` and release the 1.1.x patch now, but I really need help understanding the cause as well as the impact of this change moving forward.

-Tres

**Comment by eagles051387** [comment]
https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html

it seems like we are reverting to the default behaviour here.

According to the above link this is what -O3 and -OO are

-O3Optimize yet more. -O3 turns on all optimizations specified by -O2 and
also turns on the -finline-functions, -funswitch-loops,
-fpredictive-commoning, -fgcse-after-reload, -ftree-loop-vectorize,
-ftree-loop-distribute-patterns, -ftree-slp-vectorize, -fvect-cost-model,
-ftree-partial-pre and -fipa-cp-clone options.
-O0Reduce compilation time and make debugging produce the expected results.
This is the default.

On Fri, Mar 6, 2015 at 6:05 PM, Tres Finocchiaro <notifications@github.com>
wrote:

> FYI: I updated the mingw-x-gcc package yesterday (latest version from Git
> (4.9 branch)) so the working plugins might be related to it as well.
>
> Yes, I saw that however the issue is still present with the latest version.
>
> Only after changing from -O3 to -O0 am I able to get the Win32 VST
> functionality to work.
>
> I don't know the impact of changing this in our source or even exactly
> what the cause is, mostly due to my lack of understanding of what gcc
> versions are affected by this optimization bug versus which ones we're
> using when doing a build versus which ones were used to make the mingw ppa
> packages.
>
> So I can switch theCMakeLists to use -O0 and release the 1.1.x patch now,
> but I really need help understanding the cause as well as the impact of
> this change moving forward.
>
> -Tres
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LMMS/lmms/issues/1757#issuecomment-77595137>.
>



-- 
Jonathan Aquilina

**Comment by tobydox** [comment]
I don't think the problem is caused by the above mentioned bug (described in the bug reports) because it relates to building WINE and not building win32/win64 binary with mingw-gcc. Furthermore the bug is rather old so we would have been affected by mingw-x-gcc 4.8.x as well.

**Comment by tresf** [comment]
> I don't think the problem is caused by the above mentioned bug (described in the bug reports) because it relates to building WINE and not building win32/win64 binary with mingw-gcc. Furthermore the bug is rather old so we would have been affected by mingw-x-gcc 4.8.x as well.

Thanks for clarification.

How do you recommend we proceed?  Change to `-O0` and move on?  File upstream bug w/ mingw team?  If we have little to gain with this specific `-O3` setting, we can release our `1.1.x` patch now. :confused:

**Comment by tobydox** [comment]
Yes O0 is far better than having nothing. Performance might be a bit impacted compared to previous versions but as the actual CPU intensive DSP code happens in the VST plugins itself, it shouldn't be a problem. Does O1 work?

**Comment by tresf** [comment]
@tobydox,

I believe I tried O1, O2, O3 to no avail.  I'll commit the `-O0` change to `stable-1.1` and fire off the patch release.  Thanks for the advice.

-Tres

**Comment by tresf** [comment]
Closed per #1757.

Github should have the 1.1.3 build uploaded [here](https://github.com/lmms/lmms/releases/tag/v1.1.3) shortly.

It will show up as a pre-release until we have some testing.  @Sti2nd @musikBear if you have time to test this version out with VSTs, that would be terrific. :+1:

**Comment by musikBear** [comment]
I have tested 
ReleaseVersion 1.1.3 (shows correctly)
*installs
*opens
*preserve settings
*uses locale
*load older project
*replay
*saves
correctly & with no problems on win 32 (xp)

*VST-Instrument*
loads vst-instrument-container
container loads dll
access to lmms-controllers (wrench)
LMMS controllers works
automation works
automation-connections preserved after save / load

*VST-Effects*
loads
has effect (vst & ladspa)
can be automated
responds to general-FX (W/D)
automation-connections preserved after save / load

**Are there any specific test you would like?**

Other wise, this looks nice on xp
-In respect to the optimation /permormance impact : I have loaded 2 instances of this relase and both can play simultaneous with no significant cpu spiking -Thats ofcause very impiric and useless, but at least it posible - 

(btw Three lmms instances is not! Something creates a conflict, and the computer has serious issues, up til ans including bsod, but that can be my system only)

1.1.3 :+1:

**Comment by tresf** [comment]
Terrific, thanks.

I've built and uploaded the Apple version.  @Sti2nd , @Umcaruje, want to do the announcement?

**Comment by curlymorphic** [comment]
:)

**Comment by Umcaruje** [comment]
Made an announcement on the Facebook page. @tresf make 1.1.3 a full release instead of pre-release?

**Comment by tresf** [comment]
Done. :)

**Comment by Sti2nd** [comment]
Was just going to as well. Nice
