### ISSUE TITLE
Rakarrack Integration Request

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms#176]
Yesterday, a member of the KVR community asked if a plugin called Rakarrack could be integrated with LMMS.

It appears to be an effects processor popular for guitars (and likely other instruments).

Personally, knowing nothing about this, I looked it up and it appears to be based off of source code for ZynAddSubFX.

What is the likelihood this could make it into a future LMMS build?  Is the fact that is a "JACK" plugin make it unusable?  Would it need to be ported to LADSPA?  Has this already been asked before (sorry if it has).

Today he stated he got it working, but suggested he was using the VST, but I wasn't aware we offered compatibility with VST effects yet, so I'm perplexed.

Thoughts welcome.  I'd like to open an enhancement request.

![image](https://f.cloud.github.com/assets/6345473/2011200/eabb189e-8777-11e3-90bd-9d0d551b0e2f.png)

**Comment by badosu** [comment]
It looks like it's primarily designed for JACK, I could not find any reference for other compatibility layers.

This would be a show-stopper since we allow the use of lmms without JACK.

If this could be ported to LV2 we could include it by default on lmms as soon as LV2 support lands.

**Comment by tresf** [comment]
Ok, thanks for looking into this.  I did not examine the code but I was under the impression that if it had enough similarities to ZynAddSubFX, we would have the ability to treat it as a native plugin with some helpers.

**Comment by badosu** [comment]
@tresf I didn't look really in depth, maybe it is.

**Comment by badosu** [comment]
So, my opinion is that this feature should be closed in favour of LV2 support.

There's an ongoing effort in porting rakarrack effects to LV2, see: http://sourceforge.net/u/ssj71/rakarrack/ci/master/tree/lv2/ . Joining efforts would be better overall for everyone.

**Comment by tresf** [comment]
:+1:
