### ISSUE TITLE
Just a very important feature that should be added...

### ISSUE THREAD

**Issue by Renorax** [LMMS/lmms#1763]
In FL Studio, you can resize the start and end of an imported audio file. LMMS can only do the end of a file, yet it plays the whole file, even when I crop the file, please fix and add the ability to resize both ends of a audio file. Thank you!

**Comment by tresf** [comment]
> LMMS can only do the end of a file, yet it plays the whole file, even when I crop the file


Please be more specific and give steps to reproduce.

We support many files.  WAV and OGG files for example can be resized via AudioFileProcessor.

SampleTrack does not yet have this capability, but we already have these improvements on the radar.

**Comment by tresf** [comment]
Closing as invalid.  Please reopen this bug report after you've cleaned it up. :+1:
