### ISSUE TITLE
Load Failure VST Plugin in LMMS 1.1.2 Beta Version

### ISSUE THREAD

**Issue by paulomois** [LMMS/lmms#1765]
Hello!

No plugin is loading in LMMS 1.1.2 Beta Version for the Windows 7 (x86) and x64. Is showing the load failure message.

![error_loading_vst_plugins](https://cloud.githubusercontent.com/assets/4085838/6203650/be555970-b513-11e4-9be1-ba605cd19e12.png)

**Comment by badosu** [comment]
Hi @paulomois, this is a known issue that's not really a bug in the LMMS code but in the build process that generated that binary. Try https://github.com/tresf/lmms/releases/tag/v1.1.2-1 and see if it still happens.

**Comment by tresf** [comment]
Duplicate of #1757

**Comment by paulomois** [comment]
Hi, Badosu! 

I was tested this new compilation and LMMS the 32bit version functioned normally , but the LMMS x64 version continued showing error, but for me already resolved in version 32-bit.

Thanks!

**Comment by tresf** [comment]
> but the LMMS x64 version continued showing error, but for me already resolved in version 32-bit.

There is a slight chance I uploaded the wrong build.  Either way, we recommend using 1.1.0 until we fix our build environment.

**Comment by badosu** [comment]
Hi @paulomois, a little off-topic but which country are you from? I am a lusophone as well, from São Paulo - Brasil.

**Comment by tresf** [comment]
Just tested again with 64-bit version 1.1.2-1 and it does work.  We're still working on this.

![image](https://cloud.githubusercontent.com/assets/6345473/6204504/9815c7b0-b51b-11e4-80bf-d32eb8458589.png)

**Comment by paulomois** [comment]
Yes, Badosu! I am in Sao Paulo, Brazil. Thanks again!
