### ISSUE TITLE
NSIS help link URLs (win32)

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms#1766]
Does anyone know why the NSIS help links are in the format `http:\\\\\\\\lmms.io`?

![image](https://cloud.githubusercontent.com/assets/6345473/6204698/8671344e-b521-11e4-99c4-57a1396e3ceb.png)

The values which currently use this syntax are:
```
CPACK_NSIS_HELP_LINK
CPACK_NSIS_URL_INFO_ABOUT
```

I get the purpose of escaping (or in this case double-escaping) backslashes, but why backslashes to begin with?  Why not forward slashes (i.e `http://`)?  Is this normal?

Per [`CMakeLists.txt#L578`](https://github.com/LMMS/lmms/blob/master/CMakeLists.txt#L578)

I've looked up other NSIS examples and they seem to do the same thing.  Is this to circumvent an old bug or something?

**Edit:** Still seems to open the URLs properly, so this is just cosmetic.

**Comment by pbella** [comment]
That looks like a bug... http:\\ is not valid syntax

**Comment by tresf** [comment]
Perhaps, but it is what the NSIS website recommend, so most scripts I've found use it.

![image](https://cloud.githubusercontent.com/assets/6345473/6218599/cbaa12fc-b5ed-11e4-8da0-b3dd0a9f6494.png)

It seems to work both ways.
