### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms#1769]
```
2015/02/16 18:40:05 [error] 32100#0: *200 FastCGI sent in stderr: "PHP message: PHP Fatal error: 
 Interface 'Silex\ServiceProviderInterface' not found in 
/home/deploy/lmms.io/vendor/silex/silex/src/Silex/Provider/TwigServiceProvider.php on line 30" while 
reading response header from upstream, client: 176.250.216.5, server: lmms.io, request: "GET 
/download/ HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "lmms.io", referrer: 
"https://www.google.co.uk/"
```

I'm having a hard time figuring this one out...

**Comment by eagles051387** [comment]
What kind of web server setup are we using as I am seeing all sorts of
issues relating in particular to nginx and the solutions being permissions.

On Mon, Feb 16, 2015 at 7:41 PM, Tres Finocchiaro <notifications@github.com>
wrote:

> 2015/02/16 18:40:05 [error] 32100#0: *200 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Interface 'Silex\ServiceProviderInterface' not found in /home/deploy/lmms.io/vendor/silex/silex/src/Silex/Provider/TwigServiceProvider.php on line 30" while reading response header from upstream, client: 176.250.216.5, server: lmms.io, request: "GET /download/ HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "lmms.io", referrer: "https://www.google.co.uk/"
>
> I'm having a hard time figuring this one out...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LMMS/lmms/issues/1769>.
>



-- 
Jonathan Aquilina

**Comment by tresf** [comment]
nginx.

**Comment by Sti2nd** [comment]
ouch, maybe tag badosu?

**Comment by tresf** [comment]
Thanks.  That @eagles051387 that would make sense.  Let me check the permissions because the code is fine here.

**Comment by tresf** [comment]
@eagles051387 can you provide more details around what you are speaking about?

**Comment by badosu** [comment]
@tresf Can you show up on IRC: #lmms?

**Comment by tresf** [comment]
@badosu I'm on.

**Comment by tresf** [comment]
FastCGI just needed restarting per

```sh
sudo service php5-fpm restart
```

**Comment by badosu** [comment]
Ok, I just saw your messages now :-(. But I am glad it got sorted out,
