### ISSUE TITLE
Refuse to run as root

### ISSUE THREAD

**Issue by softrabbit** [LMMS/lmms#1770]
Inspired by troubleshooting on IRC, I strongly believe LMMS should just _refuse to run_ (and of course tell the user why) if started as root on Linux (and OSX?). Maybe with a _command line option_ to bypass the check, for those who are 100% sure they want to run as root.

And the reasons...
1. Security, root can do anything and a bug can screw up your entire system 
2. If you by mistake do ```sudo lmms``` your ```.lmmsrc.xml``` and possibly ```~/lmms/```will be owned by root and you'll need to ```chown``` them back to make them writable again.

**Comment by tresf** [comment]
Simply checking for root is probably sufficient for 99.9% of cases, but a reminder that some systems may be built in a way where a user without the `root` username still has the ability to overwrite system files.

Also the majority of Linux/Unix systems (Apple included) have switched from `root` to `sudo`.  I'm not sure how this affects the C++ library referenced below.

Here is an article which covers the topic a bit:

http://www.cplusplus.com/forum/unices/45522/

The relevant code:

```cpp
#include <stdio.h>
#include <stdbool.h>
#include <unistd.h>

bool isRoot(void) {return getuid()==0;}

int main(void)
{
  if (isRoot())printf("root\n");
  else printf("other\n");
  return 0;
}
```

**Comment by pbella** [comment]
Sudo only prevents the user from logging in as root, not becoming root once logged in so the issue would be the same on those systems.

**Comment by tresf** [comment]
The sudo comment was in reference to library compatibility, not severity of usage.  BTW, I started this to no avail so far...  I'll keep tinkering.

**Comment by softrabbit** [comment]
UID 0 is UID 0, no matter if it's through a login shell or trough sudo, both are just programs that happen to start LMMS. So that issue should be pretty irrelevant.

The situation that _is_ different is if someone is stupid enough to turn the setuid bit on for LMMS, which would AFAIK result in the _effective_ UID (returned by ```geteuid()```) being that of the owner of the binary (usually 0 for root) but ```getuid()``` still returning the UID that started LMMS. So, I'm pretty sure it's better to call ```geteuid()```. Or maybe check both for 0...

**Comment by tresf** [comment]
Thanks.  @softrabbit do you know why the example claims to to need `#include <stdbool.h>` ?

My first attempt intentionally didn't include it.  My first attempt also didn't work. :)

**Comment by tresf** [comment]
And my code for reference:

![screen shot 2015-02-21 at 9 51 52 am](https://cloud.githubusercontent.com/assets/6345473/6314504/4db84a24-b9af-11e4-8cf7-6e77e8cd3d6a.png)

**Comment by tresf** [comment]
Nevermind, user error. :)

**Comment by curlymorphic** [comment]
looks like you have it sorted tres. I just ran an experiment checking both uid and ueid if this helps at all

````
#include <stdio.h>
#include <unistd.h>

int main(void)
{
	int uid = getuid();
	int ueid = geteuid();
	printf("uid %d \n",uid);
	printf("ueid %d\n",ueid);
	return 0;
}
````

the results
````
dave@dave-700-230ea:~/Development/qt/userId$ ./userId
uid 1000 
ueid 1000
dave@dave-700-230ea:~/Development/qt/userId$ sudo ./userId
[sudo] password for dave: 
uid 0 
ueid 0
````

**Comment by tresf** [comment]
Yeah, I left a root terminal open on this VM :speak_no_evil: 

So it works, but not I get `Invalid option --forceroot` when I try overriding it...

Is there a second location to whitelist the params?

-Tres

**Comment by curlymorphic** [comment]
The only place im aware of is the long chained else if in main.cpp ln 152

When i added to this list i added this code

````
else if ( argc > i &&
				  ( QString( argv[i] ) =="--float" ||
						QString( argv[i] ) == "-a" ) )
		{
			os.depth = ProjectRenderer::Depth_32Bit;
		}
````

it must be an  else if

**Comment by tresf** [comment]
Hmm... perhaps I'll need to put it twice then?  IMO, the root check should come in the first pass, before processing any of the rendering or settings command line options, i.e. [main.cpp#L121](https://github.com/LMMS/lmms/blob/master/src/core/main.cpp#L121). (`--render` is one that appears in both loops too).

**Comment by curlymorphic** [comment]
hmm, yeah your right, the correct place would be here

````
for( int i = 1; i < argc; ++i )
	{
            //***CHECK ROOT USER HERE ****
		if( argc > i && ( ( QString( argv[i] ) == "--render" ||
					QString( argv[i] ) == "-r" ) ||
				( QString( argv[i] ) == "--help" ||
						QString( argv[i] ) == "-h" ) ) )
		{
			core_only = true;
		}
		else if( argc > i && QString( argv[i] ) == "-geometry" )
		{
			// option -geometry is filtered by Qt later,
			// so we need to check its presence now to
			// determine, if the application should run in
			// fullscreen mode (default, no -geometry given).
			fullscreen = false;
		}
	}
````

but the command line options would also be needed to be added to the elfe if statement because that is where valid options are checked.

**Comment by tresf** [comment]
I figured it out... just set `argv[i] = ""` and it skips processing it on the second pass.

Here's an initial commit... comments appreciated... 

https://github.com/tresf/lmms/commit/7385aa7be6f780e25f07715ebdb9c9a7ec11f5e4


-Tres

**Comment by curlymorphic** [comment]
im about to look at the code. my first thought, what happens if there are more flags on the line

````lmms --forceroot --render```` for example

can you think of a valid use case to run a Daw as root user?

**Comment by tresf** [comment]
> can you think of a valid use case to run a Daw as root user?

Not for average end-users, no, but I've seen some single-user embedded kiosks be designed (rather poorly) with root everything.

> what happens if there are more flags on the line

Needs testing.  I only tested the basics so far.

-Tres

**Comment by tresf** [comment]
@curlymorphic besides the devilish underscores, can you review #1784? :)

**Comment by curlymorphic** [comment]
@tresf done, looks good :)

**Comment by tresf** [comment]
Thanks, merging.  Please blame me if this breaks anything :).
