### ISSUE TITLE
FATAL LMMS BUG

### ISSUE THREAD

**Issue by kLik-kLak** [LMMS/lmms#1773]
If you have an instance of the sampler open and click on the waveform display while its playing, LMMS crashes. I just lost an amazing song to this bug and I made an account just to report it, This may be a a bug that's been around for a while also because I recall encountering this big once before YEARS ago, I think...

**Comment by tresf** [comment]
Are you talking about AudioFileProcessor?  We'll need exact steps to reproduce to fix this.  P.S. LMMS still has many bugs.  Please save projects very often.

**Comment by badosu** [comment]
@kLik-kLak I am really sorry to hear that, I know how it's awful to lose something like that :-(.

However to really help you we need more detailed information on this issue, can you recall in the most detailed sense what were you doing when this happened?

If you are able to tell us that you can make it crash again and how that would help even more.

**Comment by kLik-kLak** [comment]
Yes it was the AudioFileProcessor. It crashed when I was going through the samples. I opened up the"trumpet" sample (stock). While playing a note, I accidentally clicked the blue waveform display. Then LMMS proceeded to crash. Luckily my last save for the project had the trumpet in it (not the other instruments unfortunately) but I continued working on it and now its twice as developed then when it crashed. I'm gonna see if I can crash it in its current save, and if I can ill upload and link it for debugging or whatever.

**Comment by kLik-kLak** [comment]
Well interestingly, clicking the waveform display DOES NOT crash it anymore... and even weirder, ZASFX crashed it like 3 times (saved) when I tried to edit the rhodes, but when I opened it this time around it hung for a few seconds then opened fine...

**Comment by tresf** [comment]
> Well interestingly, clicking the waveform display DOES NOT crash it anymore...

Yeah, I tried right after reading your bug report and couldn't reproduce either.

> ZASFX crashed it like 3 times (saved) when I tried to edit the rhodes, but when I opened it this time around it hung for a few seconds then opened fine...

Hmm... ZASFX is usually pretty stable.  Sounds like you are having all sorts of crashes.

**Comment by badosu** [comment]
> > ZASFX crashed it like 3 times (saved) when I tried to edit the rhodes, but when I opened it this time around it hung for a few seconds then opened fine...
>
> Hmm... ZASFX is usually pretty stable. Sounds like you are having all sorts of crashes.

I know this is probably not related to the issue being discussed, but the weirdest thing is happening to me: when I play unfa`s InAndOut track it works, but if I click on "Show GUI" on the Bass's ZASFX It crashes the whole X session!

**Comment by kLik-kLak** [comment]
Yea the same thing happens to me sometimes, well more randomly for me. One instance will open fine and another will crash the whole project. Could the (first) bug be related to me using ASIO4ALL with LMMS? Using 32 bit LMMS on 64 bit OS? Maybe both?

**Comment by eagles051387** [comment]
Klik what operating system are you on?

On Fri, Feb 20, 2015 at 6:54 AM, kLik-kLak <notifications@github.com> wrote:

> Yea the same thing happens to me sometimes, well more randomly for me. One
> instance will open fine and another will crash the whole project. Could the
> (first) bug be related to me using ASIO4ALL with LMMS? Using 32 bit LMMS on
> 64 bit OS? Maybe both?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LMMS/lmms/issues/1773#issuecomment-75193299>.
>



-- 
Jonathan Aquilina

**Comment by kLik-kLak** [comment]
Windows 8.1

**Comment by musikBear** [comment]
the show gui crash could be because of a bug in zasfx, that has to do with specif wave-forms in the wave-form-editor
To investigate further
Open a *new* instance of zasfx
use the advanced zasfx gui and open all the forms down to this
![pastenot](https://cloud.githubusercontent.com/assets/6662066/6285680/c7e01464-b8fe-11e4-868f-3c5716c4ab1f.PNG)
here it is focused on 'sine'
Test *every one* of the shapes, by selcting and changing them . 
Does all 'load'?

**Comment by tresf** [comment]
@musikBear aren't you describing an XP-only bug that crashes Zyn?

**Comment by musikBear** [comment]
sounds like others may have *similar*problems - could be with other waveforms
I suspect a data-structure to be insufficient -eg defined too small. Looks like the 1.1 zasfx selection-dd has more options than before.

**Comment by tresf** [comment]
> sounds like others may have similarproblems

@musikBear I'm not sure where you are drawing these conclusions from.

> "Show GUI" on ZASFX It crashes the whole X session!

@musikBear since X is the display manager, the entire desktop is what is crashing here.  That is quite different.  Also it has no similarities with the bug you are describing other than the fact that Zyn is assumed to be part of the cause. :)

**Comment by badosu** [comment]
I shoud not have talked about that "Show GUI" thing, please let's mantain the issue on the AudioFileProcessor problem.

**Comment by kLik-kLak** [comment]
Good thing I don't use XP anymore.

**Comment by tresf** [comment]
Closing as invalid (we can't reproduce).  @kLik-kLak When you figure out the steps to reproduce this crash, please reopen with the button below
`.....................................................................................` :arrow_down:
