### ISSUE TITLE
LMMS Serious Bug

### ISSUE THREAD

**Issue by Mark0001** [LMMS/lmms#1778]
LMMS serious bugs and crashes that the entire program as soon as you open multiple editors working for example song editor + beat bass line editor, effect, editor automation etc .... just open these windows the software goes into lock and tilt totally and you have to close the windows task manager and oftentimes even after forgetting to save a project done discreetly and touches it again and it's a little annoying to fix please.

**Comment by badosu** [comment]
@Mark0001 We have  lots of serious bugs, so many that it's difficult to track each one individually.

If you are able to tell us how we can reproduce the bugs that are annoying you maybe we can fix.

**Comment by musikBear** [comment]
@Mark0001 
as badosu said and also
please post your:
* OS
* lmms vers
* hardware specification (ram is the most imortant)

**Comment by Mark0001** [comment]
OS Windows 7, LMMS Vers 1.1.2,cpu dual core 2.20 ghz, Ram memory 2GB

Date: Mon, 23 Feb 2015 02:47:54 -0800

**Comment by Spekular** [comment]
Are you on a desktop or laptop? If possible, consider upgrading to 4Gb ram.
Not just for this issue, but for performance in general. It's pretty much
the standard, and an extra 2GB shouldn't cost much (plus it's easy to
install).

**Comment by tresf** [comment]
The ram and OS are nice to know, but the OP needs to provide **exact** steps to reproduce or else we can't fix this.

**Comment by tresf** [comment]
Unless you can provide steps to reproduce, this bug can't be fixed.

Closing out as invalid.  Please reopen when you have the steps necessary to reproduce the crash.
