### ISSUE TITLE
I'm still alive

### ISSUE THREAD

**Issue by diizy** [LMMS/lmms#1779]
I apparently can't currently access my email at all (read/write) so I'm starting this issue so people can contact me if they need me for anything. I'll try to go through some PR's and stuff this week so if anyone has code/things/etc they want my input on just respond here.

Hopefully I'll get my internet issues sorted by next month, right now things are still a bit crazy here...

**Comment by badosu** [comment]
Nice @diizy, really cool to hear from you.

There have been a lot of bugfixes and UI quirks from @curlymorphic and some patches from me. Also, @Lukas-W helped with some bugfixes and added test support.

We are experiencing some issues with building LMMS for VST support, @tresf is more capable of telling what's up.

Me and @curlymorphic have been studying a lot of sound processing techniques and LV2 arquitecture lately, this should result in some nice core improvements and plugin support in the future.

**Comment by badosu** [comment]
Also, there's that nice VST fix and MIDI export :-)

**Comment by tresf** [comment]
> Hopefully I'll get my internet issues sorted by next month, right now things are still a bit crazy here...

Sorry to hear they are crazy.  Hope all else is well. :+1:

**Comment by musikBear** [comment]
Nice hear from you! Thumbs up from here too :+1:

**Comment by diizy** [comment]
Ok hey thanks @tresf @musikBear. Things are well, really, just some changes in living situations... you know, real life stuff...

@badosu I'll be taking a look at various pr's during this weekend if I can.

For that matter, this month should be a lot less crazy. I *should* be getting my internet working soon (I'm on cellphone internet right now which really, really, REALLY sucks). I'll hopefully be able to also start writing some code again soon. (As soon as I get a working mouse, which also broke. Good times...)

**Comment by curlymorphic** [comment]
> (I'm on cellphone internet right now which really, really, REALLY sucks).

You have my sympathy, I spent some time on that, It's not a pleasant experience.

**Comment by tresf** [comment]
@diizy we've fallen quite far behind on PRs.

@curlymorphic's done 6 PRs in regards to smoothing and sample-exact that we could really use some review on. :)

https://github.com/LMMS/lmms/pulls?q=is%3Apr+is%3Aopen+%22sample+exact%22+

**Comment by diizy** [comment]
Yeah, I'm aware. I'll go through them as soon as I can. Btw I have proper internet now, but didn't get new email boxes so I'll have to look into getting those...

**Comment by tresf** [comment]
@diizy it's been about a month since you last updated this thread... how is your situation going?  We have a bunch of PRs that we need your help with. :+1:

**Comment by Umcaruje** [comment]
Closing to reduce the clutter of the issue tracker.
