### ISSUE TITLE
Better EDM support?

### ISSUE THREAD

**Issue by Mark0001** [LMMS/lmms#1780]
Hi I wanted to propose to implement the program audiowork Linux (LMMS) tools in time and bass, sub, drum, bass drum and synth, piano etc .... to produce the style of the moment EDM Music Dyro and others because at the time the style that is produced easily and the old techno, trance music, eurodance all other genres but the EDM is difficult for old synthesizers and samples and codecs present reviewing this issue in LMMS with future versions thanks. (current version 1.1.2 beta)

**Comment by Umcaruje** [comment]
What?

**Comment by Mark0001** [comment]
nothing I wanted to propose to include some tools for the production of music EDM (Electronic Dance Music of the moment DJ style Dyro About sounds or maybe that's all thanks anyway they approach the work you do to improve the program LMMS.

Date: Mon, 23 Feb 2015 02:42:27 -0800

**Comment by Spekular** [comment]
Sounds like "develop LMMS so that you can make EDM in it" to me. Way too
broad as an issue, too specific as a goal for LMMS, and already possible.

**Comment by musikBear** [comment]
exactly, there is absolutely nothing missing in lmms, if you want to make house bigroom and or rap in every subgenre, at all
The only thing is can figure out from this post, is that you miss samples, that would go directly as EDM, eg you think of lmms ad if it was *sonyAsid*. Lmms is not a dedicated sampler, it can be used as one, but it is a DAW, and *you* are suposed to make the loops yourselfs, not just puzzle them together from a collection of ready-makes. or in short hand.. Lmms needs a composer, just as FLs or Reaper. If you are more a sampler guy, then sonyAsid is your tool
sugest close as invalid

**Comment by tresf** [comment]
@Mark0001,

Welcome to the bug tracker.

I think what you are describing is a long-term enhancement to make LMMS more EDM-centric.  What you are describing can be done now by:
 * Finding samples licensed as CC0 and contributing them to the project.  We have a repository for that, but we're very strict about what goes in.
 * Making project demo's that we can bundle with LMMS that showcase some of the techniques you believe could contribute to this genre.
 * Creating your own tutorials on the matter (we generally don't include specific genre tutorials in our official wiki, but we would at least consider it if written properly).

That said, this bug report is messy.  The title is an entire paragraph and even when asked to clarify your point, you just copied/pasted the same confusing run-on sentences. 

Lastly, this is a long term goal without very clear goals in mind which means this bug report can't be closed (defeating the purpose of having it open to begin with).   This topic may be better suited for our forums and then you can ping back and forth in open discussion about what you're looking to get out of LMMS. :+1: 

I'll leave this open for a few days to give you ample time to respond, but unless it is seriously cleaned up, it will be closed out as invalid.

-Tres

**Comment by tresf** [comment]
As far as EDM production, your wishes are duly noted.  There are many genres which are difficult to create using LMMS and we are working to improve the software to make some of those possible.

If you are aware of a specific feature that would help make this goal possible, please chime in. :+1: 

I'm closing this as invalid, since this bug report has no specific problems to solve.  Please feel free to reference it on other related bug reports by tagging it by number `#1780`.

-Tres
