### ISSUE TITLE
Enhancement Midi keyboard connection as default 

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#1781]
If i completely misunderstand this, then ..sorry, but I have read a thread where the op asks for a peculiar thing, because i actually thought that it was default behavior, when a external keyboard was connected..
He asks if its possible to avoid having to manually connect every preset to the external kb, and it is *that* part, that came as a surprize to me. I thought that was implicit, when the kb was connectet?
But it isent afai understand now?
**each** individual preset in song-editor, must be *manually* connected to the external midi (cogwheel) ?
Isent it posible to have default connections for a *whole* project, and then let the one thats 'opend' have the actual output?
Is singleton connection the only way to connect midi-devices, and is this also how it is in other DAWs?
Perhaps this is something for 2.0 .. -if at all posible ?
(wiki page really do not explain limitations, if any exists)

**Comment by tresf** [comment]
Similar to #1189

**Comment by tresf** [comment]
This request has been consolidated into a placeholder issue #1472, which includes this request as well as many others around general MIDI improvement.

**Comment by tresf** [comment]
@musikBear I've put this in the main list.

![image](https://cloud.githubusercontent.com/assets/6345473/6328496/2126c5f2-bb36-11e4-9e6f-d1da238e81d0.png)

**Comment by musikBear** [comment]
Great! looks promizing :+1:
