### ISSUE TITLE
LMMS an excellent open source program

### ISSUE THREAD

**Issue by Mark0001** [LMMS/lmms#1785]
I wanted to thank for maintenance in the program LMMS a great opensource audio work to produce music.

**Comment by StakeoutPunch** [comment]
Chiming in here to say that this is a bug tracker for the developers, not a forum. I know that sounds a little mean, but it definitely a truth. There is a forum full of musicians and a few of the developers as well, you can find it here: http://lmms.io/forum/

**Comment by tresf** [comment]
> Chiming in here to say that this is a bug tracker for the developers, not a forum.

But the developers don't all get notified when a new message is posted on the forums.

> I know that sounds a little mean, but it's definitely a truth.

When someone says "thank you" and your first response is "go away", yes that is mean.

> would you mind closing this issue, so that the tracker stays tidy?

I wasn't aware you were actively helping us close out bug reports.  :smile:

**Comment by diizy** [comment]
@Mark0001 thanks, it's nice to hear our work is appreciated!

**Comment by StakeoutPunch** [comment]
@tresf I come back for one message and get jumped on. Touché. 

Your response to his other issue comes to mind. Taa

**Comment by tresf** [comment]
:+1:
