### ISSUE TITLE
proposal to extend the most basic effects of the program LMMS in the full version, not beta 1.1.2 thanks.

### ISSUE THREAD

**Issue by Mark0001** [LMMS/lmms#1789]
prejudice if I wanted to propose in the full version, not beta of 1.1.2 you could add more basic effects of the program because there are currently 10 maybe someone could produce too much that I'm able, I think at least a further 10 or 20 5 more about better than nothing, for the tracks maybe conpiù effects especially with regard to the stop and the end of the songs or pieces of music alone, and instead start as early songs we there are two that are good and are the "start01.ogg" and "start02.ogg", let me know thanks.

**Comment by tresf** [comment]
Are you asking for more pads/filter sweeps/startup sounds?

We know we need better samples, but we need people to make them and donate them to the project first. :+1: 

Discussions for samples should generally go here: 

https://github.com/LMMS/Samples

-Tres
