### ISSUE TITLE
LMMS

### ISSUE THREAD

**Issue by Mark0001** [LMMS/lmms#1790]
Hi I wanted advice on how to connect the notes with the arrows on the piano roll? let me know thanks.

**Comment by tresf** [comment]
@Mark0001, general usability questions should go to the forums, not our tracker.  This is because our bug tracker is used for software bugs.

As far as "connect[ing] the notes with the arrows", can you be a bit more specific?

Are you referring to the arrow keys?

**Comment by Mark0001** [comment]
yes  those that are used to connect the square between the notes in the piano roll I do not know what I mean?

**Comment by tresf** [comment]
Can you take a screenshot please?  Are you looking to "glue" two notes together?

**Comment by tresf** [comment]
I'm closing this out to clean up our tracker but please feel free to continue the discussion below.
