### ISSUE TITLE
Multiple Instruments on 1 Channel (Launchpad Support)

### ISSUE THREAD

**Issue by thore00** [LMMS/lmms#1792]
I think it would be cool if you could set up in the MIDI settings so the instrument plugin only receives a signal if the signal is between two notes you choose.
This would allow you to play multiple instruments at the same time on the same piano.
This would also create Launchpad support.

Thank you for reading!

In the LMMS Forum: https://lmms.io/forum/viewtopic.php?f=15&t=1721
(BTW How do you add lables in GitHub?)

**Comment by Umcaruje** [comment]
Related: #1381 #1460

This should be consolidated in #1472

>(BTW How do you add lables in GitHub?)

Regular users can't add labels, your post can be labeled by someone from the dev team (They have 'Contributor' or 'Owner' next to their names).

**Comment by thore00** [comment]
Thanks, and how do I fix this so it's a part of #1472 ?

**Comment by Umcaruje** [comment]
Don't worry, @tresf or some other dev will do that :)

**Comment by tresf** [comment]
Identical to #1381, marking as duplicate.
