### ISSUE TITLE
Song/BB Editor toolbar not exposed through style.css, unused image main_toolbar_bg

### ISSUE THREAD

**Issue by Spekular** [LMMS/lmms#1793]
The toolbars in song editor and BB editor use toolbar_bg.png, which seems to be hardcoded as it is not present in style.css. The main toolbar is on the other hand present and uses a qLinearGradient, meaning main_toolbar_bg is unnecessary. I propose we expose the Song/BB Editors toolbars and remove toolbar_bg and main_toolbar_bg. I'll get to work on this and report back if I need help/make progress.

**Comment by Spekular** [comment]
Haha, found this in BBEditor.cpp:
```
// TODO: Use style sheet
```

**Comment by Spekular** [comment]
GitHub search isn't working for me and I can't locate any mention of toolbar_bg in the files I've searched... Anyone know where it's located?

**Comment by Sti2nd** [comment]
The theme

**Comment by tresf** [comment]
@Spekular good find. Took me a while to find it.. This commit seemed to remove it from code:
https://github.com/LMMS/lmms/commit/384a48f121631c510da0c0ae53ca63f5b0cfe3ee

This commit removed it from the CSS file:
https://github.com/LMMS/lmms/commit/cf2fb230a23332a608d248fb0987eb331bc89021

So this file can probably be removed from master and closed.  Please test fully and we'll accept the PR and close this one out quickly. :+1:

**Comment by Sti2nd** [comment]
> I propose we expose the Song/BB Editors toolbars and remove toolbar_bg and main_toolbar_bg.

Oh, so it is in the CSS now after all?

**Comment by tresf** [comment]
> Oh, so it is in the CSS now after all?

Which part. the image or the gradient?  I think my last post explains it, no?

**Comment by Sti2nd** [comment]
The gradient replaced the images I suppose, so the gradient is in the CSS. Oh, now I understand, Spekular is going to finish off some unfinished job of making LMMS CSS themable.

**Comment by Spekular** [comment]
@tresf I was testing on Stable 1.1, but I see that my first issue (Song/BB Editor not being themable) has been fixed in master. Perhaps this ought to be cherry picked to the next stable release if it hasn't already.
As for removing the unused (in master) toolbar images, what kind of testing is needed?
LMMS is definitely using the color/gradient from style.css, (I changed it to bright red to check) so it shouldn't matter if the images are there or not.
If they're removed from data/themes/default and target/shared/lmms/themes/default everything still seems to work fine.
Oddly enough if I copy & paste another image and rename it to toolbar_bg and then launch lmms, whatever copied image turns into the old toolbar_bg... Spooky :P
This happens in both data/themes/default and target/shared/lmms/themes/default.

**Comment by tresf** [comment]
> Oddly enough if I copy & paste another image and rename it to toolbar_bg and then launch lmms, whatever copied image turns into the old toolbar_bg... Spooky :P
This happens in both data/themes/default and target/shared/lmms/themes/default.

Your windows icon cache is stuck.

> As for removing the unused (in master) toolbar images, what kind of testing is needed?
LMMS is definitely using the color/gradient from style.css, (I changed it to bright red to check) so it shouldn't matter if the images are there or not.

That kind of testing. :+1: 

> Perhaps this ought to be cherry picked to the next stable release if it hasn't already.

I think we'll only make the change in master and moving forward. There isn't much value making this change on frozen (bugfix only) branches IMO.

**Comment by Spekular** [comment]
@tresf *ubuntu icon cache if so, can't build on windows. Seems like bad
behavior for a cache...

**Comment by tresf** [comment]
> @tresf *ubuntu icon cache 

Sorry for making that assumption.


> Seems like bad behavior for a cache...

Perhaps, but this is what a cache does, it stores stuff in memory so that it doesn't have to read the file again each time.  

Try:

```bash
rm -rf ~/.cache/thumbnails
```


> Can't build on windows.

Well, it is technically possible just no one has [grunted through to completion](https://github.com/tresf/lmms/wiki/Compiling-lmms-(on-Windows)) yet. :)

**Comment by tresf** [comment]
Closed via #1805
