### ISSUE TITLE
new tape machine plugin

### ISSUE THREAD

**Issue by Reaper10** [LMMS/lmms#1794]
It would be cool for LMMS to have a tape machine plugin I don't how to make plugins.

tape machine plugin
![tape-emulations-kramer](https://cloud.githubusercontent.com/assets/8137561/6427233/68461394-bf40-11e4-9296-3f9b30b75767.jpg)
The tape machine plugincould use a playback speed knob. What is the playback speed knob, It slows down or speeds up the sample playback and drops or highers the pitch by the same amount. The pitch knob of the AFP is not affected this more for recreating the when in the old days when someone would take the tape machine and record at one speed and then play it back at another speed.

**Comment by badosu** [comment]
I don't know what you're trying to simulate but you can use the included Calf Vintage Delay.

Setting Medium to 1 you have "Tape" and setting to 2 you have "Old Tape".

You also can have tape saturation with TAP TubeWarmth.

Other people may be able to provide further help, try posting this question on http://lmms.io/forum

**Comment by Reaper10** [comment]
The tape machine plugincould use a playback speed knob. What is the playback speed knob, It slows down or speeds up the sample playback and drops or highers the pitch by the same amount. The pitch knob of the AFP is not affected this more for recreating the when in the old days when someone would take the tape machine and record at one speed and then play it back at another speed.

**Comment by tresf** [comment]
GET OUT
