### ISSUE TITLE
extension of a synth suitable for electronics edm house / progressive house sounds of the moment because we are already very harmonious but are similar to the old 90'dance or trance music.

### ISSUE THREAD

**Issue by Mark0001** [LMMS/lmms#1817]
Hail to the community of LMMS wanted to propose to implement a synth that comes close to the electronics of the songs of the top dj Dyro maybe not accurate but a synth / oscillator that produces a typical synth style EDM because the synth that there are very similar to 'eurodance and trance music of the 90's, thank you and good evening everyone.

**Comment by rubiefawn** [comment]
It's not about the synth, it's about what you can synthesize. ZynAddSubFX, while difficult to learn and use, can definitely produce these sounds and is built in to LMMS. Synth1 is a great VST for this kind of stuff too. Play around with those and you'll get the sounds you're looking for.

**Comment by rubiefawn** [comment]
Here's a link to the first ZynAddSubFX Tutorial: https://youtube.com/watch?v=M_oLSb5DIpM
Here's where you can download Synth1: https://daichilab.sakura.ne.jp/softsynth/index.html

If you have LMMS, you already have almost everything you need to get those sounds.

**Comment by tresf** [comment]
Duplicate of #1780

**Comment by tresf** [comment]
@Mark0001 we love the compliments, but you are failing the very basic requests made in #1780, namely https://github.com/LMMS/lmms/issues/1780#issuecomment-75541519.  Please use your existing bug reports to clarify your enhancement request with specific goals we can address.  Otherwise, we're just chatting, and we already have a [place](https://lmms.io/forum) for that.

**Comment by badosu** [comment]
>  Otherwise, we're just chatting, and we already have a place for that.

@tresf You should pay a visit for us at #lmms on Freenode. It's been an active place for discussions.

http://webchat.freenode.net/?channels=lmms

**Comment by tresf** [comment]
> @tresf You should pay a visit for us at #lmms on Freenode. It's been an active place for discussions.

If there is a specific discussion you prefer my input on, please drop a message in email.  :+1:

**Comment by badosu** [comment]
Not really, it's just that since you coordinate so much stuff outside technicalities for LMMS it would help to understand and achieve our goals for the future of lmms.

@curlymorphic is there and @diizy is sometimes as well.
