### ISSUE TITLE
Haiku build support

### ISSUE THREAD

**Issue by SeanCollins** [LMMS/lmms#1820]
I recently tried to build lmms on Haiku os, I ran into numerous cmake issues with finding the installed librarys for QT. Haiku has a customer package manager which may be cuasing some issues. 

any help appreciated, in fact a functioning daw may get some haiku devs to kick back code to the lmms project they are fairly good about upstreaming patches etc.

**Comment by tresf** [comment]
@SeanCollins, thanks for contacting us.

Haiku (BeOS) may be quite the challenge.  KDE seems to have an [available port](http://tiltos.com/drupal/node/17) (dated article), but if there isn't an easy way to meet the development libs, you may find yourself writing a bunch of curl or wget scripts to snag and extract the build deps.

Finding [QT Creator success](http://i.imgur.com/rxHDFAX.png) may be a good step as well due to the QT requirements to build GUIs with the IDE.

This may will be a long road.  When we ported to OSX it took about a month and most of the legwork had already been done by the MacPorts community.   Good luck and please post your progress here.

On a side note, what I found very valuable was creating a github wiki article documenting my trial and error.  It makes it nice to be able to reference an exact command or error message.

**Comment by SeanCollins** [comment]
I was unaware of the requirement for the KDE librarys, Haiku does have support for QT4.8 however and SDL. 

the issue I was encountering was that the cmake engine could not find the QT librarys, I expect this is due to the paths to these librarys being potential hard-coded in some part of the cmake build files etc.

**Comment by tresf** [comment]
> the issue I was encountering was that the cmake engine could not find the QT librarys, I expect this is due to the paths to these librarys being potential hard-coded in some part of the cmake build files etc.

If I understand correctly, it is quite the opposite.  CMake itself may be looking in specific locations for QT, but LMMS should be using your defaults.

I believe this to be the line that locates QT:

https://github.com/LMMS/lmms/blob/master/CMakeLists.txt#L117

On Mac, I had to add the MacPorts directory manually per:

https://github.com/LMMS/lmms/blob/master/CMakeLists.txt#L57

More information here (QT5, but most of it should apply): http://doc.qt.io/qt-5/cmake-manual.html

You may also want to engage the Haikuports community:  http://haikuports.org

-Tres

**Comment by tresf** [comment]
Also, I believe @eagles051387 and a few others have used the Gentoo `portage`, which Haikuports claims to be a very similar process.

**Comment by SeanCollins** [comment]
I geuss my next question is how do I get cmake to detect the QT library's ? Also does it need the full QT dev package or will the existing libs be good enough ?

**Comment by tresf** [comment]
> how do I get cmake to detect the QT library's

For starters you could add them to your environment and see if CMake picks them up... 

```bash
$ LIBRARY_PATH=/foo/bar:$LIBRARY_PATH 
$ export LIBRARY_PATH 
```

And for headers you could try:
```bash
$ C_INCLUDE_PATH=/foo/bar:$C_INCLUDE_PATH
$ export C_INCLUDE_PATH
$ CPLUS_INCLUDE_PATH=/foo/bar:$CPLUS_INCLUDE_PATH
$ export CPLUS_INCLUDE_PATH
```

Then call `cmake`, etc.

If this works, we can add them to our `CMakeList.txt` file permanently, but this is really dependent where the OS puts them by default. :+1: 

IIRC, they can also be supplied as parameters to the `cmake` executable via `cmake -INCLUDE=/foo/bar` or whatever.

**Comment by SeanCollins** [comment]
so if I understand you correctly, we will need the QT development headers ? this is going to be issue number to get resolved as the current QT package does not contain the QT headers AFAIK. 

I will work to get that resolved and report back once that is handdeled correctly.

**Comment by SeanCollins** [comment]
https://github.com/qt-haiku/qt4/issues/8

**Comment by tresf** [comment]
Just a quess... perhaps the `dev-qt` package?

http://ports.haiku-files.org/wiki/dev-qt

> so if I understand you correctly, we will need the QT development headers ? this is going to be issue number to get resolved as the current QT package does not contain the QT headers AFAIK.

You could always wget and untar the matching source in a script driectly from qt.io if you needed to, no?

**Comment by eagles051387** [comment]
What package management system does haiku use?

On Wed, Mar 4, 2015 at 2:51 PM, Tres Finocchiaro <notifications@github.com>
wrote:

> Also, I believe @eagles051387 <https://github.com/eagles051387> and a few
> others have used the Gentoo portage, which Haikuports claims to be a very
> similar process.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LMMS/lmms/issues/1820#issuecomment-77160556>.
>



-- 
Jonathan Aquilina

**Comment by waddlesplash** [comment]
@eagles051387 @tresf Sorry about @SeanCollins, it appears he doesn't know how to properly set up his build environment. I'm one of the lead porters at HaikuPorts, and am currently the maintainer of the Haiku port of Qt.

Does LMMS really require KDE? Because I have a half-working port of KDE4, but it crashes on startup for pretty much anything, so avoiding that would be nice. Otherwise, we may have to wait for Qt5/KF5 on Haiku to do a port.

**Comment by tresf** [comment]
> Does LMMS really require KDE?

No, it runs just fine without the KDE Desktop (we port to Linux, Windows and OSX).

Of course... It does require QT, but I'm sure you knew that. :)

> it appears he doesn't know how to properly set up his build environment.

That's fine. We don't mind helping him with that, we just don't know enough about his setup.  If we can provide steps to make compilation on BeOS/Haiku easier we'd be happy to host them on our wiki. :+1: 

-Tres

**Comment by tresf** [comment]
On a side note, I was in @SeanCollins's same position when we ported to MacOS (I didn't know the first thing about setting up a build environment), so we welcome the conversation here... If he has these questions porting to a new platform, it is very likely others will down the road. :+1:

**Comment by waddlesplash** [comment]
> That's fine. We don't mind helping him with that, we just don't know enough about meeting dependencies on the OS. If we can provide steps to make compilation on BeOS/Haiku easier we'd be happy to host them on our wiki. :+1:

All of the dependencies are already met, aside from a configuration error in our FFTW port which I am fixing atm. After that I'll push a recipe to our portage repository.

**Comment by tresf** [comment]
> All of the dependencies are already met, aside from a configuration error in our FFTW port which I am fixing atm. After that I'll push a recipe to our portage repository.

Terrific!  Do you have a wiki area you maintain these things so that we can link to it from our [downloads page](https://lmms.io/download/#linux)?

-Tres

**Comment by waddlesplash** [comment]
> Terrific! Do you have a wiki area you maintain these things so that we can link to it from our downloads page?

Yes, although it's mostly for developers. I'll upload a package to our main package repository, so it'll appear in the software center.

**Comment by tresf** [comment]
:+1:

**Comment by badosu** [comment]
:+1: Really excited about this :-)

**Comment by waddlesplash** [comment]
OK. As it turns out, there are a few quirks in the LMMS build system & source files that Haiku doesn't like. Most of these aren't specific to Haiku, so I'll send a pull request your way once I get through all of them.

**Comment by SeanCollins** [comment]
thanks for all the help waddlesplash ! anything I can do to help ?
