### ISSUE TITLE
Recursive path for VST folder search with symlinks?

### ISSUE THREAD

**Issue by mikobuntu** [LMMS/lmms#1821]
Hi I am almost sure that in older versions of LMMS Stable branch I was using my hidden ~/.vst folder for my VST search path, which in turn had a symlink set to my ~/vst folder, which was also searched.
Now if i set ( which has to be done manually i.e the GUI does not allow hidden file search afaik ) only those files in ~/.vst are listed as plugins. Basically the symlink is ignored
I believe the correct behaviour should be to search through both/all recursively.

thanks Mikobuntu ;)

**Comment by tresf** [comment]
> the GUI does not allow hidden file search afaik

This is probably a desktop setting.  Do you feel this should be changed? (I don't)

> the symlink is ignored

Are you saying this won't work when `/home/tres/symlink` is used as the VST path?

`/home/tresf/symlink` --> `/home/tresf/.wine/drive_c/Program\ Files/Steinberg/`

IIRC, a symbolic link should be transparent to C++, it should treat it as another folder.

-Tres

**Comment by mikobuntu** [comment]
This is probably a desktop setting. Do you feel this should be changed? (I don't)

True perhaps that should remain to not allow access to hidden files through the menus, now that you mention that. A user with such knowledge will be able to easily know how to access their hidden files.

   Are you saying this won't work when /home/tres/symlink is used as the VST path?

Yes here is my example in the LMMS :- 

![vstpath](https://cloud.githubusercontent.com/assets/335217/6489531/f0dcbd62-c296-11e4-8441-9b4784bb27b8.png)

* Note that i try setting the path ~/.vst without the trailing slash, but it is added autoatically on restart *

and my local path is :- 

mikobuntu@mikobuntu-MS-7721:~/.vst$ ls -la | grep vst
lrwxrwxrwx   1 mikobuntu mikobuntu       19 Feb 11  2014 vst -> /home/mikobuntu/vst


~/.vst is used by most other Linux audio software as a VST/(i) search path and it is documented to use symlinks from there to other folders as they will be also searched.

thanks @tresf

**Comment by tresf** [comment]
Hmm... `stable-1.1`, no issues with `~/.vst` sysmlink.  I'll upgrade and see if we broke it. :+1: 

![image](https://cloud.githubusercontent.com/assets/6345473/6490411/21bb33c8-c274-11e4-8dd2-cd8e1aff23b1.png)

![image](https://cloud.githubusercontent.com/assets/6345473/6490441/5ebcd93e-c274-11e4-956d-8ca2dc617143.png)

**Comment by tresf** [comment]
Works fine in master, even in a subdirectory (Ubuntu 12.04).. Are you sure this isn't a problem on your end @mikobuntu ?  Perhaps you have something wrong with your symlink (permissions, etc?)

![image](https://cloud.githubusercontent.com/assets/6345473/6490657/e25f75c0-c275-11e4-8899-e81fa68017ab.png)


-Tres

**Comment by mikobuntu** [comment]
@tresf  I will check this soon as I am not my main box and report back thanks :)

**Comment by mikobuntu** [comment]
@tresf  I have full permissions on my ~/.vst and ~/vst files. I also deleted and created a fresh ~/.vst symlink, but still the same outcome. I also tested by creating a symlink from ~/lmms/samples/ to my main sample folder ~/samples/ and this works fine i.e LMMS shows all my samples in the browser.

mikobuntu@mikobuntu-MS-7721:~/lmms$ git status
On branch stable-1.1
Your branch is up-to-date with 'origin/stable-1.1'.

**Comment by tresf** [comment]
Oh... I was testing master.  I don't believe we support recursive searching in stable-1.1 yet.

**Comment by DomClark** [comment]
Can this issue be closed now? Recursive searching is supported in `stable-1.2` and `master`.

**Comment by tresf** [comment]
> Looks like it to me.

👍
