### ISSUE TITLE
FX Chain /sends routing chain/  I/O tab

### ISSUE THREAD

**Issue by Reaper10** [LMMS/lmms#1823]
The FX Mixer routing could be inproved by using a routing box where the rouding knob is now on the mixer strip, you can see all of the routing  boxs on all of the mixer strips at all times . If you add a rounding box you can see all of the tracks that are routed to a track at one time and change how much of the track is being sent to the other tracks at all times.

The Routing Box 
![rouding box](https://cloud.githubusercontent.com/assets/8137561/6492135/b29f4eee-c277-11e4-98cf-f1da5314cf85.png)

How to set up:

1 select all the tracks to be rouded.
2 click the add send button of the tracks rouding box that you want to send to.
Your all done.

The Send

![send](https://cloud.githubusercontent.com/assets/8137561/6492128/a4910b3a-c277-11e4-8854-f5477a369653.png)

To remove the send right click the track send then click the delete option in the menu.

To move the sends around in the  rouding box right click the track send then click the move up or move down options.
To adding send chain box like this
<img width="127" alt="2d4972d2-4522-11e5-87bc-e25344e1bbb5 1" src="https://cloud.githubusercontent.com/assets/8137561/9332761/db44d854-458b-11e5-9d9c-777f69f15359.png">

you just need to add Fx chain / Send chain tabs like this 
<img width="184" alt="117dad2e-4523-11e5-9f1b-345d74ac8647 1" src="https://cloud.githubusercontent.com/assets/8137561/9332806/1a50042e-458c-11e5-8458-b2d638fc7378.png">

The I/O tab 
<img width="367" alt="untitled" src="https://cloud.githubusercontent.com/assets/8137561/9864443/4f991ed4-5b0f-11e5-8644-6c396e1005fc.png">

The I/O tab has:
1 audio input selector window /LED read out box, audio input gain knob 
2 Output routing chain
I don't know what the Output boxes should look like any, ideas?

**Comment by tresf** [comment]
Are you talking about moving the SEND from above the FX channel to over in the FX Chain?

**BEFORE**
![image](https://cloud.githubusercontent.com/assets/6345473/6492433/8aed812c-c281-11e4-9093-3d0599010c32.png)

**AFTER**
![image](https://cloud.githubusercontent.com/assets/6345473/6492597/e9366c66-c282-11e4-9fca-535c462495cc.png)

**Comment by mikobuntu** [comment]
@tresf  I think I understand what the OP is asking for, not moving of the actual knob, but extra functionality to show the full routing of sends from the chosen FX channel... if so this could be realised through a list, perhaps by some context menu item in the mixer strip ?

**Comment by tresf** [comment]
> Reaper10Reaper10 closed this just now

??

**Comment by Reaper10** [comment]
you already add what I want with this 
![e9366c66-c282-11e4-9fca-535c462495cc 1](https://cloud.githubusercontent.com/assets/8137561/6532142/f33f7450-c403-11e4-99d6-91d7d3b4d285.png)  thanks:)

**Comment by tresf** [comment]
@Reaper10 that is just a mock-up...

**Comment by badosu** [comment]
@tresf I don't understand how this is additional functionality, isn't this rack just a listing ot the mixers that send to the current channel?

The knobs for adjusting this already exist.

**Comment by tresf** [comment]
From what I'm reading it is just an alternate way to display what we already have.

**Comment by badosu** [comment]
Ok, I was just trying to understand.

**Comment by Reaper10** [comment]
When this added to the LMMS mixer you can add a pan knob and LED ring where the send is right now
![8aed812c-c281-11e4-9093-3d0599010c32 1](https://cloud.githubusercontent.com/assets/8137561/9340893/333f05f8-45b8-11e5-8436-e2b3441f187b.png)

**Comment by Umcaruje** [comment]
>When this added to the LMMS mixer you can add a pan knob and LED ring where the send is right now

No. There is no indication this will be added into LMMS. This is just an idea. You can't expect anyone to fulfill any of your requests. Also, we had this discussion before, and it was agreed that there won't be a pan knob in the mixer. If you want a pan knob in your mixer, go learn C++ and Qt and fork LMMS and implement it yourself. 

If you keep bumping your closed issues and cross-referencing them, I'll start closing and locking them one by one.

**Comment by musikBear** [comment]
@Reaper10  - there is *no reason* for a pan knob, you can create you own panning on a FX-mixer channel by using the stereo-matrix-plugin. That way you can get exactly what you want in that respect.

**Comment by Reaper10** [comment]
The I/O tab has:
1 audio input selector window /LED read out box, audio input gain knob 
2 Output routing chain
I don't know what the Output boxes should look like any, ideas?

**Comment by tresf** [comment]
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.
