### ISSUE TITLE
LMMS Pitch Adjuster  and Voice Synth plugin Instrument

### ISSUE THREAD

**Issue by Reaper10** [LMMS/lmms#1830]
LMMS could use a  pitch adjusting and voice synth plugin Instrument I got the idea after seeing this https://www.youtube.com/watch?v=dr6LdmW7VYc
how you use it:
https://www.youtube.com/watch?v=gdJxuQewngs
https://www.youtube.com/watch?v=9EnLXNTxDqE
I don't if this possible it's just an idea.

**Comment by badosu** [comment]
It is possible, but should not be on the scope for LMMS but for a plugin that could be used together with.

**Comment by tresf** [comment]
@badosu is completely correct.  If you're looking for voice altering plugins for LMMS, please locate a 3rd party plugin (probably a VST) that can do what you are looking for.

Robot voice: (AM Pitch Shifter)
https://www.youtube.com/watch?v=VZMvqqHVxII

Vocoder/Talkbox:
https://www.youtube.com/watch?v=rSqorcfHgxc

Pitch Corrector:
https://www.youtube.com/watch?v=cIth24qAI-c

Please also feel free to create your own howto videos.  We are in need of footage for our LMMS channel. :)

Closing as wont-fix.
