### ISSUE TITLE
Better Save As/Open/Browse Dialog

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms#1834]
![screen shot 2015-03-07 at 8 51 57 am](https://cloud.githubusercontent.com/assets/6345473/6541558/3eee0bfc-c4a7-11e4-825d-74e5e44099b0.png)

This is a placeholder to offer some enhanced features to our "Save", "Open" or "Browse" dialog, which can be used to browse for a project, plugin, sample, preset.

Ardour is depicted above because it fairly feature complete and serves as an example of: sample playback, tag support, 3rd party web service integration, copy-to-project abilities.

---

**Basic Enhancements**
- [ ] Preview samples/presets/plugins before opening (similar to the [File Browser](https://cloud.githubusercontent.com/assets/6345473/6541604/985577f0-c4a9-11e4-9cdd-3cf1a7a6026a.png))
- [ ] Custom icon rendering (similar to the [File Browser](https://cloud.githubusercontent.com/assets/6345473/6541604/985577f0-c4a9-11e4-9cdd-3cf1a7a6026a.png))
- [ ] Display format, quality settings
  - Format:  WAV, OGG, etc
  - Sample Rate: 48,000 Khz, etc
  - Channels: 1, 2, etc
  - Length: 1:43 min, 5.2 sec, etc
- [ ] Display loudness / output meter
- [ ] Better cross-platform error messages for invalid file names (#1831, #671)

**Future-map / Advanced Enhancements**
- [ ] Add ability to copy files to a working or project directory
- [ ] [LSP](https://lmms.io/lsp) integration #661
- [ ] [Freesound](https://www.freesound.org/) or 3rd party integration
- [ ] Project preview support

-Tres

**Comment by mikobuntu** [comment]
@tres This is a good placeholder ;) 

Some time ago, I think it was the 0.9 master branch did have LSP import support, so perhaps the actual code would not be too hard to merge into master branch at some point?

**Comment by tresf** [comment]
> Some time ago, I think it was the 0.9 master branch did have LSP import support, so perhaps the actual code would not be too hard to merge into master branch at some point?

Yes, most likely in the 0.4.x branch.  Toby wrote the code and we discussed it quite a bit in #661.

The issues, which I think I covered pretty well in #661 is that our website isn't the place for 100,000 simultaneous sample downloads.  We should leverage a Content Delivery Network for that, which can have high costs associated per [Cloud Comparisons](https://github.com/LMMS/lmms/issues/661#issuecomment-70510309).

So if we turn this on, we should probably focus on a robust, secure and readily available LSP first, then we can discuss how to hook into it with C++ afterward.

**Comment by musikBear** [comment]
File Save As has had the strange double option : mmpz mmp
It confuses new users
I suggest 3 separate options in the dialog:
![seperate options](https://user-images.githubusercontent.com/6662066/27391592-9d7c69f2-56a4-11e7-9e0e-cdcc5a5a8de9.PNG)

down the line an option for midi -or maby that should be in **export**, though midi is a valid import format, so it also make sense to have midi in Save As, imo

**Comment by tresf** [comment]
Agreed, `mmp` is very useful for debugging, should be more obvious how to select it.

**Comment by tresf** [comment]
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.
