### ISSUE TITLE
New Presets

### ISSUE THREAD

**Issue by Reaper10** [LMMS/lmms#1840]
This is not a bug, this is for new presets for LMMS.  I hope to have more out soon.

TripleOscillator Drum Set
https://drive.google.com/folderview?id=0B0Ar66xX6aiRfk5jWWlYRHh0V3U4UUJPVkJvVEtKUThsc21iZnRpNDlCdHdxV0RCdjF0Wjg&usp=sharing
Synth Drum Kit Track Template
https://drive.google.com/file/d/0B0Ar66xX6aiRU1A1WjJvcEd5VFU/view?usp=sharing

**Comment by tresf** [comment]
Thanks @Reaper10!  We normally do these things as pull requests (requires the GitHub desktop application).

Did you make these yourself?  What license are they released under?  Thanks!

**Comment by Reaper10** [comment]
made these from shrach

**Comment by tresf** [comment]
Thanks.  We'll take a look.  In the mean time, take a look at the GitHub client, fork our repository and find a place you'd like these included in our `/data/presets/` folder. :+1: 

@Sti2nd who's helping approve presets and samples these days now that StakeoutPuch and HDD are gone?

**Comment by Reaper10** [comment]
how do you add the folders all I have is xpf files?

**Comment by Sti2nd** [comment]
> who's helping approve presets and samples these days now that StakeoutPuch and HDD are gone?

I think for now if more than one person approves of the presets and no one have any objections they are good to go.

More information: The last time we spoke about this was in the discussion about licencing of demo songs. Several ways to pick out good presets were proposed, I especially remember the competition idea. That idea however required us to settle the licencing debate, and we ended up with postponing the CC0 effect until 1.1.2.

Someone should perhaps write a wiki with guidelines for how one shall approve presets and demo-songs. I believe I will try to arrange a competition/challenge for presets and/or demo projects. Why not just steal good presets from the lsp? Unfortunately lsp allow licencing the presets, so by submitting the preset to such a challenge the licence will be changed to CC0. Maybe LMMSc can be a tool we can use to get presets and demo projects into LMMS? 
Btw: If someone want to have fun, you are very welcome to be the next host of LMMSc, contact me, or point a finger at someone you think want to.

**Comment by Sti2nd** [comment]
And now my rating of the presets. I like Hi Hat Open and Lo Tom. Are the release supposed to be 0 on Mid Tom? Sounds weird. Anyway I am personally not a fan of hardcore trance, hardstyle or electronic sounding drums so I declare myself incompetent. I would probably never use these presets. If they had been for Kicker I would have liked them more because I like using Kicker.

**Comment by Reaper10** [comment]
If no one likes them I'll take then down.

**Comment by Reaper10** [comment]
Synth Drum Kit Track Template
https://drive.google.com/file/d/0B0Ar66xX6aiRU1A1WjJvcEd5VFU/view?usp=sharing

**Comment by Reaper10** [comment]
hope it's usefull

**Comment by musikBear** [comment]
I would love to hear  these (all you made) just because one user dont use a certain type of preset, does not mean that it is a uninteresting preset :)
I cant build (no env), so if someone would make a youtube or likevice demo, that would be super! -or can these presets be tested in other ways, like vst-host ? -or similar ?

**Comment by Sti2nd** [comment]
> just because one user dont use a certain type of preset, does not mean that it is a uninteresting preset

exactly, that was what I was saying

**Comment by Reaper10** [comment]
I mad all of by ear.

**Comment by Reaper10** [comment]
Anyone like Marilyn Manson's Sweet Dreams I'm working on a Keyboard Rig Track Templates?

**Comment by tresf** [comment]
> Anyone like Marilyn Manson's Sweet Dreams I'm working on a Keyboard Rig Track Templates?

Very cool.

> I would love to hear these (all you made) just because one user dont use a certain type of preset, does not mean that it is a uninteresting preset :)

> I cant build (no env), so if someone would make a youtube or likevice demo, that would be super!

They are just TripleOscillator presets... just download them and try them out.

-Tres

**Comment by musikBear** [comment]
>They are just TripleOscillator presets... just download them and try them out. (no build environment is needed)

oh im so dumb.. i .. thought .. well  since it was here on tracker ..new **preset** ..oki  .. :dancer:

**Comment by tresf** [comment]
> @Reaper10 I think a super place for all announcement of new presets would be in the facebook-group! There you will get emediately reviews, and add to the activities in that community, in a great creative way!

Are you sure about that?  AFAIK, Facebook is kind of limited in regards to sharing stuff like this, no?

-Tres

**Comment by Sti2nd** [comment]
If he want's feedback, sure just post the presets anywhwere on the internet, I don't think devs or the people approving presets are going to look all over the internet for LMMS presets.

**Comment by tresf** [comment]
> If he want's feedback, sure just post the presets anywhwere on the internet,

That's not what was recommended... musikBear recommended the Facebook group, which is what I was questioning.  Furthermore "anywhere on the internet" too vague.  If we have some resources to direct him to, we should share. :)

**Comment by musikBear** [comment]
yes, i dont think you can 'put' anything **up** on faxebook, and that was not what i meant. 
a heads-up & simple description of the new presets, plus a link to a dl -*That* was my context
Reaper can tell our facebook-group-users about his new presets, and the users /followers can dl them -  from f.i. LSP :) The group gets more activity, and user generated content, and Reaper get his presets noticed, and perhaps reviewed in hours -winwin

**Comment by tresf** [comment]
> Reaper can tell our facebook-group-users about his new presets

How exactly?

**Comment by Umcaruje** [comment]
A bit off-topic but LMMS has a Facebook group? Since when? 

We do have an official Facebook page, but that isn't very similar to a group.

**Comment by Sti2nd** [comment]
I don't get this with Facebook or any other sites. If someone wants to include presets in LMMS they make a PR here on github, alternatively asks someone else to do it. 

So you @musikBear are suggesting that instead of including them in LMMS he can show them off somewhere else? Of course! I thought you wanted these presets in LMMS, that is why I was confused.
