### ISSUE TITLE
presets-tab-focus are not preseved when presets are closed/ reopend

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#1843]
to reproduce
Open any preset
click on any of the tabs (f.i. 'FX') ..ofcause that opens the FX-tab
Toggle the preset out of focus, or cloce it on the 'x'
Reopen the preset
Focus is now not on the FX-tab, but has reverted to 'PLUGIN' tab
imo, the focused tab should be the one that the preset had, when it was toggled down/ closed. That will most often be where the user are working
This has connections to
https://www.youtube.com/watch?v=2xQIJ3EHV8M

**Comment by tresf** [comment]
You want the instrument tab to remember the last place you were?  Tempted to mark this as wont-fix.  Interested to hear other's opinions.

-Tres

**Comment by Sti2nd** [comment]
I agree on wont-fix, mostly because I have no clue what he means. This is not the same as http://linux-multimedia-studio-lmms.996328.n3.nabble.com/discussion-of-default-workflow-form-focus-td11666.html

**Comment by tresf** [comment]
Paraphrase.... 


If you close 3xOsc on the Env tab, @musikBear  wants it to reopen on that tab.  Frankly I don't mind the existing behavior. but I'd like to know the consensus. :)

**Comment by badosu** [comment]
Well, this feature request makes some sense, it's just that it's very superfluous, but valid. :-)

**Comment by mikobuntu** [comment]
I agree that it could be a useful FR. Perhaps best to have it an option in the setup configuration window tho.

**Comment by softrabbit** [comment]
Just unfocusing or even minimizing the preset window doesn't switch tabs for me, I have to close and reopen for that to happen (Ubuntu, LMMS master branch). @musikBear, does it really work as you described on Windows?

IMO remembering the tab selection is a good idea. Clearly an improvement and a pretty minor detail too, so it should be OK without a setup option.

**Comment by musikBear** [comment]
@softrabbit 
>does it really work as you described on Windows?

Yes, if i use the *instrument-button* in song-editor to toggle the instrument up/dn (which in fact IS a *close-event!*) then the preset reverts to PLUGIN tab -But that should *not* be confused with *loosing focus*! In *that* situation nothing has happend to the preset in question, it is 'just' overlayed by a different form, so ofcause *loosing focus* does absolutely nothing to the preset
(Can actually also be seen in the video)
I gues that it this sentence that is difficult to understand:
>Toggle the preset out of focus, or cloce it on the 'x'

Because i write *toggle* it is an *active* user interaction with the preset -eg a mouse-click *on* the toggle-button. How that can be confused with a passive accidential form-overlay, where the user do *not* actively interact with the preset-object ..?
Well, thats really a surprice to me

..except i misspelled cloce .. close cloce ... not that hard to understand -is it?

**Comment by softrabbit** [comment]
@musikBear, chill! Looks like I misread "out of focus" as actually meaning the window losing focus. Thanks for the clarification.

**Comment by SecondFlight** [comment]
Closing in favor of #3646 which is significantly more readable.
