### ISSUE TITLE
Intermittent crash, possibly browser related

### ISSUE THREAD

**Issue by Radiarc** [LMMS/lmms#1845]
I'm currently running Linux Mint 17.1, and after having used LMMS 1.0.0 without any issues (even with other processes such as Skype running), the switch over to 1.0.3 has caused random crashes without any warning; the window simply force quits on its own.
I've left a 3-vst project running overnight to see if it'd crash, but it was fine, so I'm beginning to wonder if it's just an issue of having so many vsts running at once.
It'd be different if it just froze or sound stop working because I've had those issues in the past (although that was months ago), but when it crashes this time, it's just not there.

So far it's only crashed on this 14-vst project I'm working on; all crashes I've had only occurred when I had Firefox open, and my most recent crash was during a simple page refresh, however, the first crash happened to me mid-work after a brief pause during playback.
In the past, I've had my CPU spike during playback due to so much going on at once, but playback has never completely stopped and caused the program to quit all on its own.

**Comment by Sti2nd** [comment]
> such as Skype

Wow, many users have not managed to do that, and Skype just updated to a new version, did it do that for you too?

It does sound like the CPU spikes are the problem, and many can confirm that if the CPU spikes too much LMMS... crashes.

**Comment by musikBear** [comment]
@Radiarc these spikings could happen if you have **auto-save** *ON*. You should look in *Settings* and if it is ON, toggle it OFF

**Comment by tresf** [comment]
@Radiarc nice to see you on the bug tracker.

As you're well aware, what you are describing needs to be reproducible for us to offer any insight as to the cause.

From my experience, flash can have playback issues in Linux on its own without LMMS running in the background, so a first step may be to disable that in the browser and see if it helps.

Another option perhaps is to write a shell script to launch LMMS from terminal and pipe its console output to a file so that you can send us the logs when the crash occurs.  Naturally, running a development build helps in this regard, but with 14 VSTs I'm sure you could benefit from the optimizations that the normal build has.

Unrelated, but FYI, we're having a music competition.  Nudge. :)

**Comment by tresf** [comment]
Also, this may not be related, but I've noticed on Apple, using a 3rd party HDMI volume control plugin (SoundflowerBed) causes instability in the software.  This reproducible crash on Apple might be an area we can investigate in code to try to catch the exception as it occurs and prevent a hard crash. :+1:

**Comment by Radiarc** [comment]
Is there any way I can just revert completely back to 1.0.0?
I've even got the files for it, but the last time I forced 1.0.0 through a package manager, vestige wasn't included so it was essentially useless.
I've found the crash isn't browser-related as it's happened without having anything else open at all.
It's crashed during loading, during playback, and during idling, but there's absolutely no consistency whatsoever other than it crashes without an error message.

**Comment by eagles051387** [comment]
What would help us to truly solve this problem if you could try and get us
a back trace to help us determine why this is happening. Also what
operating system are you on?

On Thu, Mar 12, 2015 at 6:27 AM, Radiarc <notifications@github.com> wrote:

> Is there any way I can just revert completely back to 1.0.0?
> I've even got the files for it, but the last time I forced 1.0.0 through a
> package manager, vestige wasn't included so it was essentially useless.
> I've found the crash isn't browser-related as it's happened without having
> anything else open at all.
> It's crashed during loading, during playback, and during idling, but
> there's absolutely no consistency whatsoever other than it crashes without
> an error message.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LMMS/lmms/issues/1845#issuecomment-78425987>.
>



-- 
Jonathan Aquilina

**Comment by Radiarc** [comment]
Linux Mint 17.1.

If you can give me instructions in getting a back trace, that'd be fantastic; I've done a bit of looking on how to do it, but I wasn't able to understand much of anything because I don't work with code.
I'd be more than happy to do it if someone would show me how.

**Comment by Sti2nd** [comment]
What audio back-end do you use? I think I remember something about a user having problem on Mint with VSTs, and we fixed it somehow... So trying to remember

**Comment by musikBear** [comment]
**Forum** User **vlad1777d**  had Feb 16  Linux Mint 17 running, and working with VST *Kontact* 
If @Radiarc send him a pm **on forum**, then vlad could explain his mint 17 audio-set-up. Perhaps that could work for @Radiarc too.
Thread in question: 
https://lmms.io/forum/viewtopic.php?f=4&t=1686
2. post

**Comment by badosu** [comment]
@Radiarc 
> If you can give me instructions in getting a back trace, that'd be fantastic;

Basically:

1. Install gdb, I don't know what package it is on linux mint though. Did a bit research but did not find it.
2. Open a terminal, run `gdb lmms`. When gdb prompts you, type `run`, hit enter.
3. Run lmms like you would, when it crashes now instead of closing the window it will hang up. This means that control has passed to gdb.
4. Switch to the terminal running gdb. If it captured the crash, it will offer a prompt. Type `backtrace`, hit enter. Copy the output and paste it on pastebin of https://gist.github.com/
5. Share the link of the pasted output here.

**Comment by eagles051387** [comment]
Amadeus you dont need to install gdb by default alot of distros I know have
it already installed.

On Thu, Mar 12, 2015 at 12:51 PM, Amadeus Folego <notifications@github.com>
wrote:

> @Radiarc <https://github.com/Radiarc>
>
> If you can give me instructions in getting a back trace, that'd be
> fantastic;
>
> Basically:
>
>    1. Install gdb, I don't know what package it is on linux mint though.
>    Did a bit research but did not find it.
>    2. Open a terminal, run gdb lmms. When gdb prompts you, type run, hit
>    enter.
>    3. Run lmms like you would, when it crashes now instead of closing the
>    window it will hang up. This means that control has passed to gdb.
>    4. Switch to the terminal running gdb. If it captured the crash, it
>    will offer a prompt. Type backtrace, hit enter. Copy the output and
>    paste it on pastebin of https://gist.github.com/
>    5. Share the link of the pasted output here.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LMMS/lmms/issues/1845#issuecomment-78466009>.
>



-- 
Jonathan Aquilina

**Comment by tresf** [comment]
> Amadeus you dont need to install gdb by default alot of distros I know have
it already installed.

IIRC, `gdb` is provided by the meta package `build-essential` which is NOT included by default on Ubuntu and Ubuntu variants such as Mint.

-Tres

**Comment by mikobuntu** [comment]
Possibly use strace. the only thing is, if you do not specify a grep keyword the file can grow so large that it is almost impossible to debug. hers an example of using a keyword "zynadd" being grepped to a txt file >> 
(strace ~/lmms/target/bin/lmms) 2>&1 | grep zynadd | tee /tmp/u

So basically use parenthesis containing "strace" and path to "lmms" binary > "2>&1" << is piping the output of the previous commands >> "grep" your keyword > "tee" to a file in this case /tmp/u 

Hope this helps :)

**Comment by tresf** [comment]
Closing as this is likely sound driver related and its been a month without any further information.

Please feel free to reopen when we have a backtrace pointing to where in our code this is breaking (so that we can evaluate if we have the ability to fix.) :+1:
