### ISSUE TITLE
Wrong sound driver extra options

### ISSUE THREAD

**Issue by M374LX** [LMMS/lmms#1848]
This issue is closely related to #1814.

By opening the settings dialog, changing the sound driver, and then opening the dialog again, the extra options for the sound driver are not the ones for the newly selected driver, but those for the previously selected driver.

For example, if one changes from ALSA to Dummy and opens the dialog again, one now will see Dummy selected, but the options below it are those for ALSA.

**Comment by tresf** [comment]
Perhaps something as simple as a checkbox on the active one, so we can have the best of both worlds?

**Comment by badosu** [comment]
@M374LX Well, the user should restart LMMS to actually have the backend settings changed. It would not make sense to restore the previous settings after the user changed them, specially when we tell on the screen that the user should restart.

**Comment by M374LX** [comment]
The wrong options are shown for the same reason as in issue #1814: values read from the mixer instead of `ConfigManager`. I will create a pull request as soon as possible.

@badosu 
The restart button is a great idea, but what about a rework so that no restart is needed?

**Comment by badosu** [comment]
@M374LX 

> The wrong options are shown for the same reason as in issue #1814: values read from the mixer instead of ConfigManager. I will create a pull request as soon as possible.

I don't understand this, didn't you already fix this behaviour?

>  The restart button is a great idea, but what about a rework so that no restart is needed?

Well, adding a GUI utility is far easier than making the mixer change the backend dynamically, if you think you can do it, I'am all for it :-). But to be frank I don't know if this is feasible/worth it.

**Comment by tresf** [comment]
Closed via #1851
