### ISSUE TITLE
Working on updating/Improving VST and SF logos

### ISSUE THREAD

**Issue by mikobuntu** [LMMS/lmms#1854]
Hi guys.... I am currently working on making replacements for the vst and soundfont logos which are displayed in the file browser.
 Below is how I have the vst logo looking so far, there just needs to be a few adjustments to make it stand out more. 
One problem I am having is scaling my working copy in G.I.M.P from 160px or 320px to 16px ( the default size ) I lose a lot of clarity in the outline mostly.
I have been referencing some of the other "newer" .png like the folder icons etc in the default themes folder and they look like they are drawn using a 1px pencil/brush while working in 100% scale of 16x16px ( which is hard to get the right results especially using angles. ..... soooo basically my question are 

* Does anyone know how to scale down in GIMP, so that everything is drawn in single shaded pixels ?

* How did the original autor create these .pngs, was some vector graphics app used ( which I have very little experience in ) ?

** Note I also think we should use this VST icon ( when completed ) to replace the VeSTige logo as I believe it leans too closely to the original Steinberg logo for possible future copyright infringements ...

Anyway thanks ;)

![newvstlogo](https://cloud.githubusercontent.com/assets/335217/6585127/d0ed3196-c767-11e4-957b-1b4864a2009a.png)

**Comment by tresf** [comment]
Vesa just made these for the 1.1 release.  Prob should run changes past him.

As far as good 16 pixel icons, it is a fine art.  I recommend using inkscape and adjusting the strokes until it works at a small size, but you'll prob still have some undesired antialiasing.

Also consider tagging Rebecca too as she may more small/pixel art tricks.

**Comment by Umcaruje** [comment]
AFAIK most icons are done in inkscape and then exported to the desired size. Using vector graphics would probably fix your problem :)

You can find the source files to all the artwork at [`LMMS/artwork`](https://github.com/LMMS/artwork).

**Comment by mikobuntu** [comment]
@tresf  Cool, yes iirc these were just placeholders, but I will tag @diizy and see his thoughts on this thanks. ;)  
Arrggghhh Inkscape, I will have to use it more often as I never really need to go past gimp for my basic editing needs.
 Ok @Umcaruje I will take a look at the source files now.
And perhaps you could help with my above question https://github.com/RebeccaDeField ? thanks :)

**Comment by Sti2nd** [comment]
> Note I also think we should use this VST icon ( when completed ) to replace the VeSTige logo as I believe it leans too closely to the original Steinberg logo for possible future copyright infringements ...

If you are afraid of that you should probably tell these guys too, that is the host KXStudio uses http://festige.sourceforge.net/

**Comment by mikobuntu** [comment]
@Sti2nd I was actually thinking of doing that. @falkTX please read above regarding my thoughts on VeSTige. thanks :)

**Comment by Sti2nd** [comment]
> Does anyone know how to scale down in GIMP, so that everything is drawn in single shaded pixels

I don't understand what you want. You want it so that when you draw one pixel the rest are unaffected? Use the pen tool, and of course set the size to 1

**Comment by mikobuntu** [comment]
@Sti2nd  I can already do what you mention with the pen tool, It is as @tresf said " it a fine art " drawing in single pixels. One of the questions I was asking... If I make my artwork at 10x scale i.e 160x160 px is there any way to keep from antialiasing so that single pixels are not blurred?

**Comment by diizy** [comment]
Yeah these icons must be made in inkscape. Also you should follow the same style and colour scheme as the other icons.

**Comment by Spekular** [comment]
@mikobunto, if you don't want smooth textures, there's no reason to work at
10x scale. If you change the scaling mode to "nearest neighbor"/"near" or
something similar it'll just take one pixel per area, and be sharper as a
result, but then you might as well work at 16x16 as you lose any detail you
had at the higher resolution.

**Comment by mikobuntu** [comment]
@diizy that's cool, I think I can ( with the help of a few tutorial vids ) work these in inkscape and I will follow the style and colour scheme, thanks ;)  @Spekular .. good to know , thanks ;)

**Comment by Umcaruje** [comment]
@mikobuntu what's the status on this issue?

**Comment by mikobuntu** [comment]
@Umcaruje If you don't mind keeping this one open, I will get to work on it the 1st chance I get ..thanks ;)

**Comment by Umcaruje** [comment]
>If you don't mind keeping this one open, I will get to work on it the 1st chance I get

:+1:

**Comment by Umcaruje** [comment]
As the new theme has uniform new icons for all of the files, I'm going to close out this issue. I really like your Vestige logo design @mikobuntu though. and I think at some point we should replace the vestige logo with it.
