### ISSUE TITLE
I can't see instrument names in ZynAddSubFX's bank

### ISSUE THREAD

**Issue by CrackedP0t** [LMMS/lmms#1856]
Either the text is the same color as the background or the text isn't showing at all.
![zynaddsubfx](https://cloud.githubusercontent.com/assets/6243860/6591410/e295a5b4-c784-11e4-9090-50eacda32204.png)
I tried to use ntk-chtheme to switch the theme, but nothing happened.

**Comment by badosu** [comment]
This is weird, if you click where a preset would be does it get select?

We need to check if they are blended in your theme colors or if your bank is empty, or even if this is a bug on Zynaddsubfx itself.

**Comment by CrackedP0t** [comment]
They get selected fine. ZynAddSubFX is perfectly usable, except I can't see the names and my selection doesn't highlight(not sure if it's supposed to).

**Comment by badosu** [comment]
In this case the problem is probably the incompatibility of your desktop theme and fltk (the toolkit used by Zyn).

If you change your theme does the Presets appear?

**Comment by CrackedP0t** [comment]
Changing the theme doesn't do anything to it.

**Comment by badosu** [comment]
Hmm... I am sorry but I really can't imagine a reason for this to be happening.

**Comment by musikBear** [comment]
known issue 
IF you are on windows, you can hack-fix with a click on *show-pad-synth*
I made a video some weeks back:
https://www.youtube.com/watch?v=foUqtb725JE
Its a bug in zasfx, but they have fixed it, but not in a version that 'fit' to lmms

**Comment by tresf** [comment]
Clarification... We don't know if 2.5 fixed this or not.... 

https://github.com/LMMS/lmms/issues/1001#issuecomment-76601326

**Comment by tresf** [comment]
@CrackedP0t are you using LMMS?

We don't yet ship with the NTK theme (per #713), so I'm not sure how this could be an LMMS bug.  Please explain. :+1:

**Comment by tresf** [comment]
Either way, this is an exact duplicate of #1001.  Closing as duplicate.  I'm tagging @fundamental just in case this is something he's familiar with. :+1:

**Comment by etsnyman** [comment]
This is still happening when one loads ZynAddSubFX inside LMMS. Outside/independantly, there are no issues!

**Comment by tresf** [comment]
@etsnyman we know.  Don't double post please.  If you want to help fix this, tear into the 2.4 source and try some things or help us get 2.5 working.  Zyn upstream isn't going to fix it and 2.5 won't be here for a while, see #1860.
