### ISSUE TITLE
Piano roll: clicks cause Shift+Arrow keys shortcuts to stop working

### ISSUE THREAD

**Issue by M374LX** [LMMS/lmms#1867]
On the piano roll, if one selects notes and clicks on the area below the title bar containing the buttons, the notes are still shown as selected, but the Shift+Arrow keys shortcuts stop working.

**Comment by tresf** [comment]
We have quite a few focus/key listener issues with the software.  :+1:

**Comment by musikBear** [comment]
cant reproduce on win32 1.1.3
I can select any subset of notes
change tools in piano-roll (eg click area below piano-roll tittle-bar)
toggle piano-roll u/d, or click the main-menu ( eg, click on main)
open instruments (click in sidebar)
Notes remain selected, and respond to any combination of ctrl-arrowkeys

**Comment by SecondFlight** [comment]
Commenting to remind myself to attempt to reproduce when I get home.

**Comment by SecondFlight** [comment]
Cannot reproduce in 1.2.0 RC8 or master.

Steps taken to reproduce:
1. Add a MIDI clip to the default TripleOscillator.
2. Add a note.
3. Press ctrl + a to select the note.
4. Click the area below the title bar (shown below):
![image](https://user-images.githubusercontent.com/6700184/54248845-7cfb0980-4514-11e9-99b5-0c30ecf68a6c.png)
5. Press `shift`+`up`, `shift`+`down`, `shift` + `right` and `shift` + `left`. All shortcuts still work.
