### ISSUE TITLE
Enhancement. Consistent behavior on all Items-select-boxes

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#1872]
All of lmms' selects-items (aka 'Drop-down-boxes') allow usage of both left and right mouse, but only some allow the user to scroll the items *from* last item.
In piano-roll *Magnification* and *Q* selects **do** allow last-item-selects. but *Note* *Scale* and *Chord* selects, does not. imo select from *both* the top and the bottom, is a nice feature, and all *selects* should behave that way.

**Comment by tresf** [comment]
Can you please reword this?  I can't understand what you are describing.

**Comment by musikBear** [comment]
![paste](https://cloud.githubusercontent.com/assets/6662066/6655771/df1805dc-cb0b-11e4-9028-ed6ce070ae3d.PNG)
if you right click on + it scrols from button, if you do it on %, it does not 
Different behavior in select-boxes

**Comment by tresf** [comment]
What is "scrols from bottom?".

**Comment by Sti2nd** [comment]
It is bad wording. When you left click you get the next item on the list, when you right click you get the previous.

**Comment by tresf** [comment]
Ok, thanks for the translation.  Musikbear, can you reword your bug report to explain this?

Also "all items" is a bit broad.  Let's focus on the editor you use the most and progress from there.

**Comment by musikBear** [comment]
:ear: red
sorry - this is invalid. I failed to realize that *Magnification* and *Q* did **not** display **top** item of the list. They display items 3. & 6. pos of resp. lists, So *those* lists are kind of 'shown from inside', Note, Scale & Chord selects shows *top-item*
That is all my fault. The behavior *in same select position!* **is** consistent
my bad :(
