### ISSUE TITLE
Mixer checks for GUI before GUI's initialization

### ISSUE THREAD

**Issue by M374LX** [LMMS/lmms#1878]
We have the following statements in `GuiApplication.cpp`:
```C++
	Engine::init();
	s_instance = this;
```

`Engine::init()` creates a new `Mixer` object, whose constructor contains the following statements:
```C++
if( !Engine::hasGUI() )
{
	m_framesPerPeriod = DEFAULT_BUFFER_SIZE;
	m_fifo = new fifo( 1 );
}
```

`Engine::hasGUI()` is implemented as:
```C++
bool Engine::hasGUI()
{
	return gui != nullptr;
}
```

`gui`refers to `GuiApplication::s_instance`.

As we can see, `Mixer` calls `Engine::hasGUI()` before `GuiApplication::s_instance` is set, which causes it to get a wrong value and consequently set `m_framesPerPeriod` and the FIFO size to incorrect values.

A simple solution is to invert the order of the statements:
```C++
	s_instance = this;
	Engine::init();
```
Nevertheless, a better solution is to decide the number of frames per period outside of `Mixer`, so that is does not need to touch the GUI or even `ConfigManager`.

**Comment by M374LX** [comment]
One more thing I have noticed is this:
```C++
else if( ConfigManager::inst()->value( "mixer", "framesperaudiobuffer"
                        ).toInt() >= 32 )
```

It seems that the minimum number of frames per buffer is 32, but the minimum selectable in the settings dialog is 64.

**Comment by Umcaruje** [comment]
@M374LX Please issue a Pull Request with the appropriate changes, you will get a lot more feedback on this.
