### ISSUE TITLE
Peak Controller needs logscales

### ISSUE THREAD

**Issue by JohannesLorenz** [LMMS/lmms#188]
This is the only way to control a frequency filter via Peak Controller. I hope I can do this before the next release (when will it be?). I might need 1 or 2 days.

Also, I am not sure what role the multiplicator should have for logscales. Please comment on that.

Also, will the GUI team kill me if I say that the background needs to be extended? :)

**Comment by Sti2nd** [comment]
Still not close?

**Comment by badosu** [comment]
Why do you think this should be closed?

**Comment by Sti2nd** [comment]
Cause logscales is implemented, or am I misunderstanding the issue here...

**Comment by badosu** [comment]
I don't guess so, this is the Peak Controller of today:

![2015-01-30-225329_202x157_scrot](https://cloud.githubusercontent.com/assets/347552/5986021/78d812a8-a8d3-11e4-94c3-b7a6fd1502fd.png)

It's not clear to me if it uses logscale (whatever this means) or not.

**Comment by Sti2nd** [comment]
> It's not clear to me if it uses logscale

Another one of my brilliant assumptions when I am tired...

**Comment by unfa** [comment]
Offtopic:

I wonder how hard would it be to give peak controller a wavetable control
allowing for freehand-drawn amplitude response curves to be applied to the
input/output signal (before or after AR envelope follower).
31 sty 2015 02:10 "Stian Jørgensrud" <notifications@github.com> napisał(a):

**Comment by SecondFlight** [comment]
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.
