### ISSUE TITLE
Can't preview ZynAddSubFX patches

### ISSUE THREAD

**Issue by softrabbit** [LMMS/lmms#1880]
In master, click a Zyn patch to preview it and get this in the console:
```
qUncompress: Z_DATA_ERROR: Input data is corrupted
at line 1 column "error occurred while parsing element" 
```
...and 2 message boxes, first the "seems to contain errors" one, https://github.com/LMMS/lmms/blob/043a56591960f4e1b3f329a092edeea37e0670b1/src/core/DataFile.cpp#L828, and then the "does not appear to be a valid file" box, https://github.com/LMMS/lmms/blob/06e1415bbd02a5f3ebc25a1f7154455727765694/src/gui/FileBrowser.cpp#L469 (I'm pretty sure that one was introduced in #1782 )

**Comment by softrabbit** [comment]
So, LMMS tries to open an .xiz file (gzipped XML) through qUncompress, which fails because of the format being wrong. Then the XML parsing fails and so on...

**Comment by tresf** [comment]
@softrabbit Thanks! So that should make it fairly easy... we probably forgot to add that to the XML data types and fall back onto unknown compressed territory.  @curlymorphic that should help point to the problem/solution.

**Comment by tresf** [comment]
Also, we may want to consider making an enum out of our file extensions prior to the 1.2 release... this hard coded XML, MMPZ, MPT, XIZ, XPF stuff could be caught by some select/case statements.
