### ISSUE TITLE
"Mod Wheel" knob on wrench part of Vestige or add Modwheel to front of Vestige?

### ISSUE THREAD

**Issue by davetbass2** [LMMS/lmms#1889]
Hi, 
It was suggested that I add an issue, after posting in the lmms forum

https://lmms.io/forum/viewtopic.php?f=7&t=1717

In order to record and playback mod wheel movements, there has to be a mod wheel knob in the wrench section, most VSTi don't have this

Phutura does, for example:

http://www.phuturetone.com/phutura.php

How could this be explained to a developer so the could add it so it would show up in the wrench section?

**Comment by tresf** [comment]
AFAIK, there is no special knob considerations coded into VSTs, but rather a standard plugin interface.

If we don't expose a certain control, this is a good chance the VST doesn't expose it to us.

There's also the chance that we have a bug.  This is the right place to ask. :)

**Comment by tresf** [comment]
I don't know the Steinberg (VST) interface rules, but I'll quote an article from [JohnnyPumpHandle.com](url=http://www.johnnypumphandle.com/johnny/tutor/Tutor1_Automation.htm)

> Some VST plugins, do not support automation because they were not designed to make their parameters available to the host program.

This likely explains what you are observing.

**Comment by grejppi** [comment]
Mod wheel is a MIDI control. With the exception of pitch control LMMS does not expose any of those to the user.

Related: #1472 (#1159 in particular)

**Comment by tresf** [comment]
Thanks @grejppi.  Closing as duplicate.

@davetbass2, please subscribe to #1472,  #1159 to track progress.
