### ISSUE TITLE
LMMS Instruments Assignable Mod Wheel

### ISSUE THREAD

**Issue by Reaper10** [LMMS/lmms#1890]
Just asking if the LMMS instruments will have a assignable mod wheel built in to them? If not I'll start a mockup.
mockup based on the lfo env tab 
![modwheel](https://cloud.githubusercontent.com/assets/8137561/6956148/4a4916d8-d8af-11e4-9348-ad18c9ff46dd.png)

how to:
1 To assign right click any knob, button or slider. 
2 Click assign to mod wheel.
3 Then go to the mod wheel tab to set the mod slot. To enable or disable a slot press the mod slot button next the name of the mod slot.
4 To assign the Velocity to the right click in a empty space in the mod wheel tab then click Velocity.

how to remove:
 To remove the Velocity or any other one  to the right click in a empty space on the Velocity mod wheel LFO tab then click remove mod slot.
The mod wheel tab can have unlimited mod slots.
![master mod](https://cloud.githubusercontent.com/assets/8137561/6972068/e1e658d8-d946-11e4-81e7-e47ff06ceb16.jpg)
The rage box is a master range box that uses the sitting you have set up in all mod slots.

**Comment by Reaper10** [comment]
do you want me to close this

**Comment by tresf** [comment]
Is this proposal just a quick-access controller/automation dial?

**Comment by Reaper10** [comment]
this is for the mod wheel

**Comment by tresf** [comment]
> this is for the mod wheel

That doesn't answer the question.  I asked you in the other thread too and you said:

> #1890 that mod wheel

If you can't answer a basic question, we won't help.

**Comment by cubician** [comment]
He means the Mod Wheel as in MIDI CC 1.
The thing next to the pitchbend wheel on most keyboards. Being able to automate this would make FM8 a whole lot easier to use.

**Comment by tresf** [comment]
> He means the Mod Wheel as in MIDI CC 1.

Thanks for translating Ian.  We have a dedicated thread for the MIDI stuff.  When we introduce better MIDI support, we'll need a place for this mod wheel, so I'll crosslink.

P.S. Reaper, I've closed out the majority of your bug reports to clean up the tracker.  Here's a list of those that are still open and that I consider valid and useful.

https://github.com/LMMS/lmms/issues/created_by/Reaper10

**Comment by Reaper10** [comment]
it's envelope/ lof tab based on the basic  lfo env tab that's  just for the mod wheel

**Comment by tresf** [comment]
That makes no sense.  You have to be much specific on the intent of the functionality.
