### ISSUE TITLE
How in the world do I use a vst compressor in lmms?????????????

### ISSUE THREAD

**Issue by mrdrogo** [LMMS/lmms#1898]
VST synths were very intuitive. Just plug and play. But how do I get a track to be recognized by a vst compressor? The ones I have don't allow you to import a file. I tried playing a file in a sample track but the vst compressor doesn't even react to it. AAHHHHHHHHHHHHHHHHHHH. WHERE DO I PUT THE SONG? Sounds so simple but I just don't know so it's so maddening?

**Comment by tresf** [comment]
Normally, the FX plugins are added via the settings dialog.

![image](https://cloud.githubusercontent.com/assets/6345473/6795922/6704a4aa-d1bf-11e4-9a88-b3ef686936f0.png)

We understand this is slightly confusing as the VST instruments are added through a completely separate interface.

**Comment by tresf** [comment]
Edit... 

Then it should show under the FX areas of the software (mixer, FX tabs, etc).


![image](https://cloud.githubusercontent.com/assets/6345473/6795934/9540e680-d1bf-11e4-8a2e-1b81104601b2.png)


We understand this is slightly confusing as the VST instruments are added through a completely separate interface, but that is how you do it. :+1:

**Comment by diizy** [comment]
For future reference, questions like this are better to post on our forum. 
https://lmms.io/forum/index.php

**Comment by Sti2nd** [comment]
And wre have a wiki lmms.io/documentation but there are no search bar there so I agree it can be hard finding what you want

**Comment by mrdrogo** [comment]
Tresf
Thanx, much thanx
Not only did I get an accurate and easy to follow answer. I also got a laugh out of the bargain. I never imagined that happening. That was awesome how you put my question in the lmms paths framework as an answer! cool. :+1: 


diizy
Fair enough. I believe in order and structure. When I enter someone else's domain I like to play by the rules. I had never been on here before (which is really telling of how user friendly lmms actually is). Lesson learned. Peace.

**Comment by tresf** [comment]
:+1:
