### ISSUE TITLE
LMMS crashes when opening automation track

### ISSUE THREAD

**Issue by jypiou** [LMMS/lmms#1901]
Hi all,
I've recently created an automation track and each time I wan to edit it, LMMS crashes and the log is the following on the console :
`QtXmlWrapper::loadXMLfile(): empty data 
ASSERT: "it == time_map.end()-1" in file /build/buildd/lmms-1.0.0+stable/src/gui/AutomationEditor.cpp, line 1600
Abandon (core dumped)`

I'm running Ubuntu 14.04 and LMMS 1.0.0.

Thanks
jy

**Comment by tresf** [comment]
We no longer officially support the `stable-1.0` branch.  Can you confirm this also occurs on `1.1.3`?

**Comment by softrabbit** [comment]
Looks like it's fixed since 1.0.1, a year ago. https://github.com/LMMS/lmms/issues/721#issuecomment-43181241

**Comment by jypiou** [comment]
Yes, you're right, it is fixed.
This will probably regularly come up as 1.0.0 is in the stable repositories of ubuntu.

Thanks !
jy

**Comment by tresf** [comment]
> This will probably regularly come up as 1.0.0 is in the stable repositories of ubuntu.

Yeah, we have some area for improvement there per #1620.

Closing as duplicate of #721.
