### ISSUE TITLE
Make the EQ plugin resizeable 

### ISSUE THREAD

**Issue by Umcaruje** [LMMS/lmms#1904]
This would be truly neat and make the EQ plugin even more usable.

It'd also allow people with larger monitors to stretch out the plugin for bigger precision.

Now I am not sure how hard would this be to implement but @curlymorphic will probably have an idea about that.

**Comment by curlymorphic** [comment]
Resizing of the analyser widget should be easy enough. The work will be how to handle the knobs and faders, and scalling the background image.

@Umcaruje has offered to look the the current gimp artwork, to see if it can be turned into SVG

**Comment by RebeccaDeField** [comment]
> See if it can be turned into SVG

@BaraMGB Isn't your new EQ design in .svg?

**Comment by BaraMGB** [comment]
No. It uses png. I think it'd be possible to make the eq able to resize. But there are a few of things to do for that. At first : lmms don't allow to resize effect plugins at the moment. Second : all graphics has to be scalable. We could do that after 1.2 is released along with some more improvements planned by@umcaruje and me.

**Comment by RebeccaDeField** [comment]
> We could do that after 1.2 is released along with some more improvements planned by @umcaruje and me.

:+1:

**Comment by tresf** [comment]
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.
