### ISSUE TITLE
Inconsistent clamping behavior in automation editor

### ISSUE THREAD

**Issue by Wallacoloo** [LMMS/lmms#1907]
When moving a point in the automation editor, if I drag the cursor outside of the window to the *right*, the point will still follow the cursor. But if I drag it outside the *left* of the editor, then it stops updating. The gif below should explain it better.

![Inconsistent Automation Editing](https://cloud.githubusercontent.com/assets/1210751/6888638/b36994fa-d673-11e4-9ddc-fc5f9ea514ac.gif)

This behavior seems inconsistent. Is it by design or is it a flaw?

(This behavior was observed in a fresh build from the git repository using the latest commit: c1a2fde2ef)

**Comment by Spekular** [comment]
It's probably because you can always drag a point more to the right,
whereas there's a left boundary. You certainly ought to be able to drag to
the left when you're not at that border though.

**Comment by Wallacoloo** [comment]
To be clear, there is about another 1.25 measures offscreen to the left in that gif. This was not the result of trying to place an automation point at some time < 0.

**Comment by Spekular** [comment]
Yup, I'm just guessing that the reason for the boundary is to prevent
people from placing points too far left, and no exception has been made for
when you've actually got a valid area on the left.

**Comment by tresf** [comment]
Possible culprit:  

[`AutomationEditor.cpp#L613`](https://github.com/LMMS/lmms/blob/master/src/gui/editors/AutomationEditor.cpp#L613)

It should set the point to `0` rather than not processing the mouse move event.  It is a rather large function, but should be a relatively small change.  @Spekular do you have any interest in patching this behavior?

**Comment by Wallacoloo** [comment]
Unless you really want to take this on, I'd like to give it a try instead. Been meaning to contribute to lmms for a while.

**Comment by tresf** [comment]
> Unless you really want to take this on, I'd like to give it a try instead. Been meaning to contribute to lmms for a while.

Absolutely, please do! :+1:

**Comment by tresf** [comment]
P.S. If you need any help to get started, please ask! :+1:

**Comment by tresf** [comment]
Closed via #1910.  Thanks @Wallacoloo!
