### ISSUE TITLE
LMMS doesn't reconnect to JACK

### ISSUE THREAD

**Issue by unfa** [LMMS/lmms#1909]
Hey!

I'm using ZynAddSubFX non-stop. Sometimes (it was more severe in earlier versions, but still present in 1.1.3) when I open or close Zyn's GUI LMMS's JACK ports are destroyed and there are new ones created. The client name changes:

    lmms
    lmms-01
    lmms-02
    lmms-03
    ...

And LMMS doesn't connect it's output to system sinks in JACK. Result - no sound.

I need to manually connect LMMS to system:playback ports to be able to continue my work.

**Comment by tresf** [comment]
Related 1240?

**Comment by tresf** [comment]
Related #1240?

**Comment by unfa** [comment]
Yes. Sorry for redundancy.
