### ISSUE TITLE
1.1.3 - segfault when tweaking in ZynAddSubFX external GUI

### ISSUE THREAD

**Issue by unfa** [LMMS/lmms#1912]
Yesterday LMMS started to crash like a jealous dodo.

Console output:

```
unfa@unfa-K52Jc:~$ lmms
VST sync support disabled in your configuration
RemotePluginClient::shmget: No such file or directory
Starting Audio: NULL
Audio Started
Starting MIDI: NULL
MIDI Started
Segmentation fault
```

To reproduce (doesn't happen every time):
1. Run LMMS
2. Add ZynAddSubFX
3. Start tweaking knobs here and there
4. Wait for segfault
   It seems to always happen when I work on a ZynAddSubFX patch. I touch a knob and LMMS crashes.
   How can I get more info about this? Debugging?

**Comment by tresf** [comment]
Good question... @tobydox how do we debug remote processes?  If they're complied with the debug flag, does it throw it up the stack properly, or do we need to attach gdb to the remote process each time it is started?

**Comment by tresf** [comment]
Furthermore, @unfa this is likely a `wontfix` because Zyn development on our current branch has ended, so we'd have to reproduce on 2.5, which we don't have integrated yet.

**Comment by unfa** [comment]
Yes, I hope 2.5 will get this fixed in itself.

Should I contact Zyn team for this issue?
I'm not sure if it's LMMS related or not.

**Comment by tresf** [comment]
> Should I contact Zyn team for this issue?

If you can't reproduce on 2.5 (and furthermore can't create a stacktrace), there's not much point.

**Comment by badosu** [comment]
@unfa Does this happen if you run Zyn standalone on the same version as lmms (I guess we're at 2.4.x?) ?

**Comment by unfa** [comment]
I'd have to try, don't know.

**Comment by musikBear** [comment]
puzzles me - i run a heap of zyns, and i cant crash lmms -except in wave-shape-setting, but i wont go that way, because tresf will crucify me, if i mention this xp-only issue even once.. oh.. dear ..im toast..
@unfa -are you sure it is zyn - couldent it be a component on FX-tab of a zyn, that is the actual reason?
Eg can you get lmms to crash with *only* a clean zyn instance (like a factory-preset) ?

**Comment by tresf** [comment]
@musikBear... Ready to upgrade? :)

**Comment by Spekular** [comment]
@musikBear
Option 1:
1. Grab a copy of windows 7 or 8
2. Get a free upgrade to windows 10 when it's out
3. ???
4. Profit

Windows 7/8/10 all only require a 1Ghz processor and 1 Gb of RAM, so if you
can run LMMS you ought to be fine.
Windows 7 with "Appearance and Performance" set to max performance looks
just like XP, so the looks should be fine too. ;)

Option 2: (The secret Bill Gates doesn't want you to know)
1. Grab a linux distro
2. You're instantly really cool and tech savvy
3. You're not really instantly tech savvy
4. Spend some time getting used to it
5. Profit

As you can tell, option 2 is a bit harder, but it's also FREE.

**Comment by tresf** [comment]
Linux is free so as long as your time is worth nothing. :)

> 5. Profit

Bahaha.

**Comment by curlymorphic** [comment]
> 2. You're instantly really cool and tech savvy
> 3. You're not really instantly tech savvy

You get to keep the `really cool` though :)

**Comment by lukas-w** [comment]
I can't reproduce this on `stable-1.2`. Close?

**Comment by tresf** [comment]
> I can't reproduce this on stable-1.2. Close?

👍
