### ISSUE TITLE
Fonts are nearly unreadable

### ISSUE THREAD

**Issue by es20490446e** [LMMS/lmms#1913]
Interface doesn't follow system font size, and there's no option for configuring it through a graphical interface. This makes the text nearly unreadable in high resolutions.

![screenshot](https://cloud.githubusercontent.com/assets/9594332/6923247/c6950b0a-d7d0-11e4-95a4-524cd4588295.png)

**Comment by es20490446e** [comment]
Also reported to https://bugs.launchpad.net/lmms/+bug/1438771.

**Comment by tresf** [comment]
Thanks for reporting.

We're well aware and we need some help in this regard.  Closing as duplicate of #541, #1839
