### ISSUE TITLE
Dual Filter frequency automation does not work

### ISSUE THREAD

**Issue by karmux** [LMMS/lmms#1919]
When I try to connect frequency knob to either MIDI or user controller to get wobble effect, it results constant frequency. But I can hear the wobble when moving knob with mouse. Connecting to controller doesn't work with any of the effects in dual filter.

**Comment by tresf** [comment]
@karmux this may be a duplicate of #1472.  If so, please close it out and we'll track progress over there. :+1:  If not, let me know what's missing and I'll add it. :+1:

**Comment by karmux** [comment]
@tresf if was only MIDI controller then probably yes, but it doesn't work also with LFO controller from Controller Rack. So it shouldn't be related to MIDI only.

I tried to connect frequency knob to automation track and this way it gave me correct result.

**Comment by tresf** [comment]
@karmux thanks for clarification.  Here's another bug report related to linear vs. logarithmic... #1642

**Comment by karmux** [comment]
Changing linear/logarithmic for know didn't help.

**Comment by tresf** [comment]
Reproduced.  I didn't realize it moves but doesn't work.  Confirmed.

**Comment by karmux** [comment]
Forgot to mention reso knob of the same filter. Gain seems to be controllable by LFO.

**Comment by curlymorphic** [comment]
@karmux can I ask what version of lmms you are running, and where you got it from please?

**Comment by tresf** [comment]
@curlymorphic i could reproduce on 1.1.3 (I was on Apple at the time of testing)

**Comment by tresf** [comment]
P.S. It moves, just has no effect.

**Comment by karmux** [comment]
@curlymorphic I found this bug on 1.1.3.

Now trying on master branch and automating frequency surprisingly works there but reso knob doesn't do anything even when moving manually. Also I found that BassBooster has similar issue (frequency and ratio are buggy but gain can be automated). Tested some more LMMS's plugins and they did work as expected.

**Comment by curlymorphic** [comment]
My initial thought was that I may have broke it with the sample exactness, but thats not in 1.1.3.



> Now trying on master branch and automating frequency surprisingly works there

looks like the sample exactness is effecting this, will take alook tomorrow.

Thanks for the information @karmux

**Comment by curlymorphic** [comment]
The above pull request fixes DualFilter where  the Res not working on master. both filters had the res controlled the res 2 control.

**Comment by tresf** [comment]
Are we skipping stable for this one?

**Comment by curlymorphic** [comment]
@tresf 

The introduction of samples exactness, removes the original bug. IIRC that is not in stable.
This fix, is just correcting a typo in the sample exactness code. 

Are you asking for a separate bugfix just for 1.1.3?

**Comment by tresf** [comment]
Yeah I thought so... Just asking if we think it is worth it....

**Comment by curlymorphic** [comment]
I will take a look tomorrow

**Comment by badosu** [comment]
@curlymorphic I can cherry-pick your PR's commits and the latest on a separate branch to target 1.1.x. Is it ok with you?

**Comment by tresf** [comment]
@badosu I dont think the code is compatible.  From what I'm reading it is really a separate bug that was found and fixed while troubleshooting with master.

**Comment by badosu** [comment]
@tresf I have followed the history of the sample exactness commits since their introduction, I am suggesting to backport all the relevant ones to 1.1.x.

Which mostly only means cherry-picking them, there should be no conflicts.

**Comment by tresf** [comment]
I would recommend these wait for thier intended branch, not a feature-frozen one.  I think @diizy and @curlymorphic would agree.

**Comment by badosu** [comment]
@tresf What I mean is exactly that, to create a PR targeting the *intended* branch by cherry-picking commits.

**Comment by tresf** [comment]
Relevant to what?  It was intended for master.  We dont add new features to stable.  I understand some can interpret sample exact as bug-fix (versus feature) but I dont feel comfortable with this proposal and I'm not sure why we'd press this issue.  We have plenty of bug-fix type changes to master that haven't been back-ported.  What is special about this one?  Am I missing something?

**Comment by badosu** [comment]
> What is special about this one? Am I missing something?

I don't know, are you? I am confused now, I was actually asking @curlymorphic if he wanted my help to backport this as I am more experienced on git and wanted to alleviate his work on this.

I actually just progressed on this dicussion (and made is special?)  because you actively engaged on it for some reason (I don't know).

Anyway, the backport is done as it was more difficult to explain than to actually do it, feel free to continue the discussion on backport worthiness on it. See: https://github.com/LMMS/lmms/pull/1923

**Comment by tresf** [comment]
I saw your PR and realized you were only referring to **this** plugin lol.

**Comment by badosu** [comment]
Cool :-)

**Comment by tresf** [comment]
Just re-read.... 

> I am suggesting to backport all the relevant ones to 1.1.x.

So now I'm really confused.... 


But is this bug really about sample exact?  You are quick to dismiss my involvement in this conversation, but someone needs to merge this stuff, and I'm still a bit confused as to the cause and proposed fix.

**Comment by badosu** [comment]
@tresf Sorry, by `ones` I meant commits. It actually was just 2 commits that had to be picked. No, this bug is about something else, but pulling sample exactness altogether with the latest fix is easier.

**Comment by tresf** [comment]
@badosu per our conversation in #1923, I think you'll have to strip out the memory manager stuff to get what you are describing to work.

**Comment by badosu** [comment]
@tresf As I commented on #1923, @curlymorphic's improvement and subsequent fix for this issue is not applicable to 1.1.x without non-trivial work.

**Comment by tresf** [comment]
One difference I can see is the DualFilter uses boolean flags to notify the filters to get updated.... i.e. https://github.com/LMMS/lmms/blob/stable-1.1/plugins/DualFilter/DualFilter.cpp#L60.

But that's about as far as I get... the models and slots tend to send me into a tailspin. :)

**Comment by tresf** [comment]
(Amplifier doesn't have such flags, which is why I mention it).

**Comment by badosu** [comment]
@tresf The rabbit hole is deeper, there are at least 3-4 @diizy's commit that would have to be pulled in. So if someone wants to fix this for 1.1.x I'd recommend to not follow this approach.

Only if it's acceptable to backport a huge feature set as Sample Exactness to 1.1.x (I can take a look at it).

**Comment by tresf** [comment]
Agreed.... Again... the [problem may lie in the reliance on the boolean flags](https://github.com/LMMS/lmms/blob/stable-1.1/plugins/DualFilter/DualFilter.cpp#L60).  Probably a slot needed fired by data changed event on the model underlying the knobs, but I'm not good with this stuff. :)

So I'll repeat my original question.... 

> Just asking if we think it is worth it....


-Tres

**Comment by tresf** [comment]
I just found your vote:

>  we can close it as 1.2.0 has it fixed.

Agreed.  @karmux, we'll have this fixed up in 1.2.  Thanks for the bug report! :)

**Comment by badosu** [comment]
@tresf Just so that future readers of this thread do not get confused, this should be already fixed as soon as 1.2.0 gets released.
