### ISSUE TITLE
Add a clone this tracks audio input routing option

### ISSUE THREAD

**Issue by Reaper10** [LMMS/lmms#1920]
In #1471 you should add a clone this tracks audio input routing option in the Sample Track gear menu witch will make a new blank track but, it'll just keep the audio input routing setup in the new track. This will make it easier to make comp tracks.

**Comment by Spekular** [comment]
Couldn't you add this as a comment there instead?

**Comment by tresf** [comment]
He did, and I ignored him because its not a Sample Track feature, but just a general usability feature.

**Comment by Reaper10** [comment]
do you think it's good idea?

**Comment by tresf** [comment]
> do you think it's good idea?

Copying anything from one track to the other is a good idea.  This concept is similar to a word processor when you paste "Just contents" or "Just formatting".  In this case, we could probably benefit from pasting "Envelope Information, FX information".

Do I think its a good idea?  Sure.  I think it is a much better idea that we work to implement these things.

**Comment by tresf** [comment]
I also think your bug reports aren't thought out and aren't clear.  You keep claiming not to be a coder, but you could probably benefit at least from putting some of these ideas on scratch paper and putting them as high-level goals somewhere.  Once you get them organized, we could put them on the software's future map.

The bug tracker is really a place to track a bug or enhancement, but when we're free to open as many reports as we want, we expose how terribly unorganized we are.  Many submitters do this, and we end up closing out duplicates of their own bug reports.  This is time better spent on fixing bugs.  Please take some responsibility for yourself and help make our tracker better, not more cluttered.

**Comment by Reaper10** [comment]
#1977

**Comment by Reaper10** [comment]
Could this be add?
