### ISSUE TITLE
AFP Enhancments 

### ISSUE THREAD

**Issue by Reaper10** [LMMS/lmms#1921]
1. You should add a open in AFP in song editor or open in AFP in B&B editor right click options on to the sample in the Sample Track witch will auto load it into a new AFP in the song editor or open it into a new AFP in B&B editor.
2. You should add a Sample stretch knob next to all of the others witch stretch out sample out you can use all other modes with it, ie, all loop modes and the reverse mode.

**Comment by tresf** [comment]
> You should add a open in AFP in song editor or open in AFP in B&B editor right click options on to the sample in the Sample Track witch will auto load it into a new AFP in the song editor or open it into a new AFP in B&B editor.

You've already proposed this before somewhere else.

> You should add a Sample stretch knob next to all of the others witch stretch out sample out you can use all other modes with it, ie, all loop modes and the reverse mode.

I don't think we have a bug report for this feature yet, but no project can ever keep up with these requests.  Put them on a blog or something, you are flooding our tracker.
