### ISSUE TITLE
duplicate demo songs in master

### ISSUE THREAD

**Issue by eagles051387** [LMMS/lmms#1925]
I am noticing that there are multiple of the same songs in the cool songs directory . Some of them had been moved into their own directory like skessi and CapDan and Zakarra. They still are showing in cool songs.

Can I get some pointers on what i need to do to clean this up?

**Comment by eagles051387** [comment]
I have done some digging on this and the issue seems to be with the list of items being displayed in my projects under the cool songs directory.

In the source code, the files are in their respective directories but then in LMMS from master recompiles this morning its showing them as not in the respective author directory.

Any pointers on where I should look to fix this issue?

**Comment by tresf** [comment]
Confirmed.  Possibly caused via https://github.com/LMMS/lmms/commit/ce0a56a482819f728fdcfba01f6ba3ceb32e2ff7.

![screen shot 2015-04-06 at 10 41 37 am](https://cloud.githubusercontent.com/assets/6345473/7005805/9c728bd6-dc49-11e4-8c4f-00e549429c30.png)
