### ISSUE TITLE
(Apple) cracking audio

### ISSUE THREAD

**Issue by eagles051387** [LMMS/lmms#1926]
I am on master and I am running things through the debugger, but I am noticing that alot of the audio files either are clipping causing massing crackling in the audio, but even those that are not clipping are still producing some sort of cracking. 

Is anyone experiencing this with the current stable version?

**Comment by tresf** [comment]
I suppose the backend you are using would be good to know, but current stable is actually built on Lion for maximum compatibility.

In terms of crackling audio, all projects start that way for me, but after pausing and playing seem to play ok.

**Comment by eagles051387** [comment]
What I have noticed on master when I start it normally after compilation and installation no window comes up for what back end to choose

**Comment by tresf** [comment]
```bash
rm -f ~/.lmmsrc.xml
```

**Comment by eagles051387** [comment]
It brought up the window but if I use any of the other audio options I get
no audio output what so ever. If I leave the default option as dummy audio
no output option I get sound.

lldb im seeing

JACK compiled with POSIX SHM support.

loading driver ..

Oddly enough when i selected jack the first time after removing the lmmsrc
xml file I had no audio but once the file is created with the dummy backend
and then i switch to the jack audio option I have sound. But even a single
click on the kicker keyboard for example is sounding very crackly on master.




On Sun, Apr 5, 2015 at 11:24 PM, Tres Finocchiaro <notifications@github.com>
wrote:

> rm -f ~/.lmmsrc.xml
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LMMS/lmms/issues/1926#issuecomment-89854315>.
>



-- 
Jonathan Aquilina

**Comment by tresf** [comment]
Why Jack?

**Comment by tresf** [comment]
Sometimes we have bugs which surface with the debug build and optimized build, but I fail to see any evidence of that here.  What is your motivation to use JACK on Mac?  You should use PortAudio (Which will use Core Audio) or you can use SDL if you choose.


![screen shot 2015-04-06 at 10 16 56 am](https://cloud.githubusercontent.com/assets/6345473/7005451/16247ede-dc46-11e4-9199-4a3f48f76a10.png)

**Comment by eagles051387** [comment]
That is what seems to be the default with a debug build

**Comment by eagles051387** [comment]
I will try again with port or sdl. When I first chose port audio I was getting no audio. I will do some further testing

**Comment by tresf** [comment]
> That is what seems to be the default with a debug build

Hm... Perhaps we should bump it down the list.... 

https://github.com/LMMS/lmms/blob/master/src/core/Mixer.cpp#L780

> When I first chose port audio I was getting no audio

Me too.  I have to restart LMMS afterwards for some reason.  Just make sure the right device is selected.

**Comment by eagles051387** [comment]
If you can provide me some pointers I ca make the change

**Comment by tresf** [comment]
> If you can provide me some pointers I ca make the change

https://github.com/LMMS/lmms/issues/1600#issuecomment-90094383

**Comment by eagles051387** [comment]
Thanks will look into this when I'm back at the hotel In an hour

**Comment by tresf** [comment]
@eagles051387 did you create a new tag called "Apple Bug" ?

**Comment by eagles051387** [comment]
Ya i did makes it a bit easier to identify which bugs are related to osx.
if you want to remove it feel free. I did this as I was having some issues
distinguishing apple specific bugs in the tracker and when searching.

On Thu, Apr 16, 2015 at 4:46 AM, Tres Finocchiaro <notifications@github.com>
wrote:

> @eagles051387 <https://github.com/eagles051387> did you create a new tag
> called "Apple Bug" ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LMMS/lmms/issues/1926#issuecomment-93622705>.
>



-- 
Jonathan Aquilina

**Comment by tresf** [comment]
> if you want to remove it feel free

We dont have tags for other OSs.

I didn't add it, you did.

I'm maintaining the list of apple bugs.  They can be found easily because I put `(Apple)` in the title.  Is that too difficult to search for?

**Comment by eagles051387** [comment]
no but the way the tracker search seems to work is based on tags I could be
wrong there.

On Thu, Apr 16, 2015 at 7:05 AM, Tres Finocchiaro <notifications@github.com>
wrote:

> if you want to remove it feel free
>
> We dont have tags for other OSs.
>
> I didn't add it, you did.
>
> I'm maintaining the list of apple bugs. They can be found easily because I
> put (Apple) in the title. Is that too difficult to search for?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LMMS/lmms/issues/1926#issuecomment-93642312>.
>



-- 
Jonathan Aquilina

**Comment by tresf** [comment]
You are talking in circles.  If you cant justify it, please remove it.

**Comment by Umcaruje** [comment]
@tresf were you ever able to confirm this issue on Apple?

**Comment by tresf** [comment]
@Umcaruje 

> @tresf were you ever able to confirm this issue on Apple?

> > In terms of crackling audio, all projects start that way for me, but after pausing and playing seem to play ok.

Yeah, sorta.  A better description is that songs start out as crackling, which happens on other platforms as well.  Closing.  We can track in another issue that actually is written properly. :)

**Comment by Umcaruje** [comment]
:+1:
