### ISSUE TITLE
Frequency and ratio knobs in BassBooster cannot be automated

### ISSUE THREAD

**Issue by karmux** [LMMS/lmms#1927]
Automating frequency or ratio knob in BassBooster with LFO or MIDI controller results static effect (knobs are moving but no actual value change). These knobs work when changing values manually or using automation track. Similar issue like in #1919.

I can reproduce it on both 1.1.3 and latest master. Sample exactness seems to be finished for BassBooster in #1802.

**Comment by curlymorphic** [comment]
@karmux Thanks for carrying this over from #1919 :). 

The above pull request should fix this in the master branch.

**Comment by karmux** [comment]
@curlymorphic Nice! :)
