### ISSUE TITLE
No playback cursor in AFP (master and stable)

### ISSUE THREAD

**Issue by softrabbit** [LMMS/lmms#1939]
The playback cursor cursors no more, neither in master nor in stable-1.1. Cosmetic bug, but a bug anyway.

**Comment by tresf** [comment]
I noticed this too... Is this dependent on a certain capability of the hardware, or just a setting we accidentally mucked up between versions?

**Comment by Sti2nd** [comment]
There is a setting for it which by default is off?!?

**Comment by tresf** [comment]
Yeah, I tested it before posting... still doesn't seem to do anything (please correct me if I'm wrong here)

**Comment by softrabbit** [comment]
This is independent of hardware, it's graphics drawn just like everything else, around here: https://github.com/LMMS/lmms/blob/master/plugins/audio_file_processor/audio_file_processor.cpp#L980

**Comment by tresf** [comment]
Thanks.  Hmm... the boolean logic looks ok per: https://github.com/LMMS/lmms/blob/master/src/gui/SetupDialog.cpp#L123.

**Comment by tresf** [comment]
Edit and https://github.com/LMMS/lmms/blob/master/plugins/audio_file_processor/audio_file_processor.cpp#L777
