### ISSUE TITLE
Documentation Guidlines

### ISSUE THREAD

**Issue by JohannesLorenz** [LMMS/lmms#194]
Those are possibly needed.

I often see header files with large classes and not a single comment. Not even a comment what the class is doing, and almost all public functions are not documented. I mean, a comment like "This gets x" on a function named "int get_x() { return x }" is not necessary, but there are many more complicated examples.

The same counts for cpp files... most algorithms are not documented well. Having a comment each few lines would not harm. E.g. when you begin a large for- or if-loop.

Imo this should be done:
 * Comment your new code enough, otherwise it should be *rejected* by admins. Your comments do not have to be perfect, but you should at least try to follow documentation guidelines
 * Comment on existing code whenever you see something you understand.
 * Let's make a doc directory in the root, where cmake (or an additional Makefile) will build doxygen docs. That way, it gets easy for the programmer to see existing docs as well as his new ones. And you see where docs/comments are still missing.

**Comment by badosu** [comment]
I can't see how this issue sets a goal that can be accomplished to fix it. Can we close this?

**Comment by Lukas-W** [comment]
> Can we close this?

Yes we can. :)
