### ISSUE TITLE
Knob rendering error in Organic instrument

### ISSUE THREAD

**Issue by Wallacoloo** [LMMS/lmms#1946]
The Organic instrument renders its knobs really oddly. Here's a gif what happens when you adjust one of the knobs:

![organic error](https://cloud.githubusercontent.com/assets/1210751/7099772/8149b0d0-dfed-11e4-80d4-6a6f3d9d1e85.gif)

It appears that the knob handle is being drawn as coming from the top-left of the knob instead of from the center. It affects all the knobs (not just the VOL knobs), but the rest are just turned fully counter-clockwise at start up, so the knob handle isn't visible until you turn them clockwise.

Using the latest git commit on Ubuntu.

**Comment by softrabbit** [comment]
Theme problem, you're loading an old theme instead of the one that comes with the sources.

**Comment by Wallacoloo** [comment]
Interesting. That was indeed the causes of the issue. 

Thanks.
