### ISSUE TITLE
Muting B&B-track affects sound (filter?) in unrelated track when playing from piano roll (master)

### ISSUE THREAD

**Issue by softrabbit** [LMMS/lmms#1947]
TripleOscillator, preset "Dirty Reece", master branch.

The picture should explain how to reproduce, but in brief:
- If playing a pattern from the piano roll, the sound will be different when an unrelated B&B-track is muted
- The B&B-editor doesn't need to contain any instruments
- Notes played during editing in the piano roll (e.g. moved notes) are unaffected.

The change happens around the hump in the spectrum analyzer, below the big number 3 in the screenshot. Could be the filter being bypassed, that sounds (and looks) very similar.

![mute_damping](https://cloud.githubusercontent.com/assets/6411463/7101026/e347ee30-e049-11e4-8325-53f64b121483.png)

**Comment by Umcaruje** [comment]
Confirmed on the `master` branch - Ubuntu 15.04 x64.

It seems that the filter gets turned off when you mute the BB-track.

**Comment by softrabbit** [comment]
So far, I've come to believe the problem is ```InstrumentSoundShaping::processAudioBuffer()``` not being called, and that is happening because ```NotePlayHandle::isBbTrackMuted()``` returns true, in https://github.com/LMMS/lmms/blob/master/src/tracks/InstrumentTrack.cpp#L171

Will dig deeper later, to figure out why a notePlayHandle from a non-BB-track gets a BBTrack assigned to it (https://github.com/LMMS/lmms/blob/master/src/tracks/InstrumentTrack.cpp#666)

**Comment by PhysSong** [comment]
This bug can be fixed easily by not setting BB track for play handles from instrument track(and/or sample track) not in BB track container. I will open a pull request soon.
