### ISSUE TITLE
LMMS quick start menu

### ISSUE THREAD

**Issue by Reaper10** [LMMS/lmms#1948]
LMMS could use a quick start menu for loading project or template files or start a new  project or template file.

LMMS quick start menu
![loading screen](https://cloud.githubusercontent.com/assets/8137561/7103379/f6adcede-e069-11e4-9496-ecf052a7c28d.PNG)
It can show a list of tracks and all track info.
new will load the basic track you have now when open LMMS.

Pro Tools quick start menu
![screen-shot-2014-08-08-at-2 52 50-pm 1](https://cloud.githubusercontent.com/assets/8137561/7103405/505e0808-e06b-11e4-9045-05b433d48db7.png)

**Comment by Wallacoloo** [comment]
We already have File -> Recently Opened Projects and the "My Projects"  browser in the left pane (which includes a templates directory) that serves for opening projects and templates easily/quickly (likely more quickly than that mockup). 

It might be worth considering making the "My Projects" browser expanded by default at start though (to serve as a quasi-quickstart type thing). The biggest benefit to that is it would give new users a chance to easily open templates and demos. It would be pretty easy to whip up a setting to disable that behavior under edit->settings->general, too.
