### ISSUE TITLE
Link the Mute and  Solo LED Together 

### ISSUE THREAD

**Issue by Reaper10** [LMMS/lmms#1949]
Link the song editor and B&B editor Instrument tracks Mute and  Solo LED to the the mixer's  Mute and  Solo LED.so work together.

**Comment by unfa** [comment]
Well, I kind of disagree. If you want to send multiple instruments to one mixer channel, you might want to mute just one of them.

To make this consistent it'd require of further binding of instruments to mixer, which in the long run could be beneficial, but also not quick and easy to do.

I keep looking at Ardour - every track creates a mixer strip, but you also can create mixer buses, which are tracks with no audio or MIDI data, used to do submixes, effect sends and other audio routing.

**Comment by curlymorphic** [comment]
I agree with @unfa, mutes and solos on the instruments, serve a different purpose.

> I keep looking at Ardour - every track creates a mixer strip, but you also can create mixer buses, which are tracks with no audio or MIDI data, used to do submixes, effect sends and other audio routing.

lmms is the first daw I have used that does not function like that.

**Comment by Wallacoloo** [comment]
I actually quite like the way lmms does things in which each instrument has
an FX channel on the instrument panel itself rather than the mixer, as this
allows for presets to include both instrument configuration and associated
effects config.

The workflow could always be improved though.

**Comment by Reaper10** [comment]
ok ill close this
