### ISSUE TITLE
Travis build failing, mingw related

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms#1952]
> ```
In file included from /home/travis/build/LMMS/lmms/src/core/ConfigManager.cpp:245:0:
/opt/mingw32/i686-w64-mingw32/include/shlobj.h:37:3: error: 'EXTERN_C' does not name a type
   SHFOLDERAPI SHGetFolderPathW (HWND hwnd, int csidl, HANDLE hToken, DWORD dwFlags, LPWSTR pszPath);
```

In this code block:

https://github.com/LMMS/lmms/blob/master/src/core/ConfigManager.cpp#L245

Related commit (different project):

https://github.com/Nuand/bladeRF/commit/c631100589d86db708757d51f004cb36c06c5ec3

**Comment by Wallacoloo** [comment]
Here's the source for the current ming shlobj.h: http://sourceforge.net/p/mingw-w64/code/HEAD/tree/trunk/mingw-w64-headers/include/shlobj.h

Also, I feel that your line numbers are somehow off (actually, it looks like the file was just recently edited. `ConfigManager.cpp:245` in master is just a `return (void);` statement, so I don't see how that could be causeing a compilation error in shlobj.h. 

Is [this](https://github.com/LMMS/lmms/blob/d516c74b739936fa7ced0c8d7fc94df565fed1ba/src/core/ConfigManager.cpp#L257) the line that triggers the error? I.e. just including shlobj.h is the cause? If that's the line, then i's almost surely a bug internal to mingw or a broken installation on your computer.

I'm guessing EXTERN_C is supposed to be pound-defined somewhere in the mingw libraries. It may be useful searching for the file that defines it (in the mingw repository) and manually including that same file or defining it before the include.

**Comment by Wallacoloo** [comment]
Looks like that's supposed to be defined in [basetyps.h](http://sourceforge.net/p/mingw-w64/code/HEAD/tree/trunk/mingw-w64-headers/include/basetyps.h) (not a typo). Try adding `#include <basetyps.h>` right before `#include <shlobj.h>` to see if that can solve the issue.

**Comment by tresf** [comment]
@Wallacoloo, thx, it looks like we have a new one now per [`jobs/58370993`](https://travis-ci.org/LMMS/lmms/jobs/58370993)... :)

```
/opt/mingw32/i686-w64-mingw32/include/shlobj.h:37:3: error: 'DECLSPEC_IMPORT' does not name a type
   SHFOLDERAPI SHGetFolderPathW (HWND hwnd, int csidl, HANDLE hToken, DWORD dwFlags, LPWSTR pszPath);
   ^
In file included from /opt/mingw32/i686-w64-mingw32/include/windows.h:108:0,
                 from /opt/mingw32/i686-w64-mingw32/include/rpc.h:16,
                 from /opt/mingw32/i686-w64-mingw32/include/objbase.h:7,
                 from /opt/mingw32/i686-w64-mingw32/include/ole2.h:17,
                 from /opt/mingw32/i686-w64-mingw32/include/shlobj.h:107,
                 from /home/travis/build/LMMS/lmms/src/core/ConfigManager.cpp:258:
/opt/mingw32/i686-w64-mingw32/include/commdlg.h:575:53: error: expected class-name before '{' token
   DECLARE_INTERFACE_(IPrintDialogCallback,IUnknown) {
                                                     ^
/opt/mingw32/i686-w64-mingw32/include/commdlg.h:588:53: error: expected class-name before '{' token
   DECLARE_INTERFACE_(IPrintDialogServices,IUnknown) {
                                                     ^
/opt/mingw32/i686-w64-mingw32/include/commdlg.h:621:5: error: 'LPUNKNOWN' does not name a type
     LPUNKNOWN lpCallback;
     ^
/opt/mingw32/i686-w64-mingw32/include/commdlg.h:645:5: error: 'LPUNKNOWN' does not name a type
     LPUNKNOWN lpCallback;
     ^
```

**Comment by Wallacoloo** [comment]
So what caused the break? Can we trace it back to a specific commit, or was
it a change in the mingw version that Travis tests against? It seems odd
for this problem to just appear from nowhere.

**Comment by tresf** [comment]
Well, the issue I linked in the original post suggests mingw, but that is a pretty blind assumption.  If you look at how they fixed it, it wasn't a missing import, but rather a dynamic load which fixed the issue.

I would suspect an mingw bug because the similar  issues I found were mostly recent.

As far as commits to our code, I'll take a look back, but I don't recall anything surrounding this code changing for quite some time.

**Comment by tresf** [comment]
I went back quite a few commits to no avail on our end per:

https://github.com/LMMS/lmms/commits/master/src/core/ConfigManager.cpp

**Comment by tresf** [comment]
> or a broken installation on your computer.

You've probably realized this now, but this bug is on Travis, so my computer will likely only be affected once I update my packages, and even then, it wouldn't surface until a Windows installer is made. :)

**Comment by curlymorphic** [comment]
I can confirm I can make windows builds on an old vm, but not on a new one with fresh packages.

**Comment by tresf** [comment]
Upstream has some more dialog about this.  I'll quote it because the mailing archive tends to be hard to read:

>  *Subject: [PATCH] Add more includes to shlobj.h* 

> *wtypesbase.h and wincrypt.h pull some other headers,
together they all provide EXTERN_C, DECLSPEC_IMPORT and WINAPI macros,
which are needed by shlobj.h directly or indirectly.*

> `mingw-w64-headers/include/shlobj.h`

```diff
--- a/mingw-w64-headers/include/shlobj.h
+++ b/mingw-w64-headers/include/shlobj.h
 <at>  <at>  -6,6 +6,8  <at>  <at> 
 #ifndef _SHLOBJ_H_
 #define _SHLOBJ_H_
 
+#include <wtypesbase.h>
+#include <wincrypt.h>
 #include <winapifamily.h>

 #if WINAPI_FAMILY_PARTITION (WINAPI_PARTITION_DESKTOP) || defined(WINSTORECOMPAT)
```

Without mucking with upstream, the OP had success using:

```diff
++#include <basetyps.h>
#include <shlobj.h>
++#include <windef.h>
++#include <wtypesbase.h>
++#include <wincrypt.h>
```

Although there seems to be comments about this never working in a true Windows build environment, so we should make sure we note this patch would be temporary until mingw's patch makes it into the normal ppa channels.

**Comment by tresf** [comment]
No dice... 

Just discovered that CMake is having issues as well per:

```
/opt/mingw32/lib/libogg.dll.a;/opt/mingw32/lib/libvorbis.dll.a;/opt/mingw32/lib/libvorbisfile.dll.a;/opt/mingw32/lib/libvorbisenc.dll.a
CMake Error at /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:306 (message):
  pkg-config tool not found
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:320 (_pkg_check_modules_internal)
  CMakeLists.txt:303 (PKG_CHECK_MODULES)
-- Could NOT find Wine (missing:  WINE_LIBRARIES WINE_INCLUDE_DIRS) 
CMake Error at /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:306 (message):
  pkg-config tool not found
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:320 (_pkg_check_modules_internal)
  CMakeLists.txt:351 (PKG_CHECK_MODULES)
```

I'll go back on a few Travis builds and see if this is normal or not...

**Comment by tresf** [comment]
And here are some changes from about a month ago:

https://sourceforge.net/p/mingw-w64/mingw-w64/ci/524630a9662c5a012f85023a4af49d6aa1c74a1d/

**Comment by Wallacoloo** [comment]
That Cmake issue looks to be because Travis doesn't have pkg-config (which
is an application wholly separate from CMake) installed. Perhaps try adding
`apt-get install pkg-config' (or whatever variation is needed based on
permissions) somewhere in travis.yml before the CMake build gets invoked.
Make sure that the pkg-config installation directory is added to the $PATH
if it isn't already.

**Comment by tresf** [comment]
>  because Travis doesn't have pkg-config (which is an application wholly separate from CMake) installed. Perhaps try adding `apt-get install pkg-config' (or whatever variation is needed based on
permissions) somewhere in travis.yml before the CMake build gets invoked. Make sure that the pkg-config installation directory is added to the $PATH if it isn't already.

Yeah I agree, this needs to be addressed although upon further investigation, that error goes back quite a ways and shouldn't be related to the mingw build error we are receiving now.

In regards to the mingw problem, I'm not sure the best approach to fix this as it appears to be an upstream issue.  We may have to wait.

**Comment by tresf** [comment]
Here's another project (mxe) with the same issue.  https://github.com/mxe/mxe/issues/664

**Comment by tresf** [comment]
I'm changing this to use `getenv("ProgramFiles")`.

The one downside to this is the 32-bit Windows version will return `C:\Program Files (x86)\` and the 64-bit version will return `C:\Program Files\`, which is slightly different than what the `SHGetKnownFolderPath` method would return.

The only area of the code currently using the offending function is the logic which tries to set a default value to the VstDir on Windows, which has much room for improvement per #1808.

Since environmental variables are user-overridable, many people discourage a `getenv()` approach over the API equivalent.  In our case, the risk and impact are minimal since the path in question is already in a user-definable area of the software and most users are likely to set this to something manually.

I'll have a PR momentarily which should fix this for both mingw32 and mingw64.

**Comment by Wallacoloo** [comment]
@tresf I'd say it's worth the trade-off - we need to get Travis back
online. Glad to see you're working to fix this.

**Comment by curlymorphic** [comment]
@tresf :+1:
