### ISSUE TITLE
sustain pedal not working in Zynaddsubfx

### ISSUE THREAD

**Issue by curlymorphic** [LMMS/lmms#1953]
irctc665 Has reported on irc that zyn does not respond to sustain midi messages in lmms. As a standalone Zyn responds correctly for this user in the same setup.

**Comment by tresf** [comment]
Possibly related:  #1700 #1918 

Not really related, but worth mentioning: #1632

@curlymorphic Does the OP know if this was ever working?  May be #1472.

**Comment by curlymorphic** [comment]
> Does the OP know if this was ever working?

The only information I have is the following irc conversation

````
<irctc665> I have a question - I have a sustain pedal hooked up to my midi keyboard, and it works in some synths in LMMS
<irctc665> but it doesn't work in zynaddsubfx
* orlp has quit (Ping timeout: 246 seconds)
<fundamental> that must be a bug in lmms routing the message to zyn as the zynaddsubfx standalone certainly works with the sustain pedal
<irctc665> amidi -d shows that the pedal works
<irctc665> B3 40 7F B3 40 00
<dobey> yeah, standalone works for me as well
<curlymorphic> It is probably a lmms bug, im checking the bug tracker now
<irctc665> I'm trying to see if zynaddsubfx works standalone for me
<irctc665> I can
<irctc665> I can't seem to get it to output sound though, it's complaining my ALSA output device is busy...
<dobey> it probably is busy
<dobey> anyway, i have to go, so later
<curlymorphic> fundamental, I have just posted on lmms github, about running just the UI external
<curlymorphic> fundamental, it i said anything incorrectly , please feel free to say
<irctc665> now I try to run zynaddsubfx standalone
<irctc665> sound works if I use the virtual keyboard
<irctc665> when I connect my midi keyboard in aconnectgui through ALSA zynaddsubfx says it finds the MIDI connection
<irctc665> but it doesn't recognize any keypress
<irctc665> oh, apparently it's on channel 4 for some reason >.<
<fundamental> are you sending events with the right midi channel?
* Gegsite has quit (Ping timeout: 252 seconds)
<irctc665> I don't know
<irctc665> in lmms it's channel 1
<irctc665> but when I run zynaddsubfx it's on channel 4
<irctc665> I don't understand why
<irctc665> but the pedal works
<irctc665> so it's a lmms bug
<irctc665> (LMMS 1.3.1)
````

**Comment by softrabbit** [comment]
Tested this with master and VMPK, if VMPK sends on channel 1, sustain works unless "forward MIDI Control changes" in the instrument window is off. But if VMPK sends on any other channel, Zyn ignores sustain.

So, I'd say LMMS always sends notes to Zyn on channel 1, but the sustain CC goes through without any modification and ends up turning the sustain on for some other part. Maybe LMMS should catch all CCs that come in on the chosen MIDI channel and reroute them to channel 1 for Zyn, I think it might be more logical that way.

**Comment by curlymorphic** [comment]
> So, I'd say LMMS always sends notes to Zyn on channel 1, but the sustain CC goes through without any modification and ends up turning the sustain on for some other part. Maybe LMMS should catch all CCs that come in on the chosen MIDI channel and reroute them to channel 1 for Zyn, I think it might be more logical that way.

@softrabbit nice investigating, and solution :)
