### ISSUE TITLE
LMMS Does Not Launch Correctly Without Installing

### ISSUE THREAD

**Issue by fundamental** [LMMS/lmms#1958]
Currently launching lmms from the build directory without installing results in a mostly broken setup. A fair number of plugins complain that they cannot be found and virtually all UI graphics missing. A user should not be forced to install the software (regardless to the fact that you can specify the install directory) in order for it to be functional.

## Steps to replicate.
1. get a system with no prior lmms installation
2. clone and mkdir build && cd build && cmake .. && make && ./lmms

## Expected Result
Lmms to launch normally and to present the user with various dialogs concerning this being the first use of the program

## Actual Results

Lots of warnings and windows looking like 
![Broken GUI](http://fundamental-code.com/tmp/broken-lmms.png)

**Comment by geedubess** [comment]
It makes sense to me that the program would require some level of installation step; why would I expect that the object tree has the same structure as the output tree for all components?

On the other hand, you don't *have* to install to your system directory. My build script looks like:

rm -rf build target; mkdir build target
cd build
cmake ../lmms -DCMAKE_INSTALL_PREFIX=../target && time make -j8 install &&../target/bin/lmms
cd ..

**Comment by tresf** [comment]
Mark,

AFAIK, Lukas has stared this feature per #1719
