### ISSUE TITLE
feature request for beat bassline pattern editor

### ISSUE THREAD

**Issue by oeai** [LMMS/lmms#196]
- for beats it would be nice to have a duplicate whole pattern into a new one, so just adding few beats was easier.
- those beats patterns got an ability for enlarging in main sequence it would be nice to have the same for all instrument patterns
- for instrument pattern editor when mouse-selecting notes it would be nice to have auto move focus with mouse to scroll window (it is possible now with right - left keys)
- also if any line of pattern got more steps than others then it would be nice to add steps for all instrument lines
- add half, quarter and trinity steps or define pattern measure, so it was a little easier to add some shifted beats
- and yes i think that for each new pattern there should be separate instrument instance, not sure on how it is done right now it seems like it is conflicting a little when getting on same line with few little changes. at least instrument settings of last used pattern are set for other pattern if they was not used.

**Comment by badosu** [comment]
@oeai Could you describe better what's your proposal?

After that, could you rename this issue? I really can't figure out what's this about. It would be better to open a separate issue for each proposal and track them.

Also, a lot of time has passed since your original submission, so maybe some of your concerns were already addressed. :-)

**Comment by tresf** [comment]
Yeah we don't really like loaded bug reports because they never get closed.  If he doesn't respond, we can close this out as wontfix and reference it later when it is brought up again.

**Comment by badosu** [comment]
@tresf Can we close this issue?
