### ISSUE TITLE
Sample Track Trimming Bug

### ISSUE THREAD

**Issue by Reaper10** [LMMS/lmms#1960]
#1471 I don't know if I am nitpicking on the Sample Track but, I tried trimming an audio clip down in length from it's original length that I loaded into the Sample Track and it played the hole sample back even tho I trimmed it down.

PS You should be able to be able to trim the sample down from the beginning and not just the end of the sample.

step1
![step 1](https://cloud.githubusercontent.com/assets/8137561/7167940/42ccfcbe-e37f-11e4-8581-cf35b738e66e.PNG)

step2
![step 2](https://cloud.githubusercontent.com/assets/8137561/7167994/9f852148-e37f-11e4-830d-74b7d596c35a.PNG)

step3
![step 3](https://cloud.githubusercontent.com/assets/8137561/7168002/baae8cac-e37f-11e4-8d7e-494e0590619a.PNG)

step4
![step 4](https://cloud.githubusercontent.com/assets/8137561/7168016/d6bdc66a-e37f-11e4-80af-ce1e40f7d0c1.PNG)

**Comment by mikobuntu** [comment]
I believe this is a known bug. There are plans for the future as far as I am aware of for better sampletrack integration in general, where the actual part of the sample that the timeline is passing over will be played. Right now as it stands sampletracks are only triggered at their starting point and play right through, regardless of length of clip set.

**Comment by mikobuntu** [comment]
@Reaper10  please see this post #1471
