### ISSUE TITLE
Make automation recordable

### ISSUE THREAD

**Issue by theguitarplayer** [LMMS/lmms#1961]
We can already record in the piano roll from midi devices and channel piano.  My idea is to record automation from a device that controls levels directly while the song is playing - exactly what piano roll is able to do.

**Comment by Reaper10** [comment]
Like a hardware mixer?

**Comment by Umcaruje** [comment]
![screenshot from 2015-04-16 00 48 18](https://cloud.githubusercontent.com/assets/6282045/7170891/672fc17e-e3d2-11e4-93d1-60af9de7854b.png)

Already possible in LMMS 1.1 

This should be closed.

**Comment by theguitarplayer** [comment]
Thanks Umcaruje!
