### ISSUE TITLE
ZynAddSubFX: use the empty ENV/LFO tab to control Zyn's envelopes

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#1965]
as all knows, zasfx has a 'free /empty' tab-page ENV/LFO. 
Why leave this tab empty
Wouldent it be a neat thing to fill it with lmms controllers for f.i. zasfx's Amp-envelope, Amp-lfo & Filter-envelope ?

**Comment by tresf** [comment]
This may be a good idea for any remote plugins.

**Comment by musikBear** [comment]
nje it wont work for vst, because -how would you link lmms-controllers to unknown features- i cant imagine how. But with zyn, we know exactly what dials we link, and those are static links, a discussion about which are most valuable, is ofcause needed before any decisions. I just listed some i think would be really neat :)

**Comment by tresf** [comment]
:+1:

**Comment by mikobuntu** [comment]
This would be a neat idea. I just wonder how far along ZASF development is in reference to what all controls are exposed to midi... I have only so far found this documentation http://zynaddsubfx.sourceforge.net/doc_3.html

**Comment by curlymorphic** [comment]
hmmm. looks like I didnt click comment earlier :(, it was a lovely post with pics.

I was suggesting we use this space for assignable midi cc controllers, ZASF and many vst's can do "midi learning" allowing the user to assign these controls how they like.

**Comment by mikobuntu** [comment]
@curlymorphic  that is a hateful feeling when you have spent ages preparing a great post esp with pics only to forget to actually post it :zap:       yeah I have to agree here , I'm thinking the term is now called "macros" according to a few other daws :)

**Comment by musikBear** [comment]
@curlymorphic ..woot thats even better! im all for more flexibillity and user options -always, i just have NO knowledge of midi / midi-assign or macros with midi, so im kind of in the blanc, in respect to the actual functionalities 
(done that posting thing, too.. *sigh* ..also on other pages, and FB ..its such a fail feeling of wasted time:)

**Comment by mikobuntu** [comment]
@musikBear Macros are basically knobs which work in the traditional way of 0-127 [value] or from centre to either -64/+64 that control a parameters "range". Macros can be assigned to multiple controls simultaneously and each control can be set to it's own range too..... then to take it further you can automate or modulate these macros, the possibilities are quite endless.
Heres macros in action on Bitwig, so this video should give you a general idea of how macros work https://www.youtube.com/watch?v=rRZd5G6AMmo

**Comment by curlymorphic** [comment]
I feel macros as described above to be a really useful feature, especially when linking controls across various instruments and fx in a chain. Live has a similar feature that I have used. This can be very useful when making presets, setting up a macro exposing the parameters most suited to tweaking.

 What I can see here is two separate features. 

1. to expose more external parameters
2. create a "Macro" system for linking paramters

The reason I feel this should be done separately. Is a macro system should be able to control all parameters in an instrument chain. If the external parameters are exposed as lmms controls, then a macro system would be able to handle both internal and external plugins with ease.

A macro system may need some discussion as to it's implementation, exposing external instruments parameters is a good step in that direction.

**Comment by musikBear** [comment]
@mikobuntu Thanks for the link! - That looks very interesting, indeed.
That is a whole new angle on automation. Making dials 'intelligent', and 'learn' sequence of movements of other controllers.. wow!

**Comment by softrabbit** [comment]
I'm not sure you want ZynAddSubFX to expose all its parameters to LMMS, there are quite a few...
http://linuxmusicians.com/viewtopic.php?f=48&t=11404&start=45#p49118
> the total number of addresses is 6,347,092 at the moment (834 if you only count the 1st voice with the first kit, with the first harmonics, etc etc)

**Comment by curlymorphic** [comment]
> I'm not sure you want ZynAddSubFX to expose all its parameters to LMMS, there are quite a few...

We Could Make use of the Zyn Midi learn feature, then the user gets to select what one of the 6 million parameters they want to control,

**Comment by SecondFlight** [comment]
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.
