### ISSUE TITLE
Give piano roll focus when it opens

### ISSUE THREAD

**Issue by Wallacoloo** [LMMS/lmms#1972]
I often open up the piano roll by double-clicking on a pattern in the song editor. But even though the window is on top and has focus, the piano roll editor ignores all keyboard events until I first click inside of it. This disrupts common workflow practices like opening a pattern, selecting all notes with `ctrl+a` and shifting them up an octave via `ctrl+up`, as it requires an extra mouse press somewhere inside the window before I can activate any keyboard shortcuts.

**Comment by musikBear** [comment]
oh yes, for all who owns a midi-kb, i can understand, because you have to do an 'extra step', before you can get tones from a key-down event. :+1:

**Comment by tresf** [comment]
Closed via #1978
