### ISSUE TITLE
SFXR "Squre Duty" and "Squre Sweep" tooltip typos

### ISSUE THREAD

**Issue by Wallacoloo** [LMMS/lmms#1973]
![lmms-squre-duty](https://cloud.githubusercontent.com/assets/1210751/7214364/71480b90-e598-11e4-8ed6-7d90b75ec22b.png)

I'm fairly certain "Squre" should be "Square" for both the "S.DUTY" and "S.SPD" tooltips. But I'm not positive, because it seems unlikely for a typo like that to occur in two different labels *and* a [code comment](https://github.com/LMMS/lmms/blob/fe797cb09fb897ade99bacdb014fc6fb97af6583/plugins/sfxr/sfxr.h#L266). But [other parts of the code](https://github.com/LMMS/lmms/blob/fe797cb09fb897ade99bacdb014fc6fb97af6583/plugins/sfxr/sfxr.cpp#L106) refer to this value as "square_duty" and "square_sweep".

If somebody can confirm that this is a typo and not some musical term I haven't learned yet, then I can submit a PR for this, otherwise, sorry for the trouble. The code responsible for setting the tooltips is right [here](https://github.com/LMMS/lmms/blob/fe797cb09fb897ade99bacdb014fc6fb97af6583/plugins/sfxr/sfxr.cpp#L340).

**Comment by Umcaruje** [comment]
I'm fairly certain that that is a typo, this is a screenshot of the original SFXR:
![image](https://cloud.githubusercontent.com/assets/6282045/7215721/6fe62ace-e5e4-11e4-9cb1-24103a49325c.png)

And the settings listed are 'Square Duty' and 'Duty Sweep', which is probably 'Square Sweep'

**Comment by tresf** [comment]
Uros, good research!
