### ISSUE TITLE
LMMS Audio Routing, Jack Audio Routing  and  Midi Routing all in one Routing window

### ISSUE THREAD

**Issue by Reaper10** [LMMS/lmms#1977]
The LMMS tab is only for inputs and outputs of LMMS tracks ie, the Inputs box will show all of your track outputs of your Group Tracks, Instrument Tracks and Sample Tracks. The Output box will show all of your track inputs of your Group Tracks, Instrument Tracks, Sample Tracks. 

The Jack tab is any for Jack Audio inputs and outputs ie, the inputs box will show all of your LMMS track outputs ie, your Group Tracks, Instrument Tracks and Sample Tracks. The outputs box shows you any of your jack audio supported software audio inputs you have open. The output box shows you your audio inputs to your interface and or hardware mixer audio inputs.

The Midi tab is only for Midi inputs and outputs ie, the inputs box will show all of your LMMS Midi Instrument Tracks outputs and any of your other midi inputs supportting software you have open. The outputs box shows you your midi inputs ie, midi inputs of your midi keyboard and or your midi supportting hardware mixer.

Routing Box
![cf989716-e1db-11e4-87b4-0f7db6871f46 1](https://cloud.githubusercontent.com/assets/8137561/7217153/1fd1b02a-e5e0-11e4-8e32-21ec7cdd1d6e.png)

Audio Routing Icon/ button

![speaker-512](https://cloud.githubusercontent.com/assets/8137561/7121760/5988bd84-e1dc-11e4-9dce-2a3b811799a3.png)

Jack Routing Icon/ button

![jack](https://cloud.githubusercontent.com/assets/8137561/7217563/816f96e6-e5f7-11e4-9773-6131e907ff59.png)

Midi Routing Icon/ button

![midi-512 1](https://cloud.githubusercontent.com/assets/8137561/7217565/ac7bd304-e5f7-11e4-86f7-d044681fb125.png)

The Routing Icon and or buttons could auto open the right tab if you have the option on in the LMMS options menu.  The Routing box will just open to the Audio Routing  tab if you don't have the auto open option on in the LMMS options menu.

**Comment by tresf** [comment]
Stop submitting garbage.  This is atrocious.

![image](https://cloud.githubusercontent.com/assets/6345473/7222352/9d5b3980-e6da-11e4-98ed-b73472e07af1.png)

**Comment by tresf** [comment]
Also, we don't shamelessly plug your bug reports on every bug you think is related just to promote it.  It is rude, selfish and abusive.  Deleting all shameless plugs.

**Comment by tresf** [comment]
@Reaper10 I have to make this very clear... you are wasting people's time on here because you are littering our bug report with cleanup tasks that should be put toward other items.

This bug report is better than some you've created, but the strange oversized glyph icons make it terrible to read and I have lost patience with cleaning up your posts.  Please create a new one that's cleaner, and let the bug managers decide where it should be listed.

**Comment by Reaper10** [comment]
I'm really I'll work on a new one was rotuing  box ok?

**Comment by Reaper10** [comment]
#1986
