### ISSUE TITLE
When you add vestige, have it automatically pop the find VST plugin dialog

### ISSUE THREAD

**Issue by Wallacoloo** [LMMS/lmms#1983]
This is something from the ancient [TO-DO](https://github.com/LMMS/lmms/blob/master/TODO) file from before lmms was on github.

I believe the rational for this is that to load a VST, you currently have to do 3 steps:
1. Drag VeSTige from the plugin browser onto the track list.
2. Click on the newly created plugin instance.
3. Click "Open other VST-plugin" from within VeSTige & browse to the VST plugin.

and the author wanted this reduced to 1 step: Drag VeSTige into the track list and it will perform step 3 immediately, prompting you for the VST plugin to load.

I haven't used VSTs in LMMS before, but this seems like a useful workflow improvement.

**Comment by Wallacoloo** [comment]
#434 is a relevant discussion that suggests having new instances of Vestige open some user-assigned default VST upon instantiation instead.

**Comment by tresf** [comment]
This was before we could drag+drop from the sidebar file browser.

If we are to add auto-promot for file - based plugins, we should remain consistent and do it for all.

It is my personal experience that people at the plugin level tend to be advanced enough to not need to be spoon fed a blocking dialog, so if we do this:

 1.  We make it configurable
 2.  We do it for all plugins that require a file to work such as SF2, GIG, AFP, etc.

**Comment by musikBear** [comment]
> This was before we could drag+drop from the sidebar file browser.

Is that fixed in Master? No longer an orphan pre-'view' window on left-click ?  Great job :+1: !

**Comment by curlymorphic** [comment]
> It is my personal experience that people at the plugin level tend to be advanced enough to not need to be spoon fed a blocking dialog

This is my feelings, just written better. :+1: 

There is no need to dumb down the lmms experience. This issue may have been more relevant 6 years ago, but I feel less so today.

**Comment by tresf** [comment]
> Is that fixed in Master? No longer an orphan pre-'view' window on left-click ? Great job

You're talking about presets, we're talking about plugins.  In the case of this request, the idea is to prompt the user when an empty plugin is added to the Song Editor or BB Editor to reduce the amount of clicks.  Since 1.1, DLL's can be dragged directly from the left pane file browser into the Song Editor, and they're denoted with a `V` icon so people know they're VST plugins.

What you are describing is a bug with I believe the 1.0 branch which chewed up CPU and memory each time a VST is previewed because we weren't disposing of the remote process correctly.  That is more rare as it requires someone to store VST presets.  The VST preset preview bug was fixed by disabling previews for VSTs.  But you know all of this because you wrote the bug report... #300. :)

**Comment by tresf** [comment]
@Wallacoloo yes, I agree... with the default VST argument.  If we can find a GPL licensed VST plugin (one which wasn't compiled against the proprietary Steinberg headers) then this would be a very nice option.

**Comment by Sti2nd** [comment]
Sounds really smart! Should have been implemented year ago, really

**Comment by musikBear** [comment]
> Since 1.1, **DLL's** can be dragged directly from the left pane file browser into the Song Editor

wooo *that* i did not know :|  
:+1: 
-Need to documented wiki wise - I will try the workflow, and then add a paragraph, to 'working with vst'

**Comment by tresf** [comment]
Can we close this request out then?  I think current functionality beats the proposal from the OP (which was copied from an old TODO).

I understand there's a want for the VSTs to show as actual instruments somewhere as a long-term solution, but I believe that is a different objective.

**Comment by musikBear** [comment]
one thing though, it is not **only** vst-dll's that are marked with a 'V', it is **all** dll's. That makes the workflow less intuitive, and not as potent as i expected.
(i have added a paragraph to the wiki, btw)

**Comment by Wallacoloo** [comment]
@musikbear that happens in the Fx selector too.

**Comment by tresf** [comment]
> one thing though, it is not only vst-dll's that are marked with a 'V', it is all dll's. That makes the workflow less intuitive, and not as potent as i expected.

Sure, but that's already on our radar per:  https://github.com/LMMS/lmms/issues/1807#issuecomment-86239225

So we don't lose track, I've added a dedicated bug report for it here:  #2003
