### ISSUE TITLE
All-in-one routing window

### ISSUE THREAD

**Issue by Reaper10** [LMMS/lmms#1986]
The LMMS tab is only for inputs and outputs of LMMS tracks ie, the Inputs box will show all of your track outputs of your Group Tracks, Instrument Tracks and Sample Tracks. The Output box will show all of your track inputs of your Group Tracks, Instrument Tracks, Sample Tracks. 

The Jack tab is any for Jack Audio inputs and outputs ie, the inputs box will show all of your LMMS track outputs ie, your Group Tracks, Instrument Tracks and Sample Tracks. The outputs box shows you any of your jack audio supported software audio inputs you have open. The output box shows you your audio inputs to your interface and or hardware mixer audio inputs.

The Midi tab is only for Midi inputs and outputs ie, the inputs box will show all of your LMMS Midi Instrument Tracks outputs and any of your other midi inputs supportting software you have open. The outputs box shows you your midi inputs ie, midi inputs of your midi keyboard and or your midi supportting hardware mixer.

Routing Box
![cf989716-e1db-11e4-87b4-0f7db6871f46 1](https://cloud.githubusercontent.com/assets/8137561/7217153/1fd1b02a-e5e0-11e4-8e32-21ec7cdd1d6e.png)

Audio Routing Icon/ button

![stock-illustration-25237577-speaker-icon 1](https://cloud.githubusercontent.com/assets/8137561/7222728/9ea12bfc-e6d9-11e4-97b6-fefd5b09aba7.jpg)

Jack Routing Icon/ button

![jack](https://cloud.githubusercontent.com/assets/8137561/7217563/816f96e6-e5f7-11e4-9773-6131e907ff59.png)

Midi Routing Icon/ button

![midi-128 1](https://cloud.githubusercontent.com/assets/8137561/7222719/757763cc-e6d9-11e4-89d7-269f84ae43f8.png)

The Routing Icon and or buttons could auto open the right tab if you have the option on in the LMMS options menu.  The Routing box will just open to the Audio Routing  tab if you don't have the auto open option on in the LMMS options menu.

**Comment by Sawuare** [comment]
Great idea!

Please correct "the Inputs box will show all of your track outputs" in the audio, JACK and MIDI paragraphs.
It should look like "the Inputs box will show all of your track inputs", not outputs.

**Comment by Sawuare** [comment]
I suggest these names for the window:
"Routes map" or "Connections map".

I suggest a new tab for instrument and effect plug-ins parameters called "Parameters".
This tab will show

**Comment by tresf** [comment]
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.
