### ISSUE TITLE
"Muted" vs "Solo" wording mismatch

### ISSUE THREAD

**Issue by Wallacoloo** [LMMS/lmms#1993]
If you right-click on a track's mute button in the song editor (the green box in the default theme), the name of the control will appear in the context menu as "Muted". If you do the same on the solo button, its context menu shows "Solo".

There is a minor discrepency there: it should either be "mute" and "solo", or "muted" and "soloed", but the tenses should definitely match (I vote for the former).

For comparison, right clicking on other controls, like volume and pan give "Volume" and "Panning" respectively, but neither of those are boolean controls so that's not all that useful to reference.

I would submit a PR for changing Muted -> Mute, but quite a few translations are affected by this so I wanted input.

**Comment by tresf** [comment]
The translation files have a history of breaking other PRs from being merged automatically as they can cause merge conflicts, but don't let that stop you. :)

In regards to the wording, I vote for the former as well. It is easier to maintain and probably easier to translate.  As far as the broken translations... past tense translation is still better than no translation. :+1: 

-Tres

**Comment by Wallacoloo** [comment]
So I did search through the code, and it looks like this is the only place in which "muted" occurs within a string passed to `tr()`. So it *should* be safe to **replace** the "muted" translations with "mute", rather than have duplicate "muted" and "mute" translations.

So should I keep around the translations for "muted"? Or should I just replace them altogether? We can always bring them back via the git history if needed, but I want to be sure they aren't used anywhere first.

**Comment by Wallacoloo** [comment]
Oh, the translations are hierarchical, so I don't have to worry about the translation being used elsewhere.

**Comment by tresf** [comment]
Closed via #1999
