### ISSUE TITLE
Sample Track Playback Bug

### ISSUE THREAD

**Issue by Reaper10** [LMMS/lmms#2001]
I tried to play a sample back in the Sample Track and it stuttered when I tried to play it back.  I tried Wav & Ogg, try it and see if it dose it to you.
https://drive.google.com/open?id=0B0Ar66xX6aiROG92ajFOeEpKSkk&authuser=0
In file Project, Ogg File & Wav File.

**Comment by tresf** [comment]
Steps to reproduce are required.

**Comment by Reaper10** [comment]
sorry about that
! Load file in sample track 
2 press play.

**Comment by tresf** [comment]
Can't reproduce.  Invalid.

**Comment by Reaper10** [comment]
It mite just be me, Sorry

**Comment by tresf** [comment]
> Mites, along with ticks, are small arthropods belonging to the subclass Acari and the class Arachnida. The scientific discipline devoted to the study of ticks and mites is called acarology. *Wikipedia.com*

**Comment by Reaper10** [comment]
the sample tack problem just be me then, Sorry
