### ISSUE TITLE
Sample Track Playback Bug

### ISSUE THREAD

**Issue by Reaper10** [LMMS/lmms#2002]
tried to play a sample back in the Sample Track and it stuttered when I tried to play it back. I tried Wav & Ogg, try it and see if it dose it to you.
https://drive.google.com/open?id=0B0Ar66xX6aiROG92ajFOeEpKSkk&authuser=0
 In file Project, Ogg File & Wav File.
 Steps to reproduce are:
 ! Load file in sample track 
 2 press play.

**Comment by tresf** [comment]
Deleted.
