### ISSUE TITLE
Use OS-defined shortcuts for common operations

### ISSUE THREAD

**Issue by Wallacoloo** [LMMS/lmms#2012]
Right now we have shortcuts for open (`ctrl+o`), undo (`ctrl+z`), redo (`ctrl+y`), etc, hardcoded. But the actual conventions for these common shortcuts vary subtly across OS's. For example, whereas Windows favors `ctrl+y` for redo, Macs favors `cmd+shift+z`. We should really be making use of [QKeySequence::StandardKey](http://doc.qt.io/qt-4.8/qkeysequence.html#standard-shortcuts) in order to be consistent with the rest of the applications running on the user's particular OS.

If there are no objections, I'll probably go through MainWindow.cpp & drop in the replacements.

**Comment by Spekular** [comment]
Sounds good to me!

**Comment by tresf** [comment]
Or we honor both.  OSs aren't really that consistent with undo/redo as the applications seem to use what they want.  If we support both versions of Redo we are likely to get the most positive feedback.

For example, IntelliJ defaults to CTRL+Shift+Z despite Windows favoring CTRL+Y.

In terms of copy/paste, QT already habdles the CTRL modifier for us automatically, so this is a very minor detail.

**Comment by tresf** [comment]
From http://doc.qt.io/qt-4.8/qt.html

| Constant | Value | Description |
|-------------|----------|-----------------|
| Qt::Key_Control | 0x01000021 | On Mac OS X, this corresponds to the Command keys. |

As far as `CTRL + SHIFT + Z`, @Wallacoloo is correct, this seems to be overwhelmingly preferred on OSX over `CTRL + Y`.  Tested:  TextWranger, Chrome, Firefox, Safari.

I'm still not opposed to having multiple shortcuts perform the same function.  For example, this can be observed in Firefox: 
 * `ALT + Left Arrow` and `Backspace` are mapped to the same shortcut on Windows.
  * The `Backspace` shortcut is likely to ease the transition from Internet Explorer
 * Also, `CTRL + F` and `/` both perform a page search in Firefox.
  * The `/` is likely to ease the transition from certain CLI applications, such as vi, man.

**Comment by Wallacoloo** [comment]
Alright. Then I guess we'll have to go through this on a case-by-case basis.

For redo, we should support both ctrl+y and ctrl+shift+z. Which one should
we have displayed in the edit->redo menu action text? There's only room for
one. Should we have the menu item display the OS-preferred shortcut?

**Comment by tresf** [comment]
> Should we have the menu item display the OS-preferred shortcut?

If possible, yes. :)

**Comment by Wallacoloo** [comment]
@tresf yup! That should be fairly trivial to do. I'm going to hold off
until #2009 is settled though so as to avoid any merge conflicts.

**Comment by Wallacoloo** [comment]
#2022 should more-or-less take care of this.

**Comment by tresf** [comment]
Don't mind the OS L&F differences here... We intentionally build on a Lion VM per #1270... 

Tested:

 * CTRL + Z (Pass)
 * CTRL + Y (Pass)
 * CTRL + SHIFT + Z (Pass)


```
OLD                              NEW
```
![screen shot 2015-04-28 at 12 45 22 am](https://cloud.githubusercontent.com/assets/6345473/7362947/e7dc3480-ed3f-11e4-9341-73e15e7684e7.png) ... ![screen shot 2015-04-28 at 12 45 09 am](https://cloud.githubusercontent.com/assets/6345473/7362946/e6a993b4-ed3f-11e4-9299-ea780f8a19c7.png)

@Wallacoloo I'll let you decide to close this or not as you may have some other ideas in mind. :+1:

**Comment by Wallacoloo** [comment]
@tresf "L&F"? Anyway, that looks nice! Pretty much all the common shortcuts except for `undo` are more-or-less the same across operating systems, so I'd consider this resolved.

**Comment by tresf** [comment]
> @tresf "L&F"

Look & Feel.  Yosemite changed fonts and other items quite a bit, so I wanted to fully disclaim that.
