### ISSUE TITLE
Add Ctrl+F shortcut to preset/sample browser

### ISSUE THREAD

**Issue by Wallacoloo** [LMMS/lmms#2013]
The project/preset/sample/directory browser at the left edge of the LMMS window supports filtering files by name via typing into a textbox at the bottom of the pane. Whenever that pane has focus, I think `Ctrl+F` should give focus to the filter textbox.

**Comment by tresf** [comment]
> Whenever that pane has focus, I think Ctrl+F should give focus to the filter textbox.

:+1: And possibly other areas of the DAW.

**Comment by Wallacoloo** [comment]
Closed via #2024.
