### ISSUE TITLE
Can't set tempo to 135 bpm

### ISSUE THREAD

**Issue by andrewRybakin** [LMMS/lmms#2016]
When I'm trying to set tempo for 135 bpm, LMMS rounds it to 130, or 125 to 120, etc.

**Comment by Wallacoloo** [comment]
I see you closed this issue quickly after opening it. Was that an accident, or did you figure out the tempo issue?

**Comment by andrewRybakin** [comment]
Oh, it was my fault:) I've imported midi file, and in this file bpm was wrong (130). It's strange that I couldn't change bpm in LMMS... 
Sorry for late answer. I've found email just now.
And sorry for my bad English:(
