### ISSUE TITLE
enhancement -beat and bass editor playhead

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#2019]
Not sure if mentioned previously (?), but BB-editor need a playhead. It would be good if it was possible to follow the bb-lines 'active' sound
This feature could  be optional enabled  in BB-editor (no need to waste cpu)

**Comment by tresf** [comment]
Duplicate of #1954 #1195

**Comment by musikBear** [comment]
i searched beat and baseline playhead, nothing came up
bnwm - as long as this has a ticket

**Comment by tresf** [comment]
Third result:

https://github.com/LMMS/lmms/search?q=playhead&state=open&type=Issues&utf8=%E2%9C%93
