### ISSUE TITLE
Numerator Automation 

### ISSUE THREAD

**Issue by blrzzzt** [LMMS/lmms#2030]
LMMS only exports song until automation track changes the value for the numerator. Then the export stops and I'm left with half a song :(

I'm on LMMS 1.1.3 Windows 10

**Comment by Wallacoloo** [comment]
Hi benjammin93, thanks for reporting this.

For the record, I'm able to reproduce this in Ubuntu 14.10 with the latest git build. By starting with a time signature of 4/4 and automating the time signature's numerator up to 12 in the middle of a song, it doesn't immediately stop exporting once the automation begins, but rather after 1-2 bars have passed.
