### ISSUE TITLE
VSTi crash on Windows (both 32 and 64 bit)

### ISSUE THREAD

**Issue by kpone33** [LMMS/lmms#2031]
On Windows I can't use VST Instruments using VeSTige as it causes LMMS and the remote VST plugin to freeze. This happens on both 32 and 64 bit versions of LMMS 1.1.3 (current release).

On 64 bit it takes about 10 seconds to a few minutes. It happens when the VSTi GUI is visible. I've tested this with an old version of VB-1 by Steinberg and with SFZ by rcg audio. Also, it's rather random when it occurs. In SFZ it mostly occurs when selecting the file to use, in VB-1 it happened when I wanted to change one of the knobs on the GUI.

**Comment by tresf** [comment]
@kpone33 is there a chance it is related to #1389 or #1183 (both issues are still open).

-Tres

**Comment by kpone33** [comment]
@tresf the issues sound similar, but those aren't the same VSTs. This randomly happens to some other VSTs as well as I've just tested. It's mostly when the mouse cursor is inside the VST GUI or in anything corresponding to it (like a file open dialog)

**Comment by tresf** [comment]
@kpone33 thanks. 

The best thing you can do for the devs is to make a list of steps to reproduce this every time, i.e.:

```
1.  Drag in foo.dll from the file browser to the Song Editor
2.  Open Bar instrument, click xyz to open the abc dialog
3.  ...
4.  Crash, reproducible [every_time|rarely|etc]
```

If it's not reproducible in Linux, we can try out the steps in Wine on a Linux machine and see if we experience the same thing, as Wine gives some more detailed output for these types of things. :+1:

**Comment by Umcaruje** [comment]
@kpone33 can you please offer some steps to reproduce your problem.

**Comment by tresf** [comment]
Closing due to lack of steps to reproduce and lack of response from OP.

-Tres
