### ISSUE TITLE
LMMS 1.1.3 not working properly

### ISSUE THREAD

**Issue by UglinessInTheUI** [LMMS/lmms#2032]
@tresf deleted May 2nd

**Comment by tresf** [comment]
Deleted.  Please use manners or go away.  The team owes you nothing and you have no right to disrespect the developers, artists or users.

**Comment by UglinessInTheUI** [comment]
![113 pianoroll](https://cloud.githubusercontent.com/assets/12206146/7480004/452d2af6-f31a-11e4-94f2-5a906074a27f.jpg)

I'm not trying to disrespect anybody just trying to figure out how did it get so instantly to version 1.1.3 
and become so ugly and broken in the piano roll when version 0.4 still runs fine without graphical
glitches. You guys are scamming it too much on the version numberings and stuff. Stop screwing around.

This broken crap-ware doesn't qualify as version 1.1.3 when compared to version 0.4 

From version 0.4 to 1.1.3 there are no visible improvements anywhere to be seen only a messed up
piano roll full of vertical numbers. If that's not a bug in the 1.1.3 piano roll then what is it ?

Plus people nowadays pay for 32bit color monitors so they can use more than just greyscale bitmaps in the user interface. If I try to colorize the skin it becomes unusable. It only accepts greyscale images for the skin. You guys are guilty, that's all I'm saying.

True or false ?

**Comment by Spekular** [comment]
No, see, you admitted to deleting the artwork, and now you're complaining
that it's ugly. PEBKAC. It's no developers fault if you don't like your own
personal modifications to the program. Also, aside from the wonderful new
theme (which is much improved over 0.4), there have been tons of features
added and bugs fixed and so on. Feel free to browse the merged pull
requests or solved issues.

**Comment by UglinessInTheUI** [comment]
Yes I deleted the artwork because I tried a few downloaded skins and none of those worked properly.
All the skins that I tried so far made everything look way worse and not better so of course then I restored the original skin but it's still showing ugly numbers in the piano roll. The uninstaller was supposed to restore all settings and clean up but it didn't. That's illegal right there. It's called bugsy-ness extreme. So, after uninstalling it and reinstalling it I was left with no user interface at all only the lmms.exe running in the task manager but no graphical user interface. Very screwy programming.

I had to call for an army of helpers just to get the damn UI to show again because uninstalling it and reinstalling didn't do it. You see. That makes the programmers guilty right there.

**Comment by Spekular** [comment]
Huh, I somehow missed your screenshot the first time. Everything looks fine
there though, what's the issue? The numbers and letters are note labels,
they're an optional feature and disabled by default. You can toggle them in
Settings>General>"Enable note labels in piano roll".

**Comment by UglinessInTheUI** [comment]
I see. Thanks for your help. I was thinking it's some kind of graphical glitch or a bug.  I tried to install a different skin and everything got really ugly. It looked way worse than the default skin. Is there a way to change the background color in the piano roll or replace the piano roll background bitmaps to show note lanes like in FL Studio ? That's why I installed different skins because I was trying to make the piano roll background look more like the FL Studio one. Anyway, none of the skins that I tried worked. All those skins made everything look worse.

**Comment by Umcaruje** [comment]
Old themes are not supported on newer versions of LMMS. You can edit the `style.css` file in your theme folder to change the appearence of  the piano roll.

I would have to ask you to watch your language. There is no need to call people scammers and call the software crap-ware. If you keep insulting others and being ignorant, your comments will be deleted.

**Comment by UglinessInTheUI** [comment]
Feel free to delete my comments, no problem there but how exactly do you expect people to know not to try old skins on this new version ? Have you seen it what the UI looks like when you try to use an old skin on this new version ? Plus those note numbers looked like nothing usable and more like covering the entire piano roll with some graphical glitches. 

Also try this. Go to the settings menu , select the entire text path that shows under the "ARTWORK DIRECTORY" , delete it so that the entire field is left blank and press ENTER. Click the OK button and then restart LMMS. Let me know what happens in that case if you do that by mistake.

**Comment by tresf** [comment]
> how exactly do you expect people to know not to try old skins on this new version

If you think things need to be improved, please help, otherwise, go away.

For example, if you have a sound font that you created and are willing to share with the team, you could request the file type be added to the LSP rather than creating a display name of `Top Secret Classified Information N/A 2 Scammers` on the LSP and uploading the tarball to the themes directory.  YOU are the problem.  Fix that and perhaps we can work together to make the free world a better place.

**Comment by tresf** [comment]
>  broken in the piano roll when version 0.4 still runs fine without graphical
glitches.

The preference to display notes on the piano roll (normally off by default) may have been improperly upgraded from a future version.  If you can open a separate bug report outlining the steps to reproduce, we'd be happy to take a look.

> just trying to figure out how did it get so instantly to version 1.1.3 

Google can answer this question, but I'll give into your laziness and quote Wikipedia

> >  **wikipedia.com**: *Version 1.0.0 is the last major version built on the previous 0.4.0*




... 

> This broken crap-ware doesn't qualify as version 1.1.3 when compared to version 0.4

Who is a third party to judge the decision to move to 1.1.3?
 * It was unanimously decided.
 * It has a lot of improvements over 0.4, read the release notes if you think this is a loaded statement.
 * It is just a version number after all (Windows 3.1, Windows 95, Windows XP, Windows Vista, Windows 7, Windows 10).  Who cares?
 * We can only improve upon what we have by people helping.

There is a phrase "don't look a gift horse in the mouth".  It is a concept that those who judge superficially of something that was given to them for free, needn't deserve the gift to begin with.   YOU DON'T DESERVE TO BE USING FREE (AS IN FREEDOM) SOFTWARE.   YOU HAVE NOTHING TO ADD TO THIS PROJECT.  PLEASE SHOVE YOUR DEMANDS TO THE PAID-EXPECTED-DELIVERY I-GET-WHAT-I-PAY-FOR COMMUNITIES.  WE WANT NOTHING TO DO WITH YOUR COMMENTS, YOUR VULGARITY OR YOUR PERSONALITY.  ITS NOT WELCOME HERE.

-Tres

**Comment by UglinessInTheUI** [comment]
Ok first of all I'm here to help but you guys need to take it one step at a time. I uploaded that SF2 in the themes directory because the website is not allowing me to upload files with extension .sf2 it only allows tar.bz2 and even then it gives no option where do I want to upload it. The only option available was the Themes folder. How is that my fault ? I don't see how. 

Second of all , you guys need to tell me what happens if i delete that text by mistake and how do I restore it. If I delete the text in the "ARTWORK DIRECTORY" field and restart LMMS I'm left with a blank window that has no user interface. So, what do I do in that case ? How do I fix it ? What's the secret sauce command switch that restores the default settings ? Nobody knows.

Does anybody know ?

You guys need to try it. Go delete the text under "ARTWORK DIRECTORY" , leave that field blank , restart LMMS and then what ?

Nobody knows. Well , somebody is got to know. Ask the programmers. 

The "Top Secret Classified Information N/A 2 Scammers" that's my name simply because you guys tried to make me start a corporation and an entire business when all I wanted to do is upload a song maybe and some sound fonts. It's illegal for you guys to pretend that in order for people to have access to the forums they need to sign up for a business and start a corporation. That makes the entire https://github.com look like nothing but scammers. Agreed or not ? True or false ?

Maybe the corrupted laws of US allow those kind of scams but my court room right here does not.

Fair enough ?

**Comment by tresf** [comment]
> It's illegal for you guys to pretend that in order for people to have access to the forums they need to sign up for a business and start a corporation. That makes the entire https://github.com look like nothing but scammers. Agreed or not ? True or false ?

Can you please provide a reference to this misinformation you are spewing?

**Comment by UglinessInTheUI** [comment]
What are you saying ? That if I want to upload a LMMS song or some presets or some sound fonts I need to create a corporation ? That's what your website tried on me when I signed up.

**Comment by tresf** [comment]
> the only option available was the Themes folder. How is that my fault ? I don't see how.

You want to use a 4 wheeler to get from your house to your friends house but:
 1. You don't have a driver's license
 2. You can't drive a 4 wheeler on the road.

So you decide to drive the 4-wheeler across your neighbors yard.  When the grass gets torn up:
 1. Is it the state's fault for mandating a drivers license?
 2. Is it your neighbors fault for having a property between you and your friend?

In your world, it is everyone's fault but your own.  Your world steps on generous kind giving people.  You are neither generous, nor kind, nor giving, unless we'd consider manure a "gift".

**Comment by tresf** [comment]
> What are you saying ? That if I want to upload a LMMS song or some presets or some sound fonts I need to create a corporation ? That's what your website tried on me when I signed up.

Wrong, what are YOU saying is the question.  Don't answer a question with a question.  I asked you a question.  I am challenging your statement which I believe to be false. When you issue blame, the burden of proof is on you.  That is something most judicial systems know every well.

**Comment by UglinessInTheUI** [comment]
This has nothing to do with any driver license from anywhere. Your website tried to force me to sign up for a corporation or whatever business account when all I wanted to do is upload a song or some presets. Does that make https://github.com look like illegal scammers ? Yes it does. Is https://github.com guilty ? Of course it is. Can I punish https://github.com extremely if I want ? You bet. How much punishment do you guys want ? Pick your punishment quick so I don't have to pick one for you.

Just go through your registration and login process and you'll see the proof right there.

**Comment by tresf** [comment]
> Your website tried to force me to sign up for a corporation or whatever business account when all I wanted to do is upload a song or some presets. 

This isn't our website.  You are clearly too naive to understand that, but this is github.com.  This is a free bug tracker we use.  Our site is http://lmms.io.

**Comment by tresf** [comment]
P.S. No one owes you anything.  I'm not sure why you feel you can upload tarballs anywhere anytime.  You are clearly more obsessed with justifying your bad behavior then you are with resolving the upload problem, and that ignorance to progress is a waste of everyone's time.

**Comment by UglinessInTheUI** [comment]
Ok , so then github is guilty and forget about it. No big deal. That explains the nickname right there.
That's why the name says: "Top Secret Calssified Information N/A 2 Scammers"

**Comment by tresf** [comment]
> Ok , so then github is guilty and forget about it. No big deal.

Forget about it?  Is that a half-assed apology?  You need to step back and appreciate life a little.  GitHub is the best thing that's happened to open source software in a long time.   Your high expectation are guilty of much more than GitHub.  Find another project.  We don't want you.

**Comment by UglinessInTheUI** [comment]
How is me trying to upload a song for the LMMS community a bad behavior ?

**Comment by tresf** [comment]
> How is me trying to upload a song for the LMMS community a bad behavior ?

4-wheeler, back yard torn up.  I couldn't make it more clear.

**Comment by UglinessInTheUI** [comment]
I don't apologize to scammers so tell github to get a clue.

**Comment by tresf** [comment]
> tell github to get a clue.

No, I'm telling you to.  GitHub is terrific, they offer us a lot.  You are not and offer us slander for something we didn't do and can't have the human decency to say sorry.  Piss off, please.

**Comment by UglinessInTheUI** [comment]
I'm still waiting for that magical solution. You guys are avoiding the answer. How do you restore your precious LMMS to default settings after you delete the path to "ARTWORK DIRECTORY" by mistake ?

It's not enough for github to offer stuff only to you. It needs to treat everybody else fairly and it failed so far.

**Comment by UglinessInTheUI** [comment]
GitHub will soon become my property so I can piss on it if doesn't get a clue quick.

**Comment by tresf** [comment]
The solution is to buy FLStudio.

**Comment by UglinessInTheUI** [comment]
Stop avoiding the issue. I already have all versions of FL Studio with forever lifetime upgrades. That's not the point. The point is, how do you restore LMMS to default settings if you delete the "ARTWORK DIRECTORY" path by mistake. Answer the super important question already. Does anybody know ?

**Comment by tresf** [comment]
Uninstall LMMS completely.  You have lost your opportunity to be treated "fairly".  You are hereby sentenced to life without parole.  We are no longer accepting plea agreements.

**Comment by UglinessInTheUI** [comment]
You guys have pissed on my court room right here without even the courtesy of calling it rain and without paying properly for a permit. Stop screwing around and tell people the answer to the supper important buggy question. Uninstalling LMMS and reinstalling it doesn't solve the problem.

**Comment by UglinessInTheUI** [comment]
How do you restore the entire LMMS to it's default settings if you delete the path to the ARTWORK DIRECTORY by mistake ? That's the only question that matters and you guys have failed so far to provide a solution or an answer.

**Comment by mikobuntu** [comment]
@tresf Don't waste your time replying here, the team needs you to keep focused on positive things that matter !! ;)

**Comment by UglinessInTheUI** [comment]
Uninstalling LMMS is the most positive thing we can do ? Wow ! Seriously ? That's the best we can do ?

**Comment by UglinessInTheUI** [comment]
Tell GitHub to waste their storage space on something more useful in that case. Uninstalling LMMS is the best idea we can come up with ? Seriously ? That's fucking weak. So weak, it should be illegal.

**Comment by UglinessInTheUI** [comment]
Where's that damn source code for LMMS cause I'll have to recode this crap myself somehow. If I wait for you guys to fix it's pretty clear it will never get there anytime soon.

**Comment by Umcaruje** [comment]
Ok so @UglinessInTheUI you actually created a black hole inside your processor when you removed that directory. Nothing will help you, and there is nothing we can do about it. Expect your PC to self destruct very soon.
______

You must be enjoying this sad little game in your sad life, but nobody here owes you anything. If you are polite, people will help you, but acting like a prick will piss people off. Nobody likes trolls, and there is no place on this tracker for you.
