### ISSUE TITLE
Some VST plugins don't fit in window

### ISSUE THREAD

**Issue by rghvdberg** [LMMS/lmms#2037]
**Specs:**
- Ubuntu 14.10 with KX Studio repos (http://kxstudio.sourceforge.net/Repositories)  
- lmms 1.1.3 (package 1:1.1.3-1kxstudio4  amd64)
- wine 1.6.2 / 1.7.41 (tried both version)
- hardware 
  - Dell Inspiron 3847
  - cpu Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
    - configuration: cores=4
  - memory   8GiB
  - display GeForce GT 705
    - driver nvidia-331 
  - multimedia Series/C220 Series Chipset High Definition Audio Controller

**Problem:**
Did a reinstall of my os.
Now I notice that some vst don't fit the windows properly.
- **NoiseMaker** [http://kunz.corrupt.ch/downloads/plugins/TAL-NoiseMaker.zip](http://kunz.corrupt.ch/downloads/plugins/TAL-NoiseMaker.zip) first loads fine but after adjusting a slider/knob the gui jumps to another position in the windows. After touching a slider/knob once again the gui disappears.
- **TyrellN6** [http://www.amazona.de/wp-content/tyrell/TyrellN6_V3_Win.zip](http://www.amazona.de/wp-content/tyrell/TyrellN6_V3_Win.zip) is 'offset' in its window.

Here's a video [https://youtu.be/uIVf9FOeXmk](https://youtu.be/uIVf9FOeXmk)
and screenshots 

![tyrell](https://cloud.githubusercontent.com/assets/10710663/7510101/f9f6ee16-f498-11e4-9b49-11e0e0a28bed.png)
![noisemaker](https://cloud.githubusercontent.com/assets/10710663/7510104/ffd804b4-f498-11e4-9ac1-7f6201ccfdc0.png)

**console output:**

> lmms
> C:\users\rob\Bureaublad\/TyrellN6.log 
> no deskTopFile found 
> unique ID: tYn6
> RemotePlugin::DebugMessage: inputs: 2  output: 2
> RemotePlugin::DebugMessage: creating editor
> fixme:ole:RemUnknown_QueryInterface No interface for iid {00000019-0000-0000-c000-000000000046}
> RemotePlugin::DebugMessage: editor successfully created
> RemotePlugin::DebugMessage: failed getting shared memory
> p11-kit: couldn't load module: /usr/lib/i386-linux-gnu/pkcs11/gnome-keyring-pkcs11.so: /usr/lib/i386-linux-gnu/pkcs11/gnome-keyring-pkcs11.so: kan gedeeld objectbestand niet openen: Bestand of map bestaat niet
> unique ID: ncut
> RemotePlugin::DebugMessage: inputs: 2  output: 2
> RemotePlugin::DebugMessage: creating editor
> fixme:ole:RemUnknown_QueryInterface No interface for iid {00000019-0000-0000-c000-000000000046}
> RemotePlugin::DebugMessage: editor successfully created
> RemotePlugin::DebugMessage: failed getting shared memory

**Attempts at fixing:**
- Resizing the windows has no effect.
- Changing theme has no effect.
- Tried a couple of Ubuntu vbox installs, all with the same results.
  *Strangely in a vbox of Lubuntu 14.10 (with KXrepos) everything is fine ... o.0 
  ![lubuntu1410](https://cloud.githubusercontent.com/assets/10710663/7510706/6ff0ea1c-f49f-11e4-956c-235949871d00.png)
  So I figured maybe install lxde/openbox. It had slightly better results. In openbox Noisemaker loads fine but TyrellN6 is still loaded wrong. So I removed the lxde / openbox stuff

**Comment by tresf** [comment]
Thanks for the extremely detailed bug report.

> Strangely in a vbox of Lubuntu 14.10 (with KXrepos) everything is fine ... o.0

That is strange.  Maybe due to DPI or graphics driver or a bug with the way the plugin is placed.  Does this occur on DSK Musicbox too?

**Comment by rghvdberg** [comment]
DSK Musicbox loads fine ... 
tried different window managers
marco (mate) and kwin, all have some sort of problem with placing the windows

**Comment by rghvdberg** [comment]
installed linux mint 17.1 
no problems here

**Comment by tresf** [comment]
@rghvdberg, so this problem is resolved with Linux mint?  Can you tell us the QT and Wine versions for what works and what has the graphic anomalies?

**Comment by Wallacoloo** [comment]
So I'm a bit late here but:

The way the ui stuff is laid out for *native* instruments is that there is
a top-level widget inside the instrument's window. If you accidentally
reposition this widget programmatically, when you meant to reposition the
window, you get this exact same graphical glitch.

I don't know if this is similar to how VSTs are handled, but if it is,
there could be some code path that does just that.

**Comment by rghvdberg** [comment]
the problem is resolved in Linux Mint 17.1 cinnamon 
hope this helps
>dpkg -l | grep qtcore
ii  libqtcore4:amd64                            4:4.8.5+git192-g085f851+dfsg-2ubuntu4               amd64        Qt 4 core module
ii  libqtcore4:i386                             4:4.8.5+git192-g085f851+dfsg-2ubuntu4               i386         Qt 4 core module
ii  qtcore4-l10n                                4:4.8.5+git192-g085f851+dfsg-2ubuntu4               all          Qt 4 core module translations

>wine --version
wine-1.7.41

I don't have information about the versions don't work cause I reinstalled :-/
I have tried various debian/ubuntu based distros in virtualbox, all of them had the glitches, except for Mint, so installed that and on hardware it works too. (and very good btw)

**Comment by rghvdberg** [comment]
Tested in virtualbox debian 8, same glitch appears.

>dpkg -l | grep qtcore
ii  libqtcore4:amd64                      4:4.8.6+git64-g5dc8b2b+dfsg-3       amd64        Qt 4 core module
ii  qtcore4-l10n                          4:4.8.6+git64-g5dc8b2b+dfsg-3       all          Qt 4 core module translations


>wine --version
wine-1.7.41

**Comment by rghvdberg** [comment]
Test in Linux Mint 17.1 Mate , everything works ok
Could it be that the displaymanager (mdm) has something to with it ?

**Comment by karmux** [comment]
TAL NoiseMaker has been always running away here after a couple of clicks. Initial load is correctly displayed but every mouse click shifts it away until nothing is seen. Still same in Kubuntu 16.04, Wine 1.8 and LMMS master.

**Comment by musikBear** [comment]
FYI No problem with TAL or Tyrell in windows. Guess this is a linux exclusive issue.

**Comment by PhysSong** [comment]
I guess #3786 should fix this issue. @rghvdberg Could you try our latest release(1.2.0-RC5) if you're still interested?
