### ISSUE TITLE
LMMS source code is incomplete and not able to compile on Windows

### ISSUE THREAD

**Issue by UglinessInTheUI** [LMMS/lmms#2039]
I downloaded LMMS source code and it's incomplete. Also is missing the CompileAndRun button. That part is illegal right there in any country and any court room not just in my court room right here.
Source code needs to include all the compilers and dependencies , all libs and all those extras in order to compile and run as soon as I download it and unpack it. Why is the CompileAndRun button missing ? Cause you scammers and you scamming it extra special, that's why. That's illegal everywhere god damnit.
 
After downloading the source code it looks like it still needs lots of extras. Even after downloading all the extras is still not able to find libsndfile despite the fact that i downloaded that one too. Where do i have to place libsndfile for the compiler to find it ?

Looks to me like some kind of extreme discrimination going on towards Windows. Are you guys guilty again of organizing crimes against Windows and Windows users ? How much is the punishment for that ? Ask the Supreme Court of USA. Make it quick cause time is money.

After you do that also make sure you ask my court room right here because all your illegal activities are happening in my territory. My zone and my computer is not governed by the laws of USA unless I say so. That means extra special punishments for all of you. 

Don't even think about saying some illegal crap like:
- Oh you know, the developers don't owe anybody anything for any reason because that scam right there will hold true in my court room for about one full second. After that second expires you will also see how that excuse will expire along with it.

See my point ? 

You guilty. 
You punishable. 
You scammers.

Who the hell would want to download some source code that is missing all the important parts and is always guaranteed to be incomplete and non-functional with tons of missing components ?

You guys failed to include the full and 100% complete source code with the compiler + all the libs + the CompileAndRun button.

It was supposed to be ready to compile and run right after download.

Fix it !

**Comment by tresf** [comment]
Not sure if this is supposed to be funny, but our compile instructions are complete and in the wiki.  Feel free to take a gander when you are done with your ranting.
