### ISSUE TITLE
valgrind error on vestige plugins initialization failure

### ISSUE THREAD

**Issue by Bloody95** [LMMS/lmms#2041]
On Linux, when loading a vestige plugin fails (improper wine configuration), the vestigeInstrument::loadFile() function calls closePlugin();

In this case, the m_scrollArea field is not initialized.

sha1 : 388dfbc38ccf4a5e2779b2260e5a4d0dbb1c332a

```
diff --git a/plugins/vestige/vestige.cpp b/plugins/vestige/vestige.cpp
index 45fd94a..79a691f 100644
--- a/plugins/vestige/vestige.cpp
+++ b/plugins/vestige/vestige.cpp
@@ -77,6 +77,7 @@ vestigeInstrument::vestigeInstrument( InstrumentTrack * _instrument_track ) :
        m_plugin( NULL ),
        m_pluginMutex(),
        m_subWindow( NULL ),
+       m_scrollArea( NULL ),
        vstKnobs( NULL ),
        knobFModel( NULL ),
        p_subWindow( NULL )
```

**Comment by Wallacoloo** [comment]
Good catch. If you submit this (and your other reports) as a [pull request](https://help.github.com/articles/using-pull-requests/), then one of the project administrators can easily merge this fix and the changes will be linked against your github account / email address, which is generally useful information to preserve.
