### ISSUE TITLE
valgrind error in SampleBuffer::decodeSampleSF()

### ISSUE THREAD

**Issue by Bloody95** [LMMS/lmms#2042]
valgrind reports an error in the sf_open() call at the beginning of the SampleBuffer::decodeSampleSF() function. According to the sf_open() documentation, the format field of the sf_info structure must be initialized.

sha1 : 388dfbc38ccf4a5e2779b2260e5a4d0dbb1c332a

```
diff --git a/src/core/SampleBuffer.cpp b/src/core/SampleBuffer.cpp
index 6941c6d..4605162 100644
--- a/src/core/SampleBuffer.cpp
+++ b/src/core/SampleBuffer.cpp
@@ -385,6 +385,8 @@ f_cnt_t SampleBuffer::decodeSampleSF( const char * _f,
        f_cnt_t frames = 0;
        bool sf_rr = false;
 
+       sf_info.format = 0;
+
        if( ( snd_file = sf_open( _f, SFM_READ, &sf_info ) ) != NULL )
        {
                frames = sf_info.frames;

```

**Comment by zonkmachine** [comment]
Hi!

Nice catch! Sorry for the epically slow response time.

The preferred way to submit code here is by issuing a pull request.
https://github.com/LMMS/lmms/wiki/Submitting-a-patch
I'll do a PR this time as we're about to release soon. Everything you need to know on GitHub is there in the wiki...

If you want to fire up valgrind again we're more active here now than last May so there will be faster response this time... :fingers_crossed: :smiley:
