### ISSUE TITLE
Segfault in zynaddsubfx/src/Nio/NulEngine.cpp destructor

### ISSUE THREAD

**Issue by Wallacoloo** [LMMS/lmms#2049]
As reported by @jayay in his [comment](https://github.com/LMMS/lmms/pull/1991#issuecomment-100551390), the NulEngine destructor appears to cause a segfault. He kindly provided a stack trace for this: https://gist.github.com/jayay/b62b1ec3b5320820a3d6

This problem affects my system as well. The stacktrace is very confusing in that no possible code path should lead to the lmms Engine being destroyed from within the zynaddsubfx NulEngine destructor.

The NulEngine destructor is empty and the class has no non-trivial members. However, NulEngine inherits from zynaddsubfx/Nio/AudioOut which inherits from zynaddsubfx/Nio/Engine.

So it's likely that gdb links this error to the wrong Engine class. Alternatively, the includes might be misconfigured such that Nio/AudioOut is actually inheriting the wrong Engine, but I highly doubt that. 

Perhaps this is a double-free issue on our end.

**Comment by fundamental** [comment]
To my knowledge multiple conflicting definitions of the same class in the same namespace is resulting in a case where the vtable of one is getting overwritten by the other (same name/namespace means same vtable symbol). One of them needs to be renamed or namespaced.

**Comment by Wallacoloo** [comment]
That would make sense, as it could explain why the error arose after
changing lmms' Engine to subclass QObject (before it was a base class with
no virtual methods).

On the other hand, I thought this was what name mangling was for. Don't
these classes actually get assigned different symbol names in the binary
based upon the layout of their members/parents?

**Comment by fundamental** [comment]
On 05-12, Colin Wallace wrote:
> On the other hand, I thought this was what name mangling was for. Don't
> these classes actually get assigned different symbol names in the binary
> based upon the layout of their members/parents?
Nope, symbol mangling is mainly designed to handle various arguments to
functions/methods/etc and their scope.
For example looking at another project of mine, the class 'zVBar' results
in the symbol _ZTV5zVBar which c++filt translates to the vtable symbol
for that class.
Nothing in that symbol provides information about the class itself, it
just states that "_ZTV" it's a vtable "5" with a 5 character name
"zVBar" named 'zVBar'.

**Comment by Wallacoloo** [comment]
I can confirm that placing Zyn's Engine class inside its own namespace does resolve this issue. If we go with a namespace fix, I think it makes more sense to place all of LMMS' classes in a `lmms` namespace from a maintenance point of view.

What do you say, is there any reason we should *avoid* placing all lmms classes into an lmms namespace?

As a side note, it looks like both the LMMS Engine.h and the zyn Engine.h use the exact same include guard #define. I'd say we're getting pretty lucky that this hasn't caused any (noticable) errors yet either.

**Comment by tresf** [comment]
> What do you say, is there any reason we should avoid placing all lmms classes into an lmms namespace?

I'd like to hear @Lukas-W's thoughts on this.  :)

**Comment by Wallacoloo** [comment]
Well I moved everything in src/* into a new `lmms` namespace (thus the plugins remain in the global namespace). This has fixed the issue with Zynaddsubfx, but I'm currently getting some minor graphical glitches. Specifically, the grey cog next to each track is rendering as an oversized empty grey button, some colors are slightly different, and the timeline of the song editor only has vertical lines instead of both vertical and horizontal lines, plus it lacks the background color alteration that normal occurs for every group of 4 bars. There are lots of minor things like different icons being used for the master volume/pitch slider, and some icons are sized slightly differently.

I suspect it's either an issue in the way paths are specified in themes, or perhaps something in the .ui files created in QCreator rely on absolute classpaths.

My branch is available at [wallacoloo/namespaced](https://github.com/Wallacoloo/lmms/tree/namespaced) for testing if anyone wants to take a stab at it. If not, I'll probably figure it out eventually.

**Comment by Wallacoloo** [comment]
Looks like the theming issues is due to Qt's style sheet automatically taking namespaces into account ((link)[http://doc.qt.io/qt-5/stylesheet-syntax.html#widgets-inside-c-namespaces]). Thus 

```css
TrackOperationsWidget > QPushButton::menu-indicator:hover {
	image: url(resources:trackop_h.png);
}
```

needs to be changed to
```css
lmms--TrackOperationsWidget > QPushButton::menu-indicator:hover {
	image: url(resources:trackop_h.png);
}
```

An easy fix, but it breaks theme compatibility.

**Comment by tresf** [comment]
> An easy fix, but it breaks theme compatibility.

FYI, We've stopped providing theme support between minor releases via [`#1442`](https://github.com/LMMS/lmms/pull/1442/files), it is just too volatile until we get the refactoring, renaming and decoupling finished (e.g. [`#1353`](https://github.com/LMMS/lmms/pull/1353/commits)).

If you'd like to entertain the possibility of upgrading styles, we could offer an `upgrade()` function in [`LmmsStyle.cpp`](https://github.com/LMMS/lmms/blob/master/src/gui/LmmsStyle.cpp#L131) and build a HashMap of compat fixes.

**Comment by Wallacoloo** [comment]
I created a new pull request that solves this issue (and others): #2064.

Qt doesn't expose its internal css parsing functions necessary to preserve theme compatibility (css isn't quite simple enough for a string replace of the old class names with the namespaced ones to do the job error-free), so maintaining compatibility with existing themes would take more effort than it's likely worth.

**Comment by tresf** [comment]
Duplicate of #2269.  Both bug reports have good information in them, but that one is slightly easier to find when searching the tracker.
