### ISSUE TITLE
Beat+Bassline Editor: Edits affecting all beats in song editor.

### ISSUE THREAD

**Issue by kyle-rader** [LMMS/lmms#2051]
## Description
It appears the drop down menu at the top of the beats+baseline editor doesn't actually change the selected beat/bassline being edited.  **Or** I just don't fully understand the intended functionality.

## Example
1. Add a beat in the song editor
2. Select a measure to play this beat
3. Right click that measure and open in beats+bassline editor
4. Add a sound there.
5. In the song editor, add a second beat.
6. Select another measure for beat 2 to be active.
7. Right click that measure for beat 2 and open in the beat+bassline editor.
Opening this 2nd beat shows the same sound that had been added to beat 1 but with no selected beats on.  If you remove that sound from the beat editor, you will find that it has also been removed from beat 1 along with whatever beat you may have already created there - effectively losing your work.

This may be intended but if so I think removing a sound that is in use in other beats should raise some warning before proceeding. 

Thanks!
(P.S. I am a developer interested in music creation and mixing)

**Comment by tresf** [comment]
@kyle-rader Your first sentence reads like a bug, but after reading your detailed steps (thanks) I believe you're reporting a duplicate of #453.

**Comment by kyle-rader** [comment]
@tresf Aha!  Yes that is exactly the kind of feature I would intuit.

**Comment by tresf** [comment]
:+1:
