### ISSUE TITLE
illogical controller for level on Calf Equalzer 12 bands ladspa 

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#2052]
imo the _Level_ controllers are illogical. They are now calibrated for span ~0..~64, but logically levels for an EQ should be calibrated **around 0** - like -32..0..32. This would allow the user to add and subtract from the chosen freq. (just as f.i. in the **C*Eq**)
Furthermore are the graining for _level_ and _gain_, much too rough, and could easily be divided with a factor 10 -at least. That would give a much more sane span for the dial(s) -Now they seriously overload at setting ~10 %

**Comment by tresf** [comment]
Can you please take screenshots and illustrate what you are describing?

The code for the EQ is here: https://github.com/LMMS/lmms/blob/master/plugins/LadspaEffect/calf/src/modules_eq.cpp

I don't see anything in the EQ class specifically bound to the range you are describing, so if you can help locate the place in the code that is limiting this range it will make fixing this issue more likely.

P.S. You can search through the source code using the search bar at the top of this page.

-Tres

**Comment by softrabbit** [comment]
No need for screnshots, on Linux you can use ```analyseplugin``` to figure out properties of LADSPA plugins, e.g. ```analyseplugin /usr/lib/i386-linux-gnu/lmms/ladspa/calf.so```. Some interesting control ranges for this EQ:

```
        "Input Gain" input, control, 0 to 64, default 1
        "Output Gain" input, control, 0 to 64, default 1
        "Level L" input, control, 0.015625 to 64, default 1
        "Level H" input, control, 0.015625 to 64, default 1
        "Level 1" input, control, 0.015625 to 64, default 1
        "Q 1" input, control, 0.1 to 100, default 1, logarithmic
```

**Comment by tresf** [comment]
:+1: 

https://github.com/LMMS/lmms/blob/master/plugins/LadspaEffect/calf/src/metadata.cpp#L706

-Tres

**Comment by SecondFlight** [comment]
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.
