### ISSUE TITLE
Making LMMS a Non-Destructive Editing DAW

### ISSUE THREAD

**Issue by Reaper10** [LMMS/lmms#2057]
Could you make LMMS a Non-Destructive Editing DAW?  Ie make it so if you cut a part out of a clip and change your mind and want the part back  you can just stretch the end of the clip back out, and the part is restore.

**Comment by jack126guy** [comment]
I thought it was non-destructive...

**Comment by tresf** [comment]
@Reaper10 has a track record for poor quality bug reports and spamming our tracker with never-ending and often redundant enhancement requests.
