### ISSUE TITLE
Old Movie Projector Sound FX plugin

### ISSUE THREAD

**Issue by Reaper10** [LMMS/lmms#2063]
Could someone make a movie projector sound simulator FX plugin? It could be a Fx plugin like your vinyl plugin.   As an Fx plugin  you can have it on a buss track and you can have unlimited tracks sened to the bus and set the amount of the send.  What if you're recording your guitar lick on the sample trackor a whole track and you need it to sound like it's coming out of a Old Movie Projector.  If it's a plugin you can tweak the sound more then you can a sample.
It sound like this:
https://www.youtube.com/watch?v=it4vOMqK2yk
https://www.youtube.com/watch?v=IlwKt9FRouk

**Comment by mikobuntu** [comment]
A plugin for just one sound is not logical and I doubt very much that it will be implemented into LMMS. Try freesound or ccmixter for a similar sample instead please.

**Comment by Reaper10** [comment]
it could be a Fx plugin like your vinyl plugin.

**Comment by tresf** [comment]
@Reaper10 this may already be possible via our plugins by using a series of distortions, etc.  If that is not possible, some basic automation can likely create it too.  Probably best for the forums.

In terms of an FX plugin, that would be a different story.  Might want to look for a VST plugin that does this and import it in.

**Comment by mikobuntu** [comment]
@Reaper10 . I was just thinking the same thing about the vinyl plugin ( which is a bundled LADSPA effect ) someone could probably write this quite easily. I would look at using ZynAddSubFX and using some wizardry with effects you could get close to this sound.

**Comment by dednikko** [comment]
If anything, you might modify the vinyl plugin, but, honestly, you could
just snag a sampled recording from Freesound.

I did just that for a short film intro.

**Comment by Reaper10** [comment]
I tried looking of a plugin couldn't fine one I'll try other pugins but could look into it as a FX plugin someday?

**Comment by musikBear** [comment]
ahemm.. eh.. how about .. well eh ..Record or ... dl the actual  ... file you linked to ?! :mouse:

**Comment by Reaper10** [comment]
But as an Fx plugin  you can have it on a buss track and you can have unlimited tracks sened to the bus and set the amount of the send.  What if you're recording your guitar lick on the sample track and you need it to sound like it's coming out of a Old Movie Projector.  If it's a plugin you can tweak the sound more then you can a sample.

**Comment by tresf** [comment]
> your guitar lick on the sample track

I hate it when my guitar licks the sample track. :lips: 

Agreed though, an FX plugin is ideal.

**Comment by Reaper10** [comment]
guitar lick on the sample track sorry about that LOL :laughing:

**Comment by SecondFlight** [comment]
Use a sample.
