### ISSUE TITLE
Instruments description not translated in Instrument plugins browser

### ISSUE THREAD

**Issue by midi-pascal** [LMMS/lmms#2066]
The description of the instruments is not displayed in the current language in the Instrument plugins browser even where translation exists.
In PluginBrowser.cpp, the code is there to display the translated description but is does not work.
PluginBrowser::tr( m_pluginDescriptor.description ) always return the English description.

I am looking for the glitch right now...

**Comment by midi-pascal** [comment]
Found the translation problem:
PluginBrowser::tr() does not work in this case. One must use qApp->translate() instead as per Qt documentation.
Creating a pull request right now...
The same problem occurs for the plugins description in "Add effect" window.
Now looking a it!

**Comment by midi-pascal** [comment]
Found!
Added to PR #2065

**Comment by Umcaruje** [comment]
Closed via #2065
