### ISSUE TITLE
LMMS doppler FX plugin

### ISSUE THREAD

**Issue by Reaper10** [LMMS/lmms#2067]
Using parts from Amplifier, LFO controller, Dual filter and the XY pad and the gain slider form the new delay plugin you can make a LMMS version of grm tools doppler.

What is grm tools doppler:
https://youtu.be/MCyTBNlZK-I?t=1m50s

How it works:
up and down on xy pad = volume
side to side on xy pad = pan
![lmms doppler](https://cloud.githubusercontent.com/assets/8137561/7761693/a676d6a0-ffee-11e4-98e5-0852baca0394.png)

controller point
![controller point](https://cloud.githubusercontent.com/assets/8137561/7761710/e75f9828-ffee-11e4-9913-d49d6fed815b.png)
The small points circle around the big point are the controller point ie, the small points circle around the big point to how the speed of the LFO

**Comment by tresf** [comment]
You really have to stop it.  Just buy these commercial plugins or learn C++.

**Comment by Reaper10** [comment]
I would buy  it but it's  an Rtaz plugin ie only on Pro Tools I like LMMS better can afford Pro Tools.

**Comment by tresf** [comment]
Regardless, it costs hundreds of dollars/euros.  If you cherry-pick every plugin you like, it will be a never ending list.  Perhaps you should have a dedicated thread called "Reaper10's wish list" and just type whatever you like in there.

**Comment by tresf** [comment]
P.S. The documentation on that plugin says this:

> GRM Tools Classic is a bundle of eight plug-ins that provide superb tools for sound
enhancement and design. They are available in AAX, Audio Unit and **VST** (32 & 64 bits) and
RTAS (32 bits) formats, and also as Stand-Alone application. 

Are you sure it doesn't work with LMMS?

**Comment by dednikko** [comment]
This seems like a really cool tool. Is there a preset file we can use?

Any chance you could share an mmpz so we could see what that would look
like in action? Maybe just use one of ZynADDSubFX's wind presets?

Actually, maybe we could look into devs and users coming up with more
presets for the built in instruments. I can think of a few presets we could
toss in that are based on included sounds/presets.

**Comment by Reaper10** [comment]
I'm not sure I was just trying a pro tool to LMMS if will pardon the pun.
