### ISSUE TITLE
ZynAddSubFX presets "Splited" and "Splitted" are identical

### ISSUE THREAD

**Issue by ycollet** [LMMS/lmms#2072]
I used the current lmms master.
In the  ZynAddSubFX presets directory, presets in "Splited" and "Splitted" directories are identical.

**Comment by grejppi** [comment]
Most likely it was changed in Zyn upstream, and when they were copied to LMMS tree the old folder remained there.

**Comment by zonkmachine** [comment]
Upstream typo fixed here:
https://sourceforge.net/p/zynaddsubfx/instruments/ci/a06fadb98d2d9937a2e0127f1a9f7e5f0237c29b/

**Comment by Umcaruje** [comment]
Closed by #2489
