### ISSUE TITLE
Mismatch between selected tools in instrument editor

### ISSUE THREAD

**Issue by ycollet** [LMMS/lmms#2073]
I use lmms 1.1.3 compiled from sources on fedora 21 64 bits.

* Create an instrument sequence.
* Clone this sequence in the song editor (via control + click + drag)
* Open the instrument editor via a double clic on the cloned sequence

-  the selected tool in the button bar is pencil, but the tool associated to the cursor is erasor.

**Comment by Spekular** [comment]
I think this has been fixed, and I'm certain that it's been reported, but I
can confirm that this happens for me too, Win 7, x64, 1.1.3.

**Comment by ycollet** [comment]
I tried to test on lmms from master but I was not able to perform the ctrl + click + drag. The sequence is not cloned and an empty sequence is dropped.

**Comment by Wallacoloo** [comment]
I'm getting slightly different results in 64 bit Windows 8.1 for the 1.1.3 version. The same thing happens, except the selected tool is the pencil and the actual tool becomes the *selection box*.

**Comment by tresf** [comment]
Related:  #431

**Comment by zonkmachine** [comment]
> the selected tool in the button bar is pencil, but the tool associated to the cursor is erasor

It will now open up with the last selected tool and there is no mismatch between the cursor and selected tool.


> I tried to test on lmms from master but I was not able to perform the ctrl + click + drag. The sequence is not cloned and an empty sequence is dropped.

This now works.

Closing
