### ISSUE TITLE
Automation Editor: Missing pixmap files

### ISSUE THREAD

**Issue by midi-pascal** [LMMS/lmms#2075]
In automation editor, the pixmaps files associated with the buttons "Flip vertically" (flip_y.png) and "Flip horizontally" (flip_x.png) are missing in the default theme directory. (Master)

**Comment by Spekular** [comment]
@diizy I think you said that tou would create these, since you worked on
the retheme?

**Comment by Umcaruje** [comment]
I've started making these icons. Here is what I have so far:  
![image](https://cloud.githubusercontent.com/assets/6282045/8582550/cde11cd8-25c7-11e5-94f0-9e0d82b4362f.png)

Feedback appreciated.

**Comment by midi-pascal** [comment]
:+1:

**Comment by tresf** [comment]
:+1:

**Comment by musikBear** [comment]
:+1: nice!

**Comment by midi-pascal** [comment]
Merge, someone? :smile:

**Comment by zonkmachine** [comment]
:+1:

**Comment by Umcaruje** [comment]
![](https://cloud.githubusercontent.com/assets/6282045/8621475/0cb129d0-2726-11e5-96bf-bbfdbfeeb1bb.png)

That's the final look. Opened PR #2178

**Comment by zonkmachine** [comment]
Cool! They blend in well with the other buttons.

**Comment by tresf** [comment]
:+1:

**Comment by Umcaruje** [comment]
:+1:
