### ISSUE TITLE
Adding Video Support to LMMS

### ISSUE THREAD

**Issue by Reaper10** [LMMS/lmms#2079]
This is  a long  term enhancement Could you build the Video support into LMMS? Why you may ask it would be good for those who are working on a movie and you're doing the soundtrack or sound FXs or voice over, you can see  the video and hear the sound from the video inside of LMMS  .

XJADEO - The Video Monitor 

The first way to do this is built in the XJADEO - The Video Monitor to LMMS. . The gear menu has these options remove track and open video and all other options of XJADEO You can all so open video by the open video button on the video screen. 
![ss1 1](https://cloud.githubusercontent.com/assets/8137561/7900048/cf233142-0706-11e5-87c3-6f83fa80500f.jpg)

open video window
![open video](https://cloud.githubusercontent.com/assets/8137561/8482876/27b7a008-20b2-11e5-88dd-0e8e22778df7.PNG)

The XJADEO - The Video Monitor is default way to use videos in LMMS unless you have a video editor.

Streaming a Video
If a user has a video editor they should be able to be to stream a the video signal from the video editor in to the LMMS video screen via a jack like video signal routing box window.

![video track gui](https://cloud.githubusercontent.com/assets/8137561/8483307/83f25c34-20b5-11e5-8671-1108898ccd64.png)
 

the video track
![tc3](https://cloud.githubusercontent.com/assets/8137561/7900036/045f0b34-0706-11e5-8e0e-2355c3a96870.jpg)

LMMS Track
![video track](https://cloud.githubusercontent.com/assets/8137561/7900039/3fb43e16-0706-11e5-947c-ca04ae669f80.png)
![video track2](https://cloud.githubusercontent.com/assets/8137561/7900040/4ccff14e-0706-11e5-9c1e-e9ef5e7df9e2.jpg)

LMMS Video Screen GUI
![video track gui](https://cloud.githubusercontent.com/assets/8137561/8481221/8c7c9e40-20a7-11e5-8ba7-3bed1629aec6.png)

![rig698mil 1](https://cloud.githubusercontent.com/assets/8137561/8482892/49b8b76e-20b2-11e5-97a8-40b274541d9e.jpg)

Full Screen button 
![fullscreen_icon 1](https://cloud.githubusercontent.com/assets/8137561/8481257/c7fa4de6-20a7-11e5-95ed-e7048a6b17b1.png)

Track icon/ button
![video track icon](https://cloud.githubusercontent.com/assets/8137561/7900045/aa9ce41c-0706-11e5-9dff-c75dee45c51e.jpg)

The video track is a two in one track ie the video timeline and audio track from the video are together. You can send the sound from the video into the LMMS mixer via the fx Channel box you also have the pan and volume knobs and the mute and solo buttons. Jack trace port will keep the  the video in sync with your video editor.

**Comment by hashhakaj** [comment]
Hello
I agreed with this idea . 
since the word LMMS is an abbreviation of Lunix Multi Media Studio. and the word Multimedia is general meaning of audio video content.
until now, LMMS still handling the word Multimedia for audio only or , I think LMMS will become Lunix Music Maker Studio. :)

**Comment by Wallacoloo** [comment]
Well "Linux MultiMedia Studio" has long since been a misnomer, since it
runs on more platforms besides Linux, so the name argument doesn't really
hold much weight.

**Comment by hashhakaj** [comment]
I don't blame the word Lunix itself. my focus in word Multimedia that doesn't had a real function in the software itself :). 
I know it's not that important since most people know more about word "LMMS" than its full name

**Comment by Spekular** [comment]
I think we decided a while back that LMMS doesn't stand for anything
anymore.

**Comment by hashhakaj** [comment]
hmm, that's worse. we know that Fruity Loops Studio now known as FL Studio and it become quite popular with this short name. So, if someone asked about what FL stands for, it has.
anyway, I won't this topic goes to judge the name of the software. including video player option in LMMS is cool feature of multimedia Studio. 

that's all :)

**Comment by musikBear** [comment]
> I think we decided a while back that LMMS doesn't stand for anything

.. sounds chillingly similar to most danish political parties........

Naee c'on ..
Lucas(?) gave the perfect LMMS acronym explanation, believe almost 2 y ago now.. ?
LMMS : el-em me(nt)s -pronounced **Elements** The modular DAW !

better then my own
*Leisure music making studio*
for hobby musicians  :)

Now just to address the actual topic, down the road in a distant future lmms could have video, sure, but right now, imo there is 100+1 more important things to look at.
A thing that could be even more interesting than 'simple' video, and could be looked at *in a distant future* too, was export of a stream of values, corresponding to the music. That stream could then be used for work on music **visualization** proprietary programs

**Comment by tresf** [comment]
This pipe dream has no basis for reality, at least not in the forseable future.

**Comment by Umcaruje** [comment]
I agree with Tres, this is pretty much out of scope now.

**Comment by b4zz4** [comment]
It is the I that was looking for to edit the sound of the http://4232.cf

**Comment by b4zz4** [comment]
I think that could add  synchronism in jack and not having to use a linea of time. Only xjadeo or blender and jack

example musescore:

![2017-08-06-160841_727x124_scrot](https://user-images.githubusercontent.com/643833/29006220-e9f6ddbc-7ac1-11e7-8515-b39a2b4880d6.png)

**Comment by EaryChow** [comment]
Why is this closed? I am trying to make a sound track for a video, and I am surprised that LMMS does not have the option. If Davinci Resolve has a piano roll feature I would definitely use Davinci, but it doesn't. I know that most other DAWs like Logic, FL Studio and Cubase have built in video players and this helps much when making video soundtrack. This is important, we need to see what's on the visual to sync it with the music, like an explosion in the video syncing with a heavy bass drum beat. 

> has no basis for reality

> down the road in a distant future lmms could have video, sure, but right now, imo there is 100+1 more important things to look at

So you guys thought this was not important? How should we make soundtracks for videos without being able to sync the video with the music in the timeline? Now a workaround might be finding a video player vst that works with LMMS, but I have yet to find one. Or just simply switch to other softwares.

**Comment by IanCaio** [comment]
@EaryChow

It's not that the feature is not important, obviously importance is a matter of personal needs as well. It's just that at the current state and focus of LMMS, there are lots of other features that are deemed more important and that already require lots of labor (all of which is volunteer work). I think most developers, and probably most users, are inclined to the music production side of LMMS and there are lots of features being worked on towards that. Video support is a HUGE task, and it's not that it's never going to happen, just that it's probably not happening in a near future. For that reason @tresf closed the issue, to keep the issue tracking cleaner. But it can be reopened when a volunteer shows up willing to take this task.

**Comment by EaryChow** [comment]
Alright then

**Comment by tresf** [comment]
> How should we make soundtracks for videos without being able to sync the video with the music in the timeline? 

LMMS can barely do this with audio tracks.  In regards to syncing, perhaps a JACK control between LMMS and a video player could sync the playback as a stop-gap, but I'm not a JACK user so perhaps someone with experience could offer steps to help.

**Comment by trebmuh** [comment]
If LMMS could support [JACK-transport](https://jackaudio.org/api/), then we could sync it with any other JACK-transport-able application, including Xjadeo.

**Comment by marcgardent** [comment]
this repo contains the Jack-transport : https://github.com/gi0e5b06/lmms
Demo here : https://www.youtube.com/watch?v=2PYt4hJUA9o
Jack-transport Patch 2hours, not merged  and not finished https://github.com/gi0e5b06/lmms/issues/1
