### ISSUE TITLE
Can't set other BPM values, keeps resetting to 240

### ISSUE THREAD

**Issue by william1835** [LMMS/lmms#2081]
Basically, every time I try to set the tempo, for example, to 140, it holds that value. However when I play it, it sets it back to 240. Can someone explain this for me?
Thanks.
P.S The first image shows the BPM before playing and the second during and after.#
Edit: This is only when playing in the Song-Editor. The Piano-Roll and Bass+Beatline Editor don't change the tempo when playing.
![image](https://cloud.githubusercontent.com/assets/7988916/7992800/ae8102c4-0af9-11e5-9b68-b6cf9162a6ba.png)
![image](https://cloud.githubusercontent.com/assets/7988916/7992840/f2e02b02-0af9-11e5-94fb-619275cdcb15.png)

**Comment by william1835** [comment]
Edit 2: Sorry, another edit. I've realised that there's automation on the BPM, though I don't know how it got set the first place. Maybe you should look into this?

**Comment by tresf** [comment]
Can you try this:

https://github.com/LMMS/lmms/issues/1252

**Comment by william1835** [comment]
Yes, I've realised what has to be done. So this a known error?

**Comment by tresf** [comment]
If you can reproduce it, yes.  If you can't, then it's an unknown-known error. :laughing:

**Comment by cnuptak** [comment]
same shit. but it changes to 100 bpm)

**Comment by Spekular** [comment]
@cnuptak have you tried the suggested fix? (Right click tempo, remove automation)

As tresf said, we already know about the issue, but nobody has steps to reliably reproduce it.

**Comment by cnuptak** [comment]
thx, it helps
