### ISSUE TITLE
Automation set/clear record button

### ISSUE THREAD

**Issue by theguitarplayer** [LMMS/lmms#2083]
Implement record botton onto song editor like this:

![setclear record](https://cloud.githubusercontent.com/assets/6945072/8014521/9ce7aab2-0b9f-11e5-95df-cebfe219d629.png)

**Comment by theguitarplayer** [comment]
Or this is neater:

![setclear record 2](https://cloud.githubusercontent.com/assets/6945072/8025863/82f9e73e-0d32-11e5-91f1-741ea3770e45.png)

**Comment by Wallacoloo** [comment]
Why have you closed this? I thought it was a useful idea, I'm just not
familiar enough with recording in lmms to provide any input.

**Comment by Umcaruje** [comment]
I think this is a totally valid enhancement, we already have a set/clear record for automation in the track menu, and it'd be much more accessible as a button in the track.

**Comment by SecondFlight** [comment]
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.
