### ISSUE TITLE
Pitch Controls / Automation of VST plugins ignored when Exporting

### ISSUE THREAD

**Issue by Moth-Tolias** [LMMS/lmms#2084]
When an export is made, custom pitch values and automation relating to such are ignored.
Widows 64-bit, Version 1.1.3

**Comment by tresf** [comment]
You have to be more specific.  We had this issue with OpulenZ and fixed it in 1.1.3, so this statement may oblybbe true for certain instruments.

**Comment by Moth-Tolias** [comment]
Ah! Apologies, i really should have put that down... It's a VST problem

**Comment by tresf** [comment]
:+1:

**Comment by musikBear** [comment]
This may be related
http://lmms.io/forum/viewtopic.php?f=7&t=26365&p=49533#p49533
He cant export VSTs in correct pitch from win10 -1.1.3 64b

**Comment by DomClark** [comment]
@Moth-Tolias Can you test the latest beta version to see if this issue still persists? Some issues relating to VST automation and pitch have been addressed recently.

**Comment by Moth-Tolias** [comment]
appears to be fixed, thank you.
