### ISSUE TITLE
VST tuning off

### ISSUE THREAD

**Issue by Moth-Tolias** [LMMS/lmms#2085]
I have tested several VSTs. Many seem to have a tuning bug where they are, well...
![pitch a](https://cloud.githubusercontent.com/assets/10255268/8019725/7b25e11c-0c55-11e5-90a5-f86ef491c70d.png)
Triple Oscillator, playing a single sinewave at C (in tune)

![pitch b](https://cloud.githubusercontent.com/assets/10255268/8019726/7b284f60-0c55-11e5-9d23-6393e11bfe2c.png)
Glureeds VST, playing at C (out of tune)

The MTuner vst plug-in shows that the vsts "think" that their tuning is correct. However, I have compared the output of TripleOsc with several commercial samples, as well as Audacity's Tone Generator, and found it to be in tune.

Mtuner also agrees with another tuner VST, Gtune. both report identical values with the same offset.

Windows 64-bit, version 1.1.3. Appears not to happen in 32-bit, though It's been a while since I last checked.

**Comment by Umcaruje** [comment]
Hi, have you tried loading the VST's in some other DAW (Reaper or FL Studio) and checking if they register out of tune there too? If that is the case, then that's not our bug, and it can only be fixed by the plugin developers.

**Comment by Moth-Tolias** [comment]
Downloading the demo of FL studio now, will report later.

**Comment by smokedawg17** [comment]
i dont know where to post this, but why dont you guys look into making everything microtonal.. even the vestige plugins like they do on logic. Ive seen a max plugin for ableton that you can midi detune for microtonal music on all vst's, i think that would be a super feature to bring lmms to the top! dont mind me just popping by (A4=432hz, pythagorean ratios accross 12 notes MAGIC)

**Comment by Umcaruje** [comment]
@Moth-Tolias did you ever test these plugins in some other daw?

**Comment by tresf** [comment]
@smokedawg17 is your request covered by #1472 (last item), per #1387?

**Comment by softrabbit** [comment]
Looks like it's a case of 44100 vs 48000 Hz. 

44100/48000 = 0.91875, plug that in to the calculator at http://www.sengpielaudio.com/calculator-centsratio.htm and you get -146.7, which is a semitone and 47 cents down, fits exactly with the first screenshot.

**Comment by Moth-Tolias** [comment]
@Umcaruje not yet, sorry. I've almost learnt FL to the point where I can test and report back, but a lot of school deadlines have been coming in and I simply haven't had the time to spare

**Comment by softrabbit** [comment]
I have 0 experience with VST on LMMS, but the first spot I'd try is removing the if clause:
https://github.com/LMMS/lmms/blob/master/plugins/vst_base/RemoteVstPlugin.cpp#L578
and just call ```updateSampleRate();``` for all plugins. That check might of course be there for a reason, but I guess it doesn't hurt (much) to try.

**Comment by Moth-Tolias** [comment]
I can now confirm that the affected VSTs running in FL studio return a different pitch to that in LMMS.

**Comment by DomClark** [comment]
@Moth-Tolias Can you test the latest beta version to see if this issue still persists? Some issues relating to VST pitch errors have been addressed recently.

**Comment by Moth-Tolias** [comment]
thanks for letting me know, i'll take a look.

**Comment by Moth-Tolias** [comment]
looks as though this bug at least is fixed, thank you.
