### ISSUE TITLE
VST-Instrument cross-dragging, crashes lmms

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#2086]
1.1.3 win32 xp
It is possible to drag a simple instrument (native) from one project to another. (2 instances open at same time, of cause) If that is attempted with a VST (Synth1), lmms crash and hang.
Release only through taskMng

**Comment by tresf** [comment]
Thanks for the report.  FYI, we dont officially support running more than one instance at the same time, our code will break in other places as well.

**Comment by PhysSong** [comment]
Does #3776 fixes this?

**Comment by musikBear** [comment]
@PhysSong is 3776 included in your build 14 hours ago? I will test this too

**Comment by PhysSong** [comment]
It's already in rc5.

**Comment by musikBear** [comment]
@PhysSong I can cross-drag synth1 forth and back from two opened instances of lmms, and both works, and play correctly in both piano-roll, and song-editor.
I would call this fixed! Good job!
