### ISSUE TITLE
Crash when dragging new sound clip onto AudioFileProcessor

### ISSUE THREAD

**Issue by Coburn37** [LMMS/lmms#2090]
Windows 8.1 Pro 64-bit
Microsoft Surface Pro 3
LMMS 1.1.3

When I create a new AudioFileProcessor, either through the "Instrument Plugins" tab or just dragging a sound file from the "My Samples" tab, and then try to drag a new audio file from the "My Samples" tab onto the AudioFileProcessor instrument gui, it crashes.

To reproduce:
1) Open a new project
2) Create a new AudioFileProcessor instrument
3) Open the GUI for that instrument
4) In the left pane navigate to the "My Samples" tab
5) Take any sound and hold and drag it over the AudioFileProcessoe instrument and let go

**Comment by musikBear** [comment]
but this does only happen sometimes - right?
try your 1..5 but with:
folder 'drums'
1. file bassdrum01.ogg
2. file clap01.ogg
That does not crash anything -right?
So what file swap exactly, will cause a crash **every** time?

**Comment by Coburn37** [comment]
Yup, it still crashes.
It seems to only happen when I drag it over the sample waveform portion. Anywhere else and it doesn't crash.

![image](https://cloud.githubusercontent.com/assets/6759176/8105532/35eb5c06-103a-11e5-9a37-06b8c2af6e05.png)

**Comment by musikBear** [comment]
oki, thats is different for me on win32xp 1.1.3
I can abuse the drag /drop really seriously, (fast, sloppy-drop, repeated same file) and i cant get a crash at all
64x issue only??
Is 'MS-surface' ok for lmms?

**Comment by tresf** [comment]
> Is 'MS-surface' ok for lmms?

Yes, it is just a PC in a small form factor with a very high resolution.

-Tres

**Comment by tresf** [comment]
Edit: It also has touch screen and a stylus which could make a difference.

**Comment by Coburn37** [comment]
I am not using either the touch screen or the stylus for this but yes, it does have those.
The resolution I'm using is at max (2160x1440). I've had problems with Open Broadcast Software where it doesn't work correctly due to DPI scaling on the surface.

**Comment by midi-pascal** [comment]
I tried this - many times - under Linux (Ubuntu 12.04) - and no crash here wherever I drop the sample.

**Comment by zonkmachine** [comment]
> Windows 8.1 Pro 64-bit
> Microsoft Surface Pro 3
> LMMS 1.1.3             <------- Suspect A



> Here's what the error encountered box said if it helps at all?
> 
> ```
> Problem signature:
>   Problem Event Name:   APPCRASH
>   Application Name: lmms.exe
>   Application Version:  1.0.93.0   <------- Suspect B
> ```

@Coburn37 Yes. I suspect you had an earlier beta version 1.0.93 (1.1.0-RC3) that wasn't removed before installing lmms-1.1.3 . I'm closing this.
Please reopen if you still see this bug on a later version, 1.2.0-RC5 (or later).
https://lmms.io/download/#windows
