### ISSUE TITLE
SF2 drag-and-drop behavior

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms#2094]
Has anyone tried dragging a SF2 file from the file browser on master branch?

I'm working with @softrabbit on a potential fix for SF2 on Apple, and this is what shows when I try dragging in an SF2 file:

![screen shot 2015-06-12 at 12 16 33 am](https://cloud.githubusercontent.com/assets/6345473/8123492/75903094-1098-11e5-9f35-59059df47b99.png)

![screen shot 2015-06-12 at 12 18 02 am](https://cloud.githubusercontent.com/assets/6345473/8123494/83a45cb4-1098-11e5-8eec-ff12383f332e.png)

This message isn't entirely accurate though, since the SF2 player works when the instrument is added manually.

**Comment by softrabbit** [comment]
This happens immediately on mousedown, before dragging, so I'd say LMMS tries to preview the file. Right-click and "open in new instrument track" works.

Console output:
```qUncompress: Z_DATA_ERROR: Input data is corrupted
at line 1 column "error occurred while parsing element"```

**Comment by tresf** [comment]
That `qUncompress` seems strikingly familiar to some issues we had after some file browser enhancements.  Tagging @curlymorphic. :)
