### ISSUE TITLE
Can't edit settings?

### ISSUE THREAD

**Issue by Fyuchanick** [LMMS/lmms#2099]
Whenever I go into settings and hit "ok", it gives me an alert saying I must restart LMMS before changes are applied. However, if I quit and reopen LMMS, the changes are not applied, making it impossible for me to change the sound output from "dummy".

**Comment by Wallacoloo** [comment]
What version of lmms are you running, and on what operating system?

**Comment by Fyuchanick** [comment]
I'm running windows, and lmms version 1.1.0

**Comment by Fyuchanick** [comment]
I updated to the latest version and had the same problem.

**Comment by tresf** [comment]
Please run CMD as administrator and paste this command and tell us your results:

```batch
move %USERPROFILE%\.lmmsrc.xml %USERPROFILE%\.lmmsrc.xml.bak
```

**Comment by musikBear** [comment]
@Fyuchanick you should also look at our forum
http://lmms.io/forum/index.php
, and maybe sign up?
Questions like this one really does belong under *Troubleshooting* in forum, not in the dev-bug-tracker :)

**Comment by Umcaruje** [comment]
@Fyuchanick have you tried changing your device settings to SDL? That's our recommended backend for windows.

**Comment by zonkmachine** [comment]
Solved per this forum post:
https://lmms.io/forum/viewtopic.php?f=7&t=3403
