### ISSUE TITLE
Demo projects that are missing samples.

### ISSUE THREAD

**Issue by zonkmachine** [LMMS/lmms#2101]
Some projects miss drum samples:
https://github.com/LMMS/lmms/tree/master/data/projects/demos/Zakarra

Downstream bug:
https://bugs.launchpad.net/ubuntu/+source/lmms/+bug/1386542

Demo projects last changed in commit ce0a56a482819f728fdcfba01f6ba3ceb32e2ff7
miss some (or all) samples. 
@cubician  Do you have the original files so you can complement the projects?

_Edit: Fix links_

**Comment by jack126guy** [comment]
I believe this is because that project uses samples from the [Hydrogen drumkits integration](https://github.com/LMMS/hydrogen-drumkits).

**Comment by zonkmachine** [comment]
Sorry for the late reply!

I think you're right. I wonder if there are more projects than these that have missing dependencies like this.

**Comment by gumbo-cms** [comment]
I've just installed v1.1.3 from dnf in Fedora and I've only got drumsynth for samples,,,, Can I at least get a hold of the built-in samples somewhere so I can install them manually? thx

**Comment by tresf** [comment]
> I've just installed v1.1.3 from dnf in Fedora and I've only got drumsynth for samples,,,, Can I at least get a hold of the built-in samples somewhere so I can install them manually? thx

This is off-topic.  We do have a support channel on Discord that you can seek out troubleshooting help.  https://discord.gg/3sc5su7

**Comment by tresf** [comment]
@gumbo-cms and yes to answer the question for others finding this on Google, if you `git clone https://github.com/lmms/lmms` you can pull them from the `data` folder.  Please direct further questions to our `#support` channel on Discord.  https://discord.gg/3sc5su7

**Comment by gumbo-cms** [comment]
thx a lot tresf, that's just what I was looking for!
