### ISSUE TITLE
Sample Lengths

### ISSUE THREAD

**Issue by Hgroyal** [LMMS/lmms#2117]
I have and issue/question.  I have been trying to use my own samples in lmms.  I upload the samples using the AFP.  However, when I try to play a sample that is for example 7 seconds long, I will only get may 3 or 4 seconds of the sample.  The only way that I can get the entire sample to play is if I choose to play the sample across the notes, but I do not like this option because I cannot control when the sample restarts and ends. I am rather new to lmms so I could totally be missing something. In the end, I would like to be able to insert my samples (of whatever length).  Help!

**Comment by musikBear** [comment]
similar to #1471

**Comment by tresf** [comment]
@musikBear, this is an AFP bug, not a Sample Track bug.  This is a bug, not an enhancement.  The duplicate is here:  #1592, specifically here:  https://github.com/LMMS/lmms/issues/1592#issuecomment-70837313
