### ISSUE TITLE
AudioFileProcessor: Allow sample loading from OS' drag-and-drop

### ISSUE THREAD

**Issue by Wallacoloo** [LMMS/lmms#2120]
Currently, you can load a sample into the AFP by dragging it from one of the file browsers in the left pane and dropping it somewhere over the AFP's UI. I propose that you should be able to do the same thing by dragging an audio file _from any other program_ (specifically the operating system's file browser) and releasing it over the AFP as well.

This shouldn't be too difficult to do, as I believe Qt's drag-and-drop system is designed to integrate into the OS just like this.

**Comment by tresf** [comment]
I'd like to add that this should be extended to work with all file types supported (samples, patches, vst instruments, presets, projects) as the string-pair drag and drop logic already exists for all of them.

**Comment by Reaper10** [comment]
Will you be able to do this with audio clips from a sample track?

**Comment by Wallacoloo** [comment]
@Reaper10 yes, that should be possible. Not sure if sample tracks are
already set up for drag and drop,  but Qt's drag and drop system is very
capable.
On Jul 2, 2015 12:58 PM, "Reaper10" <notifications@github.com> wrote:

Will you be able to do this with audio clips from a sample track?

—
Reply to this email directly or view it on GitHub
<https://github.com/LMMS/lmms/issues/2120#issuecomment-118150487>.

**Comment by tresf** [comment]
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.
