### ISSUE TITLE
Link Piano-Roll editor and Automation editor playback

### ISSUE THREAD

**Issue by kpone33** [LMMS/lmms#2123]
I think it would be nice to be able to have an option to playback an automation track synchronized with the Piano-Roll playback to have a better way to edit for example pitch automation without having to solo the corresponding track in the song editor and use loop markers to have automation applied as expected.

As mentioned, it would be very useful, if you use pitch automation or something else that affects the sound in general like changing the oscilator type of a synth or adjusting oscilator modulation, just to mention a few examples.

**Comment by musikBear** [comment]
copy of #857

**Comment by tresf** [comment]
Consolidated into #3740
