### ISSUE TITLE
can't export as loop with CLI

### ISSUE THREAD

**Issue by Baccanno** [LMMS/lmms#2129]
Options do not precise how to export as loop from the command line. 
And looking at main.cpp it does not seem possible right now.

We have 100+ sounds to export so it would be great to automate this :)

**Comment by michaelgregorius** [comment]
Should be fixed with pull request #2131. Hope it helps you with your conversions. :smiley:

**Comment by Baccanno** [comment]
We did it by hand this time -_-, but it will be much appreciated for the following work :)

Thx

**Comment by tresf** [comment]
Closed via #2131
