### ISSUE TITLE
WANT_VST_NOWINE in CMakeLists.txt

### ISSUE THREAD

**Issue by Israel-D** [LMMS/lmms#2132]
Hi,
@falkTX packages lmms for KXStudio and includes a patch to give the CMakeLists.txt a WANT_VST_NOWINE variable (as well as some debian specific code that uses and sets this).
AFAIK currently this would _probably_ not adversely effect other Linux builds, as they wont set this variable to true... basically

```
(line number 311)
 IF(WANT_VST)
IF(WANT_VST_NOWINE)
    SET(LMMS_SUPPORT_VST TRUE)
    SET(STATUS_VST "OK")
ELSE(WANT_VST_NOWINE)
     FIND_PACKAGE(Wine)
     IF(WINE_FOUND)
         SET(LMMS_SUPPORT_VST TRUE)
### .......

(line number 318)
     ENDIF(WINE_FOUND)
 ENDIF(WANT_VST_NOWINE)
 ENDIF(WANT_VST)
## .........
```

Are there any downsides to doing this?  Would this cause undue hardships, or be a simple fix to make @falkTX (and my) life a bit easier?  This could also help other (non-Debian/Ubuntu) distros implement the same function

**Comment by grejppi** [comment]
This option doesn't even do anything.

**Comment by falkTX** [comment]
This option enables the LMMS-VST without actually building the code.

It's used on 64bit builds where the code for it isn't actually built (since it only works for 32bit afaik),
but we still want to enable the vst option.

The module is installed in a separate 32bit-only package, which when installed on a 64bit system makes lmms able to load 32bit vsts.

**Comment by tresf** [comment]
@falkTX in your opinion, do you recommend we use that option moving forward?  Or is this more of a matter of permanently fixing the CMakeList.txt to reflect exactly what you're describing with a new flag for controlling it?

Ideally we'd like our upstream code to accommodate the packaging requirements.

**Comment by falkTX** [comment]
that option is fine, it's not going to hurt anyone.

the reason that option is needed is because of some weird debian oddities when building packages that use winelib.
As I explained it needs a way to enable wine stuff even if it's not going to be built.

It's not an option for end users, only for packagers.

**Comment by tresf** [comment]
Then we should have no issue merging it in. :+1:  :)

**Comment by tresf** [comment]
@Israel- can you issue a pull request with this addition in it please?

**Comment by Israel-** [comment]
@tresf sorry I have been really busy lately.  I will get to work on this.

**Comment by tresf** [comment]
@Israel-D if this is still desired, please submit a PR with the appropriate change.

**Comment by lukas-w** [comment]
Don't we already have this option? (per 061333bb7cca52b65cddfd4acb3d6cab897ac696 and #2735)

https://github.com/LMMS/lmms/blob/bd8c27249fec77d4ade4bd6ddfeb242284f75b1c/CMakeLists.txt#L68

https://github.com/LMMS/lmms/blob/bd8c27249fec77d4ade4bd6ddfeb242284f75b1c/CMakeLists.txt#L452-L454

**Comment by tresf** [comment]
I don't think @Israel-D did a good job of explaining the patch... Looking at the current code ([CMakeLists.txt#L444](https://github.com/LMMS/lmms/blob/bd8c27249fec77d4ade4bd6ddfeb242284f75b1c/CMakeLists.txt#L444)) we seem to look for Wine regardless of this option.

**Comment by SecondFlight** [comment]
`if this is still desired, please submit a PR with the appropriate change.`

Closing, as it has been a year with no response. no-response bot sure is nice to have around :)
