### ISSUE TITLE
opening a VST preset should not open the VST GUI

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#2143]
tittle says it, but it is unnecessary that all VST GUI is opened, either when the user picks a single VST-preset from 'My-presets' _and_ when a project with VST-presets is opened 
All these GUIs are just a tedious windows-closing-task, that has to be done, because the presets are not meant to be changed! The Lmms-vst-ctlr-page is where the user will automate dials.
I would prefer VST loading, without all GUIs being opened at the same time 

..what says ye ?

**Comment by Spekular** [comment]
Closing and consolidating into #5433
