### ISSUE TITLE
Track name not shown in PianoRoll titlebar

### ISSUE THREAD

**Issue by midi-pascal** [LMMS/lmms#2144]
A useful - IMHO - little plus would be to display the current track name in the Piano Roll titlebar.
This could avoid some mistakes when editing a track with the piano roll - I experienced this already -.
The current track is already highlighted in the song editor but it can be scrolled out of view then one cannot see which track is displayed in the piano roll hence modifying the wrong track.

**Comment by midi-pascal** [comment]
As I dig in the code, this appears to be a bug since the code to do it is in PianoRoll.cpp at line 581:
setWindowTitle( tr( "Piano-Roll - %1" ).arg( m_pattern->name() ) );
but the window title is not displayed :(
I put a breakpoint on it while debugging and this code is effectively executed but with no result.

**Comment by Wallacoloo** [comment]
@midi-pascal (by the way, that's a neat username) editors like the Piano
Roll are all split into two classes - I think one's named "PianoRoll" and
the other is "PianoRollEditor", or something. In terms of UI, one is the
parent and handles all the window menus (the stop/play buttons, etc) and
one is the child, which renders the main content.

I don't know which is which off the top of my head, but make sure you're
setting the window title of the main parent widget and not the child one.

**Comment by midi-pascal** [comment]
@Wallacoloo The setWindowTitle() was already there. I did not change anything (yet :-)

**Comment by midi-pascal** [comment]
This bug is not as trivial as it looks... I dug more and still do not understand what is wrong with the PianoRoll code. This should be tagged as a bug anyway.

**Comment by michaelgregorius** [comment]
Please note that this bug might be related to issue #1267 and might even be a problem with Qt itself (for more details see #1267).

**Comment by Umcaruje** [comment]
> might even be a problem with Qt itself

I don't think that's the case here, since this bug is only present in the master branch. I don't experience it in the `stable-1.1` branch

**Comment by midi-pascal** [comment]
@Umcaruje You are right, the PianoRoll titlebar is Ok in the documentation screenshots and also in stable-1.1.
I dug in PianoRoll.cpp history but found nothing that could explain this bug.
I must admit, I am stalled on this one :-(

**Comment by tresf** [comment]
Shot in the dark, but perhaps related to #2103?

**Comment by midi-pascal** [comment]
@tresf I read #2103 carefully and I don't think it is related. The window geometry problem under X11 is well known - I added a hint about this in #2103 - but this is the first time I see a problem setting a window title unless the object is not part of the windows family, in which case the code does not even compile.
So I stay really clueless on this one :-(

**Comment by michaelgregorius** [comment]
Problem is fixed with pull request #2146. @Wallacoloo gave the right tip. The top level MDI widget is not `PianoRoll` but `PianoRollWindow`.

**Comment by midi-pascal** [comment]
@michaelgregorius Wow! :+1:

**Comment by Wallacoloo** [comment]
Fixed by @michaelgregorius in #2146 with the following caveat:

> It's worth noting that changing the current instrument's name while it's open in the piano roll does not cause the window title to update, however. I believe this was present in the original behavior though.
