### ISSUE TITLE
Master ( as off 1.07.2015) - Not possible to copy note-Blocks in song-editor

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#2147]
win32x 
cant copy note**blocks** NEITHER INSIDE A TRACK OR from one track to another
 
(Notes copied from inside one block can correctly be copied to any other block)

---------

This is more complicated than i thought -I had a crash, and after the crash, i CAN copy whole blocks - not sure whats happened, except i removed the orphan VSTs manually
Has anyone else seen this 'not-block-copy' thing?

**Comment by Wallacoloo** [comment]
Can you clarify what you mean by "noteblock"? Are you attempting to select
multiple notes in the Piano Roll and then copy them? Or are you trying to
copy whole patterns in the song editor? Or something else?

**Comment by Umcaruje** [comment]
@musikBear please offer steps to reproduce, AND STOP USING CAPS LOCK. Nobody likes being yelled at.

**Comment by musikBear** [comment]
No this 'bug' disappeared
I did a complete clean Master test install, so it had not to do with garbage form the old 1.1.3 - I honestly dont know what caused it, and wish i had recorded ..diddent
I have closed / opend, multitude of times -and even reinstalled, but i cant make it happen again
For now i think this is 'invalid', but i sadly knows all to well, that if a weird random behavior has apeared just once, its a ghost in the machine, and eventually it will resurface

@Wallacoloo blocks are https://lmms.io/wiki/images/6/62/Instrument_pattern_Song_Editor1.0.0.png
so it was simply ctrl+drag of blocks that did nothing. the dropped block appeared, but only as a empty black square - and i tested many times. Then crash, cleanup, and ...'solved' 

and SORRY :)

**Comment by musikBear** [comment]
@Umcaruje Just as expected it did resurface, here is a video of the behavior. 
https://youtu.be/4U6EtpvfUcA
and now i know more.
I **saved** the project, (had save message) and then closed lmms.
When i reopened the project, the block that i had tried to copy, was not there.
So it is not the actual copy-event that does not take place, it is in fact a not-registrated   or not-seen block that fails to be recognized, and hence cant be copied either
That is what i know now. The erroneous behavior disappeared after reopen of the failed project.
