### ISSUE TITLE
BB-pattern length in song editor doesn't update

### ISSUE THREAD

**Issue by Spekular** [LMMS/lmms#2148]
Adding or removing bars from a BB-pattern in the BB-editor should change the distance between notches on said pattern in the song editor, but this doesn't take effect until you grab the pattern in the song editor.Here's an ugly demonstration:
![ugly](https://cloud.githubusercontent.com/assets/8918426/8480960/0c56104a-20e1-11e5-9760-f66ed48d22cf.png)

**Comment by Umcaruje** [comment]
Confirmed on the master branch on Ubuntu 15.04 x64 

Here is a gif of the behaviour:
![gifrecord_2015-07-06_234809](https://cloud.githubusercontent.com/assets/6282045/8534127/b9a180da-2439-11e5-855f-0683a36768c7.gif)

**Comment by Wallacoloo** [comment]
It appears to me that [TrackContentWidget::paintEvent](https://github.com/LMMS/lmms/blob/master/src/core/Track.cpp#L1455) is responsible for the relevant portion of rendering that occurs in the song editor here.

This should just be an issue of tying either [TrackView::update](https://github.com/LMMS/lmms/blob/master/src/core/Track.cpp#L2464) or [TrackContentWidget::update](https://github.com/LMMS/lmms/blob/master/src/core/Track.cpp#L1103) to the appropriate signal in the B&B editor.
