### ISSUE TITLE
Add support for acidized samples

### ISSUE THREAD

**Issue by liftarn** [LMMS/lmms#2154]
An “Acidized” file is a standard .WAV file, but it takes advantage of an audio-file feature that allows non-audio data to be embedded into a file’s header. This extra information provides ACID with a loop’s length (in beats and bars), time signature, slice points and the base transposition key.

**Comment by tresf** [comment]
Acid is one of many programs the can recognize wave cue markers, so "acidized" is probably the wrong term to use here.  We've discussed allowing AudioFileProcessor to read these for as an enhancement to the looping functionality, but I'm not sure where that left off.

This enhancement should probably be split into AudioFileProcessor and Sample Track, where Sample Track would care about time signature and AudioFileProcessor would care about the cue points (loop points).

Here's a bit more about it, from a coding perspective.
http://www.juce.com/comment/303101#comment-303101

**Comment by liftarn** [comment]
At http://www.recordingmag.com/resources/resourceDetail/323.html there is a description from a user standpoint. WAV files with markers are most often called Acid or acidized. The article also mentions ReCycle (REX) files and Apple Loops. Those may also be nice to have support for, but they are not as popular as acidized loops.

**Comment by softrabbit** [comment]
Rex files are proprietary and AFAIK they haven't been successfully reverse engineered. I have no idea about Apple Loops, but they should at least be readable as aiff. 

Libsndfile, which LMMS already uses, handles a lot of the info found in acidized wavs. Right now AFP could use loop points and root note, but any beat, meter and tempo info is at the moment mostly useless, until time stretching is first implemented.

Here's what's in one acidized wav, someone with Apple Loops available could try the same trick. (Didn't feel like signing up to get some freebies from the loop merchants)

```
$ sndfile-info WahRoads.wav 

Version : libsndfile-1.0.25

========================================
File : WahRoads.wav
Length : 425022
RIFF : 425014
WAVE
fmt  : 16
  Format        : 0x1 => WAVE_FORMAT_PCM
  Channels      : 2
  Sample Rate   : 44100
  Block Align   : 4
  Bit Width     : 16
  Bytes/sec     : 176400
data : 421248
LIST : 38
  INFO
    ICOP : 1999, Sonic Foundry, Inc.
acid : 24
  Flags     : 0x0002 (Loop,RootNoteValid,StretchOff,RAMBased,??Off)
  Root note : 0x45
  ????      : 0xFFFF8000
  ????      : 0.000000
  Beats     : 4
  Meter     : 4/4
  Tempo     : 100.501366
strc : 3644
End

----------------------------------------
Sample Rate : 44100
Frames      : 105312
Channels    : 2
Format      : 0x00010002
Sections    : 1
Seekable    : TRUE
Duration    : 00:00:02.388
Signal Max  : 32767 (-0.00 dB)
```

**Comment by softrabbit** [comment]
Libsndfile takes care of the format-specific details, so this would go somewhat like:
```
SF_LOOP_INFO sf_loop_info;
bool sf_rr = sf_command( snd_file, SFC_GET_LOOP_INFO, &sf_loop_info, sizeof(SF_LOOP_INFO) );
if(sf_rr) {
    qDebug("Got loop: %d/%d time, mode %d, %d beats, %f bpm, root key %d", 
        sf_loop_info.time_sig_num, 
        sf_loop_info.time_sig_den,
        sf_loop_info.loop_mode,
        sf_loop_info.num_beats,
        sf_loop_info.bpm,
        sf_loop_info.root_key);
}
```

**Comment by Reaper10** [comment]
LMMS would all so need some kind of built in Acid file editor.

**Comment by Reaper10** [comment]
when this is added LMMS should be able  to do this  https://youtu.be/at33phHJOcA?t=4m

**Comment by Reaper10** [comment]
When this is added to the AFP it will be one more step closer to the AFP being a multi sample player ie, one AFP playing more then one sample. Like linux sampler only it uses WAV or AFF.

**Comment by softrabbit** [comment]
> LMMS would all so need some kind of built in Acid file editor.

When the features in the format are supported by LMMS, saving acidized samples should be possible.

> When this is added to the AFP it will be one more step closer to the AFP being a multi sample player ie, one AFP playing more then one sample.

No, it won't. The AFP becomes a multi sample player if someone adds multi sample support to it, regardless of this feature. AFAIK acidized wavs and Apple Loops contain one loop only. There is a `smpl`chunk defined for .wavs that can contain multiple sample loops, but I have no idea if it's widespread enough to be worth looking into: https://sites.google.com/site/musicgapi/technical-documents/wav-file-format#smpl. And it looks like it only defines multiple loops for the same note, which is a bit primitive as far as multi sampling goes.

The `inst `chunk looks like it could be useful as well: https://sites.google.com/site/musicgapi/technical-documents/wav-file-format#inst

And a few more things (notes to myself):
Looks like the acid format isn't as simple as a loop: http://www.sonycreativesoftware.com/consumer_alert_acidized_files

LoopAuditioneer should be useful for creating test cases: http://loopauditioneer.sourceforge.net/

**Comment by Reaper10** [comment]
here is a idea for this option icon 
![audio-wave](https://cloud.githubusercontent.com/assets/8137561/9829439/b10e17ca-58c9-11e5-876e-010828bb94eb.png)

**Comment by Reaper10** [comment]
When the sample track has a audio clip editor like the midi and automation editor it needs #2356 for muting a hole audio clip and or audio slices and #746.

**Comment by tresf** [comment]
@Reaper10:

 * Enthusiasm: :+1: 
 * Unnecessary invaluable bumping and crosslinking: :-1: 

If you want to chat, try our forums.  Meanwhile, learn some C++ and you can start helping rather than flooding us with requests.

**Comment by PhysSong** [comment]
Consolidated into #6745.
