### ISSUE TITLE
Fixing Wine problems during compilation in Debian 8

### ISSUE THREAD

**Issue by ruggiero** [LMMS/lmms#2161]
I couldn't compile the development version with VST support. First I got the following message after running `cmake ..`, and then `make` would fail after some time compiling, when it got to the VST plugins. 

> Carla Patchbay & Rack       : not found, please install the latest carla
> SoundFont2 player           : OK
>  Stk Mallets                 : OK
>  VST-instrument hoster       : not found, please install (lib)wine-dev (or similar) - 64 bit systems additionally need gcc-multilib and g++-multilib
>  VST-effect hoster           : not found, please install (lib)wine-dev (or similar) - 64 bit systems additionally need gcc-multilib and g++-multilib
>  CALF LADSPA plugins         : OK
>  CAPS LADSPA plugins         : OK
>  CMT LADSPA plugins          : OK
>  TAP LADSPA plugins          : OK
>  SWH LADSPA plugins          : OK
>  GIG player                  : OK

The solution was to add /usr/lib/i386-linux-gnu/wine/bin to PATH (`export PATH=$PATH:/usr/lib/i386-linux-gnu/wine/bin`). After removing CMakeCache.txt and running `cmake ..` again, I still got the message above, but I was able to run `make` without issues. The VSTs work normally after compiling this way.

Note that it's necessary to have libwine-dev:i386 installed for this to work.

Should this information be on the INSTALL file, as a note for Debian users?

**Comment by tresf** [comment]
> Should this information be on the INSTALL file, as a note for Debian users?

Our windows build tutorial is our best maintained place for these things.

> The solution was to add /usr/lib/i386-linux-gnu/wine/bin to PATH

Thanks!  I don't see any harm in just adding this to our build script directly, but for now, I've added it to our build instructions per:  [Compiling-lmms-(Windows)#compile](https://github.com/LMMS/lmms/wiki/Compiling-lmms-(Windows)#compile)

@Lukas-W has taken charge of most of our build items.  I'll allow some time for him to chime in with some feedback prior to closing this out.

**Comment by Lukas-W** [comment]
@ruggiero Please pull the latest changes from `master` and check if f770164730349e5da0235c04c058c96cf2ab1b94 fixes the problem.

**Comment by ruggiero** [comment]
@Lukas-W, I could compile the current `master` out of the box this time. But I still got those two warnings after `cmake`.

**Comment by PhysSong** [comment]
@ruggiero Can you still reproduce this on latest `stable-1.2` or `master`?

**Comment by tresf** [comment]
Sounds like #2958, #3708.  Closing.
