### ISSUE TITLE
Master 01.07 Main volume slider. Broken value-display, when scrolled

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#2164]
This
https://lmms.io/wiki/images/f/fa/Master_volume_1.0.0.PNG
controller, will not show changed values if it is mouse-wheel scrolled.
If it is grabbed and then pushed, it does show correct changed values.
(pitch-slider works correct)

**Comment by michaelgregorius** [comment]
Fixed with pull request #2166.

**Comment by Umcaruje** [comment]
This has to be the fastest fix for an issue that I've seen so far :+1:

**Comment by michaelgregorius** [comment]
@Umcaruje It wasn't such a big issue anyway. :)

The tip that the pitch slider works correctly also helped a lot because I could simply check the structure of the pitch slider code and apply it to the volume slider. Thanks @musikBear!
