### ISSUE TITLE
Disabling or changing the Song Editor's Bar Grid

### ISSUE THREAD

**Issue by unfa** [LMMS/lmms#2171]
I'd love to be able to modify the bar grid in Song Editor to my needs. By default it's highlighting every other group of four bars. Sometimes I'd like to turn this off, or cut one or two bars out to break the pattern when my composition requires it. Sometimes I need to compose with one-bar offset which is kind of difficult - turning the bar grid off would make things easier in such cases.

**Comment by tresf** [comment]
I remember another bug report mentioning this but I cannot find it... The somewhat stalled "futuremap" (#908) mentions it as well... and slightly in #874, 

> Time signature reworked: convert current time sig widget to work more as a "grid" setting which doesn't affect pattern lengths but only the song editor snapping. Add a separate time sig property to all patterns, so that each pattern can have their own internal time sig, and different time-sigs can be mixed in the same project. (no time-estimate for this, but possibly before 2.0)

**Comment by musikBear** [comment]
wouldent a user-controlled snap value be a better idea?
Then 'rhythmic'  placing is preserved, but user has a free choice
We can already move anything *without* snap in songeditor (ctrl+drag), but i fear that a disabled grid, just will lead to a shower of Qs in forum

**Comment by Umcaruje** [comment]
I think this could be solved by having a project-specific 'Grid Offset' setting in the Edit menu.

**Comment by zonkmachine** [comment]
> 'Grid Offset' setting in the Edit menu.

Yeah. Either this or in the Song editor tool bar. Settings 'on/off' and 'offset' should be easy to add.

![songeditor](https://cloud.githubusercontent.com/assets/6368949/8606358/60f92240-268b-11e5-8630-b82fbebd144f.png)

**Comment by musikBear** [comment]
Now an addition grid-feature is requested in forum
For 'recording' midi-notes, it should be possible to disable all snap, so the played notes (midi-keyboard ao pc-kb) would be exactly as they are layed, in respect to both timing-position, and length
Guess that could be called 'free.mode'
That is so closely related, that it fit on same ticket.
ref:
http://lmms.io/forum/viewtopic.php?f=3&t=3450#p11030

**Comment by zonkmachine** [comment]
> That is so closely related, that it fit on same ticket.

Sorry. Not even close.

**Comment by Umcaruje** [comment]
>That is so closely related, that it fit on same ticket.

@zonkmachine is right. That forum post has no connection with this request. I think it can be related to #1530 though.

**Comment by simonvanderveldt** [comment]
@unfa is it about what you see/what LMMS shows or about how LMMS works?
To be more precise: Is it purely that the grid as shown doesn't align with something you want to do?
Or Is actually handling (adding, shortening, lengthening) of notes difficult because of quantization?

**Comment by tresf** [comment]
@simonvanderveldt it's purely visual.   The problem is that a song doesn't always align exactly to the n-bars (e.g. 4 bars) visually.  For starters, there may be a half-bar or a 2-bar lead-in which misaligns the bar highlighting for the rest of the track.

**Comment by simonvanderveldt** [comment]
@tresf thanks for the extra explanation. That makes sense.
I guess the ideal fix would be to have the possibility for a different time signature including offset per track like it's mentioned in the futuremap?
And then based on that information render the correct track specific gridlines.

**Comment by tresf** [comment]
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.
