### ISSUE TITLE
Live Pattern Play Mode

### ISSUE THREAD

**Issue by Reaper10** [LMMS/lmms#2179]
Live Pattern Play Mode is for turning a B&B Track into a live Pattern that a user can use a key the New Midi keyboard track  #2162  to act as the play/ stop  buttons just for that pattern. Why? This is for those who want to use the B&B as a loop track without needing to have anything in the B&B track in the Song Editor, ie the B&B track is an empty track in the Song Editor but the user has tracks in the B&B when it's opened up.  A user can mix and mash patterns just by pushing a key on the  midi keyboard track. To play the pattern  push the key on the midi keyboard track
 & hold it down until you want it to stop the track.

How to set up:
1. make a midi keyboard track
2. turn on midi out via the Live Pattern Play Mode option found in the B&B gear menu of track in Song Editor 

![live patteren play icon button](https://cloud.githubusercontent.com/assets/8137561/8625288/752f9b90-2703-11e5-9552-95399a74ff8f.png)

3. set key trigger via 
<img width="175" alt="live patteren play" src="https://cloud.githubusercontent.com/assets/8137561/8625048/d2b2c2b2-2701-11e5-9e63-54e14326d3be.png">
4. use the All-in-one routing window #1986 to send midi to theNew Midi keyboard track  #2162  
your done

To disconnect click again the Live Pattern Play Mode option found in the B&B gear menu of track in Song Editor. 

![live patteren play icon button](https://cloud.githubusercontent.com/assets/8137561/8625288/752f9b90-2703-11e5-9552-95399a74ff8f.png)

This will add more power to Live Mode Mute Switch (LMMS) #770 
This can act like LIVE's clip launch mode.
This mode would be great for Multiple Instruments on 1 Channel (Launchpad Support) #1792 in the B&B editor.

**Comment by tresf** [comment]
We've beat up the "live mode" over and over on this tracker.  It won't happen any time soon, but when it does, we'll be sure to make Beat and Bassline segments triggerable.

-Tres
