### ISSUE TITLE
Double-clicking on instrument's Fx Channel LED gives focus to mixer channel, but only if mixer is already open

### ISSUE THREAD

**Issue by Wallacoloo** [LMMS/lmms#2186]
I apologize for the long title. Anyway, when you open an instrument, there's an LED control that routes an instrument to a mixer slot. If the mixer is open, even in the background, double-clicking on this LED will bring the mixer to the front and automatically have it focus on whatever channel the instrument is connected to (see image below).

![lmms-fx-link](https://cloud.githubusercontent.com/assets/1210751/8665125/cec30650-29cf-11e5-9166-83b0b65362dc.png)

However, if the mixer is not open, this doesn't happen. From a usability perspective, I would expect double-clicking the LED to bring focus to the associated mixer slot regardless of if the mixer is already open (i.e. it should open the mixer if it isn't already).

Can someone confirm the desired behavior for double-clicking the LED?

**Comment by tresf** [comment]
> Can someone confirm the desired behavior for double-clicking the LED?

:+1:

**Comment by midi-pascal** [comment]
:+1:  For the usability enhancement and :+1: for the idea

**Comment by musikBear** [comment]
I would like to do the vis-a-vi as well:
double-clicking on the mixer-channel-LED would then open the instrument preset, and bring it on top -it would now be the focused-preset.
(a different ticket? or related here)

**Comment by tresf** [comment]
> (a different ticket? or related here)

Different.  But a question for you.... what if there's more than one instrument routed?

-Tres

**Comment by Wallacoloo** [comment]
@musikBear That was actually discussed in another thread - dunno which one
though. Conclusion was similar to what @tresf pointed out: some mixer
channels are fed by multiple instruments, some by none - any implementation
of the requested behavior would be wrought with inconsistencies.

**Comment by Wallacoloo** [comment]
Issued a fix: #2187 - only needed to add one missing line of code.

**Comment by musikBear** [comment]
> what if there's more than one instrument routed?
true
