### ISSUE TITLE
Marked semitones should be marked across all octaves.

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#2193]
I think it would be better if this marked/unmarked all *identical semitones* over *all* octaves 
(or 'over all octaves' could be added as new option)

(thought its been up before, but search did not reveal anything..?)

**Comment by Umcaruje** [comment]
@musikBear please offer some screenshots, mockups and further clarify this issue.

**Comment by musikBear** [comment]
current behavior
![marksemicurrent](https://cloud.githubusercontent.com/assets/6662066/8775196/31380b44-2ee6-11e5-8b50-8bc528ab1f5c.JPG)

*Suggested behavior*
![marksemicurrentsugg](https://cloud.githubusercontent.com/assets/6662066/8775205/3dcff060-2ee6-11e5-88ca-cf342cae264d.JPG)

from experience i find that there are two primary reason for semi-tone-marking:
* I want to mark the tone, because i want to *insert* notes on that tone  
* I want to *exclude* that note from already existing markings (f.i. a marked scale)

If i want to insert, then i may like to insert on the note on more than one octave, if so, its neat that all identical semitones in all octaves are marked, if i dont, its quite easy to see what octave im working in, because they have numbers, so additional marked notes wont be a real problem.

If i want to exclude a note from already marked notes, it is logical to exclude that note from all octaves, and with current behavior, i will have to that manually, Suggested will do that for me.

wheater or not the current single method still is needed, must be discussed, but a method to achieve picture  *Suggested behavior*, would enhance the workflow

**Comment by unfa** [comment]
I had this idea too. It'd make the option much more helpful.

**Comment by waxspin** [comment]
@musikBear @unfa I propose making it an additional option in the popup menu, so that the user has the option.  I am implementing this now, but it's easy enough to not include the option in the menu if anyone thinks we shouldn't.

**Comment by musikBear** [comment]
@waxspin that is a very fine solution. :+1:

**Comment by waxspin** [comment]
@musikBear I have completed this, and uploaded a validation build [here](https://github.com/waxspin/lmms/releases/tag/p2377) for you to test.  Thanks in advance for the help!

**Comment by musikBear** [comment]
@waxspin Very nice! It works very good. :+1: 

Btw and Not related, but I think the differences in shading between marked notes, and the marked 'current-note' is too small:
![forlilleforskel](https://cloud.githubusercontent.com/assets/6662066/10098332/ddbfc978-6380-11e5-84ea-7557e7579afb.jpg)

The shading of the note in focus, 'current-note' is almost indistinct-able, from the notes that shows the current selected scale -Perhaps that need to be looked at in a different ticket.

**Comment by waxspin** [comment]
Awesome, glad it works well!  I think the same about the highlighting, but perhaps we should open a new ticket for that.

**Comment by tresf** [comment]
Closed via #2377.
