### ISSUE TITLE
(Vestige) VSTi won't load.

### ISSUE THREAD

**Issue by qwerytiop** [LMMS/lmms#2196]
Ubuntu 15.04 using lmms-vst-full

lmms freezes after I try to load a VST instrument. I have tried this with multiple instruments, and they give the same result.

There isn't anything coming out from terminal, it just runs forever :/.

I tried purging and reinstalling wine, reverting to older versions of wine, purging and reinstalling lmms and lmms-vst-full, but they don't seem to fix the issue.

If one kills the RemoteVSTPlugin.exe.so process from the terminal, lmms comes up with an error notice telling me to try to run the VST with other programs.

**Comment by Umcaruje** [comment]
@qwerytiop can you tell us what is the VST in question?

**Comment by qwerytiop** [comment]
DSK ChoirZ and DSK AcoustiKGruitarZ

The second one was in the Tested VSTs page

**Comment by qwerytiop** [comment]
I'm not sure exactly what I did but now I'm also these getting error messages during startup:

Notice: could not set realtime priority.
VST sync support disabled in your configuration
"Cannot load library /usr/lib/lmms/libcarlabase.so: (libcarla_standalone2.so: cannot open shared object file: No such file or directory)" 
"Cannot load library /usr/lib/lmms/libcarlapatchbay.so: (libcarlabase.so: cannot open shared object file: No such file or directory)" 
"Cannot load library /usr/lib/lmms/libcarlarack.so: (libcarlabase.so: cannot open shared object file: No such file or directory)" 
"Cannot load library /usr/lib/lmms/RemoteVstPlugin.exe.so: (/usr/lib/lmms/RemoteVstPlugin.exe.so: wrong ELF class: ELFCLASS32)"

The VSTis still don't load in a reasonable amount of time.

**Comment by Umcaruje** [comment]
Are you using 64bit or 32bit DLL's? IIRC 64bit VST's don't work on linux.

**Comment by qwerytiop** [comment]
They're 32 bit DLL's (x86 == 32-bit right XD)

**Comment by qwerytiop** [comment]
oh, also the new error messages stopped appearing again after I restarted my computer, and the VSTs still don't work, so I don't think that's related.

**Comment by qwerytiop** [comment]
The program is also crashing randomly when I'm using Zynaddsubfx

Notice: could not set realtime priority.
VST sync support disabled in your configuration
QtXmlWrapper::loadXMLfile(): empty data 
ASSERT: "asize <= aalloc" in file /usr/include/qt4/QtCore/qvector.h, line 474
Aborted (core dumped)

The Zynaddsubfx window doesn't close after lmms crashes.

**Comment by qwerytiop** [comment]
I need to kill the process to close it (close button doesn't work), but all the knobs and stuff work fine in the still open window.

**Comment by Umcaruje** [comment]
@qwerytiop Could you perhaps build LMMS from source and make a Debug build, and offer backtraces? You have guides here:
https://github.com/LMMS/lmms/wiki/Debugging-LMMS
https://github.com/LMMS/lmms/wiki/Compiling-lmms

That'd be really helpful. Building is pretty straightforward, but if you need help, just leave a comment.

**Comment by qwerytiop** [comment]
okay

**Comment by qwerytiop** [comment]
I got this output from gdb

(gdb) run
Starting program: /home/qwerytiop/lmms-debug/lmms/target/bin/lmms 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Notice: could not set realtime priority.
VST sync support disabled in your configuration
RemotePluginClient::shmget: No such file or directory
^C[New Thread 0x7fff7b7fe700 (LWP 26319)]
[New Thread 0x7fff7bfff700 (LWP 26317)]
[New Thread 0x7fff90ef0700 (LWP 26316)]
[New Thread 0x7fff91d0d700 (LWP 26315)]
[New Thread 0x7fff92a92700 (LWP 26313)]
[New Thread 0x7fff93293700 (LWP 26312)]
[New Thread 0x7fff93fff700 (LWP 26310)]
[New Thread 0x7fff988d7700 (LWP 26309)]
[New Thread 0x7fffc449f700 (LWP 26308)]
[New Thread 0x7fffc4ca0700 (LWP 26307)]
[New Thread 0x7fffe0e0d700 (LWP 26306)]
[New Thread 0x7fffe1e0f700 (LWP 26302)]
[New Thread 0x7fffe3124700 (LWP 26301)]

Program received signal SIGINT, Interrupt.
0x00007ffff7bcb23d in recvmsg () at ../sysdeps/unix/syscall-template.S:81
81	../sysdeps/unix/syscall-template.S: No such file or directory.
(gdb) fixme:console:CONSOLE_DefaultHandler Terminating process 2f on event 0

(gdb) thread apply all backtrace

Thread 14 (Thread 0x7fffe3124700 (LWP 26301)):
#0  0x00007ffff43b68dd in poll () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007ffff3b9eebc in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff3b9f242 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fffeac30af6 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#4  0x00007ffff3bc5955 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff7bc26aa in start_thread (arg=0x7fffe3124700) at pthread_create.c:333
#6  0x00007ffff43c1eed in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 13 (Thread 0x7fffe1e0f700 (LWP 26302)):
#0  0x00007ffff43b68dd in poll () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007ffff3b9eebc in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff3b9efcc in g_main_context_iteration ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff3b9f009 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff3bc5955 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff7bc26aa in start_thread (arg=0x7fffe1e0f700) at pthread_create.c:333
#6  0x00007ffff43c1eed in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 12 (Thread 0x7fffe0e0d700 (LWP 26306)):
#0  pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff6805c56 in QWaitCondition::wait(QMutex*, unsigned long) ()
   from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#2  0x00000000004a2ce3 in MixerWorkerThread::run (this=0xb848e0)
    at /home/qwerytiop/lmms-debug/lmms/src/core/MixerWorkerThread.cpp:168
#3  0x00007ffff68056ff in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#4  0x00007ffff7bc26aa in start_thread (arg=0x7fffe0e0d700) at pthread_create.c:333
#5  0x00007ffff43c1eed in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 11 (Thread 0x7fffc4ca0700 (LWP 26307)):
#0  pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff6805c56 in QWaitCondition::wait(QMutex*, unsigned long) ()
   from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#2  0x00000000004a2ce3 in MixerWorkerThread::run (this=0xb8d020)
    at /home/qwerytiop/lmms-debug/lmms/src/core/MixerWorkerThread.cpp:168
---Type <return> to continue, or q <return> to quit---
#3  0x00007ffff68056ff in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#4  0x00007ffff7bc26aa in start_thread (arg=0x7fffc4ca0700) at pthread_create.c:333
#5  0x00007ffff43c1eed in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 10 (Thread 0x7fffc449f700 (LWP 26308)):
#0  pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff6805c56 in QWaitCondition::wait(QMutex*, unsigned long) ()
   from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#2  0x00000000004a2ce3 in MixerWorkerThread::run (this=0xb4ff10)
    at /home/qwerytiop/lmms-debug/lmms/src/core/MixerWorkerThread.cpp:168
#3  0x00007ffff68056ff in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#4  0x00007ffff7bc26aa in start_thread (arg=0x7fffc449f700) at pthread_create.c:333
#5  0x00007ffff43c1eed in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 9 (Thread 0x7fff988d7700 (LWP 26309)):
#0  0x00007ffff43b68dd in poll () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007ffff5db5601 in ?? () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
#2  0x00007ffff5da6b41 in pa_mainloop_poll ()
   from /usr/lib/x86_64-linux-gnu/libpulse.so.0
#3  0x00007ffff5da71de in pa_mainloop_iterate ()
   from /usr/lib/x86_64-linux-gnu/libpulse.so.0
#4  0x00007ffff5da7290 in pa_mainloop_run () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
#5  0x00007ffff5db5596 in ?? () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
#6  0x00007ffff15696c8 in ?? ()
   from /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-6.0.so
#7  0x00007ffff7bc26aa in start_thread (arg=0x7fff988d7700) at pthread_create.c:333
#8  0x00007ffff43c1eed in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 8 (Thread 0x7fff93fff700 (LWP 26310)):
#0  0x00007ffff43b68dd in poll () at ../sysdeps/unix/syscall-template.S:81
#1  0x00000000004f59f1 in poll (__timeout=250, __nfds=2, __fds=0x7fff8c0013b0)
    at /usr/include/x86_64-linux-gnu/bits/poll2.h:46
#2  MidiAlsaSeq::run (this=0xd9fd30)
    at /home/qwerytiop/lmms-debug/lmms/src/core/midi/MidiAlsaSeq.cpp:476
#3  0x00007ffff68056ff in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#4  0x00007ffff7bc26aa in start_thread (arg=0x7fff93fff700) at pthread_create.c:333
#5  0x00007ffff43c1eed in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
---Type <return> to continue, or q <return> to quit---

Thread 7 (Thread 0x7fff93293700 (LWP 26312)):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007ffff6804062 in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#2  0x00007ffff680042d in QMutex::lock() () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#3  0x0000000000491d0e in lock (this=0xb847a0)
    at /home/qwerytiop/lmms-debug/lmms/include/Mixer.h:308
#4  Mixer::renderNextBuffer (this=0xb847a0)
    at /home/qwerytiop/lmms-debug/lmms/src/core/Mixer.cpp:343
#5  0x00000000004925c4 in Mixer::fifoWriter::run (this=0x13fcb40)
    at /home/qwerytiop/lmms-debug/lmms/src/core/Mixer.cpp:945
#6  0x00007ffff68056ff in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#7  0x00007ffff7bc26aa in start_thread (arg=0x7fff93293700) at pthread_create.c:333
#8  0x00007ffff43c1eed in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 6 (Thread 0x7fff92a92700 (LWP 26313)):
#0  pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff6805c56 in QWaitCondition::wait(QMutex*, unsigned long) ()
   from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#2  0x00007ffff6801a7b in QSemaphore::acquire(int) ()
   from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#3  0x00000000004c29be in read (this=0xb3a230)
    at /home/qwerytiop/lmms-debug/lmms/include/fifo_buffer.h:62
#4  nextBuffer (this=<optimized out>)
    at /home/qwerytiop/lmms-debug/lmms/include/Mixer.h:367
#5  AudioDevice::getNextBuffer (this=this@entry=0xcb1c60, _ab=_ab@entry=0x7fff88002da0)
    at /home/qwerytiop/lmms-debug/lmms/src/core/audio/AudioDevice.cpp:83
#6  0x00000000004be38a in AudioAlsa::run (this=0xcb1c60)
    at /home/qwerytiop/lmms-debug/lmms/src/core/audio/AudioAlsa.cpp:267
#7  0x00007ffff68056ff in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#8  0x00007ffff7bc26aa in start_thread (arg=0x7fff92a92700) at pthread_create.c:333
#9  0x00007ffff43c1eed in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 5 (Thread 0x7fff91d0d700 (LWP 26315)):
#0  pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff6805c56 in QWaitCondition::wait(QMutex*, unsigned long) ()
---Type <return> to continue, or q <return> to quit---
   from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#2  0x00007ffff759b91d in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#3  0x00007ffff68056ff in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#4  0x00007ffff7bc26aa in start_thread (arg=0x7fff91d0d700) at pthread_create.c:333
#5  0x00007ffff43c1eed in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 4 (Thread 0x7fff90ef0700 (LWP 26316)):
#0  0x00007ffff43b68dd in poll () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007ffff3b9eebc in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff3b9efcc in g_main_context_iteration ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff693f85e in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#4  0x00007ffff690ed21 in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#5  0x00007ffff690f085 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#6  0x00007ffff6802e89 in QThread::exec() ()
   from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#7  0x00007ffff68ef493 in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#8  0x00007ffff68056ff in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#9  0x00007ffff7bc26aa in start_thread (arg=0x7fff90ef0700) at pthread_create.c:333
#10 0x00007ffff43c1eed in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 3 (Thread 0x7fff7bfff700 (LWP 26317)):
#0  0x00007ffff43b8743 in select () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007ffff68ebc0f in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#2  0x00007ffff68056ff in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#3  0x00007ffff7bc26aa in start_thread (arg=0x7fff7bfff700) at pthread_create.c:333
#4  0x00007ffff43c1eed in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 2 (Thread 0x7fff7b7fe700 (LWP 26319)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 ()
    at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
#1  0x00007ffff68041da in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#2  0x00007ffff6804a9d in QThread::msleep(unsigned long) ()
   from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#3  0x000000000049c6bb in ProcessWatcher::run (this=0x1f5f700)
---Type <return> to continue, or q <return> to quit---
    at /home/qwerytiop/lmms-debug/lmms/src/core/RemotePlugin.cpp:57
#4  0x00007ffff68056ff in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#5  0x00007ffff7bc26aa in start_thread (arg=0x7fff7b7fe700) at pthread_create.c:333
#6  0x00007ffff43c1eed in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 1 (Thread 0x7ffff7fad7c0 (LWP 26300)):
#0  0x00007ffff7bcb23d in recvmsg () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007fffefd909b7 in ?? () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#2  0x00007fffefd91198 in ?? () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#3  0x00007ffff24cedb8 in ?? () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#4  0x00007ffff24ceefe in ?? () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#5  0x00007ffff24cf1dd in _XEventsQueued () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#6  0x00007ffff24c1207 in XPending () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#7  0x00007fffea083cfe in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
#8  0x00007ffff3b9e3fd in g_main_context_prepare ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#9  0x00007ffff3b9ede8 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#10 0x00007ffff3b9efcc in g_main_context_iteration ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#11 0x00007ffff693f85e in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#12 0x00007ffff7131c66 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#13 0x00007ffff691401d in QCoreApplication::processEvents(QFlags<QEventLoop::ProcessEventsFlag>, int) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#14 0x000000000049d9c9 in RemotePluginBase::waitForMessage (this=this@entry=0x1f5f6d0, 
    _wm=..., _busy_waiting=_busy_waiting@entry=true)
    at /home/qwerytiop/lmms-debug/lmms/include/RemotePlugin.h:979
#15 0x00007fffc59fb2b5 in waitForInitDone (_busyWaiting=true, this=<optimized out>)
    at /home/qwerytiop/lmms-debug/lmms/include/RemotePlugin.h:719
#16 VstPlugin::tryLoad (this=this@entry=0x1f5f6a0, remoteVstPluginExecutable=...)
    at /home/qwerytiop/lmms-debug/lmms/plugins/vst_base/VstPlugin.cpp:180
#17 0x00007fffc59fb70f in VstPlugin::VstPlugin (this=0x1f5f6a0, _plugin=...)
    at /home/qwerytiop/lmms-debug/lmms/plugins/vst_base/VstPlugin.cpp:100
#18 0x00007fffc4edb7ee in vestigeInstrument::loadFile (this=0x1b74a80, _file=...)
    at /home/qwerytiop/lmms-debug/lmms/plugins/vestige/vestige.cpp:259
#19 0x00007fffc4eda1bf in VestigeInstrumentView::openPlugin (this=0x1bab340)
    at /home/qwerytiop/lmms-debug/lmms/plugins/vestige/vestige.cpp:657
#20 0x00007ffff69251ec in QMetaObject::activate(QObject*, QMetaObject const*, int, void**)---Type <return> to continue, or q <return> to quit---
 () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#21 0x00007ffff7722332 in QAbstractButton::clicked(bool) ()
   from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#22 0x000000000054f717 in automatableButton::mouseReleaseEvent (this=<optimized out>, 
    _me=<optimized out>)
    at /home/qwerytiop/lmms-debug/lmms/src/gui/widgets/automatable_button.cpp:154
#23 0x000000000053e279 in pixmapButton::mouseReleaseEvent (this=0x1bea7f0, 
    _me=<optimized out>)
    at /home/qwerytiop/lmms-debug/lmms/src/gui/widgets/pixmap_button.cpp:94
#24 0x00007ffff70dcdc8 in QWidget::event(QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#25 0x00007ffff70899bc in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#26 0x00007ffff709063f in QApplication::notify(QObject*, QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#27 0x00007ffff69101cd in QCoreApplication::notifyInternal(QObject*, QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#28 0x00007ffff708fc9f in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) ()
   from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#29 0x00007ffff71099a2 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#30 0x00007ffff710924c in QApplication::x11ProcessEvent(_XEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#31 0x00007ffff7131ba2 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#32 0x00007ffff3b9ec3d in g_main_context_dispatch ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#33 0x00007ffff3b9ef20 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#34 0x00007ffff3b9efcc in g_main_context_iteration ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#35 0x00007ffff693f85e in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#36 0x00007ffff7131c66 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#37 0x00007ffff690ed21 in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#38 0x00007ffff690f085 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#39 0x00007ffff6914b09 in QCoreApplication::exec() ()
   from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
---Type <return> to continue, or q <return> to quit---
#40 0x000000000047fd62 in main (argc=1, argv=0x7fffffffc800)
    at /home/qwerytiop/lmms-debug/lmms/src/core/main.cpp:529
(gdb) q
A debugging session is active.

	Inferior 1 [process 26300] will be killed.

Quit anyway? (y or n) y

**Comment by qwerytiop** [comment]
Running it through valgrind, piping output to a file.

here: http://pastebin.com/bCb8aGNj

in comparison I get this: "ERROR SUMMARY: 51 errors from 35 contexts (suppressed: 0 from 0)"
in Terminal (at the end) before I try to run Vestige.

**Comment by qwerytiop** [comment]
Also, from the debug version, everything crashes and I go back to the ubuntu login screen when I try to open the Zynaddsubfx GUI

http://pastebin.com/y73uymMg

(works fine on regular version)

**Comment by qwerytiop** [comment]
The terminal crashes, so I can't get past that.

**Comment by Umcaruje** [comment]
@qwerytiop yeah the crashing when opening zyn gui is not a LMMS bug, but an Xorg bug. There's nothing we can do about it. 

Thanks for the backtraces. I'm marking this as a bug.

**Comment by Israel-** [comment]
@qwerytiop what Ubuntu package are you using?
you mentioned lmms-vst-full
This bug might be related to the packaging as well, or similar issue

**Comment by qwerytiop** [comment]
Agh, I got a new computer since then. (Old computer's screen and everything basically just broke.) Sorry. LMMS works completely fine on my new computer though (in windows).

**Comment by tresf** [comment]
> LMMS works completely fine on my new computer though (in windows).

I'm going to close this out for two reasons... 

 1. You're no long on the computer experiencing the issue
 1. We're tracking known VST crash issues in some other areas (#1875, #2390, #2304)
