### ISSUE TITLE
tri function (chord/arpeggio)

### ISSUE THREAD

**Issue by DeRobyJ** [LMMS/lmms#2200]
What's the origin of the "tri" function?

It plays 4 notes per octave, each of them is 3 semitones after the one before. So it works in a similar way to a tritone (half of an octave), but with half the space between notes (so it becomes quarter of an octave)

I've searched for "semitritone" (and "semitritono" in latin), and I found some latin books from the middle age which just name it but don't explain it well (or at least, it would be quite difficult to understand, not because of latin, but because of symbols!)
The only English book I found must be downloaded from some site...

Now: was it actually intended to be a tritone? It would make sense, since the tritone is interesting for illusions like the tritone paradox.
Should we change it to actual tritone? The "semitritone" would he easy to reproduce by playing two tritones, 3 semitones distant.
Or should we keep the current "tri", look for the correct name (which I really think is semitritone), and then add tritone?

~DeRobyJ

**Comment by musikBear** [comment]
https://en.wikipedia.org/wiki/Trichord
isent that the one?

**Comment by DeRobyJ** [comment]
Nope, these are groups of 3 notes that would come one after another in a major or minor scale.

Here we have 4 notes of a tone and a half.

A trichord is like C-D-E, or A-B-C
This is like
C-D#-F#-A
If you put two trichord together, you get an hexachord.
If you put two "tri" together, you get a tri and the same tri at the above octave.

I think "tri" stands for "three semitones each".
It's more similar to a Tritone
https://en.wikipedia.org/wiki/Tritone
But with 3 semitones instead of 3 tones between each note, thus dividing each octave in 4 parts, instead of two.

**Comment by softrabbit** [comment]
https://en.m.wikipedia.org/wiki/Diminished_seventh_chord

**Comment by DeRobyJ** [comment]
Yep, there it is.
So the correct name is diminished seventh chord...

Let's find a name like the others.

I see that "m7b5" is the closest, as the only difference is that the 7 must be diminished.

So we may call it "m7b5b7"?
And we should probably place it right after m7b5.

Anyway, we don't have a tritone then!

**Comment by softrabbit** [comment]
dim7 is what I'd call it. And I think simply moving it in the list of chords and scales could affect the playback of existing projects.

**Comment by tresf** [comment]
If that's the case (compat problem) we can shim a new compat line in easy enough, we just need to remember.

**Comment by DeRobyJ** [comment]
I think dim7 can be confused with other things... but since it's more similar to the complete name, we may take it.

It's a minor 7th with diminished 5th and 7th...

Anyway, I think that list lacks of titles for each chord category, so we may leave it in its place and then create an enhancement issue to add "category titles".

**Comment by tresf** [comment]
> we may leave it in its place and then create an enhancement issue to add "category titles".

Please do. :+1: Closing as this was a question which has since been resolved.
