### ISSUE TITLE
Empty Template

### ISSUE THREAD

**Issue by mamins1376** [LMMS/lmms#2202]
Hello. i think it is a little boring to remove and clean up the default track, automation, triple osc and baseline at start, it is better to have a "Clean" or "Empty" template like FL Studio. can it be included in the default templates that coming with project?

**Comment by zonkmachine** [comment]
A - Yes, Good idea!

I'll look into it.

**Comment by midi-pascal** [comment]
This one is so easy to solve: 
1- open an empty project
2- remove the tracks you do not want
3- save it as "default.mpt" in your projects directory
That's it!
That's what templates are designed for. :smile:

**Comment by musikBear** [comment]
Silly -i read that different, i thought he meant creating a template from a project 8| -but ofcause he wrote 'default'. 
A method to remove all notes and blocks in all editors, could however be useful 
Eg preserve all instruments and effects with settings, but get rid of all song-editor blocks -Optional choice to also clean BB-events, but that would quite often *not* be wanted!
At least when i make a project into a template, i like to preserve the percussion 
-The same could be said for effects..
So in the end, a simple choice to 'templatenize' a project, would properly not be a one-button-click event

**Comment by midi-pascal** [comment]
I understand what you mean and agree on that, but @mamins1376 is asking for 'a "Clean" or "Empty" template' - his own words -.
Hence the hint I gave here.

**Comment by mamins1376** [comment]
it is useful a lot for working faster. but i have an idea: create a "platform" like VBA in Office apps, a script system to automate some processes, e.g. a special configuration for triple osc, or making some standard tricks like sidechaining or developing a 'Riff machine' using a small script.
I know that wants lots of time and programming but can be a nice feature to create a special ability to making musics.
-- 
Sent from K-9 Mail.

**Comment by tresf** [comment]
> e.g. a special configuration for triple osc, or making some standard tricks like sidechaining or developing a 'Riff machine' using a small script.

This is similar to the concept of an FX preset (#1680), but a bit more specific.  For now, a screen reader may be a better stop-gap.  You may also find a quick way to perform these using XML manipulators against our project file format.

**Comment by tresf** [comment]
@mamins1376 either way, this is probably suited for its own bug report, rather than in the template bug report.

**Comment by mamins1376** [comment]
oh, sorry! I will open a new issue about that.

On ۲۹ ژوئیهٔ ۲۰۱۵ ۲۳:۵۴:۲۴ (GMT+04:30), Tres Finocchiaro <notifications@github.com> wrote:
>@mamins1376 either way, this is probably suited for its own bug report,
>rather than in the template bug report.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/LMMS/lmms/issues/2202#issuecomment-126067191

-- 
Sent from K-9 Mail.

**Comment by musikBear** [comment]
>  but mamins1376 is asking for 'a "Clean" or "Empty" template' - his own words -.
Hence the hint I gave here.

Ya, i know :p Thats where the first word *Silly* comes from 8]
