### ISSUE TITLE
SF2 pitch knob screwed by export

### ISSUE THREAD

**Issue by softrabbit** [LMMS/lmms#2204]
https://lmms.io/forum/viewtopic.php?f=7&t=3471

Confirmed on master:
- Add Triple oscillator and SF2 player, dial the same pitch bend on both (keep range at 1) and compare sound.
- Put down a few notes and export to file.
- Listen to resulting file, pitches don't match.
- Listen to the project after rendering and the pitch bends won't match until the SF2 pitch range is changed to something else and back.

Initialization problem?

**Comment by tresf** [comment]
Sounds similar to #1286 :)

**Comment by Moth-Tolias** [comment]
sounds exactly like the problem I described in issue #2084 .
...I'd like to mention here that this, the linked issue, and #2085  are effectively stopping me from producing with lmms...

**Comment by michaelgregorius** [comment]
Some more results here. To reproduce follow these steps (using master):

1. Start LMMS.
2. Add an Sf2 Player.
3. Load a SoundFont into the player that you have just added.
4. Add two notes which are a half tone apart for the Sf2 Player, e.g one bar of A4 followed by one bar of G#4.
5. Add a pitch automation for the player. e.g. using the available automation lane. The automation should stay at 0 for the A4 and then increase to 100 for the G#4.
6. Play back the two notes in LMMS. Both notes should sound the same now, i.e. play an A4.
7. Render to a file.
8. Listen to the rendered file. The notes that are played are A4 and A#4 now!
9. Play back in LMMS again. The notes sound like A4 and A#4 here as well.
10. Set the automation for the G#4 to 50.
11. Play back in LMMS. Now both notes are at A4 again.
12. Render to file again.
13. The file now also contains two A4 notes.

So it seems like before the rendering step a value of 100 means to use the complete pitch range of 1 semitone but during and after rendering a value of 50 indicates to use the complete pitch range.

The problem also manifests in the other direction, i.e. when using an A4 followed by an A#4 and then setting the automation to -100 for the A#4. After rendering the value has to be changed to -50 to correct the automation and to make both notes play A4 again.

I assume that a value of 100 should always indicate to use the full range and that 50 is the incorrect value?

**Comment by M374LX** [comment]
More details found.

It looks like a `emit sampleRateChanged();` statement inside a `Mixer`method is enough to cause the pitch problem, which means that the cause might be in one of the slots collected to the `Mixer::sampleRateChanged()` signal.

In the case of exporting a project, this happens because `ProjectRenderer` calls `Mixer::setAudioDevice()`, which in turn emits the signal.
