### ISSUE TITLE
LADSPA plugins not working on Slackware

### ISSUE THREAD

**Issue by lleroy** [LMMS/lmms#2206]
I installed lmms and it seems like the ladspa plugins are not working
properly.

I nailed it down to the init function not being called when the shared
library is loaded

[`plugins/LadspaEffect/caps/interface.cc#L72`](https://github.com/LMMS/lmms/blob/master/plugins/LadspaEffect/caps/interface.cc#L72)
```cpp
__attribute__ ((constructor))
void caps_so_init()
{
...
}
```

I think it's caused by the `-nostartfiles` in the [`CMakeLists.txt#L19`](https://github.com/LMMS/lmms/blob/master/plugins/LadspaEffect/caps/CMakeLists.txt#L19)
which according to the document below should not be used when compiling
shared libraries:
http://tldp.org/HOWTO/Program-Library-HOWTO/miscellaneous.html
http://stackoverflow.com/questions/4760567/how-to-run-constructor-even-if-nostdlib-option-is-defined

Ps: lmms-1.1.3+ (from git), gcc-5.2.0, qt4.7, Slackware-13.37

**Comment by tresf** [comment]
Thanks.  I changed the title to reflect Slackware since we don't have confirmation of this on other platforms (Is gcc-5.2 default on Slackware?  Can someone else on GCC5 reproduce?).  I also added some GitHub markdown to help formatting.

I assume you built from source?  Can you confirm modifying the `-nostartfiles` fixes this issue for you?

**Comment by lleroy** [comment]
no, it's not default: I installed the freshly released gcc-5.2 from source, since the gcc-4.5.2 from slackware-13.37 is too old to compile some of the dependencies (like Carla)
yes, removing the "-nostartfiles" fixed the problem

**Comment by tresf** [comment]
Ok, I'll take a swing at that w/ gcc 4.6 and see if it works.

**Comment by tresf** [comment]
Seems to work just fine.  I'll send over the PR.  Thanks!

![image](https://cloud.githubusercontent.com/assets/6345473/8877094/a2482554-31f1-11e5-8ed3-67c4c1aa6fdd.png)
