### ISSUE TITLE
demo songs dont fully load in song editor

### ISSUE THREAD

**Issue by eagles051387** [LMMS/lmms#221]
I was just listening to skessi's random project number and for some reason the song in its entierty. the rest of the song only becomes visible after you scroll to the right

**Comment by badosu** [comment]
@unfa @eagles051387 @Sti2nd 

Is it possible to reproduce this error today? I could not...

**Comment by eagles051387** [comment]
will need to pull any changes and recompile on mac but will have to be
later on today to confirm as I am currently at work.

On Tue, Jan 13, 2015 at 12:29 PM, Amadeus Folego <notifications@github.com>
wrote:

> @unfa <https://github.com/unfa> @eagles051387
> <https://github.com/eagles051387> @Sti2nd <https://github.com/Sti2nd>
>
> Is it possible to reproduce this error today? I could not...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LMMS/lmms/issues/221#issuecomment-69731162>.
>



-- 
Jonathan Aquilina

**Comment by tresf** [comment]
Once again Jonathan filed two bugs against the same issue.  He can reopen this if it is valid.  The description and his followup post are completely separate bugs so even he can't get this one straight.  It's not our job to decipher.

-Tres

**Comment by tresf** [comment]
@badosu thanks for finding this one.  Greatly appreciated. :+1:

**Comment by eagles051387** [comment]
@tres this could have been one i copied over from source forge which most
likely was the case.

On Tue, Jan 13, 2015 at 2:13 PM, Tres Finocchiaro <notifications@github.com>
wrote:

> @badosu <https://github.com/badosu> thanks for finding this one. Greatly
> appreciated. [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LMMS/lmms/issues/221#issuecomment-69741914>.
>



-- 
Jonathan Aquilina
