### ISSUE TITLE
When exporting a song with carla-jack, sample rates are not set correctly

### ISSUE THREAD

**Issue by ycollet** [LMMS/lmms#2212]
I have a jack configuration at 48000 Hz.
When I  export a track, the default sample rate is set to 44100.
When I export the track, the rendering is not correct. Some instruments are higher than the others, which certainly means that somewhere (carla-rack maybe) the sample rate for export is not set correctly.

The problem occurs on lmms-1.1.3 compiled from source on fedora 21 64 bits with carla master from git repo.

**Comment by ycollet** [comment]
after several tests, the difference is related to exporting using command line wrt exporting using the export dialog. When I use the export dialog, the song has the correct pitch, but with the command line, the pitch is higher (using command line, I specified the sample rate using the -s parameter).

I tested combination of sample rates set which jack (44100 and 48000) and the problem is always the same.

**Comment by SecondFlight** [comment]
Closing in favor of #4606, simply because it's newer and not as buried.
