### ISSUE TITLE
volume control on individual B&B tracks

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#2218]
If you prefer to split your percussion in individual BB-lines, the possibility of having better control on the song-editor BB-track offers some great opportunities.
Here in this mockup 
![extendedbbcontrols](https://cloud.githubusercontent.com/assets/6662066/8907791/9b862e80-3478-11e5-8e3a-d72e65bd8633.png)

I have added the current track-controls also on each of the BB-tracks.
That would allow me to set individual volume and stereo-position on each of the hat-variations. This is not possible now, because any volume or pan setting in BB-editor, is global for all BB-lines, this also mean that a different way to achieve the same feature, is to have individual values on different BB-lines, that would be less intuitive, but infact also give more adjustment opportunities.  

Cant remember i saw this already, and i dont know if the architecture allows it (?)

**Comment by Umcaruje** [comment]
I'm not sure how this can be implemented. What do the knobs control? The relative track volume? Or relative note volume?

In either case, what will happen if all my tracks are maxed out on 200% volume and/or note volume, and I turn that knob up by 25%. Will the volume become 225% somehow?

**Comment by Spekular** [comment]
225% sounds great! Everyone knows that if you're not redlining you're not
headlining. To be more serious, maybe the knob could max out at 100%. I
agree that it should be relative as well, similar to an fx channel I guess.
I'm more concerned about how panning would work if ot were relative. Does a
note panned 30% left become 15% left when the bb track is panned 50% right,
or 65% (?) right? I think adding together the pans would work best.

**Comment by musikBear** [comment]
>  Will the volume become 225% somehow?
> I agree that it should be relative as well, similar to an fx channel I guess.

Yes that would work well
Panning is perhaps over ambitious, but maybe it could be considered when the 2.0 architecture reach design phase, i a couple of years :) - It would be nice to be able to do it..

**Comment by tresf** [comment]
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.
