### ISSUE TITLE
Certain MIDIs Crash LMMS

### ISSUE THREAD

**Issue by seltzernoob** [LMMS/lmms#2220]
I have had this problem ever since i started using LMMS. Whenever i [try to] import certain MIDIs (such as "smetbri2.mid" from vgmusic.com), the screen showing me how much percent of the MIDI has been imported will stop and give me the "Not Responding" salute. Most MIDIs will import fine, but some won't. It's very annoying and frustrating when a song only has 1 MIDI available, and i can't use it because it crashes the program.

I would love this to be fixed.

**Comment by Umcaruje** [comment]
@seltzernoob please note your OS and LMMS version. There have been recent fixes in midi importing on master, so there is a big chance your problem was fixed.

**Comment by seltzernoob** [comment]
Windows 7 Home Edition
LMMS 1.1.3

**Comment by Umcaruje** [comment]
I'll make you some fresh builds of master for you to test. 64 bit or 32?

**Comment by seltzernoob** [comment]
64-bit, thank you.

**Comment by softrabbit** [comment]
That file works here, imports in ~5 seconds. (master, Linux x86_64, Qt 5.4.1, GCC 4.9.2)

Creating the automations used to take very long on import, but wouldn't crash per se. Eventually the import should finish in 1.1.3 as well (no telling how long it will take), the changes to the main logic were pretty minimal IIRC.

**Comment by seltzernoob** [comment]
Alright, i'll leave it sit for a while and see what happens.

**Comment by Umcaruje** [comment]
@seltzernoob here you go: https://drive.google.com/open?id=0B49dcRGtm8vJRkVXMEtWRl9TaEk

Note that this is a development version of LMMS, so its not recommended for daily use. 

Please use it to test the importing of the MIDI file in question.

**Comment by seltzernoob** [comment]
It works, Umcaruje. Thank you so much!

**Comment by Umcaruje** [comment]
:+1: 

Closing this as fixed.
