### ISSUE TITLE
I Can't load my last project

### ISSUE THREAD

**Issue by deenbee** [LMMS/lmms#2224]
I Can't load my last project, the load sequencer is ok but press play buttom do not work any sound, if load a empty project the sound and play work ok

**Comment by musikBear** [comment]
Belongs here:
http://lmms.io/forum/viewforum.php?f=7
Please create an account, and a ticket.
It will help if you also post your

* lmms vers
* hardware specification (ram & soundcard is the most imortant)
* lmms sound device chosen
* if any -screenshots of error
* if relevant, demo mmp
* if any used; names and best download links of the failing vst's

**Comment by deenbee** [comment]
Core i3 4130
4G ram
Asrock B85 pro4
Sound Card: M-Audio Audiophile 24/96
Windows 8.1 x64
Lmms 1.1.3 x86

I try another external usb sound card today work fine
But need more support to professional audiophile 24/96 soundcard

**Comment by tresf** [comment]
Closing, as this is a standard support request.  Please feel free to continue commenting here, but this will appear as `closed` from our tracker.
