### ISSUE TITLE
LMMS New Default UI proposal

### ISSUE THREAD

**Issue by IvanMaldonado** [LMMS/lmms#2225]
Alright, everyone here seems to be working on bugs and other features and I don't know if anyone is doing something for the gui. The gui is alright, it's fine and easy to use but the default one could look more modern if someone invests some time on it.

Those people are the community on the share platform. I've invested some time grabbing some of the best things I could from diverse themes and I added some stuff myself, as in the CSS code, as in the .png files.

![about](https://cloud.githubusercontent.com/assets/12549082/8994166/541cd8e2-36cf-11e5-8b8f-cf2990142022.png)

Here's how it looks:

http://www.deviantart.com/art/LMMS-New-Default-UI-Request-549915999

I may add some other stuff with time, so we can add this as the default theme in the next release.

There are some other Gui's ideas that are just awesome, but as far as I know, they need a lot of time on the code so they could be released, in the meantime, why don't we enjoy a new suit?

**Comment by brianmillar9** [comment]
I talked with the team over email about the GUI before and we discussed ways to improve it. I did some development myself on improving it (didn't submit any pull requests as it was not mature enough). I'm learning QT at the moment and would like to contribute to LMMS so I'd be more than happy to help with an effort to improve the UI in any way I can.

**Comment by tresf** [comment]
:+1:

**Comment by unfa** [comment]
I like some parts of this (the knobs, the plugin panes) I like the overall flat theme that is simplistic and very readable.

I don't like the mixer strips look, especially the faders and meters. I think we could go with Ardour style a bit here - drop the actual fader "handle" graphic and replace it with something symbolic, and more precise, like a horizontal line for example, also the mechanic should change a bit, so you can grab and drag anywhere on the fader/meter area, and the handle is there just for visual reference.

I tried making a quick design but it looks like it's not so easy as I thought. My design was awful and not readable as I wanted it to be.

**Comment by tresf** [comment]
@IvanMaldonado, "Default GUI" is a bit of wishful thinking.  This is a nice addition to our themes for sure, however, to become the next **default theme** would be a carefully planned replacement of artwork and we'd prefer that is done in stages as was done with our 1.0.0 theme.  This is normally done in the form of a proposal and several Pull Requests.  Furthermore, time spent on themes is probably better spent on collaboration with issue like #880 or #1839 (I believe we discussed this on IRC).  I hope you don't mind, I'm closing this out as we already have the ability to host themes on our [LSP](https://lmms.io/lsp).  Please feel free to continue discussion here as needed.
