### ISSUE TITLE
DSP Plugins support

### ISSUE THREAD

**Issue by deenbee** [LMMS/lmms#2231]
Like to add support for DSP winamp  plugins (please developers help) there is a another way to support great mastering audio processing tool such "Stereo Tool" a dsp plugin the sounds is great more natural more ambiance here is a best comparison with another big plugin as Ozone.

Watch the video in HD from my channel and listen the diference with dsp plugin "Stereo Tool" is better than another VST

https://www.youtube.com/watch?v=koZo0gEVAx8

**Comment by tresf** [comment]
Please rewrite your request as to not sound like a self-promotion/advertisement or it will be closed.

**Comment by unfa** [comment]
Honestly I'd better want LV2 support be done, and I guess the DSP winamp plugins are rather "consumer" tools so not much use for music production I guess (haven't tried them) also, is Winamp DSP even an open standard?

Also, I prefer to do mastering in Ardour, which seems much more suited for this kind of work than LMMS. I'd kill myself trying to master an album with LMMS, even though I released  3 LPs entirely composed in LMMS, the vocals and mastering was done in Ardour. LMMS is great for sequencing music but not for mastering recordings. LMMS'd need a solid metering, LV2 plug-in support or at least full LADSPA support with displaying feedback info from the plug-ins like compressors and limiters and ability to play an audio track from any point, not just from the beginning. Not to mention a multi-region export, naaah LMMS ain't for mastering, let's keep it that way.

So if the mastering 'plugin is the only reason to implement support for a plug-in standard, I guess the coders have better things to use their precious time for...

**Comment by Umcaruje** [comment]
Well, OP hasn't responded in a while and I fail to see how LMMS would benefit from these plugins, so I'm gonna close this.

@deenbee if you refine this issue and explain why this is a good idea, please reopen.
