### ISSUE TITLE
add to the app stores

### ISSUE THREAD

**Issue by Reaper10** [LMMS/lmms#2242]
This is not a bug, some day it would be cool to find LMMS in the Windows app store and or the apple app store.

**Comment by tresf** [comment]
Closing as won't-fix.  We won't be in any proprietary app stores that prohibit GPL software.

Furthermore what you are describing isn't free as the software must be signed with a trusted certificate, which starts around $100 annually.

A better goal is to get in the Linux app stores and keep our version up to date.

Installing on Windows or Mac is too easy to put the time and money required for this.
