### ISSUE TITLE
Position of Time

### ISSUE THREAD

**Issue by tkotobu1048** [LMMS/lmms#2244]
Hello. It's my opinion.  I'm waiting for your advices and opinions. 

![lmms_time2](https://cloud.githubusercontent.com/assets/13713003/9153231/b42c7c30-3e84-11e5-8e5f-0abaf89d9f35.jpg)

**Comment by BaraMGB** [comment]
What do you think is the benefit from this?

**Comment by tkotobu1048** [comment]
I think the benefits are readability and design.  :D

**Comment by michaelgregorius** [comment]
I think the whole toolbar is in dire need for a facelift. But I think most of that is already covered in #1911 anyway.

**Comment by tkotobu1048** [comment]
Oh,the UI is very nice and will resolve this problem. But,it seems to take time to implement.   :(

**Comment by michaelgregorius** [comment]
Yes, implementing #1911 will be quite some journey. :)

**Comment by Umcaruje** [comment]
This has some similarities to #387 too.

**Comment by tkotobu1048** [comment]
Wps! I couldn't  find it. The CPU meter is too small. :(
