### ISSUE TITLE
CLI export tracks option

### ISSUE THREAD

**Issue by rcorre** [LMMS/lmms#2254]
In the GUI, we have the options `Export` (which creates a single ogg/wav file) and `Export Tracks` (which creates an ogg/wav for each track).

On the CLI, we only seem to have the regular `Export` option (via the `--render` flag).
It would be nice to have a `--render-tracks` CLI option or something similar.

**Comment by tresf** [comment]
Related #2131

**Comment by rcorre** [comment]
working on this over at https://github.com/rcorre/lmms/tree/render_tracks_cli

**Comment by tresf** [comment]
:+1:
