### ISSUE TITLE
Cannot get rid of B&B editor in default template

### ISSUE THREAD

**Issue by midi-pascal** [LMMS/lmms#2256]
As I would like an <i>minimalistic</i> template on startup I removed all the default tracks and closed all the windows from Lmms except the song editor and the FX Mixer, then saved this setup as default.mpt.
Alas when opening Lmms, all is ok except the B&B editor window always showing up.
I do not want it by default and found no way to get rid of it yet.
I think this is a bug since the default template should show only what I need and nothing more.
Is this really a bug or am I too demanding on the template features?
All opinions are welcome :smile:

**Comment by tresf** [comment]
Yeah, it sounds like a bug.  A template is a template and our editors position and visibility AFAIK is stored in the `mmp(z)`.

**Comment by midi-pascal** [comment]
And there is no reference to the B&B editor in the default.mpt so this looks like it is instantiated by default whatever the template contents.
I'll have a look at this one.
