### ISSUE TITLE
Fix inconsistency: change "--loop-mode" command-line option to "--loopmode"

### ISSUE THREAD

**Issue by M374LX** [LMMS/lmms#2258]
If one looks at the command-line options, no one except `--loop-mode` has a hyphen in the middle: `--samplerate`, `--bitrate`, `--oversampling`, `--allowroot`.

Thus, for consistency reasons, I suggest changing it to `--loopmode`.

There is another detail: the output of `--help` lists `--output-format` as an option, but it is actually `--format`.

**Comment by Wallacoloo** [comment]
I'm pretty neutral as to the hyphen vs non-hyphen discrepancy, so I'll just see what others have to say.

Another thing is that the help for the bitrate option says:
```
-b, --bitrate <bitrate>		specify output bitrate in kHz
				            default: 160.
```

The dimensions there are incorrect. bitrate is bits/[time], whereas Hz is just 1/[time]. My guess is that the intention was for the unit to be kbps (and I'm thinking this only applies to ogg export).

**Comment by M374LX** [comment]
Another possibility is shortening it further to `--loop`, as in #2131.

**Comment by tresf** [comment]
Thanks.  Changed to `--loop` per 2nd suggestion.  Also addressed other typos via https://github.com/LMMS/lmms/commit/de40aa81ce2f84b7d058b59d89c3355bb4f9a4bb.
