### ISSUE TITLE
blurred / obscured values on time-bar

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#2259]
These are quite difficult to read. I dont believe this has been an issue before? Have the tickmaks been changed?
![grimmetal](https://cloud.githubusercontent.com/assets/6662066/9250170/32da5d42-41cb-11e5-81ae-2ed2a5a9b950.png)

**Comment by michaelgregorius** [comment]
This should be fixed as part of pull request #2222. On my system it looked even worse because only the bottom of the numbers was shown:
![timeline-bottom](https://cloud.githubusercontent.com/assets/9293269/9257630/dd6ebdc2-41f6-11e5-9a78-f8abcc387a08.png)

**Comment by unfa** [comment]
Maybe the vertical lines indicating bar boundaries should be drawn in bigger intervals when the session is zoomed out?

![bars](https://cloud.githubusercontent.com/assets/491704/9291413/712be6de-43be-11e5-89fc-594907a96556.png)
![bars1](https://cloud.githubusercontent.com/assets/491704/9291417/8b3459e4-43be-11e5-97b5-9209a9b36b79.png)

**Comment by musikBear** [comment]
@unfa yes, that *could* be a way, but then i feel that mouse-over should show precise pos. -But
Then we have a cpu eater, and that would be a catastrophe -so mouse-over is b a d
But from a moles 'view'point -the values should be more contrasting in respect to the background. It will be interesting to see what 2222 fix

**Comment by unfa** [comment]
Maybe a subtle black rectangle behind the number text would add extra contrast and increate readability?

**Comment by LYF610400210** [comment]
Adding shadow to the text may increase readability.

**Comment by zonkmachine** [comment]
![timebar](https://cloud.githubusercontent.com/assets/6368949/17080689/876363ea-5138-11e6-9edf-bae038596504.png)

This looks much better now.

**Comment by Umcaruje** [comment]
True. This issue was fixed. Closing.
