### ISSUE TITLE
Rendering from command-line does not check if file exists

### ISSUE THREAD

**Issue by M374LX** [LMMS/lmms#2262]
When trying to render a nonexistent file from the command-line (using the `--render` option), it does not display an error message and stop. Instead, it tries to render the "otherworldly" file, although it never goes past 0%.

**Comment by michaelgregorius** [comment]
Fixed with pull request #2266.

**Comment by zonkmachine** [comment]
I think the consensus is to use qDebug for messaging.
Thus you would substitute the iostream stuff for:
```#include <QDebug>```
and 
```qDebug() << "The file" << file_to_load << "does not exist!";```
