### ISSUE TITLE
Compiling using Homebrew on OSX Lion

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms#2263]
Via  #2271, I'm working on switching our Mac build tutorial over to Homebrew to match Travis but I'm receiving this error.  Any insight appreciated.

```
In file included from /usr/local/Cellar/qt/4.8.7/include/QtCore/qvector.h:48:
/usr/local/Cellar/qt/4.8.7/include/QtCore/qlist.h:55:10: fatal error:
      'initializer_list' file not found
#include <initializer_list>
         ^
1 error generated.
make[2]: *** [src/CMakeFiles/lmmsobjs.dir/core/AutomatableModel.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/lmmsobjs.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by Wallacoloo** [comment]
@tresf that's a c++11 header. You can try compiling with -std=c++11. But
that's weird, because I would not expect qt to depend on c++11 features.

**Comment by tresf** [comment]
> You can try compiling with -std=c++11

I tried a few switches to CMake last night to no avail.  Do you have a recommended approach for setting this flag?

**Comment by Wallacoloo** [comment]
I believe you can: `cmake ../ -DCMAKE_CXX_FLAGS=-std=c++11`

**Comment by tresf** [comment]
Thanks @Wallacoloo.  No luck with `-DCMAKE_CXX_FLAGS=-std=c++11`.

FYI - I'm on an old platform (OSX Lion) although this is the same platform I use to build our MacPorts installers on.

**Comment by tresf** [comment]
Ok, I think I got it... via [this article](http://stackoverflow.com/a/29874483/3196753)

```bash
cmake .. -DCMAKE_CXX_FLAGS="-std=C++11 -std=libc++"
```

I assume this could be added around here [`CMakeLists.txt#L439`](https://github.com/LMMS/lmms/blob/master/CMakeLists.txt#L439)

Now I have a new error:

```
/Users/tres/lmms/plugins/LadspaEffect/calf/src/modules_eq.cpp:341:16: error:
      explicit instantiation of 'calf_plugins::equalizerNband_audio_module' must
      occur in namespace 'calf_plugins'
template class equalizerNband_audio_module<equalizer8band_metadata, true>;
               ^
/Users/tres/lmms/plugins/LadspaEffect/calf/src/calf/modules_eq.h:37:7: note:
      explicit instantiation refers here
class equalizerNband_audio_module: public audio_module<BaseClass>,...
      ^
/Users/tres/lmms/plugins/LadspaEffect/calf/src/modules_eq.cpp:342:16: error:
      explicit instantiation of 'calf_plugins::equalizerNband_audio_module' must
      occur in namespace 'calf_plugins'
template class equalizerNband_audio_module<equalizer12band_metadata, true>;
               ^
/Users/tres/lmms/plugins/LadspaEffect/calf/src/calf/modules_eq.h:37:7: note:
      explicit instantiation refers here
class equalizerNband_audio_module: public audio_module<BaseClass>,...
      ^
8 warnings and 3 errors generated.
make[2]: *** [plugins/LadspaEffect/calf/CMakeFiles/calf.dir/src/modules_eq.cpp.o] Error 1
make[1]: *** [plugins/LadspaEffect/calf/CMakeFiles/calf.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by Wallacoloo** [comment]
Maybe check if the upstream version of calf is immune to this error?

**Comment by tresf** [comment]
I threw the namespace in front of those and it fixed it... Yes, we certainly are suffering some upstream issues,  however that is a separate task altogether and not one I feel comfortable doing.

Here's the next compilation issue I'm running into: #2044

@Wallacoloo since you were able to locate the cause of #2044, can you commit the patch upstream so that we can squash two bugs and then we'll open a new task to merge all upstream code?

-Tres

**Comment by Wallacoloo** [comment]
@tresf #2044 happened precisely *because* our calf was outdated. It was fixed upstream over a year ago: https://github.com/LMMS/lmms/issues/2044#issuecomment-103499179

**Comment by tresf** [comment]
Sorry, stumbling over words... I meant can you apply the patch **mid-**stream as a stop-gap?

**Comment by tresf** [comment]
I was going to do it myself based on the diff that was linked in that comment, but sourceforge won't load it.

**Comment by Wallacoloo** [comment]
@tresf they moved to github. Diff is [here](https://github.com/calf-studio-gear/calf/commit/aaca6447de6ed07bb39f376095bb246cc8f3580a)

I'll let you do it :P

**Comment by tresf** [comment]
Thanks.  Done via https://github.com/LMMS/lmms/commit/5375bda6ac9a155173f007f4c8cd0276270acca1

Proceeding... :smile:

**Comment by tresf** [comment]
Next error... 

```
[ 94%] Linking CXX shared module ../../libmalletsstk.so
ld: warning: directory not found for option '-L/opt/local/lib'
Undefined symbols for architecture x86_64:
  "stk::Stk::setRawwavePath(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)", referenced from:
      malletsSynth::malletsSynth(double, double, double, double, double, double, double, int, unsigned char, unsigned int) in mallets.cpp.o
      malletsSynth::malletsSynth(double, double, int, double, double, double, double, double, unsigned char, unsigned int) in mallets.cpp.o
      malletsSynth::malletsSynth(double, double, double, double, double, int, double, double, unsigned char, unsigned int) in mallets.cpp.o
```

Full contents:


https://gist.githubusercontent.com/tresf/b4dca9abdc1e8415bf71/raw/92a6a9a9f2a2afed609cf1ff0585ab79431553f6/gistfile1.txt

**Comment by tresf** [comment]
Ok, i've managed to get past the above error by removing the stdlib command from the stk build instructions per: 

Before:

```cmake
SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fexceptions")
```

After
```cmake
SET(CMAKE_CXX_FLAGS "-fexceptions")
```

I think this is the wrong approach, but what I'm reading online is that this is a symptom that the library we're linking against was build with the wrong libc++.  I'm not very strong in this area, so if someone has some better advice, please let me know.

In the mean time, I'm inclined to put these patches in for the apple build so that we can work towards fixing our `INSTALL` target to work with both MacPorts and Homebrew (it is currently hard-coded to distribute with MacPorts libraries).  And also, I'm sick of applying this patch #1633 each time I create a DMG... :)

**Comment by Wallacoloo** [comment]
Hey @tresf,

This does seem like a bad idea. Maybe you can just look for the specific 
flag that needs to be removed & remove it? Something like (not valid CMAKE):
`SET(CMAKE_CXX_FLAGS REPLACE("${CMAKE_CXX_FLAGS} -fexceptions", 
"-stdlib", "")` if the flag you wanted to remove was called "-stdlib"

**Comment by tresf** [comment]
@Wallacoloo thanks, advice taken.

I think I have a PR ready now via [#2271/files](https://github.com/LMMS/lmms/pull/2271/files)

I had to add a folder `cmake/postinstall` due to some order of operations ugliness with `cmake` coming before `src` for the `CONFIGURE` step, but it broke order of operations for the `INSTALL` step, so I had to put `cmake/postinstall` lower in the `ADD_SUBDIRECTORY` listing.

As always, feedback welcome, although Travis is pissed at me for some reason.

**Comment by Lukas-W** [comment]
@tresf 
If it's the `-std=c++0x` that fixed your first compilation problem, better add that here: [src/CMakeLists.txt#L68](https://github.com/LMMS/lmms/blob/master/src/CMakeLists.txt#L68), and remove the `-DCMAKE_CXX_FLAGS="-std=C++11 -std=libc++"` option. Adding `-std=c++11` to all targets (including plugins), as you did, is bad and most likely the cause of your newer problems.

**Comment by tresf** [comment]
@Lukas-W thanks... trying that now via https://github.com/tresf/lmms/commit/295d4ee6173240a7e730440ce06e645368b1bc04

**Comment by tresf** [comment]
Ok, I think this is ready to be merged.  I'll allow some time for comments.

If everything is ok, next will be switching to node's appdmg script for creating the DMG installer.

**Comment by tresf** [comment]
DMG logic added via https://github.com/tresf/lmms/commit/76ca1c1017ac6e81f211614fa9b44b77292ec57c
