### ISSUE TITLE
Just a thought of renaming the app... just a thought...

### ISSUE THREAD

**Issue by mamarilmanson** [LMMS/lmms#2264]
The L in lmms stands for linux but it doesn't just work on linux anymore... why not M.M.O.S.S.

maybe like Multimedia Open Source Software? or Music Making Open Source Software?  :)

**Comment by M374LX** [comment]
Previously, as currently LMMS does not stand for anything.

**Comment by tresf** [comment]
@mamarilmanson thanks for the suggestions.  We aren't actively looking to rename the software, so I'm closing this out as won-fix, but please feel free to continue the discussion here if needed.
