### ISSUE TITLE
bad playback bug

### ISSUE THREAD

**Issue by Reaper10** [LMMS/lmms#2268]
I've been having bad sound playback in lmms fyi buffer size: frames 768 latency 17.4 ms. My desktop pc is windows 10 32 bit os, my laptop is windows 8.1 64 bit os, and they both up to date, and they both have this bug. I don't know how to fix it. Fyi the sample track was only part  of LMMS that had this bug when my desktop was running on an up to date windows 7 32 bit os. I don't have an hardware audio interface fyi.

samples of the bug
https://drive.google.com/open?id=0B0Ar66xX6aiROTcwaXA3Zm9MRUE
what's in here :
1. TripleOscillator Instrument playback test 
2. Sample used in the Sample Track
3. Sample Track playback test
4. LMMS project output file
5. LMMS project playback test

Thanks So Much

**Comment by musikBear** [comment]
This is a support request
Please use the **forum** 
http://lmms.io/forum/viewforum.php?f=7
and open a thread *there*
Other users that do *not* look in bugtracker may benefit from a help-request topic *there* -Not here!
I will look at it, but i will answer you *in forum*

**Comment by tresf** [comment]
What he said.

**Comment by Reaper10** [comment]
https://lmms.io/forum/viewtopic.php?f=4&t=3532

**Comment by Reaper10** [comment]
I hope can find away to fix this

**Comment by tresf** [comment]
We've asked this before.  Stop bumping your own posts.
