### ISSUE TITLE
Creation of the user default template is not intuitive

### ISSUE THREAD

**Issue by michaelgregorius** [LMMS/lmms#2272]
The creation of the user default template `default.mpt` is currently done in `MainWindow::createNewProject`. I don't think that this is a good place. For example imagine the following scenario:
* A new user checks out LMMS for the first time.
* He notices that there are some demo songs and decides to listen to some of them.
* Now he wants to create something by himself and clicks "New Project".
* From now on he will always be greeted by the layout of the last song he had loaded and has to find out about templates to revert it back. Also it was not obvious to him that "New Project" will change his default settings.

The cleanest solution might be to remove the automatic code in `MainWindow::createNewProject` and to only save templates when the user asks LMMS to do so. I think the template handling in [REAPER](http://reaper.fm) might serve as a good inspiration. In REAPER you can store different templates and select in the preferences which template is loaded when the application starts. The templates are also listed in a sub menu in the files menu so that you can quickly load a template.

**Comment by michaelgregorius** [comment]
Fix in pull request #2272 which removes the non-intuitive saving when a new project is created.

The pull request also fixes some other problems with templates that I have encountered. For example the user templates were not shown in the menu of the tool button that can be used to create new projects from templates. Now they are shown. I have also added a new menu entry "New from template" to the file menu which shows the same menu as the tool button. I think having the option in the file menu as well makes templates more discoverable by the user.

**Comment by unfa** [comment]
Blender has an option to save current project as a starting point for the program.

**Comment by michaelgregorius** [comment]
The current version of the pull request's branch offers a new menu entry "Save as default template". It saves the template as `default.mpt` into the user template directory. So there is no need to be `root` or to know where the file has to be put.

Once the default template (or any other user template) is written it becomes available in the list of templates provided by the new menu entry "New from template". It is also available in the corresponding tool button which was fixed to now also show the user templates.

I guess it cannot get simpler than that. :)

**Comment by michaelgregorius** [comment]
@tresf has requested some screenshots of the changes in the PR. Here they are.

Menu (Two new entries: "New from template" and "Save as default template"):
![2272-menu](https://cloud.githubusercontent.com/assets/9293269/9315124/9d5d96f6-452d-11e5-9ff5-ac3666f9336f.png)

Fixed tool button (Now also shows the user templates, e.g. "default"):
![2272-toolbutton](https://cloud.githubusercontent.com/assets/9293269/9315137/b26a4ca6-452d-11e5-93f2-8abf664f5b5b.png)
