### ISSUE TITLE
adding send chain box

### ISSUE THREAD

**Issue by Reaper10** [LMMS/lmms#2279]
To adding send chain box like this
<img width="127" alt="c6d85258-1901-11e5-8afe-ec5384d6e48d 1" src="https://cloud.githubusercontent.com/assets/8137561/9320663/2d4972d2-4522-11e5-87bc-e25344e1bbb5.png">

you just need to add Fx  chain / Send chain tabs like this 
<img width="184" alt="untitled" src="https://cloud.githubusercontent.com/assets/8137561/9320744/117dad2e-4523-11e5-9f1b-345d74ac8647.png">

this way you don't need to make the mixer window any bigger to add send chain box. A user can get the chain they need by clicking the tab they need just like lmms plugin / env lfo tabs on LMMS Instruments.

**Comment by Umcaruje** [comment]
This was already proposed in #1823. Stop reposting your same issues, and stop cluttering up the bug tracker.
