### ISSUE TITLE
Adding a midi learn button

### ISSUE THREAD

**Issue by Reaper10** [LMMS/lmms#2283]
I'm not sure if this is good idea or not but, I just  thought it all so be good idea to have a midi learn button somewhere on the transport. What is it is a button that is like the connect to controller just faster.
How to:
1. User clicks the button 
2. move the c ontroller you want
3.  Use the connect to controller window       
<img width="129" alt="capture" src="https://cloud.githubusercontent.com/assets/8137561/9419789/7212792c-4824-11e5-9bc2-cc8a7c6d7617.PNG">
4. move knob,slider or push button on you controller 
5. click ok or cancel to close
A user can connect as many  controls to the controller as a user wants to until midi learn is turned off. To overwrite a controller  connection.  Fyi the connect to controller window for midi learn only need midi connect option.
1. User clicks the button 
2. move the new controller you want
3.  Use the connect to controller window       
<img width="129" alt="capture" src="https://cloud.githubusercontent.com/assets/8137561/9419789/7212792c-4824-11e5-9bc2-cc8a7c6d7617.PNG">
4. move a new knob, slider or push button on your controller 
5. click ok or cancel to close

mockup

![midi icon learn](https://cloud.githubusercontent.com/assets/8137561/9414357/6cd0f58c-47fd-11e5-9f75-e55944043086.png)
Fyi the connect to controller window for midi learn only need midi connect option.

**Comment by Reaper10** [comment]
Fyi the connect to controller window for midi learn only need midi connect  option.

**Comment by tresf** [comment]
Learn to edit your posts.  We get notice of every post.

**Comment by Reaper10** [comment]
Thoughts,  if it's not an good idea I'll close this.

**Comment by tresf** [comment]
STOP BUMPING YOUR OWN POSTS.  CLOSING AS PUNITIVE OF NOT FOLLOWING INSTRUCTIONS.
