### ISSUE TITLE
Changing Beat-/Bassline colours depending on their name

### ISSUE THREAD

**Issue by nucular** [LMMS/lmms#229]
What about automatically changing the colours of the Beat-/Basslines when their name is changed? For example if the name contains "bass", it is coloured orange, it it's "beat" or something, it's green. Of course there would have to be priorities between the colours, or the colour could be mixed depending on the name ("bass" adds 0.5 to the R channel etc).
Also, if the colour was changed manually by the user, a flag should be set to skip all this to avoid breaking the workflow.
I just think that this would result in a nicer, more colorful design and a better usability.

**Comment by SecondFlight** [comment]
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.
