### ISSUE TITLE
Vertical Zoom Support in Piano Roll

### ISSUE THREAD

**Issue by LYF610400210** [LMMS/lmms#2294]
LMMS can have a "vertical zoom" button in the piano roll window. It seems that the blocks of notes are too small.

![Vertical Zoom](https://cloud.githubusercontent.com/assets/6359921/9488514/2865e9ca-4c0d-11e5-8e8d-fbcb38788a0a.PNG)

**Comment by musikBear** [comment]
Yes the room for those labels are in-sufficient, but that will be changed. #2285

**Comment by Spekular** [comment]
@LYF610400210 Can you explain whst this would be used for? Do you want to
be able to zoom out, in, or both?
@musikBear I'm sure if we really want to implement this we'll be able to
make room for it.

**Comment by LYF610400210** [comment]
@Spekular The labels can be wider, so I will not add a new note by mistake when I want to click on the note to play it.
![Wider Labels](https://cloud.githubusercontent.com/assets/6359921/9494368/24c5afd2-4c38-11e5-96d4-e495f2f3c76b.png)
But I think the labels are too small to zoom out vertically.

**Comment by tresf** [comment]
>  The labels can be wider, so I will not add a new note by mistake

Valid reasoning.  I'll categorize appropriately and leave this open for feedback.

**Comment by musikBear** [comment]
> able to zoom out, in, or both?
IF something would be useful, i would say IN. That would aid selection of larger segments (but if time-spanned-selections comes, then that wont even be really interesting.)
The thing is, that expanding the notes in height, will first and foremost lead to less of the composition on screen, i really cant see the usecase for that?

@LYF610400210 (or anyone else)  -where will **that** be a benefit? 

> (**More** on screen -eg a result of 'thinner' notes *could*, at rare situations, benefit -like marking a few notes in or out of a existing selectionl.. )

**Comment by tresf** [comment]
Probably the most sensible way of implementing this is to make the height of a [white key resizable](https://github.com/LMMS/lmms/blob/master/src/gui/editors/PianoRoll.cpp#L81-L82) and let the note heights follow suit.  After reviewing this enhancement again, I feel a full-fledged vertical zoom feature is overkill for the piano roll.  It's only useful up to about 200% and it would take up unnecessary real estate on the toolbar.

In some ways, I feel this qualifies more as an accessibility feature.

**Comment by tresf** [comment]
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.
