### ISSUE TITLE
Different color lines in the piano roll

### ISSUE THREAD

**Issue by IvanMaldonado** [LMMS/lmms#2296]
It would be cool if it could be 2 different tones of color in the piano roll so one could easily find whites and blacks, like so:

http://i.imgur.com/d3b2oMV.png

**Comment by Umcaruje** [comment]
If you want to mark all the white notes, you can select and mark the C major scale in the piano roll.

**Comment by tresf** [comment]
Confirmed.  This is already implemented.

@IvanMaldonado please select 

 * `Major`

   ![image](https://cloud.githubusercontent.com/assets/6345473/9967283/b7052a38-5e0f-11e5-90a5-eb395eadfd41.png)
 * Right Click any `C` note, `Mark Current Scale`

   ![image](https://cloud.githubusercontent.com/assets/6345473/9967406/7403f81c-5e10-11e5-8692-557bd67c3a14.png)

 * Whites/blacks are displayed:

   ![image](https://cloud.githubusercontent.com/assets/6345473/9967445/987131b0-5e10-11e5-95c6-7ed2b05c1cdc.png)
