### ISSUE TITLE
SID & Monstro pulse width speed, pulse width modulation  & amount knob

### ISSUE THREAD

**Issue by Reaper10** [LMMS/lmms#2301]
I was trying to see if I could make a sound that sounds something like this
https://www.youtube.com/watch?v=w3LZPF9g_LQ
with the SID & Monstro plugin I had no luck, I think having a pulse pulse width speed pulse width modulation & amount knob may help.

**Comment by Umcaruje** [comment]
There are VST's that can probably do this. Once you have a reasonable enhancement, maybe this issue will be reopened. Until then, issues like these are unacceptable and will always be closed.

**Comment by Reaper10** [comment]
I thought asking for pulse width speed pulse width modulation & amount knob was good request.
I'm sorry

**Comment by softrabbit** [comment]
> pulse width speed pulse width modulation & amount knob

So, you wan't pulse width modulation with adjustable speed and amount? In Monstro you can modulate the PW with 2 envelopes and 2 LFOs just internally (see the **Matrix** tab), and if that's not enough there's always the LFO controllers. In SID you'll have to use an external LFO controller.
