### ISSUE TITLE
No group operations in song editor

### ISSUE THREAD

**Issue by Achifaifa** [LMMS/lmms#2302]
I don't know if this is a bug or it's just that it's not implemented. I can select a group of things in the song editor, but I can't delete, cut, copy or paste. 

Using version 1.0.3 from the debian testing repository.

**Comment by Spekular** [comment]
That sounds like a bug. You should be able to move selections by dragging
(cut), copy them by shift+dragging (copy and paste), and remove them with
the delete key. Or maybe you mean cut and paste between patterns?

**Comment by Achifaifa** [comment]
No, I mean with groups. I've tried:
* Deleting
* Cutting 
* Copying
* Pasting
* Cloning (Shift/Ctrl/Alt+Dragging)

None of these work, then only thing I can do is to move a group through the track.

**Comment by Wallacoloo** [comment]
@Achifaifa Try updating to 1.1.3 and see if the bug persists. 1.0.3 is over a year old & lmms has developed rapidly since then.

**Comment by Spekular** [comment]
Oh dear, I guess I still haven't woken up fully. I thought you were talking
about notes, sorry!

**Comment by Achifaifa** [comment]
Haha, don't worry :P

@Wallacoloo I'll try that. This is what sucks about Debian... :(

**Comment by musikBear** [comment]
> Using version 1.0.3 from the debian testing repository.
do you mean 1.1.3? ..or is linux 'behind' ?!

>  or it's just that it's not implemented
isent, only moving of selections-of-blocks afaik in 1.1.3 - ( Copy works in Master)

**Comment by Achifaifa** [comment]
I'm having issues compiling (My fault) so I haven't been able to test it. But yes, it's version 1.0.3 (Most of the things in the debian/ubuntu repositories are *very* outdated).

**Comment by tresf** [comment]
Our download page provides kxstudio links for this very same reason
(outdated repos).

Can you please try the kxstudio links?

https://lmms.io/downlaod

**Comment by tresf** [comment]
*

https://lmms.io/download

**Comment by Achifaifa** [comment]
Ok, it took a while to upgrade but finally using 1.1.3. The issue is still there, I can move groups, but not copy/paste/etc them.

**Comment by tresf** [comment]
@Achifaifa sorry we gave slightly bad advice.  This has been fixed in `master` but not in `stable-1.1` via https://github.com/LMMS/lmms/issues/46#issuecomment-44714485.

So please continue using the 1.1.3 version for now, and this will be rectified when 1.2 is released.  I'm closing since this is technically fixed from a code perspective.

If you decide to compile from source for this feature alone, I have to warn that we have one bug with ZynAddSubFX on master that will make stability suffer, so that would be a decision you would need to make.

**Comment by Achifaifa** [comment]
Thanks! Don't worry, I just wanted to compile it to fiddle with the code and see if I could do something useful with it. Just being able to move groups is good enough for me right now :)

**Comment by tresf** [comment]
> I just wanted to compile it to fiddle with the code

:+1: We need more people that mention that in bug reports.  Please chime in if you require any assistance. :+1:
