### ISSUE TITLE
Zooming in song editor doesn't zoom to part under cursor

### ISSUE THREAD

**Issue by MightyPork** [LMMS/lmms#2303]
This is more of a "missing feature" than a bug - should be easy to fix.

When you zoom in in the song editor, it simply changes horizontal scale without moving the scrollbar, and the thing you were trying to zoom is usually somewhere off the screen. It'd be great if it changed h-scrollbar to keep the under-mouse part visible.

![LMMS bug - zoom moves to start](http://cdn.makeagif.com/media/1-26-2016/3iHwRt.gif)
[Here's the bug captured (YouTube video)](https://youtu.be/XSELW7VWDQw)

![LMMS zoom bug - expected behavior](http://cdn.makeagif.com/media/1-26-2016/Z7n6GS.gif)
[Expected behavior (YouTube video)](https://youtu.be/YHcLewlrMtM) (after some video cutting with kdenlive ^^)

**Comment by LocoMatt** [comment]
I agree with @MightyPork it's very annoying.

**Comment by Umcaruje** [comment]
Took the liberty of updating the original post with gifs made from the videos.

**Comment by PhysSong** [comment]
Implemented in `master` via #3835.
