### ISSUE TITLE
LMMS qustion

### ISSUE THREAD

**Issue by Reaper10** [LMMS/lmms#2305]
This is not a bug I just wanted know why the analogue voice plugin isn't a part of LMMS?
<img width="840" alt="capture" src="https://cloud.githubusercontent.com/assets/8137561/9585392/3a984a34-4fdc-11e5-9d51-62f2786ef154.PNG">

**Comment by Umcaruje** [comment]
If you have questions like these, ask them on the forums and stop flooding the issue tracker with useless issues.

**Comment by Spekular** [comment]
@reaper10 this is better suited for the forums or mailing list imo, unless
you make it a request.
