### ISSUE TITLE
Add the ramp waveform to LFOs

### ISSUE THREAD

**Issue by Reaper10** [LMMS/lmms#2307]
Could you add the ramp waveform to all LFOs ie
LFO Controller
ENV/LFO tabe

**Comment by softrabbit** [comment]
Top row, third waveform?
![controller](https://lmms.io/wiki/images/e/eb/LFO_controller_1.0.0.PNG)

And I see it in the ENV/LFO tabs,too. Closing.

**Comment by Reaper10** [comment]
what ok, your missing the mog waves

**Comment by tresf** [comment]
@Reaper10 stop being lazy.  Even when translated your message makes absolutely no sense.

**Original**
> what ok, your missing the mog waves

**Translated**
> What? Ok.  You're missing the moog saw-wave.

Stop littering our tracker with horrible bug reports and lazy responses.

**Comment by Reaper10** [comment]
am I missing the saw that what ram was?

**Comment by Wallacoloo** [comment]
@Reaper10 Please post a screenshot illustrating what is missing and where.

**Comment by tresf** [comment]
> am I missing the saw that what ram was?

![image](https://cloud.githubusercontent.com/assets/6345473/9636613/5d7202fe-516a-11e5-8d60-7d871c9e8bcc.png)

**Comment by Reaper10** [comment]
I thought that ramp waveform button was the sawtooth wave button.
![plugins_envlfovol1 0 0](https://cloud.githubusercontent.com/assets/8137561/9639038/9123350a-516f-11e5-9311-a5e43ab12fb0.png)

**Comment by tresf** [comment]
http://public.wsu.edu/~jkrug/MUS364/audio/Waveforms.htm

> Sawtooth Wave - **also called a "ramp"** wave for obvious reasons is the most complex of the basic wave shapes.  You can view it as the 'front end' of a triangle wave and the 'back end' of a square wave.  The more complicated shape generates more overtones, in this case every harmonic is present at gradually decreasing levels.

How do you manage to garner 8 replies before getting your point across?  Get off of our tracker.   This isn't a conversation place, this is a bug tracker.
