### ISSUE TITLE
enhance the view of piano-roll & automation-editor

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#2308]
I think it would enhance usability if there was a slight shade difference in alternating bars in editors
eg : 
![piano-rollshadeopdelt](https://cloud.githubusercontent.com/assets/6662066/9628191/90aef84e-5169-11e5-8ffd-d27f81f218aa.png)
-and the same in automation-editor.
The shade difference could be less, but an alternating shading would benefit editing

**Comment by unfa** [comment]
That'd be nice.

**Comment by Reaper10** [comment]
This would all so be great in B&B and the song editors tracks.

**Comment by tresf** [comment]
@Reaper10 BBEditor and Song Editor already have this shading on my systems...

![screen shot 2015-09-28 at 5 06 21 pm](https://cloud.githubusercontent.com/assets/6345473/10148745/4f6faa6e-6603-11e5-9792-917cc5d8cde9.png)

**Comment by simonvanderveldt** [comment]
@musikBear What is the reason behind this request? Why do you want to have alternating background colors per bar?

**Comment by vlad1777d** [comment]
I like this idea.
But I think that it would be better to divide each 4 bars by color: https://github.com/LMMS/lmms/issues/3019#issuecomment-246997997

@musikBear , what do you think about this?

**Comment by musikBear** [comment]
@vlad1777d by color ? You link to this image https://cloud.githubusercontent.com/assets/12682937/18511453/67e33e32-7a8c-11e6-8f37-ae52e2469163.png
That is not the one, right. The one you think of is this one: https://cloud.githubusercontent.com/assets/12682937/20227155/c1203b54-a853-11e6-8d99-07b80846edf8.png
right?
Well, it has already been established, that different note-colors cant be implemented :) -But honestly, if you want my opinion, it is uneasy for the eyes, and confuses me. Im not sure i fully understand your idea.
Your grid is at first glance great, because of the big difference in between bars, but then take a second look. On the bright-shaded bar the beat and tick-lines are infact almost impossible to distinctly identify: I only mention these problems, in order to make everyone understand, how difficult the design-job that Umcaruje and Rebecca are facing. It is *damn* difficult!

**Comment by vlad1777d** [comment]
@musikBear , on first image too. But there (on first image) is a very little difference between color.

For color notes I created separate issue: https://github.com/LMMS/lmms/issues/3027 , and here I placed color notes only for example.

I only think, that dividing by color per 4 bars is better, that each bar. 
Why I think so I described here: https://github.com/LMMS/lmms/issues/3019#issuecomment-246997997
Maybe you would agree with me.

**Comment by musikBear** [comment]
@vlad1777 Four Bar? Ohh, so it is 4 bar and not 4 beats! 
Nono that is not at all the idea. The shading is for 2 functional reasons. 
* Making a clean visual difference between odd and equal bars.
* * This something very often used in EDM. One sort of 'pattern' for odd and another for equal bars. With alternate shading, this gets much easier to see,
* Eliminating the need for vertical bar-dividing lines, and making the grid emediately intuitive in a glance.

I can definitely understand your thought on having 4 or 8 or 16 or 32 bar visual-'groups', but there i think lmms would need a new feature, something where the user *set* a value in a spindle, and lmms then make some kind of marker, not just in piano-roll, but in all the screens. The keyword here should be user-control and flexibility

**Comment by vlad1777d** [comment]
@musikBear , there was not notification for me about answer, so I accidentally just had seen it.
OK, I agree with you. Such visual separation is good too.

**Comment by Umcaruje** [comment]
Implemented with #3062
