### ISSUE TITLE
Can't save the project

### ISSUE THREAD

**Issue by IvanMaldonado** [LMMS/lmms#2309]
Hi, I started a new project as normal and I started working on it, I save the file regularly so I can go back if I start to don't like where it is going, suddenly, when trying to save, it didn't work, everytime I save the project and I open the file it gets stuck in the pre-save file, If I add something, I save it and I open the file again it starts from the previous save before the last one.

**Comment by IvanMaldonado** [comment]
I'm sorry I can't remove the post.
Closing and opening LMMS again fixed the problem.

I got in panic when this happened, I didn't want to lose this file.

**Comment by musikBear** [comment]
It was propl. an OS issue rater than a lmms issue -When you encounter something like this, it is always a general good method to simply use the **save-as** option. This is general, not 'only' in lmms.

**Comment by Umcaruje** [comment]
>I'm sorry I can't remove the post.
Closing and opening LMMS again fixed the problem.

>I got in panic when this happened, I didn't want to lose this file.

No problem, but next time you should post to the forums before you have a reliable way of reproducing your problem.
