### ISSUE TITLE
Flanger "LFO Hz" knob reports incorrect units

### ISSUE THREAD

**Issue by Wallacoloo** [LMMS/lmms#2319]
The tooltip text for the LFO knob in the (native) Flanger plugin reports the frequency in units of "s". This would be fine, if it was reporting the period of the LFO, but it seems that it's actually reporting the frequency and is just mislabeled. I say that because a value of "5.0s" causes an oscillation that's much more frequent than a value of "0.1s".

**Steps to reproduce:**
1. Open some project and in the Mixer, add "Flanger" to one of the Fx Channels (e.g. Master).
2. Turn the "regen" and "amt" knobs up so that you can hear the effect.
3. Turn the "Lfo Hz" knob clockwise and notice that the oscillation appears to increase in frequency whereas the readout suggests its period would increase instead.

I timed it and when the LFO reads "0.2s", it actually takes 5 seconds for the flanger to cycle. So it's definitely in units of Hz as opposed to rad/sec, etc.

![lmms-lfofreq](https://cloud.githubusercontent.com/assets/1210751/9701630/53b2c71a-53e7-11e5-867a-5be1225a31e5.png)

**Comment by michaelgregorius** [comment]
@Wallacoloo Sorry, I did not see you fix. I will delete mine. :smile:

**Comment by musikBear** [comment]
nice find! :+1:

**Comment by Wallacoloo** [comment]
Closed by #2320
