### ISSUE TITLE
custom Color for midi clip

### ISSUE THREAD

**Issue by Reaper10** [LMMS/lmms#2325]
This goes with Better Color Handling #1665 adding a custom Color for midi clip option in gear menu. When a user picks a custom Color the midi notes in the piano roll window are the same custom Color as  the midi clip Color.

**Comment by tresf** [comment]
Are you suggesting that the piano roll notes are the same color as the song editor or bb editor pattern?

**Comment by Reaper10** [comment]
sorry didn't see that one.
