### ISSUE TITLE
Need to be able to delete/change large parts of automation

### ISSUE THREAD

**Issue by diizy** [LMMS/lmms#233]
The automation editor has changed in a good way, I like the new way of using points in a graph to edit automation.

BUT... older songs still have legacy automation tracks, that were made with the discrete mode, and in a worst case scenario, they're in 1/64 intervals (often they will be, as that was the best way to draw automations in .4.15). 

Say I want to change a bar in that kind of automation, I now have to go through each node separately because the discrete drawing functionality no longer works - can't just draw freehand anymore. So to edit a bar of an old automation track, I'd have to move by hand 64 nodes separately... 

We need a way to select, copy, delete and move several nodes in an automation track - but for now, even just being able to delete select parts of an automation would be great.

**Comment by SecondFlight** [comment]
My vote is to close this issue, but I'll leave it open for a bit in case there are any objections.

This was an issue with easing the transition from 0.4.15 with the previous automation system. It's been 5 years, and it's not our problem if someone is still using a version from 5 years ago. There are more important things to spend our time on IMO.

**Comment by SadaleNet** [comment]
@SecondFlight In fact this bug was never a valid bug in the first place. One could always right click and drag to remove a large part of automation notes. It has been this way since the new automation mechanism got implemented, and it's still so as of 1.2.0-rc8.

**Comment by SecondFlight** [comment]
Thanks for the reply. It's been a while since I used LMMS regularly, but now that you mention it I remember being able to right click to delete.

Closing as invalid / wontfix.
