### ISSUE TITLE
Scroll lock implementation

### ISSUE THREAD

**Issue by IvanMaldonado** [LMMS/lmms#2330]
Using the "Scroll lock" key on the keyboard to enable/disable auto-scrolling.

![scroll](https://cloud.githubusercontent.com/assets/12549082/9722673/e5fe674c-5576-11e5-99d9-97a942c8f979.png)

**Comment by haicat** [comment]
nah mayne it should toggle auto-scrollin if anything

**Comment by Umcaruje** [comment]
I agree with @haicat, **scroll** lock should toggle auto-scrolling, if its gonna be assigned with a shortcut.

**Comment by IvanMaldonado** [comment]
LOL, yeah, this is exactly what I meant, sorry, my english is not good enough to explain things.

**Comment by IvanMaldonado** [comment]
No, I actually mentioned the wrong button and functionality, epic fail

**Comment by Umcaruje** [comment]
Please update your original post with fixed description and picture :)

**Comment by IvanMaldonado** [comment]
Done

**Comment by tresf** [comment]
Creative idea, but emember, this would put a strange reliance on a lesser-used key which is a toggle for something completely separate from a DAW.

For example, on a full keyboard, this would out the number pad into "scroll" mode, which would break data inout for something like typing numbers into a spreadsheet.

Also, if someone has this key changed when LMMS launches, do they get different behavior?

Put it this way...  We could bind CAPS LOCK to be a toggle for mute but the ramifications (typing passwords in CAPS when it is forgotten to be disabled, reverse indicator when changed by a program such as Microsoft Word (try it, type "tHE" and hit space bar in MsWord) would give some very strange and unpredictable behavior.  

Even if we implement it as described, I'd like some real world testing and feedback before merging.

**Comment by IvanMaldonado** [comment]
I don't plan to start an arguing here:

"Creative idea, but remember, this would put a strange reliance on a lesser-used key which is a toggle for something completely separate from a DAW."

And it will be this way until someone changes it.

"For example, on a full keyboard, this would toggle the number pad into "scroll" mode, which would break data input for something like typing numbers into a spreadsheet." 

We won't know until someone with a full keyboard test this.

"Also, if someone has this key changed before LMMS launches, do they get different behavior?"

FL studio does this, have no problems at all, I don't remember if they get the "reverse" function but as long as it works it should be fine.

"Put it this way... We could bind CAPS LOCK to be a toggle for mute but the ramifications (typing passwords in CAPS when it is forgotten to be disabled, reverse indicator when changed by a program such as Microsoft Word -- Try it, type "tHE" and hit space bar in Microsoft Word) would give some very strange and unpredictable behavior."

The only relation I find between Caps lock and Scroll lock is that they both have a led indicator in many keyboards.

"My vote is a no."

My vote is a yes.

"Even if we do implement it as described, I'd like some real world testing and feedback before merging."

Let's test this then!

If this goes wrong, this can be changed.

**Comment by Spekular** [comment]
I support @tresf on this.

I also don't see how the "only" similarity is that they sometimes have an
indicator. They both often have indicators because they both alter the
keyboards input, and both can be really frustrating when you don't realize
what state they're in. It feels to me like saying the only similarity
between a Volvo and a VW is that they have headlights.

**Comment by IvanMaldonado** [comment]
Can't this be testeable?

**Comment by tresf** [comment]
@IvanMaldonado I'm not looking to start an argument either, just raising some concerns about implementation since we are modifying the keyboard input behavior.

If other DAWs currently do this, the impact to the keyboard is likely minor, but keep in mind that monitoring a key's toggle state versus receiving it's keyboard input are two entirely different tasks.  FLStudio -- for example -- may use native hooks such as DirectInput on Windows to detect this.  Here's a good mailing list archive on the topic:

http://comments.gmane.org/gmane.comp.lib.qt.general/42258

**Comment by IvanMaldonado** [comment]
It is fine then, I never considered "scroll lock" has an impact on the inputs as the "caps lock" key.

Focusing on things that matter is always a better option.

**Comment by Umcaruje** [comment]
Should this be closed as a `won't fix`?

**Comment by tresf** [comment]
For now  probably yes.  We can open a new one if we want to use another
hotkey or try to tackle the scroll lock key.

**Comment by Umcaruje** [comment]
K, closing as a `won't fix` then.
