### ISSUE TITLE
Adding fx plugin & sends using  moving handles

### ISSUE THREAD

**Issue by Reaper10** [LMMS/lmms#2335]
After seeing FX-Mixer: Drag'n'Drop Reordering #605 I would like to see this ability added to FX plugins fx chain and the same goes for sends chain FX Mixer sends routing chain #1823.  You could do this with the movement handles just like the ones from the instrument tracks. Adding this will help when LMMS is running on a touch screen or on a tablet.

**Comment by tresf** [comment]
I'd say it is a duplicate of this comment https://github.com/LMMS/lmms/issues/1278#issuecomment-63136208
