### ISSUE TITLE
Rendering between loop marks

### ISSUE THREAD

**Issue by Achifaifa** [LMMS/lmms#2336]
When I have to render, for example, 4 bars, I have to set the pointer in the current position and then render the rest of the song. That's inconvenient. 

Would it be possible to make LMMS render only what's between the loop bars? That we we could do small scale tests without having to render parts we don't care about at the moment.

**Comment by michaelgregorius** [comment]
@Achifaifa This feature is already implemented in master, i.e. it will be available in the next release:

![2336-export-loop-markers](https://cloud.githubusercontent.com/assets/9293269/9826110/1db98838-58d8-11e5-8ebc-55425072e969.png)

**Comment by Achifaifa** [comment]
Oh, awesome! Sorry to bother again :P
