### ISSUE TITLE
Duplicate in the "Involved" list.

### ISSUE THREAD

**Issue by ThomasJClark** [LMMS/lmms#2338]
I'm in the involved list in the about dialog twice, probably because I changed my default email, so `git shortlog` has no way of knowing the two commits are by the same author.

Assuming this is actually something people care about, I think someone with direct write access could fix this pretty easily by amending commit cdeba9c, changing the author to `Tom Clark <the.thomas.j.clark@gmail.com>`, and doing a force push.

I'm not sure if this is actually a huge problem for anyone, but if so, I'm pretty sure I can't actually submit a PR to fix it without confusing GitHub.

**Comment by tresf** [comment]
Fixed via https://github.com/LMMS/lmms/commit/55db0c8e305bf978a5e1f8da47690f09e31ff5cb

-Tres

**Comment by Wallacoloo** [comment]
Of course the man with 4 entries in .mailmap would be the first to fix it :3

**Comment by tresf** [comment]
> Of course the man with 4 entries in .mailmap would be the first to fix it :3

:eyes:

**Comment by tresf** [comment]
> Of course the man with 4 entries in .mailmap would be the first to fix it :3

Via web interface too FTL. :) (tested via `git shortlog -sne |grep homas` first)
