### ISSUE TITLE
Instrument controls look unbalanced and cluttered

### ISSUE THREAD

**Issue by michaelgregorius** [LMMS/lmms#2342]
The instrument controls (volume, pan, pitch, fx channel) currently look unbalanced:
![instrumentsettings-current](https://cloud.githubusercontent.com/assets/9293269/9831202/4ca6ad04-594d-11e5-9748-e1cdb1d06512.png)
The labels for "RANGE" and "FX" are higher than the other labels which gives the layout an unbalanced and "nervous" look.

As one solution I tried to align the controls for "RANGE" and "FX" to the bottom but then the spin boxes are lower than the other widgets:
![instrumentsettings-aligned](https://cloud.githubusercontent.com/assets/9293269/9831207/84b46880-594d-11e5-80ee-78ad34c2f4e0.png)

Finally I used a grid layout which gives a more balanced look:
![instrumentsettings-grid](https://cloud.githubusercontent.com/assets/9293269/9831208/983b6124-594d-11e5-9d16-cd05bd324a89.png)

**Comment by michaelgregorius** [comment]
Solved by pull request #2343.

**Comment by Spekular** [comment]
The save button is now much higher than the rest though...

**Comment by Wallacoloo** [comment]
This does improve some things. It also appears to make the whole control section take up more vertical space than before though. Maybe decrease the vertical padding a bit?

**Comment by Umcaruje** [comment]
Also, the controls were grouped for a reason. The Vol and Pan knobs go together, and the pitch and range go together. When everything is distributed equally like here, it makes it harder for the user to distinguish the controls.

Also the FX mixer selectors should be centered to the knobs imo.

**Comment by michaelgregorius** [comment]
This is the current version of the pull request which takes most of the remarks into account:

![instrumentsettings-grid-improved](https://cloud.githubusercontent.com/assets/9293269/9836172/a225d080-5a0f-11e5-8dde-50a0640fea33.png)

I was not able to completely reduce the vertical size back to the previous height but it should only be a difference of a few pixels.

Last but not least I have added a label "STORE" which makes the save button look more in line with the rest of the widgets.

**Comment by Wallacoloo** [comment]
This looks *very* nice to me.

**Comment by michaelgregorius** [comment]
@Wallacoloo Thanks for the nice words! Although I now wonder whether I should rename "STORE" to "SAVE" which is shorter. "STORE" and "SAVE" also convey different "vibes" for me. With "STORE" I would rather associate hardware units from the 80ies or 90ies and with "SAVE" something modern and more computer related.

**Comment by Umcaruje** [comment]
@michaelgregorius my vote goes to 'SAVE', since its more common than 'STORE'

**Comment by tresf** [comment]
Neither.  The save icon doesn't need text.

**Comment by Spekular** [comment]
My vote goes with tresf. If I had to choose, however, I'd go with "Save".

**Comment by michaelgregorius** [comment]
Merged with a "SAVE" label because it looks more balanced and is also more informative.

The merge resulted in two commits again although the code was squashed and rebased to the most current master at that time. I used the button provided by GitHub. Do I have to do the merge by command line to prevent this?

**Comment by tresf** [comment]
> The merge resulted in two commits again

Shows as one for me.   If you're looking at https://github.com/LMMS/lmms/commits I believe what you are seeing is the commit and the PR showing as two separate lines in the history.  This is normal AFAIK.

> Merged with a "SAVE" label because it looks more balanced and is also more informative.

Ok, minor, but our toolbar doesn't use this text, so keep in mind that this is slightly inconsistent and puts another unneeded translation item in our software.

**Comment by michaelgregorius** [comment]
Closed via merge of pull request #2343.
