### ISSUE TITLE
Can't make package with mingw, libsoundio missing

### ISSUE THREAD

**Issue by Umcaruje** [LMMS/lmms#2355]
While building lmms using for windows using the mingw scripts, `make package` exits with an error: 
```
[100%] Built target zynaddsubfx
Run CPack packaging tool...
CPack: Create package using NSIS
CPack: Install projects
CPack: - Run preinstall target for: lmms
CPack: - Install project: lmms
CMake Error at /home/umcaruje/lmmswax/build/src/cmake_install.cmake:41 (FILE):
  file INSTALL cannot find "/opt/mingw32/bin/libsoundio.dll".
Call Stack (most recent call first):
  /home/umcaruje/lmmswax/build/cmake_install.cmake:33 (INCLUDE)


CPack Error: Error when generating package: lmms
make: *** [package] Error 1
```

It seems to look for `libsoundio.dll` even though there are no mingw packages for it at the moment.

This probably has something to do with #2339 so I'm tagging @andrewrk.

**Comment by tresf** [comment]
Can you comment it out and see if it proceeds?  If so, comment it out on master and we'll remove it when we have the supporting mingw package.

**Comment by tresf** [comment]
@waxspin, FYI

**Comment by Umcaruje** [comment]
Checking it out now, Offending line is [`src/CMakeLists.txt#L186`](https://github.com/LMMS/lmms/blob/master/src/CMakeLists.txt#L186) I'll comment it out and see how it goes.

**Comment by Umcaruje** [comment]
Ok so https://github.com/LMMS/lmms/commit/09bc6f158a261619586f932549162cc2af1b57e7 comments it out and makes a temporary fix.

When the libsoundio packages are added to the mingw ppa, this should be uncommented.

**Comment by Wallacoloo** [comment]
Shouldn't this be conditional upon the `WANT_SOUNDIO` variable defined in [/CMakeLists.txt](https://github.com/LMMS/lmms/blob/master/CMakeLists.txt), and shouldn't we be putting `libportaudio-2.dll`, `SDL.dll` `libvorbis-0.dll`, `libvorbisenc-2.dll`, `libvorbisfile-3.dll`, and `libogg-0.dll` behind `WANT_PORTAUDIO`, `WANT_SDL`, and `WANT_OGGVORBIS` conditionals?

**Comment by tresf** [comment]
@Wallacoloo hypothetically, yes.

Pratically what you are describing wouldn't happen unless we get more Windows developers with special build environments.  Unlike Linux, we have an extremely static toolset for Windows cross-compilation so the build process has gotten away with being static.

So yes, we can and eventually should do what you are describing, but there is very little advantage in doing currently IMO.
