### ISSUE TITLE
New mute clip tool

### ISSUE THREAD

**Issue by Reaper10** [LMMS/lmms#2356]
I don't know if I am nit picking on this bug report or not, but I would like a mute clip tool added. You all ready have the tool in the right click mute clip option. All you need to do is add a button on the song editor, B&B  editor, midi clips editor and the mute clip icon for the mouse pointer. In #746 it adds Razor and Glue tools. The new mute clip tool adds a quick way to mute clips and or midi notes. Just like the Razor tool dose with clip and or midi notes cutting and Glue tool dose with combining clips and or midi notes. This for those who want mute a lot of clips or notes. This is all so for Collapsible Song Editor Groups #735 with a lot of the sample track.

**Comment by Umcaruje** [comment]
You can already quickly mute clips (patterns, bastards, whatever) using the `Ctrl + Middle click` and `Ctrl+ Alt + Right click` shortcuts + there is the context menu you mentioned. Muting a lot of patterns isn't a very common thing to do (at least for me) so I don't really see much benefit from such a tool.

**Comment by Reaper10** [comment]
This for those who want mute a lot of clips or notes.

**Comment by BaraMGB** [comment]
IMO we should

**Comment by Umcaruje** [comment]
I'm closing this request since the OP (who is now banned) failed to prove the usefulness of such a feature, and this is a generally poorly written bug report.
