### ISSUE TITLE
Where can I obtain old sample music pack?

### ISSUE THREAD

**Issue by TheBlackMIDIMasta** [LMMS/lmms#2364]
Where can I get the old sample music pack from older versions of LMMS? The old sample pack included a song called "Underline" by Numarul7. Anybody know where I can obtain this sample music pack or a version of LMMS that included this sample music pack?

**Comment by jack126guy** [comment]
It's in the history of the repository. [Version 0.4.11](https://github.com/LMMS/lmms/tree/v0.4.11/data/projects/cool_songs) was the last version to include that song.

**Comment by tresf** [comment]
Thanks @jack126guy!

Here is the full source download, which will also included any necessary samples too:

 
https://github.com/LMMS/lmms/archive/v0.4.11.zip


Closing as this resolves the OPs question.
