### ISSUE TITLE
Misleading version information

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms#2365]
Currently, if someone grabs the master branch, they build LMMS and it will be labeled in respect to the version information in `/CMakeLists.txt`, which currently is `1.1.3`.

This is misleading because most developers will build from `master` when developing a new feature and any binaries released will bear the stable version number in the dialogs.

Should we try to leverage git in the build process to detect a non-stable build?  If so, how should we do the numbering for a non-stable build?

My thought is to take a "nightly" approach:

**Edit:** The agreed approach is:

```cmake
   SET(VERSION_MAJOR       "1")
   SET(VERSION_MINOR       "1")
   SET(VERSION_PATCH       "3")
   # and perhaps
   SET(VERSION_SUFFIX      "a1b2c3") # commit id
```

This would be done by checking the origin of the `git remote` and if it is not `/lmms/lmms` and does not contain the word `stable` in the branch name, use the above versioning.

**Edit2:** Overridable via `cmake -DFORCE_VERSION=x.x.x-x`

(old, left for historical purposes... disregard this part)
```cmake
   SET(VERSION_MAJOR       "2015")
   SET(VERSION_MINOR       "09")
   SET(VERSION_PATCH       "21")
   # and perhaps
   SET(VERSION_SUFFIX      "0932") # 9:32 AM
```

The biggest downside is that this may have some unintended side-effects when comparing stuff like `ProjectVersion` which uses version_major, etc inside the code for compat code and project and config file upgrades.  Thoughts?

**Comment by musikBear** [comment]
>  Thoughts?

Only that i highly applause this initiative :+ 
Version control is SO important, and i have been confused a couple of times 
but
VERSION_MINOR       "09"
couldent date and perhap even timestamp be a part too?
like
VERSION_MINOR       "09_21_15:42"

**Comment by tresf** [comment]
> couldent date and perhap even timestamp be a part too?
like

Yeah, perhaps `VERSION_SUFFIX`, which we rarely use, but is avail.

**Comment by Wallacoloo** [comment]
We could use the [even=release, odd=devel](https://en.wikipedia.org/wiki/Software_versioning#Odd-numbered_versions_for_development_releases) versioning system. That retains 100% compatibility with the existing version comparisons.

Alternatively, we could go with `Major.Minor.Patch.CommitNumber`, which still allows for version comparisons within development builds. `CommitNumber` would have to be the total number of commits in the given branch, rather than the hash of the branch head, to allow for version comparisons, and we would only include it in devel builds and maybe RCs.

Although I prefer the former, it looks like *most* projects that ever used that convention have abandoned it for various reasons - one common one because users consistently ask questions like "What happened to version 1.4, 1.6 and 1.8?". [One such discussion on the matter](https://github.com/znc/znc/issues/748). Notably, Gnome still uses even/odd versioning.

**Comment by tresf** [comment]
@Wallacoloo thanks.  Perhaps you could help explain as I'm not sure I see the correlation since our master builds are so drastically far from our `stable-1.1.3` builds that offering a `1.1.3.1` would be misleading, or perhaps I'm missing something...

**Comment by Wallacoloo** [comment]
@tresf I was saying the even/odd versioning can be confusing. `Major.Minor.Patch.CommitNumber` shouldn't be confusing, just ugly :P 

For even/odd versioning, we would only publish versions like this on lmms.io:
```text
1.0.0
1.0.1
1.0.2
1.2.0
1.2.1
1.4.0
1.6.0
1.6.1
[...]
```

Users would ask "where is version 1.1, 1.3 and 1.5?" The answer is "those were unstable versions the developers used internally".

i.e. after we release version 1.2.0, we would immediately bump the version in `master` to 1.3.0 and continue developing. Then once we stabilized master, we would release `1.4.0` in the stable channel and bump master to `1.5.0`.

I'm not sure how release candidates would work. We could just release `1.3.1`, `1.3.2`, etc. as release candidates for `1.4.0`. I'm not sure how they're handled currently anyway.

Upon re-reading your comment, I can't figure out exactly how it's supposed to read, so I may be misinterpreting it. Sorry if what I said above is totally irrelevant to your question.

**Comment by tresf** [comment]
> I'm not sure how release candidates would work. We could just release 1.3.1, 1.3.2, etc. as release candidates for 1.4.0. I'm not sure how they're handled currently anyway.

Today we do `1.1.90` as a RC-predecessor to `1.2.0`.  That works because it tells people it's `almost` `1.2.0` and the version is greater than `1.1.3` which was our last stable.

Your proposal works, but it means our `.0` releases will never be stables, which work from a coding mentality, but not as much from a PR mentality as our users would be quite confused that we're working up to a milestone of `1.2.7` (for example) versus `1.2.0`.

Perhaps we just adopt an arbitrary date for non-release and non-RC builds and do our ProjectVersion type testing manually?

**Comment by tresf** [comment]
@Wallacoloo 4360427 is an experiment to switch to a date-based versioning when we've strayed from the stable branches.  Opinions welcome.

**Comment by Wallacoloo** [comment]
> Today we do 1.1.90 as a RC-predecessor to 1.2.0. That works because it tells people it's almost 1.2.0 and the version is greater than 1.1.3 which was our last stable. RC2 will be 1.1.91, etc.

We could still totally do that with the even/odd system *or* `Major.Minor.Patch.CommitNumber`. To use gnome as an example again, `1.17.0`, `1.17.1`, etc. are internal versions, while `1.17.90`, `1.17.91`, etc are RCs for `1.18.0`. [More detail](https://wiki.gnome.org/ThreePointSeventeen).

@tresf Using two disparate versioning systems (`YYYY.MM.DD` and `Major.Minor.Path`) seems needlessly complex in comparison to adapting our existing versioning system to fulfill both roles. Don't forget, we have comparisons against "1.1.90" in our source tree right now (ConfigManager.cpp:140), and switching to YYYY.MM.DD will needlessly destroy such comparisons and upgrade paths inside of development builds.

**Comment by tresf** [comment]
> Don't forget, we have comparisons against "1.1.90" in our source tree right now (ConfigManager.cpp:140), and switching to YYYY.MM.DD will needlessly destroy such comparisons and upgrade paths inside of development builds.

1.1.90 is a RC version, which would get its information properly still since:
 * It would pass the `grep -i "lmms/lmms"` check as well as 
 * It would pass the `grep "stable-"` check

This would only affect non-LMMS and non-stable-branch builds.  We could allow an override too if we decide to, but RC releases won't be affected by the example provided.

**Comment by tresf** [comment]
Note, the override would be be mandatory for build systems like Debian, Fedora, etc as they may not clone our code directly from Git but instead maintain their own source archive.

**Comment by Wallacoloo** [comment]
@tresf here is the code that gets run for LMMS_VERSION < "1.1.90":
```c++
        // Remove trailing " (bad latency!)" string which was once saved with PulseAudio
	if( value( "mixer", "audiodev" ).startsWith( "PulseAudio (" ) )
	{
		setValue("mixer", "audiodev", "PulseAudio");
	}

	// MidiAlsaRaw used to store the device info as "Device" instead of "device"
	if ( value( "MidiAlsaRaw", "device" ).isNull() )
	{
		// copy "device" = "Device" and then delete the old "Device" (further down)
		QString oldDevice = value( "MidiAlsaRaw", "Device" );
		setValue("MidiAlsaRaw", "device", oldDevice);
	}
	if ( !value( "MidiAlsaRaw", "device" ).isNull() )
	{
		// delete the old "Device" in the case that we just copied it to "device"
		//   or if the user somehow set both the "Device" and "device" fields
		deleteValue("MidiAlsaRaw", "Device");
	}
```

This accounts for changes that have occurred *after* the release of 1.1.3 but *before* the release of 1.1.90. It's *intended* to affect both the RC and the development versions. If this check is bypassed (e.g. because "2015.09.21" is not < "1.1.90"), then the next time we do something like change the "Device" property to "device", developers will manually have to go into ~/.lmmsrc and make the changes themselves. *Why??* What is the logic behind this? What are the benefits of using two *totally different* versioning systems?

If including the date is *really* important to you, there is yet another system we could use that doesn't needlessly break version comparisons: `Major.Minor.Patch.YYYYMMDD` for development versions and `Major.Minor.Patch` for releases.

**Comment by tresf** [comment]
> This accounts for changes that have occurred after the release of 1.1.3 but before the release of 1.1.90. It's intended to affect both the RC and the development versions.

But as long as we keep `CMakeLists.txt` at 1.1.3, none of our devs can test without manipulating the version number.

> @tresf Using two disparate versioning systems (YYYY.MM.DD and Major.Minor.Path) seems needlessly complex in comparison to adapting our existing versioning system to fulfill both roles.

> then the next time we do something like change the "Device" property to "device", developers will manually have to go into ~/.lmmsrc and make the changes themselves. Why??

I'm not saying they should, I'm trying to walk through this problem with a solution.

The problem is that `Major.Minor.Patch` is wrong 99% of the time for devs and I'm hoping we can find a way around that without having to adjust `CMakeLists.txt`.

**Comment by tresf** [comment]
I guess my main fear is from a branding perspective... we're making a release called `1.1.3` and all unstables are called `1.1.3-foo`.  It just seems too misleading.   I agree that YYYYMMDD breaks our version checking and it is just a proposal, but I hope you can understand why I don't want `1.1.3-foo` in the about dialogs for our nightlies.  It just misrepresents the code behind the version number.

**Comment by Wallacoloo** [comment]
@tresf 
> I'm hoping we can find a way around that without having to adjust CMakeLists.txt.

Ah, I see. I'm not sure exactly how we actually tag releases in git, and I know we have a separate stable vs. master branch, which complicates things. But I think our solution in general is to use git tags.

Let's assume that when we release 1.2.0, the stable branch is in sync with the master branch. Let's tag the head of each branch at that point as "stable-1.2.0". Within the stable branch, we can continue tagging "stable-1.2.1", etc. Then in cmake, we can do the following, which removes having to keep *any* version info in the repository files:

1. Check for the most recent tag starting with `stable-`
2. If it is equal to the current head, extract the full version from the tag (e.g. `stable-1.1.3` becomes `1.1.3`).
3. If it is *not* equal to the current head, extract only the major and minor components, and set PATCH=90, SUFFIX=YYYYMMDD.

Due to release candidates, step 3 would have to be slightly more complicated. It would have to be something like PATCH=max(90, last_tagged_patch+1), so that any commits after "1.1.90" is tagged would become "1.1.91.YYYYMMDD".

**Comment by tresf** [comment]
@Wallacoloo here's what the `MAJOR.MINOR.VERSION-COMMIT` looks like from a code perspective https://github.com/tresf/lmms/commit/420b782a8b31fec44ca3c64633cae0a17b19382f

And what it looks like when building:

![image](https://cloud.githubusercontent.com/assets/6345473/10004021/8292a85a-607d-11e5-8b5e-d15c9951854d.png)

**Comment by Wallacoloo** [comment]
@tresf that's the format you want to avoid, right? (`1.1.3-fcef3e8`)

> we're making a release called 1.1.3 and all unstables are called 1.1.3-foo. It just seems too misleading.

**Comment by tresf** [comment]
> that's the format you want to avoid, right

Yeah, but we're splitting hairs... :)

Here's the comparison... https://github.com/LMMS/lmms/compare/master...tresf:2365-versions

**Comment by Wallacoloo** [comment]
@tresf 

> Yeah, but we're splitting hairs... :)

So you *are* fine with `MAJOR.MINOR.VERSION-COMMIT`? If so, I have no problems with that format.

**Comment by tresf** [comment]
> we can do the following, which removes having to keep any version info in the repository files

I love this idea as it fixes the major problems... but it puts a hard requirement on our software for version control to be tag-aware.  It also will force us to version our master branch somehow since it's tag is currently just `master` as far as I know.

> So you *are* fine with `MAJOR.MINOR.VERSION-COMMIT`? If so, I have no problems with that format.

Yeah, I think it's the lesser of two evils.  I hadn't realized how well the `< 1.1.90` logic actually was for interim builds until this conversation. :+1:

**Comment by tresf** [comment]
I'm going to squash the commits and open a PR for comments.  Testing this one is a bit trickier because the `git` commands won't be testable on stable without a merge or some manipulation.

**Comment by Wallacoloo** [comment]
@tresf ok, sounds good. Glad we got things figured out & sorry if I came off a bit strong throughout the conversation.

**Comment by tresf** [comment]
:)

How do you feel about the [`DateInfo.cmake`](https://github.com/tresf/lmms/blob/2365-versions/cmake/modules/DateInfo.cmake).  We technically don't need it now since we're not doing that calculation but I thought it might be beneficial down the road perhaps...

**Comment by tresf** [comment]
... also, I think we'll still need a way to prevent the hash from being appending for other build channels... Do you agree?  Perhaps a CMake flag such as

```bash
cmake -DFORCE_BASE_VERSION=1
```

**Comment by Wallacoloo** [comment]
@tresf if DateInfo isn't used, then it shouldn't be in the repository. You could upload it as a gist & insert a link to it in the PR if you want it to be easily accessible should you need it in the future.

@tresf What are the other build channels, besides stable and master? If your concerns are when somebody builds their own development branch of lmms and the version info includes a commit that isn't present in `lmms/master`, maybe the solution is to encode the version as `Major.Minor.Patch-BranchName:hash`, where BranchName is omitted for master?

**Comment by Wallacoloo** [comment]
Ah, I'm guessing things like Debian releases. In that case, we should have an override. Maybe something like "-DFORCE_VERSION=1.1.3-debian1" - that way the debian maintainers can still distinguish different versions of their own builds against 1.1.3.

**Comment by tresf** [comment]
Ok.  All fixed up via [#2368/files](https://github.com/LMMS/lmms/pull/2368/files)

Archive of [`DateInfo.cmake`](https://gist.github.com/tresf/5d331a410746aecf8428)

**Comment by tresf** [comment]
So to summarize... `VersionInfo.cmake` will parse the `VERSION_MAJOR`, `VERSION_MINOR`,`VERSION_PATCH` and optionally `VERSION_SUFFIX` from the command line.  If a full version is not supplied (e.g. `1.2`) cmake will fail with an out of bounds error.

I cherry-picked this feature on to stable-1.1 to verify the commit hash doesn't get appending... tests pass via screenshots below.

I'll give this some more time for feedback prior to merging.  Even a head nod would be nice so I know the PR has been reviewed [#2368/files](https://github.com/LMMS/lmms/pull/2368/files)


![image](https://cloud.githubusercontent.com/assets/6345473/10020217/b6281b9a-610f-11e5-9f06-f30751bd2472.png)


![image](https://cloud.githubusercontent.com/assets/6345473/10020255/ec982ada-610f-11e5-9f88-3c9c22333648.png)

**Comment by softrabbit** [comment]
Looks fine to me. The date could of course be useful for comparisons, but something like ```1.1.3-yyyy-mm-dd-hash``` would be too long to be worth it IMO.

**Comment by tresf** [comment]
Date is a bit more "nightly" IMO, and I wouldn't be opposed... We could remove the dashes and pull out commit ID completely?  Open to ideas. :)

**Comment by tresf** [comment]
So the only concern I have left is if @Israel- @falkTX or other packagers use non-upstream source for the code but still use git, where an arbitrary hash would be appended unless the packager took the time to supply the matching version number on command line... 

So I've added another option `cmake .. -DFORCE_VERSION=internal`, which overrides the hash calculation but allows the fallback on the default version information contained within `CMakeLists.txt`.

I've also updated the output to help explain this.

![image](https://cloud.githubusercontent.com/assets/6345473/10063378/d4957524-623a-11e5-907c-1e1ddfee28bd.png)

**Comment by falkTX** [comment]
For KXStudio at least I usually go with the stable tarball releases.
I might import some patches from the stable branch that fix known issues which will be part of the next release.
