### ISSUE TITLE
alternative way to silence a track in song-editor

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#2371]
The neat improvements on *mute*, *solo* and normal play features -Eg how unmuting a muted track now emediately set all tracks back to normal re-play, makes for a new level of silencing in piano-roll. This new level is for tracks that the user almost has decided to really delete, but user are just not 100% sure, if the track *is* **badTrack**. If user now **mute** such a track, **that** track will come back in the mix, with the next *solo* to *solo-off* event, and user then have to browse to the **badTrack** and mute it once more.
There are two neat ways, (and one awful) to tackle this:
* A new menu-option in cog-wheel-context: *Exclude track from mix*
 *  *  Could be implemented as a cascade block-muting
* Explain in wiki what i just wrote here, and ask user to turn of volume :p 

So the choice is between a *feature solution* or a dead simple heuristic 

A pro/con swot is not really there, because diiz has explained, that all note events are 'counted' (uses cpu), weather they are audible or not.

so..   feature solution or simple heuristic ? 

*The awful is to manually mute every block in badTrack, but thats so darn tedious and right of dumb*

**Comment by tresf** [comment]
I have no idea what I just read.  Can you make this understandable in a sentence or two?

**Comment by michaelgregorius** [comment]
@musikBear I cannot reproduce what (I think) you have described. When I mute several tracks and then solo another one then all the previously muted tracks will stay muted when I unsolo that track. Therefore one can simply use the mute button to mute tracks that potentially will be deleted later.
