### ISSUE TITLE
New toolbar behavior

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms#2379]
Something @grejppi pointed out is that the new toolbar functionality creates a cosmetic problem when using the `Right Click` shortcut to switch to a previous Beat/Bassline.

 1. Branch:  `master`
 2. Open new project
 3. Add a second Beat/Bassline to default project (you need at least two)
 4. Open `Beat/Bassline 1` window (2nd)
 5. Right click the `Beat/Bassline 1` in the tool bar
 6. Menu appears AND it switches to `Beat/Bassline 0`

![image](https://cloud.githubusercontent.com/assets/6345473/10081454/f9e817ae-62c2-11e5-9f19-35f1d0861478.png)

@michaelgregorius feedback welcome.  I personally agree with the context menu behavior for consistency purposes, but this is something which causes undesirable behavior for users that are historically used to this mouse shortcut.

Related #2287

Since this relates to shortcuts, this is also related to our `WIP Default shortcuts` thread #1488.

**Comment by grejppi** [comment]
The behaviour of our `ComboBox` everywhere in LMMS is that left clicking increases and right clicking decreases the value. Preferring the context menu over the default behaviour would result in a jarring inconsistency.

**Comment by tresf** [comment]
> Preferring the context menu over the default behaviour would result in a jarring inconsistency.

There is obviously a bit of preference that goes into a decision like this, but most platforms consider the right-click as the pop-up trigger, so using it as an action event could equally be viewed as a jarring inconsistency.

@Sti2nd started identifying these because the software has historically used shortcuts inconstantly throughout (e.g. double-clicking a track name renames, right-clicking a track name renames, double-clicking a pattern opens, right clicking a pattern shows context menu).  This needs to be ironed out and I hope we keep the big picture in mind when deciding how to leverage our user interface moving forward.

**Comment by grejppi** [comment]
How many times do you think "gee, I really want to customize this toolbar" while producing music, compared to "let's quickly see what's in the previous pattern"?

**Comment by tresf** [comment]
> gee, I really want to customize this toolbar

I think you're misinterpreting the purpose of the modular toolbar... This wasn't really for that, but rather used a built-in Qt functionality for organizing and stacking the items so reduce horizontal real-estate.

To answer the specific question, I personally think the toolbar is gross and cluttered, so I would advocate for many of the items hidden by default, personally.

To answer it more broadly, I don't think we should ever mess with the popup trigger.  Middle wheel click?  Sure.  Right click?  Not so much.

**Comment by michaelgregorius** [comment]
The toolbar behavior for the BB-ComboBox seems to be a bit strange anyway. Here is what I get when I right click on the arrow on the right side:
![bb-context_menu](https://cloud.githubusercontent.com/assets/9293269/10083132/505283d8-62fd-11e5-8293-90f8b9e55376.png)
It's created by this code:
```C++
void ComboBox::contextMenuEvent( QContextMenuEvent * event )
{
	if( model() == NULL || event->x() <= width() - CB_ARROW_BTN_WIDTH )
	{
		QWidget::contextMenuEvent( event );
		return;
	}

	CaptionMenu contextMenu( model()->displayName() );
	addDefaultActions( &contextMenu );
	contextMenu.exec( QCursor::pos() );
```
So, if there is no `model` or the click did not go on the arrow on the right side it delegates to the `QWidget` implementation which I assume is ultimately responsible for showing the context menu of the toolbar. Otherwise a menu is created and shown. The empty space at the top of the menu in the screenshot is likely intended to show the display name of the `model`, then some default actions are added. However, does resetting to zero, automation, etc. even make sense in this context (non pun intended :wink:)?

If there are some other contexts in which the delegation to `QWidget` makes sense we might fix this by adding a `bool` to the `ComboBox` class which can be used to configure the `ComboBox` to ignore and consume the event. The `ComboBox` of the BB-Editor would then get configured to do so. If there are no other contexts it might even make sense to remove the delegation completely and to consume the event. What do you think?

**Comment by grejppi** [comment]
> If there are no other contexts it might even make sense to remove the delegation completely and to consume the event.

This affects every single `ComboBox` in every toolbar. Zoom, scale, you name it.

For me the most important feature here is the ability to quickly browse through all patterns. I know you can use the scroll wheel, but it is not as precise.

To be honest, I still haven't found a single good use for the modularity. Especially in the B&B editor, where I have yet to find a button that goes unused.

Also, what if you decide to hide all toolbar parts? There's nothing to prevent that. Good luck trying to get them back without restarting when you have zero pixels of the toolbar left. (Recommended reading: [*Checkboxes that kill your product*](http://limi.net/checkboxes-that-kill/))

**Comment by tresf** [comment]
> For me the most important feature here is the ability to quickly browse through all patterns. I know you can use the scroll wheel, but it is not as precise.

You could make the same argument for any spinner box too, but we don't do right-clicks actions.  Instead we offer a context menu.

Also, I'd like to point out... semantics, but `all patterns` would extend to piano roll patterns as well, which don't have such a combo box.

> There's nothing to prevent that. Good luck trying to get them back without restarting when you have zero pixels of the toolbar left.

We're certainly not the first to face this problem and although that doesn't justify it, we need to be careful as to how we describe our struggles to those helping.  We're all in this together.

> Especially in the B&B editor, where I have yet to find a button that goes unused.

Agreed, but the main toolbar and the piano roll toolbar are a bit of a mess and I would like to see zoom handled in a more consistent way in general (sticky to top right or bottom right for quick and intuitive access).

So if we turn off the ability to show/hide toolbars (@grejppi's right, this can be done all-too-accidentally and piss someone off), how easy is that @michaelgregorius?

Should we settle for a context menu that isn't in the right click of **every single component**, offered (perhaps) as a **Right click, Customize Toolbar** menu?

**Comment by michaelgregorius** [comment]
What I wanted to ask was whether there is a single situation in LMMS where the execution of this `if` clause makes sense / is needed:
```C++
if( model() == NULL || event->x() <= width() - CB_ARROW_BTN_WIDTH )
{
    QWidget::contextMenuEvent( event );
    return;
}
```
If there is none we could solve the problem by changing the code as follows:
```C++
void ComboBox::contextMenuEvent( QContextMenuEvent * event )
{
    if( model() || event->x() > width() - CB_ARROW_BTN_WIDTH )
    {
        CaptionMenu contextMenu( model()->displayName() );
        addDefaultActions( &contextMenu );
        contextMenu.exec( QCursor::pos() );
    }
}
```
This would only show the context menu for clicks on the arrow.

Alternatively we could disable the context menu for the toolbars. That would only need the addition of a single line in `Editor::addDropToolBar`:
```C++
toolBar->setContextMenuPolicy(Qt::PreventContextMenu);
```

**Comment by musikBear** [comment]
What if **context** was sh+right-mouse-click?
Honestly, i think that this 'show/hide' speedbar button-groups feature, will be one of the seldom used of all. Only thing that will occur is 'some' Qs on forum:
*"Why cant I find .... anymore "*
8{

**Comment by tresf** [comment]
After some deliberation on the #lmms channel on IRC, I think we need to remove the show/hide toolbar context menu.

>  'show/hide' speedbar button-groups feature, will be one of the seldom used of all

Yes, this has been @grejppi's point all along and after using master branch I believe his concerns should be taken more seriously.  When right-clicking items, I accidentally hid critical components on several occasions, so if we do make this toolbar something that can be configured by the end-users, we need it stashed away somewhere, if we decide to keep it at all.

Another point @grejppi made was in regards to the problem this modular toolbar is fixing.  If we have too many components on the piano roll toolbar, perhaps we clean it up rather than giving the option to hide items.  The marking of chords as well as the ability to enter chords quickly is a pretty advanced feature and perhaps we should re-think the usefulness of this on the piano roll toolbar by default.

Another space saving measure will be when we finally settle on a global toolbar so that buttons like cut/copy/paste aren't chewing up space on subwindows, and even the play/pause/stop buttons make it to a dedicated location as well.

But in lieu of closing out this ticket, @michaelgregorius I'd vote we disable the context menus until we have a better-planned approach for toggling them.  @grejppi's right, we can't roll out 1.2 with the context menu we have, and until we find better shortcuts for the combo boxes, we're better off keeping the existing right-click behavior anyway.

**Comment by michaelgregorius** [comment]
Oops, seems like GitHub automatically closes issues if you write something like "fixes #2379" into the commit message. Anyway, this problem was solved using the one liner for `Editor::addDropToolBar` that was described above.

**Comment by tresf** [comment]
:+1:

**Comment by tresf** [comment]
I'd like to add for those that are perusing via email... the actual fix applied which closes this is:

```diff
+	toolBar->setContextMenuPolicy(Qt::PreventContextMenu);
```
