### ISSUE TITLE
LADSPA instruments

### ISSUE THREAD

**Issue by yukulele** [LMMS/lmms#2403]
Hi, I'm unable to use LADSPA instruments.
on `tools > LADSPA Plugin Browser`, in `instruments` tab (keyboard icon), there is a lot of instruments.
How to use them?

**Comment by musikBear** [comment]
you cant. the browser is a quaint stepchild of lmms... It actually shows what is not available in lmms
btw :)

This resourse is not the right forum for Q&A, Q&A should takes place in our dedicated help-forum :)
Could i ask you to create an account there: http://lmms.io/forum/ ?

**Comment by Reaper10** [comment]
I never understood the plugin browser  being that a LMMS user can't use them or Installed into LMMS.I think it would be great to see the LADSPA plugin browser  instruments & FX be able to be Installed into LMMS and a user be able to use them or uninstalled if the user wants to uninstall them.

**Comment by grejppi** [comment]
There is no such as a LADSPA instrument due to limitations of the specification They are wrongly categorized.

LMMS just ships a bunch of plugin sets as-is. They unusable plugins would not be useful in a linear effect chain like in LMMS.

**Comment by Reaper10** [comment]
what is the point pf  the plugin browser?

**Comment by karmux** [comment]
Latest LMMS from master doesn't find any installable LADSPA plugins even if I tell it to load from /usr/lib/ladspa. Few months ago on master branch I had like 200 of them installed via apt. Now I have only 15 that come with LMMS.

**Comment by tresf** [comment]
Marking for 1.2 milestone.

**Comment by tresf** [comment]
> There is no such thing as a LADSPA instrument due to limitations of the specification. They are wrongly categorized.

@grejppi's answer is the correct one since this is in regards to instruments.  @yukulele if you want to use an LADSPA effect, that is supported via the FX mixer or FX tab of an instrument.

Closing this out as we are unlikely to add LADSPA instrument support.

The LADSPA plugin listing bug is a separate issue (https://github.com/LMMS/lmms/issues/2426).
