### ISSUE TITLE
A new deault  splash screen with Animations

### ISSUE THREAD

**Issue by Reaper10** [LMMS/lmms#2405]
I think in Modern And Sleek Theme For LMMS #880   RebeccaDeField brought up the idea of a nee default splash screen with .gif animation. I think this a great idea being that when I start I can't tell if LMMS is going to load or not.

![136dc1fc-c362-11e4-8343-842efe15554b](https://cloud.githubusercontent.com/assets/8137561/10412776/3ade8168-6f56-11e5-9f4b-4ed63d6d5fc1.png)

In this splash screen simply having the pattern fade in and out good. 

![26880c0a-baae-11e4-9cd9-e06a7efea289](https://cloud.githubusercontent.com/assets/8137561/10412802/ee71c424-6f56-11e5-9f80-46df25dde7c9.png)

In this splash screen simply having the lines crawl back and forth good. 

default splash 

![68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f323837393931372f323138393331392f61623964313236382d393831342d31316533](https://cloud.githubusercontent.com/assets/8137561/10412965/f0b14e24-6f5d-11e5-99bc-77330597cd43.png)

In this splash screen simply having a green box crawling  up the splash screen and then having it do it in revere  forth good.

**Comment by Spekular** [comment]
1.2 already has loading text to show progress, plus I doubt we have the
avility to display a gif as is. While animated loading could be nice, I
doubt a gif is the best option and I'd consider it very low priority

**Comment by Umcaruje** [comment]
No.

**Comment by Reaper10** [comment]
well adding animation can be added down the road and it's up the programmers on the best way do this

**Comment by grejppi** [comment]
No.

**Comment by tresf** [comment]
> The next time we close a bad issue request from you or have to warn to stop bumping your own request, we will issue a final warning. After the final warning you will be banned. 

@Reaper10 this is the final warning.
