### ISSUE TITLE
LFO controllers remain in controller rack after closing project

### ISSUE THREAD

**Issue by grejppi** [LMMS/lmms#2409]
Steps to reproduce:

1. Open LMMS
1. Observe the emptiness of the controller rack
1. Click on 'Add' in the controller rack
1. Create a new project
1. The ghost of the LFO controller will still be present in the controller rack. Right-clicking to show its context menu, or trying to access its controls will crash LMMS.

Introduced in #2222, cd0176b5afe18eef71bc45c66ec2017a109a0602 to be exact.

Hi @michaelgregorius, nice to meet again.

**Comment by michaelgregorius** [comment]
@grejppi Thanks for the bug report! Fixed with #2410.
