### ISSUE TITLE
Kicks, closes the program after pressing "Save"

### ISSUE THREAD

**Issue by MaxQNEI** [LMMS/lmms#2416]
Kicks, closes the program after pressing "Save"

Terminal:
Notice: could not set realtime priority.
VST sync support disabled in your configuration
Connection established.

Stream successfully created

*** Error in `lmms': malloc(): smallbin double linked list corrupted: 0x000000000716bda0 ***

**Comment by Umcaruje** [comment]
@MaxQnei please offer steps to reproduce this issue, your LMMS version and a backtrace (if you can)

**Comment by MaxQnei** [comment]
Thnx!
Before update Ubuntu to 15.10, i have 15.04. I don't remember LMMS version. But, i do:
1. Make mix
2. CTRL + E
3. Begin
Result: Crash =(
But, "sound.wav" have size 40 byte (may be).

P.s. Sorry for my english ^_^

**Comment by zonkmachine** [comment]
Sorry, still too little information. The new LMMS 1.2.0 will be out in a month or so. Grab that one and try your project again. If you still see this bug, please reopen this issue and update the information.

Thanks!
