### ISSUE TITLE
VSTs won't run from build directory

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms#2419]
Steps to reproduce:
1. Compile lmms (`master` branch)
2. From the build directory run `./lmms`
3. Drag a VST into your project
4. Receive console message `remote plugin died! invalidating now.`

Work-around:
1. After compiling, run `make install`
2. Run lmms from install directory (i.e. `../target/bin/lmms`)

Related:  #1719

**Comment by zonkmachine** [comment]
@tresf This seem to work fine now.
`linuxmint 17.3, Qt4`

**Comment by tresf** [comment]
Closed via #1719.  @zonkmachine thanks for the follow-up!
