### ISSUE TITLE
Double clicking into piano roll from B+B is broken

### ISSUE THREAD

**Issue by karmux** [LMMS/lmms#2431]
When in Beat+Bassline editor double clicking on piano roll doesn't do anything. When in song editor view then it's possible to double click into piano roll. To go from B+B to piano roll I have to use right click menu. Has been issue for some time already in master.

**Comment by tresf** [comment]
Thanks.  This was introduced with https://github.com/curlymorphic/lmms/commit/6ad5d88c086adb47c4019b3f7794bbbf0d8751bd but the fix is trivial.  Patching now.

**Comment by karmux** [comment]
That was quick! Thanks!
