### ISSUE TITLE
Triple oscillator: fixing pop-up indications

### ISSUE THREAD

**Issue by GNUMariano** [LMMS/lmms#2435]
Hi everyone! I've noticed this:

The helping tips on 3xOsc indicate (on the PM, AM, MIX, SYNC, FM buttons):
 _"Use phase modulation for modulating oscillator 2 with oscillator 1"_
_"Use amplitude modulation for modulating oscillator 2 with oscillator 1"_
_"Use frequency modulation for modulating oscillator 2 with oscillator 1"_
etc...

When actually **Osc 2 is the modulator, and Osc 1 is the carrier**. It's the same for Osc 2 + Osc 3. 
I know it's a minor issue but it puzzles new users, specially those who are just learning how to program a synthesizer. I love Triple Osc, it's a great synth. I hope we can fix that and add some extra help for newbies!

Thanks. All comments are welcome!
![pop-up](https://cloud.githubusercontent.com/assets/15054164/10893995/a67968a2-818a-11e5-9c47-44a32445eb56.png)

**Comment by midi-pascal** [comment]
@GNUMariano Unless you want to do it yourself I volunteer to fix the source code and the French translation file as well. Let me know.

**Comment by GNUMariano** [comment]
Thanks @midi-pascal ! 
I've just finished translating LMMS completely to Spanish and I think it would be nice to get this fixed so I can also do so in the Spanish translation too. I'm new in Github and still don't know how to proceed. @tresf has been very helpful, and we're discussing this here: https://github.com/LMMS/lmms/pull/2359#issuecomment-146951642 
If you could fix the source I'll do the same with the Spanish translation (by now I translated it "as it is" till the source is fixed). I'm waiting for this before sending the reviewed translation.
Thanks again!

**Comment by midi-pascal** [comment]
@tresf Should I fix this in stable 1.1 or in master branch - or both -?

**Comment by tresf** [comment]
@midi-pascal I'd recommend master only.

**Comment by midi-pascal** [comment]
@tresf Fine :+1:

**Comment by Umcaruje** [comment]
The fix is here: #2527 

@midi-pascal @GNUMariano when its merged, you can fix the translations.

**Comment by midi-pascal** [comment]
For sure I will! :smile:

**Comment by GNUMariano** [comment]
That's good news. I'll be glad to fix the Spanish translation.
Thank you!

2016-01-28 21:12 GMT-03:00 midi-pascal <notifications@github.com>:

**Comment by midi-pascal** [comment]
@tresf Should I open a new issue for the fix of the French translation file related to this issue?
The fix is ready :smile:

**Comment by tresf** [comment]
> Should I open a new issue for the fix of the French translation file related to this issue?
The fix is ready

PRs are plenty for translations without a separate bug report, in my opinion. :+1:

**Comment by midi-pascal** [comment]
@tresf @GNUMariano French translation updated (PR #2544)

**Comment by GNUMariano** [comment]
Hi @tresf @midi-pascal  I want to update the Spanish translation, so I cloned both the master and stable and compiled both of them. The source is fixed in the masterbranch but not in stable. 
Which file should I use (es.ts from stable or es.ts from master)?
Should I upload both of them?

**Comment by midi-pascal** [comment]
@GNUMariano As long as I am concerned I modified only the master branch since version 1.2 is about to be released from it. It will be the next stable soon. But @tresf has the last word :wink:

**Comment by GNUMariano** [comment]
Thanks @midi-pascal , I'm working on the master branch too, (it has about 200 more lines to translate) and I guess that's the file to update. But since I'm new at this, I need your advise.
Thanks for the reply, I'll add a commit to update the Spanish translation in a few days :)

**Comment by IvanMaldonado** [comment]
@GNUMariano Count with me for any help you need :+1:

**Comment by GNUMariano** [comment]
@IvanMaldonado thank you! Sorry for the late reply (I was ill...) But now I'm into it, it'll be done by this weekend. I'll ask if in doubt of something. Luckily you can revise it soon and merge it soon. 
Thanks for the help!

**Comment by GNUMariano** [comment]
Hello! I added a commit #4668f57 with the full translation to Spanish.
@IvanMaldonado there are two lines I couldn't translate ('hp grp' and 'lp grp'. I guess 'hp' stands for 'high pass' and 'lp' stands for 'low pass' but I can't figure out what 'grp' stands for.).
Sometimes the translated sentences are too long (ej: my presets == mis preconfiguraciones, etc) maybe I must abbreviate this like "mis preconf"?
I've compiled the masterbranch (By the way, it looks awesome and works fine, it only crashes from time to time. Great job everyone! 1.2 is around the corner, thanks!) But some sentences still appear in English although they are translated.
Also I got this warning "translation does not refer to the same place markers as in the source text." in two or three lines.
I've translated 'duty-cycle' as 'ciclo de trabajo' but it can also be translated as 'ciclo de vida'.
The Language selection works great, it'll be very useful for Spanish speakers that are used to English names (And _That_ is very common!).
Let me know if I can improve it in any way.
Thanks!

**Comment by zonkmachine** [comment]
> there are two lines I couldn't translate ('hp grp' and 'lp grp'. I guess 'hp' stands for 'high pass' and 'lp' stands for 'low pass' but I can't figure out what 'grp' stands for.).

'grp' is short for group. It's the Hi/Lo pass selection buttons (12dB, 24dB and 48dB) under numbers 1 and 8 in the equalizer.

**Comment by GNUMariano** [comment]
Thanks @zonkmachine ! I'll mantain 'grp' in the translation ('group' in Spanish == 'grupo' so it works both ways!!). Now the translation is complete!

**Comment by IvanMaldonado** [comment]
@GNUMariano Is "Mis preconfiguraciones" intended to be here? because I feel there's enough space to be this way.

![captura de pantalla_2016-03-11_17-56-27](https://cloud.githubusercontent.com/assets/12549082/13718756/9cf20b16-e7b2-11e5-89f4-314c349adf8b.png)

**Comment by GNUMariano** [comment]
@IvanMaldonado Yes! There is enough space, but in 4:3 monitors it appears truncated ("Mis Preconfiguraci"). Yet you can resize  that panel till it appears complete, so I guess it'll be OK. 

BTW I added a commit a few days ago. Is there anything else I can do to help getting the translation merged?

**Comment by tresf** [comment]
> BTW I added a commit a few days ago. Is there anything else I can do to help getting the translation merged?

Probably best to ask in the relevant, open PR.  BTW, commits don't trigger any notifications to admins or @mention's, so if you ever add a commit to a PR and want peer or admin review, you have to bump it with a comment. :+1:

**Comment by GNUMariano** [comment]
Thanks @tresf I'll do so.
BTW I've read the topic on Transifex, is this going to change the way we [must] work on the translations? 
PS: I've noticed I'm posting on a closed topic, maybe I shoud ...?

**Comment by tresf** [comment]
> BTW I've read the topic on Transifex, is this going to change the way we [must] work on the translations? 

Great question.  @liushuyu is the person to ask, but in short, yes. :+1:

**Comment by GNUMariano** [comment]
Thanks, I'll ask him. About the PR I've noticed that it's closed. Should I open a new pull request commenting that commit?

**Comment by tresf** [comment]
I'm still not sure which PR you're talking about.

**Comment by liushuyu** [comment]
>BTW I've read the topic on Transifex, is this going to change the way we [must] work on the translations?

Well, in this case, you can feel free to contact me by email, Hangouts, or Telegram. Or you can comment on the closed thread.

**Comment by GNUMariano** [comment]
@liushuyu thank you. I'll do it!
