### ISSUE TITLE
add effect from fx tab freeze.

### ISSUE THREAD

**Issue by tecan** [LMMS/lmms#2437]
tried with both sf2 and triple oscillator causes freeze not sure if its improper plugins or paths maybe someone can reproduce.

**Comment by Umcaruje** [comment]
Hi, please provide more information on this problem with steps to reproduce and a backtrace if you can.

**Comment by Umcaruje** [comment]
No response in over a month, closing.

**Comment by gh2o** [comment]
Just a heads up to passerbys: if any of your directories in Edit -> Settings -> Directories is set to your home directory or any other directory with a lot of files, LMMS will appear to freeze as you click Add Effect as it searches that directory for plugins. Either clear the directory field or point it to a proper directory.
