### ISSUE TITLE
Shutdown memory error message when using "Dummy"

### ISSUE THREAD

**Issue by M374LX** [LMMS/lmms#2441]
As said in #2376, when using the "Dummy" audio device, the following error message is show at the program's shutdown:
``*** Error in `lmms': free(): invalid size: 0x00000000020169b0 ***``

Here is what happens, which may be related to this problem:
1. By calling `Mixer::stopProcessing()`, the FIFO writer is stopped and deleted (audio devices, as opposed to audio file devices, typically use `Mixer` with the FIFO writer).
2. The audio device (Dummy), still running, calls `Mixer::nextBuffer()` which now renders a new buffer without the FIFO writer, but it looks like something goes wrong.

**Comment by zonkmachine** [comment]
This is fixed in #2793
