### ISSUE TITLE
segfault error with master branch 2015/11/17 on Debian Jessie 64bits

### ISSUE THREAD

**Issue by rawthought** [LMMS/lmms#2447]
Hi, I just compiled lmms master and I get a segfault error.

When I launch it without jack it gives me this :
```bash
me@mine:/opt/lmms-master/bin$ ./lmms
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jackdmp 1.9.10
Copyright 2001-2005 Paul Davis and others.
Copyright 2004-2014 Grame.
jackdmp comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details
no message buffer overruns
no message buffer overruns
no message buffer overruns
JACK server starting in realtime mode with priority 10
self-connect-mode is "Don't restrict self connect requests"
audio_reservation_init
Acquire audio card Audio1
creating alsa driver ... hw:io2,0|hw:io2,0|512|2|96000|0|0|nomon|swmeter|-|32bit
configuring for 96000Hz, period = 512 frames (5.3 ms), buffer = 2 periods
ALSA: final selected sample format for capture: 24bit little-endian
ALSA: use 2 periods for capture
ALSA: final selected sample format for playback: 24bit little-endian
ALSA: use 2 periods for playback
JackEngine::XRun: client = lmms was not finished, state = Running
JackAudioDriver::ProcessGraphAsyncMaster: Process error

[...] (Mod edit: the message repeats a lot)

JackEngine::XRun: client = lmms was not finished, state = Triggered
JackAudioDriver::ProcessGraphAsyncMaster: Process error
JackEngine::XRun: client = lmms was not finished, state = Triggered
JackAudioDriver::ProcessGraphAsyncMaster: Process error
Erreur de segmentation
me@mine:/opt/lmms-master/bin$ Unknown error...
terminate called after throwing an instance of 'Jack::JackTemporaryException'
  what():
```

And then I have to enter "ctrl+c" to get my prompt back.

When I launch it with jack previously started I get this :

```
me@mine:/opt/lmms-master/bin$ ./lmms
Erreur de segmentation
```

PS : I've tried to change my terminal langage to english with "export LANG=en_GB.UTF-8" but I still get the french message "Erreur de segmentation" instead of "segfault error".
PS2: my soundcard is a Alesis IO2 Express.
I have not seen any particular problem with it on GNU/Linux and it used to work well with LMMS.

**Comment by grejppi** [comment]
Could be anything. We can't know without a [backtrace](https://github.com/LMMS/lmms/wiki/Debugging-LMMS).

**Comment by rawthought** [comment]
Hello,
Sorry for haven't given more details, in fact I haven't succed to get any informations from gdb because the text was printing very fastly on the screen and I have'nt managed to output it in a file.
(I am not a developper, I'm just curious and fan of LMMS...)

By the way, LMMS seems to start normaly now, so I think the ticket can be closed.

**Comment by Umcaruje** [comment]
:+1: If this problem resurfaces, and if you are able to grab a backtrace, feel free to reopen this issue.

**Comment by rawthought** [comment]
thx
