### ISSUE TITLE
Knobs in some plugins have their indicator rotate around the top-left corner instead of knob centre.

### ISSUE THREAD

**Issue by FLamparski** [LMMS/lmms#2449]
![screenshot from 2015-11-18 21-51-44](https://cloud.githubusercontent.com/assets/912935/11255582/ed6d596a-8e3e-11e5-8aa0-1ba51d4265bc.png)
![screenshot from 2015-11-18 21-50-53](https://cloud.githubusercontent.com/assets/912935/11255583/eefdf33e-8e3e-11e5-9dba-d37e602b375a.png)
![screenshot from 2015-11-18 21-55-53](https://cloud.githubusercontent.com/assets/912935/11255627/28adc028-8e3f-11e5-9989-8cb24a7b71b1.png)
![screenshot from 2015-11-18 21-56-26](https://cloud.githubusercontent.com/assets/912935/11255642/3bdee492-8e3f-11e5-8996-aa51220028a5.png)
![screenshot from 2015-11-18 21-57-19](https://cloud.githubusercontent.com/assets/912935/11255662/5bc68ca6-8e3f-11e5-9f61-7726c16c99ed.png)
![screenshot from 2015-11-18 21-58-02](https://cloud.githubusercontent.com/assets/912935/11255680/746f78ee-8e3f-11e5-9434-2a40fdb8701d.png)

Watsyn is hard to see but the bug does occur

![screenshot from 2015-11-18 21-59-39](https://cloud.githubusercontent.com/assets/912935/11255732/b556addc-8e3f-11e5-9283-b0b414be1b6e.png)

```
$ git rev-parse --short HEAD
3e03e71
$ ./lmms --version
LMMS 1.1.3-g3e03e71
(Linux x86_64, Qt 4.8.6, GCC 5.2.1 20151010)
```

**Comment by tresf** [comment]
This generally occurs when LMMS is using the wrong theme folder, which is common when multiple versions are installed.

Please open LMMS preferences and delete the path pointing to the theme directory, and it should reset to the current version.  Another fix is to simply move the `~/.lmmsrc.xml` file which will have the same effect, but will reset all LMMS settings.

**Comment by FLamparski** [comment]
Ah. Any way to have LMMS indicate that themes are broken?

**Comment by tresf** [comment]
We do it currently actually, but the version must change (master is labeled as 1.1.3, so the check fails).

https://github.com/LMMS/lmms/issues/1412

**Comment by FLamparski** [comment]
Alright, closing
