### ISSUE TITLE
Organic Knobs Display Incorrect Tooltips

### ISSUE THREAD

**Issue by jackokring** [LMMS/lmms#2459]
Top two rows of knobs display %1 instead of oscillator number.

**Comment by tresf** [comment]
The title should read "Organic Knobs Display Incorrect Tooltips"

Description is pretty good, although it wouldn't hurt to add a screenshot of the problem. :+1:

**Comment by jackokring** [comment]
Done

**Comment by tresf** [comment]
Thanks.  Now about fixing this thing... Assuming you want to get your hands dirty, is this something you think you can tackle?  We're here to help.

**Comment by jackokring** [comment]
https://github.com/LMMS/lmms/blob/master/plugins/organic/organic.cpp

```line 560 to 563, no .arg( <stuff> ) ```

**Comment by tresf** [comment]
Ok, you've found the line. :smile: How familiar are you with `git`?  https://github.com/LMMS/lmms/wiki/Submitting-a-patch

**Comment by jackokring** [comment]
Well I've used it on cloned repos. The merge down usually is lots of copy and paste from my use. Never need to issue a pull, as this was sent via other channels.

**Comment by jackokring** [comment]
So I've sent a pull request (hopefully), I had to rename a branch, make a branch, delete back to the 1.1, and add the edit. But it is a 2 line edit. Hope this worked OK, ...

**Comment by tresf** [comment]
@jackokring thanks for the PR.  We didn't make this obvious, but we're targeting the master branch for everything currently as we prepare for the `stable-1.2` branch.  We have no intentions on working on the `stable-1.1` branch, so please re-base your changes against master (close out the `stable-1.1` PR and issue a new PR for `master`).

Also, some of your peak controller changes made it into that PR.  I'd recommend cloning master into a new branch prior to issuing the PR, that way you can work on one branch per feature/fix.

-Tres

**Comment by jackokring** [comment]
I couldn't get the master to compile, as there were missing correct Cmake files giving errors indicating Qt4 was not found.

**Comment by tresf** [comment]
@jackokring if there is a compilation problem with master, file a bug please (or just post the message here if you'd like).   We have Travis showing successful builds on QT4, QT5, Windows 32-bit, Windows 64-bit, Mac, so I have the feeling your issues are isolated to your environment, but we're here to help. :+1:

**Comment by jackokring** [comment]
The build is going now 6%, so I assume as all I have done since yesterday is add package qt5-default, then this must be it.
