### ISSUE TITLE
Volume and pan knobs with decimals?

### ISSUE THREAD

**Issue by Sti2nd** [LMMS/lmms#246]
When I use left mouse button to adjust the knob it visits 0.1-0.9 before next whole number.

Not sure how much I like this as I rarely use the decimals, only for automation I guess. This probably arrived as a solution to of those who has no middle mouse button? The middle mouse button still works though. I suggest that Shift + Drag could be the fine adjustment.

**Comment by Sti2nd** [comment]
Now that I think about it, this behavior seems wrong. LMMS previously worked so that you could fine adjust with middle mouse button.

LMMS had three alternatives of adjusting a knob
- Drag with left mouse button (adjusts on a higher level)
- Scroll with mouse wheel (fine adjust)
- Double click and enter the exact number you want

https://github.com/LMMS/lmms/pull/77 Now with this code some knobs are behaving like if you scrolled the mouse wheel on top of them all the time, but Faders and the Sample track knob are for example not behaving that way. I know @andrewrk wanted the knobs to feel smoother, which he achieved (probably by turning off the magnetic effect), but I don't understand why one would ruin the logic, cause **it is not more precise**. You could achieve this just as easily before. Neither is it faster in my experience, cause you often use longer time to get to where you want the knob to be, and then it is not so easy to fine adjust either.

Proposal: Allow two different modes on knobs like before.
- Drag with left mouse will go through a volume and pan knob as integers
- Scroll with mouse wheel and Alt + drag on knob will go through as decimals

**Comment by diizy** [comment]
On 01/20/2015 10:04 PM, Stian Jørgensrud wrote:
>
> Now that I think about it, this behavior seems wrong. LMMS previously
> worked so that you could fine adjust with middle mouse button.
>

What? No it didn't. It's shift (hold shift after clicking on the knob)
and it still works just the same as always.

**Comment by Sti2nd** [comment]
> What? No it didn't. It's shift (hold shift after clicking on the knob)
and it still works just the same as always.

It did. I just installed 0.4.15 and confirmed I were right. You are right too, you can do the same with Shift. So I really don't see any benefits in the decimals on normal drag.

**Comment by diizy** [comment]
On 01/20/2015 10:22 PM, Stian Jørgensrud wrote:
>
>     What? No it didn't. It's shift (hold shift after clicking on the knob)
>     and it still works just the same as always.
>
> It did. I just installed 0.4.15 and confirmed I were right. You are
> right too, you can do the same with Shift. So I really don't see any
> benefits in the decimals on normal drag.
>

I don't see any benefits in not having the decimals...

They're just numbers. There's no reason why you'd actually need to
constrain the volume to integers. Integer volumes don't behave any
differently from other volume amounts...

**Comment by Sti2nd** [comment]
> I don't see any benefits in not having the decimals...

Please, let me

1. It is faster (to set the knob where you want). Why? Try to move your mouse slowly, you obviously have to scroll for a longer time with decimals than if the values had been integers.
2. It is easier (to set the knob where you want). Why? Cause you are more likely wanting to set the knob 50% down, than 50.3%.

**Comment by andrewrk** [comment]
Have you tried my suggestion yet?

> Perhaps we should simply adjust the smoothness ratio from 1/8 to 1/4 or so?

You can adjust this number to a compromise between precision and ability to quickly change the knob's value. I think that I perhaps leaned too far toward the precision side when I first guessed the ratio to use.

**Comment by Sti2nd** [comment]
@andrewrk If you drag slower with your mouse, will the scrolling be logarithmic slower or is it linear?

> Perhaps we should simply adjust the smoothness ratio from 1/8 to 1/4 or so?

If you do that and it is going to be even harder to select the decimals by just dragging (linear), then it is even less points in having the decimals?

**Comment by diizy** [comment]
On 01/20/2015 10:36 PM, Stian Jørgensrud wrote:
>
>     I don't see any benefits in not having the decimals...
>
> Please, let me
>
>  1. It is faster (to set the knob where you want). Why? Try to move
>     your mouse slowly, you obviously have to scroll for a longer time
>     with decimals than if the values had been integers.
>

Incorrect. The step size plays no part in the speed of the knob. The
same movement will move the knob by 10%, no matter if the step size is
1.0 or 0.1.

>  1. It is easier (to set the knob where you want). Why? Cause you are
>     more likely wanting to set the knob 50% down, than 50.3%.
>

Are you really though? Why, what's so special about 50%? Why is 50%
inherently more desirable than 50.1% or 49.9%? There's no difference in
quality of DSP whether the value is integer or not.

For that matter, shouldn't you be listening to the actual sound output,
and setting the value where it sounds good, rather than aim for some
arbitrary value?

**Comment by diizy** [comment]
On 01/20/2015 10:39 PM, Andrew Kelley wrote:
>
> Have you tried my suggestion yet?
>
>     Perhaps we should simply adjust the smoothness ratio from 1/8 to
>     1/4 or so?
>
> You can adjust this number to a compromise between precision and
> ability to quickly change the knob's value. I think that I perhaps
> leaned too far toward the precision side when I first guessed the
> ratio to use.
>

I've completely rewritten the knob smoothing code since that suggestion
(pre-1.0) because it had broken the AFP knobs and had to be implemented
differently, so that suggestion probably isn't relevant anymore...

**Comment by Sti2nd** [comment]
> For that matter, shouldn't you be listening to the actual sound output,
and setting the value where it sounds good, rather than aim for some
arbitrary value?

Yes, so how much change can 0.1% really be, a.k.a be necessary? And if it does you can easily make it happen with the way I am proposing. You could introduce yet another 9 decimals and use the same arguments you do... What you are debating for are unnecessary decimals, and that I simply do not understand.

**Comment by badosu** [comment]
@Sti2nd If you want exact numbers why don't you use the double click functionality?

My only problem currently is that you can't use the double click parameter assignment with VST's or zynaddsubfx.

**Comment by diizy** [comment]
On 01/20/2015 11:27 PM, Stian Jørgensrud wrote:
>
>     For that matter, shouldn't you be listening to the actual sound
>     output,
>     and setting the value where it sounds good, rather than aim for some
>     arbitrary value?
>
> Yes, so how much change can 0.1% really be, a.k.a be necessary?
>

How much? Depends on where you start. Volume is logarithmic... In the
top end, 0.1% is negligible. In the bottom end, it can be huge.

In fact, for accurate adjustment for the low end, 0.1% is actually
inadequate... hence why we're moving to dBV controls.

> And if it does you can easily make it happen with the way I am
> proposing. You could introduce yet another 9 decimals and use the same
> arguments you do... What you are debating for are unnecessary
> decimals, and that I simply do not understand.
>

Unnecessary? For you maybe, and no one forces you to use them. But they
are maybe necessary for others.

This whole thing just seems like pointless griping, unless you can give
at least one good reason why you want volumes snapped to integer values.
Do you expect a visit from the mixer inspector and want to make
everything look tidy? Are you trying to align your FX faders in some
kind of numerological pattern? Or what? I'm struggling to find a
rational reason why one would want to use integer values but not the
ones in between...

**Comment by Sti2nd** [comment]
> I'm struggling to find a
rational reason why one would want to use integer values but not the
ones in between..

I've already told you it is faster. Before you could go to 130% like in second (by dragging), now I (and everyone) use almost more than two to reach 130.0%. And this doesn't mean I won't turn it to 130.1% with the mouse wheel afterwards, or later when listening, so it doesn't mean I won't use the values in between, they are just as accessible as before. I surrender, though, I hadn't thought about that you actually loose precision with integers because it is logarithmic. It all makes sense now, the percentage confused me :)

> If you want exact numbers why don't you use the double click functionality?

You are probably right, I should start doing that. I am used to listen and dragging at the same time which worked like a charm and was fast, and then landing on integers of course. Diizy is right though, the volume knobs are logarithmic so the decimals aren't as redundant as I claimed.

Thank you for answering! Now I can defend the decimals, and stop wondering why it isn't like before.

**Comment by badosu** [comment]
@Sti2nd Cool! :-) We sure want to improve the UI, I am certain that there is a better way to satisfact your urge, but it's not clear yet.

**Comment by Sti2nd** [comment]
I look forward to when they are in db. I think I will like that (even with decimals) much better :)

And just discovered that I hadn't read your whole reply.
> Do you think a sticky behaviour onto integers would be a solution? I'd not like to have decimals removed.

No of course no decimals are going to be removed, they would still be accessible with mouse wheel/shift + drag and through double clicking.

**Comment by diizy** [comment]
On 01/20/2015 11:49 PM, Stian Jørgensrud wrote:
>
>     I'm struggling to find a
>     rational reason why one would want to use integer values but not the
>     ones in between..
>
> I've already told you it is faster.
>

And I told you you're incorrect. Step size plays no part in speed of the
knob.

> Before you could go to 130% like in second (by dragging), now I (and
> everyone) use almost more than two to reach 130.0%.
>

Maybe you should adjust your mouse settings. The speed of the knob
accelerates exponentially if you move it faster. In any case, any speed
difference is entirely unrelated to the knob's step size. You can see it
for yourself - open up some LADSPA plugin where you have controls with
different step sizes.

> And this doesn't mean I won't turn it to 130.1% with the mouse wheel
> afterwards, or later when listening, so it doesn't mean I won't use
> the values in between, they are just as accessible as before.
>

So why do you need to move it to 130 in the first place?

> I surrender, though, I hadn't thought about that you actually loose
> precision with integers because it is logarithmic. It all makes sense
> now, the percentage confused me :)
>

You lose precision when you reduce precision. That's fairly obvious,
isn't it? And no, the controls are not logarithmic (yet). That's the
problem though, because volume itself is logarithmic, it's how sound
works. That's why most audio softwares use dBV controls, it's a
logarithmic scale.

What I mean is this: If you move from 100% to 99%, that's only a -0.08
dBV change. But if you move from 1% to 2%, that's a +6 dBV change. In
both cases, the difference in linear units (%) is the same, 1%, but at
the low end, the actual perceived difference is much larger (6 vs 0.08).
So at the low end, we need higher precision - at least until we can
convert the knobs to work in dBV units.

**Comment by diizy** [comment]
... We could just change the knobs from percent to permille, then you'd
have your integers ;)

http://en.wikipedia.org/wiki/Per_mille

**Comment by Sti2nd** [comment]
> We could just change the knobs from percent to permille

Hehe.. Nah, I'm fine. 

> the controls are not logarithmic

My bad, the sound is, yes. You will tweak the sound linearly with db knobs, right?

**Comment by diizy** [comment]
On 01/21/2015 12:10 AM, Stian Jørgensrud wrote:
>
>     We could just change the knobs from percent to permille
>
> Hehe.. Nah, I'm fine.
>
>     the controls are not logarithmic
>
> My bad, the sound is, yes. You will tweak the sound linearly with db
> knobs, right?
>

With dBV knobs, the scale is in dBV. You move from -120 dBV to -119 dBV,
the difference is +1 dBV. You move from +0 dBV to +1 dBV, the difference
is +1 dBV. So the precision is constant accross the scale, unlike with
percentages where the precision is much lower at the low end.

With dBV knobs, we can still use linear knobs, because the scale itself
is logarithmic, so the knob movement doesn't have to be logarithmic
"again".
