### ISSUE TITLE
OpulenZ crash

### ISSUE THREAD

**Issue by jackokring** [LMMS/lmms#2463]
![screenshot from 2015-11-24 15 18 41](https://cloud.githubusercontent.com/assets/594069/11371135/e003fec6-92be-11e5-9255-cbe85d6665d6.png)

I was starting this baseline, all 4 of the Opulez bar notes were filled, I fiddled with some controls on Opulez, and after about a minute a crash happened (the music was not as sychronized as it sounds now after a session recovery), the Opulenz was very non synchronus in timbre. There is one LFO controller in operation on the Opulenz note, and the kicker note.

**Comment by jackokring** [comment]
The controller disconnected itself from the note (keyboard mod), and the last two bar notes were not restored. I reconnected LFO, and got the inharmony back, but then disconnected it again, and got harmony with a tonal drone which will not stop. It's been going for a few minutes now. There is no post envelope with this instrument.

**Comment by jackokring** [comment]
```c
// Pop least recently used voice
int opl2instrument::popVoice() {
	int tmp = voiceLRU[0];
	for( int i=0; i<8; ++i) { /* NB ERROR HERE note max not constant 8 OPL2_VOICES !!!!
		voiceLRU[i] = voiceLRU[i+1];
	}
	voiceLRU[8] = OPL2_NO_VOICE;
#ifdef false
	printf("<-- %d %d %d %d %d %d %d %d %d \n", voiceLRU[0],voiceLRU[1],voiceLRU[2],
	       voiceLRU[3],voiceLRU[4],voiceLRU[5],voiceLRU[6],voiceLRU[7],voiceLRU[8]);
#endif
	return tmp;
}
```

**Comment by jackokring** [comment]
As an aside is the author looking for a note culling algorithm for replacing the LRU anyway? As the notes indicate so. https://github.com/jackokring/aceb/blob/master/src/com/github/jackokring/aceb/Audio.java is some Java code with my ideas on a simple audio tracker.

**Comment by grejppi** [comment]
What is the issue here? Crash? Something with OpulenZ? Controllers?

And if LMMS crashes, provide a [backtrace](https://github.com/LMMS/lmms/wiki/Debugging-LMMS) first -- speculate later.

**Comment by softrabbit** [comment]
> There is no post envelope with this instrument.

Right. There are two kinds of instruments in LMMS, the multi-stream ones that render their notes separately and thus can have envelopes and filters applied to them, and the single-stream ones (at least Opulenz, Vestige, ZynAddSubFx) that get MIDI in and return one audio stream that's already mixed down.

> I think the Opulez has a bug.

Wouldn't be surprised. OTOH, it could be a case of LMMS dropping the note off command, in which case the blame is somewhere else.

> is the author looking for a note culling algorithm for replacing the LRU anyway?

No, not really. But if you want to implement one, nobody's stopping you. Now the logic goes _"If there are free voices, use the one that's been idle for the longest time. If there aren't, ignore the note on."_, IIRC. 

> This whole file needs searching for constant 8 dependacies, and the header too.

True, and don't forget the nines.

**Comment by jackokring** [comment]
Clarification: The LFO controller assigned to green dot above keyboard, large number of notes triggered, (or mouse select the keyboard and wiggle generating a sweep of notes for quite a few minutes), had no problem with any other machine I've tried. Implication Opulenz is not cancelling some notes. Now I assume in good faith there is no ```if(Opulenz) { forgetNoteOff(); }``` and so the implication is a fault in Opulenz.

**Comment by jackokring** [comment]
Not crashed yet after a few minutes, but I have notice if I quickly mouse tap a high note, I can get it to stick very occasionally.

**Comment by jackokring** [comment]
https://dl.dropboxusercontent.com/u/1615413/Own%20Work/J-00.mmpz and quickly tap using mouse in spurts of about 4 or 5 clicks with a gap the C7 note on keyboard. And I'm wondering if the next song version down is J--1.

**Comment by Umcaruje** [comment]
@jackokring Stop spamming the thread or I'll lock and close it. When you figure out the steps to reproduce and give us a backtrace, please put them in your original post. Its really hard to track a problem if you keep posting off-topic comments on the issue.

**Comment by Umcaruje** [comment]
I'm going to close this issue. Once the OP provides concise steps to reproduce this issue can be reopened.
