### ISSUE TITLE
TheMaster.xpf TripleOscillator preset is silent.

### ISSUE THREAD

**Issue by karmux** [LMMS/lmms#2468]
Also, if OSC1 + OSC2 and OSC2 + OSC3 are both either PM or AM in any combination, TheMaster.xpf preset stays silent (couldn't find other preset that is silent in these combinations). Tested with current master.

**Comment by softrabbit** [comment]
Osc1 has a user defined waveform, guessing it isn't loaded from the file as I get sound after clicking the question mark and loading the pre-selected file. #2412 behaved in a pretty similar way.

**Comment by musikBear** [comment]
x32 winxp
fyi, this preset *has *sound in Master14/7, In all Matrix combos, *with* the user-defined-sound on OSC1
-Eg this issue occurred later that 14/7  

(The Master of 14/7 is also btw really stable.  It would not be a bad piont-of-entrance, in case a roll-back is inalienable, alas )

**Comment by karmux** [comment]
First time when I click + sign in OSC 1 of TheMaster it opens folder with **shapes** from second time on it opens folder with **waveforms**. If I select some shape or waveform, it starts to make sound.

**Comment by musikBear** [comment]
Pfffh.. :confused: 8|  *Now* its silent again - Change the PM-modulation of osc1+osc2 away from PM/AM and its 'on' again

**Comment by softrabbit** [comment]
Works now, file loading was fixed in https://github.com/LMMS/lmms/commit/ca8f80d44f9690fdf7a42da1307ed68b0b2f45ae.
