### ISSUE TITLE
Bar display breaks after 999th bar

### ISSUE THREAD

**Issue by unfa** [LMMS/lmms#2469]
![bars over 999](https://cloud.githubusercontent.com/assets/491704/11442727/1839fe5c-9518-11e5-99be-04143a42fc24.png)
The extra digit appears, but the objects to the right aren't shifted so the final digit is unreadable.

**Comment by Wallacoloo** [comment]
Hmm. So we can either make the bar display permanently larger, have it grow on-demand, or cap the display at "999:4:47" (or whatever the exact limit is).

The last option is most likely the easiest patch, but also the least useful.

I think both other options are doable though. Looking at the Time Sig display, we have 2 digits there, and 3 digits for tempo, so I don't think the graphics are done in a way that would prevent us from setting up a 4-digit readout.

I don't like the idea of the display expanding on-demand. Unless we complicate the layouting, that would cause all UI components downstream to be bumped over at the instant the display expands, which is problematic if the user is currently using any of those components. 

The tick field only seems to go up to 47, and I've never heard of someone using a time signature with more than 99 beats in a bar. **I propose we shrink Beat & Tick to only have 2 digits each and expand Bar to have 4 digits**. I imagine that proportionality would look OK. If that sounds good, I can look into implementing this.

**Comment by tresf** [comment]
Can we just truncate the string?  What would 0001 harm?

**Comment by Wallacoloo** [comment]
@tresf "truncate the string" as in "show `001` (3 digits) when the actual bar is `1001`"?

**Comment by tresf** [comment]
Yes.

**Comment by Wallacoloo** [comment]
@tresf IMO, that's a bit misleading - 200:4:1 could mean bar 200 or bar 1200 (or 2200, ...) for a lengthy song, so the readout can't be trusted. I agree it's better than the *current* visual error, but if want to stick with 3 digits, I think capping it at 999 is more useful. In that way, bars 1-998 are shown correctly with no ambiguity (e.g. 023 means bar 23, never bar 1023) and it's made obvious to the user when the bar has overflowed.

**Comment by Spekular** [comment]
If we're ok with capping at 999 (which I don't like) we should instead use
suffixes. It would then be perfect up to 999 (as opposed to 998) and would
be less precise but still useful afterwards.

999->1K (for 999 bars)->2K
999->10H (for 99 bars)->11H
It's not possible to use Deca unless the bars field is expanded to four
numbers, but at that point I doubt anyone will hit the limit either way.

**Comment by softrabbit** [comment]
> The tick field only seems to go up to 47

The ticks can go to 191 if the time signature denominator is 1 (i.e. a whole note). If the tick resolution increases 3 digits will be even more common. 

> and I've never heard of someone using a time signature with more than 99 beats in a bar.

Looks like LMMS maxes out at 32/32 for now.

At 180 BPM in 4/4 time 1000 bars is 22 minutes. That makes the wraparound problem rare enough that simple truncation is OK by me, it's not like you can't glance at the song editor to see where the play head is. But shrinking the middle box and expanding the left one is fine, too.

The third option, proposed by @Spekular, no. I don't see the point in that, really. It's less accurate and confusing to the user.

**Comment by Wallacoloo** [comment]
Alright. Thanks for sharing those technical details. I'm fine with doing a
truncation approach whereby we show the 3 least significant digits (i.e.
998->999->000->001). It sounds like there's consensus there :+1:

**Comment by Spekular** [comment]
@softrabbit I only mentioned suffixes as a better alternative to capping at
999, in which case it's a better option. Obviously just expanding to four
numbers is better from an accuracy and range standpoint.
