### ISSUE TITLE
disorder tracks when i clone a track

### ISSUE THREAD

**Issue by djchals** [LMMS/lmms#2470]
Hi!

I'm using LMMS version 1.1.3 with a real synthesyzer connected by midi usb interface.

I found a bug:

When I clone a track and i made a changes after and save and close the program, When i open again LMMS and open the project, the content of the below tracks is disordered and mixed, and destroyed the song :( And I must create other time the content for these.

![lmms1](https://cloud.githubusercontent.com/assets/16034655/11443714/91254126-951f-11e5-80a1-1e86d1014d9b.png)

**Comment by musikBear** [comment]
@djchals Does this change if you do *not* connect your keyboard at all?
could you **dis-connect** the kb. **Restart the pc**, and **retry** if the bug appears. Then any relation to externals could be excluded.

**Comment by djchals** [comment]
I made this change with the synthesyzed is off:
I'm using the version 1.1.3 

I attach two files. 
This is before i clone a track 
http://www.webfutura.es/carlos/new gen9.mmpz

This is after i clone the track
http://www.webfutura.es/carlos/new gen9CORRUPT.mmpz

If you opens the bassline editor in the below tracks the content is changed in the corrupt file.

**Comment by musikBear** [comment]
Hi -i took a look at your files, and you are using the drum-synth kicker for all instruments. That is fundamentally wrong.
What i will ask you to do is to read and work through this section of the wiki:
https://lmms.io/wiki/index.php?title=Your_First_Song_with_LMMS
If you run into problems, do *not* open a ticket here. Direct all questions here:
http://lmms.io/forum/viewforum.php?f=7
a lot of peeps will be happy to help you learn how to use lmms, in there. :)
I could btw not reproduce the fail you described here.

**Comment by michaelgregorius** [comment]
@musikBear The kickers in the example confused me as well but then I remembered that @djchals is using an external synth so he might no care what is triggering the notes. Therefore I assume that he knows how to use LMMS.

I think this issue is likely a duplicate of #2277. However, I was not able to reproduce the problem in both cases. Can anyone please provide an example file that is as simple as possible with precise steps on how to corrupt this file? It would also be great if the non-corrupt file would produce something recognizable so that one instantly notices when something is wrong. Thanks!

**Comment by tresf** [comment]
> If you run into problems, do not open a ticket here.

If his tracks were saved out of order, that is a bug.   The rest of your advice is speculative.

**Comment by djchals** [comment]
Hi! 

Yes, i'm using a external synth with midi interface i muted the pc sound when i play a song.

I recorded the error in this video:
https://www.youtube.com/watch?v=xTinXAP7G74&feature=youtu.be

Regards and thanks ;)

**Comment by michaelgregorius** [comment]
@djchals Thanks for the video! I was now able to reproduce the problem.

Here is how to reproduce the problem:

1. Copy the XML data below into a text editor and save it in a file with the extension `mmp`, e.g. `2470-reproduce.mmp`.
2. Start LMMS and load the file.
3. Click on the different names of the tracks in the song editor and get acquainted with the different patterns shown in the Beat+Bassline Editor. The names should give some hints to the patterns.
4. In the Song Editor clone the track "Rythmic".
5. Use "Save as..." to save the file under a different file name, e.g. `2470-reproduce-corrupt.mmp`.
6. Close LMMS.
7. Start LMMS again and load the file you have just saved.
8. Compare the track names with each pattern. Up to the cloned track everything is ok, then all tracks will be one off:
  * "Sparse" now contains the data of "Long 2".
  * "Long 2" now contains the data of "Offbeat".
  * "Offbeat" now contains the data of "Sparse".

Attached you can find a diff of the original file and the corrupt file with the cloned data:
![2470-diff](https://cloud.githubusercontent.com/assets/9293269/11457094/694261fc-96a0-11e5-8d2d-0826128ea448.png)

It seems like there are the following problems:

1. Patterns and BB-Track don't seem to be associated via IDs or something similar but rather by order.
2. The patterns of the Kicker instrument seem to be differentiated by their position which seems like a hackish solution.
3. When you clone a track its data seems to be put at the position of the track below it and that track is moved to the very end of the list. This is causing the mix up described above.

Her is the data for the initial file:
```XML
<?xml version="1.0"?>
<!DOCTYPE lmms-project>
<lmms-project version="1.0" creator="LMMS" creatorversion="1.1.3-g3e03e71" type="song">
  <head timesig_numerator="4" mastervol="100" timesig_denominator="4" bpm="140" masterpitch="0"/>
  <song>
    <trackcontainer width="600" x="5" y="5" maximized="0" height="300" visible="1" type="song" minimized="0">
      <track muted="0" type="1" name="Long" solo="0">
        <bbtrack>
          <trackcontainer width="580" x="992" y="200" maximized="0" height="300" visible="1" type="bbtrackcontainer" minimized="0">
            <track muted="0" type="0" name="Kicker" solo="0">
              <instrumenttrack pan="0" fxch="0" usemasterpitch="1" pitchrange="1" pitch="0" basenote="57" vol="100">
                <instrument name="kicker">
                  <kicker decay_numerator="4" decay_denominator="4" distend="0.8" click="0.4" endnote="0" version="1" decay="440" syncmode="0" noise="0" slope="0.06" dist="0.8" env="0.163" startnote="0" startfreq="150" endfreq="40" gain="1"/>
                </instrument>
                <eldata fres="0.5" ftype="0" fcut="14000" fwet="0">
                  <elvol lspd_denominator="4" sustain="0.5" pdel="0" userwavefile="" dec="0.5" lamt="0" syncmode="0" latt="0" rel="0.1" amt="0" x100="0" att="0" lpdel="0" hold="0.5" lshp="0" lspd="0.1" ctlenvamt="0" lspd_numerator="4"/>
                  <elcut lspd_denominator="4" sustain="0.5" pdel="0" userwavefile="" dec="0.5" lamt="0" syncmode="0" latt="0" rel="0.1" amt="0" x100="0" att="0" lpdel="0" hold="0.5" lshp="0" lspd="0.1" ctlenvamt="0" lspd_numerator="4"/>
                  <elres lspd_denominator="4" sustain="0.5" pdel="0" userwavefile="" dec="0.5" lamt="0" syncmode="0" latt="0" rel="0.1" amt="0" x100="0" att="0" lpdel="0" hold="0.5" lshp="0" lspd="0.1" ctlenvamt="0" lspd_numerator="4"/>
                </eldata>
                <chordcreator chord="0" chordrange="1" chord-enabled="0"/>
                <arpeggiator arptime="100" arprange="1" arptime_denominator="4" syncmode="0" arpmode="0" arp-enabled="0" arp="0" arptime_numerator="4" arpdir="0" arpgate="100"/>
                <midiport inputcontroller="0" fixedoutputvelocity="-1" inputchannel="0" outputcontroller="0" writable="0" outputchannel="1" fixedinputvelocity="-1" fixedoutputnote="-1" outputprogram="1" basevelocity="63" readable="0"/>
                <fxchain numofeffects="0" enabled="0"/>
              </instrumenttrack>
              <pattern steps="16" muted="0" type="1" name="Kicker" pos="0" len="768">
                <note pan="0" key="52" vol="100" pos="0" len="768"/>
              </pattern>
              <pattern steps="16" muted="0" type="1" name="Kicker" pos="192" len="768">
                <note pan="0" key="60" vol="100" pos="0" len="48"/>
                <note pan="0" key="60" vol="100" pos="192" len="48"/>
                <note pan="0" key="60" vol="100" pos="336" len="48"/>
                <note pan="0" key="60" vol="100" pos="480" len="48"/>
                <note pan="0" key="60" vol="100" pos="576" len="48"/>
              </pattern>
              <pattern steps="16" muted="0" type="1" name="Kicker" pos="384" len="768">
                <note pan="0" key="60" vol="100" pos="0" len="48"/>
                <note pan="0" key="60" vol="100" pos="576" len="48"/>
              </pattern>
              <pattern steps="16" muted="0" type="1" name="Kicker" pos="576" len="768">
                <note pan="0" key="48" vol="100" pos="0" len="768"/>
              </pattern>
              <pattern steps="16" muted="0" type="1" name="Kicker" pos="768" len="768">
                <note pan="0" key="52" vol="100" pos="96" len="48"/>
                <note pan="0" key="52" vol="100" pos="288" len="48"/>
                <note pan="0" key="52" vol="100" pos="480" len="48"/>
                <note pan="0" key="52" vol="100" pos="672" len="48"/>
              </pattern>
            </track>
          </trackcontainer>
        </bbtrack>
        <bbtco muted="0" usestyle="1" name="" pos="0" color="4286611584" len="768"/>
      </track>
      <track muted="0" type="1" name="Rhythmic" solo="0">
        <bbtrack/>
        <bbtco muted="0" usestyle="1" name="" pos="0" color="4286611584" len="768"/>
      </track>
      <track muted="0" type="1" name="Sparse" solo="0">
        <bbtrack/>
        <bbtco muted="0" usestyle="1" name="" pos="0" color="4286611584" len="768"/>
      </track>
      <track muted="0" type="1" name="Long 2" solo="0">
        <bbtrack/>
        <bbtco muted="0" usestyle="1" name="" pos="0" color="4286611584" len="768"/>
      </track>
      <track muted="0" type="1" name="Offbeat" solo="0">
        <bbtrack/>
        <bbtco muted="0" usestyle="1" name="" pos="0" color="4286611584" len="768"/>
      </track>
    </trackcontainer>
    <track muted="0" type="6" name="Automation-Spur" solo="0">
      <automationtrack/>
      <automationpattern tens="1" mute="0" prog="0" name="Zähler" pos="0" len="192"/>
      <automationpattern tens="1" mute="0" prog="0" name="Nenner" pos="0" len="192"/>
      <automationpattern tens="1" mute="0" prog="0" name="Tempo" pos="0" len="192"/>
      <automationpattern tens="1" mute="0" prog="0" name="Master-Lautstärke" pos="0" len="192"/>
      <automationpattern tens="1" mute="0" prog="0" name="Master-Tonhöhe" pos="0" len="192"/>
    </track>
    <fxmixer width="561" x="508" y="717" maximized="0" height="349" visible="1" minimized="0">
      <fxchannel num="0" muted="0" volume="0" name="Master" soloed="0">
        <fxchain numofeffects="0" enabled="0"/>
      </fxchannel>
    </fxmixer>
    <ControllerRackView width="400" x="1040" y="607" maximized="0" height="200" visible="1" minimized="0"/>
    <pianoroll width="640" x="0" y="0" maximized="0" height="480" visible="0" minimized="0"/>
    <automationeditor width="640" x="0" y="0" maximized="0" height="400" visible="0" minimized="0"/>
    <projectnotes width="640" x="0" y="0" maximized="0" height="400" visible="0" minimized="0"><![CDATA[<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta name="qrichtext" content="1" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body style=" font-family:'Noto Sans'; font-size:10pt; font-weight:400; font-style:normal;">
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:'Oxygen-Sans'; color:#e0e0e0;">Schreiben Sie hier Ihre Projekt-Notizen auf.</span></p></body></html>]]></projectnotes>
    <timeline lp1pos="192" lp0pos="0" lpstate="0"/>
    <controllers/>
  </song>
</lmms-project>
```

**Comment by tmerr** [comment]
Here's the simplest way to reproduce the issue I can think of: https://www.youtube.com/watch?v=oXey21dfOYQ

I'll try to look into this

**Comment by softrabbit** [comment]
This bug was probably created in https://github.com/LMMS/lmms/pull/1704, before that cloned tracks were added last.

**Comment by zonkmachine** [comment]
> This bug was probably created in #1704,

I can confirm that this is the case. Bug introduced in 6e68eca6f88a36a7c6fd13d907a8b6fe55069bbc

**Comment by softrabbit** [comment]
Compare the track order in the song editor and the B&B editor for an easy way to see the disorder happening.

![disorder_2470](https://cloud.githubusercontent.com/assets/6411463/14344794/6560143a-fcb2-11e5-9caa-96f597bb3431.png)

**Comment by Umcaruje** [comment]
@badosu could you take a look at this, since this regression was caused by your PR?

**Comment by zonkmachine** [comment]
https://github.com/LMMS/lmms/blob/master/src/core/Track.cpp#L1781

If I change `tcView->moveTrackView( newTrackView, index + 1 );` to
`tcView->moveTrackView( newTrackView, index + 2 );`

the cloned track will be created one step down as expected but the tracks won't otherwise be scrambled. It will save and load consistently.

Also, see [this comment](https://github.com/LMMS/lmms/pull/1704/files#r25202424) on the PR:


>  I changed the logic of all other tracks from swapping to a move action, this can however change the location of the BB track on the selector in an inconsistent way.

**Comment by musikBear** [comment]
> the cloned track will be created one step down as expected but the tracks won't otherwise be scrambled. It will save and load consistently.

Can you read-out what value *index* has before
`tcView->moveTrackView( newTrackView, index + 1 );`

**Comment by zonkmachine** [comment]
> Can you read-out what value index has before
> ```tcView->moveTrackView( newTrackView, index + 1 );```

Presumably the position of the track being cloned starting from 0.

**Comment by zonkmachine** [comment]
> I think this issue is likely a duplicate of #2277.

Right, I closed that one as this one has more info in it.

**Comment by musikBear** [comment]
> Presumably the position of the track being cloned starting from 0.
@zonkmachine 

No i mean the actual *value* of the variable `index`
can you make a debug readout of ìndex` before and after the de-reference-call
`tcView->moveTrackView( newTrackView, index + 1 )`

My thought is that if the value of `index` is 'weird' after the call, then it could explain why the tracks are mixed up, so a trace of `index` could be informative -just a thought

**Comment by zonkmachine** [comment]
> No i mean the actual value of the variable index

The actual value corresponds to the presumed one. My guess is that you'll be more lucky if you dive into the code somewhere around BBTrack::swapBBTracks( ... ) .

**Comment by badosu** [comment]
@Umcaruje I am sorry I could not find much time to look into this and I don't know if I will be able in a short time.

If you revert the commit is it fixed? Won't it bring back the old bug?

**Comment by zonkmachine** [comment]
@badosu I'm on the case. Care to take a look at #2950?
