### ISSUE TITLE
directory settings

### ISSUE THREAD

**Issue by djchals** [LMMS/lmms#2471]
Hi!

I'm using LMMS version 1.1.3 with a real synthesyzer connected by midi usb interface.

I found other bug:

In the Settings menu, if i change the working directory and the others LMMS is deleting the previous folder and all the contents that was here (all the projects, etc...)

Regards

**Comment by musikBear** [comment]
naa, that has nothing to do with lmms. If anything physically disappear from your harddrive, then something else has happened
Changing anything in the settings menu can not cause that.
Im willing to eat a hat, if it did.
**Logically** you may not be able to **see** a folder and its content, **inside** LMMS, but i bet the hat-eating-event, that your files still are in the same folders they were before you changed any settings, inside LMMS
This topic deals with setting issues:
https://lmms.io/forum/viewtopic.php?f=7&t=3403
Follow my instructions about your **.lmmsrc.xml** file
If you still have problems, please open a ticket on forum :https://lmms.io/forum/viewforum.php?f=7

**Comment by djchals** [comment]
Really, i like very much lmms rathen that others :) 

But All the folders are empty when i changed the settings, yesterday all the songs appears deleted, and i try to recover with three undelete tools: testdisk, photorec and extundelete. With extundelete i could see and recover the files but all were corrupted.

The change was from /home/carlos/lmms to /home/carlos/documentos/lmms, and in all the folders except the last i add "documentos" between "/home/carlos" and the suffix

I have pc since 1988 and i'm php programmer for 10 years and 10 years i have linux. I'm not a newbie with computers. Lmms deleted the files, please trust me, check it ;)

**Comment by michaelgregorius** [comment]
I am not able to reproduce this issue in master. For a quick test I have switched my working directory from `$HOME/lmms` to `$HOME/lmms2` and back to `$HOME/lmms` (always restarting in between) and at least the projects and the templates in the original directory did not disappear.

**Comment by djchals** [comment]
I tried now, but i cant reproduce the error now seems it works. But i review the bash history from yesterday, and i didnt write any "rm" or something. I dont know what occurs yesterday, only i written cp -rpf lmms /home/carlos/documentos/lmms This is making me feel silly, lol

if it happens again, i will communicate it.

Sorry and thank you very much alike :)
