### ISSUE TITLE
missing buttons

### ISSUE THREAD

**Issue by djchals** [LMMS/lmms#2472]
Hi!

I like the program, is easy for use ;) I m using the 1.1.3 version.

In this window, I think a missing button to create a new bassline (there are a buttons for create new tracks and automation track, but not for bassline)

![lmms2](https://cloud.githubusercontent.com/assets/16034655/11443906/6fea6796-9521-11e5-8c25-4d8bfe4cd1a0.png)

Regards

**Comment by jackokring** [comment]
You create a new bass line in the base line window and it will add a track. A little unintuative, but it works. Change title to "make adding baseline easier in song window" maybe. As a feature request.

**Comment by softrabbit** [comment]
And then there's the button to the right of the dropdown that selects which bassline to edit... identical to the "add beat/bassline" button in the song editor.

**Comment by musikBear** [comment]
and all is also explained *here*
https://lmms.io/wiki/index.php?title=Beat_Bassline_Editor
Please take this kind of support requests to the forum, before you open a new ticket in tracker.
http://lmms.io/forum/viewforum.php?f=7

**Comment by Umcaruje** [comment]
![screenshot from 2015-11-29 20 07 33](https://cloud.githubusercontent.com/assets/6282045/11459354/17dfc176-96d5-11e5-95fb-c52a1d01499a.png)
The Buttons to add a new Beat/bassline are right there.

Closing as invalid.
