### ISSUE TITLE
loop is not infinite

### ISSUE THREAD

**Issue by djchals** [LMMS/lmms#2473]
I'm using the 1.1.3 version with a real synthesyzer is connected by midi usb interface.
When i click on play button in this window, it sound  few minutes and then the program crashes (possible 5-10 minutes for it) This track is arpeggied, i dont know if it passes with all tracks

![lmms2](https://cloud.githubusercontent.com/assets/16034655/11444062/b62f07c4-9522-11e5-9c44-29d182bfac97.png)

Regards

**Comment by musikBear** [comment]
needs clarification

**Comment by unfa** [comment]
Could you provide some GDB info about the crash?

**Comment by Umcaruje** [comment]
@djchals please provide your OS, steps to reproduce and backtrace.

Right now this could be anything.

**Comment by djchals** [comment]
Sorry, I could not repeat the mistake again. When it happening again i notice us ;) 

Thank you very much
