### ISSUE TITLE
Directory/executable mix-up?

### ISSUE THREAD

**Issue by DeathHammer000** [LMMS/lmms#2474]
Trying to compile 1.1.3 on Debian to get VeSTige (it's not in my APT repository). Generating the makefile with CMake does work, but upon building, this error shows up at around 22% of the way in:

```
Linking CXX executable ../lmms
/usr/bin/ld: cannot open output file ../lmms: Is a directory
collect2: error: ld returned 1 exit status
src/CMakeFiles/lmms.dir/build.make:476: recipe for target 'lmms' failed
make[2]: *** [lmms] Error 1
CMakeFiles/Makefile2:1024: recipe for target 'src/CMakeFiles/lmms.dir/all' failed
make[1]: *** [src/CMakeFiles/lmms.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

Looks like ld's a bit confused. I can't find a way to fix this one. If you could help me that would be appreciated.

**Comment by Umcaruje** [comment]
Where are you running make from?

**Comment by DeathHammer000** [comment]
Not exactly sure. I think it's in the directory above the /src and /build one...

**Comment by Umcaruje** [comment]
You should run cmake and make from the build directory, as is said in the build tutorial: https://github.com/LMMS/lmms/wiki/Compiling-lmms

Closing this as a support request, you can still comment if you need further assistance.
