### ISSUE TITLE
Piano Roll will not Open  Inside Program

### ISSUE THREAD

**Issue by LibelousNewt** [LMMS/lmms#2478]
Inside the actual software I have found some sort of issue. I have been working on the newly downloaded program for a couple hours now and all of a sudden when I tried to open up the piano roll for another instrument it simply was not responding to my request. I attempted restarting the program and my computer itself. I didn't do anything to the program prior to simply using it for its designated purpose. If you guys could find out the reason for this issue I would be very grateful!

**Comment by musikBear** [comment]
What 
* OS
* LMMS version

if you dont have a 16:4 broadscreen monitor, it could simply be outside view, to the right.
If you have minimized piano-roll, it will only be visible as a small label in the bottom of the screen.
Does any of this fit your issue?

**Comment by grejppi** [comment]
@LibelousNewt, 
I'm closing this as support requests do not belong on the bug tracker, but you may still continue the discussion here, in case an actual bug is found.

Could you post a project file where this happens?

**Comment by tresf** [comment]
> if you dont have a 16:4 broadscreen monitor

What aspect ratio have to do with it?  Just ask him to scroll to the right.

Also, I'm not sure how [common of an aspect ratio 16:4 is](https://www.youtube.com/watch?v=hIm95PZ1zKw), but I've never seen it in person.
