### ISSUE TITLE
In piano roll, curser stays in "ctrl-mode" although not pressed anymore

### ISSUE THREAD

**Issue by notiflux** [LMMS/lmms#2479]
This bug only sometimes happens to me and I only partially know how to reproduce it. Sometimes, when I want to mark something in the piano roll, after I released the ctrl key, the curser stays in that ctrl-mode and it also acts in the ctrl-mode.

**Comment by musikBear** [comment]
duplicate #431

**Comment by zonkmachine** [comment]
Duplicate of #431 and fixed...
