### ISSUE TITLE
 freehand-option for LFO shapes 

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#2480]
Feature Suggestion:
Add a new option for all generic '?'-slots in all LFO s : **Freehand**
![lfo](https://cloud.githubusercontent.com/assets/6662066/11628344/5f1eb1c4-9cf1-11e5-8267-73a7026428d0.png)
This should let the user draw a shape, directly, just like LMMS-wave-shaper. 
Whit this feature, it would be easy to especially create sidechain shapes, that other wise are a little difficult to make, but surely a lot of other creative heads, will find use for wave-shapes in this slot.

**Comment by tresf** [comment]
> Add a new option for all generic '?'-slots in all LFO s : Freehand

What does the `?` have to do with this feature exactly?

> This should let the user draw a shape, directly, just like LMMS-wave-shaper. 

Or perhaps (or also) we allow the importing (and thus exporting) of waveshapes from the waveshaper plugin.  Reasonable enough request, but the write-up could use some improvements including a GUI mockup and a picture of the waveshaper.

**Comment by musikBear** [comment]
> Or perhaps (or also) we allow the importing (and thus exporting) of waveshapes from the waveshaper plugin.

You mean directly into the adding an export-option to waveshaper? Yes, that would do, because then that wave-form, could simply just be imported into the existing feature (The '?'-slots)
Thats a good idea :+1:

**Comment by Umcaruje** [comment]
@musikBear please clarify this issue and offer some mockups?

**Comment by musikBear** [comment]
I tried to use the current waveshaper-gadget to draw a pattern, but thats very difficult with a mouse. But lmms also already has a perfect feature for curve-drawing; The Automation-pattern-editor. So i would suggest that Automation-pattern-editor is used, instead of the waveshaper. Then a new option in the **Edit** menu can be added **"export Automation pattern"** 
The export-format should be **wav**.
![exportapmockup](https://cloud.githubusercontent.com/assets/6662066/11780675/0d8964ee-a264-11e5-9351-3b03dd7ee3e0.png)

That will allow for users to create their own collection of wave-shapes, for everything, but especially side-chaining, and gating-patterns in LFO's in this slot
![insrumentlfo](https://cloud.githubusercontent.com/assets/6662066/11780714/6c4644ca-a264-11e5-96b6-012208ff96bb.png)

**Comment by BaraMGB** [comment]
Why you don't use automation for this?

**Comment by StakeoutPunch** [comment]
@BaraMGB an LFO repeats its set modulation continuously. Musikbear wants there to be user-definable LFO shapes so that we have more options aside from the existing wave shapes. As an LFO will repeat its set wave shape at the defined speed and amount for the duration that it is enabled, it is not possible to draw the automation required to replicate this in any reasonable amount of time. You also can't dynamically draw automation curves in real time while your project is playing back. You also can't automate automation to achieve the amount of control you can get while automating the controls of an LFO.

I agree with @tresf. This seems like a good idea, just needs more clarification.

**Comment by Umcaruje** [comment]
BTW, you can draw straight lines in the wave display by using shift while clicking.

**Comment by softrabbit** [comment]
> What if I have a 2 bar long automation, how will it turn that into a waveform?

You could have it in the B&B editor...

**Comment by musikBear** [comment]
@Umcaruje 
> you can draw straight lines in the wave display by using shift while clicking

Yes, but the difficult thing is a fine smooth curve, the exact thing you like for a sidechain.
You are right about the shape-length. I only saw this as an option to draw a **one bar** sized shape, for the use in LFOs just like the ones in the folder *"Shapes"* -And even an option for just **one beat**. 
For usage in LFOs shapes should not be longer than one bar. If the user wants longer shapes, they would be real patterns, and those should be made as *automation*, so the export should simply only allow one bar to be converted to a wave-shape, no matter how long the actual automation pattern was drawn. A single beat sized shape, should be repeated to fit of the LFO envelope *precisely*!

The tool exists in FLs, that is how they sidechain. They also have a library of 'common' sidechain patterns, but everything is editable ( bezier-curves and slope indicators )
(I btw made my own external tool, in 2010 
![wavewrite](https://cloud.githubusercontent.com/assets/6662066/11810686/21a6c74c-a330-11e5-995e-43becaf2be1b.png)
but its clumsy, and has unpredictable strange artefacts on some outputs -eg not very good :p)

But if the waveshaper should be the tool of choise, then it would need to upsized -Properly to triple it current size, its would be too difficult to use as it is. But honestly, LMMS already has a good tool : Automation-editor, so i would still favor that. If #2466 reach success, then it will be even better for the job.

**Comment by musikBear** [comment]
Since lmms instrument LFO's let ~50% through even with max AMT, #2487, neither sidechaining or gating, will be sound good, invoked with LFO.

**Comment by jackokring** [comment]
It is really Nyquist and some smoothing (or interpolation) of the curve. I think a rate limited distortion (LPF) point of view works best in practice, and some indication of synchronized bar length (or discreet speed increments, as bounds to twist the dial and complain of lack sync). As in the L of LFO in practice.
