### ISSUE TITLE
Files are not opened in plugins via drag-and-drop if a path contains non-ASCII characters

### ISSUE THREAD

**Issue by danpla** [LMMS/lmms#2481]
When I drop FLAC or SF2 file onto Song Editor or Beat + Bassline Editor, an appropriate plugin is added, but it's empty — a file itself is not loaded. However, WAV and OGG samples are loaded without problems.

At the same time, all is OK with double click.

Ubuntu 14.04 x86-64, LMMS 1.1.3 from KXStudio repositories

**Comment by musikBear** [comment]
from **where** do you 'drop' those files?
Afaik Dropping a soundfile only works if the soundfile is **inside** lmms, so drag&drop from side-bar folders will add correct instrument -eg AFP for soundfiles, and SFplayer for SF2-files
That works in windows.
drag&drop from win-explorer does not work, and i dont think it meant to.

**Comment by danpla** [comment]
If course I drop them from the LMMS' Side Bar.

I'm not tested this on Windows.

**Comment by musikBear** [comment]
Sound as a linux-bug, then 
More linux-users needed to confirm 
Strange if this has been un-observt for so long 8|

**Comment by danpla** [comment]
Seems like this happens only if a path contains non-ASCII characters.

**Comment by danpla** [comment]
I have tested this on Windows and got the same result. So the issue is with non-ASCII paths.

Can you update the issue title?

**Comment by tresf** [comment]
Related: https://github.com/LMMS/lmms/issues/1191

@danpla you can change your own titles. :+1:

**Comment by danpla** [comment]
The problem is that after drag-and-drop all non-ASCII characters are replaced by question marks. Maybe after transformations in `StringPairDrag`.

**Comment by softrabbit** [comment]
If it's ```StringPairDrag```, chances are this is fixed in master: https://github.com/LMMS/lmms/commit/c3687199ea3b6cc14c66d0ed534bbfcde037e994

**Comment by danpla** [comment]
Yes, that's it. The build from master works without problems, so the issue can be closed.

**Comment by Umcaruje** [comment]
:+1:
