### ISSUE TITLE
when i download imms and i hit finish it doesn't do anything 

### ISSUE THREAD

**Issue by Lucky8ball17** [LMMS/lmms#2484]
i have a windows and when i hit finish download it doesn't do anything
i've tried everything please help

**Comment by Spekular** [comment]
Does the download succeed? Have you tried a different browser? Are you
running the installer after downloading it? Do you have admin rights on
your user?

I'm not sure of anything else that could be an issue. I've never seen a
"finish" button when downloading anything.

**Comment by musikBear** [comment]
> i have a windows

Which version?
Did you get lmms from here: https://lmms.io/download/#windows

>  I've never seen a "finish" button when downloading anything.

neither have i, if we are talking about the official lmms download.
(imo support request)

This resource is not the right forum for Q&A, Q&A should takes place in our dedicated help-forum :)
Could i ask you to create an account there? : http://lmms.io/forum/

**Comment by tresf** [comment]
> This resource is not the right forum for Q&A

Agreed.  Please feel free to continue discussion here if you wish.  Closing as support request.
