### ISSUE TITLE
Icon Sizes

### ISSUE THREAD

**Issue by mijas1999** [LMMS/lmms#2490]
I have a Surface Pro 2 with Windows 10 and the high screen resolution means your icons are very tiny and almost unreadable.
Is there a way to make them bigger other than messing around with the resolution (or getting a huge monitor?
Thanks
John

**Comment by tresf** [comment]
In part, a duplicate of #2209.

Worth reading:
https://github.com/LMMS/lmms/issues/455#issuecomment-156446456
