### ISSUE TITLE
Adding a ready to use controller for pitch modulation

### ISSUE THREAD

**Issue by DeRobyJ** [LMMS/lmms#2496]
Almost every physical synth has 2 wheels next to the keyboad: the pitch wheel ad the modulation wheel, which is mostly used for pitch modulation.

I think we should have a controller ready in the default "new project".
Base 0.5, Speed synced to 8th or 16th note, amount to 0 (should be then changed with automation track when wanted, or linked to a physical knob for live operation)

This controller will be then linked by the user to the pitch/detune knob of any oscillator (or of the instrument itself).

There is also a little problem when using it live with a physical keyboard: since you may want to attach the instrument pitch to the controller, you will then be unable to use the midi pitch wheel of the keyboard. 

This is not a big deal with oscillator based instrument (eg. 3OSC or Monstro), and might not be a problem when composing (thanks to per-note pitch automation), but it will be hard to both pitch shift and modulate, for example, ZynAddSubFX, which only has the plugin pitch knob to change detuning on the go.

What do you think?

**Comment by Umcaruje** [comment]
I'm failing to see why this should be included in the default template.

If you would benefit from this, you can easily change your default template to have the desired controller in it, but I think the one shipping with LMMS should be as blank as it gets. Everybody has different needs, and not everyone needs a pre-added pitch controller when opening lmms.

**Comment by musikBear** [comment]
> I think the one shipping with LMMS should be as blank as it gets.
:+1: Agreed 
If a rehaul of default "new project" takes place, i would like to link these two here
#2092
#113

**Comment by DeRobyJ** [comment]
ok, was just my opinion.
We can close this. :)

**Comment by Umcaruje** [comment]
>ok, was just my opinion.
>We can close this. :)

:+1:
