### ISSUE TITLE
Steps per Bassline

### ISSUE THREAD

**Issue by teeberg** [LMMS/lmms#250]
If you previously added steps to a bassline, adding another instrument will insert it with the default amount of steps (16). This is unexpected behavior to me. Shouldn't it be added with the same amount of steps as the other instruments? And why are there still options to add/remove steps in the instrument's context menu? With the latest changes, I think there should only be a number of steps for the current bassline and no longer for each individual instrument.

**Comment by Veratil** [comment]
This looks to be fixed.
