### ISSUE TITLE
Release build?

### ISSUE THREAD

**Issue by oeai** [LMMS/lmms#2500]
Hi! i think that a lot of work is done.
the zyna preset bug is fixed, gui rewamped
can i ask for some release build like pre-1.1.4
just for people to know that something has changed?

**Comment by Umcaruje** [comment]
Please do not use the issue tracker for these kinds of conversations. The mailing list is there for stuff like this.

**Comment by tresf** [comment]
@oeai please feel to create a release on your own.  We need to fix the preset-crash bug prior to testing 1.2, so this will come when #2315 gets closed. 

As @Umcaruje has illustrated, we have been discussing the roadmap to 1.2 in our email thread, so opening this bug report is redundant at this point.

**Comment by oeai** [comment]
hmm, looks like i deleted all mail for last year...
HappyNewyEar!
