### ISSUE TITLE
Documentation/UI incorrect for Automation Track on Mac OS X

### ISSUE THREAD

**Issue by follower** [LMMS/lmms#2503]
The documentation and UI say to "`Drag a control while pressing <Ctrl>`" onto an Automation Track.

On Mac OS X the correct key to press appears to be the "Command" ("Butterfly") key. Although this may depend on whether the "control" key has been configured to act as a second mouse button.

There may be other places where this is an issue but this is where I got confused for a while. :)

Using 1.1.3 but the text appears to be the same in trunk.

Thanks.

**Comment by tresf** [comment]
Thanks, confirmed.

Unless someone knows how to get the CTRL modifier dynamically, I propose:


* [`AutomationPattern.cpp#L598`](https://github.com/LMMS/lmms/blob/master/src/core/AutomationPattern.cpp#L598)

   ```cpp
	return tr( "Drag a control while pressing <%1>" ).arg(
#ifdef LMMS_BUILD_APPLE
		"⌘");
#else
		"Ctrl");
#endif
```

I believe the translation files would all have to be updated as well so that the `%1` would make it through.

**Comment by Umcaruje** [comment]
>This would be a great fix for someone new to the project that wants to get familiar with submitting patches/PRs.

I'm not new, nor I need to get familiar with git, but did it anyways :wink: #2522

**Comment by follower** [comment]
For the record, the 1.2.0-RC1 (a.k.a. 1.1.90) displays the "Command key" symbol incorrectly:
![command-symbol-display-bug](https://cloud.githubusercontent.com/assets/189962/18535943/80deab68-7b4c-11e6-99e2-f3278d4cbc81.png)

But it appears it's been fixed since that release as it displays correctly with the 1.1.91 version by @tresf in #2890 : 
![command-symbol-display-corrected](https://cloud.githubusercontent.com/assets/189962/18535944/80e65ebc-7b4c-11e6-98b2-4da3399f22e2.png)

Just wanted to mention this in case anybody else was going to report it.

**Comment by tresf** [comment]
@follower likely fixed by switching to Qt5.  Thanks for the information.

**Comment by follower** [comment]
One nit pick with this I just noticed, is that generally when the command key symbol is used it doesn't have surrounding angle brackets (unlike, say, `<CTRL>` or `<ALT>`), so it looks a little strange.
