### ISSUE TITLE
in the about pane the copyright is 2004 - 2014

### ISSUE THREAD

**Issue by trollworkout** [LMMS/lmms#2508]
should be 2015 based on the release :) and is using (c) when the copyright symbol is part of unicode available on any platform anywhere ©

**Comment by tresf** [comment]
Similar in nature to #1540.  The short of it is, there's no benefit in hard-coding the copyright anywhere and we should have it passed in through a variable at compile time via something like: `PROJECT_COPYRIGHT`, which is now available via [`3114cce`](https://github.com/LMMS/lmms/commit/3114ccea26a17c93cd79fdfa84504b4bdebc8fa7#diff-af3b638bc2a3e6c650974192a53c7291R29).

The next step is to `configure` it by placing it in something like [`lmmsversion.h`](https://github.com/LMMS/lmms/blob/master/src/lmmsversion.h.in)`(.in)`, which will expose it to the source code,` #include` it to the necessary source file(s), and then will be accurate everywhere, forever.

This is a pretty straight-forward task for someone interested. :+1:

**Comment by trollworkout** [comment]
:))) :+1:
