### ISSUE TITLE
MIDI tab not shown in instrument editor (translation issue)

### ISSUE THREAD

**Issue by StCyr** [LMMS/lmms#2519]
Hi,

The instrument editor's MIDI tab isn't shown in French.

I discussed this issue today on the IRC, and someone noticed that launching "LANG=fr lmms" on his computer only shows the "M" of "MIDI" of the instrument editor's MIDI tab; On my computer, I can't see any letter of the MIDI tab's label.

A quick workaround to this problem is to start LMMS by typing "LANG=C lmms".

I can send you a PR for updating the French translation if you want (any lmms policy to be followed here?).

Related to this, is there any reason why these windows aren't resizable? That would also fix the issue.

**Comment by Umcaruje** [comment]
>I can send you a PR for updating the French translation if you want (any lmms policy to be followed here?). 

Please do. 

Useful links:

**Comment by Umcaruje** [comment]
Ok, I checked out the master branch and loaded all translation. The midi tab is visible in the french translation, but the new `MISC` tab is cut off. Also affected are Portugese, Dutch, and Galego.
Barely holding up are German and Polish (the text is too close to the edge).
Some pics: 
![screenshot from 2016-01-26 21 35 14](https://cloud.githubusercontent.com/assets/6282045/12595289/b4378662-c47a-11e5-978f-e997b48088b9.png) ![screenshot from 2016-01-26 21 45 27](https://cloud.githubusercontent.com/assets/6282045/12595325/ebb0849a-c47a-11e5-9019-49b982e1330e.png)

There are more, I didn't want to spam the issue with pictures. 

For comparison, this is how the english version looks: 
![screenshot from 2016-01-26 21 36 59](https://cloud.githubusercontent.com/assets/6282045/12595309/cc37c2fe-c47a-11e5-9b66-70dcfe68ffcc.png)

**Comment by StCyr** [comment]
https://github.com/LMMS/lmms/pull/2521

**Comment by StCyr** [comment]
Here's the fix: https://github.com/LMMS/lmms/pull/2521

But, if you don't mind I would prefer to try and implement your suggestion of adding a second row of tabs.

Cyrille

**Comment by StCyr** [comment]
Ok, I'm starting to have something for the 2nd row implementation.

You can have a look at my progress here: https://github.com/StCyr/lmms/tree/StCyr_2ndRow

**Comment by claell** [comment]
Could it be an option to simply automatically reduce/increase padding adaptively to the length of words, so they exactly fit the space given? Also the font size could be lowered.
