### ISSUE TITLE
"Crunchy sound" using the Peak Controller

### ISSUE THREAD

**Issue by SimoneIervasi** [LMMS/lmms#2534]
Hi! I've got this problem: everytime i use the Peak Controller (for sidechain-pumping compression) the sound becomes dirty, full of "crunchy noise", it happens especially with basses (and low frequencies in general).
Thanks for the attention.

Simone

**Comment by eagles051387** [comment]
Good Morning Simone,

Can you provide the necessary steps to reproduce and maybe a sample file
where you are seeing this occur please.

Jonathan Aquilina

**Comment by SimoneIervasi** [comment]
I think it's a duplicate of #1281   
However i'll try to make a sample for let you hear the crinkle noises i'm talking about.

**Comment by Umcaruje** [comment]
>I think it's a duplicate of #1281

Indeed. And the issue is closed as fixed. Closing

**Comment by cnuptak** [comment]
on lmms 1.1.3 still have this bug

**Comment by Spekular** [comment]
IIRC the fix is in 1.2.
