### ISSUE TITLE
GigaSampler Player forgets loaded samples

### ISSUE THREAD

**Issue by karmux** [LMMS/lmms#2537]
If I add GigaSampler player with some sample gig file and save project then after loading same project all GigaSampler Players are empty. I'm using master branch.

**Comment by softrabbit** [comment]
Could this be related to #2412 and maybe #2468?

**Comment by karmux** [comment]
@softrabbit could be. I see that #2412 is fixed but still I have issue with #2468.

**Comment by softrabbit** [comment]
@karmux, can you check if this still is valid for the latest master?

**Comment by karmux** [comment]
@softrabbit , unfortunately this is still issue for latest master.

**Comment by karmux** [comment]
`new GigInstance( _gigFile )` gets `RIFF::Exception` with every gig file I have. Same with latest 4.0 version of libgig and libgig-dev.

**Comment by zonkmachine** [comment]
When I try the last of the original commits by @floft 205056621c353fe50316f963b479b6f824ca6246 the files don't reload either.
The saved project looks correct though.
I'm on LinuxMint, libgig6 3.3.0-2

**Comment by karmux** [comment]
I entered full absolute path of gig file to the project file and it loaded correctly. Trying to fix it.

**Comment by zonkmachine** [comment]
@karmux  Cool, make sure file links are preserved in recovery files too.
These are my finds after probing it a bit but you posted in between so this may be nothing new to you.

> 
> Some finds
>  * GigInstrument::openFile is passed the relative argument gig/file.gig on loading and "" on recovering while in sf2, which gigaplayer is based on, sf2Instrument::openFile is passed the absolute path on both opening and recovering.
>  * GigInstrument::loadFile doesn't seem to be called anywhere. It's inherited from sf2 where it's used to load a default sf2 soundfile. It can probably be removed. Probably...
