### ISSUE TITLE
Since commit  bc77a13, carla plugin doesn't compile anymore

### ISSUE THREAD

**Issue by ycollet** [LMMS/lmms#2549]
Since commit  bc77a13, carla plugin doesn't compile anymore.

**Comment by michaelgregorius** [comment]
Seems like the Carla plugin in not part of the Travis job because all builds have been green at the time of my commit.

 @tresf Is it possible to add the Carla plugin to the Travis builds?

**Comment by ycollet** [comment]
I saw also that the lb303 directory was leaved untouched by your commit.
I saw nowhere that something is compiled by cmake in this directory.
A #add_subdirectory(lb303) is in a CMakeLists.txt but nothing else. Some 
old code ?

**Comment by tresf** [comment]
> @tresf Is it possible to add the Carla plugin to the Travis builds?

Anything is possible, but this isn't as straight forward as enabling a plugin.

1. Is there a repo for pre-compiled Carla as well as the headers we can tap into and is it up to date?
2. If no, can we predictably script the fetch, install and includes?
3. Last but not least, we need a way of enabling this for Linux (native) only as Carla doesn't work yet on Win32/Win64/Mac AFAIK.


If someone can help me with the deps etc, I can do the cmake stuff.

**Comment by michaelgregorius** [comment]
For now I have reverted my changes using
```
git reset --hard HEAD~1
git push -f origin master
```
Hope that no one used that small time frame to merge or commit something to the master.

**Comment by michaelgregorius** [comment]
Regarding the other topics:
* It seems that there are no instructions in the WIKI on how to build with Carla enabled? @ycollet Can you help with this? It seems that you have tried to build for such a configuration. I am using Ubuntu 15.10 in a virtual machine.
* Yes, the stuff in the `lb303` directory was not changed indeed. In fact it only came to my attention after your comment. A git blame indicates that it was commented out by @tobydox on 2008-07-22. So I'd assume that it is not maintained anymore?

**Comment by tresf** [comment]
> lb303 [...] is not maintained anymore?

Correct.

**Comment by ycollet** [comment]
To allow the compilation of the carla plugin:

I installed carla in a specific directory. So, in my build directory, I do:

export PKG_CONFIG_PATH=/opt/carla-devel/lib/pkgconfig:$PKG_CONFIG_PATH

cmake . # I restart cmake to detect carla

make
su make install

To allow the use of the plugin on some linux distribution, it may be a 
little bit more difficult than that.
I think that with some cmake versions, the MODULE link way of cmake 
seems to have changed. I modified the carlabase cmake so as it compiled 
as a SHARED library instead as a module and then link explicitely this 
shared library in carlarack and carlapatchbay.
I join to this mail the modified cmake and a cmake script stored in 
cmake/modules

YC

Le 07/02/2016 19:39, Michael Gregorius a écrit :
>
> Regarding the other topics:
>
>   * It seems that there are no instructions in the WIKI on how to
>     build with Carla enabled? @ycollet <https://github.com/ycollet>
>     Can you help with this? It seems that you have tried to build for
>     such a configuration. I am using Ubuntu 15.10 in a virtual machine.
>   * Yes, the stuff in the |lb303| directory was not changed indeed. In
>     fact it only came to my attention after your comment. A git blame
>     indicates that it was commented out by @tobydox
>     <https://github.com/tobydox> on 2008-07-22. So I'd assume that it
>     is not maintained anymore?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/LMMS/lmms/issues/2549#issuecomment-181076112>.
>


if(LMMS_HAVE_CARLA)
        INCLUDE(BuildShared)
        INCLUDE_DIRECTORIES(${CARLA_INCLUDE_DIRS})
        LINK_DIRECTORIES(${CARLA_LIBRARY_DIRS})
        LINK_LIBRARIES(${CARLA_LIBRARIES})
        BUILD_PLUGIN(carlabase carla.cpp carla.h MOCFILES carla.h EMBEDDED_RESOURCES "${CMAKE_CURRENT_SOURCE_DIR}/*.png")
        SET_TARGET_PROPERTIES(carlabase
                PROPERTIES SKIP_BUILD_RPATH TRUE
                BUILD_WITH_INSTALL_RPATH TRUE
                INSTALL_RPATH_USE_LINK_PATH TRUE
                INSTALL_RPATH "${CARLA_RPATH}")
endif(LMMS_HAVE_CARLA)

if(LMMS_HAVE_CARLA)
	ADD_DEFINITIONS(-DCARLA_PLUGIN_PATCHBAY -DCARLA_PLUGIN_SYNTH)
	INCLUDE(BuildPlugin)
	INCLUDE_DIRECTORIES(${CARLA_INCLUDE_DIRS} "${CMAKE_CURRENT_SOURCE_DIR}/../carlabase")
	LINK_DIRECTORIES("${CMAKE_CURRENT_BINARY_DIR}/../carlabase"
                          ${CARLA_LIBRARY_DIRS})
	LINK_LIBRARIES(carlabase)
	BUILD_PLUGIN(carlapatchbay carlapatchbay.cpp EMBEDDED_RESOURCES "${CMAKE_CURRENT_SOURCE_DIR}/*.png")
endif(LMMS_HAVE_CARLA)

if(LMMS_HAVE_CARLA)
	ADD_DEFINITIONS(-DCARLA_PLUGIN_RACK -DCARLA_PLUGIN_SYNTH)
	INCLUDE(BuildPlugin)
	INCLUDE_DIRECTORIES(${CARLA_INCLUDE_DIRS} "${CMAKE_CURRENT_SOURCE_DIR}/../carlabase")
	LINK_DIRECTORIES("${CMAKE_CURRENT_BINARY_DIR}/../carlabase"
                          ${CARLA_LIBRARY_DIRS})
	LINK_LIBRARIES(carlabase)
	BUILD_PLUGIN(carlarack carlarack.cpp EMBEDDED_RESOURCES "${CMAKE_CURRENT_SOURCE_DIR}/*.png")
endif(LMMS_HAVE_CARLA)

**Comment by ycollet** [comment]
Maybe it's time to clean this :)

**Comment by Umcaruje** [comment]
>Is there a repo for pre-compiled Carla as well as the headers we can tap into and is it up to date?

In the KXStudio repos, the `carla-git` package is up to date and gets updated regularly, and I compile my LMMS with it, without any special configuration.

**Comment by michaelgregorius** [comment]
I have now added the KXStudio repository to my development machine as described here:
http://kxstudio.linuxaudio.org/Repositories

I have then installed `carla-git` and adjusted LMMS' code for Carla. The new pull request is #2550.

@ycollet Can you please clone my repository and check whether the branch `untangling-dependencies` is building for you? Thanks!

**Comment by michaelgregorius** [comment]
I have created issue #2551 for the unmaintained `lb303` folder.

**Comment by ycollet** [comment]
Thanks, I will try to do this ASAP.

**Comment by ycollet** [comment]
Thanks for the new issue.

**Comment by Umcaruje** [comment]
@ycollet is this still an issue?

**Comment by tresf** [comment]
@Umcaruje this should probably remain open until we chain Carla into our build process.

It's quite simple to add stuff to travis, and the PR will show pass/fail for newly added items.

Repository can be added here: https://github.com/LMMS/lmms/blob/master/.travis/linux..before_install.sh
Package can be added here: https://github.com/LMMS/lmms/blob/master/.travis/linux..install.sh

Assuming the `CMakeLists.txt` picks up the change, we'll have Carla building with Travis.  If it doesn't, we can tag falktx and see if there's some additional items we need to add. :+1:

**Comment by michaelgregorius** [comment]
Now that there is a new issue for the Travis integration I think this one should be safe to close. The critical changes have been [reverted](https://github.com/LMMS/lmms/issues/2549#issuecomment-181075191) anyway.

**Comment by tresf** [comment]
> Now that there is a new issue for the Travis integration

Agreed to a point, but it's a new PR, not a new issue AFAIK, so if the PR gets closed by @Umcaruje out of frustration, the project can lose sight of the task at hand.

**Comment by michaelgregorius** [comment]
@tresf Ah, ok. Didn't notice that it was a PR.

**Comment by tresf** [comment]
> Now that there is a new issue for the Travis integration I think this one should be safe to close. The critical changes have been reverted anyway.

We opened a new bug report and then closed it.  In short, we'll add this eventually, but the repos + Travis just don't make this easy yet. :+1:
