### ISSUE TITLE
ZynAddSubFX presets broken for latest master

### ISSUE THREAD

**Issue by karmux** [LMMS/lmms#2558]
All Zyn presets sound like sinus.
Started to happen after https://github.com/LMMS/lmms/commit/ca8f80d44f9690fdf7a42da1307ed68b0b2f45ae by @Lukas-W

**Comment by zonkmachine** [comment]
After `make install` . The sounds work when you run it from `/build` directly

**Comment by karmux** [comment]
@zonkmachine I run from build directory with `./lmms` and `make install` didn't fix it.

**Comment by zonkmachine** [comment]
Sorry. I did a new build and install and now it works ( ... doesn't work ), like you describe it.

**Comment by zonkmachine** [comment]
b7d5b2d  fixed it for me.
