### ISSUE TITLE
Improved Browser - UI Concept

### ISSUE THREAD

**Issue by budislav** [LMMS/lmms#2559]
Reorganized browser for faster workflow.

![browser_all](https://cloud.githubusercontent.com/assets/3619927/13015764/2ad3946c-d1bb-11e5-8639-86e300a4455f.png)

**Comment by tresf** [comment]
Closing as superseded per email request from @budislav, see also https://github.com/LMMS/lmms/issues/1911#issuecomment-2027443697.
