### ISSUE TITLE
In the bar/tick/msec display mode of the time marker, the "bar" and "tick" fields do not change if the song is stopped and one moves the cursor manually

### ISSUE THREAD

**Issue by M374LX** [LMMS/lmms#256]

**Comment by Wallacoloo** [comment]
This no longer appears to be an issue - I can drag the playhead in the song editor, automation editor or piano roll and the min:sec:msec or bar:beat:tick display updates correctly. Somebody in the LMMS group should probably close this issue.

**Comment by musikBear** [comment]
only works in 'time'-mode - switch to 'bar'-mode, and the counter will not react to any playhead dragging

**Comment by Wallacoloo** [comment]
It's working in both modes for me using the latest git. I'll make a video
when I get a chance.

**Comment by tresf** [comment]
@Wallacoloo thanks.  We can reopen if needed. :+1:
