### ISSUE TITLE
Show mixer channel on each instrument

### ISSUE THREAD

**Issue by repsej** [LMMS/lmms#2563]
In the song editor and in the bb editor it would be very nice if one could see what mixer channel each instrument is set to (without having to open each instrument to check).

Mockup : 
![lmms-idea](https://cloud.githubusercontent.com/assets/116525/13029674/f5868d72-d292-11e5-92e2-79b54a66b9e3.png)

**Comment by Umcaruje** [comment]
@repsej On the current master branch there's a feature in the context menu that pretty much does the same thing you described here, except its not so direct, you still have to click the cogwheel to get to it: 


![](https://media.giphy.com/media/l4KhX1vq0ATnyD3Og/giphy.gif)

**Comment by repsej** [comment]
When mixing a song I need an overview of where all my instruments are being routed.

The new feature looks really nice and handy (esp the "assign to new fx" :) ... but it still dosn't give the overview.  I will still have to click my way thru all the instruments (now with the right mouse button) to make sure all instruments go where they should.

**Comment by Umcaruje** [comment]
>I will still have to click my way thru all the instruments (now with the right mouse button) to make sure all instruments go where they should.

Well, in the current master you also have the feature to quickly go thru the instruments by using navigator buttons next to the instruments name: 
![gifrecord_2016-02-14_222714](https://cloud.githubusercontent.com/assets/6282045/13036539/5db935f2-d36a-11e5-9ac1-755f6b65441c.gif)

Your request sounds reasonable to me, but with these functions that already exist it sounds a little bit redundant, don't you think?

**Comment by repsej** [comment]
I love the new features <3 <3 <3

but ... what I'm still missing is the overview ... I'd like to be able to quickly skim down the list of instruments and see that all are routed to where I want them to go ... just as we can currently do with pan and vol

I really think that this would be a nice feature :)

**Comment by DeRobyJ** [comment]
@Umcaruje I would not share that last gif xD 
(sorry for OT)

**Comment by zonkmachine** [comment]
:smiling_imp:

**Comment by musikBear** [comment]
I have to support @repsej here. I also miss a fx-indication on all channels.
I made a mockup long back in #355 
[https://cloud.githubusercontent.com/assets/6662066/6901309/a0ace260-d70c-11e4-9fa5-df65317cfedf.PNG](url)
The huge issue is the limited space, but it would be a very useful addition indeed 
As would a 'update-this-connection-to-fx-mixer' option.
Here would a click on the indicator, update the name in the fx-mixer.
This is especially need if older projects are opend, couse no track-names are inserted in the mixer. (1.2.1 or later)

**Comment by miketurn** [comment]
@repsej
I agree this is a great idea.
To be able to not only view the FX channel number but also be able to assign it from there as well would be a nice addition.
I like the idea of using the same "FX" double digit graphic to keep things looking the same and also the position of it, placing it right after the tracks label.
It does however take up a little extra space, that could probably be gotten back with removing a little bit of the padding around the gear icon and the mute/solo buttons, and maybe just extending the overall width a little beyond the pan knob.
Just keeping enough room for the label itself, without all of them getting cut off.
Just thought I would share my opinion on the matter.

**Comment by musikBear** [comment]
mockup of instrument-button with FX-mixer display.
The mute and solo buttons are changed to round diodes, and placed differently, to give a bit more space on the left side of the button
![instrumentbutton](https://cloud.githubusercontent.com/assets/6662066/21319071/faf05424-c60b-11e6-9192-c917b27a9dd0.PNG)
I think there is space enough for this, without destroying usability, and crowding the button.

**Comment by miketurn** [comment]
If this item is still being considered, 

Does anyone like something like this?
![track edit](https://cloud.githubusercontent.com/assets/24556082/22002362/878539ae-dc19-11e6-86e8-938028742627.JPG)

In my own opinion, I like the placement of where @repsej shows the FX Channel Number Window at the end of the tracks label, because you would read the Track Label first and then look for the Channel it is linked to, reading from left to right.

Moving the gear icon to the left and stacking the mute and solo buttons allows for more label space as well as the FX channel number window itself.

**Comment by BaraMGB** [comment]
Looks great!

**Comment by musikBear** [comment]
@miketurn 
> I like the placement of where @repsej shows the FX Channel Number

Only issue is if the instrumentname is l o n g, then it may need cutoff, so that placement makes it more complicated, but otherwise, fine

**Comment by BaraMGB** [comment]
> Only issue is if the instrumentname is l o n g, then it may need cutoff, so that placement makes it more complicated, but otherwise, fine

It needs to be elide (...) at the end anyway. This isn't implemented yet but should. Similar to the mixer label.

**Comment by miketurn** [comment]
I didn't realize that those labels didn't have that "elide", yeah that would be a nice idea to add that to all labels (instrument tracks, sample tracks, b+b tracks, automation tracks, audio files, etc.)

I think I mentioned this above but will mention it again, it would also be nice if the added FX channel number windows were interactive, meaning you can mouse scroll over it and assign the channel number you want to link to right from there, not just having them for show.

**Comment by jibin1573** [comment]
We can even place the mute/solo button vertically. Like this, link: https://m.imgur.com/a/MxG4XF6

**Comment by jibin1573** [comment]
We can also replace the gear icon with a spanner icon. It will provide even more space. Like this:
https://m.imgur.com/a/IdFduKk

(Please bear with the horrible art work. It is just to give an idea)

**Comment by tresf** [comment]
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.
