### ISSUE TITLE
LMMS hangs on opening project from Windows Recent File list

### ISSUE THREAD

**Issue by boulder74** [LMMS/lmms#257]
Opening a LMMS project via Windows Startmenu (Recent projects) LMMS hangs for occationally for several minutes:
![windowsstartmenurecent](https://f.cloud.github.com/assets/6583992/2076005/30400fd8-8d99-11e3-8326-f19d6d80692e.png)

It seems that the preconigured audio-interface gets somehow lost because afterwards following diaolg is displayed:
![windowsstartmenurecent2](https://f.cloud.github.com/assets/6583992/2076032/d783fa34-8d99-11e3-8640-8c7e164ca638.png)

Opening the same project via Windows Explorer (doubleclick) as well via the "project open" possiblities within LMMS (project open file dialog, recent project list, ... ) works fine

Win7 32bit

**Comment by badosu** [comment]
@boulder74 no feedback for a long time. Can we close this issue and reopen if necessary?

**Comment by tresf** [comment]
> Can we close this issue and reopen if necessary?

:+1:
