### ISSUE TITLE
Language dropdown is blank

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms#2577]
The language drop-down in the settings area is broken, at least on Windows.

* Tested using the 32-bit installer on Windows 10 x64.
* A clean removal of `~/.lmmsrc.xml` was **not preformed** prior to installation.

![image](https://cloud.githubusercontent.com/assets/6345473/13113035/649e22b8-d55b-11e5-9f57-167ae453a317.png)

@DanWin FYI.  Related #1497.

**Comment by michaelgregorius** [comment]
I cannot reproduce the problem on Linux in master but that's no surprise as it was already stated that it's a problem on Windows.

The language drop-down is filled by this code block in `SetupDialog.cpp`:
```C++
QDir dir( ConfigManager::inst()->localeDir() );
QStringList fileNames = dir.entryList( QStringList( "*.qm" ) );
for( int i = 0; i < fileNames.size(); ++i )
{
    // get locale extracted by filename
    fileNames[i].truncate( fileNames[i].lastIndexOf( '.' ) );
    m_languages.append( fileNames[i] );
    QString lang = QLocale( m_languages.last() ).nativeLanguageName();
    changeLang->addItem( lang );
}
```
My first guess is that it's one of these two:
* `ConfigManager::inst()->localeDir()` points somewhere with no `qm` files.
* The `qm` files are not copied into the locale dir during the installation (this should be quick to check).

@tresf Can you please check for the existence of `qm` files in your installation directory?

**Comment by tresf** [comment]
```cmd
C:\Users\tfinocchia>dir "C:\Program Files\LMMS\data\locale"
 Volume in drive C is Windows
 Volume Serial Number is 0AE0-C2BA

 Directory of C:\Program Files\LMMS\data\locale

02/17/2016  03:27 PM    <DIR>          .
02/17/2016  03:27 PM    <DIR>          ..
03/07/2015  09:55 PM           118,806 ca.qm
03/07/2015  09:55 PM           110,029 cs.qm
03/07/2015  09:55 PM           302,180 de.qm
03/07/2015  09:55 PM                16 en.qm
03/07/2015  09:55 PM            38,461 es.qm
03/07/2015  09:55 PM            37,233 fa.qm
03/07/2015  09:55 PM           231,627 fr.qm
03/07/2015  09:55 PM           197,454 gl.qm
03/07/2015  09:55 PM           293,007 it.qm
03/07/2015  09:55 PM            81,993 ja.qm
03/07/2015  09:55 PM            74,791 ko.qm
03/07/2015  09:55 PM            77,251 nl.qm
03/07/2015  09:55 PM           192,788 pl.qm
03/07/2015  09:55 PM           225,556 pt.qm
05/02/2015  05:16 AM             5,167 qtscript_eu.qm
05/02/2015  05:16 AM            55,319 qt_ar.qm
05/02/2015  05:16 AM           319,892 qt_cs.qm
05/02/2015  05:16 AM           119,822 qt_da.qm
05/02/2015  05:16 AM           325,046 qt_de.qm
05/02/2015  05:16 AM            82,411 qt_es.qm
05/02/2015  05:16 AM           236,038 qt_eu.qm
05/02/2015  05:16 AM           293,097 qt_fa.qm
05/02/2015  05:16 AM           255,103 qt_fr.qm
05/02/2015  05:16 AM           323,547 qt_gl.qm
05/02/2015  05:16 AM           215,294 qt_he.qm
05/02/2015  05:16 AM           272,162 qt_hu.qm
05/02/2015  05:16 AM           247,849 qt_ja.qm
05/02/2015  05:16 AM           241,938 qt_ko.qm
05/02/2015  05:16 AM           165,343 qt_lt.qm
05/02/2015  05:16 AM           316,133 qt_pl.qm
05/02/2015  05:16 AM            70,321 qt_pt.qm
05/02/2015  05:16 AM           288,364 qt_ru.qm
05/02/2015  05:16 AM           238,734 qt_sk.qm
05/02/2015  05:16 AM           228,388 qt_sl.qm
05/02/2015  05:16 AM            65,848 qt_sv.qm
05/02/2015  05:16 AM           215,985 qt_uk.qm
05/02/2015  05:16 AM           117,335 qt_zh_CN.qm
05/02/2015  05:16 AM           117,253 qt_zh_TW.qm
03/07/2015  09:55 PM           209,794 ru.qm
03/07/2015  09:55 PM            23,220 sv.qm
03/07/2015  09:55 PM            71,398 zh.qm
              41 File(s)      7,101,993 bytes
               2 Dir(s)  169,620,291,584 bytes free
```

**Comment by michaelgregorius** [comment]
@tresf Ok, seems like everything is there. My next step would be to build a broken version and print out the value of `ConfigManager::inst()->localeDir()` and some of the other stuff at the time when the drop-down is populated. Can you do that?

**Comment by tresf** [comment]
@michaelgregorius I can confirm that it's working properly Windows, but seems to be suffering an upgrade problem.  After deleting the `~/.lmmsrc.xml`, it's populating.

**Comment by michaelgregorius** [comment]
@tresf Does `~/.lmmsrc.xml` also store the locale directory? If yes: has the directory structure changed so that the old entry points at the wrong directory?

**Comment by tresf** [comment]
I take that back... this isn't an upgrade issue... Here's a fresh install and some values that look fishy after letting lmms create a brand new `~/.lmmsrc.xml`.

Note, Mallets crash on playback because the rawwaves can't be found.  Windows 10 x64 + 1.1.90 x64.

Tagging @Lukas-W as this is most likely related to the way config directories are stored in master.

```
artwork="data:\themes\default\"
stkdir="data:\stk\rawwaves\"
```

**Comment by Lukas-W** [comment]
I don't have any Windows machine to test on, so can somebody check if branch `iss-2577`(eec6c5b4f035168c0c5c6a63d1713665c6e66acd) fixes anything? If not, printing out `ConfigManager::inst()->localeDir()` would be helpful, as @michaelgregorius  suggested.
@tresf What exactly looks wrong to you in the config file? Just the path separators being `\` instead of `/` or the fact that the search path prefix `data:` is stored instead of an absolßte file path?

**Comment by tresf** [comment]
@Lukas-W the `/` tend to work just fine on Winßlows.  IMO, I'd like to abolish the `\` completely if we can (which eec6c5b seems to be addressing :smiling_imp: ).  They just cause problems. `</rant>` I'm not sure what the paths should look like now (I didn't compare), but Mallets definitely crashes, which I assume is also related.  I think something wrong is happening resolving the `data` directory on Windows.  Wine should be exhibiting the same exact issues.  I'll attempt to reproduce on Wine.

> printing out ConfigManager::inst()->localeDir() would be helpful

Getting console messages from Windows is quite painful, I'd have to use a `QMessgaeBox` instead (I'll pass on that).

> can somebody check if branch iss-2577(eec6c5b) fixes anything?

Yeah, I'll try that out

**Comment by DeRobyJ** [comment]
I have a question about this language selection system.
Are users able to create their language files, add them to the folder, and use them?

If yes, this can be used to freely create custom laguages for customization / theme / joke.


(oh, I'm on windows 7: public 1.1.90 has that dropdown broken too. I can test windows 7 and windows 8.1 64bit if necessary, however I can't build versions myself)

**Comment by tresf** [comment]
Well, no luck launching with Wine... I'm not sure what event is triggering the error, but this happens when the SettingDialog tries to show.  The software launches ok if the `~.lmmsrc.xml` exists, but crashes if it does not and subsequently crashes when trying to make the SettingDialog visible.

```
Couldn't initialize PortAudio: Internal PortAudio error
wine: Call from 0x7ff3f1e8ae6a to unimplemented function KERNEL32.dll.InitOnceBeginInitialize, aborting
```

**Comment by tresf** [comment]
> can somebody check if branch iss-2577(eec6c5b) fixes anything?

Yes, it fixes it. :+1: Mallets/STK still crashes tho... 

![image](https://cloud.githubusercontent.com/assets/6345473/13232587/c724d08c-d97d-11e5-8484-acca3988228d.png)

**Comment by tresf** [comment]
@DeRobyJ can you confirm the language issue is fixed here: [`tresf/lmms-1.1.90-geec6c5b-win64.exe`](https://github.com/tresf/lmms/releases/download/v1.1.90.1/lmms-1.1.90-geec6c5b-win64.exe)

**Comment by DeRobyJ** [comment]
It works.
There is a big group of languages which are blank tho
![screenshot_9](https://cloud.githubusercontent.com/assets/6437521/13233225/ff0b5f7c-d9b2-11e5-9368-b55ff44ab938.png)


(also, Mallets doesn't crash to me, win7 64bit)

**Comment by tresf** [comment]
> (also, Mallets doesn't crash to me, win7 64bit)

Please move your `%USERPROFILE%\.lmmsrc.xml` and try again. It will crash.

**Comment by tresf** [comment]
@Lukas-W is is safe to say we need to `QDir()` these [`mallets.cpp#L536`](https://github.com/LMMS/lmms/blob/master/plugins/stk/mallets/mallets.cpp#L536)?  Since Linux uses a hard-coded path, this problem wouldn't surface unless tested on Windows.

**Comment by DeRobyJ** [comment]
When .lmmsrc.xml is moved and the program is launched, it promptly asks for a working directory. Then it creates the file and the problem is fixed...
Well, at least it's like that on windows 7

**Comment by Lukas-W** [comment]
> is is safe to say we need to QDir() these

Yep, that should do. Just wrap a `QDir(…).absoluteFilePath()` around it.

**Comment by tresf** [comment]
> When .lmmsrc.xml is moved and the program is launched, it promptly asks for a working directory. Then it creates the file and the problem is fixed...
Well, at least it's like that on windows 7

I should have been more specific... Mallets doesn't crash, playing a sound with mallets crashes (because the stk rawwaves directory is not a valid path, so once you try to play any note with any Mallet preset (including the Default preset) the plugin will crash and take LMMS down with it.  The only way this would work on any Windows machine with a fresh config file is if someone had manually clicked the "Browse" folder icon and click "Use Folder" and then used Mallets, but of course, that's circumventing the problem. :beer: 

> Yep, that should do. Just wrap a ~~`QDir(…).absoluteFilePath()`~~ `QDir(…).absolutePath()` around it.

FTFY and done via https://github.com/LMMS/lmms/commit/d88902e95bc88ae77e6c75aee40ac945a0c5f324, once the branch is merged. :beers:

**Comment by Lukas-W** [comment]
> done via d88902e

Does it fix the crash?

**Comment by tresf** [comment]
> > done via d88902e
> Does it fix the crash?

Sorry forgot to mention that part... yes it does. :+1:

**Comment by Lukas-W** [comment]
:+1:

**Comment by tresf** [comment]
Partially fixed per https://github.com/LMMS/lmms/issues/2611#issuecomment-191564863 via 85011cd.

This is still going to be a problem for Windows until this recommendation is done. https://github.com/LMMS/lmms/pull/1498#issuecomment-189782211

Reopening until we've shimmed our Windows packagers, documentation and Travis-CI scripts.

Test results (Apple):
![screen shot 2016-03-03 at 12 37 08 am](https://cloud.githubusercontent.com/assets/6345473/13485679/4ccb49da-e0d8-11e5-9d9f-f576c9881805.png)
