### ISSUE TITLE
Add MIDI export

### ISSUE THREAD

**Issue by davidgerard** [LMMS/lmms#258]
LMMS presently only saves in LMMS XML, which nothing else reads.

Pretty much everything ingests MIDI, so MIDI export of LMMS projects would greatly increase interoperability.

**Comment by mohamed--abdel-maksoud** [comment]
Hey, I've been a silent fan of lmms for a while and I'd like to see the MIDI export added. I volunteer to implement it if needed.

**Comment by tresf** [comment]
@mohamed--abdel-maksoud,

Great.

It doesn't appear anyone else is actively working on it.  Please issue a pull request once you start so we know progress is being made and have the opportunity to offer advice asking the way. :)

**Comment by badosu** [comment]
@mohamed--abdel-maksoud Amazing! Any help is greatly appreciated :-)

**Comment by mohamed--abdel-maksoud** [comment]
cool, I'll have a go on it from today, wish me luck :)

**Comment by curlymorphic** [comment]
> cool, I'll have a go on it from today, wish me luck :)

nice :)

**Comment by badosu** [comment]
First of all I want to thank @mohamed--abdel-maksoud for the outstanding work on the MIDI import feature.

Now I want to ask here if it's desirable that we are able to export only a single instrument track to MIDI, instead of the whole project.

**Comment by Sti2nd** [comment]
It is not that important, since you can delete the undesired tracks in another program anyway, but it can be useful I guess. So if you want to do it, it can't harm?

**Comment by tresf** [comment]
> Now I want to ask here if it's desirable that we are able to export only a single instrument track to MIDI, instead of the whole project.

Well, obviously we'd take anything that improves the software but moving forward, this may prove to be useful, perhaps for a drum beat once we start to focus a bit more on dedicated drum instrument tracks (we instead tend to use a bunch of independent tracks for a drum pattern).  I'm also not sure if this would warrant a dedicated context menu or button per-instrument.  What do you think @badosu?

**Comment by badosu** [comment]
I was thinking of using the instrument context menu on the widget, that `wheel` button. Anyway, @mohamed--abdel-maksoud has already implemented modularized track export, so if this is needed in the future it's easy to do.

**Comment by tresf** [comment]
FYI, this has been implemented for the future 1.2 release per #1686.  Added to release notes. :+1:

**Comment by dednikko** [comment]
Yeaaaahhhh! I just want to let you know how much this will improve my life.
You guys rock so hard!

**Comment by tresf** [comment]
:)

Big thanks to @mohamed--abdel-maksoud for the hard work. :+1:

**Comment by mohamed--abdel-maksoud** [comment]
> FYI, this has been implemented for the future 1.2 release per #1686. Added to release notes. :+1:
Great news!

> Big thanks to @mohamed--abdel-maksoud for the hard work. :+1:
I've had great time working on this feature, lmms is a beautiful piece of software :)

**Comment by Baccanno** [comment]
> On 10/15/2014 05:20 PM, M=== ===== wrote:
> 
> > Hey guys, what about any MIDI export solution ? It seems like a must
> > have feature for any music composing software.
> 
> Are you volunteering to implement it?

Hi sorry to bother you on another subject. Could you remove my personal name from your quote ? Best regards.

**Comment by Spekular** [comment]
@Baccanno I've edited the post now. FYI quoting you now gives

> > On 10/15/2014 05:20 PM, M=== ===== wrote:

**Comment by Baccanno** [comment]
Thank you very much
