### ISSUE TITLE
-DWANT_MINIMAL

### ISSUE THREAD

**Issue by zonkmachine** [LMMS/lmms#2580]
Git bisect is a wonderful tool but it takes time. I suggest, just a thought, that we make a
new compile option MINIMAL which lets you build lmms without most of the pluggins.
We have little use of it today but I suspect that we'll have good use of it a year from now.
Many times when I bisect I test against the previous stable release so for this to work it
should be included now for 1.2

```
ADD_SUBDIRECTORY(kicker)
ADD_SUBDIRECTORY(triple_oscillator)

IF(NOT WANT_MINIMAL)
ADD_SUBDIRECTORY(Amplifier)
ADD_SUBDIRECTORY(Bitcrush)

...


ENDIF()
```

Test builds after make clean. This doesn't mean that an actual bisect will take half the time but it will cut it significantly. Two lines of code well spent I say.

```
cmake .. -DCMAKE_INSTALL_PREFIX=../target -DCMAKE_BUILD_TYPE=DEBUG

real	5m50.047s
user	9m55.876s
sys	0m51.896s


cmake .. -DCMAKE_INSTALL_PREFIX=../target -DCMAKE_BUILD_TYPE=DEBUG -DWANT_MINIMAL=ON

real	2m44.669s
user	4m43.520s
sys	0m24.904s
```

**Comment by jasp00** [comment]
Other projects allow to set the list of components to build. `-DPLUGIN_LIST="audiofileprocessor kicker tripleoscillator"` would be more flexible than `-DWANT_MINIMAL`.

**Comment by Lukas-W** [comment]
As discussed in #2581, you can use

    make lmms audiofileprocessor kicker tripleoscillator

Closing.

**Comment by zonkmachine** [comment]
As per my comment [here](https://github.com/LMMS/lmms/pull/2907#issuecomment-231615004) I think this is still not solved. I need to be able to also install `make install` the 'minimal' build, that's just my experience from bisecting a whole lot. So far the only solution that's worked as I intended was my original hack in #2581. That said I know preciously little about make and cmake...

**Comment by Umcaruje** [comment]
I'm not very expirienced with cmake and have no idea how to proceed in my PR. From what I gather from @tresf 's findings it would also require hacks to the CMake files to make it work as make install, and I'm not comfortable with making those changes, and also fail to see how they are better than @zonkmachine 's original solution. So I'm probably going to close my PR.
