### ISSUE TITLE
Equalizer wrong label

### ISSUE THREAD

**Issue by DeRobyJ** [LMMS/lmms#2583]
1.1.90 windows 7 64bit

The first bandpass filter has "resonance" instead of "bandwidth" in the knob editing label.
(and "octaves" is missing too)
![screenshot_1](https://cloud.githubusercontent.com/assets/6437521/13144862/50d87812-d64d-11e5-9cf6-8d95e5f643b9.png)

should be:
![screenshot_2](https://cloud.githubusercontent.com/assets/6437521/13144904/9344809c-d64d-11e5-827b-a979c8160407.png)

The line designed in the graph is correct, thought: it's horizontal like other bandwidth, while the high pass and low pass resonances are drawn as a vertical line.

**Comment by waxspin** [comment]
@DeRobyJ This was a quick fix-- I also fixed the highest (6th band) label too-- also incorrect I believe.  I will post a build for you to test.

**Comment by waxspin** [comment]
@DeRobyJ You can find a win64 test build [here](https://github.com/waxspin/lmms/releases/download/p2592/lmms-1.1.90-gc4038fb-win64.exe).

**Comment by DeRobyJ** [comment]
It's fixed.

**Comment by tresf** [comment]
Closed via #2592.

**Comment by zonkmachine** [comment]
> The first bandpass filter...

Those filters in between the Lo/Hi-pass and the bandpass filters are resonant shelving filters. The knob models for them has a suspicious "res" in them. The new gui looks correct to me.
That said, I'm in no way an authority on filter design... 

![shelvingfilter](https://cloud.githubusercontent.com/assets/6368949/13200565/08ebc682-d84e-11e5-82a4-8da2f0c386f5.png)

**Comment by waxspin** [comment]
@zonkmachine I am confused as to the issue then... in the UI as reported by @DeRobyJ above, they were incorrectly labeled as to their functionality, and are now fixed.  Not sure why this was reopened, but if you can explain I'd be happy to take a look again.

**Comment by waxspin** [comment]
@zonkmachine Ah, I think you're saying that the confusion exists in the difference between the actual functionality, and the UI.  I apologize-- it appears that the UI design is confusing then.  I think the models for those knobs DO appear to be resonance models, so the indexing was correct previously, but the fact that this is the case is not at all obvious from the UI design in the old design... is that it?  If so, I could change them back, although I additionally added an internationalization tr() call that was missing previously, so we will want to leave that in.  However, I'm not sure if there's a fix we would want other than a less confusing UI layout, as you show in your example...

**Comment by waxspin** [comment]
As an additional note, are you looking at a mockup, or is that UI implemented somewhere...  The broken design exists in master, which is why it appeared "fixed" to @DeRobyJ after I posted said build.  That build can be found [here](https://github.com/waxspin/lmms/releases/download/p2592/lmms-1.1.90-gc4038fb-win64.exe) if you're interested in testing it.

**Comment by zonkmachine** [comment]
> but the fact that this is the case is not at all obvious

Indeed not. I had to read up on filters a bit here. 

> are you looking at a mockup, or is that UI implemented somewhere...

This is the new UI just merged into master. Give it a go! :-P

**Comment by waxspin** [comment]
Thanks!  I'll pull the latest and fix this tonight.

**Comment by zonkmachine** [comment]
> If so, I could change them back, although I additionally added an internationalization tr() call that was missing previously, so we will want to leave that in.

Just revert the label fix and not the translation part.

**Comment by zonkmachine** [comment]
> Thanks! I'll pull the latest and fix this tonight.

:+1:

**Comment by waxspin** [comment]
@DeRobyJ @zonkmachine A test build for the partial rollback, including the new UI is available [here](https://github.com/waxspin/lmms/releases/download/p2598/lmms-1.1.90-g34ae074-win64.exe).

**Comment by DeRobyJ** [comment]
Oh I see...
Tested, Now it works as intended, with 2 resonances, 4 bandwidths and 2 more resonances.

**Comment by zonkmachine** [comment]
Fixed, closing! :beers:
