### ISSUE TITLE
Instrument in Midi Export

### ISSUE THREAD

**Issue by DeRobyJ** [LMMS/lmms#2585]
Just a note for future development.
Currently, it is possible to select a "program" for midi output.
It would be nice to actually keep that program number in midi export, so you can select the instrument.

For drumkits, we need also an instrument bank selection.
Or, we may get both from Sf2 player if it's used in the track.

This feature quickly leads to easy midi editing with lmms.

**Comment by Fastigium** [comment]
Midi Export is in need of an overhaul anyway, perhaps this could be added in the process. Please think along at #2384 if you want to speed things up.

**Comment by DeRobyJ** [comment]
Can be closed since it's part of #2384

**Comment by tresf** [comment]
> Can be closed since it's part of #2384

You have the ability to close your own bug reports. :+1:

**Comment by DeRobyJ** [comment]
Oh ok
closed as part of #2384
