### ISSUE TITLE
Piano Roll new alt+arrows shortcut always goes on previous

### ISSUE THREAD

**Issue by DeRobyJ** [LMMS/lmms#2588]
- Create some blocks in an instrument track with different notes
- Open one of them
- Alt+left works
- Alt+right goes left too

Windows 7 64bit 1.1.90

**Comment by zonkmachine** [comment]
@Wallacoloo 
Change happened in this commit: 8504633103f665cb69d6732b110d5c8cb40a6c6c

**Comment by Wallacoloo** [comment]
Hey @zonkmachine, thanks for tracking down the source & tagging me. I confirmed the bug on my system & I'll try to whip up a fix for it, if I'm in a good enough state of mind to deal with that section of code.

**Comment by Wallacoloo** [comment]
Okay, here's a fix for it: #2591. It turned out to be really straightforward.
