### ISSUE TITLE
Extra flat theme

### ISSUE THREAD

**Issue by IvanMaldonado** [LMMS/lmms#2590]
Now that we are at it...

I would like to propose another theme for the LMMS as an 'extra' for the people (who like me) like flat designs without gradients (pretty much what google has been doing lately).

This is the theme I am using as a reference:

![x8l8e7c](https://cloud.githubusercontent.com/assets/12549082/13164010/a066cf4e-d677-11e5-92e8-9eeb22970af6.png)

And this is my current progress: 

![current](https://cloud.githubusercontent.com/assets/12549082/13164049/f69105a6-d677-11e5-8cbf-0a79d0658187.png)

I still have to work with the new gradient-free possibilities made possible via   
7d874fc and  2869d53

I will also change some graphics (like the knobs and other things that doesn't match very well)

I hope I'll have your support guys, thank you for the new possibilities provided!

**Comment by rubiefawn** [comment]
:heart: would use.

**Comment by tresf** [comment]
@IvanMaldonado we appreciate your hard work, but we don't usually open a new bug report for each theme proposal, we have [LSP](https://lmms.io/lsp) for that.

In the case of the #2587 theme, this theme has been planned and coordinated by several developers over the course of almost 2 years, which is why it is a good candidate and why it doesn't come as a surprised proposal.  Furthermore, we don't yet have a theme-switcher, and even if we did, we can't maintain too many themes at once.

I'll kindly ask that you help us with the #2587 effort for now and we encourage you to share your theme though whatever means necessary.

**Comment by IvanMaldonado** [comment]
It's a shame, I just want to clarify that the only reason I made this is because I thought other people would like to have an extra theme, just like the classic theme will also be there. If you feel there can't be other themes incluided with the standard install, I respect that. :+1:

I was thinking that maybe some themes from the LSP from other designers would also be well accepted by the community, since not many LMMS users know about the LSP and not everyone enter the forum. Most of the people I have known in other forums say that one of the main reasons they don't use LMMS that often is because of the look, I was thinking that maybe adding more than one look, could satisfy a bigger group of people but this is just my idea, I know there are a lot of other more important things that must be worked on.

I accept what you say and maybe I was too impatient to change the look of LMMS (the issues I open are all about the look).

Just one question: what did you mean with this?

> we can't maintain too many themes at once.

**Comment by tresf** [comment]
> Just one question: what did you mean with this?

> > we can't maintain too many themes at once.

Once we accept a theme into our codebase, we need to maintain it.  This means if a class in our codebase changes from `sf2Instrument` to `Sf2Instrument`, we have to modify it in every theme we bundle.

If our code was a bit more stable from a namespace perspective, this wouldn't be an issue, but as long as it is (and it will continue to be for a few more years), we have to do what's necessary to ship with sane defaults.

Even the idea of shipping both `Noir` and `Classic` (for lack of better names) is a difficult decision.  We may pull `Classic` at the last minute to prevent this same issue (although both are feature-complete for the 1.2 release, so we'll see how that goes).

What I think many people would like is the ability to quickly switch between dark/lite themes, which we may eventually offer support for, but even [QtCreator struggles with that](http://stackoverflow.com/questions/2244774/qt-creator-color-scheme), so this isn't a trivial task.

-Tres

**Comment by RebeccaDeField** [comment]
@IvanMaldonado I sent you an email with some resources for this theme :)
