### ISSUE TITLE
Getting rid of the Mixer padding

### ISSUE THREAD

**Issue by IvanMaldonado** [LMMS/lmms#2593]
I think we could get more workspace if we reduce the mixer padding like this:

![mixer](https://cloud.githubusercontent.com/assets/12549082/13186921/f90b5822-d70d-11e5-9700-e07d37778525.png)

So it can match the padding used in the b+b editor:

![specimen3](https://cloud.githubusercontent.com/assets/12549082/13186934/0e521c3e-d70e-11e5-94e9-319b2d4f888d.png)

Before and after:

![specimen4](https://cloud.githubusercontent.com/assets/12549082/13186950/27dfbf30-d70e-11e5-9ebc-6eb161bc75ce.png)

![specimen5](https://cloud.githubusercontent.com/assets/12549082/13186956/2be4f1cc-d70e-11e5-8f8b-218adab3198e.png)

**Comment by tresf** [comment]
:+1: Please do.

**Comment by Umcaruje** [comment]
Yes, this has been bugging me as well. :+1:

**Comment by midi-pascal** [comment]
:+1:
