### ISSUE TITLE
Memory-Leak on unloading projects with VeSTige plugins?

### ISSUE THREAD

**Issue by boulder74** [LMMS/lmms#260]
- new project (i.e. Proj1) and create 1 VeSTige plugin
- link a VST-instrument (library) to it -> i've used "Synth1 VST.dll"
- save the project
- open new project
- open Proj1 again
- open new project
.... 

In the taskmanger at the LMMS process you will see that the virtual memory will increase (commit size) ... 
![memleak](https://f.cloud.github.com/assets/6583992/2076339/81701758-8d9f-11e3-8fd5-f105925de1e3.png)

Win7 32bit

Edith says: note - this was only with 1 VeSTige plugin - having a project with many VeSTige plugins may fill up the used memory more faster....

**Comment by Umcaruje** [comment]
@boulder74 can you still reproduce this issue?

**Comment by Umcaruje** [comment]
No response from OP in almost 2 months. Closing. Please reopen if you can still reproduce.
