### ISSUE TITLE
Update readme about FX Mixer

### ISSUE THREAD

**Issue by DeRobyJ** [LMMS/lmms#2600]
Readme.md still has:
- An FX mixer with _64 FX channels_ and arbitrary number of effects allow unlimited mixing possibilities

I didn't change it myself because I don't know how to update it properly, my bad English...
We need to state that channels are arbitrary and we have sends

**Comment by tresf** [comment]
> We need to state that channels are arbitrary and we have sends

I'm not adding the sends portion to the readme but if you feel it needs to be added to our home page, feel free to open an issue at the lmms/lmms.io repo.
