### ISSUE TITLE
LMMS doesn't store some zynaddsubfx data well

### ISSUE THREAD

**Issue by DeRobyJ** [LMMS/lmms#2601]
It appears that when loading a preset or even closing the Zyn GUI, lmms loses some data.
To reproduce:
- Create a ZynAddSubFX track
- Open Zyn GUI and go to Scales menu (top right of the main window in advanced mode, not available in beginner mode)
- Enable Microtonal

(for info about that window, here is the wiki: http://zynaddsubfx.sourceforge.net/doc_2.html#w2 )

Now, in the first big text field, you are supposed to input two different kind of data:
- semitone cents in a float number (they work), the first 11 defaults are like that (100.00, 200.00, etc)
- frequency ratio as an integer divided by another one, the last default is for example 2/1

So first problem is:
if you enter an integer major than 127, lmms will read it right, but if you cose and re-open the GUI it will be changed to 127
So for example I may want to write 400/17, closing and re-opening will give me 127/17

Now let's go to the keyboard mapping field.
As stated in the wiki, if you want to skip a key, you place an "x" instead of a number.
LMMS once again works if the GUI is left open, but then if it's closed and re-opened all the x change to 0.

(Please note that to hear the difference after a change you need to click the "Retune" button)
I'm on 1.1.90, but I think it's the same in earlier version.

**Comment by softrabbit** [comment]
For this to work, LMMS would need to invoke the "save scale settings" code in Zyn and capture the ``.xsz`` file created. Something similar is done to patch files already. 

Even better would IMO be to implement #1387 and patch Zyn to accept MIDI tuning messages (which currently aren't supported, https://github.com/LMMS/lmms/issues/1387#issuecomment-94803770)

**Comment by DeRobyJ** [comment]
I agree for both options, but the second one wouldn't be a fix: users trying to use a zyn preset (.xiz) with a scale (which can't be exported by zyn itself, asaik) will have to rewrite that into the program. They may eventually do it anyway, though...

**Comment by DeRobyJ** [comment]
Closing this, it woulb be way better to implement #1387 !
