### ISSUE TITLE
sample tracks and mixer tracks

### ISSUE THREAD

**Issue by mqbaka** [LMMS/lmms#2619]
I think It should be good if we can assign a sample track to a mixer track. Is it possible?

**Comment by Umcaruje** [comment]
@mqbaka Please, please search the issue tracker if you request exists before posting a new issue:
![screenshot from 2016-02-29 11 12 29](https://cloud.githubusercontent.com/assets/6282045/13391600/9fa666e4-ded5-11e5-8736-c1b75bf7e236.png)

**Comment by Umcaruje** [comment]
Duplicate of #1471
