### ISSUE TITLE
w10 RC2 wrong knob position 

### ISSUE THREAD

**Issue by oeai** [LMMS/lmms#2620]
![lmms 1](https://cloud.githubusercontent.com/assets/2557665/13406458/af85638a-df34-11e5-9d9e-61cd55ca9b2b.png)
![lmms 2](https://cloud.githubusercontent.com/assets/2557665/13406686/e17a9878-df35-11e5-89c5-fb96ff5d6a21.png)

all instruments knob pointers are in wrong position
this one from kicker but also in tripleoscillator for example
this pointer works somewhere at left+top corner

**Comment by tresf** [comment]
@oeai please properly uninstall LMMS first (like all version) and stop opening bug reports.

**Comment by oeai** [comment]
i've uninstalled LMMS (there was only 1.1.90 in programs list) then installed it back
lmmsrc.xml is 1.1.90
both errors are there

**Comment by Umcaruje** [comment]
Your `lmmsrc.xml ` is pointing to an outdated theme. Please clear out the theme field in your settings, and your LMMS will reset to the default theme.

**Comment by oeai** [comment]
ok, i found it, i'm using x64 version and theme was set to x86
C:\Program Files (x86)\LMMS\data\themes\default\\
some older version really exist there

**Comment by oeai** [comment]
thank you, both errors gone.

**Comment by tresf** [comment]
> C:\Program Files (x86)\LMMS\data\themes\default\

Which should be gone if you properly uninstalled.

I assume this time you installed the 64-bit version, so you had to versions installed side-by-side, which is not yet supported.

**Comment by oeai** [comment]
well, installator needs more work, but i don't see it in rep
when i uninstalled x64 version, x32 wasn't in list and there's only 1 version LMMS for all, 
so when i uninstalled x32, then x64 was also deleted from list of installed programs.
i'd use some registry marks for versions and installators so it was proprely registered in programs and removed if there is already some version or if they are together.
in fact i've installed just to test, usually i prefer stable version not beta and you know, just click-click-click and whatever it asks, it's alright if it works.
