### ISSUE TITLE
w10 RC2 Zyn can't get preset banks

### ISSUE THREAD

**Issue by oeai** [LMMS/lmms#2621]
maybe it's because of some restrictions for Program Files folder
there's a folder data:/presets/Zyn but there's no banks in Zyn
if i manually add c:/program files/lmms/data/presets/Zyn and then refresh banks 
then i can work with it, but after lmms restart i got to redo that
better solution is in placing it somewhere in Users/AppData or somewhere else in user folder
or maybe only config files should be in a user writable directory.

**Comment by tresf** [comment]
@oeai something sounds wrong.  Where did you get RC2 from?  Are you abbreviating something? We've never called it `Zyn`.  How are you browsing, using the sidebar or Zyn itself?

**Comment by oeai** [comment]
https://lmms.io/download/#windows

**Comment by tresf** [comment]
There's no RC2 there.  From your other bug report (theme bug) I suspect you never uninstalled.  If you did, the `%USERPROFILE%/.lmmsrc.xml` has your old config in it, duplicate of #2615.

Regardless, you've been on our tracker for far too long to be spamming it with new bug reports.  Please be courteous of our developers, they read every-single bug report.

**Comment by oeai** [comment]
well really i didn't uninstall expecting that uninstaller will do that for me

**Comment by tresf** [comment]
> well really i didn't uninstall expecting that uninstaller will do that for me

No, it's never done that.  Take a crack at it if you'd like though: https://github.com/LMMS/lmms/blob/master/cmake/nsis/CMakeLists.txt

Here's one of many examples:
http://nsis.sourceforge.net/Auto-uninstall_old_before_installing_new

But this specific bug is better explained in #2615.  The preferences really don't upgrade well between versions, so if you really want this fixed for all platforms, we're open to ideas. :+1:
