### ISSUE TITLE
Move an object in the stylesheet

### ISSUE THREAD

**Issue by IvanMaldonado** [LMMS/lmms#2630]
> Anyways, this conversation is entirely pointless on this PR and has 0 relevance to it.
Issue a Pull Request or open an issue about this if you want, I'm locking this.

Just did.

> No it shouldn't look like that, you just made the play and stop buttons square again...

No, I didn't
![4](https://cloud.githubusercontent.com/assets/12549082/13513401/3f09d86e-e166-11e5-8e31-1b84d627e5b0.png)

Ignore the .css edit, I'm just talking about the position of the text on the stylesheet

Also, the 1.1.3 stylesheet has this object in the position I'm telling you but titled as "QToolButton, toolButton"

**Comment by Umcaruje** [comment]
Please make your request clear in the new issue, better yet, fork the repo and just make the changes you want. Reviewing that will be a lot easier than hypothetically talking here :)

**Comment by IvanMaldonado** [comment]
Closed as the PR now exists.
