### ISSUE TITLE
Add a colored rectangle in the loop area

### ISSUE THREAD

**Issue by IvanMaldonado** [LMMS/lmms#2635]
![flat](https://cloud.githubusercontent.com/assets/12549082/13543985/4fbd4f3a-e236-11e5-94f5-2c1442c3c5aa.png)

Adding just a rectangle with 20% opacity can help us to easily detect where we are working without having to locate the indicators individually and it also looks sexy as hell.

**Comment by michaelgregorius** [comment]
@IvanMaldonado Implemented with #2657.

**Comment by IvanMaldonado** [comment]
@michaelgregorius Muchas gracias! :smile: :+1:

**Comment by tresf** [comment]
@IvanMaldonado this issue will be closed automatically when the PR is merged.  No need to close it prematurely. :+1:

**Comment by zonkmachine** [comment]
Closed in #2657
