### ISSUE TITLE
"Solo" terminates the sound in every send

### ISSUE THREAD

**Issue by IvanMaldonado** [LMMS/lmms#2637]
Not sure if this is intended or not.

What I get:

![captura de pantalla_2016-03-05_00-31-50](https://cloud.githubusercontent.com/assets/12549082/13546141/ee1843b4-e269-11e5-8ae4-8eca7066f4c6.png)

(There isn't any instrument in this channel, just the sends)

What I expect:

![captura de pantalla_2016-03-05_00-32-45](https://cloud.githubusercontent.com/assets/12549082/13546144/f35c56bc-e269-11e5-84b0-8719fcdac3bf.png)

EDIT: Making an instrument 'solo' on the mixer stops making sense once you send the signal to another channel.

**Comment by tresf** [comment]
You're clicking "solo" not "mute".  This is how solo behaves.  When I click the green indicator, non-related instruments routed through similar channels continue to play.  I think this is you confusing the purpose of the buttons.

Maybe solo doesn't make much sense when dealing with sends, but that's a "smart solo" feature, which is much (much) more complex than what we have today.

**Comment by IvanMaldonado** [comment]
Tresf Youre right, I don't know why I wrote Mute instead of Solo, anyway, I don't know much about programming but couldn't it just be like:

Channel 1, channel 2, channel 3... Channel n = true 
If channel1.solo = true then channel 2, channel 3... Channel n = false
If channel n -> channel 1 = true then channel n = true and channel 2, channel 3... n+1 = false

Just remembered what I learnt in school

**Comment by tresf** [comment]
@IvanMaldonado what if other instruments are routed through the sends?  Are the sends intelligent enough to mute **only those instruments which have been exclusively marked for playback** ?  This sounds like it will only confuse people.

**Comment by Umcaruje** [comment]
Well, the solo function could be a bit more intelligent. For example, if Have 4 channels:  'Kick', 'Snare' 'HiHat' and 'Drums'.  'Kick', 'Snare' and 'HiHat'  all send to 'Drums' rather than to master. When I solo 'Drums', I expect to hear the output of the other 3 tracks as well.

**Comment by IvanMaldonado** [comment]
Alright, I will close this and see if there is a good chance to pull a smart solo feature in the future. :+1:

**Comment by softrabbit** [comment]
> Well, the solo function could be a bit more intelligent. For example, if Have 4 channels: 'Kick', 'Snare' 'HiHat' and 'Drums'. 'Kick', 'Snare' and 'HiHat' all send to 'Drums' rather than to master. When I solo 'Drums', I expect to hear the output of the other 3 tracks as well.

You're basically saying the sends should be "tapped" from the signal before the mute/solo function?
