### ISSUE TITLE
Making the name of plugins translatable 

### ISSUE THREAD

**Issue by liushuyu** [LMMS/lmms#2639]
I found that plugins names are hard-coded and not be able to be translated. Therefore, making it more difficult for translators and users to translate and use LMMS.

Currently, and I found the template of a LMMS plugin is:
```C++
Plugin::Descriptor PLUGIN_EXPORT YourPluginNameHere_plugin_descriptor =
    {
           STRINGIFY( PLUGIN_NAME ),
           "YourPluginNameHere",
           QT_TRANSLATE_NOOP( "pluginBrowser",
                               "YourPluginDescriptionHere" ),
           "YourNameHere <YourEmailAdressHere>",
           0x0100,
           Plugin::Instrument,
               new PluginPixmapLoader( "logo" ),
               NULL,
               NULL
    } ;
```
It's  obvious that the name `"YourPluginNameHere"` cannot be marked by linguist tool.
AFAIK, to do this, `QT_TRANSLATE_NOOP` should be used: http://doc.qt.io/qt-4.8/qtglobal.html#QT_TRANSLATE_NOOP

But, somehow I tested and this didn't work 

So, any ideas?

**Comment by Umcaruje** [comment]
Why would we even make the instrument names translatable? They are names, and as such they shouldn't be translated. 

Imagine a spanish user reading our english documentation, and his confusion when he starts looking for a plugin in his software, but can't find it since the name is different.

**Comment by midi-pascal** [comment]
@Umcaruje :+1:

**Comment by liushuyu** [comment]
Maybe I didn't state clearly about my opinion:
>Why would we even make the instrument names translatable? They are names, and as such they shouldn't be translated. 
I also agree this to some extent, for terms shouldn't be translated in common cases.

>Imagine a Spanish user reading our english documentation, and his confusion when he starts looking for a plugin in his software, but can't find it since the name is different.

Yes, I'm aware of that. I mean, provide a chance for developer to choose whether the name can be translated. For instance, the string "LADSPA Plugin Browser" also exists in main UI,
thus making it awkward:

![spectacle qv98281](https://cloud.githubusercontent.com/assets/6829345/13554689/b5e7b480-e3e9-11e5-83e0-296e8e6ab614.png)

"LADSPA Plugin Browser" is not marked translatable for example, but I personally think we should translate it.

**Comment by liushuyu** [comment]
Alright, it seems that you are not agreed to do this, that's also fine to leave them 'as-is'
Closing
