### ISSUE TITLE
Ideas for the plugins' icons

### ISSUE THREAD

**Issue by IvanMaldonado** [LMMS/lmms#2646]
I've worked on some ideas for the icons of some effects we have. I have to remark these are just ideas and not design proposals (As you will see, I draw like a kindergarten kid).

Some of them are conceptual, other funny, I hope you can get a good interpretation of them. :+1: 

Waveshaper

![sh](https://cloud.githubusercontent.com/assets/12549082/13561844/44e93c6e-e3f7-11e5-8876-12d789e6081a.png)

Stereomatrix

![stereo](https://cloud.githubusercontent.com/assets/12549082/13561848/4f32b218-e3f7-11e5-8a57-1ebf4ff8181d.png)

Spectrum analyzer

![spec](https://cloud.githubusercontent.com/assets/12549082/13561852/572c1f68-e3f7-11e5-9574-3fe6c3147c76.png)

Peak controller

![peak](https://cloud.githubusercontent.com/assets/12549082/13561853/5b9f1ec4-e3f7-11e5-8b9e-2bbc075f63a7.png)

Flanger

![flanger](https://cloud.githubusercontent.com/assets/12549082/13561855/624e904c-e3f7-11e5-80f8-712bd05f7335.png)

Bitcrush

![crusher](https://cloud.githubusercontent.com/assets/12549082/13561861/660cddd8-e3f7-11e5-9d92-033f2fffdb1e.png)

Dynamics processor

![dyn](https://cloud.githubusercontent.com/assets/12549082/13561862/6bafc8cc-e3f7-11e5-8878-177d63788a51.png)

Delay

![delay](https://cloud.githubusercontent.com/assets/12549082/13561864/6f9e37de-e3f7-11e5-94fb-05dbc4c6791c.png)

Amplifier

![amp](https://cloud.githubusercontent.com/assets/12549082/13561870/736abd4c-e3f7-11e5-8749-92134ca15256.png)

All of them in their original sizes

![captura de pantalla_2016-03-06_23-57-44](https://cloud.githubusercontent.com/assets/12549082/13561874/7e0e2e6e-e3f7-11e5-9cc4-df23a7d9cc20.png)

**Comment by liushuyu** [comment]
Wow, looks like pixel art 😃
I think this is somehow beautiful ()

**Comment by SimoneIervasi** [comment]
Nice ideas! The only thing i don't like is the Pac-Man monster in the spectrum analyzer icon :)

**Comment by tresf** [comment]
> these are just ideas and not design proposals (As you will see, I draw like a kindergarten kid).

We appreciate you sharing.

> Some of them are conceptual, other funny, I hope you can get a good interpretation of them.

If you don't have a bug or enhancement to report, I'd suggest closing this out and referencing it down the road.

On a side note, the smaller version is plenty.  I'm not sure what the large drawings aim to achieve, but they make the issue much harder to read... 

![screen shot 2016-03-09 at 1 24 28 am](https://cloud.githubusercontent.com/assets/6345473/13627090/c963e198-e595-11e5-8559-ccdf8796169b.png)

**Comment by IvanMaldonado** [comment]
@tresf I know I have read somewhere here that it would be good to change the penguin that is already being used as an icon for the plugins, maybe it will be a good idea to reference it to that comment.

> On a side note, the smaller version is plenty. I'm not sure what the large drawings aim to achieve, but they make the issue much harder to read... Web pages just aren't supposed to be navigated this way... 

When I first uploaded the image with the original sizes I found them hard to see, that's why I did it this way.

**Comment by tresf** [comment]
> @tresf I know I have read somewhere here that it would be good to change the penguin that is already being used as an icon for the plugins, maybe it will be a good idea to reference this to that comment.

Yeah, I had implied this was the intention, but currently @Umcaruje and @RebeccaDeField are working very hard on the branding portions and this isn't in alignment with their designs or our current design in my opinion.  I'm not trying to be critical of the artwork specifically, but rather what the end goal of this bug report is.

**Comment by IvanMaldonado** [comment]
> currently @Umcaruje and @RebeccaDeField are working very hard on the branding portions and this isn't in alignment with their designs or our current design in my opinion.

Neither I like what I did, I'm aware that these designs don't match the recent work on the style for lmms (they don't even match my themes), I was just offering ideas about how the designs could be, if someone someday wants to work on them (someone who actually know how to draw stuff).

>  I'm not trying to be critical of the artwork specifically, but rather what the end goal of this bug report is.

If you don't feel this belongs here, feel free to close it, I saw #2243 and I thought this may be more or less the same, since both are about design and both started asking for opinions. I thought people could discuss about wether they liked the ideas or not so they could be worked on in the future.

**Comment by Umcaruje** [comment]
I like the idea for bitcrush and flanger, but Tres is right, this doesn't fit in with the new theme or the current one.

**Comment by tresf** [comment]
> If you don't feel this belongs here, feel free to close it, I saw #2243 and I thought this may be more or less the same, since both are about design and both started asking for opinions. I thought people could discuss about wether they liked the ideas or not so they could be worked on in the future.

We certainly don't want to discourage progress.  How about this... Fix the original bug report as requested and show some mockups and we'll leave it open.  Otherwise, it's getting closed. :+1:

**Comment by IvanMaldonado** [comment]
@tresf I'll see what can I do :+1:

**Comment by musikBear** [comment]
Somehow this points in direction of a relation to theming
Down the road, there may be interests in making these icons *themeable* and @IvanMaldonado nice artwork, could then be a part of a theme, other than what i now call *RebeccaNoir* eg. #2587

**Comment by Umcaruje** [comment]
>making these icons themeable

They are themeable. Read: https://github.com/LMMS/lmms/issues/2770#issuecomment-220005870

There hasn't been much development here, and I'm currently designing new icons, I think this issue should be closed.

**Comment by IvanMaldonado** [comment]
@Umcaruje No probs with that, as long as we get rid of that penguin :+1:

**Comment by zonkmachine** [comment]
Cool stuff!

As the new theme is done and the penguin is gone I close this.
