### ISSUE TITLE
BBTrack update bug

### ISSUE THREAD

**Issue by zonkmachine** [LMMS/lmms#2649]
Since f136ba3097d45b8651e45b494f8af5a6d606cd59 the BBTrack needs a little push once in a while to redraw properly.
To see the bug in action:
 * Open a a new project
 * Open a BBTrack
 * Open yet another new project... presto!
You need to resize the window to make the pattern fill out properly.
@Umcaruje 
![bbtrack](https://cloud.githubusercontent.com/assets/6368949/13611636/d556044a-e563-11e5-81b7-85d9b2eaec36.png)

**Comment by Umcaruje** [comment]
Actually, it happens whenever I add a new BBtrack. That's weird. I don't recall touching that portion of the code... 

I'll look into it.

**Comment by Umcaruje** [comment]
Ok, I removed 
```c++
m_pat->changeLength( m_pat->length() );
```

from the PaintEvent for Pattern. Note that this bug exists for automation tracks in 1.1.3:
![screenshot from 2016-03-08 23 06 31](https://cloud.githubusercontent.com/assets/6282045/13618126/a6d2aea6-e582-11e5-84d3-cc241f986c6d.png)

I'm not sure why this was in the paint-event though, shouldn't it have been in the constructor?

**Comment by Umcaruje** [comment]
@zonkmachine can you test out #2655?

**Comment by zonkmachine** [comment]
:+1:
