### ISSUE TITLE
L10n: zh locales should be available in different variants

### ISSUE THREAD

**Issue by MingcongBai** [LMMS/lmms#2651]
Currently LMMS has a `zh.ts` as the only zh_* (Chinese) locale data set available. In fact, there are many Chinese locales. LMMS should not assume that zh_CN (Chinese, China) is the only Chinese out there (and they can be quite different with each other, the best example is zh_CN and zh_TW).

In fact, here below is a list of Chinese locales supported by GNU C Library.
 
```
zh_CN
zh_HK
zh_SG
zh_TW
```

If you guys wouldn't mind, I will create a Pull Request containing a factored out `zh_CN.ts` instead of `zh.ts`, the rest of the locales should be filled in by volunteers using the respective variants of Chinese.

**Comment by tresf** [comment]
> LMMS should not assume that zh_CN (Chinese, China) is the only Chinese out there

We're going over this same topic with the Spanish translation and due to the huge amounts of work it is to maintain multiple Spanish translations, the various Spanish translators agreed to work together on a single translation.

From [latinumnetwork.com/differences-regional-spanish-dialect-2](http://www.latinumnetwork.com/differences-regional-spanish-dialect-2/)

> “Compré poporopos y dulces”
> “Compré rositas de maíz y caramelos”
> 
> At first glance, it’s probably evident that both sentences are in Spanish; what’s less apparent is that they both say the exact same thing: “I bought popcorn and candy.” The difference? The Spanish dialect. The first is from Guatemala, and the second is from Cuba.

We can merge this, but I'm a bit uncertain what benefit it has until we have additional Chinese translations available.  I vote we wait until a second translation is available before changing this.  Opinions welcome.

**Comment by MingcongBai** [comment]
Well, Chinese is a very different story in this case. Not only that the
dialects are different, the actual script/characters are wildly different
as well.

I would not be confident to assume that zh_CN and zh_TW can be made out as
one.

Maintaining as one language "until we have additional Chinese translations
available" is really a horrible idea: being unscientific (as not being
accurate in presentation), and I find it offensive if one would not make a
clear line between different language variants.
2016年3月8日 23:22，"Tres Finocchiaro" <notifications@github.com>写道：

**Comment by tresf** [comment]
>  I would not be confident to assume that zh_CN and zh_TW can be made out as one.

Then we'll change it. :)

>  I find it offensive if one would not make a clear line between different language variants.

Sorry about that and thanks for the explanation. :beer: 

I ended up looking this up no stackoverflow to understand a bit more.

> There are several countries where Chinese is the main written language. The major difference between them is whether they use simplified or traditional characters, but there are also minor regional differences (in vocabulary, etc). The standard way to distinguish these would be with a country code, e.g. `zh_CN` for mainland China, `zh_SG` for Singapore, `zh_TW` for Taiwan, or `zh_HK` for Hong Kong.
> 
> Mainland China and Singapore both use simplified characters, and the others use traditional characters. Since China and Taiwan are the two with the biggest populations, just `zh_CN` and `zh_TW` are often used to distinguish the simplified and traditional character versions of a website.
> 
> More correct, however, would be to use `zh_HANS` for (generic) simplified Chinese characters, and `zh_HANT` for traditional Chinese characters, except for rare cases when it is meaningful to distinguish different countries.

:+1:
