### ISSUE TITLE
ProjectVersion tests never fail

### ISSUE THREAD

**Issue by StCyr** [LMMS/lmms#2653]
In "src/core/ProjectVersionTest.cpp", if you replace (for example) the test:

`Q_ASSERT(ProjectVersion("1.1.0", CompareType::Minor) > "1.0.3");`

by 

`Q_ASSERT(ProjectVersion("1.1.0", CompareType::Minor) < "1.0.3");`

the tests still pass:

```
cyr@opennms-dev:~/lmms/build$ tests/tests
>> Will run 1 test suites
********* Start testing of ProjectVersionTest *********
Config: Using QTest library 4.8.6, Qt 4.8.6
PASS   : ProjectVersionTest::initTestCase()
PASS   : ProjectVersionTest::test()
PASS   : ProjectVersionTest::cleanupTestCase()
Totals: 3 passed, 0 failed, 0 skipped
********* Finished testing of ProjectVersionTest *********
<< 0 out of 1 test suites failed.
```

I don't exactly know why (maybe because Q_ASSERT does nothing if QT_NO_DEBUG was defined during compilation?)

Anyway, according to https://doc.qt.io/qt-4.8/qtestlib-manual.html it seems better to use QVERIFY rather than Q_ASSERT

Cyrille

**Comment by StCyr** [comment]
PR: https://github.com/LMMS/lmms/pull/2654

**Comment by tresf** [comment]
> Anyway, according to https://doc.qt.io/qt-4.8/qtestlib-manual.html it seems better to use QVERIFY rather than Q_ASSERT

Or just plain old `assert` according to this... http://faif.objectis.net/beware-of-q_assert/?searchterm=None.

Since @Lukas-W wrote the test code, I'll let him merge.  Nice find BTW. :+1:
