### ISSUE TITLE
Regression: Pattern size is not updated when it is altered by changing note length

### ISSUE THREAD

**Issue by Fastigium** [LMMS/lmms#2660]
Commit fcec8dd causes a regression in the drawing of Patterns on the song editor. To reproduce, enlarge any last note in a piano roll so that the Pattern becomes at least one measure longer. Now look at the song editor and notice that the Pattern still has its old length.

@Umcaruje As this is your commit, could you look into this regression? Let me know if you have trouble reproducing it.

**Comment by musikBear** [comment]
FYI enlarging last notes in tresf' qt5-build for xp, *does* enlarge the song-editor-block correctly. Eg, i could not reproduce on *lmms-1.1.90-win32-qt5*
I enlarged 1/16 from 1. to 4. tick to 2/4/6 and 8 bars length. The blocks were sized accordingly, both in enlarging and shortening.

**Comment by Umcaruje** [comment]
@musikBear this was caused by a commit I pushed yesterday, it couldn't have been in your build.
