### ISSUE TITLE
VST plugins fail to load from folders containing diacritical marks

### ISSUE THREAD

**Issue by jmarianski** [LMMS/lmms#2662]
Problem looks just like with every VST loading problem.

Steps to reproduce:
1) Download any VST plugin into a directory, in which path there are diacritical marks (in Polish we have these: ąćęłńóśżź), for example C:/Users/Jacek Mariański/VST/plugin.dll
2) Try to load them.

Easily fixable by moving into any other folder. Like to C:/VST/

**Comment by tresf** [comment]
Related #1998 #1325 #1933 #1995

**Comment by tresf** [comment]
I can confirm this bug still exists in `master` despite StringPairDrag patch in #1325, either `RemoteVSTPlugin` or `Vestige` likely needs an additional patch to support UTF8 characters.

Furthermore, we have several locations in our code which [still rely on Latin1 and also need to be fixed](https://github.com/LMMS/lmms/search?q=toLatin1).

Results:
:white_check_mark: PASS: `Marianski/GTG DPC3.dll`
:no_entry: FAIL: `Mariański/GTG DPC3.dll`

**Comment by softrabbit** [comment]
> despite StringPairDrag patch in #1325

That wasn't supposed to fix anything apart from drag & drop.
