### ISSUE TITLE
Edit-menu. Item for mixer-channel clean-up is missing

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#2663]
lmms-1.1.90-win32-qt5.exe
on xp
To reproduce
Click Edit in task-bar
This is shown
![editmenu](https://cloud.githubusercontent.com/assets/6662066/13686633/06df7cb2-e717-11e5-82f6-27d197fb08b2.png)
I noticed that some options has been taken off from the Edit-menu, one i  believe was there in last PR was options for removing unused mixer-channels eg #1206, but where is the dialog?
Has the feature been removed?

**Comment by michaelgregorius** [comment]
It's still there but it was an option in the context menu of the channel mixer from the start. Closing this one.

**Comment by musikBear** [comment]
> It's still there but it was an option in the context menu of the channel mixer from the start.

:open_mouth: Oo then i remember it wrong, sorry ..

**Comment by michaelgregorius** [comment]
@musikBear No problem! I has been found after all. :wink:
