### ISSUE TITLE
Plugins' notes blank space acts like a b+b pattern

### ISSUE THREAD

**Issue by IvanMaldonado** [LMMS/lmms#2664]
![frfr](https://cloud.githubusercontent.com/assets/12549082/13690088/58ffe546-e6f3-11e5-8af0-1e851d0a3661.png)

Zooming in.

![captura de pantalla_2016-03-10_19-01-05](https://cloud.githubusercontent.com/assets/12549082/13689997/960cd120-e6f2-11e5-8092-35cebca62f61.png)

You can even use this.

![captura de pantalla_2016-03-10_19-01-19](https://cloud.githubusercontent.com/assets/12549082/13689999/9ada3080-e6f2-11e5-8f87-e33f048f5ed7.png)

**Comment by tresf** [comment]
This has always been like this.
