### ISSUE TITLE
PatternView ( ... ) does not have a property named "fgColor"

### ISSUE THREAD

**Issue by zonkmachine** [LMMS/lmms#2666]
Since f136ba3097d45b8651e45b494f8af5a6d606cd59 I get `PatternView(0x3634750)  does not have a property named  "fgColor"`.
@Umcaruje

**Comment by Umcaruje** [comment]
Your theme is outdated, the `qproperty-fgColor` became `color`, while `color` became `background-color`.

**Comment by zonkmachine** [comment]
Ach so... Danke schön!
