### ISSUE TITLE
Wrong free Space displayed in installer

### ISSUE THREAD

**Issue by DrConsole** [LMMS/lmms#2673]
Hey, 
I'm new to this project and just installed it, when I noticed that if I switch to my data patition (6TB HDD) the installer displayes 4.6GB free space but it should be 4.6TB.

It's not a that important bug, but I think it's a small thing that can be debuged in one of the next releases.

NG
DrConsole

**Comment by tresf** [comment]
> I'm new to this project and just installed it, when I noticed that if I switch to my data patition (6TB HDD) the installer displayes 4.6GB free space but it should be 4.6TB.

We only have a Windows, installer, so if this statement is correct, it belongs on the NSIS bug tracker and all NSIS-based Windows installers would suffer from it.  Closing, as it's not our bug.

http://nsis.sourceforge.net/Bug_Reports

**Comment by tresf** [comment]
@DrConsole looks like they may already know about it... if that's the same bug, it will be fixed when we upgrade our Windows build environment.

https://sourceforge.net/p/nsis/bugs/896/
