### ISSUE TITLE
recipe for create a deb package with cpack

### ISSUE THREAD

**Issue by skypce** [LMMS/lmms#2679]
1.-Add this two lines to CMakeLists.txt of main folder of your project.
SET(CPACK_DEBIAN_PACKAGE_MAINTAINER "César R. Cid Méndez")
SET(CPACK_PACKAGE_CONTACT "César R. Cid Méndez")
Change the name by your name.
2.-inside main project;
mkdir build ; cd build ; cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr .. ; sudo cpack -G DEB ..

**Comment by tresf** [comment]
@skypce I linked you the relevant bug reports for this... can you please close this out and have the conversation there?

**Comment by skypce** [comment]
sure tres.

2016-03-15 14:18 GMT-03:00 Tres Finocchiaro <notifications@github.com>:
