### ISSUE TITLE
State Variable LADSPA Filter isn't working correctly

### ISSUE THREAD

**Issue by Henelik** [LMMS/lmms#2692]
The filter labeled as "None" is actually some kind of low pass filter.

**Comment by tresf** [comment]
Can you offer a screenshot?  We bundle many LADSPA filters and it will help to know which plugin you are referring to.

**Comment by Umcaruje** [comment]
This really isn't a problem with LMMS though, but with the developer of that LADSPA plugin.

**Comment by tresf** [comment]
> This really isn't a problem with LMMS though, but with the developer of that LADSPA plugin.

Correct, but it depends on the publisher.  SWH doesn't update his own, so all patches have been from downstream projects like us.  We've provided a few patches to his repo.

Calf on the other hand has changed so much we haven't been syncing in changes.

The status of the bug rides on which plugin has the bug, then we can escalate as needed. :+1:

**Comment by grejppi** [comment]
@tresf this one is in SWH Plugins.
