### ISSUE TITLE
Make text of both MainToolbar and Tracks editable

### ISSUE THREAD

**Issue by IvanMaldonado** [LMMS/lmms#2695]
![captura de pantalla_2016-03-20_20-08-09](https://cloud.githubusercontent.com/assets/12549082/13909390/bbf49e9e-eed7-11e5-997b-8aab6a863f41.png)

It's hard to make clear themes with no way to change these.

**Comment by tresf** [comment]
@IvanMaldonado it's hard-coded here:

https://github.com/LMMS/lmms/blob/master/src/gui/widgets/LcdWidget.cpp#L189
