### ISSUE TITLE
Hang on Open/Save operations

### ISSUE THREAD

**Issue by Spekular** [LMMS/lmms#2699]
* I'm running Windows 7 Home Premium, 64 bit.
* I'm using 1.2.0-RC1 64 bit
* If I attempt to open, save, import, or export a file, LMMS hangs. 
* If I install the 32 bit version, it works fine.

EDIT: Apologies for the eyesore of a title.

**Comment by Umcaruje** [comment]
Could you please provide us with a specific file where this issue happens, or does it happen with all files?

**Comment by tresf** [comment]
Sounds strikingly similar to #2698 (in symptom only of course)

**Comment by Spekular** [comment]
@Umcaruje happens when I first launch LMMS, without any file loaded.

@tresf could be. Thanks for cleaning up the title :+1:

**Comment by Spekular** [comment]
Is there anything I can do to get more info on this crash? Or should I just wait for RC2?

**Comment by tresf** [comment]
Probably worthy of Googling around a bit and reviewing the File dialog code.  This is very unlikely to be fixed in RC2, so don't hold your breath. :)

**Comment by Umcaruje** [comment]
well @Spekular if you wanna test it out, here's a fresh qt5 build of master as of today:

https://drive.google.com/open?id=0B49dcRGtm8vJcV9LU0xqZW81QjQ

This is a shot in the dark, but you could test if this maybe gets magically fixed by using qt5.

**Comment by Spekular** [comment]
@Umcaruje @tresf fixed in that build, sweet!
