### ISSUE TITLE
Equalizer shows high frequency content for sine wave at 110 Hz

### ISSUE THREAD

**Issue by michaelgregorius** [LMMS/lmms#2703]
Playing a sine wave at 110 Hz through an Equalizer results in some signal shown in the high frequency ranges, e.g. 5 kHz. As far as I know the sine in LMMS is computed using the `sin` function from the math library so I'd expect no signal to show in the higher frequencies because these frequency contents should already be well beyond -100 dB FS.

Here is a screenshot that shows the effect:
![equalizer-signal-for-sine](https://cloud.githubusercontent.com/assets/9293269/14043875/866bd458-f289-11e5-8a20-b6fd19b44738.png)

**Comment by michaelgregorius** [comment]
While checking the spectral content of a 110 Hz sine wave generated by `sin` in Reaper I noticed that you can select different [window functions](https://en.wikipedia.org/wiki/Window_function) in the analyser which yields different results.

[Rectangular window](https://en.wikipedia.org/wiki/Window_function#Rectangular_window):
![sine110-rectangular](https://cloud.githubusercontent.com/assets/9293269/14046890/83aa1dea-f2a4-11e5-8471-c5783991b6fa.png)

[Blackman-Harris window](https://en.wikipedia.org/wiki/Window_function#Blackman.E2.80.93Harris_window):
![sine110-blackman-harris](https://cloud.githubusercontent.com/assets/9293269/14046931/b13e0230-f2a4-11e5-8364-533906dbaf7c.png)

[Blackman window](https://en.wikipedia.org/wiki/Window_function#Blackman_windows):
![sine110-blackman](https://cloud.githubusercontent.com/assets/9293269/14046943/cf153616-f2a4-11e5-8cd3-757b6eae29d0.png)

I haven't had a detailed look at the code but my assumption is that the equalizer code use a rectangular window which leads to the quite heavy [spectral leakage](https://en.wikipedia.org/wiki/Spectral_leakage) in the higher frequencies.

Pinging @curlymorphic as he knows the code better.

**Comment by curlymorphic** [comment]
I would agree that being able to select the window type and size used could be a nice addition giving the plugin a more polished and professional analyzer function, The reading of a DFT display does require an understanding of the results presented, the window type  used and the size of the window if to be read accurately. The code in the eq uses the fft helper classes from lmms, which in turn are based on FFTW library.
Implementing this should not be difficult, but I unfortunately have a busy schedule,
