### ISSUE TITLE
Make the mixer color editable

### ISSUE THREAD

**Issue by IvanMaldonado** [LMMS/lmms#2704]
The colors of the mixer are linked to the general background.

![edit](https://cloud.githubusercontent.com/assets/12549082/14054179/ce192464-f29c-11e5-94da-a7753bb4722c.png)

If possible, making the mixer editable could enrich the UI in color.

![captura de pantalla_2016-03-25_15-05-51](https://cloud.githubusercontent.com/assets/12549082/14054185/e260c9d6-f29c-11e5-9b32-8293db12def9.png)

**Comment by tresf** [comment]
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.

**Comment by Spekular** [comment]
Implemented by #5589.

**Comment by messmerd** [comment]
Reopening this because while #5589 added custom colors to mixer channels, the mixer background appears to still lack theming support. If I'm wrong, feel free to close.
