### ISSUE TITLE
Language names not showing up in settings

### ISSUE THREAD

**Issue by codythecoder** [LMMS/lmms#2719]
After downloading and installing RC1, I found that none of the language names showed up in the settings.
![temp](https://cloud.githubusercontent.com/assets/13900631/14269762/fe1fe1a2-fb2a-11e5-8c58-aa109bae6550.png) ![temp](https://cloud.githubusercontent.com/assets/13900631/14269769/0b8bc72a-fb2b-11e5-959a-12e5bed27eaf.png)
I'm running win10 64bit and LMMS 64bit. I can give any further details if you need.

P.S. I'm pretty sure LMMS is currently in Hungarian, and I can't seem to find English :) It's not so much a problem for an experienced user, but I'd imagine someone new to LMMS would have some issues with this.

**Comment by tresf** [comment]
Duplcate of https://github.com/LMMS/lmms/issues/2577.

**Comment by codythecoder** [comment]
:+1: Forgot to check closed issues.
