### ISSUE TITLE
LMMS atypical crashes...

### ISSUE THREAD

**Issue by WinLin97** [LMMS/lmms#2720]
Hi all,

Sorry for my English - I use the Google Translator...
My LMMS crashes ... After I open a project ... In a short time (irregularly) following symptoms:
1. During playback, and sometimes even in idle LMMS suddenly switches itself off.
2. After loading the project, or during playback, there is a crash, which after some time disappears or is as long, until restart the LMMS.
In order to illustrate, everything is in the video: https://drive.google.com/file/d/0B1MViqpbQv3AS3hLamVNWlBHNFU/view?usp=sharing
Imho: Crash not depends to Wine version, kernel or system or loaded project.

In Polish language:

> Mój LMMS ulega awarii... Po tym jak otworzę jakiś projekt, w niedługim czasie (nieregularnie) występują następujące objawy:
> 1. W trakcie odtwarzania, a czasami nawet w bezczynności LMMS nagle wyłącza się sam.
> 2. Po załadowaniu projektu, lub w czasie odtwarzania występuje awaria, która po jakimś czasie znika, lub zostaje tak długo, aż zrestartuję LMMS.
> W celu zobrazowania, wszystko jest w tym filmie: https://drive.google.com/file/d/0B1MViqpbQv3AS3hLamVNWlBHNFU/view?usp=sharing
> Moim zdaniem: Crash nie zależy od wersji wine, kernela, systemu, czy załadowanego projektu.

My config:
Motherboard: GIGABYTE F2A88XM-D3H
Processor (APU): AMD A10-7850K
RAM: Geil 8GB
Drive: 512GB HDD + 128GB SSD
System: Ubuntu Studio 15.10 (x86)
Kernel: 4.2.0-35-lowlatency
Wine Version: wine-1.9.7 (Staging)
LMMS Version: 1.1.3

My VST:
Tal-Dub 1,2
CS12-M
SPAN
Proximity
LoudMax
Tal-Vocoder-2
Glace-Verb
Gonio-3
TAL-Chorus-LX

My VSTi:
Superwave P8
TAL-UNO-62
Prodigious
Erebus
Synth-1
RGC Square I
SQ8L
Latte-Free
Pro-53 Demo
Poly-2106

**Comment by DeRobyJ** [comment]
Hi!
What's your LMMS version?
The current stable is 1.1.3

**Comment by WinLin97** [comment]
No, it does not depend on what project is loaded. Projects which crashes, is more than two which are in the video.

**Comment by liushuyu** [comment]
The VST handling has been a headache in LMMS for years...
I think this is relevant to  #2448 #1875

**Comment by WinLin97** [comment]
Yes, this problem is in VSTs... Most likely the fault in the new version of wine.
On this hardware config, stable is: LMMS 1.1.3 + Wine 1.7.55 :)

Thanks for all replys :)

**Comment by zonkmachine** [comment]
@WinLin97 Can you test this again with the latest beta of lmms 1.2 (lmms-1.2-rc5)?
https://lmms.io/download/#linux
Also, the latest stable of Wine is 2.0.4 which was released just a week ago.

**Comment by tresf** [comment]
This was reported as possible duplicate and has since gone stale.  We've fixed a lot of VST issues in the recent versions.  Please open a new bug for one of the VSTs if these crashes occur with the latest 1.2.0+ build from our downloads page.  We require a valid, reproducible test, so please limit the bug reports to simple tests that are easy to reproduce and thus debug and fix.  Closing.
