### ISSUE TITLE
Improve lmms/data/locale/nl.ts

### ISSUE THREAD

**Issue by kstr** [LMMS/lmms#2721]
Some parts of the dutch locale are not or incorrectly translated.  I could help out by translating it...  Do i need to fork, or just email the improved version?
.

**Comment by IvanMaldonado** [comment]
We already have a localization platform online, you have to sign up and request the language you want to translate here:

https://www.transifex.com/lmms/lmms/

**Comment by tresf** [comment]
^ :+1:
