### ISSUE TITLE
Interoperability between 32-bit and 64-bit code

### ISSUE THREAD

**Issue by jasp00** [LMMS/lmms#2724]
I am having locking problems with VST on amd64. It looks like sem_t cannot be shared between 32-bit and 64-bit processes.
https://sourceware.org/bugzilla/show_bug.cgi?id=17980

Inter-process communication should use new sem32_* functions, pipes or sockets. You may consider endianness too (VST on powerpc). Do you want me to code this feature?

**Comment by tresf** [comment]
> Do you want me to code this feature?

If you believe you can fix it, yes please.
 * Do you believe it is the cause of #1875?
 * If so, should't a 32-bit OS not exhibit these problems?
 * Can you explain something... when Wine uses `sem_t`, does it interact with the 64-bit Wine executable?  If so, wouldn't it be immune to this problem?

You'll have plenty of people to test if you think you can fix this.

**Comment by tresf** [comment]
> You may consider endianness too (VST on powerpc)

I assume you're talking about LinuxVSTs then?  We don't have any users actively testing against PowerPC architecture currently, so if you have something to compile/test on, we may have some other areas to work on for proper PowerPC support.

**Comment by jasp00** [comment]
> * Do you believe it is the cause of #1875?
Possibly.

> * If so, should't a 32-bit OS not exhibit these problems?
It should not.

> * Can you explain something... when Wine uses `sem_t`, does it interact with the 64-bit Wine executable? If so, wouldn't it be immune to this problem?
I am not familiar with 64-bit Wine, but I believe 64-bit Wine cannot load 32-bit plugins and it cannot interact with 32-bit Wine using `sem_t`.

**Comment by jasp00** [comment]
My versiont works on amd64. It should be easy to handle endianness in the future. I use Unix sockets because QLocalSocket does not work properly in my system; I hope local sockets will not be a problem in other systems. I will commit the code in a few days.

**Comment by jasp00** [comment]
I am afraid the Windows builds will fail. I would be working blindly if I had to write the Windows implementation (using QLocalSocket, Gnulib or Winsock). Thus, I will leave the old implementation for that system.

**Comment by tresf** [comment]
> I would be working blindly if I had to write the Windows implementation (using QLocalSocket, Gnulib or Winsock).

We all work blindly when developing for Windows.  Microsoft provides 30-day VirtualBox images for testing against their OS:  https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/windows/

**Comment by jasp00** [comment]
Nice, I read 90 days. Unfortunately, my system does not have VirtualBox (nor the RAM). This may be handy in the future. Although I am concerned about whether I can legally use these images to develop LMMS; do you want me to find out about it?

**Comment by tresf** [comment]
> Although I am concerned about whether I can legally use these images to develop LMMS; do you want me to find out about it?

Well you wouldn't be using it for development, but rather for testing.  The images were intended for testing, you're fine.  I use these images for testing many products on various Windows versions.

**Comment by tresf** [comment]
> Although I am concerned about whether I can legally use these images to develop LMMS; do you want me to find out about it?


Found the license (scroll down to the bottom).  Don't see anything against using them for dev and testing purposes.

http://modernievirt.blob.core.windows.net/vhd/release_notes_license_terms_1_5_15.pdf

**Comment by jasp00** [comment]
*You may not use the software for commercial purposes.*
Imagine I (or someone else) decided to accept 100 euros to fix VST bugs. There is a *Donate* section in LMMS.

*(You may not) reverse engineer*
This could affect possible contributions to Wine. Contributions do not come from reverse engineering Windows, but may come from reverse engineering plug-ins, and it is a nuisance to keep the evidence.

I would need advice from Debian legal people before using these images. It would be easier if LMMS worked on Wine.

**Comment by liushuyu** [comment]
>Imagine I (or someone else) decided to accept 100 euros to fix VST bugs. There is a Donate section in LMMS.

This is not commercial, what they mean should be *these images can't be used to sell or benefit. Donations are **not** commercial behavior.

 >(You may not) reverse engineer

They mean you shouldn't reverse engineer their images, not the plugins. As some plugins are protected by their own licenses.

**Comment by tresf** [comment]
Commercial and donation are not the same and we're not developing Wine here, so there shouldn't be an issue.  The same general text is in the MSDN copies.  If you're really worried, we'll buy you a copy.

In regards to working with Wine, I feel like that's possible.  I assume it's broken currently?

**Comment by liushuyu** [comment]
>Commercial and donation are not the same and we're not developing Wine here, so there shouldn't be an issue. The same general text is in the MSDN copies. If you're really worried, we'll buy you a copy.

I agree :+1: 

>In regards to working with Wine, I feel like that's possible. I assume it's broken currently?

The last time I used Wine to test LMMS, it worked really well.

**Comment by jasp00** [comment]
> In regards to working with Wine, I feel like that's possible. I assume it's broken currently?

Now it works (Wine 1.8.2). There are crashes, but may be well enough to write the Windows implementation of #2739.

**Comment by jasp00** [comment]
There are no local sockets on Windows. An implementation using the loopback address in TCP/IP is very inefficient. I do not know how an implementation using Windows named pipes would perform, but it would be harder to maintain than the current one using Qt objects, and AFAIK there are no interoperability issues between 32-bit and 64-bit on Windows. Therefore, I think it is time to merge #2739.

**Comment by liushuyu** [comment]
>AFAIK there are no interoperability issues between 32-bit and 64-bit on Windows. Therefore, I think it is time to merge #2739.

AFAIK, Windows uses RPC to complete similar jobs. So this shouldn't be a problem under Windows.

The fix in #2739 works fine with Wine 1.8.x and 1.9.x despite some small acceptable flaws. Maybe it is appropriate to merge.
