### ISSUE TITLE
Restore metalish_dong01.ogg's quality

### ISSUE THREAD

**Issue by jasp00** [LMMS/lmms#2733]
The file pulled in #2392 has less quality; the original is stereo. I will send a version where the data is copied rather than re-encoded. It was created with:
`ffmpeg -i old/metalish_dong01.ogg -acodec copy new/metalish_dong01.ogg`

**Comment by tresf** [comment]
Just send over the PR please and we'll merge. :+1:

**Comment by tresf** [comment]
:+1:
