### ISSUE TITLE
Equalizer graph lag

### ISSUE THREAD

**Issue by karmux** [LMMS/lmms#2736]
Equalizer graph is lagging at ~2 fps. When I hold mouse on one of the points (1-8) then graph shows very smoothly. I believe it should always be smooth.

**Comment by BaraMGB** [comment]
Can you give informations about your system and version of lmms? Thank you

**Comment by IvanMaldonado** [comment]
This happens to me as well. 

Manjaro latest version (sorry, not at home) 
Lmms 1.1.9

**Comment by karmux** [comment]
I'm using master on Kubuntu 15.04.

**Comment by softrabbit** [comment]
The fix could be as easy as creating a slot in the right class (```EqCurve```?) and connecting it to the same signal as the faders:
```connect( gui->mainWindow(), SIGNAL( periodicUpdate() ), this, SLOT( updateVuMeters() ) );```

**Comment by Umcaruje** [comment]
Reproduced over on elementary OS Freya 64-bit. Here's a gif: 
![gifrecord_2016-05-02_001920](https://cloud.githubusercontent.com/assets/6282045/14944708/ffd74df6-0ffb-11e6-9898-04c1ae0c2621.gif)
It seems that the faders too are affected by this, not only the graph.

**Comment by Umcaruje** [comment]
Gonna tag @curlymorphic @BaraMGB, since they both worked on this plugin.

**Comment by karmux** [comment]
Currently, it's much better than when I reported this issue but still graph is noticeable slower when not holding points. `timer->start();` values below 5 gives me smooth graph without holding anything.

**Comment by BaraMGB** [comment]
@karmux may be, but have you watched your cpu usage? Drawing this is not cheap.

**Comment by karmux** [comment]
CPU usage is ~18% if I don't hold points and graph is not so smooth and ~29% if I hold points and graph is very smooth.

**Comment by Umcaruje** [comment]
I think this issue should be resolved so we actually limit the redraws when holding points. Oh and another question: why doesn't the EQ plugin use the global refresh timer, like FxMixerView does?
https://github.com/LMMS/lmms/blob/52ec3874b110f9204bfb3f3d4ac54206955b1375/src/gui/FxMixerView.cpp#L152-L153
