### ISSUE TITLE
License of the project as a whole is GPL-3+

### ISSUE THREAD

**Issue by jasp00** [LMMS/lmms#2752]
The following files are licensed under GPL-3+:

    plugins/flp_import/unrtf/*

Files are included in `plugins/flp_import/unrtf.cpp`. This commit changed the license: 98371cb1481e2e11d284223deed0d349ee953010

    plugins/LadspaEffect/swh/vocoder_1337.c

This one is being handled in #2366.

    plugins/zynaddsubfx/zynaddsubfx/src/Nio/AlsaEngine.cpp
    plugins/zynaddsubfx/zynaddsubfx/src/Nio/AlsaEngine.h
    plugins/zynaddsubfx/zynaddsubfx/src/Nio/JackEngine.cpp
    plugins/zynaddsubfx/zynaddsubfx/src/Nio/JackEngine.h

These files are not enabled.

**Comment by tresf** [comment]
Good find.

Albeit obvious, stating that we should switch them to GPL2 to match the source license would put more definition around this task (and then explain who we have to contact to do so, etc.)

**Comment by jasp00** [comment]
Regarding unrtf, the first to contact is Dave Davey <daved@physiol.usyd.edu.au>. It looks like LMMS is using version 0.20.5, from 2008 (ftp://ftp.gnu.org/pub/gnu/unrtf/). Then, there is David Santinoli without contact information.

**Comment by softrabbit** [comment]
> It looks like LMMS is using version 0.20.5, from 2008

And 0.20.3 (7 months earlier) is the last GPL2 version. Looks little only 4 of the files had real changes between 0.20.3 and 0.20.5, so downgrading might be feasible, too.

**Comment by jasp00** [comment]
According to `plugins/zynaddsubfx/zynaddsubfx/README.txt`, ZynAddSubFX is under GPL-2 only. In version 2.5.2, the four files listed above are under GPL-2 only. This would make LMMS undistributable as a whole; it could be distributed separately from the affected plugins.

**Comment by fundamental** [comment]
@jasp00 that file is out-of-date and the issue has been resolved upstream. I can dig up the mailing list post where the license was changed to GPLv2+ if you need me to.

**Comment by jasp00** [comment]
I see that version 2.5.4 is under GPLv2+. I am curious about the mailing list post; I have found [this one](https://sourceforge.net/p/zynaddsubfx/mailman/message/2254008/) from 2007, which makes little sense. But if upstream has gathered the necessary permissions, then it is all right.

**Comment by fundamental** [comment]
That's the post. At that stage in the project's history all commits were done by that author.

**Comment by jasp00** [comment]
Why later versions were released under GPLv2 only? In Debian, there is [this information](http://metadata.ftp-master.debian.org/changelogs//main/z/zynaddsubfx/zynaddsubfx_2.5.2-2_copyright) about ZynAddSubFX:
````
Files: *
Copyright:
 2002-2009 Nasca Octavian Paul <zynaddsubfx@yahoo.com>
 2006-2009 Lars Luthman
 2009-2010 Ryan Billing
 2009-2010 Mark McCurry
 2009 Harald Hvaal
License: GPL-2
````
(GPL-2 means GPLv2 only.) Did Lars Luthman, Ryan Billing and Harald Hvaal consent to the license change?

**Comment by fundamental** [comment]
Debian had the wrong license. After the license change to GPLv2+ there was some confusion due to how the license was changed within individual files and as such debian mislabeled the project.

**Comment by jonassmedegaard** [comment]
Ignore the Debian infom then - that's just a reflection of actual copyright and licensing statements withing sourcecode itself.

The following files, in the sourcecode used for Debian redistribution of zynaddsubfx, has GPL-2.0 (without "...or later" as license:

 src/DSP/AnalogFilter.cpp
 src/DSP/AnalogFilter.h
 src/DSP/FFTwrapper.cpp
 src/DSP/FFTwrapper.h
 src/DSP/Filter.cpp
 src/DSP/Filter.h
 src/DSP/FormantFilter.cpp
 src/DSP/FormantFilter.h
 src/DSP/SVFilter.cpp
 src/DSP/SVFilter.h
 src/DSP/Unison.cpp
 src/DSP/Unison.h
 src/Effects/Alienwah.cpp
 src/Effects/Alienwah.h
 src/Effects/Chorus.cpp
 src/Effects/Chorus.h
 src/Effects/Distorsion.cpp
 src/Effects/Distorsion.h
 src/Effects/DynamicFilter.cpp
 src/Effects/DynamicFilter.h
 src/Effects/Echo.cpp
 src/Effects/Echo.h
 src/Effects/Effect.cpp
 src/Effects/Effect.h
 src/Effects/EffectLFO.cpp
 src/Effects/EffectLFO.h
 src/Effects/EffectMgr.cpp
 src/Effects/EffectMgr.h
 src/Effects/EQ.cpp
 src/Effects/EQ.h
 src/Effects/Phaser.cpp
 src/Effects/Phaser.h
 src/Effects/Reverb.cpp
 src/Effects/Reverb.h
 src/globals.cpp
 src/globals.h
 src/main.cpp
 src/Misc/Bank.cpp
 src/Misc/Bank.h
 src/Misc/Config.cpp
 src/Misc/Config.h
 src/Misc/Control.h
 src/Misc/LASHClient.cpp
 src/Misc/LASHClient.h
 src/Misc/Master.cpp
 src/Misc/Master.h
 src/Misc/Microtonal.cpp
 src/Misc/Microtonal.h
 src/Misc/Part.cpp
 src/Misc/Part.h
 src/Misc/Recorder.cpp
 src/Misc/Recorder.h
 src/Misc/Stereo.cpp
 src/Misc/Stereo.h
 src/Misc/Util.cpp
 src/Misc/Util.h
 src/Misc/WaveShapeSmps.cpp
 src/Misc/WaveShapeSmps.h
 src/Misc/WavFile.cpp
 src/Misc/WavFile.h
 src/Misc/XMLwrapper.cpp
 src/Misc/XMLwrapper.h
 src/Nio/AlsaEngine.cpp
 src/Nio/AlsaEngine.h
 src/Nio/AudioOut.cpp
 src/Nio/AudioOut.h
 src/Nio/Engine.cpp
 src/Nio/Engine.h
 src/Nio/JackEngine.cpp
 src/Nio/JackEngine.h
 src/Nio/JackMultiEngine.cpp
 src/Nio/JackMultiEngine.h
 src/Nio/MidiIn.cpp
 src/Nio/MidiIn.h
 src/Nio/NulEngine.cpp
 src/Nio/NulEngine.h
 src/Nio/OssEngine.cpp
 src/Nio/OssEngine.h
 src/Nio/OssMultiEngine.cpp
 src/Nio/OssMultiEngine.h
 src/Nio/PaEngine.cpp
 src/Nio/PaEngine.h
 src/Nio/WavEngine.cpp
 src/Nio/WavEngine.h
 src/Output/DSSIaudiooutput.cpp
 src/Output/DSSIaudiooutput.h
 src/Params/ADnoteParameters.cpp
 src/Params/ADnoteParameters.h
 src/Params/Controller.cpp
 src/Params/Controller.h
 src/Params/EnvelopeParams.cpp
 src/Params/EnvelopeParams.h
 src/Params/FilterParams.cpp
 src/Params/FilterParams.h
 src/Params/LFOParams.cpp
 src/Params/LFOParams.h
 src/Params/PADnoteParameters.cpp
 src/Params/PADnoteParameters.h
 src/Params/PresetsArray.cpp
 src/Params/PresetsArray.h
 src/Params/Presets.cpp
 src/Params/Presets.h
 src/Params/PresetsStore.cpp
 src/Params/PresetsStore.h
 src/Params/SUBnoteParameters.cpp
 src/Params/SUBnoteParameters.h
 src/Synth/ADnote.cpp
 src/Synth/ADnote.h
 src/Synth/Envelope.cpp
 src/Synth/Envelope.h
 src/Synth/LFO.cpp
 src/Synth/LFO.h
 src/Synth/OscilGen.cpp
 src/Synth/OscilGen.h
 src/Synth/PADnote.cpp
 src/Synth/PADnote.h
 src/Synth/Resonance.cpp
 src/Synth/Resonance.h
 src/Synth/SUBnote.cpp
 src/Synth/SUBnote.h
 src/Synth/SynthNote.h
 src/Tests/AdNoteTest.h
 src/Tests/AllocatorTest.h
 src/Tests/ControllerTest.h
 src/Tests/EchoTest.h
 src/Tests/MessageTest.h
 src/Tests/MicrotonalTest.h
 src/Tests/MiddlewareTest.h
 src/Tests/MqTest.h
 src/Tests/OscilGenTest.h
 src/Tests/PadNoteTest.h
 src/Tests/PluginTest.h
 src/Tests/RandTest.h
 src/Tests/RtAllocTest.h
 src/Tests/SubNoteTest.h
 src/Tests/UnisonTest.h
 src/Tests/XMLwrapperTest.h
 src/UI/guimain.cpp

**Comment by fundamental** [comment]
@jonassmedegaard Please notice the copyright and author fields associated with those files. This is nothing more than a collection of typos that originated at the original GPLv2->GPLv2+ change.

**Comment by jonassmedegaard** [comment]
Quoting Mark McCurry (2016-05-06 04:05:40)
> @jonassmedegaard Please notice the copyright and author fields 
> associated with those files. This is nothing more than a collection of 
> typos that originated at the original GPLv2->GPLv2+ change.

Please elaborate: What in particular should I notice about those 
copyright holders, which makes the licenses of same files ignorable?

 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by fundamental** [comment]
@jonassmedegaard The majority of those files have the copyright and author field assigned to Nasca Octavian Paul, i.e. the individual who performed the relicensing to GPLv2+ in 2007. This issue has been resolved upstream.

**Comment by jonassmedegaard** [comment]
Quoting Mark McCurry (2016-05-06 14:18:34)
> @jonassmedegaard The majority of those files have the copyright and 
> author field assigned to Nasca Octavian Paul, i.e. the individual who 
> performed the relicensing to GPLv2+ in 2007. This issue has been 
> resolved upstream.

URLs supporting that, please.

 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by fundamental** [comment]
https://github.com/zynaddsubfx/zynaddsubfx/commit/8a403abf9b80484efcd3253f3e04f5697f5742d0

The license is GPLv2+.
Anything stating otherwise was an omission erroneously done at this commit, or a result of result of incorrect refactoring which occurred due to a transfer of maintainership years after this transition.
If you want to see the email to the public mailing list corresponding with this commit, please just look at the previous post in this issue's thread. At that point all license holders agreed on this change.

**Comment by jonassmedegaard** [comment]
Quoting Mark McCurry (2016-05-06 14:57:29)
> https://github.com/zynaddsubfx/zynaddsubfx/commit/8a403abf9b80484efcd3253f3e04f5697f5742d0
> 
> The license is GPLv2+.
> Anything stating otherwise was an omission erroneously done at this 
> commit, or a result of result of incorrect refactoring which occurred 
> due to a transfer of maintainership years after this transition.
> If you want to see the email to the public mailing list corresponding 
> with this commit, please just look at the previous post in this 
> issue's thread. At that point all license holders agreed on this 
> change.

Ahh - now I see what is going wrong - here is one of the license grants:

  This program is free software; you can redistribute it and/or modify
  it under the terms of version 2 of the GNU General Public License
  as published by the Free Software Foundation.

...and here is the disclaimer following above license grant:

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License (version 2 or later) for more details.

Problem is the license grant explicitly permit only version 2 of the GPL 
license, whereas the disclaimer tells how you see details in either 
version 2 or a later version of the GPL license.

The original change (possibly done in CVS but now represented as) seems 
to be this: https://sourceforge.net/p/zynaddsubfx/code/ci/8a403ab

I am convinced that those places specifically edited back then was 
intended as a change of licensing.

I have not checked if...

 a) the change covers _all_ places which had license grant limited to 
GPL 2 when the edit was made: If not, then arguably remaining parts 
(e.g. parts lacking consent from some copyright holders) was not 
relicensed.

 b) any of those intended-relaxed-but-still-only-GPL2 had changes 
afterwards from new copyright holders who acknowledged only the written 
text, not the intended more relaxed license: If so, I believe any such 
later contributors need to approve the relicensing (or their changes 
reverted).

 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by Umcaruje** [comment]
@jonassmedegaard I'm sorry, but wouldn't this discussion be more appropriate on the zynaddsubfx issue tracker?

**Comment by jonassmedegaard** [comment]
Quoting Umcaruje (2016-05-06 19:26:28)
> @jonassmedegaard I'm sorry, but wouldn't this discussion be more 
> appropriate on the zynaddsubfx issue tracker?

Possibly.

I was made aware of the discussion here, and try provide input as best 
as I can.  Feel free to rais a similar issue at the zynaddsubfx issue 
tracker and invite me there if input is wanted (and simply referencing 
my existing posts here isn't sufficient).

My email is dr@jones.dk in case anyone wants to contact me outside of 
Github.

 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by jasp00** [comment]
A decision should be made about whether references to GPLv2 only can be changed to GPLv2+ in the copy of ZynAddSubFX in LMMS without gathering more permissions. My guess is that they can be changed.

**Comment by tresf** [comment]
> A decision should be made about whether references to GPLv2 only can be changed to GPLv2+ in the copy of ZynAddSubFX in LMMS without gathering more permissions. My guess is that they can be changed.

Agreed.  If upstream has changed them, we should too.  If @fundamental says they can be changed, then they can.  Of course, this becomes moot once #1991 is finished as we'd be using the fixed versions anyway.

In regards to the methods upstream used to get permission to change their own license, that is better suited for the upstream tracker as @Umcaruje has pointed out.  Please feel free to cross-reference this discussion.

@jasp00 back to the topic at hand I've reached out to (what I believe to be) both FLP import authors for permission to switch the code back to GPL2.  I've emailed are `daved` awaiting a response and `frolovs` email is no longer valid.  Since @tobydox seems to have fast-forwarded the changes, he may have more information about when/why this GPL2-to-GPL3 change was made although it very well may have been a sync from an upstream repo.

That said, we very well can keep our plugins in their original license (right?).  AFAIK, we can stay GPL2 and our plugins can stay GPL3 so as long as we aren't misleading about that.  Please correct me if I'm wrong here.

**Comment by jasp00** [comment]
> That said, we very well can keep our plugins in their original license (right?). AFAIK, we can stay GPL2 and our plugins can stay GPL3 so as long as we aren't misleading about that.

The problem is how can we not be misleading. The About dialog shows GPL2. The Windows installer shows GPL2 too. There is no indication that an instrument plugin is under GPL3. Perhaps both licenses should be displayed.

**Comment by tresf** [comment]
> The problem is how can we not be misleading

Good question.

> About dialog shows GPL2. The Windows installer shows GPL2 too. There is no indication that an instrument plugin is under GPL3. Perhaps both licenses should be displayed.

I don't disagree, but I'd like to know the use-case.  Is the concern that someone using the software may do something with the GPL3 binaries that they are not allowed to?   From and end-user perspective what are the major risks in leaving certain plugins as-is?

I searched for alternate contact information of the flp import GPL3 author for quite a while to no avail.

I also question the legality of some of these authors switching the license to something different to begin with.  Had the code been audited, those changes would likely be scrapped and we'd have to [clean-room](https://en.wikipedia.org/wiki/Clean_room_design) every offending change.

To your point, yes we could just as easily state something in our About dialog stating some components are GPL2+ or GPL3 also.  We could even name those components specifically in the about dialog and packaging information if you think that will help prevent any misleading assumptions, but I do have to question the merit behind this from an end-user's perspective.  Most of the differences in the GPL2 and GPL3 text affects the code more so than the binaries from my understanding (but I'd be happy to be proven wrong).

**Comment by jasp00** [comment]
Most users do not care about the license, they just want the program to work and make music. We might as well switch to GPL3+ (as a whole); anyone is free to do this change from GPL2+ in their project. Thus, LMMS would not suffer from possible [tivoization](https://en.wikipedia.org/wiki/Tivoization) and users get explicit patent protection from contributors. Regarding new features, we lose the ability to combine with projects under GPL2 only, but we gain the ones under Apache license.

> Is the concern that someone using the software may do something with the GPL3 binaries that they are not allowed to?

Our main concern is authors that want to enforce the copyright. Authors' concerns are tivoization (something wrong with GPL3 binaries) and patents; or maybe they just choose GPL3 because the FSF says it is a good license (and it is).

> From an end-user perspective what are the major risks in leaving certain plugins as-is?

If the GPL3 is enforced by the copyright holders, the plugins would have to be distributed separately; that would mean an extra download and installation. Or there could be two versions of LMMS, one under GPL3 with the plugins.

The GPL2 requires that the interactive notice (About dialog) point to GPL2; the GPL3, to GPL3.

**Comment by tresf** [comment]
> The GPL2 requires that the interactive notice (About dialog) point to GPL2; the GPL3, to GPL3.

Then I vote we simply do that.

**Comment by tresf** [comment]
`daved` at `physiol.usyd.edu.au` now forwards to an unrelated email address, so no luck at all contacting the authors of the FL-import plugin.

**Comment by tresf** [comment]
> daved at physiol.usyd.edu.au now forwards to an unrelated email address, so no luck at all contacting the authors of the FL-import plugin.

This statement is slightly incorrect, it's him, he's just not an LMMS author.  How did this happen?  It appears it was the cherry-picking of `unrtf` code which placed him in the codebase as an author.  The `unrtf` project uses GPL3, so it was most likely the motivation of the change.

What does this mean for LMMS?  We can choose to distribute with a mixed license, strip out the plugin entirely, or try to use the upstream library.  Here's Dave's email response... 

> "I am certainly not an expert on licensing matters.  I know that the current
sources are released under GPL v3.  I don't think I have any ability to
give (or not) permission to use the code.  My understanding is that the
license says it all."

> "At first glance it does not look to me like that code is the most recent
release.  There was quite a bit of work on unrtf last year with many
improvements and bug fixes.  Since that time the code seems to have been
very stable.  I've not seen a bug report for many months."

**Comment by grejppi** [comment]
I just tried importing `NewStuff.flp` from FL Studio 12.

The result looks nothing like it should.
* Velocity of notes is zero or very close to it
* Steps are completely jumbled
* The import code does not support the new playlist
* Instrument names are blank
* Pattern names are only one letter long
* There is no support for audio clips and automation clips in LMMS (they work in a different way in FL Studio anyway)

![kuvakaappaus 2016-05-09 03-52-32](https://cloud.githubusercontent.com/assets/772336/15101462/9de426de-1599-11e6-8259-9e595304b2da.png)

It is fine for projects made with old enough versions of FL Studio, but as the format evolves at Image-Line's whim, this feature is going to be less and less useful in the future.

In fact, if you ask me, I would be in favour of removing the FLP import feature altogether. The fewer unmaintained incomplete features, the better.

~~(Same goes for sample tracks tbqh)~~

**Comment by tresf** [comment]
@grejppi thanks, terrific feedback, much appreciated.  :+1: from me.

**Comment by liushuyu** [comment]
>In fact, if you ask me, I would be in favour of removing the FLP import feature altogether. The fewer unmaintained incomplete features, the better.

Or we can replace the implementation with a new one. 

BTW, It should be noticed that MuseScore really does a good job at importing non-native project files.

**Comment by jasp00** [comment]
Perhaps unrtf is only used for comments (`FLP_Text_CommentRTF`) to set the project notes. That item could be removed or refactored to use the external `unrtf` application.

**Comment by paulnasca** [comment]
Hi.
I feel that there are needed some clarification from me regarding ZynAddSubFX.
Initially, in 2002, I have decided to release it under "GPL v2" and only under that version.

But, by request, I have changed the license of ZynAddSubFX to "GPL v2 or later" (including GPL v3, of course) in 2007 (more exactly, in 9 sep 2007, GIT commit on sourceforge 8a403abf9b80484efcd3253f3e04f5697f5742d0). I forgot to update license on some files by then, sorry, my bad. Please consider my part of ZynAddSubFX as being under "GPL version 2 or later", which includes GPL version 3+. 
Thank you.
