### ISSUE TITLE
Qt5::Core dependency is missing for RemoteZynAddSubFX

### ISSUE THREAD

**Issue by ycollet** [LMMS/lmms#2755]
I compile lmms from master branch.
Under fedora 23 64 bits, the compiler complains about a missing dependency to Qt5Core in RemoteZynAddSubFX.
I added the following patch and everything went fine:

```diff
diff --git a/plugins/zynaddsubfx/CMakeLists.txt b/plugins/zynaddsubfx/CMakeLists.txt
index 9922f73..18e91c4 100644
--- a/plugins/zynaddsubfx/CMakeLists.txt
+++ b/plugins/zynaddsubfx/CMakeLists.txt
@@ -162,6 +162,9 @@ ENDIF(WIN32)
 SET(CMAKE_INSTALL_RPATH "${CMAKE_INSTALL_PREFIX}/${PLUGIN_DIR}")
 SET(CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE)
 ADD_EXECUTABLE(RemoteZynAddSubFx RemoteZynAddSubFx.cpp "${WINRC}")
+IF(QT5)
+TARGET_LINK_LIBRARIES(RemoteZynAddSubFx Qt5::Core)
+ENDIF(QT5)
 INSTALL(TARGETS RemoteZynAddSubFx RUNTIME DESTINATION "${PLUGIN_DIR}")
 
 # Remove useless dependencies from FLTK. Use fltk-config to avoid static library
```

**Comment by midi-pascal** [comment]
This goes fine for me to. Thanks! :+1:

**Comment by jasp00** [comment]
Then I will add this to #2756.

**Comment by tresf** [comment]
Closed via #2756.

**Comment by jasp00** [comment]
RemoteZynAddSubFx does not depend on Qt5::Core. If the error is the same @midi-pascal has, instructions are given in https://github.com/LMMS/lmms/pull/2748#issuecomment-218621679.

**Comment by ycollet** [comment]
It looks like a commit has reverted this fix.
With the current master, I have the link problem.

**Comment by ycollet** [comment]
A new way of fixing this:
diff --git a/plugins/zynaddsubfx/CMakeLists.txt b/plugins/zynaddsubfx/CMakeLists.txt
index fcce85d..84167d5 100644
--- a/plugins/zynaddsubfx/CMakeLists.txt
+++ b/plugins/zynaddsubfx/CMakeLists.txt
@@ -181,9 +181,9 @@ TARGET_LINK_LIBRARIES(RemoteZynAddSubFx zynaddsubfx_gui -L.. -lZynAddSubFxCore $
 ADD_DEPENDENCIES(RemoteZynAddSubFx ZynAddSubFxCore)
 
 # link Qt libraries when on win32
-IF(LMMS_BUILD_WIN32)
+#IF(LMMS_BUILD_WIN32)
        TARGET_LINK_LIBRARIES(RemoteZynAddSubFx ${QT_LIBRARIES})
-ENDIF(LMMS_BUILD_WIN32)
+#ENDIF(LMMS_BUILD_WIN32)

**Comment by jasp00** [comment]
@ycollet, RemoteZynAddSubFx does not depend on Qt libraries, ZynAddSubFxCore does and it is already linked. What is the error and the linking command (configure with `-DCMAKE_VERBOSE_MAKEFILE=ON` to see the command)?

**Comment by ycollet** [comment]
Here is the result of make VERBOSE=1:

[100%] Linking CXX executable ../RemoteZynAddSubFx
cd /home/collette/repositories/lmms/build/plugins/zynaddsubfx && /usr/bin/cmake -E cmake_link_script CMakeFiles/RemoteZynAddSubFx.dir/link.txt --verbose=1
/usr/lib64/ccache/c++   -fno-exceptions -Wall -Werror=unused-function -Wno-sign-compare -Wno-strict-overflow -Wno-array-bounds  -fPIC -DPIC -O2 -Wno-write-strings -Wno-deprecated-declarations -fpermissive -O2 -g -DNDEBUG   CMakeFiles/RemoteZynAddSubFx.dir/RemoteZynAddSubFx.cpp.o  -o ../RemoteZynAddSubFx -rdynamic -Wl,--enable-new-dtags zynaddsubfx/src/UI/libzynaddsubfx_gui.a -L.. -lZynAddSubFxCore -lfltk -lpthread -Wl,-rpath,"\$ORIGIN" 
/usr/bin/ld: CMakeFiles/RemoteZynAddSubFx.dir/RemoteZynAddSubFx.cpp.o: référence au symbole non défini «qt_version_tag@@Qt_5.6»
/usr/lib64/libQt5Core.so.5: error adding symbols: DSO missing from command line
collect2: erreur : ld a retourné 1 code d'état d'exécution
plugins/zynaddsubfx/CMakeFiles/RemoteZynAddSubFx.dir/build.make:95: recipe for target 'plugins/RemoteZynAddSubFx' failed
make[2]: *** [plugins/RemoteZynAddSubFx] Error 1
make[2]: Leaving directory '/home/collette/repositories/lmms/build'
CMakeFiles/Makefile2:8044: recipe for target 'plugins/zynaddsubfx/CMakeFiles/RemoteZynAddSubFx.dir/all' failed
make[1]: *** [plugins/zynaddsubfx/CMakeFiles/RemoteZynAddSubFx.dir/all] Error 2
make[1]: Leaving directory '/home/collette/repositories/lmms/build'
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jasp00** [comment]
The first patch will be restored in #2782.
