### ISSUE TITLE
sustain pedal not working with soundfont

### ISSUE THREAD

**Issue by autumna** [LMMS/lmms#2758]
version: 1.1.91
Soundfont doesn't seem to detect the sustain in 1.1.91. This feature used to work on 1.1.3.

**Comment by DeRobyJ** [comment]
Related to #1700 maybe?

**Comment by autumna** [comment]
I did run into #1700 using both 1.1.3 and this current build. Sustain didn't and still doesn't record. :) However, the issue I am referring to is related to how the notes play as the notes are inputted from a midi keyboard:
In 1.1.3 when using sustain during recording, sound reflects the sustain even if it didn't record to the piano roll. 
In 1.1.91 when you play with sustain not only you cannot hear the sustain, some of the long pressed begins sounding stacatto. (even through they are recording with what their current length would be without sustain).

**Comment by DeRobyJ** [comment]
Maybe the sustain pedal has been linked to decay. Seems like a bug then!

**Comment by tresf** [comment]
@softrabbit do you recall us touching any of the code that would impact MIDI/SF2?

**Comment by softrabbit** [comment]
> @softrabbit do you recall us touching any of the code that would impact MIDI/SF2 since 1.1.3?

Can't say I do. My understanding is that the SF2 player doesn't receive MIDI input at all, so the problem should be somewhere between the MIDI port and the spot where the ```NotePlayHandles``` or whatever are created. And it should then affect most instruments in a similar way.
