### ISSUE TITLE
Some projects do not allow commercial usage

### ISSUE THREAD

**Issue by jasp00** [LMMS/lmms#2761]
Projects under CC BY-NC or Yellow OpenMusic cannot be included in distributions such as Debian, works are considered non-free. One long term goal is to not ship license restricted songs with LMMS.

**Comment by tresf** [comment]
Agreed, songs, samples and presets.  Duplicate of https://github.com/LMMS/lmms/issues/1273#issuecomment-62189752, https://github.com/LMMS/lmms/issues/1693.

Somewhat related https://github.com/LMMS/samples#commit-rules
