### ISSUE TITLE
Some projects are licensed under Creative Commons 1.0

### ISSUE THREAD

**Issue by jasp00** [LMMS/lmms#2762]
Projects under CC BY or CC BY-SA without a version cannot be included in distributions such as Debian. The licenses are assumed to be version 1.0 and the works are [considered non-free](https://wiki.debian.org/DFSGLicenses). This kind of licensing still happens (#2727). It would be nice if authors could specify version 3.0 at least.

**Comment by jasp00** [comment]
@grejppi, would you confirm that `Greippi-ardudar.mmpz` is under CC BY-SA 3.0 (or 4.0)?

**Comment by grejppi** [comment]
@jasp00 To be honest I'd prefer to remove it altogether. It has served its purpose.

**Comment by grejppi** [comment]
@jasp00 Done. (#2763) No need to worry about that track anymore, ever.

**Comment by SecondFlight** [comment]
It looks like this issue has served its purpose, but maybe I'm wrong. @jasp00 can you confirm either way?
