### ISSUE TITLE
Note re-trigger on some linux DE

### ISSUE THREAD

**Issue by DeRobyJ** [LMMS/lmms#2768]
On some linux system (probably actually related to certain Desktop Environments), the Keyboard Repeat function goes in conflict with LMMS: when you keep a note pressed, it re-triggers randomly.

It's not an expected behavior: one might think that after the delay (which is default to 660 ms), the note would be triggered continuously (default, 25 repeats per sec). Instead, it re-triggers just randomly and sometime starts even before the delay.

This bug gets fixed by disabling the feature Keyboard Repeat or by putting "Leave Unchanged".
The latter is better since this way you get to delete long lines of text by long-pressing Backspace or Delete.

I found the bug on KXStudio and Ubuntu Studio, I remember @Umcaruje had the same problem (even if he doesn't play with the pc keyboard much).
I also know this bug is not preset on some Ubuntu Unity based systems (like Ubuntu itself), but I might be wrong.
So it's probably related to KDE?

I wonder if a program can check for system settings. If yes, I suggest to warn the user at program startup!
(if it's not an easy fix from LMMS, that is)

**Comment by liushuyu** [comment]
@DeRobyJ  I can confirm that. I am on Plasma KDE 5 (Qt 5.6.0, KDE Framework 5.21.0, using xcb window system), this sure happens when long pressing one key and multiple notes were inputed on the screen

**Comment by tresf** [comment]
Can you please review #851 for a possible duplicate?

**Comment by liushuyu** [comment]
@tresf , yes, it's highly identical to #851

**Comment by DeRobyJ** [comment]
Mhe, I spent some time to search for that bug when I didn't know about the Keyboard repeat, and i couldn't find it xD

Closing as duplicate

**Comment by tresf** [comment]
@DeRobyJ that other bug report is closed. Shall we reopen it, or it is an unfixable upstream bug?

**Comment by DeRobyJ** [comment]
(not sure what an upstream bug is)

Anyway, that one is more discussed, so I thought we should reopen that, if we need any.
This is easy to fix by the user, it's just that I think this information should be more accessible.

**Comment by tresf** [comment]
> (not sure what an upstream bug is)

A bug from something out of our control (usually a project which sits at a higher level, such as a Windowing system ('X') a desktop environment (KDE, Gnome, Cinnamon) a framework (Qt) or a codebase which we rely on or import (SDL, Wine, Calf/swh/Caps etc), where the problems flow "downstream" to us, so to speak.

> This is easy to fix by the user, it's just that I think this information should be more accessible.

Ok, if the fix is in the other report, we'll leave it closed.  If this is not, I'd like you to decide whether or not it needs to be reopened.

**Comment by DeRobyJ** [comment]
It is there, even if I hope this one will get to be googled from users seaching for help on this case.

Since a closed issue still gets googled, we can leave both closed!

**Comment by tresf** [comment]
> we can leave both closed!

:+1: Thanks.
