### ISSUE TITLE
Sample tracks shortened at >44100 samplerate export

### ISSUE THREAD

**Issue by Spekular** [LMMS/lmms#2778]
Found in 1.1.9.0-g0-c9bf9b. Exporting a track at above 44100 samplerate will cause sample tracks to stop playback earlier than they should. They do, however, retain the correct playback speed.

Correct: https://drive.google.com/open?id=0BxmQmjduN8QxTUpNS0hSX3N6MlE
Incorrect: https://drive.google.com/open?id=0BxmQmjduN8QxalNUejNBV1BqSjQ

**Comment by Spekular** [comment]
Updated.

**Comment by Umcaruje** [comment]
We should really disable the sample tracks. There's just so much wrong with them that a complete rewrite is probably necessary.

**Comment by Spekular** [comment]
Without them a lot of my current projects would be impossible though. What
ways are they broken in aside from this? I know you can't play from the
middle and you can't send them to mixer channels, but those aren't as bad.

**Comment by softrabbit** [comment]
I think this was the first LMMS bug I reported back in 0.4.5 or so, long before I contributed any code... sweet memories :smile:. Guess it never got fixed, then. 

IIRC, playback is OK but export is buggy, do you agree @Spekular?

**Comment by Spekular** [comment]
@softrabbit indeed.

**Comment by tresf** [comment]
Possible duplicate of https://github.com/LMMS/lmms/issues/1471#issuecomment-118354809

> What ways are they broken in aside from this?

#1471

**Comment by Spekular** [comment]
@tresf I suppose I ought to close this and consider it part of the meta-issue?

**Comment by tresf** [comment]
> @tresf I suppose I ought to close this and consider it part of the meta-issue?

Probably.  44K+ isn't all that popular of a format and AFAIK we have some other issues that crop up over 44K as well.

**Comment by Spekular** [comment]
Consolidated into #1471
