### ISSUE TITLE
AFP resets endpoint on render

### ISSUE THREAD

**Issue by Spekular** [LMMS/lmms#2779]
Found in 1.1.9.0-g0-c9bf9b. When rendering, AFP resets the endpoint of a sample. This affects the project file and the rendered output. Most likely it will also affect start/loop point, but I have not tested this. 

[Video Example](https://www.youtube.com/watch?v=w16Sw6baOmU&feature=youtu.be)

**Comment by DeRobyJ** [comment]
I think this is also present on 1.1.3
I remember trying to render loop with a sample with a controlled endpoint, and the exported wave was completely different from the playback on LMMS.
Can't test right now tho

**Comment by Spekular** [comment]
Updated issue with video example.

**Comment by xodene** [comment]
I'm also having the same issue on Windows - same version. It definitely messed up a few projects when I didn't realize the problem was with AFP.

**Comment by tresf** [comment]
> I think this is also present on 1.1.3

Are you sure?  I've used custom loop points in 1.1.3 dozens of times without any recollection of this.  I'm marking for 1.2 unless we find evidence otherwise.

**Comment by DeRobyJ** [comment]
Errata corrige: I was referring to a different problem, I misread the first post.
In my case, the points get reset if they were controller with a controller.
That is, in the render they are still...
Or better: sometimes they are still, some other times they are rendered as "discrete" (like the controller was set to some kind of squared curve, instead of a sine).

But this is a separate issue anyway.

**Comment by zonkmachine** [comment]
It happened here:  #1088, 857de8d2c829dc688745f41ba8eddbe148a63a20

```
zonkmachine@zonkmachine:~/builds/lmms/lmms$ git bisect good
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
9fe55161a83defb76d33ea751a03103362fbb607
68b5a21d14352188175b4f95f9041cbaa45b837e
dc4bfdc60defdd9b47a21848af70fd350ca7ef28
7bc97f5d5bd9fcb43971f62e546ba464be1e818f
f25da35c244be9fe3af3d4c73b44658bcecb10ae
50bfed7180b2554d80f7109c2a52b3f9a7a936ee
9a3d3cb3064e38c22b60d092a32edef1959673b9
1864dcfaa1260e2659c85d1fb63cb2d428e9f1ab
8a596b0898bdc12568c8b3670b52ba93bdb93e4e
1deb80acc38c4f42a5d7859a8251a9b09caed65a
f207613d5f98c4f657a3c21d8ac79872a8ffa071
857de8d2c829dc688745f41ba8eddbe148a63a20    <--- First
b441bdae15446f1965e38ef26a81cdad9c8da61a
ba05b7523d4fe1e757b74df7c8c12e3e532a09a7
We cannot bisect more!
```

After exporting, if you save the project it will still come back like it was prior to the export and play back fine. You just can't export it.

**Comment by musikBear** [comment]
imho this ought to be upgraded to *Critical*
