### ISSUE TITLE
Cloning "even" tacts in BBEditor

### ISSUE THREAD

**Issue by DeRobyJ** [LMMS/lmms#2785]
Let's say you have a pattern in the BBEditor that takes 32 steps. (at default StepsPerTact, in 4/4)
Now you want to duplicate the steps to create a similar one with 64 steps (4 tacts).

What happens right now is that using Clone Steps twice you'll get two new copies of the first 16 steps.
In most cases, this is not the expected behaviour, imo.

I think it's better if new "even" tacts are cloned from the second tact!
(starting from the fourth of course)

This way, in the example above, you would just have to clone twice to get the third tact cloned from the first and the fourth cloned from the third, and then make your variation.

If this sounds like a reasonable feature, it would just take a little edit in src/tracks/Pattern.cpp > Pattern::cloneSteps()

**Comment by DeRobyJ** [comment]
![snapshot6](https://cloud.githubusercontent.com/assets/6437521/15337510/6db3757a-1c7c-11e6-820c-d216e32be627.png)

That's it.
(I created the first tact, cloned it and edited the second tact, then clicked on clone twice to get the third from the first and the fourth from the second)

The code should be ready to be pulled, I tested it with different tempo marks, and everything seems fine.
Question: can I open a new pull request while have a pending one?

**Comment by Spekular** [comment]
I think perhaps the clone button should double pattern length, which is
similar to what this does. 2^X are probably the most common lengths so it
would make sense.

With this feature it takes two clicks to get four times the length and one
click to get three. With a doubling clone, it would take one click to get
four times the length and two clicks to get four.

**Comment by Umcaruje** [comment]
>Question: can I open a new pull request while have a pending one?

Yes, but you need to do your work on seperate branches. You can create a new branch by doing `git checkout -b [name of the branch]` and then you push to origin: `git push origin --set-upstream [name of the branch]`. Note that if you made your previous PR from the master branch, you'll need to hard reset this new branch to the current upstream master and then apply your work.

**Comment by DeRobyJ** [comment]
OK.

I won't pull it now, I'll wait some time, so that I'll pull the little changes I'm making to get familiar with the code all together, after asking which of them are wanted.

I'll close this for now.
I don't mind if they won't get to 1.2 actually xD

**Comment by DeRobyJ** [comment]
@Spekular I want some more feedback for that, I'm not sure it would actually be OK, but might be my opinion only.

**Comment by Umcaruje** [comment]
Superseded by #2972
