### ISSUE TITLE
Avast issue

### ISSUE THREAD

**Issue by cmurtheepic** [LMMS/lmms#2787]
Avast thinks that the windows 64bit pre-release version:1.2.0-RC1
download is a virus

**Comment by liushuyu** [comment]
Ahh… It's a kind of false positive. I think someone may want to report this
incident to Avast

**Comment by tresf** [comment]
Avast reports anything it finds suspicious as a virus.  It's their responsibility to vet out software, not ours to ask "pretty please".  LMMS is downloaded 500,000 times a year, they need to get their head out of their metaphorical ***.

**Comment by tresf** [comment]
@liushuyu apparently this is so common they have a dedicated form!

https://www.avast.com/false-positive-file-form.php

@cmurtheepic please upload the binary to Avast and let them know.

**Comment by liushuyu** [comment]
>@liushuyu apparently this is so common they have a dedicated form!

Should I say many anti-virus softwares have this kind of report form ...?
