### ISSUE TITLE
Avast blocks "lmms-1.1.90-win64.exe"

### ISSUE THREAD

**Issue by Marchhill** [LMMS/lmms#2790]
My avast is blocking the 1.2 beta version of LMMS from downloading.
http://i.cubeupload.com/4Knhl8.png

**Comment by liushuyu** [comment]
We are free and open-source software, so we can't and don't include malicious behaviors. You can report this incident to Avast: https://www.avast.com/false-positive-file-form.php

And this is a duplicate of #2787
