### ISSUE TITLE
Add a search filter in the audio / presets menu on the left

### ISSUE THREAD

**Issue by ycollet** [LMMS/lmms#2795]
Add a search filter in the audio / presets menu on the left.
This search filter will display only corresponding regex.

**Comment by musikBear** [comment]
those tree-structures has a context-filter 
If you are in doubt how to use the search, this:
https://lmms.io/wiki/index.php?title=Side_Bar#Section_Navigation
here the search feature is called **smart-search**

Also http://lmms.io/forum/index.php could be for you?

**Comment by ycollet** [comment]
Am I stupid ?? :)
I used LMMS for years and I did saw this search area ...

**Comment by grejppi** [comment]
@musikBear what is the difference between search and smart-search? The term `smart-search` is used nowhere in LMMS.

**Comment by Spekular** [comment]
@grejppi I believe he's clarifying that the wiki article refers to it as "smart-search", although I'm not sure why it's called that.

**Comment by musikBear** [comment]
@grejppi 
> I believe he's clarifying that the wiki article refers to it as "smart-search"

Exactly, it was in order to help *him* find the relevant paragraph, the article .

**Comment by grejppi** [comment]
Yes, I understand. But why does the wiki call it that in the first place? Admittedly LMMS does not have a consistent terminology, but the wiki seems full of terms that are made up just for the sake of having a fancy name for something.

**Comment by musikBear** [comment]
@grejppi i actually think that this type of search (part of search-word), in other programs, are called *token-search*, should lmms use that too?

**Comment by tresf** [comment]
> @grejppi i actually think that this type of search (part of search-word), in other programs, are called token-search, should lmms use that too?

No, he's criticizing the quality of the wiki in general.
