### ISSUE TITLE
Change the default note played in the beat/bassline editor

### ISSUE THREAD

**Issue by oliveratutexas** [LMMS/lmms#2800]

**Comment by tresf** [comment]
@oliveratutexas please provide a better issue description so that we can properly categorize this.

**Comment by Umcaruje** [comment]
Actually, you can change the note that gets played by dragging the green square on top of the piano in the instrument window.

**Comment by Umcaruje** [comment]
Closing out as a support request, ask to reopen if you think this was mistakenly closed.
