### ISSUE TITLE
Out-of-date version of ZynAddSubFX.

### ISSUE THREAD

**Issue by BJC2016** [LMMS/lmms#2811]
Synaddsubfx crashes in lubuntu 64 bit in lmms 1.1.3

When you click show gui, LMMS crashes, the terminal output is; Segmentatiefout (geheugendump gemaakt)

**Comment by Umcaruje** [comment]
@BJC2016 Please state your LMMS version

**Comment by DeRobyJ** [comment]
That's strange...
May you give us some details of OS, hardware, and if you did completely update to the kxstudio repo? (if you used it to get the latest version of lmms)

**Comment by BJC2016** [comment]
Computer generated report. I did not have updated to the Kxstudio repo, I think its the default ubunut repo. But I can give it a try, and come back with the results.
Computer
********


Summary
-------

-Computer-
Processor		: 2x Intel(R) Pentium(R) 4 CPU 3.80GHz
Memory		: 2047MB (588MB used)
Operating System		: Ubuntu 14.04.4 LTS
User Name		: bart (Bart)
Date/Time		: Wed 01 Jun 2016 04:51:40 PM CEST
-Display-
Resolution		: 1024x768 pixels
OpenGL Renderer		: GeForce 8600 GT/PCIe/SSE2
X11 Vendor		: The X.Org Foundation
-Multimedia-
Audio Adapter		: HDA-Intel - HDA VIA VT82xx
Audio Adapter		: EMU10K1 - SB Live! 5.1 [SB0220]
-Input Devices-
 Power Button
 Sleep Button
 Power Button
 Logitech USB Keyboard
 PixArt USB Optical Mouse
 Logitech USB Keyboard
 HDA VIA VT82xx Rear Mic
 HDA VIA VT82xx Front Mic
 HDA VIA VT82xx Line
 HDA VIA VT82xx Line Out
 HDA VIA VT82xx Front Headphone
-Printers-
No printers found
-SCSI Disks-
ATA SAMSUNG HD250HJ
TSSTcorp CDDVDW SH-S223L

Operating System
----------------

-Version-
Kernel		: Linux 4.2.0-36-generic (x86_64)
Compiled		: #42~14.04.1-Ubuntu SMP Fri May 13 17:27:22 UTC 2016
C Library		: Unknown
Default C Compiler		: GNU C Compiler version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) 
Distribution		: Ubuntu 14.04.4 LTS
-Current Session-
Computer Name		: bart-lubuntu-14
User Name		: bart (Bart)
Home Directory		: /home/bart
Desktop Environment		: LXDE (Lubuntu)
-Misc-
Uptime		: 2 minutes
Load Average		: 0.63, 0.51, 0.22

Kernel Modules
--------------

-Loaded Modules-
snd_hda_codec_analog		: Analog Devices HD-audio codec
snd_hda_codec_generic		: Generic HD-audio codec parser
snd_emu10k1_synth		: Routines for control of EMU10K1 WaveTable synth
snd_emux_synth		: Routines for control of EMU WaveTable chip
snd_seq_midi_emul		: Advanced Linux Sound Architecture sequencer MIDI emulation.
snd_seq_virmidi		: Virtual Raw MIDI client on Sequencer
joydev		: Joystick device interfaces
snd_emu10k1		: EMU10K1
input_leds		: Input -&gt; LEDs Bridge
bnep		: Bluetooth BNEP ver 1.3
rfcomm		: Bluetooth RFCOMM ver 1.11
snd_hda_intel		: Intel HDA driver
bluetooth		: Bluetooth Core ver 2.20
snd_util_mem		: Generic memory management routines for soundcard memory allocation
snd_hda_codec		: HDA codec core
snd_ac97_codec		: Universal interface for Audio Codec &apos;97
snd_hda_core		: HD-audio bus
ac97_bus
snd_hwdep		: Hardware dependent layer
snd_pcm		: Midlevel PCM code for ALSA.
snd_seq_midi		: Advanced Linux Sound Architecture sequencer MIDI synth.
snd_seq_midi_event		: MIDI byte &lt;-&gt; sequencer event coder
snd_rawmidi		: Midlevel RawMidi code for ALSA.
snd_seq		: Advanced Linux Sound Architecture sequencer.
snd_seq_device		: ALSA sequencer device management
snd_timer		: ALSA timer interface
snd		: Advanced Linux Sound Architecture driver for soundcards.
serio_raw		: Raw serio driver
emu10k1_gp		: EMU10k1 gameport driver
gameport		: Generic gameport layer
soundcore		: Core sound module
i2c_viapro		: vt82c596 SMBus driver
nvidia
binfmt_misc
drm		: DRM shared core routines
8250_fintek		: Fintek F812164 module
asus_atk0110
shpchp		: Standard Hot Plug PCI Controller Driver
mac_hid
parport_pc		: PC-style parallel port driver
ppdev
lp
parport
pata_acpi		: SCSI low-level driver for ATA in ACPI mode
hid_generic		: HID generic driver
usbhid		: USB HID core driver
hid
psmouse		: PS/2 mouse driver
r8169		: RealTek RTL-8169 Gigabit Ethernet driver
mii		: MII hardware support library
pata_via		: low-level driver for VIA PATA
ahci		: AHCI SATA low-level driver
sata_via		: SCSI low-level driver for VIA SATA controllers
libahci		: Common AHCI SATA low-level routines
pata_jmicron		: SCSI low-level driver for Jmicron PATA ports
floppy

Boots
-----

-Boots-
Wed Jun 1 16:49		: 4.2.0-36-generic|-
Wed Jun 1 12:43		: 4.2.0-36-generic|-

Languages
---------

-Available Languages-
en_AG		: English language locale for Antigua and Barbuda
en_AG.utf8		: English language locale for Antigua and Barbuda
en_AU.utf8		: English locale for Australia
en_BW.utf8		: English locale for Botswana
en_CA.utf8		: English locale for Canada
en_DK.utf8		: English locale for Denmark
en_GB.utf8		: English locale for Britain
en_HK.utf8		: English locale for Hong Kong
en_IE.utf8		: English locale for Ireland
en_IN		: English language locale for India
en_IN.utf8		: English language locale for India
en_NG		: English locale for Nigeria
en_NG.utf8		: English locale for Nigeria
en_NZ.utf8		: English locale for New Zealand
en_PH.utf8		: English language locale for Philippines
en_SG.utf8		: English language locale for Singapore
en_US.utf8		: English locale for the USA
en_ZA.utf8		: English locale for South Africa
en_ZM		: English locale for Zambia
en_ZM.utf8		: English locale for Zambia
en_ZW.utf8		: English locale for Zimbabwe
nl_AW		: Dutch language locale for Aruba
nl_AW.utf8		: Dutch language locale for Aruba
nl_BE.utf8		: Dutch locale for Belgium
nl_NL.utf8		: Dutch locale for the Netherlands

Filesystems
-----------

-Mounted File Systems-
/dev/sda6	/	42.58 % (52.8 GiB of 92.0 GiB)	
none	/sys/fs/cgroup	0.00 % (4.0 KiB of 4.0 KiB)	
udev	/dev	0.00 % (989.0 MiB of 989.0 MiB)	
tmpfs	/run	0.69 % (198.6 MiB of 200.0 MiB)	
none	/run/lock	0.00 % (5.0 MiB of 5.0 MiB)	
none	/run/shm	0.01 % (999.7 MiB of 999.8 MiB)	
none	/run/user	0.02 % (100.0 MiB of 100.0 MiB)	

Display
-------

-Display-
Resolution		: 1024x768 pixels
Vendor		: The X.Org Foundation
Version		: 1.17.2
-Monitors-
Monitor 0		: 1024x768 pixels
-Extensions-
BIG-REQUESTS
Composite
DAMAGE
DOUBLE-BUFFER
DPMS
DRI2
GLX
Generic Event Extension
MIT-SCREEN-SAVER
MIT-SHM
NV-CONTROL
NV-GLX
Present
RANDR
RECORD
RENDER
SECURITY
SHAPE
SYNC
X-Resource
XC-MISC
XFIXES
XFree86-DGA
XFree86-VidModeExtension
XINERAMA
XINERAMA
XInputExtension
XKEYBOARD
XTEST
XVideo
-OpenGL-
Vendor		: NVIDIA Corporation
Renderer		: GeForce 8600 GT/PCIe/SSE2
Version		: 3.3.0 NVIDIA 340.96
Direct Rendering		: Yes

Environment Variables
---------------------

-Environment Variables-
GNOME_KEYRING_PID
USER		: bart
LANGUAGE		: nl_NL:en_US:en
LC_TIME		: en_US.UTF-8
UPSTART_INSTANCE
XDG_SEAT		: seat0
TEXTDOMAIN		: im-config
SESSION		: Lubuntu
SHLVL		: 0
HOME		: /home/bart
QT4_IM_MODULE		: xim
DESKTOP_SESSION		: Lubuntu
XDG_SEAT_PATH		: /org/freedesktop/DisplayManager/Seat0
LC_MONETARY		: en_US.UTF-8
INSTANCE
DBUS_SESSION_BUS_ADDRESS		: unix:abstract=/tmp/dbus-CqDipal1SC
GNOME_KEYRING_CONTROL		: /run/user/1000/keyring-TQSViV
MANDATORY_PATH		: /usr/share/gconf/Lubuntu.mandatory.path
IM_CONFIG_PHASE		: 1
SESSIONTYPE		: lxsession
UPSTART_JOB		: lxsession
LOGNAME		: bart
GTK_IM_MODULE		: xim
DEFAULTS_PATH		: /usr/share/gconf/Lubuntu.default.path
XDG_SESSION_ID		: c1
PATH		: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
GDM_LANG		: nl_NL
PAPERSIZE		: letter
SELINUX_INIT		: YES
LC_ADDRESS		: en_US.UTF-8
XDG_SESSION_PATH		: /org/freedesktop/DisplayManager/Session0
XDG_RUNTIME_DIR		: /run/user/1000
DISPLAY		: :0
LC_TELEPHONE		: en_US.UTF-8
LANG		: nl_NL.UTF-8
XMODIFIERS		: @im=ibus
XAUTHORITY		: /home/bart/.Xauthority
XDG_GREETER_DATA_DIR		: /var/lib/lightdm-data/bart
SSH_AUTH_SOCK		: /run/user/1000/keyring-TQSViV/ssh
SHELL		: /bin/bash
LC_NAME		: en_US.UTF-8
GDMSESSION		: Lubuntu
LC_MEASUREMENT		: en_US.UTF-8
UPSTART_EVENTS		: started xsession
LC_IDENTIFICATION		: en_US.UTF-8
TEXTDOMAINDIR		: /usr/share/locale/
GPG_AGENT_INFO		: /run/user/1000/keyring-TQSViV/gpg:0:1
UPSTART_SESSION		: unix:abstract=/com/ubuntu/upstart-session/1000/1147
XDG_VTNR		: 7
QT_IM_MODULE		: xim
PWD		: /home/bart
CLUTTER_IM_MODULE		: xim
XDG_CONFIG_DIRS		: /etc/xdg/lubuntu:/etc/xdg/xdg-Lubuntu:/usr/share/upstart/xdg:/etc/xdg
XDG_DATA_DIRS		: /etc/xdg/lubuntu:/usr/local/share:/usr/share:/usr/share/gdm:/var/lib/menu-xdg:/usr/share/Lubuntu:/usr/local/share/:/usr/share/
LC_NUMERIC		: en_US.UTF-8
LC_PAPER		: en_US.UTF-8
JOB		: dbus
XDG_CURRENT_DESKTOP		: LXDE
_LXSESSION_PID		: 1273
XDG_CONFIG_HOME		: /home/bart/.config
XDG_MENU_PREFIX		: lxde-
SAL_USE_VCLPLUGIN		: gtk

Users
-----

-Users-
root		: root
daemon		: daemon
bin		: bin
sys		: sys
sync		: sync
games		: games
man		: man
lp		: lp
mail		: mail
news		: news
uucp		: uucp
proxy		: proxy
www-data		: www-data
backup		: backup
list		: Mailing List Manager
irc		: ircd
gnats		: Gnats Bug-Reporting System (admin)
nobody		: nobody
libuuid
syslog
messagebus
usbmux		: usbmux daemon
dnsmasq		: dnsmasq
ntp
whoopsie
lightdm		: Light Display Manager
bart		: Bart
pulse		: PulseAudio daemon
rtkit		: RealtimeKit
colord		: colord colour management daemon
nvidia-persistenced		: NVIDIA Persistence Daemon

Devices
*******


Processor
---------

-Processors-
Intel(R) Pentium(R) 4 CPU 3.80GHz		: 3799.56MHz
Intel(R) Pentium(R) 4 CPU 3.80GHz		: 3799.56MHz

Memory
------

-Memory-
Total Memory		: 2047584 kB
Free Memory		: 1014056 kB
MemAvailable		: 1528044 kB
Buffers		: 73720 kB
Cached		: 445660 kB
Cached Swap		: 0 kB
Active		: 594412 kB
Inactive		: 329236 kB
Active(anon)		: 405324 kB
Inactive(anon)		: 6868 kB
Active(file)		: 189088 kB
Inactive(file)		: 322368 kB
Unevictable		: 0 kB
Mlocked		: 0 kB
Virtual Memory		: 6142972 kB
Free Virtual Memory		: 6142972 kB
Dirty		: 140 kB
Writeback		: 0 kB
AnonPages		: 404364 kB
Mapped		: 258480 kB
Shmem		: 7912 kB
Slab		: 43568 kB
SReclaimable		: 23592 kB
SUnreclaim		: 19976 kB
KernelStack		: 5200 kB
PageTables		: 17632 kB
NFS_Unstable		: 0 kB
Bounce		: 0 kB
WritebackTmp		: 0 kB
CommitLimit		: 7166764 kB
Committed_AS		: 2015804 kB
VmallocTotal		: 34359738367 kB
VmallocUsed		: 305660 kB
VmallocChunk		: 34358947836 kB
HardwareCorrupted		: 0 kB
AnonHugePages		: 61440 kB
CmaTotal		: 0 kB
CmaFree		: 0 kB
HugePages_Total		: 0
HugePages_Free		: 0
HugePages_Rsvd		: 0
HugePages_Surp		: 0
Hugepagesize		: 2048 kB
DirectMap4k		: 107392 kB
DirectMap2M		: 1988608 kB

PCI Devices
-----------

-PCI Devices-
Host bridge		: VIA Technologies, Inc. CN896/VN896/P4M900 Host Bridge
Host bridge		: VIA Technologies, Inc. CN896/VN896/P4M900 Host Bridge
Host bridge		: VIA Technologies, Inc. CN896/VN896/P4M900 Host Bridge
Host bridge		: VIA Technologies, Inc. CN896/VN896/P4M900 Host Bridge
Host bridge		: VIA Technologies, Inc. CN896/VN896/P4M900 Host Bridge
PIC		: VIA Technologies, Inc. CN896/VN896/P4M900 I/O APIC Interrupt Controller (prog-if 20 [IO(X)-APIC])
Host bridge		: VIA Technologies, Inc. CN896/VN896/P4M900 Security Device
Host bridge		: VIA Technologies, Inc. CN896/VN896/P4M900 Host Bridge
PCI bridge		: VIA Technologies, Inc. VT8237/VX700 PCI Bridge (prog-if 00 [Normal decode])
PCI bridge		: VIA Technologies, Inc. CN896/VN896/P4M900 PCI to PCI Bridge Controller (rev 80) (prog-if 00 [Normal decode])
PCI bridge		: VIA Technologies, Inc. CN896/VN896/P4M900 PCI to PCI Bridge Controller (rev 80) (prog-if 00 [Normal decode])
IDE interface		: VIA Technologies, Inc. Device 5337 (rev 80) (prog-if 8f [Master SecP SecO PriP PriO])
IDE interface		: VIA Technologies, Inc. VT82C586A/B/VT82C686/A/B/VT823x/A/C PIPC Bus Master IDE (rev 07) (prog-if 8a [Master SecP PriP])
USB controller		: VIA Technologies, Inc. VT82xx/62xx UHCI USB 1.1 Controller (rev a0) (prog-if 00 [UHCI])
USB controller		: VIA Technologies, Inc. VT82xx/62xx UHCI USB 1.1 Controller (rev a0) (prog-if 00 [UHCI])
USB controller		: VIA Technologies, Inc. VT82xx/62xx UHCI USB 1.1 Controller (rev a0) (prog-if 00 [UHCI])
USB controller		: VIA Technologies, Inc. VT82xx/62xx UHCI USB 1.1 Controller (rev a0) (prog-if 00 [UHCI])
USB controller		: VIA Technologies, Inc. USB 2.0 (rev 86) (prog-if 20 [EHCI])
ISA bridge		: VIA Technologies, Inc. VT8237A PCI to ISA Bridge
Host bridge		: VIA Technologies, Inc. VT8237/8251 Ultra VLINK Controller
Host bridge		: VIA Technologies, Inc. VT8237A Host Bridge
PCI bridge		: VIA Technologies, Inc. VT8237A PCI to PCI Bridge (prog-if 01 [Subtractive decode])
VGA compatible controller		: NVIDIA Corporation G84 [GeForce 8600 GT] (rev a1) (prog-if 00 [VGA controller])
SATA controller		: JMicron Technology Corp. JMB363 SATA/IDE Controller (rev 03) (prog-if 01 [AHCI 1.0])
IDE interface		: JMicron Technology Corp. JMB363 SATA/IDE Controller (rev 03) (prog-if 85 [Master SecO PriO])
Multimedia audio controller		: Creative Labs SB Live! EMU10k1 (rev 0a)
Input device controller		: Creative Labs SB Live! Game Port (rev 0a)
Ethernet controller		: Realtek Semiconductor Co., Ltd. RTL-8110SC/8169SC Gigabit Ethernet (rev 10)
Audio device		: VIA Technologies, Inc. VT8237A/VT8251 HDA Controller (rev 10)

USB Devices
-----------


Printers
--------

-Printers-
No printers found

Battery
-------

-No batteries-
No batteries found on this system

Sensors
-------


Input Devices
-------------

-Input Devices-
 Power Button
 Sleep Button
 Power Button
 Logitech USB Keyboard
 PixArt USB Optical Mouse
 Logitech USB Keyboard
 HDA VIA VT82xx Rear Mic
 HDA VIA VT82xx Front Mic
 HDA VIA VT82xx Line
 HDA VIA VT82xx Line Out
 HDA VIA VT82xx Front Headphone

Storage
-------

-SCSI Disks-
ATA SAMSUNG HD250HJ
TSSTcorp CDDVDW SH-S223L

DMI
---

-BIOS-
Date		: 05/22/2007
Vendor		: Phoenix Technologies, LTD (www.phoenix.com)
Version		: ASUS P5VD2-VM ACPI BIOS Revision 1105
-Board-
Name		: P5VD2-VM
Vendor		: ASUSTeK Computer INC. (SEAGATE, www.seagate.com)

Resources
---------

-I/O Ports-
<tt>0000-0cf7 </tt>		: PCI Bus 0000:80
<tt>  0000-0cf7 </tt>		: PCI Bus 0000:00
<tt>    0000-001f </tt>		: dma1
<tt>    0020-0021 </tt>		: pic1
<tt>    0040-0043 </tt>		: timer0
<tt>    0050-0053 </tt>		: timer1
<tt>    0060-0060 </tt>		: keyboard
<tt>    0061-0061 </tt>		: PNP0800:00
<tt>    0064-0064 </tt>		: keyboard
<tt>    0070-0073 </tt>		: rtc0
<tt>    0080-008f </tt>		: dma page reg
<tt>    00a0-00a1 </tt>		: pic2
<tt>    00c0-00df </tt>		: dma2
<tt>    00f0-00ff </tt>		: PNP0C04:00
<tt>      00f0-00ff </tt>		: fpu
<tt>    0170-0177 </tt>		: VIA Technologies, Inc. VT82C586A/B/VT82C686/A/B/VT823x/A/C PIPC Bus Master IDE (rev 07) (prog-if 8a [Master SecP PriP])
<tt>      0170-0177 </tt>		: low-level driver for VIA PATA
<tt>    01f0-01f7 </tt>		: VIA Technologies, Inc. VT82C586A/B/VT82C686/A/B/VT823x/A/C PIPC Bus Master IDE (rev 07) (prog-if 8a [Master SecP PriP])
<tt>      01f0-01f7 </tt>		: low-level driver for VIA PATA
<tt>    0290-029f </tt>		: pnp 00:01
<tt>    0376-0376 </tt>		: VIA Technologies, Inc. VT82C586A/B/VT82C686/A/B/VT823x/A/C PIPC Bus Master IDE (rev 07) (prog-if 8a [Master SecP PriP])
<tt>      0376-0376 </tt>		: low-level driver for VIA PATA
<tt>    0378-037a </tt>		: parport0
<tt>    037b-037f </tt>		: parport0
<tt>    03c0-03df </tt>		: vga+
<tt>    03f2-03f2 </tt>		: floppy
<tt>    03f4-03f5 </tt>		: floppy
<tt>    03f6-03f6 </tt>		: VIA Technologies, Inc. VT82C586A/B/VT82C686/A/B/VT823x/A/C PIPC Bus Master IDE (rev 07) (prog-if 8a [Master SecP PriP])
<tt>      03f6-03f6 </tt>		: low-level driver for VIA PATA
<tt>    03f7-03f7 </tt>		: floppy
<tt>    03f8-03ff </tt>		: serial
<tt>    0400-047f </tt>		: pnp 00:00
<tt>      0400-0403 </tt>		: ACPI PM1a_EVT_BLK
<tt>      0404-0405 </tt>		: ACPI PM1a_CNT_BLK
<tt>      0408-040b </tt>		: ACPI PM_TMR
<tt>      0420-0423 </tt>		: ACPI GPE0_BLK
<tt>      0450-0453 </tt>		: ACPI GPE1_BLK
<tt>    04d0-04d1 </tt>		: pnp 00:01
<tt>    0500-050f </tt>		: pnp 00:00
<tt>      0500-0507 </tt>		: vt596_smbus
<tt>    0778-077a </tt>		: parport0
<tt>    0800-0805 </tt>		: pnp 00:01
<tt>    0880-088f </tt>		: pnp 00:01
<tt>0cf8-0cff </tt>		: PCI conf1
<tt>0d00-ffff </tt>		: PCI Bus 0000:80
<tt>  0d00-ffff </tt>		: PCI Bus 0000:00
<tt>    9000-9fff </tt>		: PCI Bus 0000:04
<tt>      9400-94ff </tt>		: Realtek Semiconductor Co., Ltd. RTL-8110SC/8169SC Gigabit Ethernet (rev 10)
<tt>        9400-94ff </tt>		: RealTek RTL-8169 Gigabit Ethernet driver
<tt>      9800-9807 </tt>		: Creative Labs SB Live! Game Port (rev 0a)
<tt>        9800-9807 </tt>		: emu10k1-gp
<tt>      9c00-9c1f </tt>		: Creative Labs SB Live! EMU10k1 (rev 0a)
<tt>        9c00-9c1f </tt>		: EMU10K1
<tt>    a000-afff </tt>		: PCI Bus 0000:02
<tt>      ac00-ac7f </tt>		: NVIDIA Corporation G84 [GeForce 8600 GT] (rev a1) (prog-if 00 [VGA controller])
<tt>    b000-cfff </tt>		: PCI Bus 0000:03
<tt>      bc00-bc0f </tt>		: JMicron Technology Corp. JMB363 SATA/IDE Controller (rev 03) (prog-if 85 [Master SecO PriO])
<tt>        bc00-bc0f </tt>		: SCSI low-level driver for Jmicron PATA ports
<tt>      c000-c003 </tt>		: JMicron Technology Corp. JMB363 SATA/IDE Controller (rev 03) (prog-if 85 [Master SecO PriO])
<tt>        c000-c003 </tt>		: SCSI low-level driver for Jmicron PATA ports
<tt>      c400-c407 </tt>		: JMicron Technology Corp. JMB363 SATA/IDE Controller (rev 03) (prog-if 85 [Master SecO PriO])
<tt>        c400-c407 </tt>		: SCSI low-level driver for Jmicron PATA ports
<tt>      c800-c803 </tt>		: JMicron Technology Corp. JMB363 SATA/IDE Controller (rev 03) (prog-if 85 [Master SecO PriO])
<tt>        c800-c803 </tt>		: SCSI low-level driver for Jmicron PATA ports
<tt>      cc00-cc07 </tt>		: JMicron Technology Corp. JMB363 SATA/IDE Controller (rev 03) (prog-if 85 [Master SecO PriO])
<tt>        cc00-cc07 </tt>		: SCSI low-level driver for Jmicron PATA ports
<tt>    d400-d41f </tt>		: VIA Technologies, Inc. VT82xx/62xx UHCI USB 1.1 Controller (rev a0) (prog-if 00 [UHCI])
<tt>      d400-d41f </tt>		: uhci_hcd
<tt>    d800-d81f </tt>		: VIA Technologies, Inc. VT82xx/62xx UHCI USB 1.1 Controller (rev a0) (prog-if 00 [UHCI])
<tt>      d800-d81f </tt>		: uhci_hcd
<tt>    dc00-dc1f </tt>		: VIA Technologies, Inc. VT82xx/62xx UHCI USB 1.1 Controller (rev a0) (prog-if 00 [UHCI])
<tt>      dc00-dc1f </tt>		: uhci_hcd
<tt>    e000-e01f </tt>		: VIA Technologies, Inc. VT82xx/62xx UHCI USB 1.1 Controller (rev a0) (prog-if 00 [UHCI])
<tt>      e000-e01f </tt>		: uhci_hcd
<tt>    e400-e40f </tt>		: VIA Technologies, Inc. VT82C586A/B/VT82C686/A/B/VT823x/A/C PIPC Bus Master IDE (rev 07) (prog-if 8a [Master SecP PriP])
<tt>      e400-e40f </tt>		: low-level driver for VIA PATA
<tt>    e800-e8ff </tt>		: VIA Technologies, Inc. Device 5337 (rev 80) (prog-if 8f [Master SecP SecO PriP PriO])
<tt>      e800-e8ff </tt>		: SCSI low-level driver for VIA SATA controllers
<tt>    ec00-ec0f </tt>		: VIA Technologies, Inc. Device 5337 (rev 80) (prog-if 8f [Master SecP SecO PriP PriO])
<tt>      ec00-ec0f </tt>		: SCSI low-level driver for VIA SATA controllers
<tt>    f000-f003 </tt>		: VIA Technologies, Inc. Device 5337 (rev 80) (prog-if 8f [Master SecP SecO PriP PriO])
<tt>      f000-f003 </tt>		: SCSI low-level driver for VIA SATA controllers
<tt>    f400-f407 </tt>		: VIA Technologies, Inc. Device 5337 (rev 80) (prog-if 8f [Master SecP SecO PriP PriO])
<tt>      f400-f407 </tt>		: SCSI low-level driver for VIA SATA controllers
<tt>    f800-f803 </tt>		: VIA Technologies, Inc. Device 5337 (rev 80) (prog-if 8f [Master SecP SecO PriP PriO])
<tt>      f800-f803 </tt>		: SCSI low-level driver for VIA SATA controllers
<tt>    fc00-fc07 </tt>		: VIA Technologies, Inc. Device 5337 (rev 80) (prog-if 8f [Master SecP SecO PriP PriO])
<tt>      fc00-fc07 </tt>		: SCSI low-level driver for VIA SATA controllers
-Memory-
<tt>00000000-00000fff </tt>		: reserved
<tt>00001000-0009efff </tt>		: System RAM
<tt>0009f000-0009ffff </tt>		: reserved
<tt>000a0000-000bffff </tt>		: PCI Bus 0000:80
<tt>  000a0000-000bffff </tt>		: PCI Bus 0000:00
<tt>000c0000-000dffff </tt>		: PCI Bus 0000:00
<tt>  000c0000-000ccdff </tt>		: Video ROM
<tt>  000d3000-000d3fff </tt>		: pnp 00:08
<tt>000f0000-000fffff </tt>		: reserved
<tt>  000f0000-000fffff </tt>		: System ROM
<tt>00100000-7fedffff </tt>		: System RAM
<tt>  01000000-017c875c </tt>		: Kernel code
<tt>  017c875d-01d370bf </tt>		: Kernel data
<tt>  01eb1000-01ff3fff </tt>		: Kernel bss
<tt>7fee0000-7fee2fff </tt>		: ACPI Non-volatile Storage
<tt>7fee3000-7feeffff </tt>		: ACPI Tables
<tt>7fef0000-7fefffff </tt>		: reserved
<tt>7ff00000-bfefffff </tt>		: PCI Bus 0000:00
<tt>  7ff00000-800fffff </tt>		: PCI Bus 0000:03
<tt>bff00000-bfffffff </tt>		: PCI Bus 0000:80
<tt>  bfffc000-bfffffff </tt>		: VIA Technologies, Inc. VT8237A/VT8251 HDA Controller (rev 10)
<tt>    bfffc000-bfffffff </tt>		: ICH HD audio
<tt>c0000000-febfffff </tt>		: PCI Bus 0000:00
<tt>  c0000000-cfffffff </tt>		: PCI Bus 0000:02
<tt>    c0000000-cfffffff </tt>		: NVIDIA Corporation G84 [GeForce 8600 GT] (rev a1) (prog-if 00 [VGA controller])
<tt>  d0000000-d7ffffff </tt>		: VIA Technologies, Inc. CN896/VN896/P4M900 Host Bridge
<tt>  da000000-ddffffff </tt>		: PCI Bus 0000:02
<tt>    da000000-dbffffff </tt>		: NVIDIA Corporation G84 [GeForce 8600 GT] (rev a1) (prog-if 00 [VGA controller])
<tt>    dc000000-dcffffff </tt>		: NVIDIA Corporation G84 [GeForce 8600 GT] (rev a1) (prog-if 00 [VGA controller])
<tt>      dc000000-dcffffff </tt>		: nvidia
<tt>    ddfe0000-ddffffff </tt>		: NVIDIA Corporation G84 [GeForce 8600 GT] (rev a1) (prog-if 00 [VGA controller])
<tt>  dfd00000-dfdfffff </tt>		: PCI Bus 0000:04
<tt>    dfd00000-dfd1ffff </tt>		: Realtek Semiconductor Co., Ltd. RTL-8110SC/8169SC Gigabit Ethernet (rev 10)
<tt>    dfdff000-dfdff0ff </tt>		: Realtek Semiconductor Co., Ltd. RTL-8110SC/8169SC Gigabit Ethernet (rev 10)
<tt>      dfdff000-dfdff0ff </tt>		: RealTek RTL-8169 Gigabit Ethernet driver
<tt>  dfe00000-dfefffff </tt>		: PCI Bus 0000:03
<tt>    dfee0000-dfeeffff </tt>		: JMicron Technology Corp. JMB363 SATA/IDE Controller (rev 03) (prog-if 01 [AHCI 1.0])
<tt>    dfefe000-dfefffff </tt>		: JMicron Technology Corp. JMB363 SATA/IDE Controller (rev 03) (prog-if 01 [AHCI 1.0])
<tt>      dfefe000-dfefffff </tt>		: AHCI SATA low-level driver
<tt>  dffff000-dffff0ff </tt>		: VIA Technologies, Inc. USB 2.0 (rev 86) (prog-if 20 [EHCI])
<tt>    dffff000-dffff0ff </tt>		: ehci_hcd
<tt>  e0000000-efffffff </tt>		: PCI MMCONFIG 0000 [bus 00-ff]
<tt>    e0000000-efffffff </tt>		: reserved
<tt>      e0000000-efffffff </tt>		: pnp 00:07
<tt>  fe800000-fe8003ff </tt>		: HPET 0
<tt>    fe800000-fe8003ff </tt>		: PNP0103:00
<tt>      fe800000-fe8000ff </tt>		: pnp 00:08
<tt>fec00000-ffffffff </tt>		: reserved
<tt>  fec00000-fec003ff </tt>		: IOAPIC 0
<tt>  fecc0000-fecc03ff </tt>		: IOAPIC 1
<tt>  fee00000-fee00fff </tt>		: Local APIC
<tt>    fee00000-fee00fff </tt>		: pnp 00:08
<tt>  fff80000-fffeffff </tt>		: pnp 00:08
<tt>  ffff0000-ffffffff </tt>		: pnp 00:08
-DMA-
<tt> 2</tt>		: floppy
<tt> 3</tt>		: parport0
<tt> 4</tt>		: cascade

**Comment by Umcaruje** [comment]
90% of that information is not needed. You also failed to state your LMMS version, which is the most important thing.

**Comment by grejppi** [comment]
@Umcaruje

> lmms 1.1.3

**Comment by Umcaruje** [comment]
Oh damn I didn't look at the original post, didn't expect for it to get edited. Thanks @grejppi.

I can't really reproduce this crash at the moment, since I suffer from the Xorg crash, but I'll try to update my x, so I test this out.

**Comment by BJC2016** [comment]
In English this is System profiler and Benchmark, information, generate report. And I did not generate everything except networking and benchmarks. Another strange problem is that you only can find the desktop icon in the /usr/share/icons folder and not in the menu. I installed the program according the site on sourceforge with apt-get install lmms.

**Comment by karmux** [comment]
Maybe related to #2100 ? I had similar problem (not only LMMS crashed but whole desktop). After I installed newer version of distro with newer X, it didn't happen anymore.

**Comment by BJC2016** [comment]
No, I don't think so, its more a common problem from multiple people, and systems, like the described on the Sourceforge page feedback; https://sourceforge.net/projects/lmms/reviews?source=navbar First I had it with Linux lite os, and later when I had to reinstall it, I had it with Lubuntu, both 64 bit, but on 32 bit Ubuntu none of these problems occur. Oh, and yes, I had a crash upgrading to Ubuntu 15.04, and what happened to Lite os, I can not remember.

**Comment by Umcaruje** [comment]
@BJC2016 why'd you close this?

**Comment by BJC2016** [comment]
Sorry I did not closed it, it happened by itself, or something, I reopen it.......

**Comment by zonkmachine** [comment]
```
Vendor : The X.Org Foundation
Version : 1.17.2
```
Yeah, 1.17.2 is the fixed xorg-server so it isn't the same xorg crash as the rest of us. But it could still be xorg. Where did you get xorg 1.17.2?

**Comment by BJC2016** [comment]
Hi, its not too late, but I had the x.org from Lubuntu, I have now installed ubuntu 16.04 xenial and the problem is solved.
