### ISSUE TITLE
Bundled songs update

### ISSUE THREAD

**Issue by DeRobyJ** [LMMS/lmms#2812]
As pointed out here #2809 , bundled songs must be re-saved.
This will prevent the "old version warning" to show up.

I'm working on this, and I'm writing to have feedback if I'm doing it right.
For now, I did the Shorties section, and the log is this:

```
Crunk(Demo):	removed unused mixer channels
		re-saved

Dirty Love:	nothing here

Greshz-CoolS.:	Project is too empty
		Delete?

Root84-Tranc.:	no channels used, removed
		re-saved
		Assign channels?

Skiessi-222:	no channels used, removed
		re-saved
		Assign channels?
		
Surrender-Ma.:	removed unused channels
		re-saved

sv-DnB-Start.:	removed unused channels
		re-saved
		
sv-Trance-St.:	removed unused channels
		re-saved
```

Also, what about the Tutorials folder, it only has one project.

**Comment by tresf** [comment]
@DeRobyJ please (and thanks!) run with this.  No objections at all.  If there are serious quality issues, please remove them and let us know.  If the tutorial is worth saving, do it, if not, delete it.  If it's no more or less of a tutorial than half of the songs, feel free to merge it into another category.

**Comment by DeRobyJ** [comment]
Will do :)

About the tutorial, the user needs to open the project notes.
Is there a way I can save it to open it automatically? Some projects do that

**Comment by musikBear** [comment]
> This will prevent the "old version warning" to show up.

Honestly, what **good** does that popup do? Why does lmms need that?
There is only *one* thing the user can do:
Click it away. 
I think its annoying, and against the otherwise general 'hatred ' of popups

**Comment by tresf** [comment]
In the past, saving the project with the notes maximized did the trick.

@musikBear it's not a pop-up and he didn't make it, he's just fixing it.

**Comment by tresf** [comment]
> Honestly, what good does that popup do? Why does lmms need that?

Ask @Spekular, and ask here: https://github.com/LMMS/lmms/pull/1667, you're off topic.
