### ISSUE TITLE
[1.1.90][Crash] Attempting to open settings causes crash Win 7 x86

### ISSUE THREAD

**Issue by DarkenLX** [LMMS/lmms#2814]
Hello Attempting to open lmms settings cause app to hang then crash on windows 7 pro and enterprise x86/32 bit not sure about other versions of windows 7 or windows or 64 bit as i dont have any other. 
error output is:  
 Problem Event Name:    APPCRASH
  Application Name: lmms.exe
  Application Version:  1.1.90.0
  Application Timestamp:    34e534c5
  Fault Module Name:    ntdll.dll
  Fault Module Version: 6.1.7601.23418
  Fault Module Timestamp:   5708a7a8
  Exception Code:   c00000fd
  Exception Offset: 0005280e
  OS Version:   6.1.7601.2.1.0.256.4
  Locale ID:    1033
  Additional Information 1: a23c
  Additional Information 2: a23cb810300166b16666bcbe558789bd
  Additional Information 3: 07ec
  Additional Information 4: 07ece5be911ea4badcdc6fee03f2b13f

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

**Comment by DeRobyJ** [comment]
Are you using the version from the site (RC 1)? If yes, that bug is now fixed, I think.
I'm on a more recent build and I can open settings without problems, on windows 7 64bit.

**Comment by DarkenLX** [comment]
yes im using 1.2.0-RC1 aka 1.1.90 i tried downloading and reinstalling same issue. :(

**Comment by DeRobyJ** [comment]
That's probably fixed then. We'll test again with a more recent build when possible.

**Comment by DarkenLX** [comment]
how often does the rc download link on lmms.io get updated to the most current rc version or build?

**Comment by tresf** [comment]
Not often enough this time around, sorry.  Been much busier than expected.

**Comment by tresf** [comment]
@DarkenLX can you please let us know if this still occurs with RC2?

If so, can you please read this thread and let us know if it helps?  https://github.com/LMMS/lmms/issues/3488

**Comment by DarkenLX** [comment]
I'll have to do a clean install of RC2 and let you know asap

**Comment by zonkmachine** [comment]
@DarkenLX We're now on RC5 ;)
https://lmms.io/download/#windows

I'm closing this issue as it's most likely fixed. https://github.com/LMMS/lmms/issues/3049 looks like the same crash.
Please reopen if you can replicate this crash on a RC5 or later.
