### ISSUE TITLE
MDI windows: Resize action active when "far" inside the title bar

### ISSUE THREAD

**Issue by michaelgregorius** [LMMS/lmms#2823]
When entering the title bar from the top the resize mouse cursor is still shown when it's "far" inside the title bar and the widget is still in resize mode. Example:
![lmms-scaling](https://cloud.githubusercontent.com/assets/9293269/15805063/20ad886e-2b1e-11e6-84bd-90b8f654f79c.gif)
In other implementations, e.g. KDE Plasma, the resize action is only active when the mouse is close to the edge of the title bar and the mouse cursor turns to normal mode when being inside the title bar.

**Comment by Spekular** [comment]
I've noticed this as well, RC1 64bit on Windows 7.

**Comment by BaraMGB** [comment]
I'm a little bit clueless how to fix this. :persevere:

**Comment by Umcaruje** [comment]
I also have to mention that the resize handle also appears on any window, regardless if its resizeable or not, which is a bit pointless since e.g. the Instrument window shouldn't ever have the resize handles since you can't resize it.

**Comment by tresf** [comment]
FYI, I can't reproduce in my Mac VM using `BaraMGB/fixMacSubwindow`, so this may be specific to the desktop manager.

**Comment by BaraMGB** [comment]
It's about the label. If I set the label (window title) for 2 pixel down, the issue disappears.
