### ISSUE TITLE
VST plugin MDI subwindow uses default qt styling

### ISSUE THREAD

**Issue by Umcaruje** [LMMS/lmms#2824]
Version `1.1.90-gdaedb92 (Linux/x86_64, Qt 4.8.6, GCC 4.8.4)`, Elementary os Freya x64
![screenshot from 2016-06-05 22 42 13](https://cloud.githubusercontent.com/assets/6282045/15808103/f6f73d2a-2b6e-11e6-892d-fd1c5774ce06.png)
VST instrument windows seem to ignore the custom MDI Subwindow styling. 

Tagging @BaraMGB

**Comment by tresf** [comment]
> VST plugin MDI subwindow uses default qt styling

Probably because [`VstPlugin`](https://github.com/LMMS/lmms/blob/master/plugins/vst_base/VstPlugin.cpp) extends `QMdiSubwindow` rather than our custom  [`SubWindow`](https://github.com/lmms/lmms/blob/master/src/gui/SubWindow.cpp) class.

**Comment by lukas-w** [comment]
Changed milestone to 1.3.0 per https://github.com/LMMS/lmms/pull/2826#issuecomment-344504989

**Comment by DomClark** [comment]
Fixed in #2826.
