### ISSUE TITLE
Look for missing samples with different extension

### ISSUE THREAD

**Issue by Spekular** [LMMS/lmms#2825]
If someone were to convert their entire sample library from .wav to .flac (_cough_), they would then have to manually re-select all samples in their projects, even though they're in the same location with the same name.

Instead, it would be nice if the user could allow LMMS to replace these automatically, for example:

> LMMS has detected that some missing samples may be in another file format. Replace DamnSon.wav with DamnSon.flac?
> 1. Yes
> 2. No
> -  Do this for all 256 files

**Comment by Umcaruje** [comment]
+1 for the sample name :+1: 

I like the idea too.

**Comment by tresf** [comment]
> Do this for all 256 files

This won't happen.  Instead you should save as `mmp` file extension and search/replace.

> LMMS has detected that some missing samples may be in another file format. Replace DamnSon.wav with DamnSon.flac?

No, we can't expect the software to be smarter than a human.  Instead, it can ask to replace a missing file and prompt for which file to do so with, but to make an assumption that the extension has changed is a bad idea.  Files can be unavailable for many more reasons than this one use-case.  We need to provide an interface to accommodate them all.  For example, a removable media may not be plugged in, or a folder may have been moved which had the samples, etc.  Bulk replacement is something that should only be done carefully by a human, IMO.

**Comment by Spekular** [comment]
> [...] to make an assumption that the extension has changed is a bad idea

> Files can be unavailable for many more reasons than this one use-case

I'm aware, I've had missing samples for other reasons before. However, in the case of xyz.A being missing and xyz.B existing in the same directory, it's fairly likely that they're the same sample.

What if they're not? Oh well, the user can simply choose not to replace. The prompt says samples *may be* in another file format, and it's up to the user to choose yes/no.

> *Bulk replacement* is something that should only be done carefully by a human

Sure, I can accept that. Consider the following options, perhaps?

- Yes
- No
- No to all 256 files


Either way, it's probably a good idea for the AFP file browser to start in the location of a missing sample.

**Comment by lukas-w** [comment]
Consolidated into #4309.
