### ISSUE TITLE
Effects plugin list is in reverse order alphabetically ( for the internal plugins )

### ISSUE THREAD

**Issue by mikobuntu** [LMMS/lmms#2834]
**Running latest Master branch**
![reversedorder](https://cloud.githubusercontent.com/assets/335217/15980889/ce0a2656-2f66-11e6-90f8-a859e5a5b5f6.png)

* The internal effects should be in alphabetical order as they used to be.

 * LADSPA Effects are listed correctly.
 * Presently not using windows VST ( via W.I.N.E ), so no way of checking them.

**Comment by tresf** [comment]
:+1:
