### ISSUE TITLE
saved Preset names are reformatted 

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#2839]
saved preset names are reformatted 
OS : winXP sp3
LMMS 1.1.90-g33d8v44

Issue description:
User chosen preset-names are reformatted and saved without capitals

Example:
![namedifferences](https://cloud.githubusercontent.com/assets/6662066/15984984/2b3f28f4-2fde-11e6-9afb-88f2ed2f18a0.png)
Here the preset **gi_TubeDistortedGuitar** are saved, but lmms reformats the name to the less readable gi_tubedistortedguitar.

Recreate:
Save any preset, with capitals in the name, to disk. Lmms reformat the name and removes the capitals

Claim:
If the name is legal in the OS, it should not be reformatted. 
User chosen names should be as the user have made them, also on disk.

**Comment by michaelgregorius** [comment]
Caused by the call to `toLower` in the following line in `InstrumentTrackWindow`:
```C++
sfd.selectFile(fname.remove(QRegExp("[^a-zA-Z0-9\\d\\s]")).toLower().replace( " ", "_" ) );
```
We might consider to remove the `toLower` and the `replace` in my opinion.
