### ISSUE TITLE
essentials things!

### ISSUE THREAD

**Issue by xaviersands** [LMMS/lmms#2843]
1.the benefit to choose in what side of the window i want to put the browser bar (the bar what´s contain all the folders)
2. when i put a wrong plugin for example i want to replace that plugin for other only using click right(like fl studio) o click middle no matter what click, but i consider, that speed the workflow. 
3. a skin change option inside the program
4.visual dbv guide on the side of meters of the console
5. 24 bit option for export sounds and tracks
6. option to choose what type of session setting by default when i starting the program( empty/blank, with specifics plugins, a preset i make) 

well i know exist  a lot of things to change in the program, but i consider this is essentially basic, and i consider too, the fact of  this program is free, and is a big gift for every musician in the world. so THANK YOU FOR MAKE THIS PROGRAM POSSIBLE.

**Comment by DeRobyJ** [comment]
For 2, you can use right click on presets and chose "replace to active instrument"

For 3, you select the folder from settings

For 6, you can use templates, and in 1.2 you'll be able to save one.

**Comment by tresf** [comment]
> 1.the benefit to choose in what side of the window i want to put the browser bar (the bar what´s contain all the folders)

Totally possible but likely won't happen without detachable widgets or a gui rewrite (#1911).  As of #2287, our toolbars use the detachable logic but we have the detachable function disabled.  This should be it's own bug report.

> 2. when i put a wrong plugin for example i want to replace that plugin for other only using click right(like fl studio) o click middle no matter what click, but i consider, that speed the workflow. 

Agreed. Missing plugins have much room for improvement.  This should be a separate bug report.

> 3. a skin change option inside the program

Agreed.  Mentioned in what was [once our futuremap](https://github.com/LMMS/lmms/issues/908) as "on-the-fly" theme changes.  This needs to be a separate bug report.

> 4.visual dbv guide on the side of meters of the console

We're working on it.  #2672

> 5. 24 bit option for export sounds and tracks

This should be a separate bug report.

> 6. option to choose what type of session setting by default when i starting the program( empty/blank, with specifics plugins, a preset i make)

This is really about the default template.  Related #2299.  I agree, adding a GUI option would be nice.  This needs to be a separate bug report.

Your feedback is appreciated.  To help us organize we need to track them separately.  Most of the items you've mentioned aren't being actively tracked elsewhere.  Also, as you rewrite these enhancements, any research or mock-ups you can do as part of the bug report will help the developers.  For example, if `24-bit` needs to be an option on the export dialog, make a mock-up screenshot of it between `16-bit` and `32-bit`, it will put the request into context and quickly explain the feature in a way that a tester and a coder can quickly understand.

Finally, if you have any coding skills, ping some developers for how to get involved.  We all dedicate our free time to this, so any pitching in -- even if trivial -- is appreciated. :+1:

**Comment by tresf** [comment]
@xaviersands,

Please take the time to write-up separate bug reports based on the feedback provided above and we'll track each feature request/issue separately.  Closing this item as invalid but feel free to continue commenting on the close bug report if you have any questions.
