### ISSUE TITLE
Exporting audio is broken

### ISSUE THREAD

**Issue by unfa** [LMMS/lmms#2845]
I'm using version 1.1.3-gcbf6d24 (Linux/x86_64, Qt 4.8.6, GCC 4.8.4) (built from git a few days ago).

Exporting audio produces unusable files - they are sped up, with chopped audio - sounds like a percentage of samples from the audio stream are discarded somehow. Lots of clicks and bad stuff present.

While the rendering is being done, a sped up and messed up version of the track is played back. Sound like JACK freewheeling mode messed up in such a way that the samples computed are played back. But JACK doesn't produce messed up files when this breaks.

Anybody can confirm this issue?

**Comment by mikobuntu** [comment]
Confirmed!!        Linux ubuntu-16.04 64 bit ..... LMMS Master branch from yesterday I think 
Jack and LMMS both at 44100hz
I don't normally use LMMS through Jack as it has/had a history of disconnecting continuously.
@unfa Have you tried with multiple configurations in the LMMS Export settings ? I will test this a bit further when I get more time .

**Comment by unfa** [comment]
Whoa! LMMS crashed now during the export using JACK backend.

What's even weirder - I've seen signal in the mixer channels that are not used in the project. 8O

Exporting with ALSA backend seems to work fine.

**Comment by unfa** [comment]
Okay, new details.

JACK backend produces unusable files, but when using ALSA playback won't work after rendering - I had to restart LMMS to continue work.

**Comment by PhysSong** [comment]
> but when using ALSA playback won't work after rendering

@unfa Can you reproduce this with latest `stable-1.2`?

>JACK backend produces unusable files

JACK issue would be fixed in #4005.

**Comment by zonkmachine** [comment]
No answer, closing. This would have been fixed in #4005.
