### ISSUE TITLE
Fonts To Dark (Apple)

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms#2849]
Related: https://github.com/LMMS/lmms/pull/714

* [ ] Add Effect Dialog ([1](https://cloud.githubusercontent.com/assets/6345473/16065799/c399dd66-327b-11e6-9842-df77d9e40bad.png))
* [ ] OK/Cancel Buttons ([1](https://cloud.githubusercontent.com/assets/6345473/16065801/c3a6ab2c-327b-11e6-9346-6474cdde1e32.png), [2](https://cloud.githubusercontent.com/assets/6345473/16065803/c3a9eb66-327b-11e6-9a17-53f7f7d4b4e4.png), [3](https://cloud.githubusercontent.com/assets/6345473/16065800/c3a33e7e-327b-11e6-9216-61be1467a1d6.png))
* [ ] Add Controller Button ([1](https://cloud.githubusercontent.com/assets/6345473/16065802/c3a6a35c-327b-11e6-921d-f6dd342b6c38.png))

Not font related, but contrast related:
* [ ] White "add effect window" icon ([1](https://cloud.githubusercontent.com/assets/6345473/16065799/c399dd66-327b-11e6-9842-df77d9e40bad.png))

**Comment by musikBear** [comment]
> Fonts To Dark
Agree
Can this tool be of value?
http://snook.ca/technical/colour_contrast/colour.html#fg=33FF33,bg=333333

**Comment by tresf** [comment]
> Can this tool be of value?

In this case, the font color is due to Apple using a different default value for certain components, so no, the tool is of no value in this thread.

**Comment by tresf** [comment]
Hmm... interesting enough, Qt5 on OSX 10.11 seems to fix these items... 

![screen shot 2016-06-21 at 6 08 32 pm](https://cloud.githubusercontent.com/assets/6345473/16248133/43a67b90-37db-11e6-8f5d-900471945ac8.png)

**Comment by tresf** [comment]
Closing since we have no plans to bundle against Qt4 moving forward. Will reopen if that decision changes.
