### ISSUE TITLE
Exporting A Loop Renders Past Loop Points

### ISSUE THREAD

**Issue by toliaferrode** [LMMS/lmms#2851]
I've had a project where I've set loop points in the song editor and when rendering a loop the marker goes past the loop points and renders extra data after the end of the loop.

**Comment by zonkmachine** [comment]
Yes. Render between loop points isn't implemented. Render loop in this case drop the default trailing end that ensures delay/reverb isn't cut out of the render. I close this as a duplicate as it's been mentioned before ( and after... #2965 ). Thanks!

**Comment by zonkmachine** [comment]
The function "Export between loop markers" is implemented in current master and will be in the next release, lmms-1.2 .
