### ISSUE TITLE
Can't open projects anymore

### ISSUE THREAD

**Issue by karmux** [LMMS/lmms#2858]
After couple of months I decided to pull new stuff from master branch.
I can't open any project file anymore. Even empty project that I just saved.
Cursor just keeps spinning and LMMS hangs.
There is no errors in console. Even Valgrind don't show anything.
I'm using latest Kubuntu.

**Comment by BaraMGB** [comment]
Yes, we are waiting for @jasp00 is merging https://github.com/LMMS/lmms/pull/2835

**Comment by jasp00** [comment]
Sorry for the inconvenience.
