### ISSUE TITLE
Weird noise comes and goes

### ISSUE THREAD

**Issue by karmux** [LMMS/lmms#2864]
This is something that started to happen somewhere in last couple of months (i didn't pull so long).
Easiest to reproduce is to just listen some Zyn samples that are bundled with LMMS. Randomly any of the sample can trigger this noise.
This noise kicks in and then after some time suddenly goes. Comes again etc. It affects not only samples in library but also playing song.

Edit: Happens with ALSA only. I have no such problem with SDL.

**Comment by DeRobyJ** [comment]
What LMMS version are you running?
Does this behaviour begin immediately at program start-up?

**Comment by unfa** [comment]
Could you record the sound this issue produces somehow?

**Comment by karmux** [comment]
It sounds like cracle and when playing a song, it plays like 5 times faster with crackling. After LMMS start up it's ok. It comes when playing a song or listening samples. Dissapears soon, playing speed normalizes and then soon will happen again.

I'm using latest in master branch on Kubuntu 16.04. I don't remember this problem couple of months ago. Will try to record it when I get time.

**Comment by jasp00** [comment]
Do you have PulseAudio installed?

**Comment by iurien** [comment]
Foe me on 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux is the same problem (it happens often when you select a Zyn instrument or open Zyn). Pulseaudio is installed.

**Comment by karmux** [comment]
I recompiled many changesets from beginning of the year and couldn't reproduce it anymore.

**Comment by tukkek** [comment]
I'm not involved with LMMS development but maybe you guys should try messing around with the buffer size in the settings dialog. Test several possible values and see if the issue is made better or worse - if it doesn't fix the issue, it could at least provide valuable debugging information. I think it's worth a shot.

**Comment by SecondFlight** [comment]
@karmux Are you still experiencing this issue?

**Comment by karmux** [comment]
No I it was something temporary long time ago.

**Comment by SecondFlight** [comment]
Thanks for the response!
