### ISSUE TITLE
New Theme - Window Contrast

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms#2867]
Per https://github.com/LMMS/lmms/issues/2587#issuecomment-226069613

> *On June 17, 2016 @grejppi wrote:*
>
> I'm concerned about the lack of contrast between overlapping windows:
>
> ![kuvakaappaus 2016-06-17 15-10-52](https://cloud.githubusercontent.com/assets/772336/16150078/b857dfba-349d-11e6-9d68-295db5248b48.png)

Here's a close-up example:

![screen shot 2016-06-21 at 5 54 57 pm](https://cloud.githubusercontent.com/assets/6345473/16247790/83486008-37d9-11e6-850e-3d7a196ad506.png)

Despite the tone of some of the conversations over in #2587, this isn't about opinion, it's about general usability, which is currently suffering due to some decisions made with this new theme.

It would be an injustice to the hard work put into this theme to not resolve these prior to an RC2 release.

**Comment by RebeccaDeField** [comment]
I just want to clarify that in my last comment the opinions that I posted were representing the two sides of feedback I have received from other LMMS users, not my own personal opinion. My personal changes go on the LSP whereas the default theme follows the opinion of the majority.I hope it didn't come across any differently. :simple_smile:

I have no problems with what @budislav suggested and wouldn't mind if the theme goes in that direction if someone has the time to take that on.

The difference between the overlapping windows in the classic theme and this theme is the window border color so I believe that this could be fixed by adding more clear outlines around the windows. I'm thinking that #14171a would be a good shade but I anyone can suggest a different color.

**Comment by tresf** [comment]
> The difference between the overlapping windows in the classic theme and this theme is the window border color

Although borders help, this statement is grossly misleading.  The difference between the classic theme and this theme is much more than a border or a background color.  Here's a side-by-side.

> I just want to clarify that in my last comment the opinions that I posted were representing the two sides of feedback I have received from other LMMS users, not my own personal opinion

I think you explained that well in #2587, which is why I'd like the team to focus solely on usability in this thread.  I'd like an interface that doesn't camouflage windows for an RC2.

![screen shot 2016-06-21 at 5 54 57 pm](https://cloud.githubusercontent.com/assets/6345473/16247790/83486008-37d9-11e6-850e-3d7a196ad506.png) ![screen shot 2016-06-22 at 2 01 57 am](https://cloud.githubusercontent.com/assets/6345473/16256084/61d0311e-381d-11e6-9390-33b4c4da106c.png)

**Comment by RebeccaDeField** [comment]
I was under the impression that this thread was specifically about this:
![b857dfba-349d-11e6-9d68-295db5248b48](https://cloud.githubusercontent.com/assets/7960169/16288179/373c9394-389e-11e6-925c-fcc5d970e28b.png)

I see now that this issue encompasses more than I thought, and after re-reading your previous comments on this topic I think that there was a misunderstanding.

You had asked earlier if the simple palette was intentional. The answer is yes, but this can absolutely be changed by the team. :smile:  So far the solutions that have been proposed are...
(a) Just changing the background and border color
(b) Updating the contrast in an image editing program and then updating all of the elements

If I am understanding correctly, neither of these will work, but I think I have an idea that might accomplish what you are setting out to do...

Let's identify all of the specific problem areas with contrast and build a list of them as they are found. This would be a perfect task for the users because they can report sections that might be confusing or hard to use by using it. The feedback would need to be specific as possible since we have already agreed that there is a general need for adjustments.

Solutions for those areas can be introduced by the more design orientated contributors here (there are a lot) that are willing to donate their time.

This is just what comes to mind but if you know a better way to go about this just let me know! Thank your for time on this as always :+1:

**Comment by tresf** [comment]
"Lack of contrast with overlapping windows" is the bug and the task should be done by those that spearheaded the theme.

**Comment by BaraMGB** [comment]
What's about a drop shaddow? :smile: 

![subwindowschaddow](https://cloud.githubusercontent.com/assets/6502580/16330743/d6a922c8-39eb-11e6-93ad-afc21e6fb8be.png)

**Comment by Spekular** [comment]
Drop shadow looks good to me, but is that a mockup? I thought it might be
difficult to implement.

**Comment by BaraMGB** [comment]
That's no mockup 😊. And it's quite easy to implement.

**Comment by Umcaruje** [comment]
@BaraMGB Do active and inactive windows have different drop shadows? That could make them even more distinguishable.

**Comment by musikBear** [comment]
> That's no mockup :blush:. And it's quite easy to implement. 

@BaraMGB is there a substantial CPU usage increment? afaik, shadows rendering always cost cpu 
In flash that is not negligible. What is the situation in cpp?

**Comment by BaraMGB** [comment]
>Do active and inactive windows have different drop shadows? That could make them even more distinguishable.

Not yet, I tried this between teeth brush and breakfast. It uses only a QGraphicsDropShadowEffect on Subwindow. But I think we can make this themable. 

@musicBear I don't think it cost more than the shadow on the title bar label. It's the same effect. But sure, we have to proof that.

**Comment by RebeccaDeField** [comment]
> What about a drop shadow?
Brilliant idea. This would also work quite nicely with the light border giving the window contrast against the shadow.

We might want even see if we can get a border around the actual Title _Bar_ as the selected title bar seems to blend a bit.

> @BaraMGB is there a substantial CPU usage increasement?

> I don't think it cost more than the shadow on the title bar label.

We should probably test it before pulling it in so see if the CPU usage is worth the usability. :+1: 

Here is a list of the ideas that have been come up with so far...

- Tweak background color
- Tweak border color (this may not apply if we use the shadows)
- Lighten tracks in Song Editor
- Add shadows to windows
- Add border to Title Bars

If anyone has anything else to add, please do! :grinning:

**Comment by musikBear** [comment]
@BaraMGB :+1:

**Comment by BaraMGB** [comment]
Okay, for all who wants to test the shadow and play around with this, here is the branch: https://github.com/BaraMGB/lmms/tree/SubwindowShadow

There seems to be a qt bug. If I add this shadow, the window title disappears. If I remove the shadow from the window title the title appears again. seems we can't have both: window title shadow and window shadow at the same time. 

I also noticed a cpu peak on moving the subwindow with shadow ( @musikBear ) . I don't know if it's worth to implement this. Perhaps we find a better way for contrasting the windows to each other.

**Comment by RebeccaDeField** [comment]
@BaraMGB Would it be possible to create a shadow using borders? We could use a double border around the windows, one that is the border that we are currently using and the other at, say, 5px. The second border could be transparent (using rgba) so that the windows still have a shadow, just a flat one. Please see the very rough mockup below.

![window2](https://cloud.githubusercontent.com/assets/7960169/16364483/de3de2a0-3b9c-11e6-9430-da0ab0d27d12.png)

I'm not sure if this would work, but please let me know as I don't believe this would use very much CPU.

**Comment by BaraMGB** [comment]
Wanna reference this issue https://github.com/LMMS/lmms/issues/2704

>Would it be possible to create a shadow using borders? We could use a double border around the windows

I don't think that is the right approach. In my opinion, we should decrease the contrast and make the colors and increase the brightness just a little bit. On your screen the colors may be fine but I have an old notebook. All colors fades to black. It's hard to see the elements of the gui. At next we could add a bright border to the windows. And if we decided to implement the shadow we should make an option in the preferences to turn this off. 

That's my opinion.

**Comment by Spekular** [comment]
+1 for border shadows from me, fwiw.

**Comment by musikBear** [comment]
> I also noticed a cpu peak on moving the subwindow with shadow ( @musikBear ) 

@BaraMGB Good find! 
@RebeccaDeField Im not too sure about borders. Looks a bit strange where several intersect, BUT! We also need to find a useable solution! 
If borders *is* that solution, then i am not dead against it at all. For me *function* is always the priority :)

**Comment by RebeccaDeField** [comment]
@musikBear @BaraMGB I'm not quite dead-set on the border shadow either (just the first idea that came to mind to cut CPU usage), but it might be worth giving a try. :)

I have some other ideas in progress as well.

**Comment by M4rotte** [comment]
Reassure me… all this cosmetic shadow stuff will be de-activable?

I'd like to use my CPU to render sounds when using LMMS, not to draw some bling-bling shit…

**Comment by Spekular** [comment]
@M4rotte may I suggest using a command line for your music production? That should avoid any "bling-bling" that might use a few CPU cycles to let you see what's going on.

With the new theme, shadows are necessary to avoid windows blending into each other, unless we find something better. They look good too, imo. If you don't want that, you can use the old theme instead.

**Comment by M4rotte** [comment]
@Spekular thx for your sarcastic answer. If I can still use a theme that is low on CPU usage I'm happy :) Also, I should test this new theme…

**Comment by Umcaruje** [comment]
@M4rotte Thanks for calling shadows `bling-bling shit…`, that's something I'll remember.

Anyways, any option that adds significant CPU usage should be made configurable in the performance menu, and we have enough community members that stress this issue, so you don't have a lot to be worried about.

**Comment by musikBear** [comment]
> we have **enough** community members that stress this issue

Hello.. 'waves vigorously with the keyboard from an seriously outdated low end pc*
:speak_no_evil: 

'enough'... :hamster: :heart_eyes:

**Comment by RebeccaDeField** [comment]
I have a couple of ideas that I would like to add.

We could color-pick the colors in the classic theme and change the value of all of the colors to match so that the new theme has the exact same contrast as the classic theme, but the colors match the ModernNoir pallet.

We could make the necessary changes to the ModernNoir theme and package it in the next release, but let the classic theme be default and this theme be the alternative option.

**Comment by Umcaruje** [comment]
>We could make the necessary changes to the ModernNoir theme and package it in the next release, but let the classic theme be default and this theme be the alternative option.

No, I would strongly dissagree about leaving the classic theme default.

This contrast issue is nothing that can't be solved. We can temporarily rename the themes to 'default' and 'modern' just for the RC2, but after that return the themes to the way they were and keep this the default theme

**Comment by BaraMGB** [comment]
I figured out how to change the track color. 
![trackcolor](https://cloud.githubusercontent.com/assets/6502580/16490939/07c071a0-3edc-11e6-80ea-6f40b1a9e8ee.png)

**Comment by tresf** [comment]
@BaraMGB great.  One problems is the title bar being essentially the same color as the toolbar background and side-bar when it has focus.  Can we get the title bar more visibly identifiable when it has focus?

**Comment by BaraMGB** [comment]
@Umcaruje can you make a branch where we can contribute to? So we don't disturb the release candidate procedure. And we can easily merge it if it's done. What do you think?

**Comment by RebeccaDeField** [comment]
@BaraMGB Great! :+1: Is there any way we could make the background behind the tracks lighter than the window bg, then the actual track buttons lighter than that? This might have even more contrast/less blending.

I think that the double border (without transparency) was a great step in the right direction for the title bars.

![2d977730-3df0-11e6-8675-9a0239e5345b](https://cloud.githubusercontent.com/assets/7960169/16497569/7c7a3be6-3eac-11e6-86a3-2660ac6b5847.png)

I also feel that the rounded corners being straight instead will help. We could also lighten the title bars.

**Comment by BaraMGB** [comment]
>Is there any way we could make the background behind the tracks lighter than the window bg, then the actual track buttons lighter than that?

Everything is possible. But I don't understand you. 😁 can you make a picture with arrows?

**Comment by RebeccaDeField** [comment]
@BaraMGB Awesome and no problem. Will make a pic when I get the chance.

**Comment by Umcaruje** [comment]
>@Umcaruje can you make a branch where we can contribute to? So we don't disturb the release candidate procedure. And we can easily merge it if it's done. What do you think?

That's a great idea. let me create a branch.

**Comment by Umcaruje** [comment]
@BaraMGB @RebeccaDeField made a new branch: https://github.com/LMMS/lmms/tree/theme-contrast

Whatever you do concerning the new default theme, should be directed to and based off that branch and not master. When you're doing a Pull request, just compare your branch to this branch and not master, and when you pull to your branch pull from `upstream theme-contrast` rather than `upstream master`

I spoke to @tresf and the current default theme will probably get reverted for the RC2, but the goal is to fix these issues on the separate branch and reinstate the theme back for the 1.2 release.

**Comment by RebeccaDeField** [comment]
@Umcaruje Sounds good :+1: 

@BaraMGB Please see very rough example of my previous comment
![07c071a0-3edc-11e6-80ea-6f40b1a9e8ee](https://cloud.githubusercontent.com/assets/7960169/16512032/cc0b5654-3f0b-11e6-84e7-e9a2f1240f33.png)

**Comment by BaraMGB** [comment]
@RebeccaDeField : 
![trackcolor](https://cloud.githubusercontent.com/assets/6502580/16521010/44a26a02-3f94-11e6-9f3e-8c2bc10f7dcb.png)

**Comment by RebeccaDeField** [comment]
@BaraMGB Make some color tweaks and took out the borders in GIMP. What do you think about something like this?

![44a26a02-3f94-11e6-9f3e-8c2bc10f7dcb](https://cloud.githubusercontent.com/assets/7960169/16541631/5d9a9400-403c-11e6-9ff0-512c70040824.png)

**Comment by Umcaruje** [comment]
@tresf:
![screenshot from 2016-07-08 18 28 55](https://cloud.githubusercontent.com/assets/6282045/16694336/f3888d8a-4539-11e6-98c6-3d361b8d1867.png)
This patch was just merged into the `theme-contrast` branch. Is it ok now? what else needs improving? I want to help out with these contrast issue so we roll out RC2

**Comment by tresf** [comment]
@Umcaruje thanks for the status update.  I think this helps quite a bit.

I'd say anything that stands out in @grejppi's [screenshot](
https://cloud.githubusercontent.com/assets/772336/16150078/b857dfba-349d-11e6-9d68-295db5248b48.png).

But to be specific:

 * The title bars
 * The background of the MdiArea versus the background of the subwindows.

**Comment by Umcaruje** [comment]
![screenshot from 2016-07-08 18 39 33](https://cloud.githubusercontent.com/assets/6282045/16694580/639fcca4-453b-11e6-889e-db6509b027a9.png)
Would a lighter subwindow border like this help out? 

And actually the mdiArea does have contrast in my opinion: 
![screenshot from 2016-07-08 18 41 44](https://cloud.githubusercontent.com/assets/6282045/16694637/a552903c-453b-11e6-9712-46f3ef4842b2.png)

How would you like to tackle the titlebars?

**Comment by Spekular** [comment]
If it were up to me I'd remove the gradient.

**Comment by RebeccaDeField** [comment]
@Umcaruje I think there are a few other things we can implement to help with this as well. I really think that the rounded corners should be turned to straight corners. I also think that the double stroke that @BaraMGB mocked up once will help greatly.

![7c7a3be6-3eac-11e6-86a3-2660ac6b5847](https://cloud.githubusercontent.com/assets/7960169/16700572/ba5ee290-450f-11e6-988d-621ef0c997a7.png)

I believe that darkening the BG will add some more contrast to the title bars. Great work team!

**Comment by Umcaruje** [comment]
>I really think that the rounded corners should be turned to straight corners. 

I don't think that is possible. In the code we are drawing straight rectangles and lines, but its just because we are drawing over the original subwindow it defines the actual shape.

**Comment by RebeccaDeField** [comment]
> I don't think that is possible.

In that case, you can disregard the straight corners bit in my comment.

**Comment by tresf** [comment]
Yes, the edges are better than nothing for sure, but if you zoom out just a bit, you'll see it's not immediately obvious where windows are.


![image](https://cloud.githubusercontent.com/assets/6345473/16703171/4a4c6336-4539-11e6-92ac-ab19dbf401ba.png)

Windows 10 suffers this problem too due to it's obsession with flatness and seems to skirt around it using a mostly white interface foreground combined with pretty heavy drop-shadows (which I believe were ruled out for performance reasons).

So I started thinking of other dark applications, like GitHub's Atom software.  In the case o Atom, they're a single-window-interface, so it's not a fair comparison, but they put a clear distinction between content and toolbars.  From 5 feet away, you know where the code lives and you can quickly recognize the location of components.

![image](https://cloud.githubusercontent.com/assets/6345473/16703235/b95c123a-4539-11e6-8967-de31919d7d1c.png)

**Comment by RebeccaDeField** [comment]
@tresf I understand that the ideas I mentioned may not entirely solve the contrast problems you are having, but I think, as you said, that it can help. Let's make PR's for the ideas that help and just keep it up until it looks right. :+1: 

Ideas so far...

- Tweak background color
- Tweak border color, size and wrap around the whole window
- The sidebar is another area that might be worth playing with to give a bit more contrast.


The biggest struggle specifically with overlapping windows (not regarding the other areas that could benefit from more contrast) is that the windows are the same color. We can't use shadows, but borders are a good start. We could try thicker, light borders (like 3px) that wrap around the whole window.

**Comment by BaraMGB** [comment]
>>    @RebeccaDeField :
>>    I really think that the rounded corners should be turned to straight corners.

> @Umcaruje :
>I don't think that is possible. In the code we are drawing straight rectangles and lines, but its just because we are drawing over the original subwindow it defines the actual shape.

I found a solution for this.

**Comment by BaraMGB** [comment]
![straight_corners](https://cloud.githubusercontent.com/assets/6502580/16727134/e5b7a4fc-475f-11e6-9247-7bda091d2eb7.png)

Seems to work, at first. I want to stress this a little bit today.

**Comment by BaraMGB** [comment]
Another idea : in previous versions of lmms we had a tiled pixmap background in the MdiArea. I guess it would increase the contrast a lot. That's not cosmetic purpose alone.

**Comment by RebeccaDeField** [comment]
@BaraMGB Maybe you could use a similar pattern to what @Umcaruje used in his LMMS mockup. I also created a couple of low-poly background ideas that I never used but they are still in the source files.

**Comment by Umcaruje** [comment]
status update: 
![screenshot from 2016-07-19 01 08 39](https://cloud.githubusercontent.com/assets/6282045/16933425/85e3f08c-4d4d-11e6-9b05-d29a97878aa7.png)
This is how the `theme-contrast` branch looks now

**Comment by RebeccaDeField** [comment]
I'm making a PR for some other color updates as well. Will updated here when it's done.

**Comment by BaraMGB** [comment]
@Umcaruje @RebeccaDeField what's about making the active FX line lighter?

![fxlinelighter](https://cloud.githubusercontent.com/assets/6502580/17146516/19dc6636-535f-11e6-9cb7-46972b9b0d41.png)

I've also removed the gradient here.

**Comment by RebeccaDeField** [comment]
@BaraMGB Don't have a problem with it, but would love the color to be the same as the lighter track labels for consistency :)
