### ISSUE TITLE
Compile plugin w/ multiple source files?

### ISSUE THREAD

**Issue by TheRealCodeCube** [LMMS/lmms#2870]
How can I use the CMake macro BUILD_PLUGIN to build a plugin with multiple .cpp files?

**Comment by tresf** [comment]
I've never done this before personally, but here's an example from [VstEffect](https://github.com/LMMS/lmms/blob/master/plugins/VstEffect/CMakeLists.txt#L16):

```java
BUILD_PLUGIN(vsteffect VstEffect.cpp VstEffectControls.cpp VstEffectControlDialog.cpp 
   VstSubPluginFeatures.cpp VstEffect.h VstEffectControls.h VstEffectControlDialog.h 
   VstSubPluginFeatures.h MOCFILES VstEffectControlDialog.h VstEffectControls.h 
   EMBEDDED_RESOURCES "${CMAKE_CURRENT_SOURCE_DIR}/*.png")
```

**Comment by TheRealCodeCube** [comment]
Thank you! This is exactly what I need.

**Comment by tresf** [comment]
Great, closing as answered. :+1:
