### ISSUE TITLE
Export window dosen't close

### ISSUE THREAD

**Issue by iurien** [LMMS/lmms#2874]
Export window doesn't close, and the application freezes. The export file is created correctly.

How to reproduce:  export to wave.

Build: 1.1.90-gb8d1353
OS: 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux

**Comment by jasp00** [comment]
I have this one fixed, but there are some side issues I would like to take care of.
