### ISSUE TITLE
Redesign LMMS

### ISSUE THREAD

**Issue by sibiot** [LMMS/lmms#2881]
After some expereince with LMMS, I encountered some problems with the graphical user interface of the application, and redesigning the UI of LMMS would be handy to many people all over the world.
I'm sure that working on user-friendliness would boost producer's productivity by many percents.

First, LMMS has an outdated and non-unified user interface, for example the focus on MDI workspace concept that belongs to the previous decades, and there isn't a comfortable way to play the song straight from the main toolbar.

Another example is the out-of-date _ZynAddSubFX_ instrument that consists of way too many windows and dialogs, in addition to the unreadable English there and the unaesthetic "90ish" control appearance.

I recommend also increasing the flexibility of editors like _Song Editor_ such as allowing zoom in and out more precisely without limiting it to the zooms in the unnecessary combo box in the toolbar.

The last design change that I'd like is to make all the interface components slightly bigger, so that would benefit touchscreen users. Most plugins are infected with a small, complex and inconsistent user interface that makes the usage difficult for people. Please get rid of the annoying "Show GUI" button on external plugins.

Finally, I hope, along with everyone who is dissatisfied with the current user interface of LMMS, that the developers here would pay attention to this comprehensive problem and work on it, and this may lead to a greater success of LMMS, the (currently-not-so-)powerful free audio workstation.

Sorry for my bad English if there is...

**Comment by tresf** [comment]
We are working on it.  These points are all duplicates.  Please learn to search first

**Comment by Spekular** [comment]
@sibiot 

> LMMS, the (currently-not-so-)powerful free audio workstation

None of the things you've mentioned really affect what you *can* do with LMMS. I agree that there might be UX issues, but I don't think it's fair to say that LMMS isn't powerful.
