### ISSUE TITLE
Compiling lmms - Error in the wiki ? wine-dev

### ISSUE THREAD

**Issue by zapashcanon** [LMMS/lmms#2884]
Hi,

I just tried compiling lmms. It works, but I think there's a mistake in the wiki.

It's written:

    apt-get install [...] wine-dev

But this package doesn't exist in Debian (and seems not to in Ubuntu neither).

So, I guess it's one of the following:

- libwine-dev
- libwine-development-dev

Or even maybe:

- libwine-development
- wine-development

(see the [debian website](https://packages.debian.org/search?keywords=wine-dev&searchon=names&suite=all&section=all&sourceid=mozilla-search))

But I've got no idea about it. Could some one tell me which one is correct ? I'll correct the wiki if needed then. :)

EDIT:

cmake gives this output:

    * VST-instrument hoster       : not found, please install (lib)wine-dev (or similar) - 64 bit systems additionally need gcc-multilib and g++-multilib

So I think it's libwine-dev.

**Comment by tresf** [comment]
Travis seems to be OK with `wine-dev` per https://github.com/LMMS/lmms/blob/master/.travis/linux..install.sh

**Comment by liushuyu** [comment]
Seems like `wine-dev` is not in official repository.

**Comment by liushuyu** [comment]
>So, I guess it's one of the following:
>
>libwine-dev
>libwine-development-dev

I think is `libwine-dev` in Debian…

**Comment by zapashcanon** [comment]
Travis "is running" Trusty while I'm running Debian (unstable). Indeed, it was libwine-dev, should I update the wiki ?

See [ubuntu website](http://packages.ubuntu.com/search?suite=all&section=all&arch=any&keywords=wine+dev&searchon=names), no libwine-dev here...

**Comment by liushuyu** [comment]
>should I update the wiki ?

Maybe you need to make it clear that `libwine-dev` is for Debian, not for Ubuntu 

>See ubuntu website, no libwine-dev here...

We add some more extra third-party repositories to our Travis environment, so the package `wine-dev` might be in one of these repositories.

**Comment by zapashcanon** [comment]
Done.

But there is some strange things with the wiki...

    Or, manually:

    sudo apt-get install build-essential cmake libqt4-dev libsndfile1-dev libfftw3-dev \
    libvorbis-dev libogg-dev libasound2-dev libjack-dev libsdl-dev libsamplerate0-dev \
    libstk0-dev libfluidsynth-dev portaudio19-dev libfltk1.3-dev wine-dev \
    libxinerama-dev libxft-dev libgig-dev git

First, `libsdl-dev` doesn't exist in Debian or Ubuntu, it's `libsdl1.2-dev` in both.
Then, except for wine-dev, all of this package are available in Debian - and should be in other derivatives too. Thus, I don't understant why there's just after:

    On other Debian-based systems, run instead:

    sudo apt-get install cmake ladspa-sdk libsamplerate0-dev libsdl1.2-dev \
        libsndfile1-dev libvorbis-dev libjack-dev libstk0-dev libfltk1.3-dev \
        fluid libasound2-dev libqt4-dev libpulse-dev libfluidsynth-dev \
        libfftw3-dev portaudio19-dev qt4-qmake libgig-dev

**Comment by tresf** [comment]
> First, libsdl-dev doesn't exist in Debian or Ubuntu

It is perfectly valid in Ubuntu. It's a meta package.

```
Note, selecting 'libsdl1.2-dev' instead of 'libsdl-dev'
```

**Comment by zapashcanon** [comment]
Hum ok. It's not listed on the [package search engine](http://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=libsdl+dev&searchon=names)...

**Comment by tresf** [comment]
> Indeed, it was libwine-dev, should I update the wiki ?

No.

```
E: Unable to locate package libwine-dev
```

> But this package doesn't exist in Debian (and seems not to in Ubuntu neither).

It is perfectly valid in Ubuntu.  These meta packages conveniently allow the commands to be version agnostic.  Debian may not like them, but neither does non-Debian distributions.  The wiki states it was written for Ubuntu 12.04 as at one point that was the most common build platform.  If this is no longer true, we'll need to either pick a new standard for the base compilation tutorial or start splitting the package listing for each distribution (probably the best option).  As it stands, Travis' script does the majority of the work anyway.  We even updated our Mac homebrew instructions to just call the Travis script.  Perhaps we just make a small package listing for each distribution as searching for dependencies with each new Linux flavor can certainly add unnecessary time to the build process.
```
Note, selecting 'wine1.6-dev' instead of 'wine-dev'
```

**Comment by zapashcanon** [comment]
I see.

wine-dev neither was listed.

> allow the commands to be version agnostic.

For wine-dev, idk. But for libsdl, as the 2.0 is here for a few times. I'm not sure it's a good idea.

But anyway, except those two packages, why is the "other Debian-based systems" packages list different when all the others packages are available in Debian ? e.g. git and build-essential are in the first one, but not on the other etc.

**Comment by tresf** [comment]
> It's not listed on the package search engine...

I found them... they're called "Virtual Packages".  Search doesn't list them, but you can browse them by URL... 

```
http://packages.ubuntu.com/trusty/<<<virtual-package-name>>>
```

e.g. http://packages.ubuntu.com/trusty/libsdl-dev

> But anyway, except those two packages, why is the "other Debian-based systems" packages list different when all the others packages are available in Debian ?

I don't know.  Ping @jasp00 he authored that section 15 days ago.

**Comment by zapashcanon** [comment]
Yup', I know what are meta-package, but I expected them to be shown when searching - like in Debian. My bad.

Ok. @jasp00 then. :p

**Comment by jasp00** [comment]
The list for Debian comes from the current [packaging in Debian](https://anonscm.debian.org/cgit/debian-edu/pkg-team/lmms.git/tree/debian/control). You may add `build-essential`. `git` is not important, it is useless if you compile from a source tarball. `libwine-dev` is not usable on non-i386 systems; on i386, the dependency is `wine32-tools`.

**Comment by zapashcanon** [comment]
`libwine-dev` works on my amd64 system, just needs to add a flag as it's written in the wiki.

Yep' I was saying git and build-essential but I didn't look in details, I think there are others.

I'll have a look and maybe propose an update of the list.

**Comment by tresf** [comment]
> The list for Debian comes from the current packaging in Debian. You may add build-essential. git is not important, it is useless if you compile from a source tarball. libwine-dev is not usable on non-i386 systems; on i386, the dependency is wine32-tools.

It should still be consistent though, no?

**Comment by jasp00** [comment]
> `libwine-dev` works on my amd64 system, just needs to add a flag as it's written in the wiki.

`libwine-dev` for amd64 is a useless download. The one for i386 is relevant on amd64.

> I guess you meant it's not usable on i386 systems.

No, I meant it is not usable on non-i386 systems: the amd64 version, the powerpc one, etc.

> It should still be consistent though, no?

The list will be different for the wine dependency because the packages in Debian and Ubuntu differ. The other packages could be the same. I have not tried the Debian list in Ubuntu; `fluid` is needed in Debian; `libxinerama-dev` and `libxft-dev` are not.

**Comment by zapashcanon** [comment]
I see. So, wine-dev is useless on Ubuntu amd64 too. But, it's in the default list..

**Comment by tresf** [comment]
Since this is a documentation task and it has been addressed/answer, I'm closing this out.  Please feel free to make any necessary changes to the wiki as needed.

**Comment by jasp00** [comment]
Wine in Ubuntu is different from Debian. In Ubuntu, both amd64 and i386 files are installed on amd64. It works in Ubuntu, it does not in Debian yet.
