### ISSUE TITLE
High CPU usage on master

### ISSUE THREAD

**Issue by BaraMGB** [LMMS/lmms#2887]
I notice high CPU usage on master since e55ec80c3d956dea8674afc0755bc87831c64ce6 on idle.

![cpu](https://cloud.githubusercontent.com/assets/6502580/16540217/b09dd46c-405c-11e6-87d1-87e82e5b44fe.png)

Kubuntu 14.04 64bit Qt4 and Qt5 build testet

@jasp00

**Comment by jasp00** [comment]
Yes, the CPU meter does not show it, but there is high CPU usage. I will look into it.
