### ISSUE TITLE
New Theme - Menu Icons

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms#2892]
The uppermost menu icons on Mac aren't very visible when running the default desktop theme.

I assume the decision to replace these icons with white was made so that the icons would be consistent with the new darker theme, however Mac relocates the menu icons to the OS bar and draws white over gray.

Is there a way to invert the icon colors for situations like this so that we can have the best of both worlds perhaps a [`setColorTable`](http://doc.qt.io/qt-4.8/qimage.html#setColorTable) implementation?

![screen shot 2016-07-02 at 11 55 17 am](https://cloud.githubusercontent.com/assets/6345473/16541252/ef6d0bba-404b-11e6-95df-9752aa9f67b5.png)

**Comment by simonvanderveldt** [comment]
FYI this is fixed in newer Qt5 versions https://codereview.qt-project.org/#/c/115120/, so maybe it's an option to switch the Mac OS use that?
(obviously some code changes will have to be made as well)

**Comment by tresf** [comment]
@simonvanderveldt thanks, which Qt version does this become available in?  I ask because Qt 5.6 (specifically `macdeployqt`, which is essential for bundling) suffers this problem #2862, so white icons may be the lesser of two evils for now.

**Comment by simonvanderveldt** [comment]
@tresf afaik 5.6 :x though I can't find any references to in the releasenotes.

**Comment by tresf** [comment]
Since #3349, this really isn't an issue.  Only the "document" style icons are still in the menu system and they don't look that bad.

![screen shot 2018-02-10 at 10 35 17 pm](https://user-images.githubusercontent.com/6345473/36069185-c76ab1d0-0eb2-11e8-9a70-a95831e2baf3.png)

Closing as `wontfix`.
