### ISSUE TITLE
LMMS is disconnected from JACK

### ISSUE THREAD

**Issue by jdloft** [LMMS/lmms#2896]
This issue has come up in the past but it seems that all of them have been closed as being fixed with newer versions of LMMS.

LMMS is disconnected from JACK following a brief period of time (where it works normally; usually 2-3 seconds).

Output: http://pastebin.com/9JW75DyU

It seems the culprit is `subgraph starting at lmms timed out (subgraph_wait_fd=31, status = 0, state = Triggered, pollret = 0 revents = 0x0)` since something like that shows up every time LMMS is disconnected, reconnects, and is disconnected again.

Ubuntu 14.04
LMMS: compiled from master (3baedf3)
Jack: `jackd version 0.122.0 tmpdir /dev/shm protocol 24`

**Comment by DeRobyJ** [comment]
I'm on KXStudio 14.04, lmms compiled from master, I load lmms from Claudia (custom command), and it works fine on Jack.

**Comment by tresf** [comment]
This is an upstream issue, most likely with ALSA per http://jack-audio.10948.n7.nabble.com/JACK-with-ALSA-backend-subgraph-times-out-td7858.html.  Closing as `not our bug`.  Please ask for reopen if you have evidence suggesting otherwise.
