### ISSUE TITLE
New Samples for LMMS 2.0

### ISSUE THREAD

**Issue by SirBothersome** [LMMS/lmms#2900]
Hello, I am SirBothersome, a.k.a. mrlmmsguy, and I'm going to be your waiter for a loooong time.
I'm taking over the Samples repo and have decided to take up the mantle of "Bringer of New LMMS Samples".
            The old samples have been complained of frequently, and I found what may have been the source site for one (the raving_crowd.ogg). The terms and conditions for that site only allowed the samples for personal use, and the nontrasferrability of the license seems to rule out redistribution. 
I'm planning to make some new samples specifically for LMMS, but I need your help. If you've made samples **from scratch** or know of Public Domain samples, please comment.
        If @unfa  and @StakeoutPunch  could also provide further details on their sample packs, that would be nice too. Lastly I think we should make the samples uniform in format, which is where you, the readers, come in. Should the samples be mono or stereo? .ogg's or .wav's? An honest, open-minded discussion is needed to provide LMMS users with the best samples and to speed the creation of this repository, as we may be on shaky legal ground with our current one. I'll post more details over the next few weeks
God Bless and good day

**Comment by tresf** [comment]
@SirBothersome welcome and thanks for offering your time, we need help with the samples and we've had very few volunteers to manage them.  P.S.  Discussion should be kept in `lmms/samples`.  No need to flood this tracker.

**Comment by Umcaruje** [comment]
>which is where you, the readers, come in. Should the samples be mono or stereo? .ogg's or .wav's?

No ogg's. Lossless only, which means .flac or .wav. I'd recommend .flac since it takes up less space. 44100 or 48000 sample rate, Stereo.

Though this discussion shouldn't be done here, but on the samples repo.

**Comment by SirBothersome** [comment]
> No ogg's. Lossless only, which means .flac or .wav. I'd recommend .flac since it takes up less space. 44100 or 48000 sample rate, Stereo.

Thank you for the feedback @Umcaruje . Now I have sufficient data. Will begin beta testing soon. As this thread is no longer necessary, and I have https://github.com/LMMS/samples/issues/21 to preview the samples, I am closing this issue with a majestic harrumph. HARUMPH!

**Comment by Umcaruje** [comment]
> I am closing this issue with a majestic harrumph. HARUMPH!

Stop with these riddles please.
