### ISSUE TITLE
No Steinberg attribution

### ISSUE THREAD

**Issue by SirBothersome** [LMMS/lmms#2901]
I was just reading the Steinberg license agreement for VST 3.0 and it's respective SDK. One clause is that we must reference Steinberg's copyright in our documentation. which I have been unable to find. While this is a new license, (I am yet to find the old one), I'm pretty sure that the conditions are the same/similar to any legacy license, and if not, this is probably legally binding anyway

**Comment by tresf** [comment]
It's reverse engineered, we don't use his SDK.

**Comment by SirBothersome** [comment]
but #2830 seems to suggest otherwise

**Comment by tresf** [comment]
> but #2830 seems to suggest otherwise

And the author of that code has closed the issue out as resolved.

**Comment by SirBothersome** [comment]
But there still is the issue of Legacy repos/LMMS downloads which would still contain the old source code, no? Adding the copyright reference to the docs may be superfluous, but if it is not, then I think we'll be very glad we added it

**Comment by tresf** [comment]
Yes, old versions will continue to have the suspected code.  It is fixed moving forward only.

**Comment by SirBothersome** [comment]
> Yes, old versions will continue to have the suspected code

So why can't we put in the reference? Here's Steinberg's EULA  
>"Steinberg’s copyright notice should be included in the documentation, regardless of the media
used to supply the documentation. 
Copyrights notice:"VST is a trademark and software of Steinberg Media Technologies GmbH" 
b) The VST Logo has to appear on packages and promotional material. 
The VST Logo artwork and usage guidelines are part of the 
"Licensed Software Developer Kit"" [Steinberg VST Plug-In SDK Licensing Agreement
(Version "3.1– 01.02.2010")]

All we have to add is the reference to our wiki, and the logo stamp in our promo video, or it's description

**Comment by tresf** [comment]
> So why can't we put in the reference? Here's Steinberg's EULA

Because we're not adding commits to a dead branch because you decided to look at one bug report.  We have plenty of construction around here.  Please stop pointing at the stain in the carpet.

**Comment by SirBothersome** [comment]
>Because we're not adding commits to a dead branch because you decided to look at one bug report. We have plenty of construction around here. Please stop pointing at the stain in the carpet.

@tresf ? This doesn't have anything to do with our GItHub repo, I'm talking about our user documentation, [https://lmms.io/documentation/](url) a change that should take maybe five minutes.

**Comment by tresf** [comment]
This is getting out of control.  No, we are not adding Steinberg copyright information to our documentation. Stop.

**Comment by jasp00** [comment]
@SirBothersome, adding Steinberg's brand would not work. If the code was copied indeed (I am not certain), the only choice is to stop distributing affected versions of the header. That would mean to stop distributing older binaries because of GPL.

Debian packages have this problem. I would expose the situation to their [legal team](https://lists.debian.org/debian-legal/), stressing that I only *suspect* that the code comes from Steinberg SDK. If they determine their Debian packages must be fixed, then maybe version 1.1.3 should be fixed too.

**Comment by SirBothersome** [comment]
@jasp00 Thank you for clarifying, sir. I did not realize this was Debian only. Will go back to shutting up now.
