### ISSUE TITLE
trying to show a QMessageBox when no gui is present in command line

### ISSUE THREAD

**Issue by serdnab** [LMMS/lmms#2902]
when using command line for rendering if the output or config file aren't writable, it can't create the QWidget showing the error message, because there is no gui
What do you think of including `GuiApplication.h` on the respective classes, and `if (gui)` shows the QMessageBox, or else a console message?

**Comment by Spekular** [comment]
I'm pretty sure including the GuiApplication.h in more files goes against
the initiative to decouple the Engine and Interface. Isn't it better to
send the errors via console if the messagebox fails? Or, if
GuiApplocation.h is required to check for a GUI, always send the messages
to console.

**Comment by Umcaruje** [comment]
>or else a console message?

I think this would be very much preffered.

**Comment by serdnab** [comment]
@Spekular 
> if the messagebox fails

Is there a way to check that?

> always send the messages to console

the problem is that when lmms starts normally (with gui) those error messages need to be displayed in a `QMessageBox`

**Comment by Spekular** [comment]
@serdnab Sorry, I should have been more clear. I meant always send them to both the console and the GUI. The user will only see them where they check so it should be fine, unless I'm missing something.

**Comment by zonkmachine** [comment]
I agree with @serdnab 

It crashes [here](https://github.com/LMMS/lmms/blob/master/src/core/audio/AudioFileDevice.cpp#L63):


> Isn't it better to send the errors via console if the messagebox fails?

The messagebox fails by crashing lmms.

```
QWidget: Cannot create a QWidget when no GUI is being used
Aborted (core dumped)
```
> Or, if GuiApplocation.h is required to check for a GUI, always send the messages to console.

This is how it's done elsewhere in the code. 
https://github.com/LMMS/lmms/blob/master/src/core/DataFile.cpp#L134:L146

**Comment by zonkmachine** [comment]
We could test it like this the first thing [before](https://github.com/LMMS/lmms/blob/master/src/core/main.cpp#L665) proceeding to render:
```
		QFileInfo file( renderOut );
		if( ! file.isWritable() )
		{
			printf("Failed to write to %s, please check your permissions!\n",
							fileToLoad.toUtf8().constData() );
			exit( EXIT_FAILURE );
		}
```
