### ISSUE TITLE
Source code of included libraries in installers

### ISSUE THREAD

**Issue by jasp00** [LMMS/lmms#2937]
Because LMMS and many included libraries require the corresponding sources to be available, an archive with source packages should be available to download. We are currently relying on third-party sites. If they stop providing the sources, the affected installers should be removed.

**Comment by tresf** [comment]
https://github.com/LMMS/lmms/tags

**Comment by tresf** [comment]
Can you be more specific?  Are you saying we should bundles a version with all source dependencies?

**Comment by jasp00** [comment]
For instance, the Linux installer includes `libQtCore.so.4` and `libsamplerate.so.0`. They come from `libqtcore4` and `libsamplerate0` binary packages. Thus, an archive containing `qt4-x11` and `libsamplerate` source packages should be available as a separate download.
The same happens in the Windows installer with `.dll` and `mingw-` source packages. A single archive containing the source packages related to all installers should be enough.

**Comment by tresf** [comment]
I'm not familiar with this and it sounds like a lot to manage without much reward.  I'm nit even sure the use-case.  Most source depends on more source so to have a comprehensive source archive with alli seems to be more work than what it is worth.

**Comment by jasp00** [comment]
Perhaps the archive is not needed. A documentation page stating how to obtain the sources would be enough. For instance, Trusty sources are at http://archive.ubuntu.com/ubuntu/ , but they will end up eventually at http://old-releases.ubuntu.com/ubuntu/ ; MinGW sources are at http://ppa.launchpad.net/tobydox/mingw-x-trusty/ubuntu/ ; libsoundio sources are at http://ppa.launchpad.net/andrewrk/libgroove/ubuntu/ .

**Comment by tresf** [comment]
@jasp00 most of these are mentioned (project pages, not source pages) on the Compiling-lmms tutorial.  https://github.com/LMMS/lmms/wiki/Compiling-lmms

We could add the mingw stuff to the Windows tutorial unless you have a better idea... perhaps a "Source" page in our wiki?

**Comment by jasp00** [comment]
> most of these are mentioned (project pages, not source pages) on the Compiling-lmms tutorial.

Project pages are not suitable, because the problem is not how to build LMMS, but how to build the exact libraries included in the installers.

> perhaps a "Source" page in our wiki?

Something like "Source code of included libraries in installers". An alternative to the wiki would be a script that downloads the source packages.

**Comment by tresf** [comment]
> Project pages are not suitable, because the problem is not how to build LMMS, but how to build the exact libraries included in the installers.

I'm not talking about how to build LMMS, I'm talking about how to fetch the source of the dependencies per

> Perhaps the archive is not needed. A documentation page stating how to obtain the sources would be enough.

Building the "[...] exact libraries in the installer" is arguably way out of scope for our project I strongly feel.

> Source code of included libraries in installers [...] script that downloads the source packages.

So you want to commit a file to our source tree with hard-links to source repos?  What is the use-case for this?  Should we have a test-bed? i.e. A system which builds purely from source and never from pre-built binaries?  Is this something that would be just for reference or something triggered by Travis-CI so we know it's always in good shape?

**Comment by tresf** [comment]
@zonkmachine you've :+1:.  Do you have any feedback on this?

**Comment by jasp00** [comment]
The problem is that we are distributing binary libraries without the corresponding source. If libqtcore4 version 4:4.8.5+git192-g085f851+dfsg-2ubuntu4.1 is bundled, the source for this version must be available; this is a license requirement.

>So you want to commit a file to our source tree with hard-links to source repos?

Yes.

>What is the use-case for this?

The reason to provide these sources is to meet a license requirement. A use-case would be a user that wants to audit the code to know if it has vulnerabilities.

>Should we have a test-bed? i.e. A system which builds purely from source and never from pre-built binaries?

Not for us, that would be prohibitive, but a user may want to have such a system.

**Comment by tresf** [comment]
Then I vote we provide a written offer.  Distributing all source is ludacrious given our contributor base.  It is unsustainable, unreasonable unless we can find a way to automate it.

https://www.gnu.org/licenses/old-licenses/gpl-2.0-faq.en.html#WhatDoesWrittenOfferValid

**Comment by tresf** [comment]
The author of this request has left and no one's chiming in to help.  Closing due to lack of resources. It's with fair reason to assume the development team can provide means to obtain the source to dependent libraries upon request.
