### ISSUE TITLE
Tutorial to Create and build a Simple Plugin(Not VST)

### ISSUE THREAD

**Issue by Delaley** [LMMS/lmms#2946]
I've been searching for a tutorial to create a simple plugin for LMMS to Manipulate Certain behaviours
but i can't find any.
A step by Step Approch would be good.
Thanks in Advance

**Comment by tresf** [comment]
> create a simple plugin for LMMS to Manipulate Certain behaviours

Behavior in sound or interface automation?

We don't have good examples yet, but cloning and renaming a native effect or native instrument plugin is our best advise to start with.  Here's a relatively recent Effects plugin that was written.

https://github.com/LMMS/lmms/issues/1376

A more simple Effects plugin is the Amplifier:

https://github.com/LMMS/lmms/tree/master/plugins/Amplifier

And here's a relatively recent instrument plugin that was written:

https://github.com/LMMS/lmms/commit/8b51e29467773d1227983002126a82b2266b0fa8

The task of creating a tutorial for plugins has been needed for a while.  We'll leave this open for the sake of documentation improvement, but you may find yourself documenting this task as you learn the architecture.

Also, if you're looking to do something a bit more from the Automation side of things, [Controller](https://github.com/LMMS/lmms/blob/master/src/core/Controller.cpp) may be a good starting point for studying.

**Comment by Delaley** [comment]
Thanks for the fast reply.Going to work

**Comment by SecondFlight** [comment]
A more general version of this maybe ought to be part of a larger documentation effort, but this is a very specific request that I don't believe there is much need to fill.
