### ISSUE TITLE
A drum rack/multi-sampler 

### ISSUE THREAD

**Issue by kerbingamer376** [LMMS/lmms#2947]
Hi,
would it be possible to add an instrument that works as a multi-sampler, allowing you to set multiple samples to be played when different keys are pressed? (Like drum racks in ableton)?

**Comment by tresf** [comment]
Duplicate of https://github.com/LMMS/lmms/issues/1460.  Not possible yet through LMMS alone although you may have luck with a 3rd party drum sampler plugin.
