### ISSUE TITLE
Calf Exciter don't like to be exported

### ISSUE THREAD

**Issue by karmux** [LMMS/lmms#2953]
If there is Calf Exciter on some mixer channel then exported song sounds much louder and distorted. After export also playback is louder and distorted. Before exporting playback is correct. Disabling Calf Exciter fixes playback and export but have to reopen project to have correct playback with Calf Exciter enabled. I had similar problem with Calf Limiter but there I found a workaround. I always disable ASC.

Easily reproducible with Greippi - Krem Kaakkuja (Second Flight Remix) demo song. Add Calf Exciter before hard limiter to master channel. Export settings and exciter settings don't matter.

Latest master on latest Ubuntu.

**Comment by zonkmachine** [comment]
Confirmed! This is a duplicate of #2357 Same behaviour and from the same source file.
I close the other issue as this is more descriptive.

**Comment by zonkmachine** [comment]
> from the same source file

https://github.com/LMMS/lmms/blob/master/plugins/LadspaEffect/calf/src/modules_dist.cpp

**Comment by karmux** [comment]
This is not an issue anymore in current master.

**Comment by zonkmachine** [comment]
Did you test the Calf Bass Enhancer too? #2357

**Comment by karmux** [comment]
Tested now and didn't notice any clipping.

**Comment by PhysSong** [comment]
I think I'm still experiencing this issue. I'll try to find a reliable way to reproduce it. If I found one, I'll reopen this.

**Comment by PhysSong** [comment]
NVM, It seems like I used the old CALF plugin.
