### ISSUE TITLE
No Vst support on Linux Mint 18 64bits

### ISSUE THREAD

**Issue by barbichel** [LMMS/lmms#2958]
Hi, so apparently there is an issue with the AMD64 package on Vst support (when installing manually I got an error saying that it is " Unable to locate package lmms-vst-full", and the VeSTige plugin is not showing). 
I have found a workaround in previous threads, where people used another PPA instead (https://launchpad.net/~irie/+archive/ubuntu/lmms), but this one does not support Xenial, so there's no way for me to install it. 
So is there any way to get vst support in the latest ubuntu based releases ? Or maybe I've just missed something?

**Comment by tresf** [comment]
@barbichel building `master` branch (future 1.2.0) from source is probably the best approach at this point until we make an official release.  Most distributions mirror our official release and we haven't finished 1.2.0 yet so most of them are stuck on 1.1.3 until then.  Note, 1.2.0 is in RC status.  It's pretty good for daily use.

**Comment by doyousketch2** [comment]
Years ago on another computer I got it to compile the VST plugin through Wine.
I don't recall the exact settings though.  I know I had to jump through hoops.
Most likely ended up building wine from source.

These appear to be the relevant entries in the CMakeCache.txt
<code>
//Include VST support
WANT_VST:BOOL=ON

//Include partial VST support (without wine)
WANT_VST_NOWINE:BOOL=OFF

//Path to a program.
WINE_CXX:FILEPATH=/usr/local/bin/wineg++

//Path to a file.
WINE_INCLUDE_DIR:PATH=/usr/local/include/wine

//Path to a library.
WINE_LIBRARY:FILEPATH=/usr/local/lib/libwine.so
</code>

I know there's a github post somewhere that mentions setting the compile flag:
<code>cmake -DWANT_VST=no ../</code>

It seems that at least for me, "no" doesn't appear to be a proper boolean argument,
so it should read:
<code>cmake -DWANT_VST=OFF ../</code>

Again, I don't recall the exact steps to get it to compile,
and I always see an error at about 80% when it gets to that point,
unless I turn that feature off.


You can get a precompiled version by adding the KXStudio repository
http://kxstudio.linuxaudio.org/Repositories

If you then feel like compiling from source,
you can still do so, it just won't update the VST plugin
until the KXStudio repo gets updated.

I don't know how often that one gets updates.
I know it always has more recent builds than the ones from the Debian repos.

Either way, this should solve your prob.

**Comment by tresf** [comment]
Closing, this was resolved a long time ago, we added better support for detecting various wine installations.    See also https://github.com/LMMS/lmms/pull/3708 although the code has moved around a bit, so the patches have changed since they were merged.
