### ISSUE TITLE
unbalanced output in L/R stereo-channel

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#2961]
I was wrong -This can be deleted. My idea can be simple fixed with the panning control 8| And i had a real 'cute' mockup.. 
![sepvolui](https://cloud.githubusercontent.com/assets/6662066/17443740/87ad7454-5b3c-11e6-8cc8-2e1a9c8e5b11.PNG)
:p

**Comment by Umcaruje** [comment]
Issues can't be deleted. If you made a mistake please close the issue.
