### ISSUE TITLE
Error in version numbering

### ISSUE THREAD

**Issue by serdnab** [LMMS/lmms#2969]
I'm not sure but I believe there is an error in version numbering.
`ProjectVersion.cpp` assumes that 1.x.y is major than 1,x,y-patch as we see in this line:

https://github.com/LMMS/lmms/blob/8b96172650781e0fdaf4c68accaf40c016a4ff47/src/core/ProjectVersion.cpp#L114

And actually the releases are just the opposite, the patch versions are more recent.
This could cause errors in upgrade methods in `DataFile.cpp`.

Also, between patch versions, it compares the strings, and the releases aren't in alphabetical order.

**Comment by tresf** [comment]
> And actually the releases are just the opposite, the patch versions are more recent.

Correct.

> This could cause errors in upgrade methods in DataFile.cpp.

Yes, it could and should be fixed.  We really shouldn't ever release patch versions to the public, but instead use minor versions.

> Also, between patch versions, it compares the strings, and the releases aren't in alphabetical order.

Yeah, the old patches in [`DataFile.h`](https://github.com/LMMS/lmms/blob/master/include/DataFile.h#L117:L122) just so happened to be written in a way where this wasn't a problem.

To do this proper, we should check to see if the a.patch and b.patch are both valid numbers and then use number comparison, falling back to string when they can't be compared as numbers.

**Comment by jasp00** [comment]
Versions should be 1.x.y.z where z is the number of additional commits, i.e., grab the list element 1 instead of 2 in [`VersionInfo.cmake`](https://github.com/LMMS/lmms/blob/master/cmake/modules/VersionInfo.cmake#L19).

**Comment by tresf** [comment]
> grab the list element 1 instead of 2 in VersionInfo.cmake.

:+1:

**Comment by Lukas-W** [comment]
The "-patch" comment is a bit misleading. Those lines are intended for pre-release versions, see http://semver.org/#spec-item-9.  It ensures that for instance `x.y.z-alpha` < `x.y.z-beta` < `x.y.z-rc1` < `x.y.z`.

I'm not sure when and why we started to tag pre-release versions as `lastX.lastY.90`, but calling them `x.y.z-alpha` will work just fine and would be more expressive.

**Comment by tresf** [comment]
> I'm not sure when and why we started to tag pre-release versions as lastX.lastY.90, 

A throwback to the [days of `@tobydox`](https://sourceforge.net/p/lmms/mailman/message/31942536/).

We certainly can use `1.2.0-RC2` for the next release if it doesn't break anything.

**Comment by jasp00** [comment]
Could the Debian convention be used? `~` means earlier, `-` means later. So, `1.2.0~rc2` < `1.2.0` < `1.2.0-rev1`; `-revN` could be used for security updates of bundled libraries, without changes in LMMS. Then the development versions would be `1.2.0~rc2.x`.

**Comment by Lukas-W** [comment]
> Could the Debian convention be used?

I'd rather not change it to a less-used convention. As you can see from [https://github.com/LMMS/lmms/blob/master/src/core/DataFile.cpp#L884,](DataFile.cpp) L884 and onwards, we already used the convention I described for marking pre-releases, so I suggest sticking to that. We can just mark patches as `1.2.1`, `1.2.2`, etc.

**Comment by Lukas-W** [comment]
Oops

**Comment by jasp00** [comment]
With `git describe --tags`, `-` means later. A different symbol should mean earlier. However, with current kernel versions `-` means earlier ([mainline: `4.8-rc3`](https://www.kernel.org/)). The unambiguous option and the easiest to parse is the dotted number. So, `1.1.91.x` or `1.2.0-rc2.x`?

**Comment by Lukas-W** [comment]
I vote for `1.2.0-rc2`. We've used it in the past, it's more descriptive, and we already have working code for it. No need to change something that isn't broken.

**Comment by tresf** [comment]
If RC, alpha, beta, else.

**Comment by jasp00** [comment]
Then the format would be `M.m.r-s.b` where:

* `M` is major; number.
* `m` is minor; number.
* `r` is release; number.
* `s` is stage; string; optional.
* `b` is build; number; optional. It is the number of commits. If bundled libraries need to be updated, a dummy commit is done.

**Comment by jasp00** [comment]
It looks like version should be `1.1.91.x`, because FILEVERSION in [lmms.rc.in](https://github.com/LMMS/lmms/blob/master/cmake/nsis/lmms.rc.in#L5) consists of four 16-bit integers ([documentation](https://msdn.microsoft.com/en-us/library/windows/desktop/aa381058%28v=vs.85%29.aspx)).

**Comment by Lukas-W** [comment]
Judging from the documentation you linked, we should probably use `FILEFLAGS VS_FF_PRERELEASE` to mark pre-releases on Windows instead. On a side note, I don't think that's even working right now:

![image](https://cloud.githubusercontent.com/assets/2879917/18099368/802b0f12-6ee6-11e6-8160-c63e9b8ab733.png)

**Comment by tresf** [comment]
@Lukas-W the resources are embedded into `lmms.exe`, I think you're looking at the installer.

**Comment by tresf** [comment]
To add the same version information to the installer, I believe we'll need to add support for it [into NSIS](http://nsis.sourceforge.net/Examples/VersionInfo.nsi).

**Comment by Lukas-W** [comment]
You're totally right. I was expecting `lmms.rc.in` to be used for the installer because it's located in the `nsis` directory. :wink:

**Comment by jasp00** [comment]
>we should probably use `FILEFLAGS VS_FF_PRERELEASE` to mark pre-releases on Windows instead.

This mark should be an enhancement for the future.

I have version `major.minor.release-stage.build` ready, `stage` being used for backwards compatibility. However, I suggest to use version `major.minor.build-stage.revision` [like Microsoft](https://msdn.microsoft.com/en-us/library/kstyaxxh%28v=vs.110%29.aspx). Release versions would be `1.2.0`, `1.2.0.1`, `1.2.0.2`... while development ones would be `1.2.1`, `1.2.2`, `1.2.388`, etc. This avoids two problems with current versioning:

* Release versions are limited to 90.
* After releasing `1.2.0`, development versions are `1.2.0.1`, `1.2.0.2`, etc, but stable revisions are greater (`1.2.1`).
