### ISSUE TITLE
Removing headers with name in effects plugins.

### ISSUE THREAD

**Issue by LocoMatt** [LMMS/lmms#2978]
Reffering to current redesign of effects plugins (#2831)
In my opinion names of effects should be removed from its own GUI. We still have name of plugin in window top bar. With this change we can save space without loosing anything. 
@RebeccaDeField  
![unknown](https://cloud.githubusercontent.com/assets/6965480/17781004/c77b34a0-656d-11e6-86d5-8a081c433881.png)

**Comment by RebeccaDeField** [comment]
I might be wrong, but I don't remember @budislav's design using additional titles below the title bars, so it might be a step in the right direction :)

**Comment by tresf** [comment]
mockup

![image](https://cloud.githubusercontent.com/assets/6345473/17789862/01da8152-6562-11e6-8b0e-ca8deca1cc92.png)

**Comment by Umcaruje** [comment]
:+1: I agree on this 100%

**Comment by BaraMGB** [comment]
Sounds good.

**Comment by RebeccaDeField** [comment]
Looks like all of the new plugins are being designed without the titles. @BaraMGB could you update the peak controller?

**Comment by BaraMGB** [comment]
Since we're removing the title step by step this issue can be closed. I guess we don't forget to remove the titles. ;)
