### ISSUE TITLE
Ubuntu 16.04: VST not working

### ISSUE THREAD

**Issue by ValorNaram** [LMMS/lmms#2987]
I have performed an upgrade to ubuntu 16.04 and now I'am unable to play vst's.
In Ubuntu 14.04 all worked great on the same vst's, I'm trying to play on ubuntu 16.04

I have `wine` installed and also `lmms-vst-full`

No error message, when I load vst's, but lmms goes grey

**Comment by liushuyu** [comment]
So which version of LMMS are you using?

**Comment by ValorNaram** [comment]
1,1,3

**Comment by liushuyu** [comment]
>1.1.3

Then, that is the problem.


LMMS 1.1.3 VST plugin only support up to Wine 1.7.55, which ships in Ubuntu 14.04. However, in Ubuntu 16.04 and more modernized Linux distribution like Arch Linux, Fedora, etc ships more recent Wine versions (Wine 1.8.x or even 1.9.x).

You can see your Wine version by typing
```bash
wine --version
```
in your terminal

The possible solutions could be:
- Download LMMS 1.1.90
- Compile LMMS from source (recommended, please refer to our wiki to see how to compile/build)

**Comment by ValorNaram** [comment]
then the repo isn't up to date.<br>
Have APT used to install lmms

**Comment by liushuyu** [comment]
>Thank you, i will try your steps

You are welcome. If you have further questions don't hesitate to contact us here.

**Comment by ValorNaram** [comment]
It works now, great!
Thank you so very much.
Nice GUI

Now closed
