### ISSUE TITLE
Just for opinion about sf2 player redesign.

### ISSUE THREAD

**Issue by qnebra** [LMMS/lmms#2990]
![sf2-screenshot](https://cloud.githubusercontent.com/assets/11295229/17836546/8e70abec-6796-11e6-9cc3-17a55d7e49bc.png)

What do you think about visuals and desing here? I haven't any idea for logo.

**Comment by Spekular** [comment]
What about some nice thinBOLD text for the logo? I'm not super happy with the fonts or kerning but I feel they're pretty ok.
![soundfonts](https://cloud.githubusercontent.com/assets/8918426/17836891/834e3aa2-67a2-11e6-937a-694996c3b317.png)

**Comment by SirBothersome** [comment]
I'll be honest, I kinda like that classic purple look to the sf2 player.

**Comment by tresf** [comment]
The edges of the font could be cleaned up:

![image](https://cloud.githubusercontent.com/assets/6345473/17855298/04761c1e-6846-11e6-8ca0-bde1b5c71f52.png)

Also, the white on green lacks contrast (folder icon)

![image](https://cloud.githubusercontent.com/assets/6345473/17855315/1e7d6f7c-6846-11e6-9df7-a106e8da9d9a.png)

> I kinda like that classic purple look to the sf2 player.

This raises a good point, redesign mockups should include a side-by-side with the original for comparison.

Last, @Umcaruje and @RebeccaDeField have been spearheading all redesign efforts, so coordination with them is a plus.  They can usually be found over on discord.  https://discordapp.com/channels/203559236729438208/203559236729438208

**Comment by Spekular** [comment]
Original:
![sf2 base](https://cloud.githubusercontent.com/assets/8918426/17856368/841bf3c6-687d-11e6-8bf1-49e9836d5caf.png)

While I prefer the flat/modern look we've got with the new effect plugins and Triple Oscillator, "classic purple" made me think of retrowave. I kinda like the neon text look but the actual UI is too tough so I threw something together:
![small header](https://cloud.githubusercontent.com/assets/8918426/17856570/767f88c6-687e-11e6-960e-ab2c79264858.png)

![mockup v3](https://cloud.githubusercontent.com/assets/8918426/17856521/4121b46a-687e-11e6-91a7-7ca1414cebfe.png)

**Comment by tresf** [comment]
Slightly related... @jasp00 since you seem well versed in copyright, are we legally allowed to use the branded word `soundfont` in our application?  Off topic, but I feel all instrument banks should be combined into a super-instrument which universally supports several banks (gig, sf2, patchbay) with one GUI if that helps the decision down the road.

**Comment by Spekular** [comment]
I vote the universal plugin be called "Banksy" ;P

**Comment by qnebra** [comment]
So, I don't make a merge request for that at this moment. Maybe folder icon will be completly white, and completly green when it's active.

**Comment by jasp00** [comment]
>are we legally allowed to use the branded word soundfont in our application?

I believe the uses in LMMS are [nominative](https://en.wikipedia.org/wiki/Nominative_use), they merely describe the product. The artwork says "soundfont player", that is a description; if you want to be safe, do not include "soundfont" in the artwork. The plug-in description "Player for SoundFont files" looks acceptable.

**Comment by RebeccaDeField** [comment]
@qnebra There is already some folder icons in the set we are using right now that are free to use if you want to. There is also a purple #32287e that is in the current palette that you could use. Feel free to download the source files for any buttons and backgrounds that you might want to use as well. :smile:

**Comment by vlad1777d** [comment]
I definitely like this design.
Maybe not to sf2 player, but I certainly would add this style to one of instruments.

**Comment by tresf** [comment]
There are some nice ideas here, however since the post is just a proposal, I feel we can close this out for a larger instrument redesign effort.  I'll let @RebeccaDeField decide. :)

**Comment by RebeccaDeField** [comment]
I agree with @tresf on this. We can reuse some ideas here if need be in a more standardized instrument redesign project.

**Comment by qnebra** [comment]
I can doing small help with redesign if this was be possible.

**Comment by RebeccaDeField** [comment]
@qnebra Sure, if you're still available when we start the instrument plugin design efforts you can help with as many of the designs as you want :)

**Comment by qnebra** [comment]
@RebeccaDeField Let's see what will be happen in future. Recent desings is something between anarchy and narcotic trip.

**Comment by vlad1777d** [comment]
That (first) design was great =)
It must be in some instrument )

**Comment by RebeccaDeField** [comment]
@vlad1777d I agree. I want to clarify that by closing this, I am not scraping any mockups, just prepping the issue tracker for a more organized effort that may incorporate any of these ideas where needed. :+1:
