### ISSUE TITLE
patman - noise on polyphony

### ISSUE THREAD

**Issue by zonkmachine** [LMMS/lmms#2991]
Tested on latest master with sounds from the `freepats` collection.
When playing more than one note at a time and `looped mode` is in position `off` it gets noisy like a buffer acting up.

**Comment by SirBothersome** [comment]
No such issue for me,  I could play eight notes simultaneously with no issues other than clipping. Looped mode off. What OS is this issue on? I'm using WIndows 10 64-bit, version 1511, with a dual core i3 that clocks ar 2.1 Ghz and 12 gigs of ram...

**Comment by tresf** [comment]
@SirBothersome are you on latest master branch?  The bug description is quite specific about that part.

**Comment by SirBothersome** [comment]
Ah, my bad, I thought the RC counted.

**Comment by zonkmachine** [comment]
It's good to know though that it's a newer bug. I haven't been able to look into older versions yet as I'm away for a couple of days. If someone feels the urge to practice `git bisect` this is a good practice candidate as it's easy to see if the bug is there or not. Just `sudo apt-get install freepats` , replicate the bug and then take it from there. Since patman wasn't touched recently it could be in hmm... SampleBuffer?

**Comment by musikBear** [comment]
Is *patman* used regular?
imo Patman is inferior to SF, and now comes giga.
I have made a *Patman* 7 day survey here:
http://lmms.io/forum/viewtopic.php?f=4&t=5567
Maby it could 'go' ?

**Comment by tresf** [comment]
@musikBear, please remove the poll.

**Comment by SirBothersome** [comment]
Before you give PatMan the axe, please consider this: 1) PatMan patches don't have the weird stereo or volume issues some SoundFonts have, 2) You can customize envelopes in PatMan (which you can't do with SoundFont) and 3) PatMan patches don't sound half bad.. It's not as if the thing is useless...

**Comment by tresf** [comment]
> Before you give PatMan the axe

We aren't.
