### ISSUE TITLE
[Wishlist] Add a native Multiband Compressor with GUI

### ISSUE THREAD

**Issue by SirBothersome** [LMMS/lmms#2993]
One of the most valuable tools in the mastering process of a song is a multiband compressor. I won't go into the semantics, but I've noticed that the RC has a few new native plug-ins that aren't CALF or LADSPA. Could we add a multiband compressor as well? Our current MBC has a spartan GUI, which makes it rather difficult to use. Pictured below
![lmms multiband](https://cloud.githubusercontent.com/assets/20342439/17856151/0d1af782-684a-11e6-9897-4203641bd45a.PNG)
It's not useless, but pictured below is Maximus, a very expensive, and apparently, an  industry-standard MBC
![maximus](https://cloud.githubusercontent.com/assets/20342439/17856202/50eb3512-684a-11e6-932b-cd23f8af31ec.PNG)
What makes Maximus more useful in practice than the LADSPA MBC is that you can physically see what the various compressors are doing to the waveform, and there are moldable dynamics processors rather than just a bunch of knobs. Is this a possibility in the foreseeable future? I think it would be a great boon to LMMS users

**Comment by tresf** [comment]
> Is this a possibility in the foreseeable future?

If we have someone as motivated as this guy, https://github.com/LMMS/lmms/pull/1443, https://github.com/LMMS/lmms/issues/1376, yes.  Note, this was a good month of development and the author is no longer active on the dev team.

**Comment by PhysSong** [comment]
Consolidated into #3817.
