### ISSUE TITLE
Setting instrument name doesn't update the instrument window title

### ISSUE THREAD

**Issue by zonkmachine** [LMMS/lmms#3009]
![renamebug](https://cloud.githubusercontent.com/assets/6368949/18073566/636b32f0-6e67-11e6-9bdc-ed9f51533377.png)

Since #2516 (@BaraMGB @Umcaruje) when you rename an instrument track the window title isn't updated properly.

In the picture I have renamed and then cloned an instrument two times. The window shows the name of the previous instrument on cloning but not the actual name.
Saving and reloading updates the window.

_Edit: Spelling..._

**Comment by BaraMGB** [comment]
Same on controller windows. I look into it.
![controllerrenamed](https://cloud.githubusercontent.com/assets/6502580/18108594/3a299d68-6f0d-11e6-9dff-6c05b9f52a0d.png)

**Comment by zonkmachine** [comment]
> #2869 could be related.

#2869 predates this one. I don't know how much earlier it is though, I just checked one commit earlier than this one.

**Comment by zonkmachine** [comment]
The main difference, as I see it, with the Controller Window Title behaviour is that it's present already in the 1.1.3 stable version.

**Comment by kamnxt** [comment]
Probably the same bug, but I found some more weird behavior.

1. Open LMMS
2. Rename the default TripleOsc to anything else
3. Open the TripleOsc piano roll. The title should be correct.
4. Rename the TripleOsc again, to anything else
5. The piano roll's title doesn't change
4. Create a new project, discarding the old one
5. Open the piano roll. The title is still the same as it was before resetting!

**Comment by zonkmachine** [comment]
Cool! I didn't notice the "extra stunt" that the Piano Roll window were doing but it's also fixed in #3012

**Comment by Umcaruje** [comment]
I can't see that the bug @kamnxt mentioned is fixed by @BaraMGB's PR. Here's a gif: 
![gifrecord_2016-09-12_223603](https://cloud.githubusercontent.com/assets/6282045/18451983/83c404fa-7939-11e6-8282-c6695a28792e.gif)
The piano roll title only updates when you close and reopen the window.

**Comment by BaraMGB** [comment]
I look into it.
