### ISSUE TITLE
Piano Roll Black Keys Contrast

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms#3018]
It is too hard to tell when a black key is being pressed or not in the piano roll.

Although this may seem minor when clicking with the mouse, this is much more severe when using the typing keyboard as the notes being played are much less obvious from a UI perspective.

![untitled](https://cloud.githubusercontent.com/assets/6345473/18233576/2416f7a0-72b9-11e6-98b2-3c74fe7a1da7.gif)

**Comment by vlad1777d** [comment]
Maybe to make something like in Linux Sampler's Fantasia GUI ?
![xkdwz_3-rke](https://cloud.githubusercontent.com/assets/12682937/18387761/2f2fa726-76a7-11e6-9cbf-6ba29ff0f12d.jpg)
I mean to highlight it with color, which fits LMMS theme.

**Comment by musikBear** [comment]
> It is too hard to tell when a black key is being pressed or not in the piano roll.

@tresf , thats in the new Rebecka theme, right?
Because in .90 it looks different
![keypressed](https://cloud.githubusercontent.com/assets/6662066/18410269/7689a9e4-775d-11e6-8282-d8bcf6821500.PNG)
G & G# pressed

**Comment by Umcaruje** [comment]
Agreed. The pressed black keys need more contrast.

**Comment by RebeccaDeField** [comment]
Thank you for pointing this out @tresf. I'm on it :)

**Comment by RebeccaDeField** [comment]
@tresf @Umcaruje @musikBear 

![pianoroll](https://cloud.githubusercontent.com/assets/7960169/19011076/f1dc5c48-8740-11e6-9f76-8d5c3186928e.gif)

**Comment by Spekular** [comment]
Its visible now, but the contrast is still somewhat low. If you want to avoid making the rest of the notes lighter, perhaps there could be a highlight on the played note similar to this?
![_20161001_085747](https://cloud.githubusercontent.com/assets/8918426/19012410/846ca90e-87b5-11e6-8c11-9c70acb377e5.JPG)

**Comment by musikBear** [comment]
@RebeccaDeField Yes it is clearER, but from a semi 'bat' pow i have to agree *partly* with @Spekular, it is not enough difference. However the highlight idea, i do not like, that is too much, imo.

Perhaps a rethinking of what 'white keys' and 'black-keys' actually *mean*, is all that is needed, because imo it only means **difference**. So the keyboard could have 'black' keys that unpressed was only ~50 rgb different from 'white', and then be black when pressed. That would give clean difference, both in idle, and press event

So mocked up without shading
![pianorollcontrast](https://cloud.githubusercontent.com/assets/6662066/19014299/fe5ce114-87e9-11e6-9b03-ab889ff55ffd.PNG)

What does all you other think?

**Comment by vlad1777d** [comment]
@musikBear , I better like idea with color highlighting.

@Spekular , I had such, it's Casio LK-215 ?)

**Comment by Spekular** [comment]
@vlad1777d Casio LK-230

**Comment by Umcaruje** [comment]
I personally dislike the colored piano idea, as I think it wouldn't really fit with the current theme.

@RebeccaDeField I think it should be the other way around, that pressed keys are lighter. Also, as a lover of all things flat, a flat piano like in musikbear's mockup would be fine by me :+1:

**Comment by RebeccaDeField** [comment]
I will mockup both a lighter piano as is and a colored piano, a simpler piano with black keys darker by default and one with even lighter keys by default. It really won't be that hard for me to play around with and in my experience sometimes the ideas you don't think will work turn out the best and vice versa so I like to give all the ideas a chance :)

**Comment by RebeccaDeField** [comment]
@vlad1777d's colored pressed key idea:
![piano1](https://cloud.githubusercontent.com/assets/7960169/19018114/6d7c1f36-880a-11e6-93dd-4b64f5a1c8ff.png)

@Spekular's LED light up pressed key idea:
![piano2](https://cloud.githubusercontent.com/assets/7960169/19018119/82ece3fa-880a-11e6-9be7-08c7c54da4a9.png)

@musikBear's lighter unpressed keys idea:
![piano3](https://cloud.githubusercontent.com/assets/7960169/19018121/9a6dfa50-880a-11e6-8cfc-c4515cdbedc8.png)

@Umcaruje's light pressed and dark unpressed flat design piano idea:
![piano4](https://cloud.githubusercontent.com/assets/7960169/19018125/b3cb1e2e-880a-11e6-960d-a9132941f0bc.png)

Thoughts? Opinions?

**Comment by mikobuntu** [comment]
I prefer the coloured pressed key idea.

**Comment by Spekular** [comment]
I was actually thinking more along the lines of the first mockup than the second. I figured a green or blue would fit well, so I like it!

**Comment by eagles051387** [comment]
I like the first mockup for this :)

**Comment by musikBear** [comment]
@vlad1777d suggestion is an essence the same as Umcaruje's, it just a different color, but i fear that the flickering colors would be more annoying, if the changes are from black to green or white to green :)
@RebeccaDeField The subtle way you made @Spekular suggestion looks **lovely**, but i always think about CPU-usage, and having these lights on all keys, simply must use cpu (one object for each and the logic to go with it) For the sake of keeping the cpu-usage in UI as low as possible, i will still prefer @Umcaruje or my own, because that can be implemented as a simple boolean control; Only two sprite-states, each with its own sub-sprite.

**Comment by BaraMGB** [comment]
> but i always think about CPU-usage, and having these lights on all keys, simply must use cpu (one object for each and the logic to go with it) For the sake of keeping the cpu-usage in UI as low as possible

> because that can be implemented as a simple boolean control; Only two sprite-states, each with its own sub-sprite.

such guesses are not helpful.

**Comment by vlad1777d** [comment]
@RebeccaDeField , you're wrong, my idea was the same, as @Spekular 's idea =)
(on that image, that I posted here: https://github.com/LMMS/lmms/issues/3018#issuecomment-245907018 , black key had led-like light.
I had Casio LK-215 keyboard, so I prefer led-like light on keys.

I vote for second.

But in second variant led is too close to the edge of key. I think, that it would be better to move it a little more to the center.
If you'll give me source of image, than I could try different variants too.
Thank you.

**Comment by RebeccaDeField** [comment]
@vlad1777d I will edit my comment so we don't have any confusion over who's idea was whos ;)

@misikbear In the LED idea with the more subtle green, I was imagining that exported pressed keys would be exported with the glow in one .png which would not increase CPU usage.

On phone right now, will send sources later.

**Comment by Umcaruje** [comment]
@BaraMGB 
>@musikBear

>>but i always think about CPU-usage, and having these lights on all keys, simply must use cpu (one object for each and the logic to go with it) For the sake of keeping the cpu-usage in UI as low as possible

>>because that can be implemented as a simple boolean control; Only two sprite-states, each with its own sub-sprite.

>such guesses are not helpful.

Not to mention that its completely wrong. We draw pixmaps, it doesn't matter if the pixmap has 1 color or 16 million, the CPU usage is the same, or the difference is so insignificant that we don't need to talk about it, nor it should affect design decisions.

**Comment by RebeccaDeField** [comment]
> Not to mention that its completely wrong.

I still really appreciate @musikBear always being concious about CPU usage as that is very important, it's just not a problem in this case :+1:

**Comment by Umcaruje** [comment]
Yeah, my comment might have gotten out a bit too harsh. Sorry about that
@musikBear

**Comment by RebeccaDeField** [comment]
@tresf's Would love to hear your input on this as well as you opened the issue. Would any of the options above solve difficulties you brought up here?

@BaraMGB Feel free to chime in as well. You usually have opinions about the theme orientated decisions.

**Comment by musikBear** [comment]
Il not comment on anything but the fact that i did not realise that the diode-solution ALSO could be implemented with a dual-sprite, so there is no difference at all from Umraruje, Vlads Speculars or mine, they are in respect to cpu and implementation identical.
I may regret this, but i do think @Spekular kb-lights as **subtle** diode looks just sexy, the way @RebeccaDeField has made it. I like that :)

**Comment by Umcaruje** [comment]
I'm leaning towards option 3. as well, but if we keep it this subtle. I still think the unpressed keys should be a bit darker though.

>@Umcaruje do you prefer option number 4?

After looking at I don't believe it looks natural, so no. I thought it would look better but it doesn't.

**Comment by Spekular** [comment]
@Umcaruje just to double check, you mean that the unpressed keys should be darker and the pressed stays the same?

That would move us back towards where we started, with very low contrast.

**Comment by Umcaruje** [comment]
![image](https://cloud.githubusercontent.com/assets/6282045/19041888/3742adf0-898a-11e6-99a3-7a9f2f89afe2.png)

**Comment by vlad1777d** [comment]
@RebeccaDeField , I thought about something with little more volume:
![pianoroll_2](https://cloud.githubusercontent.com/assets/12682937/19042590/47a45ac6-8995-11e6-9d1a-97ca3a3faec4.png)
[PianoRoll_2.svg.zip](https://github.com/LMMS/lmms/files/506556/PianoRoll_2.svg.zip)

**Comment by grejppi** [comment]
How it's done in the single window concept looks very nice to me:

![](https://cdn.discordapp.com/attachments/207159523616489473/232516441130139648/Kuvakaappaus_2016-10-03_17-55-43.png)

The double borders are also consistent with how TCOs look

**Comment by BaraMGB** [comment]
I'm with @grejppi here.

**Comment by Spekular** [comment]
mikobunto, eagles051387, and myself all liked rebecca's colored note idea. Grejppi's suggestion looks fairly similar and is backed by BaraMGB.

It seems to me that this idea has the most support, although I may be a bit biased since I really like it ;)

**Comment by vlad1777d** [comment]
Maybe let's search a little more. 
Yes, colored idea is good, @grejppi 's suggestion looks like finished, previous colored keys idea not looks like so.

**Comment by Umcaruje** [comment]
I like the mockup @grejppi posted too (this is from budislav's theme), as the color is not as bright as the one in @RebeccaDeField's mockup. Something like this could work.

**Comment by vlad1777d** [comment]
Maybe something like this?
![pianoroll_5](https://cloud.githubusercontent.com/assets/12682937/19048091/84a49c48-89ad-11e6-95b2-77f1e6e94e6e.png)
[PianoRoll_5.svg.zip](https://github.com/LMMS/lmms/files/506856/PianoRoll_5.svg.zip)

**Comment by RebeccaDeField** [comment]
I can see that things are leaning more in the direction of a colored key, and I'm seeing a lot of great ideas here. I will mock some new options up based on the conversation. I would like to ask @Budislav's permission before basing my design off of your work with the piano roll as people have requested.

>  @grejppi 's suggestion looks like finished, previous colored keys idea not looks like so.
You are correct. @grejppi suggested a finished design whereas my quick mockups for the keys still needed some finesse.

> P.S. I would like Budislav's interface to be implemented with current in parallel.
I created what would more technically be called a re-skin. The layout is the same, but look is different. Budislav created a complete redesign. He rearranged the program to be clearer while also introducing a wonderful new look. Basically, I am working within the box of what we already have in place and can implement fairly quickly and he was working outside of the box, giving a great design for what we want to move towards to make the layout _and_ look better. Implementing these themes is a very different process. My hope is that my theme can bridge the gap in LMMS between where we are now and where we want to be in the future. I hope that this theme will give what we already have in place a refresh so that we can have more time to put some focus into improving the stability and code side of things. I also hope that many of the things we are doing for this theme helps to being us towards the Single Window theme when we are ready to get there.

**Comment by tresf** [comment]
> @tresf's Would love to hear your input on this as well as you opened the issue. Would any of the options above solve difficulties you brought up here?

A picture's worth 1,000 words... Here's a zoom-out of the mockups.  There's only one that's suitable IMO, which is conveniently in alignment with consensus. 👍 

![screen shot 2016-10-03 at 10 03 08 pm](https://cloud.githubusercontent.com/assets/6345473/19060329/3932e1a4-89b5-11e6-87d5-e0ad806d8f10.png)

**Comment by RebeccaDeField** [comment]
@tresf As always, thank you for the invaluable feedback. I will test the next mockup from this perspective before posting.

**Comment by budislav** [comment]
@RebeccaDeField sure, go ahead :)

**Comment by RebeccaDeField** [comment]
Idea based on all of the feedback posted here:
![piano5](https://cloud.githubusercontent.com/assets/7960169/19134117/ea022a42-8b10-11e6-81ef-98cdea7ef27f.png)

@tresf @musikBear @vlad1777d @Spekular 
@Umcaruje (Happy birthday)

**Comment by BaraMGB** [comment]
Looks great!

**Comment by vlad1777d** [comment]
@RebeccaDeField , not bad, I like it. Green colors from theme, grey colors from it too.

Maybe to add a little of volume to  black unpressed keys?
(I mean a light gradient at the end of key. You have such, but they are only lines.)
Because it looks like a little flat without them. But this is not principal (not necessarily).

**Comment by Spekular** [comment]
Looks good to me!

**Comment by BaraMGB** [comment]
@vlad1777d I guess this is a mokeup. The distances will be made in code.

**Comment by RebeccaDeField** [comment]
@vlad1777d  ^^^

**Comment by vlad1777d** [comment]
@RebeccaDeField , I thought that it's your style.
It's cutting eyes to perfectionist in me =)

@BaraMGB , yeah, right.

**Comment by RebeccaDeField** [comment]
@vlad1777d Yeah, I'm a bit of a perfectionist too, but I am also very busy so I have little time to spare. I have to make compromises when I comes to things like quick and rough mockups (especially when I'm mocking up 4+ ideas at once). I spent my time on the pixel-perfect key design, the arrangement will be perfect when it's in the program as well :)

**Comment by vlad1777d** [comment]
@RebeccaDeField , well, I'll not carp then )

**Comment by mikobuntu** [comment]
![zyn-fusion-keys](https://cloud.githubusercontent.com/assets/335217/19169096/cc803838-8c0a-11e6-8d3a-84aa1b4fd83e.png)

Here's how ZynAddSubFX-3 (beta/demo) is using colour for their key press. Seems we are not the only ones opting for the green hue :)

**Comment by vlad1777d** [comment]
@mikobuntu , yes, and Linux Sampler's Fantasia GUI use green color: https://github.com/LMMS/lmms/issues/3018#issuecomment-245907018 =)

**Comment by musikBear** [comment]
@mikobuntu Oooo that is a 'shade' of green, isent it.. ?
I believe its about the same 'shade' that normally kills jedies or whamms spacecraft out of the stir :D. 
a bit over-greened for my taste.. Though, Could be an *environment-friendly* release.. "zasfx now GREEN" :rabbit: 

No jokes aside, i really cant understand why they don use the *same* green they have in most of the design? *That* would look smashing, even stylish. Neongreen looks ..neongreen *always*, and that is not necessary a good thing, unless the purpose is to mark an accident site

**Comment by vlad1777d** [comment]
I only now thought, how it's great that my favorite program was based on my feedback.
You, bourgeois, possibly dislike communism, but free software world is very similar to it =)
Thanks.

**Comment by simonvanderveldt** [comment]
Will this just need pixmap changes or code changes as well?

**Comment by RebeccaDeField** [comment]
@simonvanderveldt Just pixmap changes, which is something that I am currently working on. If all goes well with my most recent tweaks for alignment, you should be seeing a pull request for this soon. :+1:

**Comment by simonvanderveldt** [comment]
@RebeccaDeField Awesome!
Just checking if you'd need some help with the code, but even better when the changes are limited to the pixmaps, makes it easier :)

**Comment by RebeccaDeField** [comment]
@simonvanderveldt Thank you. I really appreciate you checking in and I will be sure to reach out to you if I have any coding requests that are beyond my abilities. :)
