### ISSUE TITLE
Piano Roll Grid Contrast

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms#3019]
I'm trying to adjust to the new theme and find it particularly hard to locate quarter notes.  This may be a matter of an old dog trying to learn a new trick, but I continuously find myself misjudging where to place notes.

At a glance, the major difference seems to be the grid contrast on the background.  Is anyone else experiencing this same problem?  If this is an overwhelming "no", we can close this out as invalid.

| Old | New |
| --- | --- |
| ![screen shot 2016-09-04 at 4 34 07 pm](https://cloud.githubusercontent.com/assets/6345473/18233768/bbc5fc3c-72bd-11e6-8997-8533f60d4e60.png) | ![screen shot 2016-09-04 at 4 36 10 pm](https://cloud.githubusercontent.com/assets/6345473/18233769/bca6917a-72bd-11e6-898c-12b502137689.png) |

**Comment by zonkmachine** [comment]
Yes. I have to lean forward a bit to see what's going on.

**Comment by vlad1777d** [comment]
Yes, I had such problem, I needed to count squares.
The new one (with low contrast) is better because when I looked at the old one much time, than contrast squares stayed in my eyes near 20-30 seconds from when I stopped looking on it.

I think that for readability (you made right, decreasing contrast) we need to decrease the contrast, but such dark (black) background and such pale lines may make grid illegible.

I think that the background must be more light, lines, could be lighter or darker than background depending on the situation.

**Comment by musikBear** [comment]
> Please tell what so you think about this.

A clearer visual difference in the grid, look to me as a great idea

**Comment by Umcaruje** [comment]
![screenshot from 2016-09-10 16 09 44](https://cloud.githubusercontent.com/assets/6282045/18411106/2aa5d12e-7771-11e6-8298-58010c3f54a6.png)
 
@tresf does this look better?

**Comment by tresf** [comment]
Yes, better, but I should try it out interactively for a while.  It's really the 1/4 note lines that were hard to see and https://github.com/LMMS/lmms/issues/3019#issuecomment-245580836 albeit a bit extreme, highlights the problem very well.

**Comment by Umcaruje** [comment]
I'll look into the code to change the transparency of the lines. I think @vlad1777d's idea of having a different color for a starting line is a bit of an overkill in my opinion. the alternating background color is already an enhancement (#2308) and should be handled seperately.

**Comment by musikBear** [comment]
@Umcaruje The picture is a jpg, so its not the best Quality, but i was wondering how it would look with bar-dividers made a 3 vertical lines : 
The center exactly ON the divider, but then 'flanked' by two new lines.
Then the bar-dividers on your picture could be used as beat-dividers, and the tick-dividers could be preserved as they are on your picture. There would then be 3 really clear differentiable dividers.

**Comment by Umcaruje** [comment]
@musikBear the picture is actually a png, though github probably scaled it, so you should click on it so it appears in its natural size. I don't quite understand your request, could you please draw a mockup?

**Comment by musikBear** [comment]
@Umcaruje I made it for the first bar, so you can see the difference. I think it is clearer
![bettercontrast](https://cloud.githubusercontent.com/assets/6662066/18416948/62e046e8-7823-11e6-94df-6aee8193b87a.png)

**Comment by RebeccaDeField** [comment]
I think we could get away with lightening the entire grid that @Umcaruje [proposed here](https://github.com/LMMS/lmms/issues/3019#issuecomment-246114300) so long as we can strike a balance between easy to distinguish and minimal eye strain.

**Comment by tresf** [comment]
How the competition does it, for comparison purposes only:

![image](https://cloud.githubusercontent.com/assets/6345473/18424191/1e52c426-787b-11e6-9be9-4209282c39d5.png)

![image](https://cloud.githubusercontent.com/assets/6345473/18424196/36b46efc-787b-11e6-9458-0a5908afbdb0.png)

![image](https://cloud.githubusercontent.com/assets/6345473/18424232/8fce3914-787b-11e6-9a16-d8d4ba1548eb.png)

**Comment by RebeccaDeField** [comment]
A bit of analysis...

![8fce3914-787b-11e6-9a16-d8d4ba1548eb](https://cloud.githubusercontent.com/assets/7960169/18424688/e39afcd6-7866-11e6-8258-fcf703d7d0e2.png)
In this case the actual background different shades and keeping the grid pretty transparent, which does seem give the eyes some rest.

![36b46efc-787b-11e6-9458-0a5908afbdb0](https://cloud.githubusercontent.com/assets/7960169/18424722/13a7c10c-7867-11e6-808e-3a6a3e93eb13.png)
This grid is a bit different as the background is lighter and the grid is darker than the background. This could also be a good one for lower eye stress.

![1e52c426-787b-11e6-9be9-4209282c39d5](https://cloud.githubusercontent.com/assets/7960169/18424742/487c9402-7867-11e6-9876-2b172f72b4b2.png)
This is actually a combination of the two above with a much lighter bg and darker grid and the background using different shades to differentiate. I would assume that this one might be more prone to eye strain after long periods of time.

It seems that piano roll using grids with lighter and darker lines as seen in the idea I mentioned is pretty common, so I think we should definitely do that. Can we also try using different shades of blocks in the bg? I think that would aid in identifying where you want to place your note much quicker.

**Comment by RebeccaDeField** [comment]
Just wanted to leave one last idea here that I found on an older theme thread.

![1c4bd96e-50af-11e5-9fc3-c9e2423bfaf8](https://cloud.githubusercontent.com/assets/7960169/18446312/ab15c88a-78d6-11e6-89bc-e07d1b4a7ff4.png)
Just another way we could shade the background.

**Comment by musikBear** [comment]
Have to ask
This image https://github.com/LMMS/lmms/issues/3019#issuecomment-246175403
surely **first bar** has a more distinguishing grid, than this:
https://github.com/LMMS/lmms/issues/3019#issuecomment-246113815

Im sorry i push on here, but i very often have to lean forward, so this issue is quite important to me (lousy eyes and all that)

> Just wanted to leave one last idea here that I found on an older theme thread.

Ya, #2308 that was mine, so i like it :p

**Comment by vlad1777d** [comment]
I came here to write about different background colors for Piano Roll.
I think that there is no need making new color each bar, because if grid is enough readable, everybody can see new bar as it is. But I often want to know: is now a new couplet (verse) or the old one.

So I think that new color must be every 4 bar because:
-it will match with the background color of Music editor;
-it's easy to understand where is current couplet, where is a new couplet (verse) 
(where is a new bar you can see perfectly see and without background highlighting, so I think that this "feature" with different background we must to use for another important goal).

**Comment by vlad1777d** [comment]
@tresf , about images that you posted:

-second is normal;

-first is normal - it's not contrast and not readable. It will be hard to notice the quarters and bars.
-third is just like the first one. Not contrast and readable. There is no need to change current color scheme to first or third one because we will receive no benefits. All will stay as it was earlier.

**Comment by musikBear** [comment]
![competits](https://cloud.githubusercontent.com/assets/6662066/18509764/a0179152-7a7a-11e6-9303-5f464f9d651c.PNG)

'1' is interesting. Here they option for high magnification in order to get a distinct piano-roll-view. The actual dividing vertical lines are not that clear, *however* **because** they have this large magnification, there are room for a real *legend* in the top of piano-roll. We can readout **1,2** Eg 1. beat 2. tick -etc. That can be helpful, but the downside is that it would be hard getting a overview of a whole melody. (They have a zoom for that, though)

'2' is fls..
fls has one of the most confusing features in piano-roll, and this picture here is a magnificent example
I ask you: Can you count ticks?
No, because fls has a 'floating-magnification' feature, that allows adjacent ticks to merge :/ ?!
So inside *one* beat, there is **two** ticks **drawed**
I positively **hate** that idea, and cant understand what it is good for
The vertical grid is however almost distinctly in apearence. I can clearly see the lines for bars and  beats, but the tick-lines are next to invisible. imo.. :see_no_evil:



'3' is imo without any visual difference between vertical dividing lines, and is extremely eye straining, if i try to analyse a piece of the score. That is a fault, LMMS should not recreate.

**Comment by vlad1777d** [comment]
@musikBear no, maybe that was an error in translation.  
The music consists of notes, which are grouped (if I translated it to English right) in bars (in Russian "bar" - "такт": http://www.kidly.ru/images/Untitled1-5.jpg)

And a text is grouped to quatrains. And one line of text usually matches 4 bars of music ("такт") (as you can see from picture: http://www.kidly.ru/images/Untitled1-5.jpg).
And, depending on speed of music, one line of text can also match 2 bars of music (this also happens very often).
Other variants are very rare.

So I suggested to divide each 4 bars in Piano roll by color (them to match or 1 line of text, or 2 lines).
Also such dividing will math with Song editor's dividing by color:
https://cloud.githubusercontent.com/assets/12682937/18511453/67e33e32-7a8c-11e6-8f37-ae52e2469163.png
![2016-09-14 15-27-25](https://cloud.githubusercontent.com/assets/12682937/18512083/089633f4-7a90-11e6-90c4-24a5dbf7eafd.png)
Here and in Piano roll and in Song editor first 4 bars are darker, second - lighter.

Such backgrounds are also good: https://github.com/LMMS/lmms/issues/3019#issuecomment-246432099 , but they are useless if grid is readable without them.

**Comment by RebeccaDeField** [comment]
> Such backgrounds are also good: #3019 (comment) , but they are useless if grid is readable without them.

I agree that the grid should be more lighter than it currently is and more readable. This is just a personal opinion, but I think shading the bg in addition could help to make it more readable without making the contrast too high.

Many lists also use this technique so that your eyes have an easier time counting and finding what you're looking for.
![shaded](https://cloud.githubusercontent.com/assets/7960169/18524502/7bda9350-7a6d-11e6-9200-64fd4b73dee6.jpg)

**Comment by Spekular** [comment]
That image looks a bit like dummy data considering the name "XYZ Corp", but just in case it's sensitive/private stuff you should know that it's all still readable.

**Comment by RebeccaDeField** [comment]
@Spekular It's probably dummy data, but I found the image on Google and I like to make a habit of blurring info and faces that I find from google. I really appreciate the heads up though. Updated to be "blurrier" ;)

**Comment by Spekular** [comment]
:+1: good habit imo.

The two companies I checked gave results on google. Then again there's only so many three letter combinations so it might as well be a coincidence.

**Comment by RebeccaDeField** [comment]
@Spekular Thanks, I'm a bit overly conscience about the legal side of things. Too many designers don't understand plagiarism, licencing, copyright, etc. I will not be another one  ;)

**Comment by simonvanderveldt** [comment]
Is there an easy way to try proposed changes locally, like changing an RGB value in a `.css` file somewhere in a `~/.config/lmms/` directory or something?

I think actually seeing the change in a full LMMS session and using it makes judging it a lot easier than looking at small parts of the application placed outside of it's context.

**Comment by grejppi** [comment]
@simonvanderveldt there's no way to override a theme, so you might want to make a copy of the theme and edit that.

**Comment by simonvanderveldt** [comment]
What do all of you think of using a slighter lighter background with a darker grid? To me it seems  to be a bit calmer to my eyes.

For example mimicking FL (view at 100%):
![image](https://cloud.githubusercontent.com/assets/204286/19282342/47f82052-8fee-11e6-9315-de9e7709aa6d.png)

Note that the above image contains more changes, the 3 different vertical grid lines have their own colors, from bar/darkest, beat/middle, tick/quantisation/lightest. Also the bars have a slight accent color around them (only 40% visible).

**Comment by vlad1777d** [comment]
@simonvanderveldt , hm, not bad.

**Comment by Spekular** [comment]
Personally I think it looks out of place with the rest of the theme.

**Comment by simonvanderveldt** [comment]
> Personally I think it looks out of place with the rest of the theme.

Do you mean the light background in general or these specific colors?

I'm asking because i pretty much used FL's colors, which aren't part of LMMS's color palette, so it makes sense it feels a bit out of place.

Just redid it with the darkest color used on the toolbar buttons as grid background color so it better matches with LMMS's colors.
![image](https://cloud.githubusercontent.com/assets/204286/19288067/9fbed9a0-9004-11e6-89f9-dd8591b901c7.png)

**Comment by BaraMGB** [comment]
That fits much more better in the theme. @RebeccaDeField what do you think?

**Comment by RebeccaDeField** [comment]
Thank you for taking the time to mock up your ideas and also code them up as well :) I agree with @BaraMGB that the second color scheme fits more with the theme. Here are a couple of my thoughts and ideas on it.

**1. It might have less contrast**
I scaled down a screenshot of the previous editor and your proposal. I feel that the overall contrast between the toolbar, buttons and piano roll is more distinguishable when the background is darker.
![9fbed9a0-9004-11e6-89f9-dd8591b901c7](https://cloud.githubusercontent.com/assets/7960169/19291913/14a6087a-8fcd-11e6-8356-54583f2d83c8.png)
![d1287a3e-89a9-11e6-821d-967acb2b9fc1](https://cloud.githubusercontent.com/assets/7960169/19291914/14a9d798-8fcd-11e6-9248-2034348c7f2b.png)

**2. We would want to insure consistency**
If we go ahead with this idea we might want to make other areas in the program match the look. As of now, the song editor has a darker bg and so does the automation editor, etc. We would just want to make sure that it doesn't look out of place.

I hope this is helpful and I am sure there are other solutions than the ones I come up with ^_^

**Comment by BaraMGB** [comment]
When the time line would be darker the contrast should be okay.

**Comment by simonvanderveldt** [comment]
@RebeccaDeField Thanks for the feedback. I think the main issue lies with the contrast between the time line and the toolbar right above it (with zoom, quantization, etc in it). They almost merge together which probably shouldn't be the case.

Possible solutions are to make the time line darker (or lighter? I doubt that would look good though) or do the same to the toolbars.
I noticed the topmost toolbar is darker than the other 2 as well, not sure if that's on purpose. But maybe that color can be reused for the time line.

100% agree on consistency, if a lighter background for the piano roll happens it should also apply to the other parts.

**Comment by vlad1777d** [comment]
@RebeccaDeField , **Darker** variant looks bad in comparison with that lighter one, it strains eyes much and is not so clear.

**Comment by RebeccaDeField** [comment]
@vlad1777d I'm actually not saying that the dark timeline is better, just pointing out some opportunities for improvment. 

@simonvandervelt I think that a combination of tweaking the toolbar and timeline color will wield the best results. For example, if you darken the timeline, lighten the toolbar and vice versa. Try taking a look at the same you based your idea off of and analyzing if their timeline is darker/lighter than the toolbars. 

The darker bar you are referring to is the title bar for the window and I think that picking your colors from other parts of the program like you said is a good idea :)

**Comment by RebeccaDeField** [comment]
Please ignore typos on my last comment using my phone rn and autocorrect messed up the words. Will fix once on my desktop (and delete this disclaimer ;) )

**Comment by musikBear** [comment]
Perhaps one more enhancement for easy viewing of the piano-roll?
Stroke the cursor position with a subtle shade of either the theme green (img) or the theme blue
![stroked cursor-pos](https://cloud.githubusercontent.com/assets/6662066/19485291/ff1f61fc-955a-11e6-9a47-5b7eda6bed39.png)

**Comment by simonvanderveldt** [comment]
@musikBear Actually at first I did't even notice there was highlighting going on for the note under the cursor. So imho that can definitely use some love.
I do think it's a different issue than the grid contrast, so probably deserves it's own issue.

**Comment by simonvanderveldt** [comment]
> I scaled down a screenshot of the previous editor and your proposal. I feel that the overall contrast between the toolbar, buttons and piano roll is more distinguishable when the background is darker.

@RebeccaDeField After some reflection I think the thing you're describing is actually a good thing. The contrast between the very dark background of the Piano Roll grid vs it's surroundings and the notes on it is pretty high, which is somewhat eyestraining (see also https://github.com/LMMS/lmms/issues/3019#issuecomment-253320314).
The lighter background reduces that, which makes the whole a bit easier on the eyes, whilst also increasing the grid contrast.

What's gotten worse by lightening the grid imho is how the whole LMMS window looks, the toolbars don't "frame" the grid as nicely as they did with the dark background.
I've been trying all kinds of dark combinations of the toolbars, timeline and grid, but haven't found anything that looked better and gave a better feeling of contrast.
It seems others have solved this by having the toolbars/rest of the application be a lighter color than the grid (see https://github.com/LMMS/lmms/issues/3019#issuecomment-246238246)).
(so not a light color perse, but a lighter color)

**Comment by tresf** [comment]
> lightening the grid [worsens] the whole LMMS window look

Yeah, because it breaks the theme.

My major concern (what inspired this bug report) with the current theme (in my opinion) is the difficulty in locating quarter notes and @vlad1777d's https://github.com/LMMS/lmms/issues/3019#issuecomment-245580836 seems to focus on that without sacrificing too much from the theme design.

**Comment by Umcaruje** [comment]
I'll see to implement @vlad1777d's full idea around these days.

**Comment by simonvanderveldt** [comment]
> and @vlad1777d's #3019 (comment) seems to focus on that without sacrificing too much from the theme design.

I never really understood his suggestion because they all look the same to me. But if it does work for others we're at least solving the problem for them :)

**Comment by Umcaruje** [comment]
![screenshot from 2016-11-10 22 36 52](https://cloud.githubusercontent.com/assets/6282045/20195284/309919b0-a796-11e6-8fad-11059481ca27.png)

So, I implemented @vlad1777d's idea, but there is a problem now in what order the lines are rendered. This kind of grid requires a very specific drawing order to look good: 

* 32nd lines should get drawn first
* 16th lines come next
* the non-acented horizontal lines get drawn
* the beat lines get drawn
* the accented horizontal lines get drawn (at every C note)
* finally, the bar lines get drawn.

Now the only way I see this is to use a seperate for loop for every line, like its done in the automation editor, but then we have a problem when rendering triplets.

Anyways, help would be appreciated on this, as my school started so I don't have as much free time as I had before :)

**Comment by zapashcanon** [comment]
@Umcaruje, sorry, not idea about the way to solve your problem, but anyway, I just wanted to say that it looks really better! :)

**Comment by musikBear** [comment]
@Umcaruje In AS there would be a *depth-value* for a graphic object so depth would be a way to control the order of graphic objects, but the concept of depth for graphic, does that exists in cpp? or 

But it does look better! :+1: 
Only thing i miss is the alternate shading, #2308 but if that is prosponed, then no big deal. Alternate shadings would in fact make all the fuzz about how to distinctively impress the bar-lines, completely obsolete. The bars would be immediately identifiable

**Comment by vlad1777d** [comment]
@Umcaruje , at first I drew 32-th lines, than vertical green (quarters), than vertical (bars) (more light green) and horizontal (octaves) (the same ones). That's all.

They have not opacity, so you can draw one above other. At first - grey, second - darker green, third - lighter green.

Please look here:
[lmms_piano_roll_grid_v3.xcf.zip](https://github.com/LMMS/lmms/files/586356/lmms_piano_roll_grid_v3.xcf.zip)
Here are two kinds of background (darker and lighter), two kinds of grey grid (darker for darker background, lighter for lighter). It's for @musikBear 's alternate shading idea.
I still think that it would be better to highlight each 4 bars by color: https://github.com/LMMS/lmms/issues/3019#issuecomment-246997997

**Comment by vlad1777d** [comment]
@simonvanderveldt , about your idea: https://github.com/LMMS/lmms/issues/3019#issuecomment-253041171
I like it. Maybe it lesser strains eye, than my one.
But I still think that dividing with colors is more efficient, than just by values of one color:
![lmms_piano_roll_two_octaves_grid_v1](https://cloud.githubusercontent.com/assets/12682937/20227155/c1203b54-a853-11e6-8d99-07b80846edf8.png)

Friends, what do you think about this?
I think, that then more decision was considered, than better result will be.

**Comment by Spekular** [comment]
@vlad1777d That looks pretty nice, though I think the color difference could be a bit subtler.

**Comment by vlad1777d** [comment]
@Spekular , agree, but I cannot change background with one click - I need to remake full image from this: 
[lmms_piano_roll_grid_v4-bar_without_margins.xcf.zip](https://github.com/LMMS/lmms/files/586623/lmms_piano_roll_grid_v4-bar_without_margins.xcf.zip) , I'll do this when I'll have time.

**Comment by Umcaruje** [comment]
Look, we can't have different colors across one line, it would complicate the code too much. The shading exists here but its too subtle, as I said its a WIP.

> does that exists in cpp? or

The lines get drawn in the order where the code appeares. that's pretty much it. But we render the horizontal lines first, then vertical ones, and horizontal line rendering is linked to the rendering of the piano keys. It all needs separation.

**Comment by tresf** [comment]
> Now the only way I see this is to use a seperate for loop for every line, like its done in the automation editor, but then we have a problem when rendering triplets.

I'd be interested to see the working code.  At a glance, moving the drawing of the [weak lines above the normal lines could fix this](https://github.com/LMMS/lmms/blob/master/src/gui/editors/PianoRoll.cpp#L2884:L2889).  I assume you've already tried that though.

**Comment by Umcaruje** [comment]
@tresf the problem is in the horizontal lines, not the vertical ones 
![screenshot from 2016-11-11 22 26 53](https://cloud.githubusercontent.com/assets/6282045/20230772/f610cfe0-a85d-11e6-8b3c-c3726eba05a0.png)

**Comment by tresf** [comment]
> @tresf the problem is in the horizontal lines, not the vertical ones 

Sorry, my advise was rubbish you beat me to it.  This logic is confusing though.  Where's the horizontal lines being drawn?  We just need to make that later in the monster 👹 paint event.

**Comment by Umcaruje** [comment]
@tresf when the white keys are being drawn, we also have the grid drawing in the same for loop. Now, here we need seperate for loops for everything, as you read we need the lines to intersect properly. So we need a loop for 16th, then normal horizontal lines, then beat lines, then accented horizontal lines and then bar lines at the end.

https://github.com/LMMS/lmms/blob/master/src/gui/editors/PianoRoll.cpp#L2692-L2704 is where the horizontal line rendering's at

**Comment by tresf** [comment]
If bright lines are to always to be drawn above darker lines, they shouldn't be in the same draw routine then.

Furthermore, the draw routines are misleading because efficiencies were made to reuse the key loop to also draw the horizontal grid and it makes the code extremely confusing to contribute to.

For example... the loop is improperly commented "draw all white keys".  This is entirely wrong as the black keys are draw inside the same loop as well as the horizontal lines.  Ideally, the section would be renamed "draw horizontal items" and each draw routine should be farmed off into a sub-function for clarity.

Anyway... the quick fix would be to write any bright lines lower in the code in a separate loop as you've identified.  Another alternative would be to draw a bunch of small line segments vertically that don't ever overlap the horizontal lines (would still need a similar "horizontal line position" type loop, so the CPU overhead would be about the same as a single additional loop).

Regardless, you're trying to fix a single bulb in a string of old used Christmas lights so you have to decide what's worth your time.

**Comment by tresf** [comment]
Another option is to use one loop to place the lines into a stack for calculation purposes and then use a separate loop to draw them onto the screen for display purposes.  The underlying problem is the code was written to efficiently utilize the horizontal key positions to do everything inside the grid.  This is great conceptually until we want layering and then this catch-22 happens.

**Comment by vlad1777d** [comment]
" are to always to be drawn above darker lines" - this would make impossible quick changing of colors (to search for better result, or to tweak the theme).

I think that better would to draw lines according to their appointment.

**Comment by tresf** [comment]
> this would make impossible quick changing of colors (to search for better result, or to tweak the theme).

Please do not take words out of context.  "Bright colors" chromatically is different than ["bright colors" functionally](https://github.com/LMMS/lmms/blob/master/src/gui/editors/PianoRoll.cpp#L2873).  I'm talking about the code reference, not anything specific to color.

**Comment by vlad1777d** [comment]
@tresf , ok, I didn't knew =)

**Comment by Umcaruje** [comment]
![gifrecord_2016-11-11_231024](https://cloud.githubusercontent.com/assets/6282045/20231711/1b13cbc0-a864-11e6-8186-dcc003ddab00.gif)

(the lines on notes are from GIF compression, not actually happening)

Some progress, snatched the loop from the automation editor so it renders lines based on quantization level. 

It gets crazy at 1/192 Q though: 
![screenshot from 2016-11-11 23 15 24](https://cloud.githubusercontent.com/assets/6282045/20231838/d8e5bff0-a864-11e6-8e3e-2f76216acf02.png)

**Comment by musikBear** [comment]
> (the lines on notes are from GIF compression, not actually happening)

LOL when i saw that i spontaneously went WOW! It looked sooo sexy :dancer: 
Love the shading! -And with *that* no bar-lines are needed at all! The difference in shade denotes bars. I just hope that shades are not an efficiency slap.
But it very difficult to see difference between beat and ticks-lines.
>It gets crazy at 1/192 Q though: 

I cant see any lines at all, but i also do not have a flatscreen, just a tube-monitor, on that there is nothing -neither horizontal or vertical at all.

**Comment by Umcaruje** [comment]
![gifrecord_2016-11-13_003707](https://cloud.githubusercontent.com/assets/6282045/20242730/8962969e-a939-11e6-8a55-85fa85794625.gif)


Some progress, vertical lines are all in seperate loops now, though the horizontal lines are giving me a very hard time as they are offsetted when put in a seperate loop...

**Comment by tresf** [comment]
@Umcaruje does resetting `key_line_y = keyAreaBottom() - 1;` before the loop fix it?
