### ISSUE TITLE
24-bit export

### ISSUE THREAD

**Issue by unfa** [LMMS/lmms#3021]
Sometimes 32 bit-export is an overkill, but I still needs more than 16 bits.

This could save a lot of diskspace, you know :)

**Comment by zonkmachine** [comment]
I had a quick look at this and the library we use to write sound files, [libsndfile](http://www.mega-nerd.com/libsndfile/#Features), has support for this so it should be a pretty easy fix.

**Comment by WinLin97** [comment]
Pretty easy? So... When will this be fixed?

**Comment by Umcaruje** [comment]
There's nobody currently working on this issue. We're short on devs. Do you
volunteer?

**Comment by michaelgregorius** [comment]
> Pretty easy? So... When will this be fixed?

Now. :) Implemented with pull request #3516.

**Comment by michaelgregorius** [comment]
The pull request now also adds some other improvements to the export dialog:
* Enable variable bit rate for Ogg exports.
* Only show relevant widgets depending on the selected export format.

See the comments in #3516 for more details and screenshots.

**Comment by WinLin97** [comment]
Great, big thanks Michael! :D
