### ISSUE TITLE
Issues with dropped force step.

### ISSUE THREAD

**Issue by zonkmachine** [LMMS/lmms#3024]
Since #3003 / 02eee8e7b6e0645b033d5e2add4281cdf7dc6547
@Lukas-W @jasp00 
1. Some floats now needs to be rounded off in presentation. Click and drag Vol/Pan knobs and see the floats in all their glory. Used to be rounded to one decimal precision.
2. The integers values that use float models?

![fishynumbers](https://cloud.githubusercontent.com/assets/6368949/18296370/766eb80c-74a9-11e6-95f7-56ff9e4cf959.png)

**Comment by jasp00** [comment]
In `AutomatableModel`, `m_hasStrictStepSize` should be dropped, and `m_step` should be used as a restriction from the model, i.e., set `m_step` to 0 in many float models. `m_step` is currently being used as a restriction from the view; this rounding to one decimal should be in the view.

**Comment by smithjessk** [comment]
Is this still an open + untackled issue? I would be happy to try to solve it.

**Comment by BaraMGB** [comment]
A better solution would be to add a new function to Knobs and fader which gives the value truncated. Intern the model uses the untruncated value for sample exact calculations.
