### ISSUE TITLE
Piano roll: highlighting note lines with color

### ISSUE THREAD

**Issue by vlad1777d** [LMMS/lmms#3027]
Hello dear friends.

My request is to **add possibility** for user **to choose different colors for separate notes** to give him ability visually separate notes/melody lines, etc.

![melody_color_notes](https://cloud.githubusercontent.com/assets/12682937/18372527/0600fece-7646-11e6-8d71-c2efbc8fd4e1.png)

Why it's needed: https://github.com/LMMS/lmms/issues/3027#issuecomment-246762811
How it'll look: https://github.com/LMMS/lmms/issues/3027#issuecomment-246764620
Technical details: https://github.com/LMMS/lmms/issues/3027#issuecomment-246768940

Please tell me, what do you think about this.

Best regards,
Vladislav.

**Comment by musikBear** [comment]
I agree to the 2. picture. Separation in bass and lead, that way, makes the score more readable. 
An extension to that, could be that a color had a 'family-state' and we then had an option to select (mark) one or several families. Would make it very easy to copy a part of the piano-roll. 
I see no benefit in different colors pr. bar.

Btw, you can already set any color you like for the grid, with css: I use
'´PianoRoll {
	background-color: rgb(0, 0, 0);
	qproperty-gridColor: rgb( 228, 228, 228 ); ´'

**Comment by tresf** [comment]
This bug report should be shortened to: 

> Add possibility for user to chose different colors for separate notes to give him ability to ~~highlight~~ visually separate notes/melody lines, etc.
> ![image](https://cloud.githubusercontent.com/assets/6345473/18388717/ba0e1b66-7670-11e6-8c41-6d88c22dd6c7.png)

If you want to put a blurb about why this is needed, fine, but 620 words is overkill for such a basic request.

**Comment by vlad1777d** [comment]
@musikBear , thank you. I meant not just "different colors pr. bar", but when in one piano roll box (piece with notes) there will be 2 melodies: 1 after other. 
Yes, thank you, I did not knew about css to change LMMS's theme.

**Comment by vlad1777d** [comment]
@tresf , sorry.
I made this because at the forum: https://lmms.io/forum/viewtopic.php?f=15&t=1739&p=11751#p11751 such short issue had not success. (I wrote that several years ago, not many people agreed with me, some people expressed doubt about benefits of this approach)
Also a little text with one picture had not success too: https://lmms.io/forum/viewtopic.php?p=15540#p15540

So I decided to tell about this more widely.

**Comment by tresf** [comment]
@vlad1777d no apology needed; this is the right place; just clean up the original post please.

The feature request (colored pencil, color highlighted notes, etc) is part of most DAWs already, so it's a natural addition to the software. :+1:   Welcome to the tracker.

**Comment by vlad1777d** [comment]
Hello dear friends.

After I came to LMMS near 5 years ago, I straightway noticed that there is absent **ability to highlight different lines of notes or separate notes in one instrument**. In FL Studio that is made by adding different colors to different lines.

There are many situations, when you need to highlight note lines:
1. Piano melody has different lines for left and right hand (bass and main melody).
2. You want to combine several melodies, that are played on the same instrument, to one instrument (for saving hardware resources).
3. Your main melody consists from several lesser melody lines.
4. There are small inserts present in main melody.
5. Several melodies go one after other in one piano roll's piece (box).

**For example**:
My very very old track "Hod" (first) has two lines: bass and main melody:
https://vk.com/wall314234556_66
(the second melody "cc4" also has necessity highlighting several melody lines, it's made in one instrument with 3 lines: main melody, higher melody, bass)
Here is how it's written in Piano roll:
![notes in old roll](https://cloud.githubusercontent.com/assets/12682937/18372454/a0fead28-7645-11e6-913a-1f7968410639.png)
Here the devil himself can break his leg. How to play, how to edit? Where is what?
To understand we need play this track several times in needed places - this is waste of time.

Here is variant with highlighted notes:
![melody_color_notes](https://cloud.githubusercontent.com/assets/12682937/18372527/0600fece-7646-11e6-8d71-c2efbc8fd4e1.png)
From it we can see that there are only two lines, when we will listen if first time - all will became clear.
(I suggested such grid here: https://github.com/LMMS/lmms/issues/3019#issuecomment-245580836)

Then we can make a sketch: how will colored notes will look like:
![piano_roll_color_notes_grid_new](https://cloud.githubusercontent.com/assets/12682937/18372593/7d4aade0-7646-11e6-9b80-29371f95ff76.png)
Yes, they are too light, but they are enough readable. How to correct this we will look later, now let's see details.

**Details**:
![notes_details](https://cloud.githubusercontent.com/assets/12682937/18372709/4fd976b0-7647-11e6-9bc0-aa7cf8105a35.png)
-main color is chosen by user (from list of with RGB values);
-color of top and left sides of frame are made from main color by decreasing the "S" (saturation) value in HSV format to near 20 points;
-color of bottom and right sides of frame are made  from main color by decreasing the "V" (value) value in HSV format to near 25 points;

To make notes not looking like wight crow, we can decrease their light (but they'll look muddy and dirty), also we can make them a little transparent. I tried different variants of gradient, but general translucency looks like better than all other:
![glass_notes_experiments](https://cloud.githubusercontent.com/assets/12682937/18372907/8af33316-7648-11e6-85d8-4531720d38dd.png)

How the notes will look with transparency:
![piano_roll_glass_notes](https://cloud.githubusercontent.com/assets/12682937/18372921/ae6f5702-7648-11e6-8dba-397ae2f03ab8.png)
Not too light, not too dark, enough readable.

**Details**: 
-main color is chosen by user (from list of with RGB values) than it's applied to note with 30% of non-transparency (I made this in GIMP).
-color of top, left, bottom and right sides of frame are made such as they were made to non-transparent notes (they have not transparency).

My **suggestion is to add possibility for user to chose different colors for separate notes** to give him ability to highlight needed notes\melody lines.
Some details about appearance and how to change note's colors I described here: https://github.com/LMMS/lmms/issues/2903

**Details about system**:
-button to specify color of note is in the top-left side of Piano roll (on the panel, where are other buttons (copy, paste, highlight)) (it's in the place, the same where it's in FL Studio's Piano roll).
-when user specified color on the button in the top-left side of Piano roll, all next notes, that will be placed, will have the chosen color, all previous notes will remain with theirs color.

-to change last posted note's color we can place another button near the color button, called "paint". After pressing it, instrument "paint" will be activated. All separate notes, on which user will click with left mouse button, will be painted to the color, specified in button to specify color of note.
To paint several highlighted notes user can: 
--press left mouse button on the free space and drag it (frame highlighting will be activated) 
(at first I wrote to press right button, but such behavior is implicit and not very clear. If this will be left button, user without any manuals will open it). 
All chosen notes will be painted into specified color (they will not be highlighted, they'll be painted at once);
--highlight notes before pressing "paint" button, then, after pressing "paint" button, click on one of highlighted notes, than all highlighted notes will be painted into specified color (highlighting will not disappear, notes just will change their color).
_Shortly: 1. pressing left button on the free space and dragging - we change color of just selected with appeared frame notes; 2. pressing left button on note - we change separate note's color; 3. pressing left button on of one already highlighted notes - all highlighted notes will change their color._

-also it would be great to add possibility for user to change not only color, but also mode of placing notes (modes: semi-transparent, solid): --it can be implemented by adding switcher: transparent\solid into the popup menu of button to specify note's color. So user can change and note's color and mode and they both affect to drawn notes.

Optional change (requires extra amount of code): 
-the button to change color of notes can be in note's properties panel too (this panel is suggested here https://github.com/LMMS/lmms/issues/2903)
-to change color of last posted note's color or highlighted notes, user can press button in note's properties panel or highlighted notes panel (this panels are described here https://github.com/LMMS/lmms/issues/2903).


That's, maybe, all. Please tell me, what do you think about this.

Best regards,
Vladislav.

**Comment by vlad1777d** [comment]
Why it's needed?

After I came to LMMS near 5 years ago, I straightway noticed that there is absent **ability to highlight different lines of notes or separate notes in one instrument**. In FL Studio that is made by adding different colors to different lines.

There are many situations, when you need to highlight note lines:
1. Piano melody has different lines for left and right hand (bass and main melody).
2. You want to combine several melodies, that are played on the same instrument, to one instrument (for saving hardware resources).
3. Your main melody consists from several lesser melody lines.
4. There are small inserts present in main melody.
5. Several melodies go one after other in one piano roll's piece (box).

**For example**:
My very very old track "Hod" (first) has two lines: bass and main melody:
https://vk.com/wall314234556_66
(the second melody "cc4" also has necessity highlighting several melody lines, it's made in one instrument with 3 lines: main melody, higher melody, bass)
Here is how it's written in Piano roll:
![notes in old roll](https://cloud.githubusercontent.com/assets/12682937/18372454/a0fead28-7645-11e6-913a-1f7968410639.png)
Here the devil himself can break his leg. How to play, how to edit? Where is what?
To understand we need play this track several times in needed places - this is waste of time.

Here is variant with highlighted notes:
![melody_color_notes](https://cloud.githubusercontent.com/assets/12682937/18372527/0600fece-7646-11e6-8d71-c2efbc8fd4e1.png)
From it we can see that there are only two lines, when we will listen if first time - all will became clear.
(I suggested such grid here: https://github.com/LMMS/lmms/issues/3019#issuecomment-245580836)

**Comment by vlad1777d** [comment]
How it'll look like.

Then we can make a sketch: how will colored notes will look like:
![piano_roll_color_notes_grid_new](https://cloud.githubusercontent.com/assets/12682937/18372593/7d4aade0-7646-11e6-9b80-29371f95ff76.png)
Yes, they are too light, but they are enough readable. How to correct this we will look later, now let's see details.

To make notes not looking like wight crow, we can decrease their light (but they'll look muddy and dirty), also we can make them a little transparent. I tried different variants of gradient, but general translucency looks like better than all other:
![glass_notes_experiments](https://cloud.githubusercontent.com/assets/12682937/18372907/8af33316-7648-11e6-85d8-4531720d38dd.png)


How the notes will look with transparency:
![piano_roll_glass_notes](https://cloud.githubusercontent.com/assets/12682937/18372921/ae6f5702-7648-11e6-8dba-397ae2f03ab8.png)
Not too light, not too dark, enough readable.

**Comment by vlad1777d** [comment]
## Technical details.

_Back:_ https://github.com/LMMS/lmms/issues/3027#issue-175902898

**Details about non-transparent notes:**
![notes_details](https://cloud.githubusercontent.com/assets/12682937/18372709/4fd976b0-7647-11e6-9bc0-aa7cf8105a35.png)
-main color is chosen by user (from list of with RGB values);
-color of top and left sides of frame are made from main color by decreasing the "S" (saturation) value in HSV format to near 20 points;
-color of bottom and right sides of frame are made  from main color by decreasing the "V" (value) value in HSV format to near 25 points;

**Details about transparent notes:**
-main color is chosen by user (from list of with RGB values) than it's applied to note with 30% of non-transparency (I made this in GIMP).
-color of top, left, bottom and right sides of frame are made such as they were made to non-transparent notes (they have not transparency).

**General details about system:**
-button to specify color of note is in the top-left side of Piano roll (on the panel, where are other buttons (copy, paste, highlight)) (it's in the place, the same where it's in FL Studio's Piano roll).
-when user specified color on the button in the top-left side of Piano roll, all next notes, that will be placed, will have the chosen color, all previous notes will remain with theirs color.

-to change last posted note's color we can place another button near the color button, called "paint". After pressing it, instrument "paint" will be activated. All separate notes, on which user will click with left mouse button, will be painted to the color, specified in button to specify color of note.
To paint several highlighted notes user can: 
--press left mouse button on the free space and drag it (frame highlighting will be activated) 
(at first I wrote to press right button, but such behavior is implicit and not very clear. If this will be left button, user without any manuals will open it). 
All chosen notes will be painted into specified color (they will not be highlighted, they'll be painted at once);
--highlight notes before pressing "paint" button, then, after pressing "paint" button, click on one of highlighted notes, than all highlighted notes will be painted into specified color (highlighting will not disappear, notes just will change their color).
**Shortly: 1. pressing left button on the free space and dragging - we change color of just selected with appeared frame notes; 2. pressing left button on note - we change separate note's color; 3. pressing left button on of one already highlighted notes - all highlighted notes will change their color.**

-also it would be great to add possibility for user to change not only color, but also mode of placing notes (modes: semi-transparent, solid): --it can be implemented by adding switcher: transparent\solid into the popup menu of button to specify note's color. So user can change and note's color and mode and they both affect to drawn notes.

**Optional changes:** (requires extra amount of code)
-the button to change color of notes can be in note's properties panel too (this panel is suggested here https://github.com/LMMS/lmms/issues/2903)
-to change color of last posted note's color or highlighted notes, user can press button in note's properties panel or highlighted notes panel (this panels are described here https://github.com/LMMS/lmms/issues/2903).

_Some details about appearance and how to change note's colors I described here:_ https://github.com/LMMS/lmms/issues/2903

_Back:_ https://github.com/LMMS/lmms/issues/3027#issue-175902898

**Comment by vlad1777d** [comment]
@tresf , I had shortened request, details I wrote in the comments, 
I think that it'll be to read them and correct them depending on the situation then to think about them from scratch.

**Comment by tresf** [comment]
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.
