### ISSUE TITLE
One channel could partially mute another (at times)

### ISSUE THREAD

**Issue by spacediver** [LMMS/lmms#3038]
LMMS is 1.1.3 (Linux/x86_64):

1. Load this file: https://yadi.sk/d/QKRT0MQJvAUBz
2.  It sounds like this (lead sound is not heard at moments when kick is active): https://yadi.sk/d/-C-s3qgVvAUjS
3. Mute the kick (to 0%) — lead now sounds as intended: https://yadi.sk/d/cZtABh5KvAUmM

This is reproducible on per-channel too (if you pan kick 100% to the left, it only mutes the left channel of the lead). 

I suspect it's not how project mixer should function, I've never head such artifacts.

Thanks in advance,

**Comment by karmux** [comment]
Calf Limiter's output is set to 28. Changing it to some much lower value makes lead sound hearable at any moment.

**Comment by spacediver** [comment]
I see, I've probably misused limiter for the kick, but how on earth would this setting (of an effect of the kick channel) affect another channel in such surpiring way? Why could it mute another channel altogether? This sounds very weird for me, and appears as a misbehavoiur of the mixer as the whole, hence this bugreport.

**Comment by Umcaruje** [comment]
This is not a bug. You're driving the kick so hard into clipping that its actually masking the melody. Here's the same thing done in Bitwig Studio:

https://www.youtube.com/watch?v=pZVbUcjZtlM

The solution to your problem is to not drive your kick so hard that it clips.

**Comment by spacediver** [comment]
@Umcaruje, makes sense, thank you!
