### ISSUE TITLE
Runtime Error. Will not Launch

### ISSUE THREAD

**Issue by ewm2000** [LMMS/lmms#3039]
This is the error I received after installing.

![image](https://cloud.githubusercontent.com/assets/6345473/18535726/cadf2d60-7ac4-11e6-90ce-6a4963b4ee87.png)

*Edited by @tresf, inserted screenshot, removed link*

**Comment by tresf** [comment]
@ewm2000 this is a known issue, better explained in the duplicate bug reports.

Duplicates: #512 #1173 #3033
