### ISSUE TITLE
Track action button displays generic grey button not gear icon

### ISSUE THREAD

**Issue by follower** [LMMS/lmms#3040]
On OS X 10.8.x (with both 1.2.0RC-1 a.k.a. 1.1.90 and 1.1.91 from #2890) the track action button does not get displayed/rendered correctly and a generic unlabelled button is displayed instead:
![gear-action-button-bug](https://cloud.githubusercontent.com/assets/189962/18536356/bb869c0e-7b50-11e6-8042-5f4da3ba3977.png)

**Comment by tresf** [comment]
This is most likely a theme issue.  I recommend purging LMMS and installing from here; https://github.com/tresf/lmms/releases/download/v1.2.0-RC2/lmms-1.1.90-08d54d3-mac10.8.dmg which is the most recent Mac build.

**Comment by Umcaruje** [comment]
Again, a theme issue, closing. Reset your theme path in the settings.
