### ISSUE TITLE
Song Editor background not displayed correctly: no grid displayed, only black

### ISSUE THREAD

**Issue by follower** [LMMS/lmms#3041]
On OS X 10.8.x (with both 1.2.0-RC1 a.k.a. 1.1.90 and 1.1.91 from #2890) the background of the sound editor is completely black:
![song-editor-background-bug](https://cloud.githubusercontent.com/assets/189962/18536433/69f9ac86-7b51-11e6-9e80-5461e1327fb1.png)
In previous versions this has displayed a grid--I'm assuming this is a bug and not an intended theme change?

**Comment by tresf** [comment]
@follower can you confirm that this problem exists in this build?  This is the most recent and I do not recall the problem you are reporting since we've switched to the new theme.

https://github.com/tresf/lmms/releases/download/v1.2.0-RC2/lmms-1.1.90-08d54d3-mac10.8.dmg

**Comment by Umcaruje** [comment]
This is most probably a theme issue. Please reset your theme in the settings. If the problem still persists, let us know, so we reopen the issue.
