### ISSUE TITLE
My Presets filtering works only for some subfolders without expanding them

### ISSUE THREAD

**Issue by karmux** [LMMS/lmms#3047]
1) Open LMMS.
2) Select "My Presets" from left and search for "bass". Some bundled presets show up. There is Bass folder but no olivers-100 folder listed under ZynAddSubFX.
3) Clear filter box.
4) Expand and then close ZynAddSubFX/olivers-100 folder.
5) Search again for "bass".
6) Both Bass and olivers-100 folders listed under ZynAddSubFX.

I'm using LMMS master on Kubuntu 16.04.

**Comment by Umcaruje** [comment]
Confirmed using the master branch on elementary os Freya.

**Comment by tresf** [comment]
@kamnxt  (https://github.com/LMMS/lmms/commit/cd6d70a10be161811734cc24928e9b5a6b1c1aa6) which reverted functionality of https://github.com/LMMS/lmms/pull/1611.

**Comment by kamnxt** [comment]
@tresf Are you sure? I only disabled the recursive scanning of the home directory, not the other categories like My Presets.

**Comment by tresf** [comment]
> @tresf Are you sure? I 

No, you're right, the `FileBrowser` has a [separate instance](https://github.com/LMMS/lmms/blob/cd6d70a10be161811734cc24928e9b5a6b1c1aa6/src/gui/MainWindow.cpp#L126) for presets. 👍

**Comment by karmux** [comment]
Filtering from subfolders was working for few months until ef1ab883421c90a8d29ca64a43a47c89bb7a70de was committed. Unfortunately reverting ef1ab883421c90a8d29ca64a43a47c89bb7a70de causes same issue as described in #3180.
