### ISSUE TITLE
LMMS 1.1.90.0 is unusable: x64 Hangs on Windows 7 on first time start-up from clean install

### ISSUE THREAD

**Issue by PhilScrace** [LMMS/lmms#3049]
While splash screen is loaded the startup phase reaches 'Preparing automation editor' and then the app crashes. It's not possible to use the tool.
1. Install LMMS 1.1.90.0 having downloaded it from the stable releases 
   link in Github and downloaded the x64 version, on Windows 7
   1a. Restart the machine
2. Run LMMS from Program Files or from disk

Actual behavior:
Windows crash dialog with the following information:
```
Problem signature:
  Problem Event Name:   APPCRASH
  Application Name: lmms.exe
  Application Version:  1.1.90.0
  Application Timestamp:    a650a648
  Fault Module Name:    ntdll.dll
  Fault Module Version: 6.1.7601.23539
  Fault Module Timestamp:   57c99b8f
  Exception Code:   c00000fd
  Exception Offset: 000000000004db13
  OS Version:   6.1.7601.2.1.0.768.3
  Locale ID:    2057
  Additional Information 1: 2fb8
  Additional Information 2: 2fb88ed8b02d8421bb6f722538e37179
  Additional Information 3: 39ca
  Additional Information 4: 39ca20d2401901433da02bbfbfe6662a

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt
```
Expected behavior:
LMMS loads and is usable

**Comment by Jousboxx** [comment]
LMMS 1.1.90 is a very old and buggy version of LMMS. If you would like try a more powerful, stable, and new beta version, check out this build I made a few weeks ago:

https://drive.google.com/open?id=0B8dZ3IVOKKA6VXRCREdKdUU1Qnc

Keep in mind that this is not a release version, nor is it endorsed by any of the developers. There are a few bugs, but I have found it to be stable enough for normal use.

Enjoy, and if you have any problems please tell me right here!

**Comment by tresf** [comment]
@Jousboxx FYI, if you fork the repo, you can host your binaries at `https://github.com/Jousboxx/lmms/releases`

**Comment by Jousboxx** [comment]
I am very new to this whole development thing. I don't know what hash notation is or how to fork a report, but I hope to learn this kind of stuff when I have more time, probably early december.

**Comment by Jousboxx** [comment]
Repository* ;)

**Comment by tresf** [comment]
Fork:  https://github.com/LMMS/lmms#fork-destination-box
The commit hash should be generated automatically when you build.  Since your build has `RC2` in the name, I assume you renamed it.  We're going terribly off-topic now but the point is you can host the EXEs on your own GitHub lmms copy which is more trustworthy than a Google Drive link since it associates the EXE the account that built it so we can tag your name if there are any issues.

**Comment by BaraMGB** [comment]
@PhilScrace is this issue still appearing on RC2?

**Comment by codingatty** [comment]
I had the same issue. I downloaded the then-current release 1.1.90 at the end of December.  Tonight, I noticed that the current release now on the LMMS site is back to 1.1.3. I removed 1.1.90 and downloaded and installed 1,1,3, and it now starts up properly. I'm just now starting to play with it, but at least it starts.

**Comment by tresf** [comment]
>  I noticed that the current release now on the LMMS site is back to 1.1.3

FYI, It has been that way for a long time.  We've never offered 1.1.90 or 1.20-RC2 as our "stable" release.

@codingatty I'm not sure if you've tried, but [here's some research](https://github.com/LMMS/lmms/issues/3417) on a startup problem I've been having.

If 1.1.3 launches and 1.2.0-RC2 does not, I'd kindly like to have a copy of your `.lmmsrc.xml`.

**Comment by codingatty** [comment]
> We've never offered 1.1.90 . . . as our "stable" release.

@tresf That's odd; if I didn't get 1.1.90 from the lmms.io download page, I have no idea where I got it.

I just uninstalled 1.1.3 and installed 1.20-RC2. 1.20-RC2 starts without problems, too.

I have the event log (XML) for the 1.1.90 failure if that's helpful. The one I have is for 32-bit, but the problem occurred on both 32- and 64-bitt. I only tried the 32-bit when the 64-bit one did not work.

**Comment by tresf** [comment]
> I just uninstalled 1.1.3 and installed 1.20-RC2. 1.20-RC2 starts without problems, too.

Good news.

> I have the event log (XML) for the 1.1.90 failure if that's helpful. 

Unfortunately, not yet, no.  We don't provide any useful debug symbols for Windows, so the Event Log won't have anything we can use.  We've found several problems with the software since the 1.1.90 release, so we'll close this out until we receive confirmation that it still exists on RC2.

Much obliged.
