### ISSUE TITLE
Make plugin names consistent

### ISSUE THREAD

**Issue by simonvanderveldt** [LMMS/lmms#3055]
As part of #2988 there was mention of standadizing the plugin names. This issue is to track that so we don't have to spam #2988 with unrelated comments :)
Relevant comment: https://github.com/LMMS/lmms/pull/2988#issuecomment-249934390

Proposed naming scheme:
- Separate words
- Separated by a space
- Capitalize first letter of each word

If anyone has any objections or suggestions regarding the naming scheme feel free to comment :)

List of plugins to do:
- [x] Amplifier
- [x] BassBooster
- [x] Bitcrush
- [x] Crossover Equalizer
- [x] Delay
- [x] Dual Filter
- [x] Dynamics Processor
- [x] Equalizer
- [x] Flanger
- [x] Multitap Echo
- [x] Peak Controller
- [x] Spectrum Analyzer
- [x] Stereo Matrix
- [x] Waveshaper Effect

I'll check the existing plugins tomorrow and mark the ones that are already OK.

**Comment by tresf** [comment]
At a glance it appears these have all been taken care of.  @simonvanderveldt can you confirm and update the listing/close the issue?

![screen shot 2017-03-17 at 2 19 42 am](https://cloud.githubusercontent.com/assets/6345473/24031311/435559ee-0ab8-11e7-9f8c-f5995c85861a.png)

**Comment by tresf** [comment]
No response from OP, but closing as completed.  👍

**Comment by simonvanderveldt** [comment]
@tresf sorry, read the notification on my phone and then forgot to take a look at it later :x
Seems like they are all fixed now, so good job to all involved! :)
