### ISSUE TITLE
Target RemoteVstPlugin does not detect dependency changes

### ISSUE THREAD

**Issue by jasp00** [LMMS/lmms#3059]
`RemotePlugin.h` is a dependency of `RemoteVstPlugin.cpp`. If the header is updated, the executable is not rebuilt. Adding the header to `SOURCE` in `CMakeLists.txt` does not work. This could be solved by using `ADD_EXECUTABLE()` instead of `ADD_CUSTOM_COMMAND()` to build `RemoteVstPlugin` and set `wineg++` as the compiler, but CMake does not allow multiple compilers in the same directory. The solution would be to move this part of the build to a subdirectory.

**Comment by lukas-w** [comment]
@PhysSong Yup!
