### ISSUE TITLE
UI/UX inconsistency: Beat and bassline pattern shown in instrument track

### ISSUE THREAD

**Issue by simonvanderveldt** [LMMS/lmms#3060]
For an unknown reason (can't reproduce) I managed to get the Song Editor in a state where every click on a normal instrument track would show the Beat and Bassline pattern in the respective bar I clicked on. This didn't happen for a Sample Track.
Double clicking would still bring up the Piano Roll so this seems to be only a visual bug.

![image](https://cloud.githubusercontent.com/assets/204286/19021366/08c67080-88c0-11e6-90fb-536305bb6592.png)

[edit] Actually, it's even possible to enable steps in the pattern which then actually trigger the instrument :o
![image](https://cloud.githubusercontent.com/assets/204286/19021393/99c72232-88c0-11e6-98ca-3f07c678920a.png)

**Comment by Umcaruje** [comment]
This is not actually a bug, all empty patterns are BB patterns.

**Comment by simonvanderveldt** [comment]
> This is not actually a bug, all empty patterns are BB patterns.

Now I'm confused :P
This is in the Song Editor window, that should never show a BB pattern, right?

Also, this is not the normal behaviour I get. Normally when I click somewhere in the Song Editor a new pattern (colored rectangle) gets created for that specific bar, not an entire BB pattern.
![image](https://cloud.githubusercontent.com/assets/204286/19022177/18a6aefe-88d2-11e6-87a3-0f4d54a88b20.png)

**Comment by grejppi** [comment]
When you zoom close enough, all instrument patterns have steps, by design. This is not a bug, it's always been like this.

**Comment by simonvanderveldt** [comment]
> When you zoom close enough, all instrument patterns have steps, by design. This is not a bug, it's always been like this.

:o So that's what's causing it.

Would it be OK to get rid of this and just show the rectangular color for all the zoom levels?

**Comment by DeRobyJ** [comment]
Actually, thanks to this feature you can create a beat right on the song editor. This is perfect when you don't need to repeat the same thing all bars.
I feel no need to get rid of that

**Comment by simonvanderveldt** [comment]
> Actually, thanks to this feature you can create a beat right on the song editor. This is perfect when you don't need to repeat the same thing all bars.
> I feel no need to get rid of that

So you use this to put some patterns with a single note down in the Song Editor? Does that mean you don't use the Beat and Bassline editor?

**Comment by grejppi** [comment]
Why should they be mutually exclusive?

**Comment by tresf** [comment]
It IS a bug, at least from a UI/UI perspective.   (Or more accurately an enhancement). If we honor this we should do it in a non-Easter-Egg fashion.

**Comment by DeRobyJ** [comment]
I still think we have no reason to edit this feature.
First of, there are some demo projects in the program that show some composers not using BB at all for drums, they do them with pianoroll.
Then, I know this is a kind of Easter Egg, but when I found it I only felt happy to discover a new way to create drums.

@simonvanderveldt actually you can use both.
For example you can have a constant Hi-hat section, but you can vary Kick and Snare each bar, with different velocities and rhythms

Like in this project: https://lmms.io/lsp/?action=show&file=9379

of course I could use some long BBtracks, but that would take more tracks on SE, and you'd have to take note of their names and where to put them.
Also to make even a singe edit on a copy of the BB pattern, you'll have to create a new BB track.

Instead, this way you can edit the beats locally on every sample pattern with 800% zoom, and them give them a name and copy them on other places with 400% or less zoom.
and again, you can make edits on any of the copies by just doing it and maybe changing the name.

Might not be a usual way to compose on most EDM tracks, but for some genres it can be useful.


![screenshot_234](https://cloud.githubusercontent.com/assets/6437521/19052026/84b2d904-89b5-11e6-907b-becd74c27af1.png)
(random names)

**Comment by musikBear** [comment]
> do it in a non-Easter-Egg fashion.

@tresf  -True, i thought it would be as simple as changing '1600%' to 'B&B-Look', but already at 800% the B&BLook will be shown.
Perhaps it could be 
*B&B-Look x1* and *B&B-Look x2*
But then the *current* dropdown is too narrow to show the string-item, but there are abundant space to widen it.
*B&B-Look x1* and *B&B-Look x2* is intuitive imo, because 800% is half the size of the 1600%, so magnification 1 and 2 makes sense.

**Comment by tresf** [comment]
> [...] they do them with pianoroll.

This isn't about the piano roll.

> of course I could use some long BBtracks, but that would take more tracks on SE, and you'd have to take note of their names and where to put them. Also to make even a singe edit on a copy of the BB pattern, you'll have to create a new BB track.

Just because it's useful doesn't mean it's intuitive.  No one is arguing the usefulness of this.

When a pattern has zero length notes in the Song Editor, they should probably be displayed as a Piano Roll segment.  The "variation patterns" can already be handled by the piano roll and they render correct when zoomed out.  That said, I would still advocate for https://github.com/LMMS/lmms/issues/454 as a more intuitive means for variant patterns.  Static BB patterns are certainly difficult to work with for the reasons [mentioned](https://github.com/LMMS/lmms/issues/3060#issuecomment-251211417).

**Comment by DeRobyJ** [comment]
Yea I think #454 would be a much better solution.
I'd leave it like it is 'till we have independent BBblocks in tracks.

Also, should we discuss retro compatibility? Or is the feature so unused that we can leave it like that?

About using piano-roll vs using BB-like blocks, with the latter you can have a overview of the drum section, while if you use pianoroll you'd have to rembember what the kick is doing while editing the snare, and so on.

But I understand this is not the point of the issue.

**Comment by simonvanderveldt** [comment]
> @simonvanderveldt actually you can use both.
> For example you can have a constant Hi-hat section, but you can vary Kick and Snare each bar, with different velocities and rhythms
> 
> Like in this project: https://lmms.io/lsp/?action=show&file=9379

@DeRobyJ Thanks for the clarification and the example project. that helps a lot with trying to understand how others use this feature.

If I understand the concept correctly you use:
- A short Beat & Bassline pattern (1 bar) that repeats for a long time
- Multiple patterns in the Song Editor to add layers with variations

What you gain is not having to copy the repeating pattern in the Beat & Bassline editor.
Is that correct?

> of course I could use some long BBtracks, but that would take more tracks on SE, and you'd have to take note of their names and where to put them.

And what if you put everything in a BB track? Then this wouldn't be the case, right? Because they are all next to each other?
But you would need to copy the repeating pattern.

> Also to make even a singe edit on a copy of the BB pattern, you'll have to create a new BB track.

This is the issue/use case as described in #454, right?
 
> Instead, this way you can edit the beats locally on every sample pattern with 800% zoom, and them give them a name and copy them on other places with 400% or less zoom.
> and again, you can make edits on any of the copies by just doing it and maybe changing the name.

I ran into another issue with this, namely that ctrl+drag to make a copy of an existing part in the Song Editor doesn't work for these patterns

> Might not be a usual way to compose on most EDM tracks, but for some genres it can be useful.

If it helps you it's obviously useful :)

The reason I created this issue is that it caught me by surprise (i.e. it clashed with the [principe of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment)).
This was caused because I understood LMMS to do 2 different tasks:
- Arrange in the Song-Editor
- Compose in the Piano Roll and the Beat+ Bassline editor
(and obviously there's the mixer and global automation as well)

This is pretty much how all the other DAWs I've used work as well. I believe even FL Studio doesn't do composing in the arrangement view (Playlist). (this is not meant as a suggestion not that what others do is the correct thing to do, but as a reference about why I found it surprising that it's different in LMMS)

Not sure if this it the right place, but I ran into workflow issues with the BB editor straight away (both the lack of creating variations and composing them within a single track, no way to do slides and no way to control the instruments in it with a MIDI controller) so I switched to single instruments (for now samplers or Synths with banks, haven't found a way to combine the two) that can just be composed using the Piano roll.
This easily solves all these usability issues for me :)

**Comment by DeRobyJ** [comment]
Yea I think we both understood pretty everything.

About copying, in 800% it gets a little tricky, you'll have to Ctrl+drag the upper line of the bbpattern, the same place you'd double-click on BBEditor to transform the pattern in a pianoroll.

**Comment by musikBear** [comment]
> About copying, in 800% it gets a little tricky

In piano-roll? No, not in current Master /PR -You can hold sh and just drag along the bar-indicator, that will mark all notes under that line. 

Unfortunately a *second* selection is not possible, so unless all notes you like to 'handle' are displayed at 25% magnification, the job need to be repeated for the rest of the notes, but it is a wonderful option. (search, but could not find the ref)

**Comment by RebeccaDeField** [comment]
@simonvanderveldt It seems like the title of this issue should be updated.

**Comment by SecondFlight** [comment]
As part of a pruning effort, this `enhancement` request has been consolidated into #4877.
