### ISSUE TITLE
Vertical zoom in piano roll

### ISSUE THREAD

**Issue by BaraMGB** [LMMS/lmms#3063]
I'll noticed the piano roll don't have a vertical zooming feature. It should be easy to implement:

![2016-10-03-225518_1280x800_scrot](https://cloud.githubusercontent.com/assets/6502580/19054141/42e8a892-89be-11e6-9603-d881ae8e3a87.png)
_(the piano roll isn't stretcht in this picture, that is something that has to be happen in the finished implementation. I only increment the constant KEY_LINE_HEIGHT in the PianoRoll.cpp for zooming in vertical.)_

The question is, how to implement the UI for that? For horizontal zooming we have a Combobox in the header. I want to discuss this in this issue a little bit. Some ideas?

best regards

**Comment by musikBear** [comment]
@BaraMGB I (batman.. rather moleman..) like the idea for obvious reasons :eyes: .. But the piano looks really weird, so that would need to scale accordingly

**Comment by BaraMGB** [comment]
Duplicate of https://github.com/LMMS/lmms/issues/2294
