### ISSUE TITLE
If "Sinc Medium" is (recommended) why isn't it default?

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms#3070]
The Export Track dialog tells us "sinc medium" is "(recommended)".  If it's recommended, why isn't it the default?

![screen shot 2016-10-08 at 2 43 19 pm](https://cloud.githubusercontent.com/assets/6345473/19215216/a879d1c2-8d65-11e6-8ece-f94b85e48ee2.png)

**Comment by SirBothersome** [comment]
I wholeheartedly agree. Also, why can't preferred export settings be set/saved?

**Comment by zonkmachine** [comment]
It's sinc, not sync. I think it's this function: https://en.wikipedia.org/wiki/Lanczos_resampling
It could also be that the (recommended) comment was put on the wrong option.

**Comment by tresf** [comment]
The article sites 2 as being the best compromise.  I don't think it's mislabeled.

>  (with a = 2) the "best compromise in terms of reduction of aliasing, sharpness, and minimal ringing"

**Comment by zonkmachine** [comment]
Probably just enough to change ` <number>1</number>` to  `<number>2</number>` here:
https://github.com/LMMS/lmms/blob/48cc3bb5ef85bac8cc7c01b11dd3139c547a0677/src/gui/dialogs/export_project.ui#L239

**Comment by unfa** [comment]
I'd make this change if I knew how to, but I have no idea what branch etc. Could someone change that one digit in the code and close this issue, please? :)

**Comment by Umcaruje** [comment]
> I knew how to, but I have no idea what branch etc.

Well, isn't this issue a perfect one for you or someone else to familiarize with git? We have extencive documentation on how to submit patches and how to use branches: 
https://github.com/LMMS/lmms/wiki/Accessing-git-repository
https://github.com/LMMS/lmms/wiki/Submitting-a-patch

I plan on making a git cheatsheet kind of thing on the wiki, to help all of you people out.

**Comment by zonkmachine** [comment]
Maybe we should have a `bitesize` issue label?

@unfa If you want to apply the change I suggested just go ahead. You need to do it from the current master.

**Comment by zonkmachine** [comment]
> Could someone change that one digit in the code and close this issue, please? :)

OK. Fixed it! :wink:

**Comment by tresf** [comment]
Thanks @zonkmachine !!
