### ISSUE TITLE
knob/fader dragging ignores precision in model

### ISSUE THREAD

**Issue by BaraMGB** [LMMS/lmms#3074]
That happens on **all knobs I tested**. If one drag a knob the precision is unnecessary high.

Bitcrush is only an example for that. In the BitcrushControlls.cpp we have 
```m_inGain(` 0.0f, -20.0f, 20.0f, 0.1f, this, "Input gain" ),```

If one use the mouse wheel the precision is correct. But if one drag the knob for adjusting, we've got this:

![2016-10-13-103733_1920x1080_scrot](https://cloud.githubusercontent.com/assets/6502580/19342521/7b8235ee-9132-11e6-9319-17e88879e65c.png)

**Edit: same with Fader**

**Comment by zonkmachine** [comment]
This is a duplicate of #3024

**Comment by BaraMGB** [comment]
Close this because of duplicate of https://github.com/LMMS/lmms/issues/3024
