### ISSUE TITLE
Language selection problem

### ISSUE THREAD

**Issue by bogdoslav** [LMMS/lmms#3076]
Languages listbox in settings do not show names of languages - only emply lines.
Also menu always on English (even language was changed and app rebooted).

**Comment by liushuyu** [comment]
What version of LMMS are you using?

>Also menu always on English (even language was changed and app rebooted).

Unfortunately, our translation work never got finished due to the difficulty of our strings. If you have the capability, you could also help us improve the translation.

**Comment by bogdoslav** [comment]
1) 1.1.9 (1.2.0 RC1)

2) I mean in RC1 Version menu strings is not translated at all.

**Comment by tresf** [comment]
Duplicate of #2719, #2577.
