### ISSUE TITLE
librtaudio5a collides with librtaudio5

### ISSUE THREAD

**Issue by OffifialMITX** [LMMS/lmms#3080]
I've tried to install the testing version on Debian Jessie but the error message appears:
`librtaudio5a : collides with: librtaudio5 but 4.1.1~ds0-2 must be installed` (I've translated it from German).
I was trying to do it by `~# apt-get install lmms/testing calf-ladspa libstdc++6/testing libstk-4.5.0 fil-plugins mcp-plugins omins fluid-soundfont-gm librtaudio5a stk` I've added the other packages manually as far as they have been shown as needed but not automatically installed.

**Comment by SecondFlight** [comment]
@OffifialMITX Are you still experiencing this issue?

**Comment by OffifialMITX** [comment]
I'm not completely sure, but it didn't bother me fora long time, so I guess not.

On March 13, 2019 2:35:09 PM UTC, Joshua Wade <notifications@github.com> wrote:
>@OffifialMITX Are you still experiencing this issue?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/LMMS/lmms/issues/3080#issuecomment-472447173

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by SecondFlight** [comment]
Thanks for the response!
