### ISSUE TITLE
all vsts effect plugins are opened on loading Project

### ISSUE THREAD

**Issue by Cedware** [LMMS/lmms#3082]
When I'm opening a Project, which uses some vsts Plugins for creating effects, for each effect a gui is opened in a completely separate window.
After closing those windows, and trying to reopen it by clicking the "controls"-Button in FX-Panel, the gui sometimes isn't loaded correctly.

(Kubuntu 16.04, LMMS 1.1.3, Wine 1.8)

**Comment by Umcaruje** [comment]
There have been changes on how VST's are handled on Linux on the master branch. Would you be willing to compile the master branch and see if this issue is still happening? https://github.com/LMMS/lmms/wiki/Compiling-lmms

**Comment by lukas-w** [comment]
No feedback from OP, closing.
