### ISSUE TITLE
Cant register into LMMS Sharing platform

### ISSUE THREAD

**Issue by Texxiliator** [LMMS/lmms#3084]
I cant register into LMMS Sharing platform
everytime I try to it says : invalid security code .
It try the english keyboard and Czech Keyboard and they both didnt work
Here is the Pic : 
![invalid](https://cloud.githubusercontent.com/assets/22986832/19608476/f66adc70-97d1-11e6-9516-0f8f8fc34e2f.png)

**Comment by Umcaruje** [comment]
are you sure you're typing the code correctly?

**Comment by Umcaruje** [comment]
I just succesfully made an account using google chrome:
![screenshot from 2016-10-21 23 22 27](https://cloud.githubusercontent.com/assets/6282045/19612149/4abc1a56-97e5-11e6-9af6-1014fec3717c.png)

**Comment by RebeccaDeField** [comment]
@Texxiliator Have you tried this in a different browser?

**Comment by Texxiliator** [comment]
Oh ok guys i made account with internet explorer
Seems that chrome doesnt like LMMS for some reasons . . .

**Comment by tresf** [comment]
We use a SESSION variable for that code verification and some browsers have an issue with it, namely when private browsing is enabled.

Thanks for the update.  Closing as resolved.  The underlying issue will be solved when we migrate to a new LSP technology.
