### ISSUE TITLE
FX-Mixer: Deleting a song-editor track, should reset its mixer-channel name

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#3092]
OS  : winXP sp3
LMMS: 1.1.90-g33d8v44

Issue description: When a whole named track in song-editor is deleted, its allocated FX-channel will still have the name of the deleted track.

Example          : non

Recreate         : insert any preset in song-editor, use the cogwheel context-menu to allocate the track to a new FX-channel. Observe that the FX-channel now correctly has the name of the song-editor-track. In song-editor, use the cogwheel context-menu to *remove-this-track*. Observe that the FX-mixer-channel, still has the name of the removed track.

Claim            : The FX-channel ought to be either reset to default *FX<Nm>* or also be removed.

**Comment by tresf** [comment]
> Deleting a song-editor track, should reset its mixer-channel name

Only if it's a 1:1 relationship.  For example: If there are 3 channels sending to one mixer track, this is a bad idea.  It may still be a bad idea though.  If I have two tracks named "Bass Guitar 1" and "Bass Guitar 2" where one of them is routed through a dedicated mixer channel and another is only sending to the default master channel, I may not want LMMS making assumptions about renaming anything.  When I delete "Bass Guitar 1" which is routed, I may have intentions on re-routing "Bass Guitar 2" to the "Bass Guitar 1" mixer channel.  If the channel gets renamed on me but still has all of the FX stacks on it, it just adds confusing.

In coding, this is a concept known as "Refactoring" which is usually an explicit operation.  Perhaps the best approach would be a dialog "Cleanup attached FX Channels" with a visual display of what's routed, but that can quickly turn into a large feature.

**Comment by musikBear** [comment]
Hear you loud and clear. Correct if several tracks connect to the same FX-channel, it would be wrong with a reset. I feel the 'wrongness' weighing way more that the tiny inconvenience with a manual reset, so closing :+1:
