### ISSUE TITLE
Add secondary faster scroll to FX-mixer-sliders

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#3098]
**Inv. Component:** FX-mixer

**suggested feature:** Let user scroll FX-mixer-slider with whole steps. Currently steps 1/10

**Advantage:** Since there are no logarithmic movement on sliders, a secondary scroll would make it easier to find a best slider-position, without having to scroll like mad   

**suggested combo:** sh+scroll

**Schedule:** 1.2.1 or later

**Comment by Spekular** [comment]
I'd personally suggest that the fine adjust uses a hotkey as opposed to the other way around. This is the way most other software I've used does it (inkscape, blender)

**Comment by Umcaruje** [comment]
Or we actually make the faders logarithmic, which absolutely makes sense
when handling volumes

**Comment by DeRobyJ** [comment]
Or both

Also I prefer having to shift-drag for whole steps and preserve current behavior: we already have an option for fine adjust, the mouse wheel.

**Comment by tresf** [comment]
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.
