### ISSUE TITLE
Draw note length in Piano Roll

### ISSUE THREAD

**Issue by BloodyRain2k** [LMMS/lmms#3101]
Could a small addition to the way notes are "drawn" into the piano roll be made to allow drawing the length instead of pasting either the last used length or a fixed set-before length?
Like holding shift and instead of moving the note around will it instead start where it was drawn and end where you let go of the mouse button?

I know that you can quickly copy a note's duration by clicking one, but I simply keep expecting to draw the length instead of pasting and then start moving a note when I draw them.

**Comment by Umcaruje** [comment]
Agreed, a draw mode for piano roll would be pretty useful.

**Comment by musikBear** [comment]
ehr.. but *not* with **sh**, that has been for copy for ever, and it would be really awkward to change that
Perhaps **alt**. The intuition here would be 'the alternative way to add a note', but please *not* **sh**

**Comment by BloodyRain2k** [comment]
Didn't even know that shift does something.
As far as the proposal goes can "shift drag note", which I assume is what you meant, stay as it already is because this was meant to add a behavior to shift clicking in free space, which as far as I can tell does nothing different from normal clicking.

**Comment by BaraMGB** [comment]
Alt + click is reserved on most Linux Systems for dragging the window.

**Comment by musikBear** [comment]
@BloodyRain2k sh + left-mouse dragged, copies a single note (or a block (if any))
I believe it would be possible to do that conditionally, eg 
If a block exists, the sh-drag mean copy to drop-pos
If a block NOT exists, the sh-drag mean draw in length from drag to drop-pos
That would work.
The copy-event in PR is sadly inconsistent with block-copying in SE, there lmms uses ctrl+drag. 
darn..

@BaraMGB Thanks diddent know that, so alt+mouse is nogo. (a drag of its own in a way..

**Comment by BloodyRain2k** [comment]
Maybe this could be added along some consistency changes:
ctrl+drag on a note becomes copy like in the Song Editor, ctrl+drag on free space becomes "draw note"
shift+drag becomes quick-select, which makes more sense anyways as a shift selection in general creates a new selection based on what is now being selected where as a ctrl selection alters what was selected before.
Currently the selection is on ctrl+drag but behaves like a shift selection and the actual ctrl selection behavior is on ctrl+shift+drag.

This works so far but you really shouldn't have different approaches on how to do the same thing across different windows in the same application.

**Comment by musikBear** [comment]
> Maybe this could be added along some consistency changes:
..yee, but some workflows has been 'in' for so long, that it could lead to serious confusing
Maby it should be looked at SE and change it there.. :hear_no_evil:

**Comment by tresf** [comment]
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.
