### ISSUE TITLE
Piano Roll editor's position resets when stopping playback even with auto-scrolling disabled

### ISSUE THREAD

**Issue by BloodyRain2k** [LMMS/lmms#3102]
LMMS 1.1.3 Qt 4.8.7 on Win7 x64

When you use the piano roll editor to put together a for example 8 measure wide pattern and you try to work on the end of it then you'd likely play it from the beginning and see how the end fits in.
And depending on your monitor and/or window setup will your editor window fit no more than 4-5 measures so you'd naturally scroll to the end and turn off auto-scrolling so the editor stays there.

But sadly it doesn't : ( each time the playback stops does it zip back to the beginning, even if you use loop playback with the markers set to 4-8.

https://youtu.be/GQuR9p7sq-w shows it as it happens to me.

The only way to prevent this completely is by setting the playback to stay where it is after stopping, but then you have to scroll back to the beginning each time manually to play it again from there, which is just as bad.

**Comment by musikBear** [comment]
You need to read this
https://lmms.io/wiki/index.php?title=Song_Editor#Playback_Controls
from: *The Return Mode button is a 3-position*

**Comment by BloodyRain2k** [comment]
The issue isn't with the playback position moving back to the beginning, the problem is that the editor area follows while it's told to _not_ do that.
Atleast it seems bugged to me that disabling auto-scrolling makes it scroll automatically anyways, even if it's then limited to this one case at stopping and going back to the beginning.

**Comment by musikBear** [comment]
ok, so let say you want to play from 6.3 to 9
Set your play-head @ 6.3
Set Return Mode button to <<
press play
The playhead will 
* start @ 6.3
* move to the end of the last bar with no note in it from *there* it will **always** start @ 0.0, yes -But!
* If you press space, they playhead will jump *back* to the *start-play-pos* eg 6.3!
What you describe is the return of playhead when it meet an empty bar. *There* it will return to 0.0, but if you need a 'reaction time', just drop one note in the (here 10. bar) then you have amble time to either stop playhead with a press on space, or to use your mouse and the buttons.

**Comment by BloodyRain2k** [comment]
I still don't get what that has to do with the fact that the editor area moves also back when it's told to not do that.
Atleast I expect it to _not_ follow the playhead while auto-scrolling is off.

**Comment by midi-pascal** [comment]
This issue has been analyzed long ago:  #2291
I solved part of it in #2423 for the Song Editor but got stuck in Piano Roll code...

**Comment by BloodyRain2k** [comment]
Arrrgh, I kept searching for piano roll to make sure it wasn't already an issue made, but totally forgot to check auto scroll...

Guess this can be closed then since it's technically a dupe.

**Comment by midi-pascal** [comment]
@BloodyRain2k I think so :+1:

**Comment by Umcaruje** [comment]
This bug has been fixed in the master branch: 
![gifrecord_2016-11-08_210352](https://cloud.githubusercontent.com/assets/6282045/20115034/fd5beeec-a5f6-11e6-9a6a-6102c85dc8df.gif)
