### ISSUE TITLE
[1.2.0-RC1] export (.wav and .ogg) stops after 3:54 on Win7Pro

### ISSUE THREAD

**Issue by hedwig2013** [LMMS/lmms#3105]
Each time i'm trying to export a project it stops at 3:54. The Project is over 9 minutes long. A short "sound shock" can be heard in the moment lmms stops the export.

**Comment by DeRobyJ** [comment]
Hi, I'm on Win7Pro on a more recent build, and I've exported longer projects, so I think it's been fixed.

But, to be sure, could you upload this project for us to test, or check if it always happens with any project?

**Comment by hedwig2013** [comment]
Hi, here is a screenshot with export configurations.  I can't attach the original file here cause it is copyrighted material. The file has 17 voices and uses sf2 player instrument only. The SoundFont is the GeneralUser GS 1.47 Soundfont. https://lmms.io/documentation/Useful_resources http://www.schristiancollins.com/generaluser.php I'm using automation tracks for pitch and volume. The play time is about 9:25. A second screenshot visualizes the song's structure. The bass instruments are configured with a BassBooster and the Calf Reverb LADSPA is used in the FX-Mixer.

The lmms installation is unchanged. The preferences are unchanged with the exception that i configured the default soundfont as GeneralUser GS 1.47 file.

I hope this will help you to reproduce the bug.

Thanks!

![capture](https://cloud.githubusercontent.com/assets/4510765/20067388/3acc3f44-a515-11e6-8f4d-3c0bb613ebc2.PNG)

![capture1](https://cloud.githubusercontent.com/assets/4510765/20067854/fead2e68-a516-11e6-9357-4784d1260401.PNG)

**Comment by tresf** [comment]
>  I can't attach the original file here cause it is copyrighted material.

If you can exchange it privately with a tester (such as @DeRobyJ) to confirm that the latest fixes it, that would help.  If not, we would need a project file which reproduces the crash but does not violate any copyrights.

**Comment by hedwig2013** [comment]
Done via mail

**Comment by DeRobyJ** [comment]
gmail put the mail in spam, I just read it >_>
I can reproduce. Each time I export, it will stop at a certain point.

And the problem is the time signature.
The first point that stops the export is around 1:20 rather than 3:54, and that's exactly the place where time signature changes from 4/4 to I believe 5/4.
There, export fails, and if it doesn't fail there, it will sooner or later.

Can you please create a copy of your project and remove global automation of the time signature?
The song should be exported fine. 

Then, I tested the problem on a new project, and it seems there's no problem. So there's something else that makes time signature crash the export process.

**Comment by zonkmachine** [comment]
#2030 ?

**Comment by liushuyu** [comment]
Well, I think this issue is identical to #2030. So mark one of them as
duplicate?

**Comment by DeRobyJ** [comment]
Kinda, but I can't reproduce on a new project

**Comment by hedwig2013** [comment]
Sorry, but now it does not simply stops. Now it hangs or crashes. Even if I remove all global automations of any type. The behaviour is the same for "export" and "export tracks". I used the same file i send you previously.

![2016-11-13 16_59_06-yes - homeworld](https://cloud.githubusercontent.com/assets/4510765/20247039/f872dc44-a9c3-11e6-83ad-9de7d112950e.png)
![2016-11-13 17_08_10 lmms crash](https://cloud.githubusercontent.com/assets/4510765/20247040/f87c5f4e-a9c3-11e6-800c-48c0bc8bc3bd.PNG)
![2016-11-13 16_57_50-rendering_ 100](https://cloud.githubusercontent.com/assets/4510765/20247041/f882e134-a9c3-11e6-88e7-657ea7c1dfc7.png)

**Comment by DeRobyJ** [comment]
That could be because of how unstable was that build, there's no problem in my version

**Comment by hedwig2013** [comment]
Okay. So I will retest with the next RC. Thank you for your support so far.

**Comment by DeRobyJ** [comment]
Thank you for sharing the issue :)

**Comment by softrabbit** [comment]
https://github.com/LMMS/lmms/blob/master/src/core/ProjectRenderer.cpp#L183

The export loop condition contains `Song::isExportDone()`,which checks for the done-ness by doing math that will be wrong at some point as soon as the song contains more than one time signature, see https://github.com/LMMS/lmms/blob/master/src/core/Song.cpp#L431. It multiplies the song length in bars with the length of a bar to get a value in ticks, which obviously breaks when the time signature changes.

Maybe checking the current position against `exportEndpoints.second` would be wiser?

**Comment by Umcaruje** [comment]
@hedwig2013 can you retest with the RC2 please?

**Comment by Umcaruje** [comment]
The op hasn't replied in more than a month and #3576 should fix this. It will be available in RC3. If this issue still exists in RC3, @hedwig2013 let us know so we reopen.

**Comment by hedwig2013** [comment]
Sorry for my late response. The bug is fixed. Everything is working fine.
