### ISSUE TITLE
Audio Interface automatically switches to pulseaudio when selecting ALSA

### ISSUE THREAD

**Issue by freeasinbear** [LMMS/lmms#3108]
Hi,

I'm trying to set lmms to use the ALSA audio interface (because I have a device that won't appear as a jack interface, but only ALSA one, so I'm trying to link the device to lmms), but every time, after I restart lmms, it sets to pulseaudio by itself. I can't even set the MIDI interface to ALSA raw, it gets switched to "Dummy" (I suppose because it doesn't recognize the midi interface)..

Is this normal? Am I missing something?

**Comment by Umcaruje** [comment]
@freeasinbear what version of LMMS are you using and what is your distributon?

**Comment by freeasinbear** [comment]
v 1.1.3
OS Debian 64bit

**Comment by Umcaruje** [comment]
So, could you please type `aplay -l` in a terminal. You'll get a list of your sound devices. Find the device you want LMMS to use, then in the sound settings type `hw:X,X`with X,X replaced with your device's numbers.
![screenshot from 2016-11-10 23 27 33](https://cloud.githubusercontent.com/assets/6282045/20196945/540c5ebe-a79d-11e6-8392-c0c0e3e37013.png)

It should work then.

**Comment by jasp00** [comment]
Debian version switches to the PulseAudio back end because the ALSA device is likely to be intercepted by PulseAudio; this is intended. A better solution where PulseAudio allows not to intercept ALSA is being worked on.

**Comment by tresf** [comment]
> A better solution where PulseAudio allows not to intercept ALSA is being worked on.

Well, I don't see this being worked on, so I'm marking as won't-fix for now.  If someone can shed more light on this, please request a reopen.
