### ISSUE TITLE
Since .flp FL Studio files aren't supported, it should be removed from metadata on the website.

### ISSUE THREAD

**Issue by JtLively** [LMMS/lmms#3109]

**Comment by tresf** [comment]
@JtLively can you please be more specific?

**Comment by JtLively** [comment]
On lmms.io -
"Import of MIDI files, Hydrogen project files and FL Studio ® project files"

I've been told in an earlier issue this function isn't being supported anymore.

**Comment by tresf** [comment]
Closed via https://github.com/LMMS/lmms.io/commit/ce1a5e0798cced16319bc0dfd5c134ac7cc38552.

**Comment by JtLively** [comment]
@tresf random question - how did yall set up your site to run from Github ?

**Comment by tresf** [comment]
@JtLively, we run a web service on the server-side specifically designed for the github web hooks, which is in the advanced section if the repo.  It's called "git-deploy" and uses a secret that's part of the web hook so that only our repo can push there.

**Comment by JtLively** [comment]
@tresf Thanks for the response. I'll go research and ask for more info else. You've helped a lot. Any chance yall can use help with anything web or app related? I'm planning to do more with LMMS as I learn and migrate from FL.

**Comment by tresf** [comment]
> Any chance yall can use help with anything web or app related

We always have work to be done.  Here's our current list:

https://github.com/LMMS/lmms.io/issues

**Comment by JtLively** [comment]
I'll do what I can.
