### ISSUE TITLE
Beat Slicer for audio loops and Plug-in store for Quick Downloads

### ISSUE THREAD

**Issue by ghost** [LMMS/lmms#3116]
Is a built-in beat slicer or a "plug-in" store with links to download recommended plugins in the works ?

**Comment by DeRobyJ** [comment]
All the built-it plugins are shipped within lmms.
You can have different slices of the same sample by loading it in different Audio File Processor tracks (and moving loop points as you like)

You can only add VSTs to the program, and if you're searching for new presets of existing plugins, you can look in the lsp
https://lmms.io/lsp/

**Comment by JtLively** [comment]
Shuriken is the only audio slicer I've found. I've never thought of using multiple audio tracks, but that would be time intensive. I'll keep looking. I'd like to see a app similar to Slicex for FL Studio.

https://github.com/rock-hopper/shuriken

**Comment by ReceivedChunky** [comment]
shuriken seems to be exactly what i'm looking to see in lmms (as per [here](https://github.com/LMMS/lmms/issues/3103)).

**Comment by mrrm92** [comment]
Beside slicing a sample (which could be useful anyhow), also automations could be sliced to use a subset of one of them elsewhere.
I think LMMS should support slicing.

**Comment by zonkmachine** [comment]
Closed in #6857
