### ISSUE TITLE
Blue Cat VST 'Flanger' causes LMMS to stop loading the project about midway (42%). Other issues too.

### ISSUE THREAD

**Issue by TrumpislikeCyrus** [LMMS/lmms#3118]
The audio project was about 20 minutes long and had relatively large number of samples loaded into it. It was worked on for a few months. Upon the first time using 'Blue Cat' flanger on 'watsyn', saving, closing, and reopening it, the project loading was stopped at 42% and the program had to be closed. Thanks to the support forum and thanks to God, it was made clear that the removal of the appropriate vsts from the system can fix the issue right away. Removing the entire 'bluecat flanger' package worked and the project loads with ease. Now the said plug-in was replaced by an inbuilt plugin and it is a little under-powered compared to the one removed. There are so many other threads on the forum about how certain vsts from external vendors aren't loading properly in LMMS. BlueCat plugins load and work with ease on other DAWs and LMMS has a long way to go so I decided to report it here. 

P.S. Firstly, a MIDI keyboard controller, a very popular one, AKAI Pro LPK25 is not recognized by the built in LMMS MIDI driver. Please look into that. Possibly add a better MIDI driver for controllers like these. Secondly, recording audio seems to be not possible with built in microphone in LMMS . Please look into that also. Thirdly, please take into consideration that the "satan" plugin in your software is not funny at all. It's obvious that users don't wanna see such nonsense either so they delete it. Why not an Angel one? Why do the programmers have to give glory to something that has the least glory and is the most evil spirit? May God show you the way and truth. As a former atheist, I would urge you to call on God and ask for repentance before the end of the year of Divine Mercy which ends on 20th of this November, 2016.

May God bless LMMS and may God further and help the coders.

**Comment by Umcaruje** [comment]
>There are so many other threads on the forum about how certain vsts from external vendors aren't loading properly in LMMS

Yeah this is a known issue, though debugging VST's is pretty tricky, so there hasn't been to much progress on that front.

>Firstly, a MIDI keyboard controller, a very popular one, AKAI Pro LPK25 is not recognized by the built in LMMS MIDI driver. Please look into that. 

This is most probably an issue with your operating system. I own the LPK25 and I can attest it works perfectly with LMMS on my system.

>Thirdly, please take into consideration that the "satan" plugin in your software is not funny at all. It's obvious that users don't wanna see such nonsense either so they delete it. 

Can we please not bring religion in software development? That particular plugin is a third party LADSPA plugin and its developer had the full right of choosing a name for his plugin. I don't think we will be removing or renaming that plugin, unless its author decides to change its name.

>Why not an Angel one? Why do the programmers have to give glory to something that has the least glory and is the most evil spirit? May God show you the way and truth. 

If you decide to write an actual useful audio plugin, and name it 'Angel' I think we would gladly accept that into the codebase. 

>As a former atheist, I would urge you to call on God and ask for repentance before the end of the year of Divine Mercy which ends on 20th of this November, 2016.

Look, let's put it this way: LMMS developers are not Atheists, nor are we Christians, Muslims, Buddhists or of any other religion. We are comprised of a big group of people, and I don't think we should give precedence to any belief.

**Comment by TrumpislikeCyrus** [comment]
Seculars seculars everywhere...smh.

**Comment by TrumpislikeCyrus** [comment]
Umcaruje

I appreciate you replying to my post btw. I wanted to clarify why I brought
"religion" into discussion. Because I want you to know that all people are
indoctrinated to be separated from God since childhood. See, the world is
not a spinning blue ball and that's obvious to a little kid who wasn't
indoctrinated.

There's too much indoctrination and I'm not some troll trying to irritate
you. Whereas I, as said earlier, am a former atheist and I have found the
earth to be just as it's depicted in the Bible. You see, there's a great
error with the way the false "heliocentric model" works. It started off as
pagan mythology from Greeks, the only civilization to deny the great flood
of Noah. Some fake "scientists" came much later on trying to "prove
gravity" by attaching 2 concrete balls on a rod and spinning them, how
false! It still parades as a "scientific fact" but I encourage you to think
of it this way. According to their theory, the earth and all the "planets"
would have been long ago consumed by the "gravity" of the sun but it hasn't
and it never will because the sun and the moon are roughly the same sizes,
are spotlights, above the plane of the earth and below the curved dome of
the earth. You see, the sky is blue because above the dome there are
massive amounts of water. The dome holds them back and there was a time in
human history when it was unleashed and it was the time of the great flood
of Noah. Greeks denied it because they were
hellenic/hell-centric/helio-centric pagans who believed that those
"planets" and luminaries were their gods as masses of matter and not just
mere lights. Look, if you wanna write back, I'll explain it further.

I'm not a coder so I can't write a LADSPA plugin, yet. But whoever wrote it
should have discerned the fact that he/she is contributing to the secular
indoctrination and insensitive attitudes to morals from God, the inevitable
fate of the wicked (ie hell) and the eternal life of heaven for the
repented sinners. That's why I said to repent so whoever would read it
would at least pray to God to forgive them before the completion of the
year of Divine Mercy. I know that pope is preoccupied with "global warming"
which is against the point I'm making here but remember that he's a Jesuit
pope.

Honestly
Rare music

**Comment by tresf** [comment]
Please reopen a new topic without the off topic rant.  This is the wrong place and this will not be tolerated.  This is your second warning.  The third will yield a permanent ban.

Closed for inappropriate content.  Locked to percent further discussion.
