### ISSUE TITLE
VST Effects not loading properly

### ISSUE THREAD

**Issue by Jousboxx** [LMMS/lmms#3119]
I have been trying a lot of paid VST effects recently (free trials), and many of them do not load properly. When I click 'add effect' and try to open them, the effect appears in my FX chain, but it doesn't have the 'controls' button. I have tried loading them in LMMS 1.1.3 and in a build that I made from master a few weeks ago (1.2.0 rc2). If I am in 1.1.3, a message pops up that says 'The VST plugin [effect name].dll could not be loaded for some reason.' The effect appears in the chain in both versions. 

Here is a list of the plugins I have tried that have this issue:
Waves MaxxBass
IL Maximus
IL GrossBeat
IL Edison
IL Vocodex

Reproducing the problem is very easy. Just open a new project and try to put one of these effects on any FX channel or instrument FX chain.

I am running Windows 7 SP1 64 bit. I have 8GB RAM and my CPU is an i7-4510U.

**Comment by DeRobyJ** [comment]
Commercial VSTs often use advanced graphics, and Vestige isn't really built for new GUIs!

It's true that instrument VST tend to work better than effects, tho

Just to make sure, can you load, for example, this effect? 
https://sevenphases.wordpress.com/spectrum-analyzer/
It should work fine on win7

**Comment by musikBear** [comment]
@Jousboxx 
We have a page on wiki, dedicated to tested effects plugins that does work
https://lmms.io/wiki/index.php?title=Tested_VSTs#VST_Effects_.26_plug-ins
Perhaps you can find one there that you like.

**Comment by Jousboxx** [comment]
@DeRobyJ The Spectrum Analyzer VST works great.

**Comment by Jousboxx** [comment]
@musikBear I have looked at that list and it is very handy! Unfortunately there aren't any other plugins that have the same functionality and ease of use as IL Maximus. However, Xfer OTT is similar. It's halfway between Soundgoodizer and Maximus. It runs perfectly on Windows, and it's usable on Linux. Perhaps you could add it to the list.

**Comment by musikBear** [comment]
@Jousboxx 
> However, Xfer OTT is similar.

Great, i will add it for windows asap, Thanks!

**Comment by Jousboxx** [comment]
I have found a workaround for this problem: If you run LMMS as an administrator, Maximus works perfectly!

I also tried Edison (works) and MaxxBass. MaxxBass didn't work, but that is likely because I messed up the complicated install process or because my free trial is over. I will test more IL and Waves plugins when I get a chance.

**Comment by tresf** [comment]
> If you run LMMS as an administrator, Maximus works perfectly!

This sounds like a bug with the plugin, this shouldn't be needed.

Can you please research which permission are stuck so that we can provide a non-brute force way to run it?

**Comment by Jousboxx** [comment]
Sure, I'll tell you if I find anything.

**Comment by PhysSong** [comment]
@Jousboxx Can you still reproduce this issue with RC6?

**Comment by Jousboxx** [comment]
Yes, I just reproduced the issue in rc6. I installed a fresh copy of Maximus in a folder that has nothing but the Maximus DLLs and files. I was able to open it successfully on my admin account but not on my standard one. It's also worth pointing out that this is a different install of Windows than I was using when I started this thread.

**Comment by DomClark** [comment]
I can't reproduce this in rc7. I installed the trial version of IL Maximus, and both the 64- and 32-bit versions load properly.
However, I do recall at some point having a problem with some Windows software that didn't install properly from a standard user account. The installer needed to be run as administrator, and upon entering the administrator credentials, the software was installed for that administrator user rather than the standard user. The result was permission errors whenever I tried to run the software. Might this be the issue here?

**Comment by SecondFlight** [comment]
*hmm*
@Jousboxx Can you still reproduce this in RC8?

**Comment by Jousboxx** [comment]
No, I can no longer reproduce. Maximus works properly in RC8 on a standard account.

**Comment by SecondFlight** [comment]
@Jousboxx Thanks for testing this!
