### ISSUE TITLE
When I hold a note on my computer keyboard, it sometimes does a random Arp.

### ISSUE THREAD

**Issue by JtLively** [LMMS/lmms#3121]
Will I have to stop being lazy and use my MIDI controller for this issue for now?

**Comment by tresf** [comment]
Possibly related #1644.

**Comment by DeRobyJ** [comment]
or maybe #2768

Write your OS and lmms version, please

**Comment by JtLively** [comment]
Seems similar. 
Ubuntu Studio and 1.1.3

**Comment by BaraMGB** [comment]
That seems to be a qt issue. I noticed this on some systems, too. Once I had the same system (kubuntu? I don't remember) on laptop and desktop PC. The issue appeared only on my laptop. It's really annoying.

**Comment by zonkmachine** [comment]
> Seems similar.
> Ubuntu Studio and 1.1.3

Closing as a duplicate of https://github.com/LMMS/lmms/issues/110 and https://github.com/LMMS/lmms/issues/2768 and some others. :)

@JtLively Workaround here: https://github.com/LMMS/lmms/issues/110#issuecomment-274394366
