### ISSUE TITLE
Can't change tempo on saved tracks 

### ISSUE THREAD

**Issue by smithjessk** [LMMS/lmms#3124]
Thanks for LMMS! I'm a big fan.

Ran into a bug where I cannot change the tempo on tracks that I've saved and reopened. Unfortunately, I can't consistently reproduce it yet. But, as I discover more clues, I'll put them here.

```
$ lmms -v
LMMS 1.1.3
(Linux x86_64, Qt 4.8.7, GCC 6.0.0 20160201 (Red Hat 6.0.0-0.9))
```

**Steps to reproduce:**
1. Open LMMS via the terminal
2. Create a track, change that track's tempo to (e.g.) 90, save the track and close LMMS
3. Open that track in LMMS, change its tempo to (e.g.) 100, and play it. LMMS automatically changes the tempo back to 140.

**Comment by tresf** [comment]
Possible duplicates: #1252, #2081, #3029

**Comment by tGuMedia** [comment]
make sure you have deleted the bpm automation.

**Comment by smithjessk** [comment]
Deleting BPM automation solved the problem. Thanks and sorry for the fake bug.
