### ISSUE TITLE
Velocity indicating on piano roll makes notes barely visible

### ISSUE THREAD

**Issue by aercanozcan** [LMMS/lmms#3125]
It is cool that we can see the velocity of the note from piano roll without scrolling to bottom thanks to the transparency effect. However, when we are using very low velocity notes it is really painful to see them. I would rather change it to some colour transformation instead of opacity change. (higher velocity => red maybe?) no big deal though. cheers!

**Comment by DeRobyJ** [comment]
Hi, the new theme for lmms 1.2 should look similar to this:
![screenshot_279](https://cloud.githubusercontent.com/assets/6437521/20364790/bbaf88f6-ac44-11e6-9d61-c3080d24e3a0.png)

Do you still find it hard to see, on your screen?

**Comment by ercanoezcan** [comment]
Yes! that is visible, thank you. And sorry for stupid ticket! 
cheers.

**Comment by Umcaruje** [comment]
>Yes! that is visible, thank you. 

Glad you like the redesign. Closing.
