### ISSUE TITLE
Please show indicator on playing Beat+ Base Line Editor

### ISSUE THREAD

**Issue by Jeevanson** [LMMS/lmms#3126]
Please add a progress line like we have in song editor. It would be very helpful to know which beat is currently playing. I am new to LMMS please ignore if I am wrong.

**Comment by musikBear** [comment]
Duplicate of #3052. #857

**Comment by tresf** [comment]
Added "Beat/Bassline" to title of #3052.  Closing as duplicate.  Thanks.
