### ISSUE TITLE
No audio on Windows 10

### ISSUE THREAD

**Issue by DeltaFour** [LMMS/lmms#3131]
When I try to play some audio, nothing plays. I tested the speakers, and they work. It might just be something I did wrong.

**Comment by tresf** [comment]
@GammaThree you'll need to provide us some more information.  For starters, which version are you on?  This should be either 1.1.3 or 1.2.0-RC1.  The latter being unstable and bug prone.

Second, when you navigate to Edit, Settings, Audio is SDL selected?  If not, can you select it and restart LMMS?

Finally, if you reboot and perform a fresh install does the same problem occur?

**Comment by GammaThree** [comment]
I am using version 1.1.3, and I have tried uninstalling and reinstalling.

**Comment by tresf** [comment]
@GammaThree what about SDL

**Comment by musikBear** [comment]
@GammaThree you need to read and follow
https://lmms.io/wiki/index.php?title=LMMS_Settings#Audio_Settings

**Comment by BaraMGB** [comment]
@DeltaFour I close this out because you answered not in a month. If this issue is not resolved for you please reopen this and give us more information about your system.
