### ISSUE TITLE
(VeSTige) Use a few VST(i) for many tracks

### ISSUE THREAD

**Issue by Ju-E** [LMMS/lmms#3136]
↓ Existing LMMS
VST(i)A-Track1
VST(i)A-Track2
VST(i)B-Track3

↓ I want
VST(i)A-Track1 (Midi port 1)
　　　＼Track2 (Midi port 2)
VST(i)B-Track3

+Sorry for unkind explanation because I'm not good at English

**Comment by DeRobyJ** [comment]
If I understood correctly, you want to load a single VST instrument for more that one track, using MIDI channels.

**Comment by tresf** [comment]
Related: https://github.com/LMMS/lmms/issues/1460, https://github.com/LMMS/lmms/issues/62, https://github.com/LMMS/lmms/issues/1472

**Comment by tresf** [comment]
I misread.   The bug reports https://github.com/LMMS/lmms/issues/1460, https://github.com/LMMS/lmms/issues/62, https://github.com/LMMS/lmms/issues/1472 only cover the one-to-many scenarios, this also wants many-to-one.  Re-using an existing instrument across multiple tracks would only be possible currently through MIDI-send and the project would start looking confusing.

I don't think the use-case is limited to VST(i).  Hierarchically it sounds like we would need something that behaves like an instrument "symbolic link", where the instrument controls are bound to the same instrument instance across tracks.

I think this is two separate issues.

**Comment by Umcaruje** [comment]
I think it's more similar, if not the same as #793

**Comment by Spekular** [comment]
Closing and consolidating into #5433
