### ISSUE TITLE
Update on sample packs

### ISSUE THREAD

**Issue by SirBothersome** [LMMS/lmms#3139]
Hello all. It's me again. Did you miss me? Well, due to a variety of factors, including low beta tester response, apparent dev disinterest and a few personal issues of my own, I haven't been able to make nearly as much progress on the new samples I hoped. So as of today I am officially discontinuing my LMMS sample making for the time being. I have evidently not been of much use here, so I shall not stay. Should there arise a legitimate need (i.e., conclusive proof of copyright violation) or a concentrated _team_ effort, I'll be happy to return. Until then, sayanora

**Comment by tresf** [comment]
This is a bug tracker, not a place for status updates or conversation  Closed and locked.  Please post specific status updates in the relevant threads instead of creating new.
