### ISSUE TITLE
Drums sound totally different in beat+bassline editor after envelopes are on by default

### ISSUE THREAD

**Issue by karmux** [LMMS/lmms#3143]
Drums (especially kicks, snares, crashes, rides and other longer sounds) sound very different in library and when added to project.

When I add drums to project I have to put so much effort now to make them sound again like in library.

Just drag and drop kick04 and snare07 to B+B and listen how wrong it sounds. How this even got merged?

**Comment by DeRobyJ** [comment]
I can't reproduce, they sound the same to me!

**Comment by karmux** [comment]
When I checkout 9a95d73ab788928f246e436c969b3268be831c8c (commit before enabling envelopes) drums sound same everywhere.

**Comment by DeRobyJ** [comment]
Sorry I didn't think you were talking about latest master, I'll test later

**Comment by karmux** [comment]
In B+B notes are extremely short (they have always been) and this is why samples sound very short there.

**Comment by DeRobyJ** [comment]
Yeah I see.
the problem is that BB-Pattern notes work differently to normal Piano-Roll notes.
We had a similar discussion in #3060 

We may want not to apply #3090 on BB-Tracks, that is, disabling Envelope in those and set Hold again to 0.5 (as it affects notes even if Envelope is OFF, for some reason)

**Comment by Umcaruje** [comment]
>How this even got merged?

Nobody ever made remarks about this on the Pull Request, and I forgot to check for this.

**Comment by karmux** [comment]
Let's have envelopes enabled with default HADSR values? This would fix current issue while still being a temporary workaround for #3086 I guess.

**Comment by musikBear** [comment]
In a book i saw that and envelope with
ATT, DEC, SUS, REL == 0
HOLD==1
is called 'negated', and that is regarded as a standard
would a ENV setting with negated-envelopes change the percussion sound at all?
I dont have a current Master, so i cant test.
The question is ofcause also, if a negated-envelope will cause clicks.

**Comment by BaraMGB** [comment]
Could we just exclude audiofileprocessor from this?

**Comment by tresf** [comment]
@BaraMGB, Yes, I believe so, anticipated here:
https://github.com/LMMS/lmms/pull/3090#issuecomment-263080554

> How this even got merged?

This is the wrong way to end a bug report for many reasons. Let's focus on fixing or reverting this.

**Comment by karmux** [comment]
Can we revert this for now? You can ping me to test when proper fix is ready.
