### ISSUE TITLE
How to play c6 note with keyboard ? 

### ISSUE THREAD

**Issue by getzelone** [LMMS/lmms#3144]
Hello,
I play piano roll with computer keyboard.
I want to move the range of notes (tone) higher. 

Is it possible to play c6 and the notes above ? 
Is it possible to change binding of keys qwertyuiop etc ? 

Thanks.

**Comment by tresf** [comment]
@getzelone you should be able to slide the starting note on any given instrument to the left an octave (or three) to achieve what you're asking for.

![screen shot 2016-12-04 at 1 48 57 pm](https://cloud.githubusercontent.com/assets/6345473/20868406/ad44fc8c-ba28-11e6-971f-4bb116eaa8b0.png)

**Comment by getzelone** [comment]
@tresf  Ah yes you're true thanks. 
I didn't perceive that first, because the notes pushed visually were the same.

**Comment by tresf** [comment]
:+1:
