### ISSUE TITLE
Drag-&-Drop adding of VST plugins in the FX-Mixer's effects chain

### ISSUE THREAD

**Issue by sksar** [LMMS/lmms#3150]
I would like to see the complete support or the VST Effect Plugins which are loaded in the FX mixer channels (Effects  for a channel) of most VST's .... This is only what is lacking in LMMS in case of VST's..... As there are many VST filter plugins out there which can really make audio production more better..

NOTE: This feature will also be useful to those who are current using a lot of free VST effects (such as filters, compressors, etc) available as freeware on the internet....

**Comment by tresf** [comment]
These are supported today although it's a bit convoluted process for loading them.

https://lmms.io/wiki/index.php?title=Working_with_VSTs_effects

Can you be more specific as to what's broken so that this bug report can be updated with the proper description?

**Comment by sksar** [comment]
I would like to see more features for quickly loading the VST effects which are seen as in other DAW's like Ableton, or FL-Studio ..... LMMS is powerful but it should be made more professional....

**Comment by tresf** [comment]
@sksar I think you'll find many that agree, however we require the bug report to be more precise.
Please read the history of https://github.com/LMMS/lmms/issues/1368. If you can clarify the vision by amending your title and description, we'll leave this open and categorize it accordingly.

**Comment by sksar** [comment]
Okay @tresf, **To be more precise**: I like the way the Vst effects show up in the explorer (sidebar) at the left of **Ableton Live Software**. Also it has the support for **multiple directories for the location of VST effects**,

So, what i actually want to see in LMMS is that a **separate section in the sidebar** (the left one) for VST effects where the effects (found in the directories specified in the settings) will come one by one **in the form of a list** and will simply be **drag-able and drop-able** in the fx mixer's channel's **Effects Chain section**.. 

Also note that i would be better that in the settings window we get a feature where we can add many number of **VST effects location directory setting**... (kind of like a list with add and remove)..

If you need more info other than this then please do let me know..

**Comment by BaraMGB** [comment]
Accidentally your caps lock key was turned on. Please edit your topic to lower case. Thank you

**Comment by sksar** [comment]
No, I intentionally put the topic to all Uppercase.... 
Additional Info: It would be better if the Drag and Drop could also be done for the VST synths, so that they may directly get into the Song Editor without any hassle of dropping VStiege and then manually loading the dll's each time...

**Comment by tresf** [comment]
1. VST instruments already support drag-and-drop.  Please see https://github.com/LMMS/lmms/pull/752.
2. Thank you for the additional information.  Please edit the original description, which is what developers will read when trying to implement features.
3.  All caps doesn't add value to the bug report and is generally frowned upon.

**Comment by sksar** [comment]
Oh sorry i didn't see that.

**Comment by tresf** [comment]
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.
