### ISSUE TITLE
Song Editor & B+B Editor - FX Channel Numbers Visible In Them

### ISSUE THREAD

**Issue by miketurn** [LMMS/lmms#3159]
Hello Everyone,

Please don't scold me for this one, I could have sworn I had seen this request somewhere but when searching on this forum I was not able find it.

Not sure if this information is needed by all users but it might be nice to make the double digit FX Mixer Channel number graphic be visible and be able to be assigned to the MIXER right from the SONG EDITOR and the B+B EDITOR windows.  Where something like that would be placed is up to anyone who agrees strongly enough with it to include it in the software, maybe before or after the items label?

(If this has been added to the 1.2.0 beta release I apologize I don't have the ability to use this)
Anyways if any one has any opinions please share them.
Thank You

**Comment by tresf** [comment]
#1627

**Comment by miketurn** [comment]
Please forgive me if I am incorrect but I glanced over this link and I don't think this post is the same as mine  (Post #1627 seems to be requesting a kind of context menu unless it evolves into what I am saying)

What I am saying is take that two black and green 2 digit graphic call "FX" contained in each items window that allows you to link that item to a channel in the mixer and also place that exact 2 digit graphic "FX" and be able to see it per each item in the SONG EDITOR and the B+B Editor.
So say for example in the SONG EDITOR you have a TripleOscillator.
It would show the gear icon / the mute and solo buttons / the TripleOscillator Label / and then that two digit graphic FX number right there letting you know what mixer channel it is linked to and also allowing you to assign it from there as well, rather than having to open up each item to see where they are linked, the graphic would be able to be seen per item right there in the editors.
 
Again I apologize if I am wrong about your post.
I am currently a little under the weather so I am not all here.

**Comment by musikBear** [comment]
difficult to read but @miketurn do you mean like #2563

**Comment by miketurn** [comment]
Ahhh, Thank You very much for finding this musikBear, I knew I saw this somewhere.
Yes that is what i was referring to.

I apologize for the double post, I do understand why double posts are not desired, and believe me I don't feel great when I contribute to them.  I do searches before I post, maybe it is me and the terminology I use to search, but a perfect example is the post you mention #2563, the title is not necessarily incorrect, it does state what it is doing, but in my searching I would not have found it.
Anyways thank you very much for finding this, I will close this thread and maybe leave a post there.

**Comment by musikBear** [comment]
@miketurn great, yes you are correct. 2363 has a bad headline
@tresf can you change the tittle to **"Show FX-mixer channel on each instrument"** from Show mix channel on each instrument

**Comment by tresf** [comment]
Duplicate of #2563.
