### ISSUE TITLE
Milestone Questions

### ISSUE THREAD

**Issue by miketurn** [LMMS/lmms#3161]
I am rather new to this forum, to be honest I actually just discovered what "Milestones" are a couple of weeks ago.  I apologize for asking this question here because it is not really a request but not sure where else to ask it.

My question is when it comes to milestones for example currently there are two of them.....
Milestone 1.2.0
Milestone 1.3.0

Are these set in stone, meaning once a milestone is posted nothing new will be added to them, or are they more flexable where items are added?
(I would imagine 1.2.0 is set in stone, so I guess I am speaking of 1.3.0 when I ask this question.)

Thank You

**Comment by SirBothersome** [comment]
> I am rather new to this forum, to be honest

@miketurn, this is not a forum, it is a bug tracker and a place to suggest new features. Milestone's refer to the LMMS release. The current stable release is 1.1.3.  LMMS 1.2 is the next slated release and new features with the 1.2 milestone are intended to be released with it. 1.3 Milestones refer to features for LMMS 1.3. A very far way off.

**Comment by tresf** [comment]
> Are these set in stone, meaning once a milestone is posted nothing new will be added to them, or are they more flexable where items are added?

It's absolutely impossible to keep them set in stone without dedicated developers which we don't have.  They are intended to drive feature development, but the project is suffering from lack of development help and a huge influx of bug reports, so this situation will only get worse unless we get more help.

Closing as invalid to keep the tracker clear, but please don't take that as discouragement for  discussion.

**Comment by tresf** [comment]
More specifically to the milestones you've mentioned:
 * Yes, 1.2 is going to receive a feature freeze.  The developers are discussing this now.  We have open coded fixes and features that we feel should be completed and merged prior to release as well as some unexpected upstream -- "not our bug" -- bugs which have slowed down the 1.2 release.  1.2 has suffered some of the best help and some of the most devastating developer losses throughout it's development cycle which has put many items on the ticket only to be taken back off.  See the Zyn 2.5 thread for a good example.
 * 1.3 is just a guideline at this point.  If you have strong feelings about some of the smaller UI proposals you've made I would strongly recommend setting up a dev machine and hacking a few lines of code.  Most of us aren't seasoned developers but rather users of the software that wanted to scratch an itch, so to speak.
