### ISSUE TITLE
Ubuntu not using bleeding edge for toolbar shortcut

### ISSUE THREAD

**Issue by SirBothersome** [LMMS/lmms#3163]
So I finally got around to getting Qt and the necessary libraries set up on my Linux machine. I have the a stable lmms (though apt-get) installed, and I also got the bleeding edge though git. I compiled and ran the bleeding-edge (by the book) though the terminal, oohed and aahed, and locked it to the toolbar. When I restarted it after exiting, the 1.1.3 version loaded. The two versions are in separate directories, and I locked LMMS to the toolbar with the B-E running. Any one else have this? Ubuntu  16.04 LTS, QT 5.0.7.

**Comment by tresf** [comment]
You're making an assumption that a built-from-source-LMMS has something to do with your bugged launcher shortcut; It doesn't. 

https://help.ubuntu.com/community/HowToAddaLauncher#The_Easy_Way
http://askubuntu.com/a/450847/412004
http://askubuntu.com/a/224021/412004
https://ubuntuforums.org/showthread.php?t=1969819
