### ISSUE TITLE
Automation slope icons could use more contrast

### ISSUE THREAD

**Issue by SirBothersome** [LMMS/lmms#3165]
I've found that in the latest master, its a little difficult to distinguish the diagonal slope from the curved slope in the automation editor at a distance of around a foot. Here's what I mean
![screenshot from 2016-12-17 10-53-38](https://cloud.githubusercontent.com/assets/20342439/21288096/4c8c7d32-c448-11e6-8c92-c66fe889681b.png)

Compared to the legacy icons, I dunno, it just seems a little less clear, as there appears to be more on the bottom
![automation](https://cloud.githubusercontent.com/assets/20342439/21288088/1dbcbac6-c448-11e6-9193-add44b9a0d0b.PNG)

**Comment by tresf** [comment]
Agreed.

**Comment by mikobuntu** [comment]
Perhaps a full sine wave for the curved slope, meaning the right side would be raised more.. mockup to follow.

**Comment by RebeccaDeField** [comment]
If we wanted to make the angles a bit more extreme:

![icons](https://cloud.githubusercontent.com/assets/7960169/21290199/0e30a310-c466-11e6-89fe-49f9d95a9a76.png)

@mikobuntu Looking forward to seeing your idea :)

**Comment by SirBothersome** [comment]
Pardon my horrendous graphic design chops, but I think something along the lines of
![auto](https://cloud.githubusercontent.com/assets/20342439/21290560/bfcc5d6e-c48c-11e6-87d7-0bf8c1768b4c.png)
would be the least confusing

**Comment by Spekular** [comment]
How about something like this:
![_20161218_094310](https://cloud.githubusercontent.com/assets/8918426/21292451/91999694-c506-11e6-9a16-d5a315197e01.JPG)

(Pardon the sketchiness)

**Comment by RebeccaDeField** [comment]
@SirBothersome I believe this is what your idea would look like in action:
![automation](https://cloud.githubusercontent.com/assets/7960169/21833027/3126e936-d764-11e6-9f15-1f187a5639c4.png)

@Spekular And your idea:
![automation2](https://cloud.githubusercontent.com/assets/7960169/21833089/b14a36fe-d764-11e6-80b7-94cc52ea0abc.png)

Please let me know if I have mocked up your ideas as you imagined so I can get some votes and we can decide on what route to take :)

**Comment by Spekular** [comment]
Looks about right!!I like how they look when properly done.
The middle icon could have the second "point" more centered perhaps, the asymmetry/unevenness was mostly a result of sketching on my phone.
Either way my (definitely not biased) vote goes to my idea.

**Comment by SirBothersome** [comment]
I believe @Spekular 's Idea is more definitive. My vote goes to his.

**Comment by RebeccaDeField** [comment]
@Spekular Glad to hear that you like it! I'm not sure I'm understanding your tweak perfectly. Do you mean to make the second icon stairstep down symmetrically in three "steps" or to have it look the same as it down now in the program?

**Comment by Spekular** [comment]
I mean the "step up" could be centered as opposed to off to the left. The lower and higher regions would be the same width.

It's a bit hard to describe. If needed I can make another mock up to show what I mean.

**Comment by RebeccaDeField** [comment]
@Spekular Now that you put it that way, I think I actually know exactly what you mean.

![automation2](https://cloud.githubusercontent.com/assets/7960169/21881060/09967988-d857-11e6-8f30-af4af4912fad.png)

Please let me know if this is accurate :)

**Comment by Spekular** [comment]
Yup! That's what I meant :+1:

**Comment by RebeccaDeField** [comment]
Would like to get some feedback on these options...

Redesigning the icons according to @Spekular's feedback
![09967988-d857-11e6-8f30-af4af4912fad](https://cloud.githubusercontent.com/assets/7960169/21957472/9bc7ff3e-da4b-11e6-99f2-958d05024f22.png)
OR
Adjusting the angles to make the icons a bit more distingishable
![0e30a310-c466-11e6-89fe-49f9d95a9a76](https://cloud.githubusercontent.com/assets/7960169/21957476/aea86634-da4b-11e6-855d-7a1c2633bfa4.png)

@BaraMGB @tresf @Umcaruje @mikobuntu @SirBothersome

**Comment by Umcaruje** [comment]
@RebeccaDeField I vote the option 2, looks nicer to me.

**Comment by BaraMGB** [comment]
Option 2 don't really fix the issue, I guess.

**Comment by RebeccaDeField** [comment]
@BaraMGB Thanks for the feedback! I would love to get a more info about why it doesn't work for you, if option 1 is a better solution or what you might suggest instead. :)

**Comment by tresf** [comment]
I think what he's saying is option 2 suffers the same problems as the bug report describes... The linear and bezier both look somewhat bezier.

I'd vote option 2, with the linear swapped from option one.

**Comment by RebeccaDeField** [comment]
@tresf 

Ah, thanks I think I see what he's saying.

**That makes option 3** :)
![automation3](https://cloud.githubusercontent.com/assets/7960169/21960771/8fbec8ee-daaa-11e6-9694-26c5fc99d87a.png)
I personally like this idea the best so far.

I also thought of this as a sort of in between for option 2 and 3
![automation4](https://cloud.githubusercontent.com/assets/7960169/21960778/c8e51ca4-daaa-11e6-893e-53dbe18a72eb.png)

**Comment by Spekular** [comment]
:+1: option 3

**Comment by zonkmachine** [comment]
👍 The last one... option 4?

**Comment by BaraMGB** [comment]
option 3 + 4 both fixes the issue. :+1: 
I vote for option 3

**Comment by RebeccaDeField** [comment]
I believe that option 3 is our winner here and I think it's a good compromise between the various ideas that have been posted. I just want to confirm before I make the pull request that we will want to update the linear icon throughout the rest of the program where it is used to represent automation.

![shot-2017-01-21_18-57-03](https://cloud.githubusercontent.com/assets/7960169/22179549/00265a50-e00c-11e6-9d38-aff02f2cfd69.png)

@tresf @BaraMGB

**Comment by tresf** [comment]
> I believe that option 3 is our winner here and I think it's a good compromise between the various ideas that have been posted. I just want to confirm before I make the pull request that we will want to update the linear icon throughout the rest of the program where it is used to represent automation.

Agreed.  👍

**Comment by Spekular** [comment]
Could we use one of the other two as the icon? To me they convey "automation" better since they have more points.

**Comment by tresf** [comment]
@Spekular I thought about that too.  The problem I see with the other solutions...
1. The Bezier curve could be misinterpreted for an LFO symbol
2. The olympic stairs are just a confusing icon when taken out of the context of the automation editor.
3. The straight slope is a very, very common use of the automation editor for beginner producers to do a volume-fadeout.  I think this is the widest adoption rate for beginners and advanced users.

`</"$0.02">`

**Comment by Spekular** [comment]
@tresf fair points.

Adding actual points/handles to the editor icon might help, but could look pretty bad/cluttered.

**Comment by tresf** [comment]
> Adding actual points/handles to the editor icon might help

I'll defer that to the designers.  For reference, Gimp uses this artwork:  ![screen shot 2017-01-22 at 9 45 46 am](https://cloud.githubusercontent.com/assets/6345473/22183253/93b1018c-e087-11e6-817d-289476147d35.png)

FL Studio uses something similar:  
![screen shot 2017-01-22 at 9 48 12 am](https://cloud.githubusercontent.com/assets/6345473/22183276/eddb559a-e087-11e6-8658-5ea1303c349d.png)

Personally, I think a beginner is confused by dots and lines.  A ramp (with or without dot) seems quite logical, at least for now. 👍

**Comment by RebeccaDeField** [comment]
@tresf pretty much summed up my perspective on this.

@Spekular I still have a couple tweaks to make to my PR, but what do you say if we finish this idea and if there is any confusion over the icon, we can revisit it?

**Comment by Spekular** [comment]
@RebeccaDeField :+1:
