### ISSUE TITLE
Unfa - Spoken missing a sample

### ISSUE THREAD

**Issue by SirBothersome** [LMMS/lmms#3167]
![unfa](https://cloud.githubusercontent.com/assets/20342439/21290670/adf2b21e-c491-11e6-9ddf-4a660268e874.PNG)
'Nuff said

**Comment by tresf** [comment]
Strip it, save it, commit it, PR it, close it.

**Comment by DouglasDGI** [comment]
Should this issue still be open?  Unless we're planning to include that sample as a part of LMMS, or just remove that instrument track from the project, this should probably be closed.

**Comment by tresf** [comment]
Yeah just patch the track

**Comment by Rossmaxx** [comment]
I was thinking of patching this one but was wondering if i might get yelled at for "fixing" a project and was about to ask but since i saw this issue, i'mma open a PR soon.

**Comment by tresf** [comment]
> I was thinking of patching this one but was wondering if i might get yelled at for "fixing" a project and was about to ask but since i saw this issue, i'mma open a PR soon.

Thanks!  No, you won't be yelled at for fixing this!!
