### ISSUE TITLE
Are controller-rack-LFO supposed to be continuous?

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#3178]
LFO inserted in Controller-rack are continuous.
Imo they ought to be retricked as pr note.
The fact that they are continuous, makes it impossible to use the LFO for identical outputs, notes of identical length, will change sound, depending on *position* in piano-roll.
This is an example:  
![noteset1o64](https://cloud.githubusercontent.com/assets/6662066/21484813/3993d13c-cb99-11e6-8e03-3d2b50fa8af6.PNG)
Here 1/4 notes has been placed in piano-roll with a 1/64 shift to the right.
The notes are identical.
A LFO controls the pitch. LFO-speed is synchronized to note-length (1/4). Shape is saw.
This is the output:
![notelfograph1o64](https://cloud.githubusercontent.com/assets/6662066/21484835/88727d62-cb99-11e6-9c8b-42f759d19386.PNG)
'(obs the image has been edited, the distance between each, are removed, for image reasons)
I have marked the most obvious discrepancies between the sound-spectrums.
Imo the sound of each note should be identical.
The perhaps best approach, would be a setting on the LFO : 
*Continuous* / *Discrete*
That would allow for both behaviours, and it would also insure, that no projects was backward damaged, by the improvement. 
*Continuous* should be default.

If the LFO is meant to be retricked pr. note, then its a bug.

**Comment by tresf** [comment]
> Are controller-rack-LFO supposed to be continuous?

They are not per-note, no.

**Comment by musikBear** [comment]
are you saying fo, this is not interesting at all, and then close the ticket, because this is wont-look-at /wont fix  ?

**Comment by Umcaruje** [comment]
Well I think an retrigger option would be really useful in instrument LFO's. 

For retrigger to happen on these global LFO's it would require some changes in the design of the controllers.

**Comment by tresf** [comment]
> are you saying fo, this is not interesting at all, and then close the ticket, because this is wont-look-at /wont fix ?

No, you asked a question and it was answered.  If you'd like a feature proposal, please edit the bug report to reflect that or open a new one.
