### ISSUE TITLE
cmd-drag race condition on OSX

### ISSUE THREAD

**Issue by leeavital** [LMMS/lmms#3179]
Hi folks,

I think I've found a race condition, or at least a bug with cmd-dragging automation tracks on OSX.
Environment:
- OSX 10.11.5
- Clang
- qt5

Bug: if I open any synth (I tried triple oscillator and organic), and try to cmd+drag one of the knobs onto an automation track.

Some things I tried:
- with some print statement debugging, it seems like we get to
  `AutomationTrackView::dragEnterEvent` and call `acceptProposedAction()` on the
  passed event, but even then, `AutomationTrackView::dropEvent` doesn't get called.
- If I call, `dropEvent()` directly from `dragEnterEvent()`, it looks like `dropEvent()` does what it's supposed to. Qt just isn't calling dropEvent for some reason.
- Now the race condition part: if I step through in lldb and set a breakpoint inside `dragEnterEvent`, `dropEvent` somehow starts getting called.

questions:
- is anyone else seeing this? Perhaps on different platforms
- how would one go about debugging this?  I know next to nothing about Qt.
- is there another way to create automation tracks like this without click-dragging?

**Comment by tresf** [comment]
@leeavital yes, we are also experiencing this.

https://github.com/LMMS/lmms/issues/2890

We were under the belief that it was Qt5 + XCode SDK related.  If it is a race condition it will help us fix this.  It's a blocker for a Mac Qt5 release.

**Comment by leeavital** [comment]
I just built this against qt 5.7.x, and cmd-drag is working.  I think you're right, this can be chalked up to a bug in QT.
