### ISSUE TITLE
Shouldn't saving preset save FX channel as 0?

### ISSUE THREAD

**Issue by karmux** [LMMS/lmms#3182]
When you save some instrument preset then also FX channel is saved.
If you listen previously saved preset in another project it plays either silence (when FX channel does not exist) or some random effects that happen to be on that channel.
If channel were saved as 0 then it plays user created presets consistently with factory presets.
Currently one can solve this by changing channel to 0 before saving preset.

**Comment by tresf** [comment]
> Shouldn't saving preset [files] [default the] FX channel [to] 0

👍

**Comment by softrabbit** [comment]
I disagree. I think this should be handled through ignoring any saved FX channel on load. That way you won't have to reset the channel when you load a preset into a track you already assigned to a channel.

**Comment by Umcaruje** [comment]
I agree with @softrabbit we shouldn't save FX channel information in presets at all.

**Comment by tresf** [comment]
Well @softrabbit is saying to go ahead and save it, just ignore it on load.

**Comment by Umcaruje** [comment]
Well, maybe the best of both worlds? Save with FX0, to avoid problems on preview and ignore on load.

**Comment by tresf** [comment]
@Umcaruje I'd be more interested to see if we can abolish the FX channel keys from the XML without causing a crash.  Might hit two birds, so to speak.

**Comment by tresf** [comment]
```diff
- <instrumenttrack pan="30.0333" fxch="1" usemasterpitch="1" pitchrange="2" pitch="-90.9667" basenote="46" vol="48.1">
                                 ^-------
+ <instrumenttrack pan="30.0333" usemasterpitch="1" pitchrange="2" pitch="-90.9667" basenote="46" vol="48.1">
                                 ^------- (REMOVED)
```

Tested, works. 😄 

![screen shot 2016-12-30 at 5 37 15 pm](https://cloud.githubusercontent.com/assets/6345473/21573784/a1df5dc2-ceb6-11e6-9f00-6fd44b2541dc.png)

**Comment by tresf** [comment]
Can be shimmed in the `saveSettings` function of the `InstrumentTrack` class:

https://github.com/LMMS/lmms/blob/master/src/tracks/InstrumentTrack.cpp#L1561:L1594

**Comment by tresf** [comment]
@softrabbit I tested this... it seems to also preserve the existing FX channel selection when dragged over an existing instrument button.

**Comment by softrabbit** [comment]
Ideally the fix should:
- preserve channel selection when loaded into an existing track 
- work with old presets (just not saving the channel doesn't)
- not break preview
... any more?

**Comment by tresf** [comment]
Further testing shows some unexpected behavior when the preset with missing channel is dragged.

It appears LMMS does some form of internal caching and has a tendency to reset it anyway after preview.  This request may be two-fold.
