### ISSUE TITLE
[Feature Request] Mono/Stereo button on mixer channels, or just a stereo width knob.

### ISSUE THREAD

**Issue by Arber87** [LMMS/lmms#3189]
Would be really helpful if a track need be mono, but is sampled stereo.

**Comment by tresf** [comment]
@Arber87 we have a plugin called "Stereo Matrix" available in the mixer effects.  Is this what you're talking about?

(Screenshot is from unreleased 1.2 version, 1.1 version will look differently)
![image](https://cloud.githubusercontent.com/assets/6345473/21536913/0669ee1c-cd57-11e6-855f-32cc4d3449d5.png)

**Comment by Arber87** [comment]
Very cool. Thanks!

**Comment by tresf** [comment]
@Arber87  Is this what you're talking about?  If so, can you close the bug report?  If not, can you explain the enhancement in more detail?
