### ISSUE TITLE
[Feature Request] Mixer channel routing.

### ISSUE THREAD

**Issue by Arber87** [LMMS/lmms#3191]
Would be helpful for creating drum busses.

**Comment by tresf** [comment]
@Arber87 we've had channel routing [since 1.1](https://github.com/LMMS/lmms/pull/902).  Is that what you are talking about?  If not, can you please clarify?

**Comment by Arber87** [comment]
Im such a noob! Thanks @tresf

**Comment by zonkmachine** [comment]
@Arber87 The best place to unnoobify yourself is in the LMMS forum, not the issue tracker... :wink: 
https://lmms.io/forum/
and for support:
https://lmms.io/forum/viewforum.php?f=7
