### ISSUE TITLE
[Enhancements] Being able to record notes in piano roll while song is playing

### ISSUE THREAD

**Issue by Arber87** [LMMS/lmms#3192]
Maybe i am asking for too much?

**Comment by tresf** [comment]
@Arber87 have you tried to use this button?

![image](https://cloud.githubusercontent.com/assets/6345473/21536819/c3111074-cd55-11e6-83a9-34be4ec84163.png)

**Comment by musikBear** [comment]
You need to do a tiny trick, but then it is fully possible to record and have simultaneous playback:
https://www.youtube.com/watch?v=pFy8tipBbB8
You do btw, not need to setup a loop, you can do this with the transport selected as **<<**

**Comment by Arber87** [comment]
Really helpful! Thank you!

**Comment by Umcaruje** [comment]
@Arber87 can this be closed? Is this the feature you were looking for?

**Comment by Arber87** [comment]
Yes, sir! Thanks a bunch and Merry Christmas!

**Comment by Umcaruje** [comment]
Merry Christmas to you too (mine's on January 7th though haha)
