### ISSUE TITLE
native Flanger creates glitches

### ISSUE THREAD

**Issue by DeRobyJ** [LMMS/lmms#3195]
- On a new project, add the flanger effect on triple oscillator
- Set quantity to any value but 0
- Play a note

Some gliches will cycle from right channel to left channel.
After realeasing the note, you can ear some more glitches

Editing the Delay Knob will also change the distance between the glitches.

**Comment by zonkmachine** [comment]
Introduced in 4f76241e6803a61377fe32ef522378d9c5b1b7e5 like #3276

```
commit 4f76241e6803a61377fe32ef522378d9c5b1b7e5
Author: Dave French <dave.french3@googlemail.com>
Date:   Sat Apr 18 18:40:41 2015 +0100

    Delay and Flanger, removed noise from delay when automating length
    
    The original delay code, was setting it read index relative to the length
    of the delay. This fixes that, now when the length is changed the read
    index stays in the correct place in the buffer
```

**Comment by zonkmachine** [comment]
![flangernoise1](https://cloud.githubusercontent.com/assets/6368949/22172503/d4877e96-dfa8-11e6-88b4-4f525c09409c.png)

![flangernoise2](https://cloud.githubusercontent.com/assets/6368949/22172535/d84630b2-dfa9-11e6-8a14-8299e7eff98c.png)

**Comment by zonkmachine** [comment]
Closed in https://github.com/LMMS/lmms/pull/3524
