### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by eqsavage** [LMMS/lmms#3196]
"this application has requested the runtime to terminate it in an unusual error. please contact the application support team for more information." exactly what the error said when i tried to open up a song in lmms. the rest of my tracks pull up super easy, but this one just wont. please help me out here

**Comment by karmux** [comment]
If other tracks open without problems then try to disable or remove instruments and effects (save backup before) in your project until it can be opened. This way you can find out what causes this problem and we can investigate further.

**Comment by karmux** [comment]
Could you provide the project you can't open for investigation?

**Comment by eqsavage** [comment]
how do i provide it for investigation?

*3QSavageOfficial*

**Comment by eqsavage** [comment]
and the error pops up as im trying to load the file. once it loads to about
99%, the error pops up and lmms crashes

*3QSavageOfficial*

**Comment by karmux** [comment]
@eqsavage Zip it and like [this](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/).

**Comment by eqsavage** [comment]
*3QSavageOfficial*

**Comment by eqsavage** [comment]
idk which one you are wanting to take so i sent both

*3QSavageOfficial*

**Comment by karmux** [comment]
@eqsavage I don't see attachments in your messages.

**Comment by eqsavage** [comment]
there?

*3QSavageOfficial*

**Comment by karmux** [comment]
Nope.

**Comment by eqsavage** [comment]
im supposed to be sending you the mmpz file from lmms right?

*3QSavageOfficial*

**Comment by tresf** [comment]
@eqsavage Stop using email to respond.

**Comment by tresf** [comment]
Attachments only works through the GitHub webpage.

**Comment by eqsavage** [comment]
i converted the file to ZIP but it wont let me drop it
