### ISSUE TITLE
Travis Qt5 + Mac Failing

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms#3200]
https://travis-ci.org/LMMS/lmms/jobs/188122770

> **zonkmachine wrote:**  @tresf It looks like some changes upstream is breaking Travis.
Around here?: _Updated Dec 30, 2016_  https://bintray.com/homebrew/bottles/qt5/5.7.1

**Comment by tresf** [comment]
@zonkmachine thanks for the tip above.  Turns out Homebrew finally switched from qt4 to qt5.  I'm sure packages all over the internet are breaking because of this, but I've found a qt4 backport which has been recommended on other websites.

Part of #2611 was to remove the qt4 scripts from Travis, but until https://github.com/LMMS/lmms/issues/2890 is resolved, it doesn't make sense to pull the qt4 option.

**Comment by zonkmachine** [comment]
Cool. I dropped the message from PR3133 as to not pollute it.

**Comment by tresf** [comment]
Qt4 downloaded with the new backport but the Travis-CI build stalled... Firing it off again.

**Comment by tresf** [comment]
Turns out the formula has a problem.  Filed upstream bug report for help.
https://github.com/cartr/homebrew-qt4/issues/7

**Comment by tresf** [comment]
Upstream issues was false positive.  Author didn't have binaries for build system, qt4 was compiling from source, timing out the CI environment.  Forced Sierra on qt4 builds, patched a configure time bug, fixed.  PRs can rebase against master to fix Travis.
