### ISSUE TITLE
Ability to make/load third-party LMMS plugins at runtime?

### ISSUE THREAD

**Issue by PaulBatchelor** [LMMS/lmms#3204]
Basically, I would like to build a plugin not included with LMMS that can be loaded by LMMS at runtime. 

It looks like LMMS plugins are already a collection of shared object files that get linked with the final binary, so I feel like this is either feasible or already possible.

Knowing how to do this would be a good step in getting FAUST to generate LMMS plugins. (and also to try to figure out #19)

**Comment by tresf** [comment]
@PaulBatchelor most plugins have simply been cloned over time from previous ones and we have no official documentation to support this process.

A good place to start is the [`BUILD_PLUGIN`](https://github.com/LMMS/lmms/blob/master/cmake/modules/BuildPlugin.cmake) macro and a simple plugin like [`Amplifier`](https://github.com/LMMS/lmms/tree/master/plugins/Amplifier).

**Comment by PaulBatchelor** [comment]
@tresf Thanks! I'm stumbling along here now.

I seem to have brute-forced a method for plugins (in particular, my reverbsc) to be built outside of the LMMS project. Things could probably be spruced up. If anyone on the LMMS team is knowledgeable in this area and would like to look at it, I am more than happy to make a repo for it.

**Comment by tresf** [comment]
@PaulBatchelor if you're using part of LMMS sources to do the plugin creation, it may be a good idea to incorporate it into our build tools.  `cmake` allows custom targets and if you're already using some of our `cmake` scripts, we can leverage the wiki for encouraging plugin development.  Please do share.  LMMS could really benefit from having this I feel.

**Comment by PaulBatchelor** [comment]
@tresf I've created a repo for my mess here:

https://github.com/PaulBatchelor/lmms-reverbsc

I've never used CMake before, but I kind of frankensteined things together until it worked. I also included a few sources that it was complaining about, and I copied over the entire include folder (brute-force, but it worked.)

**Comment by BaraMGB** [comment]
Why this was closed?

**Comment by PaulBatchelor** [comment]
@BaraMGB I felt the issue had been resolved, so I closed it. 

The following was figured out:

1. Yes, it would seem that plugins can be loaded at runtime. 
2. On linux, the install location is /usr/local/lib/lmms
3. It does seem possible to make plugins external to the LMMS project. A test of this can be found
[here](https://github.com/PaulBatchelor/lmms-reverbsc)

Do you think this should be re-opened?
