### ISSUE TITLE
LMMS Segfault with JACK when closing

### ISSUE THREAD

**Issue by PaulBatchelor** [LMMS/lmms#3207]
I am building from source. My Linux distro is Fedora 23. JACK version is 1.9.10. 

I've found that when I simply open LMMS and then close it again, it causes a segfault.

i've attached a gdb backtrace of the problem here : [out.txt](https://github.com/LMMS/lmms/files/683936/out.txt)

Any ideas?

**Comment by PaulBatchelor** [comment]
I was able to plug the error by taking [this](https://github.com/LMMS/lmms/blob/master/src/core/Mixer.cpp#L415) line:

`FxMixer * fxMixer = Engine::fxMixer();`

And making it check for NULL values, breaking out early if it is NULL:
```
FxMixer * fxMixer = Engine::fxMixer();
if(fxMixer) {
fxMixer->prepareMasterMix();
} else {
return m_readBuf;
}
```

This seems to plug up my issues, but I'm not sure if this would create others.

**Comment by softrabbit** [comment]
Sounds reasonable, object destruction order and stuff like that has bugged LMMS before. This time it's about assuming there always is an ```fxMixer```, when this obviously isn't the case. I believe JACK controls when audio is rendered, and might ask for a buffer even while LMMS is tearing everything down?

That early exit from ```Mixer::renderNextBuffer()``` looks safe to me, and at that point everythings being torn down anyway. An exit should probably happen if there is no ```Song``` to be found at [line 342](https://github.com/LMMS/lmms/blob/master/src/core/Mixer.cpp#L342) as well, right?

**Comment by PaulBatchelor** [comment]
That would seem to make sense as well.

**Comment by jasp00** [comment]
`Mixer::renderNextBuffer()` rotates buffers, manages play handles, and more. Would it make sense to run without a song? Playing preview handles?

**Comment by PaulBatchelor** [comment]
It could very well be that Engine::getSong() returning NULL may not ever happen realistically. The segfault that happened for me happened well after the return value was utilized. 

For the sake of not overengineering things, perhaps it is best just to place the NULL check for the line that did cause a segfault? My fix was pretty naive (I don't know the LMMS codebase well at all), so I'm mainly wondering if my fix is safe or not.

**Comment by softrabbit** [comment]
[the Mixer used to be destroyed before the fxMixer](https://github.com/LMMS/lmms/commit/b645f43cfd08d17d01175603c154fc0cf5f7efaf), but that made LMMS crash on exit in a different way, see #2584 . 

The most correct fix here would be making sure JACK doesn't ask for any more samples, close to the top of ```LmmsCore::destroy()```.  Any NULL checks without some kind of synchronization will probably leave a race condition, but if ```fxMixer = Engine::fxMixer();``` is called right before each time it's used a crash will be a lot less likely.

**Comment by Umcaruje** [comment]
I can confirm this still happens on the `master` branch.
