### ISSUE TITLE
RC2 - Theme fails to integrate on Windows 10

### ISSUE THREAD

**Issue by SirBothersome** [LMMS/lmms#3225]
Namely 
![lmms theme](https://cloud.githubusercontent.com/assets/20342439/21767817/27dcf206-d644-11e6-99de-a2bd5ce8e537.PNG)
Not sure if this is related, but the B+B editor shows the notes entered at mininum volume, even when they're not. Notes play at full volume though
![b b editor](https://cloud.githubusercontent.com/assets/20342439/21767837/4bdcd892-d644-11e6-9475-10700194b3fe.PNG)

**Comment by BaraMGB** [comment]
Did you deinstallieren the old lmms installation?

**Comment by karmux** [comment]
New dark theme had an issue that all beats were very bright (#2863) and then I made #2960 to simplify logic how beats are drawn and fixed it. I think we need to make old theme using the same simple logic.

**Comment by Umcaruje** [comment]
@SirBothersome your LMMS is pointing to an old theme, go to your settings and clear out the theme field to reset it.

@karmux that's a good catch. I'll see the classic theme today and report on how it looks.

**Comment by Umcaruje** [comment]
I'm closing this. @SirBothersome feel free to continue the discussion here, should you need more assistance.

**Comment by SirBothersome** [comment]
Very strange, Theme integrated upon restarting the program several hours later, B+B problems stopped... Idk
![lmms theme](https://cloud.githubusercontent.com/assets/20342439/21773249/50990438-d65c-11e6-8106-679c1160ba34.PNG)
