### ISSUE TITLE
Drop sample on sampletrack should add new tco 

### ISSUE THREAD

**Issue by BaraMGB** [LMMS/lmms#3228]
Currently a new audio file processor track will be inserted by dropping a sample on a (empty) sample track. Intuitive I would expect to get a new tco on that sample track.

**Comment by musikBear** [comment]
..sorry to ask dumb Qs but 'tco' ..mmm that is kind of realestate related 8|

**Comment by BaraMGB** [comment]
A tco means a track content object. This are these colored rectangles in a track.

**Comment by musikBear** [comment]
;+D ahhh ! a block
> We should make a dictionary in the dev wiki

Yep!
@BaraMGB Thanks!

**Comment by PhysSong** [comment]
Implemented via #5043.
