### ISSUE TITLE
SF2 with no "default" patch

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms#323]
Some soundfonts have a default bank number a default a patch number that is higher than zero.

1. Download [045_Florestan_Pizzicato.sf2](https://musical-artifacts.com/artifacts/397) (or any SF2 where the default patch is non-zero)
2. Drag it into the Song Editor
3. Try playing a note

This is minor, as the SF2 still works great with LMMS, except when browsing sounds, the SF2 doesn't make a sound.

The request is to allow SF2's to "automagically" choose the first patch that is available for initial preview and playback.

Pictured is an example of a free soundfont that has a "default" patch of 45.
![image](https://f.cloud.github.com/assets/6345473/2180908/d92030cc-9737-11e3-82a2-5f457cda4a0b.png)

**Comment by SecondFlight** [comment]
This appears to be fixed in RC5.

**Comment by zonkmachine** [comment]
> This appears to be fixed in RC5.

I don't see this. @tresf Do you see this issue solved?

**Comment by tresf** [comment]
> This appears to be fixed in RC5.

@SecondFlight on what evidence?

> I don't see this. @tresf Do you see this issue solved?

Thanks for catching this.  Of course not.  Nothing's changed to warrant a close.

![ezgif-1-01be90744630](https://user-images.githubusercontent.com/6345473/55303517-b9839c00-5414-11e9-822e-8b2baeb8e118.gif)

**Comment by SecondFlight** [comment]
Huh. I know I tested this and thought the issue was solved, but I guess I didn't hit this specific edge case? And I certainly didn't document my process. Sorry about that!

**Comment by tresf** [comment]
> default a patch number that is higher than zero.
> > didn't hit this specific edge case? 

The specific edge-case is the only unit test.  Sorry, I wrote this bug report 5 years ago so there's no exact steps to reproduce.   Here they are:

1. Download [045_Florestan_Pizzicato.sf2](https://musical-artifacts.com/artifacts/397) (or any SF2 where the default patch is non-zero)
2. Drag it into the Song Editor
3. Try playing a note

**Comment by amazing-username** [comment]
Is this issue still valid? I want to give it a go as my first contribution.

**Comment by tresf** [comment]
Yes, please!

**Comment by amazing-username** [comment]
I'll give it a go, I appreciate the quick response.
