### ISSUE TITLE
Inverting the Zoom Direction

### ISSUE THREAD

**Issue by SE2Dev** [LMMS/lmms#3232]
Is there a way to invert the zoom controls for the scroll wheel? Moving the scroll wheel in the direction that zooms in prior versions appears to zoom out instead in 1.2 RC2 and vice versa. Is this a bug, or is there an option to invert this somewhere?

I'm using the 64bit version of 1.2 RC2 on Windows 7.

It also might be worth noting that when I initially launched this version, the color scheme matched the old version except for several editor backgrounds which were solid black. Restarting the application appeared to fix that though.

**Comment by Umcaruje** [comment]
This was probably changed in #2517: https://github.com/LMMS/lmms/pull/2517/files#diff-155e9c8d6e46d108ea5748eb5ce59047L1494

I agree, the zooming is now inverted. Scrolling up should zoom in and scrolling down should zoom out.

Tagging @zonkmachine

**Comment by zonkmachine** [comment]
I changed this in #2517 and the reason was that the scroll direction was different when you 
set zoom level by scrolling the combo box or by Ctrl+Scrolling the track the wheel directions weren't the same. I should maybe have been more verbal about it.

**Comment by Spekular** [comment]
Ctrl + Scroll Up zooms in Chrome, but the page zoom dropdown in settings
has higher zooms towards the bottom. I don't see this as a problem.

**Comment by zonkmachine** [comment]
As I understand it, the decision to fix the scroll so it would be the same on `'combo box + wheel'` and `'Ctrl + wheel'` was right but I got the overall direction wrong.
I've inverted the zoom direction in #3273
