### ISSUE TITLE
BROWSER - Add a Close "X"

### ISSUE THREAD

**Issue by miketurn** [LMMS/lmms#3234]
Hello Everyone,

I think a close "X" added in the upper right hand corner of the browser would be useful and would follow the theme of all other windows.
In ADDITION to the close "X" it may also be nice to program the ability to close the browser by double clicking on the "6 Dot" dragging grip located in the middle of the right side of the browser.

Not big items but may be nice in the future if others agree.
Thank You

**Comment by tresf** [comment]
Like this?

![image](https://cloud.githubusercontent.com/assets/6345473/21831381/52d30ca6-d771-11e6-89d7-57b77bb21c9e.png)

**Comment by miketurn** [comment]
@tresf 
Correct

Maybe even just giving the browser a title bar like all the other windows.
Where it has an     icon at the left   /   title   /   X (to close)
Tough to say because I am aware that it is a special kind of sidebar, but it might make it fit in a little more, if desired.


While I have you here for a second, sometimes it is hard to tell if I should group my suggestions on a specific topic, such as say "The Browser" or to separate them.  I like them separate, but sometimes they are very minor suggestions I feel weird making single posts for.  I feel they would probably get more attention if separate.
(Sorry for asking this here, I can remove this part of the post after, once I receive an answer)

Like for example,  I would recommend maybe removing those instructions underneathe the red "X" in the picture you provided above.
"Drag an instrument..........existing instrument track."

Thank You For your quick response and for the graphic provided.

Oh by the way, the "p" in "Instrument plugins" needs capitalizing :)

**Comment by tresf** [comment]
> I would recommend maybe removing those instructions underneathe the red "X" in the picture you provided above.

I think everyone is in agreement, but we need to make it a bit more UX consistent with the file browser (Right Click context menu, double-click) then the help text can be removed.

> Oh by the way, the "p" in "Instrument plugins" needs capitalizing :)

Please make the [change yourself](https://github.com/LMMS/lmms/blob/master/src/gui/PluginBrowser.cpp) and we'll merge.  Please tag @liushuyu in your commit so he knows to update transiflex translation files.

**Comment by miketurn** [comment]
> Please make the change yourself and we'll merge. Please tag @liushuyu in your commit so he knows to update transiflex translation files.
I didn't realize I would be allowed to do that, I can see where the text needs to be updated on the link you provided, I would change it but I don't know the process of how to actually do it.
Believe me, if I did I would "P" all over that code :)

**Comment by tresf** [comment]
Click the pencil edit icon, make your change, it should place it in a fork of LMMS on your own personal GitHub account under a branch called `patch-1`.  Create a pull request and we'll merge.

**Comment by mikobuntu** [comment]
While we are commenting on the Browser, I would like to make a suggestion:- 

I find the existing behaviour, where I click on an icon in the Sidebar to be slightly confusing.

* I expect the icon to to remain at the top ( where I have naturally clicked on ) , with the text to show below the icon.

![browserbehaviour](https://cloud.githubusercontent.com/assets/335217/21837377/92f7298c-d7c3-11e6-8142-3a56ec500c4b.png)

**Comment by miketurn** [comment]
@tresf 
Ahhh, I was going to ask you how to do this, but didn't want to take up your time, thank you very much for taking the time to explain this, I will take care it.  I have found a few pieces of text to edit, not sure if that is okay to do so, I imagine they get previewed before they are merged, so if they are not desired I guess just ignore them?  I like when things are "proper case" (where each word is capitalized), there are a few items in the menu bar drop-down menus that aren't, can those be fixed by me?  If so if you link where to find those items I will do so.

@mikobuntu 
Funny that you mention that, I have many ideas about this as well that I am going to make a post for, I will link to it once I create it (I have to create some graphics to get my point across).  I think my ideas will clean up the browser a little hopefully others will agree.

**Comment by tresf** [comment]
> can those be fixed by me?

Please. :)
