### ISSUE TITLE
MIXER - Label Beginning Gets Chopped Off

### ISSUE THREAD

**Issue by miketurn** [LMMS/lmms#3237]
Hello Everyone,

When you edit a channel label in the mixer and the label name itself gets long enough for it to cut off where it adds the "..." to the end, right before the channel number graphic.
This causes the beginning letter of the label to get chopped off as well.

For example if you type in the following as the channel label name
ABCDEFGHIJKLMN

you get
BCDEFGHI...

Understandably the JKLMN gets cut off, but if you look at the beginning of the label you only see a little piece of the "A" which shouldn't happen, only the ending should get cut off when the label is too long.

Thank You

**Comment by BaraMGB** [comment]
Confirmed

**Comment by BaraMGB** [comment]
I can not reproduce on linux at the moment. Neither qt4 nor qt5. On windows I can reproduce this issue. But I'm sure I've seen this on linux too recently.

**Comment by musikBear** [comment]
Confirming for win32 on XP
first two letters are cut.
![fxmixlabelcut](https://cloud.githubusercontent.com/assets/6662066/21890225/f9aea736-d8cc-11e6-999d-3c1a304794cb.PNG)

Ch1 has 2 letter padding
Ch2 has 1 letter padding
Ch3 has 0 letter padding

**Comment by BaraMGB** [comment]
@miketurn can you please test this pr: https://github.com/LMMS/lmms/pull/3241
I added windows builds for 32 and 64 bit.
