### ISSUE TITLE
Effects Chain & Controller Rack - Replace "Add" Text With Plus Icons

### ISSUE THREAD

**Issue by miketurn** [LMMS/lmms#3242]
Hello Everyone,

Obviously not a huge deal, but does anyone like this idea of replacing the "Add" text at the bottom of the Effects Chain and the Controller Rack with Plus Icons like the one in the Mixer that adds new channels?
I think it has a nice clean look to it.

![plus sign edit](https://cloud.githubusercontent.com/assets/24556082/21896515/a68e78fa-d8b4-11e6-9793-df9628dc8205.jpg)

Oh Yeah!, Now that I found out how to add images to my posts, be prepared!

**Comment by tresf** [comment]
What about the Instrument Plugin?

![image](https://cloud.githubusercontent.com/assets/6345473/21919788/1e13033e-d92b-11e6-9b88-120df82836dc.png)

**Comment by miketurn** [comment]
@tresf 
Thought about that one, but for some reason I keep thinking that if you change one they are all linked to change, which is not the case.
Thank You for mentioning it.

That being said...
There is also an "effects chain" window that opens if you click on a "sample track"s label, which would have to be updated as well for consistancy.

**Comment by RebeccaLaVie** [comment]
@miketurn Hey there, this thread hasn't had any activity for some time so I just wanted to follow up to see if you are still interested in pursuing the idea. :octocat:

**Comment by Umcaruje** [comment]
This shouldn't be too hard to implement, you'd just need to make a smaller plus icon (so we remain pixel perfect and don't run into scaling issues) and add them to the buttons. Pretty easy for a beginner to do, and perfect for getting to know the codebase.

**Comment by miketurn** [comment]
@RebeccaLaVie 
@Umcaruje 
I apologize I didn't know I was being considered to work on this.

I have been trying to convince someone I know to join this forum, most of the ideas I have shared have actually come from him directly and or have been part of conversations we have had about LMMS, including this one.

He has so many ideas to share, I had to stop and try to convince him to join himself, because I couldn't keep up :)
I know he does not know much about coding, but I am sure if anyone is willing to help him out a bit, I know he is interested in more of the graphical side of coding.  He actually has provided the graphic examples for all of my posts so I know he can help with visual stuff, but again someone would have to be willing to help him as far as coding goes.  As you mention this is a perfect little project to get started with such coding.

I believe he should be joining within the next couple of weeks, so when he does I will point him here and see if he is interested.

**Comment by tresf** [comment]
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.

**Comment by sound8** [comment]
Still would be nice to see this added (pun intended).
If adding an image takes too much time, could also consider the following....

Can replace the "Add effect" text by actually typing "+"
Then can do things such as applying a bold setting, assigning a bolder font type (like one used for Settings headers), changing font size to fit, etc.
Whatever is needed to make the "+" look similar to the vertical "+" button used to add channels to the mixer.

Hope this helps
