### ISSUE TITLE
cmake doesn't find non-stable Wine on Ubuntu

### ISSUE THREAD

**Issue by karmux** [LMMS/lmms#3245]
I'm using Kubuntu 16.10 64-bit and can compile with VST support without problems using wine-stable 1.8 from Ubuntu repositories. It seems not possible to compile when Wine is either:
- wine-development 1.9 from Ubuntu repositories
- wine-devel 2.0 from Wine repositories

In both cases I installed 64 bit and also 32 bit packages.

I removed CMakeCache.txt before running cmake. `cmake ..` output:

`-- Could NOT find Wine (missing:  WINE_LIBRARIES WINE_INCLUDE_DIRS)`

Wine development files are located at `/opt/wine-devel/include/wine/windows`.
Wine libraries are located at `/opt/wine-devel/lib` and `/opt/wine-devel/lib64`.

**Comment by tresf** [comment]
@karmux may be worth looking at this chunk of code and adjusting to your environment:

https://github.com/LMMS/lmms/blob/master/plugins/vst_base/CMakeLists.txt#L34-L46

**Comment by tresf** [comment]
And if Wine isn't found at all.... `FindWine.cmake` may be worth looking into (actually, I'd argue all of the above logic could live in `FindWine.cmake` and not have to clutter the `vst_base` plugin... )

https://github.com/LMMS/lmms/blob/master/cmake/modules/FindWine.cmake

**Comment by karmux** [comment]
@tresf thanks!

cmake found Wine after these changes in `cmake/modules/FindWine.cmake`:

```
-FIND_PATH(WINE_INCLUDE_DIR windows/windows.h PATH_SUFFIXES wine)
-FIND_LIBRARY(WINE_LIBRARY NAMES wine PATH_SUFFIXES wine i386-linux-gnu/wine)
+FIND_PATH(WINE_INCLUDE_DIR windows/windows.h PATHS /opt/wine-devel/include PATH_SUFFIXES wine)
+FIND_LIBRARY(WINE_LIBRARY NAMES wine PATHS /opt/wine-devel/lib PATH_SUFFIXES wine i386-linux-gnu/wine)
```

Now compiler can't find none of the Wine header files but they do exist.

`/home/karmo/Dev/lmms/plugins/vst_base/RemoteVstPlugin.cpp:56:28: fatal error: wine/exception.h: No such file or directory
 #include <wine/exception.h>`
