### ISSUE TITLE
TripleOscillator and Organic - Slight Pop At The End Of Each Note

### ISSUE THREAD

**Issue by miketurn** [LMMS/lmms#3246]
Sorry for doing this, I will close if this is not really an issue.

It seems all my audio is fine, I don't notice any crackling or pops, but when I load up TripleOscillator or Organic instruments (maybe others?) with the first default settings (only volume knob is lowered a bit).

Can others test this out and see if they experience this?  I am not sure if it is just part of the default sound or if there is something wrong?  Just play a C4 note and when you release the note does anyone else hear a little snap/pop sound?

I think my latency settings are fine and I lower the volume knob down from the 100% default and I am not getting any signs of clipping.  I tried some other presets and I don't hear it so it is probably just part of the first presets.

Just wondering if this is normal
Thank You

**Comment by mikobuntu** [comment]
This is a known issue for all plugins, see #3086 .

**Comment by miketurn** [comment]
@mikobuntu 
Ahhh, Thank You, I will close this
