### ISSUE TITLE
Zynaddsubfx graphical interface crashes LMMS 1.2-rc2, No communication with Jack 1.9.10

### ISSUE THREAD

**Issue by E-Gwen** [LMMS/lmms#3247]
With Windows XP, LMMS 1.2-rc2 32 Bits crashes when you try to use the Zynaddsubfx graphical interface.

Not the case with 1.1.3 32 bits version.

Impossible to make LMMS 1.2-rc2 32 Bits communicate with Jack 1.9.10, under Windows XP SP3 32 Bits,
Notice it is possible with Musescore 2 , Ardour 5, Ocenaudio 3, or even TuxGuitar 1.4.

Best regards.

E-Gwen.

**Comment by tresf** [comment]
These issues are unrelated, please file a separate issue for each problem.

The Zyn issues sounds similar to #2819, but you'll need to reproduce on something other than Windows XP please.  It may be worth trying Zyn with optimizations off (set here: [plugins/zynaddsubfx/CMakeLists.txt#L22](https://github.com/LMMS/lmms/blob/master/plugins/zynaddsubfx/CMakeLists.txt#L22))

> With Windows XP, LMMS 1.2-rc2 32 Bits crashes when you try to use the Zynaddsubfx graphical interface.

We can't support Windows XP with 1.2, so please reproduce on something newer or we'll have to close as won't-fix. https://github.com/LMMS/lmms/issues/248

**Comment by musikBear** [comment]
Just want FYI notice that RC3 now allows the zasfx-UI to be opened also on win32.xp That feature was lost in 1.0 -Its back 🍾 
Thank to whoever got that fixed 👯 
-The weird #716 persists -propl 'not our bug'

**Comment by musikBear** [comment]
win32 
Sadly in RC3-49 zynAddSubFX crashes again, if  *show-gui* is pressed. This happens for both old existing presets, and new from *Instruments*
Iow: The bug has been re-introduced between 27 jun, and RC3-49

**Comment by lukas-w** [comment]
Closing for reasons stated by @tresf.
