### ISSUE TITLE
MIXER - Fader Location In The Center At 100% Volume (0dB)

### ISSUE THREAD

**Issue by miketurn** [LMMS/lmms#3253]
Hello Everyone,

Just had a quick question, bear with because I am a little out of it at the moment.
I am obviously not a professional mixer, but isn't the placement of the fader in the middle which is 100% and in other words really 0dB an odd place for it?  Considering that you usually aren't really supposed to go over this, isn't that kind of wasted space?  The upper half from 100% to 200% is a total of 6dB.
1.) Shouldn't the faders 0dB point be closer to the top graphically?
2.) Should the fader graphic be moved more to the top?
3.) Could some of this space be removed to give a little more room to the mixer channel vertically?

Hopeful I am making some kind of sense (or if someone else has posted something similar) I will close this.
Thank You

**Comment by DeRobyJ** [comment]
It's at the center because our mixer fader is linear.
Other programs have it on the upper side because they use dB in the fader. Which makes more sense, in a way, but I think it's less obvious for beginners.

**Comment by tresf** [comment]
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.
