### ISSUE TITLE
How to fetch  rc versions from github?

### ISSUE THREAD

**Issue by jasonMisaq** [LMMS/lmms#3255]
I see version 1.1.90.442 of LMMS was released one year ago in early 2016, and I noticed there is now an rc release, so I tried twice to get the newest version from LMMS' Github repository, but both times I ended up building version 1.1.90.442. I found a page for 1.2-rc version of LMMS on Github, though, where I downloaded the zip file for LMMS source and after extracting it, I executed cmake .. and I saw this message among configuration output:   
```
--------------------------
* Project version             : 1.2.0-rc2
*   Major version             : 1
*   Minor version             : 2
*   Release version           : 0
*   Stage version             : rc2
*   Build version             : 0
*

```

While the former version fetched from Github's branch showed the following config message:   
```
* Project version             : 1.1.90.442
*   Major version             : 1
*   Minor version             : 1
*   Release version           : 90
*   Stage version             : 
*   Build version             : 442
*

```
Why is that so? Is there a way,  I can get the latest version directly from github via something like `git pull https://github.com/LMMS/lmms.git`?

**Comment by tresf** [comment]
@jasonMisaq the safest way is:

```diff
git clone -b master https://github.com/lmms/lmms
+git checkout tags/v1.2.0-rc2
```

Note:
1. Master current IS the latest version directly from github.
2. Master being latest 1.2 is temporary.  We will forking a snapshot to `stable-1.2`.
