### ISSUE TITLE
MIXER - Channel Name Tooltip Style Tag Labels

### ISSUE THREAD

**Issue by miketurn** [LMMS/lmms#3257]
With the release of 1.2.0 RC2 a new feature was added, where when you keep your mouse cursor hovered over a mixer channel and tooltip style tag animates down from the cursor showing the mixer channels full name.  I can understand the purpose of it, but to me it becomes distracting how it functions because it constantly pops up, even on mixer channel names that don't get cutoff by the channel number display (adding the "..." to the end)

I would personally like to see this removed completely but if others like it maybe a setting somewhere that can turn this on/off.

If anyone has any ideas/opinions to share please do so.
Thank You

Here is a picture of the tag that I am speaking of just in case I am not making any sense......
![mixer channel name dropdown tag](https://cloud.githubusercontent.com/assets/24556082/21910377/b9411770-d8e9-11e6-94a1-f43a25677144.jpg)

**Comment by tresf** [comment]
Can you shorten the description?  "Remove tooltip, it covers stuff" doesn't require > 280 words.

**Comment by tresf** [comment]
And don't version your titles please.  Put the specifics in the body.

**Comment by Sawuare** [comment]
> to me it becomes distracting how it functions because it constantly pops up

When hovering over a channel, the time that passes before the tooltip appears (**initial delay**) is less than a second. When hovering between channels, the time that must transpire before subsequent tooltip windows appear (**reshow delay**)  is instant.
I too find this to be distracting, and annoying.

We shouldn't remove the tooltips.
I think we should (if possible) bump the initial and reshow delays to a second or a little bit more.

**Comment by Spekular** [comment]
IIRC 300ms is the appropriate delay.

**Comment by musikBear** [comment]
Still the tooltip thing is inferior to #3239

**Comment by tresf** [comment]
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.

**Comment by russiankumar** [comment]
Is this feature still required? May try to implement this after reorg.
