### ISSUE TITLE
MIXER - Allow Vertical Stretching To The Mixer Window

### ISSUE THREAD

**Issue by miketurn** [LMMS/lmms#3258]
If vertical stretching was allowed in the Mixer window, using the channel name label cutoff point (represented by the red line in the following graphic) then you could stretch the mixer out, allowing you all the room you need for channel name labels.
![mixer - current](https://cloud.githubusercontent.com/assets/24556082/21938736/8cd364a8-d98a-11e6-8d8f-18b87370573c.jpg)

Here is what it can look like....
(A side benefit would be that you would also be able to see all effects linked to that channel if desired, rather than a limiation of 4 effects.)
![mixer - vertically stretched](https://cloud.githubusercontent.com/assets/24556082/21938762/a6d53476-d98a-11e6-90dc-15910b82c5ea.jpg)

**Comment by BaraMGB** [comment]
Why to heck you want to use such long channel names? You invested a massive amount of brain energy to this issue. :flushed:

**Comment by mikobuntu** [comment]
I think the channel names space could be increased a bit perhaps ( not just as much as your mockup tho @miketurn , but I would prefer the mixer LED's to be taller and to have some markers at crucial DB levels. there is another post somewhere that describes better scaling of the levels. I will make a mockup with my thoughts in my next reply.

**Comment by Spekular** [comment]
I think this has been on the radar for a while, both to allow longer names
and taller faders. The issue AFAIK is in getting the right parts to scale
(and using vector art for the faders), and it become ever more difficult
when dealing with high DPI displays.

**Comment by miketurn** [comment]
@BaraMGB 
> Why to heck you want to use such long channel names? You invested a massive amount of brain energy to this issue. :flushed:

Just trying to help to improve the program, but thank you for the comment that makes me feel good about spending time on it, hopefully you feel good about yourself too.

The second graphic obviously is overdone to show that the window has have been stretched vertically, I am not saying anyone HAS to stretch it out that far, it just gives others the options to adjust the height.
As mentioned it also allows you to see more effects if desired.

Have a great day

**Comment by BaraMGB** [comment]
Actually I like this approach. It would work with an (evetually) implementation of a one-window-solution in future.

**Comment by tresf** [comment]
> vertical stretching [...] in the Mixer

Yes.

> I told you I would rock your worlds, with this post. This post was so massively ground breaking that it caused a "Major Service Outage" at GitHub when I tried to post it, the servers just couldn't handle it!
If you don't believe me just ask the angry rainbow colored 404 unicorn.

🦄

**Comment by musikBear** [comment]
buuut it will still be quite difficult to read those verticals 👎

**Comment by miketurn** [comment]
Okay....
Well while I am on the track of upsetting some, I guess this would be a good time to keep the train running with the following....
This idea of being able to vertically stretch the mixer may also offer a solution for the following....
#1974 (Which I am aware has been closed)
I posted some thoughts at the bottom of that thread if anyone is interested in some opinions.
As I mention there, I agree that it is a tough decision and I get why it may not be wanted, but might be worth some consideration, maybe something modular.

**Comment by tresf** [comment]
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.
