### ISSUE TITLE
Glitchy Sound in FreeBoy

### ISSUE THREAD

**Issue by popsip** [LMMS/lmms#326]
Something is wrong with FreeBoy's sound when played under Linux version of LMMS.  It makes a glitchy/static like sound when played.

I played the same notes with the same FreeBoy settings on both the Linux and Windows version of LMMS.

Linux: http://streams19.tunescoop.com/266702_IncorrectFreeboySound_stream.m4a
Windows: http://streams19.tunescoop.com/266703_CorrectFreeboySound_stream.m4a
- This issue also occurs in  Linux version of LMMS 0.4.15

**Comment by zonkmachine** [comment]
There seen to be updates done to this code in the package included in Game_Music_Emu

The version in papu/gb_apu/Gb_Apu.cpp reads:
`// Gb_Snd_Emu 0.1.4.`
And Gb_Apu.cpp from Game_Music_Emu reads:
`// Gb_Snd_Emu 0.1.5.`

http://blargg.8bitalley.com/libs/audio.html#Game_Music_Emu
https://groups.google.com/forum/#!forum/blargg-sound-libs

**Comment by karmux** [comment]
I tried updating to newer files from https://github.com/kode54/Game_Music_Emu but the noise remained.

**Comment by zonkmachine** [comment]
OK. I had another go at searching and [this repo](https://bitbucket.org/mpyne/game-music-emu/wiki/Home) looks more like a proper upstream and with [more recent commits](https://bitbucket.org/mpyne/game-music-emu/issues).

**Comment by karmux** [comment]
Sound that I get from Freeboy is actually correct.
Channel 4 is meant to be noise: https://github.com/LMMS/lmms/blob/stable-1.2/plugins/papu/papu_instrument.cpp#L271

All channels sound exactly same in Linux and Windows for me.

**Comment by Fighter19** [comment]
I was going to post a bug report when I found that it's in fact this issue (To me it still persists):
Version 1.1.3 (Ubuntu 17.04)

When changing notes, FreeBoy often emits a noise, even though all channels except for Channel 2 are muted.

![noise](https://user-images.githubusercontent.com/1475802/30661988-ebbef736-9e45-11e7-8bff-cb085b4d5282.png)

The picture above shows, how it should look like (approx.) and how it looks by lmms.

I don't know if this is intended, but not hearing this with VLC which also uses blargg (granted, I can't mute the other channels so I can't be 100% sure), I guess this is an issue.
