### ISSUE TITLE
VST failed getting shared memory and Window outside of LMMS

### ISSUE THREAD

**Issue by Hamschta** [LMMS/lmms#3260]
Hi there

compiled the newest version of lmms (1.2.0) and tried the vst plugin 
the plugin starts but the plugin content will start in a separate window and not embedded 
so as i closed that window and tried to reopen it, it doesn't open again
I also get a debug message "failed getting shared memory"

My system runs on Kubuntu 16.04 
I'm compiling with QT5

Thanks in advance
Hamschta

**Comment by Hamschta** [comment]
![screenshot_20170115_023811](https://cloud.githubusercontent.com/assets/25127218/21959664/c991bf86-dacd-11e6-8c64-7c257f8e314d.jpeg)

**Comment by tresf** [comment]
Thanks.   Identical bug, including screenshots.. :) #2855

The shared memory issue is documented here: https://github.com/LMMS/lmms/issues/1468

**Comment by Hamschta** [comment]
Thanks for reply. After compiling it with QT4 it works.
Great work. love this App
