### ISSUE TITLE
Window Fullscreen and Close "X" Icons Have Issues When Fullscreen Is Activated

### ISSUE THREAD

**Issue by miketurn** [LMMS/lmms#3263]
Song Editor / B+B Editor / Piano Roll / (maybe others?) windows contain ability to make them Fullscreen
![windows condensed](https://cloud.githubusercontent.com/assets/24556082/21990676/acb6957e-dbdd-11e6-8ac3-e33d71392248.jpg)
When Fullscreen is activate, the icons look like this
![windows expaned](https://cloud.githubusercontent.com/assets/24556082/21990704/cb3a6ca0-dbdd-11e6-922e-d01410e4bd63.jpg)

**Comment by BaraMGB** [comment]
Thanks for file this issue. That seems to be a Qt 5 issue. At the moment I don't see any possibilities to fix this.

**Comment by tresf** [comment]
> Thanks for file this issue. That seems to be a Qt 5 issue. At the moment I don't see any possibilities to fix this.

Correct, per https://github.com/LMMS/lmms/issues/2611#issuecomment-193942180, this is an upstram issue with Qt5.  One workaround may be to prevent maximize and override it with a stretch method. This is how Mac does things, so it may make the behavior more consistent at the cost of code complexity.
