### ISSUE TITLE
Sample Track - Effect Chain Window - Add Title and Remove The Fullscreen Icon

### ISSUE THREAD

**Issue by miketurn** [LMMS/lmms#3268]
Means nothing to me, but something I noticed.

If you click on a "sample track"s label it will open up an "effects chain" window for it.
1.) Might be a good idea to add the sample tracks name as a title for this effects window to know what sample track it is linked to.  (Might be tough due to the width of the effects chain, probably why it is not there)
2.) This "effects chain" window also contains a maximize/fullscreen icon to the left of its "x" close icon in the titlebar, which should probably be removed.

**Comment by BaraMGB** [comment]
:+1:

**Comment by BaraMGB** [comment]
Perhaps we should add the ability for adding the sample track to an fx channel and get rid of this ugly effect window?

**Comment by tresf** [comment]
The effect window is only ugly because the instrument is otherwise and empty screen.

If the standard instrument controls (envelope, LFO, pitch) are desired, keep the window, else delete. :)

**Comment by PhysSong** [comment]
#3632 should fix this. :+1:

**Comment by DomClark** [comment]
Fixed in #3866.
