### ISSUE TITLE
Track rearrange by dragging label

### ISSUE THREAD

**Issue by miketurn** [LMMS/lmms#3269]
May be a stupid request, but I was wondering if it was possible to be able to expand mouse drag moving of an item from not just the grips/deadspace but from the label as well.
My natural instinct keeps making me try to move items this way but I get denied every time, would anyone else find this helpful?

This is a concept graphic for something else, but in this example I am referring to the "TripleOscillator" label.
![track edit](https://cloud.githubusercontent.com/assets/24556082/22002515/a06440a4-dc1a-11e6-9d2a-250893def8ef.JPG)

**Comment by tresf** [comment]
@miketurn yes, I believe what you're describing would be just fine... remove the drag handles and just allow drag-and-drop of channels.  Best would be to implement it in code and gauge feedback.

**Comment by BaraMGB** [comment]
Technical there aren't drag handles. There's only that png. The channels can be dragged on several positions. We only have to implement the drag event for the track label button, too.

**Comment by BaraMGB** [comment]
Done .. :)

**Comment by miketurn** [comment]
@BaraMGB 
Damn you're good, thank you for adding this.
