### ISSUE TITLE
user LFO only moves dial when note plays

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#3272]
OS  : winXP sp3
LMMS: 1.2.0 RC2

**Issue description:** 
User LFO behavior is changed in rc2. the connected dial only moves with the lfo, if a note is active. This looks strange when short notes are played in concession, then the dial kind of hacks or skips and it looks bad. The output however is **correct** in respet to the set values in the lfo

**Recreate         :**
* Insert a 3oc
* insert a user lfo
* connect VOL to user lfo
* observe that the VOL dial does not move.
* press any note. Observe that the VOL dial will move as long as the key is down
**Claim            :**
Since lmms user-lfo are continuous, imo the previous behavior **looks** better

**Comment by mikobuntu** [comment]
Confirmed on Linux too .

**Comment by BaraMGB** [comment]
What do you mean by "user lfo"? A lfo in controller rack? I can't reproduce.

**Comment by musikBear** [comment]
@BaraMGB 
> What do you mean by "user lfo"? A lfo in controller rack?

Yes the **RACK**-one -The one with the default name USER next to where you activate it
and you *cant* reproduce?

**Comment by zonkmachine** [comment]
According to git-bisect it happened here: 2a7bdf3fe8113439a8703c32d7b353ded8ef1a2c :open_mouth:
Nothing that pops up as remotely related but the original PR #2570 had one merge commit in it (as opposed to rebasing to master). Apart from that I'm out of ideas.

```
commit 2a7bdf3fe8113439a8703c32d7b353ded8ef1a2c
Author: midi-pascal <midi-pascal@users.noreply.github.com>
Date:   Sat Apr 23 17:27:34 2016 -0400

    Fix cmd-line help, add config option, use local lmmsrc file in dev (#2570)
    
    * Fix command-line help, add --config option and use local lmmsrc file in dev mode
    
    * Fix a typo in help screen for option --geometry (second dash missing)
    
    * Replace tabs with spaces in help screen
    Update man page
    
    * Lineup items in help screen
    
    * Accept both -geometry and --geometry as valid options
```

**Comment by zonkmachine** [comment]
No. If I delete .lmmsrc.xml and go with the default one the problem is gone. It's not directly related to the above PR.

**Comment by zonkmachine** [comment]
For me it happens with a buffer size over 256 frames.

**Comment by zonkmachine** [comment]
I see this in 1.0.3/1.1.3 too. The only thing they have in common is the .lmmsrc.xml
This is why my bisect above homed in on 2a7bdf3fe8113439a8703c32d7b353ded8ef1a2c as this commit makes lmms look for two different config files. After, locally in the build directory from where I launched lmms, and before that commit in the $HOME directory.
Try and delete your .lmmsrc.xml and see if starting from fresh will clear this up.

**Comment by musikBear** [comment]
> Try and delete your .lmmsrc.xml and see if starting from fresh will clear this up.

@zonkmachine -Clearly you re correct! Buffer-size is the reason, and that also why .lmmsrc.xml influence this bug, but buffer-size is the the real problem

**Comment by zonkmachine** [comment]
> As soon as a note plays, the dial moves as if it was lubed

No notes needed. Just hit play and it syncs perfectly. It could be related to some effort to make lmms be leaner on the resources.

**Comment by zonkmachine** [comment]
@musikBear I can't replicate this with any methods described here. I think I've casually bumped into the issue not long ago on master but something seem to have changed so maybe the method to replicate it need to be updated.

**Comment by musikBear** [comment]
> something seem to have changed so maybe the method to replicate it need to be updated.

I will give it a lookover and see if i can reproduce at all.
