### ISSUE TITLE
Mallets plugin update

### ISSUE THREAD

**Issue by Mark-Agent003** [LMMS/lmms#3275]
The mallets plugin in LMMS could be usefull, but it doesn't sound right. Is there any way to fix that?

**Comment by zonkmachine** [comment]
Have you tried the latest [1.2.0-RC2](https://github.com/LMMS/lmms/releases/tag/v1.2.0-rc2)?

**Comment by Mark-Agent003** [comment]
Yes, but the sounds for the marimba, vibraphone, and some others just don't sound very much like a marimba and vibraphone...

**Comment by zonkmachine** [comment]
Mallets is based on[ stk-instruments](https://ccrma.stanford.edu/software/stk/classstk_1_1ModalBar.html) which is based on, and shipped with stk, the synthesis toolkit so the sound of it isn't really in our hands. Those are modelled after real physics but still models. To get a bit closer to the actual stuff you would need the instruments sampled per key at various velocities.

Add a limiter to take off the highs when you tweak the hardness/position and add equalisation with a bit of resonance to lively it up and perhaps some reverb.
