### ISSUE TITLE
LMMS hangs when DVS Guitar plugin loaded through Vestige

### ISSUE THREAD

**Issue by lmmsUser** [LMMS/lmms#328]
LMMS hangs when DVS Guitar plugin loaded through Vestige.  Using WIndows 32-bit version 0.9.90.  I have Windows Vista PC.

**Comment by Umcaruje** [comment]
@lmmsUser can you confirm this issue on LMMS 1.1.3?

**Comment by Umcaruje** [comment]
No response from the OP in months, Closing. Please reopen if you can still reproduce.

**Comment by BrahRah** [comment]
I just got the same problem with lmms 1.1.3.
