### ISSUE TITLE
Can't change mixer volume sliders

### ISSUE THREAD

**Issue by voec** [LMMS/lmms#3283]
_This has only happened to me in 1.2.0-rc2 - it worked in previous versions.
**EDIT: Not sure on this anymore. Might have been that it didn't work before as well, just that my monitor setup was different when I was using an older version. See below.**
My OS is Windows 10, 64bit._

I can't change any of the volume sliders in the mixer by left-clicking and dragging. They just stay at their current volume.
It does work however when I hover over them and use the mouse wheel, but only very slowly.

All other knobs in the instruments, song-editor or effects windows seem to work fine.

**Comment by tresf** [comment]
Do you have a stuck key?  Sounds like ctrl is stuck.  Hit your modifier keys a few times and see if it helps.  It is very unlikely that this is a big with LMMS itself but if we can reproduce it, then we can attempt to fix it.

**Comment by voec** [comment]
It's not a stuck key, since the problem persists even after hitting different keys and even rebooting.

However I have found out now that it only happens when LMMS is on my second monitor! (The first being my netbook screen)
When I drag the window back on the netbook screen the sliders work again and when I put it back on the monitor they stop moving.

I have never had anything similar happening to me in any other program so I believe it is an issue with LMMS.
I will try to reproduce the problem on a different machine when I get the chance.

**Comment by tresf** [comment]
> I have never had anything similar happening to me in any other program so I believe it is an issue with LMMS.

LMMS doesn't really have any special code that can influence this.  I checked Qt's bug tracker and they have several issues regarding to a second display, especially on HiDPI setups.

https://bugreports.qt.io/browse/QTBUG-13202?jql=status%20%3D%20Open%20AND%20text%20~%20%22monitor%22

**Comment by musikBear** [comment]
@voec try to right-click the slider, and chose "remove-global-automation"

**Comment by BaraMGB** [comment]
Is this issue solved for you?

**Comment by voec** [comment]
> Is this issue solved for you?

Sorry for not replying.

I assume it is related to what @tresf linked to. Seems highly likely.
So, no, the issue still persists, but I guess it is nothing that can be fixed by the people that work on lmms.

If someone has an account for the qt bug report site, I would appreciate it if they could notify them of the problem.

(It's not related to global automation btw, just in case)

**Comment by tresf** [comment]
@voec I'll mark this as not our bug for now.  Feel free to request a reopen if you're able to prove otherwise.

**Comment by leidentech** [comment]
> @voec try to right-click the slider, and chose "remove-global-automation"

This worked for me - not sure exactly what's going on here but it was as for a song that I created with a older version of LMMS.

**Comment by leidentech** [comment]
> @voec try to right-click the slider, and chose "remove-global-automation"
This worked for me - not sure what was going on but it was for a song I created with an older version of LMMS

**Comment by musikBear** [comment]
_Global automation_ originate most often from import of a MIDI-file. At least the The _hidden nature_ of this,  is meant to be removed completely.
