### ISSUE TITLE
Mouse pointer jumps off of GUI after selection

### ISSUE THREAD

**Issue by amsynthdotcom** [LMMS/lmms#3285]
Hello,
I've encountered a bug whereby the mouse pointer jumps off the VST synth GUI after making a selection (moving a knob/slider, selecting from a drop-down window, etc).  This doesn't occur with all synths, but one to test would be "Nocturna", available here: 

[Nocturna](http://electriccafemusic.com/nocturna/)

brian

**Comment by zonkmachine** [comment]
Yes, I have this with Synth1 also. (Linuxmint 17.3/wine-1.6.2) Basically the position the mouse jumps to is where the knob would have been if the GUI would have been in the upper left corner. Coordinates 0,0 .
Which OS/version, Lmms/version, and Wine(if on Linux)/version, are you using?

**Comment by amsynthdotcom** [comment]
Thank you for getting back. I'm using linux, the latest AntiX (Debian flavor) with LMMS version 1.1.3 and Wine version Wine-rt 2:1.8.0-1-kxstudio1.

Of course, there are other synths that create this same error, although I haven't kept track of each one.

brian

**Comment by zonkmachine** [comment]
@musikBear Do you see this on Windows? I think this may be a Wine/Linux only issue.

**Comment by musikBear** [comment]
@zonkmachine No i have never seen that.
I have moved the GUI around aligning the edge to top botom left and right + center, and the mouse stays on the chosen controller in every pos, left/ right/ 3. mouse-click .
In Synth1 it does 'jump', but that is to the precise point of current value of the slider-position -Iow -Perfect
This looks like a linux issue only.

**Comment by zonkmachine** [comment]
Thanks! I'll try and see if this is reproducible on the latest wine.

**Comment by zonkmachine** [comment]
@amsynthdotcom Can you see if https://github.com/LMMS/lmms/pull/3786 improves it?
That fix has an AppImage (binary) so you can test it easily. Just download/make executable/run.
https://transfer.sh/pIL0f/lmms-1.2.0-rc4.106-linux-x86_64.AppImage

**Comment by zonkmachine** [comment]
No response. I'm closing this.
@amsynthdotcom Try a recent version of Wine. 3.0 was just released and looks like a good candidate. I can't replicate the issue on wine >= 2.0 .
Please reopen if you can replicate this issue on a recent Wine release.
