### ISSUE TITLE
LMMS Effect Utility - Mixer Send

### ISSUE THREAD

**Issue by DeRobyJ** [LMMS/lmms#3294]
Right now, you apply effects on a plugin, then send the audio to a channel in the Mixer, and there you apply some more effects and sends between channels.

Once you get used to this, it's really clear and easy to set up.
But if you want to do some more complicated things, like sending "dry" and "wet" signals to different channels, then this system becomes a little messy.
I'll write the channels names in **bold**.
Let's say I'm using an echo delay and a reverb, and I want different channels for each of them to EQ and compress them.
The plugin will have to send the dry signal to channel **"dry"**, which then sends to the **"delay"**, which then sends to the **"reverb"**.
Which is, again, clear if you're used to it. But what about EQ and compression?
Any FX done to the **Dry** channel, will also have effect to the **delay** and then the **reverb** channels. If you don't want this to happen, you need another channel for the **dry**, turn off the Master Send from the **first dry**.
Same thing if you need to add an effect to **Delay** only, without affecting the **reverb**.
That is 5 channels to mix dry, delay and reverb of a sound separately.
Moreover, you can't save a preset of this, since the effects are in the mixer and not in the instrument plugin.

That's why I think we need something like this:
![mixer send effect](https://cloud.githubusercontent.com/assets/6437521/22291832/9a94dd9c-e308-11e6-8f85-91ea78207276.png)

What it does:
The first knob (or number) decides what channels receives sound from this effect.
Then we have a knob for Quantity to the channel (like the knobs of the sends in the mixer) and a knob for Quantity to the next effect if the FX-list this plugin is in.  If there's none, then it just goes where it should have gone without an effect. 
Sorry if I'm a bit unclear on this.

Now let's see how this applies to the example above.

In the instrument plugin, I'll have this FX-list:
1) Mixer Send to channel **"Dry"**, 100% Q.ty on both knobs
2) Delay effect
3) Mixer Send to channel **"Delay"**, 100% Q.ty on both knobs
4) Reverb effect
and the instrument track sends to the channel **"Reverb"**

Now the 3 mixer channels we've used do not send to each other, so you can use them to have different EQ and compression for dry, delay and reverb. No need for the two additional channels
As a plus, we can save the delay and the reverb, and this setup, in a plugin preset!

This would also be a temporary workaround for #133, by putting the Mixer Send as last effect of a Sample Track, with  "Q.ty to Next FX" at 0%, so it doesn't send anything to Master.

Notes:
1 - it can become messy, as messy as a "goto", and I think we have to disable it in the Mixer for looping reasons.
2 - setting the channel mustn't imply there actually is one. Once the channel is set in the effect, it will not change without the user knowing and the effect will only send signal if there actually is a channel. Perhaps we can add some led that warns the user that there's no channel with the given number.

Let's say I saved the example above in a preset.
If I want to do it again, I'll have to load the preset, then create the channels and, if needed, change the settings.

**Comment by jasp00** [comment]
I know it has been suggested to rename FX-Mixer to Mixer, but [Mixer](https://github.com/LMMS/lmms/blob/master/include/Mixer.h) has a different meaning in LMMS already.

@DeRobyJ, you should upload a sample project to better grasp the problem, with the setup used as a workaround. As I understand, your proposal is translated into using some sort of internal channels, equivalent to pushing the "Send" buttons and turning the "Channel send amount" knobs. I do not see the change in functionality.

**Comment by DeRobyJ** [comment]
Take a look at this project: https://lmms.io/lsp/?action=show&file=10203
(I'm using RC2, it should be fine in 1.1.3 too)

As you see, I want to have separate EQ and  filter for dry, delay and reverb.
To do this, I need 5 channels!
If I were to have some synth like this on a bigger project, I think 3 channels are already enough.
Moreover, now that I've created that set up, if I want to use it in another project, I'll have to re-do all the effects, since they're stored in the mixer, not in the plugin preset.

With a Send utility (which, yes, is pretty similar to a send in the FX-Mixer), I can put delay and reverb on the plugin itself, and only do the EQ and filter in the FX-Mixer. That way I'll be able to store delay and reverb in the plugin preset itself. And I'll only use 3 channels of the mixer, not 5.

**Comment by tresf** [comment]
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.
