### ISSUE TITLE
Piano Roll Window Opens With Narrow Width

### ISSUE THREAD

**Issue by miketurn** [LMMS/lmms#3299]
Not sure if this is on purpose but when you open your first instance of the piano roll the window opens up with a very narrow default width, causing you to have to stretch it out to see everything.

**Comment by BaraMGB** [comment]
:1+

**Comment by mikobuntu** [comment]
Agreed . I think the default size should show all tools on the toolbar at least.

**Comment by tresf** [comment]
This was partially fixed in https://github.com/LMMS/lmms/issues/2288; fixed when loading a saved project but never addressed an empty project file.

**Comment by mikobuntu** [comment]
It seems if we use the same width as the Song_Editor window, it allows all tools and drop-down menus to be shown and also opening and closing the Piano_Roll looks aesthetically better ( as though someone cared  enough to align the Song_Editor and Piano_roll's dimensions at least )
