### ISSUE TITLE
Piano Roll - Vertical arrow cursor stuck

### ISSUE THREAD

**Issue by zonkmachine** [LMMS/lmms#3306]
![untitled](https://cloud.githubusercontent.com/assets/6368949/22370657/d00175f4-e492-11e6-8c04-3959e93d4a9e.png)

In the Piano Roll, if you move the cursor over the border to the Note Edit Area (Bottom...) the cursor is changed to an override cursor with vertical arrows. This is true for all the edit modes but the override cursor is only dropped when moving out of the area if you're in draw mode. For the other modes, the only way to drop the vertical arrows is to switch to draw mode.

The switch to vertical arrow happens here:
https://github.com/LMMS/lmms/blob/master/src/gui/editors/PianoRoll.cpp#L1987:L1988

**Comment by BaraMGB** [comment]
this would be fixed in https://github.com/LMMS/lmms/pull/3065
