### ISSUE TITLE
Empty VST tracks creates noise in playback

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#3308]
OS  : winXP sp3 & Windows 7
LMMS 1.1.90-RC2.2 & RC2.8

**Issue description:**
If an empty VST-container is inserted in song-editor, and playback initiated, the a weird humming noise is the result.
The noise disappears emediately, if you either loads a VST.dll, or simply if you mute the empty track
The empty VST-track, does not need any notes in it

**Recreate         :**
open default project
insert any notes in 3oc
play
That sound fine
Drag a VST in from sidebar
play
Now there are noise

**Comment by zonkmachine** [comment]
@grejppi has mad skillz at buffer noise.

**Comment by grejppi** [comment]
Could this be a case of not [zeroing](https://github.com/LMMS/lmms/blob/master/src/core/RemotePlugin.cpp#L299) the buffer [if there is no plugin present](https://github.com/LMMS/lmms/blob/master/src/core/RemotePlugin.cpp#L271)? I'm not familiar with the codebase anymore, sorry 😞

**Comment by zonkmachine** [comment]
I tried that and it didn't seem to do any difference. The word 'offset' popped up in my mind, but other than that I have no clues.

**Comment by Umcaruje** [comment]
I can confirm this on elementary os Loki, `stable-1.2` branch
