### ISSUE TITLE
Readme badges are inconsistent

### ISSUE THREAD

**Issue by Spekular** [LMMS/lmms#3314]
Every badge except for "chat on discord" has a single word on gray and then the rest on a colored BG. The discord badge breaks this trend by having two words on gray and one on colored. Even worse, it's inconsistent with "translate on transifex" which is right next to it.
![screenshot_2017-02-03_14-29-43](https://cloud.githubusercontent.com/assets/8918426/22593148/79e8202e-ea1d-11e6-8a0f-e2712eec9b5e.png)

Contrast between white text and green BG could perhaps use a boost as well, ie darker green.

**Comment by tresf** [comment]
Please file a bug against `shields.io`, this isn't our bug.

https://github.com/LMMS/lmms/edit/master/README.md

**Comment by Spekular** [comment]
Might be our bug, this shield appears to be custom.

**Comment by tresf** [comment]
@Spekular yes it is.  Closed via #3316.  Thanks!
