### ISSUE TITLE
Automatically assign each new track to a new Mixer Channel

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#3315]
Suggest an option in *Edit* that simply traverse all instruments in a project (SE+BBE) and adds them to FX-mixer-channels, with the names of the instrument in question.

**Comment by BaraMGB** [comment]
I would prefer an option in the settings for automatically assign a new track to a new fx channel in the mixer,  link the names and delete it by deleting track.

**Comment by musikBear** [comment]
@BaraMGB Yes that would also work, except for when the user changes names in song-editor, but your idea is good 👍

**Comment by BaraMGB** [comment]
> except for when the user changes names in song-editor

Therefore I wrote link the names. This behavior were near to other DAWs I know.

**Comment by follower** [comment]
FWIW "intruments" in the title is a typo. :)

Also, agree some form of this could be handy as I currently do it manually. (Although I didn't understand that's what "Add cascade FX-assignment option for all instruments in project" meant. :) Maybe change issue title to something like "Automatically assign each new track to a new FX Channel "?)

**Comment by musikBear** [comment]
@follower Yes your tittle mirrors BARAs better idea.
A cascade event takes everything form a data-structure loops through it, and process is according to a rule. Here it would have meant that every time a user clicked the option, all instruments would have been traversed, and the mixer would have been updated accordingly.
But BARAs idea is *better*, but perhaps also more difficult

**Comment by jasp00** [comment]
>automatically assign a new track to a new fx channel in the mixer, link the names and delete it by deleting track.

If you mean a new instrument track, it is done already: it is the FX tab.

**Comment by tresf** [comment]
> it is done already: it is the FX tab.

It's currently inaccessible by the mixer UI.

**Comment by jasp00** [comment]
>It's currently inaccessible by the mixer UI.

You may like to relocate the FX tab to the FX mixer. The FX channel number in the instrument would be unnecessary, because you could assign by using the "Send" buttons.

**Comment by musikBear** [comment]
Similar to 1215 Closing

**Comment by tresf** [comment]
#1215, not 1215. ;)
