### ISSUE TITLE
Missing icons for full/ windowed mode

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#3318]
OS  : winXP sp3
LMMS 1.1.90-RC2.8

**Issue description:**
The icons for toggle up/down in all components are missing, when the component is maximized

**Example          :**
![missingicons](https://cloud.githubusercontent.com/assets/6662066/22602055/ed8363a8-ea41-11e6-8dc5-41a65139c05b.JPG)

**Comment by zonkmachine** [comment]
I think it's this one and on purpose: https://github.com/LMMS/lmms/pull/2983

**Comment by tresf** [comment]
Won't-fix and not our bug per https://github.com/LMMS/lmms/issues/2611#issuecomment-193942180.
