### ISSUE TITLE
un-synchronized buttons for mute and solo

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#3319]
OS  : winXP sp3
LMMS 1.1.90-RC2.8

**Issue description:**
The solo and mute buttons in song-editor and FX-mixer are not synchronized, As you can see on the image. 

![solo_mutenotsynchronized](https://cloud.githubusercontent.com/assets/6662066/22602484/a62929fa-ea43-11e6-98ec-53e10540df50.jpg)

The instrument with active diodes, is ofcause routed to FX1

**Comment by Spekular** [comment]
They're not supposed to be

**Comment by zonkmachine** [comment]
The song editor buttons controls a track. The Mixer butons controls the mixer channel. If you assign one track per mixer channel it would seem logical but it really isn't.

**Comment by tresf** [comment]
> If you assign one track per mixer channel it would seem logical but it really isn't.

A track can only be assigned to a single mixer channel, so it's not an unreasonable request to have an "effective mute" enhancement down the road.  I'd argue we leave the LEDs out of sync and visually gray-out the track.
