### ISSUE TITLE
Automatically name peak controllers by source

### ISSUE THREAD

**Issue by diizy** [LMMS/lmms#332]
When you have many peak controllers in a project, it can become hard to tell them apart. Naming the controllers helps, but why wouldn't we do this for the user?

So when the user adds a peak controller to an FX chain, the peak controller in the controller rack would by default named by the instrument or FX channel where the effect is added to. 

Say you have an instrument track named "MyTripleosc", then add a peak controller to it's FX chain, the controller would automatically be named "MyTripleosc peak controller 1".  If you add another peak controller to the same instrument, just increment the number. The same if you add one to the FX mixer, the controller would be automatically named eg. "FX 01 peak controller 1".

Not sure if this should be implemented for 1.0.0... I think probably not because we should concentrate on bugfixes and such now. However if someone finds the free time, implementing this would probably be a pretty easy task... 

Btw, while we're at it, LFO controllers could also be named "LFO controller x" by default, instead of just "Controller x" as they currently are.

**Comment by SecondFlight** [comment]
`Btw, while we're at it, LFO controllers could also be named "LFO controller x" by default, instead of just "Controller x" as they currently are.`

Looks like this part at least has already been added at some point.

**Comment by SecondFlight** [comment]
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.
