### ISSUE TITLE
Fix/Map navigation keys in song editor

### ISSUE THREAD

**Issue by teknopaul** [LMMS/lmms#3320]
SongEditor::keyPressEvent() left and rigth don't work for me. Position just goes to the end of bar one and stays there.

I was able to map 

* Home - go to start
* End - go to end of song
* PgDn - advance one whole bar
* PgUp - back one bar

https://github.com/teknopaul/lmms/commit/8e2f06baabdf024f3acfcd69ff11a4e72552ca9c

Has this working.

**Comment by zonkmachine** [comment]
Cool, works like a charm!
I'm thinking about the behaviour when loop is on and you press to go to the end. You will now instantly be transferred to the start. It's perfectly logical but perhaps there is a better alternative, like stopping and moving position to one beat short of the end? ... idk.

Nice work. This is on your master branch so a link to the commit isn't the best thing here. To test this one does:

```
git remote add teknopaul https://github.com/teknopaul/lmms.git
git fetch teknopaul
git checkout teknopaul/master
```

I do know how it is to start out with Git/GitHub but it really pays off. What you want to do here is create separate branches for every separate job.
`master`
`groove`
`songeditkeys`

**Comment by tresf** [comment]
@teknopaul thanks.  As @zonkmachine mentioned, please cherry-pick this commit to a new branch and issue a pull request so it's not mixed with the other commits.

[Jump on discord](https://discord.gg/5kSc32Z) if you need help starting a new branch.

**Comment by teknopaul** [comment]
I could not work out how to convert a commit to a pull request.
Or how to create branch from a commit.
After fucking about with git for another few hours I got no where except to delete history which scares me. It made me have to merge my _own_ commits together to be able to save them when I'm only on one branch, my workspace should have nothing to merge just sequential commits.
So git fails for a single commit with no conflicts. :)

**Comment by tresf** [comment]
@teknopaul 

1. Using [your GitHub page](https://github.com/teknopaul/lmms), create a new branch.
![image](https://cloud.githubusercontent.com/assets/6345473/22615281/92091108-ea5f-11e6-8f6f-cf92c3d8aea4.png)
1. Pull down your new branch
   ```bash
   git pull
   ```
1. Checkout your new branch
   ```bash
   git checkout foo
   ```
1. Rewind the new branch back to what lmms is without your changes
   ```bash
   git reset --hard head 421243a # Made automation slopes more distinguishable
   ```
1. Cherry-pick your keyPress commit
   ```bash
   git cherry-pick 8e2f06b
   ```
1. Push your changes
   ```bash
   git push origin foo
   ```
1. Create a [new pull request with only the changes from the `foo` branch](https://github.com/LMMS/lmms/compare/foo...teknopaul:master)

**Comment by teknopaul** [comment]
Cheers for the tip,

I'm still recovering form a git push having battered my code with 
=====================
>>>>>>>>>>>>>>>>>>
and sha hashes.

:)

**Comment by zonkmachine** [comment]
> and sha hashes.

Ah, those ones!

I've pushed what I've got from your stuff to a branch here:
https://github.com/zonkmachine/lmms/tree/songeditkeys
It's the key fixes without the groove stuff.

**Comment by tresf** [comment]
> I'm still recovering form a git push having battered my code with

Looks like @zonkmachine created a new branch for this code.  The only downside to that is you won't be able to make any changes to it... @zonkmachine will have to.

@zonkmachine FYI, in rare occurrences, I'll ask the developer to grant me access to their personal GitHub repository so that we can work together where we both have write access.  This may be a good candidate.  If @teknopaul is as ambitious, we could really benefit from having him comfortable with fixing his own merge conflicts. 👍

**Comment by zonkmachine** [comment]
> Looks like @zonkmachine created a new branch for this code. The only downside to that is you won't be able to make any changes to it... @zonkmachine will have to.

Well, I meant so he can branch it. The commit still reads technopaul and I didn't issue a pull request. It's all a bit shady from here on... :)

**Comment by tresf** [comment]
> Well, I meant so he can branch it. 

I'm not sure that simplifies anything and now you've allocated a new branch.  General rule of thumb... 

Two dev (commit access) collaborating:
 * Create a `lmms/lmms/tree/foo`

Non-dev collaborating:
 * Lives in `johndoe/lmms/tree/foo`

Non-devs can grant security on their personal repos, so this encourages `johndoe` to learn the forking and branching process and also allows someone like @zonkmachine or @tresf to step in and help cleanup `johndoe` without owning commits we didn't author.

**Comment by zonkmachine** [comment]
Should I just delete that branch then? :-o -?

**Comment by tresf** [comment]
@zonkmachine yes, I feel you should.  His commit ID from the original post is still accessible from GitHub, it's just a matter of @teknopaul following the standard process for making his own branch, which I think several people would be happy to help him with per:

> [Jump on discord](https://discord.gg/5kSc32Z) if you need help starting a new branch.

**Comment by zonkmachine** [comment]
> yes, I feel you should

Fixed...

**Comment by BaraMGB** [comment]
Is this related to this https://github.com/LMMS/lmms/issues/3148?

**Comment by zonkmachine** [comment]
> Is this related to this #3148?

No.
