### ISSUE TITLE
LMMS does not build with Qt5

### ISSUE THREAD

**Issue by FrantaK** [LMMS/lmms#3330]
I have followed exactly the Instructions on GitHUB
(there is an error in stating to run cmake from inside the build directory - but this only aside)

running cmake like this:
```bash
lmms# cmake -DCMAKE_INSTALL_PREFIX=/opt -DWANT_QT5=ON -DCMAKE_PREFIX_PATH=/opt/Qt/5.8/
```
leads to:
```
CMake Error at /usr/share/cmake-3.5/Modules/FindQt4.cmake:1326 (message):
  Found unsuitable Qt version "5.5.1" from /usr/bin/qmake, this code requires
  Qt 4.x

qmake is a link to qtchooser  and the environment variable QT_SELECT
is set to QT_SELECT=5
```

**Comment by tresf** [comment]
@FrantaK I think you just need to delete your `<buildir>/CMakeCache.txt` and re-run that same command.  It thinks you want Qt4 still, likely leftover from a previous configure.

```bash
rm CMakeCache.txt
cmake -DCMAKE_INSTALL_PREFIX=/opt -DWANT_QT5=ON -DCMAKE_PREFIX_PATH=/opt/Qt/5.8/
```

**Comment by FrantaK** [comment]
Hi. thanks for your comment,
this was not it:

CMake Error at /usr/share/cmake-3.5/Modules/FindQt4.cmake:1326 (message):
  Found unsuitable Qt version "5.8.0" from /opt/Qt/5.8/gcc_64/bin/qmake, this
  code requires Qt 4.x

But there is an improvement. CMake finds the correct installed Qt version

**Comment by Lukas-W** [comment]
Would you mind posting the output of `cmake -L` from your build directory?

**Comment by Lukas-W** [comment]
Closing as @FrantaK hasn't replied yet, so I'm assuming this issue's been resolved.
