### ISSUE TITLE
Multitap Echo (lmms plugin) Broken?

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#3332]
OS  : winXP sp3
LMMS 1.1.90-RC2.8

**Issue description:**
I cant get head or tail out of this plugin. To me it sounds like it makes n (determined by the scrollable number) fast extra hits, infront of a somewhat  'normal' note
If two notes are placed in different piano-roll pos, in same bar, both notes 'echos' will be played at same time? 
I actually expected some kind of frequency influenced arpeggio
Am i or the plugin broken 

Plugin used : 3oc/ bell.xpf

**Comment by DeRobyJ** [comment]
Sorry I can't understand what's the problem.
Could you please upload an example?

**Comment by musikBear** [comment]
@DeRobyJ It properly because i dont know what a multi-tap-echo should do :P 
I will make a sound-file on sC

**Comment by DeRobyJ** [comment]
Once the base note has played, each vertical bar is "one echo", defined with volume and cutoff.
So if you have 10 bars you'll have 1 + 10 notes

**Comment by musikBear** [comment]
@DeRobyJ Sorry to have taken your time- *Now* it makes sense. I saw the two panels as left/right :p 
Perhaps a legend on the panels, or just tool-tips?

**Comment by DeRobyJ** [comment]
Mmm I think I understood it because of the values on the left.
The top graph has negative numbers, the seem dB, while the bottom has a logarithmic scale from 20 to 20k, which are of course frequencies.

Also you can right click on the last knob and it says "lowpass stages".
Yea it needs some explanation
