### ISSUE TITLE
**Equalizer** has flicker default 

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#3336]
OS  : winXP sp3
LMMS 1.1.90-RC2.8

**Issue description:**
If the button in the green circle is active, all indicators in the sliders (red arrow) flickers in both idle, and playback

![eq flutter](https://cloud.githubusercontent.com/assets/6662066/22704061/ab0418ec-ed66-11e6-8091-0fb947842d0b.JPG)

**Recreate         :**
Insert **Equalizer** in master in an empty project, and toggle the *green circled* button. The indicators will flicker depending on on/of of the *green circled* button
Also, there are not any tool-tips, on anything.

**Comment by Umcaruje** [comment]
This is going to be fixed in #3030

**Comment by BaraMGB** [comment]
>This is fixed with #3030

Exept the tool tips.

**Comment by Umcaruje** [comment]
>Exept the tool tips.

I didn't even read that sentence lol

**Comment by zonkmachine** [comment]
Fixed in #3030

As for the tool-tips that should be in a 'tool-tip'/'What's this' messages meta-post .
LIke here: #896
