### ISSUE TITLE
crossover  equalizer: distortion from dials

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#3339]
RC.2.8 win 32
This image shows random notes with automation of the 1/2-dial in crossover equalizer 
![crossoverbuttons](https://cloud.githubusercontent.com/assets/6662066/22795120/cbabdf72-eef5-11e6-988c-82fc7c85f4f7.JPG)
Listen to this recording
https://soundcloud.com/musikbear/crossoverdials
The distorting are where the slope of the automation-track makes the dial turn
The clean sound is on the plateaus
Can that be fixed?

**Comment by michaelgregorius** [comment]
Should be fixed with #3343.

**Comment by zonkmachine** [comment]
Closed in https://github.com/LMMS/lmms/pull/3343
