### ISSUE TITLE
Should we have a bundle format?

### ISSUE THREAD

**Issue by tonychee7000** [LMMS/lmms#3340]
If some projects have some resources (such as audio file), could we have a format that include resource files?

**Comment by musikBear** [comment]
Duplicate from @908 **'Export format'**
I believe others as well

**Comment by zonkmachine** [comment]
@musikBear Fixed your link. I always use the preview function and test the links first. @ is for alerting a GitHub user and there is a user named 908.

**Comment by tresf** [comment]
Closing as duplicate of #1257
