### ISSUE TITLE
Tab FUNC / New arpeggio : several issues

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#3342]
OS  : winXP sp3
LMMS 1.1.90-RC2.8

**Issue description:**
Arpeggio is mixed up, and has several errors

**Recreate         :**
New project
insert a c-maj chord with 2 bar length notes
FUNC-TAB/ ARP
Set:
* GATE 10%
* TIME synch to ½ note
* Rest default

play
FREE works as SYNC should work
-All 3 notes in the chord is played simultaneous 
Mark all notes and move them ½ bar fwd
play
There are now one extra hit ½ a bar from the end of the notes
If you move them 1 bar, There are now one extra hit as the playhead starts second cycle at 0

change to SORT
play
One of the notes will not play arpeggio, but plays one long note, then 2 notes play shortly, then 1 note

Change to SYNC
play
first a short all-notes artefact occur. Then one note play a long note, then all notes play simultaneous

Could it bee that a wrong commit has been used for RC?

---
Do anyone want a file?

**Comment by zonkmachine** [comment]
I don't think there is a drastic difference from 1.1.3 .

> There are now one extra hit as the playhead starts second cycle at 0

Thanks! I knew there was an extra hit in there somewhere but I thought it was the master note sounding with the arpeggio note. It's an extra trailing note that comes back as a ghost note when looping.

**Comment by zonkmachine** [comment]
> There are now one extra hit as the playhead starts second cycle at 0

I think I nailed this one at least but the arpeggio sync problems is a bit tricky.

**Comment by musikBear** [comment]
> I think I nailed this one at least 

Good job! Over time i think it would make sense to re-furbish arpeggio. Options like in Oatmeal and Synth, where different delays on selected notes are possible, would open for amazing new sound.

> but the arpeggio sync problems are a bit tricky.

Believe the arp has been bugged from day one, has always only had success with the *sorted* setting

**Comment by zonkmachine** [comment]
Fixed in #3858  #3867
