### ISSUE TITLE
Impossible to change the track name when the instrument window is open 

### ISSUE THREAD

**Issue by Umcaruje** [LMMS/lmms#3353]
![gifrecord_2017-02-13_225132](https://cloud.githubusercontent.com/assets/6282045/22905049/126b1530-f23f-11e6-819e-3c2aac55633b.gif)

When double clicking the track label button that is active (window open), it is impossible to change the name of the track. The QLineEdit appears for a very short time, but double clicking will just close and open the window again.

CC @BaraMGB

**Comment by BaraMGB** [comment]
Can not reproduce here. But, you can rename by right click too.

**Comment by Umcaruje** [comment]
Weird, are you on Qt5 or Qt4 @BaraMGB?

**Comment by BaraMGB** [comment]
Okay, can reproduce on current master. But can't on RC2. Something is happend in the meantime.

**Comment by BaraMGB** [comment]
I guess it was me with this: https://github.com/LMMS/lmms/commit/c5aa22663e555524d34813dd00bf350e5d5ba33b

**Comment by musikBear** [comment]
FYI RC 2.8 windows x32 was fine
