### ISSUE TITLE
Copies of  shapes in automation are wrong

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#3359]
OS  : winXP sp3
LMMS 1.1.90-RC2.8

**Issue description:**
Graphs/  shapes in automation are wrong, after they have been copied.

**Example          :**
![copyautomarionerror](https://cloud.githubusercontent.com/assets/6662066/22985894/2cf08c52-f3aa-11e6-80c7-9d289659e925.JPG)
**Recreate         :**
New project
* drag a panning-dial into automation-track
* Open track
* insert automation like in the picture' top part
* Close editor
* ctrl+drag-copy block to other pos.
The result is like the second part of the picture
A similar issue exists for all 3 shapes, but in linear the bug will only apear if a *declining* pattern is drawn.

Bug is logical (no dial control), not just graphical

**Comment by Spekular** [comment]
The controller/value gets disconnected afaik

**Comment by tresf** [comment]
> after they have been copied.

Copied or pasted?

**Comment by musikBear** [comment]
@tresf the error is in the new copies of cause,  so pasted
@Spekular that was ifaik fixed in RC2.2, i used the same automation-pattern several times and even inverted it so one went up, and one went down, but as mirrored copies 
And the connection is not lost. As i wrote the copy is fine if it only has linear inclining shape

**Comment by musikBear** [comment]
Here is the proof for this working earlier
![copyautomarionerrornotin119_](https://cloud.githubusercontent.com/assets/6662066/23063892/3db48fb6-f50d-11e6-9acd-041ae8812ecc.JPG)
I have used the same block-pattern as above 
(1) is the orr. 
(2) is a copy
(3) is the *copy* flipped vertically
(4) is the copy flipped horizontally
The release-version can be seen in the ring 

So this bug appeared between 1.1.9 and RC2

**Comment by musikBear** [comment]
A rather important thing is that this erroneous behaviour was introduced **before** @lukas-w made his 3382 read-back enhancement for automation.
It cant be the 3382 enhancement that caused this new bug.

**Comment by tukkek** [comment]
I can confirm this, here's what happens when I try to `Ctrl`-drag-copy an automation block:

![screenshot_20180228_175119](https://user-images.githubusercontent.com/3819826/36812479-151ace14-1cb0-11e8-9009-36d087cf4cfd.png)

As stated before this is not just a visual bug: the new automation block does not sound as intended.

**Comment by tukkek** [comment]
Adding to my last note: as soon as I drag the right control to the new block, it suddenly fixes itself! That was a (nice) surprise :D

![screenshot_20180228_175523](https://user-images.githubusercontent.com/3819826/36812654-a67e5a56-1cb0-11e8-93aa-ef92eb228c25.png)

Sounds like it should too! I'm using 1.2.0-rc5.

**Comment by tresf** [comment]
@tukkek your issue sound like #3781.

**Comment by musikBear** [comment]
@tukkek indeed re-conecting the blocks, does re-establish the *functionality*. This also in coherence with my comment here https://github.com/LMMS/lmms/issues/3781#issuecomment-331671169
Re-connecting looks like working the same way, as manually adding the key in the mmp.
Before reconnect 
![rc5automations](https://user-images.githubusercontent.com/6662066/36846686-e6441cb0-1d5b-11e8-8f0a-49514f7da984.JPG)
After reconnect:
![rc5automationsrecon](https://user-images.githubusercontent.com/6662066/36846764-36112f4e-1d5c-11e8-80d3-5d037970f107.JPG)
