### ISSUE TITLE
LMMS doesn't free memory

### ISSUE THREAD

**Issue by zonkmachine** [LMMS/lmms#3366]
If you load a bunch of large samples and then delete them from the project, the memory isn't freed up. If you once more load some other big files they will use this earlier acquired memory. The same is true if I copy paste a whole lot of notes in the piano roll, enough to put a 'dent' in the used memory, and then deletes the track.
I don't know if it technically falls under memory leak as the memory is still usable but that's what it looks like. You need to shut lmms down in order to free up the memory if you've been using large samples. This worked in 1.1.3

**Comment by softrabbit** [comment]
I wonder if this is due to "[All of this causes some waste in memory, but here's the thing... I don't
really care about that. ](https://github.com/LMMS/lmms/pull/1088#issuecomment-53979218)", i.e. a feature of the memory manager?

**Comment by zonkmachine** [comment]
> a feature of the memory manager?


Bisected. 

Last good commit is the one before the memory manager was introduced.
6f963159dfaa9c2372486c0634af00ab83737a27


Next comes the first two commits that introduce the memory manager but which crashes on launch so they can't be tested. 9c25be1bde33247a8fb0c435950864e1d8345e51 75770b4d2e23e3171cf820894b32589135f66889

9972cb3d4df800e5dd48d638ec972f65fc2cd3e8 compiles and runs but crashes a lot on deleting a sample track but when it doesn't crash it also doesn't free memory so it's the first confirmed bad commit.

To get the changes that introduced this bug in one dump:
```
git diff 6f963159dfaa9c2372486c0634af00ab83737a27 9972cb3d4df800e5dd48d638ec972f65fc2cd3e8
```

**Comment by zonkmachine** [comment]
I think it's just not implemented. If it would be I'd expect this function to take care of it:
https://github.com/LMMS/lmms/blob/master/src/core/MemoryManager.cpp#L208:L221

**Comment by musikBear** [comment]
> I don't know if it technically falls under memory leak

I would say 'no', if the allocated memory is useable for new samples, then the memory is not leaked for the active program (lmms) but it is 'bogarded' from other running programs. I guess you could call lmms a memory-hoader :p 
> I suspect this is not just with samples.

Do you mean that something like adding a preset, then removing it, also keep previous allocated memory occupied by lmms?

**Comment by zonkmachine** [comment]
> Do you mean that something like adding a preset, then removing it, also keep previous allocated memory occupied by lmms?

Yes. It looks like this is the case but I need to probe more into it.

**Comment by musikBear** [comment]
> This worked in 1.1.3

Is of cause very important -Good find!

**Comment by PhysSong** [comment]
I think we need to improve memory manager. I will open a separate issue if needed.

**Comment by PhysSong** [comment]
How about creating new menu "Free unused memory"?

**Comment by musikBear** [comment]
@PhysSong 
> How about creating new menu "Free unused memory"?

Noo -memory is not something the user should maintain, but if you can find a way to do *that* as a menu item, i would say, that it could 'just' be a thing that was done in connection to some active user-action, f.i. *save-project*

**Comment by Umcaruje** [comment]
I agree with @musikBear users should not worry about this at all, it's bad UX

**Comment by lukas-w** [comment]
Closing since MemoryManager was replaced by rpmalloc via #3873.
