### ISSUE TITLE
Reimplement Borg Jr with Soundpipe

### ISSUE THREAD

**Issue by PaulBatchelor** [LMMS/lmms#3367]
Was very sad to see #2668 closed on account of technical difficulties with STK. I would very much like to collaborate with @zonkmachine and revamp their Borg using Soundpipe (resistance is futile?)

I haven't looked closely at the implementation of the STK instrument Borg Jr is based on, but it seems to be more or less a simple FM pair. I feel pretty confident that the functionality could be duplicated using code imported from Soundpipe.

Taking it a step further, it would also be feasible to add and improve the current implementation. 

Some ideas I had could be:
- More oscillators with a routing matrix
- Feedback
- More comprehensive LFO control
- Envelopes
- Keyboard scaling
- Other effects?

**Comment by zonkmachine** [comment]
Cool. I more closed it temporarily as there are many other PR's that needs attention. It's not technical difficulties as much as a competence issue I'm afraid. As we already have STK in there but you can't really add other STK based units without solving the issue with thread safety I think that needs solving anyway. It would probably not be that hard for someone else. ;)
I didn't have a specific idea to make an FM synth but just swapped out the Tubular Bells in Mallets for one of the other FM synths and I liked it. I'm not against using Soundpipe but my focus right now is just fixing everything related to the 1.2 release.

> * More oscillators with a routing matrix
> * Feedback
> * More comprehensive LFO control
> * Envelopes

Yes!

> * Keyboard scaling

I think there is an issue for this to be implemented for the Instrument Sound Shaping. Or if not there should be.

> * Other effects?

I think just adding a chorus in there or tweaking the built-in delay line (spread) to pan left/right, a sort of 'true' pan as it now only delays one side and it essentially pans the sound (don't know which as my speakers seem to have switched sides). Add a switch to link the delay to the pan? I want this in Mallets too.

**Comment by PaulBatchelor** [comment]
@zonkmachine ah, I see. Well, in that case carry on. I'll close this for now then. Thanks for the response!
