### ISSUE TITLE
Envelope, filters & effects ignored when playing a soloed pattern from piano roll

### ISSUE THREAD

**Issue by Umcaruje** [LMMS/lmms#3379]
Here's a project file: [wtf.mmpz.zip](https://github.com/LMMS/lmms/files/793788/wtf.mmpz.zip)

How I made the project:
1. Change the default TripleOscillator to all squares, just to give us more harmonics to work with
1. Apply an envelope + a filter (I went with a lowpass and a short volume decay)
1. Apply an effect (I used calf multichorus)
1. Add a new pattern with some notes on the instrument

To reproduce the bug:
1. Play the pattern from the piano roll
1. Solo out the TripleOscilaltor track
1. You should hear the change in sound and the envelopes, filters and effects ignored.

This does not exist in 1.1.3. because the pattern goes completely silent when the track is solo'd
OS and version: elementary os Loki x64, master branch.

Possibly related bugs: #1110, #1947

**Comment by musikBear** [comment]
confirm for win32 on xp

**Comment by PhysSong** [comment]
It occurs when the tco index of the pattern is not greater than the number of BB tracks. I think this is a part of #1947.
