### ISSUE TITLE
[Automation Editor] GUI Status for 'Tension' knob should look Active/Inactive depending which mode is selected.

### ISSUE THREAD

**Issue by mikobuntu** [LMMS/lmms#3380]
The Tension knob is only used by ( logically ) the 'Cubic Hermite' mode , I suggest a way to make the knob look inactive when the other 2 automation modes are chosen would be to change the colour from the green to a grey shade.
![tensionknob](https://cloud.githubusercontent.com/assets/335217/23238698/141fc4a2-f95b-11e6-8281-e5bf08d9ffd9.png) [ Ignore selected mode, this is just a quick edited image to show how the Active vs Inactive Tension knob might look ]

( By the way guys the new look for both Piano_roll and Automation_Editor' background grids are amazing , this is one of the most clearest in any DAW that I have used )

**Comment by RebeccaDeField** [comment]
Visually, I have no problem with this, but you will need some feedback from people that use this function on whether or not it would be useful to them.

I also want to note that we're not using any gray knobs anywhere else in the program, and although I think it's pretty clear in your example that the knob is inactive, I'm not sure what that would take from a coding perspective.

**Comment by Umcaruje** [comment]
well, we could either draw a gray overlay over the knob or make a new inacive knob specifically for this purpose.

**Comment by musikBear** [comment]
we could set it *not-visible* in the two irrelevant modes?
That way it would appear as a additional option when the 'Cubic Hermite' mode was selected

**Comment by BaraMGB** [comment]
>we could set it not-visible in the two irrelevant modes?
That way it would appear as a additional option when the 'Cubic Hermite' mode was selected

This would be the easiest way to implement this.

**Comment by Spekular** [comment]
I don't think hiding the knob entirely is a good idea. AFAIK no other editor does anything similar, and it feels too abrupt to me.

**Comment by BaraMGB** [comment]
Okay, I will look into it. Perhaps there's an easy way to grey out the knob.

**Comment by Umcaruje** [comment]
>Perhaps there's an easy way to grey out the knob.

Painting a transparent grey rounded rectangle that would look like a circle should work the easiest tbh

**Comment by jasp00** [comment]
If you add a pixmap for inactive knobs, you may customize the look.

**Comment by zonkmachine** [comment]
Fixed in https://github.com/LMMS/lmms/pull/5549
