### ISSUE TITLE
sfxr - buffer noise

### ISSUE THREAD

**Issue by zonkmachine** [LMMS/lmms#3383]
The usual buffer stuff. There is noise with other instruments with the decay if using the general envelope (ENV/LFO).

_Example. May get a bit loud..._
[sfxrbuffer.mmp.zip](https://github.com/LMMS/lmms/files/798365/sfxrbuffer.mmp.zip)

**Comment by PaulBatchelor** [comment]
When you mute bitinvader after hitting play, you get a buzz, so something is getting "stuck" in the buffer.

**Comment by zonkmachine** [comment]
I don't get any buzz with bitinvader (or sfxr) when muting on/off. With or without envelope and/or other instruments around.

**Comment by PhysSong** [comment]
If the R value for sfxr is large, you will get a buzz regardless of its settings. Can be reproduced without B&B.

**Comment by zonkmachine** [comment]
> If the R value for sfxr is large, you will get a buzz regardless of its settings

Yes, I seem to have mistaken. It's not in relation to other instruments. At least I can't reproduce that.
