### ISSUE TITLE
Things necessary to make LMMS really usable on MacOS

### ISSUE THREAD

**Issue by algorev** [LMMS/lmms#3384]
Just a list to made as an user to put some priorities and bump some things:
1. Fix SF2Player support: See #649.
2. Fix ZynAddSubFX support: See #703.
(3. Add .vst support for VeStige: Not as important.)
I think the first two aforementioned issues should deserve special attention for MacOS LMMS, since the choice of instruments provided with LMMS is rather poor, and that SF2 and ZynAddSubFX are truly the most powerful instruments that make it possible to make music without using VSTs.

**Comment by Spekular** [comment]
"Bumping" is generally not useful. I also think we mostly know what users want or would prioritize, but devs are the ones who decide what they think they can tackle and want to work on.

**Comment by Umcaruje** [comment]
These are very well known issues, and we needn't be reminded what is the priority, but a lack of Mac developers is really what's stopping these issues from being resolved.

**Comment by tresf** [comment]
@algorev also double-click project opening per (https://github.com/LMMS/lmms/pull/3219)

**Comment by jasp00** [comment]
Assuming there is a will, I wonder what prevents @algorev (or any other macOS user) becoming a developer.

**Comment by algorev** [comment]
A very simple reason: qt. I don't have admin rights on my Mac, but I installed the CLT to be able to develop on the machine, but qt needs xcode, and xcode, for some reason, needs an agreement to be agreed, and because of a very stupid design choice the way apple loves them, this agreement needs the admin password to be agreed. At least, that's the case for qt5. If it is any different for qt4, please tell me. Anyway, thanks for asking this question, and I hope my answer was good.

**Comment by tresf** [comment]
> for some reason, needs an agreement to be agreed, and because of a very stupid design choice the way apple loves them, this agreement needs the admin password to be agreed

The Xcode command line tools are installed system-wide, unfortunately.  This is how most compilers are installed .  I'm unaware of a way around this.

> qt needs xcode

Compiling in general require XCode.

> If it is any different for qt4, please tell me

It is not.

>  I hope my answer was good.

It's fine, but it's not something we can do to help.  You'll need to get someone to enter the password. 🍻

**Comment by algorev** [comment]
No, because the CLT don't need admin rights to be installed. Anyway, I just found out that maybe only qt5 needed xcode.

**Comment by tresf** [comment]
> only qt5 needed xcode.

Wrong.  For Clang compiler, you need XCode unless you get it elsewhere, which is not trivial.  I am the sole author and maintainer of the Mac tutorial.  I wrote it for Qt4 and now maintain it for Qt5.  [XCode is needed](https://github.com/LMMS/lmms/wiki/Compiling-lmms-(Apple)#dependencies).

**Comment by tresf** [comment]
> because the CLT don't need admin rights to be installed.

What is CLT and how is it relevant to this discussion?

**Comment by tresf** [comment]
@algorev FYI, the `lldb` command (Clang's equivalent of `gdb`) used for debugging and getting a stack-track requires the administrator password as well on Mac.

**Comment by algorev** [comment]
Anyway, that's not the point. What I wanted to prove was that there are
people who'd want to help but can't because of reasons they can't work
around, so please, don't be too eager to call them "lazy" or whatever it
may be.

**Comment by tresf** [comment]
> What I wanted to prove was that there are people who'd want to help but can't because of reasons they can't work around

There are also people who cannot afford a Mac which seems to be a larger obstacle than a password.

I don't recall anyone using the word "lazy".  If you can work out your own issues, there's plenty of room for help.  I put more information in #649.  If you know more, please chime in.

**Comment by jasp00** [comment]
Learners are not lazy, they just do not know where to start. If we do not know the problem, we cannot help. So, let us try to solve your case.

I believe CLT means "Command Line Tools". Among these tools there should be a compiler. @algorev, are you able to produce an executable? If you can, there is a chance to build LMMS without an admin password; this is possible on Linux. It is not easy, we may hit an admin wall, there is a lot of compilation, but there is a way. Do you want to try?

**Comment by algorev** [comment]
Yes, I do.

**Comment by jasp00** [comment]
Fine, we will advance slowly because of time constraints of mine; the same excuse is right for you.

First, we need the tool to configure LMMS build environment: `cmake`. Install CMake. If you cannot, download the source code of a stable version and extract to a directory. Tell me when you are done.

**Comment by algorev** [comment]
It's just brew install cmake, but it is 10 pm in my country, so i must go to bed. I'll manage to do something, i'm already on my way.
