### ISSUE TITLE
track focus stays after closing the piano roll window.

### ISSUE THREAD

**Issue by gnudles** [LMMS/lmms#3388]
when you double click on a track sample to open the piano roll, it is drawn with a green border around it.
when you close the piano roll, the border stays.. I think it should disappear...

![screenshot](https://cloud.githubusercontent.com/assets/12647462/23403166/8d037e80-fdb7-11e6-9208-9ffcf375bf08.png)

But maybe I'm wrong because if you then open the piano roll from the main toolbar, it opens the last thing you worked on...

**Comment by musikBear** [comment]
No no ! That is highly beneficial 
That shows you what block you just have been tampering with, it it then sounds horrid, you can easily reopen that block, because it is still visible marked.
That should not change!

**Comment by BaraMGB** [comment]
I guess we can close this. If you disagree please ask for reopening.
