### ISSUE TITLE
Scan for native LMMS plugins in home lmms directory

### ISSUE THREAD

**Issue by PaulBatchelor** [LMMS/lmms#3392]
Noticed that lmms folder created in $HOME has a "plugins" folder for ladspa and vst plugins. It would be great if there was also a folder for native LMMS plugins. Right now, the only place to copy such plugins is to /usr/local/lib/lmms, which requires sudo/root permissions.

**Comment by PaulBatchelor** [comment]
LMMS already has an environment variable defined here: https://github.com/LMMS/lmms/blob/master/src/core/PluginFactory.cpp#L71

It ain't working for me yet though...

**Comment by tresf** [comment]
> It ain't working for me yet though...

Me neither, but you may be the first to attempt this since @Lukas-W wrote the class.  Pinging him... :)

**Comment by PaulBatchelor** [comment]
I think I fixed it! On Linux at least. Will make a PR in a few minutes.
