### ISSUE TITLE
import/export native pattern data

### ISSUE THREAD

**Issue by PaulBatchelor** [LMMS/lmms#3393]
What is the feasibility with regards to importing/exporting LMMS pattern data?

I would imagine it would save the data in a similar way that it is represented inside the mmpz format (last I checked, this was some sort of XML, but I could be wrong here). It could then be loaded similarly to how you load a project. 

My thinking here is that this could be a good step forward towards using external programs to generate pattern data, which would be a huge win in my opinion.

**Comment by jasp00** [comment]
>What is the feasibility with regards to importing/exporting LMMS pattern data?

It depends on what you want to do. LMMS needs to export and import data to copy between program instances.

**Comment by PaulBatchelor** [comment]
I want to write programs to generate patterns for me.

**Comment by musikBear** [comment]
> programs to generate pattern data, which would be a huge win in my opinion.

With the term *pattern data* you @PaulBatchelor mean notes, right?
Eg program generated music.
I had an exchanges of view-points on this, with an user that wanted that, some weeks ago. I must say, im against it. Computer generated midi-patterns are.. idk ..'wrong' 
I like that programs can aid creativity, **just** like lmms, for whitc without, i personally never would have made any music -ever!
But having the program making the creative parts as well..?

**Comment by jasp00** [comment]
>I want to write programs to generate patterns for me.

If your program is GPL-compatible (MIT, BSD, etc.) or only used by you, it can be integrated as a tool plug-in. For other cases, you may import data through the file browser, drag and drop and the like. Fixes may be needed, but the feature is certainly feasible.
