### ISSUE TITLE
Multitrack recording button and countdown clock

### ISSUE THREAD

**Issue by Gabrielxd195** [LMMS/lmms#3394]
Hello!. My name is Gabriel Lopez, and I am Latin from Dominican Republic, so I do not speak English and everything I wrote is translated, so forgive my spelling mistakes. First of all I would like to tell you that I am not a developer and that I am starting to get into music, with lmms I am taking my first steps and that is why I want to give two of many ideas that I have to improve linux multimedia studio, lmms is versatile and powerful but le There are many things to improve and add, such as: The button of simultaneous recording of multiple tracks and the countdown clock at the time of recording. 
![boton multigrabacion actual](https://cloud.githubusercontent.com/assets/26127693/23489277/c2b4fd36-fec7-11e6-9364-cb498ee68834.png)
 That's the current interface, with the two useless recording buttons. (These images edit them with gimp, so forgive the mistakes)

![boton de grabacion multipista](https://cloud.githubusercontent.com/assets/26127693/23490167/20bfb222-fecd-11e6-9968-edc8c8ff2a61.png)
And this is the interface suggested by me. As in the case of ardour or pro tools, the buttons on the tracks marked with the record button on (red button) are recording simultaneously, while the other disabled instruments (gray button) do not record. The recording buttons of the song editor when pressed, give the command to record on the marked tracks (red button).

![cuenta regresiva actual](https://cloud.githubusercontent.com/assets/26127693/23490327/61b6adb6-fece-11e6-953f-a42a5550498f.png)
As far as I've seen, lmms does not have a multitrack record button, but it also does not have a countdown (the 4 seconds before recording) at the moment of pressing the record button on the tracks, causing it to lose rhythm and time. So I suggest a clock that marks the allocated seconds before recording.
![reloj de conteo regresivo](https://cloud.githubusercontent.com/assets/26127693/23490367/b04031be-fece-11e6-9b32-d22e753c4d9e.png)

**Comment by musikBear** [comment]
You can already do both in lmms

In respect to: 
* selective export: 
mute the tracks you do not want in your export
LMMS will also (shortly) allow you to export one track at a time, to separate sound-files 

* countdown
insert one-bar of sharp ticks before the part you plan to record, then you can listen for the ticks and be prepared to play on your keyboard, when the fourth tick rings out.
A countdown clock has also been proposed before, btw

**Comment by Gabrielxd195** [comment]
As I said initially. I do not speak the English, am Latin. Then I ask for pardon for the mistakes of spelling, maybe I was not very clear, but the images say everything. Never, mensione the "export" or " selective export ", use these options before (and it is very useful certainly), which I wanted to say is in the image edited with gimp, that is very clear, my Idea (if perhaps it is valid) must assign a button of recording in the tracks and enable the buttons of recording of the publisher of song, when the buttons of recording of the tracks are activated (in red), then they press the button of recording of the publisher of Song, initiating a simultaneous recording of several tracks with his assigned instruments. I suppose that it would be useful to have this option, this would be an advance.

**Comment by jasp00** [comment]
These are not bad ideas. Master branch does not have the recording buttons in the song editor. The buttons should be brought back and recording should be allowed from song editor and BB editor. However, I would not add the suggested per-track buttons because enabling MIDI input should be enough concerning GUI.

**Comment by Animtim** [comment]
I support this idea of multi-track recording interface as Gabrielxd195 suggests.
It would give a good base for live performance workflow. This way, one could record live some instruments in the pattern editor, while other instruments stay "locked", and quickly select what needs to be recorded. Also, one could play on top of a pattern on the same instrument without editing the pattern, while recording automations or another instrument. It gives all kinds of creative possibilities.

For now in 1.2.0, the situation about recording is pretty bad. It is only available from single piano-roll pattern editors, and can not be activated while playing... and it's not possible to record automation at all?
Those are quite some regressions. I guess that was needed because of deep changes, but I really hope things will move soon on this topic.

**Comment by jasp00** [comment]
Anyone volunteering to implement this feature is welcome, no matter your skill. Just raise your hand and ask for guidance.

**Comment by liushuyu** [comment]
>Anyone volunteering to implement this feature is welcome, no matter your skill. Just raise your hand and ask for guidance.

I would like to try, but of course I can't be full-time on this

**Comment by jasp00** [comment]
>I would like to try, but of course I can't be full-time on this

Take your time. Do you know how to start?

**Comment by liushuyu** [comment]
>Take your time. Do you know how to start?

TBH, I don't know much about this part of LMMS, although I have tried to find where to start, but because of lacking documentation, I really don't have idea. Sorry

**Comment by Gabrielxd195** [comment]
You speak Spanish ?, I ask for your name and because you appear in the list
of developers of lmms, also I would express better speaking in Spanish ...
Another suggestion is that they add the scroll bar in the file explorer; The
possibility of deletion and duplication in group with the selection tool in
the song editor; I also suggest (maybe they think it's an absurd idea, it's
that I'm a beginner) audio editing by integrating audacity to lmms. I
explain myself better. For example: You have a sound file (wav, ogg) in
lmms in the song editor, bb editor or in the sample tracks, and you quickly
want to edit that sound (cut, split, add effects and all audacity
possibilities) , Left click and the menu appears and you click on a button
that says '' edit with audacity '', and automatically opens audacity
importing the audio, you edit and when saving appears in audacity the ''
save in lmms '' button , Then it closes and you enter lmms and ready, the
audio has been edited. Well, I guess they would have to make deals with the
audacity developers. Or more expensive but serious, replace the sample
tracks and audio processor, by an '' Audio Editor '' in lmms, would be more
expensive, but would be a great advance in lms as in linux in general, if I
were programmer Would collaborate. I do not know what you think, but it is
my humble opinion, that you oppose ?.

2017-03-22 23:36 GMT-03:00 Javier Serrano Polo <notifications@github.com>:

**Comment by jasp00** [comment]
>You speak Spanish ?

I think so. When I communicate in an unknown language, I attach the original text in a comment. You may want to add a [Gist](https://gist.github.com/) link with your original words.

>Another suggestion [...]

Please, one feature per issue. Choose a simple feature, open a new issue, get an OK from us, and we will teach you little by little how to implement your feature.

>I really don't have idea.

@liushuyu, first choose a feature: multitrack recording button or countdown clock?

**Comment by liushuyu** [comment]
>@liushuyu, first choose a feature: multitrack recording button or countdown clock?

Maybe count down clock first, this one should be easier.

**Comment by jasp00** [comment]
Fine. First we want to add the GUI element because we need a way to test the feature. This would be a good moment to hear from the GUI team, but we can use a draft in the meantime. If you like @Gabrielxd195's proposal, you should locate the toolbar and add an LCD display. Do you know how to do that?

**Comment by liushuyu** [comment]
@jasp00 I've got UI implemented, here's the screenshot:
![image](https://cloud.githubusercontent.com/assets/6829345/24484061/5913fcf8-14b9-11e7-8286-e82c7a249c68.png)

I have put the count down timer value in `Song` class, because I don't know where to put this thing in.

**Comment by liushuyu** [comment]
Okay, here's my draft: https://github.com/liushuyu/lmms/tree/countdown/

**Comment by jasp00** [comment]
>I will try my best not to let you - and - everyone else down.

Good attitude, but take it easy.

>here's my draft

This looks like a good start. Make a WIP pull request and we will continue there.
