### ISSUE TITLE
LMMS crackles when rendering to file

### ISSUE THREAD

**Issue by PaulBatchelor** [LMMS/lmms#3396]
As the issue says, I get crackles when I render anything to file.

The test project I am working with is a default instance of ~~Organic~~ TripleOscillator playing a note for two bars. When I render it with the default options, I get crackles. The resulting audio file and project are zipped below:

[one_note.zip](https://github.com/LMMS/lmms/files/813006/one_note.zip)

Weird thing is, I only get this sort of error on my Fedora E6530 laptop. On my Chromebox running Slackware, things run fine. 

I should also note that when I try to render anything using my [Sporth plugin](http://www.github.com/paulbatchelor/LMMS-Sporth.git), things flat out crash on my laptop.

**Comment by PaulBatchelor** [comment]
When using my Sporth plugin, I'm getting a similar backtrace as #3207, trying my hack from there. 

I should note that my segfaults happen at random points, which would suggest some sort of threading problem.

**Comment by zonkmachine** [comment]
Those gaps seem to be 256 samples wide. Can you try another buffer size?

> The test project I am working with is a default instance of Organic playing a note for two bars. When I render it with the default options, I get crackles. The resulting audio file and project are zipped below:

one_note.mmpz has a 3osc and not organic. There actually is a crackle issue with organic that is on my list of things to do.

> When I render it with the default options,

What are your audio settings?
Have you tried rolling back some to an earlier commit?

**Comment by PaulBatchelor** [comment]
> Those gaps seem to be 256 samples wide. Can you try another buffer size?

LMMS was set to 256 buffer size, bumped it up to 512. Similar crackles.

> What are your audio settings?

Using JACK. 44.1kHZ 256 buffer size 4 periods/buffer. 

>  Have you tried rolling back some to an earlier commit?

Not yet, no. Will look into that.

**Comment by Umcaruje** [comment]
>Using JACK. 44.1kHZ 256 buffer size 4 periods/buffer

I'm amazed that you can even export with Jack. My LMMS instantly crashes for every project. Reported here: #2934

**Comment by PaulBatchelor** [comment]
> I'm amazed that you can even export with Jack. My LMMS instantly crashes for every project. Reported here: #2934

This is horrifying. Bouncing to disk shouldn't be dependent on what audio backend you use.

I've been digging around some core LMMS code, and I'm seeing a LOT of red flags here. For starters, this whole class gets me worried:

https://github.com/LMMS/lmms/blob/master/src/core/MixerWorkerThread.cpp

It gets called in the Mixer class, which I am guessing where your buffer gets rendered:

This I am assuming handles all of the polyphony and note events:

https://github.com/LMMS/lmms/blob/master/src/core/Mixer.cpp#L431

This, I am assuming, is doing all the effects processing:

https://github.com/LMMS/lmms/blob/master/src/core/Mixer.cpp#L461



I don't fully understanding what is going on, but it looks like LMMS is using QThreads to process audio on multiple threads. If this is the case (and I really really hope it's not), that's a  huge problem. Unfortunately, the stack traces I've been doing, and the types of crashes and glitches I've been getting would suggest that the issues are related to threading issues.

**Comment by PaulBatchelor** [comment]
Also found #2845. Same deal.

**Comment by PaulBatchelor** [comment]
#3360 looks very similar as well.
