### ISSUE TITLE
just read below

### ISSUE THREAD

**Issue by JohnnyDcrypt** [LMMS/lmms#3398]
when i open lmms (any version after 0.4.15) i get the "this app has requested runtime to terminate it in an unusual way" error when the splash screen says it's loading the automation editor, and then the app closes. I have tried several bug fixes for this (reinstalling visual c++, updating audio drivers, reinstalling graphics drivers, installing visual studio, etc.) and i have uninstalled and reinstalled the 32 bit and 64 bit versions of the program in multiple versions after 0.4.15. I am runnting windows 10 home 64 bit on 4 gb ram and an x64 intel i5-2450M 2.50 GHz processor. my audio driver is the default conexant smartaudio driver, updated to the newest version. My laptop is a Sony Vaio VPCEG3BFX, with an nvidia geforce 410m graphics card.
Nothing seems to work, and only the RC version 0f 0.4.15 from portableapps.com works

**Comment by musikBear** [comment]
covered on forum

**Comment by zonkmachine** [comment]
Dealt with here: https://lmms.io/forum/viewtopic.php?f=7&t=8566
Closing.
