### ISSUE TITLE
There should be the option to universally assign a Midi input, and then have that Midi input applied to just the current armed track.

### ISSUE THREAD

**Issue by tigerprawn** [LMMS/lmms#3400]
At the moment if you are playing a Midi keyboard and you want to use it on a different tracks, you need to connect it every time to each new track and arm the track, and even then it is still connected to the other unarmed tracks. I think it would be better if it functioned like Ableton where you setup a Midi device in Preferences and then it is automatically connected just to the current armed track.

**Comment by tresf** [comment]
We're aware.  Mentioned here generically (Faster access to MIDI assignment/auto-assignment): #1472

Which is also mentioned here #1189 #1781 #1918 #1942 #3185
