### ISSUE TITLE
ReverbSC - Method to change sample rate

### ISSUE THREAD

**Issue by zonkmachine** [LMMS/lmms#3401]
As mentioned here: https://github.com/LMMS/lmms/pull/3202#issuecomment-282132629

ReverbSC doesn't  have a method to change sample rate. This means the rate will stay the default when you export so if you choose another rate and/or oversampling the reverb will come out wrong.

**Comment by PaulBatchelor** [comment]
Copying and pasting a comment from that thread:

@zonkmachine Ah, okay. I can look into that.

So, the easy part is telling Soundpipe what the new SR is. That's just a matter of setting a variable in the struct, like I do when I initialized the plugin:

https://github.com/LMMS/lmms/blob/master/plugins/ReverbSC/ReverbSC.cpp#L53

One possible issue I forsee lies is reallocating memory for RevSC. The delay lines are computed at init-time based on the engine samplerate. The only way to do this is by destroying the instance of RevSC and creating a new instance with the new samplerate. Not ideal if this is an operation on a thread.

**Comment by PaulBatchelor** [comment]
I made a PR. Should definitely be tested.

**Comment by zonkmachine** [comment]
I'm on the case...

**Comment by PaulBatchelor** [comment]
@zonkmachine since #3403 has been created, can this be closed? Trying to minimize my github issue footprint for LMMS.

**Comment by Umcaruje** [comment]
@PaulBatchelor usually we leave the issue open until the PR is merged. The nice thing is if you mention the related issue with `fixes` or `closes`, It'll automatically get closed on the merge, so this is nothing to worry about :)

**Comment by PaulBatchelor** [comment]
Sweet! Open it shall stay.
