### ISSUE TITLE
Sound doesn't work

### ISSUE THREAD

**Issue by gameslayer** [LMMS/lmms#3405]
Play back sound does not work, tried every setting and nothing seems to work while everything else does through my logitech headphones, I even tried SDl.

corey@corey-desktop:~$ lmms
Notice: could not set realtime priority.
VST sync support disabled in your configuration
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock

**Comment by musikBear** [comment]
#support-request

You need to post :
os
lmms ver
hw specification
Open an account here: 
http://lmms.io/forum/

**Comment by BaraMGB** [comment]
@gameslayer this seems not to be a lmms issue. I'll close this. Please get support on our forum http://lmms.io/forum/ 

If no one can help you, please feel free to repost your problem here again.
