### ISSUE TITLE
Helm VST crashes on Windows 7 64-bit PC (for both 32 and 64 bit DLL)

### ISSUE THREAD

**Issue by rknonchalance** [LMMS/lmms#3407]
**WARNING:** Audio will get insanely loud.

Recorded with OBS here, along with description of the error outputted by Microsoft: https://www.youtube.com/watch?v=7Hcb4QI_Oqw&feature=youtu.be

Will update this once I get the dxdiag text (not using the same PC that I did here). I'm also about to post this on the forums just in case.

**Comment by zonkmachine** [comment]
Can you please test the latest development release for lmms 1.2.0 .
It has a bunch of fixes for VST related issues.
https://lmms.io/download/#windows

**Comment by PhysSong** [comment]
Confirmed with rc2(in my case, helm not crashed but hanged) and fixed in rc4. Closing.
