### ISSUE TITLE
Grid disappeared in Piano Roll

### ISSUE THREAD

**Issue by binyominzeev** [LMMS/lmms#3423]
Sorry, I am maybe doing something wrong, but somehow the grid in Piano Roll disappeared completely.

![2017-03-13-220316_2304x1024_scrot](https://cloud.githubusercontent.com/assets/4866177/23875215/eb660552-0838-11e7-882a-78c0e73d9c29.png)

As far as I know, I only installed the latest version of LMMS and chose Classic Theme, that's all. With Default Theme it works, but I don't like its colors...

**Comment by binyominzeev** [comment]
In the meantime, I noticed an interesting output on my console:

``
PianoRoll(0x257b7d0)  does not have a property named  "gridColor" 
``
``
AutomationEditor(0x25de320)  does not have a property named  "gridColor" 
``
``
AutomationEditor(0x25de320)  does not have a property named  "gridColor" 
``
``
PianoRoll(0x257b7d0)  does not have a property named  "gridColor" 
``
``
PianoRoll(0x257b7d0)  does not have a property named  "gridColor" 
``

**Comment by Umcaruje** [comment]
oh my, I completely forgot to update the classic theme after #3062 happened. On the case

**Comment by Umcaruje** [comment]
@binyominzeev thank you for the bug report!
