### ISSUE TITLE
VST3 SDK can be licensed using GPLv3 now.

### ISSUE THREAD

**Issue by Umcaruje** [LMMS/lmms#3427]
This opens up quite some possibilities: 

https://sdk.steinberg.net/viewtopic.php?f=4&t=282

It's dual licensed which means it can be finally used in open source projects like LMMS. 

Now they didn't do anything about the VST2 SDK which is something we'd ideally replace Vestige with.

**Comment by BaraMGB** [comment]
>Note that VST2 sources are NOT part of the GPLv3!

hmm, Steinberg want to kill VST2. A lot of plugin developer uses VST2 only. That's a pain for Steinberg. They wanna force VST3 technology. But as far as I know LinuxVST uses VST2 only. I don't know if LinuxVST can build against VST3 SDK.

**Comment by BaraMGB** [comment]
I ask in the juce forum about this issue. Juce handles all VST2 stuf by it self.
https://forum.juce.com/t/juce-gpl-and-vst-sdk-license-mystery/14935/19

**Comment by grejppi** [comment]
VST3 is under GPLv3, LMMS under GPLv2, which are incompatible with each other (or would change LMMS to GPLv3 too). A similar situation was discussed in #2752.

**Comment by jasp00** [comment]
This looks like good news. We can develop a VST3 plug-in for LMMS and distribute it separately.
Regarding VST2, Steinberg is a company and has to make money, which is understandable. They will not free the technology until they see the benefit. I am certain Yvan Grabit would like to free VST2.

**Comment by T0NIT0RMX** [comment]
I have some important news : VST2 SDK has been removed from Steinberg's servers.
[http://forum.cabbageaudio.com/t/important-vst2-plugin-no-longer-an-option/1228/3](url)

As I understand, that means there will no longer be any new VST2 plugins.
So, I think a VST3 support in LMMS is mandatory right now, would it be possible ?

Should I open a new issue, explaining the problem ?

**Comment by musikBear** [comment]
@T0NIT0RMX Your link is dead
Always best with new issue, if the context differ from all current issues

**Comment by T0NIT0RMX** [comment]
> @T0NIT0RMX Your link is dead
> Always best with new issue, if the context differ from all current issues

Link updated, but how to make sure it doesn't end like [this](https://github.com/LMMS/lmms/issues/2352) ? Ok it was 3 years ago, before they anounce the end of the support and it was copy pasted, but I can't create a new issue that is the same as an old closed one :/

**Comment by jasp00** [comment]
> it was copy pasted

Are you going to do the same?

>Should I open a new issue, explaining the problem ?

Explain your problem in a new issue and ping me.

**Comment by T0NIT0RMX** [comment]
> > it was copy pasted
> 
> Are you going to do the same?
> 
> > Should I open a new issue, explaining the problem ?
> 
> Explain your problem in a new issue and ping me.

No, of course, and here is the new issues [#4715](https://github.com/LMMS/lmms/issues/4715)

**Comment by tresf** [comment]
The point of this bug report seems to be awareness and license compatibility.  We're aware, and LMMS is compatible once GPL2 has been upgraded to GPL3.  Closing discussion.
