### ISSUE TITLE
Module «» doesn't exist or can't be loaded 

### ISSUE THREAD

**Issue by R-033** [LMMS/lmms#3435]
![2017-03-18 22-37-49](https://cloud.githubusercontent.com/assets/15189406/24072109/32b097ea-0c2d-11e7-8bc5-9a48d69ef508.png)

> Module «» doesn't exist or can't be loaded! Reason: «The library /usr/bin/../lib/x86_64-linux-gnu/lmms/ could not be loaded: (/usr/bin/../lib/x86_64-linux-gnu/lmms/: Unable to read file data: this is directory)»

I'm trying to load a VST, and this message appears.

Ubuntu 16.04, lmms 1.1.3

**Comment by Umcaruje** [comment]
>Ubuntu 16.04, lmms 1.1.3

How did you acquire LMMS? Compiled yourself, or the KXStudio repos? do you have the `lmms-vst-full` package installed?

**Comment by R-033** [comment]
Lmms was installed from Ubuntu repos via `sudo apt-get install lmms` command
`lmms-vst-full` not installed and not found

**Comment by lukas-w** [comment]
@R-033 As far as I know, Ubuntu 16.04 doesn't ship with LMMS's VST plugin. You'll have to use another source, such as the KXStudio Repo: http://kxstudio.linuxaudio.org/Repositories
