### ISSUE TITLE
Mixer solo and mute automations have empty label

### ISSUE THREAD

**Issue by karmux** [LMMS/lmms#3443]
If you connect mixer mute or solo button to automation track it's label is empty.
Right click and disconnect option shows also "".
All other automation connections show something like "BitInvader>Volume" or "Amplifier>>Panning".

**Comment by Umcaruje** [comment]
Confirmed on `lmms Version 1.2.0-rc2.93 (Linux/x86_64, Qt 4.8.7, GCC 5.4.0 20160609)`
