### ISSUE TITLE
Command line rendering with VST plugins broken

### ISSUE THREAD

**Issue by lukas-w** [LMMS/lmms#3449]
From #3434, quoting @karmux:

-----

When project has VST plugins:
```
$ ./lmms -r ~/Documents/LMMS/projects/ProjectWithVST.mmpz -o ~/ProjectWithVST.ogg -f ogg
VST sync support disabled in your configuration
Loading project...
QWidget: Cannot create a QWidget without QApplication
Aborted (core dumped)
```

**Comment by BaraMGB** [comment]
Perhaps we can put out a warning for users. I don't have a clue how to fix it at the moment.

**Comment by musikBear** [comment]
@BaraMGB is cmd-line rendering important? Is this used by many users?

**Comment by BaraMGB** [comment]
The problem is in the current version we have a crash. Crashes are always bad. If we catch this up and print out "you can't render a project with Vst plugs on the command line". This were a few better behavior.

**Comment by zonkmachine** [comment]
> `QWidget: Cannot create a QWidget without QApplication`

Could this be related to https://github.com/LMMS/lmms/issues/2143?
A project with a VST instrument will open the instrument GUI by default. In the projects I've tried the GUI is hidden behind the other windows but it's open nonetheless.

**Comment by BaraMGB** [comment]
Yes, if we fix this one here we could fix https://github.com/LMMS/lmms/issues/2143

But I don't know a way to use a Vst without gui.

**Comment by Umcaruje** [comment]
>But I don't know a way to use a Vst without gui.

Well when the window is closed, the gui is destroyed and you still use the VST, right?
