### ISSUE TITLE
Automations inside patterns don't work anymore

### ISSUE THREAD

**Issue by karmux** [LMMS/lmms#3464]
After 6004edae5c5108560caf9d1f67789b5e47329212 automations inside patterns don't work anymore. 

- Create B+B pattern
- Add automation track inside pattern
- Connect some random knob or slider (e.g. master volume) to automation track
- Draw something into automation track
- Play and connected knob or slider stays still

Automations in song editor work.

**Comment by Lukas-W** [comment]
@karmux Thanks for reporting! #3481 should fix it once merged.

**Comment by karmux** [comment]
@Lukas-W thanks! #3481 fixes it.
