### ISSUE TITLE
Error loading pixmaps when using the resource system

### ISSUE THREAD

**Issue by jasp00** [LMMS/lmms#3468]
With VeSTige, I get errors like:
```
Error loading icon pixmap "vestige/track_op_menu_active": File not found
```
and dot pixmaps are used.

**Comment by Umcaruje** [comment]
Is this related to or the same as #3498 ?

**Comment by tresf** [comment]
> Is this related to or the same as #3498 ?

Yes per [@karmux's branch](https://github.com/LMMS/lmms/compare/stable-1.2...karmux:3498_missing_vestige_icons#diff-00e08b1a3bdce754576149caf3643db6R429), this is one of the file affected.

Closing, marking as duplicate of #3498.
