### ISSUE TITLE
April Fools' Day feature

### ISSUE THREAD

**Issue by jasp00** [LMMS/lmms#3474]
I propose to include this feature or another one following this spirit. On April 1, LMMS should:

1. Display the old splash screen, the one showing a note with a face (did it ever get a name?).
2. Prepend this text to the license tab:

```
Each contributor grants you a non-exclusive, worldwide, royalty-free right to
have fun as much as you want...

subject to the following license:
```

3. Show a configuration setting to disable this feature.

**Comment by liushuyu** [comment]
Unfortunately it will be too late for this year's April Fool 😄

**Comment by tresf** [comment]
VLC and Minecraft have easter eggs inside them for specific times of the year as well.  VLC shows a Santa hat on the icon around the end of the year.

I don't see much value in this feature and it can be confusing to see a very old splash screen.  It will also require us to keep around the old splash screen graphic in our source code for ever.

That said -- if it's implemented -- I wouldn't clutter the configuration screen with a dedicated checkbox for it.

I don't think a professional tool should go out of it's way to perform tricks on people, especially when used in education or government sectors.  Unless it's subtle, like the small santa hat, I feel it actually subtracts value from the product. `</opinion>`

**Comment by jasp00** [comment]
>I don't see much value in this feature and it can be confusing to see a very old splash screen.

Some people like humor, unless it hinders usability. We could make a revamped splash screen of the note with a face (same background style, same logo size, etc.).

>I wouldn't clutter the configuration screen with a dedicated checkbox for it.

It would show only on April 1 for convenience. Once disabled, it would not appear anymore.

**Comment by jasp00** [comment]
>(same background style, same logo size, etc.)

Same as the official splash screen.

**Comment by musikBear** [comment]
..nee imo no
But something on FB that is of subtle yet amusing style and of cause trickery..
Like announcing going commercial and 2.0 will cost money.. 
or putting it up too peeps that 'we' have decided that users starting with a letter need to pay for server-time.. other really wacky stuff
something where peeps would fall in and write something 'uncontrolled' 
I believe @Umcaruje did a neat thing last year..? 
Just something to create a blush april 2. 
Not a 'feature' in LMMS **imo**
I ...kind of wonder juuuuust a tiiiny bitti bit, if @jasp00 arent actually pulling a fast one on everybody.. Uhmmm? 🤡

**Comment by Mark-Agent003** [comment]
![splash2](https://cloud.githubusercontent.com/assets/25230510/25504103/3f76aae2-2b62-11e7-89ee-543df14524c0.png)
This could be the christmas logo. :)

**Comment by Mark-Agent003** [comment]
This was kinda what @tresf mentioned. It's not too intrusive and it shouldn't confuse any users. It's just a little easter egg. If somebody can make this (or something else) show up through December or some time around December 25, and y'all like it, I can touch it up a bit.

**Comment by musikBear** [comment]
>  I can touch it up a bit.
imo its shading looks great with the roughish shades on the logo
The combined appearance made me think of a green-haired 'Heidi' / Pippi-Longstocking at a Christmas rave :)

**Comment by tresf** [comment]
I like the artwork done by @Mark-Agent003 and I think the old logo is a funny concept, but as a professional tool, the April fool's concept is really just confusing and I'm not sure how that helps the software move forward.  If someone really wants to add this through a pull request, we can have a poll.  @Umcaruje likes to do some jokes on Facebook around April 1st and it seems to go well, so there may be a community warmness to this, I just don't agree.

In regards to the santa hat, I hold the firm position that anything even remotely religious (or politically) oriented should never touch our codebase, ever.  Yes, I understand the santa hat is a mostly kid-friendly and commercial representation of a character, but there's no way to do this for all characters and all holidays and inclusion of non-standard "holiday" characters may offend.

So I vote to close this out.  We're a global software and we aim to be professional grade.  If we want to add something, perhaps we honor Toby's birthday or display a blurb about a random dev while the software is loading.  I vote no to easter eggs and santa hats.

**Comment by BaraMGB** [comment]
I agree with Tres here.

**Comment by Mark-Agent003** [comment]
@tresf, I totally understand and agree. 👍

**Comment by tresf** [comment]
Thanks.  Closing out as wont-fix for now.
