### ISSUE TITLE
Internal routing of MIDI from step-sequencer to instrument

### ISSUE THREAD

**Issue by liftarn** [LMMS/lmms#3485]
This don't seem to be mentioned here, but there is a discussion at for instance https://sourceforge.net/p/lmms/mailman/message/32465913/

What I want to do is
1. Load a step-sequencer VST like BlueARP as an instrument (this works)
2. Feed input from the piano roll into the VST (this works)
3. Feed the MIDI output from the step-sequencer VST to another instruments MIDI in (this don't work)

Some other DAWs that shall remain nameless handles this vis internal MIDI routing, but LMMS seem to lack this feature.

**Comment by tresf** [comment]
As part of a pruning effort this request has been consolidated into `meta` issue "Better MIDI support". #1472
