### ISSUE TITLE
 ZynAddSubFx Not Responding on clicking Show Gui

### ISSUE THREAD

**Issue by scottwolff** [LMMS/lmms#3488]
Happens in LMMS version 1.1.3, on my system with these specs (post 1607 cumulative update):

-----------------------------------------------------------------------------
```
OS Name	Microsoft Windows 10 Pro
Version	10.0.14393 Build 14393
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	DESKTOP-V22RDSM
System Manufacturer	MSI
System Model	MS-7693
System Type	x64-based PC
System SKU	To be filled by O.E.M.
Processor	AMD FX(tm)-6300 Six-Core Processor, 3500 Mhz, 3 Core(s), 6 Logical Processor(s)
BIOS Version/Date	American Megatrends Inc. V10.3, 3/28/2013
SMBIOS Version	2.7
Embedded Controller Version	255.255
BIOS Mode	Legacy
BaseBoard Manufacturer	MSI
BaseBoard Model	Not Available
BaseBoard Name	Base Board
Platform Role	Desktop
Secure Boot State	Unsupported
PCR7 Configuration	Binding Not Possible
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume4
Locale	United States
Hardware Abstraction Layer	Version = "10.0.14393.206"
User Name	DESKTOP-V22RDSM\grey2
Time Zone	Central Daylight Time
Installed Physical Memory (RAM)	8.00 GB
Total Physical Memory	7.95 GB
Available Physical Memory	4.46 GB
Total Virtual Memory	16.4 GB
Available Virtual Memory	11.3 GB
Page File Space	8.50 GB
Page File	C:\pagefile.sys
Hyper-V - VM Monitor Mode Extensions	Yes
Hyper-V - Second Level Address Translation Extensions	Yes
Hyper-V - Virtualization Enabled in Firmware	Yes
Hyper-V - Data Execution Protection	Yes
-----------------------------------------------------------------------------------------
```

![speccy snapshot](https://cloud.githubusercontent.com/assets/19482044/24733534/f6bad18c-1a3d-11e7-94a5-7266012abb7a.png)

I caused LMMS to lock up (not responding) while trying to click Show Gui in the ZynAddSubFx.

![lmms lockup](https://cloud.githubusercontent.com/assets/19482044/24733579/33a7f0c0-1a3e-11e7-9efd-ce63da434068.png)

I was able to get it to work by running LMMS: As Administrator.

Posted here following my posts in this thread: https://github.com/LMMS/lmms/issues/2269#issuecomment-292041867

>  tresf commented 2 hours ago • edited

> @scottwolff your problem is unrelated to the original problem (his was Linux related).

> Since you are running Microsoft Windows, your problem may be a permissions issue with the .zynaddsubfxXML.cfg file or the directory it is contained within.

> Please look in either %userprofile%\lmms\.zynaddsubfxXML.cfg or in your LMMS_HOME directory for this file and ensure your profile has sufficient permissions to read and write to this location.

> If you are unfamiliar with file permissions, this file can also be safely deleted.

>>  scottwolff commented an hour ago

>> What would be the appropriate resource to put this information in, for those that were having the same problem as I?

>>>  tresf commented an hour ago

 >>>>   What would be the appropriate resource to put this information in, for those that were having the same problem as I?

>>>Well, running as administrator is not a recommended solution, so I suppose that depends on whether or not the above steps help.

>>>>>  scottwolff commented 31 minutes ago

>>>>>lmms permissions

>>>>>![lmms permissions](https://cloud.githubusercontent.com/assets/19482044/24733677/a203dbce-1a3e-11e7-9091-769136c1a0cc.png)

>>>>> I don't see anything wrong with the permissions. Even after setting the same for LMMS in the program files it still hangs. I was already in the administrators group for my pc.

>>>>>I deleted the .zynaddsubfxXML.cfg file with the same results.

>>>>>>  tresf commented 12 minutes ago • edited

>>>>>> @scottwolff thanks for trying. Probably best to track this issue in a new topic since it's not a quick fix. Please provide as many details as you can including what you've tried, what's work and what hasn't.

>>>>>> The next thing I would recommend is performing a forced disk check and reboot as some new solid state drives (SSDs) in Windows can get bad security descriptors and cause all sorts of crashes. The next steps will be to use process monitor to trace what files are being accessed to determine what part of the computer is read/write by Administrator/UAC but not by you.

**Comment by tresf** [comment]
@scottwolff I notice one of the drives in your system is solid state.  Please run the following command from cmd.exe

```cmd
chkdsk /f
```

When prompted to scheduled the disk check after reboot, say yes.

Assuming this does not correct the problem, download and run [`ProcMon.exe`](https://download.sysinternals.com/files/ProcessMonitor.zip) from Microsoft and set a filter on:
* ![image](https://cloud.githubusercontent.com/assets/6345473/24734049/5cc28992-1a49-11e7-89cb-7c35e6be6efe.png) Click filter
*  `Process Name` is `RemoteZynAddSubFx.exe`.
* `Result` is not `SUCCESS`

See if anything stands out.  There will be A LOT of errors in there.  I'm not entirely sure why (and I'm not an expert on ProcMon).  Comparing the results with Administrator and with standard user should help point to the problem that is crashing.

On a side, note you may also chose to test out the [1.2.0-RC2](https://github.com/LMMS/lmms/releases/tag/v1.2.0-rc2) build to see if this helps. Download links are at the very bottom.  I recommend doing a full uninstall prior to reinstalling.  Also make sure all instances of `RemoteZynAddSubFX.exe` and `lmms.exe` are not running.

**Comment by scottwolff** [comment]
I am running the Intel SSD program for data integrity at the moment. As soon as that's finished I will do the chkdsk.

Curious, the filter is on RemoteZynAddSubFx.exe. When I go to run it independently, with or without LMMS open I get this error:

![remotezynaddsubfx](https://cloud.githubusercontent.com/assets/19482044/24734353/74c16984-1a42-11e7-91fb-147fdc1d70dd.png)

**Comment by tresf** [comment]
`RemoteZynAddSubFx.exe` can only run with certain libraries on the path and they're all located a directory higher, in `\lmms\`, rather than `\lmms\plugins\`.

It's not really intended to be run stand-alone though, so even if you fix the `.dll` errors, you'll still hit a wall.  It must be launched from within LMMS.

**Comment by scottwolff** [comment]
![full ssd scans](https://cloud.githubusercontent.com/assets/19482044/24735000/2b0fe78a-1a46-11e7-8dac-4c28158d82a9.png)

Ran that first, including optimizations and full scan.

After that I ran the checkdisk, scanned before loading windows, now it works after that. 👍 

Gosh darn, and I thought SSDs were all stellar improvements over spinning XD

**Comment by tresf** [comment]
> After that I ran the checkdisk, scanned before loading windows, now it works after that. 👍

Great news!

> Gosh darn, and I thought SSDs were all stellar improvements over spinning XD

This single problem has been my only complaint.  After getting burned a few times, I just run `chkdsk /f` as soon as a program starts acting up.

I'm glad to hear this fixed your problem.  Thanks kindly for sharing your information.  Your results are sure to help others experiencing the same problem. 👍
