### ISSUE TITLE
Lmms settings and application crashing

### ISSUE THREAD

**Issue by Floffah** [LMMS/lmms#3499]
I installed lmms 1.1.3 (the latest) from the official site and its the 64 bit version and originally when i tried to open the settings it crashed but now after reading this site https://github.com/LMMS/lmms/issues/1865 it now crashes when i open it and i took all the steps carefully and it just made it worse so please help
edit: it says
Microsoft visual c++ Runtime Library (what it says at the top
Runtime Error!

Program: D:/program files/lmms/lmms.exe (where i installed it)

This application has requested the runtime to terminate it in an unusual way
please contact the application's support team for more information

and then i press ok and it says lmms.exe has stopped working a problem caused the program to stop working correctly windows will close the program and notify you if a solution is available and then i press close program and it goes away untill i start the program again

**Comment by musikBear** [comment]
#512 is perhaps the solution?

**Comment by zonkmachine** [comment]
> This application has requested the runtime to terminate it in an unusual way

This should have been fixed in lmms-1.2.0-rc5 (or earlier). Closing.
@Floffah Please test the latest beta version of the new stable 1.2 here:
https://lmms.io/download/#windows
