### ISSUE TITLE
LMMS Parametric Equalizer Ignores Wet/Dry Effect Knob

### ISSUE THREAD

**Issue by UnityParadox** [LMMS/lmms#3505]
On 1.2.0 RC2, the wet/dry knob seems to have no effect on the built-in parametric EQ. Uncertain of whether or not this is either a setup or system issue, as opposed to a bug.

**Comment by Spekular** [comment]
Same problem here. Win 10 64 bit and 64 bit 1.2.0 RC-2, fwiw.

**Comment by JordanKyser** [comment]
I have actually had the same problem.
