### ISSUE TITLE
Feature request: Option to disable animated expand/collapse of panels

### ISSUE THREAD

**Issue by Oddwarg** [LMMS/lmms#3507]
This is a minor issue, and I am using Windows 7.

In the Instrument Plugins menu, moving the mouse over the instruments will make the panels slowly expand and collapse, offsetting the items below in the list and creating an artificial delay before the user can read the full description. This behaviour slows down user interaction.

![image](https://cloud.githubusercontent.com/assets/6345473/25237230/124c3c4e-25b8-11e7-92df-50d487c872a5.png)

Ideally, the UI should be redesigned so that the appearance of the description does not offset (nor occlude) the items below in the list. However, the ability to either speed up or entirely disable the animation would be a helpful patch.

**Comment by tresf** [comment]
I believe this is a `10ms` call to `updateHeight()`.

https://github.com/LMMS/lmms/blob/master/src/gui/PluginBrowser.cpp#L235

Simply changing [`+1` to `+10`](https://github.com/LMMS/lmms/blob/master/src/gui/PluginBrowser.cpp#L221) should do the trick for faster animation.

**Comment by Umcaruje** [comment]
I agree on this.

**Comment by zonkmachine** [comment]
I believe this was fixed in #3773
