### ISSUE TITLE
Frequency Error through WAV conversion

### ISSUE THREAD

**Issue by JordanKyser** [LMMS/lmms#3508]
I don't know how this happen, but I will provide 3 examples.

FM Gain Error: http://www.newgrounds.com/audio/listen/735349
Filter Frequency Error: http://www.newgrounds.com/audio/listen/733510
                                    http://www.newgrounds.com/audio/listen/740543

Anyways, a demonstration of what is most likely happening will be very appreciated.

**Comment by Umcaruje** [comment]
Can you explain what is happening here? What was expected to happen and what did actually happen? An isolated test case or p a project file with this issue would be appreciated.

Is this about zynaddsubfx?

**Comment by JordanKyser** [comment]
It is ZynAddSubFX.

**Comment by Umcaruje** [comment]
>but it is most likely a reading error.

You should try to get an isolated test case. Are you automating the knobs? Are they clean from any global automation? 

You still didn't specify what exactly happens. Do the values change on exporting? Or do the values stay the same but the frequency / FM gain goes to a specific value on export?

The more specific information we get about this bug, the higher the probability will go for fixing it.

**Comment by JordanKyser** [comment]
I have provided a link to one of the above songs:

FM Gain Usage: https://lmms.io/lsp/?action=show&file=10518 (http://www.newgrounds.com/audio/listen/735349)

On the MP3 file (the MP3 file given has the same sound as the WAVE file), on the Talker. the FM Gain has a glitch to where it stops at random spots (the courtesy of the remix is of FGKOfficial and credits of the original go to both Texxiliator and me).

**Comment by tresf** [comment]
@JordanKyser I'm sorry, but you've failed to answer the most basic of questions to allow a developer to reproduce.  Please request a re-open once you're able to provide detailed steps to reproduce.
