### ISSUE TITLE
Unusual static noise

### ISSUE THREAD

**Issue by Nitrocell12345** [LMMS/lmms#3519]
The LMMS version I have is 1.1.3 64 bit, and I have been enjoying and experimenting with it for a couple of days now. Today, however, something is wrong: the notes in the song adopt a semi-static, semi-chipping noise when played a few seconds after they're struck. This happens to every instrument I used in the song, as well as the ones in other projects as well. I've restarted my computer, let alone uninstalling and reinstalling LMMS to see the issue, but even that doesn't work. I don't know if this is a playback error or something else, but I know for sure that it isn't my computer.

**Comment by musikBear** [comment]
@Nitrocell12345 you do not tell what OS you are on.
If it is windows, it sounds like you are using the wrong backend
Please read: 
https://lmms.io/wiki/index.php?title=LMMS_Settings#Audio_Settings
And for windows select **SDL**

**Comment by BaraMGB** [comment]
@Nitrocell12345 I close this issue by not answering in 29 days. If this issue is not resolved for you please inform us.
