### ISSUE TITLE
Pressing the "add effect" key can cause (almost) endless loops in case of a bad VST dir

### ISSUE THREAD

**Issue by JohannesLorenz** [LMMS/lmms#3528]
Pressing "add effect" leads to LMMS scanning for "VST sub-plugin features":

If you have a VST directory "x" with a subdirectory "y" containing a symbolic link to "x", e.g. "x/y/z" points to "x", [this loop](https://github.com/LMMS/lmms/blob/stable-1.2/plugins/VstEffect/VstSubPluginFeatures.cpp#L75-L81) causes almost endless recursion, like "x/y/z/y/z/y/z..."

You can temporary fix this by setting your VST directory to a directory without such symbolic links. Or by disabling VST (-DWANT_VST=OFF), but when I did it, I had to remove my build dir because of caching.

**Comment by tresf** [comment]
Can you please explain the use-case for having recursive directories?

**Comment by JohannesLorenz** [comment]
In my example, I had "~/.wine/dosdevices/", which contains symbolic links to my root and home directory. This seems to be common in WINE installations.

My VST directory was $HOME, which caused the problem.

Btw: IMO it's no bug that needs to be fixed urgently. The workarounds should suitable for all use-cases.

**Comment by tresf** [comment]
> My VST directory was `$HOME` [... containing ] `~/.wine/dosdevices/`, [... containing] symbolic links to my root and home directory. 

Ok.  This seems like an edge-case.  You really shouldn't be using the root of home for VST plugins.

One option is to short-circuit the scanning process to omit `~/.wine/dosdevices/` completely.  This directory is very common on Linux machines and seems like it would fix the problem.  A more elegant but more difficult solution would be to write our own recursion detection, which I'd prefer to avoid in the codebase.

If opinion counts though, I don't really think this is a bug at all.  The `$HOME` directory is simply a bad place to stash plugins.

**Comment by Umcaruje** [comment]
>I don't really think this is a bug at all. The $HOME directory is simply a bad place to stash plugins.

I kinda second this. You shouldn't keep your VST DLL's in the root of your home directory.

**Comment by JohannesLorenz** [comment]
> The $HOME directory is simply a bad place to stash plugins.

I agree, but I wonder why my VST directory is set to $HOME. IIRC, I never changed it. From looking at  src/core/ConfigManager.cpp, it looks like the default is never $HOME, but "$PWD/plugins/vst/" instead. So it should probably not happen to people installing LMMS for the first time.

Concerning a cycle detector, I currently don't have a good idea. Maybe wait for a week or two until anyone comes up with a nice solution, and if no one has a good idea, close it? (This should still not keep us from releasing 1.2)

**Comment by tresf** [comment]
>  I wonder why my VST directory is set to `$HOME`

Can you please perform two unit tests:

1. Close lmms, move your `~/.lmmsrc.xml`, relaunch, see if it occurs.
2. Make the VST Plugins path in the settings dialogs blank, relaunch, see if it occurs.

If neither of these trigger it, we'll close out as invalid for now.  Adding a tripwire for known problematic paths is a fine solution if this becomes more common.  Auto-detecting requires a way to cache and compare canonical paths and that's something we can entertain as well if there are enough use-cases to justify it.

**Comment by JohannesLorenz** [comment]
In both cases, LMMS resets the VST path to $HOME/lmms/plugins/vst and the bug does not occur.

If you wish to close it now, that would be OK.
