### ISSUE TITLE
Upgrade method for broken sample paths

### ISSUE THREAD

**Issue by Lukas-W** [LMMS/lmms#3533]
#1719 introduced a bug that made all sample paths being saved as absolute in project files (reported in #3491).

 #3510 fixed the regression, but we should try to find a method to fix/relativize samples from existing projects since `1.2.0-rc2`.

**Comment by tresf** [comment]
Started the upgrade logic here https://github.com/tresf/lmms/commit/08581c55b07b3f0d4fe024b4b8d55e6986e0ea3a, but something's broken.  Can't get the debugs to fire.  Second set of eyes appreciated.

**Comment by tresf** [comment]
I had run into a self-inflicted snag checking for newer project versions.  I'm glad I did... Although first instinct is to honor this logic, making samples relative can fix an annoyance occurred when the LMMS WORKING DIRECTORY is misconfigured.  So I'm proposing to run this upgrade task on each run, thus no longer calling it an upgrade at all.   Thoughts and testing welcome.  PR available in #3540.

**Comment by tresf** [comment]
Fixed via #3510, we just didn't know it at the time.  Explanation here: https://github.com/LMMS/lmms/pull/3540#issuecomment-300448858
