### ISSUE TITLE
Please use CMake

### ISSUE THREAD

**Issue by berserk82** [LMMS/lmms#3536]
Hello there.
My name is Ivano Arrighetta and I'm Italian.
I would like to suggest to use CMake for creating build projects for Windows and Mac OS, other than Makefiles for *nix.

I'm pretty sure everyone would benefit from this.

Bye, Ivano.

**Comment by Lukas-W** [comment]
We are using CMake.

**Comment by berserk82** [comment]
Yes, you're right. I'm really sorry, I noticed *after* I downloaded the GIT repo.
Please excuse me.

**Comment by Lukas-W** [comment]
No worries.
