### ISSUE TITLE
MIDI Sustain ignored when envelope is on.

### ISSUE THREAD

**Issue by Umcaruje** [LMMS/lmms#3537]
While doing some testing for #1700 I noticed another bug.
In non-midi-based instruments when you have the envelope on, the sustain pedal gets ignored. 

Video of the behavior (first part of the video is the piano roll recording problem):
https://youtu.be/PA0mxaMIVrc?t=33s

**Comment by zonkmachine** [comment]
Confirmed. This bug is in 1.0.3 .

**Comment by zonkmachine** [comment]
I'm trying to bisect this one and #1700 .

**Comment by zonkmachine** [comment]
This doesn't seem connected directly to #1700 and seem to never have worked. I've gone back to around 0.4.15 .

**Comment by zonkmachine** [comment]
For some reason the 'close issue on merge task' didn't work for this one.
Fixed in #3730

**Comment by tresf** [comment]
> For some reason the 'close issue on merge task' didn't work for this one.
> Fixed in #3730

Because the PR wasn't against the [default branch](https://help.github.com/articles/closing-issues-using-keywords/).

**Comment by zonkmachine** [comment]
Ah, difawlt brawnch...
