### ISSUE TITLE
How to enable the metronome.

### ISSUE THREAD

**Issue by SolarPolarMan** [LMMS/lmms#3538]
How do I enable the metronome while recording?

![image](https://cloud.githubusercontent.com/assets/13716824/25782917/da89738a-334a-11e7-9e2c-483c5807d2d6.png)

It's not at the top as suggested in other places on the internet.

**Comment by Spekular** [comment]
Github isn't for support requests. You can try the [forum](https://lmms.io/forum/) or [discord](https://discordapp.com/invite/5kSc32Z).

That being said:
In 1.2 the metronome should be in the top bar, but as you're on 1.1.3 it might be elsewhere, I don't remember. Try checking your settings or using the "record and play" button (circle with a cut out triangle). If that doesn't work, you can make a bb track with metronome samples in it and use record+play as a workaround.

![image](https://cloud.githubusercontent.com/assets/8918426/25782962/092bddaa-3354-11e7-8d35-855ac9752770.png)
