### ISSUE TITLE
Enable MIDI clock

### ISSUE THREAD

**Issue by mendomusic** [LMMS/lmms#3539]
according to the following thread it does currently not seem to be possible to synchronise tempo through midi clock with external gear:
[How Can I Sync LMMS with External Midi Device's Midi Clock](https://lmms.io/forum/viewtopic.php?t=1555#p6733)

Please try to add this. It would make it possible to work with outboard gear.

**Comment by DBarthe** [comment]
Hello here,
Is there any plan to support external midi clock or jack-transport?
Do you have any workaround for this or even some instructions to start working on implementation?
Thanks

**Comment by Spekular** [comment]
Consolidating into #1472.
