### ISSUE TITLE
Compiling LMMS on Windows 10 using Visual Studio Community 2017

### ISSUE THREAD

**Issue by berserk82** [LMMS/lmms#3542]
As in the subject, how do I compile LMMS on Windows 10 using Visual Studio Community 2017?

Thanks in advance for any help.

Bye, Ivano.

**Comment by tresf** [comment]
Sorry, we do not yet offer MSVC++ support per https://github.com/LMMS/lmms/wiki/Compiling#compiler.

If you have experience setting up projects with MSVC++, please stop by our [Discord server](https://discord.gg/5kSc32Z), we have a `#devhelp` channel that we can discuss on.
