### ISSUE TITLE
Support for Windows Store via the Desktop Bridge

### ISSUE THREAD

**Issue by rogersachan** [LMMS/lmms#3546]
With the release of Windows 10 S, many consumers (and students like me) will be switched by their companies/schools/etc. to an OS that only supports applications from the Windows Store. Will this app be available eventually on the store?

**Comment by tresf** [comment]
> Will this app be available eventually on the store?

No, there are no plans to publish.  If there are ModernUI requirements, then it won't be possible.

Furthermore, the restrictions of choice that are being imposed stifle competition and innovation.  The decision to use Windows 10S for an educational desktop that plans to use classic desktop software like Gimp, LMMS, Pidgin, Putty, VirtualBox, Blender must be made very carefully.

**Comment by tresf** [comment]
Take this with a grain of salt, but this is a respected game developer expressing concerns about the Universal Windows Platform: https://soundcloud.com/polygon-newsworthy/4-tim-sweeney-on-microsofts-evil-plan

Microsoft has come back with open arms, but the task of switching to an "everything" platform really doesn't fly with a strictly C++ cross-platform project like LMMS.

VLC was able to [kickstart this idea](https://www.microsoft.com/en-us/store/p/vlc-for-windows-store/9wzdncrfj3t0?rtc=1) but this drastic change just isn't in our future.
