### ISSUE TITLE
Font really tiny on Windows 10, for 1.1.3 and 1.2.0 RC2

### ISSUE THREAD

**Issue by mavas** [LMMS/lmms#3547]
Hello,

On Windows 10, I downloaded and installed version 1.1.3, opened it up, and the font was incredibly tiny.

I uninstalled version 1.1.3, and then downloaded and installed the latest release candidate beta, and it was the same thing.

Thank you.

**Comment by musikBear** [comment]
@mavas 
Please read: 
http://lmms.io/forum/viewtopic.php?f=7&t=24335
Report back about the result.

**Comment by tresf** [comment]
@musikBear please be more responsible.  There are duplicate issues right here on the tracker that don't involve @mavas scrolling through a conversation on a different site.

@mavas, this is a duplicate #2510.

We a patched installer available here: https://github.com/LMMS/lmms/issues/2510#issuecomment-299253698

**Comment by mavas** [comment]
Thanks for the link; that's interesting.

I'm glad you folks are already aware of this and are working on it.

LMMS is awesome, thanks!

**Comment by tresf** [comment]
@mavas, did you try the patched installer?

**Comment by mavas** [comment]
I did just now and it works, thanks.
