### ISSUE TITLE
VST parameter changes do not take effect until after show/hide is toggled.

### ISSUE THREAD

**Issue by ilazarte** [LMMS/lmms#3548]
Windows 10 64 bit LMMS.  I'm working with Voxengo Boogex (http://www.voxengo.com/product/boogex/) although this happens with other Voxengo plugins and the u-He Tyrell N6 as well as other examples.

Basically, any change to the vst will kill sound, until a show hide is triggered on the vst, either through the plugin window itself or via the "hide controls" button in the fx tab.

**Comment by idoleat** [comment]
Same here.

**Comment by DomClark** [comment]
I can't reproduce this. Do you (or anyone else) still experience this in the latest beta version?

**Comment by musikBear** [comment]
>  (or anyone else)

I cant reproduce on Tyrell N6
I have testet:
* play notes manually on virt-kb with mouse 
* play notes manually pc-kb with mouse 
* insert notes in piano-roll and making live-vst changes
* insert notes in piano-roll and making live-LMMS-VST-ui changes

Tyrell plays changes emediately, and there is no need for toggles of any kind
winXPSP3 rc7 x32 @DomClark
Could be a x64 'thing'(?) -cant test
