### ISSUE TITLE
I moved the piano roll window too high now I cant move it down

### ISSUE THREAD

**Issue by FierceSavitar** [LMMS/lmms#3549]
![image](https://cloud.githubusercontent.com/assets/25285581/25911007/dcbde07e-35a1-11e7-9fc7-d6489f979365.png)

**Comment by tresf** [comment]
Have you tried using the scrollbar?

![image](https://cloud.githubusercontent.com/assets/6345473/25911059/7c4ed02a-3580-11e7-8fc3-48c237c0468b.png)

**Comment by FierceSavitar** [comment]
whoa you commented fast, and yes but Im talking about the piano roll window, I moved it too high and I want to make it the normal size

**Comment by FierceSavitar** [comment]
Thanks, it helped `how could I not see that`
