### ISSUE TITLE
Optional Linking preset-name and mixer-channel-name

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#355]
I would suggest a little button next to the FX-choice on the presets. Clicking it would add the instrument name as new name of the chosen mixer-channel. This feature is known from several other DAVs, and would be a workflow-enhancement.

**Comment by musikBear** [comment]
I addition to the connector, something like this ugly mockup 
![presetbuttonmockup](https://cloud.githubusercontent.com/assets/6662066/6901309/a0ace260-d70c-11e4-9fa5-df65317cfedf.PNG)

could enhance this further
As you may be able to conclude from the screenie, i like to have a ref to the FX-channel on the preset-button. I do that manually now, but that is messed up, if i move a FX-channel in mixer. A direct connected dispay, would be much better. In respect to placing, i 
would say, that the mute/solo buttons could be smaller, than they are now - Simple round diodes, would do fine -imo

**Comment by Wallacoloo** [comment]
In re: to the first request, right clicking on "fx" and selecting Assign To -> New FX Channel might do something close enough to what you want (it creates a new channel and sets the name to that of the instrument). If not, we could add a new option to the right-click menu, and perhaps an associated keyboard shortcut. I'm not sure the benefits of a dedicated button make up for the extra UI clutter, whereas the keyboard shortcut costs less (IMO) and would be trivial to document (make the option Right-Click -> "Assign To" -> "Current FX Channel (Ctrl+L)", or whatever the shortcut is).

A key distinction that should be made in the first request: If the instrument is routed to FX 12, and in the mixer I have FX 14 open/selected, what action should be performed? Should FX 12 just be renamed to the instrument name? Or should the instrument be routed to FX 14 and then FX 14 is renamed to the instrument name?

As for the second request (mixer slot number next to the instrument panel), I definitely support that. The main benefit I see is that I could just double-click the FX channel number next to the instrument panel and LMMS could take me straight to that FX channel. Also, a tooltip would do just fine in explaining what the number means to newcomers.

**Comment by musikBear** [comment]
>A key distinction that should be made in the first request: If the instrument is routed to FX 12, and in the mixer I have FX 14 open/selected, what action should be performed? Should FX 12 just be renamed to the instrument name? Or should the instrument be routed to FX 14 and then FX 14 is renamed to the instrument name?

oh no no - action made from the preset should not be influenced by any selection on the FX-mixer. Eg selected-FX-channel in mixer is irrelevant in respect to allocating the new preset *with* the name.
Again we need to look at how the current *work-flow* for *User want a new preset added to the project* is now:
Open FX-mixer
Add one new channel
Open My_instrument / My_presets / My_sounds
Drag new preset from either, and add to project
Open new preset
Name preset, it it is un-named
Allocate FX to newest created
<new feature> Press new naming-button (or as you suggest do a key combo)

Now the new preset & its name is linked and dispayed in FX-mixer on the chosen channel
In addition the fx_channel is also shown on the preset-button (eg second new suggested feature)

I believe this is the correct workflow for **current architecture**. A lot could be said about this, but current 'hen-and-egg' situations, results in the described workflow (imo..

**Comment by Wallacoloo** [comment]
Oh! I definitely misinterpreted your first request. It makes more sense now. I've never actually used presets in lmms, so I'll have to familiarize myself with them first.

**Comment by Umcaruje** [comment]
@musikBear Since #1627 was merged, I'm closing this as fixed, if you believe some parts of this request weren't implemented, please open a new issue.
