### ISSUE TITLE
Pianoroll background scrolling mismatch.

### ISSUE THREAD

**Issue by qnebra** [LMMS/lmms#3557]
My title is very inaccurate, so I explain it here.

![ituqirq](https://cloud.githubusercontent.com/assets/6345473/26074208/f0e945d0-397e-11e7-9df4-4dae074afbf4.gif)
*tresf edited, added screenshot to post*

1. Set time signature to non standard value (4/4 is standard).
2. Scroll pianoroll horizontally.
3. Expected: background synchronized with bars.
4. Really happen:

Time signature 5/4 gif as example.

**Comment by zonkmachine** [comment]
This? https://github.com/LMMS/lmms/issues/3389

**Comment by qnebra** [comment]
Well, no. On standard 4/4 all is correct, but if you set to 3/4 or 5/4 or some other unstandard "time sig" you should have glitches.
