### ISSUE TITLE
AudioFileProcessor deletes loop/start point after export

### ISSUE THREAD

**Issue by Mark-Agent003** [LMMS/lmms#3560]
Whenever I export a file from LMMS that uses AudioFileProcessor and I have edited the starting, loop, and ending points inside AFP, it resets them to the default values.  I am using 1.2.0 RC2.

**Comment by zonkmachine** [comment]
This https://github.com/LMMS/lmms/issues/2779 !

**Comment by Mark-Agent003** [comment]
@zonkmachine, does that mean this has been fixed? In what version?

**Comment by zonkmachine** [comment]
> does that mean this has been fixed? In what version?

Yes. Fixed in upcoming RC3.
