### ISSUE TITLE
LMMS  crashes when using VST

### ISSUE THREAD

**Issue by Andrew344** [LMMS/lmms#3561]
I use LMMS 1.1.3 (64-bit ver.) on Windows 7 64bit, аnd I have problem with VST plugins. 
Neither one doesn't work acceptable.
Watch the video: https://www.youtube.com/watch?v=FxKjCU7Bcao
This happens regardless of instrumemts, and number of track in project.
It can happens even if project is empty. 
I can't see what's error because, the terminal displays nothing.
![default](https://cloud.githubusercontent.com/assets/28777908/26202495/52026ac8-3be0-11e7-84fa-53ed465bc9b7.png)

![default](https://cloud.githubusercontent.com/assets/28777908/26202274/6d64d540-3bdf-11e7-9d21-f880c2f8384a.png)

At first I thought that the reason the memory is full, but judging from the readings of Windows task manager, the amount of used memory doesn't exceed 2.7 GB (4 GB total).
The antivirus program does not affect it too.

Therefore, most probably it's LMMS bug.

Sorry for my broken English.

**Comment by tresf** [comment]
FYI, Unlike Linux, Windows can't show terminal output without recompiling with the `mconsole` flag, which permanently makes `lmms.exe` open a command window on launch.  This is a limitation of the platform.  We will address this in a future release using a logging framework.

In regards to your problem, does it go away with the latest RC build? (At the time of writing this, 1.2.0-rc2)

**Comment by Andrew344** [comment]
Sorry, I forgot to write, in LMMS 1.2 this problem remains.

**Comment by musikBear** [comment]
@Andrew344 
Could you try with a VST that is on the list:
https://lmms.io/wiki/index.php?title=Tested_VSTs#Keys
I recommend MDA-piano, because it is tiny in dl and quite good as a piano emulator.
"Predator" is not tested

**Comment by Andrew344** [comment]
MDA piano works OK. Probably, I downloaded the wrong plug-ins. I'm not going to close the issue now. I will try to use different plugins for two more days, if the problem does not appear, the issue will be closed.

**Comment by Andrew344** [comment]
I will try another plugins.

**Comment by musikBear** [comment]
> MDA-piano works OK

Ok then that *Predator* is not 'liked' by lmms. A few VST instruments and more FX is that way. Its being looked at.
Does the CPU load stays high after loading?
The best VST in lmms is Synth1. You need to install, but both quality and cpu-load is magnificent
(Your ram-usage looks to be really high, are you running a lot of programs simultaneous with lmms? Soundcard using programs does not like that)

**Comment by Andrew344** [comment]
CPU usage is 20% max. I don't run many programs. It's antivirus, system control manager (needs for touch panel working), and qbittorrent.
 I can assume that the problem is in the error operating system because sometimes, I see a blue screens. It all appeared after use "cleaners". I will re-install Windows and then write about the results.
Thank you for help.

**Comment by Andrew344** [comment]
I re-installed Windows, and VST doesn't work. Again.  I install Visual C++ , and  it 's still doesn't work. 
![lmms](https://cloud.githubusercontent.com/assets/28777908/26263970/a09029ce-3ce3-11e7-95ac-fff691c6bf5b.png)
![lmms2](https://cloud.githubusercontent.com/assets/28777908/26263977/a66a032e-3ce3-11e7-8b68-fa7ede50689a.png)

**Comment by Andrew344** [comment]
ART PYRITE free works OK, but it's crashed after three minutes using. I will continue experiments.

**Comment by Andrew344** [comment]
I installed someone's plugins  from https://lmms.io/wiki/index.php?title=Tested_VSTs#Keys and it works OK, LMMS doesn't crash. I will use this. 

Thanks.
