### ISSUE TITLE
Translation error in the French version of the software (1.2.0-rc2)

### ISSUE THREAD

**Issue by DIpsum** [LMMS/lmms#3562]
There is a translation error in the French version of the software (1.2.0-rc2)

In "File" it says "Sauvegar**d**der en tant que **om**dèle par défaut".

Here's the correction: "Sauvegarder en tant que modèle par défaut"

**Comment by speedy-software-ch** [comment]
I think there is a .po or .mo translation file, or am i missing something?

**Comment by liushuyu** [comment]
Tagging our French translator @trebmuh

**Comment by Umcaruje** [comment]
@DIpsum please refer to https://github.com/LMMS/lmms/wiki/Creating-a-localization#how-to-create-a-translation

to help improve the translation

**Comment by DIpsum** [comment]
ok, I've send a request to join the Transifex LMMS team

@trebmuh

**Comment by DIpsum** [comment]
OK, I corrected the error in the Web Editor

**Comment by Umcaruje** [comment]
>OK, I corrected the error in the Web Editor
:+1:

**Comment by midi-pascal** [comment]
Merci :-)

**Comment by trebmuh** [comment]
Yep, good eyes @DIpsum .
I had already submitted a patch for those 2 typos 2 weeks ago ( https://github.com/liushuyu/lmms-translations/pull/7/files ) and that have been merged already. So I hope there will not be a conflict here. @liushuyu please, advise.
