### ISSUE TITLE
Pattern length does not change automatically while shifting notes

### ISSUE THREAD

**Issue by PhysSong** [LMMS/lmms#3563]
Hello,
I'm using LMMS 1.2.0-rc2.

When I press Ctrl(or Shift)+Left(or Right) to shift some notes in piano-roll, the note moves but pattern length does not change automatically.

I think adding m_pattern->updateLength(); to PianoRoll::shiftPos may solve this bug.

**Comment by BaraMGB** [comment]
If you want you can provide a pull request for your solution.

**Comment by PhysSong** [comment]
I know, but I wonder if there are any better solutions. If there's no better solution, then I'll make a pull request.

**Comment by PhysSong** [comment]
@BaraMGB I know, but I wonder if there are any better solutions. If there's no better solution, then I'll make a pull request.

**Comment by BaraMGB** [comment]
We should give it a try. Please make a pull request against stable-1.2

**Comment by BaraMGB** [comment]
Works like a charm.
