### ISSUE TITLE
New theme not active by default in 1.2

### ISSUE THREAD

**Issue by n-pigeon** [LMMS/lmms#3565]
When I've compiled 1.2 and tried it first time new theme didn't load properly.

I've fixed it going to `Settings` and changing `Theme directories` to `classic` and back to `default`.
I think it uses windows like `appdata` shortcut thats why it doesn't load correctly.

**Comment by Texxiliator** [comment]
Isnt that normal you dont have classic theme by default?

**Comment by n-pigeon** [comment]
@Texxiliator
Sorry if I wrote something confusing.

I've opened LMMS 1.2 and I had broken theme, some stuff were new theme some old.
I wanted to fix it, so first I've turned ON classic theme. It fixed it but looked like classic :P
Then I've turned ON new default theme and it looked like it should this time. It loaded properly.

I hope this clarifies things.

**Comment by BaraMGB** [comment]
@n-pigeon may be you haven't properly deinstalled the old version of lmms? You also have to remove the .lmmsrc file.

**Comment by BaraMGB** [comment]
Not answered in ten days. I close this issue. If this problem is not solved for you please inform us.
