### ISSUE TITLE
About C* Eq, C* Eq2x2 and Multiband EQ in LMMS 1.1.3 (French version in Win7)

### ISSUE THREAD

**Issue by ghost** [LMMS/lmms#3566]
About C* Eq, C* Eq2x2 and Multiband EQ in LMMS 1.1.3 (French version in Win7)

1) An error of labeling :

When you add C* Eq (=mono), it's C* Eq2x2 (=stereo) that appears 
When you add C* Eq2x2 (=stereo), it's C* Eq (=mono) that appears 

2) When you add C* Eq or C* Eq2x2, it appears that a notch filter is automatically applied to the signal at +/- 22 kHz (I see this through Sonogram SG-1). It seems that this is the only equalizer plugin that does this.

I think it's a notch filter because when I export my signal (e.g. a white noise), then I import it into the AudioFileProcessor and I detune it one octave down, well the sonogram tells me it would be a notch filter 

3) When you add Multiband EQ, It automatically increases the signal volume by a few dB and it delays the signal by a few ms. It seems that this is the only equalizer plugin that does this. 

Procedure for hearing the delay:
- in the BB Editor, use the Kicker with the parameter "Length" = 5 ms (to get a click sound)
- duplicate the Kicker
- add the Multiband EQ to one of the two
- activate a few steps and play them together

Procedure for hearing the volume increase:
- Activate and deactivate the Multiband EQ several times and keep an eye on the vu-meter of the master channel

**Comment by zonkmachine** [comment]
> 1. An error of labeling :
> 
> When you add C* Eq (=mono), it's C* Eq2x2 (=stereo) that appears
> When you add C* Eq2x2 (=stereo), it's C* Eq (=mono) that appears

Tested this in 1.2.1 and it looks like it's something going on here for sure.
I can't test this properly right now and no apparent wrongs pop up with a first attempt with 'grep'.
@tresf Can you look into this under https://github.com/LMMS/lmms/pull/4027?



> 2. and 3.

I think this would fall under upstream with the caps project. http://quitte.de/dsp/caps.html
Though the plugins delivered with lmms is currently quite a bit dated. See #4027

**Comment by tresf** [comment]
> @tresf Can you look into this under #4027?

I feel strongly that this bug should be fixed separately from the submodule.  The submodule is likely to never be merged, or worse, merged and break a bunch of backwards compat.

If the wrong plugin is inserting, we just need to debug why that's occurring and patch.  In 1.2.x, we host all of the plugin code in the repo, so it's our bug to fix, and then we can tarball a fix upstream if it still exists there.

At a glance, it's probably a simple off-by-one bug.

**Comment by zonkmachine** [comment]
Looking into this again and I think I know what's going on. C* Eq is mono and C* Eq2x2 is stereo. In lmms mono ladspa plugins opens up in stereo with an option to link the controls or have separate settings left/right. This looks confusing because one plugin that is mono (picture left) will appear as being stereo and a stereo (picture right) will have one set of controls so compared side by side one would agree that something is up with those plugins. The ladspa plugins are correct in this regard so I'm closing this as invalid.

![caps-eq](https://github.com/LMMS/lmms/assets/6368949/e84a921d-f529-4b1a-9494-9850633b2e82)
