### ISSUE TITLE
Exports .WAV as Backup File

### ISSUE THREAD

**Issue by Lechetunes** [LMMS/lmms#3574]
**Issue**: LMMS exports .wavs as a backup file.
![test export pic](https://cloud.githubusercontent.com/assets/28935168/26424800/aefe0954-408f-11e7-81e0-067b2625b035.png)
**Version**: 1.2.0-rc2
Had the issue for the last few months now. 
First saw problem when I updated to the 1.2 beta.

**Can Be Avoided by**
- Re-exporting through audacity.
- Exporting between loop markers.

**Export Settings**
File Format: .wav
Samplerate: 44100 Hz
Bitrate: 160 KBit/s
Depth: 16 Bit Integer
Interpolation: Sinc Medium
Oversampling: 1x
Export as loop: no
Export between markers: no

Project file that does this:
https://www.dropbox.com/s/t7tc0zx64ybxg0n/Future%20Bass%20.mmpz?dl=0

**Comment by tresf** [comment]
Sounds like https://github.com/LMMS/lmms/issues/764 which should have been fixed long ago in https://github.com/LMMS/lmms/pull/808.

**Comment by musikBear** [comment]
.BAK files are not wave-files in rc4 win32
Have they (.BAK) *ever* been ?
Never saw that, *ever*

**Comment by tresf** [comment]
@musikBear the OP never claimed it was an LMMS backup file. ;)

**Comment by zonkmachine** [comment]
The project title has a space before the suffix: **Future Bass .mmpz** I've never seen that with a project before. Maybe that's just fine. The exported project also adds this space to it. **Future Bass .wav**  Are you on windows? For me on Linux this project exports fine and it is recognized as a wav file and plays back fine although the samples are lacking so it's not a full test.

**Comment by tresf** [comment]
RC3 handles the space just fine on Windows 10.  I think it's something else.

![image](https://user-images.githubusercontent.com/6345473/32179219-3b5cb5d8-bd65-11e7-9206-b35fe0b8063b.png)

**Comment by zonkmachine** [comment]
OK. So the export crashes in some way before the file is finalized? I think the working copy is given it's final name in the very last step. @Lechetunes What sound settings are you using SDL? What OS/version do you use?

**Comment by tresf** [comment]
@zonkmachine this [may be true for the project file](https://github.com/LMMS/lmms/blob/32f07ac317b42dda42a1d00b0a3b1fa1feef0655/src/core/DataFile.cpp#L273), but is this also true for the rendered file?  I can't find the code that uses `.bak`.

**Comment by tresf** [comment]
I think the OP is making an assumption that this is a backup file.  I think it's just a file with no extension.  @Lechetunes please send us the actual file extension of this file.  You can drag it into a CMD window to find out.

**Comment by zonkmachine** [comment]
> I can't find the code that uses .bak.

It's the one you linked to. It's only used for the project files. The only one mentioning literally .bak is @musikBear and not the OP. I don't know where the rendered file is given it's name.

**Comment by musikBear** [comment]
well he does say 
> Issue: LMMS exports .wavs as a backup file.

That *backup* kind of sound like backup to me 🙊  :D 
(i dont think the OP knows about lmms' .bak at all:)
Kind of think that OP tried the export-feature, and expected mp3, but got the default wave..
If the OP also has hidden extensions on files, he will be unaware of what he has made.. idk.. 🤡me

**Comment by zonkmachine** [comment]
@Lechetunes Can you still reproduce this on 1.2.0-rc5 ?
If so, can you zip and upload a failed exported file here?

**Comment by tresf** [comment]
We've never had steps to reproduce.  Closing.  If evidence surfaces proving this is an actual bug, please request a reopen.
