### ISSUE TITLE
Music slower than its supposed to be?

### ISSUE THREAD

**Issue by B4Hire** [LMMS/lmms#3578]
For some reason the music is playing really slow, its very weird.

**Comment by Texxiliator** [comment]
??? 
Give us more info! We cant fix a problem when we dont know what or how it works!

**Comment by musikBear** [comment]
@B4Hire Sounds like a hidden 'global automation'
Right-click the BPM-gadget, and find the item

**Comment by tresf** [comment]
Per @musikBear please see https://lmms.io/wiki/index.php?title=Working_with_Automation#Song-global_automation.

If this doesn't fix it, let us know and we'll reopen.

**Comment by B4Hire** [comment]
@Texxiliator Instead of the music going regular time, a second is taking longer than it should have so its going kinda like slow motion. When I first downloaded lmms it didn't have this problem so idk if I pressed something and made it go like that.
@musikBear I tried to remove global automation from the BPM but it didn't change the music really. It made it a little faster but it wasn't the normal speed it used to be, it was still slow.
My version of lmms is 1.1.3, I'm not sure where to find the OS or what a mmp is (Sorry I got lmms yesterday I don't know either of those terms). 
Thanks for the help.

**Comment by zapashcanon** [comment]
> I'm not sure where to find the OS

Are you using Windows, Mac OS X or Linux ?

**Comment by B4Hire** [comment]
Windows

**Comment by tresf** [comment]
> @Texxiliator Instead of the music going regular time, a second is taking longer than it should have so its going kinda like slow motion. 

Please change sound settings to SDL and reboot your computer and post your results.

**Comment by B4Hire** [comment]
@Texxiliator <https://github.com/texxiliator> That fixed it, thanks
