### ISSUE TITLE
"Time-line position marker" GUI bug in "Song-Editor".

### ISSUE THREAD

**Issue by Hussam-Eddin-Alhomsi** [LMMS/lmms#3581]
This is how the "time-line position marker" looks after opening LMMS:
![lmms song position 1](https://cloud.githubusercontent.com/assets/25503477/26524757/a8730224-4346-11e7-8aa2-24bfe6b8a378.PNG)
This is how the "time-line position marker" looks after moving it/playing the song (this is how it should look like, right?):
![lmms song position 2](https://cloud.githubusercontent.com/assets/25503477/26524762/d99a760c-4346-11e7-8666-daed94636083.PNG)

**Comment by musikBear** [comment]
sorry cant see any difference - can you make pictures that only focus the issue, and not the whole screen. Pictures look identical to me

**Comment by Umcaruje** [comment]
ah I get it, it doesn't extend to the end of the screen when it gets loaded, yeah this is a bug
