### ISSUE TITLE
LMMS's native samples.

### ISSUE THREAD

**Issue by Hussam-Eddin-Alhomsi** [LMMS/lmms#3586]
I was browsing through LMMS's native sample and I found some bad issues that need to be fixed:
•  Bad naming, sorting and grouping.
• The peak amplitude of the samples isn't consistent.
• Unnecessary silence.
• Most of the samples use the Ogg file format which is a lossy compression format.
• Unwanted noise and compression artifacts.
• Aliasing.
• Click, pops.

Where do these samples come from and who is the team that is in charge of them?

I'm not hating on the samples or anyone who is involved in them but I want them to be as good as they can be. 😄

**Comment by Hussam-Eddin-Alhomsi** [comment]
Fixing these issues is essential.
I have experience in audio editing and I would like to work on them or add new ones.
Where can I start?

**Comment by Spekular** [comment]
There's an initiative to completely replace the default samples, which would most likely fix all of the above issues as well. Check out the LMMS samples repository here: https://github.com/LMMS/samples

You can also get on Discord, there's been some discussion of the sample project there as well:
https://discordapp.com/invite/PHcQDx3

**Comment by Umcaruje** [comment]
The samples replacement project is ongoing on https://github.com/LMMS/samples @iamwontolla took point on this and already made some samples. There is always help needed on actually discussing and testing the samples, but that is all handled in the other repo.

Also if you ever want to talk with us directly, the easiest way is our discord server: https://discord.gg/PHcQDx3

**Comment by Umcaruje** [comment]
@Spekular ninja'd

**Comment by musikBear** [comment]
Important!

**Comment by musikBear** [comment]
-remember **not** to use **file-names** already used in current packs, that would destroy existing projects. That would be a bad thing.

**Comment by SirBothersome** [comment]
> The samples replacement project is ongoing on https://github.com/LMMS/samples @iamwontolla took point on this and already made some samples. There is always help needed on actually discussing and testing the samples, but that is all handled in the other repo.

@Umcaruje So I guess @unfa and my work is just gonna sit in Limbo then? ;-; I've had two PR's sitting there for months... Whatevs tho

**Comment by tresf** [comment]
> I've had two PR's sitting there for months... Whatevs tho

Let's discuss those in the samples repository and/or Discord please.  At the time of typing this there are 47 open pull requests for the codebase alone.  We are backlogged and samples are lower on that priority.

**Comment by musikBear** [comment]
> The same file names should be reusable so as long as their contained in different folders.

in Principe yes, but it would be so natively wrong to have different data with same names. Current samples will be preserved by everyone that has used lmms before the arrival of a **new** (up till now elusive) sound-sample-pack, and it will be hell for those users (us) if different data-elements has same names 
Lets for GS avoid that!
And **LOCK** this now, and force this issue to discord!

**Comment by tresf** [comment]
> that would destroy existing projects. 

> > it would be so natively wrong

Two separate arguments but I don't disagree.  It's quite common sense to not use the same name twice in an interface but the severity is much different.

> Lets for GS avoid that! And LOCK this now, and force this issue to discord!

More appropriately, discord and the samples repository.  I recommend anyone that is not already subscribed to the samples repository but interested in following these types of topics to do so here:

https://github.com/LMMS/samples/subscription

Discord, for those not aware is available here:
https://discord.gg/3sc5su7

**Comment by musikBear** [comment]
I want to 'reopen' this, because a producer & new forum user, has offered to make samples for LMMS. 
By 'reopen' i mean *scratch all above*, and restart a **new** conversation about new samples.
I had to browse through 150 threads, with the keyword *'Samples'*, before i got this hit.. It is also strange that *new samples* is not mentioned in consolidation-page *"Better-workflow"*.
Here is a link to the forum-topic, with his offer:
https://lmms.io/forum/posting.php?mode=quote&f=4&p=72615
-If a new issue is preferred instead of reopening *this*, then lets do *that*

**Comment by tresf** [comment]
@musikBear the goal is to use this repo: https://github.com/LMMS/assets

**Comment by musikBear** [comment]
That is brilliant. I will refer him to the page. 👍
