### ISSUE TITLE
sampletrack mutes the playing sample by muting a different one

### ISSUE THREAD

**Issue by BaraMGB** [LMMS/lmms#3590]
![mutingsampletrack](https://cloud.githubusercontent.com/assets/6502580/26573085/add4c1b2-451c-11e7-9538-bdc66b076f52.jpg)

By muting/unmuting a sample on a sampletrack the playing sample will be muted, too.

**Comment by PhysSong** [comment]
Changing sample file of other sample track object also mutes the playing sample track, too.

https://github.com/LMMS/lmms/blob/stable-1.2/src/tracks/SampleTrack.cpp#L168
Engine::mixer()->removePlayHandlesOfTypes( getTrack(), PlayHandle::TypeSamplePlayHandle );
in SampleTCO::playbackPositionChanged()

It removes play handle(s) of currently playing sample(s). I think it causes this problem.
