### ISSUE TITLE
Fix semantic versioning

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms#3594]
We've been using the `1.0.0-rc1` style releases, however this is not proper.

According to semantic versioning, it should be "rc.1" instead of "rc1". (e.g. `2.0.0-rc.1`)

http://semver.org/spec/v2.0.0-rc.1.html

**Comment by Umcaruje** [comment]
The RC4 release is now on a `v1.2.0-rc.4` tag. I suggest we close this issue out and have correct versioning for all consecutive releases, starting from RC4.

**Comment by tresf** [comment]
Have we unit tested this against our internal comparators?

**Comment by Lukas-W** [comment]
The way I understand the spec, "rc1" is not a violation. Pre-release versions may be dot-separated, but don't have to be. Dot-separated identifiers that contain letters are compared lexicographically. So `rc1` < `rc2` holds true. We're fine as long as we don't reach `rc10`.

**Comment by tresf** [comment]
Correct, we'd be betting on the chance we never hit 10, which isn't a violation, but also is not proper.

**Comment by Lukas-W** [comment]
> which isn't a violation, but also is not proper

Agreed.

I just wanted to share the way pre-release versions are sorted according to the specification (see [point 11](http://semver.org/spec/v2.0.0.html#spec-item-11)), because of what switching mid-release will mean: `rc.4` < `rc3` because `rc` < `rc3`! Better not start with RC4.

**Comment by Umcaruje** [comment]
>because of what switching mid-release will mean: rc.4 < rc3 because rc < rc3! Better not start with RC4.

Thanks for the insight, I reverted the change for RC4 on the draft release

**Comment by Hussam-Eddin-Alhomsi** [comment]
I think we should omit the 0s to the right of the version number. They're as useless as having 0s to the right of a decimal number.
For example: `1.2.0` should be `1.2`.

**Comment by tresf** [comment]
@Hussam-Eddin-Alhomsi, we increment this zero to a one when we release a patch to a stable version.  This has happened every single release.  Truncating the zero would be more work than what it's worth.

**Comment by Spekular** [comment]
Now that #5636 is merged I think we can definitely consider this closed. If anyone disagrees please feel free to reopen w/ justification!
