### ISSUE TITLE
"Beat+Bassline Editor" excess steps GUI bug.

### ISSUE THREAD

**Issue by Hussam-Eddin-Alhomsi** [LMMS/lmms#3600]
When you have a track in the "BB E" with this bug: https://github.com/LMMS/lmms/issues/3598 and then add steps, this is what happens:
![bug 4](https://cloud.githubusercontent.com/assets/25503477/26633251/6ebd9580-461b-11e7-98c7-97d5868f2911.png)
^ The first track is normal, the second has the bug.
This bug can go away by removing steps to the minimum steps in the "BB E" that is 16 steps.

**Comment by zonkmachine** [comment]
Since this is not an issue if you press play and the pattern is visible before you add steps, it's probably just another aspect of https://github.com/LMMS/lmms/issues/3598 and not an issue of its own.

**Comment by zonkmachine** [comment]
I found that this issue is introduced in the same commit as #3598
