### ISSUE TITLE
Beat+Bass patterns go over grid

### ISSUE THREAD

**Issue by ghost** [LMMS/lmms#3606]
The title says it all. The beat + bass patterns : 
![image](https://cloud.githubusercontent.com/assets/22986832/26760525/fce59748-491a-11e7-8df9-0f9b233f6519.png)
goes over the grid.
We could do something like this to prevent it : 
![image](https://cloud.githubusercontent.com/assets/22986832/26760530/20da1a16-491b-11e7-8b40-df0753243069.png)
and also this : 
![image](https://cloud.githubusercontent.com/assets/22986832/26760532/2ab3f19c-491b-11e7-8b22-fac21125d4d7.png)
on the left is the original and on the right is the edited.

**Comment by RebeccaLaVie** [comment]
@Texxiliator Can you update your screenshots with the default theme so that I can better understand your issue?

**Comment by Texxiliator** [comment]
@RebeccaLaVie yeah 
![image](https://cloud.githubusercontent.com/assets/22986832/26828446/bf380900-4ac1-11e7-96e5-7504aa9107e8.png)
![image](https://cloud.githubusercontent.com/assets/22986832/26828461/d47ef346-4ac1-11e7-953b-95c8c163d87e.png)
![image](https://cloud.githubusercontent.com/assets/22986832/26828465/d868bc58-4ac1-11e7-8b05-4a60a7f01561.png)

**Comment by Umcaruje** [comment]
Note that this is intentional with regular patterns cause they have an actual border. The reason BB patterns are borderless is to fit nicely inside the BB editor. Now this has always been an edge-case but I suppose we could add a border to BB tracks that are in song editor.

**Comment by Texxiliator** [comment]
*update* This happens to everything : 
![image](https://user-images.githubusercontent.com/22986832/26961167-220d95b4-4cdd-11e7-9ce8-1b72061d62b7.png)

**Comment by Spekular** [comment]
Patterns are supposed to go over the grid, and they have notches every bar.

**Comment by musikBear** [comment]
> update This happens to everything :

Nono! as specular says that is intended! Think about it:  it would be absurdly confusing if you move a block, and have no idea what actually is part of the block, before it is moved. There should not be grid over blocks!

**Comment by RebeccaLaVie** [comment]
The OP is no longer on github, so I can't really investigate their problem with the grid much further, but I do think the borderless empty tracks might be a valid issue, in addition to adding a border to BB tracks that are in song editor.

![d868bc58-4ac1-11e7-8b05-4a60a7f01561](https://user-images.githubusercontent.com/7960169/26992353-20f7a2ce-4d13-11e7-8fd7-6a5e44b11dd4.png)

I wonder if anyone else has had any difficulty with this?

**Comment by musikBear** [comment]
> I wonder if anyone else has had any difficulty with this?

Doubt it :´) - imho no reason to spend any time on this

**Comment by Texxiliator** [comment]
@RebeccaLaVie i still am on github just on diffent account :^)

**Comment by zonkmachine** [comment]
No recent action here. I don't think this should hold back RC4. I suggest removing it from the RC4 project.

**Comment by Umcaruje** [comment]
agreed.
