### ISSUE TITLE
Crash when clicking "Quantize" in a Piano-Roll with no pattern

### ISSUE THREAD

**Issue by styken** [LMMS/lmms#3608]
Reproduce:
1 - open pianoroll
2 - press quantize

**Comment by Texxiliator** [comment]
Nothing happens 
atleast for me

**Comment by Texxiliator** [comment]
What OS are you using?

**Comment by karmux** [comment]
I can reproduce.

**Comment by DeRobyJ** [comment]
I cannot reproduce in Windows 8.1 or Windows 7, 64-bit

**Comment by styken** [comment]
Do you have an empty roll? I only have the text "Please open a pattern...".
Then I press 'Q' to the left of the scissors.

**Comment by Hussam-Eddin-Alhomsi** [comment]
The issue's title should be "Quantizing in Piano-Roll causes a crash.".

**Comment by zonkmachine** [comment]
Closed in https://github.com/LMMS/lmms/pull/3609
