### ISSUE TITLE
xml structure of project-notes

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#3610]
I have serious problem with a project. The project will load to 98%, and then it revert to 82% and freeze. 
Studying the xml of the mmp, i found a quite complex structure of the xml in the project-notes:
`
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:12pt;">der bruges ENTEN </span></p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:12pt;">wilted hats </span></p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:12pt;">ELLER</span></p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:12pt;">wilted tick</span></p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:12pt;">IKKE begge</span></p>
<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;"><br /></p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:12pt;">OG</span></p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:12pt;">ENTEN ticker</span></p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:12pt;">ELLER</span></p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:12pt;">wilt</span></p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:12pt;">--------------------</span></p>
<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;"><br /></p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:12pt;">A#min</span></p>
<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;"><br /></p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:12pt;">nye repeaters i percussion build fase</span></p>
<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;"><br /></p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:12pt;">07 er med en volume intensing over tyime på arp -med det mudrer vist</span></p>
<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;"><br /></p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:12pt;">08 droppet sqeak sekvensen helt, indsat en forsigtig repeater</span></p>
<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;"><br /></p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:12pt;">086 droppt whitle og ændret pluck solo til 3 okt over</span></p>
<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;"><br /></p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:12pt;">09 tilføjet en subttle coxy roll uder det meste, og ændret 1. strofe lidt</span></p>
<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;"><br /></p>
<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;"><br /></p>
<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;"><br /></p>
<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;"><br /></p>
<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;"><br /></p>

`
Unfortunately, removing project-notes did not change the 98 to 82% revert jump, so *that* problem is apparently unrelated (my thoughts was that usage of æøå could have been an issue)
Is this xml structure not extremely over complicated?
Looks like each cr-lf creates a new style definition 

It does not look like the actual code can be in code-tags, Inserting code-tags `code` converts the code to the actual *project-note-text* i will add a screenie of the xml copied from the project mmp-file.

**Comment by musikBear** [comment]
Better picture:
![xml](https://cloud.githubusercontent.com/assets/6662066/26763356/00ff7fe2-4952-11e7-8401-193ce02148b3.PNG)

**Comment by tresf** [comment]
If you have a project that freezes lmms, please share, and let a developer debug.  It's a waste of time for everyone involved to speculate.  `CDATA` tags are always hard to read because it's HTML inside HTML.  A quick Google search would have discovered this.  Also, you should use code  tags for  XML raw data, not a picture.  This bug report is not of acceptable quality.  Please clean it up or it will be closed.

**Comment by musikBear** [comment]
>  It's a waste of time for everyone involved to speculate.

I only ask if the project notes are over complicated in structure.
With respect to the freeze, i can read the mmp myself, and i have discovered something interesting, that perhaps can explain the chunk issue: #493
I suspect that vst-ui controllers of non-dial or slider type, one example could be a x-y-patch, actually make one entry in the chunk for each **possible** point position!
Synth1 is properly the most benign VST of all i know of, Synth1 has a very tiny chunk 3040 chars, and it also a very simple UI. No co-ordinate controllers, drawed sequencer settings.

**Comment by tresf** [comment]
CDATA and chunk are considerably different.  CDATA is verbatim, usually HTML parsable data that is intentionally embedded inside HTML to about overkill character escaping.

Chunk data on the other hand is binary/blob data that cannot be represented with a CDATA chunk, but is usually encoded onto the ASCII-compatible base64 encoding scheme, which allows something as complex as an image or a bunch of raw data types to be safely stores in a clear-tex HTML or XML document.  Base64 usually like like this "AFGB...==".  CDATA generally looks like HTML.

Project notes don't really take much time to load (DOM parsing is < 50ms generally.  On the other hand, loading 10 copies of calf.dll or tripleoscillator.dll can take time.

The mismatched loading is probably due to some order of operations (non-equal) loading of instruments, effects, controllers.  Cart-before-horse problems.

**Comment by musikBear** [comment]
> Project notes don't really take much time to load (DOM parsing is < 50ms generally.)

Ok, then no reason to look into the structure with the abundance of identical style defs. 👍
