### ISSUE TITLE
Code question for Whom did implement the VST-dial array

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#3612]
I have a question for the dev that implemented the array of automateable VST controllers:
Is there is a way to discover, if a controller *on the VST* is saved as a automateable lmms-controller in that array?
If so, maby #493 can be solved

**Comment by tresf** [comment]
@musikBear can you please move this discussion to #493 as well as your thoughts?  Opening a brand new bug report to pin down a developer isn't the right way to bring attention to an already open issue.

**Comment by musikBear** [comment]
done, doubt it will catch the person in questions eyes
