### ISSUE TITLE
24-bit export noise. Integer overflow.

### ISSUE THREAD

**Issue by zonkmachine** [LMMS/lmms#3616]
At levels over +/- 1.0f the signal will fold over.

![24bitclip](https://user-images.githubusercontent.com/6368949/26849761-9f232c14-4b05-11e7-8568-4dbc55a81cd0.png)

@michaelgregorius

**Comment by michaelgregorius** [comment]
Fixed by #3617. All wave exports will now clip data to 1.0 or -1.0 like it was already done for the 16 bit and 32 bit exports.
