### ISSUE TITLE
"Effects chain" & "User controller" LEDs should be responsive

### ISSUE THREAD

**Issue by Sawuare** [LMMS/lmms#3620]
This button ![effects chain](https://user-images.githubusercontent.com/25503477/26935803-8fd417b6-4c75-11e7-9619-5e150ef55431.png) turns on automatically when an effect is added in the effects chain of a mixer track or in the effects chain of an instrument plug-in. Why doesn't it turn off automatically when there are no plug-ins, too?
Lesser clicks and time, better UX.

**Comment by tresf** [comment]
Slightly off-topic, but I feel the controller dropdown should behave like the EFFECTS CHAIN and select the LED for you.  Good proposal.

**Comment by Hussam-Eddin-Alhomsi** [comment]
@tresf 
Which "controller dropdown"?

**Comment by tresf** [comment]
@Hussam-Eddin-Alhomsi this one... 

![screen shot 2017-06-12 at 11 43 10 pm](https://user-images.githubusercontent.com/6345473/27065052-f0336c64-4fc8-11e7-825b-452f1607d6f6.png)

**Comment by RebeccaLaVie** [comment]
@Hussam-Eddin-Alhomsi  I agree :100:%

The controller LED should definitely automatically enable when someone selects an option from the dropdown. @tresf should a separate issue be created for the controller or do you think this is related enough that one issue can cover both LED proposals?

**Comment by tresf** [comment]
>  @tresf should a separate issue be created

Separate, unless the PR gets ambitious. :)

**Comment by Hussam-Eddin-Alhomsi** [comment]
I noticed different behaviors between the the LEDs in LMMS:
• The "**EFFECT CHAIN**" & "**USER CONTROLLER**" LEDs allow the user to add/set a value without turning the LED on first and their LEDs turn on when a value is added/set by the user.
• The "**ENABLE MIDI INPUT**", "**ENABLE MIDI OUTPUT**" & "**CUSTOM BASE VELOCITY**" LEDs don't allow the user to set a value without turning the LED on first.
• The "**FILTER**", "**STACKING**", & **ARPEGGIO**" LEDs allow the user to set a value without turning the LED on first, but when the user does, they don't turn on.

IMO, the all of the LEDs above except the "**ARPEGGIO**" LED should:
• Allow the user to set a value without turning the LED on first.
• Turn on when their value is changed.
• Turn off when they are set to their default/not-active value.

**Comment by Sawuare** [comment]
When there are any user controllers, the first one is automatically selected, so I think the user controller LED behavior is fine as is.
![image](https://user-images.githubusercontent.com/25503477/38621070-bfd21808-3da8-11e8-838c-abaab4ea940c.png)

**Comment by tresf** [comment]
> When there are any user controllers, the first one is automatically selected, so I think the user controller LED behavior is fine as is.

When clicking the drop-down though the LED does not get selected which needs to be addressed.

**Comment by Sawuare** [comment]
@tresf Got it. I implemented the functionality for both LEDs and will open a PR soon.

**Comment by Sawuare** [comment]
Closed via https://github.com/LMMS/lmms/commit/f7a0553e6a505d6a81e3e7ffbc1d6090ace7daf0.
