### ISSUE TITLE
Triple Oscillator - knob friction on negative values

### ISSUE THREAD

**Issue by DeRobyJ** [LMMS/lmms#3622]
- Open triple oscillator
- In the plugin tab, try to turn down any knob to negative values

Turning down while on positive values is ok, turning up is always ok, the bug happens only when turning down while on negative values.

**Comment by zonkmachine** [comment]
I believe this 'stickyness' was fixed in https://github.com/LMMS/lmms/pull/3597

**Comment by BaraMGB** [comment]
Yes that is fixed.
