### ISSUE TITLE
Equalizer: Enable the user to switch the windowing function used by the analysis display

### ISSUE THREAD

**Issue by michaelgregorius** [LMMS/lmms#3625]
Enable the user to switch the [windowing function](https://en.wikipedia.org/wiki/Window_function) used by the analysis display of the Equalizer plugin:
![equalizer-current](https://user-images.githubusercontent.com/9293269/27002027-7de82f70-4dd7-11e7-9155-2872876cede6.png)

See #2703 and #3530 for more details.

**Comment by PhysSong** [comment]
I think this things are needed:

- Add a combo box to select window functions
- Add a LED button to turn on/off FFT windowing
- Implement various window function generators
- Update windows buffer(maybe need to be thread safe)

Then it will be a very cool feature.

**Comment by PhysSong** [comment]
@michaelgregorius We already have hamming window and hanning window in fftw_helper.cpp, and we can implement other window functions like that.
See https://github.com/LMMS/lmms/blob/stable-1.2/src/core/fft_helpers.cpp#L59

**Comment by PhysSong** [comment]
I'm trying to implement it, see my eq-test branch.
I also found bug #3654 while testing it. It should be fixed to make my implementation work well, but this isn't necessary.

**Comment by curlymorphic** [comment]
@PhysSong 

I like this, I shall test out later, but the code all looks good, Are you planning on implementing other fft windows, such as Blackman-Harris, as this would then compliment #3530.

**Comment by PhysSong** [comment]
Consolidated into #4395.
