### ISSUE TITLE
Equalizer: Enable the user to change the buffer size used for the analysis display

### ISSUE THREAD

**Issue by michaelgregorius** [LMMS/lmms#3626]
The current implementation of the Equalizer's analysis display uses a buffer size of 2048. Enable the user to switch the buffer size to larger and smaller sizes as a trade off between accuracy and latency:
![equalizer-current](https://user-images.githubusercontent.com/9293269/27002055-e858110e-4dd7-11e7-81fd-ffdd8973d703.png)

See #2703 and #3530 for more details.

**Comment by PhysSong** [comment]
Consolidated into #4395.
