### ISSUE TITLE
Edit > Settings:  Restart notification behaviour.

### ISSUE THREAD

**Issue by mikobuntu** [LMMS/lmms#3627]
Hi guys I think the popup window below should not be shown unless we have actually changed a setting in 
 Edit>Settings.
![restartnotification](https://user-images.githubusercontent.com/335217/27004432-13e20964-4e01-11e7-9e16-a5654521c9de.png)

* Right now the default behaviour is to show the Restart notification even if we don't click on anything in the settings window

**Comment by Texxiliator** [comment]
Yeah this should be fixed.

**Comment by tresf** [comment]
I vote we take it a step further and not be vague.  Something like a boolean flag for notifying only when an actual restart setting was changed, then make the wording explicit.

**Comment by follower** [comment]
Related to #2109?

**Comment by Sawuare** [comment]
> I vote we take it a step further and not be vague. Something like a boolean flag for notifying only when an actual restart setting was changed, then make the wording explicit.

Implemented in #3820:
`• Changed the restart warning from a QMessageBox to a QLabel that is shown when a setting that requires restarting is changed.`

Closing.
