### ISSUE TITLE
Can I disable Wine dependancy when building?

### ISSUE THREAD

**Issue by unfa** [LMMS/lmms#3628]
I can't install any wine-dev package. I don't need it though, because I won't use any VSTs.

How can I disable VST support so I can build LMMS without the Wind dependancy?

**Comment by zonkmachine** [comment]
Add `-DWANT_VST=OFF` to your cmake command should do the trick.

https://github.com/LMMS/lmms/wiki/Compiling

**Comment by unfa** [comment]
It works, thank you!
