### ISSUE TITLE
How to enable ZynAddSubFX when building 1.2.0 RC3 from source?

### ISSUE THREAD

**Issue by unfa** [LMMS/lmms#3629]
I've managed to build LMMS 1.2.0. but I have no ZynAddSubFX instrument available.
I don' have any zynaddsubfx-dev packages available, what should I do to have that?
Also - the Cmake configuration screen didn't list anything I could install to have ZynAddSubFX onboard.

**Comment by karmux** [comment]
Do you have FLTK development files installed?

**Comment by unfa** [comment]
I don't think so. I'll try installing them and building again.

**Comment by tresf** [comment]
@unfa for future reference, we have a `# devtalk` channel on [Discord](https://discord.gg/3sc5su7) that would have yielded the same answer but much quicker.

**Comment by unfa** [comment]
Ok, I've installed libfltk1.3-dev and updated my local repo from Git. WHen I run cmake I got this:

```
CMake Error at /usr/lib/fltk/FLTK-Targets.cmake:102 (message):
  The imported target "fluid" references the file

     "/usr/bin/fluid"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/usr/lib/fltk/FLTK-Targets.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  /usr/lib/fltk/FLTKConfig.cmake:13 (include)
  /usr/share/cmake-3.5/Modules/FindFLTK.cmake:146 (include)
  CMakeLists.txt:381 (FIND_PACKAGE)


-- Configuring incomplete, errors occurred!
```
