### ISSUE TITLE
Feature Request: Concatenate subsequent patterns (segments)

### ISSUE THREAD

**Issue by Raltux** [LMMS/lmms#3633]
Alas, Ubuntu Xenial provides an old version of LMMS (=1.1.3-1build1), maybe it is fixed already:

It is neither possible in a straight forward way, to copy patterns within the same track, nor can
I then combine two subsequent patterns to one pattern (merge, melt, concatenate).

There is so many good things to say about LMMS, I think this feature would make it perfect.

Thanks
Raltux

**Comment by BaraMGB** [comment]
Yes, I planned to implement such a knife tool for sample tracks. For an melt or glue tool we would do a little bit more. For this the track content object needs to be able to have more than one sample buffer.

**Comment by tresf** [comment]
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.
