### ISSUE TITLE
Sound/Settings issue

### ISSUE THREAD

**Issue by XXDrown** [LMMS/lmms#3635]
I go to Edit>Settings and to sound, and select the audio interface (Port Audio) and select the "Backend" and "Device", and click okay. Window pops up and says that most changes won't take effect until LMMS is restarted. I click okay, and I'm in. The only problem is that it can't play sound. I go back to the settings and it's back on dummy (no sound). I change it again to what I had previously, and click okay.

Still doesn't work, and I have no idea how to fix this. Is this a common problem where I have to reinstall LMMS to have it work properly, or is it just me?

**Comment by Spekular** [comment]
Have you tried restarting LMMS after changing the device? If that doesn't
work, try changing the setting, saving a project, and then restarting LMMS.

**Comment by musikBear** [comment]
@XXDrown If you use windows the correct setting is SDL
https://lmms.io/wiki/index.php?title=LMMS_Settings#Audio_Settings
This not a general lmms issue, so forum http://lmms.io/forum/ is the correct place for more discussion/ help

**Comment by XXDrown** [comment]
The settings that I select don't save.

**Comment by musikBear** [comment]
> The settings that I select don't save, and I don't quite understand why.

That is because of a file you need to get rid of:
https://lmms.io/wiki/index.php?title=LMMS_Settings#Problems_with_Settings
After lmms have failed with an install, *that* file will be a problem.
If *this* does not fix it, make an account in forum http://lmms.io/forum/

**Comment by zonkmachine** [comment]
@XXDrown Can you please test this with the latest lmms-1.2 beta?
(rc4 is the latest right now and rc5 is just around the corner)
https://lmms.io/download/#windows

**Comment by zonkmachine** [comment]
No response, closing.

@XXDrown Please reopen if you can reproduce this on a later build, RC5 or later.
