### ISSUE TITLE
ArchLinux Dell XPS 13 / HiHDPI

### ISSUE THREAD

**Issue by trmendes** [LMMS/lmms#3638]
Hi there!
Just installed the LMMS Version 1.1.3 and the icons and the fonts are too small. Can't really work on it.
Any theme to fix it?

**Comment by tresf** [comment]
Duplicate of #2510.  No, we don't have a fix for Linux.  We found a workaround for Windows for the 1.2.0 beta, but we're not aware of a workaround for Linux at this time. Ideas welcome.

**Comment by tresf** [comment]
Some more documentation is available here: http://doc.qt.io/qt-5/highdpi.html

**Comment by trmendes** [comment]
Thanks :)...gonna check it
