### ISSUE TITLE
                                                        .

### ISSUE THREAD

**Issue by Texxiliator** [LMMS/lmms#3644]

**Comment by zonkmachine** [comment]
@Texxiliator Why did this issue get deleted?

**Comment by RebeccaLaVie** [comment]
It looks like this was originally an issue about adding flags to the translation options on the website?

**Comment by Umcaruje** [comment]
It was decided on discord that we won't be adding flags to the website or the program because a single flag can't represent a language, since a language can be spoken in many countries.

**Comment by RebeccaLaVie** [comment]
@Umcaruje That makes sense.

@Texxiliator In the future, please do not erase all of the information before closing issues. It is also easier to keep track of everything if a comment is added to explain why it has been closed, especially to bridge the gap on any communication that might have taken place on Discord. :+1:
