### ISSUE TITLE
Instrument plug-ins tab memory.

### ISSUE THREAD

**Issue by Hussam-Eddin-Alhomsi** [LMMS/lmms#3646]
Each instrument plug-in has 5 tabs. The "plugin" tab is only 1/6 of the total tabs an instrument plug-in. Clicking on an instrument plug-in always opens its "plugin" tab. It'd be useful if the instrument plug-in memorizes what tab was open the last time before it was closed, and re-open this tab the next time the user opens the instrument plug-in.

**Comment by musikBear** [comment]
Duplicate of #1843

**Comment by Hussam-Eddin-Alhomsi** [comment]
Closing this because it's a duplicate of #1843.

**Comment by SecondFlight** [comment]
Instead of reopening this (as per comment in #1843), I'm adding it to #4877.
