### ISSUE TITLE
Text missing on the envelope tabs with Classic theme.

### ISSUE THREAD

**Issue by zonkmachine** [LMMS/lmms#3652]
Since 53772c052ba8d0de1bb82b22249895e4737cfdf6 #3569, `Allow WidgetTab to use artwork tabs (@StCyr)`, some text is missing with the Classic Theme. I've only noticed this on the instrument plugins envelope tab as shown below. 'GENERAL SETTINGS' and the row above the envelopes beginning with 'TARGET' is missing. @Umcaruje 

![classic](https://user-images.githubusercontent.com/6368949/27405891-910b5ab4-56d3-11e7-8620-e78f847eb72a.png)

**Comment by Umcaruje** [comment]
I'll work on this once my exams are over (25th)

**Comment by PhysSong** [comment]
Not only these text but also other texts(for example, some texts in setting window) have been disappeared.

**Comment by PhysSong** [comment]
It's the problem of style.css and easy to fix. I sent a PR to fix this.

**Comment by PhysSong** [comment]
@Umcaruje did you check my PR?

**Comment by Umcaruje** [comment]
@PhysSong yes but the colors need work, I wonder if I should push to your branch or make a new PR alltogether

**Comment by PhysSong** [comment]
@Umcarjue Okay. I'll grant you push access.
