### ISSUE TITLE
Link to gentoo package is missing

### ISSUE THREAD

**Issue by jonasstein** [LMMS/lmms#3656]
Please add a link from
https://lmms.io/download/#linux
to 
https://packages.gentoo.org/packages/media-sound/lmms
Thank you

**Comment by tresf** [comment]
@jonasstein sorry for the burden, but could you please reopen this against our website repository?

https://github.com/LMMS/lmms.io/issues/new

Note, we accept Pull Requests against that repository as well if you are capable of writing the web code. 👍

**Comment by jonasstein** [comment]
done. Thank you for the link. https://github.com/LMMS/lmms.io/issues/235
