### ISSUE TITLE
Move search and refresh fields above file navigator

### ISSUE THREAD

**Issue by Mark-Agent003** [LMMS/lmms#3657]
Moving the search field and the refresh button to the top of the file navigator would help the user's experience in many ways. It would:

- Bring it to the direction of the user's eye (Then nobody has to "search" for the search)

- Make it where people actually know it exists (I've heard many times of people not even knowing it existed)

- Make the search more standard (you don't see Google's search on the bottom of the page)

(I may be able to provide some concept pictures tomorrow)

Thanks

**Comment by Mark-Agent003** [comment]
Also adding a "Search" placeholder text in the text box would help. Here's a concept image:

![image](https://user-images.githubusercontent.com/25230510/27484336-782df01c-57ee-11e7-8b7b-10c05ab18bd9.png)

**Comment by Hussam-Eddin-Alhomsi** [comment]
Great proposal!
I didn't know that there were a search field and a refresh button tbh. 😆

**Comment by michaelgregorius** [comment]
Move of the search bar to the top is implemented in pull request #3662 which is based on `master`.

**Comment by michaelgregorius** [comment]
Commit 96b136f adds the placeholder text "Search". This is how it currently looks:
![3657-filebrowser](https://user-images.githubusercontent.com/9293269/27498770-e2a1262c-5860-11e7-9314-0dbf020e4f52.png)


Adding the default text was one line and much simpler than I would have thought. Qt for the win! 😄

**Comment by Mark-Agent003** [comment]
How does it look in the classic theme?

**Comment by michaelgregorius** [comment]
@Mark-Agent003 This is how it looks with the classic theme:
![3657-filebrowser-classic](https://user-images.githubusercontent.com/9293269/27506982-e945f4ca-58c5-11e7-92a1-046b1384e38e.png)

**Comment by RebeccaLaVie** [comment]
@michaelgregorius Nicely done!

**Comment by BaraMGB** [comment]
@Mark-Agent003 why do you closed this issue?

**Comment by michaelgregorius** [comment]
Reopening this one so it can be closed once #3662 is integrated.

**Comment by Mark-Agent003** [comment]
I closed it because we already had a pull request open for this, and I didn't think we needed two separate discussions about the same thing. Do we actually need this open?

**Comment by grejppi** [comment]
Yes, because it will be closed once the pull request is merged

**Comment by Mark-Agent003** [comment]
Ok, that's fine

**Comment by michaelgregorius** [comment]
Shall I merge this one?

**Comment by tresf** [comment]
> Shall I merge this one?

👍 from me.

**Comment by zonkmachine** [comment]
Tested. Works much better on top!

**Comment by michaelgregorius** [comment]
Closed with #3662.
