### ISSUE TITLE
Clicking on some knobs increments their value after entering a negative value.

### ISSUE THREAD

**Issue by Hussam-Eddin-Alhomsi** [LMMS/lmms#3659]
This is probably a bug.
To re-produce:
(1) Open a project.
(2) Double click a PAN or PITCH or AMOUNT knob.
(3) Enter a negative value then click OK.
(4) Click or double click the same knob and you'll notice that its value has been decremented.

**Comment by BaraMGB** [comment]
I hope you don't wanna open an issue for every knob in lmms.

**Comment by Hussam-Eddin-Alhomsi** [comment]
I thought you guys are going to tell me to make a single issue for each knob and I thought that only 2 knobs have this bug. Now I noticed the same behavior with the AMOUNT knob.

I'm going to close #3658 and organize everything in here. Sorry.

**Comment by BaraMGB** [comment]
Question : which version you used?

**Comment by grejppi** [comment]
Related to this? https://github.com/LMMS/lmms/pull/3075#pullrequestreview-35502479

**Comment by Hussam-Eddin-Alhomsi** [comment]
> Question : which version you used?
Version1.2.0-rc3.

**Comment by Umcaruje** [comment]
probably related to that bug then

**Comment by BaraMGB** [comment]
https://github.com/LMMS/lmms/pull/3597 yes, I guess it's fixed.

**Comment by Hussam-Eddin-Alhomsi** [comment]
Please mark this issue as a `bug`.
@BaraMGB Are you sure it's fixed with 3597, if it is, I will close this issue.
