### ISSUE TITLE
PatMan logo distortion

### ISSUE THREAD

**Issue by Texxiliator** [LMMS/lmms#3660]
This logo is on the edges distorted (as the title says) and its pretty weird since its the only one logo to do this. I say we should put this logo : ![image](https://user-images.githubusercontent.com/29334338/27495472-454f573a-5852-11e7-96f8-4ed4250f786b.png)
instead of the old one.
Here is the old one for comparison :![image](https://user-images.githubusercontent.com/29334338/27495324-d0810016-5851-11e7-93ab-4104e9a74814.png)

**Comment by RebeccaLaVie** [comment]
@Texxiliator Please add more details and screenshots to your issue so that we can investigate this further. :)

**Comment by Texxiliator** [comment]
@RebeccaLaVie What details?

**Comment by RebeccaLaVie** [comment]
@Texxiliator Thank you for updating your post, I think I understand you now. Is your picture of the new logo a screenshot? If so, please make a pull request to replace the old logo with the smoother version.

**Comment by Texxiliator** [comment]
@RebeccaLaVie 
![image](https://user-images.githubusercontent.com/29334338/27656794-a5ee18b4-5c4a-11e7-80fd-31bbe9868ab6.png)

**Comment by Texxiliator** [comment]
@RebeccaLaVie 
![image](https://user-images.githubusercontent.com/29334338/27657464-0b405108-5c4d-11e7-818a-92de9f804787.png)

**Comment by zonkmachine** [comment]
@Texxiliator I think it looks good but it doesn't have the oval thing going on like the original.
If you want to see it in action in LMMS you need to first delete the file named `embedded_resources.h` in `/lmms/build/plugins/patman/`, before you recompile. If you use a separate build directory that is.

**Comment by Texxiliator** [comment]
@zonkmachine Look at this version now :) : ![image](https://user-images.githubusercontent.com/29334338/27702312-ed7e2944-5d03-11e7-8730-4ac7e68ebb59.png) this is what i want to replace the old logo with. (Except the black backround, that would be transparent)

**Comment by RebeccaLaVie** [comment]
@Texxiliator smoothed out the edges of the Patman logo by painting on top of the oval, but we will need to edit the source files to fix this, which I am having difficulty locating. The Playboy logo has too much aliasing in the instrument plugins list as well.

**Comment by Naruto0** [comment]
I can do that.
