### ISSUE TITLE
Some knobs aren not always reaching the minimum value visually.

### ISSUE THREAD

**Issue by Hussam-Eddin-Alhomsi** [LMMS/lmms#3661]
![wet dry](https://user-images.githubusercontent.com/25503477/27497892-6b912eba-5865-11e7-8936-67fd06b8fcac.png) 
![gate](https://user-images.githubusercontent.com/25503477/27497904-712b9dce-5865-11e7-86cb-eb9a7eb62509.png)

To re-produce:
(1) Open a project.
(2) Add an effect plug-in anywhere.
(3) Move the W/D knob to reach the minimum value or move the GATE knob slightly above 0 and try to move it to reach 0 again.

**Comment by BaraMGB** [comment]
@Hussam-Eddin-Alhomsi this issue is fixed to with this https://github.com/LMMS/lmms/pull/3597. That's all the same bug.

**Comment by Hussam-Eddin-Alhomsi** [comment]
Omg...
I should consider searching the pull requests before creating an issue the next time.

**Comment by Hussam-Eddin-Alhomsi** [comment]
Please mark this issue as a `bug`.

**Comment by tresf** [comment]
Marked and cross-referenced. 👍

**Comment by Hussam-Eddin-Alhomsi** [comment]
@tresf  This bug here isn't visual only, right? If it isn't visual only, I'll remove the `visually` part from the issue's name.

**Comment by tresf** [comment]
@Hussam-Eddin-Alhomsi the name is OK.  We can't expect every bug to know how it's broken under the covers.  The title is accurate.
