### ISSUE TITLE
Strange static sounds and slowness

### ISSUE THREAD

**Issue by tyehu** [LMMS/lmms#3668]
Whenever I open up the program, it periodically makes a static sound and everything plays slowly. For example, if I'm clicking on a loop to hear its sound or even playing something that I've made, the program will spontaneously play that thing slower for about a second and distort the sound with a static sound. It makes keeping pace difficult.

**Comment by PhysSong** [comment]
Did you check buffer size setting? Please try larger buffer size.

**Comment by musikBear** [comment]
@tyehu thats not a general issue, so its a support request
Best is to post a support ticket in our forum 
http://lmms.io/forum/index.php
But the first thing i would say to you there is :) to set your sound-device to SDL, so try that :)

**Comment by PhysSong** [comment]
@tyehu Can you still reproduce this issue with 1.2.0 rc4?

**Comment by PhysSong** [comment]
This is fixed in `stable-1.2` branch and it will be in RC5, which will be released soon. If you still have issue with RC5, please feel free to request reopening. :)
