### ISSUE TITLE
Crash when replacing instrument (Zyn?)

### ISSUE THREAD

**Issue by softrabbit** [LMMS/lmms#3669]
I get a segmentation fault whenever replacing ZynAddSubFX in Shovon-ProgressiveHousePluckDemo. Ubuntu 16.04, LMMS version:
>LMMS 1.2.0-rc3.21
(Linux i386, Qt 5.5.1, GCC 5.4.0 20160609)

Doesn't matter if the track is playing or not, if the filter automation track is removed first or not, if I drag and drop a plugin or send a preset using the context menu. 

Haven't reproduced this in a project from scratch yet, so it's possible that this is a rare edge case. 

_Edit: works fine on my Windows system:_
>Version 1.2.0-rc3 (win32/x86_64, Qt 5.4.2, GCC 4.9.4 20150716 (prerelease))

**Comment by zonkmachine** [comment]
> Doesn't matter if the track is playing or not, if the filter automation track is removed first or not, if I drag and drop a plugin or send a preset using the context menu.

And what about if you remove the Peak Controller?

**Comment by zonkmachine** [comment]
How about a backtrace?

**Comment by musikBear** [comment]
FYI No crash on win 32xp3 1.2.0 rc3
A side remark would be that rc3 *even* allows the zasfx GUI to be opened, that had been broken since 1.0. 👍

**Comment by PhysSong** [comment]
@softrabbit Can you still reproduce this on RC6?
