### ISSUE TITLE
LMMS crashes when project loading is cancelled

### ISSUE THREAD

**Issue by PhysSong** [LMMS/lmms#3670]
How to reproduce:
- Open demo project Jousboxx-BuzzerBeater.mmpz
- Press Esc key when progress is about 20%

Tested version: 1.2.0-rc3

The error message is: `ASSERT: "c != NULL" in file /home/hjsong/lmms-stable-1.2/src/core/Song.cpp, line 1264`

In the project, FX Ch11 uses peak controller from 'Sidechain' in B/B track, but this track wasn't load yet when I cancel loading.

Here's another example [test.mmp.zip](https://github.com/LMMS/lmms/files/1107624/test.mmp.zip).

Song::restoreControllerStates() should handle this situation. Unfortunate
ly it doesn't.

If there's someone who has an idea, please write a comment.

Edit: When I removed Q_ASSERT(), there was no crash. However, in the context menu of knob which was connected to peak controller, LMMS says there is an controller connection(there can't be such connections because the controller isn't loaded).

**Comment by zonkmachine** [comment]
> Edit: When I removed Q_ASSERT(), there was no crash. However, in the context menu of knob which was connected to peak controller, LMMS says there is an controller connection(there can't be such connections because the controller isn't loaded).

I think this is how the user will experience it as the assert is probably only there if you build with the debug  flag.

**Comment by PhysSong** [comment]
Then It is fine to fix the bug only?

**Comment by PhysSong** [comment]
Fixed in #3941, with #3636.
