### ISSUE TITLE
New methods for chord-table use

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#3673]
I suggest that the use of *chord* should be a bit different from current methods.
If a user has selects a chord in the table, and then click in piano-roll, on a single note, it would be smart, if that single note was *replaced* by the selected chord.
The workflow now is convulsed, because either the single note, need to be deleted before the chord is inserted, and then the 'template' is gone befor the chord is inserted or the chord is inserted one note of, the single note deleted, and the chord moved. Both workflows are not optimal.

Chords also need a method, that would allow *one single note* of the chord, to be moved. It could be that it is better, that a new inserted chord simply is inserted *unselected*, that would make single-note manipulation easy. I think the situation for the need of aug or sus of one note in a chord, happens more frequently, than the need for moving the whole chord. Octave duplication, would also be more logical, after aug/sus issues has been taken care of -No need to do that twice

**Comment by Hussam-Eddin-Alhomsi** [comment]
> If a user has selects a chord in the table, and then click in piano-roll, on a single note, it would be smart, if that single note was replaced by the selected chord.

I don't agree.
Chords are like single notes, but in a combination. Since you can't add a single note on top of another one, I don't think you should add a chord.

> Chords also need a method, that would allow one single note of the chord, to be moved. It could be that it is better, that a new inserted chord simply is inserted unselected, that would make single-note manipulation easy.

I agree.
When chords are stamped, they shouldn't be selected, just like single notes **or** they stay selected but there should be a faster way to escape the selected chord or group of notes other than the "Esc" key, like a mouse left-click.

**Comment by musikBear** [comment]
> I don't agree.
Chords are like single notes, but in a combination. Since you can't add a single note on top of another one, I don't think you should add a chord

@Hussam-Eddin-Alhomsi Rethink, its all about work-flow:
You have composed a simple melody in single-notes, now you want to 'chordyfy' these single notes -effectively you want to **replace**, some or all, of the single notes, with chords! That process would be way simpler, if the chord 'overwrites' the existing single note. -Eg deletes it.
I recognize your point of view 
> *Chords are like single notes*

But thats just it, They are *not* like single notes! They are *replacements* for single notes :)

**Comment by tresf** [comment]
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.
