### ISSUE TITLE
Add FLAC export support

### ISSUE THREAD

**Issue by PhysSong** [LMMS/lmms#3679]
LMMS supports wav, ogg, and mp3 exports. Many other DAWs support FLAC export feature.
Although it is not strongly needed, it can be a convenient feature because FLAC is famous and widely used lossless audio encoding.

Since `libflac` and `libflac++` is dependencies of libsndio, no additional dependency will be needed.

**Comment by musikBear** [comment]
compared to wave, what is the most obvious advantage?
Is the advantage significant (enough) to lead to *yet* a new feature?

**Comment by PhysSong** [comment]
Compared to .wav, .flac file has smaller size. Furthermore, FLAC is lossless.

**Comment by tresf** [comment]
@musikBear this isn't so much of a "feature" as MP3 support.  FLAC is a common encoding and it adds value.  Let's not bikeshed over such a trivial request please.

**Comment by softrabbit** [comment]
> Since libflac and libflac++ is dependencies of libsndio, no additional dependency will be needed.

And then there's libsndfile, which LMMS already uses for audio file export (WAV at least). It has handled FLAC since 2009.

**Comment by Umcaruje** [comment]
I actually find flac to be the best of the audio formats. It's lossless, and it doesn't hold as much space as a wav file. A win-win.

**Comment by trollworkout** [comment]
Exporting FLAC is not really that useful. Maybe the ability to import FLAC into  a wav track would be more useful. You can always export wav and convert it to flac.  FLAC is more of a portable lossless audio format . It helps you get CD quality but in a smaller package . I see no other benefit.

**Comment by tresf** [comment]
> Exporting FLAC is not really that useful. Maybe the ability to import FLAC into a wav track would be more useful.

You just explained a use-case.  If you're exporting something that's to be used again later, FLAC. :)

> You can always export wav and convert it to FLAC

The same can be said for MP3 as well, but it's one of our biggest complaints.  We should strive to support encoding and decoding equally and consistently unless there's a good reason not to.

**Comment by Umcaruje** [comment]
>Maybe the ability to import FLAC into a wav track would be more useful.

Actually, you can load FLAC files in LMMS just fine, with no trouble at all.

>You can always export wav and convert it to FLAC.

Yes but as @tresf the same can go with any other format, having to use external software to have a flac file is just bad UX.

**Comment by trollworkout** [comment]
I mean here's my take on it . Flac is great format because you know high quality smaller package .  So is PERFECT for a sample library. 

I would totally be into having a library of flac samples to use in lmms .  However, why would I ever need the ability to export flac? 

First of all I do my sample chopping outside lmms in Audacity or similar software. Second would lmms give me great control and power over exporting flac or is just something you guys wanna slap in for the sake of  good UX?

Just adding the export feature won't really add any value would be more of a nice extra feature. I'd probably still use flac from the command prompt in batch mode after i chop the sample. 

Whatever you guys decide is up to you. That's my 2 cents on this issue

**Comment by tresf** [comment]
For further discussion, hop on Discord.  The points have been made several times now, this will turn into an endless discussion.

**Comment by farvardin** [comment]
FLAC is roughly 4 times smaller than WAV, so I no longer store my stuff in WAV but in FLAC instead, especially when it concerns master tracks. Yes at the moment I just export to wav in a temporary folder, then convert to Flac and mp3 and ogg with Audacity, so I can live without this flac export. It would just be convenient to have it.

Now I'm wondering, Flac import works fine, but when exporting my music to WAV, my VST are exported, but the samples are missing. Could it be related to the flac format?

**Comment by Umcaruje** [comment]
>Now I'm wondering, Flac import works fine, but when exporting my music to WAV, my VST are exported, but the samples are missing. Could it be related to the flac format?

I haven't encountered that, are you using VST effects on sample tracks? That's an issue that was fixed #3511

**Comment by farvardin** [comment]
I'll test further. It's on LMMS 1.2.0 rc2.151, I have no VST on them but the "EQ" effect (native to LMMS, a very well-designed effect btw) and some automation.
I've noticed if I export with the resampling 2x all the samples are in the exported wav (but the sound is not that nice), with resample 1x (none) some samples are not present. As I said I'll test further, on other computers and with an other example.

**Comment by zonkmachine** [comment]
@farvardin LMMS does some extra tests when exporting to ensure that odd data like 'infinit' values etc. are filtered out. You could have some bad data or extreme settings that will trigger these tests. Try and solo each channel and see if you spot something odd in the 'Scope'. What plugins are you using on the tracks that have sound missing?

**Comment by Umcaruje** [comment]
@farvardin once you do more extencive tests and narrow down the issue, I suggest opening a new issue over here, so we don't take this one off-topic

**Comment by farvardin** [comment]
yeah, sorry for highjacking this thread ;)
I've opened a bug there: https://github.com/LMMS/lmms/issues/3702

**Comment by tresf** [comment]
Closed via #3731.
