### ISSUE TITLE
Restart warning on setup dialog itself

### ISSUE THREAD

**Issue by M374LX** [LMMS/lmms#3681]
A less annoying alternative for a restart warning popping up after closing the setup dialog is to display the message on the dialog itself, like so:
![lmms-restart](https://user-images.githubusercontent.com/6584238/27809632-ca94161a-6027-11e7-86e1-b547a554dbca.png)

This would also make the option "Show restart warning after changing settings" unnecessary.

**Comment by PhysSong** [comment]
I ageree. It is good alternative of current method(i.e. the warning dialog).
The dialog won't be needed anymore.

**Comment by musikBear** [comment]
Njaa.. The right way would be to newer show the dialog, if the setting change made, was not in *need* of a restart.
There are now quite a lot of changes, that takes place emediately, so making those changes, should simply just not launch the dialog. (1.2x or (much) later

**Comment by Hussam-Eddin-Alhomsi** [comment]
I agree.
A single line of text would be a lot better than a window with a close button, OK button, an image and a single line of text. It would be better for the machine and the user.
![image](https://user-images.githubusercontent.com/25503477/27835585-3fe22ac6-60e4-11e7-96cd-1312a46c97cf.png)

**Comment by tresf** [comment]
> The right way would be to newer show the dialog, if the setting change made, was not in need of a restart.
There are now quite a lot of changes, that takes place emediately, so making those changes, should simply just not launch the dialog.

Correct.  The dialog should not be ambiguous.

**Comment by PhysSong** [comment]
Regardless of warning method which LMMS uses, users should know which change needs restart.
In my opinion, warning message should be in the setting dialog and tell which change needs restart.

**Comment by tresf** [comment]
> In my opinion, warning message should be in the setting dialog and tell which change needs restart.

Let's be clear.  The warning is to tell the user that the changes WON'T take effect until a restart.  To suppress an interrupting message in favor of an easily unnoticeable message won't cut it.  The time spent clicking "OK" is much less than the time spent when people don't read the bottom of a dialog.

The real problem is that we show this popup for everything and that we have interrupting dialogs in general.  The proposed solution isn't really a fix.  A good non-modal way of doing this in my opinion is how code editors do this, with a popup bubble notification, like we use here: https://github.com/LMMS/lmms/blob/c2f26a76d4ac5d729397bbda478a0e3f6fac23ea/src/core/Song.cpp#L1190.

**Comment by musikBear** [comment]
@tresf 
>  like we use here:

Woot, that one i have (luckily) never seen! Should that not be with a distinctive different background (f.i. red) than the ok-message. I honestly doubt, i would notice it in its current layout. User expect a tiny floating black box, and get one either way. A serious saving error should imo stand out, much more.

**Comment by M374LX** [comment]
A situation where the warning makes no sense is when the dialog is displayed at the program's first launch.

A red background, as suggested by @musikBear, is a nice idea.

**Comment by tresf** [comment]
> A situation where the warning makes no sense is when the dialog is displayed at the program's first launch.

Agreed.  Ideally, we can (eventually) eradicate this message on first launch, but that's another enhancement.

**Comment by follower** [comment]
Related: #2109 & #3627.
