### ISSUE TITLE
SC2185 should be enabled when fixed upstream

### ISSUE THREAD

**Issue by zapashcanon** [LMMS/lmms#3684]
Hi,

Just a reminder, see [this comment](https://github.com/lmms/lmms/commit/e90bc630fabb3e8c2e815250594204578931066a#diff-cd31ca8078680e1895d11f56d1fe38c2R7)

**Comment by zapashcanon** [comment]
Fixed upstream, but probably not in Travis yet...

**Comment by tresf** [comment]
@zapashcanon I'm closing this because it's not our bug and even Ubuntu 18.04 hasn't received this yet a year later.  We have a lot of code that's workarounds for upstream issues, we can reopen at a later time (perhaps 20.04 LTS).
