### ISSUE TITLE
Flanger - Render from gui not set up properly

### ISSUE THREAD

**Issue by zonkmachine** [LMMS/lmms#3689]
Something isn't properly set up/reset when rendering from the gui. I've seen this with the Flanger effect only so far. I'm not sure if this is an issue with Flanger specifically but ReverbSC and Delay renders identically from the gui.

Left side rendered from the command line and to the right, from the gui.
![flangercl](https://user-images.githubusercontent.com/6368949/27983026-61cb9632-63b3-11e7-82b4-d20247f71ae1.png)

Edit: [flange.mmp.zip](https://github.com/LMMS/lmms/files/1132851/flange.mmp.zip)

**Comment by PhysSong** [comment]
@zonkmachine Could you upload the project file? I'll do some tests with it.

**Comment by zonkmachine** [comment]
^^--- Fixed!

**Comment by zonkmachine** [comment]
Oops, wrong project. Fixed!

**Comment by zonkmachine** [comment]
Sorry, earlier confusing message removed. The actual issue isn't fixed... the issue _report_ is.

**Comment by PhysSong** [comment]
Our native flanger has built-in LFO. It isn't reset automatically when the export starts.
I haven't tested yet, but I guess that's the reason.

**Comment by PhysSong** [comment]
We may add something like this in the LFO controller class, in order to reset a flanger's LFO:
https://github.com/LMMS/lmms/blob/e5db27542b3b05fe0b0cbdfe277f1ad187cf48d0/src/core/LfoController.cpp#L61-L62

**Comment by PhysSong** [comment]
This bug seems minor, but flanger is the only plugin with this behavior AFAIK. So I don't know which branch is proper as the target.
@zonkmachine How do you think about this?

**Comment by zonkmachine** [comment]
Bump flanger overlord @curlymorphic
