### ISSUE TITLE
Track height is not restored when loading a project

### ISSUE THREAD

**Issue by michaelgregorius** [LMMS/lmms#3693]
Steps to reproduce:
1. Start LMMS.
2. Change the height of the Triple Oscillator track in the Song Editor by dragging the track while holding the SHIFT key.
3. Save the project.
4. Load the project.

Expected result: The changed track height of the Triple Oscillator track is restored upon loading.
Actual result: The Triple Oscillator track has the default height.

**Comment by michaelgregorius** [comment]
Solved by #3692.

**Comment by musikBear** [comment]
i think it would be a fine feature to have a selectable setup-choice:
*Use wide tacks*

**Comment by RebeccaLaVie** [comment]
@musikBear If users can already resize the tracks, I do not see a reason to add this to the settings. If the current tracks are too small, then we should change the default to a more usable size.

**Comment by michaelgregorius** [comment]
For me the pull request is only one of several steps that need to be taken to be able to change the default size of the tracks. Other steps are:
* Making sure that all type of tracks look good at an increased height, e.g. fix the problem with the beats and basslines tracks described in #3683.
* Make the resize option more prominent. A prerequisite for this is to fix the issue described in here because otherwise users will make use of the more prominent resize option, save their file and then have to resized everything over and over again.

**Comment by musikBear** [comment]
@RebeccaLaVie -Its just an option that would omit the need for the user to manually widen each new track, but its definitively a very minor thing, perhaps even a minor 'thinglet' 🤡

**Comment by michaelgregorius** [comment]
Closed via #3692.
