### ISSUE TITLE
Melody patterns do not make good use of height when enlarged

### ISSUE THREAD

**Issue by michaelgregorius** [LMMS/lmms#3698]
The current implementation draws the notes of melody patterns as lines regardless of the pattern's size:
![patternlineslargeold](https://user-images.githubusercontent.com/9293269/28239007-2e27383c-6961-11e7-81b0-e6148a547885.png)

Also the notes are always painted underneath the text label even if the pattern is enlarged.

**Comment by michaelgregorius** [comment]
Fixed with #3699. The pattern above looks as follows at larger heights:

![3698 - pattern new](https://user-images.githubusercontent.com/9293269/28239100-d2c7b068-6963-11e7-98f3-caae901d9b18.png)

Please note that at larger heights the notes are moved completely below the text label. For patterns with a small height like in the second track the notes are drawn underneath the text label to make best use of the constrained space. #3699 also has an animated GIF that shows the dynamic aspects when the pattern is resized.

**Comment by michaelgregorius** [comment]
Here's a variation where the black keys are indicated in the pattern as well (only drawn when the notes are drawn as rectangles):

![3698 - variant with black key indicators](https://user-images.githubusercontent.com/9293269/28239301-a0037d6e-6969-11e7-9d13-1e88b5973d06.png)

**Comment by BaraMGB** [comment]
Nice idea!

**Comment by Mark-Agent003** [comment]
It seems like the notes gain more opacity the bigger they get. Was that intended?

**Comment by michaelgregorius** [comment]
@Mark-Agent003 I think what you observe is caused by the fact that for the notes in the third pattern you see more of their darker border than their inner fill. The code does not change the color or opacity depending on the note height.

**Comment by Umcaruje** [comment]
@michaelgregorius I find the black keys idea would just add unneeded complexity, and can't figure out a valid usecase for it. I like what you've done with the drawing, but I think the rectangles shouldn't have any border, just be plain single-colored, it will look sharper and nicer

**Comment by michaelgregorius** [comment]
@Umcaruje I agree that showing the black keys rather adds clutter than useful information and that it might make the song editor very busy.

Regarding the note borders: my first implementation had notes without any borders. However, for some patterns the borders really help to convey a bit more information about whats happening in the pattern. Here's a pattern without borders:

![3698 - notes without border](https://user-images.githubusercontent.com/9293269/28246503-81d4b30a-6a1b-11e7-9228-ea086598a2c4.png)

On first sight it looks like the pattern starts with one long note. Here's the same pattern with borders:

![3698 - notes with border](https://user-images.githubusercontent.com/9293269/28246506-9b07251a-6a1b-11e7-90cf-5e937493ae3c.png)

Here it's much more obvious that the pattern starts with several repeated notes.

I think the introduction of using a cosmetic pen (see [this comment](https://github.com/LMMS/lmms/pull/3699#issuecomment-315539555)) in commit 4021db2468bc1e4790212c2c8906438e67999479 has also helped to make the rendering of the notes sharper.

**Comment by RebeccaLaVie** [comment]
Perhaps if we do need the border, it can be green instead?
![28246506-9b07251a-6a1b-11e7-90cf-5e937493ae3c](https://user-images.githubusercontent.com/7960169/28285454-9dd0ae1e-6ae9-11e7-81cd-543df38414a7.png)

**Comment by michaelgregorius** [comment]
@RebeccaLaVie I will give it a try. I guess it makes sense to expose these attributes in the CSS as well.

**Comment by michaelgregorius** [comment]
@RebeccaLaVie With commit eae3a2ea5828c792bdd223af88e826c652f7b62e the properties for the note fill and border colors are now exposed to the style sheet. They are exposed for the muted and not muted cases. I have changed the style in the default theme such that the borders also use the background colors to yield as design as proposed by you.

Example for the default theme:
![3674-exposed-css-default](https://user-images.githubusercontent.com/9293269/28475474-a3e25fd0-6e4c-11e7-8ace-62e17c750d38.png)

Example for the classic theme:
![3674-exposed-css-classic](https://user-images.githubusercontent.com/9293269/28475476-ad392532-6e4c-11e7-86e9-847e7f9be4b1.png)

**Comment by michaelgregorius** [comment]
Closed via merge of #3699.
