### ISSUE TITLE
Vibed : Param. Length' span is weird

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#3703]
is the *length* param sensible?
Currently it goes from 'quite long' to 'absurd-long'/indefinite 
ENV settings can ofcause be used, but the instrument itself, has a strange span over only 'long'
(Bad thing, cause a better span setting, would break backward

**Comment by zonkmachine** [comment]
No. It has nothing to do with envelope as the one you find in a synth, but is part of a physical simulation of a vibrating string. It depends on the other settings. Turn up the string stiffness, **S**, a bit and the length value will not be indefinite no longer. The parameter itself is an over sampling value and therefore a whole number.
