### ISSUE TITLE
Sometimes window positions aren't loaded correctly

### ISSUE THREAD

**Issue by diizy** [LMMS/lmms#371]
This is a really annoying bug because moving the windows around is kind of a pain. 

Usually when you save a project the window positions get saved too which is great. But sometimes when you load the project, they don't get loaded correctly - the sizes are correct but the windows get stacked so they overlap each other.

This seems like it was much more common in 0.4.15 but it still happens in the latest version.

**Comment by tresf** [comment]
Please reopen if not fixed by #1490
