### ISSUE TITLE
ExportProjectDialog may break on some build configs

### ISSUE THREAD

**Issue by irrenhaus3** [LMMS/lmms#3713]
The file-scope function convertIndexToExportFileFormat(int) in gui/ExportProjectDialog.cpp implements the following hard mapping onto ProjectRenderer::ExportFileFormats values:  
0:WAV  
1:OGG  
2:MP3  
However, the actually availabe menu items that correspond to these indices are subject to build configurations.  
In a build config where LMMS_HAVE_OGGVORBIS is undefined, but LMMS_HAVE_MP3LAME is defined, the OGG export menu item would not exist, thus the MP3 item index would go off-by-one and be 1 instead of 2. Because the mapping function doesn't respect these options, selecting MP3 export would then show the controls for the vorbis renderer and possibly generate invalid settings for the mp3 renderer.  
  
Possible solutions:
- Check the build configurations for optional export types within the convertIndexToExportFileFormat function and use this information to handle possible offsets.
- Do not have a hard-coded order at all.

**Comment by michaelgregorius** [comment]
@irrenhaus3 Can you please check if you can also fix the problem described [here](https://github.com/LMMS/lmms/pull/3615#pullrequestreview-51988486)? It's a related problem.

**Comment by irrenhaus3** [comment]
@michaelgregorius @PhysSong Should be fixed via https://github.com/irrenhaus3/lmms/commit/ac932dcab3f08ef666169dff3590d0b643742bf4

**Comment by PhysSong** [comment]
Merged #3714.

**Comment by michaelgregorius** [comment]
@irrenhaus3 Thanks!
