### ISSUE TITLE
[feature request] Please have WANT_OSS option like with other audio interfaces

### ISSUE THREAD

**Issue by yurivict** [LMMS/lmms#3725]
It should be possible to disable it like others.

**Comment by tresf** [comment]
Should be as simple as adding the option to the `WANT_...` section and wrapping the [OSS detection block in it](https://github.com/LMMS/lmms/blob/master/CMakeLists.txt#L339).

This is a very trivial change, if you're comfortable with Pull Requests, this would be appreciated, if not, we'll add it ourselves eventually.

**Comment by gi0e5b06** [comment]
Done.

**Comment by tresf** [comment]
@gi0e5b06 can you please elaborate?  I do not see a Pull Request which adds this feature.

**Comment by QuixoticJk** [comment]
hi has this issue already been fixed?

**Comment by PhysSong** [comment]
Not yet.

**Comment by Rossmaxx** [comment]
> hi has this issue already been fixed?

Opened the PR now. So, it'll be fixed soon.
