### ISSUE TITLE
Status of MIDI export feature?

### ISSUE THREAD

**Issue by sanz999** [LMMS/lmms#3729]
I'm interested in using LMMS for MIDI files, but it doesn't give me the option to export them. I looked through the issues and saw that this had been a feature before but was disabled because it was broken. Is there a way to experimentally enable this, or a plugin I could use? Also, I'm wondering if there are plans to fix the feature and bring it back soon (and possibly an ETA?).
Thanks

**Comment by PhysSong** [comment]
It will be fixed soon and should be re-enabled. See #2384.

**Comment by zonkmachine** [comment]
@sanz999 Hello Santiago!

I close this issue as it's been answered. Please use one of our [Discord](https://discordapp.com/invite/3sc5su7) channels for questions. That's where the developers hang out.

**Comment by zonkmachine** [comment]
Also. You can revert 0b056caa3a608424afa29f09e7a680e023dcb47e as this is the commit  that hides the MIDI export feature.
`git revert 0b056caa3a608424afa29f09e7a680e023dcb47e`
