### ISSUE TITLE
Time Signature in BB Editor

### ISSUE THREAD

**Issue by gi0e5b06** [LMMS/lmms#3735]
Same than for the song editor. The time signature is not displayed correctly.
Actually, there is other problems too. Well, this screenshot says it all:
![pattern_display](https://user-images.githubusercontent.com/30031949/28743794-cdb55ff4-7452-11e7-888b-7424a38a4937.jpg)
Not done. WIP.

**Comment by zonkmachine** [comment]
> Actually, there is other problems too. Well, this screenshot says it all:

No, the screenshot isn't enough...

What commit are you on?
Is this in the latest stable?
How do you reproduce the single beat note?

I hacked around this here: https://github.com/LMMS/lmms/pull/2959

**Comment by gi0e5b06** [comment]
1) master
2) yes
3) I just changed the time signature.

I don't think it is related to #2959, it is just a display problem.

**Comment by zonkmachine** [comment]
> 3. I just changed the time signature.

How does one reproduce it, step-by-step. What is the starting time signature? Where do I place the notes? To what time signature do I change?

I can easily reproduce this in stable-1.1.3 by:
1 - Set time signature to 5/4
2 - Place a note at step 17
3 - Set time signature to 4/4
4 - Hit the remove steps button... :-)

How do I achieve something similar on stable-1.2 or master?

**Comment by gi0e5b06** [comment]
@zonkmachine note in step 1, signature to 1/10.
anyway, the visual is correct, just ugly.

**Comment by PhysSong** [comment]
> anyway, the visual is correct, just ugly.

@gi0e5b06 What do you want to say with this issue? Do you think the visual should be better?

**Comment by musikBear** [comment]
@PhysSong 
when i look at the pictures, i can see issues.
In The top one, the length of the beat simply causes the display to be very condensed. It is difficult to insert events, without errors.
That gives me this idea:
If the B&B *input area* was scrollable, then there could be same-size event-boxes, in-dependent of  the length of the actual beat.
Not only would it look better, but it would also make the actual usage more intuitive. Change of content in a view, could be confusing for new users.
So something in the line of:
![improvedbb](https://user-images.githubusercontent.com/6662066/35194001-ca73b85c-feab-11e7-864d-1bcbf02151b2.JPG)

Obs the added play-head. Transport is already connected to main-display, but lacks a play-head

The bottom OP pic.. I have NO idea what that is - Never seen it

**Comment by gi0e5b06** [comment]
@PhysSong Look at my screenshot. Ugly and unpractical.
@musikBear I totally agree with making the area scrollable and adding a timeline.

**Comment by BaraMGB** [comment]
I close this. If you feel this issue is valid please clean up the first comment. No one can see what's the problem here.

**Comment by gi0e5b06** [comment]
Seriously?
