### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by mrrm92** [LMMS/lmms#3737]
Would you mind, other than the plugins you already support, to add a modular synth?
The interface could be like the sampler plugin, but in the plugin tab, the user could build its own synth (let's tell it: like FlowStone) and save it as a preset, then share his/her awesome synth with the LMMS community.
Maybe something similar already exist, if so, I'm not aware.

Thanks in advance for help.

**Comment by zonkmachine** [comment]
> the user could build its own synth (let's tell it: like FlowStone

This is probably a bit too complex. I used the precursor to FlowStone, Synthmaker, and it was absolutely wonderful to work with, but It's basically way too much work for a small project like this.
Please see [the answer](https://github.com/LMMS/lmms/issues/3197#issuecomment-270017733) in issue 3197 from a developer who has made a sound programming library and knows the amount ow work involved.


This has been suggested before, at least two times: https://github.com/LMMS/lmms/issues/3197
Closed as a duplicate.

**Comment by mrrm92** [comment]
Sorry, I should have used the search function.
Do you know anything for patching which is as simple as FlowStone? I know there is PureData, but I'd like something more "user-friendly", with which I could just put (example) Osc -> ADSR -> Out in a visual way.

**Comment by zonkmachine** [comment]
Not really. What OS are you on?

For Linux there is [Alsa Modular Synth](http://alsamodular.sourceforge.net/). I haven't worked with it that much though.

**Comment by mrrm92** [comment]
I'm on Windows 10.

**Comment by zonkmachine** [comment]
Right. Then I'm pretty much clueless. ;)

**Comment by mrrm92** [comment]
Shame on me!
I were under Linux until Yesterday...
