### ISSUE TITLE
Error message on closing

### ISSUE THREAD

**Issue by gi0e5b06** [LMMS/lmms#3739]
When closing LMMS:
`QXcbConnection: XCB error: 3 (BadWindow), sequence: 5107, resource id: 29365774, major code: 40 (TranslateCoords), minor code: 0`

In MainWindow.cpp#1379, I think the event should not be accepted (early).
Commenting _ce->accept() fixes the problem.
Done.

**Comment by zonkmachine** [comment]
> Commenting _ce->accept() fixes the problem.
> Done.

This is a bit confusing. Nothing is done here. Do you intend to issue a Pull Request for this?
It is time for you to figure out git/GitHub. Really. If you need help with this, just post in the LMMS Discord page. The way to work is to make a Pull Request against master. That's it.

**Comment by gi0e5b06** [comment]
Nothing confusing. You can pull every thing from my rep.
I already have a pull request but I can make a new one.

**Comment by gi0e5b06** [comment]
Same problem on choosing a sample and cancelling (open the file dialog, hit cancel).
Not done (because I didn't see any immediate solution). If someone wants to look at it...

**Comment by gi0e5b06** [comment]
Reverted and can be closed.
After more googling, it seems this is related to the oxygen theme with KDE/Kwin/Qt and there is no clear workaround. Anyway not related to LMMS.
