### ISSUE TITLE
Can not open recent files (KDE)

### ISSUE THREAD

**Issue by gi0e5b06** [LMMS/lmms#3741]
Qt can add automatically accelarators for each menu entries and KDE does that by default. So a recent file like myproject.mmp becomes mypr&oject.mmp and can not be opened.
As a workaround, if a file is missing and contains an ampersand, the ampersand is removed and the file is tried again. Implemented. Works. May not work if your original filename contains one or more '&'.

PS: implementing a clean solution would require 30-40 lines of code, so way over the allowed PR size limit.

**Comment by Spekular** [comment]
There's no restriction on pull request line length.

**Comment by zonkmachine** [comment]
> would require 30-40 lines of code, so way over the allowed PR size limit.

What size limit? where did you see this?

**Comment by gi0e5b06** [comment]
BTW, that should go into stable-1.2 too.
https://github.com/gi0e5b06/lmms/blob/ab1b45a32a6213ebbe09bda8c809380404c5ae4e/src/gui/MainWindow.cpp#L907
```
void MainWindow::openRecentlyOpenedProject( QAction * _action )
{
	if ( mayChangeProject(true) )
	{
		QString f = _action->text();
		// workaround for KDE
		QFileInfo recentFile(f);
		if(!recentFile.exists()&&(f.indexOf('&')>=0))
		{
			f=f.replace("&","");
		}
		//end
		setCursor( Qt::WaitCursor );
		Engine::getSong()->loadProject( f );
		setCursor( Qt::ArrowCursor );
	}
}
```

**Comment by irrenhaus3** [comment]
@gi0e5b06 If you have a clean solution to the problem, please follow these steps:  
* Create a new git branch in your fork, based on this repo's stable-1.2 branch
* Implement your solution on that branch
* Create a new Pull Request of your branch into stable-1.2 of this repo.
  
There are no size restrictions on PRs, although complex or large changes may take longer to review. See also: https://github.com/LMMS/lmms/wiki/Submitting-a-patch  
Also, could you explain where you saw the stuff about PR size limitations? If that's in the wiki somewhere, it needs to be taken out.

**Comment by gi0e5b06** [comment]
@irrenhaus3 I posted the code. Feel free to go from there.

**Comment by zonkmachine** [comment]
Closed in https://github.com/LMMS/lmms/pull/3872
