### ISSUE TITLE
LMMS crash on drag and dropping a file into AudioFileProcessor

### ISSUE THREAD

**Issue by a2aaron** [LMMS/lmms#3744]
For reference, I am on LMMS version: `Version 1.1.3 (OS X/x84_64, Qt 4.8.6, GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28).` (I am using the precompiled binaries from https://lmms.io/, not built from source)

OS: macOS 10.12.5 (16F73)
Kernel: Darwin 16.6.0
RAM: 8 GB, DDR3, 1600 MHz
CPU: Intel Core i5 @ 3.2 GHz
GPU: NVIDIA GeForce GTX 675MX

How to reproduce:

1. Open any LMMS project (even the default).
2. Create an AudioFileProcessor instrument track.
3. Open the AudioFileProcessor plugin window thing
4. Open the "My Samples" tab and attempt to drag and drop a sample into the AudioFileProcessor window
5. LMMS will crash immediately.

Note that dragging and dropping a sample into the Song Editor window or double clicking a sample will successfully create an AudioFileProcessor track.

![Example of crash](https://user-images.githubusercontent.com/15718048/28850226-6ba72a60-76e9-11e7-8116-c7f8dddf6c9c.png)

![Example of not crash](https://user-images.githubusercontent.com/15718048/28850323-ee1c1aaa-76e9-11e7-81ec-430a451224a2.png)

**Comment by tresf** [comment]
Just tried this on 1.2.0-rc3 and the bug does not occur.  Please test bugs on our beta version as much of the code has changed.

The beta versions are available at the bottom of the downloads area.

**Comment by a2aaron** [comment]
Tried it on `1.2.0-rc3` as well and the bug did not occur. Thank you for your help!

**Comment by tresf** [comment]
@a2aaron thanks for the excellent write-up, by the way, much appreciated.
