### ISSUE TITLE
request: global transpose in semitones

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#375]
I would like to sugest a menu item -could logically be in 'Edit'
Feature: 'Transpose project'
The user should be able to select number of semitones + up/dn
The result would be that the complete project would be in a new key/ scale.

**Comment by softrabbit** [comment]
>We could add a checkbox option to instrument tracks such as "ignore master pitch", accessible from the trackops menu. 

This transposition idea could move forward now, the checkbox exists in master.

**Comment by Umcaruje** [comment]
Since #1593 was merged, I'm closing this issue as fixed. If you believe this was closed in error, feel free to reopen the issue.
