### ISSUE TITLE
Pattern on some tracks is rendered hundreds of pixels high

### ISSUE THREAD

**Issue by sonicflops** [LMMS/lmms#3750]
Using: 1.2rc3.115
I had a brief look to see if it was reported, forgive me if I'm duplicating a bug... however, when it pops up it is hilariously gargantuan. I haven't seen a pattern of when it happens yet but I'll keep looking!

![screenshot at 2017-08-04 22-41-54](https://user-images.githubusercontent.com/25714009/28988314-2094e7c6-7967-11e7-877b-c8d7fdd3fee5.png)

In addition, the drag&drop area takes up the same area

**Comment by zonkmachine** [comment]
Hello!

This is a known issue: https://github.com/LMMS/lmms/issues/3721
I'm closing this as a duplicate.
