### ISSUE TITLE
Song editor selections stay selected in editor mode

### ISSUE THREAD

**Issue by Mark-Agent003** [LMMS/lmms#3762]
I am using the latest release candidate; although, I think this is a universal problem. I have noticed this problem many times, but @spekular has also expressed he wanted this changed. Here's how to reproduce this: select a pattern using selection mode in the song editor, then click edit mode. The selected pattern is still selected, and the only way to deselect is to go back into selection mode and unselect.  I think that whenever you switch to the editing mode, it should always automatically deselect any selected patterns. This would save time, and it just seems practical.

**Comment by BaraMGB** [comment]
With this pr https://github.com/LMMS/lmms/pull/3649 the behavior should be more logical. But unfortunately we can't merge it because the undo function doesn't work like expected. And no one knows how to fix it.

**Comment by zonkmachine** [comment]
> With this pr #3649 the behavior should be more logical.

#3649 is now merged.

**Comment by BaraMGB** [comment]
I close this because https://github.com/LMMS/lmms/pull/3649 should fix this.
