### ISSUE TITLE
Vertical Zoom in Song Editor

### ISSUE THREAD

**Issue by Spekular** [LMMS/lmms#3763]
With the recent improvement to vertically larger patterns in the song editor (PR 3699), a vertical zoom makes more sense than before. This would allow every track to be scaled vertically by the same amount, and could be more convenient than shift+dragging even if you only want to focus on one track.

Right now the following shortcuts use the mouse wheel:

| Modifier | Modifier | Mousewheel = | Direction | Operation |
| ---: | ---: | :---: | :--- | :--- |
|  |  | Mousewheel = | Vertical | Scroll |
|  | Shift + | Mousewheel = |  Horizontal | Scroll |
|  | Alt + | Mousewheel = | Horizontal | Scroll |
|  | Ctrl + | Mousewheel = | Horizontal | Zoom |

Since there are two horizontal scroll shortcuts, ether Shift or Alt could in theory be used for vertical zoom. However, I think a modified Ctrl would make more sense. This would lead to something like this (excluding alt for brevity):

| Modifier | Modifier | Mousewheel = | Direction | Operation |
| ---: | ---: | :---: |  :--- | :--- |
|  |  | Mousewheel = | Vertical | Scroll |
|  | Shift + | Mousewheel = | Horizontal | Scroll |
|  | Ctrl + | Mousewheel = | Horizontal | Zoom |
| Shift + | Ctrl + | Mousewheel = | Vertical | Zoom |

However, this would mean that an unmodified scroll is vertical, and an unmodified zoom is horizontal. Perhaps these should be unified, so an unmodified scroll and zoom operate on the same axis. I would then propose changing a regular unmodified mousewheel scroll to move horizontally, leading to:

| Modifier | Modifier | Mousewheel = | Direction | Operation |
| ---: | ---: | :---: | :--- | :--- |
|  |  | Mousewheel = | Horizontal | Scroll |
|  | Shift + | Mousewheel = | Vertical | Scroll |
|  | Ctrl + | Mousewheel = | Horizontal |  Zoom |
| Ctrl + | Shift + | Mousewheel = | Vertical |  Zoom |

This would make all mousewheel events horizontal by default. Shift becomes the "vertical" modifier, and Ctrl remains the "zoom" modifier.

**Comment by Spekular** [comment]
Here's a rough mockup, although I'm not sure if one is necessary. I haven't actually built a version with the drawing changes so this isn't even properly representative.

![image](https://user-images.githubusercontent.com/8918426/29221987-ffe330b4-7ec0-11e7-9422-69086441eaab.png)

**Comment by musikBear** [comment]
I wonder if the zoom could include larger fonts? @Spekular 
I could see this zoom-method as a great help for visual impaired, especially if also fonts was scaled up

**Comment by tresf** [comment]
Please do not change mouse wheel to be left/right scroll by default.  This is non-standard UI and will cause much grief.

**Comment by tresf** [comment]
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.

**Comment by nestg** [comment]
This is a urgent feature, tracks are very short height.
