### ISSUE TITLE
[Bug LMMS 1.2 RC3] VSTs are loaded outside of their window

### ISSUE THREAD

**Issue by Zeioth** [LMMS/lmms#3766]
This is what happens when I load a VST in LMMS 1.2. As you may notice, it loads (and works) correctly, but the window is duplicied/broken.

![as](https://user-images.githubusercontent.com/3357792/29254192-2aacda90-8090-11e7-9241-7117619b4cc4.png)

This bug does not exists in LMMS 1.1.3

![cv](https://user-images.githubusercontent.com/3357792/29254213-8ffd5f0a-8090-11e7-8984-c635fa97cc6f.png)

Probably you already know about this. If that is the case, please feel free to close this issue. Thank you for your time.

Extra notes: I've tested it with 'libwine', 'wine-stable', and 'winehq-staging', with the same results.

**Comment by PhysSong** [comment]
Known issue #2855. Currently for X11+Qt5.
1.1 uses Qt4, but 1.2 uses Qt5.

It will be fixed in 1.2.0 stable release.
