### ISSUE TITLE
Glitch with layered sustained notes

### ISSUE THREAD

**Issue by zonkmachine** [LMMS/lmms#3777]
Got one more glitch with recording sustain that I unfortunately missed when testing. Some layered notes seem to finish early and the lost length is added to the following note. True both for chords and single notes played multiple times when under sustain.

Example. C-maj played struck twice:
![sustain](https://user-images.githubusercontent.com/6368949/29738776-58bf9b38-8a2d-11e7-8af5-f3ef3416c2db.png)

Should have been:
![sustain2](https://user-images.githubusercontent.com/6368949/29738779-621a45de-8a2d-11e7-890c-e693d40a0dd0.png)

@serdnab

**Comment by PhysSong** [comment]
https://github.com/LMMS/lmms/blob/v1.2.0-rc3/src/gui/editors/PianoRoll.cpp#L3486
The if clause compares only the notes' keys, not their positions. So lengths can be mixed.

**Comment by zonkmachine** [comment]
I can't replicate this. May have been fixed in https://github.com/LMMS/lmms/commit/81966fa1a68293a5dfa37408da993bc95ac8402d . Need to test this more though.

**Comment by zonkmachine** [comment]
> https://github.com/LMMS/lmms/blob/v1.2.0-rc3/src/gui/editors/PianoRoll.cpp#L3486
> The if clause compares only the notes' keys, not their positions. So lengths can be mixed.

If it can be replicated I guess a fix then would be as easy as changing this line from:
https://github.com/LMMS/lmms/blob/afd22c8b74e23f6a89f2fac9ae596dd16979f4f7/src/gui/editors/PianoRoll.cpp#L3486

to:
```cpp
 if (it->key() == n.key() || it->pos() == n.pos())
```

**Comment by PhysSong** [comment]
> `if (it->key() == n.key() || it->pos() == n.pos())`

Shouldn't it be `&&`?

**Comment by zonkmachine** [comment]
That is what I meant. Tried it and it didn't record anything. :-/

**Comment by PhysSong** [comment]
`InstrumentTrack::processInEvent()` doesn't save the time offset in `NotePlayHandle`s when received `MidiNoteOn`, that's why the `&&` doesn't work.
I think the fix is from #3803. One problem is that it assumes notes in a `Pattern` is always sorted by position. It might be fine because `Pattern::addNote()` always ensure that, at least for now.

**Comment by zonkmachine** [comment]
OK. I think we're fine closing this then.
