### ISSUE TITLE
AFP: 3 dials moves if sample is moved

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#3782]
win32 RC3
Insert any sample in a AFP
Magnify sample for best visual
point on the spectrum in either end
The hand-cursor is shown
move the sample
Observe the dials, for start, end and loop, they will turn, and the settings are also changed (eg the span of the selection is not fixed)
I would expect only the sample to move, not the selection

**Comment by zonkmachine** [comment]
> I would expect only the sample to move, not the selection

It's the selection you're moving. It's just another way of doing it. This way you move all three settings at the same time.
