### ISSUE TITLE
Sample track: delay feature

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#3784]
*Suggestion 1.2.x*
Just as we have **DEL** in default instrument-ENV, a DELay would be very useful in *Sample-track.*
A DELay with 1½ bars span, would make it easy to synchronize a sample, with the beat in the project. That is a difficult task with current sample-track features
-Ideally sample-track should have default ENV and LFO, inculuding default filters, but DEL is a minimum requirement

**Comment by BaraMGB** [comment]
Why you don't move the sample to the right position?

**Comment by PhysSong** [comment]
You can use Ctrl + Drag(press Ctrl key after you start dragging) to adjust sample positions precisely.

>Ideally sample-track should have default ENV and LFO, inculuding default filters

I think including filter is a good idea, too.

**Comment by musikBear** [comment]
@BaraMGB @PhysSong 
> Why you don't move the sample to the right position?

That is exactly what we need to do now, and it would imo be much better to turn a dial, during playback. Mouse dragging to correct ms, is not perfect. Turning a dial would be a quality-method

**Comment by musikBear** [comment]
I wonder if this 'oldie' isent fixed with the Master-feature of *snapping outside bar-divider* in song-editor? If the granularity is all down to 1/192, i would say it is, but what is the general opinion on that?

**Comment by Spekular** [comment]
Yes, this can easily be accomplished by moving the sample track forward the appropriate amount, or with a delay effect. Thanks for the heads up :)
