### ISSUE TITLE
Missing folder when trying to start LMMS a second time (Qtcore4.dll)

### ISSUE THREAD

**Issue by ImirTournevis** [LMMS/lmms#3793]
When I first downloaded LMMS, it started as normal, but the next time I wanted, a folder was missing (name is "Qtcore4.dll"). It advised me to redownload LMMS, what I have done. 

But that has restarted. The first time it works, but the second time the folder (always the same btw) is missing. So I checked in the folders of LMMS ans I CAN FIND IT. WTF? I can find the folder it tells me it's missing, and when I start LMMS it continues to tell me the folder isn't there. 

![bug wtf](https://user-images.githubusercontent.com/31613477/30016885-4400897e-9157-11e7-8e58-28fb7976cb57.PNG)

Someone knows the problem? Did it ever happen to someone? I can't find the problem with this, if someone knows whatever about, please tell me. Thanks.

_Edit zonkmachine: fixed formatting_

**Comment by tresf** [comment]
This is generally a sign that the software was still in memory when installation occurred or that your drive has corrupted the files needed by LMMS.

The fact that it works the first time only is suggestive that something is corrupt.

Please do the following which will correct both problems:

1. Reboot
2. Uninstall LMMS
3. Run a scandisk on the computer (requires reboot)
4. Reinstall LMMS

**Comment by musikBear** [comment]
In addition to what tresf said -do remember to get rid of the LMMS-config-file:
read: https://lmms.io/wiki/index.php?title=LMMS_Settings#Problems_with_Settings

**Comment by tresf** [comment]
@musikBear thanks.  That helps with LMMS problems in general, but the `.dll` missing can only occur if `lmms.exe` is having problems loading.  Nothing inside the config file points to `QtCore4.dll` (plugins, yes -- some of them, Qt, no). :)

**Comment by zonkmachine** [comment]
No response, closing!

@ImirTournevis Please reopen if this is still an issue.
