### ISSUE TITLE
Annotations on timeline

### ISSUE THREAD

**Issue by DeRobyJ** [LMMS/lmms#380]
Let's say you are listening to your work in progress track in playback, and you think that there is a problem in a certain part: you know that you need to do something, but you can't figure out what, at the moment.
What would you do? You would probably take the Project Notes and write: "From bar 23 to bar 42, in the lead synthesizer track, there is a problem". 

As things like that happens many times, especially when collaborating with others, LMMS should offer an Annotation tool on the Song-Editor that allows you to highlight a certain part on the timeline and put some text as an annotation.

What will be highlighted? There are two different ideas:
- Highlight the timeline
  ![image](https://f.cloud.github.com/assets/6437521/2250811/6b458832-9d94-11e3-9d1a-00802139784c.png)
- Highlight part of the track:
  ![screenshot_5](https://f.cloud.github.com/assets/6437521/2250818/79fc9406-9d94-11e3-85ec-a7e6e3a9eafd.jpg)

**Comment by NETMANSKY** [comment]
I have adapted to lay out the timeline here:
![21](https://user-images.githubusercontent.com/14283492/53288266-7724ca80-3797-11e9-858d-2e8bd6851f2b.png)
I hope someone will come in handy

**Comment by NETMANSKY** [comment]
Can we make a track coloring but not pattern? It's more comfortable in my opinion. And pattern coloring also must be.

**Comment by musikBear** [comment]
Both 'annotations' ao named bookmarks has been up, and some day someone will make it, because it has been agreed to.
@NETMANSKY years ago i made this:
https://www.youtube.com/watch?v=jMPH5prCMv4

**Comment by tresf** [comment]
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.
