### ISSUE TITLE
Automations continue after the end of their TCOs.

### ISSUE THREAD

**Issue by Sawuare** [LMMS/lmms#3800]
![automations tcos bug](https://user-images.githubusercontent.com/25503477/30249122-4f90262e-963d-11e7-9e51-6cd62537fa1d.gif)

_The project file:_ [Automations TCOs bug.zip](https://github.com/LMMS/lmms/files/1290519/Automations.TCOs.bug.zip)

The automation in the GIF and the project automates the volume of BitInvader.
Automation TCO 1 is the same as 2, but 1 is shortened.
Automation TCO 1 behaved like 2, but it should have behaved like 3, by stopping the automation at its end and mapping the last value in the automation to the automated parameter.

**Comment by PhysSong** [comment]
Related: #3382, #662.

**Comment by musikBear** [comment]
Confirm win32 RC3
Could be related to the smart addition of setting automation value according to play-head pos - eg #3382

**Comment by zonkmachine** [comment]
As @musikBear points out this is from #3382. It's by design. @tresf Right?

**Comment by Umcaruje** [comment]
@zonkmachine I'm pretty sure that this is a bug, because the value should stay from the last value of the automation clip, not from the values that are hidden. @lukas-w do you agree?

**Comment by zonkmachine** [comment]
Right. Now I got it. It's a bug, sorry.

**Comment by lukas-w** [comment]
Definitely a bug.

**Comment by PhysSong** [comment]
There are some tricky things. For discrete progression, the value should stay the last value **before** the end point(the value **at** the end point shouldn't be included), while it should be the value at the end point for other progressions.
Anyway, I found that `TrackContainer::automatedValuesAt()` doesn't check automation patterns' length. We may check the length there.
