### ISSUE TITLE
receive mute

### ISSUE THREAD

**Issue by sv1it** [LMMS/lmms#3801]
From time to time when returning from transmit to receive the receive audio is muted and I need to restart the mchf. Any ideas?

**Comment by Umcaruje** [comment]
Sorry, this is the issue tracker for an open source DAW, not mchf. Quoting @zonkmachine:

>> I am looking for the MCHF group.
>
>This isn't it. We're coding a music studio here. :wink: 
>
>The closest I could find was these accounts:
>https://github.com/imoldovavan/mcHF-SDR
>https://github.com/df8oe/UHSDR
>
>http://www.m0nka.co.uk/?page_id=2
>
>According to [this description](https://github.com/df8oe/UHSDR/wiki#the-mchf), [This yahoo group](https://uk.groups.yahoo.com/neo/groups/M0NKA-mcHF/info) is where the development is made.

**Comment by sv1it** [comment]
Sorry
