### ISSUE TITLE
Can it be possible to save a frequency and the DSP, BW and other relavent settings to be opened up later?

### ISSUE THREAD

**Issue by Lars-mcHF** [LMMS/lmms#3802]

**Comment by Lars-mcHF** [comment]
During operation of the mcHF radio it would be nice to find really good setting and then come back to them at a later time. This can also be seen as a good way to test different settings to eliminate noise, QRM or other settings that affect the audio. Save the frequency and the settings that go along with it and make changes to the settings and then compare to see if it is better or not better.

**Comment by Lars-mcHF** [comment]
I am not sure this is where or how to use this web site, and I see this is not the place where I want my question asked, I am looking for the MCHF group.

**Comment by zonkmachine** [comment]
> I am looking for the MCHF group.
This is't it. We're coding a music studio here. :wink: 

The closest I could find was these accounts:
https://github.com/imoldovavan/mcHF-SDR
https://github.com/df8oe/UHSDR

http://www.m0nka.co.uk/?page_id=2

**Comment by zonkmachine** [comment]
According to [this description](https://github.com/df8oe/UHSDR/wiki#the-mchf), [This yahoo group](https://uk.groups.yahoo.com/neo/groups/M0NKA-mcHF/info) is where the development is made.

**Comment by Lars-mcHF** [comment]
thank you for closing

my mistake

i did find the right group

                       n_n
