### ISSUE TITLE
Window title in title bar blinks after adjusting specific knobs related to time or speed.

### ISSUE THREAD

**Issue by Sawuare** [LMMS/lmms#3807]
![title bar](https://user-images.githubusercontent.com/25503477/34035842-5b231cce-e194-11e7-8c53-0caa0e9a1524.png)
After adjusting specific knobs related to time or speed, like ARPEGGIO's `TIME` and LFO's `SPD`, the window title in the title bar (underlined in the image above) blinks.

Unfortunately, my GIF recorder wasn't able to catch the blinking. 😅

**Comment by zonkmachine** [comment]
Can you please come up with a better title without home made acronyms? :wink:

**Comment by Sawuare** [comment]
Sure.

**Comment by Sawuare** [comment]
Seems fixed on my master-based branch.

**Comment by Sawuare** [comment]
Closing this because I can't reproduce it on 1.3.0-alpha.1.
