### ISSUE TITLE
Bar numbers in Piano Roll alignment is misleading

### ISSUE THREAD

**Issue by unfa** [LMMS/lmms#3812]
Hey!

I got used to bar numbers being displayed over the middle of a bar, and in 1.2 RC3 they are shown near the left border - I miss the spot all the time because of this change.

I guess this was a rather A E S T H E T I C change, but it's actually affecting my productivity in a negative way.

![selection_024](https://user-images.githubusercontent.com/491704/30555958-81a6d6ae-9ca9-11e7-80b6-a1dc1d011f1c.png)

I think the bar numbers should be center-aligned, as that's easier to read in an eyeblink. Now I have to second guess, and I often guess wrong, ending in the 3rd bar instead of the 4th. And in the 7th instead of the 8th.

Same applies to Piano Roll, Automation editor and Song Editor.

Anybody can confirm confusion?

**Comment by Spekular** [comment]
Same thing here.

**Comment by gi0e5b06** [comment]
Make it an option. (left, center, right).
Personnally I prefer to have them on the right but that's probably not the best for every one
![bars_pos](https://user-images.githubusercontent.com/30031949/30557437-8b33dce4-9cae-11e7-9c7a-a0c327e6e957.jpg)
.

**Comment by tresf** [comment]
> Make it an option. (left, center, right)

Whatever makes sense is what we should default it to.  If a handful of musicians can come to an agreement, we us that.  Another option is to provide an override in the theme file, but we don't normally do this for alignment.  A sane default is what we need.

**Comment by musikBear** [comment]
opinions wanted?..
Im fine with left-most or center.
Rightmost seams to be weird to me.
Fls has them leftmost, as do pro-tools..
@Umcaruje -How does bitwig place them?

**Comment by zonkmachine** [comment]
I think to the left is most common and a good default.

**Comment by Umcaruje** [comment]
>@Umcaruje -How does bitwig place them?
On the left side: 
![image](https://user-images.githubusercontent.com/6282045/30603155-f41d7a5e-9d66-11e7-9f4e-a58f76d871ec.png)

 I can't say I've had an issue with this when using either LMMS or Bitwig.

**Comment by tresf** [comment]
* @zonkmachine says "I think to the left is most common and a good default"
* @Umcaruje says "On the left side [...] I can't say I've had an issue with this"
* @musikBear says "Fls has them leftmost, as do pro-tools [...] Im fine with left-most or center.

BTW, Hydrogen is left-most as well.   Sorry @unfa, you'll just have to get used to this.

**Comment by gi0e5b06** [comment]
That's why LMMS is going nowhere.
Important stuff is discarded just to avoid adding three lines of code...

**Comment by tresf** [comment]
Please don't confuse consensus with avoidance.  I had gotten used to the old too, but progressive change is good.  We're coding to the standards -- not the old habbits -- which should be encouraged, not discouraged.

Please keep arguments objective.  Regression happens when subjective arguments get in the way of objective ones. <3

**Comment by tresf** [comment]
@gi0e5b06 if you have a particular theme in mind that will suffer as a result of this change, we'll take the feature back in a CSS-property update, but the software would default to the left moving forward and UI decisions will be based with that assumption in mind.
