### ISSUE TITLE
LcdSpinBox Inconsistency with "4"

### ISSUE THREAD

**Issue by Texxiliator** [LMMS/lmms#3821]
If you edited/looked at the custom Lmms numbers you would notice the the "4" is by 1 pixel off unlike the others : 
![image](https://user-images.githubusercontent.com/29334338/30775361-405bd0ae-a092-11e7-9bce-a6cf06c2d58a.png)

I know its 1 pixel but it still looks weird. Here is how it should look like : 
![image](https://user-images.githubusercontent.com/29334338/30775372-76fa29bc-a092-11e7-9373-712bb5f2d5d4.png)
Also here is the download for the fixed version : http://www.mediafire.com/view/8a43g4wa6sk2g5z/lcd_19green.png

Also we could get rid of the other LCD numbers since i find them useless.

(Also sorry if this issue has been brought up before. I could not find any.)

**Comment by tresf** [comment]
@Texxiliator this should be patched for all versions of our LCD.  If you submit a pull request, we'd happily accept it.  https://github.com/LMMS/lmms/tree/stable-1.2/data/themes/default

**Comment by BaraMGB** [comment]
Can you please provide a pull request for the correct png?

**Comment by Texxiliator** [comment]
Ok 
But what is the pink lcd used for? @tresf

**Comment by tresf** [comment]
@Texxiliator I don't believe the others are being used by the codebase, but until we [pull support for them](https://github.com/LMMS/lmms/blob/32f07ac317b42dda42a1d00b0a3b1fa1feef0655/src/gui/widgets/LcdWidget.cpp#L273) we should keep them consistant.

**Comment by Texxiliator** [comment]
@tresf We could also rename the lcd_19pink.png to lcd_19purple.png since thats the actual color. Or we could change it a little bit to be more pink and use it for SF2 Player.

**Comment by Umcaruje** [comment]
This should be a change in the actual svg files over on [`LMMS/artwork`](https://github.com/LMMS/artwork) as well. I'll look into this

**Comment by Umcaruje** [comment]
@RebeccaLaVie is looking into the issue.

**Comment by RebeccaLaVie** [comment]
I have created a pull request for the short term alignment fix here #3864.

Longer term, all references to the additional LCDs should be removed as the primary green color is all that is necessary.

**Comment by zonkmachine** [comment]
Fixed in https://github.com/LMMS/lmms/pull/3864.
