### ISSUE TITLE
TCOs in BB editor are draggable since #3649

### ISSUE THREAD

**Issue by PhysSong** [LMMS/lmms#3822]
Steps to reproduce:
1. Create a new project.
2. Open BB editor.
3. Add TCOs by any possible ways(put notes, add automation track or sample track, etc.)
4. Try to drag them.

Note that this behavior is only in `master` branch.
@BaraMGB

**Comment by BaraMGB** [comment]
I'll have a look.

**Comment by Umcaruje** [comment]
Closed via #3832
