### ISSUE TITLE
Folder tracks

### ISSUE THREAD

**Issue by vktec** [LMMS/lmms#3836]
Many DAWs have folder tracks as a way to categorise other tracks. For example, the percussion section of a song could be contained within a folder which can be collapsed when not working on percussion, cleaning up the track list.

Ideally, this would work both in the Song Editor and the Beat+Bassline Editor.

**Comment by Spekular** [comment]
Duplicate of #735, I believe

**Comment by vktec** [comment]
Oops. Subscribed to that instead. Thanks!

**Comment by vktec** [comment]
This is why we need isaacs/github#253...
