### ISSUE TITLE
Opening a project with LB302 with specific waveforms produces a noise burst.

### ISSUE THREAD

**Issue by Sawuare** [LMMS/lmms#3842]
🔊 

To reproduce:
1. Load an LB302 instrument.
2. Change the waveform to one of the following underlined types:
![image](https://user-images.githubusercontent.com/25503477/31046039-63199622-a5fa-11e7-9165-9264fc174a93.png)
3. Save the project (the format of the project file doesn't matter).
4. Open the project.

_An example project file:_ [LB302 noise burst.zip](https://github.com/LMMS/lmms/files/1346412/LB302.noise.burst.zip)

**Comment by zonkmachine** [comment]
This is there already in 1.0.3 .

**Comment by michaelgregorius** [comment]
@Sawuare, this should be fixed with #3844.

**Comment by michaelgregorius** [comment]
Closed with the merge of #3844 into `master`.
