### ISSUE TITLE
Some headers are not checked by cmake

### ISSUE THREAD

**Issue by ycollet** [LMMS/lmms#3846]
Under linux, the following headers are not checked by the cmake script:
pulse/pulseaudio.h
vorbis/codec.h

Tested after a fresh install of fedora 26.

**Comment by PhysSong** [comment]
What do you exactly mean here?

**Comment by ycollet** [comment]
Sorry, I doubled check and these headers are checked by cmake.
I don't know what happened. Maybe a problem with my CMakeCache.txt.
I close this bug.
