### ISSUE TITLE
Clicking on VST interface moves/offsets it on certain VSTs

### ISSUE THREAD

**Issue by piece-o-ham** [LMMS/lmms#3853]
On at least 2 VSTs, clicking the UI moves/offsets the UI within the VST window. Below are some screenshots demonstrating this behavior with the Helm VST:

![screenshot_2017-10-03_01-48-03](https://user-images.githubusercontent.com/10082900/31113135-5a017002-a7dd-11e7-9a0d-0d081c350621.png)

This is what it looks like initially. Clicking on the VST changes it to this:

![screenshot_2017-10-03_01-48-34](https://user-images.githubusercontent.com/10082900/31113100-3f0f3b94-a7dd-11e7-86aa-3c37a69f2754.png)

It moves slightly down and to the right. Clicking a second time produces this:

![screenshot_2017-10-03_01-48-57](https://user-images.githubusercontent.com/10082900/31113139-611af03e-a7dd-11e7-922e-8943faa38585.png)

What's weird is that it doesn't matter where I click. It also seems to follow the same pattern every time I load the VST. Hiding and then showing the GUI doesn't seem to do anything. It also doesn't move if I click outside of the VST itself (i.e. in the area where the VST was before it moved). It also isn't a visual glitch; the actual location of the control moves too. It doesn't happen for other input like scrolling or button presses; just mouse clicks.

I know that this doesn't happen with all VSTs since I used one where this doesn't happen.

I am using wine version 2.0.2

**Comment by karmux** [comment]
I've experienced same problem with some plugins before I started to use newer implementations of VST windows in LMMS. They somehow fixed this annoying bug for me. Could you compile PR #3786 and see if it still happens? That pull request will be in 1.2 release.

**Comment by piece-o-ham** [comment]
Yep. Fixed it. Thanks.

**Comment by PhysSong** [comment]
Closing since #3786 is merged and it has been included in rc5.
