### ISSUE TITLE
RC4 : Export mp3 tests

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#3854]
rc4 win32 xp_3
@zonkmachine - as discussed 
Has tested MP3 export. Looks very good! 👍 
Tests:
**Onion** -> mp3
```
Full song          
Export as         Size on disk
* 064 b           : 1635 kb 'Joint Stereo'
* 320 b           : 8173 kb 'Joint Stereo'
Selection
* 064 b bar 21-32 : 162 kb  'Joint Stereo'
* 128 b bar 21-32 : 323 kb
* 160 b bar 21-32 : 404 kb
* 192 b bar 21-32 : 484 kb
* 256 b bar 21-32 : 646 kb
* 320 b bar 21-32 : 807 kb
-----------------------------------
* 320 b bar 21-32 : 807 kb 'Stereo'
* 320 b bar 21-32 : 807 kb 'mono'
-----------------------------------
Export as loop
* 160 b bar 21-32 : 404 kb  'Joint Stereo'
```
All rendered mp3 soundfiles with excellent sound quality. Surprisingly low disk-usage.   

Cancel during render: No crash. File is *saved* upto press of cancel 👍 
Would like if 
* user could choose *his* default export-settings
* sinc & oversampling was not shown unless it works in chosen format

Small problems
* still this confusing double selection
* miss a *render-finished* indication -like have '100%' lit up in green. Especially for my mediocher hw, because it takes 3-30 secd before the save process is finished, *after* the 100% has been reached
If i change to folder-view, this is what i see:
![rc4renderpause](https://user-images.githubusercontent.com/6662066/31137415-807b99d6-a86b-11e7-89fd-e099df30a50f.JPG)

**Comment by zonkmachine** [comment]
Please just post bugs and feature requests. Not what works. I suggest deleting everything before the second :+1:

> * user could choose his default export-settings

https://github.com/LMMS/lmms/issues/678

> * sinc & oversampling was not shown unless it works in chosen format

Sinc and oversampling apply to all output formats. First you render and then the encoding is applied. I read a comment somewhere on oversampling perhaps being defunct but that's an issue of it's own.

**Comment by zonkmachine** [comment]
> still this confusing double selection

This is the only remark in here that isn't 'invalid' or mentioned elsewhere. I have to close this one.
With invalid I'm referring to the test information above about mp3 exporting actually working. We only need issue reports about what is **not** working.
