### ISSUE TITLE
some bug with lmms

### ISSUE THREAD

**Issue by killjoyrekt** [LMMS/lmms#3857]
![screenshot 31](https://user-images.githubusercontent.com/32206707/31166741-52edd710-a922-11e7-8fa5-57dc6e631b1f.png)

**Comment by killjoyrekt** [comment]
plz help cos this happens quite often

**Comment by BumblingCoder** [comment]
Is there a particular sequence of actions that triggers the issue? Unfortunately that error message is a generic message from the operating system that doesn't give any information to debug the issue.

**Comment by PhysSong** [comment]
If your audio backend is set to PortAudio, please try SDL instead.

**Comment by musikBear** [comment]
@killjoyrekt On forum you can find several c++ runtime solutions, but we ned to know more about your system:
please post your:
* OS (+service-pack-version)
* lmms version
* hardware specification (ram & soundcard is the most important)
* Latency setting
* lmms sound device chosen
Best on a forum help-ticket
http://lmms.io/forum/viewforum.php?f=7

**Comment by killjoyrekt** [comment]
th update to rc4 was better i think, it doesnt happen anymore since i updated it
