### ISSUE TITLE
Instrument 'on' glitch

### ISSUE THREAD

**Issue by zonkmachine** [LMMS/lmms#3859]
On instrument tracks. If the volume is really low, as is often the case with some of the louder pluggins (3osc, bitinvader...) , there is shot noise the first time the track is switched on. When you press play the first time after loading a project or if the track was saved in a muted state, when you unmute it.

Steps to reproduce.
Default project, turn volume all the way down.
Enter one note and save the project.
Reload the project and press play.
Pop!
Press  stop and then play again... Silence!
Mute the instrument, save and reload.
Play and then unmute. Pop!

This is a regression on master after 1.1 and was possibly introduced in 23433a70b577bc67f2836c0ae98a4dc48ae40f93 but that commit has turned out as a possible false positive when bisecting before (https://github.com/LMMS/lmms/issues/3685).
@PhysSong

**Comment by PhysSong** [comment]
Tested, it **is** related to the value buffer. Uninitialized `m_oldValue` causes that. I think it was present before 1.1, but occured very rarely. I think memory manager increased memory reuse and that's the reason of increased rate of many bugs, especially related with uninitialized variables.
https://github.com/LMMS/lmms/blob/e7e24935b35a15066c549f4634b35ffb81910226/src/core/AutomatableModel.cpp#L594-L601

**Comment by zonkmachine** [comment]
OK, cool!

I suggest you assign this to yourself and pull something... ;)

**Comment by PhysSong** [comment]
A simple workaround for this: initialize `m_oldValue` in suitable positions, such as constructor and/or `loadSettings()`.

The code above is for smooth automation processing. However, non-automated changes or even uninitialized variables may generate unnecessary(and somtimes nonsense) value buffers. So I think we should fix that logic.

**Comment by PhysSong** [comment]
The code above is for interpolating automations, but it is applied even for non-automated changes. This part needs some works.

**Comment by zonkmachine** [comment]
> A simple workaround for this: initialize m_oldValue in suitable positions, such as constructor and/or loadSettings().

I tried both and that worked. It also fixed the buggy project in https://github.com/LMMS/lmms/issues/3685. As I don't know how to deal with `loadSettings()` properly I'm not going to PR this. When testing I just tucked `m_oldValue = 0.0f;` to the end of `loadSettings()` but that looks a bit sketchy.

**Comment by zonkmachine** [comment]
> A simple workaround for this: initialize m_oldValue in suitable positions, such as constructor and/or loadSettings().

Initializing m_oldValue in the constructor gave me a clearly reproducible NaN with one of my projects. Just keeping the one in loadSettings() still works though.

**Comment by PhysSong** [comment]
I'm testing this for `setInitValue()`, seems to be work fine. After some tests and consideration for more situations, I'll create a PR. :)

**Comment by zonkmachine** [comment]
> I'm testing this for setInitValue(), seems to be work fine. After some tests and consideration for more situations, I'll create a PR. :)

Yes, I was getting another bug. Backed some 20 commits and it was working again. :man_dancing:

**Comment by PhysSong** [comment]
For 1.2, I have two choices:
- Fix issue with initial value only. It fixes this.
- Fix issue with non-automated changes too. Undesirable but not relevant to this issue.

**Comment by zonkmachine** [comment]
> * Fix issue with initial value only. It fixes this.

Simplest?

**Comment by zonkmachine** [comment]
> Fix issue with non-automated changes too. Undesirable but not relevant to this issue.

Sorry, I don't know what that means.



> Fix issue with initial value only. It fixes this.

Does this mean what we tried above already? Sounds like a good idea then.
