### ISSUE TITLE
Crash when copying audio TCOs between LMMSs.

### ISSUE THREAD

**Issue by Sawuare** [LMMS/lmms#3862]
Using Windows 10 Pro, 64-bit OS, x64-based processor with LMMS 1.2.0-rc.4.

To reproduce:
1. Open 2 LMMSs.
2. In each LMMS, add either a sample track or an AFP.
3. Add a TCO with info (not an empty sample track or AFP) to the track of a LMMS.
4. Control and drag the TCO from one LMMS's track to the other to make a copy.

Once the copied TCO enters the track, LMMS will crash, the runtime error window will appear,
![image](https://user-images.githubusercontent.com/25503477/31308339-0a58391a-ab7e-11e7-863b-2169893eb317.png)
then the "LMMS has stopped working" window will appear.
![image](https://user-images.githubusercontent.com/25503477/31308347-298e047c-ab7e-11e7-89d2-19c1491c34f1.png)

**Comment by musikBear** [comment]
Could not recreate *exactly* on win32. rc4 xp3
However, for** AFP **the actual TCO is *stripped* and only the instrument is copied to 2. instance of LMMS
Copying a *3oc track* with TCO went perfect
Copying a *sample-track* track with TCO went perfect

**Comment by PhysSong** [comment]
Note that the crash only happens if a track whose index equals to the index of source track doesn't exist in target LMMS instance.

**Comment by PhysSong** [comment]
Should be fixed in #4862.
