### ISSUE TITLE
Crash when hitting play directly after un-muting 4+ mixer channels

### ISSUE THREAD

**Issue by millicow** [LMMS/lmms#3863]
I'm not quite sure how this works or if I understand it correctly, but it's something like that. This screen recording can show it better than I can explain it: https://youtu.be/SnAo0ng14ec . (Sorry about the weird glitches showing my wallpaper. That happens sometimes when I record my screen.)

In the video when I get the project open, up until 0:50 I show how playing, stopping, playing works fine. Then, I go re-enable the other mixer channels that were muted. As soon as I hit play, nothing happens. The play/pause button does nothing and as soon as I hit stop, everything freezes.

I have replicated this several times with the same results each time. After a quick few tests, it seems like **this happens only if I re-enable 4 or more channels before hitting play.** 3 or fewer and playing still works. I tried enabling 3, playing, stopping, then enabling one more, and then it did the same thing. (I don't remember how I got past this originally. I must have re-enabled them all, saved, closed, then re-opened the project. It's been a few weeks; I just now bothered to make this post.)

I'm running Linux Mint 18.2 64-bit, and this screenshot might contain some useful information about the LMMS version and stuff:

![image](https://user-images.githubusercontent.com/32624371/31322994-5d5e7546-ac66-11e7-8c6f-47c74e9254ad.png)

**Comment by zonkmachine** [comment]
The mixer crashes has been fixed already. If you want to try the latest version, which is 1.2.0-rc4 ( 4th beta release ), you can either build it from source or download an AppImage from [here](https://github.com/LMMS/lmms/pull/3688).
Just download and make it executable and it should run directly from the downloads directory.

I'm closing this as fixed. Please reopen if you can replicate the bug on a recent build.
