### ISSUE TITLE
LMMS 1.2.0-rc4.113 have some trouble with csladspa in Ubuntu 17.10

### ISSUE THREAD

**Issue by Z3R0C** [LMMS/lmms#3869]
LMMS did'nt run in Ubuntu 17.10 with installed ubuntustudio-audio-plugins.

`*** Error in `/opt/zeroc-DATEN/git/lmms/build06/lmms': free(): invalid pointer: 0x00007fffffffe5b3 ***

Thread 1 "lmms" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: Datei oder Verzeichnis nicht gefunden.
(gdb) backtrace 
#0  0x00007ffff37d10bb in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff37d2f5d in __GI_abort () at abort.c:90
#2  0x00007ffff381b29d in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff3942408 "*** Error in `%s': %s: 0x%s ***\n")
    at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007ffff382265a in malloc_printerr (action=<optimized out>, str=0x7ffff393ed8e "free(): invalid pointer", ptr=<optimized out>, ar_ptr=<optimized out>)
    at malloc.c:5423
#4  0x00007ffff382474e in _int_free (av=0x7ffff3b74c20 <main_arena>, p=<optimized out>, have_lock=0) at malloc.c:4172
#5  0x00007ffff382940e in __GI___libc_free (mem=<optimized out>) at malloc.c:3142
#6  0x00007fffa5f67400 in  () at /usr/lib/ladspa/csladspa.so
#7  0x00007fffa5f67622 in ladspa_descriptor () at /usr/lib/ladspa/csladspa.so
#8  0x000055555568a740 in LadspaManager::addPlugins(_LADSPA_Descriptor const* (*)(unsigned long), QString const&) (this=this@entry=0x55555601b1c0, _descriptor_func=_descriptor_func@entry=0x7fffa5f67600 <ladspa_descriptor>, _file=...) at /opt/zeroc-DATEN/git/lmms/src/core/LadspaManager.cpp:147
#9  0x0000555555691d41 in LadspaManager::LadspaManager() (this=0x55555601b1c0) at /opt/zeroc-DATEN/git/lmms/src/core/LadspaManager.cpp:89
#10 0x0000555555687e7a in Ladspa2LMMS::Ladspa2LMMS() (this=0x55555601b1c0) at /opt/zeroc-DATEN/git/lmms/src/core/Ladspa2LMMS.cpp:30
#11 0x000055555566e9d8 in LmmsCore::init(bool) (renderOnly=renderOnly@entry=false) at /opt/zeroc-DATEN/git/lmms/src/core/Engine.cpp:64
#12 0x0000555555712c83 in GuiApplication::GuiApplication() (this=0x555555cd94d0) at /opt/zeroc-DATEN/git/lmms/src/gui/GuiApplication.cpp:120
#13 0x000055555562f434 in main(int, char**) (argc=<optimized out>, argv=<optimized out>) at /opt/zeroc-DATEN/git/lmms/src/core/main.cpp:801
`

**Comment by PhysSong** [comment]
Looks like a  n upstream bug. I'll take a look at this.

**Comment by PhysSong** [comment]
I can reproduce the same issue with other hosts(ex. Audacity). Since LMMS don't have per-plugin enable/disable feature, the only solution is renaming(or removing) affected csd files or removing csladspa completely.

**Comment by bhechinger** [comment]
This is still broken in 18.04 and affects many tools. Is there an update to when the upstream provider may fix this?

**Comment by zonkmachine** [comment]
According to [this thread](http://tracker.ardour.org/view.php?id=7502) on the Ardour bug tracker, this is an issue in csound and has been fixed. Try the latest release of csound. ~6.10.0 or later should work.

**Comment by bhechinger** [comment]
I had opened a ticket in the csladspa project and he said it was fixed. I'm not sure if the fix made it into 6.10.0 though, still waiting to hear back. 6.10.0 is what ships with 18.04 and I'm still seeing this as an issue.

**Comment by zonkmachine** [comment]
OK. I'm unsure about the specific issue I linked to but I don't have time to look into it right now. Can you try the latest of csound/csladspa? If the csladspa people say it's fixed it probably is. There's not much we can do here from lmms.

**Comment by bhechinger** [comment]
Nah, you guys aren't involved at this point. I'll leave you alone now. :)
