### ISSUE TITLE
No sound for imported wav file unless started from beginning.

### ISSUE THREAD

**Issue by alextappin** [LMMS/lmms#3874]
Hi everyone,

I am encountering an issue where I cannot navigate the track. For example, in the photo below, when I click start, my wav file starts playing.

![image](https://user-images.githubusercontent.com/7875255/31421910-1c46ec92-adff-11e7-867b-c6b56bea90ca.png)

If I stop the track and click my mouse to like the photo below (middle of the track), when I click play, nothing plays.

![image](https://user-images.githubusercontent.com/7875255/31421949-7554fbda-adff-11e7-8556-081a2825b007.png)

This is problematic for me... If I am trying to edit a song, I need to listen to the entire thing in order to hear one change I make in the middle... Is there a workaround?

This also goes for pressing play, pause, then play again. No sound unless starting from the beginning. I searched the issues with a few keywords but did not seem to find any open issues related to this one.

**Comment by tresf** [comment]
This is fixed in a future release. Can you try the beta?

https://lmms.io/download, scroll down to beta.

**Comment by alextappin** [comment]
For sure! I am downloading it at the moment. I will report back.

**Comment by alextappin** [comment]
Thank you for the quick response. Downloaded the beta 1.2.0-RC4 and can confirm it is working. Closing.

**Comment by steter** [comment]
I'm using 1.2.0-rc6 and it just happened to me. I created a song yesterday, and all was fine. When I opened LMMS today, I deleted & re-imported the audio track, as it is a Hydrogen track & I'd made some changes. When I play it from the beginning, no problem. Anywhere else, there's no audio from that wav track. Am I missing something, or is this the same bug that's supposedly closed?
