### ISSUE TITLE
Add Analog Channel Toggle

### ISSUE THREAD

**Issue by SirBothersome** [LMMS/lmms#3875]
This is an issue I've been meaning to post for a while. Currently, the instrument channel interface looks like this. 
![channel](https://user-images.githubusercontent.com/20342439/31463962-df53ae52-ae9d-11e7-810d-f057196aaecf.PNG)

 in order to change the mixing channel of an instrument, you need to hover over the LED and scroll in the respective direction of the channel. I only discovered this feature by accident and in my brief glance through the documentation, I did not find this referenced. I believe if we add a small switch next to the LED, like this
![channel2](https://user-images.githubusercontent.com/20342439/31464014-157a166a-ae9e-11e7-8961-1de043881cd2.png)
The interface would be easier to understand from the get-go. Furthermore, it could be useful in the event of hardware limitations (e.g., using a touchscreen/touchpad or if your mousewheel gets its directions mixed up, which I have experienced.) and for fine-tune adjustments

**Comment by tresf** [comment]
Some context, @SirBothersome closed this after talking on [Discord](https://lmms.io/chat) #support channel.  The beta of 1.2.0 has both the double-click popup which has up/down as well as right click quick assignment, so he found the bug report to be invalid.
