### ISSUE TITLE
Cant remove dial-memory pos

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#3877]
rc4 win 32
recently a feature was presented, where the dial pos value before an automation was initiated, would be 'remembered' by the dial.
(cant remember / find the ticket)

Very nice, but how to get rid of the value?
I tried to make a gif illustrating the issue.
Here i 
* *manually* set the dial to 100%
* then press play.

The dial will flip back to a previous tried value of 30%

![insta](https://user-images.githubusercontent.com/6662066/31512991-14bd5bac-af8d-11e7-8124-5e0499aad4e2.gif)

I cant find a way to remove this 30% from the dial. I believe that the logical way, should be *reset* in context-menu. But that does not work.
I also tried with a new automation *value*. Did not work.
I tried with a new automation *TCO*. Did not work.
I 'remove-global-automation' Did not work.
It looks like it is not possible to get rid of the value in 'dial-memory'

**Comment by PhysSong** [comment]
@musikBear Could you post the affected project file?

**Comment by tresf** [comment]
@musikBear it's from https://github.com/LMMS/lmms/pull/3382.  Your automation is putting it there because you don't have any volume set prior.  Tagging @lukas-w.

**Comment by PhysSong** [comment]
#3382 is for positions after automation patterns. I can't reproduce this.
@musikBear Without looking affected project file, we can't provide any solutions now.

**Comment by lukas-w** [comment]
Agreed. #3382 shouldn't cause this.

**Comment by musikBear** [comment]
@PhysSong i will make a demo at home, but the behaviour is as you see in the gif, but its too fast and confusing

**Comment by PhysSong** [comment]
@musikBear Could you please upload minimal part of the project, or provide exact steps to reproduce?

**Comment by musikBear** [comment]
> @musikBear Could you please upload minimal part of the project, or provide exact steps to reproduce?

I cant even get the dial into 'remember-mode' 😰 
I will have to see if i can redo what i did, if i have success i will come back here, but if cant reproduce, then this is a fluke, that will resurface one gloomy day. -still... must be related to #3382

**Comment by musikBear** [comment]
> @musikBear Could you please upload minimal part of the project, or provide exact steps to reproduce?

I cant even get the dial into 'remember-mode' 😰 
I will have to see if i can redo what i did, if i have success i will come back here, but if cant reproduce, then this is a fluke, that will resurface one gloomy day. -still... must be related to #3382

**Comment by PhysSong** [comment]
@musikBear I remember you said the original issue is:
> the dial pos value before an automation was initiated

From the project note:
> Imagine that Second 3oc block is far upstreams f.i. bar 130
I want to compose in this block, and i want to have the volume 100%
I manually set the volume 100%, and press play.

That's #3382, not the original issue

**Comment by tresf** [comment]
> only a new automation will be able to change the value

Correct.  It's arguably even a bug.   This same behavior should occur after an automation point too.  When you ask a computer to turn a knob for you it has to make some assumptions, in this case, it locks the knob to the future value.  We'll need some musicians to speak for/against this behavior to make a decision.

**Comment by tresf** [comment]
> I cant even get the dial into 'remember-mode' 😰

You can, you have to fix the automation that it adjusting it

**Comment by Spekular** [comment]
I think the most convenient for me would be that automations only "lock"
the dial when the playhead is on an automation pattern, but still seek
backwards otherwise when the playhead is moved w/ the mouse.

**Comment by tresf** [comment]
> automations only "lock" the dial when the playhead is on an automation pattern

I'm not sure this helps.  If you have a fade-out in a song and you jump past it, how does the DAW know whether or not to process it?

**Comment by tresf** [comment]
... or is this more around the fact that the volume change should only occur when the cursor is manually moved and not happen mid-play unless it hits an Automation pattern?  This would allow the live-feedback and adjustment to occur despite it being reset if one were to drag it again?

**Comment by Spekular** [comment]
the volume change should only occur when the cursor is manually moved and
not happen mid-play unless it hits an Automation pattern?

Yup, this.

**Comment by musikBear** [comment]
at least should Using *context-Reset* work as a reset
-Thats logical.

**Comment by tresf** [comment]
> the volume change should only occur when the cursor is manually moved and not happen mid-play unless it hits an Automation pattern?

@musikBear can you please rewrite this "bug" as an enhancement to do exactly that?  The title and description are completely wrong now.

**Comment by PhysSong** [comment]
> The title and description are completely wrong now.

Then do we need to keep this open?

**Comment by musikBear** [comment]
Did i ever get to do that rewrite.. cant remember -*sorry*
@PhysSong No not as an open issue. I will close it now, rewrite the issue as a request, and make a reference from the new ticket, to this. Then the history of this is kept intact
