### ISSUE TITLE
Crash on 1-tick loops

### ISSUE THREAD

**Issue by gi0e5b06** [LMMS/lmms#3879]
LMMS crashes on playing 1-tick loops, but 2-ticks loops are fine.
(rc4 master alsa)
[memory20171013.zip](https://github.com/LMMS/lmms/files/1383828/memory20171013.zip)

**Comment by qnebra** [comment]
In my case lmms holds this 1-tick loop fine, very glitchy but no crash at all. But I have compiled version with merged bunch of PRs.

**Comment by gi0e5b06** [comment]
You tried the new file? If yes, then that means it is not a logical mistake...
(btw, which OS and audio?)
Not an out of memory mistake.
Maybe a memory mistake (Segmentation fault (core dumped)) thread-related?
For me, it is not glitchy (cpu usage is low because only the instruments that don't use a lot of cpu are active) but it crashes after half a second. No problem with the 2-tick loop.

**Comment by qnebra** [comment]
I tried this one you provide in first post of this thread.
(Ubuntu 17.10, lmms use SDL2)

**Comment by gi0e5b06** [comment]
I tried the other audio drivers, same problem.
I run it under gdb and it doesn't crash.
It seems @PhysSong has the same problem (or at least it looks like) #3881 (8th comment).

**Comment by PhysSong** [comment]
I got a crash and the backtrace looks like one in #777. If there are no evidences which show this isn't #777, this should be closed as a duplicate.

**Comment by PhysSong** [comment]
You may want to take a look at #2539.

**Comment by PhysSong** [comment]
@gi0e5b06 Have you got any backtrace(s)? If so, please post it. It will help a lot.

**Comment by gi0e5b06** [comment]
Thanks @qnebra and @PhysSong, it helps a lot. It was indeed #777 (May 28, 2014).
I changed the size of the queue and it doesn't crash anymore:
MixerWorkerThread.h:
```
#define JOB_QUEUE_SIZE 2048`
```
I also added this:
MixerWorkerThread::JobQueue:
```
		if( (int) m_queueSize >= JOB_QUEUE_SIZE-16 )
			qFatal("MixerWorkerThread::JobQueue full (%d)",JOB_QUEUE_SIZE);
```
I haven't had time to fix the problem but I will. It just needs a better queue.
