### ISSUE TITLE
Version number in "About" is misleading for source builds

### ISSUE THREAD

**Issue by davidgerard** [LMMS/lmms#388]
This is a very minor issue, probably just an enhancement. But the "About" window gives the version as "0.9.91" even though it's quite a few changes after that tag.

Suggest: a git change ID string and a branch name or similar, e.g. the way LibreOffice does it - where only a tagged change-ID gets "4.2.1" or whatever, and builds around that time would be named "4.3-dev", a change-ID and a date and time of build.

**Comment by softrabbit** [comment]
This is pretty much fixed now with the **1.2.0.xxx** version numbers, right?

**Comment by PhysSong** [comment]
Yes, it is.
