### ISSUE TITLE
audio problem 

### ISSUE THREAD

**Issue by mitsoss** [LMMS/lmms#3888]
I change my audio interface from dummy to port audio, I press okay but then it becomes dummy again. I 've tried restartin etc. but nothing happens. Check it if you can and thank you in advance

**Comment by Umcaruje** [comment]
Set your audio interface to SDL

**Comment by mitsoss** [comment]
It doesn't work even when i set it to SDL

**Comment by mitsoss** [comment]
actually sometimes it works, sometimes it doesn't

**Comment by Umcaruje** [comment]
Can you hop over to our discord server at https://lmms.io/chat and go to #support
