### ISSUE TITLE
Difficult to move and delete automation points

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#3896]
rc4 win 32
Irradiate/ random in occurrence
  
recreate: 
* Open an automation
* insert any curve with ~10 points

The problem seams to be most common, at high resolutions:
* set magn to 800
* set Q to 1/192

The points are tiny, and it is difficult to 'grab' one. Quite often a new point will appear instead. 
If the points were bigger, i believe this issue would be solved
Deleting one point often removes more than one

Redo works perfect! 👍

**Comment by zonkmachine** [comment]
Something is going on there. I'll have a look.

**Comment by zonkmachine** [comment]
> The points are tiny, and it is difficult to 'grab' one. Quite often a new point will appear instead.
> If the points were bigger, i believe this issue would be solved

It's not the size of the points but the quantization level versus the zoom level. If there is a control point within the distance for the quantization the point will snap to the same level as the cursor and then you can drag it. I'm touching up the code so it'll be much smoother.

**Comment by musikBear** [comment]
@zonkmachine great 👍 -But *should* the points be that tiny? I would prefer the medium-big points, for easy mouse-grabbing. Same size in all magnifications. Imo no need to scale points
