### ISSUE TITLE
mda Piano - noise burst

### ISSUE THREAD

**Issue by Z3R0C** [LMMS/lmms#3898]
i get a really loud sound-output if i use mda Piano vst together with Calf Reverb after re-open a project. using headphones can be very dangerous. i have to wait about a minute and then i can work normally again.

is that known? 

linux 64bit, RC4-153

**Comment by PhysSong** [comment]
Could you attach affected project file? Please remove unnecessary parts if you can.

**Comment by Z3R0C** [comment]
u dos'nt need a project file.
move mda Piano into BBE, drag the Calf Reverb Effect in the FX-Mixer, save the project and open it again. thats all. 

without Calf Reverb i get a short "click" only. i think the clicking sound in combination with the reverb is the cause.

**Comment by zonkmachine** [comment]
> think the clicking sound in combination with the reverb is the cause.

Correct. If you have a transient/glitch and you run that through a reverb, it will build up a wall of noise before it's done decaying. Not totally pleasant.

**Comment by PhysSong** [comment]
There is a known issue with GUI-less VST(i)s, I guess it is the case.

**Comment by Spekular** [comment]
mda Piano has a GUI.

**Comment by musikBear** [comment]
Cant reproduce on win 32 
1.2 RC 4.6493 (Travis through 4041 build
win32 winXPsp3

**Comment by zonkmachine** [comment]
> Cant reproduce

Yes. I suspected this could have been fixed. Perhaps in 6fc4577f102e5bb60cc246a426fb9ed8b4ac3be9.

**Comment by PhysSong** [comment]
> Cant reproduce

Me too. @Z3R0C Can you reproduce this on 1.2.0-RC5?

**Comment by PhysSong** [comment]
No response and unable to reproduce. Please request reopening if the bug still exists in RC5.
