### ISSUE TITLE
lb302 inherits envelopes when dropped on an occupied track

### ISSUE THREAD

**Issue by zonkmachine** [LMMS/lmms#3899]
If you drop a new lb302 plugin on another plugin who has an envelope active the lb302 will inherit, at least a subset of the instrumentSoundShaping variables, and suddenly have components that will effect the sound but can't be edited. This doesn't seem to affect other single streamed instruments or lb302 presets.

lb302 preset that was created by dropping a new lb302 over a 3osc with a volume envelope.
[testrelease.xpf.zip](https://github.com/LMMS/lmms/files/1404568/testrelease.xpf.zip)

**Comment by PhysSong** [comment]
Confirmed. SF2 player too. LB302 and SF2 player use both `NotePlayHandle` and `InstrumentPlayHandle`. It is because `NotePlayHandle::framesLeft()` don't care if the parent instrument is single-streamed or not. I think it's quite easy to fix.

**Comment by musikBear** [comment]
This  #3419 is slightly related, because it it also about dropping presets, and have effects preserved

**Comment by zonkmachine** [comment]
> This #3419 is slightly related

Yes. At least for the end user they would appear same-ish.
