### ISSUE TITLE
Beat/Bassline: New Tracks are not added at same scale as existing tracks

### ISSUE THREAD

**Issue by vwren** [LMMS/lmms#3903]
If the Beat/Bassline Editor has had steps added greater than the default 16 beats, new tracks that are placed have the default 16 beats rather than the increased length.  This leads to inconsistent display which makes editing more confusing.  For example, the beat in these two tracks happens at the same time:
![bb_editor_timing](https://user-images.githubusercontent.com/33024401/31884766-d33a9788-b7b3-11e7-860f-be14cf97bc98.jpg)

As a new user, this caused me much confusion until I figured out what was going on.  If you click "Add Steps" it sticks 16 more beats on the end of both tracks, and they are STILL out of sync, visually.

To make things more awkward, beats after the default 16 are not accessible on the new track without going into the piano roll.  As a workaround, you can right click the track and add steps, but this has to be done for every track that is added.  I'm not sure what the benefit is of having some tracks in the loop displaying more steps in the editor than others, but I REALLY can't see a benefit to the display of the beat tracks being out of sync and different scales. (the apparent length of the loop is an illusion anyway, since I can drag-copy a beat right out past the end of the loop in the Piano Roll and it will play, and change the length of the loop, but won't show up in the Beat/Bassline editor)

![bb_editor_timing2](https://user-images.githubusercontent.com/33024401/31886754-4c86b7e6-b7bb-11e7-98f9-807be4bdb736.jpg)

I suggest that it would be helpful if all new tracks that are added to the beat loop be the same length and scaling as the longest track, at least in display, and that "Add Steps" results in all tracks having the same number of steps visible in the editor.  It might be good, too, if the editor showed the actual length of the loops, or at least implement a scroll bar to indicate that there's part of the loop outside the editor view.  That would have the added benefit of improving the visual integration between the B+B editor and the piano roll.

**Comment by zonkmachine** [comment]
> I suggest that it would be helpful if all new tracks that are added to the beat loop be the same length

This has been chaned in lmms-1.2 that hasn't been released yet.
Grab a preview version here: https://lmms.io/download/

**Comment by zonkmachine** [comment]
I'm closing this as a duplicate. Please try the latest version of lmms and see if there are any more issues to address. :)
