### ISSUE TITLE
Extreamly harsh sound when no pattern is loaded on PatMan

### ISSUE THREAD

**Issue by a2aaron** [LMMS/lmms#3909]
This bug occurs on 1.2.0-RC4 This bug does not occur on 1.2.0-RC3.

OS: macOS 10.12.5
Kernel: Darwin 16.6.0
RAM: 8 GB, DDR3, 1600 MHz
CPU: Intel Core i5 @ 3.2 GHz
GPU: NVIDIA GeForce GTX 675MX

How to reproduce:

1. Open any project. 

2. Add PatMan.

3. Try to play notes in PatMan.

I can't seem to record the sound as it will only work when playing via keyboard (and randomly stops occurring after a few keypresses have been made), but it is very harsh and the waveform window looks like the image below.

![screen shot 2017-10-23 at 4 10 27 pm](https://user-images.githubusercontent.com/15718048/31910842-c3accc60-b80c-11e7-9623-7b110e973698.png)

**Comment by zonkmachine** [comment]
Hi!

This bug was fixed in 6fc4577f102e5bb60cc246a426fb9ed8b4ac3be9
Pick up RC5 when it's done (no estimated release date).
