### ISSUE TITLE
Automation "Locked Out" Bug, Affects Exporting

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms#391]
**Edit:** This bug is with the eraser behavior and quantization.  If automation events were created with quantization of 64 and then later are edited with quantization 16, it does not properly delete the events in between.  This behavior is not present in 0.4.15.

In addition, this bug is also to address an unknown cause where the automation does not get honored on export (which arguable should be its own bug, once I can reproduce this predictably).

---
## Original Post

I have a bug to report regarding the new automation editor.

It seems there are scenarios where the old automation points can't be removed and also they playback properly but don't export properly.

I'm inclined to say this is remnant of the old "straight line" trick where you could draw a straight line by holding a modifier key and clicking two positions, but whatever the cause, I now have an automation track that I cannot make adjustments to.

This picture is an Audacity rendering of the track next to the LMMS automation.
![image](https://f.cloud.github.com/assets/6345473/2291184/07a76a70-a037-11e3-9b20-700269954764.png)
In the case of this one, instead of graduating from 50% to 100% when rendering, the volume just spikes up to 100% without any graduation.

Also, notice the unique three dots, then three dots?

I tried CTRL + A to select all dots and delete, but CTRL+A doesn't seem to do anything.  I tried clicking a few more buttons and gave up.

For this particular track, I was trying to export to WAV for the new LMMS Bandcamp album and what's most interesting is the old events seem to playback fine on the song editor, but once I export, they have undesired effects.

This bug is two fold as it prevents edits to some old automation events and creates undesired effects to exported tracks.

For now I'm going to have to remove 0.9.91 and re-install 0.4.15 to get the track rendered for the album.  I'll put 0.9.91 back on once I'm finished rendering so that I can hopefully find more bugs like this.  If the developer requires an `mmpz`, please contact me individually for this particular track.

-Tres

**Comment by badosu** [comment]
@tresf Since the automation passed through some changes could you take a look if the bug is still present?

**Comment by tresf** [comment]
I believe anything that has switched to sample-exact would no longer experience this export bug.  Dont remember the GUI receiving a respective fix though...  I'll put this on my to do list. :)

**Comment by tresf** [comment]
GUI portion still exists.  Can't delete the 1/64 automation dots on the default 1/16 Quantization setting.

I can only assume the export portion is safe enough to mark as fixed... 

One reason people may not be complaining about this is that the bezier curves really make this obsolete way of drawing dots obsolete so this isn't extremely high on the priority list.

Moving forward, we may decide to store the Quantization setting per-pattern and also allow the eraser to ignore Quantization although this code is going to change considerably with 2.0 so it could very well fall into the wontfix bucket until after a 2.0 release?

![image](https://cloud.githubusercontent.com/assets/6345473/6034530/85bc0daa-abf1-11e4-8991-1be031e12a16.png)

**Comment by Sti2nd** [comment]
> bezier curves really make this obsolete way of drawing dots obsolete so this isn't extremely high on the priority list

When you record automation you get those dots at the desired quantization value, so I wouldn't say it is obsolete.

**Comment by tresf** [comment]
> When you record automation you get those dots at the desired quantization value, so I wouldn't say it is obsolete.

:+1:

**Comment by zonkmachine** [comment]
> If the developer requires an mmpz, please contact me individually for this particular track.
> 
> -Tres

@tresf You don't happen to have this project still lying around?

**Comment by tresf** [comment]
@zonkmachine I could resurrect it from Google drive but I'm not entirely sure which track so it would require some 0.4.15 reinstallations which probably aren't worth the time.

Since this bug WA swritten we've

**Comment by zonkmachine** [comment]
> which track so it would require some 0.4.15 reinstallations which probably aren't worth the time.

No. Not worth it.
