### ISSUE TITLE
Monstro's osc 3 vol knob always uses percentages.

### ISSUE THREAD

**Issue by Sawuare** [LMMS/lmms#3911]
Monstro's osc 3 vol knob with the "Display volume as dBFS" setting enabled:
![capture20171024164622676](https://user-images.githubusercontent.com/25503477/31946683-23dbf6f0-b8db-11e7-9982-9d60fbe9d8fc.png)
![image](https://user-images.githubusercontent.com/25503477/31946846-966fe582-b8db-11e7-9af0-64c8a9b4eafc.png)

It uses percentages instead of levels in dBFS.

**Comment by zonkmachine** [comment]
The other volume knobs has line to set them explicitly as a volume knob.
[m_osc2VolKnob -> setVolumeKnob( true );](https://github.com/LMMS/lmms/blob/stable-1.2/plugins/monstro/Monstro.cpp#L1680)
Try adding a line like that for `m_osc3VolKnob`, may be all that's missing in there.

**Comment by Sawuare** [comment]
Tested you suggestion, it fixes the issue and works as expected, will open a PR soon.
Which branch should I target, `stable-1.2` or `master`?

**Comment by zonkmachine** [comment]
Bug fix, stable-1.2 would be fine.
