### ISSUE TITLE
lmms does not open an older project (mmpz) and gives no error messages

### ISSUE THREAD

**Issue by pheek** [LMMS/lmms#3913]
Hello

I recently created an lmms file (see here https://gress.ly/mozz-05.mmpz).
Opening it half a year later using lmms (1.1.3 Linux/x86/64, Qt 4.8.7, Gcc 6.2.1 20161215) it closes all dialogs immediately after opening them. 

No error message on the console (except the Notice: could not set real-time priority.), no crash, no error message in /var/log/syslog.

The application (lmms) stays open, but all windows within are closed.

I use linux lubuntu 17.10 (Kernel 4.13.0-16-generic).

Any Idea?
Have there been any major changes in lubuntu or in lmms in the past 6 months?

Thanks in advance

**Comment by zonkmachine** [comment]
The song is there but opens up with the windows closed so it appears blank. Click on the song editor, the button underneath 'Create new project' and it should appear again.

**Comment by zonkmachine** [comment]
I've seen this too. Projects opening with the windows closed. I believe the the window states are saved [here](https://github.com/LMMS/lmms/blob/9715da332b0c279739414712d4be9f0335147f3a/src/gui/MainWindow.cpp#L737:L763).

**Comment by zonkmachine** [comment]
The song window from the project above is clearly saved as not visible.
```<trackcontainer width="953" x="139" y="16" maximized="0" height="628" visible="0" type="song" minimized="0">```

**Comment by musikBear** [comment]
(?) the only thing is that the project is saved with **closed** song-editor -eg empty screen.
One click on SE-button, and all is normal
If the project is saved in this state, it loads in that state -Normally

Song-editor does not auto-open, when a project is opened **and that is a GOOD thing** !!!*
The reason its a GOOD thing, is that on inferior hw (mine amo) there is a clear difference between opening and populating a huge project, between having song-editor *open* and *closed*
Some projects wont even open, if song-editor IS open.
State of objects when saved, should NOT be overridden with some new 'smart' auto-open, that would be a disaster for us with low-end hw!

**Comment by GoAm** [comment]
_Admin can delete this post (or move it somewhere else if possible) if it doesn't fit here._

I've seen these kind of objections several times regarding low-end hardware.
With the risk of being shot, wouldn't the minimum requirements for LMMS change during time?
I mean, at some point you have to take a decision to change these requirements otherwise this project will slowly die since it has to support everything from single core 1GHz and 512Mb Ram up to quad-core with 8Gb (more or less standard now).

**Comment by zonkmachine** [comment]
^OT Here is our discord channel: https://discordapp.com/invite/3sc5su7
Maybe we need to update the requirements, but people really are using LMMS on low grade machines. Raspberry Pi for instance. </OT>

**Comment by zonkmachine** [comment]
> Song-editor does not auto-open, when a project is opened and that is a GOOD thing !!!*

The default is to open the project as it was saved. The user has saved it with the project open. I have experienced this too. I always save the projects with windows open.

**Comment by pheek** [comment]
Thanks you all, specially zonkmachine. I have not known, that the window state is saved too. I will try to save the songs in the future also with at least one window open :-)

**Comment by zonkmachine** [comment]
> So it is definitely not a bug, but a funny "feature".

I'm not fully convinced that this isn't a bug actually. I'll keep one eye open. 8)
