### ISSUE TITLE
Compiling LMMS with VST on 64bit Linux

### ISSUE THREAD

**Issue by dozawndd** [LMMS/lmms#3915]
With the new rc4 version it should be possible to get vst working as far as I can see on the update list for the version...

Fix VST plugin compilation in 64bit Ubuntu (#3593)

I have tried to compile lmms with vst, but it fails at 83% with the following error:
winegcc: File does not exist: /usr/lib/i386/wine/libwinecrt0.a

I am running 64 bit kubuntu 17 and I have tried both installing wine and lmms in numerous ways.
I have tried installing through kxstudio repo and compiling from source.
I can install lmms without vst, but would like to get vst working.

How should lmms and vst be compiled succesfully???

**Comment by zonkmachine** [comment]
Try: `sudo apt-get install build-dep lmms` to pull in the dependencies in one swipe. I'm not sure that this covers wine though. The packages I have on my machine (Linuxmint) are. `wine1.6 wine1.6-amd64 wine1.6-dev wine1.6-i386`. For compiling it's the package ending with `-dev` you need. Possibly all of the others too. You are on a newer version than I am so it's not going to be wine 1.6 .

**Comment by zonkmachine** [comment]
I'm closing this to get it out of the developer work flow but please continue the discussion here.

However. For future questions it's better to use the designated support channels:
Here is our Discord channel (forum/chat): https://discordapp.com/invite/3sc5su7
and here is our original phpBB based forum: https://lmms.io/forum/ with an excellent support.

**Comment by tresf** [comment]
I'd like to provide some more information as our documentation may be at fault here... 

First, we do miss some packages in our documentation.  They're only provided in the Troubleshooting section here: https://github.com/LMMS/lmms/wiki/dependencies-ubuntu#troubleshooting.  Someone installing on a fresh 14.04 or 16.04 environment please help us make this documentation better.

Second, what you're seeing a new [`FindWine.cmake`](https://github.com/LMMS/lmms/blob/stable-1.2/cmake/modules/FindWine.cmake#L27) doing exactly what it as designed to do, but our error messages may have changed as a result.   First, `FindWine.cmake` finds that you have a file matching the pattern `/usr/lib/lib64/wine/libwinecrt0.a.*`, next it assumes you have a 32-bit prefix located at `/usr/lib/i386/`, so this confirms what @zonkmachine is saying, spelled out in the wiki troubleshooting in sections `winegcc: g++ failed/c++config.h: No such file or directory`.

If we can confirm that the symptoms /errors from CMake have changed, we can update our Troubleshooting section.  We should also make our dependencies documentation assume two things... 

1. Assume everyone's on 64-bit now
1. Assume VSTs are wanted in all installations

We can always tell those compiling without VST support how to [explicitly turn it off](https://github.com/LMMS/lmms/blob/20ea945cee6030cb5872ff27c095976c64eaf631/CMakeLists.txt#L66).  From the sheer number of requests we receive around VST support, I think we owe the community some better steps. <3 (disclaimer, I wrote the current steps)

**Comment by dozawndd** [comment]
I managed to get it working, more or less without problems.
I have installed libwine, libwine:i386, libwine-dev, libwine-dev:i386, wine32:i386, wine64 and wine64-tools, after uninstalling wine several times.
I think the line that fixed my problem was from the troubleshooting link you provided.
I ran this:
sudo apt-get install libwine-dev libwine-dev:i386 gcc-multilib g++-multilib
I think libwine-dev:i386 was the key.
I have tried looking for it through synaptic package manager, but I think it was not there, but it worked in console. Does synaptic not show i386 extension for non installed packages?
Anyway.
I have tried to do this A LOT of times with previous versions, but always ended up disabling vst support, nice that it actually works now or maybe it has for previous versions and it is just me missing what is working now.
All in all thanks for tips and help.
(On a side note, I had enabled qt5 as well but my vst plugins appeared without window edges, but I went back to qt4 and not plugin work as good as they can I guess)
Thanks again

**Comment by tresf** [comment]
@dozawndd thanks for the feedback.  I've [updated our wiki](https://github.com/LMMS/lmms/wiki/Dependencies-Ubuntu/_compare/c13944597e017a082a26a1df7959c52c359780ca...1c903e5a7a746e3a451b83efb5fad31366924217) to include the i386 and wine packages by default.  I've moved wine into the same section to isolate it for those not wanting VST support.
