### ISSUE TITLE
(Windows) Crashes withour any reason

### ISSUE THREAD

**Issue by igggo123** [LMMS/lmms#3916]
(Windows) Crashes withour any reason

**Comment by zonkmachine** [comment]
> (Windows) Crashes withour any reason

Without any more info I can only advice you to try out a version of LMMS with portaudio disabled.
https://cdn.discordapp.com/attachments/242409373505159168/368799501491634176/lmms-1.2.0-rc4-no-portaudio-win64.exe

**Comment by zonkmachine** [comment]
Here is our Discord channel (forum/chat): https://discordapp.com/invite/3sc5su7
and here is our original phpBB based forum: https://lmms.io/forum/ with an excellent support.
