### ISSUE TITLE
Instrument presets saves MIDI settings

### ISSUE THREAD

**Issue by zonkmachine** [LMMS/lmms#3922]
Instruments are saved with MIDI settings as is the case with some of our factory presets. When previewing these sounds the project is set to modified. Saving instrument presets should not save any MIDI information.
Examples: Monstro - Growl, HorrorLead

 - [x] Fix factory presets. (#4207)
 - [x] Check factory projects. (#4207)
 - [ ] Don't save MIDI settings.

Related: [Presets remember the controller connections](https://github.com/LMMS/lmms/issues/2625)

**Comment by qnebra** [comment]
Maybe this section is preset? Taken from Monstro - Growl preset:

<midiport inputcontroller="0" inports="" fixedoutputvelocity="-1" inputchannel="0" outputcontroller="0" writable="0" outputchannel="1" fixedinputvelocity="-1" fixedoutputnote="-1" outputprogram="1" basevelocity="63" readable="1"/>

**Comment by PhysSong** [comment]
Should we fix factory files in `stable-1.2`, or `master`?

**Comment by zonkmachine** [comment]
I think `stable-1.2`

**Comment by tresf** [comment]
Yes, stable.  1.3.0 is slated to use the assets repo instead.

**Comment by PhysSong** [comment]
In the checklist, first two things can be fixed easily. I can create a pull request addressing them.

**Comment by zonkmachine** [comment]
> In the checklist, first two things can be fixed easily. I can create a pull request addressing them.

Yes. Fix the first two for 1.2 and the saving issue some other time.

**Comment by zonkmachine** [comment]
Possibly related to https://github.com/LMMS/lmms/issues/1644

**Comment by Rossmaxx** [comment]
How hard is it to get this done? I might handle this. Need some pointers to look at tho.

**Comment by Rossmaxx** [comment]
@PhysSong @zonkmachine some help needed.
