### ISSUE TITLE
Bit Invader wave length

### ISSUE THREAD

**Issue by Kubek0212** [LMMS/lmms#3933]
Greetings All,
I used LMMS quite a while, so it's time for my first (and for now- only) sugestion wich will help (I think).

I had a problem with Bit Invader wave.
Itself- wave has lenght for 4 up to 200.
When the leght is automatised (e.g.- 150 bit-long wave is getting cutted to 50 bit-long) program forgets about the cutted part.
(Which force You to create the wave from the very beginning).

The button, which "saves" the whole wave lenght (200) would be very usefull.

Was this topic touched in past?

**Comment by zonkmachine** [comment]
> Was this topic touched in past?

It sounds vaguely familiar. You could try one of the new 1.2 Beta versions as the Bit Invader is a bit different in this regard but I'm not sure if this currently is regarded as a bug or not.
https://lmms.io/download/#windows

**Comment by michaelgregorius** [comment]
I think this is related to #3797.

**Comment by Kubek0212** [comment]
Yes, indeed this is what I was thinking about.
I am sincerely sorry for making a duplicate.

**Comment by zonkmachine** [comment]
> I am sincerely sorry for making a duplicate.

No worries. :)
