### ISSUE TITLE
Automation pattern glitch

### ISSUE THREAD

**Issue by zonkmachine** [LMMS/lmms#3935]
Since the Anti-Aliasing fix of the Automation Editor (899e386df71bb0d88e0b6cd873348ec2b9bf9ad1)  there is a step left at the last automation point. The pattern is somehow off by one.

![automationpatternoff](https://user-images.githubusercontent.com/6368949/32386155-98eb65d8-c0c0-11e7-94f8-d6cc65080766.png)

**Comment by musikBear** [comment]
Great find!

**Comment by PhysSong** [comment]
Confirmed. I have a fix and am testing that. I'll open a PR if it works.
