### ISSUE TITLE
Can't build RemoteVstPlugin.cpp build error

### ISSUE THREAD

**Issue by coreybruce** [LMMS/lmms#3953]
```
/media/users/Storage/lmms/plugins/vst_base/RemoteVstPlugin.cpp:59:28: fatal error: wine/exception.h: No such file or directory
compilation terminated.
winegcc: g++ failed
plugins/vst_base/CMakeFiles/vstbase.dir/build.make:61: recipe for target 'plugins/RemoteVstPlugin' failed
make[2]: *** [plugins/RemoteVstPlugin] Error 2
CMakeFiles/Makefile2:8863: recipe for target 'plugins/vst_base/CMakeFiles/vstbase.dir/all' failed
make[1]: *** [plugins/vst_base/CMakeFiles/vstbase.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by tresf** [comment]
Please see the VST section of our dependencies.  https://github.com/LMMS/lmms/wiki/dependencies-ubuntu#vst

If you're not on Ubuntu, please try to find the equivalent package(s) for your distribution.

**Comment by coreybruce** [comment]
Just to let you know these packages on Ubuntu don't exist

corey@Corey-PC:/media/users/Storage/lmms$ sudo apt-get install wine-dev libwine-dev libwine-dev:i386 gcc-multilib g++-multilib
[sudo] password for corey: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package wine-dev is a virtual package provided by:
  wine-rt-dev 2:2.0.1-1~xenial1
  wine1.6-dev 1:1.6.2-0ubuntu14.2
You should explicitly select one to install.

E: Package 'wine-dev' has no installation candidate
E: Unable to locate package libwine-dev
E: Unable to locate package libwine-dev:i386

Bug still persists after checking all dependencies were installed.

**Comment by lukas-w** [comment]
@coreybruce Those packages do exist, maybe you should take a closer look to your error message:

> ```
> Package wine-dev is a virtual package provided by:
> wine-rt-dev 2:2.0.1-1~xenial1
> wine1.6-dev 1:1.6.2-0ubuntu14.2
> You should explicitly select one to install.
> ```

Apparently you set up some third party package repository (KXStudio PPA?) that makes 'wine-dev` ambiguous.

**Comment by coreybruce** [comment]
The only PPA I have to do with wine is WineHQ-staging

**Comment by tresf** [comment]
I see a reference to Xenial.  @coreybruce can you confirm that you're on Ubuntu 16.04?  We can quickly test our own procedures and offer recommendation.  If you'd like to troubleshoot interactively, [Discord](https://lmms.io/chat) #support channel is a good place as well, there are often a few devs hanging out there.

**Comment by coreybruce** [comment]
Yes I am on Ubuntu 16.04 LTS, thank you for letting me know and testing it out for me, builds in the past worked fine until now but no problem I'm sure we can resolve this!

**Comment by tresf** [comment]
@coreybruce thanks.  Which branch are you compiling?

**Comment by lukas-w** [comment]
@coreybruce WineHQ-staging doesn't contain a package called `wine-rt-dev`, but the KXStudio repos do. Are you sure you don't have the KXStudio repos enabled?

Anyway, judging from the error message, you should be able to resolve this by explicitly selecting the package to install. Try running `sudo apt-get install wine1.6-dev`.

**Comment by coreybruce** [comment]
Don't worry after installing wine-rt-dev it fixed the issue!

**Comment by tresf** [comment]
Thanks for the update.  As @lukas-w points out you must have added the KXStudios repository at some point, so this is not a typical scenario.  We intentionally leave our Ubuntu instructions vague to use virtual package names like `wine-dev` instead of `wine1.6-dev` as it works on more Ubuntu version and is easier to maintain from a documentation perspective, so we won't be making any changes to the wiki at this time. 

Closing as resolved.

**Comment by coreybruce** [comment]
Your right I have, forgot I did that woops!

also I am using the rc versions from this git repo
