### ISSUE TITLE
The unusual name of Aporggio6

### ISSUE THREAD

**Issue by ghost** [LMMS/lmms#3967]
As the title says the name of the sixth arpeggio isnt arpeggio but aporggio in the Zyn preset folder. 
This is super minor issue but it still is kinda weird.
This was found on lmms version 1.2.0 rc4.

**Comment by tresf** [comment]
Seems to be a problem with the plugin, not with our code.

https://sourceforge.net/p/zynaddsubfx/instruments/ci/master/tree/banks/Arpeggios/

Please file a bug upstream and once fixed, we'll do the same in our fork.

**Comment by zonkmachine** [comment]
Upstream report here: https://sourceforge.net/p/zynaddsubfx/bugs/166/

**Comment by zonkmachine** [comment]
Fixed upstream of upstream but the submodule submodule needs to be synced first.

**Comment by zonkmachine** [comment]
https://sourceforge.net/p/zynaddsubfx/instruments/ci/master/tree/banks/Arpeggios/
