### ISSUE TITLE
volume of a certain vst in lmms

### ISSUE THREAD

**Issue by killjoyrekt** [LMMS/lmms#3968]
Recently when i try to use the VSCO 2 community edition in lmms, the volume of the note played in the vst compared to the daw is different. The volume in the daw is very soft. Is there any solution to this?

thxx

btw another vst called nuclear by music weapons had the same issue

**Comment by Spekular** [comment]
I leave it to someone else to decide if this is a bug or not but either way
you can always add an amplifier (or five) in the effects tab to make it
louder. It won't change the volume w/ the initial settings, so you have to
open the controls and turn the volume up. You can also crank both the left
and right knobs up by the same amount to get more amplification out of one
amplifier effect.

Obviously be careful not to make it too loud!

**Comment by musikBear** [comment]
Have you checked if the base-velocity in the midi-tab, for 'some'(?) reason, is  low. afair default is 64

**Comment by zonkmachine** [comment]
> VSCO 2 community edition

http://vis.versilstudios.net/vsco-community.html
Is it the vst version from Bigcat you're referring to?

**Comment by killjoyrekt** [comment]
yeah, also, quite a few vsts have this problem, most of th time when theres a keyboard in the vst itself, the volume when played inside the vst has a different volume and velocity when played in the daw

**Comment by musikBear** [comment]
@killjoyrekt 
> quite a few vsts have this problem

We need names for those VSTs, we cant gues
also 
* did you check the base-velosity?
* is it the bigCat version?
Please answer direct questions

**Comment by killjoyrekt** [comment]
bitsonic keyzone classic
atmos piano
sonatina symphonic orchestra (vst rompler)

**Comment by killjoyrekt** [comment]
i checked th base velocity 
even if i change it it doesnt really make a difference

also yes its the bigcat version

**Comment by musikBear** [comment]
> base velocity -even if i change it it doesnt really make a difference

@killjoyrekt -You are **not** getting any sound difference if you put *base velocity* at 5 compared to *base velocity* at 127 ?
You get *same* loudness?

**Comment by tresf** [comment]
No reply in months from the OP.  Closing.  If someone wants to reproduce this and request a reopen, please do.
