### ISSUE TITLE
Does lmms need a 'cleanup' of various interfaces before the 1.0 relase

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#399]
perhaps lmms would benefit from having an interface 'cleanup' -eg removing those elements that does not have any function? That would be the ENV/LFO + filters on the zynAdsubFX , VST + LB interfaces 
The 'record' buttons in song-editor 
-Just to avoid confusion, and have a sleaker look-feel? I dont know if that would be an enourmous task, -then forgetaboudet :p -but i feel it would benefit the project?
Any thoughts?

**Comment by tresf** [comment]
Yeah, these were implemented.   Thanks!!
