### ISSUE TITLE
Automation Editor - Draw line not aligned

### ISSUE THREAD

**Issue by zonkmachine** [LMMS/lmms#3995]
![drawline](https://user-images.githubusercontent.com/6368949/33030066-9bf8f45e-ce1a-11e7-8353-c83a56957fd1.png)

Using the `<Shift>` modifier draws one point at the same level at the beginning and/or the end of the line.

**Comment by Umcaruje** [comment]
I think the <kbd>Shift</kbd> behaviour can be dropped tbh, we can do proper lines now in the automation, and it's from a time where you couldn't do that, so you had to reside to the shortcut.

**Comment by zonkmachine** [comment]
Right. I'm perfectly fine with removing this.

**Comment by Spekular** [comment]
It's still useful. For example if you set quantization to 2Xths and draw a
line, then Xths and draw another you can get a triangle wave type shape
very quickly.

**Comment by Sawuare** [comment]
This `Shift` mode is handy.

![image](https://user-images.githubusercontent.com/25503477/33035887-c19b4e14-ce3d-11e7-9e48-ec2b3dd40a66.png) ![image](https://user-images.githubusercontent.com/25503477/33036054-60729308-ce3e-11e7-96ad-4c00630a9146.png)

**Comment by PhysSong** [comment]
Confirmed. I just found another bug: 

1. Add a point.
2. Hold shift key and click a position which is slightly closer to the first point than the exact position of the point which will be inserted.
3. One point in the line will be missing.

**Comment by zonkmachine** [comment]
OK. It looks like a majority is for keeping it. Hacking...

**Comment by zonkmachine** [comment]
@PhysSong I'm pretty much done straightening out the line. I have seen disappearing points but I'm currently failing to reproduce it from your recipe above.

**Comment by PhysSong** [comment]
@zonkmachine Could you try edited steps and test what happens?

**Comment by zonkmachine** [comment]
![steps](https://user-images.githubusercontent.com/6368949/33049627-52bf73c0-ce61-11e7-965e-b2fe05c60ae4.png)

**Comment by PhysSong** [comment]
@zonkmachine Could you retry with significant difference in Y position difference?

**Comment by zonkmachine** [comment]
Yes. I'm testing now with all settings I can think of but don't see anything. Is this supposed to be reproducible every time?

```
$ ../target-stable-1.2/bin/lmms --version
LMMS 1.2.0-rc49.11
(Linux x86_64, Qt 4.8.6, GCC 4.8.5)
```

**Comment by zonkmachine** [comment]
@PhysSong Can you test #3997 and see if this fixes the the issue you saw?

**Comment by PhysSong** [comment]
Okay, I will.

**Comment by PhysSong** [comment]
I mean https://github.com/LMMS/lmms/pull/3997#issuecomment-346416449 there.

**Comment by zonkmachine** [comment]
> I mean #3997 (comment) here.

Sorry, I didn't get that. Do you mean that you see the issues I describe in that comment on stable-1.2 ?

**Comment by PhysSong** [comment]
Not really the same, but something very similar. The issue with the start/end point and quantization. I can make a demo if you want.

**Comment by zonkmachine** [comment]
Demo, yes please!

**Comment by PhysSong** [comment]
![autoline](https://user-images.githubusercontent.com/12591074/33259494-667f21f0-d3a0-11e7-9ea2-01cad025e763.png)

1. Click a point 1/24 bar right from the very beginning.
2. Click another point 1/24 bar left from the beginning of second bar while pressing `Shift`.

The points will look weird, both with and without #3995.

**Comment by zonkmachine** [comment]
> The points will look weird

Pic please! As before I don't see anything odd here.

**Comment by PhysSong** [comment]
Ah, the line itself isn't weird, but the position of end-points are.
