### ISSUE TITLE
Dependency perl-list-moreutils needed on Arch builds

### ISSUE THREAD

**Issue by michaelgregorius** [LMMS/lmms#4006]
I noticed that I have to install `perl-list-moreutils` and it's dependency `perl-exporter-tiny` to be able to build the SWH plugins on Arch.

Is this a permanent new dependency? If the answer is "yes" then the dependencies list for Arch needs to be updated: https://github.com/LMMS/lmms/wiki/Dependencies-Arch

**Comment by tresf** [comment]
Done, thanks.

**Comment by tresf** [comment]
Supporting documentation: https://github.com/LMMS/lmms/pull/3931
