### ISSUE TITLE
MIDI for MacOS

### ISSUE THREAD

**Issue by GingkathFox** [LMMS/lmms#4007]
Idk if this was added, but could we add support for MIDI on Mac?
I might be able to help a little(I use Windows *cri*)!

**Comment by PhysSong** [comment]
We already have MacOS MIDI support since 1.2.0-rc1. Could you please download our newest release?

**Comment by GingkathFox** [comment]
Oh, kk!

**Comment by tresf** [comment]
Duplicate of https://github.com/LMMS/lmms/issues/1153.
