### ISSUE TITLE
Exporting Timeline as a Video

### ISSUE THREAD

**Issue by gi0e5b06** [LMMS/lmms#4014]
First video ever created by LMMS!
![videoline_20171127](https://user-images.githubusercontent.com/30031949/33276587-41da5d92-d396-11e7-8edf-eb6bb4f2b75b.gif)
The video:
[videoline_20171127.zip](https://github.com/LMMS/lmms/files/1506600/videoline_20171127.zip)
Making video clips will be a lot eaiser using this as a reference.

**Comment by gi0e5b06** [comment]
And the code: https://github.com/gi0e5b06/lmms/commit/ba2902e56a7852839b0a52ca69a53f6b87ac3d82
I tried to create a M-JPEG and that worked but that was not practical (lack of frame rate) so instead, I call ffmepg as an external tool to create a MP4. All images are small and created in memory so it's fast (about 10% of the song time, most of the time being spent by ffmpeg for the compression).

**Comment by lukas-w** [comment]
I'm not sure what this issue proposes, but I'd say video creation is definitely out of scope for LMMS.
