### ISSUE TITLE
Implement channel templates

### ISSUE THREAD

**Issue by michaelgregorius** [LMMS/lmms#4023]
The implementation of channel templates was originally proposed in #4004 in [this comment](https://github.com/LMMS/lmms/issues/4004#issuecomment-346678387).
# Channel templates
The idea is to provide a way to quickly add channels which are preconfigured with certain settings and plugins.
## Creation of a channel template
If you want to create a channel template from scratch you
* Create an empty channel.
* Add all the effects and plugins that should go into the template to the new channel.
* Right click the channel and select "Save channel template...". This opens a dialog where you can choose a name for the template (that must not exist yet). If closed with "OK" the template will be stored in a template directory.
## Adding a new channel from a template
If you want to create a new channel you can do so by selecting the template to use from a menu. This menu is populated from the templates found in the template directory.
## Default channel templates
For even more convenience there should be an option to set a default channel template in the options. This default channel template would then be applied to all channel that are created by a simple "New channel" option. If no default template is set an empty channel is created.
## Optional: Applying channel templates to existing channels
Provide the option to apply channel templates to existing channels, either by removing all existing plugins from that channel or by adding the plugins from the channel template before or after the existing plugins.

**Comment by Sawuare** [comment]
Since the proposed channel template only saves the effects in the effects chain of a channel, and we have an effects chain in instrument plugins, I suggest we have `Effects Chain`s that are saveable/loadable in the mixer as well as in instrument plugins.

Poll:
👍 / 👎

**Comment by musikBear** [comment]
Does that 'need' a poll? It was obvious to me, that the savable chains would be valid in both preset-FX and mixer-FX
Or did i assume too much..

**Comment by tresf** [comment]
> we have Effects Chains that are saveable/loadable in the mixer as well as in instrument plugins.

They're already save-able and load-able, just not directly, you have to save an entire preset.  I agree, the effects stack needs to be consistent across all implementations.  The original description should be updated to reflect instrument effect stacks as well.

**Comment by michaelgregorius** [comment]
If there are certain properties of a channel that should also be saved as part of a channel template then we should differentiate between the channel data that's saved and the effects chain data that's saved. An example for such a channel property would be the default amplification of the new channel, i.e. we might want to store that each new channel is set to -6dB by default. Or as another example: REAPER allows to store several channels and their routings in a template. This way you can for example create a template for drums where different drum samples go to different channels to be processed differently. This would also be an example where you want to store the amplification of each channel in the template.

If we decide to also store channel properties then we need to define (or reuse) a format for effects channels which would then be part of the channel template together with the other channel settings. An instrument would only store its effects chain as the channel settings do not apply to it. A channel in the mixer on the other hand would store more information.

The differentiation between the two types of templates would also have to be reflected in the GUI of course.

**Comment by tresf** [comment]
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.
