### ISSUE TITLE
Strange Pixmap Behavior

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms#4024]
Using LMMS 1.2.0-RC4 on MacOS 10.12 is having some issues with the way pixmaps are drawn.  They seem to be related to the Equalizer plugin.

![ezgif-5-1273747bfe](https://user-images.githubusercontent.com/6345473/33406033-f78da5ba-d538-11e7-9318-c11f1ca7ae47.gif)

This problem disappears when using the `libeq.so` from 1.2.0-RC3.

**Comment by Sawuare** [comment]
Related: #3908.

**Comment by tresf** [comment]
@Sawuare it's an exact duplicate.  Marking as such, thanks.
