### ISSUE TITLE
Crashes during playing from piano roll.

### ISSUE THREAD

**Issue by rdrpenguin04** [LMMS/lmms#4028]
When playing from the piano roll, when the cursor is in an area with no music, the program crashes.

How to reproduce:
Create a 2+ measure tune.
Delete the synth you were using and add a new one.
Only add one measure to this.
Hit play, program crashes.

Program version: 1.1.3
OS: Windows 10

**Comment by PhysSong** [comment]
Can you reproduce this with latest beta(1.2.0-rc4)?

**Comment by musikBear** [comment]
No cant reproduce 
@rdrpenguin04 
Is This issue reproduceable with *ONLY* lmms presets, or are you using VSTs

**Comment by PhysSong** [comment]
@rdrpenguin04 Could you post a project file wich causes crashes?

**Comment by zonkmachine** [comment]
Closing out from lack of response.

> Program version: 1.1.3

@rdrpenguin04 Please reopen if you can recreate this issue on lmms-1.2.0
https://lmms.io/download/#windows
