### ISSUE TITLE
Toggle automatic uploads for PRs

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms#4035]
Steps to add a testable, downloadable build artifact for every PR against LMMS.

* [x] @PhysSong  to sync `stable-1.2` back into master to pull in any `.AppImage` improvements (e.g. #3958, #4026, d0194e6, f15acb8)
* [x] @Umcaruje /@tresf to communicate with power-users (e.g. @StakeoutPunch, @SecondFlight) how to fetch the binaries, possibly get a list of testers, post on Discord, etc.
* [x] ~~@lukas-w~~ @tresf transfer the following build types:
    * [x] win32
    * [x] win64
    * [x] mac10.11
    * [x] linux64

... and wishful thinking... 

Click here: https://travis-ci.org/LMMS/lmms/builds/312544160

Click (e.g.) the win32 job here:
![image](https://user-images.githubusercontent.com/6345473/33676281-5d47c5bc-da83-11e7-8a16-4bff122ea60c.png)

Click "Follow log"
![image](https://user-images.githubusercontent.com/6345473/33675999-80838472-da82-11e7-9091-7136726cb671.png)

Wait a minute for it to catch up and then find the `https://transfer.sh` portion... 
You'll have to un-click the scroll button to go back up.

![image](https://user-images.githubusercontent.com/6345473/33676176-f4a2e47e-da82-11e7-8eab-b674fd64fcd3.png)

![image](https://user-images.githubusercontent.com/6345473/33676080-bcc2c786-da82-11e7-9b4a-ceb9abd0833b.png)

~~* Provide a webhook to update the bug report with the latest transfer.sh URL.~~

~~I'm shamelessly assigning to @lukas-w as I think he's already started this but I may end up tackling this myself if he's too busy as well as @PhysSong for the branch syncing although that's already on the todo list.~~

**Comment by lukas-w** [comment]
> I'm shamelessly assigning to @lukas-w as I think he's already started this

Haven't started any work on this. You may be thinking of my CircleCI PR #3921, which adds automatic uploading of AppImages to CircleCI's servers.

**Comment by tresf** [comment]
> You may be thinking of my CircleCI PR #3921

Probably.  I'll tackle it then.  Work is happening on the `transfer` branch here: https://travis-ci.org/tresf/lmms/branches

**Comment by tresf** [comment]
@musikBear, here's a 32-bit bit build of the `master` branch from Travis-CI.

Click here: https://travis-ci.org/tresf/lmms/builds/312198087

Click the win32 job here:
![image](https://user-images.githubusercontent.com/6345473/33647209-c97327f2-da21-11e7-80a6-5ed22248621b.png)

Click "Follow log"
![image](https://user-images.githubusercontent.com/6345473/33647250-2b42bbfa-da22-11e7-9656-053cbbe9f593.png)

Wait a minute for it to catch up and then find the `https://transfer.sh` portion... 
You'll have to un-click the scroll button to go back up.
![image](https://user-images.githubusercontent.com/6345473/33647300-71066984-da22-11e7-83ed-1e69b3843403.png)

![image](https://user-images.githubusercontent.com/6345473/33647325-8b4aba98-da22-11e7-93f4-2f65164a12c9.png)
(Please pardon the poor versioning information, I have to iron that out still).

Others please feel free to test this out.  If you think it's warranted, we can write-up a wiki on it.

**Comment by tresf** [comment]
Bad news, `transfer.sh` has posted on Twitter that it's dying.  Switching to `file.io`.  https://twitter.com/dutchcoders/status/913835197237465089

**Comment by tresf** [comment]
`file.io` is working great.  Updated PR, updated instructions.  Testing appreciated.

**Comment by musikBear** [comment]
> hope you don't mind me using you as a guinea pig.
@tresf  not at all, i will come back with results

**Comment by tresf** [comment]
> Eg is everything 'secure' for malicious attacks?

Separate topic, really but I'll bite...

**Security of temporary uploads**

This depends on the security of the site we're uploading to.  If that site is compromised, the build would be as well.  Since Windows injections are the most common, the biggest attack surface would be the win64 executables as they represent about 80% of our downloads.

Some items that mitigate the attack surface: 1. The files are only stored for two weeks.  2. The files are **generally** only used by developers and testers. 3.  The files are created and hosted on a non-Windows machine, so the germination environment is non-native which reduces exposure.

Feel free to reach out to `transfer.sh` on your own to get some baseline security practices if it will make you feel better about it all.

**Functionality test**

Thanks.  The main purpose of this is to make sure you can locate and run an installer from a PR to aid with testing.  My thought process is that if you and several others know how to fetch the build artifacts, it will be a standard part of unit testing.  e.g. The functionality testing is not needed at this time, but thanks for the sanity check. 👍 

On a side note, I'm still struggling to find a permanent home for these artifacts.  I've switched back to `transfer.sh` now as they've brought their system back online but I've received no information via Twitter in regards to how long the service will be around for.

**Comment by tresf** [comment]
All builds are uploading, @musikBear was able to locate and run the build, so the last item is the branch sync.  I'm tempted to just merge #4041 as-is so we can start taking advantage of this now for new features like groove beats, track recording, etc  @PhysSong/@liushuyu thoughts?

**Comment by musikBear** [comment]
@tresf Thanks for clarification in respect to security 👍 
I can add that it only took seconds to build online, and the procedure was simple
(i btw have a copy of the whole log. Just let me know if i should upload it)

**Comment by PhysSong** [comment]
>  @PhysSong to sync `stable-1.2` back into master to pull in any `.AppImage` improvements (e.g. #3958, #4026, d0194e6, f15acb8)

@tresf I can't sync changes in `WeakJack` in #4026 because it is a submodule in `master`. Maybe need a PR against upstream?

**Comment by tresf** [comment]
@PhysSong done via https://github.com/x42/weakjack/pull/7.  I think you can technically reference the commit ID of my PR now although I always get mixed results leveraging a non-default branch.

**Comment by tresf** [comment]
@PhysSong x42/weakjack#7 has been merged.

**Comment by PhysSong** [comment]
@tresf Branch sync is done.

**Comment by tresf** [comment]
@PhysSong thanks!  Merged #4041.  All PRs against master will now be uploaded to transfer.sh for Windows, Mac and Linux. :)
