### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by trebmuh** [LMMS/lmms#4039]
I just saw that it's written LMMS_BULID_APPLE instead (I think) of LMMS_BUILD_APPLE in 2 occurrences here: https://github.com/LMMS/lmms/blob/dd4a73eb4bb31870ff4397539710b6d3f0bbf1c6/src/gui/MainWindow.cpp#L68

I don't know how this would impact building but I thought I could mention it here then the knowledgeable coding people can have a look.

HTH

**Comment by tresf** [comment]
Thanks, we'll take care of it!
