### ISSUE TITLE
Redirect notes to VSTs

### ISSUE THREAD

**Issue by NickAcPT** [LMMS/lmms#4042]
My suggestion is to add a feature where we can direct midi/notes to VSTs.
I don't have that many examples where this would benefit, but here they are:
- [Kerovee](https://www.kvraudio.com/product/kerovee-by-g200kg)
- [GSnap](http://www.gvst.co.uk/gsnap.htm)

**Comment by PhysSong** [comment]
Related: #3485. There are some differences between this and that. #3485 is about MIDI effects(pre-instrument, from MIDI to MIDI) whereas this is about sound effects which also gets MIDI input(post-instrument, from audio+MIDI to audio).

I think this is a duplicate of #1202, which is a part of #1472.

**Comment by NickAcPT** [comment]
@PhysSong You are totally right. Will close this issue because this is a duplicate.
