### ISSUE TITLE
Off-grid automation points are not dragable.

### ISSUE THREAD

**Issue by Sawuare** [LMMS/lmms#4049]
To reproduce:
1. Open the automation editor.
2. Change the quantization value to 1/16.
3. Draw an automation point on the second step.
![image](https://user-images.githubusercontent.com/25503477/33806536-ba2305bc-ddda-11e7-96d4-cef5c3a88426.png)
4. Change the quantization value to 1/8.
![image](https://user-images.githubusercontent.com/25503477/33806541-c737d034-ddda-11e7-96f8-3d4889b668c5.png)
5. Try to drag the automation point.

It's not dragable and dragging it will create a new automation point.

**Comment by tresf** [comment]
Reminds me of https://github.com/LMMS/lmms/issues/391

**Comment by PhysSong** [comment]
I'm working on this. However, I need to choose the behavior for off-grid offsets. Should we preserve it, or not?

**Comment by Spekular** [comment]
Makes sense to preserve the offsets to me, as the same logic from the song/piano editors mostly applies and it increases consistency. If group move of automation points were implemented in the future it would make even more sense to retain off-grid offsets when moving an automation point at a coarser Q value.

**Comment by SecondFlight** [comment]
Agreed with @Spekular:
>it increases consistency

Does holding down `alt` while dragging already allow you to offset automation points from the grid?

**Comment by PhysSong** [comment]
There are a lot of problems with off-grid automation points. To solve it, I need to rewrite the logic for dragging automation points.
