### ISSUE TITLE
Lmms 1.2 crash

### ISSUE THREAD

**Issue by Videowelder** [LMMS/lmms#4053]
I have a track with the Mallets plug in running on solo and every time I try to add FreeBoy on it, the program freezes up and never recovers. When I try reopening and doing the same again, the same thing happens. When I remove the solo, same thing. Same thing for other instruments that I try putting in.

**Comment by Spekular** [comment]
If this happens no matter what instrument you try to add, I don't think the
title should reference FreeBoy.

Do you have other projects that work normally? That would indicate that
this specific project file is bugged, in which case I think you should
upload a copy of the project somewhere so a developer can take a look at it.

**Comment by zonkmachine** [comment]
@Videowelder As already have been said, please upload a project file so we can look at the issue. You need to zip it in order to attach it to a github post. Also, try and remove what isn't part of the bug so you end up with a minimal project that still breaks. Thanks!

**Comment by Videowelder** [comment]
I'll try to get that done.

**Comment by zonkmachine** [comment]
Also:
Which OS are you on?
What version of lmms? (rc number)

**Comment by BaraMGB** [comment]
I close this out because of no reaction from the opener in 3 months. @Videowelder feel free to answer in this issue anyway.
