### ISSUE TITLE
Ability to disable ENABLE_ASSERTS for rpmalloc in Debug builds

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms#4055]
From @DomClark:

> I'm trying to test a fix for the VST problem mentioned in `#support` recently, but I keep getting regular assertion failures from `rpmalloc` during playback. Is there any way to compile using the debug configuration but with these disabled?
Here's the message if it's useful to anyone:
>
> ![image](https://user-images.githubusercontent.com/6345473/34065830-5d27f3ba-e1d4-11e7-8a97-e3a1e2923be8.png)
> [...] noticed `CMakeLists.txt` has `-DENABLE_ASSERTS=1` for `rpmalloc` in debug configuration

**Comment by lukas-w** [comment]
That assertion failing means that rpmalloc hasn't been initialized on the thread using it, which is a serious problem. With assertions disabled, it'll likely result in segfault soon after. @DomClark do you still experience this?

**Comment by PhysSong** [comment]
rpmalloc have been updated a lot since we integrated it at the first time. @DomClark does using newer version of it fixes the issue?

**Comment by DomClark** [comment]
I turned this off in CMakeLists a while ago, but I've tried enabling it again and I haven't had any problems yet, so given how often this used to appear I'd say it's fixed.

**Comment by lukas-w** [comment]
Reproduced on `master`, but I guess `stable-1.2` is affected too:

1. Open `demos/DirtyLove.mmpz`
2. Export Tracks (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>E</kbd>)
3. Choose an empty directory to export to
4. Press "Start"
5. The assertion will fail a the end of the render

Or render any project normally and press "Cancel".

Backtrace:

```
1  raise                                                                  0x7ffff3612860 
2  abort                                                                  0x7ffff3613ec9 
3  __assert_fail_base                                                     0x7ffff360b0bc 
4  __assert_fail                                                          0x7ffff360b133 
5  _memory_deallocate_to_heap                    rpmalloc.c          1031 0x5555558ea122 
6  _memory_deallocate                            rpmalloc.c          1198 0x5555558e9569 
7  rpfree                                        rpmalloc.c          1666 0x5555558e94e5 
8  MemoryManager::free                           MemoryManager.cpp   76   0x5555557222b0 
9  NotePlayHandle::BaseDetuning::operator delete NotePlayHandle.h    270  0x555555734495 
10 NotePlayHandle::~NotePlayHandle               NotePlayHandle.cpp  137  0x55555573285d 
11 NotePlayHandleManager::release                NotePlayHandle.cpp  599  0x555555734345 
12 Mixer::renderNextBuffer                       Mixer.cpp           403  0x5555557260a6 
13 Mixer::nextBuffer                             Mixer.h             300  0x555555728d68 
14 ProjectRenderer::run                          ProjectRenderer.cpp 186  0x555555749a81 
15 ??                                                                     0x7ffff3fe2acd 
16 start_thread                                                           0x7ffff7bc108c 
17 clone                                                                  0x7ffff36d3e7f 
```

**Comment by PhysSong** [comment]
Reproduced too. I've tested with the latest revision of `rpmalloc` and it seems to fix the issue. @lukas-w Could you double-check this result?

**Comment by lukas-w** [comment]
@PhysSong Confirmed, 1.3.0 fixes it.
