### ISSUE TITLE
Starter problem

### ISSUE THREAD

**Issue by Cookisstador** [LMMS/lmms#4057]
When I restart a project he stop at 29%. I think it's a Vst problem but I can't do anything.

Please help me?

**Comment by musikBear** [comment]
@Cookisstador Yes most likely a flawed VST
Read:
https://lmms.io/wiki/index.php?title=Working_with_VSTs#VST_related_problems

**Comment by Spekular** [comment]
What version are you on? RC4 includes several VST related fixes.

**Comment by Cookisstador** [comment]
Version 1.1.3

**Comment by Cookisstador** [comment]
ok It worked : I uninstall lmms, restart my computer and delete all file (lmms and wrong plug in).

Thank you very much ! You saved my life ;)

**Comment by musikBear** [comment]
..Omg **why** uninstall 
Guide says nothing about that ...*sigh*
