### ISSUE TITLE
The first note that's played on the piano roll doesn't sound full.

### ISSUE THREAD

**Issue by DevSynth** [LMMS/lmms#4066]
When I play a note (which comes first) on the piano roll, I don't hear it fully and this applies to the Beat and Bassline editor

**Comment by zonkmachine** [comment]
Duplicate of https://github.com/LMMS/lmms/issues/2074 ?

**Comment by zonkmachine** [comment]
> I don't hear it fully

It doesn't play its full length or it's playing at low volume?
Which version of lmms?

**Comment by tresf** [comment]
No reply in months, closing.
