### ISSUE TITLE
[AppImage] Move lmms wrapper script into AppRun

### ISSUE THREAD

**Issue by flynn16** [LMMS/lmms#4069]
In the AppImage building process, there is originally a wrapper shell script named `lmms`, used to start the real LMMS executable `lmms.real`. This wrapper script is unused in the RC5 AppImage build. Instead, the `AppRun` script is used directly to start the LMMS executable. Code responsible for setting some environment variables, is not present in the `AppRun` script, which leads to issues like the GUI not scaling properly.

```bash
user@user-pc:~$ ps -aux
user      7579  0.0  0.0  15304  3020 pts/1    S+   14:17   0:00 bash /tmp/.mount_lmms-1PHiOKW/AppRun
user      7582  0.3  0.0  22340  2724 ?        Ssl  14:17   0:00 ./lmms-1.2.0-rc5-linux-x86_64.AppImage
user      7593 41.8  2.7 2023764 220588 pts/1  Sl+  14:17   1:10 /tmp/.mount_lmms-1PHiOKW/usr/bin/lmms.real

user@user-pc:~$ cat /tmp/.mount_lmms-1PHiOKW/AppRun
#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
if which carla > /dev/null 2>&1; then
   CARLAPATH="/usr/bin/carla"
   CARLAPREFIX="${CARLAPATH%/bin*}"
   echo "Carla appears to be installed on this system at $CARLAPREFIX/lib[64]/carla so we'll use it."
   export LD_LIBRARY_PATH=$CARLAPREFIX/lib/carla:$CARLAPREFIX/lib64/carla:$LD_LIBRARY_PATH
else
   echo "Carla does not appear to be installed.  That's OK, please ignore any related library errors."
fi
export LD_LIBRARY_PATH=$DIR/usr/lib/:$DIR/usr/lib/lmms:$LD_LIBRARY_PATH
# Prevent segfault on VirualBox
if lsmod |grep vboxguest > /dev/null 2>&1; then
   echo "VirtualBox detected.  Forcing libgl software rendering."
   export LIBGL_ALWAYS_SOFTWARE=1;
fi
if ldconfig -p | grep libjack.so.0 > /dev/null 2>&1; then
   echo "Jack appears to be installed on this system, so we'll use it."
else
   echo "Jack does not appear to be installed.  That's OK, we'll use a dummy version instead."
   export LD_LIBRARY_PATH=$DIR/usr/lib/lmms/optional:$LD_LIBRARY_PATH
fi
QT_X11_NO_NATIVE_MENUBAR=1 $DIR/usr/bin/lmms.real "$@"

user@user-pc:~$ env QT_AUTO_SCREEN_SCALE_FACTOR=1 ./lmms-1.2.0-rc5-linux-x86_64.AppImage
# Scales perfectly
```

**Comment by tresf** [comment]
What makes you think this script is not being executed?

**Comment by flynn16** [comment]
May be related
https://github.com/LMMS/lmms/commit/8bc9e9d9b4785c47a2c809bdc7de907f11381c04#commitcomment-25979076

HiDPI scaling is intentionally unset due to, Qt issues?

> We'll turn off QT_AUTO_SCREEN_SCALE_FACTOR then for now. People can
always flag it back on manually. I'll add this to the Carla PR and upload a
new AppImage.

This issue can be closed.

On Saturday, December 23, 2017, Tres Finocchiaro <notifications@github.com>
wrote:
> What makes you think this script is not being executed?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci4.googleusercontent.com/proxy/48ZI7xzDvO48oZTpN9WpCGQ2nD3AclROMa98aLyNYgCdOIzcKQ5nauIOKj5iW-7DUfIwcgIjHPQG3-ToNdTzia2bTm91lBnlYlh0i3Mhl4W1EbKaWizvpNzym7BS_1wb6arouq70XaZWighN3mby6iCR9I7OtA=s0-d-e1-ft#https://github.com/notifications/beacon/AVcBmUcf8feX9mUKPsLsx1o2ezmSMuShks5tDYRSgaJpZM4RLxy1.gif
>

-- 
Yifeng Liu @ University of Washington

Trying to report a bug?
GnuPG Key: rsa4096/07E65218F46FDDDF
Key Fingerprint: 8F90 D47D BCF9 E695 BA48  E127 07E6 5218 F46F DDDF
Binary .gpg file SHA-256: A29072DA 70B88417 6025D5EE DA9D0506 5CB829B6
33735D84 75C087AF 41AEC3DA

**Comment by tresf** [comment]
@flynn16 yes, we had to turn it off.  You should be able to turn it back on with `QT_AUTO_SCREEN_SCALE_FACTOR=1 ./lmms-1.2.0-rc5-linux-x86_64.AppImage`. If that doesn't work, you can export it in a separate variable.  When this behavior becomes more reliable in Qt, we'll happily turn it back on.

**Comment by tresf** [comment]
FYI, @flynn16, it appears`linuxdeployqt` will eventually be succeeded by `linuxdeploy`, which allows a custom `AppRun` to be specified.

I think this is the best approach long-term.

Reference: https://github.com/probonopd/linuxdeployqt/issues/289#issuecomment-410827126

For the short-term we will continue to use `linuxdeployqt` with the `lmms.real` workaround.
