### ISSUE TITLE
Sample track bug

### ISSUE THREAD

**Issue by Elias-Developpement** [LMMS/lmms#4072]
This is the process i use to get this bug : 
- I've open an tack on a sample track
- I was playing the global song
- During the global song, i have deleted the following sample track
- Then the soft crash

**Comment by teeberg** [comment]
I can't seem to reproduce this on latest master and mac os. Which LMMS version are you using, and on which system?

**Comment by musikBear** [comment]
@Elias-Developpement 
please post your:
* OS (+service-pack-version)
* lmms version
* hardware specification (ram & soundcard is the most important)
* Latency setting
* lmms instrument involved
* lmms preset (if a factory preset is used)
* a screenshots of error-state  -if any oddness appear
* a demo mmp as *.txt -You can attach directly on your post!

**Comment by lukas-w** [comment]
@musikBear Almost all of these points are irrelevant.

**Comment by musikBear** [comment]
@lukas-w  -for reproducing? I disagree. The more info about the crash, the merrier 🎄 Ooops.. better

**Comment by tresf** [comment]
@musikBear, please see below why @lukas-w is right. 

> please post your:
> * OS (+service-pack-version) ✅ **OS is often important.  Service pack is not**
> * lmms version ✅ **important**
> * ~~hardware specification (ram & soundcard is the most important)~~ ⛔️  **No**
> * ~~Latency setting~~ ⛔️ **No**
> * ~~lmms instrument involved~~ ⛔️ **It's the sample track, silly**
> * ~~lmms preset (if a factory preset is used)~~ ⛔️ **It's the sample track, silly**
> * ~~a screenshots of error-state  -if any oddness appear~~ ⛔️ **Nope.  It's a hard crash.**
> * ~~a demo mmp as *.txt -You can attach directly on your post!~~ ⛔️ **Good info, but steps to reproduce were offered, this is superfluous**

**Comment by zonkmachine** [comment]
> This is the process i use to get this bug :
> 
>     I've open an tack on a sample track
>     I was playing the global song
>     During the global song, i have deleted the following sample track
>     Then the soft crash

This sound like what you would get on lmms-1.1.3 with a file larger than 100MB. The warning would be issued to the terminal and missed if you didn't start lmms from the command line.

@Elias-Developpement Was this sample over 100MB in size?
What version of lmms are you using?

**Comment by tresf** [comment]
No reply in months, no steps to reproduce. Closing.
