### ISSUE TITLE
Extend range of supported notes in piano roll

### ISSUE THREAD

**Issue by teeberg** [LMMS/lmms#4073]
Reported in Discord: https://discordapp.com/channels/203559236729438208/332258319228207114?jump=395583597127532544

> I'm looking to create a lightshow on a launchpad and some of the lights can't be lit due to the piano roll not going high enough to have a note corrosponding to that light.

**Comment by zonkmachine** [comment]
I think the range is moderated [here](https://github.com/LMMS/lmms/blob/a3d72def4dcc1af74a79142268c71d9d794c24fa/src/core/Note.cpp#L114).

```cpp
void Note::setKey( const int key )
{
	const int k = qBound( 0, key, NumKeys - 1 );
	m_key = k;
}
```

**Comment by DeRobyJ** [comment]
The pianoroll has every possible note it can get from midi input...
You know, a midi note is described by 7 bits, so it can only go from 0 to 127...

What note number should the light get? How is it done by other software? Perhaps custom control change messages trigger by a "note"?

**Comment by zonkmachine** [comment]
> You know, a midi note is described by 7 bits, so it can only go from 0 to 127...

Yes, but not in `Note::Note()` or `Note::setKey()` where qBound is used to limit the register.

Example:
[const int NumKeys = NumOctaves * KeysPerOctave;](https://github.com/LMMS/lmms/blob/fbfcb43aeb31595433e72cd960d8b807f1ba85ea/include/Note.h#L74)

NumOctaves = 9
KeysPerOctave = 12

`Note::setKey()` max value is NumKeys - 1 which is ( ( 9 * 12 ) - 1 ) = 107.
The top 20 MIDI keys are set to 107. `Note::Note` is one higher so there you get 108.

**Comment by musikBear** [comment]
Looking for 'doables', but isent this one misunderstood?
In respect to audible notes, lmms is doing *fine*.
This very specific request is much better addressed with a  new *type* of track -we could name it *MIDICtrTCO* a track where *events* are inserted as points, and where each point has a midi-output-value.
Infact -an automation-track, but only with points.
Like: 
![image](https://user-images.githubusercontent.com/6662066/82148171-f7c75f00-9852-11ea-85f0-0b5e8a24e2cb.png)

But how many users has this need? Is this usecase general enough to spend hours of implementation for?

**Comment by Spekular** [comment]
@he29-net, do you know if this is still relevant after #5868? I would assume it's fixed now, but don't want to close without knowing for sure.

**Comment by he29-net** [comment]
Yes, I believe this issue should be resolved in the recent alpha release, all 128 MIDI keys are now available.
