### ISSUE TITLE
Enable stamping scales in the Piano Roll editor.

### ISSUE THREAD

**Issue by Sawuare** [LMMS/lmms#4079]
Just like how stamping chords is enabled.

This functionality will require replacing the current scales and chords combo boxes with a **Stamp** combo box which has 2 menus: **Scales** and **Chords**, so it will not allow having a scale and a chord selected simultaneously.

Menus support should be added to [ComboBox](https://github.com/LMMS/lmms/blob/master/src/gui/widgets/ComboBox.cpp) in order to implement this functionality.

**Comment by Umcaruje** [comment]
I don't understand, marking scales is already possible in the piano roll. What is stamping?

**Comment by Sawuare** [comment]
Stamping is that, when you have a chord selected and you click on the Piano Roll edit area, instead of creating a single note, a chord is created (stamped). The suggestion here is to enable the same functionality for scales.

**Comment by Sawuare** [comment]
The use-cases are the same as the ones for chord stamping. And for consistency.

**Comment by musikBear** [comment]
@Sawuare Cant understand why it would be *general* useable, to insert all notes in a scale in playable form. The exception would be music-teachers -they could perhaps save a few secd in class, but then the notes need to be distributed over time, but imo a very limited usability

**Comment by milkmiruku** [comment]
I think it would be handy to prime an arpeggiator or filter.

**Comment by tresf** [comment]
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.
