### ISSUE TITLE
LMMS won't export my sample-layered kick correctly.

### ISSUE THREAD

**Issue by EtornaZ** [LMMS/lmms#4081]
Sample project: http://lmms.io:8008/lsp/?action=show&file=12271
I cannot export this kick at the very beginning of the track because the two clicks will not play at all when I do so. I tested this by muting the other 3 channels and only playing the two clicks, and as a result the .wav file was empty, no sounds at all. 
However, if I move the kick forward a fourth note ahead, it will export correctly and I can use the Audio File Processor to make the kick play sooner.
If I find anything else out that is helpful, I will post it here.

**Comment by PhysSong** [comment]
I found that turning off the Calf Limiter(or replacing with other plug-in) lets clicks be exported. And I also found that Calf Limiter silences some samples from the beginning.
So I guess this is an issue with Calf Limiter. I'll try to figure out if this is a bug with LMMS or Calf plug-in.

**Comment by dullmachine** [comment]
When I layer kicks, I record them via Audacity and export them from there. That way if I use Calf Limiter, I won't have to deal with them being exported through LMMS.

**Comment by EtornaZ** [comment]
@dullmachine I'll do that in the future, thanks for the tip.

**Comment by DouglasDGI** [comment]
Should this issue still be open?  No response in over a year.

**Comment by zonkmachine** [comment]
It looks like the sample project has been deleted from the sharing platform so there is nothing to work with. It sounds like the Calf Limiter and is thus an up-stream issue. Please reopen if there is any new information or if the file is found and can be re-uploaded. (here zipped!)
