### ISSUE TITLE
B&B editor does not show notes in quantizations smaller than the default

### ISSUE THREAD

**Issue by StakeoutPunch** [LMMS/lmms#4086]
**Verson:** !.2RC5 64bit
**OS:** Windows 10
**Issue:**
The B&B editor does not show notes with a smaller quanitization than the default 1/16.
![image](https://user-images.githubusercontent.com/6579031/34458091-ddb455b6-ed8a-11e7-8c43-a2cc654e3ee0.png)
Upon "Open in Piano Roll":
![image](https://user-images.githubusercontent.com/6579031/34458094-f660f524-ed8a-11e7-9161-75ad6de4cefc.png)

**Comment by StakeoutPunch** [comment]
Went back and tried this on some older versions (1.0.3, 1.1.0, 1.2RC2, RC3, and RC4).
Results:
![image](https://user-images.githubusercontent.com/6579031/34458825-d7a6c99a-eda5-11e7-8ff6-170014135a34.png)

**Comment by zonkmachine** [comment]
You're comparing beat notes (comment 1) with ordinary notes (comment 2).
The issue is discussed previously here: https://github.com/LMMS/lmms/issues/1681#issuecomment-71250559

**Comment by StakeoutPunch** [comment]
Good catch. Closing as duplicate of #1681.
