### ISSUE TITLE
Kontakt is buggy in LMMS (Explanation in Description)

### ISSUE THREAD

**Issue by EtornaZ** [LMMS/lmms#4087]
When I open LMMS (latest beta version, RC5,) I can have the Kontakt player running in order to use my sound pack, Lunaris. However, the problem is when I reopen LMMS. Kontakt will load up Lunaris, but all of the samples are turned off, and sometimes (randomly) Kontakt will open with only a small section of the VST UI, like so. 

![image](https://user-images.githubusercontent.com/33297131/34463609-37ca0c68-ee2f-11e7-8015-4574fabb7cae.png)

This bug can happen upon reopening the project or loading the VST into LMMS. It's completely random in this case also.
Some addition information is that Lunaris can run on 4 GB of RAM at the minimum. My computer only has 4 GB of RAM, so it may be related to that.

**Comment by lukas-w** [comment]
@EtornaZ Did it work with LMMS 1.1.3? Can you change the "embed method" in the settings, restart LMMS, then try again and report with your results?

**Comment by Spekular** [comment]
Closing and consolidating into #5433

**Comment by hibobmaster** [comment]
Kontakt will be opened with a small part of UI even adjust the scale of the VeSTige.
Version: 1.22 stable and 1.3.0-alpha.1
![image](https://user-images.githubusercontent.com/32976627/102064834-c50a3700-3e32-11eb-96fe-ec8df0f770dc.png)

**Comment by musikBear** [comment]
We can add:
Using the wrench subpage for _automation - dial-array_, only open an array with _numbered_ dials, and non of them seams to actually connect to anything.
(An issue that also is true for ZynAddSubFX-VST2-version)
