### ISSUE TITLE
i found a bug in lmms and i think i found a way to fix it 

### ISSUE THREAD

**Issue by emptyusernameempty** [LMMS/lmms#4092]
if you have the arpeggio on 50 ms or lower with the AM pitchshifter and the equalizer all turned on then the equalizer tends to not work correctly. when you open the project with one wave sound with all those programs turned on then this error comes and makes you only hear sound in one ear (the right one in my experience) . the detune mode might be one other reason this habens because when it goes from one note with detune and to another without it (with arpeggio,am,eq) then your more likely to end up in the issue. the fix for all of this im not sure but i think if you make the equalizer open twise and make them both have the same equalization then delete the first one then the issue might be solved but im not a programer so im not sure how all this works but i think this might solve it. i hope you find some way to fix this because it will save me alot of time. by the way if you want to know all about my PC it has Intel i7 3770 and 25 GB ram with windows 7. ps. Scribe Ex (-:

**Comment by Sawuare** [comment]
> if you have the arpeggio on 50 ms or lower with the AM pitchshifter and the equalizer all turned on then the equalizer tends to not work correctly.

I did this and the equalizer worked correctly and I did not face this issue.
@emptyusernameempty Please post an instrument preset that has this issue.

**Comment by emptyusernameempty** [comment]
Hey I found out it was a older issue a few days ago, it has been fixed. :-)
