### ISSUE TITLE
Enhancement: Ability to have both curved and straight lines in Automation Editor

### ISSUE THREAD

**Issue by EtornaZ** [LMMS/lmms#4097]
The Automation Editor cannot currently support both straight and curved lines in the same automation. This can be worked around by either making two automation boxes and lining them up side by side in the Song-Editor, or use the 1/192 note setting so that the value is almost straight up, but not all the way. 
It would be more convenient if we could have both of these at the same time in the Automation editor. This feature would be useful for pitch values, panning values, etc.

**Comment by StakeoutPunch** [comment]
FL handles this by using what they call tension. An automation curve is straight until you grab a handle in the middle of the line and add curvature in. Is this what you're asking for?
![image](https://user-images.githubusercontent.com/6579031/34645448-3670ae56-f313-11e7-9460-81bbbe353df4.png)

**Comment by EtornaZ** [comment]
Yes, it is.

**Comment by lukas-w** [comment]
I think this would be covered by #2381, which is implemented by #2466. I don't know about the state of that PR though.

**Comment by fyrebreak** [comment]
Thanks for mentioning this, EtornaZ! The inability to create dropshelves in LMMS is certainly frustrating XD
Also thanks Devs for paying attention to this ;)

**Comment by tresf** [comment]
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.
