### ISSUE TITLE
Fix Drum Pro VST

### ISSUE THREAD

**Issue by RichardJECooke** [LMMS/lmms#4102]
I installed [Drum Pro VST](https://www.studiolinked.com/drum-pro/) with Wine and tried to open it in LMMS with Vestige.

Everything 64 bit.

Got the error shown below.

![screenshot from 2018-01-09 09-22-41](https://user-images.githubusercontent.com/5468805/34695479-b7bf8aa4-f516-11e7-9515-2de192337736.png)

**Comment by Umcaruje** [comment]
64 bit VST's are not currently supported on Linux.

**Comment by tresf** [comment]
The 32-bit doesn't work either.  Seems to be incompatible with Wine.  Can someone test on Windows?  This may not be our bug.

Backtrace: https://gist.github.com/tresf/f96d81872ed8a3d0bab4e972549cd980

**Comment by DomClark** [comment]
Cannot reproduce on Windows 10 64-bit, LMMS 1.2.0-RC5. Both the 64- and 32-bit versions appear to function correctly.

**Comment by RichardJECooke** [comment]
Oh, ok, I installed the 32 bit version instead and it plays correctly.

But both it and Helm (installed with PlayOnLinux) flash the GUI when first loaded in Vestige, but then when you try work with it the GUI it becomes blank, see screenshot below. (The default preset sound still sounds, just no visuals so you can't alter the sound)

Is this another known bug?

![screenshot from 2018-01-09 11-49-41](https://user-images.githubusercontent.com/5468805/34699830-47525962-f52b-11e7-90af-5c5a0b4b277e.png)

**Comment by RichardJECooke** [comment]
Both plugins work in Reaper using PlayOnLinux, I just gave that a try.

Never mind, I can use that instead, thanks.

**Comment by tresf** [comment]
> Never mind, I can use that instead, thanks.

1.2.0 is the next stable version and bugs should be reported against the beta, available from our downloads page.  https://lmms.io/download

**Comment by zonkmachine** [comment]
> 64 bit VST's are not currently supported on Linux.


> Both the 64- and 32-bit versions appear to function correctly.

Is this a case of needing better documentation and/or should we detect 64-bit and issue warning?

**Comment by tresf** [comment]
> Is this a case of needing better documentation and/or should we detect 64-bit and issue warning?

On Linux, yes, we should detect and warn if it's technically possible.  I'm also not sure why we don't support 64-bit.  Wine can run 64-bit binaries now.

**Comment by zonkmachine** [comment]
> On Linux, yes, we should detect and warn if it's technically possible. I'm also not sure why we don't support 64-bit. Wine can run 64-bit binaries now.

Open a separate issue for this then?

**Comment by tresf** [comment]
Probably a good idea.
