### ISSUE TITLE
64 bit VST on Linux/Wine

### ISSUE THREAD

**Issue by zonkmachine** [LMMS/lmms#4103]
Wine supports 64-bit since wine-1.2 but it doesn't seem to be working under linux/wine/lmms.
https://github.com/LMMS/lmms/issues/4102, https://lmms.io/forum/viewtopic.php?f=7&t=26647#p51235

- [ ] Assess the status/quality of 64-bit VST on Linux/Wine
- [ ] If possible, activate 64-bit VST on Linux/Wine
- [ ] Warn if needed/possible when running 64-bit VST on Linux/Wine
- [ ] Update documentation

---

Wine 3.0 is in the works and [rc5 was recently released](https://www.winehq.org/news/2018010501).
https://www.winehq.org/

**Comment by lukas-w** [comment]
I did some work to make building 64-bit `RemoteVstPlugin` work on Linux in the `msvc/vst` branch, but it fails loading VSTs with the message
```
RemotePlugin::DebugMessage: mainEntry procedure returned NULL
```

**Comment by lukas-w** [comment]
Fixed the error via 631a3dbcfb37f59541cc4ebab4659728fb8aeae8. 64bit VSTs load perfectly now when hard-coding LMMS to always use the 64-bit version of `RemoteVstPlugin`.

Unfortunately, there's still something going wrong with the trial-and-error approach we're using for starting the right version:

https://github.com/LMMS/lmms/blob/631a3dbcfb37f59541cc4ebab4659728fb8aeae8/plugins/vst_base/VstPlugin.cpp#L100-L109

The `IdVstBadDllFormat` message isn't always received for some reason and even when it is, starting `RemoteVstPlugin32` after `RemoteVstPlugin64` has already been started makes LMMS hang indefinitely.

**Comment by tresf** [comment]
@lukas-w if we do a quick file read on the DLL, we should be able to tell if it's 64-bit or not without the trial-and-error approach.  <https://stackoverflow.com/a/35418180/3196753>.

**Comment by lukas-w** [comment]
@tresf Thanks for sharing. That would work around the issue and I think we should implement it, but I suspect some deeper IPC bug causing this that may resurface, so I think this is worth investigating first.

**Comment by Spekular** [comment]
Closing and consolidating into #5433
