### ISSUE TITLE
Add 'Power' in the Chord-table

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#4106]
Enhancement
Add **power-chord** as an option in the  *Chord-selection-table*

**Comment by DomClark** [comment]
Is this not the same thing as the "5" chord already present?

**Comment by musikBear** [comment]
@DomClark  loL it is i just dont see that single '5' at all - should it be *named* 'Power'? That would make it stand out and distinctively show, that it is different from any type of 'add-note-chord'

**Comment by zonkmachine** [comment]
> it is i just dont see that single '5' at all

To the [right/bottom](
https://github.com/LMMS/lmms/blob/46512fdf19f42150d2728feb439b1c8441ce93dd/src/core/InstrumentFunctions.cpp#L137). It was added rather recently. I guess we could stick 'power' in there but I think it would fit better in as a tutorial. Knowing what a 'fifth' is in music is pretty basic.

**Comment by musikBear** [comment]
oki, lets sleep this
