### ISSUE TITLE
Fixing the Tags in this repository

### ISSUE THREAD

**Issue by Luraktinus** [LMMS/lmms#4107]
"digital" and "audio" and "workstation" makes no freaking sense... not only because you cant sort for multiple tags at once!

just use "daw" like everyone else!

https://github.com/VCVRack/Rack
https://github.com/Ardour/ardour
https://github.com/rserota/wad
https://github.com/monocasual/giada
and many other DAWs

**Comment by karmux** [comment]
I'd add `music`.

**Comment by Luraktinus** [comment]
nice, thank you
