### ISSUE TITLE
Selected notes in the Piano Roll editor do not look much different from unselected notes

### ISSUE THREAD

**Issue by raindropsfromsky** [LMMS/lmms#4111]
Earlier, the selected bars in the Piano Roll Editor appeared deep blue, and the unselected bars appeared green. Thus they looked distinct from each other, and it was easy to tell them apart.

![image](https://user-images.githubusercontent.com/9047168/34927862-775fa002-f9df-11e7-97bb-5ca001aa4a79.png)

But now the selected bars have a different hue of green. As a result, it is very difficult to tell which bars are selected and which are not.
![image](https://user-images.githubusercontent.com/9047168/34927865-7d413c7e-f9df-11e7-95c4-3088c0b84382.png)

**Desired:** Retain the color difference so that the user can easily tell which bars are selected.
In fact, showing the selected bars in yellow would be a good choice.

**Comment by Spekular** [comment]
I don't think yellow is a particularly good choice for selection as it's
just as close to green as the current blue selection color. Some indicator
other than color may be a better choice if we consider colorblindness.

"In males with protanopia, there are no working red cone cells. Red appears
as black. Certain shades of orange, yellow, and green all appear as yellow."

**Comment by tresf** [comment]
@raindropsfromsky thanks for this, we'll put it on the to-do list for 1.2.0.  @Umcaruje let's make the contrast better here.  @Spekular thanks for the research.

**Comment by raindropsfromsky** [comment]
About the color: Blender 3D uses orange outline to indicate that a shape is selected.
![image](https://user-images.githubusercontent.com/9047168/34952233-10e9999e-fa3f-11e7-916f-f2f57f24d6e0.png)
In the scene, the cylinder is selected, and the cube is not.

**Comment by musikBear** [comment]
It is available as a CSS option. My lousy eyes have already prompted me to change both selections and how scales are shown.
![pianoroll_cssmb](https://user-images.githubusercontent.com/6662066/34955231-cbaedc56-fa23-11e7-9d73-fc08459cd727.JPG)
@raindropsfromsky Here is my file:
[Copy (4) of style.zip](https://github.com/LMMS/lmms/files/1632560/Copy.4.of.style.zip)
Substitute it with the one you have in 
:\data\themes\default 
rename it style.css

**Comment by lukas-w** [comment]
> "In males with protanopia, there are no working red cone cells. Red appears as black. Certain shades of orange, yellow, and green all appear as yellow."

In case we want to take this into account without guess-working about what would look right, there's software like [Color Oracle](http://colororacle.org/) that applies a full-screen filter to simulate colour blindness.

**Comment by tresf** [comment]
This ColorOracle utility is very nice.  You don't need to install it either, you can just grab the JAR, which will open if you have Java installed already.

http://colororacle.org/ColorOracleJar.zip

Double-click the jar and then right-click the tray icon and select a color-blind profile it will temporarily switch your desktop to that color profile.

Interestingly enough, the selected notes actually appear to be grayed-out with the most common color blindness, but they actually appear a bit easier to differentiate, so this may be less of a color-blindness problem and more of a general contrast problem.

**Common**
![image](https://user-images.githubusercontent.com/6345473/34963217-62934d5a-fa15-11e7-86f5-1d408422096d.png)

**Rare**
![image](https://user-images.githubusercontent.com/6345473/34963304-c8e8d70a-fa15-11e7-9329-d17d58b8de0c.png)


**Very Rare Type**
![image](https://user-images.githubusercontent.com/6345473/34963281-a6c7d522-fa15-11e7-9332-e2968bdeb307.png)

**Comment by musikBear** [comment]
It is even simpler here 
http://www.color-blindness.com/coblis-color-blindness-simulator/
Just drop any picture
My suggestion is no good either.
Users with Blue-Weak/Tritanomaly wont see any difference at all

**Discuss:**
Wouldent this perhaps best be tackled with a **set** of CSS files?
I doubt it will be possible to retain a nice design, where all kind of color- impaired would see sufficient differences, *and* at the same time have a design that is pleasant for those with normal eyes.

**Comment by raindropsfromsky** [comment]
How about themes?

**Comment by tresf** [comment]
Another trick to force strict black/white on Windows is `Ctrl + Meta(Win) + C`, pardon the beep this makes.

![image](https://user-images.githubusercontent.com/6345473/36798041-8a28d982-1c77-11e8-82fe-71d6372e6e39.png)
