### ISSUE TITLE
LMMS Plugins

### ISSUE THREAD

**Issue by DanielRios549** [LMMS/lmms#4114]
Why isn't there plugins for LMMS for Linux? This is simply ridiculous, the program has a Linux version but the plugins does not, all plugins only have versions for Windows and Mac... What can I do to use these plugins?

**Comment by Umcaruje** [comment]
Are you talking about Linux VST support? If so, this a duplicate of #416

**Comment by tresf** [comment]
Calling a project rediculous is not acceptable demeanor for our bug tracker.
