### ISSUE TITLE
LMMS Plugins that hasn't a Linux version

### ISSUE THREAD

**Issue by DanielRios549** [LMMS/lmms#4115]
**First of all, I'm sorry about the last issue, It wasn't my intention offend the owners of the project, if it is possible, delete that issue, please.**

My doubt is how to use plugins that does not support Linux directly, for example, those we can download from websites such as meldaproduction and tal-software. I'm not sure if it is about the VST support, I only want to use these plugins, to help me to learn this software and audio in a general.

**Comment by tresf** [comment]
@DanielRios549 LMMS has very limited support for plugins.

* VST2(i)/VST2(fx) - Windows 32-bit (Windows and Linux via Wine)
* VST2(i)/VST2(fx) - Windows 64-bit (Windows-only currently)
* LADSPAv1 (fx, no DSSI) - Platform-native versions Linux, Windows, Mac
* LV2 (instruments/fx) - Indirectly via Carla (Linux only currently)
* Native plugins available from the plugins sidebar

Carla supports a few more formats that aren't listed.

Most people use Windows VSTi plugins through Wine, which offers the greatest selection albeit non-native on Linux.  Our built-in LADSPA effects are very comprehensive although some of them are becoming dated.

LinuxVST and LV2 are major gaps for us.  Sorry for the confusion over in #4114, we get a lot of opinionated rants around here. :)

**Comment by DanielRios549** [comment]
It's ok, I will try to use native plugins, but to use Windows VSTi plugins through Wine, I need only to change VST-Plugin Directory on settings, or I need to use the Windows version of LMMS with the wine prefix?

**Comment by tresf** [comment]
The easiest way to add Windows VSTi is to drag the DLL from the sidebar that has the file browser.

The directory in the settings is for the effects only.

**Comment by BaraMGB** [comment]
I think this issue can be closed.
