### ISSUE TITLE
BUG: The "Info" button does not work with the Controller Rack button in the 2nd row

### ISSUE THREAD

**Issue by raindropsfromsky** [LMMS/lmms#4119]
The "i" button does not work with the Controller Rack button in the 2nd row.
(It works with all 6 other buttons. Thus, technically this is a bug, but not worth much.)

In any case the "Info" button seems to be redundant: It does not add any value!
It just shows a tooltip when the mouse is hovered over buttons. 
Well, that same tooltip is shown even without clicking on this button first!

It does not work on the other elements of the screen, either. So I guess that it is yet to be implemented fully (?) If so, a suggestion: When the user clicks on the "i" button first, let LMMS show an **extended tooltip** instead of normal (short) tooltip.

**Comment by PhysSong** [comment]
Could you add a screenshot for this issue?

**Comment by raindropsfromsky** [comment]
Well, as the examples below show, there is no consistency in results: 
1. In some controls, there is a ban symbol, and no tooltip.
2. In others, there is a ban symbol, but the tooltip is displayed.
3. In yet others, the tooltip is shown (which is shown even without clicking on the "i" button).

**After clicking on "i" button:**
![image](https://user-images.githubusercontent.com/9047168/35030158-12fb336e-fb84-11e7-91db-8cdee7be92a8.png)

**Without clicking on "i" button:**
![image](https://user-images.githubusercontent.com/9047168/35030219-3f20dfe8-fb84-11e7-85a0-8f9168cb85ac.png)
(The only difference is the "?" overlay on the mouse-pointer.)

**After clicking on "i" button:**
![image](https://user-images.githubusercontent.com/9047168/35030172-1fd2dbb4-fb84-11e7-8ba9-c5952bad7073.png)
(Note that despite the banned symbol, the tooltip is shown anyway!)

**Without clicking on "i" button:**
![image](https://user-images.githubusercontent.com/9047168/35030188-2a6bdd1e-fb84-11e7-9ec9-88fae04f6359.png)
(Tooltip is shown.)

**After clicking on "i" button:**
![image](https://user-images.githubusercontent.com/9047168/35030248-53f1b32a-fb84-11e7-9830-595ce9434c5c.png)
(Banned symbol, and no tooltip.)

**After clicking on "i" button:**
![image](https://user-images.githubusercontent.com/9047168/35030269-69e3b0ac-fb84-11e7-9114-9796a85b0dc1.png)
(Banned symbol, and no tooltip.)

**After clicking on "i" button:**
![image](https://user-images.githubusercontent.com/9047168/35030283-75442706-fb84-11e7-972e-8f0990652277.png)
(Despite the banned symbol, the tooltip is shown anyway!)

**After clicking on "i" button:**
![image](https://user-images.githubusercontent.com/9047168/35030330-990c7e04-fb84-11e7-9332-b0adfabacbd4.png)
(Banned symbol, and no tooltip.)

**Comment by raindropsfromsky** [comment]
BTW there is yet another problem: 
Normally, after clicking on the "i" button, we can hover the mouse over multiple controls, and it goes on showing their tooltips.  But if I hover over the notes, LMMS comes out of the "info" mode automatically.

![image](https://user-images.githubusercontent.com/9047168/35030753-3c4b9a36-fb86-11e7-9fb7-9dc7913ed319.png)
There may be other controls that behave in this way.

**Comment by Sawuare** [comment]
I think we should remove the `What's this?` system because it's not fully implemented and has bugs.
Tooltips and documentation would be sufficient for teaching users.

**Comment by tresf** [comment]
> I think we should remove the What's this? system because it's not fully implemented and has bugs.
Tooltips and documentation would be sufficient for teaching users.

I wholeheartedly agree with this.  Outside of LMMS, I've never used a help system like this before.

**Comment by Sawuare** [comment]
I will remove it. What branch should I target, `master` or `stable-1.2`?

**Comment by tresf** [comment]
@Sawuare it should be properly discussed I think, but `master`.

**Comment by Sawuare** [comment]
@tresf What aspect should be discussed? 🤔

Some info:
On `master`, searching for `WhatsThis` gives 121 results in 19 files, mostly `setWhatsThis()` and `QWhatsThis::showText()` (99 translatable strings), and some code for the functionality itself and its toolbar button.

**Comment by tresf** [comment]
@Sawuare, it's something that we should run past the #devtalk channel first I think.

**Comment by Sawuare** [comment]
Fixed via #4128.
