### ISSUE TITLE
Problem with the Vestige to load external presets

### ISSUE THREAD

**Issue by Small-Develop** [LMMS/lmms#4123]
They do not load the sounds, when loading a .fxb (set of presets) the sounds are not loaded. and the set of available sounds is not shown! I have tried it in the stable version lmms-1.1.3-win32.exe and in the version lmms-1.20-rc5-win64.exe

**Comment by tresf** [comment]
@Small-Develop can you provide the name of the VST plugin you're testing with?

**Comment by DomClark** [comment]
Cannot reproduce and no reply from OP in two months, closing.
@Small-Develop please reopen this issue if you can provide more details.
