### ISSUE TITLE
 Build fatal error: X11EmbedContainer.h: No such file or directory

### ISSUE THREAD

**Issue by vrghost242** [LMMS/lmms#4124]
So been trying to get lmms to build on Gentoo, with Carla etc, and it has been more than a bit of a challenge, but soon I'll have a very cool DAW, potentially with YOUR help :) (See what I did there:) )

Just bit of background, had to install vine-2.20 vanilla on Gentoo first, then had to apply a hack the CMakeLists.txt for vst_base then FindWine.cmake (this thread if someone has the same issue on gentoo https://github.com/LMMS/lmms/issues/4108)

And now, at 68%, the build gets a fatal error:
```

[ 68%] Building CXX object plugins/waveshaper/CMakeFiles/waveshaper.dir/moc_waveshaper_controls.cpp.o
/mnt/stripe/media/lmms/plugins/vst_base/VstPlugin.cpp:41:33: fatal error: X11EmbedContainer.h: No such file or directory
 #  include "X11EmbedContainer.h"
                                 ^
compilation terminated.
make[2]: *** [plugins/vst_base/CMakeFiles/vstbase.dir/build.make:97: plugins/vst_base/CMakeFiles/vstbase.dir/VstPlugin.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```

There is a file with that name iin the git clone directory, not certain if it is the right one though
/src/3rdparty/qt5-x11embed/src/X11EmbedContainer.h

**Comment by vrghost242** [comment]
Not certain its a good fix, but seems to work
Just copy the file from ./src/3rdparty/qt5-x11embed/src/ to /plugins/vst_base/

It builds, not certain how well it will work though :)

**Comment by PhysSong** [comment]
@vrghost242 Which branch you're building from? Is your branch up to date?

**Comment by Umcaruje** [comment]
Did you run `git submodule update --init --recursive`?

**Comment by PhysSong** [comment]
> Did you run `git submodule update --init --recursive`?

`src/3rdparty/qt5-x11embed/src/X11EmbedContainer.h` already exists, but the issue is it the directory is not in the list of include directory.
I guess 5c3c052 should fix this if @vrghost242 is building from `master` between #4041 and that commit.

@vrghost242 Could you pull latest changes and try again?

**Comment by lukas-w** [comment]
No response in two months, closing.
