### ISSUE TITLE
rpmalloc build error

### ISSUE THREAD

**Issue by coreybruce** [LMMS/lmms#4125]
I get this error when trying to build the latest LMMS

`-- Configuring done
CMake Error at src/3rdparty/rpmalloc/CMakeLists.txt:3 (add_library):
  Cannot find source file:

    rpmalloc/rpmalloc/rpmalloc.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

CMake Error: Cannot determine link language for target "rpmalloc".
CMake Error: CMake can not determine linker language for target: rpmalloc
-- Generating done
-- Build files have been written to: /mnt/Storage/lmms/build`

**Comment by Umcaruje** [comment]
please run `git submodule update --init --recursive` this should fix your issues.

**Comment by coreybruce** [comment]
Thanks but I ran into another issue

```
In file included from /mnt/Storage/lmms/include/MidiEvent.h:28:0,
                 from /mnt/Storage/lmms/include/RemotePlugin.h:29,
                 from /mnt/Storage/lmms/plugins/vst_base/RemoteVstPlugin.cpp:35:
/usr/include/c++/5/cstdlib:41:28: fatal error: bits/c++config.h: No such file or directory
compilation terminated.
winegcc: g++ failed
plugins/vst_base/CMakeFiles/vstbase.dir/build.make:61: recipe for target 'plugins/RemoteVstPlugin' failed
make[2]: *** [plugins/RemoteVstPlugin] Error 2
CMakeFiles/Makefile2:9075: recipe for target 'plugins/vst_base/CMakeFiles/vstbase.dir/all' failed
make[1]: *** [plugins/vst_base/CMakeFiles/vstbase.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by Umcaruje** [comment]
run `sudo apt-get install wine-dev libwine-dev libwine-dev:i386 gcc-multilib g++-multilib libqt5x11extras5-dev qtbase5-private-dev libxcb-util0-dev libxcb-keysyms1-dev`

**Comment by coreybruce** [comment]
`Note, selecting 'wine1.6-dev' instead of 'wine-dev'
E: Unable to locate package libwine-dev
E: Unable to locate package libwine-dev:i386`

Just letting you know these packages don't exist, thanks for the help I got it compiled!

**Comment by lukas-w** [comment]
@coreybruce These package do exist. You're probably missing 
```sh
sudo dpkg --add-architecture i386
sudo apt-get update
``` 
This is described in the wiki: https://github.com/LMMS/lmms/wiki/dependencies-ubuntu#vst
