### ISSUE TITLE
Only drumsynth samples provided by Fedora system repo's

### ISSUE THREAD

**Issue by dalanicolai** [LMMS/lmms#4126]
I am not sure to where to address this "bug". Anyway I'll first try it here...
So I installed LMMS on Fedora 27 from the standard repositories, however this installation provides only the 'drumsynth' directory as samples. When I installed LMMS in Windows it came with a bunch of other directories. I found no easy/straightforward way to obtain the other samples for fedora (besides just copying them from the windows installation). I am afraid that, in this way, the Fedora users get the wrong impression of the awesomeness of LMMS. I am not sure if this is a general linux 'package' issue or a specific Fedora issue. But I figured at least it would be nice to report somewhere about the issue. Of course I am happy to receive suggestions on where and how to address these kind of bug reports...

**Comment by zonkmachine** [comment]
Thanks for reporting this!

> I am not sure if this is a general linux 'package' issue or a specific Fedora issue.

This sound like a Fedora package issue. I suggest you report this with Fedora.
https://apps.fedoraproject.org/packages/lmms/

If you want to see what the full package should look like you can try the new lmms-1.2 Beta AppImage. https://lmms.io/download/#linux

**Comment by dalanicolai** [comment]
Thanks Oskar! I will have a look at the full package and if necessary
report the issue to fedora...

**Comment by thmo** [comment]
See https://src.fedoraproject.org/rpms/lmms/blob/master/f/README.fedora. The samples are not included in the Fedora package because for many of them the copyright status is unclear.

See also this discussion several years ago: https://sourceforge.net/p/lmms/mailman/message/21407315/.

**Comment by zonkmachine** [comment]
> See also this discussion several years ago: https://sourceforge.net/p/lmms/mailman/message/21407315/.

@thmo Thanks! This is nine years old discussion. Perhaps someone from @LMMS/sample-editors can shed some light on the current license status.

**Comment by Umcaruje** [comment]
LMMS is in the progress of building a new sample library to completely replace the current samples, probably for release version 1.3. This sample library is community made and it will consist of clean, high quality samples which are licensed as CC0, that is in the public domain so there won't be any more licensing issues.

**Comment by zonkmachine** [comment]
Closing as an issue upstream. Licenses being removed is not our decision. The state of our samples and their licenses of cours is but is being worked on [here](https://github.com/LMMS/assets). Actual sample library can be accessed here: https://github.com/LMMS/assets/tree/master/Samples
