### ISSUE TITLE
Sweeping active Equalizer bands generates audio artifacts.

### ISSUE THREAD

**Issue by Sawuare** [LMMS/lmms#4127]
Sweeping active Equalizer bands generates audio artifact (clicks & pops, DC offset), especially in the range near the minimum frequency.
Sweeping speed affects the intensity of the artifacts, and manual sweeping is more likely to generate them.

[Equalizer audio artifacts.zip](https://github.com/LMMS/lmms/files/1652208/Equalizer.audio.artifacts.zip)

**Comment by PhysSong** [comment]
Sounds similar to #3527. Tagging @curlymorphic as the author of the Eq plug-in.

**Comment by curlymorphic** [comment]
fixed by #4260 

closing
