### ISSUE TITLE
Connect to multiple Automation TCOs simultaneously

### ISSUE THREAD

**Issue by DouglasDGI** [LMMS/lmms#4132]
Oftentimes, I have a very large number of automation clips on a single track, and I need multiple instruments attached to each one.  For example, I may need to automate the pitch of most, but not all of the instruments.

The issue is, each time I create a new instrument that needs that pitch automation (or any other automation, I'm just using pitch as an example), I need to Ctrl+Click+Drag the knob to be automated to _every single applicable automation clip._

![spectacle f13857](https://user-images.githubusercontent.com/34612565/35462348-cfa1e03c-02a8-11e8-954c-a568003a55e8.png)

Please no.

My proposed solution, is to add the ability to attach a knob to every single automation clip in a track.  It is quite common for people to have one automation track per type of automation, so adding that feature would allow people to only have to Ctrl+Click+Drag (or however you choose to do it) once rather than hundreds of times.

In the screenshot above, I had to connect eight instruments to each of those.  That's 264 connections I had to do one at a time.

There are multiple ways one can go about this, but I suggest maybe, once an automation clip is right clicked, have an option to take all connections on that clip and assign it to every clip in that automation track.  So, somebody could take what they want to mass connect, Ctrl+Click+Drag it onto the applicable track, right click on it, select that option, and they'd be done.  There are other ways this can be done, but that is the neatest way I can think of without things starting to get a bit messy.

If this feature could be added to future versions of LMMS, that would be amazing!

**Comment by tresf** [comment]
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.
