### ISSUE TITLE
It is difficult to auto-detect the LMMS window elements

### ISSUE THREAD

**Issue by raindropsfromsky** [LMMS/lmms#4134]
The details of the bug are provided here:
https://github.com/Snipaste/feedback/issues/796

The summary is as follows: 
When the system DPI is larger than 100%, the beta version of LMMS works without any problem with UI Automation, but has issues with MSAA (Microsoft Active Accessibility). 

The UI framework needs work to correct this issue. (HiDPI efforts: LMMS/lmms#2510)

@tresf please pardon if there are any errors!

**Comment by PhysSong** [comment]
Consolidated into #4590.
