### ISSUE TITLE
LMMS as VSTi

### ISSUE THREAD

**Issue by NETMANSKY** [LMMS/lmms#4136]
Hi!
Long time I thought about how to link LMMS and some Daw. In practice it realised by Rewire but LMMS developers answered me it's unrealizable. Well, but there is another way to realise this idea - design special plugin to launch LMMS as VSTi in different hosts seams FL launching. In my opinion it's a good idea. Who supports this approach?

**Comment by Umcaruje** [comment]
I think there are a lot more features and fixes that need to be applied to LMMS for it to be stable and competitive with other software before we even start considering doing something like this.

**Comment by tresf** [comment]
I think a more reasonable approach is to support JACK transport (#523), which some have gotten working using @gi0e5b06's one-off code available here https://github.com/LMMS/lmms/issues/1467#issuecomment-341250582.

VST(i) is a bit too general, I feel.  LMMS isn't an instrument, but rather is a daw that can offer instruments.  I can't see an easy way to do as this request is suggesting.  Perhaps an example DAW that provides this and explanation of functionality would be a good start although I'm inclined to close as won't-fix.  I don't see this happening for a very long time, if ever.

**Comment by NETMANSKY** [comment]
@tresf You talking all time: "impossible, unrealizable, not necessery". Strange approach... Do you know why i like LMMS? For its step sequencer... Nice instrument that another DAWs has no. But LMMS can not be named DAW. Untill there is no support:
- work with sound files
- freezing tracks
- multi-channel vsti
- and many others features characterised for DAW...
LMMS primarily is sequencer and will remains by SEQUENCER yet "far far far" time. And probably it's right approach. Unfortunatly, you wont see perspectives for LMMS in my suggestion and you have no resources to make LMMS as full valuable DAW but beleave me a stable LMMS as VSTi (not Jack support) is a new perspective way for full valuable sequencer that will support link to any DAW!

**Comment by Mark-Agent003** [comment]
@NETMANKSY , https://en.m.wikipedia.org/wiki/Digital_audio_workstation

As @tresf has said, LMMS is a DAW. Implementing your request would require a lot of work that AFAIK is only desired by you. Insulting the developers hard work by saying that LMMS is not a “real DAW” until it meets your list of demands is IMO very rude.

**Comment by tresf** [comment]
> by saying that LMMS is not a “real DAW” until it meets your list of demands is IMO very rude.

Agreed and I'm locking this to avoid it escalating.  @NETMANSKY we'd be happy to accept a code contribution in the form of a Pull Request with the aforementioned feature.  Since we don't even implement non-Windows VSTi's properly, I'd also ask the submitter helps with that initiative.  Thanks for sharing your idea.
