### ISSUE TITLE
Does the Piano Roll Editor have "volume control" or "velocity control"?

### ISSUE THREAD

**Issue by raindropsfromsky** [LMMS/lmms#4137]
In LMMS 1.2.0 RC5, the Piano Roll Editor has **Velocity control** rather than **volume control**. ([ref](https://en.wikipedia.org/wiki/Keyboard_expression#Velocity_sensitivity))

But not instruments are velocity-sensitive. According to Wikipedia:
- Acoustic pianos, such as upright and grand pianos, are velocity-sensitive—the faster the key strike, the harder the hammer hits the strings. 
- Baroque-style clavichords and professional synthesizers are after-touch-sensitive—applied force on the key after the initial strike produces effects such as vibrato or swells in volume. 
- Tracker pipe organs and electronic organs are displacement-sensitive—partly depressing a key produces a quieter tone.

The Wikipedia article explains that _a given instrument changes its tone and volume_ in response to **only one** of the following inputs: velocity, after-touch pressure or displacement. For example, 
- A piano would not change its sound quality (=tone+volume) in response to _after-touch pressure_ or _displacement_.  

IINW wind instruments such as flute would not change their timber and volume at all if velocity is changed.

Secondly, I could not find how the instrument changes its tone (timbre) when the velocity is changed. 
- The most logical place to look for this new implementation was in the **Instrument** window, where the volume+cutoff+resolution sections are made to respond to velocity. (e.g. the AMT and Sustenance change when the note has higher velocity.) But I do not see any new change there...

Thus, in theory, the earlier implementation (note-wise volume) seems to be the correct implementation.

**Comment by Mark-Agent003** [comment]
Are you saying that instead of the piano roll having velocity-sensitivity, it should have note-wise volume?

**Comment by Spekular** [comment]
I'd imagine the term "velocity" originally comes from velocity when playing
something like a piano, but it has a separate meaning in the context of a
DAW*. I don't think it needs to be relabeled, especially not if you're
suggesting some instruments have "displacement", others "after touch" and
yet others "velocity".

That said I do find it misleading that it falls back to just being a volume
control when an instrument doesn't support velocity (AFAIK).

*See this for example, velocity can be mapped to several different things:
https://forum.ableton.com/viewtopic.php?f=2&t=164942

**Comment by raindropsfromsky** [comment]
I did not say that.

But it is my understanding that the sensitivity to velocity, OR after-touch pressure, OR displacement are the properties of the instrument; and NOT of the musical piece. 

Therefore it should be adjustable in the Instrument window; not in Piano Roll Editor.

To give one example, if the same musician plays the same piece with identical expression on two different instruments, they should sound different, because their sensitivities are different.

On the other hand, the actual expression given to a note is the property of the musical piece. It depends on how fast the musician hits the key, OR how much pressure he exerts after depressing the key, OR how much he depresses the key. (The musician must keep in mind what instrument he is playing, and hit the keys accordingly.)

Thus the bottom pane of the Piano Roll Editor should represent the appropriate input from the musician for each keystroke; depending on the instrument: 
- If this is a Piano, then the expression is through velocity. 
- If it is a Baroque-style clavichords or professional synthesizers, then the expression is through after-touch
- If it is a flute, it does not have expression.

I expected to see this changed functionality in the new GUI, after seeing the change of label from **Volume** to **Velocity**. But except for the label, nothing seems to have changed.

In that case, "volume" seems to be the more appropriate label for that control.

**Comment by Umcaruje** [comment]
I was the one who made this change. If you look at the MIDI standard, notes have Velocity, not volume, when you record something with your MIDI keyboard you're recording it's velocity, not the volume. LMMS has a bad habit in the code where Velocity = Volume and that is simply not the case. 

Other DAWs call it Velocity too, I just checked in Bitwig and Ardour.

If the native instruments choose to handle it as a simple volume control for notes, it is what it is, but it triggers a different sample in soundfonts, not to mention VST's which get MIDI data sent to them which contains notes and velocity, not volume.

**Comment by raindropsfromsky** [comment]
@Spekular 

In LMMS, it is closest to volume, as it does not change the timbre and sustenance of the sound. (Two main noticeable things that happen in a Piano, but not in other instruments.)

But one thing is certain: It is not a property of the instrument.
It is the property of the specific keystroke.

Yes, it can be programmed to do different things. And it should be named after what it actually does.
And that precisely my point.

**Comment by Umcaruje** [comment]
Also, before you open a new issue, please use the search function and look at the context of a change.
Issues #2316 #2553

**Comment by raindropsfromsky** [comment]
oops!

**Comment by Mark-Agent003** [comment]
I see what you’re saying, but like @Spekular said, velocity means something a bit different in the context of a DAW. Velocity is used to describe the intensity of the sound. Synthesizers sometimes use velocity to affect the modulation, cutoff, or envelope. When using a multi-sampled instrument, the velocity may even change what sound file is played.
The term “velocity-sensitive” is especially useful for those using MIDI keyboards, where the more velocity you apply to a key, the more the effects mapped to velocity are applied. 
 Changing the label to volume would make the label less applicable to the functionality of the feature than velocity.

**Comment by zonkmachine** [comment]
MIDI Velocity comes from the very first MIDI standard. Basically it just describes the speed at which the key is struck and maps it to a 0 - 127 value. How the velocity is interpreted is then implementation specific. It can be synonymous with volume or it will be controlling the filter cutoff but it's really just another control signal on the palette.

> But it is my understanding that the sensitivity to velocity, OR after-touch pressure, OR displacement are the properties of the instrument; and NOT of the musical piece.

It is a bit of both. Some instruments are sensitive to after-touch etc. and they will probably have a corresponding notation to tell the player how much after touch or velocity to use. The recorded keyboard pattern is just like that notation. We just copy the keyboard activity to the recorded pattern and if the keyboard handles velocity that get's recorded too. I think this is the correct behaviour.

**Comment by BaraMGB** [comment]
This can be closed?

**Comment by raindropsfromsky** [comment]
Yes, please. 
I have amended the user manual, so that advanced users can make use of the velocity factor.
