### ISSUE TITLE
Compilation failure with Qt 5.9.1

### ISSUE THREAD

**Issue by ajtribick** [LMMS/lmms#4141]
While compiling the stable-1.2 branch in Ubuntu 17.10, I ran into an issue that the third-party library used to replace QX11EmbedContainer depends on private files internal to Qt that are not present in Qt 5.9.1, these are referenced in X11EmbedContainer.cpp.

As a quick and nasty fix, I removed the references to this library from the code and the relevant CMakeLists.txt file and removed the code that handles `if (m_embedMethod == "xembed" )` from VstPlugin.cpp entirely.

From what I can tell from the various documentation, the way to go in Qt5 would be to do something similar to what's in the `if (m_embedMethod == "qt")` section using `QWindow::fromWinId`, but this is outside my area of expertise.

**Comment by PhysSong** [comment]
You need to do `git submodule update --init --recursive` if you've cloned the source code using Git, otherwise you need to re-download source code with `git clone --recursive https://github.com/LMMS/lmms`.

**Comment by lukas-w** [comment]
@ajtribick We're using Qt 5.9 for our CI and for our AppImage builds without problems. The private files you're referring to are present in Qt 5.9.1. You're likely missing `qtbase5-private-dev` as @PhysSong pointed out.

**Comment by ajtribick** [comment]
Got it, cheers.
