### ISSUE TITLE
Doesn't start on Windows 7

### ISSUE THREAD

**Issue by sewil** [LMMS/lmms#4149]
Installed v1.1.3 64-bit on win7 64-bit, running it gives me this error, no further information or logfile is given:

![image](https://user-images.githubusercontent.com/1498414/35760782-d2bcb050-0882-11e8-8d27-7bfc29c50434.png)

I also checked the system requirements on your wiki but it only says "windows"

**Comment by zonkmachine** [comment]
This is fixed in the latest beta versions of lmms-1.2 .
Download here: https://lmms.io/download/#windows

**Comment by zonkmachine** [comment]
Closing. Please reopen if updating to lmms-1.2.0-rc5 or later doesn't fix the issue.
