### ISSUE TITLE
Can better automation-track labels from VSTs be implemented?

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#415]
Love the VSTs automation possibillities, but there is a small annoyment. When a knob is automated, it will 'name' the automationtrack as the Array-pos eg an automationtrack could get the 'name' veSTige>24. Is the actual knob-label-handle not available? It would be serious better if the auto-track was named as concanated string: Preset+":"+knob-label
eg the user would see "Synth1: FilterSaturation", and not "veSTige>24"
At least the track naming shoud be "Synth1: 24", if there is no handle to the knob-label.

**Comment by Spekular** [comment]
Closing and consolidating into #5433
