### ISSUE TITLE
More points on low-end of EQ spectrum

### ISSUE THREAD

**Issue by noahb01** [LMMS/lmms#4151]
In the native Equalizer plugin, there are noticeably less points on the lower end of the frequency spectrum, especially >120 Hz. I understand the reason for this (one point every x Hz), but the problem comes when you play, for example, a 40 Hz pure sine wave. The EQ will display the frequency as a large curve from ~20 Hz to ~60 Hz instead of the expected sharp point directly at 40 Hz. 

The simplest way to fix this in my opinion would be to add more points to the EQ on the lower end in a logaritimic style, i.e. more points the lower down the spectrum.

**Comment by PhysSong** [comment]
As a baseline comparison, here's the spectrum view of 40Hz sine wave in Audacity(FFT size 4096):
![2018-02-10 21-46-34](https://user-images.githubusercontent.com/12591074/36062268-e2dc160e-0eab-11e8-82f7-c50ac88ff4bb.png)
The way to work around this phenomenon is increasing FFT buffer size(currently 2048), but it has some side-effects(reduces time resolution and latency). Related: #3626.

**Comment by noahb01** [comment]
Maybe we could implement this as a slider/drop-down in the Settings window?

**Comment by Umcaruje** [comment]
I think this is a duplicate of #3626

**Comment by PhysSong** [comment]
> I think this is a duplicate of #3626

Agreed. Close this?

**Comment by noahb01** [comment]
Alright, closing.
