### ISSUE TITLE
Failed title revert after render

### ISSUE THREAD

**Issue by noahb01** [LMMS/lmms#4160]
After rendering a song, the main window title fails to revert to its normal title and remains as "Rendering: 100%".

**Reproduce**
open a song
render it
look at main window title, even after the render is complete it stays as "Rendering: 100%"

This is probably a simple fix...

**Comment by zonkmachine** [comment]
The function that resets the window title is [MainWindow::resetWindowTitle()](https://github.com/LMMS/lmms/blob/c3b47678368d1a617c3d58b062901ee4b732c4c9/src/gui/MainWindow.cpp#L666).
I could replicate this with the Qt5 AppImage but not on compiling the Qt4 version.



> This is probably a simple fix...

I dare you...

**Comment by noahb01** [comment]
A one-line change was all that was needed, I've created a pull request with the change. Should I close this issue?

PR: #4161

**Comment by tresf** [comment]
@noahb01 thanks for taking the time to document and fix this!  This is really a good candidate for `stable-1.2`.  I'll take it from here.
