### ISSUE TITLE
Trailing slashes can break relative paths

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms#4173]
This may be a long standing bug, but there's something in LMMS that appears to put additional trailing slashes in working paths.

e.g. 
```cmd
C:/samples/
```

vs.
```cmd
c:/samples///
```

Although I'm not sure the exact cause of this, it's a benign problem when loading samples.  The issue seems to come into play when saving because the relative path logic is broken.

To reproduce, add an extra slash or two to the `LMMS WORKING DIRECTORY` in the preferences pane and restart LMMS.

![screen shot 2018-02-13 at 1 07 00 pm](https://user-images.githubusercontent.com/6345473/36165834-cbe8b5be-10be-11e8-8b96-4378f4f2e85f.png)

Next, import some samples into the project from your `LMMS WORKING DIRECTORY PATH` and save the project to an `.mmp` format.  When the files are saved, instead of being relatively, they contain the full paths.

**Expected:**
```xml
<audiofileprocessor ... src="mysample.ogg" />
```

**Actual:**
```xml
<audiofileprocessor ... src="/home/tres/lmms/samples/mysample.ogg" />
```

The underlying bug may actually be something with the preferences dialog, but we need to fix the trailing spaces bug as well incase this is typed by a user on accident.

Disclaimer, this bug was introduced using the Sample Track, not audiofileprocessor.  Example above is hypothetical.

**Comment by PhysSong** [comment]
Reproduced. I think this logic is problematic:
https://github.com/LMMS/lmms/blob/0f0b08b852196d14683e29e3d7be3a62d1f2539b/src/core/SampleBuffer.cpp#L1435-L1437
We may leverage from [`QDir::absolutePath`](http://doc.qt.io/qt-5/qdir.html#absolutePath) or [`QDir::canonicalPath`](http://doc.qt.io/qt-5/qdir.html#canonicalPath), which removes redundant `.`, `..`, and multiple separators.
