### ISSUE TITLE
Rename the "detune" button in Piano Editor as "pitch-bend" or "portamento"

### ISSUE THREAD

**Issue by raindropsfromsky** [LMMS/lmms#4174]
When we say "detuning" of a real-world musical instrument, we really mean changing of its default scale. (=scale-shifting)

For example, changing the tension of strings in stringed instruments or certain drums (e.g. Tabla, pakhavaj, mrudangam).

This changes the playing characteristic of the instrument. 

But in  Piano Editor, the button that is called "detune" actually adds a "pitch-bend" or "portamento" effect. (usually done with a pitch-wheel in a synth).

It does _not_ change the pitch of the instrument (no shift of scale).

Therefore it should be renamed as "pitch-bend" or "portamento".
(The former name is pop form and the latter name is classical/formal form.)

**Comment by noahb01** [comment]
In the DAW world de tuning refers to changing the pitch of a note, I believe this is the correct name.

**Comment by Anonymouqs** [comment]
I agree with noahb01, detune is a better name-especially for synths. Detune is used for the various oscillators on multiple additive synths, which is a perfect description of what it does. Usually, detune is kept permanent through the whole composition, it is usually used to create "uneven" harmonics. Pitch-bend is seen as a more temporary effect, which can already be achieved with the "Detune Mode" on the Piano Roll.

On the subject of renaming "Detune Mode" into "Pitch Shift Mode" in the piano roll editor, I am in complete support of such. The change to the notes some more of a "Pitch-Bend" effect rather than a complete "Detune"

**Comment by Sawuare** [comment]
"Detune" is to put out of tune, usually statically, as @Anonymouqs pointed out. So it does not describe this feature well.

I think we should designate "Portamento", a pitch sliding from one note to another, to a feature in instrument plugins which works like `PORT` in ZASFX.

For this feature, I think the best name is either "Pitch bend" or "Pitch glide/slide".

**Comment by noahb01** [comment]
I would say "Pitch Shift" mode would be more accurate than "Portamento". Portamento refers to sliding between notes, which is a common but not the only use of this feature.

**Comment by DomClark** [comment]
Personally, I would go with "pitch bend" or "pitch shift"; "pitch glide/slide" and "portamento" seem to refer to a change in this value, rather than the value itself.

**Comment by raindropsfromsky** [comment]
How about "glissando"?

**Comment by noahb01** [comment]
@raindropsfromsky both "glissando" and "portamento" refer to sliding **between notes.** This is a common use of the detune feature but is not the only one -- simulating string bends on a guitar would not be "glissando," but it is  a common use of the feature.

**Comment by Anonymouqs** [comment]
- 👍  for Pitch-Bend Mode or Pitch-Shift Mode **in the Piano Editor**
- 👎  for keeping it named Detune Mode **in the Piano Editor**

**Comment by raindropsfromsky** [comment]
Ok so the discussion generally agrees against using "detune", but added some more suggested terms:''
"Pitch-shift", "portamento", "glissando", "pitch-bend",  and "Pitch-shift".

I have tried to compare them in one place:

IMHO **"Pitch-shift"** is a completely different musical effect, where we change the scale of a few notes temporarily _within_ a song (some part of the song is rendered at a different pitch). Note that it need not have a glide between notes at all.

The **"portamento"** or **"glissando"** effect is smooth transition **between** two notes. That is exactly what we are achieving here. But rather than adding a glide between two separate notes, we have to create the entire combination in one single note. In other words, we are creating three parts in one note: Note#1, slide, Note#2.  (Actually we have to draw a horizontal part in the composite curve to create Note#2).

Once the tool is selected, we may continue adding more and more glides in the same curve. 

Therefore this button can be called a **"glide"**.

This can also be called a **"pitch-bend"** effect (very similar to the whammy bar in electric guitar, or a pitch-wheel on a keyboard.) In both, as soon as you remove the pull, the note returns to its natural pitch. LMMS does not have this automatic centering. But other than that, the effect is the same.

**Comment by tresf** [comment]
Rename it pitch bend please.  Reasoning is sound.  No pun intended.
