### ISSUE TITLE
User cannot see the FX Mixer connections at a glance: Some solutions

### ISSUE THREAD

**Issue by raindropsfromsky** [LMMS/lmms#4181]
LMMS does not have an easy visualization that shows which instrument is connected with which FX channel; and also which channels are connected with other FX Channels.

I found a couple of implementations (see below)

Personally, I like the **patch-panel matrix** of Ardour

![image](https://user-images.githubusercontent.com/9047168/36465934-9aacbc94-16fd-11e8-920c-89522640a1cf.png)

This implementation is not only clean, but it can convey a lot of information by color-coding the dots and the labels.

The second category is where the connection is shown with a line or curve.

![image](https://user-images.githubusercontent.com/9047168/36466014-f81a0d6e-16fd-11e8-80d8-67eec770ec5a.png)
IMHO this cannot convey the information like the patch matrix can. Probably the matrix is easier to code also!

![image](https://user-images.githubusercontent.com/9047168/36467480-f6a86956-1704-11e8-8225-83e660114a45.png)
This is from OpenOctave Midi.

At minimum, LMMS should display a list of all connections as extended tooltip. 
(When the user hovers his mouse on a channel, show all connections in an extended tooltip.)

**Comment by musikBear** [comment]
> At minimum, LMMS should display a list of all connections as extended tooltip.

Or the user should use *Project-Notes* and write down what he connect, and maby more important, *why*. Im not sure a visualisation is worth that much.

**Comment by Anonymouqs** [comment]
>Or the user should use Project-Notes and write down what he connect, and maby more important, why.

Some artists just *feel*, they like to try stuff out; sometimes, the user might want to see a "summary" instead of reading the actual book. Also, hand-documenting connections is beyond tedious, it is soul-destroying in a complicated project. 

Finally, such visualization has clearly become a standard. If we want to set a standard(by going beyond), we must first *meet* it. 

And every (good) standard has a reason, this is for the ease of the user and allows them to keep their music more organized. I feel Ardour's version would be more intuitive and allows ease of refactoring.

**Comment by Spekular** [comment]
Just as an FYI, FL has a display with "cables" connecting channels:
https://www.image-line.com/support/FLHelp/html/mixer_index.htm

FWIW I'm more of a fan of the line connections (2 lists or FL style) than a
matrix display.

**Comment by Anonymouqs** [comment]
>FWIW I'm more of a fan of the line connections (2 lists or FL style) than a
matrix display.

What if we support both types? Speaking of line-based views, I like OpenOctave's rendition a lot.

**Comment by tresf** [comment]
We wouldn't turn down any of the above proposals.  The cable routing would fit within our current UI a bit better for the short-term.  The matrix view may be better off as a full-mixer spectrum analyser so that each channel can be monitored without adding a visual plugin over and over; soloing; whatever we do today.

**Comment by Anonymouqs** [comment]
Another possible solution where the fx channel number is given in the Song-Editor. Maybe the user should be given different ways to visualize Channel Routing.
![channelshow](https://user-images.githubusercontent.com/31394502/36930481-4e68aed0-1e67-11e8-9a16-2b09b177c4e3.png)

**Comment by acidavid** [comment]
@Anonymouqs that would be a great idea, i woudn't have to open the plugin window everytime i need to reroute something!

**Comment by musikBear** [comment]
not only a great idea, just about 5. or 9. time *this* exact 'great idea' is proposed 🤣

**Comment by raindropsfromsky** [comment]
@Anonymouqs, the FX Mixer already has the same information, and so this display would be redundant.
In fact, this channel number would occupy precious space in the track.
 
![image](https://user-images.githubusercontent.com/9047168/36935745-7ad82a08-1f21-11e8-99c8-7104d2da2c04.png)

**Comment by raindropsfromsky** [comment]
@tresf your screenshot itself shows the complete solution _even if we ignore the interconnecting lines_!

I have cropped your screenshot to remove the lines.
![image](https://user-images.githubusercontent.com/9047168/36935993-1fa0c47a-1f25-11e8-8ebf-769afc53b6c9.png)

As shown above, the meaning is still  absolutely clear!

This follows a simple "signal bus" concept, where-
- The signal comes out of the channel that has a downward green arrow.
- the signal enters any channel that has a volume control topped by a Circumflex symbol ˆ.

**Comment by raindropsfromsky** [comment]
I have not used that sofftware, but I guess a black volume ring means the incoming signal is muted.
But the channel still assigned as incoming channel for that signal.

**Comment by raindropsfromsky** [comment]
Compared to our SEND+arrow scheme, this scheme is far simpler and much more intuitive.

**Comment by musikBear** [comment]
https://user-images.githubusercontent.com/9047168/36935993-1fa0c47a-1f25-11e8-8ebf-769afc53b6c9.png
How can you see what comes from where and goes to *witch* - i see a lot of arrows `(and no indians:)`

**Comment by raindropsfromsky** [comment]
That's the trick: consider only those channels that have the volume
controls-- even if the ring is dark, and not green.

As regards the other (unused) channels having arrowheads, I haven't used
that software, so I cannot guess the purpose of showing so many arrow-heads.

But in our case, we can omit them.

Then the input-output relationship will be very clear. Of course, for one
output channel at a time. (Even at present, LMMS can show the connections
only for the selected channel; not all interconnections between all
channels at a time. Such a display would be too confusing!)

**Comment by acidavid** [comment]
@raindropsfromsky it might be redundant but i still think itd save lots of time from having to open each instrument everytime to assign a channel

**Comment by tresf** [comment]
FYI - The gear can assign a new or existing channel in 1.2.0.  Use it all the time. :)

**Comment by Mark-Agent003** [comment]
I think that we'd only need to add a visual and not completely remake the send system: 
![image](https://user-images.githubusercontent.com/25230510/36954346-e5c72376-1fe6-11e8-887b-a6960a358c31.png)
(that's just a mockup)

**Comment by tresf** [comment]
> I think that we'd only need to add a visual and not completely remake the send system:

Agreed, although making the lines and the knobs near each other would be a nice touch.  I think @raindropsfromsky has a valid point that the example https://github.com/LMMS/lmms/issues/4181#issuecomment-368098511 is far superior for several reasons already pointed out as well as removed the english word "SEND" from our pixmaps.  Help on this feature is greatly appreciated.

**Comment by raindropsfromsky** [comment]
@tresf on second thought, @acidavid's idea seems to have a distinct advantage over _"assign the channel using gear icon"_ scheme: 

The assigned channel is visible on "per instrument" basis. In fact, the primary function of the FX MIxer is to control a group of instrument together and apply them various common effects, right? If so, the channel number in the FX Mixer actually could be assigned to multiple instruments at a time. (e.g. to "String" section of an orchestra). This _many-to-one_ relationship is not being visualized currently. @acidavid's idea does that nicely.

In fact, let's assume that your strings are assigned to FX5. If you add a new string instrument to the Song Editor, and then try to assign it to a FX channel (using the gear), how will you assign it to FX5 unerringly? Now imagine that the other instruments are already displaying the FX channels (as suggested by @acidavid). Now it is easy to pick the correct FX channel.

When I tried to rebut his suggestion earlier, I overlooked this important factor.

**Comment by acidavid** [comment]
@raindropsfromsky hey,thanks for the recognition, but thank @Anonymouqs it was his idea!

**Comment by acidavid** [comment]
i beleive in this project(and am also too broke to buy a powerfully licenced daw) but i believe in this project, seriously.didnt expect to get that far with a free daw

**Comment by raindropsfromsky** [comment]
BTW @Mark-Agent003 your screenshot leaves some ambiguity as to how the channels are chained.

It could mean any of the following:

- FX7 -> FX9 -> FX4, FX13, FX0
- FX7+FX9 -> FX4, FX13, FX0

To eliminate the ambiguity, even the selected channel should show its arrow direction (and also its volume control).

**Comment by acidavid** [comment]
i beleive it is 9->7->4 and 13

**Comment by acidavid** [comment]
@raindropsfromsky

**Comment by raindropsfromsky** [comment]
I have a doubt: Suppose I press the **Solo** button for FX13. It will mute all other FX channels, including FX7 and FX9. In that case will its incoming signal cut off?

Or does the mute button control only the OUTGOING connection to Master, and affects no other incoming connections?

**Comment by acidavid** [comment]
soloed, logically, id say it blocks the incoming(chained)signal but the signal that comes from the instruments directly assigned to its(13) bus shall still go to master unless it does not send to master and only to 7

**Comment by raindropsfromsky** [comment]
@acidavid you have not mentioned output to Master, although the GUI shows it distinctly.
Thus we have a direct (dry) feed from FX9 to Master, and also wet feeds via FX7, FX10 and FX13.

**Comment by acidavid** [comment]
i think if you solo 13, you will only have instrument ->13->master and no 7, 9 and 13 which means that, as 9 (which is sending to 7 which is sending to 13) is muted, the signal from 9 and 7 will be muted and the only signal received is the one coming from instrument directly to 13

**Comment by acidavid** [comment]
but with this picture, we cant see which buses are connected to master and which are exclusively connected to another bus unless we click on master

**Comment by acidavid** [comment]
check out #4187 , this is an interesting solution @raindropsfromsky

**Comment by acidavid** [comment]
(nothing new, just aesthetic solution)

**Comment by Mark-Agent003** [comment]
@raindropsfromsky the arrow icons at the top of each slot should indicate the direction, but as @tresf said, it would be clearer to have the arrows and knobs right next to the cables.

**Comment by raindropsfromsky** [comment]
So, is it correct to sum up that-
1. shift the volume knob+arrow to the bottom of the Channel.
2. eliminate the SEND label.
3. Show loops as @Mark-Agent003 shows.
4. Show the volume knob and arrow even for the selected channel

**Comment by musikBear** [comment]
in respect to image https://github.com/LMMS/lmms/issues/4181#issuecomment-370289487 -the connection overview would be much improved, if each of the lines had user-chosen colors

**Comment by tresf** [comment]
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.
