### ISSUE TITLE
LMMS Crashes when Clicking ZynAddSubFX

### ISSUE THREAD

**Issue by abhaskumarsinha** [LMMS/lmms#4191]
I'm not sure what's really happening to me. I've looked at previous Duplicates for this ticket but didn't get anything fixed. So, I'm posting my problem here -

**When I click on the Show GUI Option of the Plugin, the Plugin as well as LMMS Crashes,**

I'm running Windows 7 32bit as Administrator, so there's no problem with permissions.

Sorry no steps to reproduce because few days ago (don't remember the exact date), it was running fine, I've tested it, but problem started now.

So, how can I get if there is any conflict of settings/registry/files or what, so to fix LMMS Plugin.

When I run Plugin, outside LMMS, it says that an entry point is missing in Library file - QTCore4.dll

**Comment by musikBear** [comment]
@abhaskumarsinha  what lmms version?

**Comment by abhaskumarsinha** [comment]
@musikBear I'm using LMMS v1.1.3

**Comment by tresf** [comment]
> When I run Plugin, outside LMMS, it says that an entry point is missing in Library file - QTCore4.dll

Yeah, the Zyn we bundle won't run on it's own like that.  That's normal.

**Comment by tresf** [comment]
> @tresf didn't help

What didn't help?  Rebooting, purging and reinstalling LMMS from scratch?  Checking for Qt file conflicts?  Updating your sound drivers?  Removing the `.lmmsrc.xml` file or scanning your drive for errors?

Those steps are quite involved.  A blanket statement like "They didn't work" isn't how one gauges assistance from the development team.

> anything which crashes without a warning or error is considered as a bug.

Please don't make blanket statements like this.  This statement may be true for a web page or even an interpreted/JIT language like C# or Java, but C++ has a tendency to crash hard.  There are some measures that can be taken to mitigate the crash, but they involve a debug environment that we don't yet offer on Windows, and Zyn is on the more stable side of that fence anyhow.

Closing as invalid.  Please feel free to reopen if you find evidence that there's room for improvement in the codebase.
