### ISSUE TITLE
Saving condition of playback management button

### ISSUE THREAD

**Issue by NETMANSKY** [LMMS/lmms#4192]
Condition of playback management button in song editor is not saving in project. Every time after launch of project need to press this button to setup playback as it should.

**Comment by musikBear** [comment]
"playback management button"(?)
I bet you mean |<< / << / >> aka playhead-behaviour  
Then this is a sort of a *doublet* of 'mine' #3740

**Comment by NETMANSKY** [comment]
@musikBear Yes, I'm sure you're right, but plus its state is not saved in project after closing. It's not just uncomfortable but little horrorable. I didn't know how this button mean in English and wrote as it may be translated in Russian ;-) But now I know how it's naming: поведение при проигрывании :) 👍

**Comment by NETMANSKY** [comment]
But trouble is not until solved.

**Comment by NETMANSKY** [comment]
This problem has not been solved in RC7 so far.

**Comment by tresf** [comment]
Consolidated into #3740.
