### ISSUE TITLE
Small delay before "add effect" window shows up

### ISSUE THREAD

**Issue by tukkek** [LMMS/lmms#4200]
There is a 3 or 4 second delay between pressing "add effect" and the window actually showing up. I know it's a lesser issue but it's still annoying, especially when you're opening up that window a dozen times in a row to explore the effects when building an effect chain that "just sounds right". 

If anything, isn't it possible to keep the window open but invisible and just show it again when the button is pressed? That should be instantaneous, if no other performance improvement is possible.

I don't remember this happening at all with previous versions of LMMS.

I'm copying my comment from #3990 here with a bit more info:

> I had this issue the first time I opened the latest AppImage (1.2.0-rc5). It took forever for the effects screen to show up but after it did then pressing the "Add Effect" button worked a lot faster but noticeably delayed.
> 
> Just now I tried closing and reopening LMMS. The first time I click "add effect" it takes between 10 and 20 seconds to open (a lot less than the first time around) and later clicks take about 3 or 4 seconds.
> 
> I will create a new issue for the "small delay" even after you open it the first time because it's a lesser issue but still pretty annoying on its own (and hopefully fixable).

**Comment by tresf** [comment]
> I'm copying my comment from #3990 here with a bit more info:

Why not use that bug report?  What is different about this one?

**Comment by tukkek** [comment]
That one is about a long freeze, this one is about a small but probably very fixable delay.

**Comment by lukas-w** [comment]
This is almost certainly the same issue as #3990. You probably get a smaller delay the second time you click because of filesystem cache hits.
