### ISSUE TITLE
Cannot open .pat files

### ISSUE THREAD

**Issue by tukkek** [LMMS/lmms#4202]
All my pat files who had been working on prior versions of LMMS show not one but two error messages now:

> The file /path/to/file.pat seems to contain errors and therefore can't be loaded

I press OK and a new message pops up:

> /path/to/file.pat does not appear to be a valid pat file

These files were working fine on previous LMMS versions and I can't imagine all of them suddenly broke for no reason. My samples in other formats work fine. Please also  consider having only one error message appear for legitimately broken files.

**Comment by tukkek** [comment]
Apparently the following message is displayed on console when I tried loading a .pat file:

> qUncompress: Z_DATA_ERROR: Input data is corrupted
> at line 1 column "error occurred while parsing element"

**Comment by tresf** [comment]
Might be related to https://github.com/LMMS/lmms/pull/3510.  We broke some factory samples and I think the RC still has them wrong in a few plugins.  @tukkek if you can please provide the value you're using for your `LMMS HOME DIRECTORY` as well as the full path that the `gig` file was stored as in your project file.  If you're unsure, you can do `lmms-x.x.x.AppImage -d project_name.mmpz > project_name.mmp`.  That will expose the original project and give you the exact file paths.

**Comment by tukkek** [comment]
That command shows nothing related to a gig file that I could `grep` or find in a text editor. Opening the Settings causes LMMS to crash, I'll open up a new bug report for that.

**Comment by tukkek** [comment]
Opened it as #4203.

**Comment by tresf** [comment]
Apologies, I meant `.pat` file. Can you please share more information about these files? Does the path to the `.pat` file appear correctly?  Screenshots help.

**Comment by tukkek** [comment]
The output doesn't show a .pat file because the error occurs when I'm trying to add one as a sound source to one of my tracks, not when loading a project with an existing .pat source in it. If I recall correctly there wasn't any console output either when the error dialogs were shown.

I'll reiterate though that my .pat files were working on previous versions of LMMS and that none of my .pat files seem to be working anymore (though I haven't tested every single one of them manually - those I did failed to load though).

**Comment by tresf** [comment]
> I'm trying to add one as a sound source to one of my tracks, not when loading a project with an existing .pat source in it.

Ok, this wasn't clear in the original bug report.

> my .pat files were working on previous versions of LMMS and that none of my .pat files seem to be working anymore

Got it.  Yeah, I don't think anyone's tested PatMan in the AppImage, I know I haven't, I thought this was related to #3510 which I think is still occurring with SampleTrack, but that's another bug.   Anyway, do you have any `.pat` files that you can legally upload?  This should be pretty easy to reproduce and hopefully fix before the 1.2.0 release.

**Comment by tresf** [comment]
Nevermind uploading one... I found one. https://www.doomworld.com/idgames/music/dgguspat

The one that I tested with was `xylophon.pat` which plays just fine.  Can you unit-test with this same file?  If it plays back fine then we may have to dig deeper why yours would play in previous versions of LMMS but not now.

**Comment by tukkek** [comment]
I just tried several of the .pat files here and all of them presented the same error http://cdn-fastly.deb.debian.org/debian/pool/main/f/freepats/freepats_20060219.orig.tar.gz

It's a libre download from Debian arhives but you have to extract another file inside of it first.

**Comment by tresf** [comment]
Ok, I see what's happening.  The sidebar is trying to load it as some other type of tile (perhaps `.mmpz`).  If you add a new PatMan instrument it should work just fine.  Are you sure this is the first time you've dragged from the sidebar?  We can add drag-and-drop for `.pat` files, but I don't think we ever supported this.  I'll inspect the code to make sure.

**Comment by tukkek** [comment]
I can confirm this. Adding it "manually" instead of drag-and-dropping or double-clicking works fine. Never even occurred to me to try the long away around (as probably would happen to a large number of users too).

**Comment by tresf** [comment]
I can confirm this works in 1.1.3.  1.1.3 doesn't allow it to be dragged to a new track (you have to use the right-click context menu), but the preview and the context menu work exactly as expected.

**Comment by tukkek** [comment]
1.1.3 will allow you to add the .pat file with a double click too (but apparently only adds it to a drum/bass group).

**Comment by tresf** [comment]
Somehow this functionality got refactored out between 1.1 and 1.2.  Anway... it's back now.  You can test it out here: https://github.com/tresf/lmms/releases/download/v1.2.0-rc5/lmms-1.2.0-rc5.24-linux-x86_64.AppImage

![untitled](https://user-images.githubusercontent.com/6345473/36824732-d627eee0-1cd1-11e8-931e-a7296d02f512.gif)

On a side note, I notice that `.gig` files are missing from the logic as well.  We'll have to handle that separately.
