### ISSUE TITLE
Automation in BB is condenced to half of real size

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#4208]
win32 rc5 
I had difficulty with the headline -feel free to change to anything else
Look at this picture
![onebarautmakehalfbarbb](https://user-images.githubusercontent.com/6662066/36909376-12e134f0-1e3e-11e8-9ba5-f1c16010db19.JPG)
A whole bar of automation is only used in half of the bar in BB
This is the file
[BB_HalfPatternBug.zip](https://github.com/LMMS/lmms/files/1775869/BB_HalfPatternBug.zip)
I remember an old issue -Something with  expanding automation over **expanded** BB-tracks, but this new '½ pattern' is afaik new

**Comment by PhysSong** [comment]
Confirmed. This is a GUI bug which occurs when the length of a pattern is an integer multiple of one bar.

**Comment by PhysSong** [comment]
Found the wrong logic:
https://github.com/LMMS/lmms/blob/926b6542ae6804f346eb1a014ac16e71714b1e5f/src/core/AutomationPattern.cpp#L192
I guess this should be replaced with [`MidiTime::nextFullTact`](https://github.com/LMMS/lmms/blob/926b6542ae6804f346eb1a014ac16e71714b1e5f/src/core/midi/MidiTime.cpp#L102). I'll test it soon.
