### ISSUE TITLE
Screen Icon Sizes too small

### ISSUE THREAD

**Issue by EmeraldEelEntertainment** [LMMS/lmms#4210]
When I loads LMMS up the icons are ridiculously tiny and it makes it near impossible to use the software. My laptop is a **Lenovo ideapad Y700** and my screen resolution is **3840px X 2160px** (almost 4K).

**Comment by tresf** [comment]
What OS and version of LMMS?  If Windows + 1.1.3, try the 1.2.0 beta, we hacked in a workaround.

**Comment by EmeraldEelEntertainment** [comment]
I'm using the Windows version.

**Comment by tresf** [comment]
Please download the beta, we have a workaround for this problem.

https://lmms.io/download, scroll down to beta.

**Comment by EmeraldEelEntertainment** [comment]
I downloaded the beta and the screen looks so much better. Thank you!

**Comment by tresf** [comment]
👍
