### ISSUE TITLE
Searching in the sidebar shows the node that contains matching entries

### ISSUE THREAD

**Issue by raindropsfromsky** [LMMS/lmms#4214]
In the Sidebar, if I search for a string, LMMS shows the node that contains matching entries.

For example, in **My projects** node, there is **Editing_note_volumes.mmp** entry.
This is visible when I expand the node (by clicking on the triangle on its left).

Now I simulate a search, by entering "note" in the search field. 
LMMS starts shortening the nodes' list as I type.
Finally the **My projects** node remains.

But the mmp file is not displayed until I expand the node.
![image](https://user-images.githubusercontent.com/9047168/36964177-d2a9d0b4-207b-11e8-9a20-107f5ff319af.png)

![image](https://user-images.githubusercontent.com/9047168/36964191-de05c9b8-207b-11e8-81d5-bf26ed08dabb.png)

**Desired:** Please shortlist the matching items without the nodes structure.

---

**Edited by @tresf**
Feedback from @foolo (#4609) and also in alignment with @musikBear's feedback below:
> I still want to see the directories, but expanded.

Expanded folders need to be in this design.

**Comment by musikBear** [comment]
> But the mmp file is not displayed until I expand the node.

But does that not give you a clean and non-confusing **over-view**?
Compare it to a book.
Currently you are shown the *chapters* where a search-item can be found. Then YOU as the intelligence have the option to open the *right chapter* for your specific search. 
![tokenserchinnodes](https://user-images.githubusercontent.com/6662066/36978345-7e600466-2084-11e8-99d1-ffb80b5e3efc.JPG)
Imo the leftmost presents the cleanest view

**Comment by Spekular** [comment]
I agree with musikbear on this. The current display lets you search inside
a specific folder, which a display without folders wouldn't do. The option
to expand/collapse all directories might be a decent compromise if a
show/hide directory structure toggle can't be implemented.

**Comment by raindropsfromsky** [comment]
Yes, I suppose that's the correct way to look at this feature. Thanks!

**Comment by tresf** [comment]
This is valid, we've just been waiting for someone to open the bug.  https://github.com/LMMS/lmms/issues/760#issuecomment-71763480

The search bar is in need of some improvements to make it more useful to first time users.

**Comment by Anonymouqs** [comment]
@raindropsfromsky What if I want to look through a group of folders within a folder? I have open every folder in the Zyn presets folder in order to search for a preset that contains "brass". (I don't know which preset I'm looking for, I just want every preset with brass so I can experiment)

**Comment by tresf** [comment]
@Anonymouqs it's been reopened.  You're use-case is correct.  Thanks!

**Comment by musikBear** [comment]
So to clarify:
Atm 1.2.1 a sarch for *brass* will open this result:
![image](https://user-images.githubusercontent.com/6662066/82147203-681fb180-984e-11ea-865b-56d3a73955cb.png)
But in fact the prefered display would be 
![image](https://user-images.githubusercontent.com/6662066/82147259-d9f7fb00-984e-11ea-842e-a8bbe6247133.png)
So all folder are expanded to show all subfolders, but **not** the actual files! -Because that would be messy!
Is that the correct understanding of this request @tresf 
That is why you reopened -right?
I will look at it, but dont assign me yet

**Comment by tresf** [comment]
> So all folder are expanded to show all subfolders, but not the actual files! -Because that would be messy!
> Is that the correct understanding of this request @tresf

If you re-read the OP's request, we want the mess.  I've never used a search box (ever) that doesn't return the child matches of that request (or at least previews the matches in condensed form).  We want messy.  Perhaps at some point, we can cleanup the mess by condensing the parents.  It's the best we can offer until we bring in some form of tree condensing view.

**Comment by musikBear** [comment]
> we want the mess

..oh dear
well at least the request was better dissected and specified.
I may return to this, and give you a heads up for assigning, right now i am looking at 5404
Its assigned.

**Comment by MrTopom** [comment]
I am looking for a new issue to work on.

This one seems to be fun and this is one idea.

We could put an other button at the right of the refresh list button. This Toggle Button could allow to show/hide the files when doing the search. By default it is not activated and we want to activate "the mess" we can click on it and files will be automatically visible.

We could make files visible immediately or with a little timer and showing only folders while typing and after some mseconds display files if button is toggled.

**Comment by MrTopom** [comment]
First try : PR #6845
