### ISSUE TITLE
The time signature cannot be set easily to standard values (4/4, 3/4, 2/4, 6/8 etc.)

### ISSUE THREAD

**Issue by raindropsfromsky** [LMMS/lmms#4218]
If we double click on the numerator or denominator in **Time Signature**, LMMS shows an input field. However, the spinner in this field does not behave predictably.

For example, if we operate the spinners in the numerator and denominator, they show 1, 5, 9, 13, 17, 21, 25, 29 and 32. Thus the popular values like 4/4, 3/4, 2/4, and 6/8 are not offered. These have to be entered manually.

**Desired:** Please allow these values.

*Edited by @tresf, added screenshot*
![image](https://user-images.githubusercontent.com/6345473/36993128-f79836be-207a-11e8-8d16-f4a0567095e5.png)

**Comment by tresf** [comment]
@raindropsfromsky this is a likely mouse sensitivity bug.  They work just fine with both mouse wheel and click-drag here.

**Comment by raindropsfromsky** [comment]
No I actually clicked on the "up" and "down" spinners. Even then the field cycles through these odd figures, not change by 1.

I had not rolled the mousewheel on the input field when I reported this issue, but now I did that, and the results are the same.

BTW this is not a big problem, because if I hover the mouse on the numerator/denominator and roll the mousewheel, the value changes by 1.

In fact, you didn't have to give the double-click method at all.
But now that it is there, it should not be buggy.

**Comment by tresf** [comment]
> the spinner in this field does not behave predictably.

Apologies, the LEDs are considered "spinners" to the developers.  You're not talking about them, you're talking about the popup controls.  Yes, this is a bug, it's hardcoded to `4` for some reason.  <https://github.com/LMMS/lmms/blob/stable-1.2/src/gui/widgets/LcdSpinBox.cpp#L181>.  Good first issue.

![image](https://user-images.githubusercontent.com/6345473/36993128-f79836be-207a-11e8-8d16-f4a0567095e5.png)

**Comment by raindropsfromsky** [comment]
Thanks, @tresf !

BTW note also that if I hover my mouse over the input field to the left of these spinners and roll the mousewheel, I get the same odd series (1,5,9...). 

I am not sure whether this is also caused by the spinners code, or a separate issue.

**Comment by tresf** [comment]
It's the same code.  It's exactly `4`, every time.  Should be a quick fix.  Thanks for reporting.

**Comment by tresf** [comment]
> @tresf I'm a little bit confused. Your screen shot shows the Bpm line edit.

Because it's broken too.  This is a bug with LcdSpinBox.  Relevant code is linked in https://github.com/LMMS/lmms/issues/4218#issuecomment-370520818.

**Comment by BaraMGB** [comment]
Ah, okay. Thanks for clarification.

**Comment by tresf** [comment]
Ah, I see the confusion... yeah the bug title should really change to `LcdSpinBox` only allows increments of 4 from  `QInputDialog`.

**Comment by BaraMGB** [comment]
But a fast change to some common time signatures would be a nice thing.

**Comment by tresf** [comment]
> But a fast change to some common time signatures would be a nice thing.

I guess.  It's so quick to just scroll the wheel over these numbers, but if someone wants to code it.

**Comment by tresf** [comment]
Closed via 38b69a7.  The underlying model has a `step` value, which is what I've chosen to use.  The LCD's `QInputDialog` now allows incrementing in units of `1` (or whatever the underlying model uses) now, which matches the mouse-wheel behavior on the LCD itself.
