### ISSUE TITLE
Phrygian scale misspelled Phrygolydian

### ISSUE THREAD

**Issue by zonkmachine** [LMMS/lmms#4219]
Phrygian scale is misspelled Phrygolydian.
Reported here: https://lmms.io/forum/viewtopic.php?f=7&t=27073

Reference:
https://en.wikipedia.org/wiki/Mode_%28music%29#Modern_modes
The other modes seem fine. Ionian scale is named 'Major'.

**Comment by Anonymouqs** [comment]
Note: Accidentally clicked on jasp00 :P
