### ISSUE TITLE
Suggested feature: Rearrange the BB toolbar

### ISSUE THREAD

**Issue by raindropsfromsky** [LMMS/lmms#4222]
IMHO the BB toolbar has the following issues:
1. The toolbar starts with **play/stop** buttons. </br>Logically, their turn comes at the end, after composition.</br>So, they should be placed at the end of the toolbar.
2. The toolbar does not have a **"Add beats track"** button at all.</br> (I have raised a separate bug for that). </br>Here, I have suggested a button for this missing functionality.
3. The "Add BB" button is clubbed with "Add sample" and "add automation" buttons. </br> Functionally, a **BB set** is a parent for several percussion, sample and automation tracks.</br>Therefore the **Add BB** button should not be placed together with the other buttons.
4. The "Add BB" button looks as if it is meant to add a beat track. </br> I have proposed a new artwork for this button![image](https://user-images.githubusercontent.com/9047168/37018372-1d1e98dc-213a-11e8-8d1c-b2cf278cd093.png).</br> Note that the old button ![image](https://user-images.githubusercontent.com/9047168/37018279-d181b5d0-2139-11e8-85f9-4d0297b9d552.png) gets reassigned to **Add a beat track**.

The following figure shows a suggested revamped design:
![image](https://user-images.githubusercontent.com/9047168/37016992-cb7e17aa-2134-11e8-86f2-1f2cbd40c31d.png)
As shown above, the toolbar follows the workflow: First add a BB set, then select a BB set, then add beat/bassline/automation tracks, and finally play to check the result.  

If we feel that most projects will need only one BB set, then the **Add BB** button can be shifted to the right of the drop-down menu (it becomes secondary).
![image](https://user-images.githubusercontent.com/9047168/37017897-5207a176-2138-11e8-9268-36969bbf2b13.png)
Here, a larger buffer zone is provided between the **BB** button and the **Add tracks** group.

**Comment by tresf** [comment]
I've never been a fan of the beat/bassline dropdown.  I think the Song-Editor does a fine job of selecting it, it's more of a pattern comparator in my workflow.  Wherever the play buttons are, they should be consistent throughout all editor windows.  It is short-sighted to request a redesign on one without considering the inconsistencies it would bring.

**Comment by raindropsfromsky** [comment]
> I've never been a fan of the beat/bassline dropdown. 

You said it! I have often thought that let the Song Editor add the BB, and let the BB Editor only edit it.
That compartmentalizes the tasks between the editors, without a overlap like this.

> Wherever the play buttons are, they should be consistent throughout all editor windows.

I agree. In fact, I forgot to add at the end, that the same logic holds for the play buttons in the other editors also.

**Comment by musikBear** [comment]
njei.. play/ stop is perfectly logical in first position. Its so in any other daw i have seen -prominent large and front -anywittch its a bit nitpicking, and changes will confuse users -imo

**Comment by Spekular** [comment]
Agreed, play/pause/stop belongs on the left.

**Comment by tresf** [comment]
Ableton and FLStudio put these controls left of center, for the record.

**Comment by Umcaruje** [comment]
I don't agree with this proposal, Play and Pause should be on the left to be consistent with the rest of the software.

**Comment by raindropsfromsky** [comment]
I went through the [top DAWs for 2018](https://www.musicianonamission.com/best-daw-2016/), and in none of them is the **Play** button at extreme left of the GUI.
(I am not speaking of the toolbar, but the overall GUI, if we see the controls left-to-right).
Even in Hybrid DAws the play button is not the starting point.
![image](https://user-images.githubusercontent.com/9047168/37074570-8191ef62-21f3-11e8-9a74-4ba32ad43fbd.png)
![image](https://user-images.githubusercontent.com/9047168/37074579-8c88e7c2-21f3-11e8-8f43-64f26f931314.png)
![image](https://user-images.githubusercontent.com/9047168/37074588-9336fd0c-21f3-11e8-8a28-4545d4d60243.png)
![image](https://user-images.githubusercontent.com/9047168/37074596-9b5224f8-21f3-11e8-8aa9-7016a52f48fa.png)
![image](https://user-images.githubusercontent.com/9047168/37074602-a22d5e46-21f3-11e8-87a6-2b36a9559f9b.png)
![image](https://user-images.githubusercontent.com/9047168/37074611-acfe691e-21f3-11e8-9283-cb1453e68f09.png)
![image](https://user-images.githubusercontent.com/9047168/37074616-b3c144e2-21f3-11e8-9cec-79418a4f7bde.png)
![image](https://user-images.githubusercontent.com/9047168/37074619-b9f1a4e2-21f3-11e8-973c-d21bf19916e5.png)
![image](https://user-images.githubusercontent.com/9047168/37074628-c3c3603c-21f3-11e8-8695-f19d4330c5c4.png)

**Comment by raindropsfromsky** [comment]
BTW this part ![image](https://user-images.githubusercontent.com/9047168/37074725-3f34d110-21f4-11e8-8dd0-0e4a258a751f.png) is not consistent with the **Piano Roll Editor** which does not have a similar drop-down list (or **Add track** button).

I like the simplicity of Piano roll, where it pops up and edits one track selected from Song Editor.
The BB Editor should do the same.

**Comment by raindropsfromsky** [comment]
Another thing I noticed is that in all DAWs, the transport toolbar stands almost alone. 
In fact, there are no other buttons for other purposes. Probably they pop up only when needed.

In LMMS, all the toolbars are at the top of their respective windows.
I like this. But in other DAWs they are NOT at the top.

**Comment by tresf** [comment]
Better transport is already an open issue, documented here: https://github.com/LMMS/lmms/issues/1357

**Comment by raindropsfromsky** [comment]
@tresf 
> Better transport is already an open issue, documented here: #1357

Indeed. The centralized transport will work wonders.
As such I like the consistent location of toolbars in all seven windows of LMMS.

As my collage shows, toolbars are not conspicuous in most other DAWS.
Thus LMMS seems to be better than them in this particular aspect.

**Comment by Spekular** [comment]
In the tascam, the only thing to the left of play/pause/stop is rewind and
fast forward. We don't have these.

Logic, Studio One, Ableton, Cubase, Ardour, Acid Pro, and Fl Studio have
different window layouts to us, which makes a huge difference. If the
playback buttons were to be in the global toolbar on LMMS, it would make
sense to place them after things like file loading/saving. However, our
playback buttons all belong to the windows that they control.

In your Pro Tools example, you're pointing to the play button on some kind
of plugin, not the global play button. On top of that, the play button *is*
far left inside the window it belongs to. Nobody said that the playback
buttons need to sit to the far left of the screen, just that they should be
leftmost in the windows' toolbars.

If you look at these other DAWs, you should see that the things to the left
of the playback buttons are things like changing BPM & time signature,
saving/loading, or other global settings. There's a vast difference between
these layouts and ours.

**Comment by BaraMGB** [comment]
The lmms play button is on the left side since decades. It shouldn't  be moved.

If this enhancement request about removing the "b+b drop down"  the first comment should be rewritten. To long to read

**Comment by Spekular** [comment]
FWIW FL Studio has a similar dropdown in their Step Sequencer. If space is
a concern (which I don't think it should be*), the dropdown could be
changed to a button that opens a list (this is how FL seems to do it). If
anything I think it could be restyled, but I don't think it ought to be
removed. When I used BB tracks I made use of the dropdown constantly.

*Accounting for track labels & useably wide steps in the sequencer, the BB
editor can only get so narrow. I don't think the dropdown is the limiting
factor.

**Comment by tresf** [comment]
@raindropsfromsky this is a hugely unpopular idea and I feel the arguments in favor of keeping the button far outweigh the arguments to move them.

> The lmms play button is on the left side since decades. It shouldn't be moved.

Not in the MDI interface, no.  In single-window interface, yes.  

https://github.com/LMMS/lmms/issues/1911

I'm closing this as the drop-down isn't really harming anyone.  If someone wants to shorten it to a button-length for real-estate purpose, let's tackle that with a PR please.  These types of discussions are very [bikesheddy](https://en.wiktionary.org/wiki/bikeshedding).  We need to work towards larger, progressive ideas and this is not in that direction.  Closing as `won't-fix`

**Comment by gi0e5b06** [comment]
Actually, the 'add tracks' and 'play/stop' buttons should be removed and simply appear in the main toolbar. In fact, every button that appears in more than two subwindows should be moved in a toolbar of the main window. Especially with a centralized transport.

**Comment by tresf** [comment]
@gi0e5b06 yes, we've discussed this several times over in the above conversation.  Do you have something new to share?

**Comment by gi0e5b06** [comment]
@tresf This has not been discussed at all. I have nothing more to add.

**Comment by tresf** [comment]
> @tresf This has not been discussed at all. I have nothing more to add.

You are wrong.  We have discussed this.  Here are the quotes from above.

> @tresf said
> > Better transport is already an open issue, documented here: #1357
> > In single-window interface, yes: #1911

> @raindropsfromsky said:
> > in all DAWs, the transport toolbar stands almost alone. 
> > Indeed. The centralized transport will work wonders.

**Comment by gi0e5b06** [comment]
@tresf not related to transport or to single-window.. I'm talking about moving every commonly used widget to the main toolbar. Not much coding required.
