### ISSUE TITLE
When long sample track is inserted in BB Editor, it does not show timeline to scale

### ISSUE THREAD

**Issue by raindropsfromsky** [LMMS/lmms#4224]
When long sample track is inserted in BB Editor, it does not show timeline to scale.

As shown below, I inserted two sample tracks and inserted two songs of different lengths: 4:36m and 4:20m.
The BB Editor stretched all tracks to the same length (even when the songs are not of same duration).
![image](https://user-images.githubusercontent.com/9047168/37039683-115ba3e8-217e-11e8-9469-e2e98809b83e.png)
However, in reality, when I play, the steps are played in correct time, and after that only the songs play.

In another experiment, I added more steps. 
![image](https://user-images.githubusercontent.com/9047168/37039646-ff6bc8fc-217d-11e8-9048-71c2a715df3c.png)
The BB Editor again accommodates these steps to match the length of the songs.

In a third experiment, I cloned the steps. The steps get cloned, and the entire set is stretched.

To conclude, only the display is faulty (not true time), and needs to be corrected.
- Show the steps in correct (real) time, as set by the tempo and meter.
- Show the songs in correct time (no stretching).

**Comment by tresf** [comment]
This has been reported on several occasions but I can't find where.  Anyway, consolidated into #1471, thanks for reporting.

**Comment by Itreza2** [comment]
addressed by #8369
