### ISSUE TITLE
Playhead Retrigger in piano-roll, can be inaccurate after recording

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#4228]
OS  : winXP32 sp3
LMMS RC5

**Issue description:**
If notes are being moved during a recording, lmms will calculate the retrigger-point erroneously

**Recreate         :**
* New project, any instrument
* open piano-roll and start a recording. Dont press any keys yet
* as playhead passes over ~2 bar marker play notes over some 4 bars
* Still during recording, use ctrl+a to select all notes
* Still during recording use sh+left-arrow to move all notes 
* stop recording
* press play

**Expected           :**
The play-head should return to pos 0, when it meet the first bar-devider after last visual note

**Factual event/ bug**
Playhead continues to move past bar-divider, and will retrigger to pos 0 after it has passed the last note' last *recording* position.

**comment**
This is mostly just an observation, that w/could confuse a newbee..

**Comment by musikBear** [comment]
...no there was an next to invisible 1/192 not hiding way out - my bad (eyes) 🙈

**Comment by tresf** [comment]
> OS : winXP32 sp3

@musikBear Windows 7 is EOL is less than two years https://support.microsoft.com/en-us/help/4057281/windows-7-support-will-end-on-january-14-2020. 😆
