### ISSUE TITLE
Add to the docs how to get LMMS and submodules

### ISSUE THREAD

**Issue by JohannesLorenz** [LMMS/lmms#4229]
There are many ways that LMMS users clone their submodules

```
# 1
git clone --recursive <URL>
# 2
git clone --recurse-submodules <URL>
# 3
git clone <URL>
git submodule update --init --recursive
```

Notes and observations (with git 2.16.1):
* (1) and (2) behave exactly equally
* (1) is deprecated
* (1) and (3) did differ in only one way: the local config (.git/config)
  differs in the "activeness" of the submodules (see below)
* Adding worktrees is not affected

Difference between (1) (above) and (3) (below):

```
...
[submodule]
        active = .
[submodule "src/3rdparty/qt5-x11embed"]
        url = https://github.com/Lukas-W/qt5-x11embed.git
[submodule "src/3rdparty/rpmalloc/rpmalloc"]
        url = https://github.com/rampantpixels/rpmalloc.git
```

```
...
[submodule "src/3rdparty/qt5-x11embed"]
        active = true
        url = https://github.com/Lukas-W/qt5-x11embed.git
[submodule "src/3rdparty/rpmalloc/rpmalloc"]
        active = true
        url = https://github.com/rampantpixels/rpmalloc.git
```

Summary:
* We should write somewhere that (1) is the recommended way
* We should explain that (3) can be used, too, but that after the clone,
  you need to execute `git config submodule.active .`
* This could go to a CONTRIBUTING.md file (github suggests them) or into the
  wiki. I always find it hard to search through the wiki for the right article, whereas a
  CONTRIBUTING.md file is always easy to find (especially if you don't have a web browser).

**Comment by tresf** [comment]
@JohannesLorenz I don't like adding a redundant `CONTRIBUTING.md` because it's often outdated.  Instead I recommend we make a complete source tarball with every release per #4100.

In regards to the submodules, I'm working to get `cmake` to tackle this for us since #3957.  This should alleviate the end-user's struggles fetching the source.

The biggest problem I've seen with the submodules is the following:
1. Won't checkout a specific commit hash
   * Usually caused when upstream squashed the commits out of history
   * Or when commit is on non-default branch
   * Or using older `git` version
2. The command `git submodule update --recursive --init` marks the directories as dirty and `git commit -a` puts them into the changelog.

The only thing I'm not aware of is what you're talking with with this point... 

> `git config submodule.active .`

* What is this?
* If this is needed why has noone mentioned it on Discord or here on the tracker?
* Is there a similar command to fix the dirty submodules problem (reset them to the exact commit that they **should** be at)

**Comment by JohannesLorenz** [comment]
@tresf The "active" option/folder tells git that it should track the corresponding submodule (or, if it's a folder, all submodules below that folder). I think the "dirty" problems arise from using `git submodule update --init --recursive`, which does not mark all submodules as "active". Git then somehow does not see those submodules, forgets to commit them or something, resulting in dirty submodules. I think method 3, followed by setting the "active" folder, should elliminate all those problems.

Once the submodules got "dirty", however, I'm not sure if that can easily be repaired. It's all worth trying out though.

Summarizing, methods
* (1)
* (3) followed by the `git config submodule.active .`

seem to do exactly the same thing.

**Comment by JohannesLorenz** [comment]
Btw, #3957 seems to make submodules optional, do I get it right? That's a very cool idea. IMO It should call `git config submodule.active .` before the call to `git submodule update` in order to fix the activeness issues.

**Comment by tresf** [comment]
@JohannesLorenz sorry, the documentation in #3957 may be a bit unclear.  It's exactly the opposite.  It will fail `cmake` if a submodule cannot be fetched.  The omission is a feature that's documented incase we need to chain it into e.g. `-DWANT_SWH=Off`, etc so that the feature can disable the fetching.

With that patch (active on `master`) you can simply do... 

```bash
git clone https://github.com/lmms/lmms
cd lmms
mkdir build && cd build
cmake ..
```

... and `cmake` will fetch all of the submodules for us.  If there's something needing improvement in our process, we should place it there, it will automate it for 99.9% of use-cases.  It works well now, but I agree, something is incorrect with the `--init --recursive` behavior.

**Comment by JohannesLorenz** [comment]
How do you add a worktree with submodule.active? How to get around with errors like below?

```
$ git submodule update --init --recursive
error: Server does not allow request for unadvertised object <SHA>
Fetched in submodule path <PATH>, but it did not contain <SHA>. Direct fetching of that commit failed.
```

I'll write it down here (must go to the docs aswell), so no one else (including me) will lose time with this. You can replace remote with the remote name (e.g. upstream, origin, tresf) and branch with the branch name for the new worktree (e.g. stable-1.2, veal, ...).

If you have a damaged worktree like above, setting `submodule.active` won't help afterwards. You need to delete it:

```
cd master # or wherever your worktrees are located
rm -rf ../<branchname>
git worktree prune
```

The correct way to add your worktree is:

```
cd master # or wherever your worktrees are located
git config submodule.active .  # you *must* do this before adding the submodule
git worktree add ../branch remote/branch
cd ../branch
git checkout branch # avoid the detached HEAD, don't know why this must be done
git pull -u remote branch # pull updates
git submodule update --init --recursive
```

That's the least complex way to do it imo, but improvements are welcome.

**Comment by lukas-w** [comment]
I believe this is covered by our wiki: https://github.com/LMMS/lmms/wiki/Accessing-git-repository Please reopen if it isn't.

**Comment by JohannesLorenz** [comment]
Many of those instructions in this post help you fixing things after you did not use `git clone --recurse-submodules`. This is nowhere covered in mentioned wiki page.

**Comment by tresf** [comment]
First, `--recursive` is all I've used when cloning.  If it's expected to be supported, I'd recommend it as it's easier to type.

Second, I find it problematic that the behavior of `--recursive` isn't the same as `git clone <...> && git submodule update --init --recursive`.  I too find it extremely important that we have a way to grab the CURRENT submodule without it introducing some unauthorized commits into a PR.

Secondly, the branch switching is very problematic as it doesn't properly wipe those directories created by a recursive clone.  This means branches with different submodules are a nightmare to switch between (e.g. comparing `master` with `stable-1.2`).  We need to get this sorted and to that point, I agree with @JohannesLorenz.  I'm not sure if having this issue open is going to make that happen any sooner though. :/

**Comment by JohannesLorenz** [comment]
> Third, the branch switching is very problematic as it doesn't properly wipe those directories created by a recursive clone.

Does this fail after `git clone --recursive`, or in which situations?

Anyways, in case branches are very different it might be the best recommendation to use worktrees. They work, once set up correctly.

> I'm not sure if having this issue open is going to make that happen any sooner though. :/

I'd rather prefer noting it in the wiki. I could edit mentioned wiki page and let you review it @tresf , though not in the next days/weeks.

**Comment by tresf** [comment]
We haven't agreed on what to add though?

**Comment by JohannesLorenz** [comment]
>We haven't agreed on what to add though?

I'd say all guides mentioned above for the case that you cloned without `--recursive`, plus anything else you want to add.

**Comment by tresf** [comment]
But we have no proper solution.  Is there a way to mimic `--recursive` AFTER clone?  If not, what's the point?

**Comment by JohannesLorenz** [comment]
A `git config submodule.active` (like in the examples above), plus a `git submodule update --init --recursive` should be that way, if I get your question right.

**Comment by tresf** [comment]
```
git config submodule.active
```

I've never had to use this.  Do you know if it's required?

```
 git submodule update --init --recursive
```

This is what we do in our cmake script on `master` to make it less painful for newcomers.  We can add it to the docs.  For some reason though my branch always shows a submodule on a different commit, but this may be a nuance of older git versions.  Testing now on 2.19.2, I can't see any difference at a glance (e.g. `git status && git diff`).

Looking deeper into the config files, I do see a slight difference... I assume these are effectively the same?  Anyway... I can confirm the submodules point to the exact same commits.  Both are clean clones, one just used `update --init --recursive`.

```diff
-[submodule]
-	active = .
 [remote "origin"]
 	url = https://github.com/lmms/lmms
 	fetch = +refs/heads/*:refs/remotes/origin/*
@@ -14,6 +12,8 @@
 	remote = origin
 	merge = refs/heads/stable-1.2
 [submodule "src/3rdparty/qt5-x11embed"]
+	active = true
 	url = https://github.com/Lukas-W/qt5-x11embed.git
 [submodule "src/3rdparty/rpmalloc/rpmalloc"]
+	active = true
 	url = https://github.com/rampantpixels/rpmalloc.git
```

@JohannesLorenz where do you want this to be added? `git submodule update --init --recursive` should be adequate based on the above research.

That said, switching branches still sucks.  Not sure how far you want to go with this.  Our wiki isn't necessarily the place to teach `git` to someone. :)

**Comment by JohannesLorenz** [comment]
@tresf As written above `git config submodule.active` is required (otherwise you'll end up with inactive submodules, very ugly). It does exactly what your diff shows. Maybe this should be added to the CMake script as well.

> git submodule update --init --recursive should be adequate based on the above research.

I think it's not adequate, an additional `git config submodule.active` is required.

A git tutorial is unnecessary, but we should at least help users cloning their submodules right and fixing issues with non active submodules.

**Comment by tresf** [comment]
> you'll end up with inactive submodules

How?  I don't argue that inactive sub-modules can be ugly, I've never seen this command needed.  Can you help explain?   As my diff illustrates, they're activated.

**Comment by JohannesLorenz** [comment]
I think my view on this was wrong. Reading [the docs](https://git-scm.com/docs/gitsubmodules#_active_submodules) now:

```
A submodule is considered active,

if submodule.<name>.active is set to true

or

if the submodule’s path matches the pathspec in submodule.active

or

if submodule.<name>.url is set.
```

And `url` is always set for us. So methods (1) and (3) are effectively the same. I also never had problems with both methods in the last years, so adding this info anywhere seems wrong to me. Closing my own issue.

**Comment by tresf** [comment]
@JohannesLorenz thanks for following up on this, even if it's all these years later, it's nice to know. :)
