### ISSUE TITLE
Add a lightweight default GM SoundFontf as an Asset

### ISSUE THREAD

**Issue by Anonymouqs** [LMMS/lmms#4230]
Currently, there is no default Soundfont for LMMS, should we add one? And if so, which sf2 file would have a good balance of quality and file size?

There is a SoundFont called  TimGM6mb that is only 6mb, the equivalent of 2 mp3 files containing average Taylor Swift songs.

Examples of the file in use are:
* [80s Flashback in a Nutshell](https://www.youtube.com/watch?v=s1n0K6jqt_4)
* [Cannon in D Major](https://www.youtube.com/watch?v=6wnRaszeR7g
)

There is a list of numerous Creative Commons GM SoundFont files on [Musescore's Documentation](https://musescore.org/en/handbook/soundfonts-and-sfz-files).

**Comment by tresf** [comment]
@Anonymouqs sure, we'd be happy to ship a CC0 soundfont.  Please reopen this over at https://github.com/lmms/assets and close it here.  Cross-linking is advised.
