### ISSUE TITLE
In Piano Roll Editor, the last segment of the "Note detuning" curve is missing.

### ISSUE THREAD

**Issue by raindropsfromsky** [LMMS/lmms#4231]
In instruments like Sitar and Santoor, all notes are typically detuned (pitch-bent).
Thus its notation needs to be displayed accurately.

But LMMS does not show the the last segment of the "Note detuning" curve in Piano Roll Editor.

Compare the two cases below:

![image](https://user-images.githubusercontent.com/9047168/37217454-8c45fae2-23e3-11e8-80f4-e1636de9bb03.png)

![image](https://user-images.githubusercontent.com/9047168/37217472-a1e83e46-23e3-11e8-9cdf-c0ce7d19650a.png)

**Desired:** Show the curve till the end of the note.

**Comment by Spekular** [comment]
It's not a matter of the last segment. Any points outside the length of the
note are ignored.

**Comment by raindropsfromsky** [comment]
> Any points outside the length of the note are ignored.

True, but the stretch of the curve that lies within the "active" life of the note only is significant.
For us, that's the part that needs to be visible.

**Comment by zonkmachine** [comment]
I'm working on a fix. It may be enough to just omit [this test](https://github.com/LMMS/lmms/blob/e9b83378f9160ad4a61e13aa8698f9788aa69a95/src/gui/editors/PianoRoll.cpp#L892:L895).

**Comment by Mark-Agent003** [comment]
It may be better if it just cuts off the line at the end of the note.

**Comment by zonkmachine** [comment]
You need to think about the decay of the note which isn't showing. I think it's best to draw all of the pitch bend info.
