### ISSUE TITLE
Some BitInvader parameters should apply live adjustments

### ISSUE THREAD

**Issue by Kubek0212** [LMMS/lmms#4238]
Right now that knob doesn't apply live adjustments like 3xOsc does.
Adding this feature would help in making original automatitions.

It's more like idea, rather than bug report.

**Comment by Sawuare** [comment]
I think the wavetable should apply live adjustments, too.

**Comment by zonkmachine** [comment]
The live automation issues have been fixed. Some issues on stable-1.2 and the rest om master (1.3). The only thing that could be improved right now would be the waveform selector which doesn't make sense to automate in the current configuration. Automating changing wave in a wavetable is covered by issue https://github.com/LMMS/lmms/issues/5849.

Closing as fixed.
