### ISSUE TITLE
qt5-x11embed relies on missing cmake modules

### ISSUE THREAD

**Issue by ycollet** [LMMS/lmms#4247]
In the cmake file of qt5-x11embed, a find module is used but not found:

find_package(XCB REQUIRED COMPONENTS XCB ATOM KEYSYMS UTIL)

The Module path is set to:
${CMAKE_CURRENT_SOURCE_DIR}/3rdparty/ECM/find-modules

But this directory doesn't exists in the lmms master branch.
On Fedora, this module can be found on /usr/share/ECM ...

**Comment by tresf** [comment]
@ycollet looks like a duplicate of #4100, no?

**Comment by tresf** [comment]
Sorry, I'll be more specific... it's a [nested submodule](https://github.com/lukas-w/qt5-x11embed/tree/master/3rdparty) (more submodule hell, apologies, we're working to make this better!).  `ECM @ 6604694`

**Comment by lukas-w** [comment]
@ycollet I'll assume cloning submodules fixed this for you. Please reopen if needed.
