### ISSUE TITLE
LMMS 1.2-RC5 crashes during setup on macOS 10.11

### ISSUE THREAD

**Issue by mchorse** [LMMS/lmms#4251]
Hello there! 🙂 

I wanted to try out LMMS 1.2 on the website, but it's crashes during setup (i.e. it shows the splash screen, completes few steps and then crashes). I tried launching all RC's (RC2-5 and `1.1.9` one) in the releases on GitHub, and all of have the same exact issue. I also tried building it from source, and unfortunately it crashes on setup too (when the splash screen says *Initializing data structures*).

Here is a [crash report](https://pastebin.com/XMLSGaqx) which shows up after app's crash.

I really wish I could try out this build. Is there anything I can do to fix this issue (I have experience in programming, but not much with C/C++)?

Thank you for attention!

**Comment by tresf** [comment]
Does it still happen with libsoundio disabled?

Here's an installer: https://github.com/tresf/lmms/releases/download/v1.2.0-rc5/lmms-1.2.0-rc5.23-mac10.8.dmg

**Comment by mchorse** [comment]
How do I disable it? 🤔 

I tried running the on you just linked, and it also crashes, with the same exact stack trace.

**Comment by tresf** [comment]
> I tried running the on you just linked, and it also crashes, with the same exact stack trace.

Thanks for trying.  This is consistent with what @ejj28 reported on [https://lmms.io/chat](Discord).

> Is there anything I can do to fix this issue (I have experience in programming, but not much with C/C++)?

Sure, if you have XCode installed and you're  comfortable with Homebrew, you can compile with debug flags enabled and then use `lldb` to see where it's getting hung-up.

1. Install Homebrew and dependencies: https://github.com/LMMS/lmms/wiki/dependencies-macos#qt5
2. [Clone](https://github.com/LMMS/lmms/wiki/Compiling#clone-source-code) the source code:
   ```bash
   git clone --recurse-submodules -b stable-1.2 https://github.com/lmms/lmms
   ```
3. [Configure](https://github.com/LMMS/lmms/wiki/Compiling#cmake-quickstart) the build environment with debug flags:
   ```bash
   cd lmms
   mkdir build
   cd build
   # 1. WANT_QT5 Enables debug build
   # 2. CMAKE_BUILD_TYPE Sets up local install prefix
   # 3. CMAKE_INSTALL_PREFIX Tells cmake where to find qt5
   cmake .. -DWANT_QT5=True -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=../target/ -DCMAKE_PREFIX_PATH=$(brew --prefix qt5)
   ```
4. [Build](https://github.com/LMMS/lmms/wiki/Compiling#compiling) and reproduce crash.
   ```bash
   make -j4
   ../lmms
   ```

5.  Assuming you can reproduce the crash, [debug](https://github.com/LMMS/lmms/wiki/Compiling#debugging):
   ```bash
   lldb ../lmms
   # (type "run" when prompted)
   ```

**Comment by mchorse** [comment]
OMG... thanks! It's really weird, but when running LMMS with `lldb` it works perfectly fine! The new interface looks so much better and embedded ZynAddSubFX works too, great job! 🙂 

I guess it means that there is some problem in packaging stage. 🤔

**Comment by tresf** [comment]
> I guess it means that there is some problem in packaging stage. 🤔

Very likely.  The other report was against the 10.8 build as well, so I may need to change the packaging environment.  I have some other crashes in the 10.13 build which may be unrelated.  I'll see what I can do for the RC6 release.  Is it OK to ping you for testing?  Also, are you on Discord? https://lmms.io/chat

**Comment by tresf** [comment]
Also, if you want it in your Apps folder, do `make install` and copy the `LMMS.app` folder to Applications.

**Comment by mchorse** [comment]
> Is it OK to ping you for testing?

Yeah, it's totally cool. I'll be glad to test! 🙂  
I'm already present on LMMS' Discord. I'll ping you.

> Also, if you want it in your Apps folder, do make install and copy the LMMS.app folder to Applications.

As I stated in the original message, I already tried doing, and it also crashed 🙁 

> ... I also tried building it from source, and unfortunately it crashes on setup too...

**Comment by tresf** [comment]
> As I stated in the original message, I already tried doing, and it also crashed 🙁

Oh, so it ONLY crashes after it's been packaged?  That's very strange indeed.  We should still get some more details.  Can you post an updated backtrace using the debug build (just without `lldb`)

**Comment by mchorse** [comment]
Ohh... that's weird... now the `LMMS.app` file runs fine... 🙁 

I mean, it's good, but I don't understand why it works fine now. I was playing around with LMMS `1.1.3` before trying out `1.2`, so maybe there were some configuration files which were generated that made `1.2` crash. I'll investigate this issue further. Is there any other places where LMMS writes its configuration files? 🤔

**Comment by mchorse** [comment]
I tried removing `lmms` and `.lmmsrc.xml`, but that didn't allowed me to reproduce the crash... 🤔

**Comment by tresf** [comment]
If it's the same as #4099, then it is very sporadic for me.  Like 1 in 5 times.

**Comment by mchorse** [comment]
According to a crash in that issue, it doesn't look like the same issue.

**Comment by ejj28** [comment]
I'm compiling from source right now, I'll see if I get the same results.

**Comment by PhysSong** [comment]
@mchorse I'm not sure, but I suspect your CPU doesn't support some instruction sets as well as #4317. Could you run `sysctl -a | grep machdep.cpu` and post the result here?

**Comment by mchorse** [comment]
Yeah, there it is:

```
machdep.cpu.max_basic: 13
machdep.cpu.max_ext: 2147483656
machdep.cpu.vendor: GenuineIntel
machdep.cpu.brand_string: Intel(R) Core(TM)2 Duo CPU     L9400  @ 1.86GHz
machdep.cpu.family: 6
machdep.cpu.model: 23
machdep.cpu.extmodel: 1
machdep.cpu.extfamily: 0
machdep.cpu.stepping: 10
machdep.cpu.feature_bits: 290732854951541759
machdep.cpu.extfeature_bits: 4832888832
machdep.cpu.signature: 67194
machdep.cpu.brand: 0
machdep.cpu.features: FPU VME DE PSE TSC MSR PAE MCE CX8 APIC SEP MTRR PGE MCA CMOV PAT PSE36 CLFSH DS ACPI MMX FXSR SSE SSE2 SS HTT TM PBE SSE3 DTES64 MON DSCPL VMX SMX EST TM2 SSSE3 CX16 TPR PDCM SSE4.1 XSAVE
machdep.cpu.extfeatures: SYSCALL XD EM64T LAHF
machdep.cpu.logical_per_package: 2
machdep.cpu.cores_per_package: 2
machdep.cpu.microcode_version: 2571
machdep.cpu.processor_flag: 7
machdep.cpu.mwait.linesize_min: 64
machdep.cpu.mwait.linesize_max: 64
machdep.cpu.mwait.extensions: 3
machdep.cpu.mwait.sub_Cstates: 51520032
machdep.cpu.thermal.sensor: 1
machdep.cpu.thermal.dynamic_acceleration: 0
machdep.cpu.thermal.invariant_APIC_timer: 0
machdep.cpu.thermal.thresholds: 2
machdep.cpu.thermal.ACNT_MCNT: 1
machdep.cpu.thermal.core_power_limits: 0
machdep.cpu.thermal.fine_grain_clock_mod: 0
machdep.cpu.thermal.package_thermal_intr: 0
machdep.cpu.thermal.hardware_feedback: 1
machdep.cpu.thermal.energy_policy: 0
machdep.cpu.xsave.extended_state: 3 576 576 0
machdep.cpu.xsave.extended_state1: 0 0 0 0
machdep.cpu.arch_perf.version: 2
machdep.cpu.arch_perf.number: 2
machdep.cpu.arch_perf.width: 40
machdep.cpu.arch_perf.events_number: 7
machdep.cpu.arch_perf.events: 0
machdep.cpu.arch_perf.fixed_number: 3
machdep.cpu.arch_perf.fixed_width: 40
machdep.cpu.cache.linesize: 64
machdep.cpu.cache.L2_associativity: 24
machdep.cpu.cache.size: 6144
machdep.cpu.tlb.inst.small: 128
machdep.cpu.tlb.inst.large: 8
machdep.cpu.tlb.data.small: 16
machdep.cpu.tlb.data.small_level1: 256
machdep.cpu.tlb.data.large: 16
machdep.cpu.tlb.data.large_level1: 32
machdep.cpu.address_bits.physical: 36
machdep.cpu.address_bits.virtual: 48
machdep.cpu.core_count: 2
machdep.cpu.thread_count: 2
machdep.cpu.tsc_ccc.numerator: 0
machdep.cpu.tsc_ccc.denominator: 0
```

**Comment by PhysSong** [comment]
The backtrace looks very weird for me. Can you reproduce this issue with official RC6 release?

**Comment by PhysSong** [comment]
Looking into the crash report again, it seems like old Qt 4 from 1.1.3 wasn't removed properly while 1.2.0-RC.5 expects Qt 5.
Closing for now. If anyone experiences with deleting `/Application/LMMS.app` and reinstalling 1.2 or 1.3 alphas, please let us know.
