### ISSUE TITLE
1.2.0-rc5.17 problems when copy-pasting a pattern

### ISSUE THREAD

**Issue by acidavid** [LMMS/lmms#4259]
Issues when copying automation patterns: the pattern mode automatically switches to linear progression and if i set the level to 100% and copy it (on volume automation, not on mixer) it defaults to 200%
also:Id like to be able to reassign a automation pattern to another knob or vst or anything else without having to redo the pattern completely

**Comment by musikBear** [comment]
@acidavid is it similar to #3359 ?

**Comment by acidavid** [comment]
yes.i beleive my post might be a dupe.
