### ISSUE TITLE
Working directory gets reset when the path doesn't exist

### ISSUE THREAD

**Issue by PhysSong** [LMMS/lmms#4267]
I use a directory in my NTFS partition as LMMS working directory. Once I forgot to mount the partition and launch LMMS, the working directory resets without showing "Working directory" dialog.

This is a regression from #4211. `canonicalPath` function returns an empty string for non-existent paths and causes problem.
I think we can work around by checking for empty string, or use a function that doesn't return an empty string(`absolutePath` or [`QDir::cleanPath`](http://doc.qt.io/qt-5/qdir.html#cleanPath)) in such situations.

In Qt5, `QDir::cleanPath` has an additional functionalitiy. It always use `/` for separators.

**Edit**: `CleanPath` to `cleanPath`

**Comment by tresf** [comment]
CleanPath looks like a sane replacement.
