### ISSUE TITLE
(LMMS 1.2.0rc6) Changing the type of Mallets plays weird sounds

### ISSUE THREAD

**Issue by MrTeeXD** [LMMS/lmms#4269]
**LMMS Version:** LMMS 1.2.0rc5, Win64
**OS:** Windows 10
 
**Issue:** 
When changing the Mallet plugin sounds to Tuned Bar, Tibetan Bowl and Glass will play weird sounds

**Steps to reproduce:**
1: Replace Sound Files
2: Play correct sound and pitch when clicking on the plugin piano keys

The Mallet Plugin's Tibetan Bowl, Glass and Tuned Bar sounds should play the normal sounds and will not make any weird sounds

**Comment by musikBear** [comment]
doublet, but i cant find the orr. one

**Comment by Sawuare** [comment]
I can confirm that the `BandedGW` mallets: "Uniform Bar", "Tuned Bar", "Glass" and " Tibetan Bowl" don't sound like mallets or even perc instruments, while they should.

**Comment by tresf** [comment]
@MrTertius can you help us understand the regression of this bug?  Did this work normal in 1.1.3?

If it's a 1.2.0 regression, the first suspicious change is here, but it's just a guess... https://github.com/LMMS/lmms/commit/ed7d929b2c9887ba7b7e79d1d9b658c5fba1871e#diff-798267d1547adb6bff9642f1baa3f2d0, might be worth reverting and seeing if it helps.

**Comment by zonkmachine** [comment]
> If it's a 1.2.0 regression...

I don't think this is a regression. Mallets was originally merged in a somewhat unfinished state and some of the knobs/functions has since been implemented/fixed, mostly by me [here](https://github.com/LMMS/lmms/pull/2670). I couldn't do much at all with the `BandedWG` sounds however. If I remember this correctly the noises you get from switching between the various stk modules I think is rather because of the Tubular Bells when you switch back from the BandedWG sounds.

**Comment by PhysSong** [comment]
`BandedGW` sounds bad both in 1.2 and 1.1(when `Bowed` option is checked). They don't generate any outputs in 1.1 if `Bowed` option isn't checked.
I've looked into the source code of STK library and found that `BandedWG::setFrequency` resets internal band-pass filter and delay line. That seems to make odd outputs.

**Comment by MisterTeeXD** [comment]
Hello, this issue has not been fixed in RC6

**Comment by SecondFlight** [comment]
We are on feature freeze for 1.2.0 as we fix up a few more bugs for release. If someone does decide to fix this issue for 1.3 then they will close it when it is fixed.

**Comment by zonkmachine** [comment]
Fixed in https://github.com/LMMS/lmms/pull/5428

**Comment by MrTeeXD** [comment]
Awesome. Closing this as it has been fixed.
