### ISSUE TITLE
Piano roll, BB and Automation editors can't be opened (1.2-RC5)

### ISSUE THREAD

**Issue by mchorse** [LMMS/lmms#4270]
When I was playing around with LMMS, at some point, LMMS couldn't allowed me to open piano roll, BB or automation editors, while other panels such as song editor, effect chain, and others could be opened just fine.

When I tried to open any of those panels, it looked like the current panel unfocused, but the piano roll didn't appear.

Here is a dump file and the project file where it happens. [Project file](https://github.com/LMMS/lmms/files/1835130/test.mmpz.zip) and [a bug report](https://github.com/LMMS/lmms/files/1835132/test.mmp.zip) (exported with `-d`).

**Comment by tresf** [comment]
@mchorse thanks for the bug report.  Something fishy going on for sure... For now, you can edit the `mmp` file and replace `maximized="0"` with `maximized="1"` and them move things around until they're OK.  We'll look into the underlying bug.

**Comment by PhysSong** [comment]
@mchorse Do you remember which OS and which version of LMMS did you use when saving the file?

**Comment by mchorse** [comment]
@tresf will do that, thanks!

@PhysSong I used OS X 10.11 and 1.2-RC5, as stated in the title, but I don't remember which commit it was at that time. I can try looking up the day I cloned the repo in the history, if you need that information.

**Comment by mchorse** [comment]
@tresf after I edited the file, now it works, thanks! 🙂

**Comment by Sawuare** [comment]
The editors do open, but they have no height (it's set to 0 in the project file).
This happened to one of my projects before. IIRC, with rc.4 on Windows 10 Pro.
I will look into this.
