### ISSUE TITLE
Support Omni Midi?

### ISSUE THREAD

**Issue by Disar** [LMMS/lmms#4272]
For someone like me who only has a simple setup ( a simple 31-key midi controller ) it's cumbersome to continuously switch between midi inputs.  

With an omni midi option selecting an instrument should suffice to relay all midi input to the instrument. This should vastly improve workflow.
This should also extend to having input on controllers ( like modwheel ). Current workflow keeps me out of the "rhythm", so to speak.

**Comment by tresf** [comment]
Agreed, sending midi to the top-most instrument or piano roll would be nice indeed.

**Comment by fopor** [comment]
+1, have a simple 31-key midi controller
Would be nice if midi would go to piano roll

**Comment by breathar** [comment]
+1, only having one midi channel complicates my workflow

**Comment by fopor** [comment]
Oh, just noted that this feature is merged on master!

**Comment by DomClark** [comment]
Implemented in #5499.
