### ISSUE TITLE
lmms crashing frequently

### ISSUE THREAD

**Issue by bheadmaster** [LMMS/lmms#4274]
I'm on an Arch Linux system, using lmms with SDL backend.
Here's a backtrace:

https://pastebin.com/ffdDPsKX

**Comment by PhysSong** [comment]
What's your LMMS version?

**Comment by bheadmaster** [comment]
lmms 1.1.3-4

**Comment by PhysSong** [comment]
The backtrace says you've deleted a pattern with Ctrl+Z. It won't crash since 1.2.0-RC2.
@bheadmaster Please try our latest beta([1.2.0-RC5](https://github.com/LMMS/lmms/releases/tag/v1.2.0-rc5)) which is more stable than 1.1.3 version.

**Comment by lukas-w** [comment]
@bheadmaster Assuming 1.2.0-RC5 fixes this for you. If not, please reopen.
