### ISSUE TITLE
A3 behaves strange when recorded

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#4277]
OS  : winXP sp3
LMMS RC5

**Issue description:**
note A3 behaves strange when recorded. Slow notes will contain or cover fast notes.
![a3failinrecording](https://user-images.githubusercontent.com/6662066/38103522-ce890248-3386-11e8-978b-637529f62fb5.JPG)

The picture shows a 'similar' pattern recorded on 4 notes. Obs. A3
The reds are record error pos., the yellow are expected recorded pos.
**Recreate         :**
insert any default instrument and repeat that type of pattern during recording, and try with fi. C3 and A3

**Comment by Umcaruje** [comment]
How are you recording this, your computer keyboard or a midi keyboard?

**Comment by musikBear** [comment]
Oh sorry it pc-kb -The kb is fine, but just to be on the safe side, im taking one home and trying with that too

**Comment by PhysSong** [comment]
@musikBear Do you have any reliable method to reproduce? Does that always happen?

**Comment by musikBear** [comment]
@PhysSong I have since updated to RC5-6545, and i cant reproduce. I looked for a file, im 'sure'.. i saved one, but on the other hand, why then not include it first way.. 8|
May have been a fluke, else it will reappear.
Close it for now, but remember about it, i think?
