### ISSUE TITLE
ugh...vst blues

### ISSUE THREAD

**Issue by gypsy-g** [LMMS/lmms#4278]
Hi all...
Okay first first: MX Linux Debian (stretch 9.4)
Two days ago MX blew up forcing a reinstall of root. No problem. Before that all was GREAT with LMMS except that things tended to get slow the larger the project got.
Today I can't load vsts. At all. By now I've moved things around too much to have any idea where they were, except for knowing nothing had changed to begin with. Wine=yes. FL slayer (32) did was working just fine, in fact the ONLY fx or gen that did work. I dunno what to do at this point to get things going again. Help!
Thanks.

**Comment by lukas-w** [comment]
@gypsy-g We need more information to be able to help you. I recommend you reach out to the `#support` on our [Discord](https://lmms.io/chat/) first to resolve the issue more quickly and then report back here.

**Comment by musikBear** [comment]
@gypsy-g -or remove lmms completely, and dl : 
https://github.com/LMMS/lmms/releases/download/v1.2.0-rc5/lmms-1.2.0-rc5-linux-x86_64.AppImage
