### ISSUE TITLE
BarsTicks time display mode is off by 1 tick

### ISSUE THREAD

**Issue by Sawuare** [LMMS/lmms#4281]
Looks like the 1st tick is not being counted.

![BarsTicks](https://user-images.githubusercontent.com/25503477/38212279-d26b47bc-36c5-11e8-8698-b2b7edfd741d.png)
*0 Ticks instead of 1.*

**Comment by Sawuare** [comment]
To quote @zonkmachine on Discord:
> This is nothing from a recent commit. I backed some 900 commits and the behavior is still there.

**Comment by PhysSong** [comment]
Reproduced with `stable-1.2`, but seems like fixed in `master` in #3711.

**Comment by zonkmachine** [comment]
This seem indeed to have been fixed. Closing.
