### ISSUE TITLE
Misaligned Knob in localised Delay Effect

### ISSUE THREAD

**Issue by Sauerstoffdioxid** [LMMS/lmms#4285]
![grafik](https://user-images.githubusercontent.com/35171164/38457727-bc73ac10-3a94-11e8-97eb-3bcc3443b21e.png)

The delay knob of the German localisation ("VERZÖGERUNG") is misaligned, because the German term is much longer then the English one and doesn't fit into the "side-bar".

LMMS 1.2.0 RC5

**Comment by liushuyu** [comment]
>The delay knob of the German localisation ("VERZÖGERUNG") is misaligned, because the German term is much longer then the English one and doesn't fit into the "side-bar".

I don't know if German localization can have a shorter version of that, in the case of impossibility to make a shorter version of translation, we might want to make the UI respond to the variable text length.

**Comment by Sauerstoffdioxid** [comment]
As a German, I don't think the term can be abbreviated. However, since all other knobs use the English terms (well "rate" and German "Rate" are the same, so I don't know which is used here), one possibility would be to stick to the English terms, e.g. "Delay". Afterall the plugin itself is called Delay, too, so it shouldn't be confusing.

**Comment by zonkmachine** [comment]
Same issue in our native flanger. I'll fix this in https://github.com/LMMS/lmms/pull/4482
