### ISSUE TITLE
New DMG Background

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms#4289]
I'm opening a dedicated bug report to track the new DMG Background for LMMS 1.2.0.

This is our existing DMG background that we wish to change.
![image](https://user-images.githubusercontent.com/6345473/38463339-8e93445e-3ac6-11e8-82f8-58e6cd789077.png)

The file is located at [`cmake/apple/dmg_branding.png`](https://github.com/LMMS/lmms/blob/stable-1.2/cmake/apple/dmg_branding.png).

The configuration of the icon position and size is located  at [`cmake/apple/package_apple.json.in`](https://github.com/LMMS/lmms/blob/stable-1.2/cmake/apple/package_apple.json.in).

I will post some other software DMGs as reference points.

Related #1247

**Comment by tresf** [comment]
Reference points:

Google Chrome:
![image](https://user-images.githubusercontent.com/6345473/38463360-f9bb695a-3ac6-11e8-87af-e56fbce03da9.png)

Steam:
![image](https://user-images.githubusercontent.com/6345473/38463361-ff0480f4-3ac6-11e8-8256-1962981b7f71.png)

Minecraft:
![image](https://user-images.githubusercontent.com/6345473/38463362-09c3fcb8-3ac7-11e8-8406-e561735a73ca.png)

**Comment by GingkathFox** [comment]
If I can put a suggestion, maybe the drag and drop could be like a sample to the song editor? Just have a “samples sidebar”  with the LMMS logo, and the installation would be the “song editor”.

**Comment by lukas-w** [comment]
Has there been any response from @michaelizer? Should we close this or move it to 1.3.0?

**Comment by tresf** [comment]
> Has there been any response from @michaelizer?

No.

> Should we close this or move it to 1.3.0?

Hard to triage the creative stuff.  Probably bump it.  @Umcaruje wanted to replace the main icon, but that will update on the DMG automatically.  I reached out to @michaelizer on April 8th and conversation didn't really progress.  He was putting time towards finishing the 1.2.0 LMMS icon at that point but I think it died with his first proposals.  Now it's been almost 4 months without any progress.  Note, @StakeoutPunch was assigned to this first but it didn't come to fruition.  I think our current on was done by @Umcaruje may he wants to just do it himself?

**Comment by tresf** [comment]
Fortnite/Epic DMG:

<img width="653" alt="screen shot 2018-10-03 at 7 43 51 pm" src="https://user-images.githubusercontent.com/6345473/46445423-d6306700-c744-11e8-96ca-0af27f59b418.png">

**Comment by tresf** [comment]
Correct.

**Comment by zonkmachine** [comment]
I updated the issue as it could be interpreted as assigned. Maybe bump this on `#assets` on discord?

**Comment by tresf** [comment]
Perhaps but it takes some trial and error with node's `appdmg` utility and a Mac for testing.  Probably best left here for @umcaruje or someone similar to eventually tackle.  It doesn't been to be milestoned for 1.2.0.

**Comment by zonkmachine** [comment]
Yeah. I think we should bump it to a later point then.

**Comment by GingkathFox** [comment]
![screen shot 2019-01-13 at 9 02 19 pm](https://user-images.githubusercontent.com/33764485/51093976-c201fa00-1776-11e9-8373-66afd388a111.png)
Portion of TDR Nova dmg

**Comment by RebeccaDeField** [comment]
Here's my first concept for the updated DMG. Just using the plain logo from the splash didn't seem to communicate the concept of dragging the program into the folder so I made use of the mimetype icon. To create contrast against the green, I based the background off of the Epic games launcher which I quite like the look of. The arrows are notched out of the grid as well.

![DMG](https://user-images.githubusercontent.com/7960169/58983112-e5136180-878a-11e9-9d95-6c4214eadcb5.png)

Feedback?

**Comment by tresf** [comment]
Love it.  Inherits the theme without too much fuss.  Happy to test it out.

Note, macOS has gone dark-mode for many users so if we are to embrace that you may want to mock-up with white text as well.

I've noticed many apps just clear out the word "Applications" as a workaround.  Can accommodate that as well.

**Comment by RebeccaDeField** [comment]
> Note, macOS has gone dark-mode for many users so if we are to embrace that you may want to mock-up with white text as well.

Ah, thanks for the heads up. Tried a darker green to contrast white text but it didn't look good enough to post as an option. Clearing out the text might work although it does seem to leave it a bit blank (not sure if that is a problem).
![DMG](https://user-images.githubusercontent.com/7960169/58993507-94a7fe00-87a2-11e9-8f2e-b5afd7bcc743.png)

Would it be an acceptable solution to work the labels into the raster background? I mocked it up with more stylized text (in the LMMS logo font).
![DMG1](https://user-images.githubusercontent.com/7960169/58993556-b3a69000-87a2-11e9-8846-b3fe9beec647.png)

**Comment by tresf** [comment]
We could try it out if dark mode is undesirable.  Let me know if you have an image I can test with and then we can work from a PR.

**Comment by RebeccaDeField** [comment]
Sounds great. Link for the background [here](https://www.dropbox.com/s/oc4kw505i2ic86p/dmg_branding.png?dl=0). I think 52px from both sides should make the icons line up with the grid nicely. There should be an existing mimetype that we can replace the logo icon with, if you need me to track a specific .svg down then let me know. More info can be discussed on PR :+1:

**Comment by tresf** [comment]
PR opened #5013.  I'll need help with the icon size and spacing.  The pixel-perfect alignment with the grid can work for one icon but I'm not sure about the other.

**Comment by GingkathFox** [comment]
@tresf @RebeccaDeField AFAIK DMGs can't have a dark mode. 

"Dark Mode" DMG: 

![Screen Shot 2019-06-08 at 8 42 02 PM](https://user-images.githubusercontent.com/33764485/59153677-f3cd7300-8a2d-11e9-8f0f-dc06d135ff6c.png)

"Light Mode" DMG: 

![Screen Shot 2019-06-08 at 8 42 16 PM](https://user-images.githubusercontent.com/33764485/59153679-fdef7180-8a2d-11e9-921b-be456a0b9e51.png)

**Comment by tresf** [comment]
Thanks.  These points were corrected in https://github.com/LMMS/lmms/issues/5013.
