### ISSUE TITLE
 Small enhancement: toggle note-labels

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#429]
Some way to toggle all note-labels (c-d-e-f-g-a-b-c) on/of in pianoroll
I -know- that i should be able to 'see' what note .. but i just issent :p (sometimes)
But toggable labels should be possible -or ?
If its an overhead (costs cpu) then its not worth it (just have to do with the marker and clotter on screen then :p
Perhaps it could be on the 'mark a note' ? currently the marked note has slightly different collors, pehaps a small bright colorered label could be added?

**Comment by tresf** [comment]
This feature already exists.  If we want it on the keys/notes themselves, then we should create a bug report specifying that (or rewrite this one with a good mockup).

This is what we have today...  It is ugly, but it works.  I vote we close this bug out. :+1: :-1: 

![screen shot 2015-04-06 at 11 16 16 am](https://cloud.githubusercontent.com/assets/6345473/7006349/63bf173c-dc4e-11e4-9858-697619128f54.png)

**Comment by musikBear** [comment]
![paste](https://cloud.githubusercontent.com/assets/6662066/7022165/4b2010ce-dd29-11e4-9633-9b0870dcee62.png)
Optional in *settings*

**Comment by softrabbit** [comment]
Just added PR #1938 to make toggling this easier.

**Comment by musikBear** [comment]
> Just added PR #1938 to make toggling this easier.
definitely an improvement :+1: 
I think we should omit the 'sharps' from the current method, that would make the screen less clutched, and be 'kinder' to the eye .. alt least that is my feeling without having see it..

**Comment by Sti2nd** [comment]
> I think we should omit the 'sharps' from the current method

No

**Comment by Umcaruje** [comment]
Closed via #1938
