### ISSUE TITLE
How to you submit a song for possible addition to LMMS?

### ISSUE THREAD

**Issue by TheDude102** [LMMS/lmms#4295]
If you click demos it gives you some songs that people have made as an example? How do you get your song to be one of these?

**Comment by bcaccia** [comment]
From https://github.com/LMMS/assets

> Contributing Projects
> 
> Contributing projects is not yet available. Please contact us on #assets channel on Discord for more information.

**Comment by lukas-w** [comment]
@TheDude102 In case you didn't find it already, you can reach our Discord server using this link: https://lmms.io/chat/
