### ISSUE TITLE
LMMS supports buffersize of 32 samples, but GUI only goes to 64

### ISSUE THREAD

**Issue by JohannesLorenz** [LMMS/lmms#4305]
The ruler for the buffersize is in "Edit -> Settings -> General Settings". It should go down to 32, not 64. It should still be possible to set the old values.

As @tresf has already pointed out, this can be fixed in [src/gui/SetupDialog.cpp](https://github.com/LMMS/lmms/blob/7c71bc657c34b2722f247e4820000c5e46f4d05f/src/gui/SetupDialog.cpp#L180-L185).

A simple beginner issue, but not trivial.
Not urgent, as the settings can be adjusted with a text editor.

**Comment by amelenty** [comment]
hi, is it fine if I try to do this?

**Comment by zonkmachine** [comment]
@amelenty Absolutely! I don't think anyone is working on this at the moment so go ahead.

**Comment by amelenty** [comment]
@zonkmachine 

Got a question about implementation of this.

Please take a look at this function [setBufferSize()](https://github.com/LMMS/lmms/blob/7c71bc657c34b2722f247e4820000c5e46f4d05f/src/gui/SetupDialog.cpp#L1124-L1152) in the file you mentioned.

Basically each position _**x**_ on the slider corresponds to _**64x**_ buffersize option, so currently each selected option must be a multiple of 64. I'm not sure how to make 32 work.

My best guess now is to change slider ticks/range/etc for _**x**_ slider value to correspond to _**32x**_ buffersize and provide a workaround for 64+ buffersizes to be rounded to nearest 64 multiple (similar to rounding to 256 that occurs after 256 in the function I  mentioned earlier).

Will that be fine? Sorry if my question is dumb.

P.S. I'd also like to add some comments that explain what's going on there

**Comment by JohannesLorenz** [comment]
@amelenty Thanks for trying this issue.

I would use 32 as the general step size (which should allow 32 as a minimum?). A buffer size of 64+32 should be acceptable, too.

On the other side, for cleaning up, I would limit the range to 4096:
* I experienced crashes with zyn with a buffer size > 4096
* Honestly, who uses such large buffer sizes? :smile:

**Comment by Sawuare** [comment]
> On the other side, for cleaning up, I would limit the range to 4096
> - I experienced crashes with zyn with a buffer size > 4096
> - Honestly, who uses such large buffer sizes? 😄

I agree, but I think we should limit it to 2048. That's sufficient, isn't it? And most DAWs have that as the limit. Check this small [poll](https://www.strawpoll.me/15634073/r) that I created on our Discord.

**Comment by JohannesLorenz** [comment]
@Sawuare Doesn't this poll say that 40% of users use a buffer size > 2048?

**Comment by Sawuare** [comment]
@JohannesLorenz It does, but I doubt they need to.

**Comment by amelenty** [comment]
I found some info on buffer size on [this page](https://lmms.io/documentation/Tuning_LMMS-installation#Buffer_size).

Apparently. small buffer size (up to 256) is good for recording and making real-time changes to tracks, while large buffer sizes are good for lots of non-realtime processing.

I honestly have no idea about how high the upper limit should be.

**Comment by JohannesLorenz** [comment]
@amelenty We're sorry, but someone else already committed a fix meanwhile: #4336 . Thanks for trying, anyways :1st_place_medal:

**Comment by DouglasDGI** [comment]
I'm assuming the merge of #4336 resolves this issue.  I'll close this now, let me know if it's a mistake.
