### ISSUE TITLE
VST Issue: TX16Wx causes complete UI lockup when attempting to launch file picker

### ISSUE THREAD

**Issue by SecondFlight** [LMMS/lmms#4306]
This is an issue with [TX16Wx](https://www.tx16wx.com/). 

Steps to reproduce:
![image](https://user-images.githubusercontent.com/6700184/39079347-5a6615ec-44e6-11e8-8723-30ba5c283f38.png)
![image](https://user-images.githubusercontent.com/6700184/39079352-7dcdeab4-44e6-11e8-9c15-05ad8ff178e9.png)

At this point it will lock up. The CPU meter is still active, so it appears to not be a crash or a freeze.

I did a bit of digging, this is what is supposed to come up when you use that option:
![image](https://user-images.githubusercontent.com/6700184/39079370-24f5a764-44e7-11e8-894a-9e95d019cd5d.png)

**Comment by PhysSong** [comment]
Reproduced. I don't know it will help investigating the issue, but here's a backtrace on Linux:
https://gist.github.com/PhysSong/ea5ca97884747d62ff569517b8ac0633#file-backtrace_tx16wx-txt
It seems like two threads try to open a file dialog.

Tagging @DomClark.

**Comment by justnope** [comment]
In RemoteVstPlugin.cpp if you put in the function main(): CoInitialize(nullptr) and at the end CoUninitialize(); it works.
Maybe someone who has a lot of vsts should test if this doesn't break anything else.

**Comment by SecondFlight** [comment]
I can do that, though I'm not sure what kinds of things to test. I wouldn't say I have a *lot* of vsts, but I have some commercial and quite a few free ones. It might be a bit before I can do this, since I won't be near my main machine for about another week. If you have a branch with this change, that would help a lot.

**Comment by musikBear** [comment]
FYI TX16vx -i have that on the *win-no-go list*. It does not preserve settings. 
Not tested on linux
(In fact, so far, no tested *sampler*, does work in windows

**Comment by justnope** [comment]
@musikBear thanks for the info. Is win-no-go list an actual list and if so where can I find it?

It's still an issue that needed to be fixed. If only for the reason that someone doesn't lose their recent changes because they opened a VST and the program hangs/crashed.

**Comment by SecondFlight** [comment]
Well, then that's a separate issue. Not sure what that adds to this bug report.
