### ISSUE TITLE
Improved Vertical Zoom in Automation Editor

### ISSUE THREAD

**Issue by Spekular** [LMMS/lmms#4313]
Currently, the zoom levels in the automation editor are based on some seemingly arbitrary range being 100%. I can't think of any good reasoning for this, and it also means some patterns can't be zoomed in on further than "auto".

I propose that all zoom levels in the automation editor behave as auto does, but with a multiplier. 100% displays the whole vertical range, 200% is twice as zoomed in, and so on. Unless there's a good use case for zooming displaying empty space in half the automation editor (or more), the new list of zoom levels would only include 100% and up.

1x, 2x, 4x, 8x, and 16x might also be better than 100%, 200%, 400%, 800%, and 1600% IMO, since the zeroes aren't significant. Having removed three levels (auto, 25%, 50%) and narrowed them, 32x, 64x, and 128x could be added without growing the drop-down in any direction, or it could be reduced in size.

EDIT: Updated description.

**Comment by musikBear** [comment]
> based on 100% zoom being fit-to-screen

Emediately i think 'spans from CRT Monitor to 4K+' Wont that be a problem?

**Comment by Spekular** [comment]
@musikBear No, not at all in this case. "Auto" is already the default and works fine independent of any resolution or DPI scaling. I've tried to improve the description. "Fit-to-screen" was the wrong wording, it's more like "fit-to-editor-window", but that's quite a mouthful.

**Comment by tresf** [comment]
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.
