### ISSUE TITLE
Add warning when loading newer file?

### ISSUE THREAD

**Issue by softrabbit** [LMMS/lmms#432]
AFAIK there is no warning of any kind when opening a project saved by a possibly incompatible newer version of LMMS, maybe there should be one? Something like "The project is saved in a newer format, some features may not be available". 

But as of now, only the LMMS version is included in the project, and a file from a newer version of LMMS with no changes to the save format should not show a warning. So, to avoid unnecessary warnings project file format versioning would be needed.

**Comment by softrabbit** [comment]
@Spekular, save an .mmp and edit the version number to simulate newer versions?

**Comment by Spekular** [comment]
@softrabbit I was going to but I can't remember how mmpz files are
compressed. Opening it in gedit gives me a bunch of garbage.

**Comment by Umcaruje** [comment]
>@softrabbit I was going to but I can't remember how mmpz files are
compressed.

This should be helpful: http://linux-multimedia-studio-lmms.996328.n3.nabble.com/is-it-possible-to-decompress-an-mmpz-file-without-lmms-dump-td3491.html

But you can open LMMS, click save as and instead of `filename.mmpz` edit it so it's `filename.mmp` That will give you an uncompressed file that you can edit.

**Comment by tresf** [comment]
... or change the version info in `CMakeLists.txt`,  compile, save,  change version info back.

**Comment by tresf** [comment]
Link to @Spekular's PR:  #1667 

@Spekular thanks for your work on this.... 

Here are some project versions in MMPZ format that I created by bumping the `CMakeLists.txt` in case you want to test more...

 * [`project_version_1.1.9.mmpz`](https://drive.google.com/file/d/0B4PpvIwHd1U0ckh4TXE3ZVNkN00/view?usp=sharing)
 * [`project_version_1.9.0.mmpz`](https://drive.google.com/file/d/0B4PpvIwHd1U0Z3ZydHpxd0xweGc/view?usp=sharing)
 * [`project_version_2.1.0.mmpz`](https://drive.google.com/file/d/0B4PpvIwHd1U0YVZ1aGZYMld0cE0/view?usp=sharing)

**Comment by tresf** [comment]
Closed via #1667
