### ISSUE TITLE
lmms.io: Upload file error

### ISSUE THREAD

**Issue by davidhedlund** [LMMS/lmms#4322]
![screenshot from 2018-04-25 07 16 51](https://user-images.githubusercontent.com/6416073/39227408-b853fdd4-4858-11e8-9e27-cb2615a24388.png)

I got the same error (but with other ID codes in the square brackets) when I tried to upload a file again.

**Comment by lukas-w** [comment]
Let's track this in `LMMS/lmms.io`: https://github.com/LMMS/lmms.io/issues/new

**Comment by davidhedlund** [comment]
https://github.com/LMMS/lmms.io/issues/261

**Comment by davidhedlund** [comment]
@lukas-w Thanks.
