### ISSUE TITLE
Default VeSTige File?

### ISSUE THREAD

**Issue by ahogen** [LMMS/lmms#434]
So, we have an option to set a default SF2 file. Could we get another option to have a default '.dll' for the VST player VeSTige? That would be pretty handy if there's one that you happen to use a lot, you could set is as the default one.
![capture](https://f.cloud.github.com/assets/6827790/2401500/efac6ca6-aa16-11e3-8a7d-2ccbec78f668.PNG)

**Comment by Wallacoloo** [comment]
I think what would be better than a default VST plugin is if VSTs could be displayed in the plugin browser and then you just drag them into the song editor like any other plugin & it opens in Vestige.

**Comment by musikBear** [comment]
ehh.. you mean 'Stars' in sidebar ?? -eg presets, not plugins ??  
thats totally possible now
I have saved several VSTs **as lmms-presets**, they do show up in preset browser, and loads perfectly **if** you use the context menu choose *"Send to Active Instrument Track"*  **not** drag, because you will create an orphan preview, if left clicked!

**Comment by Wallacoloo** [comment]
@musikBear I meant the "Instrument Plugins". As an end user, it would be ideal if LV2 + native + VST plugins were all treated the same in the UI, as functionally, they're all instruments.

It's nice to know about that preset trick though.

**Comment by Sti2nd** [comment]
That would be really nice Wallacoloo! Possibly differ between VST instruments and the native, but could certainly be useful

**Comment by tresf** [comment]
> I have saved several VSTs as lmms-presets, they do show up in preset browser, and loads perfectly if you use the context menu choose "Send to Active....." / "Open in new..." not drag, because you will create an orphan preview, if left clicked!
(the need for an empty vst-instrument was fixed in 1.0, afaik)

Please open a bug report if something is broken.

**Comment by tresf** [comment]
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.
