### ISSUE TITLE
Arpeggiator sometimes trigger one note too many

### ISSUE THREAD

**Issue by zonkmachine** [LMMS/lmms#4342]
_As reported on our Discord support channel._
Test project by Discord member `Half-Gray/7E7E7E`
[bass_test.mmp.zip](https://github.com/LMMS/lmms/files/1977065/bass_test.mmp.zip)

The arpeggiator sometimes triggers one arpnote to many at the end of a note with some settings.
Try turning up sustain a bit to trigger it.

The issue is there already in lmms-1.0.3 but not as obvious. In the test project you'll see a spike in the audio (mixer LEDs) when switching to a new held note. This goes away if you turn the `Sustain` and `Release` down to zero. The latest change happened in 67e93710d25a1e12e2c78fb1459d82e6d9bca42a where the glitch becomes more prominent.

_Edit: Superfluous bisect report moved to gist:
https://gist.github.com/zonkmachine/40e7000c2f93c68f0c55de2693ce27b0_

**Comment by PhysSong** [comment]
> This goes away if you turn the `Sustain` and `Release` down to zero.

https://github.com/LMMS/lmms/blob/5d90aecac90c16e9a4ec0b0450539cbe17ae7f6a/src/core/InstrumentFunctions.cpp#L344-L350
It looks like the logic uses (note length + release frames) instead of the real length. I think there's no reason to check release frames here.

**Comment by PhysSong** [comment]
Seems like LMMS plays arpeggio for released note and multiply release envelope value to new notes' volume. I don't know why/if we should...

https://github.com/LMMS/lmms/blob/5d90aecac90c16e9a4ec0b0450539cbe17ae7f6a/src/core/InstrumentFunctions.cpp#L505-L508

**Comment by zonkmachine** [comment]
Personally I haven't seen this problem a lot and thought that it had been solved simply because I've grown into the habit of using the same staccato like envelope with all of my arpeggios that wouldn't trigger the issue.


> It looks like the logic uses (note length + release frames) instead of the real length. I think there's no reason to check release frames here.

Yes. Just changing

```
( _n->isReleased() && _n->releaseFramesDone() >= _n->actualReleaseFramesToDo() ) ) 
```
to
```
( _n->isReleased() ) ) 
```
seem to fix this.

**Comment by zonkmachine** [comment]
https://github.com/LMMS/lmms/blob/5d90aecac90c16e9a4ec0b0450539cbe17ae7f6a/src/core/InstrumentFunctions.cpp#L505-L508

Right, you've got good eyes. This decay is for the releaseFrames (post above) giving a sort of pseudo delay end to an arpeggio with a long decay. I think it should just be removed along with the other change above (which makes it never execute anyway).
