### ISSUE TITLE
"Sync VST Plugins to host playback" setting not working

### ISSUE THREAD

**Issue by EtornaZ** [LMMS/lmms#4351]
A new user account on my computer was created, and when I went into the settings in LMMS on the new account and selected the "Sync VST" setting and restarted LMMS, my VST plugins did not sync. I've tried to repeatedly turn the setting on and off, but that didn't work. This setting works on my other account on the computer, so I don't know if I need to do something else in this case.

If this helps, the new user account and another older user account on the computer share my LMMS projects through the Public user. I'm on a Windows 10 laptop, 64bit and using an experimental LMMS version that has better VST support (rc5.17)

Thanks! :)

**Comment by EtornaZ** [comment]
I am fairly certain they're both one installation. How do I know if it's two? Does that mean I've installed it twice?
And also, where is the .lmmsrc.xml file located?

**Comment by musikBear** [comment]
@EtornaZ  > where is the .lmmsrc.xml file located?

https://lmms.io/wiki/index.php?title=LMMS_Settings#Problems_with_Settings
But two different versions of lmms on the same pc, will lead to weirdness, -except YOU add one more complication: two *accounts* 
You do mean TWO different windows-**accounts** (active-directory-accounts) right(?)
Must admit i have no idea if two accounts also co-use the dot-file

**Comment by EtornaZ** [comment]
I used the command prompt command to move the lmms file, and it disconnected all of the links I had set up in my LMMS, but I put the folder directories that I use back into the LMMS settings, turned on the VST Sync and now it works, somehow.  
And yes, I meant two different windows accounts.

**Comment by eagles051387** [comment]
Hi Guys,

From working with AD users each user has their own profile so there is
no cross sharing between user profiles. if the .lmmsrc.xml is on user A
user B will not work with that file of user A but it will have its on in
that users profile.

**Comment by franny23dmt** [comment]
what does "Sync VST" setting do?  it never worked for me, projects wouldnt load with it on, but VSTs seemed well synced with LMMS?  I leave it off

**Comment by tresf** [comment]
Fixed in https://github.com/LMMS/lmms/pull/4540.
