### ISSUE TITLE
[Feature Request] Piano Roll Chord Hot Key

### ISSUE THREAD

**Issue by BowB4YourSensei** [LMMS/lmms#4361]
The chord feature in the Piano Roll is very handy for quickly making chords. However it takes me out of focus to move over and select a different chord pattern. Is it possible to add a hot key action to this? Something like Ctrl+Alt+Scroll Wheel and/or Ctrl+Alt+Up/Down arrow?

Forgive me if this has been asked before.

**Comment by Jousboxx** [comment]
This is a feature that is in FL studio (Alt + Right-click) and it's one of the main things I miss having when I switch to LMMS. Doesn't seem that complicated, so I'll try to make it my first contribution to the LMMS codebase.

**Comment by tresf** [comment]
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.
