### ISSUE TITLE
Vestige Cuts Off Part of GUI After New Windows Update

### ISSUE THREAD

**Issue by Handlepower** [LMMS/lmms#4365]
After the latest Windows update which I installed yesterday, Vestige displays the VST GUI off center, and the left side is not displayed on the window. I can only interact with the part that is showing. Screenshots below. 

<img width="960" alt="arminator ss" src="https://user-images.githubusercontent.com/39383113/40193761-1524fec6-59bd-11e8-939d-6cb5c39ff425.png">
<img width="960" alt="oatmeal ss" src="https://user-images.githubusercontent.com/39383113/40193762-153f3e62-59bd-11e8-9363-8cb2861d5d18.png">

**Comment by SecondFlight** [comment]
Tagging @DomClark.

**Comment by SecondFlight** [comment]
@Handlepower That's not the latest version, and a lot of VST issues are fixed in the [current release candidate](https://lmms.io/download/#windows). Could you please download that and let us know if the issue still occurs?

**Comment by musikBear** [comment]
> That's not the latest version

He is talking about a **win10** latest update, and that winUpdate has given  issues for others using 1.1.3. They cant use Vestige anymore..
I recommended RC5x64, and hope he gets back with info.
Have any devs installed this 'latest' (?) win10x64 update?
Afaik, it should be 2 or 3 days ago
