### ISSUE TITLE
Equalizer: The visualizer takes up most of the processing time of the plugin, regardless of whether or not the plugin is open

### ISSUE THREAD

**Issue by SecondFlight** [LMMS/lmms#4389]
Tested on my current working branch (master from a week ago) with debugging symbols.

Steps to reproduce:
1) Add equalizers to the master channel until you see a significant cpu drop when you play a note.
2) Disable visualizers on all equalizers
3) Play a note, notice that the CPU is significantly lower.

With visualizers enabled:
![image](https://user-images.githubusercontent.com/6700184/40879127-4781767a-6669-11e8-9812-6db40721f64f.png)

Without visualizers enabled:
![image](https://user-images.githubusercontent.com/6700184/40879130-50641c8e-6669-11e8-88a9-b657f9a44816.png)

**Comment by PhysSong** [comment]
Currently EQ uses `EqSpectrumView::paintEvent` to enable/disable analyzing, but the event function won't be called if the window is closed.
I think it should use the visibility of `EqControlsDialog`. I will fix this.

**Comment by curlymorphic** [comment]
I will correct this now.

**Comment by SecondFlight** [comment]
Fixed via the PR above.
