### ISSUE TITLE
  Incomplete Export to .wav or .ogg

### ISSUE THREAD

**Issue by Christ0phe** [LMMS/lmms#440]
Hello,
I have found a rather strange behavior of LMMS: if I import a midi file into LMMS that contains several time signatures changes (2/4 to 4/4 and vice-versa for instance) it is played back correctly in LMMS but the Export to wav or ogg formats will stop before it reaches the end of the score. I have attached a very light example that depicts the issue. I have tried a lot of the settings (bitrate, depth, sample rate, interpolation). Same problem with the Export tracks function.
Is there a workaround to this? Is it really a bug in LMMS?
Here is a link to the article that includes very simple files to illustrate this problem: https://sourceforge.net/apps/phpbb/lmms/viewtopic.php?f=7&t=1239 
Thanks
Christophe

**Comment by utkorose** [comment]
use program for recording audio from system. Play and record your track/
