### ISSUE TITLE
Request for full downloadable source archive as part of the github release

### ISSUE THREAD

**Issue by sthen** [LMMS/lmms#4400]
Hello, the "source code (.tar.gz)" links on the github release page (https://github.com/LMMS/lmms/releases) is generated on-the-fly by github using git-archive, so it provides an incomplete download for LMMS (no submodules).

Would it be possible to create your own tar file and upload to add to releases (in the same way that you provide binaries i.e. as release assets) please? This would assist OS packagers, otherwise we'd need to make our own git checkout and generate/host a tarball ourselves.

Thank you!

**Comment by PhysSong** [comment]
I think this is a duplicate of #4100.

**Comment by sthen** [comment]
You are correct, my search didn't find that issue, it's good to know that it's already on the radar. Since this is a dup of an older issue I'll close this one to keep your tracker tidy. Thank you!
