### ISSUE TITLE
Piano Roll plays previous paused pattern instead of current pattern

### ISSUE THREAD

**Issue by EtornaZ** [LMMS/lmms#4410]
I'm on version RC6 of LMMS, with a Windows 10 64Bit computer.

When a box of notes is selected, played and then paused, and a new box of notes is selected and played, the old box of notes plays instead of the new box of notes. If you press the stop button and then press play, the new box of notes will play as intended.

**Comment by GingkathFox** [comment]
I think he means chord groups @SecondFlight 
play part of a chord, pause, skip ahead to second chord, error happens? @EtornaZ

**Comment by EtornaZ** [comment]
I'm sorry, I wasn't very clear at all. Here are some screenshots to hopefully clear the confusion up.
![image](https://user-images.githubusercontent.com/33297131/41160484-e0adc4f0-6afd-11e8-864b-8a7463cc7001.png)
I have a selection of notes in the Piano Roll above. I play them, and then pause the notes.
![image](https://user-images.githubusercontent.com/33297131/41160631-50327686-6afe-11e8-9227-7eaafff83101.png)
I now have a new set of notes selected above, but when I press play, the old selection of notes plays instead of the new selection. If I press stop and then replay, the new notes will play just fine.

**Comment by GingkathFox** [comment]
_sneak peek at new track? lol_
Aight, that helps!

**Comment by SecondFlight** [comment]
Thanks for the screenshots! So just to confirm, when you say "note selection" you're talking about patterns?

**Comment by EtornaZ** [comment]
Yes. I didn't know the correct name for them until now, heh heh.

**Comment by SecondFlight** [comment]
I'm using the FL term for them, I think it fits :)

**Comment by GingkathFox** [comment]
Yeah, that fits lol

**Comment by GingkathFox** [comment]
isnt there a debugging thing @SecondFlight? maybe u could use that @EtornaZ

**Comment by SecondFlight** [comment]
I don't know @GingkathFox, I haven't been active here for very long. If it's reproducible then that wouldn't be needed. I haven't had time to attempt to reproduce yet, but if I remember I'll do that this evening.

**Comment by GingkathFox** [comment]
ok!

**Comment by musikBear** [comment]
Nahh Firstly, nothing is selected. Neither in piano-roll, nor in song-editor.
The *lightend* TCO shows that it is the one *currently opend in piano-roll!*
Even if you close piano-roll, it is still focused, and is still the one that are ready to play.
The (faint.. alas) outline, are there to help you find the block, you just had opened in piano-roll. It is not selected.
So if i understand you @EtornaZ -You say that you then open a new song-editor block in piano-roll, and it will show *and* play the previous opened block?
Is that correctly understood?

**Comment by EtornaZ** [comment]
No. I'm saying that when I have a pattern (also knows as a song-editor block) in the Song-Editor, play it in the Piano-Roll, pause it, select a new pattern/song editor block, and play that newly selected pattern/song-editor block in the Piano-Roll, the old pattern/song-editor block plays instead. To fix this, you can press the stop button in the Piano-Roll and then press the play button, and then the correct notes will play.

**Comment by musikBear** [comment]
@EtornaZ :) Its was one word that explain it:
 *pause*
**That** is the reason.
If you does exactly the same, but *stop* play, you will not hear the previous pattern.
So it is a difference between *pausing* play, and *stopping* play, that causing this to happen.
I have tossed this pause-behaviour around a bit, but i cant find an usecase where it is beneficial. 
Guess it could be solved with having *song-editor-block-opening*, cancel anything that is *paused*, by setting it to *stopped*

**Comment by EtornaZ** [comment]
Yes, that could be the way, but I figured that if someone pressed pause on a song-editor block and then moved to a new one, they would want their current song-editor box to play instead of the old one without having to press stop. That is how I feel, which is the reason why I reported this as an issue, so a developer could fix it. :)

**Comment by madisonsilver** [comment]
Here's a video reproduction of the bug: https://www.youtube.com/watch?v=WKMDk8yf5aQ
