### ISSUE TITLE
VST UIs do not scale on HiDPI screens

### ISSUE THREAD

**Issue by ahstro** [LMMS/lmms#4411]
Using VSTs in VeSTige on a HiDPI screen opens a window that is much larger than the VST UI. I don't know if LMMS is capable of actually scaling up the VST UI to the "proper" size, but if not, we should at least make sure that the window size is correct.

Here's an image showing off the problem. The window size can not be made any smaller, so this bloats up the available UI quite a lot.
![vst-plugin-ui-bug](https://user-images.githubusercontent.com/3090888/41144412-25f1fa28-6afd-11e8-9bb2-85ce48b83479.png)

**Comment by lukas-w** [comment]
@ahstro Can you share the OS and LMMS version you're using?

**Comment by ahstro** [comment]
Running Arch Linux with latest kernel, here's the output of `uname -a
```
Linux tp-x1-arch 4.16.13-1-ARCH #1 SMP PREEMPT Thu May 31 23:29:29 UTC 2018 x86_64 GNU/Linux
```

Using the AUR package `lmms-qt5-git`, so it pulls latest from `git`, which I built today. It says the version is `1.2.0.rc6.r5.g2f19fa11c-1`. The output of `lmms --version` is:
```
LMMS 1.2.0-rc6.5
(Linux x86_64, Qt 5.11.0, GCC 8.1.0)

Copyright (c) 2008-2018 LMMS Developers

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public
License as published by the Free Software Foundation; either
version 2 of the License, or (at your option) any later version.

Try "lmms --help" for more information.
```

**Comment by lukas-w** [comment]
@ahstro Thanks.

Confirmed. For anyone without a HiDPI screen, this can be reproduced with e.g.
```sh
QT_SCALE_FACTOR=1.5 lmms
```

**Comment by Spekular** [comment]
Closing and consolidating into #5433
