### ISSUE TITLE
Keyboard/mouse error

### ISSUE THREAD

**Issue by GingkathFox** [LMMS/lmms#4414]
theres a semi-weird thing on RC6 (W10) where when you have a plugin window open and use the keyboard to play notes, then try to use the mouse, the mouse will not respond, like it is locked.

**Comment by lukas-w** [comment]
This sounds like the OS disabling a touchpad while typing to prevent accidentally moving or clicking the mouse. @GingkathFox Are you using a laptop/touchpad? Can you reproduce this behaviour in any other applications?

**Comment by musikBear** [comment]
Look if the selected tool is **pen**. I have noticed that the 'tool' is often flipping to 'selector' (rubber-box), and that makes the mouse apparently not respond. 
(This 'flipping' in RC6, is more frequent than before, but it has always been an issue.)

**Comment by GingkathFox** [comment]
@musikBear nope, its the normal pointer.
@lukas-w ok, I'll try on FL demo

**Comment by SecondFlight** [comment]
Adding back response required, will go away again when OP responds with test results.

**Comment by GingkathFox** [comment]
getting th demo now, its takin ages XD

**Comment by lukas-w** [comment]
@GingkathFox You don't need the FL Studio demo for what I'm asking. You can try any application, type some text and try to move the mouse at the same time or immediately after. If that exposes the same problem, this is a feature of your OS/driver and you need to disable it if you don't like the behaviour. Also, you didn't answer the question of whether you're using a touchpad.

**Comment by GingkathFox** [comment]
Yeah, its an OS/Driver issue. Should I close this? and I am using a touchpad.

**Comment by lukas-w** [comment]
@GingkathFox Thanks for confirming. Usually, touchpad drivers offer the ability to disable the feature in the system settings.

This means this is not an issue with LMMS and there's probably nothing we can do about it, so yes, this issue should be closed. Anyway, thanks for reporting and helping troubleshoot it! :+1:

**Comment by GingkathFox** [comment]
Wait, is it ossible for an app to override that feature, or is that not possible?

**Comment by lukas-w** [comment]
No, as far as I know this is not possible. You can disable it or reduce the timeout in your settings to mitigate the issue.
