### ISSUE TITLE
Translation in Swedish displays % character in menu

### ISSUE THREAD

**Issue by saurid** [LMMS/lmms#4415]
Menu option "View" in swedish shows "%Visa" instead of the correct "Visa". Windows 10 version 1.2.0-rc6
![image](https://user-images.githubusercontent.com/1075365/41191080-46694c64-6bea-11e8-8d54-c9a41b90c7f5.png)

**Comment by PhysSong** [comment]
I guess it should be `&Visa`. Ampersands are used for accelerator keys.

**Comment by saurid** [comment]
Seems like it, yes. Alt-V is not working for this menu option, but does work for the other ones.

**Comment by zonkmachine** [comment]
I suggested a fix for this on Transifex but couldn't push it as I don't seem to be cool enough to do this. I just glanced over the Swedish translation and it looks like people have been pushing changes online without testing it against lmms.

**Comment by PhysSong** [comment]
For 1.2, it'd be sufficient to edit `sv.ts`.

**Comment by zonkmachine** [comment]
Translations won't be merged back from transifex before 1.2?

**Comment by Spekular** [comment]
I fixed it on transifex FWIW.

**Comment by zonkmachine** [comment]
OK. I resolved the Transifex issue.

**Comment by SecondFlight** [comment]
Can this be closed then?

**Comment by zonkmachine** [comment]
I'd like to know how changes are merged back to 1.2 first. I'm a total noob at Transifex.

**Comment by PhysSong** [comment]
Editing this part should work:
https://github.com/LMMS/lmms/blob/2f19fa11c886374adcc74990e52d3ed0473fbf08/data/locale/sv.ts#L3941-L3942
Though not directly related, I also found one place where accelerator is missing:
https://github.com/LMMS/lmms/blob/2f19fa11c886374adcc74990e52d3ed0473fbf08/data/locale/sv.ts#L306-L307

**Comment by zonkmachine** [comment]
Yes, but isn't the translations going to be merged back from Transifex?

**Comment by PhysSong** [comment]
IIRC Transifex is synced with `master` now. @liushuyu Is it correct?

**Comment by Spekular** [comment]
Updated the "Copy Value" translation to "&Kopiera värde (%1%2)" as well. I was unsure about that earlier since it changes the accelerator key, but I guess it's better than not having one at all.

**Comment by PhysSong** [comment]
i18n strings in `stable-1.2` have never been updated since 9 May 2017 so I fixed it manually in 1bae047b98558981c20c85edc44550f4aa9714d9.
