### ISSUE TITLE
VST effects in the mixer // RC-7

### ISSUE THREAD

**Issue by noovaa** [LMMS/lmms#4425]

**Comment by lukas-w** [comment]
@noovaa What is the purpose of this issue?

**Comment by SecondFlight** [comment]
You can currently put VST effects in the mixer. Check your VST folder in the settings and make sure it's correct. If the folder is correct then the plugins will show up in the list along with all the other effects.

If this does not cover your issue, please comment here with more info, and I will reopen your issue.
