### ISSUE TITLE
Github wiki for installing build dependancies on Fedora includes lib-alsa-devel which isn't in Fedora package repository

### ISSUE THREAD

**Issue by PJ-Finlay** [LMMS/lmms#4427]
The [Github wiki for installing build dependencies for Fedora](https://github.com/LMMS/lmms/wiki/dependencies-fedora) under the "Qt4" header includes lib-alsa-devel which isn't in the Fedora repositories. I think that this was intended to include alsa-lib-devel which is included under the "Qt5" header.

[alsa-lib](https://admin.fedoraproject.org/pkgdb/package/rpms/alsa-lib/)
[lib-also](https://admin.fedoraproject.org/pkgdb/packages/lib-alsa%2A/)

**Comment by PhysSong** [comment]
I think you're correct. You can edit that yourself.
