### ISSUE TITLE
Using logo art on album release

### ISSUE THREAD

**Issue by franny23dmt** [LMMS/lmms#4429]
Is it ok to use the LMMS logo on my album cover artwork?    "written & produced on ...." etc 
I'd love to rub this into all the Logic/Cubase/FL Studio users :D 
.
From a historical POV, my album is going to be the longest artist album ever published yet (~12 hours) :) 

PS> i was told to ask here on LMMS forum and , I tried FB LMMS page but didnt get a reply

**Comment by SecondFlight** [comment]
Yes, that is fine :)

**Comment by franny23dmt** [comment]
awesome : )
