### ISSUE TITLE
Panning knob in song-editor partially hidden in swedish

### ISSUE THREAD

**Issue by saurid** [LMMS/lmms#4436]
The panning knob in the song-editor is pushed to the right, making it difficult to see what value it has.
![image](https://user-images.githubusercontent.com/1075365/41509504-2aafb302-7255-11e8-9fea-5c67c8b6bfed.png)
Looking in the sv.ts file on row 5985, I think the translation to swedish should be the shorter PAN. The knob is centered beneath the longer PANORERA, which makes the knob partially dissapear.

Tested in LMMS 1.2.0 rc6

**Comment by musikBear** [comment]
PAN must be enough for my neighbours. Danes would also say 'Panorere' or 'Panorering' but Everyone would understand PAN

**Comment by saurid** [comment]
It's still named PAN in stable version I think. Not sure about other languages, but if it is more than three characters, i guess they also have the same problem as I do. VOL is also a short, so I think it was just a mistake during translation :)

**Comment by zonkmachine** [comment]
This has already been fixed in master but we probably need to change it manually on stable-1.2

> PAN must be enough for my neighbours.

Correct.

> It's still named PAN in stable version I think. Not sure about other languages, but if it is more than three characters, i guess they also have the same problem as I do.

This has indeed been reported for other languages on Transifex and I do see this on stable-1.2
