### ISSUE TITLE
strange popup from REA-vst

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#4440]
OS  : winXP sp3
LMMS RC6

**Issue description:**
I am not sure if this popup is related to lmms or to windows. If i can understand it, it is complaining about an part of REAeq, that is not a _valid graphic element_(?) Unless 'image' refer to win-image, but then it makes even less sense. Could 'old'ish' graphics be a problem for qt5? 

**Recreate         :**
I dont know if it can be done. But i include the dll in a zip
[reaeq-standalone.zip](https://github.com/LMMS/lmms/files/2111773/reaeq-standalone.zip)

**Expected           :**
Normal Vst load or understandable error message 

**Factual event/ bug**
This popup:

**RemoteVstPluginexe - Bad Image**
_The application or DLL <path> reaeq-standalene dll is not a
valid Windows image. Please check this against your installation diskette._

Lmms freezes and stays in mem
Cleaned fully away, with TM: 'end-proces-tree'

**Comment by DomClark** [comment]
Here "image" is not referring to a picture, but a file containing executable code; the definition is closest to [definition 3 here](https://en.wiktionary.org/wiki/image).
I can't reproduce this issue; the VST loads fine for me. It appears to be a 64-bit DLL though - is your system 32- or 64-bit? If 32, this may be the cause of the issue. Either way, it sounds like it's a problem on your end.

**Comment by musikBear** [comment]
@PhysSong -loL I got the dll mailed to me, from one that had updated to RC6, and now he had fails with the Eq most of his projects was made with "Could i try if i could help him"
Sure!
He just forgot to tell me that he was on x64 (or i forgot to ask :p 
It is however very interesting that you can load, and use this eq, because that could indicate, that the VST does work in RC6.. I cant avoid wonder if he somehow has confused his x32 for _this_ x64, and /that/ is the reason for his problems.

**Comment by DomClark** [comment]
I'm fairly certain this isn't a bug in LMMS. @musikBear is there anything else you want us to know or can this be closed?

**Comment by musikBear** [comment]
@DomClark -He has not replied on the 32 / 64, so i call this
