### ISSUE TITLE
vst's gui is strange

### ISSUE THREAD

**Issue by Ffsharp** [LMMS/lmms#4444]
OS : Windows 10, 64bit, maybe latest version
LMMS : 1.1.3 version

I loaded these VST(synth1, TAL-Reverb, Krush, Model-E)  by VeSTige.
I didn't find any problems in sounds, knobs, etc.
It works well, except GUI.
All these VST's GUI were cut like this.
<img width="608" alt="1" src="https://user-images.githubusercontent.com/40537341/41818506-60e4f45a-77eb-11e8-9bf4-46cc098773de.PNG">
I didn't touch any settings.

**Comment by karmux** [comment]
Hi,

Try [1.2.0 RC](https://lmms.io/download/#windows). There are lots of VST fixes.

**Comment by Ffsharp** [comment]
I already tried RC6. but...#4405

**Comment by lukas-w** [comment]
@Ffsharp The issue you linked contains information on how to resolve the error. Change to an audio backend other than PortAudio using RC5 or just delete your `lmmsrc.xml` if you don't mind losing your settings. Please try that and report back, or try if RC5 fixes the VST issue.

**Comment by musikBear** [comment]
@lukas-w Wouldent it be best, with a note on DL-page for 1.1.3, that vst's does not work correctly on win10, and that RC6 should be the choice instead.
Its almost daily, that i have to tell win10 & 1.1.3 users to de-install, and get RC6 installed, because they have issues with chopped-of VSTs UI's
