### ISSUE TITLE
Make MMP the default saving-option

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#4445]
I suggest that lmms default saves as MMP, and not as now, in MMPZ.
If something goes wrong, then crippled mmpz files are useless whereas crippled mmp-files can contain almost all of the project. Crippled mmpz-files cant be converted either. The conversion does not create a valid file.

**Comment by lukas-w** [comment]
I suppose by "cippled" you mean an incomplete file produced if LMMS crashes while saving? If so, it's better to actually guard against that happening instead of trying to mitigate the issue with workarounds. I'll create an issue for it.

**Comment by SecondFlight** [comment]
No need to fill the tracker with unnecessarily open bugs. Feel free to reopen this if the conversation merits it.

**Comment by musikBear** [comment]
>  the old file will still be there with a .bak suffix.

Partly true, but if it is first save, there is noting saved.
-but if i am the only one, seeing benefits from default uncompressed saving, so be it.
