### ISSUE TITLE
Add error messages if VST loading failed

### ISSUE THREAD

**Issue by lukas-w** [LMMS/lmms#4447]
From discussion in https://github.com/LMMS/lmms/pull/4421#discussion_r196263427. Currently when loading a VST fails, such as when trying to load a 64bit VST on a 32bit VST, no error message is shown. The user should be notified of the error and we should provide a reason for failing when possible. For the 32bit vs 64bit example, this means we should check if the user's computer and the LMMS installation support the plugin's architecture.

**Comment by Spekular** [comment]
Closing and consolidating into #5433
