### ISSUE TITLE
[Feature Request] Ghost Channels

### ISSUE THREAD

**Issue by MisterTeeXD** [LMMS/lmms#4449]
The feature i want to see in LMMS is Ghost Channels, Ghost Channels are Notes that show in a blank Piano Roll from a previous Melody Pattern that will help make your Beat play on point and accurately, i think its a nice feature to have in LMMS

**Comment by PhysSong** [comment]
Is #4303 and/or #520 what you're looking for?

**Comment by MisterTeeXD** [comment]
Oh Crap, did not realise that was already requested, let me close this issue
