### ISSUE TITLE
The oscilloscope color can't be changed

### ISSUE THREAD

**Issue by DevSynth** [LMMS/lmms#4459]
Line 176 below, won't change the color of the background of the oscilloscope and it wont change the color of the sound waves

VisualizationWidget  {
	background: none;
	border: none;
}

**Comment by PhysSong** [comment]
I suggest you to change `output_graph.png` file. It's the background image for the oscilloscope.

**Comment by Umcaruje** [comment]
The color of the waveform display seems to be hardcoded:
https://github.com/LMMS/lmms/blob/32f07ac317b42dda42a1d00b0a3b1fa1feef0655/src/gui/widgets/VisualizationWidget.cpp#L141-L153
So this is a valid enhancement request.

**Comment by DevSynth** [comment]
Chaning output_graph.png doesnt do anything btw

**Comment by michaelgregorius** [comment]
#4509 makes the line colors (normal, warning, clipping) available as properties.
