### ISSUE TITLE
Enhancement: selection in piano-roll

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#446]
Enhancement: selection in piano-roll
I think everyone has tried this. A larger block of notes should be selected, but in the result, a few notes is missed. Reason: User did not drag the selection rectangle past -all- the notes. I think a real improvement would be, if it was possible to drag the selection tool over the timebar, and every note inside that timeslot, would then be selected. An alternative could be a menu-item in 'Edit' : 'Select all notes inside timeslot'. A popup form should then apear with:
From bar <user input>
To bar <user input>
<enter>
This is a litle less intuitive, but perhaps simpler to implement?
Any thoughts?

**Comment by waxspin** [comment]
@musikBear I know you recently mentioned something about doing this in master, but according to what I've found, it is already implemented, at least selection-wise.  Currently, if you hold the shift key while dragging the scrubber on the time bar, it selects all notes under that time slot.  However, it might make the UI a little more intuitive if we did something like draw a selection box around all the notes as the scrubber is being dragged.  What do you think?

**Comment by musikBear** [comment]
@waxspin Oh it has already been implemented! woow.. Nice! 
No i dont think we need a box around the notes, because a user will  intuitively see a frame box, as a limit for selection, and with this super neat timeline-slection.method, there is *no* limit, **All** is being selected! So this is perfect. Very good indeed :+1: 
If you like to 'do battle' with one more :p There is the 'playing a stack of notes' :  640

**Comment by waxspin** [comment]
Ah, sorry for the confusion, but rather than a limiting box, I meant more
of a full height highlight just as a very slight visual indicator that
something is happening, slightly less subtle than the selection color of
the notes changing.  Thanks for the note about 640, I'll take a look at
that next!

**Comment by musikBear** [comment]
> Thanks for the note about 640, I'll take a look at that next!

That would be super! :+1:

**Comment by musikBear** [comment]
@waxspin This great feature needs one more enhancement.
