### ISSUE TITLE
LMMS shows only a part of the NI Reaktor 6 interface

### ISSUE THREAD

**Issue by jibin1573** [LMMS/lmms#4461]
I am using LMMS 1.2.0 RC6 (64bit) on Windows 10 version 1803. I loaded the free Native Instruments Realtor 6 (version 6.2.2) into LMMS (through vestige) , and part of the interface was missing. This happens only for the "Lazerbass.ens' patch on Realtor 6.

**Comment by jibin1573** [comment]
Yes! That is what is happening. The VST works fine but chopped-off part is
inaccessible.

**Comment by DomClark** [comment]
Reproduced; sounds like #4087 too. I have a fix in development.

**Comment by tresf** [comment]
> #4087 

Marking as duplicate as the "cutoff" issue is already being addressed there per @DomClark's comments.  @DomClark please feel free to mark as duplicate or consolidate as you find 'em.
