### ISSUE TITLE
Feature suggestions

### ISSUE THREAD

**Issue by jibin1573** [LMMS/lmms#4462]
Feature suggestions:

1. Embedding Linux sampler:

Is it possible to embed "Linux Sampler" into LMMS? Then the developers can concentrate more on the LMMS DAW instead of plugins like GIG, SF2 player etc. Linux sampler would be a great sample player, which is being systematically developed. I checked some other threads relating to samplers, but no one is talking about embedding Linux sampler into LMMS. What say?

2. Audio file tagging:

It would be great to have a tagging feature. Like tagging the audio file when exporting. Tags include: song title, artist, album, Track number etc. Please consider this suggestion. 

3. Custom colour for instrument tracks:

 Custom colour option is available for the Beat+ Bassline grids in the song editor.
An option to change the colour of the instrument track (like Vestige, ZynAddSubFx etc) would be great.
it might be useful, like for example, Red for bass, Green for Lead, etc. It makes things easy, by allowing the user to pick custom Colors even for the instrument track

4. Glowing buttons:

Can we have glowing buttons, like in FL studio. Like when we press any button, it should light up with a different colour.

Thank you!

**Comment by Spekular** [comment]
@jibin1573 there are existing github issues for 2 and 3, so you don't need
to open those.

**Comment by jibin1573** [comment]
Oh! I already posted!

**Comment by jibin1573** [comment]
@Spekular, can you please lead me to the post with "Audio file tagging"and c"ustom Colors for instrument track"?

**Comment by jibin1573** [comment]
I'm quite excited!!

**Comment by Spekular** [comment]
Custom colors: https://github.com/LMMS/lmms/issues/1665
(and https://github.com/LMMS/lmms/issues/1160)

Samples: https://github.com/LMMS/lmms/issues/4309

**Comment by jibin1573** [comment]
Thanks a lot @Spekular!
