### ISSUE TITLE
Embedding Linux Sampler

### ISSUE THREAD

**Issue by jibin1573** [LMMS/lmms#4463]
Is it possible to embed "Linux Sampler" into LMMS? Then the developers can concentrate more on the LMMS DAW instead of plugins like GIG, SF2 player etc. Linux sampler would be a great sample player, which is being systematically developed. I checked some other threads relating to samplers, but no one is talking about embedding Linux sampler into LMMS.

**Comment by tresf** [comment]
Not easily, no.
