### ISSUE TITLE
Piano Roll: Show note labels on notes

### ISSUE THREAD

**Issue by MrcSnm** [LMMS/lmms#4466]
![51234](https://user-images.githubusercontent.com/10136262/42359729-306b5a3a-80ba-11e8-9212-4642eee2e3c9.png)

This is basically what i want you to do, when you used too much fl studio you really miss this, it is quite boring needing to make a horizontal line with your eyes backing to you can know what note you're actually playing, for some reason just appear the root note, already searched for things like this in LMMS but never found it

**Comment by PhysSong** [comment]
For piano keys, you can turn on `Enable note labels in piano roll` in Edit->Settings. It's not implemented for notes, but I think it won't be hard.

**Comment by MrcSnm** [comment]
So, the problem is that I find it pretty polluted
![5123](https://user-images.githubusercontent.com/10136262/42363133-af48af6c-80cc-11e8-8aba-09b8da799cd5.png)

Dunno if it is just for me, but it really is hard to be seeing things like this.

**Comment by lukas-w** [comment]
@MrcSnm Note labels on keys have already been implemented via #2285 and will be part of the 1.2 release:

![image](https://user-images.githubusercontent.com/2879917/42373058-21173428-8114-11e8-9b9e-d4a9f82a5778.png)

Having note labels on each note is covered by #521. However, #521 lacks a screenshot illustrating the proposal so I'll close that one as a duplicate.

**Comment by michaelgregorius** [comment]
Implemented with #4467. Here's how it looks:

![lmms-4466-notetext](https://user-images.githubusercontent.com/9293269/42412102-59b8904a-8206-11e8-9c09-e9b878ed162e.gif)

**Comment by musikBear** [comment]
@michaelgregorius -lovely little added feature. Will benefit newcomers, and since it's toggable in Settings, no adverse things here - Nice ! 🎆

**Comment by jibin1573** [comment]
Great!! Thanks!

**Comment by michaelgregorius** [comment]
Closing this issue as #4467 has just been merged into `master`.
