### ISSUE TITLE
Deleting BB Blocks in the Song editor

### ISSUE THREAD

**Issue by jibin1573** [LMMS/lmms#4470]
Using Windows 10 (Version 1804)
LMMS 1.2.0 RC6

I'm not able to delete more than one BB Block together. I can only delete them individually. ( It becomes a tedious task to delete lots of small BB Blocks!)
Is it possible to select more than one BB Block and delete them together?

Also, the Delete key on the keyboard cannot be used for deleting even one BB Block in the song editor.

(Don't know whether it's a bug or a suggestion)

**Comment by Sawuare** [comment]
This has been implemented for version 1.3, where pressing the Delete key deletes selected blocks.

Implemented in `master` via #3649.
