### ISSUE TITLE
No panning knobs in sample tracks when "Compact track buttons" is set

### ISSUE THREAD

**Issue by banti101** [LMMS/lmms#4475]
There is no leveling on Song-Editor in lmms 1.2.0-rc6. only icon . that is annoying. also no panning in sample track. @lmmsservice 
![capture](https://user-images.githubusercontent.com/41033357/42486929-2b65a8e6-841c-11e8-8653-4a4e182de1a7.JPG)

**Comment by PhysSong** [comment]
> There is no leveling on Song-Editor in lmms 1.2.0-rc6.

Do you mean track labels? If so, you can turn off **Compact track buttons** setting.

> no panning in sample track.

You can use panning after turning off the setting, but it should be there even if the setting is turned on. Thank you for reporting this!

**Comment by banti101** [comment]
thanks... its work well.

**Comment by PhysSong** [comment]
Opened a pull request #4477. The bug you've reported will be fixed in RC7. Removing `[SOLVED]` and leaving this open for now, but I'll close this one once #4477 is merged(GitHub will automatically close this).
