### ISSUE TITLE
Vestige track as default

### ISSUE THREAD

**Issue by jibin1573** [LMMS/lmms#4478]
Please provide a Vestige track as default in the Song editor. This might help the new users. It also reduces a few steps of pulling the sidebar and dragging the Vestige to the Song editor.
(I know we can create templates, but it would be great to have it as default)

**Comment by Spekular** [comment]
You can use [File>Save as default template] to set your own default startup
file if you'd like vestige to be there when you start a new project. I
personally don't think the default new project should have more tracks than
it already does, or that beginners wpuld benefit from it.

**Comment by SecondFlight** [comment]
If a user doesn't know how to get Vestige, they probably don't know how to use it either. I don't see a reason to keep this issue open, I'll let someone else on the dev team open it if they feel it has merit.

**Comment by jibin1573** [comment]
My main intention was to remove the number of steps involved in starting a VST instrument. Like, once you have a Vestige instrument, you can go on cloning the track as much as you want (almost like an  "add instrument track".
And also, Vestige is something that most users will always use; I think, more than the other defaults.

**Comment by DouglasDGI** [comment]
Actually, even though I use VSTs in almost every song, I'm rarely pulling out VeSTige because they're all VST effects rather than VSTis.  ZynAddSubFX gives me most of what I need.  I can't speak for others, but I do know there are many people out there who never even use VSTs to begin with.

I already got into the habit of loading the "Empty" project preset, but if I was still just clicking the default "New" button, I wouldn't want an extra track to delete every time.  Actually, if it wasn't for the fact that it may confuse beginners, I'd probably vote to keep the default "New" project empty.  In many circumstances, having the tracks already there for you would save you less time than it would take to delete the tracks you don't need, especially if you like keeping things organized and you cannot stand having tracks there you aren't going to use/aren't going to be using at the moment.

I'd say simply dragging it in from the left is easy enough.

**Comment by jibin1573** [comment]
Is there an option to open LMMS directly with a user template, rather than the default template?

**Comment by SecondFlight** [comment]
As @Spekular said,
>You can use [File>Save as default template] to set your own default startup
file

**Comment by jibin1573** [comment]
But it does not open as default. You have to go to the template folder to open it like a project.

**Comment by SecondFlight** [comment]
That was not my understanding of what he said but I can't confirm this as I am at work.

**Comment by Spekular** [comment]
Saving a project as default template will load it on startup and when using
File>New.

>

**Comment by jibin1573** [comment]
Frankly, there a lot of steps in using vestige.
1. Open the sidebar
2. Load vestige to song editor
3. Click vestige
4. Click browse
5. Then search for the vsti
6. Click the vsti.
So long!

**Comment by jibin1573** [comment]
Yes. I also saw another post where there was a discussion on a "My VST folder" in the sidebar. It would be great if that gets implemented. Then, we just have to drag the VSTs from the sidebar.

**Comment by RoxasKH** [comment]
Yeah a vst scanner with a sidebar should be really implemented, it's standard on all other DAWs like FL, reaper, mulab...

**Comment by RoxasKH** [comment]
So we won't need to go through vestige, if this will done automatically by the software

**Comment by DouglasDGI** [comment]
Yes, that would be a good idea, though it's kind of off-topic from this issue, and also the ability to simply drag in whatever you want from the side will make a feature like having an empty VeSTige track in the default new LMMS project even more pointless.  Which is what we're discussing right now, I'm sure there's already a Github issue open for a VST sidebar issue.  Right now we're discussing having an empty VeSTige track open in a default LMMS project, which I don't really see many good reasons for, _especially_ if the VST sidebar is added in the future.  Anyway, no point in me discussing further, the topic is already closed anyway.

**Comment by jibin1573** [comment]
I'll post it as a new topic

**Comment by jibin1573** [comment]
UPDATE:

Sorry!! I didn't notice that there was a super easy way of creating default templates in LMMS. Steps involved:

1. You just have to set LMMS, the way you want.

2. Go to "File"  and then press "Save as default template!

3. Restart LMMS.

 Viola!! You have a custom default template!! 
(I wouldn't have opened this issue if I knew about this feature)
