### ISSUE TITLE
Detuning at higher sample rates

### ISSUE THREAD

**Issue by jibin1573** [LMMS/lmms#4479]
I'm using Windows 10 (version 1803)
LMMS 1.2.0 RC6

When I export songs at a sample rate higher than 44100hz, there is an increase in the pitch of certain VST instruments. I have found out some VST instruments which get detuned:

1.MaxSynth's Bass Module (Free): Effect: Pitch shifts upwards
Cause: Happened when I was exporting wav @ 24bit with sample rate at 96000hz.
(No problems were found when I exported it at 44100hz @24bit.)

2. Helm:
Effect: Pitch shifts upwards
Cause: Happened when I was exporting wav @ 24bit with sample rate at 96000hz.
(No problems were found when I exported it at 44100hz @24bit.)

3. DSK Overture:
Effect: Pitch shifts upwards
Cause: Happened when I was exporting wav @ 24bit with sample rate at 96000hz.
(No problems were found when I exported it at 44100hz @24bit.)

4. Orchestral Strings One by Sound Magic:
Effect: Pitch shifts upwards
Cause: Happened when I was exporting wav @ 24bit with sample rate at 96000hz.
(No problems were found when I exported it at 44100hz @24bit.)

5.  Piano One by Sound Magic:
Effect: Pitch shifts upwards
Cause: Happened when I was exporting wav @ 24bit with sample rate at 96000hz.
(No problems were found when I exported it at 44100hz @24bit.)

7.  Bitsonic TB-303:
Effect: Pitch goes up one octave
Cause: Happened when I was exporting wav @ 24bit with sample rate at 96000hz.
(No problems were found when I exported it at 44100hz @24bit.)

8.  T-Force Alpha Plus by Mastrcode music:
Effect: Pitch shifts upwards
Cause: Happened when I was exporting wav @ 24bit with sample rate at 96000hz.
(No problems were found when I exported it at 44100hz @24bit.)

I'll report other VSTs, when I get time.

**Comment by naturbua** [comment]
I tested a selection of VSTs on different sample rates: https://soundcloud.com/user-498225535/detuning-at-higher-sample-rates-some-plugins/s-zw9Fd

First pass is @44100 Hz, second one is on 48000Hz, third is on 192000Hz

VSTs:
Triple Oscillator (Preset "Garfunkel")
4Front Piano Module (VST)
Tone2FireBird (VST)
Keyzone Classic (VST)
DSK Indian DreamZ (VST)

(using LMMS RC6 on Windows 10)

**Comment by DomClark** [comment]
@jibin1573 reported in https://github.com/LMMS/lmms/issues/4465#issuecomment-425727935 that T-Force Alpha Plus, Bitsonic TB303, and DSK Overture now have the proper pitch at higher sample rates, but the tuning problems are still present with Piano One. However, I no longer experience the problem with Piano One. Can anyone else test this with RC7?

**Comment by CathodeRayBlues** [comment]
I've noticed a lot of detuning and general weirdness with high sample rate exports with way more than just vst instruments. Some instruments are quieter or more reverberant than they should be, and even some zynaddsubfx instruments get super distorted. Surely this VST issue is a mere symptom of a greater problem regarding sample rates beyond 44100hz
