### ISSUE TITLE
VST folder in the sidebar

### ISSUE THREAD

**Issue by jibin1573** [LMMS/lmms#4480]
Is it possible to provide a VST folder in the sidebar. Then we can directly drag VSTs from that folder; reducing the number of steps involved in loading a vestige track from the sidebar.

(I'm not sure but I think there is an issue related to this topic)

**Comment by PhysSong** [comment]
#3048?

**Comment by jibin1573** [comment]
Thank you  @PhysSong! #3048 is the same issue. Has this been implemented?

**Comment by PhysSong** [comment]
#3048 implements this, but it has some issues, e.g. mixes instruments and effects.

**Comment by jibin1573** [comment]
Are we talking about showing the user specified vst folder in the sidebar?
If that's the case, users mostly segregate their VSTs into VSTi and VSTs (in that folder). Like in my VST folder, I have made separate folders for piano, Synth, organs etc. So, the sidebar has to just show up this folder, right?

**Comment by tresf** [comment]
> #3048?

Yes, #3048.  There's problems, but they're all covered in #2003 ❤️
