### ISSUE TITLE
ZynAddSUbFX fails to export

### ISSUE THREAD

**Issue by MichaelHabib** [LMMS/lmms#4484]
Hi,
I have the ZynAddSUbFX FREQ nub connected to a controller and managed by an Automation Track but on export the nub <> controller connection is lost and the ZynAddSUbFX track is not included in the exported file. 

I've attached a copy of the project file below. The problem with the 4 Automation tracks at the bottom.
[test1.mmpz.zip](https://github.com/LMMS/lmms/files/2193138/test1.mmpz.zip)

Tested in lmms 1.2 rc5 & rc6

**Comment by musikBear** [comment]
@MichaelHabib When i do a standard replay of your project, there are apparently no connected automation. Could you explain what dials in the two controllers, you have connected

**Comment by PhysSong** [comment]
@musikBear ZynAddSubFX4's frequency knob is connected to a LFO controller.

**Comment by MichaelHabib** [comment]
Hi, sorry about the late reply.
The LFO Controller uses automation tracks to automate the Frequency knob on ZynAddSubFX4, but on export the links are broken and the exported track in incorrect. I might have uploaded the files after an export (and after the links where broken).
You can reproduce the error by connecting a Controller to the Frequency knob on ZynAddSubFX4 , CTRL+Drag the SPEED knob from the controller window onto the automation track then export. On export, that links will be broken, even though it works fine on live playback ..

If you still need more info, I can try to re-open the project & take few snapshots within then ext 48 hours.
