### ISSUE TITLE
Casio CTK6300IN keyboard supported by LMMS

### ISSUE THREAD

**Issue by jibin1573** [LMMS/lmms#4490]
I have been using the Casio CTK6300IN Keyboard with LMMS as a MIDI input through USB, and it works flawlessly with LMMS for playing notes. So. I just wanted the name of my keyboard to be added in the list of supported keyboards for LMMS.

I'm using LMMS 1.2.0 RC6 (I have used 1.1.3 also) on Windows 10 version 1704

**Comment by Umcaruje** [comment]
> I just wanted the name of my keyboard to be added in the list of supported keyboards for LMMS.

There's no such list because all MIDI keyboards work with LMMS.

**Comment by jibin1573** [comment]
Oay, thank you!
