### ISSUE TITLE
Arpeggiator in Random and Sort mode does not randomize notes of a played chord

### ISSUE THREAD

**Issue by LostRobotMusic** [LMMS/lmms#4491]
When using LMMS arpeggios in Sort mode, it isn't currently possible for it to randomly select notes in the played chord.  Random mode only randomizes the notes chosen in the selected chord type, not the notes of a chord plotted in Piano Roll.  Hopefully I explained this well enough for you all to understand what I'm talking about.

I am unsure whether this would be considered a bug fix or an enhancement, but I would love to see this in a future LMMS release!  I already talked with @zonkmachine about it, told me to open an issue about it because it may take some work to implement.

**Comment by zonkmachine** [comment]
_From my answer on Discord_

it would need a bit of tweaking that one. The note to be played is selected here: https://github.com/LMMS/lmms/blob/3cf2afd8312252a0f1842cda25d81c064ed84beb/src/core/InstrumentFunctions.cpp#L402 The master notes are more or less agnostic of each other and calculate separately if it's their turn to generate a note. I have no ready idea how to fix that in a good way right now.

**Comment by zonkmachine** [comment]
@LostRobotMusic Can you confirm that this is fixed in #7025?

**Comment by LostRobotMusic** [comment]
Yes, it is fixed.
