### ISSUE TITLE
Loading Instrument from Song Editor

### ISSUE THREAD

**Issue by jibin1573** [LMMS/lmms#4492]
I wanted to give a suggestion regarding, loading instruments directly. The idea is:

Steps to load an instrument:

1.  "Right click" in an empty space in the Song-editor window and a "Context Menu" will open up. The Context menu will show an option to "Add Instrument".
2. Select "Add Instrument " and it will open the user's VST folder, browser window.
3. Now you can directly click and load the instrument

Better still, to add a Button (with a piano icon) in the Song-editor to "Add Instrument". This will reduce one step (no need to right click). 

Mostly, this is what the Piano button is expected to do in the main toolbar but it opens up an empty piano roll in the beginning, which isn't very useful. So there can be another "Piano button" in Song-editor", that will open the VST browser: or at least a "Context menu".

Thank you! 
(Please ignore this post, if it does not make sense 😀)

**Comment by lukas-w** [comment]
I don't think this makes sense when native instruments are still added using the sidebar. We should reduce the number of workflows for adding instruments (such as with #4480/#3048), not increase it. So I'm closing this because I believe #3048 is a better solution. Feel free to object.

**Comment by jibin1573** [comment]
I am aware of #3048, but just thought of suggesting a way that would reduce a few more steps in loading an instrument. In the Sidebar implementation, you have an extra step in the process, namely:

1. "Opening the Sidebar and

2.  Then opening the VST location.

 But with the Instrument button,  you can directly open the VST browser on clicking the "instrument button". And I think that is what most people expect from the "Piano icon" on the main tool bar.
 
(It also becomes way of doing the same thing.)
