### ISSUE TITLE
Batch Selecting Custom Notes in piano roll?

### ISSUE THREAD

**Issue by jibin1573** [LMMS/lmms#4495]
I don't know if this is already there, but just wanted to ask: In the Piano Roll, can we select custom notes, together?
(Like, in a word document, you can hold control and select different words, together. Can we do this with the notes in the Piano Roll?

**Comment by zonkmachine** [comment]
> I don't know if this is already there

It is. Please ask in any of our existing support channels before opening an issue here.
Here: https://lmms.io/forum/viewforum.php?f=7

**Comment by jibin1573** [comment]
Ok, sorry about that.
