### ISSUE TITLE
Custom Panning and Velocity Templates

### ISSUE THREAD

**Issue by jibin1573** [LMMS/lmms#4496]
Is it possible to create custom templates for Velocity and note panning, in the Piano Roll?
Mock up:

![note panning templates](https://user-images.githubusercontent.com/40867393/42820563-155d66f0-89f4-11e8-9bd7-0de101d002a7.png)

![mockup](https://user-images.githubusercontent.com/40867393/42924728-1a81a582-8b49-11e8-9dbd-d54d31a4b0fe.png)

Like, on right clicking, a context menu,  it will show the option for 'Note panning templates' or 'Note velocity templates". on clicking it we will have various custom templates for Note Velocity and Note Panning. 

Please correct me, because I am not aware of doing this quickly, in another way. Because I have been doing it manually by clicking and changing the panning for each note! So, I thought, if I could make some templates, which I can use.

-----
Edit by @SecondFlight: add new mockup from comments

**Comment by Spekular** [comment]
You can select several notes and change velocity for all of them at once,
which would help with this pattern.

**Comment by jibin1573** [comment]
Don't know how to select custom notes! I have posted another issue relating to this, which was closed. Please help.

**Comment by SecondFlight** [comment]
Not quite sure what you're asking. You can use ctrl+drag to select multiple notes at a time.

Easy way to get the first three bars:
1) Add the first two notes and pan them as you have in the picture.
2) Ctrl+drag to select them (or use ctrl+a).
3) Shift+drag to duplicate the two notes, and place them after the two you already have.
4) Ctrl+a to select all four notes, and then shift+drag the notes twice and put them where you want them to be.

**Comment by jibin1573** [comment]
I want to select random notes, "together".

**Comment by jibin1573** [comment]
I want to select random notes, "together".

**Comment by jibin1573** [comment]
I want to select random notes, "together".

**Comment by lukas-w** [comment]
@jibin1573 This is the same question as in #4495, where you've already been told to use our support channels instead of this tracker which is for development only. Please ask these kind of questions in https://lmms.io/chat/ or https://lmms.io/forum/.

**Comment by jibin1573** [comment]
Ok, thank you!

**Comment by SecondFlight** [comment]
Just for the record, and as musikbear pointed out in the forums, this is already possible with ctrl+shift.

**Comment by jibin1573** [comment]
@SecondFlight, I'm not taking about copying notes here. I had posted a separate issue purposely.

**Comment by musikBear** [comment]
@jibin1573 i told you some day ago, that you cant. Tou can make a suggestion for the feature in Forum. Eventually, it may come into consideration

**Comment by jibin1573** [comment]
@musikBear, thanks! You seem to have understood what I was saying. I want this issue to be considered as a feature request. So can this issue be opened again?

**Comment by SecondFlight** [comment]
You have gone into very little detail about how this would actually work aside from saying this would add "templates". What are templates, and how do they work? If you would like this to be a feature request, please add specifics about how you would expect a feature like this to work.

**Comment by jibin1573** [comment]
@SecondFlight , I have uploaded this mock-up. I hope this helps.

![note panning templates](https://user-images.githubusercontent.com/40867393/42924624-b61ef612-8b48-11e8-816e-2472f6577f1c.png)

**Comment by SecondFlight** [comment]
Thank you for putting that together. I have added the enhancement tag. This will remain open in case somebody wants to implement this.

**Comment by jibin1573** [comment]
Thanks you so much @SecondFlight!

**Comment by tresf** [comment]
The problem with this enhancement is that is assumes notes aren't stacked and in the use-case above that the notes are equidistant, which is one of thousands of arrangements supported by the piano roll.

This feature is cool, but it's completely illogical to implement as it scales very poorly.  An automation template would be much better and when ghost notes are merged, it makes it nearly as good as the per-note panning.

@SecondFlight I'm sorry, @lukas-w was right, this should be closed.
