### ISSUE TITLE
Splash.png Problem with alpha channel on Windows

### ISSUE THREAD

**Issue by RoxasKH** [LMMS/lmms#4511]
So, as a themers, i noticed that from 1.2.0 RC5, on windows OS, the splash didn't appear. The problem was then founded in the alpha channel present in the splash.png image. So, the problem was solved in RC6 by removing this alpha channel from the image, because as it hadn't transparency somewhere that was possible. But this thing create a new problem for themers like me: we cannot now use a splash.png with transparency. So the splash in my theme has a transparent background, that is visible only on linux and macos.
The thing i can't understand is why it was solved in this way, that is obviously faster, but no so clever. Also on previous version, like 1.1.3 or RC2, splahes with alpha channels appear correctly at the program startup.
So i hope this could solved in a right way in RC7, because it will be not an improvement for theming, but only a return on old theming possibilities. Thanks

P.S.: If my english was bad, sorry, i'm italian, but i think you could get to the point. :)

**Comment by tresf** [comment]
Closed via https://github.com/LMMS/lmms/commit/c3438a1b4e89686f16f433c66db7aa1cc866153f.  Thanks for reporting.

**Comment by ImGGAAVVIINN** [comment]
This happened again on alpha 1.3.0 and later
