### ISSUE TITLE
No audio from wav file except at beginning of track

### ISSUE THREAD

**Issue by steter** [LMMS/lmms#4520]
1.2.0-rc6
I left this as a comment on an identical bug closed last October. I created an LMMS tune with a MIDI bass line and an imported Hydrogen drum track. Everything worked well. Closed LMMS. Today I opened LMMS to delete and re-import that drum track, as I'd made a couple of changes in Hydrogen. When I play it from the beginning, no problem. If I choose any other location, I have no audio from the wav file. I haven't tried starting over with a fresh tune yet.

**Comment by musikBear** [comment]
Please upload the track, and post a link

**Comment by PhysSong** [comment]
In LMMS, you can play audio files in two ways. One is using AudioFileProcessor instrument plugin, and the other is using sample tracks.
Hydrogen import uses AudioFileProcessor to play sample files, not the sample track. LMMS can play sample tracks from its middle, but can't do the same for instrument tracks.
We might be able to implement the same for instruments, but I'm not sure.

BTW, could you upload your project file or a screenshot of it?

**Comment by lukas-w** [comment]
> I left this as a comment on an identical bug closed last October

For reference, the identical bug is #3874.

**Comment by steter** [comment]
Okay, that explains it. That's what I did. I used AudioFileProcessor. Just getting acquainted with LMMS. I hit that and went... what?? That makes sense. It's one big sample, and samples play from the beginning.

**Comment by steter** [comment]
If you'd still like a screenshot. no prob, but that's what I did.
