### ISSUE TITLE
Audio Settings on Windows doesn't save

### ISSUE THREAD

**Issue by Nick-Archi** [LMMS/lmms#4523]
When changing the Audio Interface, from Dummy to PortAudio, the message that LMMS will have to be restarted to have the changes take effect pops up. However, when exiting LMMS and returning, the audio settings are still at Dummy.

**Comment by Nick-Archi** [comment]
Found a solution to this issue. 

https://lmms.io/forum/viewtopic.php?f=3&t=283

However, I will leave this issue and someone can close it out if they wish. The bug still persists.

**Comment by musikBear** [comment]
@Nick-Archi its known, and there is a paragraph in the wiki about it.
https://lmms.io/wiki/index.php?title=LMMS_Settings#Problems_with_Settings
The sc. 'dot'-file is a headache, but eventually a solution will come

**Comment by tresf** [comment]
Published to our Troubleshooting tutorial.  Please continue to share these, preferable on [Discord](https://lmms.io/chat).

https://github.com/LMMS/lmms/wiki/Troubleshooting/_compare/17c2afd071fe53e141a2ddda0fb7edcaac326472...b9bf541f483a2051bf8ba019cf804d476f9ed618
