### ISSUE TITLE
VeSTige and Carla plugins sometimes interpreting wrong octave on MIDI keyboard

### ISSUE THREAD

**Issue by geckolinux** [LMMS/lmms#4535]
Hi, I'm using `lmms-1.2.0-rc6-linux-x86_64.AppImage` on openSUSE Leap 15.0 with an M-AUDIO Keystation 88es MIDI keyboard, running through ALSA+Jack.

I'm running into a really weird issue when using the VeSTige->sforzando VST and Carla plugins. With certain soundfonts, they appear to be shifting the scale down by a full octave. In other words, the lowest octave on the physical keyboard doesn't play any sound, and the highest key on the physical keyboard plays 1 octave too low. On the plugin's piano roll, it shows the correct keys being pressed, but the sound of the octave is wrong. In the sforzando plugin GUI, when pressing the physical keys in the lowest octave, the piano roll shows darkened keys (out of range, no voice available) being pressed. This happens with these soundfonts at least, there are probably others too:
- https://musical-artifacts.com/artifacts/3 `SalamanderGrandPianoV3_44.1khz16bit`
- http://download.linuxaudio.org/torrents/SalamanderGrandPianoV2.torrent
- https://musical-artifacts.com/artifacts/73 `maestro_concert_grand_v2`
- http://www.ivyaudio.com/Piano-in-162

On the other hand, it does NOT happen with these:
- https://github.com/KaleidonKep99/Steinway-D-274/
- https://gigasamples.com/giga-sample/maganda/

I have confirmed that the octave shift on the physical keyboard is **not** enabled, and I reset the entire keyboard and tried it with fresh configurations of LMMS and Carla several times. I also tried standalone sforzando (via Wine) and Carla standalone, as well as Qsampler, and the `maestro_concert_grand_v2.gig` file I tried in the LMMS Gig player, and this bug does **not** happen when using the same troublesome soundfonts.

I suspect this might have something to do with the different nomenclatures for octaves, depending on if it's a programmer or a musician or a standards group:
- https://www.midi.org/forum/830-midi-octave-and-note-numbering-standard
- http://dictionary.onmusic.org/appendix/topics/octaves
- http://www.soundsonline-forums.com/showthread.php?t=35897
It's just plain weird. All the keys on the M-AUDIO Keystation are labelled, and the lowest one is `A-1` and the highest is `C7`. But the LMMS Gig Player and standalone Carla and sforzando just simply work with the same troublesome soundfonts, so it looks like something needs to be improved in the logic for the VeSTige and Carla plugins.

Thanks a lot for LMMS! It's by far my favorite interface for my keyboard, which is why I'm really interested in seeing this work correctly.

**Comment by geckolinux** [comment]
Unfortunately this still prevents me from using LMMS (now testing with version 1.2.0). Using my M-AUDIO Keystation 88es, it still interprets it as an octave too low. I was playing around with moving the base note down 12 steps, which makes the lowest note on my 88 key keyboard playable, but on the other hand the highest note is silent.

**Comment by he29-net** [comment]
@geckolinux Hi; if you want, you can try to test the latest build at https://github.com/LMMS/lmms/pull/5349#issuecomment-566791587

It should have the MIDI mapping issue fixed, although I'm not yet sure how it will handle upgrade of 1.2.1 projects that use Carla (there is a small chance it will make Carla instruments sound an octave higher), so you probably shouldn't save any important projects in the new version before making sure it works as expected.

**Comment by geckolinux** [comment]
Hi @he29-net , thanks a lot for letting me know and for addressing this issue. I tested the AppImage in the linked comment, but it doesn't seem to be built with Jack support, so I couldn't make it work with my setup.

**Comment by jirislav** [comment]
Hi, I've also encountered this problem, with fresh setup of LMMS 1.2.2 64 bit & with salamander piano imported via VST: https://vst4free.com/plugin/2564/ .. this sadly also prevents me from using LMMS :/ probably going to switch to Audacity with raw audio input in microphone jack

**Comment by PhysSong** [comment]
Fixed in #5868.
