### ISSUE TITLE
Skin for a possible LMMS Sampler (Concept proposal)

### ISSUE THREAD

**Issue by RoxasKH** [LMMS/lmms#4542]
So i made this concept for a possible lmms sampler, it's bit inspired to DirectWave, and i think the final result is good. If you devs are thinking about programming a sampler for lmms in the future, feel free to use this :)

Here it is:

![](https://i.imgur.com/Vex3tCc.png)

Just let me know what you think

**Comment by PhysSong** [comment]
Possibly related: #4075

**Comment by CVTZ** [comment]
This looks good and would be a great addition to LMMS!

**Comment by NETMANSKY** [comment]
Nice view!!!

**Comment by RoxasKH** [comment]
Thanks guys!

**Comment by noahb01** [comment]
Great work overall!
Not sure how I feel about the integrated FX, it might be better to keep them on a seperate tab like the rest of LMMS (or in the FXMixer)

**Comment by RoxasKH** [comment]
As you can see, you can also disactivate the fx and use the ones you want with fx tab or mixer, i put them to fill a space and because, speaking about samplers, most of them have at least reverb integrated to make samples more realistic. Just take a loof to lmms sf2 player, it has reverb and chorus integrated, but you can also don't use them.

**Comment by NETMANSKY** [comment]
@noahb01 I think it was made for separated sample processing. It's a good idea in my opinion.

**Comment by tresf** [comment]
Consolidated into #4075.  @RoxasKH any help over there is appreciated!!!  Closing as duplicate.
