### ISSUE TITLE
Automating the tempo also causes lmms to crash

### ISSUE THREAD

**Issue by DevSynth** [LMMS/lmms#4546]
I automated the bpm of my track to make a clean outro but when I did that a couple of time and played that part, lmms would crash often, this is somehow related to the vst crash problem

**Comment by SecondFlight** [comment]
Referenced issue: https://github.com/LMMS/lmms/issues/4543

**Comment by JohannesLorenz** [comment]
@DevSynth Can you please give me an example of how to reproduce this bug? I tried with the "ZynAddSubFX" VST, but couldn't encounter any crashes.

I'd like to check this in order to prove that #4942 fixes it.

**Comment by SecondFlight** [comment]
@JohannesLorenz From #4543 (LMMS hangs when saving project while automating VSTi's pitch), which this issue is referencing:

>I use lmms 1.2.0 rc6 beta and I used the Helm VSTi, when I automate the pitch of what I make in it, it works sometimes, but when I start saving the file rapidly, which is a habit of mine to prevent data loss, Lmms freezes and I have to force close it, it may also freeze

So perhaps this?

1. Add helm
2. Automate tempo
3. Play project and save while tempo is being automated

That's only a guess though :/

**Comment by JohannesLorenz** [comment]
@SecondFlight Thanks, saving indeed caused the crash!
