### ISSUE TITLE
Loss of sound quality when using VeSTige

### ISSUE THREAD

**Issue by notxrandr** [LMMS/lmms#4548]
**OS:** Manjaro Linux
**Version:** LMMS 1.2.0-rc631 

When using VeSTige with windows VSTs there is a clear degradation in quality between VST interface and LMMS output. Issue is persistent between different VSTs. 
Video: https://www.youtube.com/watch?v=D4TBfOg_Nxg

**Steps to reproduce:** 
1. Add VeSTige track and set instrument to one that has built in keyboard. VST used in video: http://www.vst4free.com/free_vst.php?plugin=VSCO2_Cello_Section&id=2551
2. Compare sound coming from VST interface to sound coming from LMMS

To me it seems like either velocity or some of higher frequencies just get lost along the way. What's strange is that VST itself is perfectly capable of reproducing the original sound. I will update this issue with results on the newest version.

What was tried: Setting velocity to 200%

**Comment by DomClark** [comment]
Can you try changing the base velocity to 127 (the maximum) under the MIDI tab on VeSTige? The keyboard in the VSCO2 instruments plays the sounds at full velocity whereas LMMS uses a lower velocity by default. You may also want to click lower down on the keyboard in LMMS as the higher you click, the lower the velocity used.

**Comment by notxrandr** [comment]
I am currently compiling new version. Will get back with results shortly

**Comment by notxrandr** [comment]
On 160488c
Was able to reproduce same sound with changing base velocity. Sorry for wasting your time, I will close this as non issue now.
