### ISSUE TITLE
Volume slider fixed when loading old 1.0.3 project

### ISSUE THREAD

**Issue by JohannesLorenz** [LMMS/lmms#4549]
After trying to move the master volume slider it will immediately snap back, making it impossible to change the volume permanently.

Steps to reproduce:
* Open 1.0.3
* Write a song, change master volume a bit (no automation)
* Save it, open with stable-1.2

**Comment by PhysSong** [comment]
Related: https://github.com/LMMS/lmms/issues/4268#issuecomment-374813574

**Comment by PhysSong** [comment]
If you didn't save the project with 1.2, could you post affected project file?

**Comment by JohannesLorenz** [comment]
First of all: sorry, it does work now, I must have used an old lmms-1.2 yesterday. Sounds like the old bug @PhysSong pointed out. I'll probably close this soon.

@PhysSong I think I never saved it with 1.2, but I can't guarantee. The file is [here](https://gist.github.com/JohannesLorenz/7edc209ee501734f767f79dbc7f45dac) . The master volume is "Master-Lautstärke" in the savefile, and one can also see other fixed automations ("Tempo").

@musikBear Thanks, removing the automation did indeed solve it for this file.

**Comment by PhysSong** [comment]
#403 covers UI/UX issues related to global automation and is in 1.3.0 milestone. However, I think we might address some part of it if needed.

**Comment by musikBear** [comment]
@JohannesLorenz Yesss 'Global-Automation' is *evil* i tell you *eeeevil* 👿 
-No seriously, its an awful 'feature', and it has been doomed out in consensus already. So the sooner it is kicked from source, the better!

**Comment by JohannesLorenz** [comment]
Well, sorry for waking this deprecated issue up, and thanks for clarifying.

I'll close this: NO BUG.
