### ISSUE TITLE
Mouse jumps when drawing waveform

### ISSUE THREAD

**Issue by GingkathFox** [LMMS/lmms#4553]
This might be a Mac only issue, ill rename if its not. 
Whenever I draw a waveform in a plugin (like BitInvader), the mouse pointer will jump around, making the waveform jump also.

**Comment by tresf** [comment]
Yes, this happens with mouse cursor too, it's not limited to the touch pad.

**Comment by tresf** [comment]
Yes, for some reason the Graph that it uses -- shared among a few other plugins -- has logic which updates the mouse position as you're dragging stuff around.  https://github.com/LMMS/lmms/blob/28a522806bb1a670b460f0bfbf8d6147910dea72/src/gui/widgets/Graph.cpp#L142

This doesn't seem to have a negative impact on Windows or Linux, but on MacOS, this causes the cursor to jump all over the place.  It also lags the animation as if the events are being queued up.

I'm not sure exactly why the disparity in behavior, but this is a good place to start looking for a solution.
