### ISSUE TITLE
Project does not saving "After stopping" feature

### ISSUE THREAD

**Issue by KodzghlyCZ** [LMMS/lmms#4556]
This is not a big issue, but it´s kinda annoying. When I save my project and load it again, this "After stopping" button goes back to default. 
![screenshot_20180826_093118](https://user-images.githubusercontent.com/17799426/44625884-df8f0e00-a912-11e8-8852-716497e7533a.png)

**Comment by musikBear** [comment]
True 
Related #3740

**Comment by tresf** [comment]
We need a meta thread for the transport issues and then consolidate all of them.  Volunteers?  Related #1357.

**Comment by tresf** [comment]
Consolidated into #3740.
