### ISSUE TITLE
Where is custom arpeggiator button ?

### ISSUE THREAD

**Issue by banti101** [LMMS/lmms#4559]
There is a video on YouTube of custom arpeggiator... Now when I open my lmms 1.20r6 there was no customisation button.
[https://www.youtube.com/watch?v=e9c6k7iPljQ](url)

**Comment by PhysSong** [comment]
@banti101 Could you link the video?

**Comment by banti101** [comment]
Yes ofcourse.. wait a little.

**Comment by banti101** [comment]
here it is ...
[https://www.youtube.com/watch?v=e9c6k7iPljQ](url)

**Comment by PhysSong** [comment]
It looks like the uploader of the video wrote #3117 and the video looks like a demonstration of the proposed feature. It might be able in future releases(not in 1.2 series) of LMMS.

**Comment by banti101** [comment]
oooo... ok thanks..
