### ISSUE TITLE
LMMS (kinda) randomly reset itself

### ISSUE THREAD

**Issue by CVTZ** [LMMS/lmms#4560]
When I try to start LMMS it works but it is reset to default, and when I try to open up a project file it won´t open up any VST plugins which are effects, but opens up VST plugins which are instruments. Also it won´t let me open the file which I worked on the last time I used LMMS. I don´t usually report bugs/am a person who knows much about coding so sorry if this is not very helpful...

**Comment by CVTZ** [comment]
Ok so I still don´t know what happened but I figured out how to get everything working again; So for the VST effects I just had to choose the VST plugin directory again, and for that damaged project file I turned that .mmpz.bak file into an .mmpz file and it works again. Still wondering what happened tho

**Comment by SecondFlight** [comment]
If you find a way to reproduce this, please comment here with steps!

For now, I'll go ahead and close this issue.
