### ISSUE TITLE
Specific Projects don't play sound

### ISSUE THREAD

**Issue by kairuip00p** [LMMS/lmms#4561]
I have already searched the web for this and found only one solution (which didn't work). Many people say that the master volume in the mixer was turned to zero so I checked but the master volume was at 100. Are there any ways to fix this?

**Comment by PhysSong** [comment]
We need more information to solve the problem. Could you upload an example project file or take a screenshot of the FX mixer while playing problematic projects?

**Comment by kairuip00p** [comment]
[Copy.zip](https://github.com/LMMS/lmms/files/2328610/Copy.zip)
Idk it might just be my computer but here's the project.

**Comment by PhysSong** [comment]
Your project has a low-pass filter on the master channel with the cutoff frequency of 0Hz. It will block any sounds.
You can either remove the effect or adjust the cutoff frequency.

**Comment by kairuip00p** [comment]
Oh ha ha Thanks I didn't bother checking that sorry for taking up your time.
