### ISSUE TITLE
Optimize LMMS To 60FPS

### ISSUE THREAD

**Issue by MisterTeeXD** [LMMS/lmms#4562]
Hello, so LMMS currently runs at a cap of 30FPS for work flow but it would be nice if it was Optimize at 60FPS, that way we could experience a buttery smooth feel and look in LMMS.

**Comment by SecondFlight** [comment]
It's actually capped at 20. Fixing this is as simple as changing a number, though the current system of sending a frame update signal at an integer number of milliseconds feels a bit wrong to me, and it's possible this should be revisited.

**Comment by SecondFlight** [comment]
Here's the number I'm talking about:

https://github.com/LMMS/lmms/blob/28a522806bb1a670b460f0bfbf8d6147910dea72/src/gui/MainWindow.cpp#L212

**Comment by MisterTeeXD** [comment]
Ah i see it

**Comment by karmux** [comment]
Let's have `1000 / 60` until there is a more elegant solution? It makes waveform and spectrum animations much smoother.

**Comment by SecondFlight** [comment]
That makes sense to me.

**Comment by musikBear** [comment]
How does it look at low-end HW, f.i. CGI-graphic on a Tube-monitor?
