### ISSUE TITLE
Automation Window Closes Unexpectedly

### ISSUE THREAD

**Issue by MisterTeeXD** [LMMS/lmms#4566]
Hello, whenever i try to switch to the automation window when i have the Equalizer Binding to it, it will close unexpectedly.

Video Recording : 
[2018-08-29 01-43-16.zip](https://github.com/LMMS/lmms/files/2331964/2018-08-29.01-43-16.zip)

**Comment by Sawuare** [comment]
Could not reproduce this with RC7.
@MisterTeeXD Could you verify this with RC7?
