### ISSUE TITLE
Enhancement: Optional fill B&B extentions with existing note-pattern

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#457]
Enhancement: Optional fill B&B extentions with existing note-pattern
If a user chooses to extend a B&B pattern, it will quite oten be because he want to make a tiny variation in the pattern. Eg -most- of the pattern will be a copy of the first 4-beats design, the user will only move/ ad/remove few notes. As in fl-s and other DAVs, the engine could aid the user by simply extending the pattern that the user has in the default 4 beats. This should ofcause be meny controlled:
'Extend steps with pattern' 
The B&B menubar has more than suficient space for that menu-item
Also from Fl-s, there is simple option for auto-fill of notes in B&B. Again it is a nice thing to present to the user, and that could be considered too?

**Comment by curlymorphic** [comment]
I am going to take a look at this one. Are there any ideas how to make this optional, new icon, modify key + click

**Comment by tresf** [comment]
I've read this a few times and I'm confused as to what is happening... Can you post a visual of this as well as an alternative explanation of what is being requested?

**Comment by badosu** [comment]
@tresf Basically this was a duplicate of the previous issue.

The difference is that on @musikBear 's original description he wanted it to be able not only to duplicate but to also extend the pattern on fractional steps. e.g. user being able to, having a 2 bars pattern, extend to a 3rd using the first bar (this being a 1/2 extension of the original pattern, instead of the implemented 1/1 by @curlymorphic ).

**Comment by curlymorphic** [comment]
> Basically this was a duplicate of the previous issue.

what issue # is that please?

> i think the simplest way would be to do it just as 'Add steps' eg - add 16 steps/ pr click. The clone-notes should be the first 16 always.

This is what i based my implementation on.

![image](https://cloud.githubusercontent.com/assets/7412852/6569196/9aeb5f58-c6dd-11e4-8e5e-9f7ab19171e3.png)




> e.g. user being able to, having a 2 bars pattern, extend to a 3rd using the first bar

Im confused as to where fractions came in. Is the above screen shot incorrect?

**Comment by tresf** [comment]
I still don't understand the major convenience this offers over simply cloning a pattern.  What use-cases do composers have where they want this functionality?  I fail to see the major benefit this has.  Cloning something from the front to the end just doesn't seem like a button anyone would understand at a glance.  What am I missing here?

**Comment by tresf** [comment]
> Create first 16 steps manually, then extend your pattern, as a clone of first 16, 4 times, and manually edit step 61 and 64.

The more I read this the more it reads like a simple clone pattern operation.  Click once, 16 becomes 32.  Click again, 32 becomes 64.  Perhaps the proposed code implementation is ideal though and I'm over thinking it?

**Comment by tresf** [comment]
As far as the artwork, perhaps we do something like this? (ugly mockup, but add another step and use them to illustrate empty vs. clone?)

![image](https://cloud.githubusercontent.com/assets/6345473/6569741/fca5994c-c6c5-11e4-845f-b58c01e900e1.png)

**Comment by Sti2nd** [comment]
> I still don't understand the major convenience this offers over simply cloning the whole pattern to the end. 

What? Can you do that in LMMS now? I am pretty sure I can't. That's why this is requested, a very neat and time saving feauture.

> Click once, 16 becomes 32. Click again, 32 becomes 64.

But if you want three bars with the pattern you then have to click extra to remove the last bar. Also it would be against the logic of the two buttons "add steps" and "remove steps" which adds and removes one bar of steps. I think only one bar of a simple cloned pattern should be added at a time.

**Comment by tresf** [comment]
Yeah I agree actually.  I had forgotten how closely this resembles the other buttons' behavior. :+1:

**Comment by musikBear** [comment]
pssst.. Not exactly my 'bright' idea. This is one of the features in FLs BB with a little different implementation, but essentially it would work as FLs 'auto-fill'
A later enhancement would perhaps be 'humanizing' the complete auto-generated pattern

**Comment by musikBear** [comment]
I am testing all the new RC features, and i wonder if this feature should (could) include *all* tracks in B&BE
Take a look at this img:
![bbandclonedsteps](https://cloud.githubusercontent.com/assets/6662066/22599620/d7442370-ea37-11e6-8e4b-665af9952c83.jpg)

In top we have a pattern with two BB-instruments, but 3. and 4. track are resp. a sample, and an automation-track.

The second part of the img shows the result after a cloning of the two top tracks. 
Now both the sample, and automation-track are 'wrong'. They need to be completely redone, but there really are no option to do that.
What i think is that the sample, and an automation-track actually also should have been cloned, and then placed in context of the cloned instrument-tracks.
Is that possible?

**Comment by BaraMGB** [comment]
I think this is worth to be a new issue. @musikBear

**Comment by musikBear** [comment]
@BaraMGB New issue, but surely it belongs here -I just do not have any *re-open* button
![noreopen](https://cloud.githubusercontent.com/assets/6662066/22693679/8b72f5c4-ed44-11e6-8f93-b1400cbcaf28.jpg)
I dont believe that button is for everyone, as i said before

**Comment by zonkmachine** [comment]
I too think that this should be a new issue. As for the mechanics of issues I found [this answer](http://stackoverflow.com/questions/21333654/how-to-re-open-an-issue-in-github/21333938#21333938) on stackoverflow for you.

**Comment by musikBear** [comment]
@zonkmachine 
> I found this answer on stackoverflow for you.

Thanks! Now i know what to say to @tresf next time he says 'Reopen it, then' 😈 
> you cannot re-open your own issues if a repo collaborator closed them

Oki you both think this is worth a new issue, i will make it 👍

**Comment by tresf** [comment]
>  Now i know what to say to @tresf next time he says 'Reopen it, then'

Agreed.  I'll adjust my verbiage to say "Please request a reopen" instead of "Please reopen".
