### ISSUE TITLE
Automation track inside Beat+Bassline editor

### ISSUE THREAD

**Issue by Lyrcaxis** [LMMS/lmms#4576]
Say I want to make a change at the 19th bar, bassline editor will think I want to make it on the 19th bar of whatever's inside the bassline editor, and since they're just 16 steps(1 bar), it will never trigger.

There's a reason no-one uses bassline editors and the wrong implementation of scope is one of them. 
I'd say make tracks controllable from the automation track within the bassline editor to make it useful :)

![image](https://user-images.githubusercontent.com/32474602/44958266-7c8b1180-aee6-11e8-8ce5-7e1186ecd645.png)

**Comment by musikBear** [comment]
Nah, this is foiled-usage
An AUT is active from the point of inserting, relative to the note-track. You should not insert an Aut-curve at bar 19, you should _place_ the AUT-block AT bar 19, but that would mean, that your note-track should be displayed in piano-roll, not as a B&B-event-track, as in your picture, witch actually only covers one bar _loop_!
In wiki there is a chapter about 'philosophy in B&B tracks' : 
https://lmms.io/wiki/index.php?title=Composing_Bass_Lines_and_Drum_Sequences#Philosophies_of_pattern_design
Read that :)

**Comment by PhysSong** [comment]
@Lyrcaxis What you exactly want to do?
- If you want to change the value when reached the 19th bar of the *song*, you should use an automation track in the song editor.
- If you want to change the value when reached the 19th bar of the *beat/bassline*, it doesn't make sense the length of the BB pattern is shorter than 19 bars.

**Comment by Lyrcaxis** [comment]
> change the value when reached the 19th bar of the song, you should use an automation track in the song editor.

I was suggesting this should be allowed to be done from within the bassline editor, since all patterns in wiki's link require a new Bassline Editor track even for the slightest changes in the beat. I personally don't like to clog-up my Song-Editor for minor changes like that.

Well then, I'll make do with using the Song editor to do this kind of Automations, or get used to one of the patterns. Thanks for your responses 👍
