### ISSUE TITLE
Drawing messed up when something on top.

### ISSUE THREAD

**Issue by CYBERDEViLNL** [LMMS/lmms#4577]
I'm using the latest master on Arch Linux with Fluxbox.

Edit: It behaves this way when I put anything on top.

Replicate:
1. Put anything on top.
2. Open another widget and try to move it around.

~~1. Add the `Spectrum Analyser` as effect to a instrument.~~
~~2. Set the  `Spectrum Analyser` on top.~~
~~3. Open the Automation editor.~~

![](http://funkyimg.com/i/2KX4C.png)

**Comment by CYBERDEViLNL** [comment]
Well I couldn't bring any other sub-window to the front or back for that matter, they just stayed at the same index. It started tearing on movement of a sub-window.

Strange thing is I can't replicate it anymore, it is somehow fine now. I'll close this issue for now until it comes up again.

**Comment by DomClark** [comment]
Did you have a VST loaded at any point without restarting LMMS? It looks like #4183.

**Comment by CYBERDEViLNL** [comment]
@DomClark ; Nope, I had no VST loaded when it occured. Also restarted LMMS then and it still occured, the next day (after PC restart) it was gone.

**Comment by musikBear** [comment]
> after PC restart

You nailed it! A graphic buffer issue. @CYBERDEViLNL Dont *sleep* PCs! shut them *down*

**Comment by CYBERDEViLNL** [comment]
Yeah that's what I meant by restart (full shutdown, next day boot it up agian.). I will be clearer with my words next time.
