### ISSUE TITLE
Better support for scalling in windows

### ISSUE THREAD

**Issue by SaleCar** [LMMS/lmms#4579]
I have 4K monitor and 250% scalling in windows and app looks unusable. When use High DPI scalling override, text ans items are bigger but blury. 

![image](https://user-images.githubusercontent.com/39879027/45110410-72654f00-b142-11e8-9d9d-eb53d1596e3b.png)

**Comment by musikBear** [comment]
Support Question
@SaleCar Follow these instructions:
http://neoshamon.blogspot.dk/2015/06/adobe-app-scaling-on-high-dpi-displays.html?view=sidebar 

Someone claims that win10 has a special option:
1. Shift-RightClick the application icon and select 'Properties'.
2. Go to the 'Compatibility' tab.
3. Check 'Override high DPI scaling behaviour'. There are three options. 'System (Enhanced)' works for lmms.

If you @SaleCar tries this win-method, please report back, i would like to know its validity, before adding it in wiki

**Comment by SaleCar** [comment]
As I mentioned, I tried that option. Then text and items are stretched to be bigger but it looks ugly because it's blurry.

**Comment by musikBear** [comment]
@SaleCar Am i to understand that neither of the two options i gave you, creates a useable UI?
You tried *both* and *both* is unsatisfactory ?

**Comment by SaleCar** [comment]
Yes. I tried both options and all work the same. Just strech items so looks bigger but now it is all blurry. Just like you have low-res picture streched to full screen. That way program can be used but it looks ugly. You buy 4K monitor so you can have ultra sharp image without pixels (just like on mobile phones) but with Lmms you must use it blurry. For example, you can compare Lmms blurry streched interface with another similar program that supports scalling native.

![image](https://user-images.githubusercontent.com/39879027/45178636-87abad80-b216-11e8-912d-22efde846593.png)

![image](https://user-images.githubusercontent.com/39879027/45178862-305a0d00-b217-11e8-8f0b-8961510928b5.png)

**Comment by musikBear** [comment]
...Nahh if you @SaleCar have *that* quality, all is well. Of cause no magic exists, that will turn anything into 4k..
