### ISSUE TITLE
Splash screen is not shown on awesomewm

### ISSUE THREAD

**Issue by zervankoru** [LMMS/lmms#4581]
Hello. If I using awesomewm, then splash screen with lmms logo is grey window.

**Comment by tresf** [comment]
Thanks for reporting.  I just tested this on Ubuntu 18.04 and it displays just fine.  

![awesome](https://user-images.githubusercontent.com/6345473/45965440-76281b00-bff6-11e8-8253-5445ef486950.png)

As you've indicated on the [wxWidget's tracker](https://trac.wxwidgets.org/ticket/18216#comment:9), we just use Qt's `QSplashScreen` implementation, so it's not really our bug.

**Comment by zonkmachine** [comment]
As seen in https://github.com/awesomeWM/awesome/issues/2292, linked above, this is not particular to LMMS. I think this issue is better tracked with the asesomeWM project. Closing.
