### ISSUE TITLE
Show B&B patterns in Song Editor on zoom less than 800%

### ISSUE THREAD

**Issue by Sti2nd** [LMMS/lmms#459]
![b b results in nothing](https://f.cloud.github.com/assets/6373430/2422531/5893afa8-ab8f-11e3-8a5f-59fb817fb068.PNG)
When I Ctrl + drag notes from the B&B Editor to Song Editor LMMS shows the pattern as empty. They are actually B&B patterns when zooming in. So LMMS needs a way to show B&B patterns in Song Editor not only at 800%-1600% zoom, but on all zoom levels? At least 100%-1600% IMO.

**Comment by zonkmachine** [comment]
Change `ppt >= 96` to `ppt >= 24` [here](https://github.com/LMMS/lmms/blob/27007c258a7b83b8fb89bea753c9b4d767686ef3/src/tracks/Pattern.cpp#L972) to cover 200%-1600% zoom. Lower resolution will simply grey out on my screen.

**Comment by zonkmachine** [comment]
Beat Notes was instead removed completely from the Song Editor in https://github.com/LMMS/lmms/pull/5988
