### ISSUE TITLE
LMMS crashing by Piano roll resizing in 4K

### ISSUE THREAD

**Issue by WinLin97** [LMMS/lmms#4592]
Hi!

This not requires any comment:
https://drive.google.com/open?id=1MDNOvZvRTRZpmg5Tu_P8EAR6eOXfGYgO

How to recreate?
1. Open LMMS (on fullscreen 4K)
2. Open Piano roll and maximize or resize the window to max vertically.
3. Tadam! LMMS crashed!

**Comment by PhysSong** [comment]
Duplicate of #4098.
