### ISSUE TITLE
LMMS Accessibility for screen readers

### ISSUE THREAD

**Issue by pavelvlcek** [LMMS/lmms#4594]
Dear developers,
QT 5 has accessibility features for screen reader users, Window, Linux and Mac. A lot of blind music composers are looking for accessible software, which they can to use. I am screen reader user, I use Win, Linux and Mac, so I can test accessibility, if you like. So, please, can you review interfaces and integrate QT accessibility vidgets?

**Comment by Spekular** [comment]
Duplicate of #4590
