### ISSUE TITLE
LMMS Crashes When Duplicating A Instrument

### ISSUE THREAD

**Issue by MisterTeeXD** [LMMS/lmms#4595]
Hello, i have encountered a bug where if i play the song on the song editor, leave it playing and then duplicate a sample track instrument block on the Song Editor, LMMS will crash.

**Comment by jibin1573** [comment]
This has happened with me, once. 
OS: Windows 10 (Version 1704 I guess)
LMMS 1.2.0 RC series

I don't remember which RC version it was  But, even in RC 6 I'm really scared of cloning any instrument, while I'm playing the song (especially big projects)

**Comment by SecondFlight** [comment]
This is in RC6, correct?

**Comment by MisterTeeXD** [comment]
Yes, its in RC6

**Comment by jibin1573** [comment]
And I think, the actual problem might be with vestige and not the native instruments. (I'm not sure though!)

**Comment by MisterTeeXD** [comment]
This actually happened when i tried to duplicate a Sample Track Instument Block in the song editor while the song was playing

**Comment by SecondFlight** [comment]
Thanks for the extra info. By "sample track instrument", do you mean audio file processor, or do you mean the actual sample track?

**Comment by MisterTeeXD** [comment]
The actual Sample Track

**Comment by PhysSong** [comment]
@MisterTeeXD do you have a reliable steps to reproduce this?

**Comment by MisterTeeXD** [comment]
Yes, just open up a project, click play and leave the song playing, then control left click a instrument block on the timeline and drag it to a empty field on the same instrument field and LMMS should crash

**Comment by jibin1573** [comment]
When I tested this (LMMS R1.2 RC6 on windows 10, v1803), the projects with native instruments (ZynAddSubFX) did not crash on cloning. But, the projects with vestige (Tforce Alpha Plus) did hang and was on the verge of crashing, when cloning during song playback.

**Comment by JohannesLorenz** [comment]
Works for me as well (on Linux, RC7). @MisterTeeXD Can you make a video? Also, does it happen with all instruments?

**Comment by lukas-w** [comment]
No response in five months, closing as not reproducible.
