### ISSUE TITLE
LMMS Keeps crashing but finally showed an error.

### ISSUE THREAD

**Issue by HypersDevelopment** [LMMS/lmms#4596]
I was recently making some music, until LMMS crashed... I have no idea why, all I know is that I lost half an hour of work. Speeking of which, saving sometimes generates broken saves. I tried loading my save, but _**of course**_ it had to have a badly generated save. Please help me with this...
![capture](https://user-images.githubusercontent.com/35753810/45593022-4cedf780-b931-11e8-9580-963023e68f61.PNG)

**Comment by PhysSong** [comment]
The dialog says that Visual Studio failed to debug the LMMS crash.
I guess it crashed while saving projects. Could you provide more details, e.g.
- your LMMS version
- Instruments used in the project before LMMS crashed

?

**Comment by HypersDevelopment** [comment]
My version is 1.1.3
I do not remember the instruments used before the crash.

**Comment by SecondFlight** [comment]
Try updating to the latest beta, and let us know if you are still experiencing crashes. The beta is a few years newer and has significant stability improvements.

You can find the beta here:
https://lmms.io/download/

**Comment by HypersDevelopment** [comment]
Okay. Just one question. Do the 1.1.3 lmms saves port over to the beta?
