### ISSUE TITLE
Minor GUI issues

### ISSUE THREAD

**Issue by Nymbius** [LMMS/lmms#4597]
There are some minor gui issues (2).
The first one is the LFO Graph.
In the LFO Graph the wave stops before the Graph box ends.
I simply fixed it by making the LFO Graph box a little bit smaller to fit the LFO wave perfectly (as shown in the picture).

The second one is the Master Volume which I fixed(?) by adding the correct spacing.
On the right is the original and on the left is my "Fixed" version.
![image](https://user-images.githubusercontent.com/39532803/45600131-d8ca5700-b9f7-11e8-8143-476a59264092.png)

**Comment by PhysSong** [comment]
How did you fix the first issue? Could you create a pull request with the first fix?
I think the second change needs some discussion. That's not my area, but it might be intentional.

**Comment by Nymbius** [comment]
I simply made the LFO Graph box smaller as shown on this pic : 
![image](https://user-images.githubusercontent.com/39532803/45621966-b4678c80-ba82-11e8-831a-e9db18467846.png)
As for the Master Volume I could make Strawpoll and post it to the discord server to se what people think.

**Comment by PhysSong** [comment]
I think @Umcaruje/@RebeccaDeField may review your ideas and changes.

**Comment by tresf** [comment]
@Nymbius can you please submit a pull request with these changes?  We'd be happy to have them!

**Comment by RebeccaDeField** [comment]
@Nymbius did you edit the .svg source to make this change or the raster .png? If you need some help making a pr there should be support for that on discord, or alternatively, you could tell us the exact pixel difference you made for it to line up right so that someone else can make the pr for it.

**Comment by tresf** [comment]
@RebeccaDeField his PR is available here: #4613

**Comment by Nymbius** [comment]
Where can I find the .svg files?

**Comment by RebeccaDeField** [comment]
@tresf  Ah, looks like I missed the PR, thanks. 

@Nymbius 
Design elements can be found here: https://github.com/LMMS/artwork/blob/master/src/DesignElements2.svg

Icons can be found here: 
https://github.com/LMMS/artwork/blob/master/src/Icons.svg
