### ISSUE TITLE
Problems with the sample track

### ISSUE THREAD

**Issue by Gabrielxd195** [LMMS/lmms#4598]
Good night friends. First of all my apologies for any bad spelling (well, I do not speak English, it is translated and I only speak Spanish). for several months I have seen the improvements they have made in LMMS, and in each version they feel those improve, but others still apply mostly those of the sample track as:

1- They can not be added to the mixer or have any type of connection.
2- The wave changes its size according to the tempo, but the audio remains intact, does not change speed or adapt to the tempo.
3- It slows down when you extenuate or enlarge the wave with Shift.
4- Lmms can export in mp3 format but in the sample track you can not import mp3 files. (although I do not know if that has to do with mp3 being proprietary)
5- In the BB Editor, audio samples do not work, sometimes the empty ranges appear.
6- You can not divide or merge the audio tracks.
7- When you play with the trasnporte the audio stays intact, and does not change tone.
8- And I think the biggest problem of the sample track: it does not record audio.

That is the current status of the sample track
![antes problemas con el sample track](https://user-images.githubusercontent.com/26127693/45725426-d814fa80-bb88-11e8-8d66-e79753d0e50c.png)

I recognize that the lmms sample track is not an ideal wave editor, but it is still useful when it comes to voices, although it has things to improve such as:

1- It would be just a cutting tool, to divide and join the wave
2- A connection with the mixer.
3- It would be quite useful in the sample track to be able to edit an audio file with the piano roll, to modify its musical notes (not as it is done in audio processor, because this modifies the tone but affects the speed), it would be very useful to edit voices and modify their tuning.
4- You should improve the selection tool, because it selects all the audio and not the desired parts of it.
5- It would be useful to be able to see the wave divided into its two stereo channels when enlarging the image with Shift, (as in audacity)
6- And above all, the possibility of recording audio (previously I had suggested this idea but they closed the thread).

The same cursor can be used to cut the wave in the desired parts in this way
![despues problemas con el sample track](https://user-images.githubusercontent.com/26127693/45726077-bec17d80-bb8b-11e8-9cfa-26080240f4fa.png)

Obviously they are problems that others have also noticed, but ideas are worth gold, and with every update they make, it brings many changes. regards

**Comment by PhysSong** [comment]
Thank you for using LMMS! Most of those issues are covered by #1471.
Suggestion 2 and 6 are in progress, see #3866 and #4531.
I also added your suggestion 4 into #1471, thanks!

**Comment by Gabrielxd195** [comment]
Thanks for accepting my suggestions. The truth is that I love this application, and I admire how they strive to improve this wonderful application. regards

**Comment by PhysSong** [comment]
I think #1471 and #2000(mp3 import) covers this issue now. If they don't, please let me know!
