### ISSUE TITLE
Way to expand search results tree

### ISSUE THREAD

**Issue by foolo** [LMMS/lmms#4609]
When searching for instruments and samples i often use the search function.
When i search (by typing in the search box), the results list tree is collapsed, so when browsing through it, i need to double-click every subfolder. It becomes a lot of double-clicking.

I am wishing for a an "expand all" functionality.

**Comment by tresf** [comment]
@foolo thanks for reporting.  This is a duplicate of #4214 by symptom (perhaps not by description).  Related #760.  Marking as duplicate.  This is a good first issue, I'll mark the other bug as such.

**Comment by foolo** [comment]
Hmm. I don't think that's the same issue. That issue is about removing the tree structure, right? 
It says "Desired: Please shortlist the matching items without the nodes structure."

I definitely don't want that. I still want to see the directories, but expanded.

**Comment by tresf** [comment]
> I definitely don't want that. I still want to see the directories, but expanded.

No worries, I've corrected the other one to include your feedback.  The shortlist is a bad idea as each result loses context.
