### ISSUE TITLE
Add wet/dry panning knob to all LMMS effects

### ISSUE THREAD

**Issue by LostRobotMusic** [LMMS/lmms#4611]
Please notify me if this has already been requested.

Currently every LMMS effect has a Wet/Dry, Decay, and Gate knob.  A panning knob would be another fantastic thing to add, which works in companionship with the Wet/Dry knob.  It simply changes the Wet/Dry of individual ears.

This would be useful for many things:

1. I'm sure there's already a request out there to change the Equalizer so it allows different gains for each ear, this would take care of that perfectly.
2. When you want to apply an effect to just one ear, this allows that.
3. You can also have strange and unique methods of obtaining more stereo width in your music.
4. Other advantages would depend on the plugin, there are many things you can do with a feature like this!

For anybody who wants to do this with LMMS's current capabilities, here's the process they have to go through for every effect:

1. Send instrument to two different busses
2. Use the Amplifier effect to mute the left/right sides, one side per bus
3. Use two copies of the effect with different Wet/Dry values
4. Send both back into another FX bus

With that method, keeping everything sane would be... not fun.  Not to mention that the requirement of two copies of the same effect may have a very undesirable impact on weaker computers.

I understand that this would be difficult to do since the size of an LMMS effect is made to fit three knobs.  Here's the only idea I can think of (the length of the effect has not been modified, I simply moved the Controls button over):

![image](https://user-images.githubusercontent.com/34612565/45935479-0d469180-bf69-11e8-91ff-e6525e9302bb.png)

Hopefully somebody can find a neat way to implement this feature, I feel like LMMS has needed this for a long time.

**Comment by tresf** [comment]
@DouglasDGI functionally, sounds like a dup of https://github.com/LMMS/lmms/issues/1974 although he suggests it on the mixer itself.  I'm not sure how common this is, but I can't see any major reason to say no to it.

**Comment by DouglasDGI** [comment]
@tresf I did see #1974 before making this thread, but they're asking for something that pans the actual audio, while I'm asking for something that changes the Wet/Dry of effects in separate ears, which has a completely different outcome.

Do you think that image I posted of the effect with the pan knob looks acceptable?  If so, I'll see how far I can get with adding it and making it work.

**Comment by DouglasDGI** [comment]
OH, I forgot to ask, should the knob be called "PAN", or should it be called "L/R"?  I just realized that L/R is just as long and may be a more accurate term...

**Comment by karmux** [comment]
"L/R" describes better what it does I think.

**Comment by BaraMGB** [comment]
We use PAN in the tracks. I think PAN is more consistent.

**Comment by DouglasDGI** [comment]
@BaraMGB That may be misleading though, because this doesn't pan the actual audio, it simply changes the Wet/Dry of individual ears.  Some people may move the PAN knob on there expecting it to pan the audio, when that isn't what it actually does.

Here's an example of how it works: https://www.youtube.com/watch?v=8gjdnLWUCgs

**Comment by SecondFlight** [comment]
That is (almost) equivalent to mixing a the wet signal with the dry signal and using a naive panning algorithm to pan the wet signal. The difference would be that, when the wet pan is at the center, the dry signal is silent.

PAN makes perfect sense IMO.
