### ISSUE TITLE
Unable to load vst in RC7 or any other RC

### ISSUE THREAD

**Issue by iamdigitalghost** [LMMS/lmms#4620]
I have used every RC now and not once have I been able to load a vst with vestige. If I open a project made in 1.1.3 my vst works but loading a new vst into an existing or new project is a fail. It shows the loading popup for 1 second and then nothing. Vestige shows no vst loaded. I'm running 64 bit xubuntu 18.04. Is there a problem with wine stable vs staging implementation? Or is it because I have 1.1.3 installed? I'm not removing it by the way since it's the only one that works for me.

**Comment by tresf** [comment]
@iamdigitalghost I think I reproduced your problem.  There's a slight typo online when installing wine from winehq... 

```diff
- sudo apt-get install wine-staging
+ sudo apt-get install winehq-staging
```

Without the `hq` in the package name, `wine` is never added to the default search path and LMMS won't pick it up.
