### ISSUE TITLE
Inaccurate Time Units Display

### ISSUE THREAD

**Issue by Nesdood007** [LMMS/lmms#4623]
Hello everyone. I am using the LMMS 1.2.0rc7 binary from [https://lmms.io/download/#windows](https://lmms.io/download/#windows) on x64 Windows 10. I have discovered that the Measure Counter (Bar Counter) and Beat Counter in the Time Units Display is inaccurate. It looks fine when playing a song at first, however it eventually goes out of sync with the actual measure or bar being played. This is especially bad when the tempo is changed. I don't recall this being an issue with any previous stable version of LMMS. I think what is happening here is that the current bar is being calculated by using the current time (in Minutes, Seconds) in the song and the current Tempo. There must be some inaccuracy with that calculation that causes the Bar measurement to slightly shift out of sync with the music. I have linked in two examples of this problem below. As the songs progress, check the Bar measurement and somewhere toward the middle of the song, it should become obvious that there is some synchronization issue.

[Example 1](https://lmms.io/lsp/?action=show&file=13828)
[Example 2](https://lmms.io/lsp/?action=show&file=13829)

**Comment by softrabbit** [comment]
Looks like it's fixed in master. Good candidate for backporting?

**Comment by zonkmachine** [comment]
This appears to have been fixed as a part of issue #2112. Closing.
