### ISSUE TITLE
LMMS 1.2.0 rc7 some little things that are overlooked

### ISSUE THREAD

**Issue by Gabrielxd195** [LMMS/lmms#4626]
Hi guys. I downloaded lmms 1.2.0 rc7, and I saw the list of improvements and bug fixes, and I really appreciate the effort. each update brings many improvements, but I think also in this version they overlooked some small errors that together make more uncomfortable the use of lmms, those errors had been mentioned before, such errors as:

- Empty copies of automation clips
![error de copia de automatizacion](https://user-images.githubusercontent.com/26127693/46123760-30ce3e00-c1ee-11e8-8cdd-40c7147de798.png)
I have seen other people complain about this mistake. When copying an automation clip, it comes out with empty automations, and to recover them you have to assign the fader or parameter again.

- The selection tool does not delete groups by pressing '' delete ''.
![error de borrado multiple](https://user-images.githubusercontent.com/26127693/46124002-7dfedf80-c1ef-11e8-8f01-1370b4af04eb.png)
This is not a problem when you have to delete two or three clips, but it is very cumbersome to have to delete many clips one by one with the mouse wheel.

- Without self-reproduction
![error de autoreproduccion](https://user-images.githubusercontent.com/26127693/46124101-0d0bf780-c1f0-11e8-95fe-f458a6d81603.png)
Of this I spoke in another thread, and I think that this suggestion was duplicated. when choosing the samples in the browser, you have to be constantly clicking to reproduce them, as a result of this, the bb editor is full of unnecessary samples and this is wasting time, it is best to reproduce automatically by pressing down arrow or up.

These errors may seem '' irrelevant '' but when using lmms, they are very annoying. these errors must be taken into account, mention only these three because they are the ones that personally stand out most, I do not know if there are other threads talking about this, but however they should be taken into account and corrected. and if I have something to thank, is that they have introduced Carla again in this version, it was much needed in RC6. anyway, thank you. regards

**Comment by PhysSong** [comment]
> Empty copies of automation clips

#3781
> The selection tool does not delete groups by pressing '' delete ''.

Implemented in #3649 and will be available in the future version of LMMS(not in the 1.2 series)
> Without self-reproduction

#871

**Comment by Gabrielxd195** [comment]
> > Copias vacías de clips de automatización
> 
> [# 3781](https://github.com/LMMS/lmms/issues/3781)
> 
> > La herramienta de selección no elimina grupos al presionar '' eliminar ''.
> 
> Implementado en [# 3649](https://github.com/LMMS/lmms/pull/3649) y estará disponible en la versión futura de LMMS (no en la serie 1.2)
> 
> > Sin autorreproducción
> 
> [# 871](https://github.com/LMMS/lmms/issues/871)

It's a good thing that I had already commented on this before, although I expected them to correct that in the current version rc7. but what do you mean that it will come out in future versions and not in the 1.2 series ?. (sorry but I'm not very informed), perhaps there is another series apart from 1.2; perhaps there will not be rc8?

**Comment by PhysSong** [comment]
> what do you mean that it will come out in future versions and not in the 1.2 series?

I mean the feature is only available in our development branch. It'll be available when/if we release 1.3 beta or nightly/rolling builds.

**Comment by Gabrielxd195** [comment]
> > ¿Qué quieres decir con que saldrá en versiones futuras y no en la serie 1.2?
> 
> Me refiero a que la función solo está disponible en nuestra rama de desarrollo. Estará disponible cuando / si lanzamos versiones beta 1.3 o nocturnas / rodantes.

When they release betas 1.3, do they have a scheduled date? but is the rc8, or rc7 will be the last of the 1.2 series?

**Comment by PhysSong** [comment]
RC means release candidate, which is released before 1.2.0 stable releases. We don't have a scheduled date for 1.3 yet.

**Comment by Gabrielxd195** [comment]
> RC significa versión candidata, que se lanza antes de las versiones 1.2.0 estables. Todavía no tenemos una fecha programada para 1.3.

Do you already have a scheduled date for the stable version 1.2.0, which feature is missing for the stable version ?, or will you see an rc8 version with more improvements as they have done so far?

**Comment by NETMANSKY** [comment]
@musikBear It's still not working :( But we have been used RC7 already. I would like to live up to 1.3 but... who knows, God only.

**Comment by NETMANSKY** [comment]
@Gabrielxd195 My dear comrade! I would like to live up to 1.3 but... who knows, God only.

**Comment by tresf** [comment]
@Gabrielxd195 search, comment, request reopen, don't dump your thoughts in bug reports.  Don't put the same thought in two reports.  Don't create issues without searching first.  If unsure, ask on Discord https://lmms.io/chat, #support channel.  Closing this out so that the OP can learn how to use our tracker properly.
