### ISSUE TITLE
Selection tool in automation editor.

### ISSUE THREAD

**Issue by Gabrielxd195** [LMMS/lmms#4627]
The automation editor does not have a selection tool. It would be useful to be able to select several automation points simultaneously and be able to move them, copy them, delete them, etc.

Currently it is like this:
![antes herramienta de seleccion](https://user-images.githubusercontent.com/26127693/46128693-51a08e80-c202-11e8-9207-c54079061dae.png)

With the implemented tool it would look something like this:
![despues herramienta de seleccion](https://user-images.githubusercontent.com/26127693/46128711-62510480-c202-11e8-9c98-42505671171c.png)
You need that tool here, it would be useful. regards

**Comment by tresf** [comment]
Please consolidate this into #4630 as requested and close
