### ISSUE TITLE
Rendering an empty loop section

### ISSUE THREAD

**Issue by pikachuk** [LMMS/lmms#4629]
Hello, I'm posting this here because it would be useful to allow lmms to export the loop section without any notes because some vsts work by adding the notes directly into them and playing them when the playback of lmms reaches the notes in the vst (an image would help more to understand)
![unknown](https://user-images.githubusercontent.com/16335601/46163447-91f81f00-c28b-11e8-9385-b086cf5a4b2e.png)
In the current case, the vst is piapro, a vst that is used to work with VOCALOIDS and making songs with them, Piapro studio in itself is almost a complete software, but the bpm, playback etc are synced to lmms and the sounds play correctly https://clyp.it/3sq5xcy5 (I rendered this by muting a track)

it would be useful in this case to avoid to have to use specific workarounds only to be able to render a vst working this way, there should maybe have a specific option for "export the loop section" in the context menu that would allow it even if there's no notes in the lmms editor itself

**Comment by pikachuk** [comment]
![unknown](https://user-images.githubusercontent.com/16335601/46164086-4c3c5600-c28d-11e8-8731-739cd125f143.png)
Oh and what I'm suggesting by "allowing" is to be able to do it without this error message

**Comment by Z3R0C** [comment]
set an empty pattern from Beat/Bassline 0 after your loop.

**Comment by pikachuk** [comment]
@Z3R0C As I said, it's doable by adding an empty track/beat pattern, but it's still a workaround, it should be doable natively without having to use  workarounds

**Comment by PhysSong** [comment]
FYI, it's implemented in the development version: #4031
I'm not sure, but I think #4031 should cover this. You'll be able to export the project correctly without the workaround once we release the development version.

**Comment by PhysSong** [comment]
Closing because already implemented in `master`.
