### ISSUE TITLE
VestiGe Bug with rc7 - crashes when I load a plugin *.dll

### ISSUE THREAD

**Issue by LostPr3acherProject** [LMMS/lmms#4638]
I apologize for my complete lack of programming knowledge ahead of time. I know the optimum GitHub engagement is someone who brings a problem WITH a possible solution in hand to discuss. regardless, I have found a bug and it's pretty disheartening, though the rest of rc7 is incredible (and yes, I read the notes for the update). 
 I used Serum successfully with rc6 and was really amazed I could use something that high-end within an open-source DAW. I also use Synth1, Elec7ro, DVS MicroTrance, DKS the Grand, etc. I cannot use any of them now and it's killing me. **When I try to load ANY vst plugin through vestige, LMMS locks up indefinitely until you're forced to close it down**. I'd provide screenshots, but this is pretty cut and dry:
I drag in Vestige, I open it up, I click the folder icon and select my plugin .dll of choice, and when I click ok, the program locks up and then forces me to shut it down: "Would you like to wait for the program or shut it down?" after which point I shout obscenities and restart the program.
I'm going to have to go back to rc6 for sure until this is ironed out. I know you all don't get paid for making this, so I know these issues come case by case and as people have time available to fix them. I humbly appreciate EVERYTHING you do. Thank you ahead of time for any time spent figuring this out. - Matt

**UPDATE:**
**I found out that unlike earlier releases, I now have to uninstall the previous version of LMMS to install a new one, or it has a bunch of install errors regarding the QT dlls. I went back, uninstalled it, then went a step further and deleted the few folders that remained, and THEN reinstalled rc7, and now my plugins work. Unsure why it didn't happen to me with earlier versions, but regardless, I should have uninstalled things anyway and now learning has occurred. I'd have deleted this posting, but evidently that is not a feature offered by GitHub and I apologize for the seeming noob spam post.**

**Comment by DomClark** [comment]
> I apologize for my complete lack of programming knowledge ahead of time. I know the optimum GitHub engagement is someone who brings a problem WITH a possible solution in hand to discuss. regardless, I have found a bug

Don't worry about not having a solution - issues with proposed solutions are awesome, but having a bug report is still much better than not having one!

Can you try restarting your computer, then installing rc7 again? Sometimes the VST host processes don't exit properly, so when you update the installer can't overwrite them. This means you get the old VST host process with the new LMMS, which will likely crash as you've described. Restarting gets rid of any stuck processes.

**Comment by tresf** [comment]
> I found out that unlike earlier releases, I now have to uninstall the previous version of LMMS to install a new one, or it has a bunch of install errors regarding the QT dlls. 

Not true and #support channel on Discord needs to be better about their advice. :)

What happens is when LMMS has an issue often a process hangs in memory and locks those files.  This has been true for all LMMS releases.  In the details section of Task Manager look for `lmms.exe`, `RemoteZynAddSubFx.exe`, `RemoteVstPlugin.exe`, `RemoteVstPlugin32.exe` and terminate any processes matching those names.  Once you do that, the installation should succeed.

See also: https://github.com/LMMS/lmms/wiki/Troubleshooting#clean-install

**Comment by tresf** [comment]
>  I'd have deleted this posting, but evidently that is not a feature offered by GitHub and I apologize for the seeming noob spam post.

No worries, closing as resolved.
