### ISSUE TITLE
lmms 1.2.0-rc7 fails to build with fluidsynth 2.0.0

### ISSUE THREAD

**Issue by dvzrv** [LMMS/lmms#4640]
I'm currently rebuilding a bunch of software against fluidsynth 2.0.0 on Arch Linux.
Sadly that introduced an [API change](http://www.fluidsynth.org/api/index.html#NewIn2_0_0).

LMMS currently fails to build with it: 
[lmms-1.2.0rc7-fluidsynth2.0.txt](https://github.com/LMMS/lmms/files/2434148/lmms-1.2.0rc7-fluidsynth2.0.txt)

Any help in integrating/patching the `sf2_player` would be greatly appreciated!
Plus, I think this should probably be fixed before releasing 1.2.0!

**Comment by PhysSong** [comment]
Thank you for reporting! I'll look into this.

**Comment by PhysSong** [comment]
There are two types of errors:
- Missing macros
https://github.com/FluidSynth/fluidsynth/pull/385 have introduced new settings for reverb and chorus. It also removed old macros. I think we can either hardcode their values or use `fluid_settings_getnum_default`.
- Incomplete types
https://github.com/FluidSynth/fluidsynth/pull/334 made some type definitions private. Since they provide getters/setters now, we may use that. A tricky part is `iteration_next` because they also changed the function prototype.

I'll work on it in a few days and provide a fix.

**Comment by dvzrv** [comment]
@PhysSong thanks for the fast reply!

Please note: During rebuilding against fluidsynth 2.0.0, I realized, that nearly none of the projects implementing it, are compatible to the new API.
Keep in mind: Ideally LMMS should be compatible to 1.x and 2.x. Linux distributions will only be able to use the new API, once all projects have switched (or are able to implement both APIs).

**Comment by PhysSong** [comment]
@dvzrv Can you test if my [fluidsynth2](https://github.com/PhysSong/lmms/tree/fluidsynth2) branch compiles with FluidSynth 2.0?

**Comment by dvzrv** [comment]
@PhysSong will try to do that later today! Thanks! :)

**Comment by trebmuh** [comment]
Please, note that a new 2.0.1 version as been [released yesterday](https://github.com/FluidSynth/fluidsynth/releases/tag/v2.0.1).

**Comment by schnitzeltony** [comment]
Have sent similar for carla (see https://github.com/falkTX/Carla/pull/765) and looked into https://github.com/PhysSong/lmms/tree/fluidsynth2. Wouldn't it be better to ask fluidsynth on first instantiation for default values instead of pinning them?

**Comment by trebmuh** [comment]
For reference, done by @schnitzeltony as well : [Calf & fluidsynth 2.0](https://github.com/calf-studio-gear/calf/pull/203).

**Comment by PhysSong** [comment]
> Wouldn't it be better to ask fluidsynth on first instantiation for default values instead of pinning them?

@schnitzeltony Is that about hard-coded macro values? I can do that, but I think it will decrease readability a lot.

**Comment by schnitzeltony** [comment]
Since I have not contributed (much) here: it is just a suggestion.

> Is that about hard-coded macro values? I can do that, but I think it will decrease readability a lot.

Yes - advantage would be that if fluidsynth changes defaults, these changes are taken. Had the similar issue at carla so I decided to collect all defaults required at one place.

**Comment by PhysSong** [comment]
Okay. I'll try that and see if it looks okay.

**Comment by PhysSong** [comment]
@dvzrv Updated the [fluidsynth2](https://github.com/PhysSong/lmms/tree/fluidsynth2) branch(with a force-push). Tested with both 1.1.9 and 2.0.1, worked fine. Also addressed https://github.com/LMMS/lmms/issues/4640#issuecomment-428913292 .

**Comment by schnitzeltony** [comment]
Thanks for addressing my comment. I think hard-coding defaults for fluidsynth 1.x is OK - future changes in 1.x are unlikely. Have not yet build tested (will do this evening), but would be happy to see this merged: lmms is the last on my list...

**Comment by PhysSong** [comment]
PR opened: #4678
Can anyone test that?

**Comment by dvzrv** [comment]
On 2018-10-24 22:02:50 (-0700), Hyunjin Song wrote:
> Can anyone test that?

Will try to do it this evening! Sorry this takes so long.

-- 
https://sleepmap.de

**Comment by dvzrv** [comment]
@PhysSong I can confirm that your branch builds with fluidsynth 2.0.0 and 1.1.11!
Thanks so much and sorry again for the delay!

**Comment by jorgicio** [comment]
> PR opened: #4678
> Can anyone test that?

Tested the patch in Gentoo, and working fine with fluidsynth 2.0.0. Thanks.
