### ISSUE TITLE
Improvements for the FX Mixer

### ISSUE THREAD

**Issue by Gabrielxd195** [LMMS/lmms#4644]
Hi guys. The mixer fx of lmms is very simple to be the '' mixer '' of a large daw like lmms, it can not even be maximized. I think this image says it all:

![mezclador no maximiza](https://user-images.githubusercontent.com/26127693/46392543-b733c580-c6af-11e8-94ca-c98a54c31880.gif)
Look, it's just a simple window that can barely be resized horizontally.

I think that the mixer of a daw is a very important section, since this part is especially for the mix, this is where the effects and complements are eliminated and added and therefore, it deserves a better interface. using other daw, it occurred to me that the lmms mixer can be improved by adding some improvements, such as:

1. **Add maximize button.**
It is necessary to maximize the mixer for better vision and organization of channels and effects.

2. **Select several channels simultaneously.**
Using the selection tool or pressing '' ctrl '' to delete, rename, several channels simultaneously.

3. **Channel grouping arrow for buses.**
Currently when it comes to having many channels and buses is a mess. It would be very useful to be able to group all the channels in their respective buses. each bus could show or hide its assigned channels by simply pressing the display arrow.

4. **Play buttons.**
The typical buttons play, stop, repeat, fast forward and rewind to avoid having to change windows to do these functions, it is more comfortable to do them from the same mixer.

5. **Playhead in the mixer.**
As strange as this idea may seem, but having to constantly change windows to edit a specific point of the song is very cumbersome, because it is better to do everything from the same window of the mixer ?, this saves time. with this function implemented, the playback head moves as it happens in the other editors, you can do zoon, mark, repeat and manipulate at will, to check and edit the desired parts of the song. this would facilitate the user when mixing.

Well, with this image I try to explain what I said before:
![mezclador maximizado con barra de rep](https://user-images.githubusercontent.com/26127693/46394480-3d9fd580-c6b7-11e8-9889-14e08fbb9ba7.png)

I repeat these ideas may be strange averages, but even if they are not implemented, the lmms mixer has to improve its interface. the mixer of a daw is very essential, therefore when working with muhcos plugins this must be ordered, to facilitate mixing. regards

**Comment by jibin1573** [comment]
Is this related to maximising the FX Mixer #3258?

**Comment by Gabrielxd195** [comment]
> ¿Está esto relacionado con maximizar el mezclador de [efectos # 3258](https://github.com/LMMS/lmms/issues/3258) ?

It is not, he proposes to resize the window vertically, while I am suggesting several ideas, apart from this one. regards

**Comment by jibin1573** [comment]
These are very useful ideas @Gabrielxd195!

**Comment by Gabrielxd195** [comment]
> These are very useful ideas @Gabrielxd195!

Thank you. I just want to cooperate at least contributing ideas, I really like this lmms, and I love to see how you strive to improve it.

**Comment by musikBear** [comment]
@tresf Consolidate all Mixer improvements? 

@Gabrielxd195 Some are known, one is a sore toe ..

**Comment by tresf** [comment]
> @tresf Consolidate all Mixer improvements?

Crosslink dupes please?  We need help, not orders please.

**Comment by musikBear** [comment]
@tresf 
Ehhh... did you read my question as an order?? -Meant as a suggestion, and i will  do it, if you believe i can express my self understandable ..

**Comment by tresf** [comment]
> i will do it

Please do.  We desperately need help.  This tracker is out of control to a point that we may need to move enhancement requests to another repository.

**Comment by tresf** [comment]
@musikBear I've edited your bug report here as an example: https://github.com/LMMS/lmms/issues/3740.

Please follow suit if you can help out.

**Comment by musikBear** [comment]
>Please follow suit if you can help out.

will do, unless hit by sledge, this weekend

**Comment by tresf** [comment]
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.
