### ISSUE TITLE
No full RELRO for lmms binary and some libraries

### ISSUE THREAD

**Issue by dvzrv** [LMMS/lmms#4645]
I'm currently working on upgrading the Arch Linux package to 1.2.0-rc7.
After building, our [namcap](https://wiki.archlinux.org/index.php/Namcap) tool is running automatically to check for common problems with packages and their binaries.

It seems, that the lmms binary and some of the libraries created, lack [full RELRO](https://tk-blog.blogspot.com/2009/02/relro-not-so-well-known-memory.html).
Arch Linux' defaults to set this in `$LDFLAGS`, but this is not picked up by CMake with lmms.

It would be very benificial to have full RELRO for libs and especially the executable!

Here's my verbose build log with

```
  mkdir build && cd build
  cmake -DCMAKE_INSTALL_PREFIX=/usr \
        -DWANT_QT5=ON \
        -DWANT_SOUNDIO=OFF \
        -DCMAKE_INSTALL_LIBDIR=lib \
        -DCMAKE_MODULE_PATH=/usr/share/ECM/find-modules \
        -DCMAKE_PREFIX_PATH=/usr/include/wine/windows \
        -DWINE_INCLUDE_DIR=/usr/include/wine/windows \
        -DWINE_LIBRARY=/usr/lib32/wine \
        ..
  cmake -LAH ..
  make VERBOSE=1
  make DESTDIR="${pkgdir}" install
```

in case you wanna have a peek (also at the namcap output at the end):
[lmms-1.2.0-rc7.txt](https://github.com/LMMS/lmms/files/2444356/lmms-1.2.0-rc7.txt)

**Comment by PhysSong** [comment]
> Arch Linux' defaults to set this in `$LDFLAGS`, but this is not picked up by CMake with lmms.

It indeed is, see e.g. 2 lines after `[ 19%] Linking CXX executable ../lmms`.
I'm not sure about the `namcap`, but I think its output is somewhat wrong.

**Comment by tresf** [comment]
For those curious, the log indicates 5 files:

```
lmms W: ELF file ('usr/bin/lmms') lacks FULL RELRO, check LDFLAGS.
lmms W: ELF file ('usr/lib/lmms/RemoteZynAddSubFx') lacks FULL RELRO, check LDFLAGS.
lmms W: ELF file ('usr/lib/lmms/libvestige.so') lacks FULL RELRO, check LDFLAGS.
lmms W: ELF file ('usr/lib/lmms/libvsteffect.so') lacks FULL RELRO, check LDFLAGS.
lmms W: ELF file ('usr/lib/lmms/libzynaddsubfx.so') lacks FULL RELRO, check LDFLAGS.
```

@PhysSong hardening measures seem like a good addition, but how would we specify them through CMake normally?  We we just missing a build flag for the plugins that claim RELRO is missing?

**Comment by PhysSong** [comment]
The environment variable was applied correctly. With the flags, I was able to get an executable with full RELRO. It turns like the `namcap` tool has had a bug and it was fixed a couple of weeks ago. There are no releases with the fix yet.
https://git.archlinux.org/namcap.git/commit/?id=4bf61fa3c5ecb928b2aaa526f8f56f3b5284d25f

**Comment by tresf** [comment]
@PhysSong thanks for researching, switched status to "response required", since there's nothing to be done on the LMMS-side of things.

**Comment by dvzrv** [comment]
@PhysSong thanks for the hint! Will rerun again, after a new version has been released!
As what namcap is trying to achieve is a somewhat complex task, there are a lot of false positives.
That being said: Sorry for the noise! :)
