### ISSUE TITLE
Labels for relevant component

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#4648]
I suggest that labels for the most relevant component is added to each issue. Searching for ex. 'Song-editor' or 'Mixer' returns absurdly many topics. If Labels are used to really focus on *the* specific component, it will eventually be time saving, and aid the general overview.
Lmms have:
* Main
* Song-editor
* Piano-roll
* Mixer
* Controller-rack
* Project-notes
* B&B-editor
* Automation-editor
* Info
so 9 new labels.

**Comment by tresf** [comment]
@musikBear do you volunteer to classify all 700 issues?  I don't care for this idea, personally.

**Comment by tresf** [comment]
... and let's use Discord, not create more topics please.

**Comment by musikBear** [comment]
> do you volunteer to classify all 700 issues?

@tresf 
I have done worse, like sorting banana-flies in microscope .... so why not. If it would be beneficial. Yes i can do that. I will need label making rights, though, but you dont want it at all -or?

**Comment by musikBear** [comment]
@tresf -ok- if needed, you know where to find me,
