### ISSUE TITLE
0.92 Glitch- low importance: Rules for 'edited project' 

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#465]
win32 -sometimes brand new loaded projects will default have an asterix at their name, and if the project is atempted , either 
replaced
closed
initiated
lmms wil open the 'project not saved'  popup
It is unlogical, and look 'wrong', but is in no way an 'must do' issue

**Comment by Umcaruje** [comment]
@musikBear could you please offer some steps to reproduce this issue?

**Comment by musikBear** [comment]
No, this is apparently random behavior, but should be given lowest priority possible. In fact, its better that the project asks for a save, than the user looses his edits  (f.i. if bocks are moved in S.E.
I would take that to the extend, that opening always should be regarded as a edit, at least until all actual changes **do** count as *edited*

**Comment by Umcaruje** [comment]
Well, when you find a way to reproduce this, fix the title and the description of the issue and reopen it.
