### ISSUE TITLE
Consolidating (FX) Mixer threads

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#4650]
Consolidating all *FX-Mixer* ao *Mixer* *Issues*.
Issues are grouped in Main *Label-Groups* (Bold) with Sub-groups (Italic)

### (FX)-Mixer
**Enhancements**
* Replace '"export tracks" with 'pr-FXchannel-export #414 
* A play-this button on each FX-mixer-channel #2513
* Show mixer channel on each instrument #2563
* Select Multiple Mixer Channels #3155
* Make SEND+arrow more intuitive #4187

*Core*
* additional jack channels audio output on Mixer-channel #524

*Gui*
* FX-Mixer: Reordering Mixer-channels to mirror song-editor #605
* Mixer Groups #606
* Signal meters dB indication #1213 #4458
* Highlight instruments when assigned FX-mixer strip is selected #1216
* Indicator on FX channels with no route to master #1224
* Mixer peak indicators (for each channel). #1271
* All-in-one routing window #1986
* Drag instrument track label to mixer to assign instrument's FX channel #2011
* Make the mixer color editable enhancement #2704
* Replace "Add" Text With Plus Icons gui #3242
* User cannot see the FX Mixer connections at a glance: Some solutions #4181

*ux*
* create, assign rename one FX-mixer channel for every added instrument #1215 #3315
* select multiple mixer strips reroute all to newly created FX-channel #1218
* Re-route orphan FX-mixer strips to Master #1219
* Import a Mixer setting-files #1680
* Add secondary faster scroll to FX-mixer-sliders #3098
* Drag-&-Drop adding of VST plugins in FX-Mixer's effects chain #3150
* Use tittlebar for showing FX channel name information #3239
* Rename "FX-Mixer" to "Mixer" #3300
* Implement channel templates #4023

*Ux* & *Gui*
* FX Chain /sends routing chain/ I/O tab #1823
* New UI Concept - Single Window #1911
* Mixer needs a pan knob #1974
* Channel Name Tooltip Style Tag Labels #3257
* Allow Vertical Stretching To The Mixer Window #3258
* About track/FX channel mute automation #3639

*Meta* & *Bug*
*Better Color Handling #1665

*Core*
* Engine decoupling proposal #2387

**Core**
*Bug*
* NotePlayHandles may be processed multiple times per mixer round #2606

**Bug**
* Mixer volume percentage labels are off by a factor of 100 #2340
* Replacing instrument with a favorites resets mixer channel #2564
* Browser Audio Preview and Metronome Sounds Affected By Mixer Effects
#3186
* Tooltip for channel-names in FX-mixer inconsistent #3321
* Crash in Fx-Mixer #3983

*Gui* & *Upstram*
* Odd behaviors when renaming the master mixer channel. #3861

*Gui* & *Ux*
* Mixer window loses focus when moving channels #3969
* Undoing fader change only undoes partially #3973

**Un-labeled**
* Fader Location In The Center At 100% Volume (0dB) #3253
* LMMS Effect Utility - Mixer Send #3294
* Effect groups/sub-chains #4402
* Effect Chain Wet/Dry #4403
* Improvements for the FX Mixer #4644

**Comment by tresf** [comment]
All items migrated to #4877.  Thanks @musikBear!

**Comment by tresf** [comment]
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.
