### ISSUE TITLE
Effects chain drag&drop reordering

### ISSUE THREAD

**Issue by RoxasKH** [LMMS/lmms#4655]
I know that you can reorder effects in FX tab (on the instruments and on the mixer) by doing right-click --> move down/move up, but i think it will be a real improvement if we just can drag and drop them up and down, in this way reordering them would be more comfortable. 
Just think i put a limiter at the very beginning of my fx chain and now i want it to be the last one of the chain. At the moment i have only two possibilities, do right-click-->move down a lot of time (either all at one time or every time i put a new effect on the chain), or delete it and adding a new one.
With this improvement i could just drag it all down at one time and it's done. Also i think it would be more intuitive for new users, and that a lot of actual users would agree with me.

Hope this will be implemented, i thanks programmers for the work they've down since now and the support they give here and on other platforms.

**Comment by RoxasKH** [comment]
Ok now i know it's a duplicate lol

**Comment by tresf** [comment]
Should be consolidated into https://github.com/LMMS/lmms/issues/605.

**Comment by Gabrielxd195** [comment]
This idea is very useful that you mention it. when we add many effects in the mixer fx, to move some, you have to give many clicks, and this is very uncomfortable I've already experienced, but dragging them would be done in a matter of seconds.

**Comment by xy124** [comment]
I'll try to fix this ;)

**Comment by zonkmachine** [comment]
Cool!

_Hint! In your last PR you worked from master. Create a separate branch instead._

**Comment by xy124** [comment]
@zonkmachine Ok I'll create the feature branch `feature/effect-chain-dnd`

BTW: I got simplistic drag'n'drop in the effect chain working already. I wonder If it wouldn't be cool to allow drack'n'drop also between instrument properties effect chain and the FxMixer effect chain / 2 different Instruments' effect chains.
Further: I recognized that there are multiple drag'n'drop methods used in lmms' code. So is there a best practice. Especially to drag'n'drop the order of instrument tracks this is done differently than the drag'n'drop of e.g. new instrument tracks into song/BB editor...
Latter seems to be done cleaner with QDrag ... 

Especially later one could imagine to allow drag'n'drops of instrument tracks between BB-Editor and song editor if one would change the reordering implementation of the instrument tracks to use QDrag as well ;) - If you want I could try to do this later as well ;)



P.S.: Merry Christmas! :santa:

**Comment by tresf** [comment]
> I wonder If it wouldn't be cool to allow drag'n'drop also between instrument properties effect chain and the FxMixer effect chain / 2 different Instruments' effect chains.

As long as it's visually identified as a copy operation, this seems like a super helpful feature.  I guess "moving" may be useful at time (e.g. decide to move an FX stack to the mixer) but that seems less intuitive than a shortcut to copy (e.g. Ctrl/⌘).

**Comment by xy124** [comment]
@tresf yep going to implement moving first, ctrl-copy will be easy then

**Comment by musikBear** [comment]
@xy124 we have one quite similar enhancement request: Make FX-chain saves, in a new type of separate file, and reload of this file, into any preset. Maby you can see a clever solution to this, now that you have a good understanding of the FX-chain :)

**Comment by tresf** [comment]
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.
