### ISSUE TITLE
Missing names

### ISSUE THREAD

**Issue by Andrewer11** [LMMS/lmms#4656]
Hi i have an issue with the 1.2.0 rc7 version of LMMS
i have installed the rc5, rc6 and the rc7 too but it doesnt matter the names of the tracks are missing
and idk how is there a setting what i turned off? or a bug? is there a solution to get it back without reinstall?
thx
![image](https://user-images.githubusercontent.com/15068193/46760228-c8915900-ccd1-11e8-8990-327cb22913a9.png)

**Comment by PhysSong** [comment]
You should turn off the **Compact track buttons** setting to show the name of tracks.

**Comment by musikBear** [comment]
@Andrewer11 
You find this setting Edit| Settings| General Settings|
![rc7settings](https://user-images.githubusercontent.com/6662066/46818850-7a885e00-cd82-11e8-87ad-6cddf2ecc641.JPG)

**Comment by Andrewer11** [comment]
Thanks so much 
Now the issue can be closed <3
