### ISSUE TITLE
No input devises listed.

### ISSUE THREAD

**Issue by 20RT** [LMMS/lmms#4658]
New user to LMMS, but have used Linux for many years. I have a Arturia MiniLab connected via USB but no devises show up in the Input selection. I am not familiar with the General Settings so I am not sure if the MiniLab is not showing up because Audio/Midi settings are not correct or if it is a device incompatibility. It is just a midi controller. No devices are showing up. I can play notes with the computer keyboard and mouse. Is there an instruction guide that will give me more information on settings? Or do you know what I'm doing wrong?

**Comment by 20RT** [comment]
May have solved my own problem.
Audio Setting - ALSA (default)
Midi Setting - ALSA Sequencer (default)
Doesn't always work but with a few attempts it will.

**Comment by zonkmachine** [comment]
@20RT Which version of LMMS do you use? If you're not on the latest beta version, now is the time to try it out. https://lmms.io/download/#linux

**Comment by lukas-w** [comment]
Closing this issue because its author has solved the issue.
