### ISSUE TITLE
2 Connected Plugins In Automation Cancels Out

### ISSUE THREAD

**Issue by MisterTeeXD** [LMMS/lmms#4659]
Hello, i really dont know if this is a dup but whenever i connect 2 Plugins (For Ex. Reverb and EQ) to an Automation track then both of the Connected Plugins will be canceled out. So far i have seen this happened in RC6

**Comment by PhysSong** [comment]
The information you provided is not enough to investigate the issue. Could you provide a sample project or more details on automated controls?

**Comment by MisterTeeXD** [comment]
Hello, here is the requested Project File : 
[Problem.zip](https://github.com/LMMS/lmms/files/2476437/Problem.zip)

**Comment by musikBear** [comment]
@MisterTeeXD 
No you make a mistake.
The span of CALF-Reverb, is 0.4 to 15
The span of LMMS-EQ, is 20 to 20000
You cant have 2 controllers with so different span, connected to the same Automation-block/curve
Use 2 Automation tracks, and 2 separate AUT-blocks, and never try to connect more than one *type* of controller to the same AUT-block.

**Comment by MisterTeeXD** [comment]
Ok then
