### ISSUE TITLE
Allow user to change icon for AppImage

### ISSUE THREAD

**Issue by aunetx** [LMMS/lmms#4663]
On Gnome with LMMS as AppImage format, even if I created a shortcut in the dash for this appimage, when it is opened the app shows another icon than the one used by my system (Numix Circle) and the icon is not well integrated to the dash.

I don't know if this is possible using appimage, but maybe it would be great :

- to make the app more integrated in the shell (use the icon of the icon theme for example)
- or at least to allow the user to change the icon

> lmms version 1.2rc7

Thanks a lot for all your job, à bientôt !

**Comment by JohannesLorenz** [comment]
Can you please label this bug as one of "bug" or "enhancement"? And probably some other labels...

**Comment by zonkmachine** [comment]
I think only team members can add labels.

**Comment by tresf** [comment]
> the icon is not well integrated to the dash.

`appimaged` is supposed to do this, which is a separately maintained project.   It's not perfect, but it's the best that AppImage offers. https://github.com/AppImage/appimaged#appimaged
