### ISSUE TITLE
Release a stable version

### ISSUE THREAD

**Issue by Qwertie-** [LMMS/lmms#4664]
Looking at the release history the last stable version was 1.1.3 in 2015. Since then there have been 7 RC releases. Both Ubuntu and Fedora are using this ancient release for the reason I assume is there have been no releases other than RC releases since that version. The downloads page on the lmms website provides the RC release and in my experience the new RC releases are more stable than the old 1.1.3.

Just renaming the current release or releasing a new version which is not an RC should help get newer versions out to people. For ages I thought LMMS was just mostly unmaintained and buggy until I found out there is years of development that hasn't been given a stable release.

**Comment by PhysSong** [comment]
Thank you for paying attention to LMMS. There are a few remaining bugs which should be fixed before the stable release.
We have improved stability a lot and are trying to release the stable 1.2 version in this year. I'm not sure how long you should wait, but I can say it won't be too long.
Thank you for your patience. :)
