### ISSUE TITLE
detune does not work with zyn

### ISSUE THREAD

**Issue by Daniele71** [LMMS/lmms#4669]
Hi guys, detune does not work with Zyn.
Fine in tripleoscillator but not in zyn.
Lmms-rc7.appimage (but iIm quite sure it is also broken on 1.1.2)

![lmmsdetune](https://user-images.githubusercontent.com/40473719/47305704-a03b2000-d62a-11e8-9250-e753633796ad.jpg)

Known issue ?

**Comment by JohannesLorenz** [comment]
This is known. zyn does not offer this as functionality, and LMMS uses zyn via MIDI, which doesn't offer the interface. So this is impossible.

The best thing you can do is, e.g. if you never play two notes at a time, use regular instrument-detune. Or, if you have multiple at a time, use mutliple zyns.

I'd suggest to close this.
