### ISSUE TITLE
RC7 Tab ENV/LFO Random LFO *display* broken

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#4673]
![rc7lfosandombroken](https://user-images.githubusercontent.com/6662066/47358803-2444e480-d6cb-11e8-9c05-fbe23a19d6a9.JPG)
I stopped after loading 5 instruments, because its obvious that the issue is inherited  
This is *only* a graphic display bug. The logic, eg a working random LFO -is ok

**Comment by zonkmachine** [comment]
I can't replicate this. (LinuxMint 17.3)

**Comment by DeRobyJ** [comment]
Neither can I, Win10
It works as normal on 1.2 RC7

**Comment by DeRobyJ** [comment]
Yes I did choose the random shape.
I guess we need someone else with a 32bit OS to test it.

**Comment by tresf** [comment]
Closing as no one can reproduce.
