### ISSUE TITLE
Calf LADSPA plugin isn't used as a submodule

### ISSUE THREAD

**Issue by binfather** [LMMS/lmms#4676]
On Nov 5, 2017 the Calf LADSPA plugin was moved to a submodule(ae291e0709b544bc51a831ea606211801fac14b6), but the releases since then still contains the old code.

**Comment by zonkmachine** [comment]
The releases have all been on the **stable-1.2** branch and the plugin submodule changes is against the **master** branch.

**Comment by binfather** [comment]
So there is not way to merge it? There are missing features in the old Calf version.

**Comment by zonkmachine** [comment]
I think there are unofficial binaries floating around from the master branch.
Ask away in our Discord site: https://discordapp.com/invite/3sc5su7
Preferably in the `#support` channel.

> So there is not way to merge it?

In the stable-1.2 branch? No. We are closing in on an official lmms-1.2 release so no new futures are going in now.
