### ISSUE TITLE
Multitap Echo sometimes crashes when filter steps above 16 are changed

### ISSUE THREAD

**Issue by DouglasDGI** [LMMS/lmms#4679]
I haven't had a lot of time to figure out exactly what's going on with this, but I've managed to get LMMS to crash with a Segmentation Fault every time rather quickly.  Sometimes it crashes as soon as those filter steps are changed, other times it doesn't crash until audio is played after those steps are changed.

I am using LMMS RC6.395 on Ubuntu.

Here is the GDB output (edited after PhysSong's first comment):
```
Thread 24 "Mixer::fifoWrit" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff611ae700 (LWP 12503)]
0x00007fff810d44e7 in TriggerGateEffect::runFilter(float (*) [2], float (*) [2], OnePole<(unsigned char)2>&, short) ()
   from /root/lmmsnew6/lmms/build/plugins/libtriggergate.so
```

**Comment by PhysSong** [comment]
> `TriggerGateEffect::runFilter`

What is the effect? It's not part of current LMMS.
If you have a backtrace without the effect, please let me know. Also, you can get a backtrace by typing `bt`(crashed thread) or `thread apply all bt`(all threads).

**Comment by PhysSong** [comment]
The crash happens on `master` branch. `stable-1.2` is fine.
#3259 introduced some changes in `Graph::drawLineAt`. It leads to emitting `samplesChanged` signal with invalid ranges(endpoint is off by one).
I can fix it soon.
