### ISSUE TITLE
Some Soundfont Files Wont Play

### ISSUE THREAD

**Issue by MrTeeXD** [LMMS/lmms#4682]
Sometimes when LMMS loads up for the first use and you left click to preview soundfont files, it wont make a sound, even when restarting LMMS does not do anything to fix that issue

This is an issue in RC7

**Comment by musikBear** [comment]
@MisterTeeXD Can you link to the SF-file in question?

**Comment by MisterTeeXD** [comment]
Certainly, here you go :
http://freedrumkits.net/download/freedrumkits-net-violin-arco-sf2/?wpdmdl=1282&_wpdmkey=5bd506883cb2b

**Comment by musikBear** [comment]
@MisterTeeXD Link expired -nothing there

**Comment by zonkmachine** [comment]
http://freedrumkits.net/download/freedrumkits-net-violin-arco-sf2/

**Comment by musikBear** [comment]
@zonkmachine Link no good

**Comment by zonkmachine** [comment]
Because now the site is down.

**Comment by zonkmachine** [comment]
Now the site is up again. You need to register your email with them in order to download though.

**Comment by musikBear** [comment]
nae.. i rarely do that, seam to lead to spams.. thanks anyway!

**Comment by zonkmachine** [comment]
> This https://musical-artifacts.com/artifacts/11/Mega_Man_X.zip
> -ought to be a 'MEGA-man' game-music sf2...

This bug: https://github.com/LMMS/lmms/issues/4386
You are off topic and guessing wildly. Please see the original issue.

**Comment by musikBear** [comment]
Dont know why my search did not bring orr. topic up
> guessing wildly

Ehrrr is "Maby it is not a proper sf2 build?" a 'wild' guess..
