### ISSUE TITLE
Connected MIDI Will Not Register To VST Plugin GUI

### ISSUE THREAD

**Issue by MisterTeeXD** [LMMS/lmms#4687]
Hello, i do not know if this is a possible bug but when i have a window open for the VST Plugin GUI and i try to press a key, it does not register the pressed key.

**Comment by PhysSong** [comment]
Have you set up the MIDI input in the VeSTige instrument?

**Comment by MisterTeeXD** [comment]
How do i do that

**Comment by PhysSong** [comment]
1. Open the VeSTige instrument
2. Go to the MIDI tab(keyboard icon)
3. Turn on "ENABLE MIDI INPUT"
4. If there's another button with a keyboard icon, press it and check the device you want to connect

**Comment by MisterTeeXD** [comment]
Alright, will go ahead and try that and report back with results

**Comment by MisterTeeXD** [comment]
It worked thank you

**Comment by MisterTeeXD** [comment]
It worked thank you
