### ISSUE TITLE
Can't reduce the window's width with two screens

### ISSUE THREAD

**Issue by cyriellecentori** [LMMS/lmms#4689]
I am on Manjaro Linux, and recently, I updated LMMS to RC7 version. And I have one problem : I can't reduce the window's width.
When I try to resize the window, it shows me the window's size, but the numbers given seem to be smaller than the real window size. The problem can come from the fact I have to screens, because when I unplug one, LMMS works totally fine So my temporary fix is to unplug my second screen, launch LMMS and then plug the screen again, and LMMS works fine too, so it seems the problem is located during LMMS's initialization.
If you need more details, I will be happy to give some.

**Comment by SecondFlight** [comment]
Did this occur in RC6, or were you updating from 1.1.3?

**Comment by cyrioncentori** [comment]
I was updating from 1.1.3, because LMMS has been updated in the Manjaro repositories, and the last version was 1.1.3.

**Comment by SecondFlight** [comment]
I can't test this as I don't have multiple monitors. Is there anyone else with multiple monitors that can confirm this?

**Comment by cyrioncentori** [comment]
I just tested with RC6 (I used the AppImage), and I don't have this problem.
