### ISSUE TITLE
Debian sid integration

### ISSUE THREAD

**Issue by jasp00** [LMMS/lmms#4695]
I would like to integrate Debian sid support. I would also like to help release version 1.2; I might have some spare time. What is the current workflow? `master` to `stable-1.2`? `stable-1.2` directly?

**Comment by PhysSong** [comment]
@jasp00 Welcome back! We commit stuff for 1.2 into `stable-1.2`, then merge them into `master`.

**Comment by jasp00** [comment]
@lukas-w, what is going on with Qt5? qt5-x11embed is not integrated. Are we going to use it or do we fix Qt directly?

**Comment by PhysSong** [comment]
@jasp00 Can you elaborate it? This repository submodules `qt5-x11embed` which depends on the private component of core module and the X11 extras module.

**Comment by jasp00** [comment]
> the module should be rebuilt on Qt upgrades

This is inconvenient. Either we use this extension or we fix Qt and use `createWindowContainer()`. In any case, the solution should be integrated in Qt.

Also, this submodule structure is troublesome. These sources are not in the tarball and neither are packaged dependencies.

I am speaking from a distro point of view. Let us see how we organize this.

**Comment by PhysSong** [comment]
> or we fix Qt and use `createWindowContainer()`.

IIRC @lukas-w said the `createWindowContainer` implementation worked fine with Qt 5.9.
> Also, this submodule structure is troublesome. These sources are not in the tarball and neither are packaged dependencies.

There was a discussion on it, #4100.

**Comment by jasp00** [comment]
My job is done. I would like to invite @RossGammon, current maintainer in Debian, to join this project and take advantage of this Debian sid integration.

**Comment by lukas-w** [comment]
>  @lukas-w said the `createWindowContainer` implementation worked fine with Qt 5.9.

I think this was false alarm from my side. I works better, but still not as good as `qt5-x11embed` and IIRC it was stated on Qt's bug trakcer that `createWindowContainer` is not intended for our use case.
