### ISSUE TITLE
Error: Piano roll does not save the selected scale.

### ISSUE THREAD

**Issue by Gabrielxd195** [LMMS/lmms#4704]
Hi guys. I have noticed that LMMS does not save the selected musical scale of a project. I am currently working on two projects: in one the musical scale is C Major, and in the other is C # major. the problem is that when I'm working on a project, before I close it I keep it with the selected musical scale, but when I move on to the other one, the musical scale of the previous project is marked in the new project, and so on, every time I open and I close my projects, I have to select the musical scales constantly.

For example:

In this project he is working with the major musical scale of C#. before closing it I save it with the selected musical scale.
![escala de c seleccionada](https://user-images.githubusercontent.com/26127693/48390491-43ce9c00-e6d0-11e8-9cba-7a05f2a22436.png)

In this other project I am using the C major scale, I keep it with the selected scale.
![escala de c mayor](https://user-images.githubusercontent.com/26127693/48390551-9ad47100-e6d0-11e8-816c-405d496f3523.png)

And finally. I reopen the first project (that of the first image), I had saved it before with the C# major scale selected, however when I opened it again, this C increased the scale of the previous project (that of the second image).
![escala de c sin seleccionar](https://user-images.githubusercontent.com/26127693/48390662-2cdc7980-e6d1-11e8-883c-20b9243d446f.png)

I do not know if someone had reported it before, but it is clear that it is a mistake or for sure that the developers had not noticed it. but when you have two projects and you know musical theory this is not a problem, but when you have many projects it becomes annoying to have to constantly change scales. regards

**Comment by musikBear** [comment]
correct -use the *Notes* to write your scale & key

**Comment by Gabrielxd195** [comment]
> correct -use the _Notes_ to write your scale & key

This way it can work. but it is not supposed that the function of scales is for that, to mark the notes of the selected scales?. this way we save time, but this function of piano roll of LMMS has that error that before mensione, and it does not save the selected scale.

**Comment by Veratil** [comment]
@Gabrielxd195 if you're able to build the `master` branch, my PR for saving scale with the project (#5146) has been merged. I believe this would be considered fixed?

**Comment by zonkmachine** [comment]
Fixed in https://github.com/LMMS/lmms/pull/5146

**Comment by muhuk** [comment]
I am using version `1.2.2` (from Debian repository).  When I reload the file (without exiting) the scale and marked notes are retained. But if I quit and start the app again both scale and marked notes are lost.
