### ISSUE TITLE
Xpand!2 arpeggio gets out of sync over time

### ISSUE THREAD

**Issue by DomClark** [LMMS/lmms#4706]
Reported by `@fleur.#7769` on Discord. The following steps were given to reproduce the bug:
* Create 1 bar chords for 4 bars
* Loop the whole pattern several times
* It slowly slips out of sync

I have successfully reproduced the bug.

**Comment by NETMANSKY** [comment]
Desynchronization also occurs when you use CUTOFF / LFO :(

**Comment by DomClark** [comment]
I don't think that's related to this issue. The issue here appeared to be inaccurate timing information provided to the VST, but that's computed separately to LMMS's LFOs.

**Comment by NETMANSKY** [comment]
@DomClark I have been said about native instruments but not VST only. Im agree it's an
> inaccurate timing information
And it have no improved in LMMS.

**Comment by musikBear** [comment]
DomClark wrote
> The issue here appeared to be inaccurate timing information provided to the VST,

In fact it is even:
The issue here appeared to be inaccurate timing information provided to **this** *specific* VST - right?
Not general issue, but an issue with **one specific** VST

**Comment by DomClark** [comment]
> And it have no improved in LMMS.

Perhaps not, but it's not related to this issue, so let's try to keep things on topic here.

> The issue here appeared to be inaccurate timing information provided to this specific VST - right?
Not general issue, but an issue with one specific VST

The timing information was inaccurate for all VSTs, but most others seemed to cope with it better than this one.

Technical details:
The `ppqPos` field in the `VstTimeInfo` structure, which tells the plugin the musical position, was always a little ahead of the `samplePos` field, which tells the plugin the audio position. The difference was always between 0 and 256 samples, which is between 0 and 6ms at 44100Hz. I have no idea why a small bounded difference here led to an ever-increasing error in the arpeggio timing, but fixing the `ppqPos` value appeared to fix the bug.

**Comment by NETMANSKY** [comment]
Is it fixed already? I mean ARP and Cutoff/LFO.

**Comment by DomClark** [comment]
> Is it fixed already? I mean ARP and Cutoff/LFO.

The Xpand!2 built-in arpeggio timing is fixed, hence this issue being closed. I'm not sure what the cutoff/LFO bug you're talking about is, so I can't comment on whether it is fixed, but if it's the same one you mentioned earlier then it's not related to this issue and you'd be better off asking elsewhere or opening a new issue.
