### ISSUE TITLE
marked notes ignored DEMO

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#471]
(0.92 winxp 32)
Do you remember this one?
Its a random occouring thing, and everyone havent seen it. Now it happend as i tested arpeggio (whitch btw acted REALLY strange, but not reproduceable)
..So a video with that random bug
I dont think this should be given any serious attention, -especially not regarding 1.0 -for now its just a 'FYI'
link to vid http://www.youtube.com/watch?v=QZ1b3BI2VwY

**Comment by zonkmachine** [comment]
@musikBear This was reported over three years ago. If you haven't seen this since I suggest we close this as likely fixed as part of some other issue. It can always be reopened.

**Comment by musikBear** [comment]
@zonkmachine Agree. Not reproduceable and maby a fluke. Put it asleep :)

**Comment by zonkmachine** [comment]
:tractor:
