### ISSUE TITLE
LMMS Fails To Open Correctly

### ISSUE THREAD

**Issue by MrTeeXD** [LMMS/lmms#4710]
Anyone having a problem where if you try to open LMMS via a Project file, it fails to open correctly and just instantly quits?

Im on RC7

**Comment by DomClark** [comment]
Does the project file load correctly if you open it from within LMMS? Does this happen with all project files, or just one specific file?

**Comment by MisterTeeXD** [comment]
Yes, the project loads correctly within LMMS.

It does happen with all projects

**Comment by musikBear** [comment]
@MisterTeeXD
please post your OS (+service-pack-version)
> It does happen with all projects

Also those shipped with lmms? Try one of the 'cool-songs'

**Comment by MisterTeeXD** [comment]
I use Windows 10 and i have tried the ones shipped with LMMS and they open perfectly

**Comment by musikBear** [comment]
> i have tried the ones shipped with LMMS and they open **perfectly**

Ahh! so it is your browser that has issues..
try this:
* Copy the project [i]Greippi - Krem Kaakkuja.mmpz[/i] from the folder: [b]//projects\demos/[/b]
* Paste it in your folder for own projects
* Double-click in order to open
What happen *then*
