### ISSUE TITLE
Drag'n'drop from Songeditor to BB

### ISSUE THREAD

**Issue by BaraMGB** [LMMS/lmms#472]
If I drag and drop an instrument (which hasn't any notes)  from songeditor to BB-editor (hold ctrl-Key) the new intrument in the BB-editor has no ability change any notes or steps. Theres an empty area. If i clone this Track the new one hasn't steps but the old one does now. 
![bbeditor](https://f.cloud.github.com/assets/6502580/2431313/fa2d31ec-ad27-11e3-8eee-3103e5baaabc.png)

**Comment by softrabbit** [comment]
Looks like this was fixed, works for me in master. Close?

**Comment by tresf** [comment]
Sure.  We can easily re-open if it resurfaces.  Thanks! :)
