### ISSUE TITLE
GUI improvement

### ISSUE THREAD

**Issue by allphfa** [LMMS/lmms#4722]
![](https://raw.githubusercontent.com/allphfa/imgs/master/lmms.png)

**Comment by Gabrielxd195** [comment]
I think it's a good idea, but I think I should give more detail, at least in my case that I'm a novice, I'd like to know what you propose with this. regards

**Comment by allphfa** [comment]
Layout similar to video editing software DaVinci Resolve

**Comment by hartsantler** [comment]
I think the current UI works well, i like freely moveable subwindows, and it is useful that it works with X11 embedding.  

The only minor issue i have noticed with the current UI is when i add a new effect filter, and then press its `controls` button to open more sub-controls, it often opens the new controls window in the upper far right, while the fx filter is at the bottom of my screen to the left.  It would be better if by default extra subwindows would open near or on top of their parent window.  So the window layout logic needs some improvements.

**Comment by tresf** [comment]
@allphfa please retitle the bug report to be more descriptive.
