### ISSUE TITLE
Editors are empty after loading project when they were closed

### ISSUE THREAD

**Issue by PhysSong** [LMMS/lmms#4724]
Reported by @zonkmachine on Discord.
Steps to reproduce:

1. Open the song editor
2. Close it with either `Ctrl + W` or the `x` button
3. Create a new project
4. Now the song-editor window is empty

It also happens for BB editor, piano roll and automation editor as well. Shortcut `F5`\~`F8` and toolbar buttons in the main window works fine.

We use `SubWindow`s to manage various windows. Closing a `QMdiSubWindow` closes the child widget, but showing the subwindow doesn't make its content visible. We worked around it by ignoring the close events in child widgets, e.g. #1495.
However, `MainWindow::toggleWindow` uses `hide()` to close editors. When showing them, the function also shows their content.

There are several ways to fix this bug:

## `Editor`'s side
- Override `closeEvent` and hide the `SubWindow` instead of closing it, like other widgets, e.g. `FxMixer`. This is the safest way since it doesn't affect any other widgets.

## `SubWindow`'s side
Working on `SubWindow` may allow removing a bunch of `closeEvent` overrides in many windowed widgets.
- Override `showEvent` to make the content visible when the `SubWindow` becomes visible.
- Override `closeEvent` to hide the `SubWindow` itself instead of closing.

**Comment by musikBear** [comment]
Just make sure you do not force opening of any windows, when you open am existing project! That is *important* because low-end pc's can have issues opening large projects, but this goes smoothly and flawless, if all windows are *closed*, before the project is saved!
I have manually edited the flag '1' to '0' in a couple of *hanging* MMPs, and they works after these edits!

**Comment by tresf** [comment]
We noticed on Discord in #support this was similar in description to #3964.  Mentioning it here for breadcrumb purposes.
