### ISSUE TITLE
[MacOS] VST folder defined but no VST support

### ISSUE THREAD

**Issue by GingkathFox** [LMMS/lmms#4725]
Whats with the VST folder being created when installing, but there's no VST effect support? AFAIK you can't use Carla as an effect, so why create a VST folder and have the option to define a VST folder?

**Comment by tresf** [comment]
We expect better bug reports.  You didn't even mention the folder that gets created.  If it's the one inside samples, don't sweat it, some people use LMMS on more than one type of machine.  It's just a directory tree and it's harmless, just as harmless as making an `soundfonts` folder on a build built without SF2 support.

**Comment by GingkathFox** [comment]
this was a terrible report xd, ill talk about it on the Discord if u want.
