### ISSUE TITLE
[MacOS?] Loading When Assigning FX channel or Dragging in BitInvader

### ISSUE THREAD

**Issue by GingkathFox** [LMMS/lmms#4726]
This is a small issue, but it gets annoying after a while. Whenever I try to assign a instrument to a FX channel, LMMS will freeze for a second and the cursor will switch to the "loading" pinwheel. It also happens when drawing a waveform in BitInvader.
Steps to reproduce:
1. Open LMMS
2. Create a bunch of FX Channels (4 is a good number), open a plugin Menu, and scroll up on the FX number. LMMS will hang for a second and assign the instrument a channel after a bit.

**Comment by tresf** [comment]
> Dragging in BitInvader
... 
>  drawing a waveform in BitInvader.

Which one?  Those are separate actions.  BTW, you've already submitted a bug report on BitInvader here: #4553.

In regards to the FX lag, is it here?
![image](https://user-images.githubusercontent.com/6345473/53841950-24ec6200-3f6c-11e9-95f0-d15a23896bdf.png)

How are you "scrolling up"?  Mac's trackpad is way too sensitive for LMMS and it's a separate bug and should be filed as such.  Does it happen when you use the keyboard?  See if you can fix the spinner class, it probably is allow over-scrolling but it only noticeable on super-sensitive mouse wheels (or in this case, track pads).

**Comment by GingkathFox** [comment]
@tresf i scroll up by clicking and dragging, shoulda said that XD
i don't know how to use the keyboard to assign fx channels.
Also, the bitinvader one is a different issue. https://github.com/LMMS/lmms/issues/4553#issuecomment-415803120 touches on the lag, but its not what the issue is about.

**Comment by tresf** [comment]
Yes there's a delay when clicking and dragging, but now when using the two-finger scroll.

**Comment by GingkathFox** [comment]
two-finger scroll "bounces" though. try scrolling on a knob, (such as the one in AFP) and its value will bounce back and forth for a bit before moving up or down.

**Comment by tresf** [comment]
> Yes there's a delay when clicking and dragging, but not when using the two-finger scroll.

I tested this on Ubuntu and it didn't seem to suffer the same problem.  @GingkathFox this is a great first issue for you!

**Comment by GingkathFox** [comment]
this was my first issue? nice, i get bragging rights XD

**Comment by GingkathFox** [comment]
also, wish i could record the value bouncing but OBS likes to corrupt the videos it records now. ;w;

**Comment by tresf** [comment]
QuickTime (built-in) does a fine job for desktop recording in macOS.

**Comment by tresf** [comment]
> this was my first issue? nice, i get bragging rights XD

No, it's a good first issue for you to code and fix.

**Comment by GingkathFox** [comment]
theres ooone small problem...
i dont know C++ XD

**Comment by GingkathFox** [comment]
found this again, seems to be fixed now. closing.
