### ISSUE TITLE
Remove "Sync VST plugins to host playback" option

### ISSUE THREAD

**Issue by DomClark** [LMMS/lmms#4730]
The "Sync VST plugins to host playback" option causes VST plugins to be informed of the following parameters, in addition to what is sent when the option is disabled:
* Time signature (defaults to 4/4 when the option is disabled)
* Playback state (defaults to playing)
* Playback position (calculated from tempo by default)
* Loop start, end, and enabled state (defaults to loop disabled)
* Start of current bar (calculated from playback position and time signature)
* Jumps in playback (defaults to continuous playback)

The option is disabled by default, and this seems to cause confusion for some users who wonder why their VST plugins won't stay in time with the rest of their song. This has come up a few times in `#support` on Discord, and I expect there are some other users who don't report a bug or ask a question and just assume LMMS is broken. I'm not aware of any other DAW that allows toggling VST sync (correct me if there is), and I'm not sure what the use case really is.
I think we should change it to be enabled by default in `stable-1.2` to reduce confusion and fix what could be perceived as a bug, and remove the option eventually in `master`.

**Comment by zonkmachine** [comment]
> I think we should change it to be enabled by default in `stable-1.2` to reduce confusion and fix what could be perceived as a bug,...

Fix please!

**Comment by DomClark** [comment]
Enabled by default in 69a51eb28bf1d7d73594e380d9995ebb2d7b2b19.

**Comment by Spekular** [comment]
Closing and consolidating into #5433
