### ISSUE TITLE
compile fails on fedora linux

### ISSUE THREAD

**Issue by hartsantler** [LMMS/lmms#4734]
I am trying to compile from source on Fedora28 using cmake.  getting this error.
```bash
Scanning dependencies of target RemoteVstPlugin64
[ 92%] Creating directories for 'RemoteVstPlugin64'
[ 92%] No download step for 'RemoteVstPlugin64'
[ 92%] No patch step for 'RemoteVstPlugin64'
[ 92%] No update step for 'RemoteVstPlugin64'
[ 92%] Performing configure step for 'RemoteVstPlugin64'
-- The CXX compiler identification is GNU 8.0.1
-- Check for working CXX compiler: /home/kizna/lmms/build/winegcc_wrapper
-- Check for working CXX compiler: /home/kizna/lmms/build/winegcc_wrapper -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/kizna/lmms/build/plugins/vst_base/RemoteVstPlugin64-prefix/src/RemoteVstPlugin64-build
[ 92%] Performing build step for 'RemoteVstPlugin64'
Scanning dependencies of target RemoteVstPlugin64
[ 50%] Building CXX object CMakeFiles/RemoteVstPlugin64.dir/home/kizna/lmms/plugins/vst_base/RemoteVstPlugin.cpp.o
In file included from /home/kizna/lmms/include/MidiEvent.h:28,
                 from /home/kizna/lmms/include/RemotePlugin.h:28,
                 from /home/kizna/lmms/plugins/vst_base/RemoteVstPlugin.cpp:35:
/usr/include/c++/8/cstdlib:75:15: fatal error: stdlib.h: No such file or directory
 #include_next <stdlib.h>
               ^~~~~~~~~~
compilation terminated.
winegcc: g++ failed
make[5]: *** [CMakeFiles/RemoteVstPlugin64.dir/build.make:63: CMakeFiles/RemoteVstPlugin64.dir/home/kizna/lmms/plugins/vst_base/RemoteVstPlugin.cpp.o] Error 2
make[4]: *** [CMakeFiles/Makefile2:68: CMakeFiles/RemoteVstPlugin64.dir/all] Error 2
make[3]: *** [Makefile:84: all] Error 2
make[2]: *** [plugins/vst_base/CMakeFiles/RemoteVstPlugin64.dir/build.make:111: plugins/vst_base/RemoteVstPlugin64-prefix/src/RemoteVstPlugin64-stamp/RemoteVstPlugin64-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:7942: plugins/vst_base/CMakeFiles/RemoteVstPlugin64.dir/all] Error 2
make: *** [Makefile:152: all] Error 2


```

https://github.com/LMMS/lmms/issues/3915

**Comment by hartsantler** [comment]
to get it to compile i had to edit the toplevel cmake file and turn off the VST options, but that was not enough, i had to go into lmms/plugins/CMakeLists.txt and disable the following:

starting at line 79
```bash
		#vst_base
		#vestige
		#VstEffect
```

**Comment by PhysSong** [comment]
It seems like this is a bug of Wine: https://bugs.winehq.org/show_bug.cgi?id=46293
You may try downgrading Wine to 3.20(or older) or wait for the next update of Wine. The upstream fixed the `winegcc` bug a few days ago.

**Comment by noahb01** [comment]
I have this issue as well. Compiling with `cmake .. -DWANT_VST=OFF -DWANT_VST_NOWINE=ON && make -j4` fixes the issue for me at the expense of not having Windows VST support. This is on the latest master.

**Comment by zonkmachine** [comment]
Wine 4.0-rc3 was just released: https://www.winehq.org/announce/4.0-rc3

@hartsantler @noahb01 
Can you try and see if upgrading wine fixes your issue?

**Comment by noahb01** [comment]
@zonkmachine I'm going to wait until it gets pushed to the Arch repos, wine-staging is still on 4.0-rc2-1.
Once that gets updated I'll test again.

**Comment by zonkmachine** [comment]
Looks like it's been updated already.
https://www.archlinux.org/packages/multilib/x86_64/wine-staging/
**wine-staging 4.0rc3-1** :rocket:

**Comment by noahb01** [comment]
It got updated about 2 minutes after I typed that.

Yes, this fixes the issue for me.

**Comment by zonkmachine** [comment]
> You may try downgrading Wine to 3.20(or older) or wait for the next update of Wine.

@hartsantler This is the best answer here. You can also install Wine from winehq directly but since the packages is probably just a day or so from being updated it's probably better to just wait a bit.
I'm closing this as this is not our bug and the issue has been fixed in the source.
