### ISSUE TITLE
Lmms working directory

### ISSUE THREAD

**Issue by jarol00** [LMMS/lmms#4741]
How to I reset the appilication to it's original settings?

**Comment by jarol00** [comment]
I accidentally changed my working directory file and I don't know what file was originally there.

**Comment by zonkmachine** [comment]
You remove the file named `.lmmsrc.xml`
It would be in your $HOME
If you run lmms from a build directory you also have a local .lmmsrc.xml file in there.

**Comment by jarol00** [comment]
Is there a way to restore my default settings?

**Comment by zonkmachine** [comment]
> Is there a way to restore my default settings?

When you change the settings this is stored in `.lmmsrc.xml`. If you want your favorite  setup to be saved, if you are about to experiment with the settings, then you need to make a backup of `.lmmsrc.xml`. In your home directory, just right click the file, choose copy, and paste it right there and rename it as `.lmmsrc.xmlBACKUP`. You can now just delete .lmmsrc.xml and rename the backup to revert to the older settings.

Did this answer your question?

**Comment by jarol00** [comment]
Where would my build directory be?

**Comment by jarol00** [comment]
I just want a way to restart the whole program qithout my projects getting
deleted. Please help.

**Comment by musikBear** [comment]
@jarol00
Zonk already told you, but you have posted on Hub, where computer-skills are expected Firstly i think you should create an account on our Forum
http://lmms.io/forum/index.php
-You find me there :)
or on Discord
https://discordapp.com/invite/5kSc32Z

Your issue:
You need to locate a file named **.lmmsrc.xml**
Read:
https://lmms.io/wiki/index.php?title=LMMS_Settings#Problems_with_Settings
And follow those guidelines!
After you have moved the dot-file, restart LMMS, and it will start in reset-mode.
Happy New-year.

**Comment by lukas-w** [comment]
Closing as the question has been answered.
