### ISSUE TITLE
Restore Default Settings

### ISSUE THREAD

**Issue by jarol00** [LMMS/lmms#4742]
Is there a way to restore my default settings?

**Comment by zonkmachine** [comment]
I'm closing this as it is basically the same as #4741.

Support cases are better suited for or Discord site or the old forum.
[![Join the chat at Discord](https://img.shields.io/badge/chat-on%20discord-7289DA.svg)](https://discord.gg/3sc5su7) (especially the channel named `#support`)
https://lmms.io/forum/
