### ISSUE TITLE
Theming of disabled components

### ISSUE THREAD

**Issue by zonkmachine** [LMMS/lmms#4749]
Some components that are disabled don't show this without theming. An example being knobs, see the tension knob in the Automation Editor. It's only enabled with the cubic hermite progression and disabled for the other progressions but there is no visual indication that it's disabled other than that it's immobile.

https://github.com/LMMS/lmms/blob/386c471ed7fc1cc565be761927c2d7058512f4b9/src/gui/editors/AutomationEditor.cpp#L2506

I think all changes needed may be in `style.css`. We have some theming of disabled components already. See the `Edit->Redo` menu entry when there are no undone actions.

https://github.com/LMMS/lmms/blob/386c471ed7fc1cc565be761927c2d7058512f4b9/data/themes/default/style.css#L109

@LMMS/artwork-team 

_Edit: New commit with disabled knobs (https://github.com/LMMS/lmms/pull/4378)..._ https://github.com/LMMS/lmms/blob/a3ede058cdabb9254f50e69e5133fe5807036f39/src/gui/widgets/EffectView.cpp#L78

**Comment by thmueller64** [comment]
I've opened a draft PR on this one. Unfortunately, I could not get it to work with pseudo-states. See the PR for the reasoning. Maybe someone can test it and provide feedback. I still have to look for resource leaks etc., so it is a draft PR for now.

![knob_theming](https://user-images.githubusercontent.com/64359888/80872254-20772280-8cb1-11ea-8059-0e8465f501bb.gif)

**Comment by zonkmachine** [comment]
Tested. This works lovely, thanks!



> I could not get it to work with pseudo-states

And what's a pseudo state?  :)

**Comment by thmueller64** [comment]
Thank you for the testing! I had a discussion on Discord with @Veratil about that feature and refactored the PR quite a bit. I'll open a new one, but this time not as a draft.

With a pseudo state you can easily control the theming based on the state of a Widget, like:
```
QPushButton:enabled {color: green}
QPushButton:disabled {color: red}
```

**Comment by zonkmachine** [comment]
Closed in https://github.com/LMMS/lmms/pull/5549
