### ISSUE TITLE
Scanf problems

### ISSUE THREAD

**Issue by shlyakpavel** [LMMS/lmms#4756]
PVS studio warning: V614 Uninitialized buffer 's' used. Consider checking the first actual argument of the 'sscanf' function.

https://github.com/LMMS/lmms/blob/5ebe0e002d2bb754259f55aec2c00c3a3fc5437f/src/core/DrumSynth.cpp#L133

**Comment by PhysSong** [comment]
The problem with `GetEnv` doesn't look that much severe when I tested with some manually corrupted files, but I'm not sure if we can leave the code as-is.

**Comment by shlyakpavel** [comment]
@PhysSong I agree it's vulnerable so this should not be left "as is".

**Comment by M374LX** [comment]
This might be solved by adding the line
```s[0]=0;```
right after
```en[255]=0; //be safe!```
