### ISSUE TITLE
Can't build on macOS 10.14 Mojave

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms#4762]
Placeholder to fix Mojave support.  When building on the latest macOS, I get the following error:

```
[ 21%] Linking C shared module ../../ladspa/pitch_scale_1193.so
[ 21%] Linking C shared module ../../ladspa/freq_tracker_1418.so
[ 21%] Generating ../../../../plugins/LadspaEffect/swh/ladspa/se4_1883.c
ld: library not found for -lfftw3f
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [plugins/ladspa/pitch_scale_1193.so] Error 1
make[1]: *** [plugins/LadspaEffect/swh/CMakeFiles/pitch_scale_1193.dir/all] Error 2
```

It may be machine-specific or Homebrew-specific (I only have one machine running Mojave).  Advice appreciated.

**Comment by tresf** [comment]
I found a temporary workaround... 

```cmake
LINK_DIRECTORIES(/opt/local/lib)
```

I've started a public discussion with Homebrew here:
https://discourse.brew.sh/t/cmake-linking-not-working-since-mojave/3790

Hopefully there's some explanation or troubleshooting that can be provided.

**Comment by GingkathFox** [comment]
[LMMS make -j4 output.zip](https://github.com/LMMS/lmms/files/2731223/LMMS.make.-j4.output.zip)
Heres the full output when i compiled, maybe this helps?

**Comment by tresf** [comment]
@GingkathFox yes, this appears to be failing at the exact same place.  I've filed a stackoverflow article as this is probably messing up a bunch of C++ coders.  https://stackoverflow.com/q/54068035/3196753

**Comment by tresf** [comment]
So I've isolated this to the following change in the `VERBOSE=1 make` logs... 

* High Sierra and above did **NOT** use the `-isysroot` command.
* Mojave **DOES** use the `-isysroot` command.

From [gnu.org](https://gcc.gnu.org/onlinedocs/gcc/Directory-Options.html):

> `-isysroot <dir>`
> This option is like the `--sysroot` option, but applies only to header files (**except for Darwin targets, where it applies to both header files and libraries**). See the `--sysroot` option for more information.

This results in the compilation never looking in the standard `ld` locations, which can be seen by typing `ld -v dummy`.

```
Library search paths:
	/usr/lib
	/usr/local/lib
```

So what compile flag can I toggle on to add the default search paths back in?  I can certainly hard-code `/usr/lib` and `/usr/local/lib` back in for Apple, but that seems like the wrong way to do it.

**Comment by PhysSong** [comment]
@tresf Do you have any ideas where does `-isysroot` comes from?

**Comment by GingkathFox** [comment]
@tresf the links broken

**Comment by tresf** [comment]
> @tresf the links broken

Fixed.
