### ISSUE TITLE
Midi controller (lpk25)

### ISSUE THREAD

**Issue by singam96** [LMMS/lmms#4769]
When im playing the piano, notes come in different order
Ex:  i press C E G sequentially and continously
Lmms register it as 
CEG EGC EGC 
Some notes especially the third note is getting wrong time placement in  piano roll.
I can hear the sound correctly when recording, after recording and then playing gives you another sound pattern

This is reproducible tried on different os and different computer, (ubuntu studio, windows 10, linux mint)
I also tried different audio driver
Other daws dont show this problem

**Comment by Spekular** [comment]
What quantization level are you recording at? Recording is snapped to the
current quantization level, which could lead to two notes hitting at the
same time rather than in quick succession. This would also match with
playback being correct during recording and wrong afterwards.

**Comment by singam96** [comment]
What is quantization level? 😢😢😢😢

**Comment by singam96** [comment]
Thank u , still dont know wht tht is , i put it 1/192 , it now works well

**Comment by zonkmachine** [comment]
Hi!

I would suggest that you use the lmms forum instead for support as this site is more oriented to the actual programming/building of lmms.
https://lmms.io/forum/viewforum.php?f=7

We also have a chat which probably is the fastest support.
https://discordapp.com/invite/3sc5su7

Closing as this is solved. :)
