### ISSUE TITLE
Compilation issue on Ubuntu 18.04

### ISSUE THREAD

**Issue by itlives** [LMMS/lmms#4774]
Hey, when typing make -j8, the cmake process stops at 96% when building lmmsobjs. 
Heres my output: 
https://pastebin.com/THeb3Ebv

I am compiling the stable-1.2 branch

**Comment by itlives** [comment]
Furthermore, the carla installation guide in the wiki does not work (Carla does not a have a release file anymore, for me at least)

**Comment by zonkmachine** [comment]
What version of Wine do you have?
There was problems compiling with Wine staging earlier that should have been fixed in Wine 4.0-rc4.
https://github.com/LMMS/lmms/issues/4734

**Comment by itlives** [comment]
@zonkmachine the newest one. i just checked

**Comment by zonkmachine** [comment]
So, Wine 4.0-rc6.

**Comment by itlives** [comment]
another update @zonkmachine i dont know whats wrong with my cmake, but lmms now builds until:
In file included from /home/felix/Projects/lmms/include/MidiEvent.h:28:0,
                 from /home/felix/Projects/lmms/include/RemotePlugin.h:29,
                 from /home/felix/Projects/lmms/plugins/vst_base/RemoteVstPlugin.cpp:35:
/usr/include/c++/7/cstdlib:41:10: fatal error: bits/c++config.h: file not found

god knows why all this happens

**Comment by itlives** [comment]
solved, i didnt install gcc-multilib
