### ISSUE TITLE
Error: The piano roll notes align and lose their position.

### ISSUE THREAD

**Issue by Gabrielxd195** [LMMS/lmms#4776]
I do not know how to identify this error or how to name it, but with this image you can identify it.

![ezgif-2-ac0adfdf5316](https://user-images.githubusercontent.com/26127693/51355568-92f4cc80-1a85-11e9-887e-d0cb4607989a.gif)

I found this error by accident when I was creating a melody and I wanted to raise several octaves, press several times '' ctrl + Arrow up '' and I saw how the notes when they reached the last note '' B8 '' lost their position and became alienated , as if it were a kind of rule. I am using the LMMS 1.2 RC7 version but I also try it in 1.1.3 and I also pass there.

To make matters worse, when the notes are aligned, you can not restore them by pressing '' Ctrl + Z '', but the option to undo is useless and I have to restart my project (if I remember to save it). I do not know if someone already mentioned this, but since I did not know how to identify this error, I did not find anyone to talk about this. If this is a feature of LMMS, I think it's useless, but if it's a mistake I think it should be corrected. Greetings and thanks.

**Comment by JohannesLorenz** [comment]
Confirming both issues with current stable-1.2:
1. Alienation
2. Ctrl+Z

(2) Is clearly a bug. (1) Depends on how you see it. I'd find it less useful, but what do others think?

**Comment by zonkmachine** [comment]
I've seen this discussion before. It happens here:

https://github.com/LMMS/lmms/blob/dd99f3a7c466e86e02a8a8811e4b41f471a8b15d/src/core/Note.cpp#L38

https://github.com/LMMS/lmms/blob/dd99f3a7c466e86e02a8a8811e4b41f471a8b15d/src/core/Note.cpp#L42

https://github.com/LMMS/lmms/blob/dd99f3a7c466e86e02a8a8811e4b41f471a8b15d/src/core/Note.cpp#L112-L116

**Comment by zonkmachine** [comment]
> (2) Is clearly a bug. 

Add a couple of notes and shift them up/down or change position. When you hit `Ctrl + z ` it will take you back to before adding the last note. We need to add checkpoints before moving notes.

Adding `m_pattern->addJournalCheckPoint();`


Here:
https://github.com/LMMS/lmms/blob/dd99f3a7c466e86e02a8a8811e4b41f471a8b15d/src/gui/editors/PianoRoll.cpp#L954

And here:
https://github.com/LMMS/lmms/blob/dd99f3a7c466e86e02a8a8811e4b41f471a8b15d/src/gui/editors/PianoRoll.cpp#L980

**Comment by musikBear** [comment]
Oh yes, mowing notes outside scope of piano-roll, will push them from their vertical position -I have used this as a feature, when i need to 'shave' either a bass part, or a solo-part, away from a melody. When all is pushed on same note, the trick is to mark them with context-menu 'Mark all notes on this key', then kill them :p
Feature or bug ?

**Comment by Spekular** [comment]
Definitely not a feature, but I have a hard time calling it a bug. A better
behavior might be to stop the whole group of notes from moving, but that
could be confusing as well (if the top note is above the viewport, for
example).

@musikBear this can easily be accomplished by ctrl+dragging to select all
notes above a certain key, so no functionality would be lost.

**Comment by zonkmachine** [comment]
> A better behavior might be to stop the whole group of notes from moving,...

This would be better, yes.

**Comment by T0NIT0RMX** [comment]
Afaik, I use this as a feature to create bass lines from melodies, I pushed everything to the bottom until it draws a line,

It's actually really useful, I didn't know it was a bug

**Comment by zonkmachine** [comment]
MuseE actually works the same way. Notes level out.

@JohannesLorenz As I fixed the journal checkpoints for shifted notes I change label to **ux** for the remaining issue.

**Comment by Gabrielxd195** [comment]
> Afaik, I use this as a feature to create bass lines from melodies, I pushed everything to the bottom using CTRL + DOWN ARROW until it draws a line at the bottom of the pianoroll, then I can easily move groups of notes
> 
> It's actually really useful, I didn't know it was a bug.


Wow! I had not thought of it. But you take advantage of a fault to use it as a tool ?. You are a genius friend. I'm going to close this problem, I hope you do not take it into account.
