### ISSUE TITLE
I’m listed twice in the contributors document

### ISSUE THREAD

**Issue by noahb01** [LMMS/lmms#4778]
I’m listed twice in the contributors document, once as ‘noahb01’ and once as ‘Noah Brecht’. I suppose this is due to different git setups on my different devices, but I dont see a need to be listed twice. Both of my identities have the same email.

`noahb01` on line 179
`Noah Brecht` on line 146

**Comment by JohannesLorenz** [comment]
Is this file generated by script? If yes, one could prefer names in the form "firstname lastname" to "oneword" in case both have the same email. Though I wonder if it's worth the effort...

**Comment by grejppi** [comment]
You might want to add your preferred name and email to the `.mailmap` file. Like this:
```
Preferred Name <me@example.org>
```

**Comment by JohannesLorenz** [comment]
Just for explanation, as I didn't get this at first: cmake takes `git log`, filters double names/mails using `.mailmap` and then generates `build/CONTRIBUTORS`.

The following users are all duplicate in `build/CONTRIBUTORS`. If you like, can any of you please do a commit like fdccb38?
@jasp00 @BaraMGB @PhysSong @karmux @lukas-w @tobydox @midi-pascal @mikobuntu @RebeccaDeField
