### ISSUE TITLE
lilv - C or C++ ?

### ISSUE THREAD

**Issue by JohannesLorenz** [LMMS/lmms#4779]
For Lv2, it's almost required to use lilv, a library helping hosts to easily deal with Lv2.

For LMMS, I originally wanted to use lilvmm (the C++ version of lilv), but it's buggy thus not usable (@grejppi came to the same conclusion).

@drobilla announced to release a complete remake of lilvmm which will have cool features like type safety and C++11 iterators. However, Ubuntu 16.04 is 4 years late with lilv.

We have at least 2 options:

1. Use the new lilvmm => Users with LTS systems won't get Lv2 support (at least not using their system's lilv)
2. Use the C version of lilv => Less type safety, code gets a bit more hard to read (if you're more comfortable with C++)

If we choose (1), LTS users simply won't be able to use the Lv2 plugin, but since the plugin can be turned off in CMake (I'm making it optional), they can still build LMMS without Lv2. One could argue that LTS is a wrong distribution choice and we shouldn't spend efforts supporting bad choices (no offense). But even then, the danger is that LTS fans fork LMMS and replace lilvmm by C-lilv, and we already have enough forks.

So it looks like we're forced to go with (2). Maybe I'm not seeing a third option, like up-to-date repos of lilv where LTS users can get new lilv versions from? Or something else?

Any votes/opinions?

:tada: - Use lilvmm, even if this won't support LTS
:heart: - Use C-lilv, supporting LTS and rejecting the nice C++ features
:rocket: - Another option (please specify)

**Comment by JohannesLorenz** [comment]
@drobilla IIRC you said the new lilvmm requires at least the new serd. Also, what guarantees that the lilvmm of 2019 will be compatible with the rest of lilv (and its dependencies) from 2014?

**Comment by drobilla** [comment]
Depends if I do it before or after a major lilv API cleanup, but in any case, new major version, so: zero.

**Comment by drobilla** [comment]
My point was, if you want C++eyness in the LMMS code, it's not required to use bindings that ship with Lilv at all, so if you wanted to do the work (say, refine existing lilvmm for your purposes, or write a totally new one, or whatever) you could just include your own in-tree.

It's a lot of work to redo all of that, and I'm currently focused on getting the new serd out, and lilv (and friends) with minimal API changes released on top of that, so I can't promise any timeline on new official lilv C++ bindings.  Regardless, they will be more or less completely incompatible with the old ones in a strict sense, since that's the point.

**Comment by JohannesLorenz** [comment]
My gut feeling is that using C-lilv is the lesser evil than adding another submodule or adding another file without submoduling.

**Comment by tresf** [comment]
> One could argue that LTS is a wrong distribution choice and we shouldn't spend efforts supporting bad choices (no offense). But even then, the danger is that LTS fans fork LMMS and replace lilvmm by C-lilv, and we already have enough forks.

LTS is the strategy AppImages use for targeting a wide number of machines.  `#2` gets my vote.  If a PPA backport arrives (or we submodule as discussed above), `#1` then starts to look good. :)

**Comment by musikBear** [comment]
Agrees with @tresf
Using a lib that will exclude a group of users, only because that lib is 'nice' to work with, is imo wrong.

**Comment by JohannesLorenz** [comment]
Thanks for your opinions so far. The posts and the voting somehow tell me to use C-lilv for now. If we want to switch in a few years, we can still do so.
