### ISSUE TITLE
Times per box

### ISSUE THREAD

**Issue by Producer1Zem** [LMMS/lmms#4782]
It would be useful that in the Song Editor at the time of zooming in each square of 1 second this could be split in quarters or eighths of a second to accommodate the audios and parts of the song, something similar to what happens in the piano roll with the option of Quantize (Q), would be very useful because dragging it, which is the only option so far in the program complicates this work a lot. explains better in this image.
![lmms](https://user-images.githubusercontent.com/44046820/51434565-68dc0f80-1c29-11e9-91da-8f5e1c7a0f90.png)
 Thank you.

**Comment by musikBear** [comment]
Isent this 'fixed' with Masters 
![image](https://user-images.githubusercontent.com/6662066/82154189-7e3c6a80-986c-11ea-8443-3e852a04c345.png) feature?
eg option to set TCOs between bars, but still in synch ?

**Comment by Spekular** [comment]
Good catch! The denser grid isn't inplemented but there's already another issue open for that.
