### ISSUE TITLE
Crop audio

### ISSUE THREAD

**Issue by Producer1Zem** [LMMS/lmms#4783]
Cutting an audio from both sides would be a feature that I recommend putting the program, currently only allows you to cut it from right to left but not from
Inverse way (left-right). Also cutting an audio to less than a second would be great, the program only allows you to edit it only one second later
but it does not allow to cut it from 1 second to the last. Thank you.

**Comment by musikBear** [comment]
> Cutting an audio from both sides

You can do that in AudioFileProcessor. Look at the dials for start-pos and end-pos. Repeat should be the whole new selected area

**Comment by tresf** [comment]
Both SampleTrack (as of #3487) and AudioFileProcessor allow cropping from left.  There are no 1 second limitations on in regards to cropping in either plugin.
