### ISSUE TITLE
sample track out of sync with jack

### ISSUE THREAD

**Issue by smlfr** [LMMS/lmms#4786]
Hi,
my sample tracks are out of sync with the midi tracks when not starting playback from the beginning.

I'm using 1.2.0 rc7 on Linux.

**Comment by musikBear** [comment]
Is the sample-track BPM different in different MIDI-files?
I am afraid reading this, that you expect your sample-track-BPM, to be *auto-fitted* to the MIDI BPM. That is not a feature, in LMMS! 
You need to use f.i. Audacity
It is free, solid and well maintained
We dont hesitate to recommend it :
http://www.audacityteam.org/download/

**Comment by SamuelFrh** [comment]
I am not sure what you mean by 'in different midi-files.

I created a new project, set the bpm to the vocal bpm, imported said vocal into a sample-track and recorded some notes via midi. At this point I would expect both tracks to match and they do (for the whole length of the track), but only when I start playback at T = 0. Starting at any T > 0 there is a constant  delta t between both tracks (midi lagging behind)

**Comment by zonkmachine** [comment]
@SamuelFrh Try **menu - > settings - > "Sync VST plugins to host playback"**

**Comment by smlfr** [comment]
Unfortunately it did not help. I'm not using any vsts btw.
The simplest case in which I could reproduce the behaviour is a sample track and one instance of triple oscillator.

**Comment by zonkmachine** [comment]
> I'm not using any vsts btw.

Right, gotcha! Smells like a bug. How long sample/track do you need to experience the sync issue?

**Comment by smlfr** [comment]
I did experience it with samples with about a length of 7 seconds and more but not with ones of about 4 seconds and less (at least I couldn't tell). To get a more precise measurement I would need a little bit of time.
The issue also occurs when the sample track is muted and unmuted again (both from the beginning or any time later and also when done multiple times), with wavs and flacs and with Jack as well as the Alsa interface.

**Comment by smlfr** [comment]
> Ratch.. Sample-track does drift. It does it natively. No 'need' for either mute or track-inside initiation.

I'm not entirely sure how close these issues are related. I wouldn't describe my situation as a drift but rather as an offset. Note that I can also achieve a significant offset even in a 7 second clip when starting mid-track or muting/unmuting although it plays fine when starting from 0.
I might record a little demo soon.

**Comment by smlfr** [comment]
I have to correct myself again.
The issues appears to exist only when using jack

**Comment by tresf** [comment]
> The issues appears to exist only when using jack

This sounds vaguely familiar to some issues I've seen with other DAWs and mismatched sample rate (e.g. 44K vs 48K).  I do not use JACK, but is there a chance this is something you can attempt to configure?

Here's an Ardour discussion that's similar: https://discourse.ardour.org/t/difference-in-sample-rate-in-ardour-and-jack/86193/2

**Comment by musikBear** [comment]
Repeats:
Sample-track gets out of sync on RC7 and also now tested for RC8, on **Windows** x32 *without* any JACK installed at all.
This is *not* related to JACK, nor restricted to Linux

**Comment by tresf** [comment]
@musikBear can you please provide steps to reproduce this issue?

**Comment by smlfr** [comment]
I don't have the right setup at the moment but I will take another look at it within the next few days.

**Comment by musikBear** [comment]
@tresf
steps to reproduce:
* Setup a simple beat. Best samples are distinct *clicks*
* record a playback for one min with audacity
* Insert a sample-track
* import recorded file

There are now two identical audio-samples in the project
1) The BB-line
2) The recorded BB-line
* Replay and record both audio-samples

Examine the recording. The *relative* spacing between the first secd of wave-shapes, must be identical to the last secd of wave-shapes. 
The linked pictures shows that it is not the case on win32
https://i.imgur.com/4NxfOTP.jpg ( cant post pictures here )

**Comment by tresf** [comment]
The OP's bug report specifically states:
1. When not playing from beginning
2. JACK

Are you sure you're not experiencing a separate issue?  Those are quite specific details to just throw out.

**Comment by smlfr** [comment]
I still believe that we are experiencing two different issues, as far as I can tell. What you are describing is tracks "getting slower over time".
However, what I'm experiencing is two tracks (one sample track, one midi track) that play in sync for their whole length, but only when playback is started from the very beginning. When they are played back from any other point in time or if I jump within the track, there is an offset between these tracks. I'll try to create a demo that makes it better to comprehend.

**Comment by tresf** [comment]
@smlfr a demo is welcome, but your explanation is adequate, thank you.

**Comment by BaraMGB** [comment]
@musikBear, try to avoid audacity. if you render 1minute of your bb track and import it to the sample track, does this happen?

**Comment by musikBear** [comment]
@BaraMGB 
> if you render 1minute of your bb track and import it to the sample track, does this happen?

*That* was very good thinking!
No! A **Rendered**, exported soundfile, reimported into sample-track, does *not* go out of sync!
There is *no* general issue!

**Comment by tresf** [comment]
> There is no general issue!

Translation: the symptom @musikBear experienced -- unrelated to this bug report -- is no longer valid.

The OP's issue is still valid

**Comment by BaraMGB** [comment]
I'll try to reproduce the OP's issue.

**Comment by BaraMGB** [comment]
I can confirm this issue. This only appears with jack at sample rate at 48000 Hz. I tested with sample rate 44100 Hz on jack and everything seems fine.

**Comment by BaraMGB** [comment]
I guess this function is the problem. It's something like a fallback in case there's no audio device. The config manager values are always "0", so the sample rate will be set to 44100. But the bigger problem is, this function ( `Engine::mixer()->baseSampleRate()` ) is been used in the whole lmms source code. In my opinion this function should be _private_ and we should use `Engine::mixer()->outputSampleRate()` instead everywhere. Because outputSampleRate() checks if there is an audioDevice and returns the right sample rate (or just the baseSampleRate() as fallback). 

https://github.com/LMMS/lmms/blob/f79c2929a5b9baa81279d016341a01bf160eaa3c/src/core/Mixer.cpp#L264-L282

**Comment by PhysSong** [comment]
> we should use `Engine::mixer()->outputSampleRate()` instead

As a simple test, I replaced `baseSampleRate` calls in `SampleBuffer.cpp` with `outputSampleRate`. After the replacement, sample tracks seems to be synchronized correctly.

**Comment by Reflexe** [comment]
See a possible fix at: https://github.com/LMMS/lmms/commit/8323bf01670b8d74b1993e5088ae32ccc5d359b6
