### ISSUE TITLE
windows can be dragged into menu bar

### ISSUE THREAD

**Issue by smlfr** [LMMS/lmms#4795]
LMMS-Windows can be moved into the menu bar from where they can't be moved any more.

LMMS 1.2.0-rc7

![demo](https://user-images.githubusercontent.com/20004037/51786413-2d2ed180-2164-11e9-8a01-5e9ebd71cbf3.gif)

**Comment by smlfr** [comment]
>This looks like a duplicate of #765.

Correct! Didn't find that one.

**Comment by zonkmachine** [comment]
Thanks! Closing.
