### ISSUE TITLE
Context Search-field: Decide its position 

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#4798]
In RC7 the side-bar options for amo *Samples* **search-field** and **refresh-button** are placed in the bottom of the screen. In RC4, in the *top* of the screen. Have it been decided where to finally place these two components?

I strongly favour *In top of the screen*, because :
* it is in eye-focus in a natural way.
* Most common search-fields in webpages and in other programs also have search-fields placed in the *top of the screen*. 

so **Top** is intuitively better for RC8 ->

**Comment by zonkmachine** [comment]
> RC4, in the _top_ of the screen.

You probably have a version of master that was built after rc4 was merged into it. Hence the rc4 label.
The 'search field in the top' fix is in master.

Is this the issue you're referring to?
https://github.com/LMMS/lmms/issues/3657
https://github.com/LMMS/lmms/pull/3662




> for amo _Samples_

amo?

**Comment by musikBear** [comment]
amo 'among others' afaik :)
Thanks - i close this

**Comment by zonkmachine** [comment]
> amo 'among others' afaik :)

Don't use acronyms. Please!
