### ISSUE TITLE
Cloning beat/bassline patterns

### ISSUE THREAD

**Issue by digitalghosterror** [LMMS/lmms#4803]
When cloning an instrument pattern, there is an issue with the clone. Pre-saving, the pattern will be visible but will play no audio unless the piano roll is opened. Upon saving, closing and loading the same project the pattern will be shifted forward to the next beat/bassline.

I have taken screeshots to illustrate.

Here is what I did last night. Created a basic song loop and then duplicated the beat/bassline in the song editor and made changes to the 2nd version in the beat/bassline editor. Then I cloned an instrument and set the original version to mute.
In the first set of screenshots, the cloned instruments appear to have the cloned patterns, however, playing them produces no sound. 
![screenshot_2019-01-29_23-29-26](https://user-images.githubusercontent.com/47169523/51961596-ec85cf80-2465-11e9-9acd-e55c57339f51.png)
![screenshot_2019-01-29_23-29-48](https://user-images.githubusercontent.com/47169523/51961611-f4de0a80-2465-11e9-917d-346a865b5f58.png)
Then I save, close and reopen the project.
Upon doing this, you will see the cloned instrument in the original beat/bassline is blank
![screenshot_2019-01-29_23-30-44](https://user-images.githubusercontent.com/47169523/51961685-3f5f8700-2466-11e9-83b3-3f8b4ba3a613.png)
and the cloned instrument of the duplicate appears unchanged.
![screenshot_2019-01-29_23-31-45](https://user-images.githubusercontent.com/47169523/51961764-83eb2280-2466-11e9-8361-09bad866ce4e.png)
However, playing that beat/bassline in the editor now plays the notes from the original. Opening it in piano roll plays the notes from the duplicate (what it should be playing).

Not sure how else to explain this as the concept is confusing. Not sure if this happens on windows. Happens with samples too, not just vst instruments. 

Current system : 64 bit xubuntu and 64 bit lmms (1.2 RC7).

**Comment by musikBear** [comment]
> Not sure if this happens on windows.

Does not on xp3&RC7. Track-Clones plays/ behave just like Orr. track

**Comment by tresf** [comment]
> Does not on xp3&RC7. Track-Clones plays/ behave just like Orr. track

Same here, macOS, RC8.  @digitalghosterror is there a chance that the bug is related to the use of a VST?  Can you reproduce it when there's no VSTs?  Your steps are pretty clear, but there may be a step that @musikBear and I are missing when we try to reproduce.  If you can write up a use-case that has a minimal amount of tracks that reproduces it every time, then we can see if there's a bug in the code.
