### ISSUE TITLE
Bug when building on void linux

### ISSUE THREAD

**Issue by porky11** [LMMS/lmms#4806]
Almost everything works as expected, but not the linking of the executable.
The error I get is this:
```
/usr/bin/ld: 3rdparty/rpmalloc/librpmalloc.a(rpmalloc.c.o): relocation R_X86_64_32S against `.text' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: final link failed: nonrepresentable section on output
collect2: error: ld returned 1 exit status
```

**Comment by JohannesLorenz** [comment]
Is this even an *LMMS* issue?

At what stage does it happen? (We could need the full build log)

**Comment by porky11** [comment]
It happens during this command, when calling `make -j4`:
```
[100%] Linking CXX executable ../lmms
```
I don't think, the rest of the generated output will help. It's basically just a list of what's compiled.

**Comment by PhysSong** [comment]
@porky11 Could you try this patch?
```diff
diff --git a/src/3rdparty/rpmalloc/CMakeLists.txt b/src/3rdparty/rpmalloc/CMakeLists.txt
index 23d1551c2..2d94bcdfd 100644
--- a/src/3rdparty/rpmalloc/CMakeLists.txt
+++ b/src/3rdparty/rpmalloc/CMakeLists.txt
@@ -1,5 +1,9 @@
 set(CMAKE_C_FLAGS "-std=c11")
 
+if(NOT WIN32)
+       set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fPIC")
+endif()
+
 add_library(rpmalloc STATIC
        rpmalloc/rpmalloc/rpmalloc.c
        rpmalloc/rpmalloc/rpmalloc.h
```

**Comment by porky11** [comment]
I found it in the repos now, so I don't need to build it myself anymore. Not sure, why I didn't see it before.

**Comment by JohannesLorenz** [comment]
That does not mean that the bug is fixed. Try @PhysSong 's patch or find out how the void linux packagers did build their package.

**Comment by JohannesLorenz** [comment]
@devnexen Do you think this will also be fixed with the rpmalloc update?

**Comment by devnexen** [comment]
Even tough I would like the update not sure it is related here, seems just a linkage issue. it seems lmms cmake to build rpmalloc rather than ninja rpmalloc build system.

**Comment by PhysSong** [comment]
From Discord by @Sawuare:
> I get errors while building master on Kubuntu 21.04:
> ```
> [ 98%] Linking CXX executable ../lmms
> /usr/bin/ld: CMakeFiles/lmmsobjs.dir/3rdparty/weakjack/weakjack/weak_libjack.c.o: relocation R_X86_64_32 against `.bss' can not be used when making a PIE object; recompile with -fPIE
> /usr/bin/ld: 3rdparty/rpmalloc/librpmalloc.a(rpmalloc.c.o): relocation R_X86_64_32S against `.bss' can not be used when making a PIE object; recompile with -fPIE
> collect2: error: ld returned 1 exit status
> make[2]: *** [src/CMakeFiles/lmms.dir/build.make:610: lmms] Error 1
> make[1]: *** [CMakeFiles/Makefile2:871: src/CMakeFiles/lmms.dir/all] Error 2
> make: *** [Makefile:171: all] Error 2
> ```

> Adding `-fPIE` to `CMAKE_C_FLAGS` in `src/3rdparty/rpmalloc/CMakeLists.txt` fixed the rpmalloc error

Looks like a related bug. Should I reopen this, or make a new bug report?

**Comment by JohannesLorenz** [comment]
> Looks like a related bug. Should I reopen this, or make a new bug report?

I'd prefer a new issue, since this one here is really old and it's not sure how it is related. You could link this issue there. But I leave it to you.
