### ISSUE TITLE
Missing Part in Short Composition

### ISSUE THREAD

**Issue by FreshMisty** [LMMS/lmms#4808]
Very new to the program so I'm not sure if I did something wrong here. Using LMMS 1.2.0, the website where I downloaded it said it was the beta version? Yesterday I had written a 5 measure part followed by a 4 measure part both for FreeBoy, then after that a custom synth drawn in BitInvader for 8 measures. I played it all the way through one more time before saving it as a project and closing the program. Today I open the program and load up the project from the side menu and it's missing the 4 measure Freeboy part. I tried restarting the program and opening it from the File>Open menu as well and the part is still missing. Very anxious that this may happen again with larger pieces of music or larger parts written. If there's anything I can do to prevent this from happening again I'd like to know. Missing part is highlighted in attached picture.
![lmms missing part](https://user-images.githubusercontent.com/47289049/52172762-fee45f80-272a-11e9-902e-518b7ce2de21.png)

**Comment by PhysSong** [comment]
Could you upload the affected project file here? You can compress the project to a `.zip` file and upload it here.

**Comment by musikBear** [comment]
we also need to know your OS and added ServicePack, if any

**Comment by tresf** [comment]
> we also need to know your OS and added ServicePack, if any

No we don't stop asking these questions.

**Comment by tresf** [comment]
> Missing part is highlighted in attached picture.

By chance was this track Ctrl + Dragged from the Beat/Bassline editor?  If so, it may have what we call `zero length notes`, which will make the pattern go gray.

Even if it wasn't copied from Beat/Bassline editor, if the notes were copied from a converted step pattern to a Piano Roll, the cursor size will get stuck on zero-length-note and perpetuate the problem.

![image](https://user-images.githubusercontent.com/6345473/53933577-fc985c80-406c-11e9-896f-cd244463edd4.png)

If this is the symptom, you still may be able to double-click the pattern and see the notes.  Adding a single, NON-zero-length-note will turn it back into a piano roll.

If what I'm describing isn't even close to what happened, what you're experiencing is very rare.  Save often (the software can crash), but no, you shouldn't expect patterns, to disappear.

As @PhysSong mentioned, please zip and upload the project so we can take a look at the underlying data.
