### ISSUE TITLE
Ergonomy in the connection configuration window

### ISSUE THREAD

**Issue by rawthought** [LMMS/lmms#482]
When we go to the connexion configuration window (where we can assignate a midi channel or a peak controller to a knob or something) it would be nice to avoid extra mouse-clic by selecting automatically the appropriate mode (A) when we choose a controller (B) (for example, checking the "user control" box when we select a controller in the list)

![capture du 2014-03-18 16 28 05](https://f.cloud.github.com/assets/6923578/2490825/09fc23ea-b1c8-11e3-91e8-aad3a2b8e0c8.png)

**Comment by the-bebop** [comment]
As LMMS continued to develop I'm not sure if this is necessary anymore:

**Comment by Monospace-V** [comment]
I notice rawthought has been inactive for a few years. However, I believe this enhancement has already been implemented. Much the same way effects-enabled in the FX window automatically turn off when there are no effects and on when there are effects, I think selecting anything from the user controller dropdown menu automatically turns on user controllers and turns off MIDI controllers. However, this enhancement has been added only to 1.3 (alpha) and is not present in 1.2.0.

**Comment by the-bebop** [comment]
Thought so too but wanted to ping him first
