### ISSUE TITLE
Play chords, when a single key is pressed, and a chord has been selected in the chord-table

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#4820]
<Tittle> Could that be implemented?
It would be logical, that after a chord has been selected in the piano-roll chord-table, then pressing a single key on either the virtual piano, or the PC ao. MIDI-keyboard, the *chord* would play, with the pressed key as root-note. 
Inversions could be played with combos of f.i. num-keys

**Comment by sharpblade4** [comment]
I think this is solved by https://github.com/LMMS/lmms/pull/4990

**Comment by SecondFlight** [comment]
Yeah, I think you're right.
