### ISSUE TITLE
Hanging mouse cursor in piano roll

### ISSUE THREAD

**Issue by audiojoe** [LMMS/lmms#4822]
pointer does not follow active window

but remains stuck in the previous one
in this screen shot the pointer should be in the SONG EDITOR

![190212 lmms graphics problem - cursor on active field](https://user-images.githubusercontent.com/47551858/52615706-6a020480-2e96-11e9-8f4f-39908776dafe.png)

in WINDOWS 7

**Comment by tresf** [comment]
Reproduced.  Under certain common circumstances, the pencil icon stays behind.

**Comment by zonkmachine** [comment]
I also see this in the Automation Editor.

**Comment by T0NIT0RMX** [comment]
It happens a lot for me with Automation, Pianoroll, mixer, so glad you fixed it ! Thanks !

**Comment by sharpblade4** [comment]
@T0NIT0RMX  , I couldn't reproduce the bug in 'mixer', can you elaborate what is the experience you get vs what you except? a screenshot might be nice as well.

**Comment by T0NIT0RMX** [comment]
@sharpblade4
Sure, when I'll have the chance to get on it this evening, the thing is that it's not always reproductible,  but it's really anoying when you have a window, you click on it and the focus makes the windows beneath appearing..
I'll try to make a video, I think it will be even better to explain !
