### ISSUE TITLE
DPI Settings

### ISSUE THREAD

**Issue by donmor** [LMMS/lmms#4831]
I'm using lmms 1.2.0 AppImage build under Ubuntu 16.04 and its DPI goes too high, causing everything looks so big that I can hardly do anything, and when I switch to the Windows 10 and run the windows build, its DPI goes quite low that I can hardly see some parts of the UI.
I wonder should a DPI adjusting function solve this problem.

**Comment by musikBear** [comment]
For windows, there is a fix:
https://lmms.io/wiki/index.php?title=LMMS_Settings#Screen_Issues
That works with win10

**Comment by donmor** [comment]
So what about ubuntu? There's no compatibility option :(
Everything is so large that my screen is crowded with windows

**Comment by musikBear** [comment]
Sorry -i have no idea

**Comment by tresf** [comment]
@donmor, unfortunately some HiDPI displays don't scale properly.  There's more discussion around this here: https://github.com/LMMS/lmms/pull/4800#issuecomment-461681138

Please try this before running the appimage:

```bash
export QT_SCALE_FACTOR=1
export QT_AUTO_SCREEN_SCALE_FACTOR=0
export QT_SCREEN_SCALE_FACTORS=2
```

Note, by changing some advanced settings, some OSs (as well as xrandr) will allow fractional scaling for displays that are not a perfect upscale.  Our current AppImage scales properly for most but for those displays that don't work, we are not yet aware of a fix that we can combine into our software that will fix it and workarounds on the machine must be performed instead.

Closing as duplicate of #2510.
