### ISSUE TITLE
I wanna implement a ghost channel notes on the piano roll.

### ISSUE THREAD

**Issue by ca3games** [LMMS/lmms#4832]
Hi, I want to implement piano roll ghost notes, but I am new to the project, so I opened this issue to see if you guys can give me proper documentation or ideas on how to implement this feature.

I know Java and C# and python, so I think I could make this somehow, but I am unsure over what language or tools do I need to code this.

**Comment by DomClark** [comment]
Ghost notes have already been implemented in #4575, so I'm closing this issue as a duplicate. However, thanks for your interest in contributing to the project. LMMS is written in C++ using the Qt framework; if you're interested in contributing in the future, we're happy to help you out on our Discord server.
