### ISSUE TITLE
support TouchDAW

### ISSUE THREAD

**Issue by belcowin** [LMMS/lmms#4837]
Hi.

Yesterday, I bought TouchDAW android app and successfully connected LMMS 1.2.0 rc.8

At PC side, I am using rtpMIDI (virtual midi port emulator) and did set up 2 port.
One is for VSTi(of TouchDAW), another is for DAW(of TouchDAW)
And At Android side, in TouchDAW configure, i did set up MIDI port as that .

In keyboard screen of TouchDAW, MIDI input is works well, midi key-in and recording. Analog switches can be auto detected (with exact channel and controller numbers) well and can adjust analog switches of LMMS.

But in DAW screen of TouchDAW, analog switches cannot be auto detected for Connection Setting popup of LMMS. channel and controller numbers were just '---', not changed.

TouchDAW maybe has the mechanism that define profile for each DAW.
I tried all profiles. but not success.

Very strange thing, when i adjust an analog switches of DAW screen(of TouchDAW), PC play a note plus pitch variation. it's mean DAW port connected and works, right?

I monitored with VST midiMonitor x64.

When I pushed DAW controller' PLAY button, monitored as...
B0 0F 0E  Ch.1  CC #15 (), Value: 14
B0 2F 44  Ch.1  CC #47 (), Value: 68
B0 0F 0E  Ch.1  CC #15 (), Value: 14
B0 2F 04  Ch.1  CC #47 (), Value: 4

Below is for DAW's STOP button...
B0 0F 0E  Ch.1  CC #15 (), Value: 14
B0 2F 43  Ch.1  CC #47 (), Value: 67
B0 0F 0E  Ch.1  CC #15 (), Value: 14
B0 2F 03  Ch.1  CC #47 (), Value: 3

Below is when DAW's RECORD button...
B0 0F 0E  Ch.1  CC #15 (), Value: 14
B0 2F 45  Ch.1  CC #47 (), Value: 69
B0 0F 0E  Ch.1  CC #15 (), Value: 14
B0 2F 05  Ch.1  CC #47 (), Value: 5

As i guess, these midi codes are differ from each Sequencer profile of TouchDAW.
But, LMMS's play, record, stop, pause controls can be bind to DAW controller?

LMMS is free and TouchDAW app is $5. 
These combination is good start for not professional just hobby.

Thanks.

**Comment by NETMANSKY** [comment]
No. Unfortunately at this time playback synchronizing is not supported in LMMS yet. At least didn't work.

**Comment by tresf** [comment]
> But, LMMS's play, record, stop, pause controls can be bind to DAW controller?

As @NETMANSKY says, this isn't yet supported, sorry.  We are tracking this feature in #1472.  I've crosslinked this bug report.  Anyone interested in starting this feature, please submit a Pull Request!
