### ISSUE TITLE
Broken panning with LMMS RC8

### ISSUE THREAD

**Issue by KodzghlyCZ** [LMMS/lmms#4839]
I have Windows 10 and running LMMS 1.2.0 RC8 on it. But I have serious issue with panning. It doesn't seem to work at all, or it just adjusts a volume of separate channels and then it makes it mono. 

I have tried every audio output, but it didn't work as well. 

This issue seems to appear with audio file processor, but not in triple oscillator for example.

**Comment by KodzghlyCZ** [comment]
Problem solved by restarting PC, reconnecting all speaker cables, repairing the amplifier itself, repairing the audio cable and some magic. 

Nevermind, this bug is probably not real, but I had the exact same problem right after upgrading to LMMS RC8, but his problem was in badly recorded track and mine was the hardware problem.

**Comment by zonkmachine** [comment]
> Nevermind, this bug is probably not real...

OK. Closing for now. Please bump this issue if you experience this again.
