### ISSUE TITLE
Don't show error message when loading empty VeSTige instance

### ISSUE THREAD

**Issue by Spekular** [LMMS/lmms#4843]
If a VST plugin fails to load when a project is opened, LMMS will display the message "The VST plugin [plugin name] could not be loaded". However, the error check doesn't verify if there *should* be a plugin to load.

Steps to reproduce:
* Create a new project
* Place an instance of VeSTige in the song editor, without loading a VST
* Save the project
* Reload the project

An error message will show, stating "The VST plugin  could not be loaded". (Tested with 1.2 RC7/RC8)

If a VST plugin was never loaded in the first place, I'd expect the error message not to display.

**Comment by Spekular** [comment]
The message seems to be generated in vestige.cpp inside vestigeInstrument::loadFile

```
if( m_plugin->failed() )
	{
		m_pluginMutex.unlock();
		closePlugin();
		delete tf;
		collectErrorForUI( VstPlugin::tr( "The VST plugin %1 could not be loaded." ).arg( m_pluginDLL ) );
		m_pluginDLL = "";
		return;
	}
```

Would it suffice to check that the Qstring _file has a length > 0?

**Comment by Spekular** [comment]
Further testing confirms one of my suspicions.

Steps:
* Open LMMS, create a new project
* Add an instance of Vestige, load a VST instrument into it
* Save your project, close LMMS
* Move, rename or delete the VST dll so LMMS cannot find it
* Load your project
* **LMMS displays "The VST plugin [plugin name] could not be loaded"**
* Dismiss the dialog, save your project, close LMMS
* Load your project
* **LMMS displays "The VST plugin  could not be loaded"**

LMMS clears the VST when it fails to load. ``m_pluginDLL = "";`` seeps obviously responsible, but maybe other lines as well.

This makes it harder (if not impossible) to tell the difference between a VST that was never loaded, and a VST that failed to load once and was saved. It also makes the load error dialogue fairly useless.

In my opinion the solution is to not clear VST information when the VST fails to load. Instead, keep it around so the user can move the dll back into place or edit the project file to fix the paths.

**Comment by jasp00** [comment]
>Instead, keep it around so the user can move the dll back into place or edit the project file to fix the paths.

Fine.

**Comment by DomClark** [comment]
I've already got a fix for the empty VeSTige error locally; I'll put that in my next PR.

> In my opinion the solution is to not clear VST information when the VST fails to load. Instead, keep it around so the user can move the dll back into place or edit the project file to fix the paths.

Agreed. However, plugin state will still be lost; it is deserialised into and serialised from the VST plugin itself, so if the plugin is missing, the state will go too. Perhaps we should keep the whole `QDomElement` if plugin loading fails, and in that case use it to save again. This probably deserves a separate issue.
