### ISSUE TITLE
lmms-1.2.0-rc8-linux-x86_64.AppImage : no sound with JACK

### ISSUE THREAD

**Issue by sub26nico** [LMMS/lmms#4846]
I have a bug, confirmed by another user on french forum, with lmms-1.2.0-rc8-linux-x86_64.AppImage on LibraZiK distro (based on Debian Stretch). If I choose Jack as Audio interface, I have no sound, I can see sound is working in the master track in the mixer, but no output. It works nicely with previous versions (AppImage rc6, rc7). 
```
 /home/USER/Téléchargements/lmms-1.2.0-rc8-linux-x86_64.AppImage
Carla appears to be installed on this system at /usr/lib[64]/carla so we'll use it.
/tmp/.mount_lmms-1oGnTWw/AppRun: ligne 17: ldconfig : commande introuvable
Jack does not appear to be installed.  That's OK, we'll use a dummy version instead.
VST sync support disabled in your configuration
Connect: can't connect named semaphore name = jack_sem.1000_default_system err = Aucun fichier ou dossier de ce type
Cannot read socket fd = 21 err = Aucun fichier ou dossier de ce type
CheckRes error
JackSocketClientChannel read fail
Cannot open lmms client
jack_client_open() failed, status 0x21
No audio-driver working - falling back to dummy-audio-driver
You can render your songs and listen to the output files...

```

**Comment by PhysSong** [comment]
```
Jack does not appear to be installed. That's OK, we'll use a dummy version instead.
```
Are you sure that you've installed JACK? Without locally installed JACK server, the AppImage can't play audio via JACK.

**Comment by sub26nico** [comment]
> Are you sure that you've installed JACK? Without locally installed JACK server, the AppImage can't play audio via JACK.

Yes, Jack is installed , and as I said, it's works with 1.2.0-rc6 and rc7 (with Jack)

**Comment by PhysSong** [comment]
Then could you post the terminal output of RC7 with JACK?

**Comment by sub26nico** [comment]
```
/home/USER/Téléchargements/lmms-1.2.0-rc7-linux-x86_64.AppImage
Carla appears to be installed on this system at /usr/lib[64]/carla so we'll use it.
/tmp/.mount_lmms-1wzNgpp/AppRun: ligne 17: ldconfig : commande introuvable
Jack does not appear to be installed.  That's OK, we'll use a dummy version instead.
VST sync support disabled in your configuration
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map

```

**Comment by PhysSong** [comment]
```
/tmp/.mount_lmms-1wzNgpp/AppRun: ligne 17: ldconfig : commande introuvable
```
It seems like your system doesn't have `ldconfig`, right?

**Comment by jasp00** [comment]
It is normal that `ldconfig` is not available to regular users. `ldconfig` is not required for a working system either. `cmake/linux/package_linux.sh.in` should be fixed.

**Comment by damian01w** [comment]
I dont know if there is another similar issue, but no sound with Vestige using pulseaudio output on rc8. I've tested on archlinux rc8 package (available in oficial community repo) and lmms-1.2.0-rc8-linux-x86_64.AppImage with same results. No problems with rc7.

**Comment by sub26nico** [comment]
> ```
> /tmp/.mount_lmms-1wzNgpp/AppRun: ligne 17: ldconfig : commande introuvable
> ```
> 
> It seems like your system doesn't have `ldconfig`, right?

ldconfig is installed on my system (in /sbin/).

**Comment by Gabrielxd195** [comment]
The same thing happens to me but in my AV Linux 2018 distro. I can not use rc8 for this same audio error, and I do not know what to do, I do not see any connection of LMMS with Jack; however, I do not have that problem in rc7. rc8 has many improvements but it takes a long time for stable 1.2 to be released. right now debian users can not use rc8.

Is it possible to make a pr or a patch with this bug fixed?

**Comment by tresf** [comment]
I'll take a look.

**Comment by tresf** [comment]
> `ldconfig` is installed on my system (in `/sbin/`).

Same here on Debian 9.7.  If previous versions worked there may have been a bug see also fc9c3ea / #4186.  Anyway, the `ldconfig` approach is our workaround and it's how we have to handle this for libraries that we can't safely bundle along side LMMS.  I'll upload an build for testing shortly.

**Comment by tresf** [comment]
Here's a build with `/sbin` added to `$PATH` per e54969c. https://github.com/tresf/lmms/releases/download/v1.2.0-RC8/lmms-1.2.0-rc8.8-linux-x86_64.AppImage

**Comment by sub26nico** [comment]
@tresf , i have quickly tested (just made a little beat in the drums and bass editor) this v1.2.0-rc8.8-linux-x86_64.AppImage, and it works with JACK, thanks a lot.

**Comment by damian01w** [comment]
Working now again! Thanks for the quick response.
