### ISSUE TITLE
Drag-n-drop to BB

### ISSUE THREAD

**Issue by NETMANSKY** [LMMS/lmms#4848]
I don't know how it isn't  noticed yet. When BB-editor is full over and you drag and drop a plugin from the bar of Instrument Plugins to new track of BB-editor this action are changing existent instrument of track by new drag-n-dropping instrument.

**Comment by jasp00** [comment]
It is not intuitive, but you may add a new instrument by dropping to the scrollbar.

**Comment by zonkmachine** [comment]
Yes. You can change instrument in a track by dropping a new instrument on it. If there is no more space in the opened BBEditor you need to make it bigger or scroll down. When you can now longer scroll down you need to first use the Song Editor scrollbar, scroll up in there and move the BBEditor up some scroll back down again and then you have more space to extend the BBEditor. This is not intuitive.

Ways to work around this could include:
* Have the BBEditor scroll/expand down when you hover above the lower part of the window under a drop action.
* Add the same contect menu options in the preset bar for pluggins as is already there for presets.
![presetcontext](https://user-images.githubusercontent.com/6368949/53297876-53a86100-3825-11e9-9aa3-43c679d54a01.png)
*Allow dropping instruments/presets/samples to a BB track in the Song Editor.

**Comment by NETMANSKY** [comment]
@jasp00 @zonkmachine Thank you, thank you very much, guys!.. I know those ways to add a new track. But   I want to draw attention to children's diseases of our own favorite program. All of the above methods are intuitively incomprehensible absolutely. Are you agree for newbies it's a difficult way. And those moments are a lot. The reason is not most of us are not programmers. We havent see a future and just collect issues of trouble RC by RC. It has long time ago been necessary to discuss the global reprocessing of interface. But this opinion is not supported. In my opinion it is necessary to make it possible to change the instrument on the track at any time. Or best way to make it in editors. JUST add a button in bar of editor to add Insrument Plugins into new track.

**Comment by PhysSong** [comment]
Isn't this related to #3099? Or even a duplicate?

**Comment by zonkmachine** [comment]
A duplicate indeed. Closing this one.
