### ISSUE TITLE
iZotope plugins broken in RC8

### ISSUE THREAD

**Issue by Spekular** [LMMS/lmms#4849]
I've used Ozone Imager (freely available [here](https://www.izotope.com/en/products/master-and-deliver/ozone/ozone-imager.html)) and Neutron Elements on a project in RC6 and RC7, and they worked perfectly fine. In RC8, a "VST plugin [plugin name] could not be loaded" message shows up when loading the project, and the "Controls" button on the effects is gone.

Similar: #4095

**Comment by DomClark** [comment]
I can't reproduce this (Windows 10, 64-bit); the plugin loads fine for me. Are you trying to load a 64-bit version of the plugin into 32-bit LMMS? That would be a potential cause of this issue.

**Comment by Spekular** [comment]
I shouldn't be, as I downloaded the 64-bit installer (just uninstalled, re-downloaded and reinstalled to check).

About LMMS says Version 1.2.0-rc8 (win32/x86_64, Qt 5.4.2, GCC 4.9.4 20150716 (prerelease)).

**Comment by Spekular** [comment]
Can't reproduce this any more. Fairly sure it happened at least once after reinstall, but maybe my mind is playing tricks on me and I had the 32 bit version...
