### ISSUE TITLE
Change mmpz.bak backups, to mmp.bak backups

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#4852]
It is not good to have *compressed* .bak files!
In case the mmpz file is corrupted, and saved twice, the user will still loose all his work. It is **much** safer to have the bak file created as a mmp.bak!
A crucial point here is that The *mmpz->mmp method* **fails**, if the mmpz is corrupted. There is *nothing* to do!

**Comment by zonkmachine** [comment]
Can you link to a couple of those cases (lmms forum) where it has been confirmed that compression is the culprit?

**Comment by Spekular** [comment]
I thought the idea was that a broken mmp is easier to deal with than a
broken mmpz. This proposal seems like it could help with recovery rather
than preventing the error in the first place.

However, the increase in file size is a little uncomfortable. If it was
something like the recovery file, which there's only ever one copy of,
maybe it'd be fine. However, you can easily end up with almost as many .bak
files as regular projects if you version your project files.

**Comment by musikBear** [comment]
> you can easily end up with almost as many .bak
files as regular projects 

True! But that is a household issue. I used a programming tool, that always created backupsfiles, ever now and then, at opening, a message would show the user how many backups he had, and ask if he wanted to delete some. Delete-selection was then performed by user, manually.  

@zonkmachine
Here is one, but i think i have bommed out on 10
**That** said, its not at all often or many, but for the one that looses the project, its enough. It is always the same:
mmpz file is several MB. The converted mmp is 1.5 kb
I have asked for 'reasons' -Eg what did you do when the file got corrupted, noone 'did anything' / 'cant remember'
I have *never* corrupted af file
Have you?
Here is one corrupted mmpz:

? did it attach -i cant see it :|

**Comment by zonkmachine** [comment]
> bommed out on 10

?


> ? did it attach -i cant see it :|

No. Is this from a forum post? Link?

**Comment by musikBear** [comment]
>bommed out on 10 

-i failed in trying to assist in +10 cases

I am having issues with hub. surely because i have s*** old equipment :|
I will ping you on discord @zonkmachine -there i can attach files, afaik, anyway will try

**Comment by zonkmachine** [comment]
Thanks for the project file you sent me on discord. Here called, brokenFile1.mmpz.
Trying to uncompress it on the command line gave:

`$ lmms --dump ~/lmms/brokenFile1.mmpz qUncompress: Z_DATA_ERROR: Input data is corrupted`

Opening the file in a hex editor showed that the entirety of the file, 53546 bytes, was written with zeros.

The only thing I can think of that could prevent something like this to happen is if we reopen the  compressed file on creation and compare it to the original.

**Comment by musikBear** [comment]
> entirety of the file, 53546 bytes, was written with zeros.

Thats rather dismo.. 

> reopen the compressed file on creation and compare it to the original.

Yes, that would be one way, but that would take time, and users hate to wait..

I have to say, that with the prize-tag on HD/ USB-storage, 2-5 kb for a project in mmp-format, is still better that many hours of lost work.. idk :|

**Comment by tresf** [comment]
The lost work has nothing to do with the backup format.  `mmpz` is our current standard.  If you need to decompress it @zonkmachine provided perfectly fine instructions.

> Opening the file in a hex editor showed that the entirety of the file, 53546 bytes, was written with zeros.

This is the problem and it's something we need to fix, but we need more information and that needs to be reported by the OP, not 3rd party.
