### ISSUE TITLE
Adding shortcuts of frequent used and/or favorite VST plug-in in Instrument Plugins list

### ISSUE THREAD

**Issue by hek512** [LMMS/lmms#4853]
instead of openning vst.dll everytime..

**Comment by NETMANSKY** [comment]
You can save your favorite VSTi as preset. There in top right is button looking as floppy. Press-n-save :) After restart LMMS you can find it in folder VST of Preset in left sidebar.

**Comment by tresf** [comment]
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.
