### ISSUE TITLE
Space between viewport end and 0 value in Automation

### ISSUE THREAD

**Issue by Lyrcaxis** [LMMS/lmms#4860]
It's really hard to select the 0 value in the Automation Editor. 
The gizmo is only half drawn.
![image](https://user-images.githubusercontent.com/32474602/53554866-6b475880-3b49-11e9-9fcf-cf1c26b06733.png)

I suggest adding some additional space for it (or a value)

**Comment by musikBear** [comment]
It is generally difficult to 'grab' the points, **when** *high magnification* is used. I wonder if it could be possible, that the points was not scaled, or at least set a minimum size for the points.

**Comment by qnebra** [comment]
> It is generally difficult to 'grab' the points, when high magnification is used. I wonder if it could be possible, that the points was not scaled, or at least set a minimum size for the points.

Or move it away from scrolling bar by few pixels. I know, bit ugly workaround idea.

**Comment by tresf** [comment]
@Lyrcaxis I've documented this problem (as well as a near-identical issue with our Piano Roll Editor) in #4877 in the "Automation Editor" section.

As part of a pruning effort, this `enhancement` request has been archived in #4877.
