### ISSUE TITLE
Does not even start on Windows

### ISSUE THREAD

**Issue by metaa** [LMMS/lmms#4863]
I just installed the x64 version on my  x64 Windows 10 1809 PC.
After showing the splash screen and asking about creating the home directory (only first time), the program just closes and does nothing else. 🤔

**Comment by zonkmachine** [comment]
Which version of LMMS is this? 1.1.3 or 1.2.0 Beta?

**Comment by metaa** [comment]
I downloaded the latest *stable* version (1.1.3) from the website.

**Comment by metaa** [comment]
I just installed version 1.2.0-RC8 and that seems to work though.

**Comment by zonkmachine** [comment]
> Version 1.2.0-RC8 seems to work though, I just tried that.

Great! Lets call that issue fixed then. I think there is more than one "won't start on Windows" issue for 1.1.3 but they should all be fixed on the latest versions in development. Version 1.2.0-rc8 is pretty much what the next official stable release will look like. Closing.
