### ISSUE TITLE
Use "bar" instead of "tact"

### ISSUE THREAD

**Issue by M374LX** [LMMS/lmms#4865]
I have never seen the term "tact" referring to a bar anywhere except LMMS's source code, but I have found the reason for this: confusion with German _Takt_ (https://www.reddit.com/r/explainlikeimfive/comments/7bmitw/eli5_difference_between_beat_bar_steps_tempo_tact/)

I suggest changing the term from "tact" to "bar" before even more people reading the code get confused.

**Comment by musikBear** [comment]
Asshh - The code is *written* by a German : Tobias Doerfel - *Father* of LMMS...

**Comment by tresf** [comment]
@M374LX I don't think there are any objections, can you move this to a PR against master?
