### ISSUE TITLE
Rename MidiTime class

### ISSUE THREAD

**Issue by M374LX** [LMMS/lmms#4866]
The class ```MidiTime``` is not used exclusively for MIDI. So, it could be renamed to something like ```TimePos```. For the same reason, the CPP file should not be located in the ```src/core/midi``` directory.

**Comment by musikBear** [comment]
renaming and moving files around in projects, are pretty much comparable with moving wasps with your bare hands
It stings

**Comment by GingkathFox** [comment]
~~unless you use VSCode which (apparently) stops moving/renaming from breaking code~~

**Comment by tresf** [comment]
@musikBear please refrain from chiming in on codebase changes. <3

**Comment by tresf** [comment]
@M374LX I don't think there are any objections, can you move this to a PR against `master`?

**Comment by claell** [comment]
@tresf Just to get this right, in #4890 you said

>Please do not cause inconsistencies in the codebase.

So you actually are ok with renaming classes? I thought you meant that with inconsistencies.

**Comment by GingkathFox** [comment]
nice :D
