### ISSUE TITLE
Two "Enable loop" buttons on AudioFileProcessor (tooltip issue)

### ISSUE THREAD

**Issue by M374LX** [LMMS/lmms#4867]
The tooltip description of the button for ping pong loop on AudioFileProcessor is simply ```Enable loop```, the exact same as in the other loop button, which repeats the sample without reversing.

Should it not be ```Enable "ping pong" loop```?

**Comment by musikBear** [comment]
True, the one with "end-to-end" piktogram should be renamed. 
*ping-pong*.. -isent that also used for alternating echo between speakers? 
maybe *palindromic* ?

**Comment by tresf** [comment]
Thanks!
