### ISSUE TITLE
ASIO4ALL disability though Latest portaudio DLL upgraded .

### ISSUE THREAD

**Issue by CaBachhav** [LMMS/lmms#4873]
on my 32 bit Dell laptop , sigmatel onboard drivers works fine with ASIO4ALL wrapper used in other daws like reaper etc. I upgraded the latest portaudio32 DLL with old that come with lmms 1.2 rc . Yet no audio output .plz suggest some tips. I also tried Beringer uca222 but don't work.

**Comment by musikBear** [comment]
Currently no Asio4all support afaik
Properly this https://github.com/LMMS/lmms/issues/1173 comes closest to this subject

**Comment by tresf** [comment]
We just brought PortAudio back in https://github.com/LMMS/lmms/pull/4770 but ASIO4ALL is a 3rd party product and we have no official support for it.  If you'd like to spearhead support for it, we can talk about it on Discord, but please don't ask us to support this.  If we start officially supporting 3rd party device drivers, we need volunteers, not blind requests.

Note, as always with bug reports, please specify the exact version, steps expected and actual behavior.
