### ISSUE TITLE
 Close without Saving button not translated 

### ISSUE THREAD

**Issue by jony0008** [LMMS/lmms#4880]
The "Close without Saving" button that appears when closing LMMS with an unsaved project is not in Transifex. I have seen this in other projects and that string comes from the Qt GNOME theme, not LMMS.

It is the same issue: https://bugs.launchpad.net/calibre/+bug/1703101

**Comment by tresf** [comment]
I would prefer not to hard-code a button that the OS provides natively.  Can you find evidence that the `Qt GNOME theme` has this bug?  If so, the bug should be filed upstream with them so that all projects that use it can benefit from getting this bug fixed.
