### ISSUE TITLE
Special window for Automation Editor

### ISSUE THREAD

**Issue by Lyrcaxis** [LMMS/lmms#4886]
Since #4877 is here, I'd like to suggest "this" as well.
Automations should have their own UI Window, is my opinion. 
![image](https://user-images.githubusercontent.com/32474602/54165525-baef2380-4469-11e9-8324-580e39c5d370.png)

F8 should open a UI on which all Automation Tracks appear and can be selected to be edited..
I realize this may be a long-term update but it's definitely worth it imo.

Also, Different display + placement modes: (Rounded, Decimal, %) would be dope.

PS: This may not be crystal clear, but this means Automation Tracks won't appear under the "Song Editor"

**Comment by tresf** [comment]
I don't see any features that aren't part of our current UI.  Furthermore, the purpose of #4877 is to stop the floodgates of wishlist bug reports, not add more of them.

**Comment by Lyrcaxis** [comment]
> I don't see any features that aren't part of our current UI. 

That's because I copy-pasted everything from LMMS' current UI.
Only thing I had to add is the Warning panel and the Viewport's Width & Height (Min/Max) values.
![image](https://user-images.githubusercontent.com/32474602/54169133-26d98800-447a-11e9-9a06-a5fca37441ae.png)

But since you closed the issue, I assume you decided this is worse than what LMMS currently has?

**Comment by SecondFlight** [comment]
Our open issue count has been steadily growing over the last 5 years. The biggest offender here is reports that basically go something like this:

"Here's this thing that would make LMMS better, please somebody go add it."

To be clear, there's nothing wrong with this kind of report, but these issues are the ones that clutter up our list. In the past we haven't closed them until they've been added, but if we keep leaving these issues open, we'll keep getting more and more of them and that number will just keep going up.

I'll leave it to @tresf to defend closing the bug as opposed to consolidating in #4877.

**Comment by tresf** [comment]
> I'll leave it to @tresf to defend closing the bug as opposed to consolidating in #4877.

The feature I think that's nice is the warning about the track length.  MIN/MAX is currently decided by the connection, length is already drawn by the cursor.  We have some conversations already on record about how to do one automation track to many different value ranges dating back 5 years.

But all said and done, DAWs don't do automation this way.  Taking the tracks out of the sequencer is a terrible idea.  Context is important in any editor.    Quoting myself in #1959:

> I like the idea in principle. Most track-based automation overlays the actual lines over the track thumbnails (or previews) so I would rather take this a bit further and have the lines drawn right over the patterns in the Song Editor (for example, like most video editing software does for fade in/fade out).


Making a dedicated window editor actually brings the automation curves even more out of context and are in a large part a regression.

But @SecondFlight we can't go into long detail explaining every bug close.  If we do, it'll never get done.   Good DAWs are out there and people use them.  We don't need to rehash every feature we're missing in long detail.  That's hoarding. 🙁

**Comment by SecondFlight** [comment]
Yep, I'm with you there. Better to focus on large-scale improvements than incremental minor fixes that don't fully solve the overall UX.
