### ISSUE TITLE
Two little points into #4877

### ISSUE THREAD

**Issue by NETMANSKY** [LMMS/lmms#4887]
Now a list of improvements for the future development of LMMS #4877 is being formed. I would like to suggest two important points in my view.

First.
Based on experience with numerous daws I have the impression that Spacebar should be implemented as a global playback button but not as a separate button for each LMMS editor. Sometimes it is very inconvenient to move between the Editor Windows to simultaneously track the readings and listen to the section of the song. Especially on small screens 15" and 17".

Second.
It was here #3485. It seems to me that instrumental plugins should be integrated into the FX chain. This is necessary for easy drag-and-drop movement in the FX chain. Logically, it will also be able to bring us closer to MIDI routing between effects and instrumental plugins in the chain. At this moment it is impossible, because the instrumental plugin is always at the beginning. I understand that LMMS has a built-in arpeggiator and Corder, but their functionality cannot replace Bluearp, WA Instascale, CodeFN Chordz. And they should be in front of the instrumental plugin...

Third.
Thank you for heard me out. :)

**Comment by tresf** [comment]
> not as a separate button for each LMMS editor. 

That's "a better transport".  Already on the list.

> It was here #3485. It seems to me that instrumental plugins should be integrated into the FX chain. 

You're talking about effects that generate notes.  We don't support these yet.  Search around, find it, and I'll add it to the list.

We still have > 600 bug reports to comb through.  Please stop adding fuel to the fire.

**Comment by tresf** [comment]
> You're talking about effects that generate notes. We don't support these yet.

This may be as simple as adding an internal MIDI routing layer.  Windows doesn't have any dummy MIDI channels to ride on, but the "Better MIDI support #1472" meta issue has something similar mentioned:

> (Windows) empty/assignable MIDI channel #793
