### ISSUE TITLE
Effect proposal: "Sound sculptor multi-tool" Taking some effects from around the daw and integrating them into one easy to use effect.

### ISSUE THREAD

**Issue by TheDichotomist** [LMMS/lmms#489]
Not sure if this is a feature request or not but here goes nothing...

This effect proposal could get complex... just know that everything you need in it is already in lmms... just not set up right and lacking a few SIMPLE features. If it sounds over complicated and unnecessary... IT'S NOT! Trust me as a sound designer... this WILL help this program a LOT

ok remember the filter and envelope section in the channel/plugin settings window?
"this one": 
![lmms env](https://f.cloud.github.com/assets/6994378/2456553/24b46e76-af1c-11e3-814e-6745a3964ac3.PNG)

take that and make it it's own effect. preferably with multiple voices (filters running in unison rather than in series) have it open in it's own window (like vst and other fx do) 
the entire window would be about the same size as the fx channel settings window but with the spectrum analyzer always off to the right

A bit more like this: 
![lmms filter concept1](https://f.cloud.github.com/assets/6994378/2456558/5660cee2-af1c-11e3-8855-3514df5714b5.PNG)

in this window you see a tabs section just like the ones in channel settings
![capture](https://f.cloud.github.com/assets/6994378/2456572/c4e7cc9e-af1c-11e3-8a8f-a64bf18452f1.PNG)
Rather than the default [Plugin, env/lfo, funx, fx, midi] the top bar would contain the following:
 {Preamp, Filter1, Filter2, Filter3, Filter4, Phaser, Delay, Flanger, Compressor, EQ} 

The bottom bat would remain largely the same based on the current tab in the top bar.

Note that the order of some of these effects can be changed as i don't know which order to arrange them in to get the best sound
Under the filter tabs you would see exactly the same thing as in the plugin/channel settings window, just taking these filters, env sculptors (for cutoff and resonance), and lfo's and making 4 of them run in unison (or series... which ever will give me amazing multi filter sweeps) Just like the fx chain these fx/filters would be enable/disable-able. Each effect would follow it's own envelope and each envelope would have a loop function with tempo synced loop speed.... let me STRESS that every effect mentioned/included in this tool should have it's own envelope (with looping),LFO, and obviously it's own parameters under it's respective tab 

Please, do get creative with this multi tool... add other things like reverb and chorus flanger (You know what would be a great addition to this thing... "Barry's satan maximizer" after the filter's signals .... please add that XD ) 

idk if you guys know just how INCREDIBLY POWERFUL AND USEFUL an effect like this would be... trust me, this would change up the sound of ANY instrument you attach it to with multiple filter's sweeping from high to low at the same time with looping ENV for some really cool bouncing effects... if you want an example of what i'm talking about.. check out Kairatune and fruity love philter. kairatune is an amazing synth because it has a plugin much like the one i described built into it... the synth itself is very simple and not that powerful but because of those sound sculpting effects all running in one easy to use and keep track of interface... you can make some amazing sounds with this.. just imagine hooking that effect up to the 3xosc or opulanze or any other vst synth.... holly mother of god PLEASE MAKE THIS!!! =D ...... Thanks

**Comment by Spekular** [comment]
Close? I think this issue is poorly defined and there are better ways to achieve what OP wants.

Please reopen if you disagree.
