### ISSUE TITLE
Solo button in groups of channels or buses

### ISSUE THREAD

**Issue by Gabrielxd195** [LMMS/lmms#4912]
When I have many clues, I organize them and make groups of tracks or buses, and sometimes I want to listen to a single group. the problem is that when I press the '' solo '' button of the selected bus or group, even the tracks assigned to the group are muted, and then I have to activate them one by one manually. for example:
![Boton de solo](https://user-images.githubusercontent.com/26127693/54960873-e62b4580-4f34-11e9-9687-c37acdbf3638.png)
In this case I have a string section and I have the whole song divided into groups and subgroups, sometimes I want to hear only the group of strings, but when I press the '' solo '' button of the group of strings, all the clues even those of the group. Can this be fixed? regards

**Comment by Spekular** [comment]
Related #2637
