### ISSUE TITLE
Option to clone without patterns.

### ISSUE THREAD

**Issue by Gabrielxd195** [LMMS/lmms#4913]
Sometimes I want to clone some instrument track to replicate its configuration and gain more time, but the problem is that all its patterns are also cloned and I have to delete them all manually one by one, this happens with the patterns of instruments and those of bb editor. something like in this image:

![Clonacion masiva](https://user-images.githubusercontent.com/26127693/54961546-82eee280-4f37-11e9-9097-d8653210389d.png)

I suggest that in the menu of configuration of the tracks, under the option: '' clone this track '', add the option: '' clone without patterns '' (or something like that), giving us the possibility to clone the tracks without cloning the patterns and thus improve the workflow when cloning clues. regards

**Comment by Spekular** [comment]
There's a "clear track" option in the track options already. I'm not sure
adding a new option to the menu is worth it to save a single click.

**Comment by SecondFlight** [comment]
There is a feature in `master` that solves the workflow issue described here in a more elegant and much more general way. See this PR: #3649

With this new PR, here's the steps you would take:
  1. Clone the track
  2. Zoom out
  3. Use ctrl+drag to select all patterns on the track
  4. Press `del` to delete all selected tracks

I'm going to go ahead and close this. Feel free to leave a comment if you don't feel this will solve the described issue.

**Comment by SecondFlight** [comment]
Also, based on what @Spekular said, it sounds like there is already a quick way in 1.2 to remove all patterns from a track.
