### ISSUE TITLE
mono-stereo output button.

### ISSUE THREAD

**Issue by Gabrielxd195** [LMMS/lmms#4915]
Currently to change the stereo-mono output of a track or know how it would sound, you have to look for a plugin called: stereo matrix.

![Stereo matrix](https://user-images.githubusercontent.com/26127693/54962951-3dcdaf00-4f3d-11e9-85c6-278f147419e3.png) 
the plugin is useful if you know how to use it correctly.

But I think it's a bit annoying to have to add and configure a plugin for such a simple function, and more if there are many tracks and you want to listen to them one by one, that's an unnecessary consumption, that would be solved with a simple button in the editor of song on the tracks and on the fx mixer. something like:
![Boton mono-stereo](https://user-images.githubusercontent.com/26127693/54963975-10830000-4f41-11e9-851a-f76ff45222bf.png)

In this model you can see a button under the '' solo '' button, this added button will fulfill the function of stereo-mono: blue is in mono, and gray (by default) in stereo, can be applied in song editor , editor bb editor and fx mixer. this comes by default in many daw, while the other buttons are disabled this would improve the workflow at the time of mixing, as users always ask for better workflow. regards

**Comment by Spekular** [comment]
A button on mixer channels is not the way to solve this. Other DAWs have a
stereo wideness knob on their mixer channels, and if this kind of feature
is to be implemented in LMMS it only makes sense to do the same.

**Comment by SecondFlight** [comment]
Couldn't agree more with @Spekular.

**Comment by musikBear** [comment]
@SecondFlight Absolutely! Real-estate on the track-button is more precious than a certain 'ring' from litterature ....
(Imo reserved for mixer-channel-number) :+1 for a wideness dial in mixer

**Comment by Gabrielxd195** [comment]
@Spekular Well, I had not thought about that. a knob would be better than a simple button for this function. but currently it is very cumbersome to have to open and configure the stereo matrix or another plugin only to change from stereo to mono or to the reverse. I'm going to close this thread. Thank you
