### ISSUE TITLE
How to understand LMMS's internal plugins nature?

### ISSUE THREAD

**Issue by zervankoru** [LMMS/lmms#4916]
I am very curious about music plugin's standarts, such as VST, LADSPA, LV2 and others. But how to understand LMMS internal plugins, such as **audio_file_processor**. Is it LADSPA or something else type of plugin? Can I use it somethere outside of LMMS, for example in Ardour? Same about other plugins, such as **bit_invader**

**Comment by SecondFlight** [comment]
These plugins are native to LMMS and use a built-in plugin format that is tied very closely to LMMS. They cannot be used elsewhere.

**Comment by tresf** [comment]
> Can I use it somethere outside of LMMS, for example in Ardour? Same about other plugins, such as bit_invader

As @SecondFlight mentions, the plugins won't work elsewhere.  To make your own, the internal working are best described here: https://github.com/LMMS/lmms/wiki/Plugin-development

That said, several years ago, @pgiblock ported some of the native LMMS instruments to LV2 format, which can theoretically be used elsewhere. https://github.com/pgiblock/lmms-lv2

**Comment by JohannesLorenz** [comment]
Good sources to start:
* [Plugin.h](https://github.com/LMMS/lmms/blob/master/include/Plugin.h) is now well documented
* [Amplifier](https://github.com/LMMS/lmms/tree/master/plugins/Amplifier) is the most simple effect plugin
* [The Lv2 PR](https://github.com/LMMS/lmms/pull/4899) documents support for plugin collections
