### ISSUE TITLE
rc8 - unable to change tempo/bpm

### ISSUE THREAD

**Issue by cvazx** [LMMS/lmms#4921]
ubuntu 18.04..

I can open any session, if i change the tempo and hit play it reverts to it's original. No tempo automation involved with these sessions. Have not checked against previous versions.

**Comment by T0NIT0RMX** [comment]
Can you try to right click on the tempo and "remove global automation" (something like that) ?

**Comment by cvazx** [comment]
> Can you try to right click on the tempo and "remove global automation" (something like that) ?

TONITORMX

Thanks so much. That was it and something i would have never found in the manual.
