### ISSUE TITLE
Detailed plugin information in PluginBrowser its header broken.

### ISSUE THREAD

**Issue by CYBERDEViLNL** [LMMS/lmms#4924]
The detailed plugin information that should appear when hover a plugin doesn't show.  It should show in the plugin-brower its header as described here https://github.com/LMMS/lmms/pull/3773

LMMS version: latest master
OS: tried Arch and Debian

**Comment by Spekular** [comment]
It ought to show in a tooltip rather than at the top of the list, but if it's not showing at all that's a bug either way.

**Comment by CYBERDEViLNL** [comment]
The tooltip does show, I expected the description to appear in the header with a big icon like in https://github.com/LMMS/lmms/pull/3773 but if thats no longer the case I'm fine with it and this can be closed. (must have missed something) :-)

**Comment by CYBERDEViLNL** [comment]
Ah. I re-readed the comments. Makes sense now.
