### ISSUE TITLE
ignore capitals in Token-search

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#4925]
Sometimes i find it difficult to find a resource, even though i can remember its name. The reason is that LMMS make distinktion between capital letters and small letters.
So  where it would be logical that 'Horn01' and 'horn02' was listet directly after each other, they wont be if we have a series of 'Hot xyz' named resources. 
I suggest that capitals in names/ labels are ignored in Token-search-*listings*.
(May bee an accessibility related thing as well)

**Comment by PhysSong** [comment]
Currently, it looks like this(case-sensitive):
```
AB.wav
Ba.wav
aa.wav
bb.wav
```
The suggestion is(case insensitive):
```
aa.wav
AB.wav
Ba.wav
bb.wav
```
I think it should be easy to change the behavior because `QDir::entryList` have an option to ignore cases when sorting. However, I'm not sure if all people think the latter behavior is desired.

There are several different options:
* :laugh:: Keep the current behavior
* :eyes:: Ignore case when sorting(change to the latter behavior)
* :heart:: Add an option to allow users to change the behavior

Please let me know user opinion!

**Comment by musikBear** [comment]
yes, an *option* for *user* to decide, is a brilliant idea!

**Comment by musikBear** [comment]
:| cant 'vote' -The smileys are not click-able in this browser, so you can add one for "3"
> Add an option to allow users to change the behavior

**Comment by SecondFlight** [comment]
@musikBear I'll add a vote for you for :heart:. For the record though, my vote is :eyes: :)

**Comment by musikBear** [comment]
@SecondFlight  Thanks! :+1

**Comment by noahb01** [comment]
Definitely change it. When you have a ton of presets, it ends up looking like its been alphabetized twice (first all the caps, then the lowercase), which makes finding the preset/sample you want harder than it needs to be.

**Comment by the-bebop** [comment]
hey all I'm fairly new to LMMS coding, but I'd I think I can start on this one.

**Comment by zonkmachine** [comment]
> hey all I'm fairly new to LMMS coding, but I'd I think I can start on this one.

OK. Assigning you to the issue.   ;)

**Comment by the-bebop** [comment]
Thanks, just to make sure we're on the same spot we're talking about list elements like the _my presets_ browser i.e. in the fixed version _orion.xpf_ should be put before _SString.xpf_ see example screenshot from a freshly built lmms:

![grafik](https://user-images.githubusercontent.com/62464098/102821224-01abd480-43d7-11eb-88ab-52e1b06f5fd0.png)

correct?

So concludingly:
- Instrument Plugins
- My Presets
- My Projects
- My Samples
- My Home
- Root directory

should be adjusted. Do we care also about the _LADSPA Plugin Browser_? Anything else I missed?

**Comment by musikBear** [comment]
>  Do we care also about the LADSPA Plugin Browser? 

That item is an odd one. It let you look at options, but non can be changed. I have to say that besides giving LADSPA-devs an option to look into existing settings, its hard to see why we still have this component as a std-component in lmms(?) Imo we could have it as a external separate downloadable module.
Have anyone ever used it *as part of* creating or working with a project.
Lets see if someone chimes in with a super reason for keeping it embedded in lmms , before you @the-bebop does work on it.

**Comment by the-bebop** [comment]
alright I think my solution is ready, however I have no push-permissions:

```
git push --set-upstream origin 4925-ignore_capitals_in_token-search
ERROR: Permission to LMMS/lmms.git denied to the-bebop.
```

**Comment by Spekular** [comment]
> alright I think my solution is ready, however I have no push-permissions:

We use Pull Requests. You'll want to fork LMMS, push your changes to a branch on the fork, and then create a PR via the Github web interface.
