### ISSUE TITLE
Importing some midi file crashes at 69%

### ISSUE THREAD

**Issue by franckcl95** [LMMS/lmms#4926]
Hi,
I'm trying to import a midi file and LMMS (v1.1.3) stays at 69% !!
Do you know this issue ?
The file is here: http://www.sofa-group.fr/midi/talkingloud.mid

Thanks
Franck

**Comment by CYBERDEViLNL** [comment]
I tried importing that file with 1.2.0-RC8 and with the latest master, it looks to import correctly, nothing gets stuck here it imports straight away.

Maybe old bug can you try 1.2.0-RC8?

**Comment by zonkmachine** [comment]
Yes, this is a known issue and has been fixed in 1.2.0 . Thanks for reporting.
