### ISSUE TITLE
Redesign of Monstro waveforms icons

### ISSUE THREAD

**Issue by RoxasKH** [LMMS/lmms#4940]
As i'm working on Microwave design as some of you probably know, i decided to redesign the icons monstro uses for the waveforms, because in my opinion they're pretty blurry.

Here's a view
![All2](https://user-images.githubusercontent.com/40141826/56051069-d6419d00-5d4d-11e9-8c65-c7fe6063b761.png)

Let me know, and thanks for your work

**Comment by Umcaruje** [comment]
This looks cool, please make a PR for replacing the files.

**Comment by RoxasKH** [comment]
@Umcaruje I've never done my branch, but if it were only changing images i would do that. The problem is that i think some of them are larger of 1 or 2 px, so i need someone to tweak the code a bit.

**Comment by RoxasKH** [comment]
I've never done a PR, and also there seems to be a problem beacuse some icons are larger than original ones, and the dropdown box code automatically puts in a few pixels of blank space on the left, I don't think that can be removed as you can see here.

https://streamable.com/hp7gc

**Comment by RoxasKH** [comment]
I want them just to works this way https://cdn.discordapp.com/attachments/485542664570273804/566617187561897995/Example.png

**Comment by DouglasDGI** [comment]
This change has been merged, closing this issue.
