### ISSUE TITLE
Show/Focus BBEditor on TrackLabelButton click

### ISSUE THREAD

**Issue by CYBERDEViLNL** [LMMS/lmms#4946]
Often do I click on a BBEditor ~or a AutomationEditor~ it's TrackLabelButton and apparently aspect the corresponding editor to open and to be on top, but that’s currently not the case and that bugs me. Can we change this behaviour so that it does open and go on top ~(empty or not)~ ? 

**Edit**: as Spekular pointed out here https://github.com/LMMS/lmms/pull/4959#issuecomment-486203633 it is rather pointless to aspect the same behaviour for the Automation Editor.

**Comment by JohannesLorenz** [comment]
Fixed by #4959
