### ISSUE TITLE
Ideas for better audio sample manipulation anyone? 

### ISSUE THREAD

**Issue by TheDichotomist** [LMMS/lmms#495]
to name a few...
time stretching/pitch lock....... i know there is some open source code for this in mixxx...
chopping samples up into smaller ones and allowing us to edit/reverse the individual snippets 

Maybe there could be a midi instrument that takes samples (like vocals) and lets you chop them into pieces that can be played in the piano...

i can see all these features being implemented in the sample track/audio file processor don't you?

**Comment by messmerd** [comment]
The SlicerT plugin adds this functionality: #6857
