### ISSUE TITLE
make error: Carla (error: invalid conversion from ‘float**’ to ‘const float**’ [-fpermissive])

### ISSUE THREAD

**Issue by thrisp** [LMMS/lmms#4951]
```
/home/X/None/lmms/plugins/carlabase/carla.cpp: In member function ‘virtual void CarlaInstrument::play(sample_t (*)[2])’:
/home/X/None/lmms/plugins/carlabase/carla.cpp:344:39: error: invalid conversion from ‘float**’ to ‘const float**’ [-fpermissive]
fDescriptor->process(fHandle, rBuf, rBuf, bufsize, fMidiEvents, fMidiEventCount);
^~~~
```

Lubuntu 18.10

I've installed Carla from the github repo, no problem in cmake, but when running make

related to https://github.com/LMMS/lmms/issues/4909 I suppose but I do not fully understand what I need to do to fix it

hmm seems the default is the development branch and thats what I pulled,built and installed

**Comment by cet** [comment]
I have the same issue. :)

**Comment by PhysSong** [comment]
If you are on a Debian/Ubuntu based distribution and using the KXStudio repository, you can try uninstalling `carla-git` and using `carla` instead.

**Comment by cet** [comment]
Thx. :)
