### ISSUE TITLE
No exit with Appimage

### ISSUE THREAD

**Issue by thrisp** [LMMS/lmms#4952]
Appimage builds and runs, but does not exit properly.

The gui runs, but when exited leaves all processes zombied or existing.

```
Carla does not appear to be installed.  That's OK, please ignore any related library errors.
Jack appears to be installed on this system, so we'll use it.
Notice: could not set realtime priority.
Cannot load library /tmp/.mount_lmms-1311pii/usr/lib/lmms/libcarlapatchbay.so: (libcarla_native-plugin.so: cannot open shared object file: No such file or directory)
Cannot load library /tmp/.mount_lmms-1311pii/usr/lib/lmms/libcarlarack.so: (libcarla_native-plugin.so: cannot open shared object file: No such file or directory)
Cannot load library /tmp/.mount_lmms-1311pii/usr/lib/lmms/libcarlabase.so: (libcarla_native-plugin.so: cannot open shared object file: No such file or directory)
```

ps -A|grep lmms

24355 ?        00:00:01 lmms-1.2.0-rc8.
24366 pts/5    00:00:04 lmms.real

also appears to not recognize carla plugin, though it is installed

running the regular build binary and not the appimage appears to be ok

**Comment by PhysSong** [comment]
How did you get or build the AppImage? If you built that from source, which branch did you use?

**Comment by thrisp** [comment]
from branch master dowloaded 4/17, using the 'make appimage'

**Comment by PhysSong** [comment]
Then you're probably experiencing #4668.

**Comment by tresf** [comment]
> Then you're probably experiencing #4668.

Agreed.  Closing as duplicate.
