### ISSUE TITLE
ERROR: cant init jvm interface pointers! ...A missing DLL for an AppImage?!

### ISSUE THREAD

**Issue by TheOuterLinux** [LMMS/lmms#4957]
I'm using a 64-bit Debian-based Linux system. I shouldn't be getting an error related to a missing DLL file or anything "C:" related at all when this is supposed to be an AppImage. The LMMS loading screen only shows for a brief moment and then crashes. The error message I get via launching from a terminal is:

Carla does not appear to be installed.  That's OK, please ignore any related library errors.
Jack appears to be installed on this system, so we'll use it.
VST sync support disabled in your configuration
Cannot load library /var/tmp/.mount_lmms.AhIpqHT/usr/lib/lmms/libcarlarack.so: (libcarla_native-plugin.so: cannot open shared object file: No such file or directory)
Cannot load library /var/tmp/.mount_lmms.AhIpqHT/usr/lib/lmms/libcarlapatchbay.so: (libcarla_native-plugin.so: cannot open shared object file: No such file or directory)
Cannot load library /var/tmp/.mount_lmms.AhIpqHT/usr/lib/lmms/libcarlabase.so: (libcarla_native-plugin.so: cannot open shared object file: No such file or directory)

LADSPA create

***** jVSTwRapper *****
DllLocation=/usr/lib/ladspa/PL_Flanger.so
ConfigFileName=/PL_Flanger.ini
LogFileName=/PL_Flanger_log.txt
DllPath=/usr/lib/ladspa
**ERROR: Could not locate jvm.dll. 
			It seems that you dont have a properly installed Java Virtual Machine (JVM).
			If so, please download (it's free!) and install one from 

			http://www.java.com/ 

			If you already did that and see this message again, please add the path 
			where the jvm.dll is located to your PATH environment variable.

			Per default, the jvm.dll is located in 'C:\Program Files\Java\jre1.8.xxxx\bin\server'. But this 
			may differ depending on your choice during installation. 
			You can modify your PATH variable if you click 

			Start/Settings/Control Panel/System/Advanced (Tab)/Environment Variables (Button)
			/System Variables (the textbox at the bottom).
			Double-click on the variable called Path, and add a ';the-path-where-jvm.dll-is-located' 
			to the end of its value.
			Note the ';' at the beginning of the string. close all windows with ok, and you 
			should be all set.
			If you still cant use the plugin, contact the forum at 

http://sourceforge.net/forum/forum.php?forum_id=318265
** ERROR: cant init jvm interface pointers!/tmp/.mount_lmms.AhIpqHT/AppRun: line 23: 22855 Segmentation fault      QT_X11_NO_NATIVE_MENUBAR=1 $DIR/usr/bin/lmms.real "$@"

**Comment by TheOuterLinux** [comment]
And of course, GitHub formats the issue incorrectly....

**Comment by PhysSong** [comment]
Do you have any ideas where `PL_Flanger.so` is from?

**Comment by michaelgregorius** [comment]
Seems to be coming from here:
http://jvstwrapper.sourceforge.net/

While this wrapper might be technically impressive this issue is a good example of why it's not always a good idea to pile technology upon technology upon technology...

**Comment by TheOuterLinux** [comment]
I have no idea where the PL_Flanger.so came from. I removed 'guitarix-ladspa' and 'calf-ladspa', which in turn also removed the installed form of LMMS and then emptied the entire "/usr/lib/lapspa/" folder and now the latest AppImage of LMMS seems to work. The removal of all files in "/usr/lib/ladspa/" related to names with PL_* and PT_*, which I'm guessing have to do with jVSTwRapper, fixes the issue. It turns out that running PitchBox (https://www.pitchtech.ch/Plugins/index.html) may of had something to do with it. From the PitchBox website:

This plugin collection makes use of a modified version of jVSTwRapper 0.9f (a wrapper to write LADPSA/VST plugins in Java).

However, removing the files doesn't break PitchBox at all, so I'm confused. Either way, it's all good for now. However, I would still say that LMMS needs some way to ignore ladspa errors like this. Though to be fair, other 64-bit users are probably not as like to run 10+ year-old software as I am.

P.S. Please, for the love of God, tell me the maintainers aren't thinking about changing LMMS from "Linux MultiMedia Studio" to "Let's Make Music." ... Just something I noticed on the front page of the site. It's hard enough to get people to use Linux for music creation as it is, let alone know what Linux is in the first place. Be proud; don't give in to gentrification. We need all of the accidental search engine help we can get if anything.

**Comment by tresf** [comment]
> P.S. Please, for the love of God, tell me the maintainers aren't thinking about changing LMMS from "Linux MultiMedia Studio" to "Let's Make Music." ... Just something I noticed on the front page of the site. It's hard enough to get people to use Linux for music creation as it is, let alone know what Linux is in the first place. Be proud; don't give in to gentrification. We need all of the accidental search engine help we can get if anything.

Off topic.

> LMMS needs some way to ignore ladspa errors like this.

Plugins should ship with their own dependencies.   This is a bad plugin.  Perhaps we can improve stability of loading plugins but we'd need a simple use-case.
