### ISSUE TITLE
Presets containing LFO connections crash LMMS 1.2 RC8

### ISSUE THREAD

**Issue by Sauerstoffdioxid** [LMMS/lmms#4958]
### Description
I've made a preset for Zyn some time ago that used a VST reverb effect and automated one of it's parameters with a LFO from the controller rack. I do admit, saving such a construction as preset is pretty stupid, but it has worked until now (meaning it didn't crash at least). Now that I wanted to use it again, I noticed it consistently crashes LMMS regardless of how I add it to the track. Note that the VST effect is not necessary for the crash to occur (see below).

### Steps to reproduce
1. Open LMMS
2. Add a LFO in the controller rack
3. Connect it to pretty much any knob (e.g. the filter frequency) of e.g. TripleOscillator
4. Save it as preset

### Expected results
LMMS would ignore the "unknown" LFO as it used to do before.

### Actual results
After saving the preset, upon opening a different project (e.g. the "Empty" template) LMMS crashed for me.
Later, when I try to add the preset to the song editor, LMMS crashes (closes itself, no error message). It does this as soon as I left-click it (including dragging) as well as using the context menu.

### System info
Windows 10 Insider Preview 10.0.18362.30 (19h1_release) amd64 2019-04 (So basically Win10 64-bit)
LMMS RC8 as available on the website

This does not occur on LMMS 1.2 RC5 and before.

**Comment by PhysSong** [comment]
I think the issue is already reported in #4927 and fixed via #4939.

**Comment by Sauerstoffdioxid** [comment]
Yup, seems like that's it. Looks like I didn't find it when searching for a report earlier.
