### ISSUE TITLE
Piano Roll - Only base note sounds when recording chords

### ISSUE THREAD

**Issue by zonkmachine** [LMMS/lmms#4963]
While recording in the Piano Roll with a chord selected (drop down menu), only the base note is played/sounds even though the rest of the notes is properly recorded.
Related https://github.com/LMMS/lmms/pull/4938

**Comment by JohannesLorenz** [comment]
@zonkmachine You probably meant the dropdown in the piano roll? Just asking because there's also one in the "Chord stacking" tab in the instrument window.

**Comment by zonkmachine** [comment]
> @zonkmachine You probably meant the dropdown in the piano roll? Just asking because there's also one in the "Chord stacking" tab in the instrument window.

Yes.

**Comment by zonkmachine** [comment]
This was fixed in https://github.com/LMMS/lmms/pull/4990 by @sharpblade4 . Thanks!

> While recording in the Piano Roll with a chord selected (drop down menu), only the base note is played/sounds

I worded this poorly. I meant when adding notes (mouse) and not recording. When recording notes with a midi keyboard there is no support for the drop down menu scales.
