### ISSUE TITLE
Song editor: strange behavior when selecting large area

### ISSUE THREAD

**Issue by Gabrielxd195** [LMMS/lmms#4974]
I have many tracks and I want to select them all to move them, but when I activate the '' select mode '' and try to select all the tco using the mouse wheel to scroll down, the first tracks that you select remain unscreened while the bottom ones . something like:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/26127693/57801492-d1dc1b80-7721-11e9-90d3-3821b7d72fa9.gif)
As you can see, when I make the selection box and when I move with the mouse wheel, the box moves and the tco that remain outside the box are not selected and I am forced to select by parts. previously mentioned some errors and improvements in #4602 in relation to the select mode but this error had not taken into account.

**Comment by Spekular** [comment]
As a workaround for this, you can use shift+drag on the timeline at the top
of the song editor to select every track's contents between two points.

**Comment by Gabrielxd195** [comment]
> As a workaround for this, you can use shift+drag on the timeline at the top of the song editor to select every track's contents between two points.

This for me would be a temporary solution, since I can put the zoon to 12.5% and select it in this way (I had forgotten it) but the problem still persists, when the tco go out of the selection box when you scroll with the mouse wheel , the tco are left unselected and you have to select by parts or as you say with shift+drag. but anyway, thanks.

**Comment by musikBear** [comment]
The time-line-method unfortunately does not allow sh+drag for a additional selection. but sure safe method to move everything now, is to place playhead infont of the wanted split-position and the 'shove' everything upstream playhead, with sh+INSERT

**Comment by BaraMGB** [comment]
In master branch of lmms you can select all by <CTRL> + <A>.

**Comment by musikBear** [comment]
> In master branch of lmms you can select all by CTRL + A.

Not only select. These works too
* fractured-selectons
* move selected
* copy selected
* delete selected

It would be really good, if these found their way into RC9/ 1.1.2
I have enjoyed them a lot in my RC4-Master: 4.6493 
Afair i have not had one single issue and no crashes at all. Looks absolutely solid

**Comment by BaraMGB** [comment]
Since this is fixed in master this issue can be closed.

**Comment by SecondFlight** [comment]
Is the broken selection behavior fixed in master? I would consider ctrl+a to be a workaround, but the behavior shown in the GIF is definitely a bug.

**Comment by BaraMGB** [comment]
Sorry, my bad. I'll have a deeper look at this.

**Comment by BaraMGB** [comment]
I think, I know, what's going on.

**Comment by PhysSong** [comment]
Fixed in #5003.
