### ISSUE TITLE
Some problems and interface errors.

### ISSUE THREAD

**Issue by Gabrielxd195** [LMMS/lmms#4978]
I have seen some problems and interface errors, I am using LMMS 1.2.0 rc8 within the AV Linux distro, I have noticed problems like:

- **The editors appear empty.**
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/26127693/57965259-e7af3380-790f-11e9-86ec-70127c15bae8.gif)
Sometimes this happened to me, the editors were completely empty and the maximize and close buttons did not respond, this was completely random I can not explain how it happened.

- **The Sample Track window is maximized but will not be extended.**
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/26127693/57965372-72dcf900-7911-11e9-9858-43926d1fe62a.gif)
Sample track can be maximized and occupies a space but will not be extended over its frame.

- **I can not close Zynaddsubfx from its own close button (X).**
![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/26127693/57965439-4d042400-7912-11e9-8ff6-724409d9abc8.gif)
When I open zynaddsubfx from your instrument I can normally close it from its own window on its '' x '' button, but if I close the window of its instrument, I can not close it from its own window, this is uncomfortable because I open and close windows constantly. zynaddsubfx and I have to open each instrument and click on '' show gui '' to close it.

- **The small window of '' Meter '' is maximized and resized.**
![ezgif com-video-to-gif (3)](https://user-images.githubusercontent.com/26127693/57965567-e6800580-7913-11e9-9885-7af1d1018258.gif)
I do not know what is the point of placing a maximize button and the possibility of resizing to an option as small as this one that does not need it. however the instrument windows and the mixer do need it and they do not. how ironic!!

- **Rename tracks with double left click.**
![ezgif com-video-to-gif (4)](https://user-images.githubusercontent.com/26127693/57965699-b20d4900-7915-11e9-8d2e-114ecb827396.gif)
Sometimes I accidentally double left click and the tracks are renamed, this is a bit annoying. It is better to rename with a single right click.

- **Extract and contract the loop with right click and mouse wheel.**
![ezgif com-video-to-gif (5)](https://user-images.githubusercontent.com/26127693/57965759-5d1e0280-7916-11e9-8f94-560a0460bec2.gif)
The same goes for the loop, you have two buttons for the same function: right button and the mouse wheel. I always wanted to move a loop without changing its length, a good idea for this function would be to use the mouse wheel to move the loop without affecting or changing its length.

- **Resize the BB Editor tco in Song Editor.**
![ezgif com-video-to-gif (6)](https://user-images.githubusercontent.com/26127693/57965847-cbaf9000-7917-11e9-9e10-96af722c491c.gif)
I think this has been mentioned but with reference to the piano roll tco, but almost no one has mentioned that the tco of the bb editor patterns within the song editor can not be resized, they have the same options of adding, removing and cloning , but you can not resize them, however the bb editor patterns can be resized even less than a bar.

- **Strange lines with the playback head.**
![ezgif com-video-to-gif (7)](https://user-images.githubusercontent.com/26127693/57965926-20073f80-7919-11e9-9e74-039a4de3083e.gif)
While I was wondering why the playback head of the automation editor does not move when you play. I discovered this error precisely while I was writing this bug report. when you have a self-editing or piano roll window above the song editor or above, when you play, when the playhead skips over these editors and grabs the editor head, the editor head of song draws a strange line and the mouse icon is redrawn.

- **The Audio File Processor cursor is very clear.**
![ezgif com-video-to-gif (8)](https://user-images.githubusercontent.com/26127693/57966121-03b8d200-791c-11e9-8629-480f2875094a.gif)
The color of the sample is white, the background color is blue, and the color of the cursor is also blue. This is not a problem when you have a small sample, but when you have a very distorted or saturated sample takes up all the space and makes it uncomfortable to look at, especially for some people with vision problems. this is solved temporarily by lowering the volume of the sample but it is not so feasible, I think it would be better to change the color or darken the color of the sample a little more.

These particular problems so far have not affected my work, although in some cases they are annoying when you find them in passing, I think they should be taken into account. Greetings.

**Comment by SecondFlight** [comment]
> The editors appear empty.

Without steps to reproduce, this will be difficult to fix.

> The Sample Track window is maximized but will not be extended.

#3268 covers this.

> I can not close Zynaddsubfx from its own close button (X).

As I understand it, this is just a side effect of how ZynAddSubFX works. I'm not sure this can be fixed, but I could be wrong.

----

For the rest of these, please consider breaking them into separate issues. A large issue like this with multiple enhancements is difficult to track and is likely to be overlooked.

**Comment by SecondFlight** [comment]
Closing, as the issue has been broken apart. Thanks @Gabrielxd195 👍
