### ISSUE TITLE
Removing a SampleTCO while it plays will crash lmms (master and latest rc) 

### ISSUE THREAD

**Issue by Reflexe** [LMMS/lmms#4980]
## Steps to reproduce 
 - Open lmms
- load a sampletrack (doubleclick on a sample track and select an audio file)
- play it
- remove it while it plays (middle mouse button) 
- see if lmms crashes

Please verify it so I'll work on a solution.

**Comment by BaraMGB** [comment]
It crashes only with the middle mouse button. If I use the context menu, it doesn't crash.

**Comment by PhysSong** [comment]
Could you test the latest `stable-1.2`? I think it might have been fixed recently.

**Comment by Reflexe** [comment]
@PhysSong It is probably a race condition since I had to do that a couple of times in order to reproduce it. ‎This is the crash's stacktrace:
1  ??                                                                                                      0x7ffff603aadb 
2  SampleBuffer::play(float ( *) [2], SampleBuffer::handleState *, short, float, SampleBuffer::LoopMode)   0x5555556b3c1f 
```
3  SamplePlayHandle::play(float ( *) [2])                                                                  0x5555556b72ff 
4  MixerWorkerThread::JobQueue::run()                                                                      0x55555569a5d8 
5  MixerWorkerThread::startAndWaitForJobs()                                                                0x55555569a76f 
6  Mixer::renderNextBuffer()                                                                               0x5555556983aa 
7  Mixer::fifoWriter::run()                                                                                0x555555698914 
8  ??                                                                                                      0x7ffff71a7feb 
9  start_thread                                                                                            0x7ffff7f7ea92 
10 clone                                                                                                   0x7ffff5bfdcd3 
```

**Comment by PhysSong** [comment]
I found that `TrackContentObjectView::remove` may result in deleting TCOs while the mixer is rendering audio. So, I was working on the other approach than #4982:
```diff
diff --git a/src/core/Track.cpp b/src/core/Track.cpp
index 7a04ded95..eb8ebb3dc 100644
--- a/src/core/Track.cpp
+++ b/src/core/Track.cpp
@@ -422,7 +422,9 @@ void TrackContentObjectView::remove()
 
        // delete ourself
        close();
-       m_tco->deleteLater();
+       Engine::mixer()->requestChangeInModel();
+       delete m_tco;
+       Engine::mixer()->doneChangeInModel();
 }
```
#4982 looks fine, and I don't mind if any of them is accepted.

**Comment by Reflexe** [comment]
> I found that `TrackContentObjectView::remove` may result in deleting TCOs while the mixer is rendering audio. So, I was working on the other approach than #4982:
> 
> ```diff
> diff --git a/src/core/Track.cpp b/src/core/Track.cpp
> index 7a04ded95..eb8ebb3dc 100644
> --- a/src/core/Track.cpp
> +++ b/src/core/Track.cpp
> @@ -422,7 +422,9 @@ void TrackContentObjectView::remove()
>  
>         // delete ourself
>         close();
> -       m_tco->deleteLater();
> +       Engine::mixer()->requestChangeInModel();
> +       delete m_tco;
> +       Engine::mixer()->doneChangeInModel();
>  }
> ```
> 
> #4982 looks fine, and I don't mind if any of them is accepted.

I was thinking about this solution but I think that currently, every change in a SampleBuffer instance's data should be synced with the Mixer. That why, we'll avoid additional race conditions when we'll destroy a `SampleTCO` in new code.

**Comment by Reflexe** [comment]
We also have a problem with this function being called twice in a row; that will simply cause a double-free.

**Comment by Reflexe** [comment]
OK, for now, I'm going to merge it for stable-1.2. The recording branch has a better fix for that and will target master.

**Comment by BaraMGB** [comment]
@Reflexe is there a reason why you reopened this?
