### ISSUE TITLE
LFO offset

### ISSUE THREAD

**Issue by kmouse** [LMMS/lmms#499]
If I'm using LFO on a sound and I want the wave to be offset and start somewhere other than the beginning of the wave or sample, there doesn't seem to be a way to do this. I think the controller rack LFO has this but when in the ENV/LFO tab there isn't one. 
I can't get the controller rack LFO to accept a sample as the waveform.

**Comment by Umcaruje** [comment]
@kmouse Please refine this issue, provide some mockups and clarify its purpose, or otherwise it'll need to get closed.

**Comment by Umcaruje** [comment]
No response in 29 days, closing.
