### ISSUE TITLE
Export tracks :Missing metadata bug

### ISSUE THREAD

**Issue by T0NIT0RMX** [LMMS/lmms#4996]
Hello,
We found an issue when using the "export tracks" option in LMMS (RC8)

**To reproduce :** 
- Remove every existing tracks from a new project
- Load 2 3xOsc and put some notes on them
- Export tracks so you have : 1_TripleOscillator.wav and 2_TripleOscillator.wav

Issue :
![image](https://user-images.githubusercontent.com/12613367/58460386-d3e4a800-812d-11e9-939b-0925a209c5e7.png)
As you can see on the screenshot, only the first track has correct metadata, especially the "length" field ("Longeur" on my screenshot), same for the "bitrate" ("vitesse de transmission" on my screenshot)

**Consequence** : 
Even if some audio players don't care about the missing "length" field (like VLC, Audacity), some other audio players seems to pay a lot of importance to it and block the file (like the native Win10 player, FL Studio, Ableton) if the length field is missing (or maybe = 00:00:00)

This is really blocking when we try to export stems for collaborations with guys using other DAW like FL or Ableton.

Thanks in advance for your help,

T0NIT0 RMX

**Comment by PhysSong** [comment]
What happens if you export to MP3 or OGG?

**Comment by T0NIT0RMX** [comment]
We tried with .wav, .mp3, .ogg

.wav & .mp3
- 1st track : OK
- other tracks : no length field, no bitrate, can't be read by some audio players

.ogg
- 1st track : OK,
- other tracks : size = 0 bytes, but can be read by the Win10 player

Hope it helps, don't hesitate if you need more details, I'll reply ASAP

**Comment by JohannesLorenz** [comment]
@T0NIT0RMX Can you easily check if it's on master, too?

Suspected file is src/core/RenderManager.cpp .

Might be a candidate to get fixed before 1.2.0 ...

**Comment by JohannesLorenz** [comment]
Confirming on Linux on branches master and stable-1.2.

E.g. mpv says for the 2nd track: `[ffmpeg/demuxer] wav: Estimating duration from bitrate, this may be inaccurate` .

**Comment by JohannesLorenz** [comment]
OK, all `m_si.xxx` variables in `AudioFileWave::startEncoding()` have the same values when writing the two tracks. Must be a different error.

**Comment by JohannesLorenz** [comment]
The bug seems to be that `AudioFileWave` calls `sf_close` only in its destructor, and ProjectManager does not delete its AudioFileDevice `m_fileDev`. Trying to find a fix now.

**Comment by JohannesLorenz** [comment]
PR #5005 is going to fix this.
