### ISSUE TITLE
Cloning automations results in resetting the clone

### ISSUE THREAD

**Issue by qantuum** [LMMS/lmms#5004]
Hi there.
I come here to report an issue I've been ranting about on reddit : the cloning of automation tracks does not work properly. I thought it was a faulty feature on its own, but I was told it's the first time this malfunction was reported and that it may be related to my personal computer.

How to re-create the bug : Just take an automation track that you have created (for example : a simple slope), and clone it using Ctrl+drag.
As one should expect, the clone has the same length than the original and is connected to the same control (knob, ...). But to me : the clone's shape and points are resetted. I just get a plain square box with the basic square shape (if it was a curve or a slope, it's not anymore, and none of the original points are conserved).

Here are some specs of my computer and system, I hope they are enough to work with, well if not ask me and I'll do my best to find out.
LMMS : v.1.2.0-rc7 (64-bit)
Installed using the .exe, .exe was downloaded and run at 2018/10/31, all went smoothly.
Windows 10 family version : 1803
OS version : 17134.765
RAM : 8Go
CPU : Intel i5-3317U
Computer type : LAPTOP ASUS K56CB

I observed the same bug in the previous official version on the same operating system and computer. At the time I had a different HD and less RAM.

**Comment by DouglasDGI** [comment]
@qantuum I can't quite remember which version that bug was fixed in, but I think it was RC8, which is available at https://lmms.io/download.  Can you update to RC8 and see if the bug is still there?

**Comment by qantuum** [comment]
Fixed in rc8 indeed.
Was not aware this update was out.
Thanks a bunch! :)
