### ISSUE TITLE
Piano Roll: Volume difference between note and key

### ISSUE THREAD

**Issue by Gabrielxd195** [LMMS/lmms#5017]
I have noticed that the volume of the notes created sounds louder than when you play with the mouse the virtual piano roll keyboard.

![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/26127693/59142786-43aa2c80-8991-11e9-804f-229c0095184b.gif)

1- Open piano roll.
2- Play a note on the virtual piano with the mouse.
3- Now create a note in it.

Now you will notice a difference in volume.

You can also try it with the virtual piano of the instruments and also with the led of the tracks.

**Comment by Spekular** [comment]
Have you modified the velocity of your notes in piano roll? The velocity of
the latest clicked note is used when new notes are placed, and may differ
from whatever default velocity the virtual keyboard uses.

The virtual keyboard's velocity should be equivalent with a note at 100%
IMO, not based on the current note velocity.

**Comment by Gabrielxd195** [comment]
Thanks for the clarification, if you consider that there are no problems on this side, close this thread.
