### ISSUE TITLE
Assigning a qlineargradient to qproperty-graphColor breaks the CSS stylesheet.

### ISSUE THREAD

**Issue by nitronova** [LMMS/lmms#5027]
AutomationEditor has a property called graphColor that was able to accept a qlineargradient in the previous version. The expected behavior was to create that effect again. Here is the CSS code I used that worked on previous versions of the software:
```
qproperty-graphColor: qlineargradient(spread:reflect,x1:0, y1:0, x2:0, y2:1,stop:0 rgba(0,148,201,100),stop:1 rgba(168,0,41,160); /* The graph */
```
What actually happened was that this broke the stylesheet. I'll provide a before/after.

Before:
![image](https://user-images.githubusercontent.com/1452074/59164700-43677980-8ad6-11e9-99f5-285a5f28b83a.png)

After:
![image](https://user-images.githubusercontent.com/1452074/59164703-65f99280-8ad6-11e9-92e4-4570d8f92183.png)

**Comment by PhysSong** [comment]
A `)` is missing before `;`. If I add the closing parenthesis, everything works fine.

**Comment by nitronova** [comment]
You were right, so sorry about that!
