### ISSUE TITLE
Compilation failed in linux mint

### ISSUE THREAD

**Issue by dancaer69** [LMMS/lmms#5029]
I'm trying to compile lmms on a linux mint machine. I have some errors which fixed by searching here and install missing packages, but for this I haven't found a fix yet. The error is:
```
[ 83%] Built target stereomatrix
[ 83%] Generating ../RemoteVstPlugin
No such file or directory
plugins/vst_base/CMakeFiles/vstbase.dir/build.make:61: recipe for target 'plugins/RemoteVstPlugin' failed
make[2]: *** [plugins/RemoteVstPlugin] Error 1
CMakeFiles/Makefile2:8049: recipe for target 'plugins/vst_base/CMakeFiles/vstbase.dir/all' failed
make[1]: *** [plugins/vst_base/CMakeFiles/vstbase.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
```
I found 2 similar issues and I installed qt5-private-dev(or so, I don't remember exactly the package name) gcc-multilib and g++-multilib, which suggested there, but I still get the above error.

**Comment by PhysSong** [comment]
Sorry for the late response, but have you downloaded the source code with `git` and checked out submodules?

**Comment by JohannesLorenz** [comment]
No response in 6 months. Closing.
