### ISSUE TITLE
FX controllers overlap.

### ISSUE THREAD

**Issue by Lusted4ever** [LMMS/lmms#5032]
See this: ![Untitledadasdasd223122312](https://user-images.githubusercontent.com/35467995/59460559-11cd1600-8e28-11e9-8be1-aa244ed57fa1.png)
Running win10 x64.
Using current lmms build (LMMS 1.2.0 rc8)

**Comment by zonkmachine** [comment]
Confirmed on lmms-1.2.0

**Comment by zonkmachine** [comment]
This is leftover from https://github.com/LMMS/lmms/pull/4482. I can fix it by going over the translations again and just removing the borked lines but maybe this is best handled on Transifex?

**Comment by zonkmachine** [comment]
In https://github.com/LMMS/lmms/pull/4482/files#diff-463bf9a84ee53b7ed35f64c1a918887bL1035-L1038 I just swapped the translation for the original.
```diff
--- a/data/locale/cs.ts
+++ b/data/locale/cs.ts
@@ -1034,7 +1034,7 @@ Máte-li zájem o překlad LMMS do jiného jazyka, nebo chcete-li vylepšit exis
     </message>
     <message>
         <source>FDBK</source>
-        <translation>ZP. VAZBA</translation>
+        <translation>FDBK</translation>
     </message>
```

I'm not sure whether this is a good way to do it. Some other options that gives the same result (on the user side) would be to:

Delete the translation:
```diff
     <message>
         <source>FDBK</source>
-        <translation>ZP. VAZBA</translation>
+        <translation></translation>
     </message>
```

Using the unfinished tag:
```diff
     <message>
         <source>FDBK</source>
-        <translation>ZP. VAZBA</translation>
+        <translation type="unfinished"/>
     </message>
```

Using the unfinished tag and some text/translation:
```diff
     <message>
         <source>FDBK</source>
-        <translation>ZP. VAZBA</translation>
+        <translation type="unfinished">FIXME</translation>
     </message>
```

I guess it doesn't matter that much if it's not merged back to Transifex but I don't know how we manage that side of the code. I'm thinking of going with `<translation type="unfinished"/>` when just deleting a translation that messes up the gui from now on. Any opinions on this @liushuyu ?

**Comment by zonkmachine** [comment]
Closed in https://github.com/LMMS/lmms/pull/5185
