### ISSUE TITLE
Removing a patch on the debian packaging

### ISSUE THREAD

**Issue by trebmuh** [LMMS/lmms#5033]
It looks to me that [this patch](https://github.com/LMMS/lmms/blob/stable-1.2/debian/patches/contributors.patch) isn't needed anymore since [the file](https://github.com/LMMS/lmms/blob/stable-1.2/doc/CONTRIBUTORS) is now present in the source.

HTH

**Comment by Rossmaxx** [comment]
Looks like this file has been removed on master.

**Comment by trebmuh** [comment]
Yes, with https://github.com/LMMS/lmms/pull/5264
closing here
