### ISSUE TITLE
LMMS segfaults when adding Carla (master branch)

### ISSUE THREAD

**Issue by tank-trax** [LMMS/lmms#5036]
I've been building from git source (using Debian Stretch) and tried the latest stable and Version 1.2.0.466 segfaults if either Carla Patchbay or Carla Rack is added to the Song Editor

![lmms crash](https://user-images.githubusercontent.com/41337033/59524335-960faf80-8ea1-11e9-8948-277a71640f9e.gif)

the version 1.2.0-rc8.497 is stable (thankfully I kept old builds)

![lmms stable](https://user-images.githubusercontent.com/41337033/59524383-b9d2f580-8ea1-11e9-99ec-61638edbd8a2.gif)

**Comment by tank-trax** [comment]
I tried the latest AppImage and the same thing happened

**Comment by trebmuh** [comment]
I'm on Debian Stretch (LibraZiK-2 to be precise), and I've just build a package for the 1.2 stable tarball.
Testing this .deb build, I can add Carla to it.

Question: do you have Carla installed on your system?

**Comment by tank-trax** [comment]
yes I have Carla installed

I tried lmms-1.2.0.tar.gz

```
mkdir build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX=../target/
make -j4
```

it doesn't create the Makefile and responds with

`make: *** No targets specified and no makefile found.  Stop.`

I also tried the instructions from the INSTALL.txt

```
mkdir build
cd build
cmake ../
make
```
and it failed to create the Makefile

**Comment by tank-trax** [comment]
if I `git clone --recurse-submodules -b stable-1.2 https://github.com/lmms/lmms`

the CMakeLists.txt is missing 

```
OPTION(WANT_VST_32	"Include 32-bit VST support" ON)
OPTION(WANT_VST_64	"Include 64-bit VST support" ON)
```
I tried adding those lines to the file and it built but segfaults immediately

I noticed that version 1.2.0.2
![lmms 1 2 0 2](https://user-images.githubusercontent.com/41337033/59529559-5d76d280-8eaf-11e9-9780-c9c9ec7fdf74.png)

can load Carla but only builds with 32 bit Vestige support

whereas version 1.2.0.466
![lmms 1 2 0 466](https://user-images.githubusercontent.com/41337033/59529632-8d25da80-8eaf-11e9-86fe-a6ebd3e3d4fc.png)

crashes when Carla is loaded but allows for both 64 bit and 32 bit VST support

**Comment by tank-trax** [comment]
tried

```
git clone https://github.com/LMMS/lmms.git
cd lmms
git submodule update --init --recursive
mkdir build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX=../target/
./lmms 
VST sync support disabled in your configuration
convolution: samplerate mismatch preset:48000 host:44100
convolution: samplerate mismatch preset:48000 host:44100
convolution: samplerate mismatch preset:48000 host:44100
convolution: samplerate mismatch preset:48000 host:44100
convolution: samplerate mismatch preset:48000 host:44100
convolution: samplerate mismatch preset:48000 host:44100
Segmentation fault

```

**Comment by tank-trax** [comment]
I tried the AppImage and must apologize as it can load both Carla Rack and Patchbay, however Vestige is only 32 bit capable

I am wondering is the 64 bit Vestige support still experimental and not included in the stable release?

**Comment by tank-trax** [comment]
Without 64 bit VST support everything appears to be rock solid with v1.2.0.2

```
Trying to start carla-plugin using "/usr/share/carla/resources/carla-plugin"
LRDF Support not available (LADSPA-RDF will be disabled)
Carla 2.0.0 started, status:
  Python version: 3.5.3
  Qt version:     5.7.1
  PyQt version:   5.7
  Binary dir:     /usr/lib/carla
  Resources dir:  /usr/share/carla/resources
ALL OK!
```

**Comment by tank-trax** [comment]
after looking at the CMakeLists.txt for stable and master I see that stable only supports 32 bit VST
Carla Rack and Patchbay are OK in stable, this issue is with the master branch and I've tried it with the latest Version 1.2.0.467 

I have a bunch of older builds that do not have this issue and it appears to have coincided with the 1.2 release, but I could be wrong

as an aside, the `master/development Version 1.2.0-rc8.500 `is able to load both 64 and 32 bit VST as well as Carla Rack and Patchbay without segfaulting
