### ISSUE TITLE
Online collaboration

### ISSUE THREAD

**Issue by J-Cobs** [LMMS/lmms#5046]
Can we get Online collaboration? The feature to "get together" for the purpose to work on the same project at the same time, with friends or colleagues.

For the users with internet access, you can just click a button inside LMMS DAW and invite someone using their Username to your projects to get feedback or help you out would be a game changing feature in open source software, and i would like to see it come to LMMS first!

The host of this collaboration project would be the only one to save the project on their computer (for those trolls and beat thieves). They could also give and take away the ability to change anything for those who join, for feedback and alike purposes. This could include a chat feature (since LMMS is sound related, i would like to see a voice note, and voice call feature aswell) for communicating while working on the same project, or for others to lift their opinion on your project. 
This could also be a neat feature for those building a following of sort for them to "stream" their project to those who want to see their friends or professionals make beats. A follower option could help build the community, and motivate the community on their own projects.

Now, I have absolute no coding education or experience, but please, since this is open source, could someone do this project if the devs approves but do not have time for this?

**Comment by qnebra** [comment]
Really nice idea, but also not for now.

**Comment by J-Cobs** [comment]
> Really nice idea, but also not for now.

Thank you, I think this feature will be ideal.
Why do you say not for now?

**Comment by SecondFlight** [comment]
Online collaboration would be a massive undertaking and would likely require rewriting major core pieces, along with major code additions.

It's not impossible, but it will take time away from more pressing and requested enhancements, such as better sample track support.

As always, we are open to pull requests if you are interested in taking on this project yourself.

**Comment by DouglasDGI** [comment]
Yes, this is a very good feature request (and something I've been wanting for years now), but the difficulty of adding something like that is indescribable.

**Comment by NETMANSKY** [comment]
Only stems exchange do it possible and nothing more... There is not even implemented in LMMS a base feature as project archiving, at least... And yet much helpful and necessary modern features. But we hope :)

**Comment by DomClark** [comment]
Closing in favour of #5892.
