### ISSUE TITLE
Song Editor

### ISSUE THREAD

**Issue by ImprovingLMMS** [LMMS/lmms#5048]
**It should be able to divide into more parts (1/8, 1/16, 1/32, etc) as in the Piano Roll to have more precision when doing automations and others.**

**Comment by SecondFlight** [comment]
Duplicate of https://github.com/LMMS/lmms/issues/874.

Please add more descriptive titles in future issues. Your title should summarize the bug report, and this one does not.

A better title could be "Add time division dropdown to song editor", or to take a cue from #874, "Finer scaling in song editor".

**Comment by Spekular** [comment]
#4973 btw.
