### ISSUE TITLE
Stay under

### ISSUE THREAD

**Issue by ImprovingLMMS** [LMMS/lmms#5049]
### A button to stay under a window (as the Song Editor and others).
The same that the button to stay up but upside down.

**Comment by SecondFlight** [comment]
This, in my opinion, could turn into a UX nightmare:

1. A user pins the piano roll to the bottom.
2. The user opens 10 more windows and forgets they put the piano roll at the bottom.
3. The user tries to open the piano roll, but they don't see it since it appears at the bottom, and they think LMMS is broken.

What is the use-case for pinning the piano roll to the bottom? If you don't want to see a window, why not just close it and open it later?

**Comment by musikBear** [comment]
@SecondFlight Im not sure that "stay under" means *minimized* (witch i agree with you, is an nuisance/ un-necessary) I think this could be about 'pinning' Eg locking a window to *stay-on-top*, but with a visual button, instead of the context-option. (?)

**Comment by ImprovingLMMS** [comment]
> This, in my opinion, could turn into a UX nightmare:
> 
> A user pins the piano roll to the bottom.
> The user opens 10 more windows and forgets they put the piano roll at the bottom.
> The user tries to open the piano roll, but they don't see it since it appears at the bottom, and they think LMMS is broken.
> 
> What is the use-case for pinning a window to the bottom? If you don't want to see a window, why not just close it and open it later?

I think there should be this button because if I'm editing an instrument (FX, etc) and I click on the song editor (which I have maximized), the instrument's editor stay on bottom and I have to close and return to open the instrument editor or minimize the song editor and maximize it again to continue editing the instrument. I know I can activate the option to leave it up but I would have to do that with all the windows that it opened; it's much more comfortable to activate once you leave the song editor down and that's it. A greeting.

**Comment by DouglasDGI** [comment]
If you click on the name of an open instrument, it will close the instrument window.  So you can close and reopen an instrument window from the Song Editor.

**Comment by SecondFlight** [comment]
That use case makes sense to me, specifically for when a window is maximized.
