### ISSUE TITLE
Race conditions when deleting effects?

### ISSUE THREAD

**Issue by JohannesLorenz** [LMMS/lmms#5050]
@he29-net and me were wondering if there are race conditions possible when Effects are deleted while being used.

`EffectRackView::deletePlugin( EffectView* view )` does

```
fxChain()->removeEffect( e );
e->deleteLater(); // probably this deletes e after the current callback returned to Qt
```

Imagine meanwhile, the audio thread just runs. Can the following order happen and lead to a crash?

1. User uses UI to delete effect
2. audio thread fetches effect pointer
3. UI thread deletes effect pointer from fx chain (`EffectChain::removeEffect`)
4. UI thread returns to Qt event loop and deletes effect
5. audio thread now uses its fetched pointer, which points to cleaned and deleted memory

**Comment by PhysSong** [comment]
`EffectChain::removeEffect()` calls `Mixer::requestChangeInModel` before actually removing the effect from the FX chain. It means no effects will be removed from FX chains while the mixer is rendering audio.
It is guaranteed that effects won't process audio after being removed from the FX chain. I think there are no releated race conditions.

**Comment by JohannesLorenz** [comment]
Do you mean the threads are exclusive because of `Mixer::m_doChangesMutex`? That mutex is only used in `Mixer::fifoWriter::write`, but not in `Mixer::renderNextBuffer`.

**Comment by PhysSong** [comment]
> Do you mean the threads are exclusive because of `Mixer::m_doChangesMutex`?

Actually, there's one more: `m_changesRequestCondition`.
- Wait conditions prevent race conditions while `Mixer` is processing and not waiting for writing
- Mutexes prevent race conditions while `Mixer` is not running/waiting for writing

**Comment by JohannesLorenz** [comment]
So before a thread actually removes an Effect, it blocks at the wait condition, which only gets a wake up after the effect processing (Mixer.cpp: "STAGE 3").

And when it's finally woken up in order to remove the effect, no further audio can be calculated because `Mixer::renderNextBuffer` calls `runChangesInModel`, which waits at `m_changesMixerCondition`?

**Comment by PhysSong** [comment]
> And when it's finally woken up in order to remove the effect, no further audio can be calculated because `Mixer::renderNextBuffer` calls `runChangesInModel`, which waits at `m_changesMixerCondition`?

Yes. `runChangesInModel` blocks the execution until all pending changes are done.

**Comment by JohannesLorenz** [comment]
Thanks for your help. I'll add some comments to the `Mixer`, so it will get more clear.
