### ISSUE TITLE
Trimming and pitch issues on 1.2

### ISSUE THREAD

**Issue by ChampGnions** [LMMS/lmms#5051]
Before, loading an 1.1.3 project into 1.2 would cause most piano roll based samples to slightly pitch down on export, configurations proved helpless on that situation so I just exported them in 1.1.3. However, now that the same issue was seen in 1.2 and even worse having a sample's trim edit broken upon export, I don't know what to do.
Video shows LMMS playback and export playback.
https://cdn.discordapp.com/attachments/242409373505159168/591631359311872030/LMMS_1.2.mp4
Please help!

**Comment by BaraMGB** [comment]
Here is something wrong with your samplerate. The exported file seems to be 48000 Hz. 
![Bildschirmfoto von 2019-06-21 16-49-28](https://user-images.githubusercontent.com/6502580/59931254-d85a6300-9444-11e9-86c6-2d238b458106.png)

Look at you export samplerate and the samplerate of your audio device.

**Comment by ChampGnions** [comment]
> Here is something wrong with your samplerate. The exported file seems to be 48000 Hz.
> ![Bildschirmfoto von 2019-06-21 16-49-28](https://user-images.githubusercontent.com/6502580/59931254-d85a6300-9444-11e9-86c6-2d238b458106.png)
> 
> Look at you export samplerate and the samplerate of your audio device.

41Khz 16-bit worked, even with 1.1.3 files. Weird considering I've tried that before. Thanks a lot!
