### ISSUE TITLE
Song-Editor. All patterns jump right side to one step, when track name changed.

### ISSUE THREAD

**Issue by healingdrawing** [LMMS/lmms#5052]
Bug appear time to time. After restart LMMS, bug disappear, but later appear again.
All patterns of all tracks in Song-Editor move to one step right, when i rename track, or just , right mouse click on name and then press keyboard `enter`.  
kubuntu 18.04  
LMMS Version 1.2.0  
![test](https://user-images.githubusercontent.com/39751647/59929869-5f5e0a00-944a-11e9-95cd-5cd81acb5a83.gif)

**Comment by BaraMGB** [comment]
looks very odd. It would be cool if we had a method to reproduce this. Perhaps you can provide your project file?

**Comment by healingdrawing** [comment]
> Perhaps you can provide your project file?

yes, it not secret. But no guarantee bug appear, when you change track name, because i had it only 5 times per three hours editing, with pauses.
[_201906110544_xz_vball.mmpz.zip](https://github.com/LMMS/lmms/files/3315220/_201906110544_xz_vball.mmpz.zip)

**Comment by healingdrawing** [comment]
and i detect additional point . When bug appears , and i try change name of track in time of playing global song in Song-Editor then only patterns which not covered by vertical play line + placed right from this position jumping right. Patterns which placed under play line and left, not moved. Then i stop playing change name again and in this case all patterns move right.

**Comment by BaraMGB** [comment]
Thank you. I will try to reproduce this.

**Comment by BaraMGB** [comment]
I can't reproduce it. Perhaps someone else is able to reproduce it and can provide steps that triggers this issue.

**Comment by DomClark** [comment]
We have a shift+enter keyboard shortcut that does this, for easily inserting new bars. Presumably the shift modifier is stuck for some reason - I've seen reports of modifier keys getting stuck before, but I can't find any right now.

**Comment by healingdrawing** [comment]
> shift+enter keyboard shortcut that does this,

you are right shift+enter work.
Playing with `shift+enter`, I found next shitty point.
When i open empty project , which not lags when i press enter on keyboard etc(or change track name then enter), after i press once only `shift+enter` and tracks jump right, every next `enter` or `num enter` pressing , offset patterns inside song editor right to one step. Looks like shift freezed or stay like permanent artifact.
Little step forward, to founding dirty place.

**Comment by gatodev** [comment]
I found the steps to reproduce.
Open piano-roll.
Move piano-roll if song-editor is entirely hidden.
Focus song-editor.
Pressing some modifier key, click on piano-roll.

**Comment by Spekular** [comment]
The recent scroll direction fix also had to do with stuck modifiers, I wonder if that fixed this as well:

https://github.com/LMMS/lmms/commit/42f7e262e9d9353671a3920215f8e41658590891

@gatodev can you test a build of LMMS from master branch and see if the issue is still here? If you pick a minor PR on master branch and use the test binary from it you don't have to build it yourself.

**Comment by gatodev** [comment]
I tested version 1.2.1.681 and confirmed it was fixed.

**Comment by Spekular** [comment]
Great, thanks for testing! :)

**Comment by Spekular** [comment]
Or, should this stay open since it's not fixed in 1.2? I think I lean towards having it closed since a fix is merged, but if someone disagrees please reopen.
