### ISSUE TITLE
I need an executable.

### ISSUE THREAD

**Issue by Gabrielxd195** [LMMS/lmms#5054]
I understand that the master branch has more features than stable 1.2 and I suppose it is also a trial version. right ?, the problem is that I'm not a developer and I can not install it on my computer, to test it. I do not know if this is possible, since I do not see master releases, but if someone has some binary or executable: appimage or some windows executable, please send it to me. regards

**Comment by DouglasDGI** [comment]
This is for bug reports, feature requests and LMMS development in general, not for download requests.  Something like that would be better in an informal place like Discord, not Github where we have thousands of open issues that we're trying to take care of.

I've been told that nightly downloads of the master branch will reach lmms.io/download at some point, though when is uncertain.
