### ISSUE TITLE
UI Themes Glitches

### ISSUE THREAD

**Issue by chopin2712** [LMMS/lmms#5056]
Dear

I wanted to install a new theme on lmms, so I started by trying to install: 
https://lmms.io/lsp/?action=show&file=14882

And this is the result: 

![Screenshot from 2019-06-23 14-41-45](https://user-images.githubusercontent.com/33733474/59976474-6198a380-95c5-11e9-9786-bff3c847dd32.png)

*Note that the timeline was completly empty*

Then I though it was because it wasn't the latest theme so I tried with the following one:
https://lmms.io/lsp/?action=show&file=15060

And this is the result:
![Screenshot from 2019-06-23 14-46-34](https://user-images.githubusercontent.com/33733474/59976502-b9cfa580-95c5-11e9-9f0c-a8b7e1dbf5be.png)

Less buggy but still buggy. 

So what can I do? I beleive the problem comes form my computer, so how can I fix this?

**Comment by BaraMGB** [comment]
You could ask the creator of the theme. Or you can ask in the lmms.io support forum. Our bug tracker is definitely the wrong place for this.

**Comment by chopin2712** [comment]
> You could ask the creator of the theme. Or you can ask in the lmms.io support forum. Our bug tracker is definitely the wrong place for this.

The problem is that I have this thing with almost all themes...

**Comment by Spekular** [comment]
Have you installed 1.2 on top of 1.1.3 without uninstalling?

Try closing lmms, moving C:\Users\[you]\.lmmsrc.xml to your desktop, and
relaunching.
