### ISSUE TITLE
LMMS can't find libs for gigplayer

### ISSUE THREAD

**Issue by Jacalz** [LMMS/lmms#5058]
When compiling LMMS using libgig everything goes fine during compiling but when starting LMMS from terminal you will see that it prints two errors and inside the program GiGPlayer is missing.

### See errors below:
```
Cannot load library /usr/lib/lmms/libgigplayer.so: (libgig.so.8: cannot open shared object file: No such file or directory)
Cannot load library /usr/lib64/lmms/libgigplayer.so: (libgig.so.8: cannot open shared object file: No such file or directory)
```

Any help would be appreciated :+1:

**Comment by trebmuh** [comment]
Do you have on of those files?

**Comment by Jacalz** [comment]
I believe so yes, let me give you some pictures of the file contents in the folders:

LMMS in /usr/lib:
![image](https://user-images.githubusercontent.com/25466657/60031576-4e5d0500-96a5-11e9-93f7-670075038731.png)

LMMS in /usr/lib64:
![image](https://user-images.githubusercontent.com/25466657/60031627-60d73e80-96a5-11e9-942f-a5438ae73cff.png)

Libgig files also exist:
![image](https://user-images.githubusercontent.com/25466657/60031715-85cbb180-96a5-11e9-88b6-a646f9c3d35f.png)

![image](https://user-images.githubusercontent.com/25466657/60031751-97ad5480-96a5-11e9-890e-de18d41cc30d.png)

**Comment by Jacalz** [comment]
I managed to find the culprit of this using LD_DEBUG and it seems that it looks for /usr/lib/libgig.so.8 and /usr/lib64/libgig.so.8 instead of /usr/lib/libgig/libgig.so.8 and  /usr/lib64/libgig/libgig.so.8.

**Comment by Jacalz** [comment]
How would I go about telling LMMS to look inside the libgig folder?

**Comment by Jacalz** [comment]
An issue with libgig apparently...
