### ISSUE TITLE
Why sample and presets library is not updating in real time

### ISSUE THREAD

**Issue by NETMANSKY** [LMMS/lmms#5059]
Well... Why sample and presets library is not updating in real time? Indexing need?

**Comment by musikBear** [comment]
@NETMANSKY Are there any usecase where the button is not sufficient? 
I see no reason for changing that

**Comment by NETMANSKY** [comment]
@musikBear, I didnt understand what you mean :( I meant that new sample or preset is not showing in left panel "My Samples&My Presets" of LMMS when they are created in launched LMMS in real time. I asked what reason is. And I assumed this is due to indexing at the QT engine level. May be I was mistake.

**Comment by SecondFlight** [comment]
It doesn't have to do with indexing. It would require something like a file system watcher, which Qt implements: https://doc.qt.io/qt-5/qfilesystemwatcher.html

If you're interested in this as an enhancement request, please open one. For questions like this please use [Discord](https://lmms.io/chat), as questions add to clutter in the tracker.

**Comment by NETMANSKY** [comment]
But where is the tracker no one of us knows...16:41, 27 июня 2019 г., Joshua Wade <notifications@github.com>:It doesn't have to do with indexing. It would require something like a file system watcher, which Qt implements: https://doc.qt.io/qt-5/qfilesystemwatcher.html
If you're interested in this as an enhancement request, please open one. For questions like this please use Discord, as questions add to clutter in the tracker.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by musikBear** [comment]
> I meant that new sample or preset is not showing in left panel "My Samples&My Presets" of LMMS when they are created in launched LMMS in real time

Yes true, but all you need to do is to press the update-button in sidebar. OF CAUSE they have to be **saved** as a preset **first**!
Is *that* the step you do not feel is necessary? 
When should LMMS regard a new builded preset as 'archive-material'?
Every time a setting is changed? a *Nightmare* in cpu-load
Can you write down the flow of events and state where a new preset/ AFP-sample should be added to a collection, and hence visible in sidebar?
The *update-button* takes *care* of this.

**Comment by SecondFlight** [comment]
>a Nightmare in cpu-load

Only if your implementation is deeply flawed.

As I mentioned, the way to do this would be to use `QFileSystemWatcher`. This listens to the OS for filesystem change events, a method which is very efficient as it doesn't require time-consuming manual checks of the filesystem.

**Comment by NETMANSKY** [comment]
@musikBear, @SecondFlight I agree with both of you 💯  but in 5 years of use I have not been able to find this magic update button in my win.LMMS. I pressed LMB and RMB, but did not see any update button... It will be wonderful if it appears in our favorite creative Studio or the content will be updated by the methods of the engine! We, the users, do not care how it will work, we will be glad to everything! Thanks for you hard working!

**Comment by DouglasDGI** [comment]
> I have not been able to find this magic update button in my win.LMMS.

@NETMANSKY Are you talking about this?  
![image](https://user-images.githubusercontent.com/34612565/60354439-74c2bf00-9989-11e9-80d0-ddd339d12939.png)

**Comment by NETMANSKY** [comment]
@DouglasDGI Well... Im a stupid man. I never saw it. But now I see... Haliluya!
