### ISSUE TITLE
Loading project with instrument with >=4 FX misses scroll area

### ISSUE THREAD

**Issue by JohannesLorenz** [LMMS/lmms#5061]
Affects master, beginning with merge of "variable-tab-widget" (22fb650).

Steps to reproduce:
* Save a project with 4 fx in 3osc (version of LMMS does not matter)
* Load it with current master
* The 4 fx miss a scroll area, so the add effect button can not be clicked

Note:
* Scroll area is created when you have e.g. 10 fx.

Thanks to NaYEE(T)ko and @DouglasDGI for reporting.

**Comment by noahb01** [comment]
The effects also run off the bottom of the screen, so the bottom effect(s) can't be opened, edited, etc.

**Comment by JohannesLorenz** [comment]
Fixed by the mentioned commit.
