### ISSUE TITLE
Automation issues with Audio File Processor's start and loop points

### ISSUE THREAD

**Issue by Sauerstoffdioxid** [LMMS/lmms#5063]
When automating the starting point and the loop point of a sample in the Audio File Processor at the same time, only the loop point connection will be saved. If both are linked to the same automation pattern, only the loop point connection will be preserved. If they are linked to distinct patterns, the whole situation becomes even weirder. The pattern linked to the starting point of the sample turns its connection into the loop point, and the loop point pattern loses its connection completely.

## Example Projects
bug.mmp - both were orginally linked to the same pattern
bug-01.mmp - only the start point was linked to the pattern (works as expected)
bug-02.mmp - start, loop and end point were linked. The start point's connection is lost
bug-03.mmp - only start and end, but not the loop point were automated. Works as expected.
bug-04.mmp - start and loop point were originally connected to the automation tracks of the same name. As described above.
[bug.zip](https://github.com/LMMS/lmms/files/3341715/bug.zip)

Also, on an unrelated note, the automation itself is a little wonky it seems. If you listen to bug-01 a little longer you'll notice there will sometimes be multiple snares in a row. It looks like most of the time the automation is applied before the sample is played, but also sometimes shortly after, so the sample starts at the old position. The chances for either one to happen seem to be random. Please tell me if this is worth its own bug report or not.

System Info: Win10 10.0.18362.175 LMMS 1.2.0 x64

**Comment by SecondFlight** [comment]
Possibly related: #2149

**Comment by Sauerstoffdioxid** [comment]
Did some further investigation. It looks to me like the bug occurs when loading the project (and especially when loading the AFP). I compared the original bug-04.mmp to itself loaded and saved again (let's just call it bug-05). The automation tracks still target the same IDs, however the AFP lost one of its properties, which the other took over.

![grafik](https://user-images.githubusercontent.com/35171164/60452876-e15ee780-9c2f-11e9-983b-75fb02ece699.png)
[Left is bug-05, right is original bug-04.]

I took a look at the AFP loading code, but decided I don't know LMMS's code well enough (or more like, at all) to make any assumptions.

**Comment by PhysSong** [comment]
> I'd say it's related to that compat code in some way.

It seems like you're right:
https://github.com/LMMS/lmms/blob/3ada5b8a126b529c94cbe0c01b60a11ecb08dec8/plugins/audio_file_processor/audio_file_processor.cpp#L258
`AutomatableModel` can be saved in two different ways: either as an attribute or as a child element. LMMS uses the second way if the model is automated.
However, the code above check for attributes only, not child elements.

**Comment by PhysSong** [comment]
Fixed in #5472.
