### ISSUE TITLE
Add a search to samples 

### ISSUE THREAD

**Issue by harshnagarkar** [LMMS/lmms#5066]
If there was search to type in the name, for my samples, projects, and plugins, that would be great.

**Comment by DouglasDGI** [comment]
@harshnagarkar There already is...
![Screenshot from 2019-06-30 15-50-54](https://user-images.githubusercontent.com/34612565/60402572-eb5ce980-9b4e-11e9-8a09-23edf30235d1.png)

**Comment by SecondFlight** [comment]
@harshnagarkar Please make sure you're running the latest version of LMMS: https://lmms.io/download/

**Comment by harshnagarkar** [comment]
Yes, I have downloaded the latest version which is 1.2.0 from the website.
It doesn't load in mine.
![Screenshot (122)](https://user-images.githubusercontent.com/30268498/60454710-2f58f880-9bfa-11e9-8796-f43c25fec43d.png)

**Comment by DouglasDGI** [comment]
@harshnagarkar The search bar is in the bottom left of that image.  My copy has it on the top (maybe because I have the master branch), sorry for the confusion.

**Comment by SecondFlight** [comment]
Sorry about that, I should have checked it myself.
