### ISSUE TITLE
Add a rubber tool in song editor to cancel multiple patterns

### ISSUE THREAD

**Issue by RoxasKH** [LMMS/lmms#5072]
In LMMS is easy to make a lot of copies of the same pattern by selecting and ctrl-dragging it. But it's not that easy when it comes to delete a lot of patterns you want no more. Selecting them and right-click-->delete will delete only one pattern, and so it's annoying have to delete them one by one if they're a lot.

A possible solution is to add a rubber tool in the song editor to serve this purpose, that when you pass over a pattern while it's pressed it deletes it.

Or another is to make the right-click-->delete option to delete all the selected patterns.

Hope this could help

**Comment by PhysSong** [comment]
I believe this is implemented in #3649 and will be available in future releases after 1.2.x.
