### ISSUE TITLE
VST effects' GUIs don't show after re-opening LMMS

### ISSUE THREAD

**Issue by igggo123** [LMMS/lmms#5075]
> 
> 
> Does it show if you click the "Show/hide" button?

oh sorry im a ding dong lol

**Comment by DouglasDGI** [comment]
Does it show if you click the "Show/hide" button?

**Comment by DouglasDGI** [comment]
@igggo123  Instead of editing your original message, you should reply with a comment.  Now this thread doesn't really make sense to anybody who reads it.

I'll close this since it's resolved now.
