### ISSUE TITLE
Synth1 file manager doesn't open my Linux storage 

### ISSUE THREAD

**Issue by mrshroomy** [LMMS/lmms#5082]
**Kernel:** 5.2.1-1
**Linux Distro:** Manjaro XFCE
**LMMS Version:** 1.2.0 AppImage **and** 1.2.0-2 on Manjaro repository
**Wine Version:** 4.12.1 (Staging)
I opened Synth1 in Vestige and then i used the opt button in Synth1. I then used the browse button to find where my external soundbank was and i only got those locations that are shown in the picture, the same happens when trying to set a internal soundbank location. 
![bug](https://user-images.githubusercontent.com/52048952/61552513-51ef6c00-aa58-11e9-921e-49a200537cf4.png)

**Comment by musikBear** [comment]
and you cant expand *My Computer*? 
* Have you tried clicking in the square?
* Did you properly *install* Synth1, or only *unpacked* the zip?

**Comment by noahb01** [comment]
I've never used VSTs through Wine before, but I have had this issue in other programs running through Wine. I think I ultimately ended up making a new `WINEPREFIX` and starting over, but I'm not sure. Its *probably* not an LMMS bug though. Also try restarting your computer (if you haven't already), I'm pretty sure that Wine has some daemons that handle basic Windows services that may not be running on your system.

**Comment by musikBear** [comment]
To test VST with WINE try MDA-Piano http://mda.smartelectronix.com/synths.htm
It is very small in size, and you can just copy it to your folder. -Eg NO installation! Further its a quite good piano-instrument, so it is a win win

**Comment by mrshroomy** [comment]
This worked on this setup right now:

Kernel: 5.3.0-1
Linux Distro: Manjaro XFCE
LMMS Version: 1.2.0 AppImage
Wine Version: 4.13 (Staging)

So i guess that wine got configured in a bad way in some way.
