### ISSUE TITLE
The decay and gate knobs under the FX window seem broken

### ISSUE THREAD

**Issue by SeanG27** [LMMS/lmms#5091]
It seems that I can not tweak the two knobs under the FX window for any effect or instrument. When I right-click the two knobs, I get the same pop-up window as if I right-click the effect itself. In other words, there seems to be no way that I can change the decay and gate parameters.

**Comment by SecondFlight** [comment]
What LMMS version / OS are you using?

**Comment by DouglasDGI** [comment]
@SeanG27 Turn off "Keep effects running even without input" in Edit -> Settings and restart LMMS.

**Comment by SeanG27** [comment]
@DouglasDGI  Thanks! That solves my problem perfectly.

**Comment by zonkmachine** [comment]
Issue discussed here https://github.com/LMMS/lmms/issues/4749
