### ISSUE TITLE
Piano-roll : Fast method to deselect all

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#5096]
miss a fast method to deselect. 
I bet you all also 'just' click somewhere -witch does deselect all, and then 'just' delete the note that was made with that click :p
perhaps A kb-shortcut or  a simple button would spare that *extra* note-delete

**Comment by DomClark** [comment]
Isn't it sufficient just to ctrl-click somewhere without a note?

**Comment by zonkmachine** [comment]
Escape key?

**Comment by PhysSong** [comment]
Either way works on both `stable-1.2` and `master`.

**Comment by musikBear** [comment]
> Escape key?
LOL i had NO idea :+1

**Comment by Sawuare** [comment]
Right-click on empty area to deselect everything would be nice.
I will keep this in mind.

**Comment by PhysSong** [comment]
> Right-click on empty area to deselect everything would be nice.
> I will keep this in mind.

Why don't you open an issue and add a `good first issue` tag?

**Comment by DouglasDGI** [comment]
I'm not against adding another method to deselect all, just pointing out that Shift+Ctrl+A already does this.

**Comment by Sawuare** [comment]
@PhysSong #5103

@DouglasDGI I suggested the right-click mouse shortcut since most interactions with the piano roll are mouse based. Shift+Ctrl+A is a long keyboard shortcut.

**Comment by SecondFlight** [comment]
@DouglasDGI One is a shortcut, the other is a mouse interaction. Personally I think it's good to have both.

**Comment by musikBear** [comment]
Guys @zonkmachine said **Esc** It works! -i just diddent knew    ..after 12 y... :]

**Comment by zonkmachine** [comment]
> i just diddent knew ..after 12 y... :]

It's a bit newer than that but may be undocumented. I think it's perfectly fine to add yet another way to do it if people would rather want to do it with the mouse.
