### ISSUE TITLE
Extending pitch knob's range / glissando and pitch bends in the Piano Roll

### ISSUE THREAD

**Issue by unfa** [LMMS/lmms#51]
Hey, I frequently wish I could turn the pitch knob up 4 tones or such.
How about another knob changing pitch knob's range?

Another thing is a way to make a glissando between selected notes that will in fact work just like automating the pitch knob. I think of it this way, because it would work with ZynAddSubFX whitch is my weapon of choice.
It could work be selecting notes which are to start the glissando and pressing a "Gliss note" checkbox (Ctrl+G shortcut?). Then whatever note is overlapping with that one will not send another note-on, but make a pitch ramp as long as the two notes overlap.

Also a pitch curve could be displayed with control point for making manual pitch bends and changing the shape of the glissando ramp.
![concept 01](https://f.cloud.github.com/assets/491704/1941352/183f7b8a-7f89-11e3-96ce-2f597c387925.png)

**Comment by Sti2nd** [comment]
Is the difference between glissando and pitch bend that with pitch bend there will be silence when the new note starts playing and the pitch bend note is released, whereas glissando makes this seamlessly?

I think unfa suggests the ability to draw glissando/pitch bends in the Piano Roll, not having to open the Automation Editor.

**Comment by tresf** [comment]
IIRC the main difference is just the way it is used for composing.  Note
accuracy from a piano roll perspective.  FLStudio and Ableton for example,
have what is being described inside the piano roll editor.

**Comment by Snarfdog** [comment]
I've always wanted to be able to do this in the piano roll too. I luckily came across an open source project file that had exactly what you guys are talking about. Take a look at this picture:
![pitch bend in piano roll](https://cloud.githubusercontent.com/assets/10539590/5750358/db617856-9c21-11e4-8712-4cfc7057267d.jpg)

In the song it does a perfect glissando down one octave over the length of the note. This occurs at other points in the song where it glisses down a few whole steps (the end of the arrow is the end pitch obviously). Unfortunately I have no idea how it was accomplished.

**Comment by tresf** [comment]
That little blue automation graph button does that.

**Comment by Snarfdog** [comment]
Oh, just figured it out. Sorry, I'm an LMMS noob :)

**Comment by tresf** [comment]
> Oh, just figured it out. Sorry, I'm an LMMS noob :)

I just figured it out last week myself... No worries. :)

> EDIT: So how is this different from a glissando between two notes? I guess there would still be an attack on the next note...

It's really the same thing, but if you look at unfa's diagram, glissando is usually note-based rather than pitch based.  Most piano rolls just have note sliding available.  Try the LB302 with the slide button on and you'll quickly notice how much faster it is to slide note-to-note rather than pitch to pitch. :pizza:

**Comment by tresf** [comment]
> I don't think an overlapping pitch bend implementation would be a very good idea - seems to me it'd be likely to cause conflicts and overcomplexity. So the only smart way to do this would be to use the existing pitch bend functionality and add some helper tools to make glissandoing easier.

Agreed, unless we decide to introduce some note grouping functionality -- such as color assignments.

**Comment by Umcaruje** [comment]
I think this should be closed, since pitch automation is shown correctly in the piano roll now, and the pitch knob has a range.

**Comment by tresf** [comment]
Perhaps, but the "between selected notes" description unfa originally asked for hasn't been implemented yet, just an arbitrary graph which has no control over which note it is landing on.

I actually find the per-note pitchbend to be less granular than an automation graph, which is a separate issue entirely, but speaks to the difficulty in getting the note slide correctly, which is really what this bug report is asking for.

**Comment by tresf** [comment]
> I think this should be closed, since pitch automation is shown correctly in the piano roll now, and the pitch knob has a range.

Agreed.  We can file a new request for the enhancements that are missing.
