### ISSUE TITLE
Song Editor: Clone only Instrument

### ISSUE THREAD

**Issue by Gabrielxd195** [LMMS/lmms#5112]
This is a good idea friend because it avoids heavy vst crashes. I had thought this but the other way around. that is, add the option to ''clone only the instruments'', since when you have an instrument set on a track full of notes, when you only want to clone this instrument without the notes, then you have to delete all the notes manually, and This is annoying, it is best to implement both ideas: ''clone only notes'' and ''clone only instrument'', in the first case you would use 3osc by default and in the second you will clone the instrument alone.

_Originally posted by @Gabrielxd195 in https://github.com/LMMS/lmms/issues/5109#issuecomment-517863164_

**Comment by StakeoutPunch** [comment]
There is an option to clear all of a track's notes at once. Clone this track -> Clear this track
![image](https://user-images.githubusercontent.com/6579031/62428315-e6e39d80-b6c5-11e9-84f5-66ac80024b2a.png)

**Comment by Gabrielxd195** [comment]
> There is an option to clear all of a track's notes at once. Clone this track -> Clear this track
> ![image](https://user-images.githubusercontent.com/6579031/62428315-e6e39d80-b6c5-11e9-84f5-66ac80024b2a.png)

Thanks
