### ISSUE TITLE
Issues with 1.2.0 on macOS Mojave 10.14

### ISSUE THREAD

**Issue by GingkathFox** [LMMS/lmms#5113]
- Can't open instrument window
- Can't automate notes
- loops aren't snapping to grid

These are the 3 i found before i flipped and quit.

EDIT: More issues:
- Taps don't register, but clicks do.
- Double tapping to open the piano-roll locks the loop to the cursor, and the loop decides to snap to the grid. The loop will continue to stick until you click on it. (Doesn't happen when double clicking to open the piano-roll.)

**Comment by bleonard252** [comment]
I'm on a 10.14 school Mac (for Digital Media) and can add/confirm instruments (likely loops, too) don't seem to snap.

**Comment by GingkathFox** [comment]
gonna close this cause i havent had these issues with the latest build
