### ISSUE TITLE
[Lv2/SPA] Using instrument window arrow keys fails to resize

### ISSUE THREAD

**Issue by JohannesLorenz** [LMMS/lmms#5115]
When you use the arrow keys of the instrument track view (top right) to switch instruments, if the instruments have different sizes, sometimes the dialogue does not resize.

Reproduce on `lv2-review` (#4899):
* Open LMMS main window, do nothing else
* Drag the lv2-testsignal-generator on the instrument board
* Open the triple-oscillator instrument window
* Use an arrow to switch the window to use the lv2-testsignal-generator

The bug also occurs if you open the lv2-testsignal-generator first and then switch to 3osc. It does not always occur if you have had both instruments open without ever using the arrows. It's some strange caching behaviour, which may be fixed/removed in #3623 .

* Branches: all
* Observable on: Any with variable-sized instrument windows. At least `lv2-review` (#4899) and soon on `osc-plugin` (#4662) .
* Introduced: Merge of branch `variable-tab-widget` (#4906) into `master` (not as a regression issue, but as a bug of the new feature).

**Comment by PhysSong** [comment]
Reproduced with LV2. I'll see if it's related with #3623.

**Comment by PhysSong** [comment]
Dropping the caching system seems to fix this issue. I left with re-implementing the `One Instrument Track Window Mode` feature now.

**Comment by JohannesLorenz** [comment]
No need to use the arrow keys. As @DouglasDGI reported, you can

1. add tracks for triple-oscillator and lv2-testsignal-generator
2. open triple-oscillator's instrument window
3. close it
4. open lv2-testsignal-generator's instrument window

Then, the testsignal generator will have the same size as the 3osc (which is wrong). @PhysSong does your fix also fix this issue?

**Comment by PhysSong** [comment]
It looks like an almost identical issue, and the same patch should fix it. I haven't tested that yet, though.

**Comment by PhysSong** [comment]
Found a third variant:
1. Add a TripleOscillator.
2. Open it.
3. Drag and drop lv2-testsignal-generator to the open window.
4. Boom!

This variant is more complicated, but I found a fix which seems to work for all observed variants even without fixing the `InstrumentTrackWindow` caching problem.
