### ISSUE TITLE
FLAC export not identical to WAV

### ISSUE THREAD

**Issue by Spekular** [LMMS/lmms#5128]
When exporting to FLAC with a recent master build, I noticed that the output had noticeable (sometimes severe) crackling not present in previous exports. Here's a comparison of the output waveform, with WAV on top and FLAC on the bottom:

![image](https://user-images.githubusercontent.com/8918426/63210043-49d32c80-c0e9-11e9-9b6e-99ff04473669.png)

Examining the top left of both waveforms, the FLAC export appears to have a downwards DC offset. In addition, when this offset wave reaches -1.0, it wraps around and "sticks" at 1.0.

Export options: 44.1kHz, 24 Bit, Sinc best, No oversampling

Also, a minor filename bug:

- When choosing output location, leave extension on the default "WAV"
- Select FLAC as output format
- File extension of exported file is `.wav.flac`

**Comment by PhysSong** [comment]
Reproduced. 16bit FLAC works fine, only 24bit FLAC is problematic.

**Comment by PhysSong** [comment]
It seems like there's a bug with `libsndfile`'s FLAC export: https://github.com/erikd/libsndfile/issues/309
Probably we can use `sf_writef_int` instead of `sf_writef_float` which is buggy for FLAC.

**Comment by PhysSong** [comment]
Another way is to clip samples on LMMS side before passing to the buggy `libsndfile` function.

**Comment by zonkmachine** [comment]
> Another way is to clip samples on LMMS side before passing to the buggy `libsndfile` function.

This sound like the best solution to me. The buggy libsndfile versions are going to be around for quite some time so I'm milestoning this.

**Comment by zonkmachine** [comment]
[This line](https://github.com/LMMS/lmms/blob/170d28ffbd39b1f0406e437eaeac39a07389f525/src/core/audio/AudioFileFlac.cpp#L97)

```
buf[frame*channels() + channel] = _ab[frame][channel] * master_gain;
```

to

```
buf[frame*channels() + channel] = qMax(-0.9999999, _ab[frame][channel] * master_gain);
```

This works. I was thinking -1.0f as min value would work but it was still clipping.

**Comment by michaelgregorius** [comment]
I think clamping the samples inside of LMMS isn't a good idea. As written [here](https://stackoverflow.com/a/29957251) it's perfectly OK for a float encoded WAV file to have values that are outside of the [-1, 1] interval. Here's the relevant section from the link:
>WAV files saved as floating point do allow values exceeding the 0 dB range. This means the range is actually beyond [-1, 1] for values that normally would clip.
>
>The explanation for this can be that floating point formats are intended for intermediate use in production setups due to very little loss of dynamic range, where future processing (gain-staging, compressing, limiting etc.) can bring back the values (without loss) well within the final and normal -0.2 - 0 dB range; and therefor preserves the values as-is.

If you clamp the samples inside of LMMS this will not work anymore.

Therefore I think a better fix would be to integrate the newer version of libsndfile and to show a warning message to the user if the export has clipped for formats where clipping can occur. I think the engine of LMMS should never clamp any values at any point in the path and just mix (float) audio streams regardless of how they look.

**Comment by PhysSong** [comment]
> As written [here](https://stackoverflow.com/a/29957251) it's perfectly OK for a float encoded WAV file to have values that are outside of the [-1, 1] interval. Here's the relevant section from the link:

I mean, clipping on LMMS side only for 24-bit integer FLAC.

**Comment by zonkmachine** [comment]
> If you clamp the samples inside of LMMS this will not work anymore.

The FLAC export clips the sample already in:
`sf_command(m_sf, SFC_SET_CLIPPING, nullptr, SF_TRUE);`
If you remove this the export becomes even more destroyed. You need to clip it to prevent issues if the signal goes above/below +/-1.0 and libsndfile provides this function (If the code works that is).

I tried some exporting options with a loud decaying sinewave.
1. wav 
2. 16 bit flac
3. 24 bit flac
4. 24 bit flac    `sf_command(m_sf, SFC_SET_CLIPPING, nullptr, SF_FALSE);`
5. 24 bit flac    `qMax(-0.999999f, _ab[frame][channel] * master_gain);`

![flacclip](https://user-images.githubusercontent.com/6368949/82104117-e0368c00-9715-11ea-8027-608f0a88bfc5.png)

**Comment by zonkmachine** [comment]
>  Probably we can use `sf_writef_int` instead of `sf_writef_float` which is buggy for FLAC.

As I understand it then we need a 24 bit version of `AudioDevice::convertToS16`. Too much work for the same result. I'll pull a fix clipping the negative side instead.

**Comment by zonkmachine** [comment]
> It seems like there's a bug with `libsndfile`'s FLAC export: [erikd/libsndfile#309](https://github.com/erikd/libsndfile/issues/309)

libsndfile was just tagged 1.0.29: https://github.com/erikd/libsndfile/releases/tag/v1.0.29
