### ISSUE TITLE
Master hangs when opening VST automation window

### ISSUE THREAD

**Issue by Spekular** [LMMS/lmms#5132]
Win 10 64 bit, happens regardless of which VST is loaded, but not in an empty VeSTige instance.

![image](https://user-images.githubusercontent.com/8918426/63229572-09b39d00-c202-11e9-8ab8-4f0bd7b9b028.png)

**Comment by DomClark** [comment]
I get a segfault clicking that button on master. Is this the issue you're observing?

`manageVestigeInstrumentView::manageVestigeInstrumentView` tries to create a new subwindow with a null widget: https://github.com/LMMS/lmms/blob/ce5c74432e83f0eaa617cc26332f4209bc4efc7f/plugins/vestige/vestige.cpp#L910-L911
But `MainWindow::addWindowedWidget` tries to get the size hint for the given widget: https://github.com/LMMS/lmms/blob/ce5c74432e83f0eaa617cc26332f4209bc4efc7f/src/gui/MainWindow.cpp#L628

This line and the bug were introduced in c3b4d51. I guess we can just change the test to `w && w->sizeHint().isValid()`.

**Comment by Spekular** [comment]
I assume so.

**Comment by Spekular** [comment]
@DomClark will you make a PR for this?

**Comment by Reflexe** [comment]
Could someone verify that it does not happen in stable too?

**Comment by Spekular** [comment]
@Reflexe I've used this window a lot in 1.2 with no issues, but I just tested again to ensure it didn't regress in stable. Can't reproduce on stable 1.2.
