### ISSUE TITLE
Can't sign up at https://lmms.io/lsp/?action=register

### ISSUE THREAD

**Issue by javthon** [LMMS/lmms#5136]
I wanted to sign up at https://lmms.io/lsp/?action=register and I input the right security code but it always shows "Invalid security code"

**Comment by BaraMGB** [comment]
To clean up the tracker I will close this issue. I don't know how to help here and I hope someone can look at the login of the site. But this is definitely not an issue with lmms. If you have further problems with log in our discord is the better place to ask.
