### ISSUE TITLE
Redo (ctrl+Y) in the Piano Roll does not work.

### ISSUE THREAD

**Issue by GoodFaithParadigm8** [LMMS/lmms#5140]
ubuntu 18.04
version LMMS 1.1.3

#### Behavior: 

If a cord gets deleted, when I press the edit menu redo button or ctrl+Y it does not revise my previous session. 

#### Expected behavior:

If I press the redo button or ctrl+Y in the piano roll I would like to time travel back through my previous edits.

**Comment by Spekular** [comment]
Please test any bug reports with the latest version so you're not reporting something that's already been fixed. The latest official versions of lmms are available at lmms.io/download.

At time of writing, 1.2.0 is the latest version, so you should install that and see if the issue you describe still occurs.

**Comment by GoodFaithParadigm8** [comment]
Not sure if it was a system resource snag or something, but when I tested the `crtl+A` to __copy all__ `ctrl+Z` and `ctrl+Y` worked as expected. There's been a couple times the program exited for whatever reason, just installed today, familiar with pro-tools and fruity-loops. Not a bad console once you get the hang of it.
