### ISSUE TITLE
Piano Roll Select All Notes

### ISSUE THREAD

**Issue by GoodFaithParadigm8** [LMMS/lmms#5141]
ubuntu 18.04
version LMMS 1.1.3

Behavior:

If there are many cords and I hold ctrl to select all the notes in the Piano roll I can not pan the screen and select more notes.

Expected behavior:

I would like to be able to select all the notes in the Piano Roll using ctrl or otherwise.

**Comment by Spekular** [comment]
Ctrl+A is the typical "select all" shortcut in most programs, and unless i'm mistaken it works in Piano Roll as well.

**Comment by GoodFaithParadigm8** [comment]
Ctrl + A does work. Thanks.

**Comment by musikBear** [comment]
Should be mentioned here that notes can be added (or removed) to/from an *existing selection*, by pressing SH+CTRL in a mouse select.
Also, it is smart to use a low magnification, if you plan to make a big selection of notes, but that more like a 'best-method' recommendation, and not a feature.
