### ISSUE TITLE
Fix some spellling errors

### ISSUE THREAD

**Issue by RossGammon** [LMMS/lmms#5150]
Whilst packaging lmms for Debian, some spelling errors were found using the lintian tool. A patch was applied in Debian. I will create some PRs to fix them.

**Comment by RossGammon** [comment]
https://github.com/LMMS/lmms/pull/5151
https://github.com/LMMS/zynaddsubfx/pull/15
https://github.com/LMMS/veal/pull/7
https://github.com/swh/ladspa/pull/62

**Comment by JohannesLorenz** [comment]
All are merged or closed now, so closing this.
