### ISSUE TITLE
Logo inconsistency

### ISSUE THREAD

**Issue by iansannar** [LMMS/lmms#5164]
The logo for the repository, the LMMS organization on Github, and the favicon for the website uses the first iteration of the headphone logo rather than the flat silhouette logo used for the program icons & splash screen.

### Website favicon
![image](https://user-images.githubusercontent.com/8443754/64146885-d5340980-cddb-11e9-8db8-5a0f2b92a686.png)

### README.md
![image](https://user-images.githubusercontent.com/8443754/64146935-f7c62280-cddb-11e9-82f1-169df5fbcc80.png)

### Github organization
![image](https://user-images.githubusercontent.com/8443754/64146968-12000080-cddc-11e9-99c2-b0b85435e2e2.png)

I can fix and make pull requests for the [website](https://github.com/LMMS/lmms.io/pull/275) and `README.md`, but I won't be able to fix the Github organization logo.

**Comment by PhysSong** [comment]
If you make an icon for the organization logo, one of the admins(including myself) can update that.

**Comment by iansannar** [comment]
Here's two sizes depending on what you need.

### 64px
![lmms](https://user-images.githubusercontent.com/8443754/64148530-c13ed680-cde0-11e9-87de-1860383dcd7f.png)

### 1024px
![icon_512x512@2x](https://user-images.githubusercontent.com/8443754/64148570-d7e52d80-cde0-11e9-9c0e-19d273effcda.png)

**Comment by PhysSong** [comment]
@iansannar Thanks. I've changed the organization logo.

**Comment by rubiefawn** [comment]
✅ `README.md` fixed in #5166.
✅ `favicon.ico` fixed in https://github.com/LMMS/lmms.io/pull/275.

**Comment by iansannar** [comment]
Looks like someone took care of the website branding, so this is all cleared up!
