### ISSUE TITLE
Unknown LADSPA plugin fbdelay_0.1s

### ISSUE THREAD

**Issue by DanielChabrowski** [LMMS/lmms#5167]
OS: xubuntu 19.04
lmms-1.2.0-linux-x86_64.AppImage

The following happens after opening "Thalendric - Armageddon" demo:
```
The following errors occured while loading: 
Unknown LADSPA plugin fbdelay_0.1s requested.
Unknown LADSPA plugin fbdelay_0.1s requested.
```

Even though the effect is visible and should be provided by CMT:
![Screenshot_2019-09-03_22-24-13](https://user-images.githubusercontent.com/10281628/64207104-36bbad00-ce9c-11e9-90d0-4310e779ca64.png)

**Comment by zonkmachine** [comment]
If you save that project as an mmp and change "fbdelay_0.1s" to "fbdelay_0,1s" it will open.

**Comment by zonkmachine** [comment]
This issue is present already on lmms-1.0.3

**Comment by PhysSong** [comment]
It seems like CMT plugins use locale-dependent `sprintf` function to generate the plugin descriptor. Since LMMS relies on the label of the LADSPA plugin descriptor, the local dependence becomes a problem.
However, I'm still not sure how to handle this issue...

**Comment by DanielChabrowski** [comment]
Running `export LC_NUMERIC=en_US.UTF-8` before lmms is a possible workaround if someone is dying to listen to this demo in its full glory.

**Comment by zonkmachine** [comment]
>  [upstream](/LMMS/lmms/labels/upstream)

It looks like CMT isn't managed upstream anywhere today so we may have to hack around this here. See comment in issue https://github.com/LMMS/lmms/issues/3963
`warning Very old. No upstream VCS. Available as a tarball only. May need to fork.`

**Comment by trebmuh** [comment]
CMT has a released in Jan this year. [See there](http://www.ladspa.org/cmt/changes.html).

**Comment by Rossmaxx** [comment]
> CMT had a release in January this year. See there.

Did this fix the issue? Can anyone confirm.

If not, is it fine to manually tweak the mmp?

**Comment by zonkmachine** [comment]
> Did this fix the issue? Can anyone confirm.

Did you open "Thalendric - Armageddon" ?



> If not, is it fine to manually tweak the mmp?

No. I think we need an upgrade routine. Also, I don't know if this has been, or should be, reported upstream.

**Comment by Rossmaxx** [comment]
For me, the file opened fine without any errors.

**Comment by zonkmachine** [comment]
On Swedish computer.

![image](https://github.com/LMMS/lmms/assets/6368949/aa2e5f99-9a58-4a70-8870-24a4b852a208)

**Comment by Rossmaxx** [comment]
So is this error language dependent?

**Comment by zonkmachine** [comment]
> So is this error language dependent?

Local dependent, yes. See this comment: https://github.com/LMMS/lmms/issues/5167#issuecomment-528168024

**Comment by michaelgregorius** [comment]
I have a pull request which fixes half of the problem, i.e. the locale dependent delay names in the delay plugins: https://github.com/LMMS/cmt/pull/6.

Once this is merged the other half of the fix would be to write an upgrade routine in the LMMS loading code which replaces all delay names that contain commas with the ones that contain dots. Otherwise this might break the projects of people which use locales that have originally loaded the plugins with commas in their names and which have saved them as such.

**Comment by michaelgregorius** [comment]
Pull request https://github.com/LMMS/lmms/pull/7206 implements the upgrade routine. It must only be merged if the CMT pull request was merged!
