### ISSUE TITLE
Export cuts off long release/echo/reverb

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#517]
if the last note has release/echo/reverb above one bar, it is not exported. user has to add a dummynote, and force lmms to export this too - (simple -just use one outside human hearing)
Tested with both ogg & wave

**Comment by curlymorphic** [comment]
Export between loop markers is an easy way to set the end point for rendering.

**Comment by M374LX** [comment]
> Export between loop markers is an easy way to set the end point for rendering.

I think the best solution is to include this problem and the use of loop markers in the user documentation. Done that, this issue can be closed.

**Comment by musikBear** [comment]
@M374LX agree :+1: -I will find the paragraph and add it.
