### ISSUE TITLE
Hacktoberfest 2019

### ISSUE THREAD

**Issue by JohannesLorenz** [LMMS/lmms#5175]
There will be another [hacktoberfest](https://hacktoberfest.digitalocean.com/) in October 2019. It basically means that any github user who creates 4 useful PRs in October (see the [FAQ](https://hacktoberfest.digitalocean.com/faq) for more info) will earn a T-shirt.

**Let's take the opportunity to get some new devs.**

As the FAQ states, any project should list issues recommended for Hacktoberfest with a label "Hacktoberfest" (capital "H"). We can use this to get urgent issues finished and to attract new developers. However, I think the **issues should be analyzed already**, because new devs from other projects may not be able/interested to do a deep analysis. Also, **issues should be small or medium sized**.

Moreover: "You can also share issues or repositories on Twitter, using #Hacktoberfest where we’ll try to retweet as many as we can for contributors to see!"

What issues shall we tag?
* I'm for [all 1.2.1-issues](https://github.com/LMMS/lmms/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+milestone%3A1.2.1), as 1.2.1 needs to get finished. Let's analyze them all, split some if the solution will get too heavy.

**Comment by artur-twardowski** [comment]
The link to the FAQ seems to be incorrect

**Comment by JohannesLorenz** [comment]
@artur-twardowski Thanks, fixed.
