### ISSUE TITLE
Tap Tempo

### ISSUE THREAD

**Issue by GoAwayTee** [LMMS/lmms#5181]
One thing I would love to see in LMMS is the Ability to Tap your own Tempo. It can either be tapped by your spacebar or by your Left Mouse Click. This way you will definitly assign the Tempo you want.

**Comment by GingkathFox** [comment]
> ...This way we could synchronize the tempo in LMMS with external clock source, such as MIDI keyboard.

Or even the opposite, where the tempo is tapped on the midi controller and LMMS syncs with it :D

**Comment by Sawuare** [comment]
For simplicity and friendliness, I suggest to tap on any key/mouse press event on the widget.

**Comment by GingkathFox** [comment]
i agree, would be much better than clicking a button

**Comment by rezbyte** [comment]
Mind if I give this issue a shot?

**Comment by Sawuare** [comment]
The following is my GUI vision for the feature:
• Access to it would be through an action in the Tools drop-down of the menu bar, or an action in the context menu of the Tempo LcdSpinBox.
• It would be a small pop-up widget with a button for tapping. The button would show the current tempo.

**Comment by musikBear** [comment]
@Sawuare wrote
> The following is my GUI vision for the feature:

Not that way. Ergonomically it is quite difficult to finger-click in a consistent way (it has to do with anatomical mehhee ) If you try you will either find your self banging on the mouse, or pressing quite hard. After a while your finger start to hurt ;p (Tendonitis alert..).
No the easy way to keep a steady rhythm, is to tab on **space**, where the motion is in the *wrist*, not the finger

**Comment by IanCaio** [comment]
Mind me giving my two cents? It doesn't really matter whether the mouse or space is used (maybe make both a possibility?), but IMHO the BPM calculation would have to take to account an average of many user taps. The difference of the time between beats of 120bpm and 110bpm is 0.045s. Meaning that if you always calculate the difference between the last two taps you'll have a lot of different BPMs on each try. If you store the time difference between the last X beats you'll have a little more accurate and stable BPM read.

**Comment by RoxasKH** [comment]
> 
> 
> @Sawuare wrote
> 
> > The following is my GUI vision for the feature:
> 
> Not that way. Ergonomically it is quite difficult to finger-click in a consistent way (it has to do with anatomical mehhee ) If you try you will either find your self banging on the mouse, or pressing quite hard. After a while your finger start to hurt ;p (Tendonitis alert..).
> No the easy way to keep a steady rhythm, is to tab on **space**, where the motion is in the _wrist_, not the finger

Go telling that to Image-Line xD

FL one works exactly like that, and you don't really need to be precise, only to get an idea of the tempo you want you can simply adjust later.

**Comment by qnebra** [comment]
Single window with Big Friendly Button with text "Tap Spacebar when active to set tempo" on it.
