### ISSUE TITLE
AppImage has Travis-CI paths

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms#5187]
The AppImage's AppRun has some paths added that are benign but shouldn't be there, probably due to improper immediate variable expansion.

Most of these are benign because they'll never exist on a machine, but some, such as `/opt/qt59/bin` can cause issues, since the AppImage should prefer the Qt5 that it ships with.

```bash
export PATH="\
/home/travis/build/PhysSong/lmms/build/cmake/linux/squashfs-root/usr/bin:\
/opt/qt59/bin:\
/opt/qt59/bin:\
/home/travis/.rvm/gems/ruby-2.4.1/bin:\
/home/travis/.rvm/gems/ruby-2.4.1@global/bin:\
/home/travis/.rvm/rubies/ruby-2.4.1/bin:\
/home/travis/.rvm/bin:\
/home/travis/bin:\
/home/travis/.local/bin:\
/opt/pyenv/shims:\
/home/travis/.phpenv/shims:\
/home/travis/perl5/perlbrew/bin:
/home/travis/.nvm/versions/node/v8.9.1/bin:\
/home/travis/.kiex/elixirs/elixir-1.4.5/bin:\
/home/travis/.kiex/bin:\
/home/travis/gopath/bin:/home/travis/.gimme/versions/go1.7.4.linux.amd64/bin:\
/usr/local/phantomjs/bin:/usr/local/phantomjs:\
/usr/local/neo4j-3.2.7/bin:/usr/local/maven-3.5.2/bin:/usr/local/cmake-3.9.2/bin:\
/usr/local/clang-5.0.0/bin:\
/usr/local/sbin:\
/usr/local/bin:\
/usr/sbin:/usr/bin:\
/sbin:\
/bin:\
/home/travis/.phpenv/bin:\
/opt/pyenv/bin:\
/home/travis/.yarn/bin:\
/sbin"

```

**Comment by PhysSong** [comment]
https://github.com/LMMS/lmms/blob/0059c6e71f6431b4ed13d8e444f133642bbe933d/cmake/linux/package_linux.sh.in#L103
I think it should be `export PATH="\$PATH:/sbin"`.

**Comment by tresf** [comment]
I've committed the patch directly to `master`.  If it causes major issues, we can cherry-pick it to `stable-1.2`.
