### ISSUE TITLE
Alternative views (tile, tabs, etc)

### ISSUE THREAD

**Issue by DoosC** [LMMS/lmms#519]
It would be nice to have alternatives to the current "windows" view.
I can think of two new views :
- a "tab" view where each open window would be a full screen tab
- a "tile" view where each open window would be tiled and remain movable and resizable (for example, you may want to have the song editor at the top of the screen 1/3, and the remaining 2/3 of the screen having the piano roll below).

**Comment by Rossmaxx** [comment]
should we close this one in favour of https://github.com/LMMS/lmms/issues/1911 because that one's more descriptive.

**Comment by Rossmaxx** [comment]
Better to consolidate, as we all agreed to move to that direction
