### ISSUE TITLE
Running LMMS on Odroid N2

### ISSUE THREAD

**Issue by deuteragenie** [LMMS/lmms#5195]
Feature request: make LMMS OpenGL ES compatible. 
I'd like to be able to run it on an Odroid N2.

**Comment by PhysSong** [comment]
>  make LMMS OpenGL ES compatible

Which OS are you using on the device? If you're on Ubuntu, you can compile and LMMS as if it were a Linux PC.
If you use Android, there's no way to run LMMS natively on Android. You may use Linux-on-Android apps as a workaround with possible performance degradation, though.

**Comment by deuteragenie** [comment]
I can use Ubuntu on that device, that is not an issue.

I am not quite sure that LMMS can run with OpenGL ES (instead of OpenGL) though.  Is there a compilation option to that effect ?

I am aware of possible performance degradation, but would like to try it out and see what it gives.

**Comment by CaBachhav** [comment]
This is the most talked about topic among thousands of Lmms users , that LMMS on Androids should be given several  try . For latency issue it will use applicable that we should directly compile an APK for ARM processors . Ubuntu route should be avoided. several users are demanding that LMMS should come on Raspberry Pi platform.

**Comment by PhysSong** [comment]
> several users are demanding that LMMS should come on Raspberry Pi platform too.

On the Raspberry Pi, it's nothing more than the usual compilation.

**Comment by softrabbit** [comment]
> Having looked a bit around, it seems that LMMS is using QT, which appears to support Open GL ES.
> The other issue I guess is how to run LMMS without X11, as there is no driver available for the Odroid N2.

I believe a lack of X11 would mean no ZynAddSubFX (at least no UI, could be that running it headless in LMMS is possible) and no VST support (can you even get VSTs in ARM versions?). Other than that, most parts should go through Qt AFAIK, so if you get a working Qt there shouldn't be any huge hurdles.

**Comment by CaBachhav** [comment]
Is it possible that , even though our lmms main code is in C,c++ , it can be wrapped in other devlopment framework like Android development Framework.?

**Comment by PhysSong** [comment]
> it can be wrapped in other devlopment framework like Android development Framework.?

Qt supports Android, but I'm not sure about other dependencies. Android support is *theoretically* possible, but I can't estimate how much efforts do we need to support Android.

**Comment by CaBachhav** [comment]
Plz see this developer

https://medium.com/@shigmas

**Comment by deuteragenie** [comment]
> > several users are demanding that LMMS should come on Raspberry Pi platform too.
> 
> On the Raspberry Pi, it's nothing more than the usual compilation.

The Raspberry Pi is using Open GL (ie not Open GL ES) and is HW accelerated under X.11
Odroid N2 is not HW accelerated and is using Open GL ES.

**Comment by PhysSong** [comment]
> The other issue I guess is how to run LMMS without X11, as there is no driver available for the Odroid N2.

@deuteragenie I'm not sure, but it seems like Ubuntu 18.04 provides [the X11 driver for Mali GPUs](https://packages.ubuntu.com/bionic/mali-t62x-x11-driver).

**Comment by PhysSong** [comment]
@deuteragenie Are you able to run any other Qt-based apps such as OpenOffice/LibreOffice?
