### ISSUE TITLE
Piano Roll Ghost notes

### ISSUE THREAD

**Issue by DoosC** [LMMS/lmms#520]
Background sequences could be very useful in the piano roll view, see for example : http://ariamaestosa.sourceforge.net/docs/background.png

**Comment by badosu** [comment]
@musikBear @tresf @DoosC Can you help me define this feature design?

Apart from the ghost note drawing design, I have some questions:

1. How do we define which patterns will be *ghosted*?
2. In which piano-rolls should the ghost notes appear?

**Comment by musikBear** [comment]
I mailed you a design idea a good week ago .. at least i thought i did :p -Same profile picture.. so i thought ..mm If not his evil twin, then same person :D 
It should be in your *mail-list* inbox?
but it is essential what i wrote here on 8 May 2014: #696 
I now know that there are one snag -All note-events are processed by the engine, also if they have 0 volume (diiz told me) Also setting notes to negative volume (-1) could that be a problem?  -but the design in #696 would also work if the notes are set to 0.
If there is anything unclear or just garbadge, dont hesitate to ping me here

**Comment by Sti2nd** [comment]
1. Could be right click on a pattern i Song Editor and "Choose as ghost reference"
2. Are there several Piano Rolls? Are you doing this as well https://github.com/LMMS/lmms/issues/1438 ?

**Comment by tresf** [comment]
> I mailed you a design idea a good week ago .. at least i thought i did :p -Same profile picture.. so i thought ..mm If not his evil twin, then same person :D 

Don't do this please, use our tracker instead so there's no doubt.

Here's the picture hotlinked above, which I feel is adequate for a visual representation:

![image](https://cloud.githubusercontent.com/assets/6345473/5943691/2ab77b44-a6ef-11e4-91eb-4fd318446935.png)

As far as @badosu's questions about "which notes", I have a hard time envisioning that too.... There's a lot of potential patterns and tracks to choose from, so the enhancement should go as far as to offer HOW this will be selected, not just WHY.  Because if there's no HOW, we can't fix it and we can never close this bug report.

**Comment by DoosC** [comment]
As @Sti2nd suggested, right-clicking on the current piano roll to select a "ghost track" seems fine. An icon with a small ghost right on the piano rool toolbar would be nice too ;) Something like this : :ghost:
Right-clicking either on the piano roll or on the ghost would then bring a hierarchical drop-down menu : level 1 would be the track name as in the song editor, and level 2 would be the clip number for the selected (level 1) track.
For example : 
> :arrow_down_small: **Kick**
        - *Kick 1*
        - *Kick 2*
        - *Kick 3*
        - *Kick 4*
:arrow_forward: **Snare**

Does that sound feasible ?

**Comment by tresf** [comment]
> Does that sound feasible ?

What if the track has multiple patterns?

![image](https://cloud.githubusercontent.com/assets/6345473/5946740/20dcb1ea-a706-11e4-8b20-cf3d8da13e6d.png)

**Comment by DoosC** [comment]
That why I mentionned levels, in this case you would have : 

:arrow_down_small: **Track 1**
        - *Track 1 - 1*
        - *Track 1 - 2*

Level 1 is the track, and level the pattern.

**Comment by Sti2nd** [comment]
> What if the track has multiple different patterns?

What? You can only open one pattern at a time, what makes you think ghost notes would work different? 

> right-clicking on the current piano roll to select a "ghost track"

I meant and wrote right clicking on the pattern (with arrows). 
![image](https://cloud.githubusercontent.com/assets/6373430/5946825/e8c53b64-a738-11e4-90a0-c0f2120bedae.png)

**Comment by Sti2nd** [comment]
Are you suggesting using the pattern at the same time of the one in Piano Roll @DoosC ? 

Like this?
![image](https://cloud.githubusercontent.com/assets/6373430/5946910/84d7c5a8-a739-11e4-96cf-e10ba0a4d4d9.png)
It might be that you most of the time are going to compare patterns at the same time, but I feel it could be even more universal and not so limiting if you could just right click and choose "open as ghost notes in Piano Roll" on a pattern. Also with time you have the problem of choosing between several patterns at the same time interval as the other, as my image show in the first and second bar. 
I think both the simplest and best implementation is to choose a pattern that you can open as ghost notes. It will stay there when you open other Piano Rolls, or until you turn off ghost note mode.

**Comment by DoosC** [comment]
@Sti2nd you are right, it could be much simpler to do it visually.
Procedure : you left click on a pattern = you have it on the piano roll, you right click and choose "open as ghost notes in Piano Roll" and there you are, no need for cluttered drop-down lists.
The main use case is as you said comparing patterns.
Brilliant !

**Comment by badosu** [comment]
@DoosC @Sti2nd This is a nice idea, I thought about something on these lines as well.

Now comes another question, can more than one block be selected to show as ghost notes? I'd vote to have just one for now, and if this feature becomes popular and there's demand to change it, we change it :-).

Also, is this copyright issue with the "Ghost notes" name serious? If it is, we'll have to find another name.

**Comment by Sti2nd** [comment]
> I'd vote to have just one for now

Ok, one is better than none! I don't know about the name. I have found threads about ghost notes for both FL Studio, Ableton and Reaper, so I think it is strange... @musikBear

**Comment by tresf** [comment]
http://en.wikipedia.org/wiki/Ghost_note :+1:

**Comment by badosu** [comment]
@tresf Your link refers to this name in a different context than what we're talking about.

**Comment by tresf** [comment]
> @tresf Your link refers to this name in a different context than what we're talking about.

It bears many similarities to what we are describing though, notably: **dead note, muted note, silenced note or false note**.

The point though is that the term can't really be plagiarized.  Regardless of if it is a good word or not, there shouldn't be an copyright-type-hesitations when using it in the software, right?

**Comment by Sti2nd** [comment]
> there shouldn't be an copyright-type-hesitations when using it in the software, right?

If FL studio had that copyrighted it would probably be that very same feature, and that would be a problem. However I can't imagine that is the case. Lots of software have this.

**Comment by badosu** [comment]
@tresf 
> ...there shouldn't be an copyright-type-hesitations when using it in the software, right?

I really don't know, copyright laws is a infinite headed beast :-(. But if you say that we can do it, let's do!

**Comment by musikBear** [comment]
@Sti2nd sugestion is fine, it is almost how i thought about it, i just omitted the part where the engine takes care of the copy process.
I simply thought about a manual track clone (as we have already) and then on the new clone an option for "make this track into 'ghosts' "
So use *already existing methods* to most of the process
That would only need 
context-item :ghost this trac + method
method 'remove-ghosts' -should be pr block *not* for whole track -and only nessesary because of cpu-load, (because also 0-volume-notes are processed as real note-events)

I will try to look into the web-documentation, and see if image-line actually has any protection on the term, but if lmms used like 
phantoms
glass
follow
-notes
Then no problem

**Comment by musikBear** [comment]
Have search true the online docs for fl-studio. This is where they describe the feature:

*Ghost channels ( Alt+V) - When selected, the Piano roll will show the scores of all channels in the current pattern (they are displayed in the background and have a semi-transparent look). Note that these scores are displayed only as a reference for easier sequencing. Select ghost notes by double Right-clicking to change the selected Channel.* 

So they mentions *ghost-channels* and *ghost-notes* -However non of the words has a marking for copyright or alike, so i dont think theres any protection of either term. However, other 'names' that would be expected to be protected, like 'PoiZone' has no marking either.. idk.. 
I found the text here:
http://www.image-line.com/support/FLHelp/

If i find something il post it here, ofcause

**Comment by tresf** [comment]
Here's an excerpt from a US copyright office flyer that I think helps explain (via [copyright.gov](http://copyright.gov/circs/circ34.pdf)):

> Copyright law does not protect names, titles, or short phrases or expressions. Even if a name, title, or short phrase is novel or distinctive or lends itself to a play on words, it cannot be protected by copyright. The Copyright Office cannot register claims to exclusive rights in brief combinations of words such as:
 * Names of products or services
 * Names of businesses, organizations, or groups (including the names of performing groups)
 * Pseudonyms of individuals (including pen or stage names)
 * Titles of works
 * Catchwords, catchphrases, mottoes, slogans, or short advertising expressions
 * Listings of ingredients, as in recipes, labels, or formulas. When a recipe or formula is accompanied by an explanation or directions, the text directions may be copyrightable, but the recipe or formula itself remains uncopyrightable.

So in this case, we are using a brief combination of words and commercial DAWs cannot make claims of exclusivity because it is a common phrase and existed long before the commercial software was invented.

**Comment by musikBear** [comment]
well i found a contact form, so i just asked them. 
*Hi, could you please tell me, wheater or not the terms
'Ghost-notes'
ao.
'Ghost-channels'
are registraded trademarks, or in other ways protected or own by image-line or affilate owners
- or are they just 'words' :)
Just dont want to start any leagal mess, so thats why we ask you.
tyia
Br. A Jensen*
They have 3-4 days at. on un-registrated user questions
Then we *know*, and there are no traps or sticky paper

**Comment by tresf** [comment]
> well i found a contact form, so i just asked them. 

This is not to be taken personally, but I'd prefer you not to communicate on behalf of the project without discussing first.  the /way/ you *type* msgs smtimes * may not be ideal 'way' 4 our. Proj.

**Comment by tresf** [comment]
Furthermore, now if they come back and say "No, LMMS can't use 'Ghost Notes'", we're in an even worse position when we decide to use the term.

**Comment by musikBear** [comment]
...lmms are **no** where mentioned what so ever (im not a *total* retard :)
I aproached IL as a private citizen of the infinity that is cyberspace
..but imo - a clear yes or no is the best - dont you agree -why speculate and perhaps even get muddy in a seshpool of leagal c***

**Comment by tresf** [comment]
> dont you agree -why speculate and perhaps even get muddy in a seshpool of leagal c***

No, I don't agree.  We should never ask permission.  This same question came up for our use of the word "Native instruments" on our home page (which is more likely to cause controversy than a measly "Ghost Notes").

> I aproached IL as a private citizen of the infinity that is cyberspace

If someone searches your name and email, they'll find you're involved in the project.  Please don't try to make that argument. :smiley_cat:

**Comment by lukas-w** [comment]
Closing this one as duplicate of #4303 because #4303 has a better issue description.

**Comment by CYBERDEViLNL** [comment]
I have something working, will put in a PR one of these days. Still need to clean up some code before putting anything online, then add some more user feedback.

![Ghost notes feature](http://funkyimg.com/i/2KU3n.png)
