### ISSUE TITLE
[Feature Request] Portable Mode

### ISSUE THREAD

**Issue by MrTeeXD** [LMMS/lmms#5201]
Some of us are not lucky enough to have our own PC and thats where this Feature Request comes in. Am example of this Request is OBS Studio. When a .txt file is created at the base of the installation, OBS will immediately go into Portable Mode, meaning all the Settings and important things will be stored in the Installation location such as a External Harddrive which can then be used to move from one PC to another.

**Comment by PhysSong** [comment]
When running LMMS from the build directory, LMMS detects `CMakeCache.txt` and use the value of `lmms_BINARY_DIR` from that file to locate the config file. It should be easy to implement the requested functionality with a similar trick.
The relevant code fragment is in the `ConfigManager` constructor.

**Comment by MrTeeXD** [comment]
I wonder if Samples can also follow this.

**Comment by SeleDreams** [comment]
I'll look into implementing it
