### ISSUE TITLE
Allow sample tracks to go to the mixer

### ISSUE THREAD

**Issue by InVaLiD-github** [LMMS/lmms#5203]
Sample tracks can't go to the mixer, which is a crucial part of my mixing, and it's kinda infuriating that everything else can be assigned a fx track, but sample tracks cannot.

**Comment by softrabbit** [comment]
It's fixed in master, which should mean it will be in 1.3 or whatever number the next major release will be. See #3866.

**Comment by InVaLiD-github** [comment]
XD i'm using rc8 right now and didn't know that was already fixed. thanks for letting me know!

**Comment by SecondFlight** [comment]
Duplicate of #133, fixed in #3866.
