### ISSUE TITLE
Label suggestion : Consolidations

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#5206]
Label suggestion : Consolidations
There is no simple way to find the comprehensive /consolidating topics. I needed to look for weather or not *note-features* had been consolidated, but only *play-head* consolidation appeared in the search. I believe there are several comprehensive topics

**Comment by Spekular** [comment]
We already have a label for meta issues: https://github.com/LMMS/lmms/issues?q=is%3Aopen+is%3Aissue+label%3Ameta

If there's a topic that should have a meta issue but doesn't, please list the IDs of the issues you think should be included. For example, this is issue 5206. Don't add a # sign before, or they'll all have links to this issue, which we don't want.

**Comment by musikBear** [comment]
@specular The label **Meta** does not hold one of the consolidating topic, not a single one

**Comment by Spekular** [comment]
*Every single meta issue* is a consolidation of other issues.

I don't know of these "consolidating topics" you've mentioned. Judging from
#5007 it looks like you've made your own version of a meta-issue? Github
issues that consolidate several others should be tagged with the meta
label. We shouldn't have two separate labels for the same thing.

**Comment by musikBear** [comment]
ok, would you then add meta tag to #5007
