### ISSUE TITLE
Oversampling changes pitch for AFP

### ISSUE THREAD

**Issue by softrabbit** [LMMS/lmms#5218]
See picture, count the waves. 
Upper track: drums in AFP, 1x oversampling
Lower track: the same with 2x oversampling, sounds an octave too low.
![oversampling-broken](https://user-images.githubusercontent.com/6411463/66110718-04eb5280-e5d0-11e9-8475-76b73c1b91b9.png)

LMMS version: 1.2.0 in Windows 8.1 pro / 64 bit. Didn't find any fitting reported issue, and I think I've used oversampling successfully in the past, so this might be a recent bug.

**Comment by softrabbit** [comment]
Checked and it looks like the bug is in master, too. 1.1.90 is OK.

**Comment by PhysSong** [comment]
The bug was introduced in #4991. It seems like `SampleBuffer::m_sampleRate` doesn't update on sample rate changes while the actual data does. I think `update()` or `normalizeSampleRate()` should handle the change.
@Reflexe Any ideas? BTW, it seems like #4994 removes those functions.

**Comment by PhysSong** [comment]
It seems like this bug makes the situation even worse: even changing the sample rate on export breaks stuff. This applies to sample tracks as well...

**Comment by Reflexe** [comment]
I think I will have to cherry pick a few more changes from the recording branch. I don't want to duplicate my work.

**Comment by Reflexe** [comment]
I'm retargeting it for 1.3 as a fix for 1.2.1 has been merged.

**Comment by Reflexe** [comment]
@PhysSong Please comment when you're undoing something.

**Comment by PhysSong** [comment]
Sorry, I was going to sync branches and make this auto-closed.

**Comment by zonkmachine** [comment]
> and make this auto-closed

The short form for auto closing only works on the default branch. I think you could use a longer form looking something like `closes lmms/lmms/#5218`.
