### ISSUE TITLE
Undefined symbol

### ISSUE THREAD

**Issue by quaeched** [LMMS/lmms#5221]
I have built master (that is 1.2.0.539) on OpenBSD 6.5. On launch, plugins cannot be loaded, complaining about undefined symbols, e.g. 

`lmms:/usr/local/lib/lmms/libwatsyn.so: undefined symbol '_ZN6Plugin16staticMetaObjectE'`               
`lmms:/usr/local/lib/lmms/libwatsyn.so: undefined symbol '_ZN6Plugin8loadFileERK7QString'`                  
`lmms:/usr/local/lib/lmms/libwatsyn.so: undefined symbol '_ZN9ModelView13doConnectionsEv'`

A handful of these for individual .so files is followed by 

`Cannot load library /usr/local/lib/lmms/libwatsyn.so: (Cannot load specified object)`

, for example.

[This](https://openports.pl/path/audio/lmms) binary works fine, though.

**Comment by quaeched** [comment]
It is caused by this commit: https://github.com/LMMS/lmms/commit/4fd8e08f3bd02f173e97bb721a30565f17cd1dbc.

**Comment by quaeched** [comment]
Need to add
`SET_TARGET_PROPERTIES(lmms PROPERTIES LINK_FLAGS "${LINK_FLAGS} -Wl,-E")`
on the second to last line in `src/CMakeLists.txt`. 
Closing.

**Comment by PhysSong** [comment]
I'll close once the regression is fixed on the LMMS side.
