### ISSUE TITLE
Automation point adjustment mouse wheel and double click

### ISSUE THREAD

**Issue by tecknixia** [LMMS/lmms#5225]
https://cdn.discordapp.com/attachments/332258319228207114/629248936099708928/AutomationEditor2-2019-10-03_04.21.20.mp4

I have successfully made this usable already, but since I'm new to this, I'm not sure how what I did fits in with everything else, so it can be altered if necessary.  There are also elements of this issue that could use polishing, which are:

1. the values for detecting the point with the mouse on the y axis are hard coded and do not adapt to scaling changes of the y axis

2. when moving the mouse over a point, the value of the tooltip willl reflect the y value of the mouse position, instead of the point's y level, until the mouse wheel moves.  This causes an inaccurate reading of the point level depending on where the cursor is placed on the point, so the value jumps from the cursor y value to the point y level.

Here are instructions to make it work like I had it:

- AutomationEditor.h

// set variable in header
@ line 212 (or wherever appropriate) insert `float m_point_y_level;`

- AutomationEditor.cpp

// initialize variable
@ line 89 insert `m_point_y_level( 0 ),`

// reset variable to zero if mouse moves
@ line 733 (beginning of mouseMoveEvent, after vaid pattern check) insert `m_point_y_level = 0;`

// I originally intended to include a TODO comment for the 2nd point above (optional)
@ line 1102 TODO: when mouse is over a point (ti@me map key), show level of the point on tooltip instead of mouse cursor y position

// the tooltip value is decided, reads the variable that is set when mouse wheel is moved
@ line 1111 (starts with "QToolTip:showText") replace with:

```
        if (m_point_y_level == 0) {
		QToolTip::showText( tt_pos, QString::number( scaledLevel ), this );
	}

	if (m_point_y_level != 0) {
		QToolTip::showText( tt_pos, QString::number( m_point_y_level ), this );
	}

```
// when mouse wheel moves, detects the point on time map and sets
// variable to the point's y level to be read when displaying tool tip
@ line 1721 (within last "else" for wheelEvent after setting value for m_topBottomScroll) insert:

```
if( we->y() > TOP_MARGIN )
{

	float level = getLevel( we->y() );

	int x = we->x();

	if( x >= VALUES_WIDTH )
	{
		
		// set or move value

		x -= VALUES_WIDTH;

		// get tick in which the cursor is posated
		int pos_ticks = x * MidiTime::ticksPerTact() / m_ppt + m_currentPosition;

		// get time map of current pattern
		timeMap & time_map = m_pattern->getTimeMap();

		// will be our iterator in the following loop
		timeMap::iterator it = time_map.begin();

		// and check whether the user scrolls over an
		// existing value
		while( it != time_map.end() )
		{
			if( pos_ticks >= it.key() - MidiTime::ticksPerTact() *4 / m_ppt
			&& ( it+1==time_map.end() ||	pos_ticks <= (it+1).key() )
			&& ( pos_ticks<= it.key() + MidiTime::ticksPerTact() *4 / m_ppt)
			&& (level >= it.value() - 0.05) // substitute numbers with value for y scaling changes
			&& (level <= it.value() + 0.05) // substitute numbers with value for y scaling changes
			)
			{

				// when mouse wheel up
				if( we->delta() < 0 )
				{

					if( pos_ticks < 0 )
					{
						pos_ticks = 0;
					}

					// change level value
					level = it.value() - 0.001;
					m_point_y_level = level;

					// set new value
					m_pattern->setDragValue( MidiTime( pos_ticks ), level, true, false );

					// apply new value
					m_pattern->applyDragValue();

					break;

				}

				// when mouse wheel down
				else if( we->delta() > 0 )
				{
					if( pos_ticks < 0 )
					{
						pos_ticks = 0;
					}

					// change level value
					level = it.value() + 0.001;
					m_point_y_level = level;

					// set new value
					m_pattern->setDragValue( MidiTime( pos_ticks ), level, true, false );

					// apply new value
					m_pattern->applyDragValue();

					break;

				}
			}

			++it;

		}


	}
}
```

**Comment by zonkmachine** [comment]
Cool!

Can you submit this as a pull request instead?
There is info on how to do this in our wiki here:
https://github.com/LMMS/lmms/wiki/Submitting-a-patch

**Comment by tecknixia** [comment]
Sure!  When I get a chance I'll take a closer look at the wiki, maybe do slight refactoring, and create a pull request.

**Comment by stevphie** [comment]
It would be nice if we could add custom values by double clicking the dots like in the velocity tab too, because the cursor movement while inside automation editor a little bit clunky e.g inconsistent value increment while adjusting each point with mouse

**Comment by tecknixia** [comment]
> It would be nice if we could add custom values by double clicking the dots like in the velocity tab too

Oh, I didn't even think of that!  That would be a nice little enhancement as well.

I do think this works quite well though.

Btw, the code I originally posted is now out-of-date, the new code can be found in the pull request #5232  The increments work better now.

I think at some point there might be a way of refactoring the code for the mouse functions, instead of running a check for the mouse being over a point for almost every mouse function, perhaps one check could be run when moving the mouse, which allows special functionality to run during other mouse operations.  Perhaps the quoted suggestion could be integrated at that time.

**Comment by Deauthorized** [comment]
> 
> 
> > It would be nice if we could add custom values by double clicking the dots like in the velocity tab too
> 
> Oh, I didn't even think of that! That would be a nice little enhancement as well.
> 
> I do think this works quite well though.
> 
> Btw, the code I originally posted is now out-of-date, the new code can be found in the pull request #5232 The increments work better now.
> 
> I think at some point there might be a way of refactoring the code for the mouse functions, instead of running a check for the mouse being over a point for almost every mouse function, perhaps one check could be run when moving the mouse, which allows special functionality to run during other mouse operations. Perhaps the quoted suggestion could be integrated at that time.

i pray to god this feature is added for automation tracks as well

**Comment by tecknixia** [comment]
@Deauthorized you mean like this?

Working on it.

![automationPointEdit](https://user-images.githubusercontent.com/50790262/66965667-160c7880-f040-11e9-8e84-50b87128e882.png)

**Comment by stevphie** [comment]
@tecknixia yes... simple but neat

**Comment by IanCaio** [comment]
Closing after merging #5923 .
