### ISSUE TITLE
Peak controller maing clicking noises

### ISSUE THREAD

**Issue by KodzghlyCZ** [LMMS/lmms#5231]
Whenever I add a peak controller to my project, it starts clicking, even when I have the "mute" button pressed, envelope settings didn't help at all, lowpass filter didn't help.

I currently have 1.2.0 version running on Windows 10 64bit with SDL audio output mode.
It happens all over my devices, so I would say, that it's not the soundcard problem.

The volume meter is not at red, nothing is going above 0dB. 

If you have any questions, leave a comment.

**Comment by SecondFlight** [comment]
Could you create a simple test project that shows this issue?

**Comment by PhysSong** [comment]
@KodzghlyCZ Could you please answer the question by @SecondFlight if it's still relevant?

**Comment by KodzghlyCZ** [comment]
I'm sorry, I can't currently make any sample project, but if you just make any project with sidechain and apply it to some kind of bass or whatever, with basically any settings it pops. This was irritating me so much, I purchased Ableton the next day and now the issue is surprisingly gone 😄 
I hope you can solve this issue, my thought on this is, that there is the signal ending on other level, that the other one is beginning. So when the signal goes from let's say 1dB to -6dB instantly, it makes a pop noise.

> @KodzghlyCZ Could you please answer the question by @SecondFlight if it's still relevant?

**Comment by SecondFlight** [comment]
Thank you for the response, @KodzghlyCZ!

This is claimed to have been fixed (see #1281), but that was before 1.2 and whatever fix that was should've made it into 1.2. Spekular seems to confirm this in #2534. I can't test on master right now but this will need some investigation to see if it's still relevant.

A test project or detailed set of steps to reproduce would clear up some ambiguities:
- Which mute button did you press? Did you mute the peak controller effect, the output channel of the sound where the effect was being applied, the effect that the peak controller was controlling, etc?
- Does this happen when you simply add a peak controller, or do you need to link the controller somewhere for it to occur? If you need to link the controller, where did you link it to?
- Where did you put the lowpass?

**Comment by zonkmachine** [comment]
> Spekular seems to confirm this in #2534. I can't test on master right now but this will need some investigation to see if it's still relevant.

Seem to have been fixed. Please reopen this issue if you can still replicate it and provide a project that demonstrate it.
