### ISSUE TITLE
RemoteVstPlugin crashes on loading/saving presets if it fails to open the file

### ISSUE THREAD

**Issue by PhysSong** [LMMS/lmms#5234]
Regression probably introduced in #4401.
Previously, `RemoteVstPlugin` used `read()`/`write()` to read/write data to file. From #4401, it uses `fread()`/`fwrite()` instead. It seems like `read()`/`write()` just fails if the `open()` failed, but `fread()`/`fwrite()` crashes if the corresponding `fopen()` fails and return the null pointer.
I think it shouldn't be difficult to fix this bug.

**Comment by zonkmachine** [comment]
Fixed in https://github.com/LMMS/lmms/pull/5235
