### ISSUE TITLE
Improvement: option to "equalize" notes length

### ISSUE THREAD

**Issue by Minabsapi** [LMMS/lmms#5238]
## Details of the feature
When using sound samples with the Audio File Processor, an option should be displayed somewhere to adapt a sound sample length; that is, regardless of the note played, having always the same sample length.

## How could we make it ?
Though it seems not possible, it is actually doable. Free audio processing softwares (with Audacity in mind) has a functionality allowing to change a sample tune without changing its tempo. And there's even a Python script I found that allows to do the same, so it's not something really hard.
Of course, it is to mention that it is not the best in term of memory. To implement such options means making a recursive keyboard mapping with the tuned sample since the tuning can't be made in real time for obvious performances reason.
Also, I am aware that it is not a miracle solution. When using a tone too high or too low, obviously the sound will look weird. (But it is already the case without the adaptation, so I don't think it's that dramatic. Anyway, we should just warn about it.)
But still, I think it worth it for a good reason I'll explain below.

## How would it be useful ?
I personally tried to make a song using a sampled instrument. Though the notes I used only spread on the same octave, the instrument speedup was horribly noticeable. I browsed LMMS forum to find a solution and the only one I found was to make a soundfont.
2 hours. The time to learn what is it, to find a (free) software that could make it, to create a Python script generating the different tune of the sound I had to map *manually*. 2 wasted hours I don't want anybody to get through again.

**Comment by Spekular** [comment]
Duplicate. Will link issue soon.

**Comment by Spekular** [comment]
#1734, consolidated in #4877. Also mentioned in at least one other issue.

**Comment by Minabsapi** [comment]
My apologies, I didn't see these
