### ISSUE TITLE
Move PeakController out of core

### ISSUE THREAD

**Issue by Reflexe** [LMMS/lmms#5242]
@BaraMGB's https://github.com/LMMS/lmms/pull/2944 got into a problem with that. Therefore, I have implemented a way to load PeakController dynamically from a plugin and completely moved PeakController from the core since core components should not depend on plugins.  

I'll open a PR for that in the next few days. 

closes #2056

**Comment by PhysSong** [comment]
Closing because #2056 is already covering this.
