### ISSUE TITLE
[TEMP][EXPLANATION REQUEST] What is src_process ? Where is it declared ?

### ISSUE THREAD

**Issue by Minabsapi** [LMMS/lmms#5246]
Self-explanatory title, but I'll still add some things.
I am currently reviewing `SampleBuffer.cpp` to add a new functionality. 
I know I need `src_data`, and what interests me is how it is processed (pitched).
Problem is: I know the processing is made with the `src_process` method, but I don't know where it is even declared, as well as the `SRC_DATA` type.
Could anybody point me to its origin ?

https://github.com/LMMS/lmms/blob/2d17bf07f3e575a1a5a5da00df57a01d0956cf3d/src/core/SampleBuffer.cpp#L690

**Comment by JohannesLorenz** [comment]
`/usr/include/samplerate.h` from [libsamplerate](https://github.com/erikd/libsamplerate)

Does this solve the issue already?

**Comment by zonkmachine** [comment]
@Minabsapi This question looks like it's been answered already. Closing.
