### ISSUE TITLE
VersionInfo: Not tagged refs should be resolved better

### ISSUE THREAD

**Issue by Reflexe** [LMMS/lmms#5250]
Currently, for non-tagged commits, use parse version information from `--match v[0-9].[0-9].[0-9]*`. 

That does no help a lot with non-tagged commit since it results something like `v1.2.0-14`. We should at least include the commit hash in the version info and the log and maybe also use `dev` for the `rc` field.

**Comment by PhysSong** [comment]
> We should at least include the commit hash in the version info

It seems like we used to do it until #3011.

**Comment by PhysSong** [comment]
Done in #5636.
