### ISSUE TITLE
File Format Export Inconsistency

### ISSUE THREAD

**Issue by BluuDreamz** [LMMS/lmms#5265]
Say the user wants to export their project as mp3.
However - they leave the initial file type as .wav within this explorer.

![Annotation 2019-10-21 113554](https://user-images.githubusercontent.com/39863151/67219969-f33ee300-f3f6-11e9-9e3e-70e7a9132356.png)

Then, on the final export window, the user selects mp3 as desired - then renders their project.

![image](https://user-images.githubusercontent.com/39863151/67220612-19b14e00-f3f8-11e9-933a-ed73900b61d7.png)

Boom.

![image](https://user-images.githubusercontent.com/39863151/67220670-3483c280-f3f8-11e9-9df8-2fdc2dff0c60.png)

The only way around this issue, is selecting the desired file type right from the start on the directory explorer window.

The initial window's selected file type overrides the final window's File Format export option.

OS: Windows 10 (64bit)
LMMS version: 1.2.0

**Comment by allejok96** [comment]
Discussion continued in #5744
