### ISSUE TITLE
Recorded MIDI notes sometimes start being placed incorrectly

### ISSUE THREAD

**Issue by Tromino** [LMMS/lmms#5270]
While recording notes in the piano roll using the keyboard, the notes being recorded will occasionally start being placed in the wrong positions (seemingly to where the note would've been placed the last time it was pressed). This seems to be able to be triggered consistently by stopping the recording using the spacebar while a note is being held, though I'm not sure if that's the only way to trigger it. It also doesn't seem to happen when using one of the stop buttons in the UI (where the note being held gets inserted immediately).

**Comment by PhysSong** [comment]
@Tromino Could you please provide some more details? Like:
- LMMS version
- Screenshot of expected vs. actual result

**Comment by Tromino** [comment]
No. Goodbye.

**Comment by SecondFlight** [comment]
If you don't provide information, we can't diagnose anything. Best of luck with your issue.

**Comment by Tromino** [comment]
I'm sorry that you're mentally disabled. Your software is dead and you know that. Give up.

**Comment by zonkmachine** [comment]
> I'm sorry that you're mentally disabled.

@Tromino Cut back on the insults.
