### ISSUE TITLE
Everything is unusally blurry in windows 10 (1920x1080)

### ISSUE THREAD

**Issue by EJTH** [LMMS/lmms#5273]
I know there is lots of closed issues regarding scaling etc. on windows, but it is still a problem.

It can be mitigated very easily by overriding DPI scaling behavior for application.
![image](https://user-images.githubusercontent.com/4135908/67591899-c3793d80-f75e-11e9-8bf1-9938d0a6020e.png)

I will just mention it here so others have an easier time finding the solution. Feel free to close it again.

**Comment by SecondFlight** [comment]
Related: #2510

**Comment by tresf** [comment]
@EJTH LMMS on Windows ships with a very dated version of Qt.  We're working to upgrade it in hopes to disable this compatibility flag.  Please subscribe to #2510 to receive progress on that.
