### ISSUE TITLE
Replace macros by delegating ctors

### ISSUE THREAD

**Issue by JohannesLorenz** [LMMS/lmms#5278]
Use delegating constructors instead of macros. For beginners, but requires C++11 knowledge.

Start your PR by branching from `stable-1.2`. Fix the following comments:

```
src/gui/widgets/LedCheckbox.cpp://! @todo: in C++11, we can use delegating ctors
src/gui/widgets/Knob.cpp://! @todo: in C++11, we can use delegating ctors
src/gui/widgets/LcdWidget.cpp://! @todo: in C++11, we can use delegating ctors
```

**Comment by knittl** [comment]
I've created a pull request to replace the macros with delegating constructors: https://github.com/LMMS/lmms/pull/5279

**Comment by JohannesLorenz** [comment]
Thanks for the PR :+1:
