### ISSUE TITLE
New Project opens with old paramters 

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#528]
valid for loop-indicator-state & windows-states
Significance :Low

loop-indicators
In Song-editor & piano-roll:
A 'New Project' will have the loop-indicators in the same posistions, and state as the last saved project. It is more intuitive if 'New Project'loop-indicators are in the first beat, and off.

Windows-states
'New Project' open with the same windows-states as the last saved project. For instance -if all windows was closed, the 'New Project' has an empty GUI.

(cheked Main tempo, time-sign, master-vol & master-pitch -all are correctly set to default values)

**Comment by Umcaruje** [comment]
Confirmed on lmms 1.1.3 on Ubuntu 15.04 x64.

**Comment by waxspin** [comment]
@musikBear Is this still an issue for you?  I am unable to reproduce it in master currently.

**Comment by musikBear** [comment]
@waxspin 
Its the same for Master of 14. Juli (last binary i have of x32) -But currently the windows size bug, overtake the windows behavior.
But for loopmarkers position and windows being 'up' -there is no difference.
But - 
This should be (as already said) regarded **LOW priority**. There is no reason to address this for any coders, as long as there is real bugs and features to be added to 1.2
**Just forget about this, for now :)**

**Comment by waxspin** [comment]
Thanks!  I'll take a look at the other two you mentioned.

**Comment by waxspin** [comment]
@musikBear I looked at 446, but it appears to be closed.  Is this in error?

**Comment by musikBear** [comment]
@waxspin it has been merged to 1523, but if you can make the 446 feature in current Master, i would say go for it :)

**Comment by waxspin** [comment]
@musikBear Ah just saw the duplicate ticket-- thanks!  I will look into this over the next day or two when I have time.
