### ISSUE TITLE
AppImage doesn't work when the filename contains spaces

### ISSUE THREAD

**Issue by PhysSong** [LMMS/lmms#5284]
Reported by `@tatan#6472` on Discord.
![appimagespaces](https://user-images.githubusercontent.com/12591074/67725102-8219b400-fa24-11e9-8922-ab9169569aef.png)
It seems like AppImage mounts its contents to a directory with spaces in this case. However, our `AppRun` doesn't handle this properly:
https://github.com/LMMS/lmms/blob/5e4e536bf0dad4dfa28e8b51b305638fefaee468/cmake/linux/package_linux.sh.in#L124
I think `$DIR` should be quoted here and in some more places.

**Comment by Reflexe** [comment]
I think we should extract that into another file in order to avoid similar bugs and let shellcheck detect them.

**Comment by PhysSong** [comment]
> extract that into another file

Sounds good to me. Any objections?

**Comment by PhysSong** [comment]
Fixed via #5297.
