### ISSUE TITLE
Menu entry "remove all linked controllers" is bad wording

### ISSUE THREAD

**Issue by JohannesLorenz** [LMMS/lmms#5285]
It's bad because:

* you don't remove the controller, but the connection
* UI elements (like knobs) can also be linked to other UI elements (ctrl + drag-drop from one knob to another) instead of only to controllers.

Proposals:
1. remove all connections
2. remove all controller and model connections (does a user know what a model is? is the text too long?)

What shall we use?

**Comment by Spekular** [comment]
For what it's worth, Serum calls its equivalent "Remove all modulators".

Alt proposals:

- Remove all links
- Disconnect all / Unlink all
  - Disconnect from all / Unlink from all

I think your secons proposal is too long and "model" is a concept that the user shouldn't have to care about. After that I don't have much of a strong preference. Link/linked saves a few characters over connection/connected and is maybe less ambiguous, although the second point is minor and probably varies from person to person.

**Comment by Veratil** [comment]
If we remove connections... `Disconnect all controllers`

**Comment by JohannesLorenz** [comment]
> "Remove all modulators".

Sounds good, though it still sounds like removing the modulators

> "Disconnect all controllers"

Like mentioned above, connections don't always go to controllers.

So I'd be for "Disconnect everything". If no one disagrees within a few days, I'll open a PR.

Can such a PR go to stable-1.2? I ask because this will invalidate any translations... Not so good for a stable release? On the other hand, it's a bug fix...

**Comment by PhysSong** [comment]
> Disconnect everything

I disagree because users may think it disconnects automation patterns.

**Comment by Spekular** [comment]
Oh, so it dosconnects everything except automation tracks? That's hard to convey concisely.

What about something like "unlink controllers/knobs" then?

Length comparison of a few variants. I'm partial to the first:

"unlink controllers/knobs"
"unlink controllers & knobs"
"unlink controllers and knobs"
"remove all linked controllers"

**Comment by JohannesLorenz** [comment]
I just tested what PhysSong said, it's indeed correct.

> "unlink controllers/knobs"
> "unlink controllers & knobs"
> "unlink controllers and knobs"

It's not just knobs. Can be LEDs, LCD widgets, whatever. That's why I proposed models, but I agree that no one understands that. Maybe "widgets"?

> "remove all linked controllers"

That's the current wording, with the issues mentioned in the 1st post.

Another idea: "Disconnect all except automation".

**Comment by Spekular** [comment]
> That's the current wording

Yes, I put it there as a reference for the current length of the string.

Would it be fair to consider LEDs, and spinboxes controls? Not in an MVC sense, but from a user perspective. "Unlink controllers and controls" doesn't sound great but might convey what it means.

However, I've been thinking:
- I was completely unaware that arbitrary controls could be dragged onto

**Comment by Spekular** [comment]
Hit the wrong button, again. I've edited my comment above to what it ahould have been.

**Comment by JohannesLorenz** [comment]
I'm against introducing new vocabulary like "driver", but I like the idea of your removed post to name them "controls". "Disconnect all controllers and controls" sounds good to me. Or "Disconnect all modulators" like in Serum.

**Comment by Spekular** [comment]
Well, it's not exactly "new" vocabulary, although I guess it depends on
which scope you're considering.

https://docs.blender.org/manual/en/latest/animation/drivers/index.html

The concept is pretty similar, for example:

"Control a property with an object’s transform. In this example, the Y
rotation of Object 2 will be driven by the X position of Object 1."

This seems quite similar to connecting models imo, and the term "driver"
would be future proof in case the functionality were expanded upon.

**Comment by JohannesLorenz** [comment]
I was so wrong. This comes from a German translation:

```
    <source>Remove all linked controls</source>
    <translation>Alle verknuepften Controller entfernen</translation>
```

You don't need to be a German expert to understand what they translated wrong.

I still don't like "Remove", but don't see it as critical. I'm fine with a transifex fix for the German translation.

**Comment by JohannesLorenz** [comment]
Solved in transifex.
