### ISSUE TITLE
Drop Qt4 from Wiki

### ISSUE THREAD

**Issue by lukas-w** [LMMS/lmms#5289]
Any objections to dropping all Qt4 related instructions from the wiki? Qt5 was released seven years ago, both `master` and `stable-1.2` support Qt5. I don't really see a point in continuing support for Qt4.

**Comment by PhysSong** [comment]
`stable-1.2` still supports Qt4, though using it is not recommended. Since `master` stopped supporting Qt4, I think it's okay to drop Qt4-related instructions from our wiki.

**Comment by lukas-w** [comment]
:+1: I'll go ahead and remove it then.

**Comment by lukas-w** [comment]
Maybe we should think more about what this means for `stable-1.2` first: I'd suggest we make `WANT_QT5` default and keep a section in the wiki that tells you how to turn it off if you wish to use Qt4 instead. Sounds fine?

**Comment by piece-o-ham** [comment]
The compiling page says "Qt 5.6+ is required on the master branch", so does that mean this should be closed? Is this referring to a different wiki?

**Comment by lukas-w** [comment]
Yeah this was done by @tresf, see https://github.com/LMMS/lmms/pull/5294#issuecomment-569522876. Closing
