### ISSUE TITLE
Select/mark notes from piano-roll-key-context menu

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#529]
A simple yet powerfull way to get all (especially bass) notes in a piano-roll container marked for further use.
The user rightclick a key in pianoroll, and get a new menu-item "Select all notes on this key"
This should be possible n times, and selected notes should remain selected. The user can now copy this extract of notes to a different instrument -for instance an effect bass. This would be much simpler, than doing several drag-ctrl+sh selections over many bars.

**Comment by waxspin** [comment]
@musikBear This is almost complete now, just wondering if upon selecting the notes associated with a given key, whether we would want to deselect any other selected keys at the time.  My thinking is yes, but what is your opinion?

**Comment by waxspin** [comment]
Actually, now that I think about it, it might be useful to have multiple keys' notes selectable, since one can always just wipe any selection by e.g. clicking somewhere in the grid of the piano roll editor.

**Comment by waxspin** [comment]
Complete, and included in #2351

**Comment by musikBear** [comment]
> Actually, now that I think about it, it might be useful to have multiple keys' notes selectable, since one can always just wipe any selection by e.g. clicking somewhere in the grid of the piano roll editor.

Yes, exactly! Multiple selections is much more valuable :+1: 
I looking forward to see and use this. Good job ! :100:

**Comment by waxspin** [comment]
Thanks!  I'm hoping to have more time to add more features and bug fixes
now, so I'm going to try to contribute more soon.

**Comment by waxspin** [comment]
@musikBear Would you prefer a 32-bit or 64-bit windows build to test this addition, as discussed in the comment thread on #2351.  I am going to attempt to build that for you to take a look at tonight or tomorrow if possible.

**Comment by tresf** [comment]
@waxspin he's on XP 32-bit still.  He definitely needs 32-bit.  He does a lot of testing for us and despite our lobbying against it, he's still on 32-bit Windows XP. :laughing:

**Comment by waxspin** [comment]
:smile: I will build 32-bit then, thanks!

**Comment by waxspin** [comment]
@musikBear @tresf Please find the win32 test build for this issue [here](https://github.com/waxspin/lmms/releases/tag/p2351-waxspin-master-win32).

**Comment by musikBear** [comment]
:) that answers my Q on 2351 - just ignore the comment.
I will dl and test on xp later today :+1:

**Comment by waxspin** [comment]
Sounds good, thanks!

**Comment by musikBear** [comment]
@waxspin I have problems with your lmms-p2351-waxspin-master-win32.exe release.
The tempo is at least a factor +7 to slow (even at highest possible bmp 999 it is slow - i actually guess a factor 10!) 
This is also true for a new! project. So it is not only old projects that has this tempo /pitch problem
Remember! This could be totally unrelated to your work. It depends on what state Master was in, when you made your 'fetch' operation. 
I often use UNFA spoken as my proove-of-concept, when i test a new version. I cant load 'spoken'. LMMS crash at 84% loading every time.
The mark-note feature works perfectly. :+1:

**Comment by tresf** [comment]
@musikBear thanks for testing although this build has nothing to do with tempo, so the problem you are describing is only relevant to the master branch, and not specific to this pull request.

> Your mark-all-notes works perfect 

That's the feedback we need.  I assume there is no problem with implementation? Do you use chord marking or mark notes frequently?  Can you elaborate a bit on what "works perfect" is from a testing perspective, so we can merge this change?

**Comment by musikBear** [comment]
> Do you use chord marking or mark notes frequently?

@waxspin 's new method marks notes *horizontally* in piano-roll (just as i suggested in the orr. post) That part is implemented as a new context-menu item on all keys in piano-roll, and: 
both the marking of all notes on one key, and adding all notes on a new key to the first selection, works correct.
(this will allow a user to very simple selecting all notes in one voice and use the selection in a different instrument, f.i. all the bass-notes of a 5 layer chord structure)
Good work @waxspin

**Comment by waxspin** [comment]
@musikBear Thanks! Glad it worked well for you, thanks for testing it!
