### ISSUE TITLE
convert mmp into mmpz

### ISSUE THREAD

**Issue by quatran** [LMMS/lmms#5290]
What is the  command to compress a *.mmp file into a *.mmpz file?

Basically I'm looking for the opposite of ` lmms -d inputfile.mmpz > output.mmp`.

**Comment by AndiEcker** [comment]
There is an old python project at github (
https://github.com/AndiEcker/LmmsPrjMngr) that allows to convert mmpz to
mmp and visa versa.

The command line options -u converts mmpz to mmp and -c from mmp to mmpz. I
coded it 7 years ago and not touched it since then ... hope it still works
and helps.

If you have any problems let me know.

Am Mi., 30. Okt. 2019 um 18:20 Uhr schrieb Quang Tran <
notifications@github.com>:

**Comment by zonkmachine** [comment]
> Basically I'm looking for the opposite of ` lmms -d inputfile.mmpz > output.mmp`.

That I don't think we have. I'm pretty sure it's an easy task to implement it though and I guess it would be consistent with the `--dump` argument. Do you have an example of when this would be needed?
Example: `lmms --compress inputfile.mmp > output.mmpz`

**Comment by quatran** [comment]
@AndiEcker 
Your project looks interesting but have'nt tried it out yet.  I will provide feedback then.

@zonkmachine 
> Do you have an example of when this would be needed?
Example: lmms --compress inputfile.mmp > output.mmpz

My use case would be writing an application that do some stuff with the project files and then finally convert them back.

**Comment by olivia8090** [comment]
Make Real Money That,s Real Job Not Fack

like Andrew responded I'm in shock that people able to profit $4494 in four weeks on the internet .my Aunt Kyler George got a very nice BMW X 3 S just by some part-time working online with a computer. take a look at the site here
:) AND GOOD LUCK.:)

HERE →→→→→ www.securework99.com

**Comment by bahaokten** [comment]
Hi, I am a new to LMMS
This issue seems like a good first issue for a newcomer, so if it is still open, I can work on it.

**Comment by rdrpenguin04** [comment]
Wow, I was actually kinda looking for something like this without realizing it! I'm writing a converter from SDAT to MMP, so this would be a nice final step. I was thinking of implementing this, but it seems it has a PR already.

**Comment by zonkmachine** [comment]
Fixed in https://github.com/LMMS/lmms/pull/5341
