### ISSUE TITLE
Different hotkey for pause and stop

### ISSUE THREAD

**Issue by MrcSnm** [LMMS/lmms#5301]
When playing on piano roll, there is an option on the tool bar to stop the current playing and to pause it.

The difference between them is that stop will go back to the 0:00 position, while pause will maintain the current track position, what I want is to correct a bug that Stop and Pause button have the same hotkey (Spacebar), and that is boring me to death, I don't want to be going back to 0 every time I press this key.

What I recommend is having Spacebar for Pause and Shift+Spacebar for Stop, I would program this myself, but I really don't know where is the controller for that.

There is a screenshot I made showing that the hotkey are the same for these two options

![Error](https://user-images.githubusercontent.com/10136262/68080804-8c9bcb00-fde1-11e9-8be5-bf8da960213c.png)

**Comment by tjrdnjs1609** [comment]
i try to solve this problem. but i couldn't find 'pause' in SongEditor.cpp .  anyone who explain about how to add or change 'pause' shotcut???

**Comment by zonkmachine** [comment]
Have a look at [`void SongEditorWindow::play()`](https://github.com/LMMS/lmms/blob/a9e3e70ae3d28e7aa846904edae71863a9734a71/src/gui/editors/SongEditor.cpp#L1045:L1056)

**Comment by MrcSnm** [comment]
Please remember that this problem persists on piano roll, song editor and much probably in beat editor

**Comment by musikBear** [comment]
#728 orr. post

**Comment by tjrdnjs1609** [comment]
#musikBear

> #728 orr. post ..and _from_ 2014...!
Thanks for the good info. but i think same shortcut is still problem. 

Does it make sense if I solve this problem?

**Comment by MrcSnm** [comment]
Absolutely

> #musikBear
> 
> > #728 orr. post ..and _from_ 2014...!
> > Thanks for the good info. but i think same shortcut is still problem.
> 
> Does it make sense if I solve this problem?

Absolutely, having this bug on pause/stop really breaks the workflow

**Comment by zonkmachine** [comment]
> Does it make sense if I solve this problem?

As you have volunteered to fix this and have a PR open I have assigned you to this issue.

**Comment by russiankumar** [comment]
Hey, is this being worked on? The PR seems inactive and I'd be glad to work on this if I am allowed to.

**Comment by DomClark** [comment]
Fixed in #5554.
