### ISSUE TITLE
deleting an element with the backspace key

### ISSUE THREAD

**Issue by Holaff** [LMMS/lmms#5303]
Hi,

Deleting an element in a track of the song editor can be done with a middle-click. Having no middle buttons on their mouses, macOS users have to do ctrl+shift+click which is a little bit heavy for simply deleting an element. One intuitive option could be to be able to delete an element with the backspace key once it is selected.

**Comment by zonkmachine** [comment]
@Holaff Some improvements were made for macOS already via https://github.com/LMMS/lmms/pull/4851
@tresf You're the Mac guy. I believe the request here is to change [this line](https://github.com/LMMS/lmms/blob/9efb6f9a8ee63490d6706d36a8dbdcfabb946558/src/gui/editors/SongEditor.cpp#L507) from
`else if( ke->key() == Qt::Key_Delete )`
to
`else if( ke->key() == Qt::Key_Delete || ke->key() == Qt::Key_Backspace )`

**Comment by tresf** [comment]
I'm fine testing/approving the PR, but I won't be coding this feature myself anytime soon, so if someone issues the PR, I can step in and help.  Note, although a Mac is needed for final testing, the backspace key can be coded and tested on any platform.  This is only macOS by utility, not by environment, not by compiler, not by any other means.

**Comment by zonkmachine** [comment]
> Note, although a Mac is needed for final testing, the backspace key can be coded and tested on any platform.

Quite. https://github.com/LMMS/lmms/pull/5497
