### ISSUE TITLE
More specific beat markers.

### ISSUE THREAD

**Issue by jombenedict** [LMMS/lmms#5305]
The markers in the song editor are not very specific. If when you zoomed in it got more specific (showing more and more beat markers [a la 1/8, 1/16...], as you zoom). That would be much appreciated with the new recording function in 1.3.

**Comment by DomClark** [comment]
Is this addressed by #4973?

**Comment by PhysSong** [comment]
@jombenedict I don't clearly get what you mean. Do you mean the grid, or something else?
