### ISSUE TITLE
Old version of LMMS on Fedora repo

### ISSUE THREAD

**Issue by Eliyanan** [LMMS/lmms#5317]
Hello there, I found the available LMMS software version found on fedora repo is 1.1.3 but the current stable version is 1.2.1 so please can you update it on fedora repo, thanks.

**Comment by zonkmachine** [comment]
We don't administer any of the linux distributions. You need to bring this up with the Fedora people. I recommend using the AppImage though.

**Comment by zonkmachine** [comment]
Here is the Fedora bug report: https://bugzilla.redhat.com/show_bug.cgi?id=1678586
