### ISSUE TITLE
IRC topic is outdated

### ISSUE THREAD

**Issue by trebmuh** [LMMS/lmms#5318]
Hi.

Just mentionning here that the #lmms IRC channel's topic is currently set to: 

> LMMS (https://lmms.io) Need help? Don't ask to ask: Just ask! Please be patient, we'll get to your question eventually. LMMS 1.1.3 is out! Try it at https://lmms.io/download/

It'd be great to update it.

**Comment by tresf** [comment]
Thanks.  Unfortunately, our IRC administrators aren't active any longer and it's taken freenode a very (very) long time to approve any access change requests.

I tried changing the subject just now and got access denied.  Here's the latest conversation with Freenode:

> > **Sept 2018** [Tres, is] listed as the group contact for that channel, so we can make access list changes on request

> **Sept 2018** Per my email May 2nd, at a minimum I would like myself (`tresf`), `umcaruje` and `lukas-w` to have access to administer the #lmms channel.

> **November 2019** Can you please make this change now that it has been requested (several times on Facebook, several times via Email?)

**Comment by trebmuh** [comment]
A few years ago, I had to take back ownership of a freenode IRC channel. It took times until I went to the ##freenode channel. Then a freenode moderator/admin asked me to proove that I had access to the website (putting a bunch of chosen characters in the footer of the website mainpage) which I did and bim! I got admin rights on it.

**Comment by tresf** [comment]
@trebmuh thanks, they helped.  Updated.  Also, I've made you a channel administrators so you can help out.

**Comment by trebmuh** [comment]
Nice @tresf . That beeing said, I've just tried and I'm not a real channel administrator. Meaning that you made me admin for the session, but after deconnecting, I can't get back to being a channel admin.

**Comment by tresf** [comment]
@trebmuh same here.  Ugh.  Ok, I'll try to fix it later.

**Comment by trebmuh** [comment]
@tresf I can see you're listed as admin (`/msg ChanServ ACCESS #lmms list)` so you probably can login yourself as an admin by using `/msg chanserv op #lmms tresf`.

**Comment by tresf** [comment]
```js
/msg chanserv op #lmms tresf
```

Hmm... that still only sets it until I leave.  Is there a way to make this more permanent?  I've read the IRC cheatsheets, but I can't figure it out.

**Comment by tresf** [comment]
Ok, `#freenode` channel had to help... I'll summarize our conversation... 

> it is important to note that **different networks operate in different ways** [...] general guides are fine for getting started, but you need to reference what is available on each network you connect to
> * reference `/msg chanserv help flags` to see what each of them do
> * **the flag `+o`** allows someone to manually op-up, via `/msg chanserv op`
> * **the flag `+O`** will make chanserv automatically op them upon entry to the channel

So this is what I've done... 

```js
// Auto-Op + Op
/msg chanserv flags #lmms tresf +Oo
/msg chanserv flags #lmms trebmuh +Oo
```

**Comment by trebmuh** [comment]
Just tried to log out / log in, and Chanserv got me op automatically. Nice job @tresf :+1:
