### ISSUE TITLE
Prevent dragging song editor up under toolbar.

### ISSUE THREAD

**Issue by pigwink** [LMMS/lmms#5322]
I'm on Ubuntu Studio 19.10.
It is possible to drag the song editor, and other windows, upwards under the toolbar, making the top bar invisible and impossible to drag back or move again. A restart of LMMS resets the window position.

LMMS version used: 1.2.1

https://youtu.be/ECHIviNURhc

**Comment by Spekular** [comment]
A scrollbar should show up at the far right of the LMMS window when you do this, allowing you to scroll up. You can drag windows off to the left/right and below the viewport as well.

**Comment by pigwink** [comment]
OK, you're right. I had the window maximized over dual screens and missed that. Thank you.

**Comment by DomClark** [comment]
Is there a way we can make this more obvious? This comes up quite often in support on Discord, and I've seen it reported on this tracker before as well (most recently #5219 - see the original edit).
