### ISSUE TITLE
Genny and YM2612 VSTs have no GUI

### ISSUE THREAD

**Issue by rdrpenguin04** [LMMS/lmms#5323]
### Bug Summary
Some VSTs (in particular, Genny and YM2612) will not display a GUI.

#### Steps to reproduce
1. Download Genny
2. Add VeSTige instrument
3. Open Genny.dll (or Genny_x64.dll, identical behavior)

#### Expected behavior
A GUI should show up

#### Actual behavior
No such GUI shows up

#### Screenshot
![image](https://user-images.githubusercontent.com/14253380/68983173-6a398280-07cf-11ea-84b8-dc28b08dc8f3.png)

#### LMMS version used
LMMS v1.2.0.527 on Linux Mint, built from master branch... a while ago. Will update and see if anything changes.

#### Logs
<details>
  <summary>Click to expand</summary>
<pre>
rdrpenguin@rdrpenguin-Mint-2018:~/lmms/projects$ lmms
qt5ct: using qt5ct plugin
qt5ct: palette support is disabled
qt5ct: custom style sheet is disabled
VST sync support disabled in your configuration
000f:err:service:process_send_command receiving command result timed out
000f:fixme:service:scmdatabase_autostart_services Auto-start service L"WineBus" failed to start: 1053
Starting using X11Embed protocol.
RemotePluginClient::shmget: No such file or directory
RemoteVstPlugin.cpp::shmget: No such file or directory
RemoteVstPlugin.cpp: Failed to initialize shared memory for VST synchronization.
 (VST-host synchronization will be disabled)
0009:fixme:ntdll:EtwEventRegister ({5eec90ab-c022-44b2-a5dd-fd716a222a15}, 0x3f27f0, 0x400030, 0x400048) stub.
0009:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 0x3f2560, 43) stub
unique ID: GENY
RemotePlugin::DebugMessage: inputs: 0  output: 2
RemotePlugin::DebugMessage: creating editor
0009:fixme:d2d:d2d_factory_init Ignoring factory type 0x1.
RemotePlugin::DebugMessage: editor successfully created
QObject::connect: Cannot connect (null)::subWindowActivated( QMdiSubWindow* ) to SubWindow::focusChanged( QMdiSubWindow* )
0009:fixme:win:EnumDisplayDevicesW ((null),0,0x33efb4,0x00000000), stub!
0009:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset scale factor detection failed, using fallback value 2^23.
0009:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset scale factor detection failed, using fallback value 2^23.
0009:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset scale factor detection failed, using fallback value 2^23.
0009:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset scale factor detection failed, using fallback value 2^23.
0009:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset scale factor detection failed, using fallback value 2^23.
0009:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset scale factor detection failed, using fallback value 2^23.
0009:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset scale factor detection failed, using fallback value 2^23.
0009:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset scale factor detection failed, using fallback value 2^23.
0009:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset scale factor detection failed, using fallback value 2^23.
0009:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset scale factor detection failed, using fallback value 2^23.
0009:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset scale factor detection failed, using fallback value 2^23.
0009:fixme:dxgi:DXGID3D10CreateDevice Ignoring flags 0x20.
0009:fixme:winediag:wined3d_select_feature_level None of the requested D3D feature levels is supported on this GPU with the current shader backend.
0009:fixme:dwrite:get_name_record_codepage encoding 20 not handled, platform 1.
0009:fixme:dwrite:get_name_record_codepage encoding 20 not handled, platform 1.
0009:fixme:ntdll:EtwEventUnregister (deadbeef) stub.
rdrpenguin@rdrpenguin-Mint-2018:~/lmms/projects$
</pre>
</details>

#### Additional notes
I noticed several errors from WineD3D saying that some things aren't supported on my GPU. I recognize that my GPU is very, very old. Is there a way to tell Wine from LMMS to use software rendering, since VSTs are not usually something that are very graphics-heavy?

Also, this post was edited because I botched formatting the first time. Sorry about that.

**Comment by DomClark** [comment]
Can't reproduce on Windows 10. This might be a Wine or system thing - can a Linux person take a look? (For what it's worth, these plugins don't exit cleanly but crash instead, but I expect that's unrelated.)

**Comment by rdrpenguin04** [comment]
This is definitely a Wine-related issue, probably a graphics issue in particular. I'm seeing if there's a potential way to make it not affect users as much.

**Comment by zonkmachine** [comment]
I get a gui with YM2612 on LinuxMint 17.3
Version 1.2.1 (Linux/x86_64, Qt 5.9.7, GCC 4.8.4)
wine-1.6.2

**Comment by rdrpenguin04** [comment]
Like I say, it could very well be a graphics card issue. Can somebody try
getting GUIs with maybe drivers uninstalled or something other setting
changed?

**Comment by GingkathFox** [comment]
@rdrpenguin04 i have a mint boot, ill get Genny and test tomorrow.

**Comment by rdrpenguin04** [comment]
In fact, running LMMS with LIBGL_ALWAYS_SOFTWARE=1 made Genny work. Now, is there a way to make LMMS enable that by default?

**Comment by GingkathFox** [comment]
is there a setting for that in the `.lmmsrc`?

**Comment by rdrpenguin04** [comment]
Is there documentation somewhere on that? I'm not sure.

**Comment by PhysSong** [comment]
> is there a setting for that in the `.lmmsrc`?

It's the `.lmmsrc.xml` in your home directory, a hidden file that stores LMMS settings. And no, it doesn't have any entries for `LIBGL_ALWAYS_SOFTWARE`.

**Comment by PhysSong** [comment]
Anyway, it's better to have a troubleshooting guide or a programmatic way to work around this kind of issue.

**Comment by rdrpenguin04** [comment]
Could I suggest a feature for LIBGL_ALWAYS_SOFTWARE being added? That could be a good workaround for anyone else having similar problems.

**Comment by rdrpenguin04** [comment]
Of course, some setting would be nice, and that setting could probably be pretty easily passed to wine depending on how it's being invoked.

**Comment by tresf** [comment]
Launch settings generally need to happen before LMMS is launched (global environmental variable, `lmms.desktop` file, or custom `AppRun` script).  Since VSTs run in a remote process, it's reasonable to suggest LMMS should be setting this, but it's not our bug, so I'd argue that these permanent workarounds belong in the 

> Anyway, it's better to have a troubleshooting guide or a programmatic way to work around this kind of issue.

Agreed.  Added here: https://github.com/LMMS/lmms/wiki/Troubleshooting#linux

This tutorial can probably be improved as it doesn't explain how to permanently set an environmental variable.  Improvements are welcome.
