### ISSUE TITLE
Improve accessibility in "Instrument Plugins"-panel

### ISSUE THREAD

**Issue by ahstro** [LMMS/lmms#5325]
#### Bug Summary
It's hard to navigate the "Instrument Plugins"-panel because hovering on an instrument triggers an animated size change, displacing the other instruments.

#### Steps to reproduce
1. Open the "Instrument Plugins"-panel
2. Hover over an instrument
3. Try to move pointer to an instrument below the currently hovered one

#### Expected behavior
I don't know what the best solution would be here. Maybe add a little caret and only show the extra information when clicking the instrument name?

#### Actual behavior
Instruments below the currently hovered one change places, making them hard to aim for.

#### Screenshot
![hover](https://user-images.githubusercontent.com/3090888/68998721-7d734d80-08b6-11ea-9fb8-ced5316aef22.png)

#### LMMS version used
`1.2.1`

**Comment by CYBERDEViLNL** [comment]
This is fixed in master, only a tooltip is shown with info on hover.

**Comment by Spekular** [comment]
#3773
