### ISSUE TITLE
Building from a source 

### ISSUE THREAD

**Issue by Eliyanan** [LMMS/lmms#5326]
I am building the source and having this error: 

PROCESSOR: x86_64
Machine: x86_64-redhat-linux
-- Target host is 64 bit
CMake Error at CMakeLists.txt:147 (FIND_PACKAGE):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5" (requested
  version 5.6.0) with any of the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.

Please Help
[CMakeError.log](https://github.com/LMMS/lmms/files/3863732/CMakeError.log)

**Comment by PhysSong** [comment]
Can you check which version of Qt do you have?

**Comment by Eliyanan** [comment]
QMake version 3.1
Using Qt version 5.12.5 in /usr/lib64

**Comment by PhysSong** [comment]
Can you post the result of `rpm -qa | grep -i qt`?

**Comment by Eliyanan** [comment]
[output.txt](https://github.com/LMMS/lmms/files/3873834/output.txt)

**Comment by tresf** [comment]
You must set `CMAKE_PREFIX_PATH` to the location of Qt5.  This is annoying, but it's how many environments handle building with Qt.

Feel free to ask questions here, but this is not a bug.  We do have an interactive channel you can ask for help on over at Discord https://lmms.io/chat
