### ISSUE TITLE
LMMS is unstable when using a Roland System-1 (25 key synth)

### ISSUE THREAD

**Issue by Ryder17z** [LMMS/lmms#5327]
There's some odd things going on here;

If i hook it up to VeSTige - only the right half of the piano keys are detected regardless of how I configure it,

if i hook it up to SID - using two keys or controls at the same time quickly crashes lmms.

#### LMMS version used

1.2.1-win64

#### Logs
where are they? 
This info isn't on the wiki and there's no log file in the install dir nor working dir.

**Comment by tresf** [comment]
> Logs
> where are they?
> This info isn't on the wiki and there's no log file in the install dir nor working dir.

Logs for Windows are nearly impossible to obtain, don't worry about that.

**Comment by Ryder17z** [comment]
> Logs for Windows are nearly impossible to obtain, don't worry about that.

Seems silly, but alright.

**Comment by tresf** [comment]
> Seems silly, but alright.

It has to do with the fact that the software originated from Linux where you could just read the console... 

If you're interested... https://github.com/LMMS/lmms/issues/3876

**Comment by JohannesLorenz** [comment]
It's a crash, so this must be fixed on `stable-1.2` I guess?

**Comment by Ryder17z** [comment]
Seems stable now.
