### ISSUE TITLE
Qt 5.6 LTS ended in march 2019

### ISSUE THREAD

**Issue by ghost** [LMMS/lmms#5331]
https://www.qt.io/blog/2018/11/29/support-qt-5-6-lts-ends-march-2019

| Qt version | LTS till |
| :------ | :------- |
| 5.9 | 31.05.2020 |
| 5.12 | ??.??.2021 |

I'll suggest to update `CMakeLists.txt` to set the recommended version to atleast version `5.9`

**Comment by Rossmaxx** [comment]
We could bump to qt 5.9 but pretty sure our outdated cj build system won't allow it.
