### ISSUE TITLE
.ds files envelopes shortened by oversampling

### ISSUE THREAD

**Issue by softrabbit** [LMMS/lmms#5342]
> It looks like this is still an issue on drumsynth (.ds) files.
> https://lmms.io/forum/viewtopic.php?f=7&t=31122

_Originally posted by @zonkmachine in https://github.com/LMMS/lmms/pull/5226#issuecomment-555184114_

So, what happens is that the pitch is correct but the envelopes are too short. Looks like the unit for envelope times in the .ds file is samples, which breaks when a sample rate != 44100 is passed in. 

The fix is probably as simple as a one-liner adjusting the ```timestretch``` variable ( https://github.com/LMMS/lmms/blob/master/src/core/DrumSynth.cpp#L65 ) when loading the .ds file.

**Comment by zonkmachine** [comment]
@softrabbit I think it would be good to fix this in 1.2.2

**Comment by PhysSong** [comment]
> The fix is probably as simple as a one-liner adjusting the `timestretch` variable

I'll wait for a week and open a PR to fix it if no one does.

**Comment by zonkmachine** [comment]
Fixed in https://github.com/LMMS/lmms/pull/5467
