### ISSUE TITLE
KeyError: 'comment' when loading any plugin in Carla

### ISSUE THREAD

**Issue by fentras** [LMMS/lmms#5345]
### Bug Summary
Carla can't load any plugin (or loads and does nothing after this) when running in LMMS. If Carla is running as a separate process (not as plugin) — everything is working and loading. I don't know if it's Carla problem or LMMS.
#### Steps to reproduce
1. Open _LMMS_ (AppImage) and have _Carla_ installed.
2. Move _Carla Rack_ to _Song Editor_.
3. Open _Carla_ GUI and load any plugin.
4. Get nothing (or something, but it will not work) in rack view but an error when debugging.
#### Expected behavior
Working GUI of a plugin.
#### Actual behavior
Not working GUI of a plugin and nothing in rack view.
_Patchbay_ plugins (GUI) don't work either but you can get the sound from a plugin (e.g. Dexed).
#### Media
(The image is clickable for a video demonstration)
<a href="https://streamable.com/tq3of"><img src="https://user-images.githubusercontent.com/26721650/70851145-9c0f3900-1ea2-11ea-931b-e24837f5a3d6.png" alt="Screenshot_20191214_184835" width="90%"></img></a>
#### Versions used
LMMS 1.2.1 (AppImage)
Carla 2.0.90 (2.1-alpha2)
JACK 1.9.12
Fedora 31 (KDE)
#### Logs
<details>
  <summary>Click to expand</summary>
<pre>
Carla appears to be installed on this system at /usr/lib[64]/carla so we'll use it.
Jack appears to be installed on this system, so we'll use it.
Notice: could not set realtime priority.
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
/usr/bin/jackd: /tmp/.mount_lmms.AHf3yoo/usr/lib/libdbus-1.so.3: no version information available (required by /usr/bin/jackd)
jackdmp 1.9.12
Copyright 2001-2005 Paul Davis and others.
Copyright 2004-2016 Grame.
Copyright 2016-2017 Filipe Coelho.
jackdmp comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details
Cannot create RT messagebuffer thread: Operation not permitted (1)
Retrying messagebuffer thread without RT scheduling
Messagebuffer not realtime; consider enabling RT scheduling for user
no message buffer overruns
JACK server starting in realtime mode with priority 20
self-connect-mode is "Don't restrict self connect requests"
Cannot lock down 107341338 byte memory area (Cannot allocate memory)
audio_reservation_init
Acquire audio card Audio0
creating alsa driver ... hw:PCH|hw:PCH|512|2|48000|0|0|nomon|swmeter|-|32bit
configuring for 48000Hz, period = 512 frames (10.7 ms), buffer = 2 periods
ALSA: final selected sample format for capture: 32bit integer little-endian
ALSA: use 2 periods for capture
ALSA: final selected sample format for playback: 32bit integer little-endian
ALSA: use 2 periods for playback
Cannot use real-time scheduling (RR/20)(1: Operation not permitted)
AcquireSelfRealTime error
Cannot lock down 107341338 byte memory area (Cannot allocate memory)
Cannot use real-time scheduling (RR/15)(1: Operation not permitted)
JackClient::AcquireSelfRealTime error
JackEngine::XRun: client = lmms was not finished, state = Running
JackAudioDriver::ProcessGraphAsyncMaster: Process error
JackEngine::XRun: client = lmms was not finished, state = Triggered
#(15 more messages like above)
Trying to start carla-plugin using "/usr/share/carla/resources/carla-plugin"
LRDF Support not available (LADSPA-RDF will be disabled)
Carla 2.0.90 (2.1-alpha2) started, status:
  Python version: 3.7.5
  Qt version:     5.12.5
  PyQt version:   5.13.1
  Binary dir:     /usr/lib64/carla
  Resources dir:  /usr/share/carla/resources
ALL OK!
#After loading Carla
qt.svg: <input>:552:178: Could not resolve property: #linearGradient5167
qt.svg: <input>:30274: Could not resolve property: #linearGradient5167
qt.svg: <input>:30274: Could not resolve property: #pattern5614
qt.svg: <input>:30274: Could not resolve property: #pattern5626
qt.svg: <input>:5672: Could not resolve property: #radialGradient3709
qt.svg: <input>:3226: Could not resolve property: #linearGradient3893-1
qt.svg: <input>:3190: Could not resolve property: #linearGradient3893-1
qt.svg: <input>:3208: Could not resolve property: #linearGradient3893-1
qt.svg: <input>:7064: Could not resolve property: #radialGradient3709
#After loading plugin in Carla
Traceback (most recent call last):
  File "/usr/share/carla/resources/carla_host.py", line 1323, in slot_handlePluginAddedCallback
    pitem = self.ui.listWidget.createItem(pluginId)
  File "/usr/share/carla/resources/widgets/racklistwidget.py", line 241, in createItem
    return RackListItem(self, pluginId)
  File "/usr/share/carla/resources/widgets/racklistwidget.py", line 81, in __init__
    self.recreateWidget(firstInit = True)
  File "/usr/share/carla/resources/widgets/racklistwidget.py", line 171, in recreateWidget
    self.fWidget = createPluginSlot(self.fParent, self.host, self.fPluginId, self.fOptions)
  File "/usr/share/carla/resources/carla_skin.py", line 2045, in createPluginSlot
    return PluginSlot_Presets(parent, host, pluginId, skinColor, skinStyle)
  File "/usr/share/carla/resources/carla_skin.py", line 1744, in __init__
    AbstractPluginSlot.__init__(self, parent, host, pluginId, skinColor, skinStyle)
  File "/usr/share/carla/resources/carla_skin.py", line 253, in __init__
    self.fEditDialog = PluginEdit(self, host, self.fPluginId)
  File "/usr/share/carla/resources/carla_widgets.py", line 544, in __init__
    self.reloadAll()
  File "/usr/share/carla/resources/carla_widgets.py", line 716, in reloadAll
    self.reloadParameters()
  File "/usr/share/carla/resources/carla_widgets.py", line 862, in reloadParameters
    'comment':   paramInfo['comment'],
KeyError: 'comment'

</pre>
</details>

**Comment by JohannesLorenz** [comment]
Can you open Carla in another DAW? (Maybe Ardour?)

**Comment by fentras** [comment]
> Can you open Carla in another DAW? (Maybe Ardour?)

Ardour doesn't even load Carla for me, but another DAW named "Radium" had the similar issue and I managed to partially fix it by tinkering with Carla and Radium libraries, see [this thread](https://github.com/kmatheussen/radium/issues/1238). I think it's mostly libraries version incompatibility and more related to Carla itself.

**Comment by JohannesLorenz** [comment]
@fentras Many thanks for checking. This saves us a lot of time :smile:
