### ISSUE TITLE
High CPU usage with the Piapro Studio VST at Idle

### ISSUE THREAD

**Issue by SeleDreams** [LMMS/lmms#5353]
### Bug Summary
When the Piapro Studio VST is loaded on LMMS, I can see a high CPU usage that doesn't occur with any other plugins.
#### Steps to reproduce
Install Piapro Studio and a VOCALOID voicebank (The hatsune miku v4 english demo can be used, downloadable here https://sonicwire.com/product/A4080  it contains both the voice and the Piapro Studio VST)

Load the Piapro Studio VST using VeSTige.
The processor usage is high at idle.

#### Expected behavior
It should stay at a low processor usage.

#### Actual behavior
The processor usage gets high.

#### Screenshot
![image](https://user-images.githubusercontent.com/16335601/71376878-4124c280-25c3-11ea-8571-aa159e5a6d6b.png)

#### LMMS version used
1.2.1 on KDE neon 5.17

#### Logs
<details>
  <summary>Click to expand</summary>
<pre>
seledreams@seledreams-Predator-PH315-51:~/Applications$ ./lmms-1.2.1-linux-x86_64_1dd8df79ef70f3b0822d8185475899fe.appimage 
Carla appears to be installed on this system at /usr/lib[64]/carla so we'll use it.
Jack appears to be installed on this system, so we'll use it.
Notice: could not set realtime priority.
0012:fixme:wer:WerSetFlags (2) stub!
0012:fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
001b:err:module:import_dll Library mscoree.dll (which is needed by L"C:\\windows\\Microsoft.NET\\Framework64\\v4.0.30319\\mscorsvw.exe") not found
001b:err:module:attach_dlls Importing dlls for L"C:\\windows\\Microsoft.NET\\Framework64\\v4.0.30319\\mscorsvw.exe" failed, status c0000135
000f:err:service:process_send_command service protocol error - failed to write pipe!
000f:fixme:service:scmdatabase_autostart_services Auto-start service L"clr_optimization_v4.0.30319_64" failed to start: 1053
Starting using X11Embed protocol.
0009:fixme:nls:GetThreadPreferredUILanguages 00000038, 0x32ecf8, 0x32ed08 0x32ecfc
0009:fixme:nls:get_dummy_preferred_ui_language (0x38 0x32ecf8 0x32ed08 0x32ecfc) returning a dummy value (current locale)
unique ID: 
0032:fixme:ver:GetCurrentPackageId (0x10dfecc (nil)): stub
0009:fixme:ntdll:EtwRegisterTraceGuidsW (0xa85e89, (nil), {f7b697a3-4db5-4d3b-be71-c4d284e6592f}, 7, 0xd3f1c0, (null), (null), 0xda8388): stub
0009:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {72b14a7d-704c-423e-92f8-7e6d64bcb92a}
0009:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {e2091f8a-1e0a-4731-84a2-0dd57c8a5261}
0009:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {e8a3bf1f-a86b-4390-9c60-5390b969d22c}
0009:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {5727a00f-50be-4519-8256-f7699871fecb}
0009:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {7e854ec7-cdc4-405a-b5b2-aaf7c9e7d40c}
0009:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {79a60dc6-5fc8-4952-a41c-1163aeec5eb8}
0009:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {2718d25b-5bf5-4479-8e88-babc64bdbfca}
0009:fixme:process:GetNumaHighestNodeNumber (0x32fa24): semi-stub
RemotePlugin::DebugMessage: inputs: 0  output: 32
RemotePlugin::DebugMessage: creating editor
0009:fixme:ver:GetCurrentPackageId (0x32ef70 (nil)): stub
0041:fixme:nls:GetThreadPreferredUILanguages 00000038, 0x33f640, 0x33f650 0x33f644
0041:fixme:nls:get_dummy_preferred_ui_language (0x38 0x33f640 0x33f650 0x33f644) returning a dummy value (current locale)
0041:fixme:ver:GetCurrentPackageId (0x33f7c4 (nil)): stub
0041:fixme:shell:InitNetworkAddressControl stub
0009:fixme:shell:InitNetworkAddressControl stub
RemotePlugin::DebugMessage: editor successfully created
</pre>
</details>

**Comment by Ashvith** [comment]
I'm no developer or a proper producer , but what seems to be the issue is that LMMS does not support realtime rendering of audio and instrument files.
We will have to wait for the net update , it seems.
Till then , use audacity , and use a reference track.

**Comment by Spekular** [comment]
> LMMS does not support realtime rendering of audio and instrument files.

Yes it does.

**Comment by DomClark** [comment]
Have you tried it in any other DAWs? Is the CPU usage high there too, or just in LMMS?
