### ISSUE TITLE
File browser - Collapsing a directory may trigger a preview in other open directories.

### ISSUE THREAD

**Issue by zonkmachine** [LMMS/lmms#5364]
In the file browser, when you collapse a directory and the mouse pointer in the updated tree is over a sample or a preset, this will trigger a preview. The mouse click event seem to be passed on. 

I have replicated the issue on stable-1.1.3, stable-1.2 and current master.

Method to reproduce. Expand all the preset directories from AFP to ZynAddSubFX and then close them again from the bottom and up. This should trigger some random sounds.

**Comment by JohannesLorenz** [comment]
I don't understand the reproducing. If I want to collapse a directory, I always do so by clicking on the directory, so in the updated tree, the pointer is still on that directory (which is now closed). So the pointer can not be over a sample or preset?

About milestoning: It occurs on 1.2 and does not sound hard to fix, so this should be milestoned 1.2?

**Comment by zonkmachine** [comment]
> I don't understand the reproducing.

I added a method to reproduce the issue in the first post


> About milestoning: It occurs on 1.2 and does not sound hard to fix, so this should be milestoned 1.2?

If someone wants to fix this for 1.2 I think that's fine.

**Comment by PhysSong** [comment]
Reproduced with a clean build:
- Go to the preset tab and expand "TripleOscillator" and "Watsyn"
- Scroll down to the very bottom
- Collapse "Watsyn"
- You'll get a preset being played

It seems like we check the item at the mouse pointer *after* `QTreeWidget::mousePressEvent()` collapses the tree. However, the relevant item is one at the cursor *before* calling `QTreeWidget::mousePressEvent()`.
https://github.com/LMMS/lmms/blob/a5dc3fee6a5c51065f268cb19f686284752e69da/src/gui/FileBrowser.cpp#L573-L577

**Comment by ifndefJOSH** [comment]
Hey, I'm new here, but I was also able to reproduce the issue. Would this be a good thing for me, a total newbie to LMMS development, to take on?

**Comment by zonkmachine** [comment]
@ifndefJOSH Thanks for fixing this!

**Comment by Spekular** [comment]
Indeed, great work! :)
