### ISSUE TITLE
Carla not found

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms#5369]
Created an AppImage from `stable-1.2` and Carla isn't detected.  Testing on Ubuntu 18.04.

The issue appears to stem from the use of the `alias` command... Quoting the bash man page:

> Aliases are not expanded when the shell is not interactive, unless the expand_aliases shell option is set using shopt (see the description of shopt under SHELL BUILTIN COMMANDS below).

This was introduced by @Reflexe in https://github.com/LMMS/lmms/commit/02980e610c960eee97104ceefe0c9563cf0d7ec9#diff-428297f77ce73ab488f2d0fe84730c0c.

As a friendly reminder, we should be avoiding non-critical changes on the `stable-1.2` branch.  In this case, Carla is unusable and the change was never tested.

**Comment by Reflexe** [comment]
Sorry about that, I can't remember why I did that. Thanks for the fix.

**Comment by tresf** [comment]
> Sorry about that, I can't remember why I did that. Thanks for the fix.

No worries, thanks for all the time you've dedicated!

Closed via fd77c79 as part of the Xenial build environment changes.  Note, this patch has not yet landed on `master`.
