### ISSUE TITLE
req. to include bristol-synths

### ISSUE THREAD

**Issue by oeai** [LMMS/lmms#537]
hi, there's such thing, they do for about 6 years, published on sourceforge and works under linux, it is an old-school like mOOg stuff, this is emulators as i understand it - moog, korg, roland, arp 
http://bristol.sourceforge.net/
maybe there will be a time to include just like some ZyNa presets?
![shot-2014-03-29_22-56-27](https://cloud.githubusercontent.com/assets/2557665/2559268/2ba50186-b774-11e3-9194-91af302ca449.jpg)

**Comment by tresf** [comment]
> So if we'd include it, we had to write our own Qt-based UI frontend.

Closing as won't-fix since there's no one actively pursuing this initiative.  Please reopen or cross-link if this changes.
