### ISSUE TITLE
Could "vertical" zoom of the piano roll view grid cells be added?

### ISSUE THREAD

**Issue by yetoyeto** [LMMS/lmms#5371]
Could "vertical" zoom of the piano roll view grid cells be added?

**Comment by Veratil** [comment]
Yes, it can! I'll see about working on this after my other PR working in the same code area is merged.

**Comment by yetoyeto** [comment]
Thank you. Thank you. That would be helpful.

**Comment by Spekular** [comment]
Duplicate of #2294, consolidated in #4877.
