### ISSUE TITLE
composing aid: color root-note

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#5379]
## Enhancement Summary
a method that would take the lowest bote in each chord in a progression and make it a distinct color
#### Justification
It is useful to see/ know/ spot the rootnote in all chords after several inversions
#### Mockup
![image](https://user-images.githubusercontent.com/6662066/72934080-4d877100-3d63-11ea-99b0-f29a97b039fb.png)

-Could be an option in dropdown-Chord of a button next to Chord

**Comment by SecondFlight** [comment]
Here are my thoughts - please correct me if I say something inaccurate.

Based on my understanding of music theory, the lowest note is not always the root note of a chord. Even with no additional context, the root of the chord can be the middle of 3 (in the case of first inversions of major/minor triads), the top of 3 (major/minor triad second inversion), one of 4 (any inversion of a major chord that has a 7th), or technically ambiguous (C major sus2 has the same notes as the first inversion of G major sus4).

In addition, an E minor triad playing in one clip and a C playing in another clip makes a C major 7 chord, even though C is not present in the first clip. This problem of not having the full context is less of an issue I think, but it could lead to more misleading indications.

**Comment by musikBear** [comment]
> Based on my understanding of music theory, the lowest note is not always the root note of a chord.

How to word this.. You are correct! but the reason is that you say **not always**. 
That is *exactly* what this feature would take care of.
You are 'allowed' to *rearrange* any note of a chord, as long as you move the note WHOLE octave(s)
When you do *that*, you have made an *inversion* of **the** chord. It will now look *strange* and it can be difficult to see what chord it is, but it IS still the *same* chord, it is just inverted!
The feature is meant to take care of this confusion, but it is *of cause* **only** meant to be invoked on *non-inverted* chords!
Just as the chords in our *chord-table*
Any chord you select in that table, has its root in lowest position *in that chord* -Always!
The proposed feature will keep track of the rootnote -also *after* several inversions

**Comment by SecondFlight** [comment]
The enhancement summary just says
> a method that would take the lowest bote in each chord in a progression and make it a distinct color
and nothing about when it is or is not active, or how it behaves if you, say, move the indicator note away from the chord. Could you provide more detail here? I made some assumptions to fill in the details, and it sounds like my understanding is now different from yours.
- What happens when this root indicator is moved to a different note, or away from the chord? Can this indicator note be duplicated and placed elsewhere?
- When does this root indicator appear? The item below is helpful, but doesn't fully describe behavior. Is this a tool like the pencil? Is it a global enable/disable? Does it only happen when chords are being placed?
  - > Could be an option in dropdown-Chord of a button next to Chord

**Comment by musikBear** [comment]
> nothing about when it is or is not active, or how it behaves if you, say, move the indicator note away from the chord. 

*That* is a good point.
Both 'active' and 'moved' are of importance!
I actually realize that there is a different way to get the result, through a different procedure.
The roots of inserted chords, can just be marked, and copied to a 'scrap-block', then the same result is reached: Root-notes are preserved, and can be read-out from the scrap-block, they do not have to be marked in the block with the progression.
The feature is not needed. Its doable already through a different way to use existing features 
Closing.
