### ISSUE TITLE
Piano Roll Play Button Playing Wrong Segment

### ISSUE THREAD

**Issue by leopardheart982** [LMMS/lmms#5380]
https://gfycat.com/upload/results

Might have something to do with copy/pasting keys? You can see at the end that the notes are different, because they had since been changed, but it was still playing from the segment the keys were copied from, on a separate piano roll.

**Comment by SecondFlight** [comment]
Hi, the link you've posted is not a link to a specific gif, but just to the generic upload results page. Can you provide an updated link?

Thanks!
