### ISSUE TITLE
Greippi - Krem Kaakkuja (Second Flight Remix) is muted by default in 1.2.1

### ISSUE THREAD

**Issue by SecondFlight** [LMMS/lmms#5381]
First reported by `dumpster "teen"#1089` on Discord.

### Bug Summary

The Krem Kaakkuja remix has a muted master channel and produces no sound by default. This was originally reported as a support request, and I have verified it on my own machine. I have also tested all other projects in all folders, and none of them have the same issue.

#### Steps to reproduce

1. Open `Greippi - Krem Kaakkuja (Second Flight Remix)` from demos
2. Play the project

#### Expected behavior

There should be sound.

#### Actual behavior

There is no sound, as the master FX channel is muted.

#### Screenshot

![image](https://user-images.githubusercontent.com/6700184/72951583-f54d7080-3d5c-11ea-8a39-cadc3987b75d.png)

#### LMMS version used
1.2.1

**Comment by zonkmachine** [comment]
@PhysSong This would be from c436e5ca578e98f5d9b8eadbb077a283978cd867

**Comment by PhysSong** [comment]
I checked all `.mmpz` files, this is the only affected file. aeac24c06d1a839b242d7738e1412f068508cb4a should fix this.

**Comment by zonkmachine** [comment]
Tested, fixed. Thanks!
