### ISSUE TITLE
Ghost notes: Show ghost also in automation track

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#5388]
#### Enhancement 
Summary Let current ghosted TCO show up in Automation 

#### Justification
Making bitch-bend patterns precisely fit the particular note

#### Mockup
![image](https://user-images.githubusercontent.com/6662066/73981554-b3aeef00-4932-11ea-86ce-da03dd9b9dfb.png)

**Comment by Spekular** [comment]
Closing as duplicate, thanks for the heads up @CYBERDEViLNL .
