### ISSUE TITLE
PortAudio, SF2, GIG missing with mingw

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms#5390]
Installing `fluidsynth-mingw-w64`, `portaudio-mingw-w64`, `libgig-mingw-w64` [from @tobydox's `mingw-w64` PPA](https://launchpad.net/~tobydox/+archive/ubuntu/mingw-w64), the packages are not found during the initial configure step.

OS: Ubuntu 18.04

Using the [Ubuntu 18.04 "Bionic" dependencies for `mingw`](https://github.com/LMMS/lmms/wiki/dependencies-windows#ubuntu-cross-compile)

```bash
../cmake/build_win64.sh
```

```diff
  Supported audio interfaces
  --------------------------
  * ALSA                        : <not supported on this platform>
  * JACK                        : <not supported on this platform>
  * OSS                         : <not found or not supported on this platform>
  * Sndio                       : 
+ * PortAudio                   : not found, please install portaudio19-dev (or similar, version >= 1.9) ;if you require PortAudio support
  * libsoundio                  : <disabled in this release>
  * PulseAudio                  : <not supported on this platform>
  * SDL                         : not found, please install libsdl2-dev (or similar) ;if you require SDL support

  Optional plugins
  ----------------
  * ZynAddSubFX instrument      : OK
  * Carla Patchbay & Rack       : OK (weak linking enabled)
+ * SoundFont2 player           : not found, libfluidsynth-dev (or similar);is highly recommended
+ * GIG player                  : not found, libgig needed for decoding .gig files
```

**Comment by DragonEagle** [comment]
https://github.com/LMMS/lmms/wiki/dependencies-windows was missing some packages on the Bionic install.  specifically the c++ compilers and the package that contains
pkg-config.  I've updated the doc and the libraries are found now.

**Comment by tresf** [comment]
@DragonEagle did this correct SF2, GIG, PortAudio for you?

**Comment by DragonEagle** [comment]
Yes it did.  Everything was found

**Comment by tresf** [comment]
Awesome!  Thanks for the contribution!
