### ISSUE TITLE
Ubuntu-18 , CMAKE Error == Could NOT find SndFile (missing: SNDFILE_LIBRARY SNDFILE_INCLUDE_DIR)

### ISSUE THREAD

**Issue by RohitDhankar** [LMMS/lmms#5391]
### Please search the issue tracker for existing bug reports before submitting your own. Delete this line to confirm no similar report has been posted yet.
Searched few related issues found , but none seems to solve mine. 

### Bug Summary 
Ubuntu-18 , CMAKE Error == Could NOT find SndFile (missing: SNDFILE_LIBRARY SNDFILE_INCLUDE_DIR)

#### Steps to reproduce
GitClone master branch and cmake on Ubuntu-18 . Within the DIR build -  /lmms/build, using command at terminal $ cmake .. -DCMAKE_INSTALL_PREFIX=../target/

#### Expected behavior
Not sure 

#### Actual behavior
CMAKE Error == Could NOT find SndFile (missing: SNDFILE_LIBRARY SNDFILE_INCLUDE_DIR)

### CMakeError.log , CMakeCache.txt and the CMakeOutput.log , are attached . 
[CMakeCache.txt](https://github.com/LMMS/lmms/files/4179969/CMakeCache.txt)
[CMakeError.log](https://github.com/LMMS/lmms/files/4179970/CMakeError.log)
[CMakeOutput.log](https://github.com/LMMS/lmms/files/4179971/CMakeOutput.log)

#### LMMS version used
Trying to install = 1.2.1.581

#### Logs
<details>
  <summary>Click to expand</summary>
<pre>

</pre>
</details>

OS = Ubuntu 18.4
Make Command = /lmms/build$ cmake .. -DCMAKE_INSTALL_PREFIX=../target/
Terminal output of the ERROR = 

-- Checking for module 'sndfile'
--   No package 'sndfile' found
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find SndFile (missing: SNDFILE_LIBRARY SNDFILE_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindSndFile.cmake:34 (find_package_handle_standard_args)
  CMakeLists.txt:176 (FIND_PACKAGE)
#
Probable relevant text in the file CMakeCache.txt
//Path to a file.
SNDFILE_INCLUDE_DIR:PATH=SNDFILE_INCLUDE_DIR-NOTFOUND
//Path to a library.
SNDFILE_LIBRARY:FILEPATH=SNDFILE_LIBRARY-NOTFOUND
#
My CMAKE version == cmake version 3.10.2
is it in the below mentioned issue , i read correctly that we need - CMAKE version == 2.Something , to make LMMS ? Add CMake 2 support #4530
#
Closest issues and pull requests text - which i have read through.
Cant figure out if - anything from them is a solution for me - 
1/ CMake tries checking sys/time.h for sndfile and libsoundio == https://github.com/LMMS/lmms/issues/2815
2/ Add CMake 2 support #4530 == https://github.com/LMMS/lmms/pull/4530
### ScreenShot below 

![Screenshot from 2020-02-10 14-05-46](https://user-images.githubusercontent.com/13214169/74133409-843c0300-4c0e-11ea-961a-100cc9a3ff35.png)

**Comment by SecondFlight** [comment]
Hi, do you have libsndfile installed as per the [compiling instructions](https://github.com/LMMS/lmms/wiki/Compiling)? See [here](https://github.com/LMMS/lmms/wiki/dependencies-ubuntu) for quick instructions to install all the recommended ones.

**Comment by RohitDhankar** [comment]
> Hi! Thank you for the detailed report.
> 
> Do you have `libsndfile` installed as per the [compiling instructions](https://github.com/LMMS/lmms/wiki/Compiling)? There are a few dependencies that are required for LMMS to build. See [here](https://github.com/LMMS/lmms/wiki/dependencies-ubuntu) for quick instructions to install all the recommended dependencies for Ubuntu.

Thanks a lot . All good . Have been able to make and run version = 1.2.1 

![Screenshot from 2020-02-11 15-40-40](https://user-images.githubusercontent.com/13214169/74227633-e36c4700-4ce4-11ea-8ad0-eb36874a3959.png)

**Comment by SecondFlight** [comment]
@RohitDhankar FYI: As I said in my other comment, the latest stable version is 1.2.1. The version you've built is labelled as 1.2.1, but it has a number of additional features and is less stable. It represents our 1.3 development branch.

You can get an `appimage` for 1.2.1 here: http://lmms.io/download/#linux

**Comment by RohitDhankar** [comment]
> @RohitDhankar For your information: As I said in my other comment, the latest stable version is 1.2.1. The version you've built is labelled as 1.2.1, but it has a number of additional features and is less stable. It represents our 1.3 development branch.
> 
> You can get an `appimage` for 1.2.1 here: http://lmms.io/download/#linux

@SecondFlight - Thanks again . I did clone the - master branch , presuming that would be the current stable release. I think i will live with it for now - thanks .
