### ISSUE TITLE
Loop drops onto next bar over (macOS Mojave 10.14, LMMS v1.2.1.581)

### ISSUE THREAD

**Issue by GingkathFox** [LMMS/lmms#5393]
2/5 D:
### Bug Summary
- copying and pasting a loop is offset? hovering over the bar you want it to be and dropping it drops it on the next bar

#### Steps to reproduce
Open a project, make a loop, and try to copy it to the next bar.

#### Expected behavior
Loop drops onto the bar.
#### Actual behavior
Loop drops onto the next bar.

#### LMMS version used
1.2.1.581

**Comment by Spekular** [comment]
Is this behavior the same regardless of which half of the bar you drop over? I would expect it to drop on the current bar if you're within the first half of it.

**Comment by GingkathFox** [comment]
Yeah, it drops on the next bar unless im hovering right over the dividing line between the bars.

**Comment by Spekular** [comment]
I'm fairly sure this is a consequence of #4973, so if my build is still working I'll probably try fixing it soon. Marking for 1.3 since I assume that's where #4973 will end up as well.
