### ISSUE TITLE
Song editor mode sticks if modal is opened while holding control

### ISSUE THREAD

**Issue by GingkathFox** [LMMS/lmms#5394]
3/5, more of a issue than a bug.
### Issue Summary
- clicking command in the Song Editor toggles draw and edit mode, really annoying when trying to export and the piano roll swaps to edit mode.

#### Steps to reproduce
Focus on the Song Editor and hit command. prolly works with control too on windows

#### Expected behavior
nothing happens.
#### Actual behavior
song editor toggles to edit mode until command key is released. or sometimes, when exporting for example, it locks to edit mode until command is hit again.
#### LMMS version used
1.2.1.581

**Comment by Spekular** [comment]
Yes, ctrl toggles select mode on when held. This is to allow ctrl+drag selection of several clips, instead of having to click into select mode (and back out) every time you want to group select.

What exactly is the issue with this?

**Comment by GingkathFox** [comment]
Its annoying when i hit, say, command+S to save, cause then when i go to move something i end up highlighting it

**Comment by Spekular** [comment]
The fact that select mode is active *while control is held* is an invalid issue, this is a feature. However, the fact that it can get stuck is valid. I've figured out how to reproduce this:

- Focus the song editor and hold ctrl
- Open a modal while holding control
  - Help > About
  - Edit > Settings
  - File
    - Open
    - Save*, Save As, Save as New Version*
    - Import
    - Export, Export Tracks, Export MIDI
    - Quit**

*These only work if the project has never been saved
**This works if there are unsaved changes

**Comment by PhysSong** [comment]
It sounds similar to #3833. I think we can consolidate this and that into single issue.

**Comment by Spekular** [comment]
Am I correct in understanding that the issue with piano roll was fixed by #4393?

**Comment by PhysSong** [comment]
> Am I correct in understanding that the issue with piano roll was fixed by #4393?

Yes. However, the method doesn't work well with the song editor. I'm investigating it.
However, it's easy to allow reset the editing mode by hitting the control key again.
