### ISSUE TITLE
RemoteVstPlugin uses text file I/O for loading/saving fxp/fxb files

### ISSUE THREAD

**Issue by PhysSong** [LMMS/lmms#5395]
https://github.com/LMMS/lmms/blob/792e4786ad4d21d3d118afffc08daad1141b8353/plugins/vst_base/RemoteVstPlugin.cpp#L1241
https://github.com/LMMS/lmms/blob/792e4786ad4d21d3d118afffc08daad1141b8353/plugins/vst_base/RemoteVstPlugin.cpp#L1293
`git blame` points to 792e4786ad, but it has been there for a very long time.
This issue doesn't have any effects on Linux because Linux uses `\n` for the newline character. On Windows, however, this will make `\n` to be converted to `\r\n`, or vice versa.
On Windows, this breaks loading `.fxb`/`.fxp` files and makes saved `.fxb`/`.fxp` files unusable on other programs.

**Comment by Spekular** [comment]
Closed by #5411
