### ISSUE TITLE
Preserve the FX-Track when an instrument gets replaced

### ISSUE THREAD

**Issue by panos** [LMMS/lmms#5399]
### Enhancement Summary

When an instrument gets replaced (through drag and dropping), it'd be great if the FX-Track that was assigned to the previous instrument would not switch back to the master track (as soon as the instrument gets replaced with a drag and drop).

#### Justification

This would probably make a lot more sense, considering that when you replace an instrument, certain other properties are not affected (e.g. the piano roll and the MIDI configurations).

##### Potential use case

Say that a user decides to try out different musical instruments one-by-one and wants to use the same mixing settings every time.

Spending time with opening the instruments every single time the instrument is changed can be very annoying and does hinder productivity. This particularly applies to genres where mixing settings that essentially change the core aspects of a specific sound. (e.g. dream pop)

**Comment by Spekular** [comment]
Tested on a master build and on 1.2.1, here's what I find:
- When an instrument plugin is dropped on an existing, track, the FX channel is unaffected
- When a preset is dropped on an existing track, the preset decides the FX channel. For example, AngryLead in LB302's presets is set to FX channel 1. The rest of LB302's presets have the channel set to 0.

Assuming the mixer channel is what you're referring to, I don't see any issue with your proposal (i.e. dropping a preset shouldn't affect the track's channel setting).

As for preserving the FX-chain on the instrument itself, that would present a few issues. Some presets rely on FX, so ignoring the preset's effects chain could drastically change the preset sound. If the user's effects are to be preserved (added after the preset's effects), you get a cumulative pile of effects if you swap presets several times. I think the current behavior (override existing chain with preset's chain) is reasonable here, though it'd be good if the preset-drop could be undone.
