### ISSUE TITLE
Incorrect note velocity on change

### ISSUE THREAD

**Issue by BluuDreamz** [LMMS/lmms#5405]
Selecting a group of notes on a piano roll in order to change the velocity of said selected notes to a new value altogether through the dialog box only updates the first selected/highlighted note to the designated value.

#### Step 1:
Group-select a series of notes on a piano roll.

#### Step 2:
Double-click on any one of the velocity nodes within the note velocity editor on the piano roll to prompt the dialog box.

#### Step 3: 
Enter in any value you wish to change the group-selected notes to.

#### Expected behavior
Changing the note velocity of a selected group of notes through the dialog box to x value should set all selected notes to that value.

#### Actual behavior
Despite having them all selected, changing the note velocity of a selected group of notes through the dialog box to x value only sets the first highlighted/selected velocity note value to the designated value.

#### Screenshots
![image](https://user-images.githubusercontent.com/39863151/75263093-816b1180-57bb-11ea-8090-ddcdd51fc8ec.png)

![image](https://user-images.githubusercontent.com/39863151/75263140-95167800-57bb-11ea-93f5-0bb41d60733d.png)

![image](https://user-images.githubusercontent.com/39863151/75263155-9a73c280-57bb-11ea-9cab-8843a85147dd.png)

#### LMMS version used: 1.2.1

The practicality to this function is to allow the user to reset a select group of notes to a default value of their choice.

**Comment by JohannesLorenz** [comment]
@BluuDreamz There's a fixing PR #5438 that needs testing. Would you mind to do some testing for your issue?

**Comment by zonkmachine** [comment]
Fixed in https://github.com/LMMS/lmms/pull/5438

@BluuDreamz Thanks for reporting! The fix will be available in lmms-1.2.2, coming soon-ish...
