### ISSUE TITLE
font size issue

### ISSUE THREAD

**Issue by aliencq** [LMMS/lmms#541]
How can I change font size for settings dialog? Default size is too small and it ignores my DE settings.
![scr1](https://cloud.githubusercontent.com/assets/7108174/2561785/7bd40124-b829-11e3-8676-c1c1f56403d2.jpg)

**Comment by tresf** [comment]
I'm consolidating this into #1839 as a general theme improvement setting although it is only slightly related and may be addressed separate from the Cusis initiatives.  Feel free to open if you feel this was consolidated in error. :+1:

**Comment by messmerd** [comment]
The Setup Dialog font size was improved by #6779
