### ISSUE TITLE
Chord Progressions Don't Get Recorded

### ISSUE THREAD

**Issue by MrTeeXD** [LMMS/lmms#5410]
### Bug Summary
So, LMMS has this thing in the VST menu where you can have Chord Progressions and that you can use to come up with great ideas. However, when arming the VST for recording, those Chord Progressions don't get recorded, they are replaced with Single notes which seems odd. 

#### Steps to reproduce
Here is a GIF I have to reproduce this issue:
![aYjRbXStSM](https://user-images.githubusercontent.com/37266538/75597828-71e01700-5aa0-11ea-8fa5-42239de566a1.gif)

#### Expected behavior
The Chord Progressions shown in the GIF should have been recorded as more then one note instead of one single note. I was expecting it to add more notes when a Chord Progression was change in the VST menu

#### Actual behavior
It only records that whole Progression as one note which is not right at all.

#### Affected LMMS versions
1.2.1

#### Logs
<details>
  <summary>Click to expand</summary>
<pre>

</pre>
</details>

**Comment by Spekular** [comment]
Related: #4807, #4938

Are you recording with KB/M or a MIDI keyboard? I believe this should work as you expect, at least for for typing keyboards and mouse , but MIDI might not work.

**Comment by MrTeeXD** [comment]
Hello there. Yes, I am recording with a KB/M since I dont own a Actual MIDI Keyboard

**Comment by musikBear** [comment]
Chords selected in piano-rolls **Chord-table** *are* recorded in Master, that part is fixed ( rc7.623 ) 
Eg there is a way to record chords implemented already, Recording through the instrument-stacking is not needed

**Comment by Spekular** [comment]
Just saw the gif for the first time, closing as invalid. The stacking feature plays back chords even if only one note is input. If it recorded to several notes it would then play several chords instead.
