### ISSUE TITLE
Ability to move instruments into Beat/Basslines

### ISSUE THREAD

**Issue by AlwaysLivid** [LMMS/lmms#5412]
### Enhancement Summary

From what I'm gathering, the instruments in the song editor are for linear compositing, while the beat/basslines are for creating loops in a similar fashion to FL Studio.

It would be a nice idea to be able to move instruments in (and potentially out) of the Beat/Basslines.

#### Justification

It would give the user the ability to work in a more flexible manner, and it'd also give more space for them to work in an abstract, spontaneous manner. An additional benefit that would also probably come with this feature is moving instruments out of Beat/Basslines and then placing them in another Beat/Bassline, which sounds pretty good from an organizational perspective.

**Comment by musikBear** [comment]
invalid.
You can insert any kind of instrument in Beat&Bass-editor already.
You can even move any instrument from song-editor with all notes -and vis-a-vi
-And..
You can even move anything from one project to an other project, if you have sufficient RAM @AlwaysLivid 
Close as invalid

**Comment by Spekular** [comment]
@musikBear It would be helpful if you explained *how* to do this, if you're going to claim it's possible. I wasn't aware of this functionality either, and simply dragging doesn't work.

@AlwaysLivid if you hold ctrl and then drag a track, you can move them between the BB editor and Song Editor.

**Comment by musikBear** [comment]
> It would be helpful if you explained how to do this
true- should have
Well heres a video :p @AlwaysLivid  https://www.youtube.com/watch?v=Sq203Ka3t9E

**Comment by AlwaysLivid** [comment]
> @musikBear It would be helpful if you explained _how_ to do this, if you're going to claim it's possible. I wasn't aware of this functionality either, and simply dragging doesn't work.
> 
> @AlwaysLivid if you hold ctrl and then drag a track, you can move them between the BB editor and Song Editor.

Yeah, apologies for opening an issue without investigating any further. I truly appreciate the help nevertheless.

**Comment by poyribn** [comment]
Moving Patterns into Beat/Bassline should be briefly and unobtrusively explained in the UI,
when the Composer first opens Beat/Bassline Editor,
until they checks “Don’t show this again” and then moves a Pattern into Beat/Bassline.

I would imagine this Hint appears below the Instruments in Beat/Bassline Editor.
It would not have an OK Button to close it.
It would be permanently closed by checking “Don’t show this again” and then doing the Action it explains.
