### ISSUE TITLE
Watsyn's A2->A1 envelope pops

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#5414]
### Bug Summary
Watsyn can prospone the mixing in of A2 in A1.
That can cause an artefact pop or click in the sound

#### Steps to reproduce
In default watsyn select 
* triangle for A1
* square for A2
Set
* A2->A1 mix: 45.5
* AMT: 140
* Matrix: MIX MIX
* Mix-envelope-attack : 1000 ms
* A2 Vol: .35

It will be like
![image](https://user-images.githubusercontent.com/6662066/76032486-4f377d80-5f3a-11ea-9665-e8254a44e2dd.png)

Press A4
After 1000 ms, there is a distinct pop before A1 tone blends in
#### Expected behavior
A1 tone should blend in without pop
#### Actual behavior
The pop can be seen in Audacity as a 'gab'
![image](https://user-images.githubusercontent.com/6662066/76031925-0a5f1700-5f39-11ea-95b6-6700f9766ab7.png)

#### Affected LMMS versions
1.2.1 win 10

**Comment by zonkmachine** [comment]
Can you add a project that demonstrates this?

**Comment by musikBear** [comment]
Here it is:
I stupidly named it monstro, but its as you can see watsyn :|
[monstrClick1000ms.zip](https://github.com/LMMS/lmms/files/4638708/monstrClick1000ms.zip)
Just press base-note for a secd+ and you can hear the click

**Comment by zonkmachine** [comment]
I think that's just the decay (same row as the attack) being turned down to 0.
Is there a Watsyn manual? I only find [this one](https://docs.lmms.io/user-manual/5-built-in-instruments/5.18-watsyn) and I don't think it's that helpful to be honest.

**Comment by musikBear** [comment]
> I only find this one and I don't think it's that helpful to be honest.

Naeh, that is not optimized ;p
Odd -i thought i wrote a piece for this some month back, maybe i diddent save it correctly :| - I should have a copy locally
