### ISSUE TITLE
Crash when importing hydrogen song

### ISSUE THREAD

**Issue by DragonEagle** [LMMS/lmms#5416]
### Bug Summary
Attempt to import a Hydrogen song and lmms segfaults.  In stable it reports that it is not a valid FL file and in git it reports that it is not a valid midi file.

#### Steps to reproduce
Open any hydrogen song.  I have tried sever with the same results

#### Expected behavior
The song will import and either place the pattern in the beat editor or the song editor.  Not sure which it's supposed to do.

#### Actual behavior
LMMS crashes and closes usually with a segfault

#### Affected LMMS versions
1.1.3 and above windows and linux

#### Logs
<details>
  <summary>Click to expand</summary>
<pre>
MidiImport::tryImport(): not a Standard MIDI file
Segmentation fault (core dumped)
</pre>
</details>

**Comment by Spekular** [comment]
Reproduced, sort of, on Win 10 with 1.2 and a master build. In my testing LMMS stopped responding rather than crashing, and I got a "no default soundfont" warning rather than "invalid midi file/fl project".

**Comment by musikBear** [comment]
ehrm.. wasent Hydrogen-file-usage dropped when FLs-files was dropped?
There are no import option hydrogen-files, only MIDI  :?

**Comment by Spekular** [comment]
@musikBear if you select File > Import, you'll find "Hydrogen Project" as an option in the file filter ("Files of type") dropdown. If hydrogen import was meant to be dropped then this option should be removed as well. I also question the ability to select "All files" as a filter.

**Comment by musikBear** [comment]
![image](https://user-images.githubusercontent.com/6662066/76441867-5dfdb480-63c0-11ea-9a25-ac3b6977d85b.png)
Holy .. farm-animal you are correct! @Spekular In both accounts
and yes that is wrong

**Comment by Spekular** [comment]
[plugins/HydrogenImport](https://github.com/LMMS/lmms/tree/ce5c74432e83f0eaa617cc26332f4209bc4efc7f/plugins/HydrogenImport) still exists on both 1.2 and master branch though, so I don't see that support would be dropped.

**Comment by zonkmachine** [comment]
Fixed in https://github.com/LMMS/lmms/pull/5420
