### ISSUE TITLE
CMake only lists optional dependencies as missing but fails to build.

### ISSUE THREAD

**Issue by poikilos** [LMMS/lmms#5421]
### Bug Summary
On Fedora 31, either missing the "if you need" or optional components or some unknown cause prevents cmake from building lmms.

#### Steps to reproduce
- Delete CMakeCache.txt as instructed by LMMS build instructions, if it exists.
- As root, install dependencies from LMMS build instructions (also `sudo dnf -y install lame-devel` to completely reproduce my case).
- As a regular user, clone the repo then run:
```
cd lmms
mkdir -p build
FORCE_VERSION=$(date "+%Y-%m-%d")
CMAKE_INSTALL_PREFIX="$HOME/.local"
cmake .. -DCMAKE_INSTALL_PREFIX=$CMAKE_INSTALL_PREFIX -DFORCE_VERSION=$FORCE_VERSION -DWANT_VST=OFF -DOpenGL_GL_PREFERENCE=GLVND

```
**:edit: SOLUTION: Use dots and regular numbers (not zero padded) in the version, such as `FORCE_VERSION=$(date "+%Y.%-m.%-d")`** (which yields a string like `2020.3.22`).

#### Expected behavior
- It should either build or tell you the reason why it doesn't.
- If anything that says optional or "if you need" are actually required, that must be corrected in the cmake output.

#### Actual behavior
It fails to build and says the reason is above.

#### Affected LMMS versions

85e05741382c688de151da34302517eaa48e7907

#### Logs
- [lmms 2020-03-17 cmake results](https://pastebin.com/15AkXAhG)
- [lmms 2020-03-17 CMakeError.log](https://pastebin.com/wsHVRsYw)
- [lmms 2020-03-17 CMakeOutput.log](https://pastebin.com/bFq9VbZa)

**Comment by knarrff** [comment]
It may be that libsndio-devel is missing from the requirements-list.

Which list did you use?
- https://github.com/LMMS/lmms/wiki/Compiling#libraries
- https://github.com/LMMS/lmms/wiki/dependencies-fedora

(libsndio, if indeed a dependency, is missing from both)

**Comment by poikilos** [comment]
I used the Fedora list. I pasted the command into terminal again and it says, "Nothing to do." confirming that. Also, take note there is no package on Fedora repos (even with rpmfusion installed) with a name containing "sndio" nor "soundio":
```bash
$ sudo dnf install libsndio-devel
Last metadata expiration check: 2:57:44 ago on Fri 20 Mar 2020 02:18:05 PM EDT.
No match for argument: libsndio-devel
Error: Unable to find a match: libsndio-devel
$ sudo dnf search sndio
Last metadata expiration check: 2:58:01 ago on Fri 20 Mar 2020 02:18:05 PM EDT.
No matches found.
$ sudo dnf install libsoundio-devel
Last metadata expiration check: 3:00:33 ago on Fri 20 Mar 2020 02:18:05 PM EDT.
No match for argument: libsoundio-devel
Error: Unable to find a match: libsoundio-devel
$ sudo dnf search soundio
Last metadata expiration check: 3:00:47 ago on Fri 20 Mar 2020 02:18:05 PM EDT.
No matches found.
```

**Comment by PhysSong** [comment]
It seems like LMMS failed to parse the `FORCE_VERSION` you passed. Can you try removing it and see if it works?

**Comment by poikilos** [comment]
(oops, now the value of my FORCE_VERSION is in the main issue comment)

I tried leaving out the -DFORCE_VERSION option, and still cannot compile.
