### ISSUE TITLE
Add relevant codebase file-names (Expert job)

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#5432]
### Enhancement Summary
It could be a huge help for development, if a superDev (yea new word..) would append issues with names of related cpp-files. Eg make it understandable where the code related to this exact issue should be located.
This will of cause not be really possible 'backward' -or at least only in fragments, but for new Issues it could be a feature.
#### Justification
New developers would be serious helped from it
It could also be said, that it is 'needed' because of the almost complete lack of comments in almost every file, witch is a huge disadvantage 
I think review-of-code should include that descriptive and fulfilling comments for *everything* should be mandatory.

#### Mockup
A new line in the bottom of the Issue where one or several *.cpp files are inserted by a 'superDev'

**Comment by zonkmachine** [comment]
No. The few times you need to ask someone about what files to look in you just ask on our discord channel. I'm closing this.
