### ISSUE TITLE
"Sample not found"

### ISSUE THREAD

**Issue by afonsov22** [LMMS/lmms#5435]
# LSSM says that samples weren't found on a saved project, even tough they are installed and working if i make a new one. Can someone help me

#### Logs
<details>
  <summary>Click to expand</summary>
<pre>

</pre>
</details>

**Comment by musikBear** [comment]
(You should use the template as listed. -your isue is not a general issue, but something wrong on your own pc, but lets see..)
Where have you saved the project that cant open? Is it inside the same folder as your new projects?
If not move it the that location, and browse to the project from sidebar| myComputer, and then open it from the correct location. Does that solve it?
If not open a support-request in either Forum, or Discord
Read: http://lmms.io/forum/viewtopic.php?f=1&t=4740
Section links

**Comment by Spekular** [comment]
Closing, but feel free to continue the conversation here if you wish. Otherwise i would recommend the #support channel on Discord.
