### ISSUE TITLE
Add BPM tags to built-in .ogg samples

### ISSUE THREAD

**Issue by ttepatti** [LMMS/lmms#5439]
### Enhancement Summary

It would be helpful to include BPM tags for the built-in samples, particularly those in the "beats" folder. For example, "909beat01.ogg" has no BPM tag.

#### Justification

All of these beats sound great on their own, but its hard to know how to use them in a project without knowing the BPM of the sample. This goes for all of the loops within the "beats" folder.

#### Mockup

If we assume the 909beat01.ogg sample is 140 BPM, a BPM tag could be added to the file name like so:

`909beat01.ogg` renamed to `909beat01_[140].ogg`

I think this would be a pretty quick change as there are only 13 included beats.

Thanks! :)

**Comment by Spekular** [comment]
We intend to replace all the factory samples eventually (due to copyright concerns) so this might be for naught.

However, *if* these samples are renamed, an upgrade routine should be written to make sure we don't break previous projects. It would also be best to apply the same naming to all other built in loops, such as the samples in the "bassloops" folder.

**Comment by Spekular** [comment]
Milestoning for 1.3. If the new sample library isn't ready by then I suppose we may as well fix this in the meanwhile.

**Comment by FrozenPixell** [comment]
if its okay i would like to take this one

**Comment by Spekular** [comment]
@FrozenPixell go ahead! As an additional note, please use the following format when renaming them:

> If the samples are loops and have defined tempos, put their tempos at the end of their filenames preceded by a hyphen like this: Drum Loop - 120 bpm.

(From https://github.com/LMMS/assets/blob/master/Samples/README.md)

**Comment by BoxedFruits** [comment]
Has this issue been handled yet? I would love to tackle it! I found a tool that can get the BPM of .ogg files.

**Comment by Spekular** [comment]
> Has this issue been handled yet?

I'm not sure. @FrozenPixell, how's it going?

> I found a tool that can get the BPM of .ogg files.

Most DJ software also has this functionality built in. That includes free software like Mixxx, and free versions of commercial options like Serato DJ Lite, VirtualDJ, and others. You would also need to manually confirm that the detected BPM is correct.

**Comment by FrozenPixell** [comment]
Im really sorry, I completely forgot :|
Ill get on it right away haha

**Comment by mirk0dex** [comment]
#6747

**Comment by zonkmachine** [comment]
> #6747
> 
> ~**Edit**: I found out that LMMS has an "assets" repo. Gonna use that.~ **Edit 1**: nevermind, I reopened the PR.

I think the asset repo is an attempt to create a new sample library from scratch. You're in the right place.
