### ISSUE TITLE
Add select-able snapping/magneting to Song-Editor

### ISSUE THREAD

**Issue by ttepatti** [LMMS/lmms#5440]
### Enhancement Summary

Select-able snapping would allow you to choose snapping on every beat, half beat, step, etc. in a way similar to other DAWs, such as FL Studio.

For more information on how their alternative snapping works, see here:

https://support.image-line.com/action/knowledgebase?ans=47

![image](https://user-images.githubusercontent.com/7002801/78467867-686d4e80-76df-11ea-8d57-6f9025f50fb6.png)

#### Justification

It's not very obvious that you can hold Ctrl to disable snapping and move a sample or pattern off-beat. Additionally, having a sample start perfectly on the off-beat in the middle of a bar is difficult to do without looking at the MSEC counter at the top of the screen to find the exact division between the two beats. Having the ability to snap to a half-bar would alleviate this problem.

**Comment by Spekular** [comment]
Already implemented in master branch by #4973
