### ISSUE TITLE
I'm removing my account.

### ISSUE THREAD

**Issue by CYBERDEViLNL** [LMMS/lmms#5444]
Hi all!

One of these days I'm going to remove my GitHub account. I don't know what this does for my open PR's so if you find them usefull please make backups.

For clarification; this has nothing to do with LMMS and everything with GitHub and it's owner.

Thanks for a great time!

**Comment by zonkmachine** [comment]
Going rogue? :crying_cat_face:

> I don't know what this does for my open PR's so if you find them usefull please make backups.

According to [this GitHub](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/deleting-your-user-account) manual page, your issues and PR's remain open but assigned to the 'ghost' account.

> Deleting your user account removes all repositories, forks of private repositories, wikis, issues, pull requests, and pages owned by your account. Issues and pull requests you've created and comments you've made in repositories owned by other users will not be deleted - instead, they'll be associated with our Ghost user.

Thanks for your contributions and hope we see you again!

**Comment by CYBERDEViLNL** [comment]
> Going rogue? :crying_cat_face:

Yes :-(

In my opinion MS isn't a ethical company at all and I want nothing to do with it, but GitHub hosts so many awesome projects and that conflict has been eating on me for a while now.

> Thanks for your contributions and hope we see you again!

Thanks and hope to see all of you too in the future! :heart:
