### ISSUE TITLE
Buzzing between tracks in song-editor in lmms

### ISSUE THREAD

**Issue by DivyanshuMJ** [LMMS/lmms#5445]
There is an glitch in lmms, when i am listening the song by running the song-editor of saved project file, then in between of the song some type of buzzing sound is coming, I don't know why is this happing but that makes me not to use lmms for making songs.I also have a video of that bug, please help or i will see any other software for making tracks and also i will not recommend lmms to any one.

And, How can i add the video for proof ?

**Comment by Spekular** [comment]
Please keeo the conversation in #5443 and don't open new issues.
