### ISSUE TITLE
windows get stuck behind top bar

### ISSUE THREAD

**Issue by MichaelDavid53** [LMMS/lmms#5446]
this is my first time installing and using the program so I'm not sure if it's a bug or a feature, but it seems to be possible to get any of the movable windows stuck behind the top bar with no way to access the handles to drag them back. there might be a setting but it's not obvious. there doesn't seem to be a way to move the top bar or shrink or unview it to show the objects behind it--they just get stuck and lost.

**Comment by Spekular** [comment]
To the far left you'll find a vertical scrollbar that you can use to scroll
up and reveal them. If the scrollbar hasn't updated, you can grab any
window and slide it out of the visible area and then back. This should
update the scrollbar range.

**Comment by Spekular** [comment]
While unintuitive, this isn't technically breaking. Therefore I think it's reasonable to mark this invalid or wontfix, since we eventually hope to transition to a UI without the detached windows.

**Comment by zonkmachine** [comment]
@MichaelDavid53 I believe it's this issue: https://github.com/LMMS/lmms/issues/765
