### ISSUE TITLE
Finishing 1.2

### ISSUE THREAD

**Issue by JohannesLorenz** [LMMS/lmms#5448]
This post is a summary about [open issues](https://github.com/LMMS/lmms/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+milestone%3A1.2.2) and [open PRs](https://github.com/LMMS/lmms/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+base%3Astable-1.2) for 1.2. You can get that list by following those 2 links, and it should be equal to the tables below. The list is updated daily by me, but feel free to update it yourself anytime (e.g. if you finished your task and are now waiting for someone else).

**Issues without PR**

| Issue        | Topic       | Next task | Waiting for  |
| ------------- |:-------------| -------------|-----------------|
| (none)   | - | - | - |

**Open PRs**

| PR            | Topic       | Next task | Waiting for  |
| ------------- |:-------------| -------------|-----------------|
| (none)   | - | - | - |

Note: If you think you should not be on the list, please remove yourself or add a comment below this post.

**Comment by tresf** [comment]
Merged #5486, left feedback on #5360, requested changes for #5487.

**Comment by JohannesLorenz** [comment]
I'll leave this open just in case we'll do an 1.2.3.

**Comment by PhysSong** [comment]
Should we keep this open?

**Comment by JohannesLorenz** [comment]
No, good point. I'll close my issue.
