### ISSUE TITLE
VST GUI no longer shown

### ISSUE THREAD

**Issue by BlackLight** [LMMS/lmms#5450]
### Bug Summary

VST GUI is no longer showing.

#### Environment

- Arch Linux latest install
- Wine: 5.5
- LMMS: 1.2.1.629 built from the `lmms-git` AUR package.
- Qt version: 5.14.2

#### Steps to reproduce

- Install the latest versions of `wine`, `lmms-git` and `qt` on Arch Linux.
- Open any VST .dll from Vestige (N.B. I have tried with plugins that used to work until a few weeks ago and are on the list of [supported plugins](https://lmms.io/wiki/index.php?title=Tested_VSTs)).

#### Expected behavior

The VST plugin is loaded and the GUI is shown.

#### Actual behavior

The VST plugin is loaded but no GUI is shown.

#### Screenshot

![screenshot](https://i.ibb.co/KmBqhxn/2020-04-13-12-26.png)

#### Logs

The following message is shown on the standard output when the VST is loaded:

```
QObject::connect: Cannot connect (nullptr)::subWindowActivated( QMdiSubWindow* ) to SubWindow::focusChanged( QMdiSubWindow* )
```

p.s. I've also tried to launch LMMS with `LIBGL_ALWAYS_SOFTWARE=1` as advised in [#5323](https://github.com/LMMS/lmms/issues/5323) but that doesn't change the situation.

**Comment by harsan81** [comment]
Had the same issue as well using LMMS 1.2.1 Appimage on Pop!_OS 19.10 
Wine Staging (5.6) & Qt 5.9.7

**Comment by PhysSong** [comment]
Can you try changing the "VST plugins embedding" setting on the settings dialog?

**Comment by harsan81** [comment]
Changed the Plugin Embedding on Settings to "No Embedding" and voila, it's working!
Thank you very much PhysSong!!!

**Comment by tank-trax** [comment]
wow... just stumbled on this had the same issue using wine-staging 6.5 on Buster... No Embedding did the trick

thx!!
