### ISSUE TITLE
Add "Open File Location" option to right-click menu in My Samples browser

### ISSUE THREAD

**Issue by ttepatti** [LMMS/lmms#5453]
### Enhancement Summary

An additional button should be added when right-clicking a sample or folder containing samples in the "My Samples" browser, allowing users to open the file or folder's location in their system's file browser.

#### Justification

This makes it easy to locate sample files on your system from within LMMS if you need to edit, delete, rename, or otherwise modify your samples.

#### Mockup

This screenshot is from FL Studio, but displays the functionality.
![image](https://user-images.githubusercontent.com/7002801/79172989-47ce8400-7dc4-11ea-8b18-8d53a3628d56.png)

**Comment by michaelgregorius** [comment]
#5454 implements a first solution which opens the folder that contains the selected file. It looks like this:
![5453-OpenContainingFolder-Cropped](https://user-images.githubusercontent.com/9293269/79227152-c5939d80-7e5f-11ea-9307-cec9d005279e.png)
