### ISSUE TITLE
Choosing how many outputs with JACK

### ISSUE THREAD

**Issue by trebmuh** [LMMS/lmms#5456]
LMMS 1.2.1 here.
When going to Edit -> Settings -> Audio settings, choosing JACK (JACK Audio Connection Kit), then double-clicking on the "_green 2_" to select the number of channels, this pop up appears :

![lmms](https://user-images.githubusercontent.com/8705846/79381049-a7ae6180-7f61-11ea-8f2a-6860b0d9e32c.png)

Shouldn't the user be proposed with choice here? Right now, the only possibility is "2".

**Comment by Spekular** [comment]
Consolidated into #1467
