### ISSUE TITLE
CrossoverEQ: Invalid checkGate function

### ISSUE THREAD

**Issue by JohannesLorenz** [LMMS/lmms#5461]
### Bug Summary

From plugins/CrossoverEQ/CrossoverEQ.cpp:
```
const float d = dryLevel();
const float w = wetLevel();
double outSum = 0.0;
for( int f = 0; f < frames; ++f )
{
	outSum = buf[f][0] * buf[f][0] + buf[f][1] * buf[f][1];
	buf[f][0] = d * buf[f][0] + w * m_work[f][0];
	buf[f][1] = d * buf[f][1] + w * m_work[f][1];
}
	
checkGate( outSum );
```

There are at least 2 bugs in this calculation:

1. It seems to calculate outSum incorrectly - it's assigned rather than incremented in the loop, so only the last sample is actually checked. (Thanks to @DomClark for reporting)
2. `outSum` must be divided by `frames` in the end. (caused by #5460)

#### Steps to reproduce

Unclear

#### Expected behavior

Unclear

#### Actual behavior

Unclear. It could lead to too early or to late stopping of effect processing, and thus to clipping.

#### Affected LMMS versions

all

**Comment by thmueller64** [comment]
I've noticed another inconsistency: The comment to `Effect::checkGate` states that "Effects should call this at the end of audio processing", which is not the case here. The buffer is processed after (if fixed above) incrementing `outSum`. In, e.g., Bitcrush.cpp and Flanger.cpp `outSum` is calculated using the processed buffer, while in CrossoverEQ.cpp, Amplifier.cpp and BassBooster.cpp it is calculated before processing. From my understanding, calculating `outSum` should happen after processing. This would also open the possibility to move the `outSum` calculation entirely to `Effect::checkGate` in order to avoid these errors. How should we proceed in your opinion?

**Comment by JohannesLorenz** [comment]
@thmueller64 thanks for the analysis. Funnily, @DomClark and me found this issue 2 days ago, too. Like he said, it must be the effect's output we look at, not the input (consider a reverb effect). Even for simple amplifiers, we need to look at the output, in order to use the "gate" properly (the gate works by silencing the effect when the output falls below the gate).

> This would also open the possibility to move the `outSum` calculation entirely to `Effect::checkGate` in order to avoid these errors.

We were wondering why this had not been done in the core. Maybe flexibility (but what for?) or saving runtime by reusing an effect from the core (but that would not be much runtime)?

I'd say let's start by fixing the single effects without yet touching the core. If it's all done, one may move it into the core in a separate commit. But I may be convinced otherwise.

**Comment by thmueller64** [comment]
Thanks for your answer and suggestions @JohannesLorenz.
> We were wondering why this had not been done in the core. Maybe flexibility (but what for?) or saving runtime by reusing an effect from the core (but that would not be much runtime)?

For now, I also can not think of a compelling reason to leave this up to the user.
Currently, `m_autoQuitDisabled` is `True` by default (see @DomClark s explanation for this in #5352), but `outSum` is always calculated, even if it is not used according to this default. The performance impact is probably negligible, but that would be another reason to move it into the core, where `m_autoQuitDisabled` can be checked beforehand. 
A possible workaround could be using an overload like `void Effect::checkGate( sampleFrame *buf, const ffp_t frames )`, calculate `outSum` and call `void Effect::checkGate( double outSum )` from there.

> I'd say let's start by fixing the single effects without yet touching the core. If it's all done, one may move it into the core in a separate commit. But I may be convinced otherwise.

I think so, too. I could go for it, if you're okay with that.

**Comment by JohannesLorenz** [comment]
> The performance impact is probably negligible, but that would be another reason to move it into the core, where m_autoQuitDisabled can be checked beforehand.

That's another good point for adding the out sum calculation into `Effect::checkGate`.

> I think so, too. I could go for it, if you're okay with that.

That would be cool. :+1:

**Comment by JohannesLorenz** [comment]
Should I leave this open for `plugins/Eq/EqEffect.cpp`, or should we open a new issue report? I think this one will auto-close as soon as stable-1.2 will be merged to master, so I'd vote for opening a new one.
