### ISSUE TITLE
Lmms Crashes when using M-audio mini 32 midi keyboard

### ISSUE THREAD

**Issue by victor00101** [LMMS/lmms#5476]
### Bug Summary
lmms crashes using ALSA without any vst plugins, when I play my midi keyboard on it.  Not right away, but in the middle of my projects unpredictably using m-audio mini 32 midi keyboard

#### Steps to reproduce
use the keyboard for 20 minutes or a half-an-hour

#### Expected behavior
I'm not sure, that lmms shouldn't crash

#### Actual behavior
crashes even if I'm not using the keyboard to play music.  But after 3 hours of playing music with usb midi keyboard unplugged.  Lmms keeps playing music

#### Affected LMMS versions
version 1.1.3 64-bit debian branch through ubuntu 18.04.4 LTS

#### Logs
<details>
  <summary>Click to expand</summary>
<pre>

</pre>
</details>

**Comment by PhysSong** [comment]
> version 1.1.3

LMMS 1.1.3 is too old. Could you try the 1.2.1 release from our official homepage?

**Comment by victor00101** [comment]
okay

**Comment by victor00101** [comment]
I tested it, and it didn't crash..  and played fine until I tried to connect some of the buttons to master volume.  But I could use it just fine otherwise during playback, and further more just leaving the keyboard plugged in did Not cause any problems either.   

Thanks for recommending LMMS 1.2  This seemed to have fixed 9/10's of the problems.
