### ISSUE TITLE
Crash when loading a project: ipatch_container_init_iter: assertion 'IPATCH_IS_CONTAINER(container)' failed

### ISSUE THREAD

**Issue by bluebear94** [LMMS/lmms#5483]
### Bug Summary

When loading the attached project, LMMS crashes.

[bpkwn.mmpz.zip](https://github.com/LMMS/lmms/files/4568957/bpkwn.mmpz.zip)

#### Steps to reproduce

Unzip the attached file, which contains bpkwn.mmpz. Open LMMS and then open bpkwn.mmpz.

#### Expected behavior

The project loads completely.

#### Actual behavior

LMMS gets stuck on loading Track 8/10, then crashes. See logs below.

#### Affected LMMS versions

1.2.1

#### Logs
<details>
  <summary>Click to expand</summary>
<pre>
VST sync support disabled in your configuration
Cannot load library /usr/lib/lmms/libcarlapatchbay.so: (libcarlabase.so: cannot open shared object file: No such file or directory)
Cannot load library /usr/lib/lmms/libcarlarack.so: (libcarlabase.so: cannot open shared object file: No such file or directory)
Cannot load library /usr/lib/lmms/libcarlabase.so: (libcarla_native-plugin.so: cannot open shared object file: No such file or directory)
QtXmlWrapper::loadXMLfile(): empty data
fluidsynth: error: fluid_sfloader_load(): Failed to open '/home/kozet/Documents/lmms/samples/': File is not regular, refusing to open it.
fluidsynth: error: Unable to open file '/home/kozet/Documents/lmms/samples/'

** (lmms:267903): CRITICAL **: 17:13:11.946: ipatch_container_init_iter: assertion 'IPATCH_IS_CONTAINER(container)' failed
Segmentation fault (core dumped)
</pre>
</details>

**Comment by PhysSong** [comment]
The project file has no path for the target SoundFont file. In this case, LMMS treats an empty string as the relative path to the SoundFont file and calls `fluid_synth_sfload()` with the directory.
It seems like version 2 of `libfluidsynth` crashes if the C runtime library allows opening directories as files. I think it's a bug of the upstream, but it's possible to avoid that kind of situation on LMMS' side.

**Comment by PhysSong** [comment]
FluidSynth 2's `fluid_synth_sfload()` even fails for a text file or an image file. :confused:

**Comment by PhysSong** [comment]
I think the crash is from a bug of `libinstpatch`. The library was not checking for errors(the failed assertion in this case) when it should.
```gdb
#0  0x00007fffd954eab9 in ipatch_dls2_inst_first (iter=0x7fffffffd170)
    at /usr/src/debug/libinstpatch-1.1.4-1.1.x86_64/libinstpatch/IpatchDLS2Inst.c:406
#1  0x00007fffd9550d8a in ipatch_dls_nullify_fixups (reader=0xac4a00)
    at /usr/src/debug/libinstpatch-1.1.4-1.1.x86_64/libinstpatch/IpatchDLSReader.c:534
#2  0x00007fffd9550d8a in ipatch_dls_reader_finalize (object=0xac4a00)
    at /usr/src/debug/libinstpatch-1.1.4-1.1.x86_64/libinstpatch/IpatchDLSReader.c:204
#3  0x00007fffd9493290 in g_object_unref () at /usr/lib64/libgobject-2.0.so.0
#4  0x00007fffd963c407 in new_fluid_instpatch
    (fcbs=<optimized out>, filename=<optimized out>, sfont=0xa1c5c0)
    at /usr/src/debug/fluidsynth-2.1.2-1.1.x86_64/src/utils/fluid_sys.c:217
#5  0x00007fffd963c407 in fluid_instpatch_loader_load
    (loader=<optimized out>, filename=<optimized out>)
    at /usr/src/debug/fluidsynth-2.1.2-1.1.x86_64/src/sfloader/fluid_instpatch.c:656
#6  0x00007fffd9624d6d in fluid_synth_sfload
    (synth=0xad1e00, filename=0xde9c60 "/home/phys/Documents/lmms/samples/", reset_presets=1)
    at /usr/src/debug/fluidsynth-2.1.2-1.1.x86_64/src/synth/fluid_synth.c:4619
```

However, it seems like `fluid_is_soundfont()` fails without crashes for directories or unsupported files. I think we can use it as a workaround.

**Comment by PhysSong** [comment]
Should we add the workaround for 1.2? It's a simple test.
For references, here's the link for the upstream bug report: https://github.com/swami/libinstpatch/issues/48

**Comment by zonkmachine** [comment]
> Should we add the workaround for 1.2? It's a simple test.

Yes.

**Comment by JohannesLorenz** [comment]
I'll try this issue.
