### ISSUE TITLE
theme problem when renaming a track

### ISSUE THREAD

**Issue by trebmuh** [LMMS/lmms#5484]
### Bug Summary

When renaming an instrument, selecting a part of the string isn't very readable because the background color is pretty much the same than the normal color.

#### Steps to reproduce
Rename a track (right-click left-double-click).
Select a part of it.

#### Expected behavior
You can easily see the selection because of a background colors difference

#### Actual behavior
You can't easily see the differences because the difference isn't strong enough. 

#### Screenshot
("_space + tra_" selected):

![lmms-rename-background-color](https://user-images.githubusercontent.com/8705846/81237376-c56e6400-8fff-11ea-941f-1e784c83f0a3.png)

#### Affected LMMS versions
1.2.1

#### Logs
no logs needed

**Comment by zonkmachine** [comment]
Yes. It's the default theme that is a bit on the dark side.

**Comment by trebmuh** [comment]
Still affecting 1.2.2.

**Comment by DigArtRoks** [comment]
See my pull request for fixing this. You can also straight away edit data/themes/default/style.css in your lmms installation directory. No need to rebuild lmms.

**Comment by trebmuh** [comment]
Awesome, it fixes it!
Thank you very much.
