### ISSUE TITLE
Missing LADSPA when loading Socceroos-Progress

### ISSUE THREAD

**Issue by trebmuh** [LMMS/lmms#5485]
### Bug Summary

When loading this demo, we've presented with an error window telling us that 2 LADSPA plugin are missing.

#### Steps to reproduce
Open LMMS
Open the demo song named "Socceroos-Progress"

#### Expected behavior
It loads fine.

#### Actual behavior
It loads with an error message.

#### Screenshot
![lmms-Socceroos-ladspa-error](https://user-images.githubusercontent.com/8705846/81358056-b22dc800-90d5-11ea-8151-428e673309b7.png)

#### Affected LMMS versions
1.2.1

#### Logs
no logs

**Comment by zonkmachine** [comment]
I don't get this message and the project plays without any errors.
The missing plugins are both Calf. Can you try and add an effect to an instrument and search 'calf' and see if any plugins show up and if Reverb and Exciter are missing.

I believe you're on linux, right?
Where did you get lmms-1.2.1?

**Comment by trebmuh** [comment]
Mmm ok, I know where the issue is nested then. I'm build my own .deb package and I'm emptying the calf-ladspa package to avoid the famous c[l,r]ash between calf-ladspa and calf-lv2. So, if the Socceroos-Progress demo is calling the a calf-ladspa plugin, that's expected to get this message then.
Sorry for the noise. Closing here then.
