### ISSUE TITLE
LMMS 1.2.1 fails to build with Qt 5.15.0RC

### ISSUE THREAD

**Issue by demmm** [LMMS/lmms#5486]
### Bug Summary
Qt 5.15 introduces the need to include QPainterPath.  Try to build with 5.15.0-rc, and the build fails at multiple places due this missing include.
#### Steps to reproduce
Build with Qt 5.15
To workaround this issue, following patch was used, fixes the build, app runs properly with it:
https://github.com/KaOSx/apps/blob/master/lmms/qt5.15.diff

#### Affected LMMS versions
1.2.1

**Comment by JohannesLorenz** [comment]
@demmm Many thanks for reporting and analyzing!

I'll turn this into a PR now.

**Comment by JohannesLorenz** [comment]
Will be fixed by #5498 .

@demmm Can you please test if my fix works? Just clone `https://github.com/JohannesLorenz/lmms.git`, checkout `fix/#5486` and see if it compiles.

**Comment by tresf** [comment]
> Will be fixed by #5498 

Merged, closing.
