### ISSUE TITLE
Sample "bassdrum01.ogg" has a really low volume hiss

### ISSUE THREAD

**Issue by DeRobyJ** [LMMS/lmms#5493]
### Bug Summary
https://github.com/LMMS/lmms/blob/master/data/samples/drums/bassdrum01.ogg
Contains a constant hiss at around 3800Hz

#### Steps to reproduce
Drag and drop the sample in a track.
Put a high-pass filter at 3000Hz.
Put the Clip effect to amplify around 40dB.
Hear the hiss. I analyzed it using Audacity and its Spectrogram, since it's not simple to see this hiss in a Spectroscope such as LMMS Equalizer.

#### Screenshot
![image](https://user-images.githubusercontent.com/6437521/81555545-10360600-9389-11ea-9ce2-3e983a011f4e.png)
![image](https://user-images.githubusercontent.com/6437521/81555618-3065c500-9389-11ea-8f94-b581784564c5.png)

#### Affected LMMS versions
Tested in 1.2.1, but the file hasn't been changed since 2007, so pretty much every version ever.

#### Workaround
If interested in using this sample right now, just drop in a Notch Filter at 3800Hz, with resonance 2 or above.

![image](https://user-images.githubusercontent.com/6437521/81555842-918d9880-9389-11ea-9765-bd02d5b65fc6.png)

**Comment by Spekular** [comment]
IMO this is a wontfix issue, as it will be irrelevant when the sample library is replaced.

Fixing the sample shouldn't be hard either, but it does technically break user projects.

**Comment by DeRobyJ** [comment]
Yeah, I'm just leaving this here for those that might be interested. I got this info from a subscriber from my channel who needed this sample.

**Comment by Spekular** [comment]
> I'm just leaving this here for those that might be interested.

Then do you mind if I close it? It will still show in searches for "bassdrum01" or when browsing closed issues.
