### ISSUE TITLE
Icons and comboboxes mismatch in arpeggiator in Instrument Editor

### ISSUE THREAD

**Issue by qnebra** [LMMS/lmms#5494]
### Bug Summary
Misaligned icons and combobox in Arpeggio editor inside Instrument Editor

#### Steps to reproduce
Open Instrument Editor, Go to "Chord stacking & arpeggio" and look down.

#### Expected behavior
Evenly aligned icons and combobox.

#### Actual behavior
Misaligned icons and combobox, which create feeling of amateur project, regarding of it's actual impressive quality.

#### Screenshot

![Adnotacja 2020-05-12 195908](https://user-images.githubusercontent.com/11295229/81728725-304dee00-948b-11ea-9524-fd03b8d1353d.jpg)

#### Affected LMMS versions

1.2.1 and further. I don't have previous versions installed to confirm that other versions than 1.2.1 were affected.

**Comment by zonkmachine** [comment]
Confirmed. The combo boxes are more narrow so their content doesn't fit.

**Comment by zonkmachine** [comment]
![new](https://user-images.githubusercontent.com/6368949/81746279-7e241f80-94a6-11ea-88a7-3358f03bb5df.png)

1.2.1 to the left and some older version to the right. The arpeggiator area has been pushed upward a bit so the components has less vertical space to share.

**Comment by zonkmachine** [comment]
The issue is there already in 1.2.0-RC5

**Comment by qnebra** [comment]
Theoretically, simplest solution will be to increase combobox height to have arrow icon centered in it. But, this was global or local thing?

**Comment by zonkmachine** [comment]
Yes. I think this could be a global thing that just happened to be troublesome in the arpeggiator control section.

**Comment by musikBear** [comment]
ehhhr
is this 
![image](https://user-images.githubusercontent.com/6662066/81850613-83da3d80-9558-11ea-8c3e-714a5e0bdbe8.png)
the subject..
The triangle ..not centred?

... Wont keep me awake ....

**Comment by qnebra** [comment]
> Yes. I think this could be a global thing that just happened to be troublesome in the arpeggiator control section.

Well, nope. There were at least two different comboboxes height in lmms.

Also Bear, I see your comment before deleting. This is kind of details which create overall feeling of quality in software.

**Comment by zonkmachine** [comment]
> Well, nope. There were at least two different comboboxes height in lmms.

Probably because there are two combobox classes being used. QComboBox and our own [Combobox](https://github.com/LMMS/lmms/blob/master/include/ComboBox.h) class.

**Comment by he29-net** [comment]
I don't think the main problem is that two different classes are used, but rather that some of the Comboboxes have a fixed height set to 22 and some do not. I ran into the issue a few days ago when adding a new Combobox to the instrument Misc tab -- without setting the fixed height, it would "collapse" just as pictured here.

The proper way to address it would be probably by setting a minimum height in the Combobox class. Or at least to use a shared global constant, to get rid of all the "22" constants scattered around the code.

**Comment by DigArtRoks** [comment]
I  made a new pull request as I messed up a bit my fork, trying to keep it synced.
