### ISSUE TITLE
Setting new loop markers is complicated

### ISSUE THREAD

**Issue by JohannesLorenz** [LMMS/lmms#5505]
### Bug Summary

We have loop markers, e.g. in the song editor, to only play a part of a song in a loop. That part will be colored green. Originally, you could use middle and left click to comfortably select the markers.

There must have been some PR that changed the behavior on master. Now, only the right click works, and it always sets that marker that is closest to your mouse.

I find this not practical. I often have large/all parts of my song selected in the loop (projects saved like that) and then want to reduce the loop to the first or last few bars. Typically because the last bars are where I'm currently continuing the song. This gets difficult:

```
<------------------------ currently selected ------------------------------>
                                                wanted selection <-----> 
```

Setting the left marker of "wanted selection" requires me to scroll through half the song! (The right marker is easy, ofc)

Aside from that, there is no tooltip explaining how the new behavior is to be used. But I'm for switching back to the old behavior.

#### Steps to reproduce

See sketch above.

#### Expected behavior

Not being forced to scroll through half of your song.

#### Actual behavior

Scrolling through half of your song.

#### Affected LMMS versions

Current master. not on `stable-1.2`

**Comment by Spekular** [comment]
The old controls are unusable on devices without a MMB (every laptop I've
used), and surprisingly many hotkeys are already used for this area.

LMB: Set playhead position
Shift + LMB: Group select everything in this range
Ctrl + LMB: Nothing (Same as LMB)
RMB: Set loop pos
Ctrl + RMB: Set loop pos (fine adjust)
Shift + RMB: Nothing (Same as RMB)

Alternatively, perhaps we could rework these to be more consistent instead:

LMB: Playhead pos
RMB: Unused/reserved for menu

Ctrl + LMB: Group select
Ctrl + RMB: Unused/same as RMB

Shift + LMB: Loop Start (snapping)
Shift + RMB: Loop End (snapping)

Ctrl + Shift + LMB: Loop Start (fine)
Ctrl + Shift + RMB: Loop End (fine)

Another proposal was to grab based on.the visible area, so both start and
end position are always grabbable regardless of zoom/pan. However, I think
I might prefer reworking the shortcuts.

**Comment by JohannesLorenz** [comment]
We could at least keep allowing the middle mouse key next to the new behavior, unless we plan to use it otherwise. That would at least help with the left marker.

> Shift + LMB: Loop Start (snapping)
> Shift + RMB: Loop End (snapping)

I like this even more. Tooltips would help to find out what the right shortcuts are.

**Comment by Sawuare** [comment]
I changed the behavior in #4034.

**Comment by Rossmaxx** [comment]
Can we close this one, since #6382 has been merged?
