### ISSUE TITLE
Natural scrolling is backwards for knobs, spinboxes

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms#5507]
Quoting https://github.com/LMMS/lmms/pull/5360#issuecomment-630293637:

> the mouse-wheel emulation is completely bazaar on Mac (disregarding the reverseness), the scrolling emulates a list/document moving at an animated pace. This isn't how it behaves in apps like GarageBand [...] whereas the LMMS MASTER VOLUME SLIDER works properly with this gesture but the knobs and spinboxes do not. This may mean we have a bug somewhere?

**Comment by PhysSong** [comment]
Qt 5.7 provides `QWheelEvent::inverted()` which allows checking for natural scrolling. FYI, LMMS currently requires Qt 5.6.

**Comment by tresf** [comment]
> Qt 5.7 provides QWheelEvent::inverted() which allows checking for natural scrolling. FYI, LMMS currently requires Qt 5.6.

Why does the master volume work just fine though?

**Comment by PhysSong** [comment]
Because `QAbstractSlider` uses that by default.

**Comment by tresf** [comment]
> Because QAbstractSlider uses that by default.

So a precompiler check plus the inverted should do it?

**Comment by PhysSong** [comment]
Copied from #5510:

| File | Needs Flip |
|-----|------------|
| src/gui/editors/AutomationEditor.cpp | ✅(excluding horizontal scroll) |
| src/gui/editors/PianoRoll.cpp  | ✅(note panning) |
| src/gui/editors/SongEditor.cpp  | ✅(excluding horizontal scroll) |
| src/gui/widgets/ComboBox.cpp | ✅  |
vsrc/gui/widgets/Fader.cpp | ✅  |
| src/gui/widgets/Knob.cpp | ✅ |
| src/gui/widgets/LcdSpinBox.cpp | ✅ |
| src/gui/widgets/TabWidget.cpp | ✖️(no, but could use proper card-swipe support) |
| src/tracks/Pattern.cpp | ✅(Velocity for beat/bassline editor) |

@tresf Said:
> I'm not sure about where the `delta()` is used for some of the editors.  If it's scrubbing/scroll bars, that's behaving properly, but I notices that note panning on Piano Roll needs it so I might be missing something.
