### ISSUE TITLE
The ability to stretch / slow down parts audio without changing pitch

### ISSUE THREAD

**Issue by KCGD** [LMMS/lmms#5519]
I was watching a production stream of someone using abelton and it had a really cool feature of stretching specific parts of audio (in this case vocals) to fit parts of the baseline, and without changing the pitch of the audio.

Ive faced this issue alot, having to re import vocals from another editor because it didnt fit the beat.
[This video](https://youtu.be/TwY9jZxMJx8?t=296) has a really good example of this feature

**Comment by Spekular** [comment]
Duplicate.

**Comment by Spekular** [comment]
For example:
#3103
#4653

And mentioned here: #1471
