### ISSUE TITLE
Enhancement: export between loopmarkers (LM)

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#552]
Enhancement: export between loopmarkers (LM)
This idea is about Export of project-parts from LM1 to LM2, but it has two flavors. 
1) export part as ogg/wave
2) export part as mmp
Both could be powerfull additions to current functionality. 
1. should be reasonable doable
2. is a different story. For 2 There will be a lot of dependencies (mixer, FXs, LFOs etc.) but i think it will be possible as batch-jobs done directly on the 'parent' mmp??

**Comment by Umcaruje** [comment]
Implemented by #1482, should be closed.

**Comment by tresf** [comment]
Thanks for the cleanup mr uros!
