### ISSUE TITLE
Almost all presets has no envelopes 

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#5527]
# Bug Summary
I have searched, but no issue seams to address this, but Almost all presets in LMMS has no envelopes. The zasfx presets does, but they are of cause internal, and not related to LMMS own ENV/LFO tab.
Most problematic are the *samples*, where many clicks and pops, but i have not been through all preset, so i cant say how many we got with artefacts.

#### Argumentation 
On youTube LMMS is ridiculed and dissed as being of low quality. Popping and clicking presets is part of this. It is reasonably easy to fix. No coding is needed, just edit and resave.
Any user with good understanding of the presets, can do this.

#### Steps to reproduce
Open any default preset

#### Expected behavior
LMMS presets ought to have an envelope, that prevents clicks and pops from attack ao release. A default All-pass-filter could also be set. 
This  would not inflict old projects or any saved presets. All presets has envelopes hardcoded in both project-file, and preset-files.

#### Actual behavior
Most presets does not have either envelope or default filter

#### Affected LMMS versions
All

#### Suggested method
All presets are renamed with an _ infront of current name with a batch-script, then they can be saved with new envelopes, without the leading underscore, and nothing would have changed. Total backward comparability is preserved.

**Comment by dj-pixus** [comment]
This is a job for me. Can I do it?

**Comment by musikBear** [comment]
@dj-pixus Wooo!
Are you *done*?
Have you tested *every* preset in both instruments and samples?
That was quick!  👍

**Comment by dj-pixus** [comment]
I fixed the problematic presets of builtin instruments except for LB302, as it does not support envelopes.
Samples are a different thing. The default preset of the AFP is what needs to be changed in order to eliminate the "problem", the samples themselves have little to do with it. If you cut a wave at a non-zero value, then it will unavoidably click, this is just how sampling works.
Again this is one of the situations where we have to find balance between making it attractive both to newbies and professionals.

**Comment by musikBear** [comment]
The replacement of all samples has been 'on the table' for .... guess 5-6 y...!
Once it was well in the makings, but then everything went seriously sour. Work was lost, so was people. I cant see a replacement in the near future 
About Bitinvader envelopes:
They are **fine**! Those are an example og how  *all* our presets *should* have been made! They are perfect, The *Sustain* is not inverted, it is *made* with a value, that is best for *that* preset!
but take a look at Nescaline |*Detune lead*, f.i.
Here you have an envelope/ filter setup as:
![image](https://user-images.githubusercontent.com/6662066/84413356-c99a2c80-ac10-11ea-9975-1487a6f040fd.png)
Or rather NO setup..
That preset is not finished. It needs an envelope, and (perhaps) an all-pass-filter
Being a *lead* it would make sense to design it as
![image](https://user-images.githubusercontent.com/6662066/84413771-5cd36200-ac11-11ea-80d1-9ca95757a408.png)
There are many presets that looks like Nescaline |*Detune lead*, some sounds 'ok', but others does not, then there are some with an envelope, but they are too loud, and clip default, others are to low
Each *Factory-preset* needs to be inspected, and tested for sensible-envelope loudness and perhaps have an All-pass added. That last thing is 'something' i have read that all ..'producers' always does, and it is frowned apron, it it is not done.. Honestly, i have never done that on my own presets. Most often i add a LP-but opens the FREQ 100%, that is in a way an All-pass
But the bad ones are those with NO envelope
![image](https://user-images.githubusercontent.com/6662066/84416148-1c291800-ac14-11ea-83fd-ebe109a02954.png)
...Yelp
Then there are CUTOFF and RESO tab, havent thought about their ENVs at all ⛑️

**Comment by dj-pixus** [comment]
The sustain, i mean the lowest value is 0, highest is 1 at most instruments. But in BitInvader, 0 is 1 and 1 is 0. Not a problem with the sounds itself, but a technical inconsistency that made me recheck everything 6 times.
About allpass filters: I really don't see much sense using them. Can be used for phase effects, but nothing really useful in this situation. A low-pass can be good for killing inaudible frequencies, but where it needs to be, there already is.
And don't forget that the presets should honestly show what that plugin can do on its own.
There are some presets that i didn't set an envelope for, just because it sounded good as is.You know, if it ain't broke, then don't fix it.

**Comment by musikBear** [comment]
> You know, if it ain't broke, then don't fix it.

👼 to *that*

**Comment by Clutterbyte** [comment]
i did some changes to initial presets that could give a better audio experience. it is a mmpz compressed.
[example.zip](https://github.com/LMMS/lmms/files/4974933/example.zip)

**Comment by musikBear** [comment]
@Clutterbyte The issue is already coded in a PR -Have you made **code-changes**, or are your changes made inside lmms?

**Comment by qnebra** [comment]
There were changes only inside lmms project, not in code. Also clicking was more to attack with value 0.0, not to hold have value 1.0

**Comment by Clutterbyte** [comment]
> @musikBear  "The issue is already coded in a PR -Have you made **code-changes**, or are your changes made inside lmms?" ive changed some presets giving you a idea about some changes in generators (initial volumen, ahdsr, etc). keeping similar to original configuration, removing unnesesary volume saturation and poping sounds, i didnt modified code.

**Comment by musikBear** [comment]
@Clutterbyte Oki, but there is an issue with your idea, or perhaps a better expression would be: Your idea is good, but it must be done differently.
The issue is, that the ENV is general! There is only *one*. All LMMS instruments will initially be 'born' with exact same ENV-setting.
In 1.2.2 That is an absolute awful setting:
![image](https://user-images.githubusercontent.com/6662066/88484130-d4b0de00-cf6c-11ea-81f2-660cde08c962.png)
-And it is initially *disabled*
But That i have changed in code to 
![image](https://user-images.githubusercontent.com/6662066/88484192-31ac9400-cf6d-11ea-9905-e9b7f87d41cf.png)
This ENV does not click or pop, and the sound-profile is 'piano-like'
But as you can see, it is not enabled!
That has a sad sad reason..
Unfortunately **all** *presets* of AFP are created in an awful way.
All our AFP-**presets** are made on 'Vanilla'-AFP, without any settings in ENV! -then the soundfile is added
...So
**ALL** AFP-**presets** has the exact *same* Envelope... 👎 
But it is *disabled*!
**That** is the reason we cant have an *enabled* envelope **at all**!
If our default envelope is enabled, **all** AFP-**presets** will play *wrong* -Eg that would destroy all older projects! A default *enabled* envelope, would break the holy-graal : **Backward-compatibility**!
#Sigh#...
So *Why* is *Your* idea in your file actually a great idea?
Because used in a new way, it solves both issues!
Your setups should be used as a *template*!
If we made a template with your settings, the users could choose that template, and have fine instruments sounds for all Vanilla-instruments!
So your work should result in a *new template* in the **template collection**, thats how i like yours setups; For a new template!

**Comment by dj-pixus** [comment]
Envelope is saved in presets themselves, and even presets are hard-coded in projects. So why would a default setting break compatibility, I ask?

**Comment by Clutterbyte** [comment]
@musikBear ok, so envelope cannot start active and with a diferent configuration in every generator, but as i understand, is posible to change another parameters in vanilla instruments like organic volume from 100 to 50%, watsyn oscs to -12db, etc?

**Comment by musikBear** [comment]
@dj-pixus 
> So why would a default setting break compatibility, I ask?

Because non of the AFP-*presets* has any envelope at all!
If we then added a default envelope, that envelope would for some odd/ ugly reason be invoked for all soundfile-presets in LMMS, and a lot of the AFP-presets plays only correctly, if they are allowed to play without an envelope.
Its a really dumb thing.. The 'solution' is to create sane envelopes for every AFP-preset, then the envelope-data would be in the preset, and the default-envelope would be ignored -Thats a *l o t* of envelope edits, especially since current samples are 'meant' to be replaces with better and also C0-licence samples... 'some' day...

@Clutterbyte Yes it a parameter **IS** changed, then it is written in the file. The issue with all Samples (AFP-presets are that *nothing* has been changed! Browse trough them in **mySamples** all has no own envelopes and all looks like the current default:
![image](https://user-images.githubusercontent.com/6662066/88596943-77995300-d066-11ea-8a50-0868bf9e038c.png)
5 taken at random..

**Comment by Clutterbyte** [comment]
@musikBear ive an idea: make that lmms recognize old projects (created in previous version) and automatically for no break projects with AFP, disable envelope if it is off.
it could work but tell me if its impossible.

------------------------------------------------------------------------------------------------------------------------------------------
[Mmpz.zip](https://github.com/LMMS/lmms/files/4992241/Mmpz.zip)

this zip contains modifications in original lmms templates getting more natural sounds in these kits (adding ladspa reverb).

Example:

[Comparison between new and old Clubmix.zip](https://github.com/LMMS/lmms/files/4992306/Comparison.between.new.and.old.Clubmix.zip)

**Comment by musikBear** [comment]
@Clutterbyte 
>  make that lmms recognize old projects (created in previous version) 

It has been suggested many times :p
It is not 'directly' impossible, and upstream it may even be a necessity, but it is not wanted.  The issue is that we already has several version-dependencies, and it gets messy.

> this zip contains modifications in original lmms templates getting more natural sounds in these kits (adding ladspa reverb).

Sorry No! That we can not use! Those instruments would technically be *presets*, and then they belong in the folder **My-presets**.
That could however be an option. Making a collection of all native instruments, with fitted Envelopes, and some LADSPA effects as well. -A group of base-presets :)

**Comment by Clutterbyte** [comment]
@musikBear 
> Sorry No! That we can not use! Those instruments would technically be _presets_, and then they belong in the folder **My-presets**.
> That could however be an option. Making a collection of all native instruments, with fitted Envelopes, and some LADSPA effects as well. -A group of base-presets :)

No problem! i would known if The 'solution' of "sane envelopes for every AFP-preset" will come before budislav´s ui change, or it isnt planned in a near future.

**Comment by musikBear** [comment]
> budislav´s ui change

I think that is far away. 2.0 or .. -Not sure its being worked atm

**Comment by Veratil** [comment]
> 
> 
> > budislav´s ui change
> 
> I think that is far away. 2.0 or .. -Not sure its being worked atm

I want to target single window UI for 2.0. Currently the only work on it is the #5261. There's a lot of core work that needs to go into it though.

**Comment by musikBear** [comment]
> I want to target single window UI for 2.0

Sound great -One thing to at least consider could be ability to *scale* all text -The bat 🦇 whispered :p
