### ISSUE TITLE
Can't give a segment the same name as the track

### ISSUE THREAD

**Issue by gatodev** [LMMS/lmms#5528]
#### Affected LMMS versions

1.2.1

**Comment by Veratil** [comment]
This isn't a bug, but [normal behavior](https://github.com/LMMS/lmms/blob/dac59a5fa056048ccc4655b06102406ac7c502ac/src/tracks/Pattern.cpp#L890-L891).

**Comment by gatodev** [comment]
But for what?
When I rename a track to the same name as a segment, all the same of the segments disappear. Is that expected, too?

**Comment by Veratil** [comment]
It was done in [this commit](https://github.com/LMMS/lmms/commit/461cb2bb3cd1c6173fa0f1730a3ee83d247f3d13) as part of [this PR](https://github.com/LMMS/lmms/pull/3699). As for why, I wasn't around then so I don't know. @PhysSong I see you were around when this PR was open, do you recall anything about this?

**Comment by PhysSong** [comment]
@Veratil No, it's was there way much before that PR.
https://github.com/LMMS/lmms/commit/dd1db7d2b76a1c677642f610d3501a6f3b42218b

**Comment by Veratil** [comment]
Interesting. I don't see a reason why other than "improve appearance".

**Comment by zonkmachine** [comment]
Let me see If I get this right. When we create a new pattern we set the name to the track name here:

https://github.com/LMMS/lmms/blob/a05306131b29ae29af2eac89794f5461f0521567/src/tracks/Pattern.cpp#L61

Then some people think that's a bit spammy (I tend to agree with that after removing the code to filter out the track name), so we forbid lmms to write that name on the pattern. It's better to not set the name to the track name in the first place if we don't want it there. I think this should be fixed somehow.

**Comment by zonkmachine** [comment]
Something like this. It will make a whole lot of tracks out there reveal hidden track names. I don't know what to do about that though.

```patch
diff --git a/src/tracks/Pattern.cpp b/src/tracks/Pattern.cpp
index 26cc1c9..f6924cf 100644
--- a/src/tracks/Pattern.cpp
+++ b/src/tracks/Pattern.cpp
@@ -56,7 +56,6 @@ Pattern::Pattern( InstrumentTrack * _instrument_track ) :
        m_patternType( BeatPattern ),
        m_steps( MidiTime::stepsPerTact() )
 {
-       setName( _instrument_track->name() );
        if( _instrument_track->trackContainer()
                                        == Engine::getBBTrackContainer() )
        {
@@ -1049,12 +1048,7 @@ void PatternView::paintEvent( QPaintEvent * )
diff --git a/src/tracks/Pattern.cpp b/src/tracks/Pattern.cpp
index 26cc1c9..f6924cf 100644
--- a/src/tracks/Pattern.cpp
+++ b/src/tracks/Pattern.cpp
@@ -56,7 +56,6 @@ Pattern::Pattern( InstrumentTrack * _instrument_track ) :
        m_patternType( BeatPattern ),
        m_steps( MidiTime::stepsPerTact() )
 {
-       setName( _instrument_track->name() );
        if( _instrument_track->trackContainer()
                                        == Engine::getBBTrackContainer() )
        {
@@ -1049,12 +1048,7 @@ void PatternView::paintEvent( QPaintEvent * )
        // pattern name
        p.setRenderHint( QPainter::TextAntialiasing );
 
-       bool isDefaultName = m_pat->name() == m_pat->instrumentTrack()->name();
-
-       if( !isDefaultName && m_staticTextName.text() != m_pat->name() )
-       {
-               m_staticTextName.setText( m_pat->name() );
-       }
+       m_staticTextName.setText( m_pat->name() );
 
        QFont font;
        font.setHintingPreference( QFont::PreferFullHinting );
@@ -1064,13 +1058,10 @@ void PatternView::paintEvent( QPaintEvent * )
        const int textTop = TCO_BORDER_WIDTH + 1;
        const int textLeft = TCO_BORDER_WIDTH + 1;
 
-       if( !isDefaultName )
-       {
-               p.setPen( textShadowColor() );
-               p.drawStaticText( textLeft + 1, textTop + 1, m_staticTextName );
-               p.setPen( textColor() );
-               p.drawStaticText( textLeft, textTop, m_staticTextName );
-       }
+       p.setPen( textShadowColor() );
+       p.drawStaticText( textLeft + 1, textTop + 1, m_staticTextName );
+       p.setPen( textColor() );
+       p.drawStaticText( textLeft, textTop, m_staticTextName );
 
        // inner border
        if( !( fixedTCOs() && beatPattern ) )
(END)

```

**Comment by Spekular** [comment]
> It will make a whole lot of tracks out there reveal hidden track names. I don't know what to do about that though.

Should be possible to write an upgrade routine that clears the pattern name if it matches the track name. It wouldn't break anything, since those names are already invisible the behavior is unchanged for existing projects.

**Comment by zonkmachine** [comment]
Yes. I have a rather poor track record with DataFile.cpp though, so I pass that on to someone else. ;)

**Comment by Spekular** [comment]
If anyone gets around to this before me, go ahead. Just assigning myself so I don't forget that I want to work on this.
