### ISSUE TITLE
stk path is hardcoded to be in `/usr`

### ISSUE THREAD

**Issue by hfiguiere** [LMMS/lmms#5535]
### Bug Summary

The STK mallet path is hardcoded (on Linux) to be in `/usr` in the source code

#### Steps to reproduce

See https://github.com/LMMS/lmms/blob/8c7e63b35b1f929dff7176406a7a1c69e6262d92/src/core/ConfigManager.cpp#L559

#### Expected behavior

A configurable option at build time.
Context: in flatpak it is `/app`, which also happen to be the prefix because it is all built there.
See https://github.com/flathub/io.lmms.LMMS/issues/4

#### Actual behavior

Assume it is in `/usr`

#### Affected LMMS versions

1.2.1, but reading the code, same for master.

**Comment by PhysSong** [comment]
@hfiguiere #5804 will fix this for `master`. For 1.2, you can still use your patch.
