### ISSUE TITLE
lmms 1.1.3 - Fedora Linux 32 - Not able to load VST plugin - Freezes on project loading

### ISSUE THREAD

**Issue by paddymahadeva** [LMMS/lmms#5540]
### Bug Summary
Tried to load an existing LMMS project which has some VST-plugins. The project open is stuck at 71% with message, loading VST-Plugin

#### Steps to reproduce
Installed new lmms from fedora repo using
`sudo dnf install lmms`

Launched LMMS from command line & saw the below error

```
Notice: could not set realtime priority.
"Cannot load library /usr/lib64/lmms/ladspa/imp_1199.so: (/usr/lib64/lmms/ladspa/imp_1199.so: undefined symbol: mk_imps)" 
"Cannot load library /usr/lib64/lmms/ladspa/sifter_1210.so: (/usr/lib64/lmms/ladspa/sifter_1210.so: undefined symbol: q_sort)" 
Connection established.

Stream successfully created

```
Post this tried to load an existing project created in lmms (linux), the load is stuck at 71% & says "Please wait while loading VST-plugin".

In console I see the below error
```

us::open: Can not get ibus-daemon's address. 
IBusInputContext::createInputContext: no connection to ibus-daemon
```

#### Affected LMMS versions
LMMS 1.1.3

**Comment by DomClark** [comment]
Can you download the latest AppImage (version 1.2.1) from our website (https://lmms.io/download#linux) and see if you can still reproduce the issue there?

**Comment by akimaze** [comment]
I think this could be the bug with Plugin Embedding. Please try set Embedding to **No embedding** in Settings, More info at https://github.com/LMMS/lmms/issues/5104
