### ISSUE TITLE
Being able to modify automation data within song editor automation track

### ISSUE THREAD

**Issue by sorath72** [LMMS/lmms#5541]
So I searched for a similar feature on the feature request and apparently it seems to nether exist or couldn't find one. Being able to make curves and modify automation in the song editor track of the automation would be a great tool. Cause sometimes its hard to see where the automation begins and ends for the song editor automation when your calculating it via the measuring tool on top it can get a little confusing as what you need. Thats why I suggest similar to other daws out there won't mention its name but starts with an F and ends with en O. They are able to modify automation data within the song editor itself making it much easier to create those smooth and precise automations in such a quick way to doing it too.

Just wanted to say I like the program but having such a feature like this would make automation lots better when using the song editor.

**Comment by Spekular** [comment]
Technically mentioned in #5495, but this report is more specific so I won't mark duplicate.

However, I'll consolidate this into #4877. Discussion about this suggestion can continue here even though it's marked as closed.

**Comment by RoxasKH** [comment]
I completely agree with this. Most of the times i don't need precise values for my automations, and i feel like automation editor should be an extra for precise automations, and automations directly in songeditor would make the workflow faster and more intuitive. Also as said this way you can references the track you're going to automate.

This is common in most of modern daws, here's some examples

<details>
  <summary>Example</summary>

  ```
  FL Studio
  ![FL](https://user-images.githubusercontent.com/40141826/90386104-5daac900-e084-11ea-8954-a51892e996fd.PNG)

  Reaper
  ![reaper](https://user-images.githubusercontent.com/40141826/90386165-71eec600-e084-11ea-92e9-3c9e0b591576.png)

  Logic Pro
  ![logic pro](https://user-images.githubusercontent.com/40141826/90386191-7a470100-e084-11ea-9528-9d1ab946c8dd.jpg)

  Cakewalk
  ![cakewalk](https://user-images.githubusercontent.com/40141826/90386206-816e0f00-e084-11ea-944d-9efc1ea19194.jpg)

  Ableton
  ![ableton](https://user-images.githubusercontent.com/40141826/90386220-87fc8680-e084-11ea-9d90-0ddc16632114.jpg)

  ```
</details>

Even if 2.0 mockup will make things alot easier having songeditor on the top and automation editor on the bottom, i feel like this should anyway be implemented.

<details>
  <summary>2.0</summary>

  ```
  ![immagine](https://user-images.githubusercontent.com/40141826/90386473-e9245a00-e084-11ea-85d4-2b72543b2065.png)

  ```
</details>

**Comment by Audits9o9** [comment]
This is a great idea imo
i made a concept image of what it could look like in LMMS

<img width="798" height="283" alt="Image" src="https://github.com/user-attachments/assets/4a9d9cdd-37c8-46be-ab71-e1b71e08bf81" />
