### ISSUE TITLE
Lmms 1.2.1 vestige cannot load carla's libs and VST GUI not rendering, but the sound works ;)

### ISSUE THREAD

**Issue by svsdval** [LMMS/lmms#5545]
Debian Sid, LMMS 1.2.1, vestige cannot load carla's libs and VST GUI not rendering/updating.

Log acquired by running Lmms through console:
https://pastebin.com/M4S7NApN
![Снимок экрана_2020-06-26_18-22-15](https://user-images.githubusercontent.com/6585839/85852717-5d582500-b7db-11ea-8bd8-6752de0dbf4b.png)

**Comment by SecondFlight** [comment]
Hi! Thanks for the report. Did you get LMMS through [lmms.io](https://lmms.io/download#linux) or from your distro?

**Comment by svsdval** [comment]
I got LMMS from lmms.io in logs i run lmms-1.2.1-linux-x86_64.AppImage :)

**Comment by SecondFlight** [comment]
Thanks for the info. Sorry, I missed the link.

**Comment by PhysSong** [comment]
If you still have this problem, can you try changing embedding method on the settings dialog?

**Comment by svsdval** [comment]
Work fine only if plugin embedding = no embedding.
On qt embedding, plugin update some while and then all plugin window turning to gray color
