### ISSUE TITLE
Can't move decay and reverb wheels on LMMS v1.2.x under Windows 10

### ISSUE THREAD

**Issue by Bronxio** [LMMS/lmms#5546]
### Bug Summary
I came from this [forum thread](https://lmms.io/forum/viewtopic.php?f=17&t=33156&sid=67c1c27baf1b092fbf86d5b0e9e313df).

When I add an effect to any instrument under Windows 10, I can't move the wheels "decay" and "reverb": the mouse acts like there isn't any control in that zone. If I create a project, save it, open it under other OS (Windows 7 and Ubuntu is what I've tested as well) or under a version <1.2.0 on any OS, I can change the values. I've reproduced this behaviour in other machine as well, but the user musikbear told in the forum he used v1.2.1 under Windows 10 and couldn't reproduce it: maybe some OS setting?

If only I could say what's different between the musikbear's machine and mines! Do not hesitate on asking me to get more info and tests!

#### Steps to reproduce
In a new project, add: my samples --> instruments --> bassslap01.ogg to the song editor. Then, click on it and, on its window (sorry, I don't know the name of this kind of window), click on the "FX" tab. Click on "Add effect", and select the ReverbSC one. Now, three wheels appears for that effect: W/D, decay and reverb.

#### Expected behavior
Mouse looks like a hand when passing it over the wheels and can change the decay and gate values.

#### Actual behavior
Mouse doesn't change when passing over the decay and reverb wheels and can't change their values: they are stuck and double-click doesn't work. It's like those controls are just "painted". (W/D one works fine)

#### Screenshot
Here you have a quick [video](https://youtu.be/UIv3yM69_bY): this is 1.2.1 under Windows 10 in machine 1 (I have two for testing). You'll see non-default values in decay and reverb because musikbear changed them on his machine.

#### Affected LMMS versions
I've found the actual behaviour on 1.2.0 and 1.2.1 (I've checked some previous versions -1.1.3 and 1.1.90- as well and no problem at all). But only under Windows 10 in two different machines (Intel and AMD): checked under Windows 7 as well in both machines (and 1.1.3 on Ubuntu on machine 1), and can't reproduce the actual behaviour with any version.

#### Logs
<details>
  <summary>Click to expand</summary>
<pre>

</pre>
</details>

**Comment by Spekular** [comment]
This is the expected behavior if you have "keep effects running without input" enabled, and I believe this is a duplicate issue.

**Comment by Spekular** [comment]
Duplicate of: #5352

Relevant: #4749

**Comment by Bronxio** [comment]
You're right. I tested that and wheels are working with that option disabled. Thank you!
