### ISSUE TITLE
Sample track cuts off first buffer of the sample

### ISSUE THREAD

**Issue by russiankumar** [LMMS/lmms#5553]
I believe a similar issue has been posted before, but that was related to export of audio files, while this one is related to playing the project itself.

### Bug Summary
When using sample tracks to play anything, the first buffer does not play. This is especially noticeable when used with kicks and snares, as the impact is greatly reduced. The sample tracks do work as expected when soloed.

#### Steps to reproduce
- Load a drum sample on a sample track
- Route it through an FX channel (not sure if this has anything to do with the bug, but that was the arrangement I had)
- Play it (possibly along with other instruments) in non-solo mode

#### Expected behavior
Sample plays from the beginning, delivering the entire sound as expected.

#### Actual behavior
Sample plays from one buffer (as measured in a similar issue) after the start of the sample, greatly reducing the impact of drums and/or other samples depending on a quick attack.

#### Affected LMMS versions
Was testing a master build (pulled latest from the `master` branch), but will update here with a comment on whether this happens with 1.2.1.

Unsure if extra information is required here, since the problem has more or less been pinned down, but am willing to share more info if so required.

**Comment by PhysSong** [comment]
The first commit of #4994 seems to fix this issue. I can confirm `stable-1.2` is okay.

**Comment by russiankumar** [comment]
I believe this is an issue only with `master`, so as it has been fixed, you may close this when the PR merges (though judging by the merge conflicts and the relative inactivity, I don't know how soon that'll be).

**Comment by PhysSong** [comment]
Fixed by e5f1007ebbec5b9ae6d576712bf2ca4676d09fbf.
