### ISSUE TITLE
Missing  lmms_1.2.2.tar.xz in the assets

### ISSUE THREAD

**Issue by trebmuh** [LMMS/lmms#5556]
Hi all.
Congratz for the 1.2.2 release!
It seems the lmms_1.2.2.tar.xz is missing from the assets on https://github.com/LMMS/lmms/releases

**Comment by PhysSong** [comment]
I was going to remove automatic `.exe` builds, but it seems like I moved `.tar.xz` as well. I'll upload it.

**Comment by PhysSong** [comment]
Uploaded, thanks!
