### ISSUE TITLE
Rack with controls to send Midi CC messages.

### ISSUE THREAD

**Issue by wujekbrezniew** [LMMS/lmms#5558]
I was looking for some workaround to try to automate Carla in LMMS 1.2.x and I found that if i launch external virtual controller (outside of LMMS of course) with capability of sending Midi CC messages and then I properly route this messages trough Jack, LMMS and Carla I can control anything i want.
So i started to thought why not add a controller to LMMS which will be capable of sending MIDI CC messages. This will solve many problems for example this one: https://github.com/LMMS/lmms/pull/4571
Btw. I think this request is bit similar to this: https://github.com/LMMS/lmms/issues/5508 

I have two ideas. First one is something similar to actual LMMS mixer, but with ability to chose MIDI channel and CC signal.
Second one is something similar to open source VST that I used for testing. Despite controllable sliders it has ability to create pads similar to launchpads. This will make LMMS a tool to play live performances or play drum kits with touch screens. I think this is even better than mixer-like MIDI Controller because will differ significantly and adds not only sliders but pads too.
New feature should be accessible from rack where now we have all buttons to access editors, controllers, notes etc... i mean here:
![image](https://user-images.githubusercontent.com/11708702/86541597-71ec9980-bf0e-11ea-97ce-f050c970a149.png)

Link to plugin code (GPLv2) and downloads: https://code.google.com/archive/p/pizmidi/

And screenshot of VST. I think this can be treated as an early mockup:
![image](https://user-images.githubusercontent.com/11708702/86541477-8a0fe900-bf0d-11ea-9487-22494a4d5393.png)

To clarify in this VST you can change channel and message signal by right clicking a pad.

**Comment by wujekbrezniew** [comment]
Closing as https://github.com/LMMS/lmms/pull/5581 fulfills my needs.

**Comment by Spekular** [comment]
Reopening until #5581 is merged.

**Comment by IanCaio** [comment]
Just merged #5581 , so I'm closing this one!
