### ISSUE TITLE
Carla build error

### ISSUE THREAD

**Issue by iurienistor** [LMMS/lmms#5568]
Hi,

I have the following compiling errors regarding carla plugin:

carla.cpp:350:88: error: invalid conversion from ‘float**’ to ‘const float**’ [-fpermissive]
         fDescriptor->process(fHandle, rBuf, rBuf, bufsize, fMidiEvents, fMidiEventCount);
                                                                                        ^
plugins/carlabase/CMakeFiles/carlabase.dir/build.make:75: recipe for target 'plugins/carlabase/CMakeFiles/carlabase.dir/carla.cpp.o' failed
make[2]: *** [plugins/carlabase/CMakeFiles/carlabase.dir/carla.cpp.o] Error 1
CMakeFiles/Makefile2:1227: recipe for target 'plugins/carlabase/CMakeFiles/carlabase.dir/all' failed

**Code:** from master branch
**GCC:** gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

**Comment by DomClark** [comment]
Duplicate of #4909, #4951, #5047?

**Comment by Spekular** [comment]
PhysSong says in #4951:
> you can try uninstalling carla-git and using carla instead.

**Comment by iurienistor** [comment]
Ok, anyway I think Carla project should decide what to do with this because it not part of LMMS only used in LMMS.
