### ISSUE TITLE
Channel selector for sidechain compressor

### ISSUE THREAD

**Issue by mnini** [LMMS/lmms#5576]
Title says it all.

**Comment by Spekular** [comment]
> Title says it all.

Not really. The sidechain compressor is controlled via the S/C level knob, which you connect to a controller, so there's no channels involved anywhere. If this has anything to do with sending two streams of audio to the sidechain compressor, it's blocked by #5108 either way.

I'm closing this, but if you'd like to elaborate perhaps it could be reopened.

**Comment by mnini** [comment]
So, I suggest full linkage board. Like where you can pick audio streams, and select channel from specific place from internodes.

Technology for that is like object connector, which on construction registrates into global registry of different states from synthesis to final output for every channel.
