### ISSUE TITLE
AudioFileProcessor doesn't recognize AIFF loops

### ISSUE THREAD

**Issue by rdrpenguin04** [LMMS/lmms#5583]
### Enhancement Summary
AIFF audio files are unique in that they can contain additional instrument data, particularly looping. AFP should have the capability to detect these loops and (optionally?) apply them to the looping settings.

#### Justification
There are several other properties, but looping is a good start, and most instruments stored in AIFF format will have looping available. Unfortunately, there isn't a good tool to find the start/end points of the loop to then put into LMMS. I was recently working on porting some Nintendo 64 music, and they all use a compressed version of the AIFF format, and they use the built-in looping data. The only way I was able to get accurate looping was by using a hex editor to find the loop start and end points.

#### Mockup
N/A

**Comment by softrabbit** [comment]
> AIFF audio files are unique in that they can contain additional instrument data, particularly looping. 

Not that unique: https://sites.google.com/site/musicgapi/technical-documents/wav-file-format#smpl 

Related: https://github.com/LMMS/lmms/issues/2154

**Comment by rdrpenguin04** [comment]
Ah, did not realize that. Would you prefer me to add this issue onto that one, or should I keep it separate, since it's a different format?

**Comment by PhysSong** [comment]
It seems like `libsndfile` can read AIFF loop points, but LMMS never use it. The library provides [`SFC_GET_LOOP_INFO`](http://www.mega-nerd.com/libsndfile/command.html#SFC_GET_LOOP_INFO) command which allows getting the loop information from audio files(if exist).

**Comment by PhysSong** [comment]
Consolidated into https://github.com/LMMS/lmms/issues/6745.
