### ISSUE TITLE
macOS: Song Editor patterns won't snap to grid

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms#5584]
### Bug Summary

Something's very wrong on macOS with the song editor, the patterns won't snap to grid.

Since the default snapping behavior is common for composers, this renders LMMS mostly useless for users relying on this behavior.  This is a major detriment to any macOS user.

Tested:
* 🚫 broken: macOS 10.16 (beta)
* 🚫 broken: macOS 10.14

Oddly, it works when using the build of LMMS targeted at older platforms (<=10.8, but not the one targeted at >=10.13)

* **GOOD:** 1.2.0 (10.8 build)
    <img src="https://user-images.githubusercontent.com/6345473/87710323-9e58af00-c773-11ea-8bdd-a0a12ba0c4bc.gif" width="400px"/>

* **BAD:** 1.2.0, 1.2.2 (10.13 build)
    <img src="https://user-images.githubusercontent.com/6345473/87710316-9c8eeb80-c773-11ea-8f6d-3069ca6a89d5.gif" width="400px"/>

### Known Workarounds

None, except to revert to LMMS 1.2.0 targeted at macOS <=10.8.  At time of writing this, this older version works fine with newer macOS versions (e.g. 10.14, 10.15, 10.16 beta).

**Comment by PhysSong** [comment]
I can confirm it. Strangely, if I build LMMS 1.2.2 on macOS 10.15, everything works fine there.

**Comment by tresf** [comment]
@PhysSong I assume it's confused about a `Qt::ControlModifier` (or Meta)  key somewhere (which should help us find an upstream bug report), but I don't know where this flag is checked on stable.  Any pointers?

**Comment by PhysSong** [comment]
>  it's confused about a `Qt::ControlModifier` (or Meta) key somewhere

I think it's `TrackContentObjectView::draggedTCOPos()` for `master` and `TrackContentObjectView::mouseMoveEvent()` for `stable-1.2`.
BTW, this might be some compatibility issue between different OS versions and/or compiler versions, like #5582.

**Comment by PhysSong** [comment]
I've created macOS 10.14+ build with Qt 5.15.0 and tested it. It seems to fix both this and #5582. I will upload it to the release page and add a warning.

**Comment by tresf** [comment]
@PhysSong thanks for that.  I can confirm that it's working fine on 10.16 (beta) as well.  Shall we close these both as `upstream` ?

**Comment by fbbdev** [comment]
Hello, the same problem is still happening on MacOS 10.13.6 with the 10.13+ build. I've just redownloaded and tested it to be sure. I'm not an expert with MacOS development so I'm not sure whether it is safe to test the 10.14+ build on my 10.13 machine.

**Comment by tresf** [comment]
> I'm not sure whether it is safe to test the 10.14+ build on my 10.13 machine.

It won't harm to try.  If it's incompatible it will simply fail to run.

**Comment by fbbdev** [comment]
In fact it refuses to run, says it is incompatible with my system.
