### ISSUE TITLE
Supply all distributions with LMMS 1.2.2

### ISSUE THREAD

**Issue by JohannesLorenz** [LMMS/lmms#5587]
The goal is to supply all distributions/package managers with our new LMMS 1.2.2 (and to find out how to inform the distributions in general).

| Distribution   | current Version   | method to inform distributor | next task  |
|---|---|---|---|
| Arch | 1.2.2 :heavy_check_mark: | flag as outdated | - |
| Debian | 1.2.2 :heavy_check_mark:  | ? | ? |
| Gentoo   | 1.2.2 :heavy_check_mark:  | ? | -  | -  |
| Homebrew (macOS)  | 1.2.2 :heavy_check_mark:  | Open a pull request to https://github.com/Homebrew/homebrew-cask | - |
| openSUSE | 1.2.2 :heavy_check_mark: | @plater can be contacted directly | - |
| Ubuntu <fill version here>  | 1.2.1 :x: | [maybe follow this guide, including creating of a .deb package?](https://askubuntu.com/questions/27101/how-to-distribute-applications) | ? |

Feel free to edit anything or add distributions. Also feel free to post comments.

**Comment by plater** [comment]
Got the message, I'll update this morning

**Comment by Daniele71** [comment]
For openSuSE i already available in GeekOsDaw repo.

**Comment by JohannesLorenz** [comment]
@plater What's the status?

Or should the package from the GeekOsDaw repo be reused?

**Comment by plater** [comment]
lmms-1.2.2 has been in Tumbleweed and multimedia:apps since shortly after the update was brought to my attention

**Comment by JohannesLorenz** [comment]
ah now I see it. Thanks!

**Comment by Spekular** [comment]
Re: Debian: I found a few pages via [packages.debian.org's search](https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords=lmms), all of which have a link to this [Developer Information](https://tracker.debian.org/pkg/lmms) page. Should we contact debian-multimedia@lists.debian.org?

**Comment by trebmuh** [comment]
1.2.2 is now available in LibraZiK-3 . See the [Mastodon message](https://mastodon.xyz/@LibraZiK/104665754032663320).

**Comment by qnebra** [comment]
1.2.2 is avalaible in Debian Sid. https://packages.debian.org/sid/lmms and in Ubuntu 20.10 https://launchpad.net/ubuntu/+source/lmms/1.2.2+dfsg1-1

**Comment by qnebra** [comment]
And in Arch "community" repo: https://www.archlinux.org/packages/community/x86_64/lmms/

**Comment by PhysSong** [comment]
Ubuntu is a bit conservative, so they probably won't upgrade LMMS to 1.2.2 for Ubuntu 20.04. 20.10 will ship with 1.2.2.
@JohannesLorenz Can we close this now?

**Comment by JohannesLorenz** [comment]
> Can we close this now?

Yes. Thanks everyone for the infos/help!
