### ISSUE TITLE
Enhancement: Colors as Adition to comment-tracks

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#560]
comment-tracks are in milestone 1. I like the idea, but i think that other project-structure methods can be implemented -also-. How about letting the user select color on each note-container in songeditor. Different colors can then be used as structure in the project (i use dummy BB for that now, it works well, but simple color on the individual container would make that overhead redundent)  Colored blocks in songeditor are used in Ableton Live btw.

**Comment by Spekular** [comment]
@tresf to be consolidated into #1665.

**Comment by tresf** [comment]
This bug report has been consolidated (at least for now) into a placeholder #1665 for better color handling in general.  Feel free to update this bug report or the parent bug as needed.
