### ISSUE TITLE
Insert/remove bar buttons in Song Editor

### ISSUE THREAD

**Issue by allejok96** [LMMS/lmms#5602]
Seems like [back in 2006](https://github.com/LMMS/lmms/commit/b762ad706f0f51e309fa16e12c1f3c44e72dcec1#diff-ae607795716a886f388ce789ff37cc55L332) the insert/remove bar buttons was removed from song editor, keeping only the keyboard shortcut shift+insert. I just recently learned about this useful feature. Like pointed out in #5599 having keyboard-only features is not user friendly, due to lack of discoverability.

Why not bring back these buttons? This should be a very easy task, since the feature exists.

Would also be nice if this feature came to piano roll, but that would require a little more work I guess.

**Comment by PhysSong** [comment]
Hi! If you have ability to put it back, that will be great. Otherwise, someone else who looks for easy tasks can probably do this.
