### ISSUE TITLE
[LMMS 1.2.2, Linux Mint 20] Vestige doesn't load vsts

### ISSUE THREAD

**Issue by GingkathFox** [LMMS/lmms#5603]
# Please search the issue tracker for existing bug reports before submitting your own. Delete this line to confirm no similar report has been posted yet.

### Bug Summary
VSTs dont load in Vestige, even though LMMS says that its loading it.

#### Steps to reproduce
- get a vst, any vst
- attempt to load it
- profit(?)
#### Expected behavior
The VST is loaded and ready for use.
#### Actual behavior
The VST is never loaded.

#### Screenshot
![hmmmm](https://user-images.githubusercontent.com/33764485/88839089-8720b500-d1a8-11ea-964f-f2a1bbb1e440.png)

#### Affected LMMS versions
1.2.2

#### Logs
Where are logs stored?
<details>
  <summary>Click to expand</summary>
<pre>

</pre>
</details>

**Comment by GingkathFox** [comment]
Loading a effect vst (using the effects button) works fine though, and i also loaded my synth vsts (though obviously with no ui)

**Comment by Spekular** [comment]
Are you testing 32 bit or 64 bit VSTs?

**Comment by GingkathFox** [comment]
after this i learned that stable doesnt support 32bit, and forgot to close this

found a new bug in stable though, will make a new issue on that
