### ISSUE TITLE
Need to make Replace FX

### ISSUE THREAD

**Issue by NETMANSKY** [LMMS/lmms#5611]
# Please search the issue tracker for existing feature requests before submitting your own. Delete this line to confirm no similar request has been posted yet.

#### Mockup

There is uncomfortable to remove FX in chain only. It forces you to rebuild the chain again if you had mistake. Better to add a replace FX in this case. Is it?

**Comment by SecondFlight** [comment]
Duplicate of #2168.

Also, please consider removing the "delete this line to confirm no similar request has been posted" bit next time :)
