### ISSUE TITLE
LB302 filter doesn't adjust to sample rate correctly

### ISSUE THREAD

**Issue by dj-pixus** [LMMS/lmms#5615]
When exporting with a sample rate other than 44.1 kHz, LB302's filter frequency goes higher than the set value.

Steps to reproduce:
- Drag LB302 to the song editor and make some pattern.
- Set the filter so that its effect is hearable
- Export the project with oversampling or higher sample rate

Expected behavior:
The sound sounds the same as in the editor.

Actual behavior:
The filter frequency is higher than expected.

Tested on current master and 1.2.2 AppImage.

**Comment by thmueller64** [comment]
There was a similar issue with exports and oversampling that is now fixed on master. Could you try to reproduce this on a master build?

**Comment by dj-pixus** [comment]
Oh yes, master also has the issue. Investigating further, it is not a problem with oversampling, but with rendering at higher sample rates generally.
The real problem appears to be that LB302 filter does not adjust itself to the sampling freq.

**Comment by thmueller64** [comment]
I followed your steps to reproduce and compared the 44.1kHz export to a 96kHz and 192kHz export. The filter frequency appears to be the same for the exports, at least there is no noticeable difference. Could you please share a project file where the problem appears? Maybe it is related to more specific settings.

**Comment by dj-pixus** [comment]
Sure.
[lb302-bug.zip](https://github.com/LMMS/lmms/files/5047156/lb302-bug.zip)

**Comment by dj-pixus** [comment]
Sure.
[lb302-bug.zip](https://github.com/LMMS/lmms/files/5047165/lb302-bug.zip)

**Comment by thmueller64** [comment]
Could you please check out the PR above and see if this fixes the problem? For me the export now sounds the same for different sampling rates. The problem turned out to be related to the 24dB filter.

**Comment by dj-pixus** [comment]
I tested the PR and yes, the problem went away. LB302 works well now, but turns out there might be more similar bugs with other instruments. For example .ds presets behave strangely too, but I believe that's a different issue.
Anyway, the PR is right.
