### ISSUE TITLE
Time Stretching Audio

### ISSUE THREAD

**Issue by AbaddonBent** [LMMS/lmms#5624]
I've noticed that LMMS has a issue with time stretching meaning that the **sound quality with a sample is altered the lower or higher a note may go**. This may or may not be a feature, but it's quite odd.
To be able to edit a sample so that it only changes the pitch rather both speed and pitch would be a major improvement as working with only synths can be a pain especially if one **using a vst sampler, the problem would still be there as it continues to alter both speed and pitch** yet again.

I'm somewhat new to github issue reporting and how it may work, but will this be fixed in a later update perhaps?

**Comment by Spekular** [comment]
Duplicate of several existing issues: #495 #3103 #4653

**Comment by DouglasDGI** [comment]
> I've noticed that LMMS has a issue with time stretching meaning that the **sound quality with a sample is altered the lower or higher a note may go**. This may or may not be a feature, but it's quite odd.

In AFP, there's a dropdown box with the options "None", "Linear", and "Sinc".  Sinc is the highest quality interpolation, though it uses the most CPU.  If you're noticing quality degradation while using the Linear mode, switch to Sinc and there will no longer be any noticeable quality loss.
