### ISSUE TITLE
64bit VSTs on Linux are broken for some Wine versions

### ISSUE THREAD

**Issue by PhysSong** [LMMS/lmms#5630]
As of some version of Wine, `winegcc` requires `__cdecl`(equivalent to `__attribute__((ms_abi))`) calling convention for `main`. Older versions require the usual System-V calling convention.
It's okay with 32bit builds because those two conventions make no differences for `main()`.
They differ on 64bit, however, making `_argc` and `_argv` corrupted. As a result, `RemoteVstPlugin64` exits with the message "not enough arguments".
I'm not sure if adding `__cdecl` will break `RemoteVstPlugin64` for old `winegcc` or not at this moment.

Upstream report: https://bugs.winehq.org/show_bug.cgi?id=49138

**Comment by PhysSong** [comment]
It seems like they reverted some changes, so I had to remove `__cdecl` again in Wine 6.0-rc1. Having it where it's not needed leads to crashes.

**Comment by PhysSong** [comment]
It seems like Wine 4.10 to 5.22 are affected. The upstream reverted the problematic commit, see https://source.winehq.org/git/wine.git/commit/2e115ab4420e9595c956c082e76b603fa684be20.

**Comment by Rossmaxx** [comment]
Do we even use wine < 5.22 anymore? so close?

**Comment by messmerd** [comment]
We recently [updated our Wine dependency](https://github.com/LMMS/lmms-ci-docker/pull/17) to use WineHQ which is currently at version 9.9.

Closing this as completed.
