### ISSUE TITLE
There is a need for a local 'No-embedding' for VST

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#5631]
## Enhancement Summary 
No embedding for VST is selectable in Settings. That however also influence VSTs that has needs for no embedding, and they will have neither abilities to stay on top, or any of the other feature, we have in the embedding.

#### Justification
Because using 'No-embedding' globally, makes all VSTs UI disappear under the program, when they loose focus, working with 'No-embedding' is quite annoying. However those VSTs that has issues with especially drop-down-menus in own UI, must have 'No-embedding' invoked, in order to use them at all.
Therefore it would be of high value, if 'No-embedding' was selectable for a specific VST, in that VSTs UI
#### Mockup
Unfortunately there is a problem. LMMS does not have a general UI-component for both VST-instruments and VST-effects.
Before discussing methods for UI-options, i just want to hear all others opinion for the need of this feature, or if this flickering VST-UI actually should be treated as a **bug**, because that is also an angle.

**Comment by musikBear** [comment]
Just should mention that there is a 'work-around'
![image](https://user-images.githubusercontent.com/6662066/90318538-722a7c80-df31-11ea-87c4-e15956b1c4c7.png)
Here LMMS is windowed and the VST UI is no longer able to disappear under LMMS, even though it does not have focus, but then it is difficult to navigate inside LMMS

**Comment by DomClark** [comment]
> Because using 'No-embedding' globally, makes all VSTs UI disappear under the program, when they loose focus

There's an option to keep them on top of LMMS, that appears when embedding is turned off:
![image](https://user-images.githubusercontent.com/1873225/90401804-62787880-e096-11ea-992f-328586fe97f9.png)

> if this flickering VST-UI actually should be treated as a bug

The menu not working is a bug in the plugins, but we plan to add a workaround to our code. See #3918.

That said, I think this suggestion is a good idea.

**Comment by musikBear** [comment]
![image](https://user-images.githubusercontent.com/6662066/90537884-1b65b280-e17e-11ea-96c7-a79288043d1d.png)
Aughh.. Welcome to "my" world -I simply did not **see** that option for no-embedding
Blind as a 🦇 😭 
> *See 3918*.
That is good! 👍
