### ISSUE TITLE
Audio File Processor should detect loop points in wav files

### ISSUE THREAD

**Issue by SeanTheBermanator** [LMMS/lmms#5634]
#### Forcing the user to define the loop points practically a second time can be a time consuming/wasting task. Adding loop point detection will make edits a whole lot easier. It's very hard to replicate a good loop, which leads to noticeable clicks.

**Comment by Spekular** [comment]
Marking as a duplicate of #5583 since wav support is mentioned in the comments. Also relevant: #2154

**Comment by PhysSong** [comment]
Consolidated into https://github.com/LMMS/lmms/issues/6745.
