### ISSUE TITLE
The Audio File Processor should be able to set a separate audio file to specific notes in the same track.

### ISSUE THREAD

**Issue by SeanTheBermanator** [LMMS/lmms#5635]
#### Adding a button to the AFP window for assigning a new sample to specific notes is all that would be needed. When the file is chosen, the user must define the notes that sample is used in through a popup, an edit button would be available in case of any mistakes that are made. This can be done with up to 12 samples per AFP track.

**Comment by Spekular** [comment]
Duplicate of #4075 and several others.
