### ISSUE TITLE
Possibility for command line controlled export.

### ISSUE THREAD

**Issue by mnini** [LMMS/lmms#5637]
Greetings, 

I must admit one thing, the sound engine is far from rendered audio, therefore, for hearing a thing, I must render my audio.
However, I somehow struggle with all the clicks and freezing interface, EQ's are going visual even when rendering, therefore I would like to have a headless LMMS, with capacity to render tracks from command line.

Summary:
`lmms --headless render project.mmp audio.wav --bitrate=96000khz --sync=best --as-loop --between-markers`

**Comment by Spekular** [comment]
CLI rendering is already available, `lmms -r`

**Comment by Spekular** [comment]
Relevant: #3402
