### ISSUE TITLE
Actually doable automatization...

### ISSUE THREAD

**Issue by mnini** [LMMS/lmms#5641]
Look at some industrial grade DAW, to see how automatization works, it's that you should right click to anything, and it brings you to automatization, but it should be editable like vectors in illustrators, just with audio restrictions, also possiblity to record automatization would also be nice, I cannot find record button, but it's just maybe that I'm dumb...

**Comment by Spekular** [comment]
Closing in favor of several specific, actionable improvements listed in #4877.
