### ISSUE TITLE
Audio splitter

### ISSUE THREAD

**Issue by mnini** [LMMS/lmms#5642]
Not just send.fx, but actual splitting, that would enable audio to go two distinct ways out of one point, and mixer to merge it in another. Good loop could also handle feedback in this settings, therefore you can mix output to input before it, with balanced effects it shouldn't do red numbers, and it's really useful.

**Comment by SecondFlight** [comment]
Could you explain how this differs in function from send FX, specifically:
1) Route an instrument to channel 1
2) Send channel 1 to channels 2 and 3
3) Send channels 2 and 3 to channel 4
4) Send channel 4 to master

The setup described above allows you to split audio, join it back together, and add effects at all points. Is there something that audio splitting would do that this can't do?

**Comment by musikBear** [comment]
In respect to what   SecondFlight wrote, lmms can also create virtual instruments already, witch is one of the things audio-splitting  does, but we have it:
https://www.youtube.com/watch?v=J8MzUXf3TX0
