### ISSUE TITLE
Sidechain selects

### ISSUE THREAD

**Issue by mnini** [LMMS/lmms#5643]
Not using knob for defining sidechain input, but normal select box, with some text over there to see what or where it is...

There is possiblity to connect saidchain to something before fx...

Also possiblity to create a separate channel that doesn't mix with master just to use as sidechain input would be amazing.

**Comment by Spekular** [comment]
Would be possible with #5108 and #3817 implemented (especially with Umcaruje's suggestion).

Please put more effort into searching for duplicates and making well written reports. You've opened 8 issues in the last 20 minutes and the majority have been duplicates. May I suggest checking in the Discord before posting to see if the feature you want already exists or has an open issue? You could ask in #support.
