### ISSUE TITLE
Midi transforms

### ISSUE THREAD

**Issue by mnini** [LMMS/lmms#5644]
You select a midi, click on transform, you select e.g. tone stacking, and it generates midi that is tone-stacked, so you can edit it later, same for appregiators and stuff like that...

It should keep original midi, but create editable overlay with those midi effect over it...

**Comment by Spekular** [comment]
Already possible via the function tab, available for all instruments including VSTs. Closing as a duplicate of #3880, which would allow you to convert the arp to MIDI that can then be edited.
