### ISSUE TITLE
Need GUI scaling

### ISSUE THREAD

**Issue by Jaeyoon07031** [LMMS/lmms#5655]
I really wish there is GUI scaling because on 1920p monitors, the gui is too big so I need to actually move to see the whole vst plugin.
![screenshot](https://user-images.githubusercontent.com/12591074/91142659-1956a300-e6ec-11ea-8bcc-0263e746bbb1.png)

Many other DAW's have gui scaling and I think there's an overall need for more settings in LMMS.

**Comment by qnebra** [comment]
Lmms use system UI scale.

**Comment by musikBear** [comment]
related to accessibility ( #4590 #4473 #1935 omo.. ) / user ctrl over UI sizes and fonts
and very true. ( I have ailing eyesight and is having increasing serious issues with our UI )
However the illustrated  example is *with a specific VST*, and is not directly related to lmms own UI scaling
Should *accessibility* as such be consolidated ?

**Comment by ChaitanyaPTank** [comment]
For the Helm, you can click on "Helm" Logo and set size at 75%.
