### ISSUE TITLE
Sustain pedal problem fixed : how to use the solution ?

### ISSUE THREAD

**Issue by naniquolas** [LMMS/lmms#5659]
Hello,
I'm quite new on linux. I tried to use LMMS (1.1.3-7 and 1.2.2) but had problems with the sustain pedal : when playing real time from my MIDI keyboard, the sustain effect is ok ; but then it doesn't work when playing the recorded song. It seems someone already fixed this (https://github.com/LMMS/lmms/pull/3710/commits/8e29ad47725107842f5484ac60100f19a23b4641) but I don't understand how to use it on my own computer. Can you help me ? :)

**Comment by Spekular** [comment]
This commit is already merged into stable branch, so if you're using 1.2.2 the fix is already applied.

**Comment by naniquolas** [comment]
ok, thanks... Then I don't understand why I can't record the sustain pedal effects... Any idea ? (should I create a new issue ?)

**Comment by Spekular** [comment]
If it really isn't possible then yes, we should create a new issue, or reopen and repurpose this.

First though, I'll ask in the #support channel of the LMMS Discord and see if anyone has gotten sustain recording working in 1.2.

**Comment by Spekular** [comment]
Can you provide a step by step breakdown of how to reproduce this issue, and explain the difference between your expected behavior and LMMS's behavior? Qnebra on Discord kindly tested this and found that sustain worked as expected on both Windows and Linux. Their process was:
- Start recording in piano roll
- Enable sustain switch
- Play a few notes with sustain on
- Release switch
- Stop recording

Apparently, the notes were recorded as long as the switch was active.

**Comment by naniquolas** [comment]
Thank you for testing ! Here is how I processed (Ubuntu 18.04.5 LTS,  LMMS 1.1.3-7 and 1.2.2) :
- Plug my midi keyboard (a Casio Privia piano)
- Open LMMS
- Use a piano instrument (I tried with soundfount "UprightPianoKW-20190703.sf2", "musica theoriaV2 (GM)" and "steinway soundbank.sf2",   and VSTi "4 front piano")
- Start recording a piano roll (I play on my piano and the sound out from my computer is as expected, with sustain pedal working)
- Clic "stop"
- Clic "play" to play the recording
--> when playing the recording, it sounds different : the only difference is that sustain effects seem to be off ; each note recorded with sustain is much shorter than it sould.

**Comment by qnebra** [comment]
I think issue will be with libraries, not with lmms. I quickly tried some libraries which I had, "Equinox Grand Piano" especially. And none of them had infinite sustain, it always fade away after some amount of time.

**Comment by naniquolas** [comment]
In my case there is no difference at all wether I use the sustain or not :(
