### ISSUE TITLE
Better/more controls in the automation editor

### ISSUE THREAD

**Issue by leopardheart982** [LMMS/lmms#5662]
#### Justification
Moving around individual points one at a time is extremely inconvenient when you need to move several points at once, for example when importing a MIDI and there's a bit of space at the beginning that you want to remove. When you move notes around, generally you want to keep the automation in line with it, and current controls make that a very annoying task.

#### Mockup
![automation editor mockup](https://user-images.githubusercontent.com/54118364/91640248-1f999780-e9ea-11ea-8657-8ca7316f07c1.png)

**Comment by Spekular** [comment]
I'll close this as part of #4602
