### ISSUE TITLE
LFO Controller/Automation exports poorly

### ISSUE THREAD

**Issue by Firepal** [LMMS/lmms#5665]
### Bug Summary
Automating a property with an LFO Controller works fine in real-time playback, but it seems to be only *occasionally* sampled on export (regardless of the file format AFAIK), and sounds "stepped" as a result

#### Steps to reproduce
LMMS project file
[bugrep.zip](https://github.com/LMMS/lmms/files/5160846/bugrep.zip)

Listen to the project file first, and then export to WAV or some other format

<details>
if you want to do it manually with the default file:<br>

1. Add an LFO Controller with any settings (Sine wave and tempo-synced to Eight Beats for example)<br>
2. Connect it to a Coarse Detuning knob in the TripleOscillator<br>

3. Add a pattern with a long note and play it in the Song Editor; the TripleOsc should sound fine as expected<br>
4. Export it to some audio file format and listen to the exported file<br>
</details>

#### Expected behavior
The exported audio file sounds like the real-time playback of LMMS with no issues

#### Actual behavior
The exported audio file has very noticeable "jumps" in the LFO Controller

#### Screenshot
A little comparison of an exported file from LMMS (top track) and recorded real-time output from LMMS (bottom track) in Audacity
![an Audacity screenshot of two tracks](https://user-images.githubusercontent.com/29317321/91954367-fc305e80-ed01-11ea-8d89-24da76305a65.png)

[bugrep-aup.zip](https://github.com/LMMS/lmms/files/5160953/bugrep-aup.zip)

#### Affected LMMS versions
Branch: master. I've noticed this issue on stable 1.2.x as well.
This never occured in 1.1.3.

**Comment by DomClark** [comment]
This is another issue with automatic signal-slot connections that should be direct instead. I fixed the ones in the core, LADSPA, and VST in #4692 and #4942, but didn't touch the built-in plugins.

**Comment by Firepal** [comment]
Just took a leisurely stroll in the TripleOscillator's code to see if setting all the signals to be `DirectConnection`s would fix this, and it did, and I'm definitely surprised that the fix is _that_ small. But I'd venture to guess it would take a good chunk of time to add this fix to all of the plugins...

**Comment by DomClark** [comment]
I'm not currently working on this, so if you'd like to open a PR with your changes, that would be very welcome. Don't worry about fixing all the plugins at once - any fix is better than nothing.
