### ISSUE TITLE
Organization of the sample sounds

### ISSUE THREAD

**Issue by anytizer** [LMMS/lmms#5667]
#### Concept Discussion

It may be a time to reorganize the samples folder. There could be several hundreds of ways to produce such samples using different instruments across different countries. If somebody has the right instrument, one can contribute the sound.

Can we create a room/standards to contribute/accept sounds from several instruments?

#### Naming Structure:

[lmms-data/samples]/[country-name]/**[instrument-name]**/[beat|scale-name].*, where the instrument originated from a specific country. This pattern is a suggestion only, as the instruments may be called differently in another language or country. Sometimes, the sound beats have the specific names when played in a particular scale.

#### Samples

![image](https://user-images.githubusercontent.com/5563341/92179384-cecada00-ee01-11ea-8913-fe2f865f5035.png)

In this screenshot, I tried to organize the names of the instruments such that they will not collide, and their unicode names may be important. May be you can create a rule to accept license file, author details, how the sound is produced, and other helpful information on how the sound sample should be classified, produced and used. Only if all information is available, the sound may appear as a new name, ready to use.

This is for a concept discussion before accepting a new sample sound in the repository, in order to **expand the default samples** which ship with the software.

**Comment by Spekular** [comment]
The sample library will be reorganized when the replacement effort is done, see https://github.com/LMMS/assets

**Comment by anytizer** [comment]
Thanks. But is there any possibility to accept unicode names of the instrument?

When written in English, it may conflict a little in the spellings. For example a [Madal (मादल)](https://en.wikipedia.org/wiki/Madal) is best explained with the spellings - maadal, while, it is a common practice to write "madal". The unicode name is more correct to preserve the actual name.
