### ISSUE TITLE
Make a selection dialog (AFP/Sampe-track) for dragged samples

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#5671]
### Enhancement Summary 
In a youtube channel for indie game-devs that i follow, software for game-music was presented. I (of-cause) also mentioned LMMS.
It led to some complaints about LMMS UI
Most was -if not irrelevant, then caused by using LMMS as FLs, and expecting success, bu t one had a good input. The way we treat dragged sample-files in song-editor.
He complained that it did not create a moveable visual clip, in song-editor. And i agree. That should be done differently. 

#### Justification
Draggin a sample into song-editor dos only create an AFP -Then what? -It is not intuitive at all, what user has to do next

#### Mockup
I suggest a selection between AFP and Sample-track, and i suggest that the clip should open in the closest 'bar', that the user points at, if user do not point into the right-side, the clip should open in 1. bar.
AFP-segments should open as a length of the sample, in A4
Sample-track should open as its length (same as it does now, in an inserted Sample-track)
Especially the way to open a AFP is important, because that removes the *'what-to-do-now'* situation, that exists when a user opens a sample in current version.

Selection mockup-image for AFP. Sample-track should be obvious:
![image](https://user-images.githubusercontent.com/6662066/92407613-5cc4fe80-f13b-11ea-9ff9-9fb74313c6f3.png)

(sorry fkD the image

**Comment by qnebra** [comment]
Or just direct drap&drop from file explorer.

**Comment by Spekular** [comment]
Fixed in master.

**Comment by musikBear** [comment]
@Spekular When you say *'fixed'* does that mean that a segment *with a note* is being inserted in song-editor, that there is no 'dead-end' where it is not intuitive what a new user should do next?
Eg similar to the mock-up picture?

**Comment by Spekular** [comment]
I mean that samples dragged onto a sample track create a new clip in that track with the sample. Hence, one can easily add a sample as either a new AFP instance, or as part of a sample track.

**Comment by musikBear** [comment]
I do not think that it does the same as described in my suggestion. The usecase that was criticised was that dragging a sample into **song-editor** ends in a non-intuitive situation. 
**We** 'vets' know all about *sample-track*, but a new user does *not*. That was what the critique was about. I find the critique valid and understandable. It *is* not intuitive, as it is now, and i think we need to address it
.

**Comment by Spekular** [comment]
It seems I misunderstood the report then, I'll reopen it!

I'll note that I'm strongly opposed to adding additional steps to dragging samples into the song editor (e.g. a menu).

I also *really* don't think we should add a clip to AFP tracks when dragging samples in. If you don't understand that you need to add a clip, then you can't use the song editor anyway. It's about as useful as a driving instructor who turns the ignition on for you every time you're going to drive; if you can't do that on your own then you won't manage the rest either.

In addition, from my experience you'd need to delete this clip nearly every time. There are endless cases where I don't want a sample-length note on beat 1 of a bar:
- The track will play a pattern that already exists on another track or slight variation, so you want to copy it over
- The pattern doesn't start on beat 1 (most snare patterns, lots of melodies, etc)
- The pattern should contain notes that aren't of the sample length
- The pattern will play notes other than A4

This feels like slowing down experienced users for the (questionable) benefit of newcomers.

**Comment by Spekular** [comment]
Closing now that #5427 is merged.
