### ISSUE TITLE
Thank you very much for the program!

### ISSUE THREAD

**Issue by mrkaban** [LMMS/lmms#5676]
Thank you very much for the program released under a free open source license! Added a program to a Russian-language site about free software, here is the [link](https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/%D0%BC%D1%83%D0%BB%D1%8C%D1%82%D0%B8%D0%BC%D0%B5%D0%B4%D0%B8%D0%B0/%D1%81%D0%B8%D0%BD%D1%82%D0%B5%D0%B7/lmms-%D1%81%D0%B8%D0%BD%D1%82%D0%B5%D0%B7%D0%B0%D1%82%D0%BE%D1%80-%D0%BC%D1%83%D0%B7%D1%8B%D0%BA%D0%B8.html).

Please do not abandon the project, this is a very interesting program!

**Comment by Spekular** [comment]
Thanks for the kind words, but I'll close this to keep the bug tracker organized.
