### ISSUE TITLE
Export Tracks: Export as loop

### ISSUE THREAD

**Issue by djethino** [LMMS/lmms#5682]
### Bug Summary
In Export Tracks, the option Export as loop doesn't work.
#### Steps to reproduce
Create multiples tracks, do an Export Tracks with Export as Loop selected.
#### Expected behavior
If you do the same by muting all other tracks and do a normal export with "Export as loop" selected it works well. It cut the sound at the end of the last block of the playing track.
#### Actual behavior
It doesn't take in consideration the option "Export as loop" in "Export Tracks", if you enable it or not it does the same result.
#### Screenshot
![LMMS export tracks bug](https://user-images.githubusercontent.com/50217311/93808210-f7e5ca00-fc4b-11ea-9ece-5fe4acdc7ba9.jpg)

#### Affected LMMS versions
1.2.1 and 1.2.2 on Windows 10 (don't know for olders versions and on other plateforms)

#### Logs
<details>
  <summary>Click to expand</summary>
<pre>

</pre>
</details>

**Comment by firewall1110** [comment]
It seems, that _this bug is fixed in current development muster_. 

This bug is in stable 1.2.2 and with bug exported only one track (it seems 1-st one).  

I have tested on Debian Buster (amd64) compiled with no VST, Carla , LV2 .
