### ISSUE TITLE
Casio CT-S100 keyboard doesn't work

### ISSUE THREAD

**Issue by viraxor** [LMMS/lmms#5708]
### Bug Summary
My keyboard (Casio CT-S100) doesn't work. I've tried it on Piano from Above, and it does work.

#### Expected behavior
The keyboard is working, and I am able to record notes with it.

#### Actual behavior
When I record and press some keys on my keyboard, nothing happens.

#### Affected LMMS versions
I am using LMMS 1.2.2.

**Comment by musikBear** [comment]
have you connected the cables in the correct **order**?
That matters!
Read: https://lmms.io/wiki/index.php?title=Using_MIDI
Especially https://lmms.io/wiki/index.php?title=Using_MIDI#Where_do_I_get_started.3F

**Comment by tresf** [comment]
MIDI keyboards are largely plug-and-play, especially newer USB-connected models like the Casio CT-S100.

* Connect the keyboard
* Attach it to an instrument using the ⚙️ > `MIDI` > `INPUT` 
    <img src="https://user-images.githubusercontent.com/6345473/97364859-1490a580-187b-11eb-8663-07c7f1316736.png" width="300px"/>
* Report your findings

If the keyboard is not listed in the `INPUT` area, check to make sure it works with other music software.
