### ISSUE TITLE
Undo/Redo of note edits via the menu is glitchy

### ISSUE THREAD

**Issue by zonkmachine** [LMMS/lmms#5722]
When undoing/redoing note edits via the menu (under Edit) the action doesn't happen until you move the mouse back over the PianoRoll note window.

#### Steps to reproduce

* Add some notes in the Piano Roll
* Menu -> Edit -> undo
* wait...
* Move mouse over the notes and see the last one disappear

This affects the master branch and bisecting suggest that https://github.com/LMMS/lmms/pull/5499, 5d7e6720e1ba0c154041fd663801f7a7a0e16cb5 is where the problem started.

commit 5d7e6720e1ba0c154041fd663801f7a7a0e16cb5
Author: Luna Nooteboom <l.nooteboom@gmail.com>
Date:   Sun Jun 21 04:17:05 2020 +0200

    Automatically assign a midi input device to the selected track (#5499)

Bump @LNooteboom   :)

**Comment by thmueller64** [comment]
Thank you for sorting out the relevant commit. Could you try this simple fix?
