### ISSUE TITLE
Hide/Show automation tracks

### ISSUE THREAD

**Issue by superpaik** [LMMS/lmms#5726]
**Enhancement Summary**
Option to hide/show automation tracks on song editor.

**Justification**
It would be a way to reduce the number of visible tracks on the song editor, hence simplifying the composition tasks. If a song has a lot instruments and samples, it gets complicated to "navigate" in the song editor, and it is not unusual to add two or three automation tracks on some instruments (sometimes I "reuse" an automation track for diferent parameters in order to reduce the number of tracks, but in the end the project gets messy). And normally, when an automation is set, we don't need to "see" it in the screen.
When hide is active, it's not possible to add or modify automation tracks, only when visible.

**Comment by Spekular** [comment]
I think #735 would solve this problem, if you add automations for a track to it's group and then collapse that group when you're not editing them. Can I close this as a functional duplicate or do you feel that collapsible groups don't solve your problem?

**Comment by superpaik** [comment]
Yes, I had seen that other open issue, but I think is a major change that would take time to implement (it goes back to 2014) This other suggestion I think would be easier to implement and would help a lot in the meantime. But if you feel like it's duplicate, or you think that #735 would be ready in the near future, feel free to close it. Thanks, anyway!

**Comment by Spekular** [comment]
Closing as consolidated into #4877, where I listed this as a stop-gap solution for the lack of track groups.
