### ISSUE TITLE
GitHub Wiki Page "Creating a localization" is broken

### ISSUE THREAD

**Issue by quatran** [LMMS/lmms#5737]
### Bug Summary
The GitHub Wiki Page [Creating a localization](https://github.com/LMMS/lmms/wiki/Creating-a-localization) is broken.

#### Steps to reproduce
Click on the link. This error message will occur:

`Sorry, there was an error rendering this page.`

#### Expected behavior
Wiki page is being displayed properly

#### Actual behavior
Wiki page doesn't show up, instead the error message occurs.

#### Affected LMMS versions
none

#### Logs
none

**Comment by tresf** [comment]
@quatran thanks.  This page was converted from MediaWiki and something with the {{flag}} code was breaking it.  Removed the flags for now, converted to markdown.

**Comment by quatran** [comment]
@tresf Thanks for the explanation and fixing that. I have noticed that you missed a closing grave accent at ``  uk` `` and I have already edited that into `` `uk` ``
