### ISSUE TITLE
Knob parameter value graphic (green circle) shows even when value is 0

### ISSUE THREAD

**Issue by sound8** [LMMS/lmms#5747]
> **Edit:** @tresf / @Spekular added screenshot of issue
> <img src="https://user-images.githubusercontent.com/6345473/98768980-0b8cf180-23ae-11eb-967f-4f0e69380ff2.png" width="300px"/>

### Bug Summary
Each knob has a green circle graphic indicating the value of the parameter which is greyed out when the value is at 0.
In certain situations the knob graphic can show a little green piece on the left side in the beginning of this circle even though the value is 0.  
#### Steps to reproduce
The easiest way to reproduce this is if you click your mouse on the knob and instead of dragging straight up or down to change the parameter like you normally would, drag your mouse pretty far out to the left and then slowly down.
You will see the value of the knob is going down (decreasing) and if done successfully you will replicate this issue.
I have experienced this in other ways, but I think this is the best way to generate an example of this issue.

#### Expected behavior
Graphic knob indicator is supposed to be greyed out when value is 0
#### Actual behavior
At times graphic knob indicator can show a little value graphically even though the actual parameter value is at 0

Not a big deal because only really happens when using the knob improperly, but if easy to fix may be worth.

#### Affected LMMS versions 
1.2.2

**Comment by zonkmachine** [comment]
> Graphic knob indicator is supposed to be greyed out when value is 0

Can you give a more specific example? The knob/button is greyed out when the it is disabled (for whatever reason). You could have a setting that only applies to some of the other settings and not all and then disable/grey out the gui part that doesn't apply or maybe hide it altogether.

Is this the issue you're referring to ?https://github.com/LMMS/lmms/issues/4749

**Comment by sound8** [comment]
@zonkmachine 
Again not a big deal
No that is not the issue I am referring to, and it is not a setting either.
This occurs with all LMMS knobs that show that green graphical indicator of how much of parameter is knob is turned to.
When any knobs value is 0 for example volume knob, if volume is set to 0 then that green indicator around the knob is grey.
When you increase volume knob to 50% then the green indicator lights up showing the knob parameter has value.
If you try the method I mention of generating the issue, what will happen is from our example above
Volume knob value will be 0 yet you will see the green indicator lit up just a little piece as if the Volume knob had a value of 5%.
I have experienced this here and there but the only way I can replicate it is by as mentioned
instead of dragging mouse straight up and down, hold down you mouse button and drag mouse far out to the left and then slowly drag down like you are mimicing the shape of a high pass filter curve :)
you will notice the knobs value decreasing and if done correctly the green indicator will still show a little piece in the beginning of it even thought the knobs actual value is 0.
Hopefully this makes sense, if not let me know and I will see if I can help
Thank you for your response

**Comment by zonkmachine** [comment]
OK. I see what you mean now. Sometimes you turn the the knob to 0 and the indicator isn't completely dimmed.

**Comment by Spekular** [comment]
A picture is worth a thousand words, so here's a screencap of the issue. Both knobs are zero, but the ring around the top knob still has a tiny segment highlighted, making it seem as if it's not set to 0. However, the context menu item "Copy value (0%)" proves that it is.
![image](https://user-images.githubusercontent.com/8918426/97623909-9cff7980-1a26-11eb-97a5-e09b738ef271.png)

**Comment by Spekular** [comment]
In the (unlikely, I'd guess) case that this does cause issues, we can probably just add `|| angle == 0`, right?

**Comment by zonkmachine** [comment]
> we can probably just add `|| angle == 0`

A one-liner. I think you should pull that. I don't know how much the performance gains are but it's pretty clear what the code does.
