### ISSUE TITLE
FindXCB cmake module not found

### ISSUE THREAD

**Issue by ycollet** [LMMS/lmms#5758]
Under Fedora, the FindXCB module needed by src/3rdparty/qt5-x11embed/CMakeLists.txt is found in:
```
 /usr/share/ECM/find-modules/ 
```
So, as a workaround, I added the following line in the principal CMakeLists.txt file of lmms:
```
SET(CMAKE_MODULE_PATH /usr/share/ECM/find-modules/  ${CMAKE_MODULE_PATH})
```
The file FindXCB.cmake is provided by the "extra-cmake-modules" package.

**Comment by PhysSong** [comment]
It's in a recursive submodule, so you should init it properly.

**Comment by ycollet** [comment]
Yes, but this file: FindXCB.cmake should have been shipped by qt5-x11embed in the first place ...

**Comment by tresf** [comment]
> Yes, but this file: FindXCB.cmake should have been shipped by qt5-x11embed in the first place ...

Why?  It's a source-only submodule which pulls in another source-only submodule?  What's wrong with the current technique?

https://github.com/lukas-w/qt5-x11embed/blob/022b39a1d496d72eb3e5b5188e5559f66afca957/CMakeLists.txt#L4

The current technique already relies on the submodule, which means it'll always be available.  LMMS relies on a ton of these currently #3963.

If you prefer to use a system-provided package instead, that may be a good justification for a PR against `qt5-x11embed`, or an issue against that project.  Another option may be to switch the project to a [`git subtree`](https://www.atlassian.com/git/tutorials/git-subtree) instead if warranted, which has the advantage of including the submodule in tarballs, etc.

**Comment by PhysSong** [comment]
> If you prefer to use a system-provided package instead, that may be a good justification for a PR against `qt5-x11embed`, or an issue against that project.

Agreed. Closing.
