### ISSUE TITLE
Performance of 32Bit plugins in 64Bit version of LMMS

### ISSUE THREAD

**Issue by sound8** [LMMS/lmms#5759]
Aplogize, I had more of a question that would need to be asked to developers rather than forum users.
(I promise I will close this thread ASAP)

If you run LMMS 64Bit version in Windows and you use a 3rd party 32Bit plugin in it, do 32Bit plugins use more CPU usage in a 64Bit LMMS version environment? than they would in 32Bit LMMS?

I ask this here because from what I understand LMMS programming handles 3rd party plugins by opening them up as separate tasks in the background, so I just wasn't sure how LMMS handles this on a performance level.
I think other DAWs wrap plugins inside of the DAWs programming as where LMMS does it externally, if that makes sense?
I provided a example in my post below if interested.

**Comment by sound8** [comment]
An Example is....
In the past I tested 32Bit VS 64Bit plugins in a Windows program called VSTHost which had a CPU meter built in.

I noticed with plugins that I had 32Bit and 64Bit versions of, that the 64Bit versions would run 3% less CPU usage (in 64Bit Host) than their 32Bit counterparts would (in a 32Bit Host).

However if I ran a 32Bit plugin in VSTHost64Bit, that 32Bit plugin would use 3% more CPU usage than its 64Bit counterpart.

So I was wondering if that was common for all DAWs?
Where because 32Bit plugins need to be wrapped to run in 64Bit DAW they end up using more CPU usage.

**Comment by Spekular** [comment]
This would be a good question to ask in the Discord, so I'm closing it. Since it's possible to reply to closed issues, it doesn't need to be open either way.

**Comment by sound8** [comment]
Ummmm yep
I am not a member of Discord.
If an item is closed, won't users will have to specifically search for closed items to see it.
Thanks

**Comment by tresf** [comment]
Quoting viva64.com:

> ...
> Note also that when you launch 32-bit versions of software on 64-bit systems of the Windows family, old 32-bit applications are executed a bit slower because of the WoW64 subsystem which emulates the 32-bit environment. An average performance loss because of this WoW64 layer is 2-3%, although in some special cases it might be much more.


So, I'd say, yes, this would impact other DAWs.  Note, many DAWs don't offer a 32-bit bridge like LMMS does.

**Comment by tresf** [comment]
> I am not a member of Discord.

No worries.

> If an item is closed, won't users will have to specifically search for closed items to see it.

I think most people search using search engines, not GitHub directly.  The big tracker has >700 open issues and although some developers (like @Spekular) regularly crawl them, many developers don't, so visibility isn't necessarily influenced on open/closed status.  I hope it doesn't deter your involvement, we appreciate the feedback.

**Comment by Spekular** [comment]
Just to clarify, while I've done one-shot things like checking the milestones on every consolidated issue, I wouldn't say I regularly trawl the issue list. I do however get emails for all issue updates, so really I'm more reactive than active :P
