### ISSUE TITLE
Drag&Drop or Pasting multiple TCOs in Song Editor allows negative positions

### ISSUE THREAD

**Issue by russiankumar** [LMMS/lmms#5768]
### Bug Summary
When you drag & drop a group of TCOs, there is a possibility of having some TCOs go behind bar 0 and end up not visible. Dragging the selection, however, snaps it back to post-bar 0 positions.

This is better described by a GIF:

![capture](https://user-images.githubusercontent.com/26451259/97137841-c85f3b80-177c-11eb-9c3e-5083429f37cd.gif)

#### Steps to reproduce

- Select a few TCOs
- Drag them somewhere near the beginning of the song, such that some TCOs could be pasted into a space before bar 0 (see the GIF)

#### Expected behavior
The TCOs snap to post-bar 0 positions in order to keep them in playable space

#### Actual behavior
The TCOs are left exactly where you placed them, and only after dragging them (the selection) anywhere will they snap to post-bar 0 positions.

#### Affected LMMS versions
Occurs on `master` and `stable-1.2`.

**Comment by russiankumar** [comment]
Resolved in #5699. Will close this when merged.

**Comment by Spekular** [comment]
Closed by #5699 as mentioned above.
