### ISSUE TITLE
[Bug] Activating "Send" button under different FX channels will crash LMMS

### ISSUE THREAD

**Issue by popsip** [LMMS/lmms#577]
This bug affects the Master branch.  Under the FX-Mixer, clicking a "send" button under another FX channel and changing to a different project will crash LMMS.

**Comment by badosu** [comment]
@popsip @Lukas-W I also was not able to reproduce this error, I use this feature extensively and never had this problem.

**Comment by tresf** [comment]
This is from April.  No need beating ourselves up over it.  Feel free to repopen if this becomes reproducible. :+1:
