### ISSUE TITLE
Controller Rack - Ability to move controller modules up and down

### ISSUE THREAD

**Issue by sound8** [LMMS/lmms#5773]
Add the ability to move controller modules in the Controller Rack up and down.

### Benefits....
Allows you to organize / order them based on your setup preferences
Can allow you to separate LFO Controllers from Peak Controller modules

### Solutions.....
1.) Create two context menu items "Move Up" and "Move Down"

2.) Add ability to move controller modules by dragging with mouse 
(using similar code already used in SE & BBE that allows tracks to moved by mouse)
Wish this approach of moving items was used more throughout LMMS just makes workflow so much faster / easier.
I feel like I would move things so much more if it was, not for the benefit of my songs, but just because I can :)
But seriously though, can get a little tedious having to keep on opening context menus over and over if needing to move items great distances.

3.) Best of both worlds, adding both methods (I am sure I will get an argument or two for this statement) :)

Anyways, I could have sworn this already existed in the context menu?
May be just thinking of effect modules (which can also benefit from mouse drag moving).

**Comment by tresf** [comment]
Also requested in comment (2017): https://github.com/LMMS/lmms/pull/2944#issuecomment-272984506
