### ISSUE TITLE
Assign track color to mixer automatically.

### ISSUE THREAD

**Issue by Gabrielxd195** [LMMS/lmms#5778]
### Summary of improvements
Assign the track color to the mixer channel automatically.

#### Justification
Currently you can assign a track to a channel of the mixer, the channel will be created automatically, but the color of the track is not assigned to the channel and you have to manually select the color of the channel, which is a bit cumbersome and impractical.

#### Sketch

Here is an image of the problem.
![Opcion para asignar color al mezclador](https://user-images.githubusercontent.com/26127693/98765260-18144880-23b4-11eb-822d-bb97f67abd36.png)
The track has a color assigned but the channel it was assigned to does not.

**Comment by russiankumar** [comment]
As I implemented the color feature, I'd like to see if I can fix this sometime in the near future, if nobody objects :)

**Comment by Spekular** [comment]
I think we ought to be careful about automatically coloring mixer channels. #1214 for example would conflict with this, so clearly different users want to use the colors for different things. Choosing them automatically like this would be an annoyance to anyone who prefers a different system.

**Comment by musikBear** [comment]
@Spekular But for 1214 would the instruments in songeditor not be color-coded in the same way?
![image](https://user-images.githubusercontent.com/6662066/98825417-bcd66a80-2434-11eb-9031-1f0b10c2346a.png)
Anywitch, it would only be a question about adding one new 'rule' in setup:
*Use song-editors track-colors as mixer-colors* on/off (default on)
Then lmms can do both regimes

**Comment by DomClark** [comment]
> I think we ought to be careful about automatically coloring mixer channels. #1214 for example would conflict with this, so clearly different users want to use the colors for different things. Choosing them automatically like this would be an annoyance to anyone who prefers a different system.

If someone wants a different system, they need to change the colour themselves anyway, right? This is only an annoyance to people who want to send a coloured track to a non-coloured mixer channel.

**Comment by IanCaio** [comment]
I'm a bit over the fence about how it should behave tbh. I'm fine having the "Assign to new FX channel" create a channel with the Track's color: even if that's not my intention it's not an unexpectable behavior and just a minor annoyance. Personally, I envisioned having the Track's follow the color of the mixer, not the other way around. But I can see how people can prefer other coloring schemes. As long as the behavior doesn't enforce one on the other and doesn't make too much of a hassle to use a different one I think it's fine. The changes made by the PR doesn't seem to really create much trouble on that matter IMHO.

**Comment by russiankumar** [comment]
#1214 in general conflicts with the idea of custom mixer colors, so having it in its original form (as coloring tracks) will probably not make much sense. If it is instead changed to showing an icon, that is something that can have all of these three PRs work together.

Regarding whether this behavior should be used, I think that most people who will use color coding in the tracks, will probably want to use it in the mixer as well. Since this specific option (Assign to new FX channel) is for creating the track's own channel, it would probably make sense to have it be colored like that track (if #1214 is implemented, it would also make sense to have the color in sync too). @musikBear's idea of having a setting seems like a bit of a hassle, but probably the best way to accommodate both opinions.

**Comment by Spekular** [comment]
Looking at the way this is implemented in the PR I'm not opposed. From the original bug report I thought the idea might be that existing mixer channels would take the color of tracks sent to them.

**Comment by musikBear** [comment]
> *existing* mixer channels would take the color of tracks **send** to them.
Oah.. The plot thickens..
*That* would be a third absolutely logical and useful behaviour 🤓
In summery
* Decorative use
* Structured use (all pads same color aso.
* Mixer-logic 

more?

**Comment by russiankumar** [comment]
This seems to be beyond what my PR is currently doing. Linking colors of existing tracks and mixer channels is a whole another debate (one I personally am against, but some seem to be in support of it). As of now, my PR (and what I assume this issue asks for too) is just the behavior of new mixer channels when they are made with that option. It appears that most people at the very least aren't troubled by the changed in the PR, so unless someone explicitly rejects this, I'll merge it tomorrow.

**Comment by musikBear** [comment]
@russiankumar I think you should make this as **you** intended. Anything fancy can eventually come later, or not. Getting user-colors on chanels and tracks was the wish -Everything after *that* is *creap-features*

**Comment by russiankumar** [comment]
@musikBear sorry, didn’t see your message until I merged this. I’ll leave the remaining of track-mixer color syncing to some other devs, if they want it. Might make a good first issue, even :)

**Comment by spechtstatt** [comment]
This may be related to issue #1215 and my current draft pull request #6407.
