### ISSUE TITLE
Show knob value without clicking.

### ISSUE THREAD

**Issue by Gabrielxd195** [LMMS/lmms#5779]
### Summary of improvements
Show the value of the knob without clicking on it

#### Justification
When I want to know the value of a knob I have to click on it, but in some cases when I click, sometimes by accident I move the mouse and change the value of the knob.

I know that we have the option of '' reset '' to restore the default value, but it would be more practical if the knob will show its value just by hovering over it like the other icons and buttons of the interface.

#### Sketch

Here is an image of the problem.
![Mostrar el valor de la perilla al pasar el puntero](https://user-images.githubusercontent.com/26127693/98775509-a8a65500-23c3-11eb-8714-6aa66fe70358.png)

**Comment by musikBear** [comment]
Agree! And it ought to be a simple fix, if the super-class has an *'on-left-click-event'*. Change that to *on-mouse-over-event*
'Off' could be an issue -though, unless there is a *on-mouse-leave-event* implemented.
Only cravat i can see is a confusing flicker of values, as the mouse is moved over controllers, and that could be annoying. A short 'delay' before the tool-tip is displayed, would sort that(?)

**Comment by PhysSong** [comment]
To implement this, one need to show and place `Knob::s_textFloat` with a `QTimer` to prevent flickers.

**Comment by salilra** [comment]
I can take this issue, if no one is working on it.

**Comment by justlog** [comment]
Thought about trying my hand at contributing to the project and came across this. It seems as though @salilra implemented the fix but it's not merged as of yet. Is there any work to be done regarding this issue?

**Comment by Rossmaxx** [comment]
@salilra update? 
@justlog feel free to make your version.

**Comment by Monospace-V** [comment]
> update?

https://github.com/LMMS/lmms/pull/5911

**Comment by AngeloSorte** [comment]
I like this! I will try to give some help!

**Comment by chaitanyak175** [comment]
Is anyone working on this issue I can give it a try as this will be my first time contributing to an open source project.

**Comment by MrTopom** [comment]
I could work on it...

**Comment by zonkmachine** [comment]
@MrTopom There seem to be an open PR for this issue. https://github.com/LMMS/lmms/pull/5911
I don't know what state it's in though.

**Comment by zonkmachine** [comment]
New comments in the PR https://github.com/LMMS/lmms/pull/5911
