### ISSUE TITLE
1.3.0 alpha binaries for common users.

### ISSUE THREAD

**Issue by Gabrielxd195** [LMMS/lmms#5781]
### Summary of improvements
Release 1.3.0 alpha binaries to make them available to common users.

#### Justification
Although 1.3.0 is in its alpha phase and it is not recommended to use it for serious projects: I think it would be better to release the binaries so that common users also have the possibility to experience it. since many users do not know how to compile the source code and in my case it gives me errors.

1.3.0 has many features that stable 1.2 does not have and is constantly updated, that would greatly please the entire community of lmms users, seeing the great changes and corrections that 1.3.0 will bring. Greeting

**Comment by russiankumar** [comment]
Nightly builds (or at least a precursor to them) were just implemented on the website ([pull request](https://github.com/LMMS/lmms.io/pull/326)). Expect to see them soon.

**Comment by NETMANSKY** [comment]
> 
> 
> Nightly builds (or at least a precursor to them) were just implemented on the website ([pull request](https://github.com/LMMS/lmms.io/pull/326)). Expect to see them soon.

Как скоро, дружище @russiankumar , это случится? Уж очень охота потрогать руками :) 
How soon, my friend @russiankumar, will this happen? Really want to touch it with hands :)

**Comment by russiankumar** [comment]
@NETMANSKY,

Этот вопрос лучше спросить @tresf. По-моему он сможет ответить на это.

На данный момент, вы можете скачать файлы [прямо отсюда](https://github.com/LMMS/lmms/pulls), подробности об этом вот здесь: [под главой How to Review](https://github.com/LMMS/lmms/wiki/Reviewing-Pull-Requests#using-the-lmmsbot-builds). Пожалуйста учтите что мы не гарантируем стабильность на эти билды ( это правильное слово?)) ), так как над ними еще работают. Или, вы можете построить LMMS сами, [подробности](https://github.com/LMMS/lmms/wiki/Compiling).

---

I think it's better to ask @tresf this question. I think he will be able to answer it.

As of now, you can download the builds [from here](https://github.com/LMMS/lmms/pulls), details of this can be found [here](https://github.com/LMMS/lmms/wiki/Reviewing-Pull-Requests#using-the-lmmsbot-builds). Please consider that these builds may not be stable, as they are still being worked on. You may also build LMMS yourself, [details](https://github.com/LMMS/lmms/wiki/Compiling).

**Comment by tresf** [comment]
Pinging @PhysSong.

**Comment by NETMANSKY** [comment]
@tresf @russiankumar Thanks guys. But im not a compiler or coder, im just a user of LMMS and cant wait for new version.

@russiankumar 
> мы не гарантируем стабильность на эти билды ( это правильное слово?)) )
В русском используется и это английское слово, но правильно будет называться "сборка" в единственном числе, и "сборки" во множественном. Спасибо, удачи!

**Comment by tresf** [comment]
They'll be up very soon.

**Comment by russiankumar** [comment]
@NETMANSKY спасибо! Я редко пользую русский язык, тем более для программирования.

Glad that the nightlies will be out soon. Any estimate by when that’ll happen?

**Comment by PhysSong** [comment]
Less than a week, I think.

**Comment by PhysSong** [comment]
It's a bit delayed to 2020-11-30 to fix some bugs to improve usability.

**Comment by PhysSong** [comment]
I think it can be delayed by one more day due to some critical bugs related to exporting which are reported today.

**Comment by PhysSong** [comment]
Available on https://lmms.io/download now, and it will be continue updating in the future. Thanks for waiting!

**Comment by Gabrielxd195** [comment]
> Available on https://lmms.io/download now, and it will be continue updating in the future. Thanks for waiting!

Thank you very much to you and the entire team of developers for your great contribution. for a moment I thought that this would take more time, but finally the improvements and corrections of master will be available to everyone. I and the Hispanic community of lmms users are very grateful for your great work. greeting

**Comment by NETMANSKY** [comment]
It's greatfull! But it cant launching in my Win10x64. Who knows a reason?

**Comment by PhysSong** [comment]
There are some troubleshooting tips in https://github.com/LMMS/lmms/wiki/Troubleshooting.
