### ISSUE TITLE
Volume knob on tracks processed before effects

### ISSUE THREAD

**Issue by jaddison06** [LMMS/lmms#5782]
### Bug Summary
The volume knob on tracks seems to change volume before effect processing, IMO this is unhelpful, and it's inconsistent with the behaviour of a Mixer channel which processes volume after effects

#### Steps to reproduce
what I've noticed:
Put a dynamics plugin on an instrument track (eg a compressor)
After setting the plugin up, change the track volume

#### Expected behavior
I think the track's volume knob should adjust output level after effects processing

#### Actual behavior
The volume knob comes before the compressor, meaning whenever you change the track volume you have to re-adjust your compressor settings. You can work around this by putting an Amplifier after the compressor, but it doesn't feel very natural and slows down my mixing workflow

#### Affected LMMS versions
I'm on 1.2.2

**Comment by Spekular** [comment]
Invalid, this is expected. If this weren't the case, there would be no way to change the pre-fx volume. You can always use amplifier effects or mixer channels to adjust the volume elsewhere in the signal chain.
