### ISSUE TITLE
[Feature Request] Ability to fine-tune envelopes

### ISSUE THREAD

**Issue by GingkathFox** [LMMS/lmms#5794]
# Please search the issue tracker for existing feature requests before submitting your own. Delete this line to confirm no similar request has been posted yet.

### Enhancement Summary
It would be nice if we could change the curves in the envelope and add more envelope points, like in ZASFX.
#### Justification
It would allow for more creativity instead of being locked into a envelope box.
#### Mockup

i have absolutely no idea how to create a mockup. Go ham, ig

**Comment by he29-net** [comment]
Looks like a duplicate of #3469.
