### ISSUE TITLE
Stop playing infinitely

### ISSUE THREAD

**Issue by anytizer** [LMMS/lmms#5821]
![image](https://user-images.githubusercontent.com/5563341/101091201-171aa500-3575-11eb-9817-2eee72fe5fd8.png)
The song editor plays silence for infinite time if not interrupted. May be it should stop after maximum length available, which is determined by the editor's data.

**Comment by hari-shreyas** [comment]
I second this

**Comment by Veratil** [comment]
Duplicate of #4643 which consolidated into #3740 then moved to #4877
