### ISSUE TITLE
Vestige doesn't work at all 

### ISSUE THREAD

**Issue by andrive-one8** [LMMS/lmms#5837]
#### Replicate:
Drag a VST to Song-Editor -OR- Create Vestige track and try to load a VST from there 

#### Expected behavior:
I drag a .dll file to Song-Editor, a new Vestige track gets created and the VST loads fine, and I get to use the instrument I intended to. I can also manually create a Vestige track and load a VST by selecting it from the plugin.

#### Actual behavior:
I drag a .dll file to Song-Editor, a new Vestige track gets created but no VST gets loaded. VSTs also don't wanna load by manually selecting them in Vestige

![lmms](https://user-images.githubusercontent.com/75690662/101522690-f4660300-395d-11eb-93bd-b718ca00ff8b.png)

#### Affected versions:
1.2.0+, tried on macOS Catalina, Windows 10 and Linux

**Comment by PhysSong** [comment]
Sorry for late response. Could you try the [troubleshooting guides](https://github.com/LMMS/lmms/wiki/Troubleshooting)?

**Comment by ExperiBass** [comment]
Lets see if this will auto-open, just in case, @PhysSong my partner is trying to open VSTs but neither Vital or Synth1 will open (the only vsts she has). Shes running windows 11 and LMMS v1.3.0-alpha.1.102+g89fc6c960.

**Comment by PhysSong** [comment]
@ExperiBass The information you provided isn't enough. Have she followed the [troubleshooting guides](https://github.com/LMMS/lmms/wiki/Troubleshooting)? If she still experience the issue after the steps, please reach out on Discord `#support`.
