### ISSUE TITLE
Lmms fails to build against wine 6x due to the removal of libwine.so

### ISSUE THREAD

**Issue by plater** [LMMS/lmms#5852]
openSUSE has wine 6.0rc2 and wine commit 497c902857241ec340e562ec3490a344704440dc removes libwine.so. This has the effect of preventing vst wine plugins not being built due to libwine.so not being found.
There is also a change in dynamic loading See comment 2 :
https://bugs.winehq.org/show_bug.cgi?id=50363

I've meanwhile added a workaround to the build to supply libwine.so to cmake.

**Comment by PhysSong** [comment]
Should be fixed in a5dc3fee6a5c51065f268cb19f686284752e69da.
