### ISSUE TITLE
Distorted audio using pipewire with pulseaudio backend

### ISSUE THREAD

**Issue by jakobdotcom** [LMMS/lmms#5853]
### Bug Summary
The audio is heavily distorted when using the pulseaudio backend on pipewire. Also noticed that the latency is quite bad.

#### Steps to reproduce
Run pipewire (0.3.17) instead of pulseaudio and select pulseaudio backend in LMMS.

#### Expected behavior
No distortion

#### Actual behavior
Heavy distortion

#### Affected LMMS versions
LMMS 1.2.1 (Linux/x86_64, Qt 5.15.0, GCC9.3.0) on Void Linux.

#### Logs
<details>
  <summary>Click to expand</summary>
<pre>

</pre>
</details>

**Comment by jakobdotcom** [comment]
So this might be a bug in pipewire since it is in heavy development. But I'm not seeing this issue with any other application so far (VLC, Firefox, Wine, etc).

**Comment by zonkmachine** [comment]
@jakobdotcom Was this solved?
