### ISSUE TITLE
Bitcrush plugins displays output clip level as % while it's dBFS

### ISSUE THREAD

**Issue by PhysSong** [LMMS/lmms#5856]
See the code below:
https://github.com/LMMS/lmms/blob/eeec3f866469f5179a81bdfe68a9bd21c12c7278/plugins/Bitcrush/Bitcrush.cpp#L141-L144
https://github.com/LMMS/lmms/blob/eeec3f866469f5179a81bdfe68a9bd21c12c7278/plugins/Bitcrush/BitcrushControlDialog.cpp#L77-L78

**Comment by deenadayalancs** [comment]
Hello @PhysSong ,

Can i replace % with dBFS and push this code?

Thanks,
Deena

**Comment by PhysSong** [comment]
Are you familiar with Git and GitHub? If not, here are the simple steps for changing only one file:
- Go to https://github.com/LMMS/lmms/blob/master/plugins/Bitcrush/BitcrushControlDialog.cpp and click the edit button(the pencil button)
- Edit the file and then click the "Propose changes" button
- Submit a pull request

If you want to contribute further, please make sure you're familiar with them!

**Comment by PhysSong** [comment]
@deenadayalancs Now you can go https://github.com/LMMS/lmms/compare/master...deenadayalancs:patch-1 and create a pull request. :+1:
