### ISSUE TITLE
Remove useless includes (using include-what-you-use)

### ISSUE THREAD

**Issue by JohannesLorenz** [LMMS/lmms#5860]
### Enhancement Summary

There's a tool to find them:

```
cmake -DCMAKE_CXX_INCLUDE_WHAT_YOU_USE="include-what-you-use;-Xiwyu;--mapping_file=/usr/share/include-what-you-use/qt5_11.imp" -DCMAKE_C_INCLUDE_WHAT_YOU_USE="include-what-you-use;-Xiwyu;--mapping_file=/usr/share/include-what-you-use/qt5_11.imp" ..
```

If the tool is named "iwyu" instead, use that in the CMake command above.

The tool gives headers that should be
* added if you follow the principle to include every header if you use a definition from it (**decided against that in discord**)
* removed (because they are useless)

The tool gets a bit confused by Qt, it asks to replace stuff like <QString> by "qstring.h" - this can be ignored.

When you submit a PR it should not contain any removement suggestions.

#### Justification

Compile time matters, and I wonder how much we would win if we would remove all useless includes.

**Comment by Spekular** [comment]
This should be closed, right?

**Comment by JohannesLorenz** [comment]
Yes. Thanks for the reminder!
