### ISSUE TITLE
Pianoroll resizing is graphically broken in LMMS 1.3

### ISSUE THREAD

**Issue by RoxasKH** [LMMS/lmms#5863]
Resizing pianoroll vertically in LMMS 1.3.0 Alpha nightly, is often graphically bugged.

Steps to reproduce
1. Open a pianoroll pattern.
2. Resize it vertically and take an eye on the keys that are now dinamically drawn.

Here's an example
![a](https://user-images.githubusercontent.com/40141826/103139866-1c38c300-46e1-11eb-94ec-dc4cd6d6d744.gif)

**Comment by Veratil** [comment]
Thanks for the report, I believe there's another issue in the same fashion with zoom levels. I'll look into this soon.

**Comment by Spekular** [comment]
Reopening. I assume this was an automatic close since there are still issues with stuttery resize, jumping octave lines, and the actual piano keys.

**Comment by Veratil** [comment]
> 
> 
> Reopening. I assume this was an automatic close since there are still issues with stuttery resize, jumping octave lines, and the actual piano keys.

Yeah thanks, didn't mean for it to actually close with #5881.

TODO:
- [ ] Piano Keys
- [ ] Grid
- [x] Notes

**Comment by superpaik** [comment]
Just testing #5965 I noticed that if playhead is not at position 0, both resizing or increasing vertical zoom does not break pianoroll.
Maybe the solution to that PR helps with the resolution of this one.

**Comment by Veratil** [comment]
> Just testing #5965 I noticed that if playhead is not at position 0, both resizing or increasing vertical zoom does not break pianoroll.
> Maybe the solution to that PR helps with the resolution of this one.

Yup, that's it! Was able to break the same way over the note area when paused and resizing slowly. Need to repaint the position line, it doesn't update along with the piano roll 100% of the time. Good catch!
