### ISSUE TITLE
Latest master: Normalizing BitInvader results in volume increasing to a deafening level

### ISSUE THREAD

**Issue by GingkathFox** [LMMS/lmms#5867]
### Bug Summary
When normalizing BitInvader, the currently playing tone plays at an extremely high volume.

#### Steps to reproduce
1: Open BitInvader.
2: Press the "Normalize" button.
#### Expected behavior
The volume stays at a consistent level.
#### Actual behavior
The volume redlines.

#### Screenshot
![Screen Shot 2020-12-31 at 10 46 51 AM](https://user-images.githubusercontent.com/33764485/103416613-80caa680-4b55-11eb-93c6-43cb61b77adb.png)

#### Affected LMMS versions
1.3.0-alpha.1.57+gaa02a2154

**Comment by zonkmachine** [comment]
I don't see a difference here compared to lmms-1.2.2 . Are you sure this isn't just BitInvader that is a bit too high compared to most other plugins with default values? This is a known issue.

**Comment by zonkmachine** [comment]
No, I see this issue too. It has got to be a new Bit Invader instance. Steps to reproduce as follows.
 * Add a new Bit Invader
 * Select 'Normalize'
 * Press a key -> insane level on master, no signal at all on 1.2
 * Select a wave
 * Press a key -> normal level

**Comment by zonkmachine** [comment]
https://github.com/LMMS/lmms/blob/d769459764197ae4e6068a66fd6e22784803045f/plugins/bit_invader/bit_invader.cpp#L149-L151

I can't build master on my 'away for holiday' machine but if I add `lengthChanged();` after  `m_graph.setWaveToSine();` on stable-1.2 it fixes the issue there. I guess swapping these lines on master coult do the trick.

**Comment by thmueller64** [comment]
I can confirm the problem on master and that your suggestion fixes the problem @zonkmachine. The call to `lengthChanged()` prior to `m_graph.setWaveToSine()` causes the normalization factor to be calculated on the uninitialized waveform and to be incorrectly applied to the initialized waveform.

**Comment by thmueller64** [comment]
It seems that you can only observe this behavior if the first thing you do on a fresh Bit Invader instance is pressing the Normalize button.
As soon as you select a different waveform or move the length knob, the normalization factor is recalculated and applied correctly.

**Comment by zonkmachine** [comment]
Fixed in https://github.com/LMMS/lmms/pull/5871
