### ISSUE TITLE
Enhancement 'New Mixer' and user-interactions

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#587]
Milestone1 has a new mixer as subject. I have a couple of ideas for user-interaction. First i must refere to an already sugested enhancement: #355  ,but i think this would even work better, if the 'select'-component on the individual presets, would display the state on the mixer: (slot-free / slot-occupied) This could be implemented in several different ways. As different colors on the preset-display. As a small diode on the preset, graying out the 'FX' label.. etc. This would give the user a way to look for an empty slot on the mixer from a preset, and then allocate the preset, as sugested in. #355.
This will improve general usabillity and workflow.

**Comment by Umcaruje** [comment]
@musikBear could you please further explain this request? It seems like a mixture of already submitted enhancements.

**Comment by Umcaruje** [comment]
No response in over 2 months, Closing.
