### ISSUE TITLE
lmms doesn't load the plugins anymore

### ISSUE THREAD

**Issue by beppuuz** [LMMS/lmms#5874]
# Please search the issue tracker for existing bug reports before submitting your own. Delete this line to confirm no similar report has been posted yet.

#### Logs
<details>
  <summary>Click to expand</summary>
<pre>

</pre>
</details>

**Comment by Spekular** [comment]
Please update this issue to follow the bug report template, or it will have to be closem. As it stands the issue description isn't nearly specific enough.

**Comment by musikBear** [comment]
Clearly a **support issue**, you @beppuuz should either go to Dischord 
https://discordapp.com/invite/5kSc32Z
(not sure that is valis still...)
or our support-forum. 
https://lmms.io/forum/viewforum.php?f=7
*Not* here!
