### ISSUE TITLE
MP3 stereo mode doesn't match to the selection in export dialog

### ISSUE THREAD

**Issue by PhysSong** [LMMS/lmms#5876]
#3826 reordered the stereo mode selections in the export dialog, but it didn't update `mapToStereoMode` function in `ExportProjectDialog.cpp`. The order should now be changed to mono, stereo, joint stereo.
https://github.com/LMMS/lmms/blob/24761a4f7772df61315957d13ab562e91f5694cc/src/gui/ExportProjectDialog.cpp#L140-L153

**Comment by deenadayalancs** [comment]
@PhysSong is this the expected changes need to be updated? please let me know. will push the changes.

OutputSettings::StereoMode mapToStereoMode(int index) 
{
switch (index) 
 	{
 	case 0: 
 		return OutputSettings::StereoMode_Mono;
 	case 1: 
                return OutputSettings::StereoMode_Stereo;
       case 2:
               return OutputSettings::StereoMode_JointStereo;
      default:
 	      return OutputSettings::StereoMode_Stereo; 
 	} 
}

**Comment by PhysSong** [comment]
@deenadayalancs You're right.

**Comment by deenadayalancs** [comment]
@PhysSong Please assign this to me. I am not able to checkout and update the code. Not able to create a pull request by myself.

Please create a pull request and assign this to me. Thanks again.

**Comment by zonkmachine** [comment]
> I am not able to merge and update the code. Not able to create a pull request by myself.

You have already made a PR earlier. What's the problem this time?
The developers are active on Discord https://discord.com/invite/3sc5su7
I suggest you use the channel `#dev-support` for help with PR's.

**Comment by deenadayalancs** [comment]
@zonkmachine thanks for the details. I tried to edit from my desktop client. guess, something is missing there.  updated and merged the code.

Have a nice day.

**Comment by DomClark** [comment]
Fixed in #5890.
