### ISSUE TITLE
Piano Roll falls apart when scrolled to the top

### ISSUE THREAD

**Issue by dj-pixus** [LMMS/lmms#5879]
When the Piano Roll window is maximized and the view is scrolled all the way up, the note area goes a step too far down, causing notes to become visible in the lollipop area. The keyboard stays in its place, so it shows false information at this point.

Here is a video for better understanding:
https://drive.google.com/file/d/1SsrTm_4BOELdGFc2wbSXQVkXPpYoq3iN/view

This bug appears only in master, 1.2 seems to work fine.

**Comment by Veratil** [comment]
Duplicate #5863
