### ISSUE TITLE
Unable to import file with non-latin characters

### ISSUE THREAD

**Issue by Maria-Smith** [LMMS/lmms#5888]
### Bug Summary
Using non-Latin characters in the file name of a sample causes unexpected or silent errors.

#### Steps to reproduce
1. Create a valid audio file (I've tested .ogg and .wav)
2. Use non-Latin characters in the name (e.g. Cyrillic, АБВ.wav or extended Latin ÁÉÚ.wav)
3. a. open the file with LMMS (throws an error)
3. b. open the file from LMMS Sample track (does not produce any sound)
3. c. drag the file from directory list on the left (appears as a track with question marks in place of invalid characters, does not produce any sound)

#### Expected behavior
Import the sample or give an appropriate warning about the invalid characters.

#### Actual behavior
"Could not open file [...] You probably have no permissions to read this file.
 Please make sure to have at least read permissions to the file and try again" when trying to open the file with LMMS directly. No sound when choosing the sample from the open program.

#### Screenshot
![image](https://user-images.githubusercontent.com/32172888/105081443-7df70d80-5a92-11eb-9215-9be6db8e3e5e.png)
![image](https://user-images.githubusercontent.com/32172888/105082611-2194ed80-5a94-11eb-9da6-fbb242a603c3.png)

![image](https://user-images.githubusercontent.com/32172888/105082688-38d3db00-5a94-11eb-8bf0-d5556a9c1ba2.png)

Same file with a valid name:
![image](https://user-images.githubusercontent.com/32172888/105082662-307ba000-5a94-11eb-963d-0cad441d26ba.png)

#### Affected LMMS versions
1.1.3 (win32/x86_64, Qt 4.8.7, GCC 4.9.3 20150305 (prerelease))

**Comment by PhysSong** [comment]
1.2.2 improved filename handling a lot. Could you please try upgrading to 1.2.2?

**Comment by Maria-Smith** [comment]
Yes, it works properly in the newer version, thank you
