### ISSUE TITLE
gcc Xcode build failing on Travis

### ISSUE THREAD

**Issue by dan-giddins** [LMMS/lmms#5897]
![image](https://user-images.githubusercontent.com/16902799/106392076-36ed0e80-63e8-11eb-9b13-6a678e749598.png)
![image](https://user-images.githubusercontent.com/16902799/106392082-3b192c00-63e8-11eb-9a26-4cdd8763f213.png)
[16:33] tresf: Probably just needs a small update to the homebrew dependencies, or perhaps an || true.  I'm not sure why deps are already installed, maybe the CI changed defaults

**Comment by DomClark** [comment]
We're planning to remove all Travis CI jobs, see #5802. @PhysSong How's this going?

**Comment by PhysSong** [comment]
The automatic migration from travis-ci.org to travis-ci.com is still in progress. We can disable the Travis builds right now if we want to do so.

**Comment by PhysSong** [comment]
Closing since we don't run Travis builds anymore.
