### ISSUE TITLE
Get all plugins to be compataible with MSVC

### ISSUE THREAD

**Issue by dan-giddins** [LMMS/lmms#5898]
Plugins are blacklisted in CMakeLists.txt. Look for `MSVC_INCOMPATIBLE_PLUGINS`.

tresf: Disabling ALL LADSPA plugins seems a bit overkill but was likely done as a quick solution to start MSVC work.  Now that MSVC is in very good shape, we'll need to be more granular about it.  This may require some CMake reworking to toggle the LasdpsaEffect folder back on and then blacklist the actually LADSPA effects one by one instead.

**Comment by DomClark** [comment]
See also #3999.

**Comment by DomClark** [comment]
>Close?

There's still GIG Player to go, but that was never in `MSVC_INCOMPATIBLE_PLUGINS` and is tracked in #3999, so yes, let's close this.
