### ISSUE TITLE
TimePos::quantize() crashes when called with quantization 1/192

### ISSUE THREAD

**Issue by IanCaio** [LMMS/lmms#5899]
### Bug Summary

If the method `TimePos::quantize()` is called with quantization 1/192, it causes an arithmetic exception because the variable `interval` ends up equal to 1 and the expression `int snapUp = offset / (interval / 2);` causes a division by 0.

#### Steps to reproduce
This bug was found out while code from a PR was being tested. It might not affect any existing functionality of LMMS, since I believe `TimePos::quantize()` is only being called when quantization is bigger than 1/192.

#### Expected behavior
`TimePos::quantize()` returning the same `TimePos` that it was given.

#### Actual behavior
Arithmetic Exception crash.

Thanks @rghvdberg for finding the bug!

**Comment by Spekular** [comment]
> `snapUp = offset / (interval / 2)`

Wasn't this fixed in some PR to be `snapUp = 2 * offset / interval`?

**Comment by IanCaio** [comment]
:man_facepalming: 

I was looking at the file from the branch I fetched from the PR, and just now I noticed it's 19 commits behind master. You're right, this is fixed by #5847 . Double facepalm because I was the one that submitted it :rofl:
