### ISSUE TITLE
LMMS allways crash at the end of file rendering

### ISSUE THREAD

**Issue by afAtedg** [LMMS/lmms#5906]
When exporting to audio file, the rendering goes well until the end where LMMS freeze at 100% and need to be killed to be restarted

This happened at every exports.
I'm using a compiled LMMS Version 1.2.2 (Linux/x86_64, Qt 4.8.7, GCC 8.3.0)
On Debian 10 Buster with Jack as sound server (rooted to an Ardour track).

I have also tried with LMMS master Version 1.3.0-alpha.1.65+g4107bc02b (Linux/x86_64, Qt 5.11.3, GCC 8.3.0). and things seems to goes well.

**Comment by PhysSong** [comment]
The issue with JACK was fixed in #5681. If you want to fix the bug in 1.2.2, you can cherry-pick the commit 435dbc5e00fa06cd789693a56e6b340f4c7722ab.
