### ISSUE TITLE
1.3 Alpha - Ghost Notes aren't displayed properly after loading a project

### ISSUE THREAD

**Issue by RoxasKH** [LMMS/lmms#5912]
Referring to: https://github.com/LMMS/lmms/pull/5862#issuecomment-778847952

### Bug Summary

This ia a graphical bug , and as the title suggests, after saving a project that had a ghost notes pattern set, reloading it will make ghost notes not displaying as they should.

#### Steps to reproduce

1. Create a new Project
2. Open an instrument pattern and draw some notes
3. Set the pattern as ghost notes
4. Open a new pattern to see that ghost notes are displayed properly (optionally take a screenshot if you wanna do a comparison)
5. Save the project
6. Reload the project in LMMS
7. Open the second pattern you made to see ghost notes
8. Now ghost notes are not displayed properly as before

Setting again the pattern as ghost notes through songeditor will make ghost notes return as they should be, but it shouldn't be a forced passage.

#### Screenshot

Before Loading the project (as they should be)
![prop](https://user-images.githubusercontent.com/40141826/108203186-6c9d3180-7122-11eb-937c-b05f1902d21d.PNG)

After Loading the project
![unprop](https://user-images.githubusercontent.com/40141826/108203198-7030b880-7122-11eb-805a-82a26753944c.PNG)

#### Affected LMMS versions

LMMS 1.3.0-alpha.1.33+g4f74151f0-mingw-win64
OS: Windows 10 64-bit

**Comment by cyber-bridge** [comment]
I did some digging and I guess this is due ghost notes don't store volume and panning info in the project file and the notes opacity is calculated with those values in `void PianoRoll::drawNoteRect`.

Possible fix could be to remove volume and panning info from ghost notes on set, I will check this and report soon.

**Comment by cyber-bridge** [comment]
Well close .. it is due we don't store the volume for ghost notes in project files and on load of a the ghost notes from a project file it sets the volume to 0 since there is no such value and it's the default for `asInt()` when the value isn't found. Will create a PR for it.
