### ISSUE TITLE
fl studio plugin in lmms

### ISSUE THREAD

**Issue by techindiesoftgaming** [LMMS/lmms#5918]
# Please search the issue tracker for existing feature requests before submitting your own. Delete this line to confirm no similar request has been posted yet.

### Enhancement Summary
                      i cannot open all the vst plugin of fl studio. i want that all the fl studio plugins could be opened in lmms.

#### Justification
                    this would enhance the sound quality of lmms .

**Comment by RoxasKH** [comment]
> ### Enhancement Summary
> 
> ```
>                   i cannot open all the vst plugin of fl studio. i want that all the fl studio plugins could be opened in lmms.
> ```
> 
> #### Justification
> 
> ```
>                 this would enhance the sound quality of lmms . 
> ```
> 
> #### Mockup

I answered you in #5917 . There's no evident need to double post, either.
