### ISSUE TITLE
Adjusting Sample Track

### ISSUE THREAD

**Issue by EhrMusic** [LMMS/lmms#5922]
Summary: The adjustment I am asking for is to be able to shorten(or lengthen) the beginning of a sample track and also propose an adjuster to the Attack and release, just like loading up an audio file through the "AudioFileProcessor" VST. 

Justification: When you click on sample track and then put something, such as a loop, onto it, you are only able to adjust the end of the sample. I propose this because there maybe something in the beginning of the sample that I don't want. The Attack, Release, etc. function would be nice to have to avoid clipping. This upgrade to the Sample Track would be amazing because I can cut right in the middle of it and still hear the drums along with it, rather than go to the beginning of the grid it is placed in on the piano roll. (had to use phone, mouse icon wouldnt go in screenshot)

Mockup: 
![20210226_173752](https://user-images.githubusercontent.com/79335874/109362733-a2949100-7859-11eb-9547-ac41583dd629.jpg)

![20210226_173739](https://user-images.githubusercontent.com/79335874/109362768-b3dd9d80-7859-11eb-8adc-2213b9f82bf3.jpg)

![lmms mock up 1](https://user-images.githubusercontent.com/79335874/109362801-c526aa00-7859-11eb-88d3-16508bc3a63c.png)

**Comment by Spekular** [comment]
Left side trim is already implemented in master. There's an open PR for fade in/out as well.
