### ISSUE TITLE
Bug 1.0 w32 : Periodical/random loss of project name

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#594]
This one is odd. It happens sometimes when i switch view (from like.. piano-rool to song-editor) the project-name then change to 'Untitled'. It is however -only- 'cosmetic. LMMS will -still- save the file in its correct name, and if 'save-as' is chosen (image):  http://snag.gy/wNe5i.jpg, LMMS will display the -correct- old name. The name is preserved, but name-display in 'windows-bar' is incorrect. If a normal 'Save' is done, either by button or shorcut, the correct name again apear in win-bar.
I would put this in between a real bug, and a anoying glitch. Some users may be confused, and think they lost data. Non is lost at all.
Not simply reproduceable :// ..alas

**Comment by Umcaruje** [comment]
Duplicate of #905
