### ISSUE TITLE
Knife tool introduces unused Q_PROPERTY

### ISSUE THREAD

**Issue by JohannesLorenz** [LMMS/lmms#5949]
### Bug Summary

8acb9222fdaef66f48f9cc4f91818113d76dd664 introduces warnings that `mouseHotspotHand` and `mouseHotspotKnife` in `include/TrackContentObjectView.h` are not accessed (see logs).

Cause: #5949.

#### Steps to reproduce

Compile (at least, I found the warning on MacOS CI, but it's probably everywhere).

#### Expected behavior

No warning.

#### Actual behavior

Warning.

#### Affected LMMS versions

master

#### Logs
<details>
  <summary>Click to expand</summary>
<pre>
AutoMoc: /Users/travis/build/LMMS/lmms/include/TrackContentObjectView.h:57: Warning: Property declaration mouseHotspotHand has no READ accessor function or associated MEMBER variable. The property will be invalid.

/Users/travis/build/LMMS/lmms/include/TrackContentObjectView.h:58: Warning: Property declaration mouseHotspotKnife has no READ accessor function or associated MEMBER variable. The property will be invalid.
</pre>
</details>

**Comment by Spekular** [comment]
This is a weird warning considering the fact that the properties are definitely read correctly (changing the property in the theme changes the cursor hotspot). I vaguely remember reading that you don't need to write both WRITE and READ in some cases, but perhaps that was via MEMBER and NOTIFY. Still, I suppose I'll make a PR to switch to MEMBER/NOTIFY and see if that fixes it.

**Comment by JohannesLorenz** [comment]
@Spekular Can you point out where in the code you access this property in a reading sense? I can't find it.

**Comment by Spekular** [comment]
The property is linked to `setMouseHotspotKnife`, which sets `m_mouseHotspotKnife`, which is read. I double checked this by messing up the hotspot so the cut position is incorrect. With the property removed LMMS spits out errors on launch + the cut position remains unmodified.
