### ISSUE TITLE
Random Clicks in SID Emulator

### ISSUE THREAD

**Issue by hawthornbunny** [LMMS/lmms#5958]
### Bug Summary
The SID emulator sometimes seems to emit semi-random clicks when playing notes. The clicks are real sounds and are present in the audio track - they can be seen on the volume meter, are affected by effects filters, and are recorded into exports.

The clicks happen sporadically (in my compositions, they occur approximately once in every 4 bars of SID notes) and usually in the same place in the track, but not always.

The clicks are audible even if the SID emulator's internal volume is turned down to 0. Using an LMMS volume envelope does not prevent the issue. This does not occur with any other plugins such as the Triple Oscillator.

#### Steps to reproduce
One way to reproduce the issue is as follows:

1. Drag a SID emulator plugin into the Song Editor.
2. Set the SID emulator's internal VOL knob (the one next to RES and CUT) to 0 so that it shouldn't produce sound.
3. Enable Arpeggio and set the Time knob to its lowest value (25 ms), so that notes are played very rapidly.
4. Play the note for a few seconds. A series of regular clicks is produced even though the SID is not playing an audible note.

#### Expected behavior
The SID emulator should not emit clicks. In particular, the SID emulator should produce no sound at all if its internal volume is set to zero. (NOTE: That's only my assumption, I don't know the inner details of how the SID produces sound).

#### Affected LMMS versions
Version 1.2.2 (Linux/x86_64, Qt 5.15.2, GCC 10.2.0)

My kernel/OS: 5.4.105-1-MANJARO

**Comment by thmueller64** [comment]
I could reproduce the issue with 1.2.2. On master, the issue is not present.

**Comment by Spekular** [comment]
@hawthornbunny can you please confirm whether or not the issue occurs in the 1.3.0-beta.1 version available at https://lmms.io/download ?

**Comment by hawthornbunny** [comment]
@Spekular Hi, apologies for the delay in this response, I didn't see the notification.

I checked this with 1.3.0-alpha and can confirm that the issue is resolved there - there are no more clicks and my SID compositions sound a lot healthier. Thanks very much!
