### ISSUE TITLE
Crash in master branch when opening/previewing ZynAddSubFX presets through file browser

### ISSUE THREAD

**Issue by ksnd** [LMMS/lmms#596]
presets:
https://drive.google.com/file/d/0B5jBSeQx_uSNd2piWjBQLWl1R0U/edit?usp=sharing

Debian 7 amd64
GCC 4.7.2

**Comment by badosu** [comment]
@ksnd Is this still an issue with LMMS 1.1.0?

I can't reproduce this, preset previewing is working fine to me.

**Comment by tresf** [comment]
Closing.  Please reopen or reference if this issue resurfaces.
