### ISSUE TITLE
1.3 Alpha playhead behavior bug in pianoroll

### ISSUE THREAD

**Issue by Feihei** [LMMS/lmms#5962]
When I pan the pianoroll window horizonally, the playhead line will move too, and then it will not align with the triangle cursor on top. I am using lmms-1.3.0-alpha.1.33+g4f74151f0-mingw-win64 version in win10

**Comment by Veratil** [comment]
Hi Feihei, I cannot reproduce this bug. Can you tell me if there was anything you did beforehand?

**Comment by qnebra** [comment]
https://youtu.be/JFFEb6qVE1U

Windows 10, latest alpha version, occurs on zoom levels above 100%

**Comment by Veratil** [comment]
Got it! Thanks!

**Comment by Veratil** [comment]
@Feihei @qnebra can you test the build in #5965 to try and reproduce the bug? All my testing trying to reproduce or even produce other odd bugs related to the position line seem to be squashed. :)

**Comment by Feihei** [comment]
> 
> 
> @Feihei @qnebra can you test the build in #5965 to try and reproduce the bug? All my testing trying to reproduce or even produce other odd bugs related to the position line seem to be squashed. :)
Thank you for the reply.
but sorry I don't know how to test, I don't have experience in pulling or building the source by myself

**Comment by qnebra** [comment]
There is lmms build bot comment in mentioned PR. You can download build to test pull request.

**Comment by qnebra** [comment]
Please close it after fix is merged to current master branch. But also this is your decision, so it is fine.
