### ISSUE TITLE
Translation issues/improvments

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms#597]
Posting this on behalf of a commmunity member.

Recently Esteban Viveros (emviveros;gmail;com) made a Portugese_Brazil translation of the components in LMMS.  This translation is comprehensive and should arrive in the next stable release. 

After translating components, Esteban made some side-notes on issues encountered, which have been listed below verbatim. If clarification is needed, please contact Esteban Directly at (emviveros;gmail;com)

![image](https://cloud.githubusercontent.com/assets/6345473/2688614/30630b04-c2b5-11e3-9dd0-2176dd2538e4.png)

***

**MeterDialog** 
-> `TIME SIG`  (Can't link)
-> Don't have translation option for `MIN`, `SEC` and `MSEC` words.

**ladspaBrowserView**
-> Don't have translation option for `LADSPA Plugin Browser` it is in Tools in menu and in the window title of this option.

**pluginBrowser**
-> `simple sampler with various settings for using samples (e.g. drums) in an instrument-track` (Can't link)
-> `versatile kick- & bassdrum-synthesizer` (Can't link)
-> `three powerful oscillators you can modulate in several ways`  (Can't link)

**sf2InstrumentView**
-> `Apply chorus (if supported)`  this comment are swapped with REVERB button comment which don't have translation option.
-> Don't have translation option for `Envelopes, LFOs and filters are not supported by the current instrument.` in ENV/LFO tab.

**InstrumentSoundShapingView**
-> Don't have translation option for `CUTOFF`

**InstrumentsMidiIOView**
-> (Can't link anything)

**OpulenZ**
-> (Can't link anything)

**lb302SynthView**
-> (Can't link anything)

**sfxr**
-> (Don't have translation option for this plugin)

**Comment by Umcaruje** [comment]
What's the status with this issue now? @DanWin and @midi-pascal made some improvements on this field.

**Comment by midi-pascal** [comment]
@Umcaruje I think most - if not all - of the problems about missing strings in translation files have been solved by the PR #2065 (commit ecbeaf7). The main cause was the usage of tr() inside macro's so the strings were not found by lupdate, and some other minor bugs in the code.

**Comment by DeRobyJ** [comment]
In 1.1.3, the only field that I know has translation in the .qm files but is shown in English is the whole Instrument Plugin tab.
The title, the description of the tab and each instrument description are still in English, while I remember reading some translated in previous versions.
I'm waiting for 1.2 to update Italian loca, and it would be good to have these fields translated!

**Comment by Umcaruje** [comment]
@tresf can this issue be closed?

**Comment by midi-pascal** [comment]
:+1:

**Comment by tresf** [comment]
Yeah, not much to speak about when the bug was emailed in.

**Comment by Umcaruje** [comment]
:+1:
