### ISSUE TITLE
VSTs ignore pitch bend range

### ISSUE THREAD

**Issue by Spekular** [LMMS/lmms#5997]
#### Steps to reproduce

- Load a VST in vestige, duplicate it
- Set the range on one instance to 60, leave the other at 1
- Automate the pitch knob on each instance to slide from minimum to maximum

#### Expected behavior

The VST with the range set to 60 should bend over a larger range.

#### Actual behavior

Both bends sound identical.

#### Affected LMMS versions

1.2.2, 1.3.0-alpha.1

**Comment by Spekular** [comment]
A previous issue with pitch bends was handled here https://github.com/LMMS/lmms/blob/master/plugins/vst_base/RemoteVstPlugin.cpp#L1016

Stuff that seems relevant:

Upon pitch knob changes, this method is called
https://github.com/LMMS/lmms/blob/f288137c228e540ba3dc439a6e385da9c5db60b0/src/tracks/InstrumentTrack.cpp#L606

And the actual calculation is done here
https://github.com/LMMS/lmms/blob/f288137c228e540ba3dc439a6e385da9c5db60b0/include/InstrumentTrack.h#L123

Upon range changes, this is called
https://github.com/LMMS/lmms/blob/f288137c228e540ba3dc439a6e385da9c5db60b0/src/tracks/InstrumentTrack.cpp#L616

Which also calls
https://github.com/LMMS/lmms/blob/f288137c228e540ba3dc439a6e385da9c5db60b0/include/InstrumentTrack.h#L129

**Comment by softrabbit** [comment]
Tried in OpulenZ, which I believe would suffer from the same bug if it was in InstrumentTrack. Pitch bend range works there.

**Comment by softrabbit** [comment]
Using the MIDI monitor VST from http://www.rs-met.com/freebies.html I get this output, which at a glance looks correct. This on Version 1.3.0-alpha.1.33+g4f74151f0 (win32/x86_64, Qt 5.9.8, GCC 7.3-win32 20180312).

```
Controller, Channel: 1, Number: 100 (Registered Parameter (fine)), Value: 0
Controller, Channel: 1, Number: 101 (Registered Parameter (coarse)), Value: 0
Controller, Channel: 1, Number: 6 (Data Entry (coarse)), Value: 3
```

**Comment by DomClark** [comment]
Most of the VST plugins I have don't respond to the pitch bend range, but Bitsonic's Keyzone Classic does. The fact that some plugins work, and that softrabbit's test indicates that the correct MIDI messages are sent, suggests that we aren't doing anything wrong and that some plugins just don't implement this feature. Can you test an affected plugin in a different DAW and see if it works there?

**Comment by Spekular** [comment]
> [...] we aren't doing anything wrong and that some plugins just don't implement this feature.

After further testing, this seems to be the case. Surprisingly, even though the plugins I tested (Serum, Addictive Keys) respond to pitch-bends and have a configurable range, they don't appear to react to the incoming messages.

> Can you test an affected plugin in a different DAW and see if it works there?

Testing in FL, which has a pitch knob with range, worked the same as LMMS. Ableton was a bit trickier as I couldn't find a configurable range, and manually attempting to send the right signals didn't do anything either, but essentially it behaved the same way as LMMS and FL.
