### ISSUE TITLE
[g4589004 | Linux Mint] LV2 error

### ISSUE THREAD

**Issue by GingkathFox** [LMMS/lmms#6011]
### Bug Summary

```Cannot load library /home/gingka/lmms-build/lmms/build/plugins/liblv2effect.so: (/home/gingka/lmms-build/lmms/build/plugins/liblv2effect.so: undefined symbol: _ZTI14Lv2ControlBase)
Cannot load library /home/gingka/lmms-build/lmms/build/plugins/liblv2instrument.so: (/home/gingka/lmms-build/lmms/build/plugins/liblv2instrument.so: undefined symbol: _ZTI14Lv2ControlBase)
```
whats this error?

#### Steps to reproduce
Build with `-DWANT_LV2=ON`.

#### Expected behavior
No errors in console
#### Actual behavior
The error above
#### Logs
<details>
  <summary>Click to expand</summary>
<pre>
› lmms                                                        lmms git:(master)
qt5ct: using qt5ct plugin
Notice: could not set realtime priority.
qt5ct: palette support is disabled
qt5ct: custom style sheet is disabled
Connection established.

Stream successfully created

Cannot load library /home/gingka/lmms-build/lmms/build/plugins/liblv2effect.so: (/home/gingka/lmms-build/lmms/build/plugins/liblv2effect.so: undefined symbol: _ZTI14Lv2ControlBase)
Cannot load library /home/gingka/lmms-build/lmms/build/plugins/liblv2instrument.so: (/home/gingka/lmms-build/lmms/build/plugins/liblv2instrument.so: undefined symbol: _ZTI14Lv2ControlBase)

</pre>
</details>

**Comment by GingkathFox** [comment]
Continued from discord: 
> ExperiBass — Today at 2:37 PM
Cannot load library /home/gingka/lmms-build/lmms/build/plugins/liblv2effect.so: (/home/gingka/lmms-build/lmms/build/plugins/liblv2effect.so: undefined symbol: _ZTI14Lv2ControlBase)
Cannot load library /home/gingka/lmms-build/lmms/build/plugins/liblv2instrument.so: (/home/gingka/lmms-build/lmms/build/plugins/liblv2instrument.so: undefined symbol: _ZTI14Lv2ControlBase)
 whats this error?
this on our end or naw?
Rdrpenguin — Today at 2:38 PM
typeinfo for Lv2ControlBase
Are we implementing Lv2ControlBase, or is that supposed to be in a separate library?
If we're supposed to be implementing it, we're forgetting to implement the key function. If it's supposed to be in a separate library, we're not linking against that library
Johannes — Today at 7:57 PM
It's in our implementation
@ExperiBass can you please file an error on github, so this won't get lost?

**Comment by rdrpenguin04** [comment]
So we just haven't implemented Lv2ControlBase yet? That's the problem?

**Comment by JohannesLorenz** [comment]
It is implemented - `src/core/lv2/Lv2ControlBase`. The error usually means that we failed to implement one of its virtuals. However, all virtuals should be implemented in "liblv2instrument.so"... So I'm not sure why the compiler complains.

@GingkathFox you're on master? Why haven't you had this error before?

**Comment by GingkathFox** [comment]
> It is implemented - `src/core/lv2/Lv2ControlBase`. The error usually means that we failed to implement one of its virtuals. However, all virtuals should be implemented in "liblv2instrument.so"... So I'm not sure why the compiler complains.
> 
> 
> 
> @GingkathFox you're on master? Why haven't you had this error before?

I never compiled with lv2 before is why

**Comment by rdrpenguin04** [comment]
```
$ nm build-release/plugins/liblv2instrument.so | grep _ZTI14Lv2ControlBase
                 U _ZTI14Lv2ControlBase
```
Hm. Which library is it supposed to be in?

**Comment by rdrpenguin04** [comment]
Oh, it looks like it's supposed to be in the `lmms` executable itself..?
@GingkathFox Check the output of `nm lmms | grep _ZTI14Lv2ControlBase`

**Comment by GingkathFox** [comment]
> Oh, it looks like it's supposed to be in the `lmms` executable itself..?
> 
> @GingkathFox Check the output of `nm lmms | grep _ZTI14Lv2ControlBase`

No output

**Comment by rdrpenguin04** [comment]
Try a clean build; it's there on my end.

**Comment by GingkathFox** [comment]
ok interesting, a fresh build fixed the error. Just in case:

```
› nm ./lmms | grep _ZTI14Lv2ControlBase                      build git:(master)
0000000000438740 V _ZTI14Lv2ControlBase```
