### ISSUE TITLE
MIDI output settings displayed incorrectly

### ISSUE THREAD

**Issue by dj-pixus** [LMMS/lmms#6019]
The value of Velocity and Program spinboxes on the MIDI tab are off by 1.
MIDI programs are numbered from 0 to 127 according to the standard, so one would expect to see these values in the ui. But LMMS uses a range of 1-128 where 1 is 0 and 128 is 127. This really can cause headache for users who don't know about it.
Similar thing happens with the velocity too, the difference here is that the actual value is correct and it's the view that shows manipulated values.
![2021-05-15-171143_250x70_scrot](https://user-images.githubusercontent.com/65627470/118368678-ccc93580-b5a2-11eb-841e-33fa0b474cf2.png)
Tested on 1.2.2 and master branch.

**Comment by softrabbit** [comment]
[The wikipedia page on General MIDI](https://en.wikipedia.org/wiki/General_MIDI#Program_change_events) says: _The numbers can be displayed as values 1 to 128, or, alternatively, as 0 to 127. The 0 to 127 numbering is usually only used internally by the synthesizer; the vast majority of MIDI devices, digital audio workstations and professional MIDI sequencers display these Program Numbers as shown in the table (1–128)._

I think it's best to follow the "vast majority" on program numbers. Velocity should probably be fixed, though.
