### ISSUE TITLE
Repeating notes are sometimes not displayed as pressed

### ISSUE THREAD

**Issue by xTibor** [LMMS/lmms#6025]
### Bug Summary

When a note repeats itself several times after each other the piano keys in the instrument window and in the piano roll doesn't always render them as pressed.

It's completely random when this happens, so I guess it might some kind of race condition between the previous note's release event and the new note's press event.

#### Steps to reproduce

1. Draw some bars of repeating 8ths of the same note.
2. Play them on loop.
3. Watch the piano keys in the instrument window and the piano roll not rendering some of the notes as pressed.

![20210520_052236](https://user-images.githubusercontent.com/1627292/118914949-6dfe1600-b92c-11eb-9dcb-7027e5a9387a.png)

#### Screenshot

https://user-images.githubusercontent.com/1627292/118915049-89692100-b92c-11eb-99b6-34621baddef3.mp4

#### Affected LMMS versions

AppImage, Version 1.2.2 (Linux/x86_64, Qt 5.9.7, GCC 5.4.0 20160609)
AppImage, Version 1.3.0-alpha.1.102+g89fc6c9 (Linux/x86_64, Qt 5.6.3, GCC 5.4.0 20160609).

**Comment by Sawuare** [comment]
Thanks for reporting. Looks like #3919 has returned. I will close this issue and open that one since it has more discussion.
