### ISSUE TITLE
Crash on exit from rpmalloc assert in debug builds, equalizer plugin related

### ISSUE THREAD

**Issue by PauseForAffliction** [LMMS/lmms#6026]
### Bug Summary
`rpmalloc` aborts from an assertion on program exit if the equalizer plugin is added to an FX track.
#5733 might be related, which was thought to be fixed by #5776.

Note: The few other plugins I've tested don't seem to cause this, only equalizer. I haven't tested many other plugins though.

#### Steps to reproduce
1. Run a debug build of LMMS.
2. Add the equalizer plugin to either the master FX track or a created FX track.
3. Close LMMS via the 'X' button or File -> Quit.

#### Expected behavior
LMMS closes without aborting preemptively.

#### Actual behavior
LMMS "crashes" from the assert calling an abort.

#### Screenshot
![image](https://user-images.githubusercontent.com/47124830/119030092-b2a6a300-b966-11eb-8f5b-8aa4ed929f6f.png)

#### Affected LMMS versions
Version 1.3.0-alpha.1.105
Debug configuration.

Unknown if on stable because I don't have the know-how to build and test 1.2.2

#### Logs
(From console)

`Assertion failed: span->list_size == span->used_count, file C:\LMMSDev\lmms\src\3rdparty\rpmalloc\rpmalloc\rpmalloc\rpmalloc.c, line 1248`

#### Note
Probably not a big deal since it happens on program exit, so the OS will (hopefully) clean up anyway, but still something to consider.

**Comment by PhysSong** [comment]
Reproduced in Linux+GCC debug builds, too.
https://github.com/LMMS/lmms/blob/877a93198f0793fb6e236c3694c7a02fc2527e57/plugins/Eq/EqControlsDialog.cpp#L200-L210
The two `setModel` calls passes `false` as the second argument, and this makes the default model constructed in the `automatableButtonGroup` constructor leaked.
