### ISSUE TITLE
Cannot move track up/down in song editor

### ISSUE THREAD

**Issue by andershu** [LMMS/lmms#6027]
### Bug Summary
Cannot move track up/down in song editor

#### Steps to reproduce
Try to drag a track up or down, as in 1.2.2

#### Expected behavior
Track moves when draged (after mouse left-clicking and holding)

#### Actual behavior
No action

#### Affected LMMS versions
lmms-1.3.0-alpha.1.102+g89fc6c960-mingw-win64

**Comment by qnebra** [comment]
Which area you try to use for drag? Also I didn't remember tracks being moved up & down when Clip/TCO is moved.

**Comment by zonkmachine** [comment]
Moving tracks up/down by dragging on the handle to the left still works for me on e9f264e37f0e73fbc24a031a8ec53a4cd3537dbd

**Comment by andershu** [comment]
Yes, that worked - thanks!
Rgds/Anders


    On Sunday, May 23, 2021, 06:02:41 PM GMT+2, Oskar Wallgren ***@***.***> wrote:  
 
 


Moving tracks up/down by dragging on the handle to the left still works for me on e9f264e

**Comment by andershu** [comment]
Hi!

It works when i click-hold on the left-most area of the track - in 1.2.2 I can click-hold in a larger area, but that's not important.
Regards/Anders


    On Sunday, May 23, 2021, 11:37:25 AM GMT+2, qnebra ***@***.***> wrote:  
 
 


Which area you try to use for drag? Also I didn't remember tracks being moved up & down when Clip/TCO is moved.
