### ISSUE TITLE
template for melodies

### ISSUE THREAD

**Issue by lamaleiste** [LMMS/lmms#6037]
https://github.com/lamaleiste/dr-wonderfuller-world/blob/main/musi.cpp

**Comment by DomClark** [comment]
It's not clear what you're asking for here. Please update this issue to follow our [feature request template](https://github.com/LMMS/lmms/blob/master/.github/ISSUE_TEMPLATE/feature_request.md), in particular filling in these three sections:
```markdown
### Enhancement Summary

#### Justification

#### Mockup

```
