### ISSUE TITLE
VeSTige: Notes play at the wrong pitch when using the JACK backend.

### ISSUE THREAD

**Issue by DarkRTA** [LMMS/lmms#6038]
Whenever I am using the JACK backend with VeSTige, all of the notes play about 147 cents too sharp. I have a feeling its probably some sampling rate mismatch weirdness as switching to the SDL backend seems to fix it.

#### Affected LMMS versions
1.2.2
1.3.0.alpha.1.102

**Comment by PhysSong** [comment]
The value you mentioned is about `48000/44100`, so it's likely a sample rate issue.
Which VST plugin is problematic? Is that for only some specific plugins, or all VSTs?

**Comment by DarkRTA** [comment]
This is affecting every VSTi I tried.

**Comment by PhysSong** [comment]
Bug confirmed. This is what's happening:

When a VST plugin is initialized, it gets the sample rate data from shared memory. `VstSyncController`, the class which fills the data, is initialized while `Song` is constructed. At this point, `Mixer` hasn't opened an audio device and returns at 44100Hz.
After that, `Mixer::initDevices` opens the specified audio device. The processing sample rate changes at this point, but the function doesn't notify the change. In the reported case, the sample rate is 48000Hz, but `VstSyncController` doesn't know the sample rate has been changed from 44100Hz to 48000Hz, making VSTs think it's running at 44100Hz.

The fix should be straightforward, only one or two lines in `Mixer::initDevices` are sufficient.

Meanwhile, you can work around the bug by exporting literally anything after starting LMMS. After the export, VSTs will receive the correct sample rate information and will run without such problems.
