### ISSUE TITLE
1.3 bug in piano-roll shortcut 

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#6039]
### Bug Summary
1.3 bug in two piano-roll shortcuts 
*Shift-right arrow 
*ctrl-right arrow

#### Steps to reproduce
Select notes
Use Shift-right arrow ao ctrl-right arrow
1.3 crashes
#### Expected behavior
Shift-right arrow should move selected notes one beat
ctrl-right arrow should move selected notes one bar
#### Actual behavior
Crash
#### Screenshot
No
#### Affected LMMS versions
1.3 (win64)

**Comment by PhysSong** [comment]
I couldn't replicate the crash under the same condition.

**Comment by musikBear** [comment]
This is the version
![image](https://user-images.githubusercontent.com/6662066/120892471-c4e33b00-c60e-11eb-8223-235b93dc06ab.png)
But if current Master do not have this problem, then it does not matter.

**Comment by Monospace-V** [comment]
It is worth noting that this crash happened only in an empty piano roll.

**Comment by PhysSong** [comment]
> It is worth noting that this crash happened only in an empty piano roll.

Thanks. I was able to reproduce the bug. The shifting code checks the position of the leftmost note to prevent moving notes to negative offset. When there are no notes, there's no such a note, but it's currently not checked properly.
https://github.com/LMMS/lmms/blob/fadf8c611ef37cf51fa0dd5c0d188a314c51004b/src/gui/editors/PianoRoll.cpp#L1213-L1216

**Comment by Veratil** [comment]
I can probably add this to #6063 unless anyone else wants to take it :)

**Comment by zonkmachine** [comment]
> I can probably add this to #6063 unless anyone else wants to take it :)

Please do!

**Comment by merrickclay** [comment]
@Veratil are you still working on this? If not I'll put together a quick PR to solve it. Should only be a few lines of code.

**Comment by Veratil** [comment]
> @Veratil are you still working on this? If not I'll put together a quick PR to solve it. Should only be a few lines of code.

I haven't had time to. Feel free to do it!
