### ISSUE TITLE
Feature request "Assign to a new FX-mixer channel" button for instruments?

### ISSUE THREAD

**Issue by unfa** [LMMS/lmms#604]
Now that we have the new FX-Mixer that requires manual adding of the new FX-channels, I thing it's a good idea to implement something that already have been discussed before in a slightly new fashion.

I wrote before about finding a way to automatically assign newly added instruments to FX-mixer channels, to cut some mouse-operation time for users.

Now it seems more reasonable and easy-to-do then ever before.

Take a look at this:

![mockup 01-01](https://cloud.githubusercontent.com/assets/491704/2689745/4ebaf89e-c31b-11e3-8dd1-bc3363200e08.png)

Pressing "New" in the FX-channel panel would:
· create new FX-channel;
· rename it after the instrument we're talking about;
· assign the instrument to it.

Saves time and is easy to understand. Am I correct?

**Comment by badosu** [comment]
@unfa Please check https://github.com/LMMS/lmms/pull/1572, maybe we can close this issue?

**Comment by tresf** [comment]
@badosu since his request is in the context of the instrument, we may want to extend this feature into there as well.

**Comment by badosu** [comment]
@unfa @tresf Adding a modified version of the new FxChannel context menu to the Fx Spinner would deliver this feature?

**Comment by tresf** [comment]
@badosu yes, I think it would.  I'm not sure where to put it on the GUI, but I think the proposal is in the right direction.

**Comment by badosu** [comment]
@tresf This was discussed as an option on https://github.com/LMMS/lmms/issues/921 as well.

Basically, the most simple way would be to add the "Assign to new FX Channel" action to the context menu when right-clicking the Fx Spinner. The more sophisticated would be to port the idea of also being able to assign to a different mixer like https://github.com/LMMS/lmms/pull/1572.

**Comment by tresf** [comment]
Context menu is simple and sweet IMO. :+1:
