### ISSUE TITLE
Default value of Note Velocity - 100%?

### ISSUE THREAD

**Issue by anytizer** [LMMS/lmms#6045]
I connected a simple piano with MIDI USB function. This hardware does not have velocity sensitivity.
But the default note velocities recorded in LMMS are nearly 200%.

Shouldn't they be 100% instead?

#### Screenshot
![image](https://user-images.githubusercontent.com/5563341/121284284-d8ee9d00-c899-11eb-80f5-bae1637b8f84.png)

#### Affected LMMS versions
1.3

**Comment by dj-pixus** [comment]
This is because your MIDI keyboard probably works with a velocity of 127. You need to set this value as the base velocity. It is not a bug, this is how it's supposed to work.
