### ISSUE TITLE
FX-Mixer: Drag'n'Drop Reordering

### ISSUE THREAD

**Issue by unfa** [LMMS/lmms#605]
What?

The idea is to make FX-mixer strips reorderable just like tracks are - using mouse drag'n'drop technique.

Why?

Sometimes I'd like to change the order of my FX-Mixer channel strips.
I like to group instruments in the FX_mixer by their function and category:
1. Drums
2. Basses
3. Pads
4. Lead
5. Special FX
It happens, that I added a new Kickdrum that belongs to the first group, but I have to assign it to channel #23 - I can't insert a new channel and offset all the rest to keep them linked and stuff.

Being able to reorder them just like instruments in the Song editor would be a great thing. Of course the numbers would change so all assigned instruments/sends should have to be updated. This could start mayhem if implemented poorly...

**Comment by badosu** [comment]
@unfa You can move mixers in a very fast way using <Alt-left/right>.

I don't know if adding a grip to the mixers is desirable, but if it is: could you create a mockup for us to see how it would look like?

**Comment by Sti2nd** [comment]
> <Alt-left/right>

wat, when, why are no one documenting this. Or rather, we don't require devs to document what they make at all, and that is stupid?

**Comment by badosu** [comment]
Hi @Sti2nd, I was surprised to find this when I was tinkering with a mixer crash.

**Comment by Sti2nd** [comment]
> do you wanna help documenting?

Yes of course.

**Comment by tresf** [comment]
> could you create a mockup for us to see how it would look like?

Possible mockup (to re-use the realestate a bit):

![image](https://cloud.githubusercontent.com/assets/6345473/5930396/fc882896-a65c-11e4-9f22-470d7fdb23d5.png)

**Comment by badosu** [comment]
Hmmm... is the top of the selected mixer used in any other way? Is this function overlapping any other that already exists?

**Comment by tresf** [comment]
> Is this function overlapping any other that already exists?

No that I'm aware of, but it would appear to require it to be selected to be moved which may be misleading.

**Comment by badosu** [comment]
@tresf Selecting it to move would be fine by me. It's better than having an extra grip hanging around all the time.

**Comment by tresf** [comment]
@badosu agreed and I'm not confident we can't clone the drag functionality to the title anyway.  I don't really like the dedicated drag handles in software due to the amount of space they take up.  I'm not sure how well this would work for Song Editor and BB Editor tracks, but whatever we decide we should be as consistent across interfaces as possible.

There's also an enhancement out there to do this drag handle up/down with the FX plugins themselves.

**Comment by tresf** [comment]
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.
