### ISSUE TITLE
Mixer Groups

### ISSUE THREAD

**Issue by unfa** [LMMS/lmms#606]
Once the mixer have no A/B/C/D tabs - I expect more time being spent scrolling the mixer to reach needed channels. This means reduced usability - more time needed to achieve the same result.

I guess the tabs were removed to make mixer sends usable. I guess sends would work with tabs, but nevermind :)

I think to some degree this situation could be optimized using mixer groups, especially if these groups could be accessed just the A/B/C/D tabs were - instantly.

Here's my idea:

![mockup 02-01](https://cloud.githubusercontent.com/assets/491704/2689828/d88caf64-c31f-11e3-9606-33c2174277b1.png)

In the above mockup channels FX1, FX2 and FX3 belong to GROUP A, while channels FX4 and FX5 belong to GROUP B.

To assign a channel to a mixer group, simply drag and drop it after the group's strip - all strips that are located after it (until the next group strip) are confined to this group. A group could also populate it's color into all strips it owns, to indicate this fact.

Also moving around group strips could be a way to move channels to a different group. If the user dragged the "GROUP B" strip one unit left, the FX3 channel would shift from GROUP A to GROUP B.

If you want to hide strips from a group, click on the "Expand/Collapse" button - it will leave only the group visible.

I think this concept needs to evolve a lot before we reach the best way to handle massive tracks well, but it's something. I see that collapsing some mixer groups could save up time spent on scrolling the mixer - while still we have access to all strips if we need (to set up sends for example).

Additionally:

The groups could have "mute" and "solo" buttons as well - making all channels belonging to a group muted or soloed respectively. However, the groups are not submixes, so no faders or VU-meters should occur.

I hope to inspire the usability-lifting spirit in this great community :)

PS:

I think the color picker could be replaced with a simple HUE knob - because saturation and value should be defined by the theme to ensure all text will be readable and stuff will look similar.
Also the HUE could be automatically assigned to new groups to ensure a new group will always look unique. Also the HUE knob could be automatable for some eye-sore effects, IDK.

**Comment by tresf** [comment]
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.
