### ISSUE TITLE
More in default view with simple change

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#6061]
### Enhancement Summary
A simple way to get more content shown, and especially not disappearing, when using either Main component or songeditor

#### Justification
Haven to re-pick smaller windows -typically instruments, is a d...r..a..g

#### Mockup
I have these two screenies
First lets see what we have atm:
![image](https://user-images.githubusercontent.com/6662066/122631725-eb54ac00-d0cd-11eb-9aa5-530cca258175.png)

My question is: Why have all that witch is crossed?
If the height of the songeditor actually only match the height of the instrument-stack, then most of the time element beneath songeditor would be directly accessible.
It is doable if the window is normalized:
![image](https://user-images.githubusercontent.com/6662066/122631787-96656580-d0ce-11eb-921a-93109c1df3d5.png)
-But most users dont do that.
If the height of the songeditor was similar to instrument-stack, more elements would be visible and clickable

**Comment by Spekular** [comment]
I'm not sure I see the issue. This same thing occurs in every other DAW (space is unused if the user makes the track list view bigger than necessary) and your example of a fix is already available in LMMS (using windowed mode). Are you proposing that we set a maximum height on the song editor?

Also, this is only a problem when the number of tracks is low enough to fit on screen *and* leave this much space. I can't speak for the average user, but IME and from what I can tell of others this is exceedingly rare once a project gets into the later stages.

**Comment by musikBear** [comment]
@Spekular 
This
> this is exceedingly rare once a project gets into the later stages

Is actually right, it would be to little gain for the cost
Retracted.👍
