### ISSUE TITLE
CMT submodule: Needed a single revision

### ISSUE THREAD

**Issue by anytizer** [LMMS/lmms#6067]
The CMT project perhaps needs something to be done in naming one of its branch.
FYI I was looking into articles about compiling in Windows.

```
__\lmms>git submodule update --remote
fatal: Needed a single revision
Unable to find current origin/master revision in submodule path 'plugins/LadspaEffect/cmt/cmt'
```

git version 2.26.2.windows.1

**Comment by anytizer** [comment]
Scenario: I cloned the lmms git first, without submodules.
Then pulled the submodules later.

May be creating a branch named "master" in cmt project should fix this.

**Comment by zonkmachine** [comment]
Hi!

The CMT submodule hasn't change and seem to work for everybody else.

From the instructions here: https://github.com/LMMS/lmms/wiki/Accessing-git-repository
Try: `git submodule update --init --recursive`

If this doesn't work our Discord `#support`channel gives the fastest response: https://discord.com/invite/3sc5su7

**Comment by anytizer** [comment]
The following seems to be working:

    git submodule update --init --recursive

**Comment by tresf** [comment]
Normally, our cmake shim would detect the broken submodule and fetch it, but MSVC has CMT disabled, so it makes sense that we'd have some issues with that workflow for someone trying to enable CMT on Windows.

On Mac/Linux, this is what a fresh clone will say in regard to CMT:

```
Checking submodules...
[...]
-- Checking cmt...
--   Fetching plugins/LadspaEffect/cmt/cmt @ --depth 100
Submodule path 'plugins/LadspaEffect/cmt/cmt': checked out 'f7c25ed4ef7f4d7efb1bcd4229d25595d4f1ce55'
Submodule 'plugins/LadspaEffect/cmt/cmt' (https://github.com/lmms/cmt) registered for path 'plugins/LadspaEffect/cmt/cmt'
Cloning into '~/lmms/plugins/LadspaEffect/cmt/cmt'...
```

However, on Windows, it will say the following instead:
```
Checking submodules...
[...]
-- Skipping plugins/LadspaEffect/cmt/cmt matches "plugins/LadspaEffect/cmt/cmt" (absent in PLUGIN_LIST)
```

I forced this to update using `git submodule update --init --recursive` and it seems to work:
```
Cloning into 'lmms/plugins/LadspaEffect/cmt/cmt'...
[...]
Submodule path 'plugins/LadspaEffect/cmt/cmt': checked out 'f7c25ed4ef7f4d7efb1bcd4229d25595d4f1ce55'
```

So I think this may be due to your git version?

**Comment by tresf** [comment]
Oh, I see you posted a solution.  Thanks! :)
