### ISSUE TITLE
flat ui?

### ISSUE THREAD

**Issue by KiteAB** [LMMS/lmms#6069]
### Enhancement Summary
the ui in the 21st centuryyyyyy

#### Justification
too old ui now

#### Mockup
like win10 or fl studio?

**Comment by Spekular** [comment]
This is neither specific nor constructive. Either way, we have an ongoing effort to move away from the MDI based GUI: #1911

~~Also, I have to laugh at the idea of FL's UI as something to aspire towards~~

**Comment by RoxasKH** [comment]
Ok, so this isn't really an issue, even if i get what you mean.
Although, it's difficult to compare a daw design to an OS design, and FL UI is anything but flat.

Also, i'd like to make you aware about this, which has been an ongoing discussion for a long time.
https://github.com/LMMS/lmms/issues/1911

The main problem, is, this is an opensource software, people aren't paid for developing it and use their free time, also LMMS is trying to fix bug and missing feature before UI for the sake of usability (for example, recording is still missing).
If you know programming and wanna contribute, tho, you're welcome.

Also i wanna stress how progress on the ui are under development, too.
For examples:
https://github.com/LMMS/lmms/pull/5952
https://github.com/LMMS/lmms/pull/5261

Not to mention LMMS is themeable, and you can find a lot of theme on the lsp.
An example of a flat theme would be Liquid
https://lmms.io/lsp/?action=show&file=18140

Or if you like FL ui, there's also an FL one
https://lmms.io/lsp/?action=show&file=15060
