### ISSUE TITLE
Preset retains solo/muted state

### ISSUE THREAD

**Issue by Monospace-V** [LMMS/lmms#6073]
### Bug Summary
It is possible for me to solo a track, save a preset, and later drag that preset into a project, and the preset still has solo on.
In other words, this:

https://user-images.githubusercontent.com/76674645/124378914-c0737600-dcd1-11eb-9388-d1db34f3dceb.mp4

#### Steps to reproduce
Step 1: Make a solo instrument track
Step 2: Save track as a preset without unsoloing it
Step 3: Create a new project and drag it into the project

#### Expected behavior
Preset should not retain information like whether track is muted or not.

#### Actual behavior
Preset saves as solo on.

#### Screenshot
![image](https://user-images.githubusercontent.com/76674645/124378941-e13bcb80-dcd1-11eb-9f5a-de1be2c115d8.png)

#### Affected LMMS versions
1.3 alpha, 1.2.0, (Presumably everything in between and before those)

Note: also extends to muted presets.

**Comment by Demomaker** [comment]
Shouldn't this issue be closed, because the fix was merged?

**Comment by Monospace-V** [comment]
Yes. Done.
