### ISSUE TITLE
Playhead tracking interferes. Allow freely scrolling around the Song Editor & Piano Roll while it is playing

### ISSUE THREAD

**Issue by alexandervrs** [LMMS/lmms#6082]
### Bug Summary
Playhead tracking interferes. Allow freely scrolling around the Song Editor & Piano Roll while it is playing.

#### Steps to reproduce
1. Press the Play button while in the Song Editor or in Piano Roll.
2. Try to scroll back as the pattern is playing. The view will scroll and focus on the playhead always fighting against your will.

#### Expected behavior
The view to allow manual scrolling while it is playing, very often you quickly need to navigate around and fix things in a song as it is playing. Having to constantly start and stop playback to do editing is tedious. Clicking on the view while the song is playing shows intent that the user noticed something and wanted to do some edits on the fly, or they simply might want to freely oversee the behind and ahead of the playback.

This could be a "Playhead tracking" Settings option with the choices to:

1. Always track & return
Current LMMS behavior.  But will stop playback once the user tries to click on something & return the view back to the playhead initial position. (Like how Stop button works)

2. Always track & stay
As above. But will stop playback once the user tries to click on something & stay at that position (do not return back to initial playback position).

3. Stop tracking on demand (Should be LMMS default behavior)
Make it so the view initially follows the playhead but once the user clicks on the view somewhere, the playhead tracking stops but the song keeps playing. 

4. Snap once playback starts
The view will snap to the playhead start position once at the beginning of the playback, but will not track it anymore.

5. Never track
The playhead will not be tracked at all.

#### Actual behavior
Right now the playhead is being tracked while the song plays and will not allow any user input while it does so, you cannot navigate around the view while the song is playing.

#### Affected LMMS versions
1.3.0-a

**Comment by Spekular** [comment]
This is already configurable, disable auto scroll and your viewport can be freely moved even during playback.
