### ISSUE TITLE
Drumsynth filter disregards sample rate

### ISSUE THREAD

**Issue by softrabbit** [LMMS/lmms#6087]
### Bug Summary
The filter in Drumsynth doesn't take into account sample rate, and so it doesn't sound the same e.g. when exporting with oversampling. Could be other parts too besides the filter.

#### Steps to reproduce
Create a beat pattern using some .ds sounds that use the filter, e.g. the TR606 ones. Export that to audio using different sample rates, the larger difference between them the better.

#### Expected behavior
Audio should sound the same.

#### Actual behavior
Audio doesn't sound the same.

#### Screenshot
![Screenshot from 2021-07-14 20-29-01](https://user-images.githubusercontent.com/6411463/125666275-516f77f5-21ad-4b52-a73d-4e20bb9d8bd3.png)

#### Affected LMMS versions
Git master.

(Looks like this was introduced in #406 and guess who did that... :flushed: )

**Comment by zonkmachine** [comment]
> Could be other parts too besides the filter.

Yes. At least Noise Bands 1 and 2 also seem to be affected.

**Comment by softrabbit** [comment]
> > Could be other parts too besides the filter.
> 
> Yes. At least Noise Bands 1 and 2 also seem to be affected.

Damn. That part seemed OK to me when I did some listening comparisons... The ones I found in addition:

- Noise slope (in the aptly named variable NT) which seems to control a filter (LPF for values <0, otherwise HPF).
- Overtones in mode 3 ("808 cymbal"), some kind of filter there too.
- Distortion includes some downsampling (averaging up to 20 samples). 
- The "droop" rate of tone generation might be off, too. 

The distortion and droop rate might be fixed simply through multiplying or dividing with a coefficient. The filters are harder, the optimal solution would probably be reverse engineering them to figure out the formulas for the magic numbers used. I have no idea how feasible that is. But who knows, maybe a DSP expert can see at a glance what is going on.

**Comment by zonkmachine** [comment]
> Damn. That part seemed OK to me when I did some listening comparisons... The ones I found in addition:
> 
>     * Noise slope (in the aptly named variable NT) which seems to control a filter ...
> 
>     * Overtones in mode 3 ("808 cymbal"), some kind of filter there too.
> 
>     * Distortion includes some downsampling (averaging up to 20 samples).
> 
>     * The "droop" rate of tone generation might be off, too.

I think it would be helpful with a setup of .ds files that demos the individual sound generators/filters separately. It would make troubleshooting so much easier.

**Comment by zonkmachine** [comment]
I actually can't replicate this issue. It looks like it was fixed in ce722dd6b6cdfa5c7378161ce7d1fa98bfe5fec2/https://github.com/LMMS/lmms/pull/6610

**Comment by zonkmachine** [comment]
^Closed as fixed. Please reopen this issue if you can still replicate it on master.
