### ISSUE TITLE
There is no vertical line that follows the playhead & extends all the way to the bottom in the Piano Roll view

### ISSUE THREAD

**Issue by alexandervrs** [LMMS/lmms#6090]
### Bug Summary
There is no vertical line that follows the playhead & extends all the way to the bottom in the Piano Roll view, that shows where the playback currently is across the pattern, but one exists in the Song Editor.

#### Steps to reproduce
Just open Piano Roll and move the playhead.

#### Expected behavior
To show a vertical line extending all the way to the bottom of the view similar how it is in the Song Editor.

#### Actual behavior
Right now there is no vertical line drawn in the Piano Roll.

#### Screenshot
![Issue](https://i.imgur.com/K9VpJnY.jpg)
(Marked with red where the playhead line should appear normally)

#### Affected LMMS versions
1.2.2

**Comment by Veratil** [comment]
Fixed in master branch as of #5253
