### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by arcade-legend** [LMMS/lmms#6100]
Hi

- What is the minimum windows version supported?

- does lmms offer extra samples to be downloaded somewhere?

- which format (new or old) do I need to use to save my songs in order to be able to load them in the 1.3.0 version of lmms?
Thx

**Comment by Spekular** [comment]
- I know windows 7 works, unsure about earlier versions. 
- There are currently no samples provided on lmms.io, but when the sample library is replaced we intend to provide a download of the old one for compatibility reasons. As with any other DAW you will likely want to acquire third party samples
- LMMS is backwards compatible between minor versions, and as such LMMS 1.3 can load projects created in 1.2, 1.1, etc. Keep in mind that projects saved with 1.3 will not necessarily load correctly in 1.2. Saving as .mmp makes it easier to modify your projects in a text editor, but if you're concerned about projects
