### ISSUE TITLE
feature request: custom UI color

### ISSUE THREAD

**Issue by arcade-legend** [LMMS/lmms#6104]
### Enhancement Summary

It would be nice to allow users to select colors for the UI windows: background color of a window, button background color, colors for the instruments "blocks" in the song-editor, ...

#### Justification
A complete user customizable UI color setting is nice to adjust the UI to any usage or environment by adjusting the colors

(I see you can choose a folder for themes, but there is no option the create a theme or save a theme...)

**Comment by Spekular** [comment]
Theming *is* available, as evidenced by the option you mention, the classic theme included with LMMS, and the themes available on the LSP. Simply copy an existing theme (e.g. the default one) and edit style.css and the images as you see fit.

**Comment by arcade-legend** [comment]
This is not a user friendly way to make a theme!
THere should be UI widgets to select colors for everything.
