### ISSUE TITLE
feature request: full screen mode

### ISSUE THREAD

**Issue by arcade-legend** [LMMS/lmms#6105]
### Enhancement Summary

It would be great, in order to maximize screen space, to have a feature to enable full screen mode. This removes the window title bar and/or can hide the toolbar(s) at the top of the window.

#### Justification

Maximize screen space.

**Comment by Spekular** [comment]
Already available in master. Please search for existing issues before opening new ones.

**Comment by arcade-legend** [comment]
I don't find any option in version 1.2.2 to go full screen.

**Comment by Spekular** [comment]
Correct. This feature is still only available on the master branch, hence you can find it in the 1.3 alphas, but not 1.2.

See #5563.
