### ISSUE TITLE
feature request: samples in FLAC format

### ISSUE THREAD

**Issue by arcade-legend** [LMMS/lmms#6106]
### Enhancement Summary

Samples in FLAC format supported.
https://xiph.org/flac/

#### Justification

Usefull for people wanting lossless compression on their samples.

**Comment by Spekular** [comment]
FLAC samples can already be loaded. The reworked sample library will feature lossless files, and convertong the existing library to FLAC would increase size without improving quality.

**Comment by zonkmachine** [comment]
Also. In master/lmms-1.3 you can export your project in FLAC.
