### ISSUE TITLE
feature request: export to FLAC

### ISSUE THREAD

**Issue by arcade-legend** [LMMS/lmms#6111]
We can now export to wav, ogg and mp3
What do you think about adding FLAC to this list?

**Comment by Spekular** [comment]
If you had read the replies to your previous (and also invalid) request, you would know that this is already available in master: https://github.com/LMMS/lmms/issues/6106#issuecomment-886229424

Simply searching "flac" also gives tons of results showing that FLAC export is already possible. If you don't improve the quality of your issues, we'll have to prevent you from opening new ones.

**Comment by Spekular** [comment]
To be proper: FLAC export was added in #3731
