### ISSUE TITLE
feature request: new instrument Atari chip

### ISSUE THREAD

**Issue by arcade-legend** [LMMS/lmms#6113]
Hi

I would like to request a new instrument, the Atari chip.
Here is an example of a VST: http://www.preromanbritain.com/ymvst/

thx in advance

**Comment by arcade-legend** [comment]
Why do you close all my feature requests?
This is a GREAT new instrument!!!

**Comment by arcade-legend** [comment]
OPEN THIS ISSUE AGAIN!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by zonkmachine** [comment]
Sorry. Coding a new plugin is not a trivial thing and the developers is needed for other tasks. Especially since we have plenty of chiptunes already. Use the VSTi that you linked to instead.

**Comment by arcade-legend** [comment]
So lmms is a dead project? Nothing new is added anymore?

**Comment by zonkmachine** [comment]
It is not a dead project but you are now actually spamming the issue tracker and you need to start reading the replies.

1. Join our Discord community and use the support channel there.
2. As you are new to LMMS why don't you spend a couple of more months to get used to it before opening requests for functions/plugins that are already in place?
3. Use the search functions before opening an issue. Here on GitHub, on Discord and as usual, Google.
