### ISSUE TITLE
LMMS crashes when I try to minimize a plug-in really quickly

### ISSUE THREAD

**Issue by Lxg3nD** [LMMS/lmms#6136]
Particularly the keyzone classic Plug-In but bigger Plug-Ins crash way, way more. Please fix this issue, Thank You.

**Comment by DomClark** [comment]
I can't reproduce this. Could you provide more detailed instructions on how to trigger it, or even a short video demonstrating the bug?

**Comment by Lxg3nD** [comment]
https://user-images.githubusercontent.com/89130928/129892697-ff1c9306-21aa-4a0c-b73f-3ff6b01d1b71.mp4

i wasn't able to show the crash but it freezes lmms and says lmms is not responding when i click minimize on the plugin

**Comment by Spekular** [comment]
Can you test if this still occurs in the alpha version?

**Comment by Lxg3nD** [comment]
so far no problem on the alpha

**Comment by Spekular** [comment]
I'll close this for now then. Reply here again if it happens with the alpha and we'll reopen then :)
