### ISSUE TITLE
Redraw Piano Roll window if open when using BB Editor

### ISSUE THREAD

**Issue by Monospace-V** [LMMS/lmms#6137]
### Bug Summary
Adding steps to beat/bassline editor with piano roll of the instrument you are adding steps to open next to it: piano roll doesn't update until it is hovered over.

#### Steps to reproduce
1. Open B/B Editor
2. Open an instrument in BB editor in piano roll and keep both windows side by side (so you can see what happens)
3. Place some steps in BB Editor without moving mouse towards piano roll.
4. Piano roll does not update unless hovered over.

#### Expected behavior
Piano roll update as steps added

#### Actual behavior
Piano roll updates only after moving mouse over it.

#### Screenshot
(Video)

https://user-images.githubusercontent.com/76674645/130049053-a52932de-ffca-43ff-b9ee-31787caac845.mp4

#### Affected LMMS versions
1.2.0, 1.3 alpha, presumably everything in between, (interestingly this issue does not show up on LMMS 0.4)

**Comment by Veratil** [comment]
This isn't a bug per se, since it does update after you hover over the Piano Roll, which means everything is still working under the hood.

This is actually an effect of Qt. Since nothing is signaling the piano roll window to update, Qt will not redraw it to save CPU.

**Comment by saswatpp** [comment]
hey @Veratil could you give some clue where should I start? I want to start contributing to the project. Thanks.

**Comment by Veratil** [comment]
> 
> 
> hey @Veratil could you give some clue where should I start for this particular issue? I want to start contributing to the project. Thanks.

Might take a look in https://github.com/LMMS/lmms/blob/master/src/gui/PatternView.cpp :)

**Comment by saswatpp** [comment]
Although it does call `getGUI()->pianoRoll()->update()` still the UI doesn't update itself in the following file: 
https://github.com/LMMS/lmms/blob/f74271075874c482e4c6af0bd0bb0febe1042314/src/gui/PatternView.cpp#L227

Can you suggest what might be causing the bug ? @Veratil Thanks.

**Comment by Veratil** [comment]
Try taking it out of the if guard.

**Comment by saswatpp** [comment]
Ok, so tried taking it out of the `if block` but it didn't have any effect.

**Comment by Veratil** [comment]
Try changing `update()` to `repaint()`.

**Comment by Veratil** [comment]
If repaint works then try putting the if guard back and seeing if it still works.

**Comment by saswatpp** [comment]
unfortunately repaint() doesn't work also(without the id-guard also). Will look at the code again.

**Comment by Veratil** [comment]
If repaint isn't working then we need to check if it's even hitting that part of the code. Put a printf before the repaint call and check if it's getting called at all. The repaint function tells Qt to *immediately* run the paintEvent function of the widget.

**Comment by saswatpp** [comment]
yes the printing works whenever I click on the BB pattern with its piano roll open. But same as before, the pianoroll doesn't get updated. 
I also tried `gui()->pianoRoll()->parentWidget()->repaint()/update()`, without any effect.

**Comment by merrickclay** [comment]
After investigating this issue for a bit, it seems that adding/removing a not in the BB Editor does update the Piano Roll if the Piano Roll is focused when the click that adds/removes the not occurs. In other words if I click on the Piano Roll window before adding or removing a beat to the instrument in the BB Editor, it will update the Piano Roll properly. Is it possible that the update() function (which is being called) only updates the window if it is in focus?

**Comment by merrickclay** [comment]
@saswatpp are you still wanting to work on this issue?

**Comment by saswatpp** [comment]
@merrickclay no, I am not working on this anymore, you can take over this one :)
