### ISSUE TITLE
Enhancement : Hot-keys (key-shortcuts) for piano-rolls Scale and Chord tools

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#615]
Mostly because these dropdwns 'disapear' on a std screen, it would be nice if there was key-shortcuts for them. Now the piano-roll need to be moved to the left in order to get to the buttons, then back again. tedious.
(propl not an issue for those with wide-screen 16:4. Not all got that)

**Comment by tresf** [comment]
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.
