### ISSUE TITLE
MIDI Export with BPM >= 256 incorrect output

### ISSUE THREAD

**Issue by Veratil** [LMMS/lmms#6153]
### Bug Summary
When exporting MIDI the tempo value isn't saved properly if the BPM is set to 256 or higher.

#### Steps to reproduce
Set BPM to 256 or higher and export as MIDI, view MIDI hex meta event `FF 51 03 tt tt tt` and tempo will be LMMS value mod 256.

#### Expected behavior
Tempo is properly set.

#### Actual behavior
Tempo is set to value mod 256.

#### Affected LMMS versions
All

### Extra Info
[plugins/MidiExport/MidiFile.hpp:242](https://github.com/LMMS/lmms/blob/master/plugins/MidiExport/MidiFile.hpp#L242) uses `uint8_t tempo` which truncates the `int tempo` of [plugins/MidiExport/MidiExport.cpp:80](https://github.com/LMMS/lmms/blob/master/plugins/MidiExport/MidiExport.cpp#L80)

@PhysSong you were last to work on this so would like your input on solutions. We could either change the `uint8_t` to `int` across most of the class and handle accordingly, or I can work on using the library'd version of portsmf from Tenacity and use the SMF writer there so we can get rid of our own rolled writer.

**Comment by JGHFunRun** [comment]
So it turns out that  the `tempo` variable in the `Event` struct is a `uint32_t` which begs the question of WHO THE FUCK CHOSE TO USE `uint8_t` FOR THE `addTempo` FUNCTION

And here I was worrying that some unforseen thing that depends on `Event::tempo` would break, PR will be up very shortly
