### ISSUE TITLE
Limit white liner to max tracks only

### ISSUE THREAD

**Issue by anytizer** [LMMS/lmms#6159]
For some aesthetic/decorative reasons, the vertical white liner should be limited to the max height of the tracks only.
Currently, it goes too below until the screen or track area ends.

When a new track is added or removed, the height should adjust by the space occupied by the new change.

![image](https://user-images.githubusercontent.com/5563341/132955571-7e11032e-84ca-4e9a-8c72-980b5922475c.png)

**Comment by mrf7777** [comment]
I think that this is a good issue for me, and I would like to work on it.
