### ISSUE TITLE
ZynnAddSubFX Gui does not open on LMMS

### ISSUE THREAD

**Issue by 2-bithacker** [LMMS/lmms#6169]
####Summary
ZynnAddSubfX Gui does not open on LMMS

####Actual Performance
When I click on the "Show GUI" button in the middle of the ZynnAddSubFX display, it does not open.

####Preferred Performance
When I click on the "Show GUI" button in the middle of the ZynnAddSubFX display, it opens the GUI.

#### Screenshot
![2021-09-24-152306_1920x1080_scrot](https://user-images.githubusercontent.com/90713990/134729310-589f75df-d3cf-4d65-a938-e648f4ca515b.png)

#### Affected LMMS versions
1.1.3

#### Logs
<I am using Raspberry Pi OS Buster>

**Comment by DomClark** [comment]
1.1.3 is very old. Our latest stable release is 1.2.2, and when reporting bugs, it's worth testing our alpha version too to see if the issue has been fixed already. Unfortunately, we don't maintain builds for the Raspberry Pie, so you may have trouble updating.

**Comment by 2-bithacker** [comment]
1.1.3 is the newest I can get on raspberry pi os. If I can get anything newer, I would like it very much.

**Comment by PhysSong** [comment]
> 1.1.3 is the newest I can get on raspberry pi os.

You can get 1.2.2 if you're on the latest Raspberry Pi OS(based on bullseye). Older version based on Debian buster provides 1.1.3.

If you still experience the same bug with 1.2.2, please let us know. If you need an AppImage, I can build one upon request.

**Comment by 2-bithacker** [comment]
I did get it to work on the latest raspbian bullseye.  (Not that I need it, but if you could make linux appimages of LMMS for ARM processors, it would be easy for people that are unexperienced to set it up.  The current appimage that they have available for download at lmms.io only works for AMD processors.  Besides, there are very few apps that even make a ARM appimage, and LMMS could become more popular among ARM users for that reason alone.)
