### ISSUE TITLE
Loop Points Have Small Overhang Above Pan Knob

### ISSUE THREAD

**Issue by JGHFunRun** [LMMS/lmms#6187]
### Bug Summary

Loop points have overhang just over where the pan knob is (not sure if that makes sense, see screen shots). After some more testing it appears that this is the timeline bar as a whole since the bar numbers are also visible in this overhang. Although not always.

Someone can probably come up for a better name for this than me

#### Steps to reproduce

Move the song editor so that the loop point is over the bar _exactly_ one bar to the left of the ones visible in the song editor, it can extend into the song editor it should just have a part of it above a bar one to the left of the leftmost currently visible bar. 

#### Expected behavior

To not have the overhang.

#### Actual behavior

There's an overhang over the pan knob. Also if a bar number shows up that may also be visible. _May_ because I've had the number show but I can't replicate it. (I do have a screenshot though)

#### Screenshots

You can't see the pan knob because it's a BnB track in these.

![example-of-overhang](https://user-images.githubusercontent.com/52897905/136071018-240847cb-576c-4386-ad37-47955e19d6dd.png)

![example-of-overhang-4](https://user-images.githubusercontent.com/52897905/136071045-26919b93-9f9e-4527-ba70-9dc1bf3e776d.png)

(note on the last one: I couldn't replicate the number appearing like that, but I have to assume it would be fixed the same way as the rest of this bug)

#### Affected LMMS versions

Occurs on stable, nightly/alpha and master for sure. All?

**Comment by allejok96** [comment]
This could be closed, right?

**Comment by anytizer** [comment]
I was one of the spectator of this issue; and I see in new commit: it does not exist anymore in Linux.
