### ISSUE TITLE
the flatpak version of lmms needs better synths bundled with it. also use zyn-fusion.

### ISSUE THREAD

**Issue by pyrotek45** [LMMS/lmms#6199]
### Enhancement Summary
Basically lmms is lacking good synths. I don't think any of the bundled synths besides zynaddsubfx can do basic unison(or basic supersaw sounds used in most edm music and trance). theyre all sort of tailored for chiptune music imho. they're not bad, just not modern. having some plugins bundled with lmms would make sense for this program. synths like surge and vitalium. also the current interface for zynaddsubfx is basically unusable, you should use the newer interface zyn-fusion.

#### Justification

The justification is that using lmms now to make edm is not a good experience( especially when trying to use the sandboxed flatpak version). it would be nice if lmms could take care of  and provide some of the best open source synths bundled with the program since many distros don't have these synths in their repos anyways, and trying to use the flatpak version with vst is not good. synths like (vitalium, dexed, surge, zyn-fusion) all bundled with lmms would be amazing. no more having to try and hunt down and install a a bunch of synths on the side making lmms a one stop shop. I think this would make lmms a much more popular program when it comes to edm producers.

**Comment by Spekular** [comment]
- Flatpak is not maintained by us, only versions from lmms.io/download
- We have an open issue regarding Zyn Fusion already
- I don't believe bundling 3rd party VSTs is a good idea. It brings licensing issues, increased installer size, and responsibility for issues with the bundled plugins. Users can simply install these plugins themselves, avoiding all of these issues and leaving the choice of plugins to each individual.

**Comment by pyrotek45** [comment]
> To be fair, Organic is excellent when it comes to making supersaws.
> 
> Also to be fair, Xpressive is great at making most other sounds (though it's only available in alpha releases).
> 
> Regarding Zyn Fusion, the developers have actually talked about this, and part of the reason we haven't switched yet is that Zyn Fusion is deliberately behind a paywall. Even if you can theoretically circumvent that by simply building from source, the point was so that the developers were compensated for their work. If we bundled Zyn Fusion with LMMS, we would be taking that away from the Zyn team. While it could be argued that the publicity and exclusivity would be sufficient for Zyn to be compensated, we can't be sure on that, and we haven't reached out to the Zyn team (that I know of) to clear up the issue.
> 
> Zynaddsubfx is perfectly usable; it may not be beginner-friendly, but many people who use LMMS (including myself) have successfully used it to make complex sounds.
> 
> Now, on to your main point. Bundling other synths would be great except for two problems:
> 
>     1. These synths are VSTs, the builtin plugins are not. Even if we bundled these synths, they'd almost certainly be using VeSTige anyway, which wouldn't be a great user experience imo.
> 
>     2. How do you choose which synths to provide? I can find a number of synthesizers that aren't on your list that would still have equal cause to be added as builtin synthesizers. Particularly, Dexed is just emulating a DX7. Why shouldn't we bundle synths that emulate the Genesis, or the SoundBlaster, or any of the other many FM sound cards/chips that all have their unique sound?

the synths i listed are just a sample or and idea of some that could be bundled imho. The reason we should have more modern synths is for more modern sounds. Windows hasa wider access to a large array of vst synths. Things like unison and wave table manipulation are standard in many modern vst programs used by professionals. I'm sorry, but don't see armin van burren using genisis emulators to make modern trance lol. synths like serum changed the synth market and its what most producers are going to want to use currently. I mean how can you even make decent trance without supersaws, a ton of unison? also organics interface is awful. sorry, I can make a supersaw in like two seconds on any modern synth with unison from vital to surge and most other paid vst, using organic is a huge pain , and its tiny on my ultrawide monitor...

I mean if you guys just want lmms to be a chiptune daw then thats fine, but dont expect it to pull in anyone moving from windows to linux when they're used to what windows has to offer. Currently I use bitwig, its amazing but my only gripe is that its not open source. However, nothing in the  FOSS world has anything that can even rival it unfortunately .  The problem is that programs like lmms and ardour are so close but have just a few things holding them back from being just "meh" to "really good" in regards to edm production. ardour has a huge problem with how they handle midi, they dont even have a separate midi window yet( and probably will never), its a shame tbh. Lmms really just needs a facelift and some modern synths imho to bring it up a huge notch. right now lmms and ardour both rely on having its users use vst and plugins for synths but it would be so much better if it took a bitwig like approach and had really good built in synths and effects. the upsides would be obvious,from being able to have lmms a cohesive daw that can do edm in the box and easily sand boxed experience considering the landscape of vst plugs on linux is pretty awful atm, the next best thing is just to have a daw that doesn't need plugins  imho.
