### ISSUE TITLE
Keystation 88 has no recognized pedal when any M GEAR sustain pedal is plugged in.

### ISSUE THREAD

**Issue by Zelulose** [LMMS/lmms#6205]
As it sounds. The MIDI keyboard for keystation 88 exists alone without any recognized sustain pedal. There is also no outside software for recognizing the sustain pedal. I have searched the internet for weeks.

**Comment by PhysSong** [comment]
If the bug presents in every software you use, there's nothing we can fix on our side. You'd better contact the support team of the manufacturer if the issue still persists.
