### ISSUE TITLE
LMMS crashing 

### ISSUE THREAD

**Issue by caretierjavier** [LMMS/lmms#6207]
Hey yall !!
I'm new to this GitHub and issues and stuff and I have an issue with opening a project that was saved earlier today and it won't completely open at all. It loads in halfway through and then crashes on me, in the project I was using some samples that made my CPU usage go up and I don't know what to do about this and I want to open the project. what should I do?

**Comment by Spekular** [comment]
I'm closing this until we can confirm that it's a unique new bug. We prefer that support requests use other platforms such as our Discord server, but you can still respond here if that's not an option for you.

Regardless of if you continue here or on Discord, please mention your OS and LMMS version (and if you're on Linux, where you obtained the version). A copy of the project file in question is also very helpful for issues that only occur with a specific project.

**Comment by caretierjavier** [comment]
Thank you so much for reaching back to be ill be join to discord to talk furthermore about this bug!
