### ISSUE TITLE
Middle mouse = impossible on laptops

### ISSUE THREAD

**Issue by Sti2nd** [LMMS/lmms#621]
So it have to be alternatives for:
- Deleting patterns with one click (middle mouse)
- Resetting knobs and faders with one click (middle mouse)
- Muting (Ctrl + Middle mouse)

SHIFT + right mouse is an option for left loop point in 1.0.0 so logic tells holding SHIFT and right mouse down should replace middle mouse (mouse 3) in the rest of these cases too. Ctrl+Shift+right could be muting? 
Can you track down middle mouse in the code? If not, here are the attempt on writing down everything http://lmms.sourceforge.net/wiki/index.php/Key_Mappings

https://github.com/LMMS/lmms/issues/81

**Comment by Umcaruje** [comment]
Closed by https://github.com/grejppi/lmms/commit/cdcba9f68519a53f3218fa02f62ae79ef59abf1f
