### ISSUE TITLE
RemoteVstPlugin fails to build with wine-6.20

### ISSUE THREAD

**Issue by plater** [LMMS/lmms#6211]
I maintain lmms for openSUSE and lmms-1.2.2 fails to build against wine 6.20
[BuildFail.txt](https://github.com/LMMS/lmms/files/7490078/BuildFail.txt)
I'm unable to find the cause but reverting wine to 6.19 enables the build.
Please help I've searched through lmms git logs and can't find a fix.

**Comment by RiedleroD** [comment]
Can confirm, the same happens for master on arch linux + wine 6.20 (I disabled VST for now) - I don't think it's a duplicate, but it might be related to #5179

**Comment by plater** [comment]
That was a previous wine change, I filed the bug. I may have to disable vst for now as well

**Comment by allejok96** [comment]
It's a wine issue. Has been fixed in 6.21
https://bugs.winehq.org/show_bug.cgi?id=51919

**Comment by plater** [comment]
Thanks for the heads up, I don't have to disable vst anymore
