### ISSUE TITLE
Automation Track - Occasional fail to round off to integer value

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#6212]
### Bug Summary
Master-volume:
![image](https://user-images.githubusercontent.com/6662066/140616772-4f86453c-59b1-46bd-ad41-29b338b77845.png)
shows unexpected resolution on _some_ positions.
'a' is most common, and is one step.
'?' represent an 'odd' step
'b' normal+odd
![image](https://user-images.githubusercontent.com/6662066/140616717-0845dc72-2b5d-494e-9c51-df6e8c3d5804.png)
The choice of progression does not matter
Tension should not matter unless the progression is cubic 

#### Steps to reproduce
Just connect master-volume to an automation-track, and set resolution as in image. Insert points. Most will snap to whole steps, 'some' will not

#### Expected behavior
I actually expected the _resolution_ to be controlled by the _settings of Q_, and that is was possible to make changes in Q-values. A test for _That_ made this 'in-between-oddness' glitch appear.

#### Actual behavior
Odd steps sometimes as in image

#### Affected LMMS versions
(at least) 1.2.2 & 1.3 win64

**Comment by musikBear** [comment]
Well automation of Master-pitch has same oddness:
![image](https://user-images.githubusercontent.com/6662066/140618365-de942407-f5af-42e1-9b9a-5be82f0cb327.png)

**Comment by zonkmachine** [comment]
Issue confirmed. The automation track will also look the same after save/reload. I get all sorts of fractional values.

![automationtrack](https://github.com/LMMS/lmms/assets/6368949/2390f8d1-1196-48fb-9df1-1d62a8ddf075)

```
          <time value="3" pos="1988"/>
          <time value="1" pos="2316"/>
          <time value="4" pos="2454"/>
          <time value="4.33333" pos="2483"/>    <--- :D ?
          <time value="4.66667" pos="2484"/>    <--- :D !
          <time value="5" pos="2485"/>
          <time value="5" pos="2515"/>
          <time value="3" pos="2692"/>
          <object id="7292700"/>
        </automationpattern>
      </track>

```

**Comment by zonkmachine** [comment]
![automationglitch](https://github.com/LMMS/lmms/assets/6368949/65be286e-d234-40d0-85aa-d93d27ab006c)

Steps to reproduce.
* In a new project, drag the master volume control to the automation track
* Open the new automation tco and set zoom to 1600
* Add an automation point somewhere in the middle and 
* Grab the bottom of the Automation Editor window and adjust the geometry so the bottom of the editor window is below half of a step to the next value below. In the example above, once I adjusted the size so the bottom is below 98.5, the bound value will instead be the lowest point of the editor, not the rounded value.

Attempt at a fix in https://github.com/LMMS/lmms/pull/7269
