### ISSUE TITLE
Mouse operations on LcdSpinBox modify "reset" value

### ISSUE THREAD

**Issue by spechtstatt** [LMMS/lmms#6213]
### Bug Summary

Mouse operations on a LcdSpinBox for changing the value do also change the initial value so the "Reset" operation in the context menu is always showing the actual value. Selecting the "Reset" operation has therefore no effect because it just sets the actual value again.

#### Steps to reproduce

- focus a LcdSpinBox 
- click the left mouse button and move up or down to change the value (alternatively you could also use the mouse wheel)
- the "Reset" menu entry inside the context menu shows always the current value

#### Expected behavior

Changing the value of a LcdSpinBox using a mouse operation should behave like the manual entering of the value in the "Set Value" modal dialog which does not alter the "Reset" value.

#### Actual behavior

Changing the value of a LcdSpinBox using a mouse operation does set the "Reset" value for every change.

#### Screenshot

![image](https://user-images.githubusercontent.com/93736385/140623067-a4940bf7-1968-4929-b652-7c170d134087.png)

![image](https://user-images.githubusercontent.com/93736385/140623075-bf60bd35-f4b9-4e02-ada0-fcfde5f89b90.png)

#### Affected LMMS versions

Version 1.3.0-alpha - actual master source state 

#### Logs
<details>
  <summary>Click to expand</summary>
<pre>

</pre>
</details>

**Comment by spechtstatt** [comment]
Inside
https://github.com/LMMS/lmms/blob/master/src/gui/widgets/LcdSpinBox.cpp
there are setInitValue calls used in the mouseMoveEvent and the wheelEvent. I am pretty sure that this need to be a normal set value call.

**Comment by merrickclay** [comment]
I'd like to implement the fix for this!

**Comment by spechtstatt** [comment]
Sorry, that I didn't saw your comment earlier.
