### ISSUE TITLE
Delete multiple segments at once on Song Editor 

### ISSUE THREAD

**Issue by kimimaru4000** [LMMS/lmms#6219]
Specs:
```
LMMS version: 1.2.2
Distro: Linux Mint 20.2 Uma
```
### Enhancement Summary
The Song Editor currently does not have an intuitive way to delete multiple segments at once. What I want out of this issue is a way to select multiple segments in Edit mode and be able to delete them, via the "delete" key or otherwise.

The Piano Roll supports this same feature and is a pleasure to work with. I would essentially like to see the same flexible controls of the Piano Roll applied to the Song Editor.

Issue https://github.com/LMMS/lmms/issues/46 opened back in 2014 addresses this, and it says it was merged [in this comment](https://github.com/LMMS/lmms/issues/46#issuecomment-44714485), but fastforward to version 1.2.2 and I unfortunately still don't know how to do this.

#### Justification
Deleting multiple segments in the Song Editor is very inconvenient and time-consuming, especially across multiple instruments on longer tracks. The best workaround I found for this is to copy what I want, move them to another instrument, clear the entire instrument track, then move them back.

This feature would make LMMS more intuitive, pleasant to work with, and less time-consuming for artists.

**Comment by Monospace-V** [comment]
1.3 (alpha) already has this feature
https://user-images.githubusercontent.com/76674645/141682461-bd604ddd-a1d2-49d4-9099-43b917bc5379.mp4

Downloading the nightly version from lmms.io should give you the 1.3 version. It is capable to select multiple segments (TCOs) and hit the "Delete" key on the keyboard to delete them.
Requesting you to check the nightly version whenever you find a feature that should exist but doesn't.

**Comment by kimimaru4000** [comment]
Thank you! I just tested out the nightly and it works as expected. Going forwards I'll check the nightly versions for new features. I appreciate the help!
