### ISSUE TITLE
Held keys don't produce continuous notes after upgrading to Ubuntu 14.04

### ISSUE THREAD

**Issue by grejppi** [LMMS/lmms#623]
Hold down a key to play an instrument. What is supposed to be one long note becomes a randomly broken set of notes:
![heldkeys](https://cloud.githubusercontent.com/assets/772336/2748226/287260ba-c7b1-11e3-8347-721d2d8d6485.png)

I suspect this is about held keys being treated as repeated. This was not an issue with Ubuntu 13.10 or earlier. (The version of libqt4-core: `4:4.8.5+git192-g085f851+dfsg-2ubuntu4`)

**Comment by pbhd** [comment]
Just to leave my 5 cents here, as I experienced same problem:
isAutoRepeat is broken, at least with 5.5.1+dfsg-16ubuntu7.2 (latest released version for ubuntu 16.04). At the end of [qkeyevent-isautorepeat-not-working](http://stackoverflow.com/questions/38102221/qkeyevent-isautorepeat-not-working) is described a workaround using grabKeyboard(), but it is at least for me not always working smoothly.
