### ISSUE TITLE
lmms crashes during "opening audio and midi devices" wdmaud.pdb not loaded

### ISSUE THREAD

**Issue by samiscoolest** [LMMS/lmms#6230]
### Bug Summary
when opening lmms it stops responding during "opening audio and midi devices" debugging in visual studio says that it failed to load wdmaud.pdb
#### Steps to reproduce
open lmms
#### Expected behavior
lmms would load
#### Actual behavior
lmms doesnt load
#### Screenshot
![image](https://user-images.githubusercontent.com/57376107/144712723-afb68658-a1fe-48fd-a99f-53c1142d086a.png)
#### Affected LMMS versions
1.2.2

**Comment by allejok96** [comment]
Have you tested on 1.3.0?

**Comment by RiedleroD** [comment]
Also, could you add your OS info to the bug report? The popup looks like win xp, but it might be anything from 95 to 7.
Also note that LMMS doesn't support any windows version older than 7 (see [minimum system requirements](https://docs.lmms.io/user-manual/getting-started/installation))

**Comment by samiscoolest** [comment]
@allejok96 updating to 1.3 did not fix it
@RiedleroD im on windows 7

**Comment by samiscoolest** [comment]
never mind apparently the problem fixed itself
