### ISSUE TITLE
Hear the entire track while on Piano-Roll

### ISSUE THREAD

**Issue by CaulHere** [LMMS/lmms#6255]
### Enhancement Summary
In the Piano-Roll, Its not possible to hear the entire track, Other DOWs can so I would like to see that feature in LMMS as a switch to turn on/off the feature.
### Mockup

**Comment by qnebra** [comment]
![Zrzut ekranu 2022-01-02 153854](https://user-images.githubusercontent.com/11295229/147879266-ff8f78d0-311f-4e6a-9deb-f7bbd2f94ad2.jpg)

It was already here.

**Comment by CaulHere** [comment]
Never knew that Thanks
