### ISSUE TITLE
Overlapping notes are quantized when playing a roll and then stopping outside of the piano editor

### ISSUE THREAD

**Issue by ExperiBass** [LMMS/lmms#6260]
### Bug Summary
When overlapping notes are in the piano roll,  and the grid is larger than a note, attempting to pause the playing notes results in the notes being quantized.
#### Steps to reproduce
1: place notes on the grid.
2: reduce the grid until at least one of the notes doesn't line up.
3: play the loop.
4: close the piano roll editor.
5: hit space to pause.

#### Expected behavior
The roll stops.
#### Actual behavior/screenshot
[Why cant github play mp4s? smh gotta upload this stupid thing to youtube](https://youtu.be/0l0AUFb5CtI)
#### Affected LMMS versions
LMMS 1.3.0-alpha.1.155+g13e17496d, master branch

**Comment by ExperiBass** [comment]
Bumping, still occurs on latest master

**Comment by Monospace-V** [comment]
Reproduced. It seems to me this is enabled by the focus not being on the song editor or piano roll after PR is closed. If we close the PR but click on the SE to focus on it, then pausing works normally.
Hitting space only triggers pause if the focus is on piano roll, song editor, B/B, automation track, etc.

**Comment by zonkmachine** [comment]
Closed in https://github.com/LMMS/lmms/pull/7035
