### ISSUE TITLE
Build breakage using Qt 5.15.2

### ISSUE THREAD

**Issue by rdrpenguin04** [LMMS/lmms#6265]
### Bug Summary

When using a very recent version of Qt, the build errors out.

#### Steps to reproduce

1. Install development headers for Qt 5.15.2
2. Start building LMMS (I used the version from commit bf323d20240ecc342aea0436aa68316a2e960b68)

#### Expected behavior

The build succeeds

#### Actual behavior

The build fails

#### Screenshot

N/A

#### Affected LMMS versions

Master branch, and likely all earlier versions that supported Qt 5.

#### Logs
<details>
  <summary>Click to expand</summary>
<pre>
[snip]
[13/1282] Building CXX object src/3rdparty/qt5-x11embed/CMakeFiles/qx11embedcontainer.dir/src/X11EmbedContainer.cpp.o
FAILED: src/3rdparty/qt5-x11embed/CMakeFiles/qx11embedcontainer.dir/src/X11EmbedContainer.cpp.o 
/usr/bin/c++ -DNOMINMAX -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_TRANSLATIONS_DIR=\"/usr/share/qt/translations\" -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -I/home/rdrpenguin/lmms/build/src/3rdparty/qt5-x11embed/qx11embedcontainer_autogen/include -I/usr/include/qt/QtXml -I/usr/include/qt/QtCore/5.15.2 -I/usr/include/qt/QtCore/5.15.2/QtCore -I/usr/include/qt/QtWidgets/5.15.2 -I/usr/include/qt/QtWidgets/5.15.2/QtWidgets -I/usr/include/qt/QtGui/5.15.2 -I/usr/include/qt/QtGui/5.15.2/QtGui -isystem /usr/include/qt -isystem /usr/include/qt/QtCore -isystem /usr/lib/qt/mkspecs/linux-g++ -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtX11Extras -Wall -Werror=unused-function -Wno-sign-compare -Wno-strict-overflow -Wno-array-bounds -Wno-attributes  -fPIC -DPIC -Wall -std=c++11 -O3 -DNDEBUG -fPIC -MD -MT src/3rdparty/qt5-x11embed/CMakeFiles/qx11embedcontainer.dir/src/X11EmbedContainer.cpp.o -MF src/3rdparty/qt5-x11embed/CMakeFiles/qx11embedcontainer.dir/src/X11EmbedContainer.cpp.o.d -o src/3rdparty/qt5-x11embed/CMakeFiles/qx11embedcontainer.dir/src/X11EmbedContainer.cpp.o -c /home/rdrpenguin/lmms/src/3rdparty/qt5-x11embed/src/X11EmbedContainer.cpp
In file included from /usr/include/qt/QtGui/5.15.2/QtGui/private/qguiapplication_p.h:61,
                 from /home/rdrpenguin/lmms/src/3rdparty/qt5-x11embed/src/X11EmbedContainer.cpp:42:
/usr/include/qt/QtCore/5.15.2/QtCore/private/qthread_p.h:177:10: error: ‘underlying_type_t’ in namespace ‘std’ does not name a template type; did you mean ‘underlying_type’?
  177 |     std::underlying_type_t<QThread::Priority> priority;
      |          ^~~~~~~~~~~~~~~~~
      |          underlying_type
[snip]
</pre>
</details>

**Comment by rdrpenguin04** [comment]
The problem is due to LMMS trying to enforce `-std=c++11`, but `underlying_type_t` is from C++14.

**Comment by PhysSong** [comment]
> The problem is due to LMMS trying to enforce `-std=c++11`

LMMS uses C++17. The flag is from [qt5-x11embed](https://github.com/lukas-w/qt5-x11embed/blob/022b39a1d496d72eb3e5b5188e5559f66afca957/CMakeLists.txt) submodule.

`std::underlying_type_t` was added in https://codereview.qt-project.org/c/qt/qtbase/+/103886, but I can't find it in vanilla Qt 5.15.2.

**Comment by rdrpenguin04** [comment]
Hmm...

I'm running on EndeavourOS, so it's possible Arch/EndeavourOS includes this patch.

**Comment by PhysSong** [comment]
I found that this one is specific to distributions. Relevant links:
https://github.com/archlinux/svntogit-packages/commit/4c02bb0c74416c06b8481330e9b9975b9de2822f
https://invent.kde.org/qt/qt/qtbase/-/merge_requests/94

**Comment by rdrpenguin04** [comment]
It may be worth forking qt5-x11embed to patch this and any other problems we find in the future.

**Comment by rdrpenguin04** [comment]
And by that, I mean it is worth it, since I doubt the maintainer of `qt5-x11embed` is coming back to fix it. And I can't make the fork on this organization (which is where it should go), so someone with organization access needs to do that.

If you all would prefer that I do this on my personal account, I could, but I don't know that I have a use for this package otherwise. Also, I feel like I remember talk of axing this embed method entirely on the Qt6 switch, unless I'm mistaken.

**Comment by allejok96** [comment]
Hm, just built master on Arch with `qt5-base 5.15.2+kde+r291-1` no errors

**Comment by rdrpenguin04** [comment]
I'm clean-building again; I have the same package version.

**Comment by rdrpenguin04** [comment]
It works now, I'm not sure what changed.

Thanks for the response!

**Comment by PhysSong** [comment]
> Hm, just built master on Arch with `qt5-base 5.15.2+kde+r291-1` no errors

It looks like the C++11 compatibility issue was fixed in r289.
