### ISSUE TITLE
SampleClip: valid file disappears when replaced with invalid one

### ISSUE THREAD

**Issue by M374LX** [LMMS/lmms#6287]
### Bug Summary
When a sample clip contains a valid audio file and the user replaces it with an invalid one, the previous (valid) sample disappears. #6286 is related and should be merged before a fix is proposed.

#### Steps to reproduce
1. Create an empty file with the ".wav" extension.
2. Start LMMS.
3. Add a sample track.
4. Add a clip to the sample track and load a valid audio file into it.
5. Replace the valid file loaded on step 4 with the empty file created on step 1.

#### Expected behavior
The previous (valid) audio file should be kept intact in the sample clip (and an error message should be shown, which #6286 addresses).

#### Actual behavior
The sample clip becomes empty.

#### Affected LMMS versions
1.3.0-alpha.1.163+g0d1b455be (Linux/x86_64, Qt 5.15.2, GCC 10.2.1 20201203).

**Comment by Rossmaxx** [comment]
Any chance #6610 might have fixed this?

**Comment by michaelgregorius** [comment]
I can still reproduce this. An error message is shown but the valid clip is removed instead of being kept.

**Comment by michaelgregorius** [comment]
Pull request #7224 fixes this.
