### ISSUE TITLE
Can't find an option to select .so files as plugin

### ISSUE THREAD

**Issue by Rajatisporwal** [LMMS/lmms#6294]
Hey there folks!
I'm a newbie to linux as well as LMMS, Using Linux mint 20.04 as of writing this.

It's related to LADSPA plugins, Can't load them in the "VeSTige in intrument plugins" section as the browser window only provides me with 2 file options ".dll" and ".exe" whereas the plugin I've installed goes with ".so"

Also tried using wine to open the ".exe" version of the plugin but it fails to do so. I would really appreciate if anyone can mind guiding me further! 

#### LMMS version 1.2.2 (Linux/x86_64, Qt 5.9.7, GCC 5.4.0 20160609)
![lmms issue](https://user-images.githubusercontent.com/65300373/151689617-2d1f284c-c30b-4c67-8c06-3c760e3b5d6d.png)

**Comment by rdrpenguin04** [comment]
Answered on Discord; not a bug. This can be closed.
