### ISSUE TITLE
dsk virtuoso fails in 1.2.2

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#6296]
### Bug Summary
Belongs to: **Specific VST-fails**

#### Steps to reproduce
Download and embed in Vestige

#### Expected behavior
sound

#### Actual behavior
No sound, and The UI does not open when open/close-button is used

#### Screenshot
%

#### Affected LMMS versions
At least 1.2.1 1.2.2 

Most likely this is not a lmms bug.  DSK has some odd ones..

**Comment by PhysSong** [comment]
1. Add DSK Virtuoso and choose some sound for each layer
2. I can hear some sound
3. Save and reload
4. No sound output until re-selecting sound sources

Loading/saving by `.fxp` file is not affected by this bug. The same thing happens in Reaper as well.

**Comment by Monospace-V** [comment]
Cannot replicate 1.2.2/1.2.0, UI _does_ open.
![image](https://user-images.githubusercontent.com/76674645/152081351-69881332-faf3-47eb-8167-1c85bae038a5.png)
Try changing plugin embed UI if that changes anything.

**Comment by musikBear** [comment]
I tried all 3 embed options. I could not toggle the UI.
 On Discord oop mentioned a  Saving and reopening 'solution'
 https://discord.com/channels/203559236729438208/242409373505159168/938263104389804062

**Comment by Monospace-V** [comment]
Then it's an un-replicable problem on your end if it can't open by default. Try reinstalling LMMS.

**Comment by PhysSong** [comment]
I can't reproduce the UI issue either.

**Comment by Rossmaxx** [comment]
Since this is a DSK bug, should we leave this open? 

> The same thing happens in Reaper as well.

LMMS is not the only one so def upstream.

**Comment by Rossmaxx** [comment]
Not our bug.
