### ISSUE TITLE
MIDI import doesn't import program change automation

### ISSUE THREAD

**Issue by TheRamsWay** [LMMS/lmms#6305]
### Bug Summary
When importing a MIDI file, LMMS doesn't create an automation track when there are multiple program change events and uses the last program number found for the whole track instead. The problem doesn't come from the MIDI files I used, as they do contain multiple program change events and VLC and Cubase react correctly to them.

#### Steps to reproduce
1. Import a MIDI file with program change events (I can provide one if needed)
2. Look at the automation tracks: you may see a bank change track but no program change track

#### Expected behavior
LMMS should create an automation track when multiple program change events are found in a MIDI file similarly to other events

#### Actual behavior
The last seen program number is used on the entire track

#### Affected LMMS versions
1.2.2

**Comment by Veratil** [comment]
If you can, test the nightly version (1.3.0-alpha.1) [found here](https://lmms.io/download)? *Be sure to install it to a separate location and do not open a project*, and then try to import the midi in question.

Between 1.2.2 and 1.3.0-alpha.1 I updated the midi import to be less broken. If it still doesn't work, if you could share the midi file here then I could inspect and fix the problem.

**Comment by TheRamsWay** [comment]
It doesn't work with the nightly version either. Here are [two files](https://github.com/LMMS/lmms/files/8053493/progchangemidi.zip) that are the same music but exported with two different tools. "noprogram.mid" doesn't create any automation track for the program change event, "banknoprogram.mid" creates a bank change track instead (but always sets it to 0).
