### ISSUE TITLE
Build fails on AudioSoundIo.cpp

### ISSUE THREAD

**Issue by hankster112** [LMMS/lmms#6325]
### Bug Summary
Building on master branch fails with:
<pre>
make[2]: *** [src/CMakeFiles/lmmsobjs.dir/build.make:1279: src/CMakeFiles/lmmsobjs.dir/core/audio/AudioSoundIo.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:379: src/CMakeFiles/lmmsobjs.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
</pre>
#### Steps to reproduce
Unknown, tried to build by following directions explicitly. Disabled LV2 in Makefile as it could not find the libs for it.
#### Expected behavior
Should build without issues.
#### Actual behavior
Will build up to around 88% then error out. Full error below.
### Attempted fixes
None, not sure where to go from here as I am not a dev.
#### Affected LMMS versions
Trying to build from master.

#### Logs
<details>
  <summary>Click to expand</summary>
<pre>
In file included from /home/USERNAME/Builds/lmms/src/core/audio/AudioSoundIo.cpp:25:
/home/USERNAME/Builds/lmms/include/AudioSoundIo.h:82:3: error: ‘ComboBoxModel’ does not name a type; did you mean ‘ComboBox’?
   ComboBoxModel m_backendModel;
   ^~~~~~~~~~~~~
   ComboBox
/home/USERNAME/Builds/lmms/include/AudioSoundIo.h:83:3: error: ‘ComboBoxModel’ does not name a type; did you mean ‘ComboBox’?
   ComboBoxModel m_deviceModel;
   ^~~~~~~~~~~~~
   ComboBox
/home/USERNAME/Builds/lmms/src/core/audio/AudioSoundIo.cpp: In member function ‘void AudioSoundIo::setupWidget::reconnectSoundIo()’:
/home/USERNAME/Builds/lmms/src/core/audio/AudioSoundIo.cpp:374:63: error: ‘m_backendModel’ was not declared in this scope
   ConfigManager::inst()->value( "audiosoundio", "backend" ) : m_backendModel.currentText();
                                                               ^~~~~~~~~~~~~~
/home/USERNAME/Builds/lmms/src/core/audio/AudioSoundIo.cpp:374:63: note: suggested alternative: ‘m_backend’
   ConfigManager::inst()->value( "audiosoundio", "backend" ) : m_backendModel.currentText();
                                                               ^~~~~~~~~~~~~~
                                                               m_backend
/home/USERNAME/Builds/lmms/src/core/audio/AudioSoundIo.cpp:426:2: error: ‘m_deviceModel’ was not declared in this scope
  m_deviceModel.setValue(deviceIndex);
  ^~~~~~~~~~~~~
/home/USERNAME/Builds/lmms/src/core/audio/AudioSoundIo.cpp:426:2: note: suggested alternative: ‘m_device’
  m_deviceModel.setValue(deviceIndex);
  ^~~~~~~~~~~~~
  m_device
/home/USERNAME/Builds/lmms/src/core/audio/AudioSoundIo.cpp: In member function ‘void AudioSoundIo::setupWidget::updateDevices()’:
/home/USERNAME/Builds/lmms/src/core/audio/AudioSoundIo.cpp:434:2: error: ‘m_deviceModel’ was not declared in this scope
  m_deviceModel.clear();
  ^~~~~~~~~~~~~
/home/USERNAME/Builds/lmms/src/core/audio/AudioSoundIo.cpp:434:2: note: suggested alternative: ‘m_device’
  m_deviceModel.clear();
  ^~~~~~~~~~~~~
  m_device
/home/USERNAME/Builds/lmms/src/core/audio/AudioSoundIo.cpp: In constructor ‘AudioSoundIo::setupWidget::setupWidget(QWidget*)’:
/home/USERNAME/Builds/lmms/src/core/audio/AudioSoundIo.cpp:485:3: error: ‘m_backendModel’ was not declared in this scope
   m_backendModel.addItem(soundio_backend_name(backend));
   ^~~~~~~~~~~~~~
/home/USERNAME/Builds/lmms/src/core/audio/AudioSoundIo.cpp:485:3: note: suggested alternative: ‘m_backend’
   m_backendModel.addItem(soundio_backend_name(backend));
   ^~~~~~~~~~~~~~
   m_backend
/home/USERNAME/Builds/lmms/src/core/audio/AudioSoundIo.cpp:492:22: error: ‘m_backendModel’ was not declared in this scope
  bool ok = connect( &m_backendModel, SIGNAL( dataChanged() ), &m_setupUtil, SLOT( reconnectSoundIo() ) );
                      ^~~~~~~~~~~~~~
/home/USERNAME/Builds/lmms/src/core/audio/AudioSoundIo.cpp:492:22: note: suggested alternative: ‘m_backend’
  bool ok = connect( &m_backendModel, SIGNAL( dataChanged() ), &m_setupUtil, SLOT( reconnectSoundIo() ) );
                      ^~~~~~~~~~~~~~
                      m_backend
/home/USERNAME/Builds/lmms/src/core/audio/AudioSoundIo.cpp:496:23: error: ‘m_deviceModel’ was not declared in this scope
  m_device->setModel( &m_deviceModel );
                       ^~~~~~~~~~~~~
/home/USERNAME/Builds/lmms/src/core/audio/AudioSoundIo.cpp:496:23: note: suggested alternative: ‘m_device’
  m_device->setModel( &m_deviceModel );
                       ^~~~~~~~~~~~~
                       m_device
/home/USERNAME/Builds/lmms/src/core/audio/AudioSoundIo.cpp:492:7: warning: unused variable ‘ok’ [-Wunused-variable]
  bool ok = connect( &m_backendModel, SIGNAL( dataChanged() ), &m_setupUtil, SLOT( reconnectSoundIo() ) );
       ^~
/home/USERNAME/Builds/lmms/src/core/audio/AudioSoundIo.cpp: In destructor ‘virtual AudioSoundIo::setupWidget::~setupWidget()’:
/home/USERNAME/Builds/lmms/src/core/audio/AudioSoundIo.cpp:501:25: error: ‘m_backendModel’ was not declared in this scope
  bool ok = disconnect( &m_backendModel, SIGNAL( dataChanged() ), &m_setupUtil, SLOT( reconnectSoundIo() ) );
                         ^~~~~~~~~~~~~~
/home/USERNAME/Builds/lmms/src/core/audio/AudioSoundIo.cpp:501:25: note: suggested alternative: ‘m_backend’
  bool ok = disconnect( &m_backendModel, SIGNAL( dataChanged() ), &m_setupUtil, SLOT( reconnectSoundIo() ) );
                         ^~~~~~~~~~~~~~
                         m_backend
/home/USERNAME/Builds/lmms/src/core/audio/AudioSoundIo.cpp:501:7: warning: unused variable ‘ok’ [-Wunused-variable]
  bool ok = disconnect( &m_backendModel, SIGNAL( dataChanged() ), &m_setupUtil, SLOT( reconnectSoundIo() ) );
       ^~
/home/USERNAME/Builds/lmms/src/core/audio/AudioSoundIo.cpp: In member function ‘virtual void AudioSoundIo::setupWidget::saveSettings()’:
/home/USERNAME/Builds/lmms/src/core/audio/AudioSoundIo.cpp:512:20: error: ‘m_deviceModel’ was not declared in this scope
  int deviceIndex = m_deviceModel.value();
                    ^~~~~~~~~~~~~
/home/USERNAME/Builds/lmms/src/core/audio/AudioSoundIo.cpp:512:20: note: suggested alternative: ‘m_device’
  int deviceIndex = m_deviceModel.value();
                    ^~~~~~~~~~~~~
                    m_device
/home/USERNAME/Builds/lmms/src/core/audio/AudioSoundIo.cpp:517:62: error: ‘m_backendModel’ was not declared in this scope
  ConfigManager::inst()->setValue( "audiosoundio", "backend", m_backendModel.currentText());
                                                              ^~~~~~~~~~~~~~
/home/USERNAME/Builds/lmms/src/core/audio/AudioSoundIo.cpp:517:62: note: suggested alternative: ‘m_backend’
  ConfigManager::inst()->setValue( "audiosoundio", "backend", m_backendModel.currentText());
                                                              ^~~~~~~~~~~~~~
                                                              m_backend
[ 83%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/midi/MidiController.cpp.o
[ 83%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/midi/MidiEventToByteSeq.cpp.o
make[2]: *** [src/CMakeFiles/lmmsobjs.dir/build.make:1279: src/CMakeFiles/lmmsobjs.dir/core/audio/AudioSoundIo.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:379: src/CMakeFiles/lmmsobjs.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
</pre>
</details>

**Comment by PhysSong** [comment]
Should be fixed in 80a6672da46a58dd6865a3dda8a7a4f05776393e.

**Comment by hankster112** [comment]
Now it gets to 100% but still errors out:
<pre>
[100%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/widgets/StepRecorderWidget.cpp.o
[100%] Building CXX object src/CMakeFiles/lmmsobjs.dir/tracks/AutomationTrack.cpp.o
[100%] Building CXX object src/CMakeFiles/lmmsobjs.dir/tracks/InstrumentTrack.cpp.o
[100%] Building CXX object src/CMakeFiles/lmmsobjs.dir/tracks/MidiClip.cpp.o
[100%] Building CXX object src/CMakeFiles/lmmsobjs.dir/tracks/PatternTrack.cpp.o
[100%] Building CXX object src/CMakeFiles/lmmsobjs.dir/tracks/SampleTrack.cpp.o
[100%] Building C object src/CMakeFiles/lmmsobjs.dir/3rdparty/weakjack/weakjack/weak_libjack.c.o
[100%] Building CXX object src/CMakeFiles/lmmsobjs.dir/3rdparty/ringbuffer/src/lib/ringbuffer.cpp.o
[100%] Building CXX object src/CMakeFiles/lmmsobjs.dir/qrc_lmms.cpp.o
[100%] Building CXX object src/CMakeFiles/lmmsobjs.dir/lmmsobjs_autogen/mocs_compilation.cpp.o
[100%] Built target lmmsobjs
make: *** [Makefile:152: all] Error 2
</pre>

**Comment by hankster112** [comment]
Also found these errors related to ZynAddSubFx:
<pre>
/usr/bin/ld: /usr/local/lib/libfltk.a(Fl_x.o): undefined reference to symbol 'XConvertSelection'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/libX11.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [plugins/zynaddsubfx/CMakeFiles/RemoteZynAddSubFx.dir/build.make:86: plugins/RemoteZynAddSubFx] Error 1
make[1]: *** [CMakeFiles/Makefile2:8986: plugins/zynaddsubfx/CMakeFiles/RemoteZynAddSubFx.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
</pre>

**Comment by PhysSong** [comment]
Strange. What does `ls -al /usr/local/lib/libfltk*` give on your system?

**Comment by hankster112** [comment]
<pre>
-rwxr-xr-x 1 root root 2806548 Mar  7 20:47 /usr/local/lib/libfltk.a
-rwxr-xr-x 1 root root   52122 Mar  7 20:47 /usr/local/lib/libfltk_forms.a
-rwxr-xr-x 1 root root  345696 Mar  7 20:47 /usr/local/lib/libfltk_gl.a
-rwxr-xr-x 1 root root   97992 Mar  7 20:47 /usr/local/lib/libfltk_images.a
</pre>

**Comment by hankster112** [comment]
Figured it out, I was messing around with binaries/builds straight from their site instead of just using apt-get. Builds and works perfectly now.
