### ISSUE TITLE
Erratic MultiTap echo output behaviour

### ISSUE THREAD

**Issue by Monospace-V** [LMMS/lmms#6326]
### Bug Summary
On higher "Length" values, the LMMS Multitap echo effect outputs progressively more erratic behaviour, sometimes not echoing at all, sometimes even the original sound isn't heard. This is more pronounced in exports, where only the original sound is heard. There are also some unusual outputs like this:
https://user-images.githubusercontent.com/76674645/157396035-a4e5829e-d706-4f6d-a1f8-ee17567b014e.mp4
Project file:
[MultiTap Echo Bug.zip](https://github.com/LMMS/lmms/files/8212683/MultiTap.Echo.Bug.zip)

#### Steps to reproduce
1. Add an instrument track and add a note.
2. Add a MultiTap Echo effect to the track, and set the "Length" to something high.
3. Playback.
4. Export.
5. Save.
6. Reopen.
7. Playback.

#### Expected behavior
Consistent behaviour and proper echo

#### Actual behavior
Nonsense

#### Screenshot
![image](https://user-images.githubusercontent.com/76674645/157398112-9bdc6efd-547b-4501-82a4-44cc1395c935.png)

#### Affected LMMS versions

1.2.0, 1.2.2, 1.3 alpha- essentially, every version containing the multitap echo plugin.

**Comment by Monospace-V** [comment]
No.

**Comment by Monospace-V** [comment]
Am closing for now. Perhaps what I've suggested is better as a potential enhancement, if felt useful enough. Not enough people deviate from the default settings, anyways, and there's no specific reason to turn the setting off for a majority of users.

**Comment by Spekular** [comment]
I think we could leave it open until/unless we have an issue to consolidate similar bugs. There are lots of potential solutions, especially for native effects (e.g. let effects define how long their tails are).

**Comment by DomClark** [comment]
See also #4284, #424.

**Comment by Spekular** [comment]
Closing in favor of #4284
