### ISSUE TITLE
Hidden relationship between 'record-buttons' and Q-value.

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#6332]
### Enhancement Summary
I here suggest that we change Q-value to 1/192 automatically, if either of the two recording-buttons are clicked

#### Justification
Ooops i did it again.
'It' being played some really nice chords, and even had record invoked, so all should be good, but.. alas
Q-value was 1/8, and not a single chord was added as i played.
That made think. 
When either of the record-buttons is selected, wouldent best Q not in most circumstances be 1/192, eg LMMS' best free placing of notes?

Atm user need to remember to set the Q value to 1/192, and then start recording.
I forget that almost every time.
I think the few times where non-human placing of notes actually is wanted, should be the one where a special selection of Q-value also should be done. At that situation the mindset is focused on a special Q-value, and it would then be intuitive to also sét that value.
A inconvenience do exists if the user first set the Q he want, and then set record, because with my idea, LMMS would then revert to 1/192.
The user need to first set the record-option and then his preferred Q, someone may dislike that the sequence play a role.
Share Any thoughts on how that could be fixed.

#### Mockup
Not really possible to mock-up this functionality. LMMS already has the controls that are needed for this.
But here 
![image](https://user-images.githubusercontent.com/6662066/158695347-0fd6dfb0-70bd-43a8-af19-63b18bae6294.png)
are the buttons marked, that i want to 'link'

**Comment by Spekular** [comment]
Rather than changing anything in the UI, I think recording should bypass the quantization setting entirely. If users want quantized recordings they can then press the quantize button.

**Comment by musikBear** [comment]
> Rather than changing anything in the UI, I think recording should bypass the quantization setting entirely. If users want quantized recordings they can then press the quantize button.

Yes, that is also a way, as long as recording always pr default insert notes as they are being played, i would be fine with that as well 👍
