### ISSUE TITLE
"No VST Plugin Loaded" Mid session fail

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#6333]
### Bug Summary
Never seen before. In the middle of a work-session the already loaded VST disappeared and was was replaced with 
![image](https://user-images.githubusercontent.com/6662066/158708790-df2b3cc5-1fc0-46ed-aaac-bf59dc3467b8.png)
That is a first for me.

#### Steps to reproduce
Non what so ever.
Most likely this is a one off, but if it can happen once, it will happen again. It is for that case i want to have this ticket.

#### Expected behavior
A loaded playing VST should stay loaded and playing

#### Actual behavior
The VST 'Disappeared' as in un-loaded itself without explanation.
Project-file not influenced

#### Affected LMMS versions
1.2.2 stable

#### Logs
Have non.

**Comment by DomClark** [comment]
That's what happens when a VST plugin crashes. Without the name of the plugin and steps to reproduce, we can't investigate, and it isn't even possible to tell whether this is a bug in LMMS or the VST.

**Comment by musikBear** [comment]
> That's what happens when a VST plugin crashes. Without the name of the plugin and steps to reproduce, **we can't investigate**, and it isn't even possible to tell whether this is a bug in LMMS or the VST.

Exactly. That is also why i wrote 
> it will happen again. It is for that case i want to have this ticket.

Next time there is a ticket that shows that it was not the first time, so it is more serious than a freak oneoff.
However since there is nothing to do, i will close this for now, then we can reopen if necessary.
