### ISSUE TITLE
Freeze or crash on export.  

### ISSUE THREAD

**Issue by worikgh** [LMMS/lmms#6336]
# Please search the issue tracker for existing bug reports before submitting your own. Delete this line to confirm no similar report has been posted yet.

### Bug Summary
Using: File -> Export... or File -> Export Tracks...  when the file has been exported lmms either freezes or crashes

If sample rate set to 44.1k it crashes with `Segmentation fault` on terminal 

If sample rate set to 48k it freezes with `QMetaMethod::invoke: Unable to handle unregistered datatype 'MidiTime'` on terminal

#### Steps to reproduce

File->Export....

#### Expected behavior

lmms keeps runing

#### Affected LMMS versions
```
 lmms --version
LMMS 1.2.2
(Linux unknown processor, Qt 5.14.2, GCC 10.2.0)
```

```
$ uname -a
Linux patchbox 5.10.92-v7l+ #1514 SMP Mon Jan 17 17:38:03 GMT 2022 armv7l GNU/Linux
```

A Raspberry PI 4

#### Logs
<details>
  <summary>Click to expand</summary>
<pre>

</pre>
</details>

**Comment by Monospace-V** [comment]
Can you/have you tried 1.3 alpha?

**Comment by worikgh** [comment]
> Can you/have you tried 1.3 alpha?

Where do I get that?  Is it usable? (Being alpha)

**Comment by Monospace-V** [comment]
https://github.com/LMMS/lmms/releases/tag/v1.3.0-alpha.1

**Comment by PhysSong** [comment]
Some basic question for diagnosis:
- How did you get LMMS? Is it from distro packages?
- Which audio interface is selected in `Edit->Settings->Audio(the speaker icon)`?
- Could you follow the [debugging steps](https://github.com/LMMS/lmms/wiki/Debugging-LMMS#debugging-with-gdb-gnu-debugger)?

**Comment by worikgh** [comment]
> How did you get LMMS? Is it from distro packages?

From packages.  I have compiled it from source (1.3 alpha) but have not used it yet

> Which audio interface is selected in Edit->Settings->Audio(the speaker icon)?

It (the version I was using) is uninstalled now.  But I am using a Pisound from Blokaslabs

If I get the same problem with 1.3 Alpha and/or that version has other problems (being alpha) I will go back and then have the chance to use GDB

**Comment by worikgh** [comment]
Version 1.3-Alpha is not exhibiting this issue.

Would it be useful for me to try to reproduce the issue?

It is not much work, happy to.

**Comment by zonkmachine** [comment]
> Version 1.3-Alpha is not exhibiting this issue.

Great, closing as fixed!


> Would it be useful for me to try to reproduce the issue?
> 
> It is not much work, happy to.

If you feel like digging into this again, please do! We need data from users on Raspberry Pi/ARM.
Just bump this issue again if you find something related.
