### ISSUE TITLE
Drag Beat+Bassline Pattern the other way in the Song-Editor

### ISSUE THREAD

**Issue by actuallyexeon** [LMMS/lmms#6346]
### Enhancement Summary
When using a Beat+Bassline Pattern in the Song-Editor you can drag it from the right to left to shorten the pattern in that direction, but what would also be nice is to be able to go from left to right so you can have the other half or quarter of the pattern instead of the first half only.

#### Justification
This would be nice when making songs like when you need to implement a beat repeat that repeats a certain part but then goes back to normal and instead of having to duplicate all of the patterns in your Song-Editor you can just simply drag them from left to right to keep a certain part.

**Comment by ToastedSadWitch** [comment]
hi, i would like to work on this :)
this is my first work on lmms so if you think it's too advanced, you can say no.
right now i figure out the gui part of the problem (there is already the starttimeoffset parameter we can make use of).
another major part would be the playback.
and a minor one the storing + compatibility with older version files.

**Comment by zonkmachine** [comment]
> hi, i would like to work on this :)

Sure, have a go!
If you haven't joined our Discord channel yet, now is the time.
#dev-support is the first place to ask If you get stuck!

**Comment by ToastedSadWitch** [comment]
thanks! i'm already on the discord as Posoppiser 👍
