### ISSUE TITLE
Better functionality of LFO-ctrl with random spectrum

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#6354]
### Enhancement Summary
I suggest that frequency should influence the effect of spectrum-choice _random_ when a LFO-ctrl is controlling a dial (Here PITCH)

#### Justification
In all other spectrum-choices like sine or triangle, changing FREQ has significant influence

#### Mockup
No

#### Explanation
Look at this picture
![image](https://user-images.githubusercontent.com/6662066/160700460-bb85b30a-71db-4eb1-87fe-dab68f3fa88d.png)
Here the PITCH dial has been connected to the LFO-ctrl, and random-spectrum has been chosen. Turning the FREQ-dial on LFO-ctrl does not influence the output.
I would think the random positions should be kept unchanged controlled by the FREQ dial setting. The span should ideally be between one whole note and 1/192 (-or as it is now).

**Comment by allejok96** [comment]
This would be awesome! Then you would essentially have a LFO that gave you a new random value ever beat or so. (And setting FREQ to maximum would behave like the current random)

**Comment by Spekular** [comment]
I would find this pretty inconsistent as the frequency knob maps to hz for all of the other waveforms. I think it'd make more sense to map it to a lowpass filter when using the noise oscillator, and add the time-stepping as a separate feature for all controllers. After all, a sine-shaped controller with the same stepped updating could also be useful.

**Comment by musikBear** [comment]
> This would be awesome! Then you would essentially have a LFO that gave you a new random value ever beat or so. (And setting FREQ to maximum would behave like the current random)

That is what i intend, but @specular remarks about inconsistency are absolutely valid. It would be absolutely _random_ so _no_ consistency between plays!

My thoughts were only aimed at having FREQ influencing random-spectrum, since it influence the other shapes.

Combining @allejok96 idea and speculars remark on consistency could be achieved in a different way. Here i mockup a 'random' automation pattern, and bind PITCH to it
![image](https://user-images.githubusercontent.com/6662066/160872503-22b5c7ed-ca34-499b-a5da-b6745cbc9b9f.png)
That 'works' in as mutch as it creates a reproducible output, but it sounds awful!
It is ofcouse not in scale. Pure ear bleeding kakaphony !
In fact, a non kakaphonic reproducible random pattern is better made by muting an instrument and then just record random white keystrokes.
Here we get like
![image](https://user-images.githubusercontent.com/6662066/160874831-53ee886f-9103-40bb-9338-2f779e16b9e5.png)
The inconvinience here is that humans are bAAAd in making random devellopment, we have a tendency to make 'patterns' 
But at least this kakaphony is in scale, so theoretically 'a composition' (ask T. Monk about _that_ ) 😏

**Comment by consolegrl** [comment]
I have been working on humanizing some drum samples (removing "machine-gunning") from my acoustic drum setups, and this is the feature I've been wanting to implement.  In synthesizers it's called sample-and-hold, the fact that the FREQ knob does nothing with the random waveform is inconsistent with the other waveforms.  FREQ changes the rate at which the sine/square/saw etc modulate the controller, but it doesn't change the rate at which random values are delivered.  Furthermore, to achieve the current functionality of ignoring the FREQ knob, just set the FREQ knob to an arbitrarily low value to effectively turn off the sample-and-hold functionality; this would be a pure addition.
