### ISSUE TITLE
Playing all patterns from Song editor or beat/bassline editor while in a piano roll.

### ISSUE THREAD

**Issue by Pazulay** [LMMS/lmms#6356]
### Enhancement Summary
Allow user to hear all the patterns of the project while working on one instrument in piano roll. 
Potential solution: Assign different shortcut for song editor play/pause.

#### Justification
Better workflow

**Comment by musikBear** [comment]
Already fully possible!
Follow these instructions:
https://www.youtube.com/watch?v=pFy8tipBbB8

Obs that the positions of loop-markers make it possible to set a restricted play-back section as well.
Mark:  Irrelevant

**Comment by Spekular** [comment]
As musikbear says, the play+record button already does this, playing from the start of the song or loop marker region:

![image](https://user-images.githubusercontent.com/8918426/161400295-1b1ae27f-9ca2-4cfb-a8d5-8b8402ef0187.png)
