### ISSUE TITLE
TripleOscillator FM clipping

### ISSUE THREAD

**Issue by Rudxain** [LMMS/lmms#6357]
# Please search the issue tracker for existing bug reports before submitting your own. Delete this line to confirm no similar report has been posted yet.
I searched, but haven't found similar Issues. I'm still not sure if this is a duplicate.

### Bug Summary
The plugin has a weird waveform pattern that repeats over time. I confirmed this is a bug because I tested the same configuration with ZynAddSubFX and it sounds correct there.

#### Steps to reproduce
0. Disable OSC3 (volume 0%)
1. Set FM mode (OSC1 + OSC2)
2. Set OSC1 to have any waveform other than Sine or Random-White-Noise
3. Set OSC2 to use Triangle or Sawtooth
4. Play any note (specially low ones)

#### Expected behavior
It should modulate the wave consistently

#### Actual behavior
It "goes down" for long intervals in a periodic manner

#### Screenshot
![](https://i.imgur.com/VDl0v1h.png)

#### Affected LMMS versions
v1.2.2 win32 x86_64
AFAIK, this bug existed since the version before 1.2.2

#### Logs
<details>
  <summary>Click to expand</summary>
<pre>

</pre>
</details>

**Comment by softrabbit** [comment]
At a glance, it looks like this bug isn't in 1.3, which makes sense to me as I'm pretty sure TripleOscillator has seen a lot of changes in the past years. 

So, I'd suggest tagging this a "wontfix", as fixing this in a hypothetical 1.2 series bugfix release would most likely change the sound enough to make users unhappy.

**Comment by Rudxain** [comment]
Thank you for the info, I didn't know it was fixed in 1.3

**Comment by zonkmachine** [comment]
Closing as this is resolved.
