### ISSUE TITLE
Quantize guides in the song editor and optimization

### ISSUE THREAD

**Issue by FredgioDazzle** [LMMS/lmms#6361]
It would be nice if LMMS had quantization guides on beats and also guides within beats

LMMS does not have good optimization in many of the effect plugins, just placing the ReverbSC Plugin consumes high resources

**Comment by musikBear** [comment]
> ReverbSC
just placing the ReverbSC Plugin consumes high resources

Cant reproduce 
![image](https://user-images.githubusercontent.com/6662066/161436977-b6fdd094-7168-40ad-b42a-629212d75885.png)

We need to know what you mean by _guides_
Do you want a grainier snap`?
Then just set a higher Q
![image](https://user-images.githubusercontent.com/6662066/161437174-166feaaa-936a-441e-a4cc-323a8bfd3000.png)
In next release there are more scaling-options:
![image](https://user-images.githubusercontent.com/6662066/161437221-95aeaec7-ece2-427c-97ab-4e7bee25f02a.png)
Mark invalid

**Comment by Spekular** [comment]
More granular snap in the song editor is available in master.
