### ISSUE TITLE
Pausing a Piano Roll TCO and continuing playback in a different TCO continues playing the previous one

### ISSUE THREAD

**Issue by Monospace-V** [LMMS/lmms#6365]
### Bug Summary
If a piano roll object is played, then paused (not stopped, paused), then opening another piano roll block and playing it continues to play the previous sequence.

#### Steps to reproduce
1. Create two separate piano roll track objects, with different patterns. (These can be on different or same instrument, it doesn't matter. The different pattern thing is so that the difference is clearer. This occurs even with same patterns, of course.)
2. Open one of them and play it.
3. Pause it. Do not stop it, do not use the spacebar, which stops it. PAUSE it, with the pause button next to the play button.
4. Open the other TCO and play it.

#### Expected behavior
Other TCO's pattern plays in the correct instrument where previous one left off.

#### Actual behavior
Other TCO's pattern appears to play, but sound heard is that of previous piano roll block.

#### Video of issue

https://user-images.githubusercontent.com/76674645/161955688-a976628c-8677-456b-8ae4-6a96cf7a8f77.mp4

#### Affected LMMS versions
0.4.15, 1.1.2, 1.2.0, 1.2.2, 1.3 alpha

**Comment by allejok96** [comment]
Duplicate of #4410

**Comment by Monospace-V** [comment]
Ah, sorry, searching didn't throw that one up for some reason :|
Closing.

**Comment by musikBear** [comment]
> Ah, sorry, searching didn't throw that one up for some reason :| Closing.

The Search-engine is dumb inside here. I have a ton positives -or non at all, when i search. Google actually does it better

**Comment by Monospace-V** [comment]
> The Search-engine is dumb inside here. I have a ton positives -or non at all, when i search. Google actually does it better

Yeah, it doesn't contain many of the keywords I used to search, whereas google's keyword search considers synonyms and whatnot. Maybe I should google it the next time instead of just searching github.
