### ISSUE TITLE
size of zasfx-data block in projects

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#6370]
### Enhancement Summary
I want a discussion around the size of the data-block used for saving zasfx data
#### Justification
Building smaller files

**Discuss!**
One instance of zasfx ~ 900 lines of XML, without a single note!
That is because every controller in zasfx is file-saved, notably also controllers not changed by user.
These values could exists as default values in code-base, and only be loaded from codebase, and not saved in project-file.
Loading a zasfx instance would then be a process of comparing default-value with file-value.
If the value is different from default-value, file-value is used, else default-value is used.
If user only used the LMMS-UI dials, and did not open zasfx at all, then at most 7 values would change, meaning 7 lines of XML instead of ~900 / instance of zasfx
Is this something for the future?

**Comment by Spekular** [comment]
Is it worth implementing a custom solution to save just ~3KB per ZASFX instance (in an mmpz file), especially when we can't do the same for anything non-native? Testing with Serum, for example, it appears to take ~6KB when initialized. Then, I was easily able to find a preset that increased (compressed) project size by over 100KB when compared to an initialized instance.

**Comment by DomClark** [comment]
Additionally, if you are concerned about project file sizes, you can save the project as a compressed `mmpz` file. The compression algorithm will take advantage of redundant information between multiple ZynAddSubFx instances, which is already similar to your proposed solution.

This seems like a complex and hard-to-maintain change with only marginal benefit, so I'm going to close this as "won't fix".
