### ISSUE TITLE
Time is ignored: The playback runs AFAP on Fedora 35

### ISSUE THREAD

**Issue by thelabcat** [LMMS/lmms#6377]
I have LMMS installed on Fedora Linux 35. When playing back, things go ridiculously fast and I get no audio (from MIDI tracks anyway, I haven't tried anything else). Fast as in the playback clock is displaying minutes going by in less than a second. This happens even in a default, blank file.

**Comment by musikBear** [comment]
At what BPM?
Witch version? If not LMMS 1.2.2 appimage -This:
https://lmms.io/download#linux
Please try that one
1.3 is also available, but there are stability-issues 
If you got no or bad sound, please retry with SDL as :
https://docs.lmms.io/user-manual/getting-started/setup#audio-settings
It works fine on Linux, (and is a must on windows)

**Comment by thelabcat** [comment]
> At what BPM?
> 
Absolutely any BPM produces the same results, but for the paperwork, I will repeat that I encounter the issue even in the default file, which sets the BPM at 140.
> Witch version? If not LMMS 1.2.2 appimage -This:
> 
> https://lmms.io/download#linux
> 
Yes, I am using 1.2.2, installed from the graphical software manager if I remember correctly.
> Please try that one
> 
If you insist. The software manager could have made a mistake (iTunes on windows, for example, does not work correctly unless installed from the Microsoft Store)
> 1.3 is also available, but there are stability-issues 
> 
I can try that as a test,
> If you got no or bad sound, please retry with SDL as :
> 
> https://docs.lmms.io/user-manual/getting-started/setup#audio-settings
> 
I doubt it's my sound drivers, but I can try.
> It works fine on Linux, (and is a must on windows)
> 
> 
On the contrary, I encountered no such issue installing LMMS 1.2.2  out of the box on Windows 11.

**Comment by PhysSong** [comment]
@thelabcat Could you check the audio interface setting of LMMS?

**Comment by thelabcat** [comment]
> @thelabcat Could you check the audio interface setting of LMMS?

As I said, I will check that.

**Comment by thelabcat** [comment]
Okay, it was audio devices. Wow, I feel humbled. Sorry! Leaving the audio controller as ALSA, I changed the output device from "null" to "default," and everything works fine. TYJ.
