### ISSUE TITLE
Pause continues to play rest of note

### ISSUE THREAD

**Issue by Monospace-V** [LMMS/lmms#6383]
### Bug Summary
I'm not entirely sure if this is intended behaviour, but pausing a song continues to play the rest of the length of the ongoing note instead of directly stopping sound, or perhaps going to Release.
Playing the rest of the note even upon pausing is unintuitive and confusing behaviour.

#### Steps to reproduce
1. In any instrument plugin, place a long note.
2. From Song Editor or Piano roll, play the start of the note
3. Pause the note. Don't stop it, pause it.
4. Rest of the note continues to play.

#### Expected behavior
Note goes silent.

#### Actual behavior
Rest of note continues to play.

#### Affected LMMS versions
1.2.0, 1.2.2, 1.3.0

_(A friend of mine who started using LMMS recently, typically uses pause instead of stop (while most of us use stop most of the time), notices these things more often than me. By the time I started filing bugs, I'd gotten used to this behaviour, and he's the reason I can point out unusual pause behaviour now- because I've gotten used to them and don't realise what's going on. New users often don't even understand the behaviour in the first place. To me, I already knew that pausing plays the rest of any ongoing note, but never stopped to think about it as unwanted or considered filing a report. This information isn't particularly useful to the report itself, but I think it's a telling bit of insight. What it tells, I know not; but there's definitely something to be gotten from this.)_

**Comment by RiedleroD** [comment]
I believe this is intended - but I also think it should be changed. Looking back, especially long bass / pad notes were always very annoying when pausing. I usually use stop instead, but this throws the view back to the start in longer tracks when I forget to disable the thingy that does that.

**Comment by musikBear** [comment]
"Intended" Naee.. But architecturely hard to avoid 
Funny 'Ha-haar' wise..
Pausing will actually not be different from stopping (space) if the transport is set to ">".
Playback will stop, and next press on space will start the playhead where it was ..so in fact :
Playhead was **Paused** :p
