### ISSUE TITLE
Project file decompression produces invalid decompressed file when the AppImage is used

### ISSUE THREAD

**Issue by Gumichan01** [LMMS/lmms#6384]
### Bug Summary

When I decompress a  `.mmpz` project file with LMMS (I use the AppImage file), the resulting XML file is invalid. In fact, just before the XML content I have this text:

When I remove the two first lines, the file is valid.

#### Steps to reproduce

1. `./lmms-1.2.2-linux-x86_64.AppImage -d test.mmpz > test.mmp`
2. run `xmllint --noout --format test.mmp`
3. (Optional) head -3 test.mmp

You can use any compressed project files to reproduce the issue.

#### Expected behavior

You must see something like this with `head -3`:
```
<?xml version=\"1.0\"?>
... # Some valid extra content
```
`xmllint --noout --format test.mmp` must not display any error.

#### Actual behavior

The XML file is not valid. `xmllint` displays a parsing error message. See screenshot

With `head -3` you have this:
```
Carla does not appear to be installed.  That's OK, please ignore any related library errors.
Jack appears to be installed on this system, so we'll use it.
<?xml version=\"1.0\"?>
...  #Some extra content
```

#### Screenshot

- With LMMS 1.2.2 (AppImage)

[![asciicast](https://asciinema.org/a/giFEn5c4kuymLxAuFP7zxHADw.svg)](https://asciinema.org/a/giFEn5c4kuymLxAuFP7zxHADw)

- With 1.3.0-alpha.1.183+g0dcf90912-linux-x86_64.AppImage

[![asciicast](https://asciinema.org/a/lm8FlCTh5d0jQ9sOSf0BLUJ5E.svg)](https://asciinema.org/a/lm8FlCTh5d0jQ9sOSf0BLUJ5E)

#### Affected LMMS versions

- [1.2.2](https://github.com/LMMS/lmms/releases/download/v1.2.2/lmms-1.2.2-linux-x86_64.AppImage) 
- [1.3.0-alpha.1.183+g0dcf90912-linux-x86_64.AppImage](https://output.circle-artifacts.com/output/job/bacfac4e-3198-4e96-9c28-c0189f29bb8b/artifacts/0/lmms-1.3.0-alpha.1.183+g0dcf90912-linux-x86_64.AppImage)..

I can reproduce in Debian 10.

**Comment by allejok96** [comment]
Thanks to your very good bug report this was easy to find
