### ISSUE TITLE
Effects rack

### ISSUE THREAD

**Issue by Rossmaxx** [LMMS/lmms#6388]
I feel like it would be a good idea to have an effects rack similar to controller rack. This window contains all the effects controls. 

![IMG_20220427_204118](https://user-images.githubusercontent.com/74815851/165554553-5407366f-3dfc-484c-95fc-0627e6087241.jpg)
this is a mock up i made with pen and paper.

This is a good way of organizing all those effects control windows into one single window. This can also help people with RSI issues as they don't need to locate different controls as everything is available within one window. This can also help move us closer to budislav's single window concept. 

This idea is just my opinion. If you differ from my view, feel free to do so. This issue is meant to initiate discussion on this topic. If anyone is kind enough to make a design and send it in here, feel free. 

Do note that to implement this, we would need to have a redesign of all the effects plugins.

**Comment by musikBear** [comment]
If i understand you you would like a screen where **all** effect-plugins that has been used in the **complete project** are both listed, _and can be edited_.
Is that correct?

**Comment by roshanrules1** [comment]
> If i understand you you would like a screen where **all** effect-plugins that has been used in the **complete project** are both listed, _and can be edited_. Is that correct?

You are correct. That's exactly what i want.

**Comment by roshanrules1** [comment]
![IMG_20220427_204118](https://user-images.githubusercontent.com/74815851/165554553-5407366f-3dfc-484c-95fc-0627e6087241.jpg)
This is a mock-up i made on pen and paper. Hope this provides enough details. If anything is missing, just reply.

**Comment by roshanrules1** [comment]
> iirc you still can't open Peak Controllers from Controller Rack... god help you if you forgot to name it, now you gotta scroll through all your instruments and guess which controller corresponds to what on the controller rack 😬 I'm a bit upset about that. If it's the same thing with FX- unmapped, uneditable directly from there, just some info, it's going to be pretty useless.
#2944 is the fix for the issue you stated and it's very similar to my proposal (tbh that's what gave me the idea in the first place.)

**Comment by Rossmaxx** [comment]
> I notice that the issue you linked to doesn't appear to have info on what parameter each controller is mapped to.

The solution to that issue can be found in my mockup (ie my pen sketch). In the title bar of the peak controller, we can just add 
~audiofileprocessor/808kick~

Hope that fixes it.
Pinging @BaraMGB

**Comment by RiedleroD** [comment]
I've long wanted a way to split, copy, merge and manipulate individual channels in the effects tab - but I think that'd need a complete rework of the effects system, wouldn't it?

Still, I wanted to mention that because if we're collecting ideas for a unified effect rack, this could be relevant.

**Comment by Rossmaxx** [comment]
Looking back, some of what i specified is stupidity and not really practical. I'll open another issue with better proposal and mockups later
