### ISSUE TITLE
project file folders for better organisation

### ISSUE THREAD

**Issue by Rossmaxx** [LMMS/lmms#6389]
### Enhancement Summary
This is my idea for organizing the 'my projects' folder in a better way. As of now, the aforementioned folder is cluttered. This can also serve as an alternative to  #1257 in the future.
This proposal can also help in implementing #6363 as the sample caches can go into this folder instead of random pre-defined folders. 
i earlier made an issue title ideas for 1.3 which got closed. this idea was a part of that meta issue. so i thought of separating this issue for better visibility.
#### Mockup
![Capture](https://user-images.githubusercontent.com/74815851/163661555-afc34836-9be8-41a4-a397-f1d335ed6bdc.JPG)

**Comment by Spekular** [comment]
Portable files are better solved via .zips as suggested in e.g. #4922 or #3981, IMO. Sample caching doesn't necessarily rely on external files at all, but if it were to do so a .zip would be suitable there as well.

**Comment by Rossmaxx** [comment]
i get it but for me, the my projects folder gets way too messy with the exports, bak files, etc along with the mmpzs. if we are to implement folders, we can put them all in one folder. also sample caches inside zip files, that is something i didn't really think about. if this gets implemented, we can zip up these folders and send them to others, atleast that's what i thought.

**Comment by Rossmaxx** [comment]
i get it but for me, the my projects folder gets way too messy with the exports, bak files, etc along with the mmpzs. if we are to implement folders, we can put them all in one folder. also sample caches inside zip files, that is something i didn't really think about. if this gets implemented, we can zip up these folders and send them to others, atleast that's what i thought.

**Comment by allejok96** [comment]
I don't understand exactly what you suggest be changed. This is already possible, and in fact how I organize my files today. You can't blame LMMS for where your files are stored. It does ask you where to save them.

That being said, there could be some improvements to loading samples, like falling back to samples in the same directory as the project file. Or a tool to scan for missing samples.

**Comment by Rossmaxx** [comment]
Closing this issue as this issue got no real point.

**Comment by Rossmaxx** [comment]
I thought this idea was cool but after these discussions, it feels like a dumb thing to implement on the codebase. Its better off th do it manually.
