### ISSUE TITLE
new roadmap for the ui/ux development

### ISSUE THREAD

**Issue by Rossmaxx** [LMMS/lmms#6393]
### Enhancement Summary
this is just a meta issue collecting all ui/ux related issues and organising them into which versions each one could go into(it also includes editing of existing milestones). this issue is meant to be a point of discussion. i'm listing the versions and what change each version can take on.

#### 1.3
- remove the file operation buttons (see the discussion on #5261 )
- better theming support pt 1 (splitting #1839 into 2 parts)
#### 1.4
- better theming support pt 2
- remove oscilloscope and take it out as a native plugin. (also from discussion of #5261 )
- reduce height of toolbar
- complete lv2 support (this is not really a ui/ux issue but i put in this one for zyn)
#### 2.0 (ui focused theme)
- full implementation of #5261
- #2944 
- #6388 
- zyn 3
- new theme (preferably one which is closer towards budislav's concept)
- #5952 
#### 2.1
- #5571
- right hand side bar
- - properties
- - always on top
- - contains controller rack, effects rack, project notes (more can be added in the future)
- - remove embedding (to prepare for 1.3, no prob if done at a later version)
#### 3.0
full implement of budislav's single window design #1911

**Comment by Monospace-V** [comment]
https://github.com/LMMS/lmms/issues?q=label%3Agui+
Could be of use.

**Comment by qnebra** [comment]
Sooo, quite nice and elaborated plan for development.

Now, opinions:

- improving UI and making new requiered splitting QT from lmms core functions, which is already ongoing
- there are some hardcoded UI values in code, those are systematically removed
- more and more elements of UI is themable via CSS
- main tendency, from what I see, is stability and functions

**Comment by Rossmaxx** [comment]
>improving UI and making new required splitting QT from lmms core functions, which is already ongoing

that is a needed point but i excluded it because i'm pretty confident it will be done soon enough (if not, no hurry).

> there are some hardcoded UI values in code, those are systematically removed
more and more elements of UI is themable via CSS

ie #1839

**Comment by Rossmaxx** [comment]
Closing this as i got a better idea.
