### ISSUE TITLE
Midi cut

### ISSUE THREAD

**Issue by CryptoCashCashoo** [LMMS/lmms#6396]
# Please search the issue tracker for existing feature requests before submitting your own. Delete this line to confirm no similar request has been posted yet.

### Enhancement Summary
To be able to cut a midi track.

#### Justification
Opening the piano roll and copy and pasting the notes into another track is really difficult / prone error and time consuming.

**Comment by allejok96** [comment]
https://user-images.githubusercontent.com/7693838/167219203-0ee64c13-6102-4f6b-9ac4-b81f3e778cfd.mp4

**Comment by Monospace-V** [comment]
Ctrl-drag.

**Comment by CryptoCashCashoo** [comment]
Sorry, I think Cutting a midi file was not a clear tittle. 
I have a Midi 60 seconds long, and I want to cut it between 30.05 and 30.40 so I get 3 Midis each.

**Comment by Spekular** [comment]
Regardless we already have an issue for the generalized version of this: #3829 (closed as it's consolidated in the "better workflow" meta issue)
