### ISSUE TITLE
Colour of Master bus on FX Mixer retains when switching project

### ISSUE THREAD

**Issue by Monospace-V** [LMMS/lmms#6398]
### Bug Summary
If a project has the master bus on the FX-Mixer set a certain colour, and then we open any other project where the master channel does not have a colour set, master channel remains that colour.

#### Steps to reproduce
1. Create a project and change the colour of the mixer's master channel. Alternatively, open a project that has a non-default colour on the mixer's master bus.
2. In the same session of LMMS, create a new project, or open any other project where master channel's colour is still default.
3. Look at the colour of master channel on mixer.

#### Expected behavior
Master channel resets to default colour

#### Actual behavior
Master channel remains coloured

#### Demonstration:

https://user-images.githubusercontent.com/76674645/167285887-deb4df1e-348a-41a1-b69f-46275cc2e5a8.mp4

#### Affected LMMS versions

LMMS 1.3 (only version with ability to change FX-channel colours)

**Comment by spechtstatt** [comment]
Maybe I can take it because I am currently completely "in" the mixer.
