### ISSUE TITLE
SF2 player: Note-Off Event of note C-1 played in piano roll crashes LMMS

### ISSUE THREAD

**Issue by SDwarfs** [LMMS/lmms#6406]
When putting the note C-1 (lowest possible note, meaning C "minus 1" not C1!!!) in the piano roll of a track using the SF2 Player, LMMS crashes at the end of this note.

**Details**
It does only crash using the SF2 Player (no other synth), Hence it's related to the SF2-Player. I also tested multiple SF2 files - it crashed with all of them. So, the bug seems to be in the SF2 Player code itself or something triggered by it. Since, this does not happen for previous versions (having C0 as the lowest possible Piano Roll note), this might be related to an index out of bounds and/or a change in that part of the Piano Roll code.

**Steps to Reproduce**
1. Open LMMS
2. Drag the SF2-Player into the Song Editor (if no default SF2 is set, load a SF2)
3. Double Click the Song Editor's grid of the new track to create a new piano roll pattern.
4. Scroll down to the bottom, put a C-1 (lowest note) into piano roll (position in time or length does not matter)
5. Hit Space-Bar (to start play back)
6. C-1 is played -> LMMS hangs shortly at the end of the note, then crashes

**Expected Behavior:**
No hanging/crashing at the end of the note.

LMMS-Version: Current Windows "Nightly"
Version-String: Version 1.3.0-alpha.1.102+g89fc6c960 (win32/x86_64, Qt 5.9.8, GCC 7.3-win32 20180312)

**Comment by Monospace-V** [comment]
Reproduced.
Doesn't occur if I move the basenote down so that C-1 produces a sound.

**Comment by PhysSong** [comment]
See also: https://github.com/LMMS/lmms/pull/6308#issuecomment-1040131468
