### ISSUE TITLE
Impulse Response Convolution Reverb Request

### ISSUE THREAD

**Issue by unfa** [LMMS/lmms#641]
LV2 plugins are not about to be usable within LMMS (AFAIK).
And what I want to use in LMMS is unfortunately availabile only as a LV2 plugin.

I'm talking about the Tom Szylagyi "IR" plugin. It's a wonderful and very versatile 2 or 4 channel convolution reverb processor:
http://factorial.hu/plugins/lv2/ir

Convolution can give the user some unique and very pleasing sounds, especially for simulating real room's reverbation, or some sampled reverb units (springs sound cool), but when fed with something wicked, you can get all sorts of cools stuff ranging form ghostly horror sounds to old radio eq. An IR processor allows for amazingly cool and creative sounds to emerge, from combining random samples (what will I get when I convolute sample A with sample B? A-hah!).

Is there any possibility that the Tom's IR effect can be ported to LMMS native effect plugin format and bundeled with it?

If not, how could we get some processor written for LMMS? It could be very simple at first only allowing one to load a IR sample, and manipulate pre and post gains and dry/wet. It would already be a big leap forward that would help getting more "realistic" and less "digital" sounds out of LMMS.

**Comment by PaulBatchelor** [comment]
Okay! So, the inner loop code has been implemented. Things have been fairly straight forward so far. 
I've attached a little audio snippet of ReverbSC being applied to the "Vibed" synth here: [revsc_test.zip](https://github.com/LMMS/lmms/files/681006/revsc_test.zip). 

What's left for me now:
- Add dcblocker filter to output
- Hook up knobs
- Tidy up code and tweak artwork to fit new dimensions
- Make PR

Should have a PR ready by tonight or tomorrow.

**Comment by PaulBatchelor** [comment]
@diizy @unfa If you've given up, I'd be willing to look into implementing this. Soundpipe has a partitioned convolution module that you can find [here](https://github.com/PaulBatchelor/Soundpipe/blob/master/modules/conv.c). It works quite well. I've been able to convolve 8s impulse responses in realtime (and still maintain a decent CPU time)! The thing you sacrifice is a delay, which you can control in samples. For something like reverb, however, this really is a non issue.

The challenge from my standpoint would be getting things hooked up with LMMS components. Being able to load files into soundpipe, and switching between them is one issue I forsee. Another is being able to change latency, which is really only an init-time thing. I will need some guidance in those areas.

**Comment by zonkmachine** [comment]
@unfa doesn't code (yet...) and @diizy pushed his impulse convolver branch [here](https://github.com/diizy/lmms/commits/impulse) but hasn't been around here in a while.

You're most welcome to pick up the convoler idea but please see this comment from above:

> Also if we get support for LV2 effects in 1.2, then it's kind of
pointless to do anyway...

@grejppi is working on LV2 support for 1.3 . I don't know how much pointlessness that would bring to this issue but I still think this would be appreciated.

**Comment by PaulBatchelor** [comment]
@zonkmachine I'll be sure to take a better look at what's been happening and assess if I even have the time for it. I couldn't resist but poke around at some of the GH issues. That being said, I am of the belief that there is still merit to having some good "in-the-box" native plugins like a convolver. Thanks for the response!

**Comment by JohannesLorenz** [comment]
As we're developing Lv2 plugin support ( #4899 is already a valid Lv2 core implementation ), it's not worth the effort to program a separate IR plugin for LMMS. We'll soon be able to use [Tom's IR plugin](https://github.com/tomszilagyi/ir.lv2).

**Comment by grejppi** [comment]
@JohannesLorenz FWIW that plugin isn't completely conforming to the LV2 specifications (it saves its state using its own not-really-portable way instead of the standard interface); there are more conforming alternatives such as `convo.lv2` or `Klangfalter`
