### ISSUE TITLE
CALF Gate LADSPA has very distorted output and very limited sane span of dials

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#6423]
### Bug Summary
I am making some experiments with gates, and CALF Gate LADSPA is a disappointing plugin.
I believe the two most obvious fails are connected.
* The span of dials are limited to decimals.
* Inside the active span, the sound is badly distorted 
 

#### Steps to reproduce
Make a note-setup like this:
![image](https://user-images.githubusercontent.com/6662066/171916401-3ef8a9f7-0085-416a-a492-6ee5f539ef7f.png)

Then add the plugin on the FX-tab, and set it up:
![image](https://user-images.githubusercontent.com/6662066/171916561-e5dd2516-0752-4c50-ac9d-18868e7e1c18.png)
Play
It sounds bad.

#### Expected behavior
The gate should shutout sounds below threshold completely, and sound above threshold should be played without distortion

#### Actual behavior
sounds below threshold can be heard going through, and the sane span of sounds are distorted 

#### Affected LMMS versions
at least 1.3

#### Considerations
LMMS already has several gates.
The one named just _Gate_ work much better, and produces clean output. The dials also has more useable span.
Why keep CALF Gate LADSPA, if it is inferior?
Perhaps LMMS should get one new *LMMSGate*, with graphical UI of the gating process, and _both_ an upper threshold and a lower threshold, as can be seen in other DAWs

**Comment by RiedleroD** [comment]
> Why keep CALF Gate LADSPA, if it is inferior?

backwards compatibility. Perhaps it's better to mark some plugins as deprecated or even hide them though.

**Comment by zonkmachine** [comment]
Gaing is a bit brute force and don't sound good on all use cases. In the settings suggested above both attack and release are set to 0 so this would probably explain the disappointment. Please, iIf you want better feedback than this you need to upload a demo track that displays the issue.
