### ISSUE TITLE
Send FX  of a channel and other Mixer FX

### ISSUE THREAD

**Issue by A350** [LMMS/lmms#6428]
Swapping fx on different channels in the fx mixer doesn't work.

Linux version

lmms-1.3.0-alpha.1.102+g89fc6c9-linux-x86_64.AppImage

**Comment by Spekular** [comment]
Please clarify what you're asking for and clean up the body of the issue.

**Comment by musikBear** [comment]
@A350 
You **MUST** use the template for either Bugs or Enhancements!
First click
https://github.com/LMMS/lmms/issues/new/choose
Then choose one of theese
![image](https://user-images.githubusercontent.com/6662066/173083863-8c59fca8-8d89-4315-82b2-c085548daa9d.png)
and there use the template!
Remove _this_ and make a new correctly formatted post, where you _use the template_

**Comment by qnebra** [comment]
Well, I want to hear more details. If it was general "send" it was possible in lmms, but somewhat hard to discover in lmms (not as hard as in some other DAWs)

**Comment by zonkmachine** [comment]
> Remove _this_ and make a new correctly formatted post,...

No, please don't! Just clear up this one.

**Comment by zonkmachine** [comment]
It is unclear what OP is trying to do. Closing in lack of response. @A350 If you still need help with this, please respond in this topic or use or Discord channel which has a dedicated #support.
