### ISSUE TITLE
Exporting (copy/pasting) Zynaddsubfx resonance curves does not work

### ISSUE THREAD

**Issue by Qtamo** [LMMS/lmms#6435]
How to reproduce:

1. Open 2 instances of ZynAddsubfx
2. On one of the instances navigate to ADsynth, click "Resonance" (bottom right), click "Enable", click "RND1", then click "C"
3. Click "Copy to clipboard" (or alternatively write something in the text bard and click "Copy to preset", neither of these work)
4. Now open the other instance of Zynaddsubfx and do the same navigation, except after clicking "enable", click "P" instead. You will notice it's impossible to paste any resonance curves from anywhere.

Version 1.3.0-alpha.1.33+g4f74151 (Linux/x86_64, Qt 5.6.3, GCC 5.4.0 20160609).

**Comment by musikBear** [comment]
zasfx internal copy/paste is _meant for voices_ inside _the same_ zasfx instrument, not between different instruments/ instances

**Comment by Qtamo** [comment]
Thanks for the clarification! Out of the scope of LMMS to change then I suppose, more something to ask about from zasfx devs.
