### ISSUE TITLE
Bad selection of colors on SF2 UI

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#6454]
### Bug Summary
Visual impaired can see the settings for BANK & PATCH.
Dark-purple on black is not functional

#### Steps to reproduce
Just look at it

#### Expected behavior
Clear and distinctable  UI-text

#### Actual behavior
Not distinctable  UI-text

#### Screenshot
![image](https://user-images.githubusercontent.com/6662066/176727481-8aeec481-13e4-4a7a-8712-be854a901543.png)

#### Affected LMMS versions
< 1.2. 

#### Type of Issue
Good fist Issue

**Comment by spechtstatt** [comment]
@musikBear: didn't you want to write "can't see"?

**Comment by Rossmaxx** [comment]
@musikBear is this issue there with 1.3 alpha too or is this a nightly specific regression? I'm thinking of taking a shot at fixing the underlying issue so need more details. Also, don't have the alpha as i exclusively use the nightly.

**Comment by DanielKauss** [comment]
Pretty sure the box uses the file `data/themes/default/lcd_21pink.png` for the colours, so just increasing the brightness of the digits may be enough of a fix. The only places where this colour is currently used are Gigplayer and SF2, so there shouldn't be any issues with changing it.

**Comment by Rossmaxx** [comment]
@DanielKauss thanks for the hint. I opened a pr (#6914) which will fix this issue.

**Comment by musikBear** [comment]
> @musikBear is this issue there with 1.3 alpha too 

Yes on my 1.3
![image](https://github.com/LMMS/lmms/assets/6662066/a19453af-83b7-4308-8257-c0761f140e34)
witch is
![image](https://github.com/LMMS/lmms/assets/6662066/97ba194f-98c2-43c5-be2c-cfe831a8d4a4)
-Its old

**Comment by Veratil** [comment]
@musikBear can you take a look at the PR Rossmaxx opened, #6914, and tell us what you think of the color change?

**Comment by tresf** [comment]
Deja vu... https://github.com/LMMS/lmms/pull/6474#issuecomment-1208904611
