### ISSUE TITLE
Missing namespaces - build problem on Linux Mint

### ISSUE THREAD

**Issue by rola22** [LMMS/lmms#6457]
Hello.

I had a problem compiling `LMMS 1.3.0-alpha.1.211+ga6e6afb0e` on Linux Mint.
According to console messages I've changed some lines of code in `lmms/plugins/ZynAddSubFx/zynaddsubfx/src/Misc/QtXmlWrapper.cpp`
After this changes LMMS compiled without errors.
I am not experienced enough to make pull request, so if this solution is correct, please merge it :)

199: `FILE *file = F_OPEN_UTF8(std::string(filename), "w");` to `FILE *file = lmms::F_OPEN_UTF8(std::string(filename), "w");`

217: `gzfile = gzdopen(fileToDescriptor(file), options);` to `gzfile = gzdopen(lmms::fileToDescriptor(file), options);`

321: `gzFile gzfile  = gzdopen(fileToDescriptor(F_OPEN_UTF8(filename, "rb")), "rb");` to `gzFile gzfile  = gzdopen(lmms::fileToDescriptor(lmms::F_OPEN_UTF8(filename, "rb")), "rb");`

513: `return LocaleHelper::toFloat( tmp.attribute( "value" ) );` to `return lmms::LocaleHelper::toFloat( tmp.attribute( "value" ) );`

**Comment by Veratil** [comment]
Please make sure you've done a submodule update. These changes are already applied. For instance, https://github.com/LMMS/zynaddsubfx/blob/b9855dbe16424edc528a6796ddbc50b1042482c7/src/Misc/QtXmlWrapper.cpp#L199
