### ISSUE TITLE
The GUI of Quiet Piano VST doesn't show properly

### ISSUE THREAD

**Issue by zi-jing** [LMMS/lmms#6468]
### Bug Summary

Shown in the screenshot, when I open the GUI of Quiet Piano, I can't see the complete GUI. Enlarging the window makes no difference.

![image](https://user-images.githubusercontent.com/44922707/180652865-810f46f1-bba6-461a-9c39-e267918494fd.png)

#### Steps to reproduce

1. Download & install Quiet Piano on [this site](https://quietmusic.eu/quiet-piano) for free.
2. Load Quiet Piano with VeSTige
3. Then the bug shows up

#### Expected behavior

The complete GUI should be shown like this:

![image](https://user-images.githubusercontent.com/44922707/180653240-ad44f166-7bf0-497e-b104-16628f3bc40b.png)

#### Actual behavior

The GUI is partly shown, which makes it unusable.

#### Screenshot

![image](https://user-images.githubusercontent.com/44922707/180653325-db8cdf0c-b7d6-4bf0-ab9c-ab88d9387d61.png)

#### Affected LMMS versions

1.3.0-alpha.1.102+g89fc6c960 (win32/x86_64, Qt 5.9.8, GCC 7.3-win32 20180312)

#### Logs
<details>
  <summary>Click to expand</summary>
<pre>
LmmsPalette(0x24d42cff1f0)  does not have a property named  "toolTipText"
LmmsPalette(0x24d42cff1f0)  does not have a property named  "toolTipBase"
Cannot load library C:\Program Files\LMMS\plugins\spectrumanalyzer.dll: ???????????????
Cannot load library C:\Program Files\LMMS\plugins\carlapatchbay.dll: ????????????顣
Cannot load library C:\Program Files\LMMS\plugins\papu.dll: ???????????????
Cannot load library C:\Program Files\LMMS\plugins\carlarack.dll: ????????????顣
Cannot load library C:\Program Files\LMMS\plugins\carlabase.dll: ????????????顣
Cannot load library C:\Program Files\LMMS\plugins\OPL2.dll: ???????????????
AutomationEditor(0x24d46afd980)  does not have a property named  "vertexColor"
AutomationEditor(0x24d46afd980)  does not have a property named  "vertexColor"
AutomationEditor(0x24d46afd980)  does not have a property named  "vertexColor"
unique ID: OUUa
RemotePlugin::DebugMessage: inputs: 0  output: 32
RemotePlugin::DebugMessage: creating editor
RemotePlugin::DebugMessage: editor successfully created
QObject::connect: Cannot connect (null)::subWindowActivated( QMdiSubWindow* ) to SubWindow::focusChanged( QMdiSubWindow* )
</pre>
</details>

**Comment by musikBear** [comment]
Go to
Edit Settings| 
Look for Embedding in either General or Performance (depd. on version)
And set embedding to **NO-embedding**
https://i.imgur.com/2Wu52W2.png

Please close if fixed.

**Comment by zi-jing** [comment]
> 

It works well! Thank you for your help.

**Comment by zi-jing** [comment]
> Go to Edit Settings| Look for Embedding in either General or Performance (depd. on version) And set embedding to **NO-embedding** https://i.imgur.com/2Wu52W2.png
> 
> Please close if fixed.

It works well! Thank you for your help.
