### ISSUE TITLE
Division with 0 in BandLimitedWave.h

### ISSUE THREAD

**Issue by zonkmachine** [LMMS/lmms#6487]
Division with 0 in BandLimitedWave.h
https://github.com/LMMS/lmms/blob/9faa1d90c4b2eac2f19ca14f78354405ca9a04dc/include/BandLimitedWave.h#L120-L123

It seem to be used only in LB302 and Monstro which will crash in fpe enabled debugging.
So, std::max() with some suitable small number.

The function above, freqToLen() is also potentially dividing with 0 but doesn't seem to be used anywhere.
https://github.com/LMMS/lmms/blob/9faa1d90c4b2eac2f19ca14f78354405ca9a04dc/include/BandLimitedWave.h#L114-L117

**Comment by luzpaz** [comment]
soft bump

**Comment by zonkmachine** [comment]
> soft bump

Please stop bumping issues/PR's with no new information.
