### ISSUE TITLE
symbol lookup error: /opt/lmms/lib/lmms/ladspa/tap_deesser.so: undefined symbol: __log10f_finite

### ISSUE THREAD

**Issue by hankster112** [LMMS/lmms#6500]
### Bug Summary
LMMS fails to launch with error:
`./lmms: symbol lookup error: /opt/lmms/lib/lmms/ladspa/tap_deesser.so: undefined symbol: __log10f_finite`

#### Steps to reproduce
Build LMMS from master 4821606 on Devuan 4 (Debian 11) 

#### Expected behavior
LMMS launches

#### Actual behavior
LMMS splash screen appears then closes. Running through terminal results in above error.

#### Screenshot
N/A

#### Affected LMMS versions
Latest build from master

#### Logs
<details>
  <summary>Click to expand</summary>
<pre>
Lv2 plugin SUMMARY: 0 of 0  loaded in 0 msecs.
./lmms: symbol lookup error: /opt/lmms/lib/lmms/ladspa/tap_deesser.so: undefined symbol: __log10f_finite
</pre>
</details>

**Comment by allejok96** [comment]
I'm grasping for straws, but what if you `make clean` or just delete everything and build again, or optionally delete `tap_deesser.so` and build again?

**Comment by hankster112** [comment]
Ran `cmake clean`, fixed itself. Thanks.
