### ISSUE TITLE
Cannot create AppImage on Debian 11

### ISSUE THREAD

**Issue by hankster112** [LMMS/lmms#6503]
### Bug Summary
cmake fails to create an AppImage after building

#### Steps to reproduce
Build LMMS from latest commit 3cc5ec7 on master on Devuan 4 (Debian 11)

#### Expected behavior
AppImage should be created after building

#### Actual behavior
Fails to create appimage. appears to have an issue downloading from linuxdeployqt

#### Affected LMMS versions
Latest commit from master

#### Logs
<details>
  <summary>Click to expand</summary>
<pre>
Downloading linuxdeployqt to /home/solomon/Builds/lmms/build/linuxdeployqt...
   [.......] Downloading (unknown): https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-unknown.AppImage
rm: cannot remove 'linuxdeployqt-continuous-unknown.AppImage': No such file or directory
make[3]: *** [cmake/linux/CMakeFiles/appimage.dir/build.make:78: cmake/linux/CMakeFiles/appimage] Error 1
make[2]: *** [CMakeFiles/Makefile2:2419: cmake/linux/CMakeFiles/appimage.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:2426: cmake/linux/CMakeFiles/appimage.dir/rule] Error 2
make: *** [Makefile:245: appimage] Error 2
</pre>
</details>

**Comment by allejok96** [comment]
Just a quick question, why do you want to create an AppImage?

**Comment by sakertooth** [comment]
Can this be closed?

**Comment by allejok96** [comment]
FYI build will still fail but that is due to a restriction in linuxdeployqt. 

#6510 only fixed some bugs that made the build process crash before reaching the mentioned restriction.
