### ISSUE TITLE
Language setting shows a long~ empty list

### ISSUE THREAD

**Issue by NORYOM** [LMMS/lmms#6506]
Edit -> Setting 
When change language will show a long empty list, and I research the folder of locale found the problem.

under \LMMS\data\locale there are many files seems not read as effective language file, so it shows nothing.
remove all file which name start with 'qt' out of the folder (\LMMS\data\locale) will resolve this problem.

**Comment by NORYOM** [comment]
Screenshot as following:

![00](https://user-images.githubusercontent.com/29390989/189043809-9cc8cce8-c05b-45b6-a642-f3b0aaa79ec4.png)
![01](https://user-images.githubusercontent.com/29390989/189043810-f3a3d612-dbf2-4b3f-8bc0-0fb2ce93d0d6.png)
![02](https://user-images.githubusercontent.com/29390989/189043811-9519739b-2a2f-486f-a3ee-6eda6a43ad14.png)
![03](https://user-images.githubusercontent.com/29390989/189043812-29cbc475-b55c-4515-861d-831fccfab6ae.png)
![04](https://user-images.githubusercontent.com/29390989/189043814-db7efb9d-de9d-4883-bfa7-89cd0b75b5c3.png)

**Comment by musikBear** [comment]
Cant reproduce 
![image](https://user-images.githubusercontent.com/6662066/189488517-43c4aa14-b49c-43a1-904b-5df58a33f90a.png)
What version/ What OS?

**Comment by anytizer** [comment]
Issue persists on Windows version - alpha 1.121. Looks like there is a huge gap from "P" to "R" initials in the list of the languages, and few other names.

**Comment by musikBear** [comment]
> Issue persists on Windows version - alpha 1.121. Looks like there is a huge gap from "P" to "R" initials in the list of the languages, and few other names.

ok, and i have
![image](https://user-images.githubusercontent.com/6662066/189539380-13d92268-a157-44e0-be75-e24a08769769.png)
where its not, but is it at all our executable that is the colpit.
It looks like there are a HUGE addition of languages in your installation.
I have ..25!
![image](https://user-images.githubusercontent.com/6662066/189539485-9d63b4e8-276f-4c17-8478-01e876c665f5.png)
If the new ones you have are 'flawed', then that could perhaps result in the gabs in the list(?)

**Comment by anytizer** [comment]
![image](https://user-images.githubusercontent.com/5563341/189551418-0b7e0d5d-49a8-45fe-8ece-33f0e4a97455.png)
Deleted LMMS Data folder and reinstalled alpha 1.222 build. 2 entries appeared blank.

**Comment by Monospace-V** [comment]
Can't replicate on 1.2.0.
Can replicate on 1.3
![image](https://user-images.githubusercontent.com/76674645/189593081-6dcdd882-506e-4f71-aeca-ee83c87d4550.png)
Two blank entries.
Windows 10.

**Comment by allejok96** [comment]
This line

https://github.com/LMMS/lmms/blob/master/src/gui/modals/SetupDialog.cpp#L284

Takes the first part of the file name and coverts it to the name of the language ("en" -> "English"). Even if there is no language matching the abbreviation (for example "qt_help..." is no language code) it still adds an empty line to the list.

Question is how did those qt_ files end up in that directory??

**Comment by NORYOM** [comment]
it happened on win7 and win10, LMMS version is 1.2.2 (win32/x86_64, Qt 5.4.2, GCC 4.9.4 20150716 (prerelease))

Thanks Rossmaxx for confirmed the bug.
Thanks allejok96, Monospace-V, anytizer and musikBear join to this bug talking.

**Comment by zonkmachine** [comment]
> Question is how did those qt_ files end up in that directory??

Could they be related to translation work, Qt Linguits?

**Comment by allejok96** [comment]
Some further research shows that the 1.2.2 build for windows includes a lot of `qt_` file, but that is not the case for 1.2.1 and 1.3. So something slipped in there during the build that shouldn't be there. I don't know why, perhaps Qt Linguist or Creator like zonk said. But it doesn't really matter, since they're not present in 1.3...

The two blank lines you see in 1.3 are for Occitan and Esperanto. Apparently Qt does not provide a `nativeLanguageName` for them.

**Comment by opensourcefree** [comment]
I have this too on windows 10, version 1.2.2 official download for 64 bit windows
