### ISSUE TITLE
copying part of a song lags lmms

### ISSUE THREAD

**Issue by TheAwesome98-Real** [LMMS/lmms#6508]
### Bug Summary
copying a small part of a large song will freeze lmms for a few seconds

#### Steps to reproduce
1. import a full song
2. snip it down to 1 bar
3. intend to copy it for a measure
4. it freezes on every copy

#### Expected behavior
lmms does not freeze at all, or for a much shorter amount of time

#### Actual behavior
lmms freezes for around 10 seconds every time you copy the track

#### Screenshot
N/A

#### Affected LMMS versions
![image](https://user-images.githubusercontent.com/59254971/189390379-fb71fd91-bbab-49ce-bae3-cadf3ef64cb5.png)

#### Logs
(nothing is output when you copy)

#### Additional information

if you open system monitor and look at lmms's memory usage, you will see something like this:

before: 1.3GiB
while: 1.7GiB
after: 1.4GiB

would it be possible for lmms to measure how much of the song it needs to copy? this would probably stop the program from freezing. alternatively, you could import it on another thread than the ui, but i don't know if this is possible either.

**Comment by allejok96** [comment]
I assume by _song_ you mean sample track. In my brief testing the AppImage uses 55MiB RAM when started and 138 MiB after importing a 3:30 long sample. That suggests your project has almost an hour of samples (every clip counts). This is a known bug (though I can't find a bug report of it). The main problem is that copying a sample clip will duplicate the full sample in memory. Solutions are underway.

**Comment by TheAwesome98-Real** [comment]
> I assume by _song_ you mean sample track.

yeah, i meant i had a full song on a sample track

> The main problem is that copying a sample clip will duplicate the full sample in memory.

yeah this is what i thought was happening

> Solutions are underway.

thank you

**Comment by allejok96** [comment]
Issue will be fixed when we get sample caching. Closing this as a part of meta-issue #1471
