### ISSUE TITLE
Lmms UI modernise

### ISSUE THREAD

**Issue by CaelanTheCoder** [LMMS/lmms#6514]
# Please search the issue tracker for existing feature requests before submitting your own. Delete this line to confirm no similar request has been posted yet.

### Enhancement Summary
Get rid of shadows
Use flat colors rethink UI

#### Justification
UI is cluttered and outdated

#### Mockup

![image](https://user-images.githubusercontent.com/107891742/190988884-d2306157-4967-47b1-84f3-2b9fc636de7e.png)

**Comment by qnebra** [comment]
1. Nope, they are useful in UI. 
2. Maybe. 
3. It's ongoing effort, slow but ongoing.
4. You didn't see really cluttered UI
5. Didn't you add undo/redo buttons into lmms headerbar and it blow up for some reason?

**Comment by RoxasKH** [comment]
LMMS already has a plan for a UI remake, even if definitely more difficult than just a theme change.

https://github.com/LMMS/lmms/issues/1911

Also that theme you posted seem to have a lot of problems. The squared buttons aren't great and everything in the topbar is misaligned.

There are better managed flat theme out there imo, like the [Liquid](https://lmms.io/lsp/?action=show&file=15315) or its [improved version](https://lmms.io/lsp/?action=show&file=18140)

**Comment by Spekular** [comment]
Low quality issue, search "UI" or "Redesign" for dupes.
