### ISSUE TITLE
beginner questions

### ISSUE THREAD

**Issue by opensourcefree** [LMMS/lmms#6521]
Hi everybody!

Thanks for this great software.
As a beginner I have some questions. I'm using version 1.2.2 on Linux.

- I saw you can save using "Save" and "Save as new version". Is the "Save as new version" there to be compatible with version 1.3.0 alpha 1 because this version will use a new fiel format? 
So it's not recommended anymore to use the old save format if I want my files to load in  1.3.0 ?

- can VeSTige use 64 bit VST or only 32 bit VST on Linux?

- If I save a LMMS file on Linux, will I be able to load it in MacOS or even Windows too (without any changes)? Is the file format completely cross-platform?

- does LMMS use multiple CPU cores when playing music or does it not matter how many CPU cores I have?

Thank you so much
Lisa

**Comment by Monospace-V** [comment]
Re: the last two questions, I've found some LADSPA effects may not load perfectly, but those are rare.
I'm pretty sure it uses all your CPU cores. If you have two it uses both. If you have sixteen it uses all.

**Comment by Rossmaxx** [comment]
> I saw you can save using "Save" and "Save as new version". Is the "Save as new version" there to be compatible with version 1.3.0 alpha 1 because this version will use a new fiel format?

Nope, the ”save as new option” is just ”save as”, ie you can make a new copy with a different name. That's gt nothing to do with 1.3 alpha. 
Also, 1.2 mmps are backward compatible with 1.3 but some ladspa plugins may fail.

**Comment by opensourcefree** [comment]
> > I saw you can save using "Save" and "Save as new version". Is the "Save as new version" there to be compatible with version 1.3.0 alpha 1 because this version will use a new fiel format?
> 
> Nope, the ”save as new option” is just ”save as”, ie you can make a new copy with a different name. That's gt nothing to do with 1.3 alpha. Also, 1.2 mmps are backward compatible with 1.3 but some ladspa plugins may fail.

Why is "save as new version" existing if "save as" is the same AND present in the same menu?

**Comment by Monospace-V** [comment]
It's not the same. Save-as makes you change the name, allows you to save as a different file. Save As New simply creates the file with same name but with an automatic additional number at the end to show version.

**Comment by opensourcefree** [comment]
> I cannot answer your second question as I use Windows.

I now understand LMMS behaves differently considering VSTs in Windows/Linux/Mac.
Can you tell me the answer for Windows to this question?
"Can VeSTige use 64 bit VSTs or only 32 bit VSTs on Windows?"

Does anybody know the answer for Linux? I think you can't use VSTs made for Windows in Linux or am I wrong?

**Comment by Spekular** [comment]
Closing as this is a support request. FWIW it will still be possible to post replies to the thread, but for future questions I recommend using the #support channel on Discord.

**Comment by Monospace-V** [comment]
> I now understand LMMS behaves differently considering VSTs in Windows/Linux/Mac. Can you tell me the answer for Windows to this question? "Can VeSTige use 64 bit VSTs or only 32 bit VSTs on Windows?"

If your operating system is 64-bit, VeSTige can use both 64-bit and 32-bit VSTs.
Alternative to #support on discord, there's also https://lmms.io/forum/  if you need help. Though there are more active people on discord.
