### ISSUE TITLE
Notes is barely visible if the Track color is light-colored

### ISSUE THREAD

**Issue by SatyrDiamond** [LMMS/lmms#6526]
maybe make the notes black or dark-gray if the track color is light-colored
![2022-09-01_04-06](https://user-images.githubusercontent.com/109001272/193566824-ed09af8b-89bf-4f66-b1cf-491cbe5bfd9e.png)

**Comment by musikBear** [comment]
I remember this from an other ticket, but find it ..i cant.
Since it is _user_ that has chosen to have very bright clip-colors, this could be solved with a _user_-toggle for clip-names. There are no reason for a RGB based logic for the name -imo

**Comment by zonkmachine** [comment]
Maybe allow changing color for the notes. You could also have an 'xor' function to change the note color if they are too close to that of the track.

**Comment by allejok96** [comment]
+1 for automatic dark on light background.

For anyone interested in fixing this, here is the line that decides [color](https://doc.qt.io/qt-5/qcolor.html#details) for notes:
https://github.com/LMMS/lmms/blob/a57265cf8dad3c341793e87177620b1531589941/src/gui/clips/MidiClipView.cpp#L526

---

And - this is not really relevant for this issue - [this line in the header file](https://github.com/LMMS/lmms/blob/a57265cf8dad3c341793e87177620b1531589941/include/MidiClipView.h#L48) creates a setter and getter function that is called by Qt when the theme is loaded. So `setNoteFillColor()` is called with the value specified in `style.css`.

**Comment by danik292** [comment]
@SatyrDiamond Its default or classics theme.
