### ISSUE TITLE
feature request: restore VSTs/samples

### ISSUE THREAD

**Issue by opensourcefree** [LMMS/lmms#6528]
Hi

Many files on the sharing platform don't have the VSTs and samples included. Maybe this is for copyright reasons?

I would like to request a feature that makes it possible to share LMMS files including the VSTs and samples so they load on the destination PC, on which the file was not created.

If you open this file for example: 

https://lmms.io/lsp/?action=show&file=17604

You get this message:

![afbeelding](https://user-images.githubusercontent.com/114779488/193687366-c9fc1f1e-ec0d-4801-bf7c-b016040197a1.png)

What is the current way to restore those VSTs/samples (if you have the original files) on the destination PC, on which the file was not created?
Do we need to re-create the file paths exactly the same as on the source PC on which the file was created and copy the original files in those file paths (for VSTs and samples)? That seems not to be a very cross-platform way. For example: how to go from a windows file path to a linux file path?

I don't know how this feature can be made exactly but maybe there can be made "VST" and "samples" subfolders in the folder where the LMMS file is saved in order to load the VSTs and samples from those subfolders on the destination PC. In this way the file paths are eliminated.

In this example you then have a folder in which the LMMS file "Closer - Chainsmokers.mmpz" is stored. 2 subfolders "VST" and "samples" of this folder are made. 

Inside the following contents:

- "VST" subfolder: files "Keyzone Classic.dll", "VSCO2 Cello Section - 64.dll" and "VSCO2 Violin Section - 64.dll" are stored

- "samples" subfolder: file "Warm 808 219_Tuned (C3).wav" is stored

In this way the file can be opened on any destination PC, regardless if it's windows/Linux/Mac and we don't need to use exact file path to recreate the VST/samples locations.

Thank you
Lisa

**Comment by qnebra** [comment]
Interesting idea, quite possible with 1.3 "project bundles" but radical NO to vst sharing. First some are really big, second it would put lmms into real legal mess.

**Comment by DomClark** [comment]
Two further concerns with bundling VSTs:
* Samples will work equally well on all machines, but the same does not go for VST plugins. Binaries are usually specific to a processor architecture and operating system, so a 64-bit Linux plugin would not work on 64-bit Windows, or 32-bit Linux, or ARM Linux, for example.
* We don't want to allow users to put executable code in project files, as this poses a significant malware risk.

For samples, you may be interested in the "project bundles" feature as qnebra mentioned. This is available in the alpha and nightly builds, and can be found as an option in the "Save As" dialog.

**Comment by opensourcefree** [comment]
Thx a lot!
I understand the VST idea is bad. 

Where can I download AppImage of nightly builds for Linux?

**Comment by Spekular** [comment]
Closing as fixed (samples) and wontfix (VSTs).

> Where can I download AppImage of nightly builds for Linux?

https://lmms.io/download

**Comment by opensourcefree** [comment]
The link you show only has the alpha version, not newer nightly builds in the form of AppImage
Maybe they are not available for non-developers?

**Comment by Spekular** [comment]
> The link you show only has the alpha version, not newer nightly builds in the form of AppImage Maybe they are not available for non-developers?

You'll notice the alpha version is listed under the "Nightly Versions" header. We do want to set up actual nightly builds available from lmms.io (hence the header), but because they're not set up yet the update process is currently manual (hence the version name). Either way the latest version available on lmms.io has the feature discussed here implemented.
