### ISSUE TITLE
Display project file version number

### ISSUE THREAD

**Issue by ghost** [LMMS/lmms#6530]
Hi

I would like to request a feature that tells, after opening a LMMS file, which LMMS version was used to save the file.
On the sharing platform this version is shown too. But we can't find this information in LMMS itself.

Why is this usefull?

- you can identify the LMMS version used to save the file and if there are some playback issues, you can go back to that LMMS version (we can't do this now, because for a file not uploaded to the sharing platform, we don't know the LMMS version...)

- you can save the file again (overwrite) so the very latest format is used. Especially useful for older files on the sharing platform. You can then verify in LMMS the latest format is used when you open the file again after overwriting it

Where can it be shown?

- Maybe in the right lower corner as a sort of small information box/status bar that shows the LMMS version (which was used to save the file) of the currently opened file in LMMS. There is no status bar at all now, so it could fit in there perfectly. Maybe even other information I don't think about now can be added there.

(maybe next to the LMMS version, some general song information can be shown like file size, number of tracks, ...)

Question: is there actually a way we can read the LMMS version used to save a file? I can't open a LMMS file with a text editor or don't know what to do with it. So I think it's not possible? How is the sharing platform reading the version number?
This is what my feature request's goal is :)

Thanks 
Lisa

**Comment by allejok96** [comment]
Thanks for a well written suggestion. As a matter of fact LMMS has this feature already. When you open a file with a different version number it displays a notification in the lower left corner. It only considers the first and second part of the version number, e.g. 1.2 -> 1.3 displays a notification, but 1.2.1 -> 1.2.2 does not.

AFAIK there is no way to see the version number of a project inside LMMS and it would be nice to have so I'm not marking this as duplicate. Related to #2557 though.

There *is* a way to extract version number from a project file if you can use the command line. This will convert a project to a format you can open in a text editor:

    lmms dump project.mmpz > project.mmp

**Comment by opensourcefree** [comment]
> There _is_ a way to extract version number from a project file if you can use the command line. This will convert a project to a format you can open in a text editor:
> 
> ```
> lmms dump project.mmpz > project.mmp
> ```

Thanks for answering all my questions.
I understand mmpz is a compressed form of mmp? What compression is used (ZIP, ...)?

**Comment by allejok96** [comment]
It's [essentially](https://doc.qt.io/qt-6/qbytearray.html#qCompress) raw [DEFLATE data](https://en.m.wikipedia.org/wiki/Deflate). Same compression used by gzip/zip but without all that extra stuff that makes possible to open with an ordinary program.

If you need more support or have more questions feel free to [join the LMMS discord](https://discord.gg/PruNxpG)

**Comment by allejok96** [comment]
OP is gone, let's move this into #2557 Improved Project Notes
