### ISSUE TITLE
Audio file transposed an octave down between versions

### ISSUE THREAD

**Issue by Monospace-V** [LMMS/lmms#6548]
### Bug Summary
On 1.2, I created a project, and have used an ogg file sample in the beat/bassline editor.
On 1.3, trying to edit the project, it is transposed up by an octave (the basenote is shifted down).

I can't seem to reproduce this with the same sample file, yet, but the bug is constant on the mmp file. So, I have attached the mmp file and mentioned where the problem is.

#### Steps to reproduce
1. Extract this zipped folder's files:
[Puppet3 AudioBug.zip](https://github.com/LMMS/lmms/files/9846844/Puppet3.AudioBug.zip)
Do not open the file yet, as you will get an error because the sample is missing.
2. In the mmp file within the zipped folder, there is a single sample file leading to C:/users/username/mp3 mb/Snap.ogg
In a plaintext editor, edit this path to lead wherever you have placed Snap.ogg from the zipped folder on your system. This step is **not needed**, though: you can just check the position of the basenote with your eyes as it is seen even there. This is simply if you want to hear the difference.
3. Save it, and open in LMMS 1.2. In the B/B editor, check the sound of the snap by clicking the preview space, or play back a b/b with the snap used on a step. Alternatively, look at the position of the basenote on the Snap in the AudioFileProcessor (See Screenshots).
![image](https://user-images.githubusercontent.com/76674645/197399836-644bc6ab-e8e0-4b89-8033-6f178612b3c7.png)
4. Now open it on LMMS 1.3 alpha and do the same.
5. Hear difference.

I cannot yet reproduce this on a blank slate. But it is reproducible within this file.

#### Expected behavior
They sound the same

#### Actual behavior
In 1.3, basenote is transposed an octave down so we hear file an octave up.

#### Screenshot
![image](https://user-images.githubusercontent.com/76674645/197399404-ad27d3d4-ec90-40a2-a766-0efa8ffe1720.png)
A5 vs A4.

#### Affected LMMS versions
1.2.0/1.2.2 -> 1.3 alpha

**Comment by Monospace-V** [comment]
It is possible this may have something to do with my automating the basenote. If https://github.com/LMMS/lmms/pull/5522 affects AFP files too, then this makes sense. I will test further and get back tomorrow if I can. I do not know if the PR has considered automation of basenote.

**Comment by he29-net** [comment]
Oof, getting backward compatibility right is hard... I think you are right and the problem is that I did not consider automation in the upgrade routine for extended MIDI range (`DataFile::upgrade_extendedNoteRange()`).

I'm not familiar with automation internals, so I'm not sure when and how I can fix it, but I'll try to look at it by the end of the year. Hopefully 1.3.0 isn't out by then. :)

**Comment by he29-net** [comment]
@michaelgregorius Thanks for the fix. I started looking into it some time ago, ran into unrelated build issues, and then completely forgot about it. I have some notes about potential edge cases etc., so I'll check if they are relevant and bring it up on the PR page if needed.

**Comment by michaelgregorius** [comment]
Fixed with pull request #6725.
