### ISSUE TITLE
Song-editor timeline instability

### ISSUE THREAD

**Issue by Ivansstyle** [LMMS/lmms#6551]
I have not found a similar issue, however there are some issues regarding positioning of a play bar in Bassline editor view. 

### Bug Summary
Song-editor playbar becomes misaligned with the sequence, beginning of the first bar falls behind the track label. 
https://user-images.githubusercontent.com/15091484/198389961-507c2d51-4442-48c5-b29c-7589457b5669.mp4

Due to this bug some of the playbar is behind track labels. Midi clips, however, are displayed in correct locations relative to the track labels. While track-clips are being displayed in correct locations, when the playbar hits the clips, clips do not play. Clips play though when playbar hits empty spots, which are equally distant from actual clips by the distance the playbar is misaligned.

#### Steps to reproduce
This issue appeared after changing Audio Interface settings. 
After reloading the project issue disappeared, however the playback was broken. 1 second of audio took 10 seconds to play. 

#### Expected behavior
Playbar moves after the track label and numbered accordingly. The clips are played when under the playbar. 

#### Actual behavior
Playbar is misaligned, clips are played not when playbar is over them. 

#### Screenshot
![playbar_overlayed](https://user-images.githubusercontent.com/15091484/198390489-12122cf0-03bc-441a-8f31-21d60e934f82.png)

#### Affected LMMS versions
1.3.0-alpha.1.102+g89fc6c960 on Windows 11

No logs available.

**Comment by allejok96** [comment]
Sounds like two different issues. From the screenshot it looks like you've enabled compact track labels, but there is a lot of gray space to the right that shouldn't be there. The sound issue is probably related to audio interface settings/drivers...

You say the issue with the timeline disappeared. Can you make it come back by changing the track label settings? (I can't reproduce this on the same version on Linux). Can you make the audio work again by changing the audio interface setting? What do you have it set to when it works/doesn't work?

**Comment by musikBear** [comment]
Do you use a theme?
The gif just show 'artistic' blur. When you park playhead, the position is precise, when it moves, there is some 'blur', i believe it is intended

**Comment by Ivansstyle** [comment]
@allejok96 I will try to reproduce the issue and update you with the steps to reproduce. Interistingly enough, right now I can not even start the software. I have tried reinstalling, running from console, but I have no output or anything. I have another version I have build myself with cmake on VS compiler that works fine, I wonder if they can interfere in any way. The issue does not appear to happen in the built version. 
@musikBear no, I am not using a theme. The problem is not with the gif and the blur. The problem is after this issue appeared, the playhead position did not correspond to the clip position on the timeline. If you take a look a the screenshot, the playhead is well before the start of the timeline, and clips are drawn relative to the timeline bar. So there is a misalignement between the actual timeline drawn and playhead with playhead timeline section. I believe this could be caused because timeline and playhead drawing are done by 2 different modules, and it seems that X position reporting can become messed, especially if playhead X=0 is taken from one widget, but clip X position is taken from its own widget. On the screenshot, the clip is drawn on bar 13, while was played on bar 3. 

I will be trying to reproduce this issue and will provide details on how to reproduce. I also could not find where does LMMS save logs, can anyone point me please?
