### ISSUE TITLE
Colored BB TCOs in 1.2 show as uncoloured in 1.3

### ISSUE THREAD

**Issue by Monospace-V** [LMMS/lmms#6555]
### Bug Summary
A 1.2 project with coloured TCOs, the colour is not shown on 1.3.
(Corresponding forum post [here](https://lmms.io/forum/viewtopic.php?t=35799). I'm surprised this hasn't been noticed...)

#### Steps to reproduce
Create a project in LMMS 1.2 and color the Beat/Bassline TCOs through the right click context menu. Save.
Open this project in 1.3.
Colours are not showing. (They show if reopening the project in 1.2, though.)

#### Expected behavior
Colours are retained.

#### Actual behavior
Colours are lost.

#### Screenshot
![image](https://user-images.githubusercontent.com/76674645/198912645-5fc6e8a5-12c4-4a75-acc8-ccded71c4bac.png)
![image](https://user-images.githubusercontent.com/76674645/198912789-59198781-a541-41e7-9f41-0694055b20fa.png)

#### Affected LMMS versions
1.2.* -> 1.3 alpha

PS: In addition to this, it would be useful if LMMS automatically coded the entire track the same colour, if most of the BB TCOs were already that colour, if imported from 1.2. Or if all BB clips made on a specific BB were the same colour as the most recent clip placed on that BB. This makes placing BB TCOs of the same colour easier.
But if this is fixed first.

**Comment by PhysSong** [comment]
Confirmed. Prior to #5573, colors was loaded/saved using [`QColor::rgb`](https://doc.qt.io/qt-5/qcolor.html#rgb). #5573 changed it to use `QColor::name()` and broke compatibility.

**Comment by messmerd** [comment]
I can try working on this one this weekend.

**Comment by PhysSong** [comment]
Fixed in #6563.
