### ISSUE TITLE
Linux: first time use help

### ISSUE THREAD

**Issue by linuxsynth** [LMMS/lmms#6559]
Hi everybody,

First, thanks for all the work on this amazing DAW!

I'm a Linux beginner, and I use Ubuntu.

I run it using the AppImage for Linux

I have installed this free synth VST, called Surge.

https://surge-synthesizer.github.io/downloads

I installed it using the file surge-xt-linux-x64-1.1.2.deb

I'm now stuck because:
- I don't know where the VST files of Surge are copied to
- I don't know how to use the VST files of Surge in LMMS.

I hope somebody can help.

**Comment by linuxsynth** [comment]
So basically my question is: how to use Linux VSTs when using LMMS AppImage on Linux?
If I found the folder where the files are copied (in my example, Surge), what to do in LMMS to load the VST?

**Comment by rola22** [comment]
Hello.
You can load VST and LV2 plugins using Carla.
I believe that if you install Carla on your computer it will show up in plugin list in LMMS (Carla Rack + Carla Patchbay).

If i remember, the easiest way to do it is to add KX Studio repository to your personal repositories and install Carla 
typing "sudo apt-get install carla" in terminal.

Please correct me if i am mistaken :)

**Comment by linuxsynth** [comment]
> You can load VST and LV2 plugins using Carla. I believe that if you install Carla on your computer it will show up in plugin list in LMMS (Carla Rack + Carla Patchbay).

So LMMS can't load any linux plugins without Carla? Is this what you are saying?
Because Surge has a native Linux version (see website), so it are not windows VST files.

**Comment by rola22** [comment]
> So LMMS can't load any linux plugins without Carla? Is this what you are saying?

Unfortunately yes. LMMS does not support native Linux VST right now.

**Comment by linuxsynth** [comment]
> > So LMMS can't load any linux plugins without Carla? Is this what you are saying?
> 
> Unfortunately yes. LMMS does not support native Linux VST right now.

Oh no!
This is actually a bit funny since LMMS was STARTED on linux :)
Are there plans to add this?

**Comment by musikBear** [comment]
> > > So LMMS can't load any linux plugins without Carla? Is this what you are saying?
> > 
> > 
> > Unfortunately yes. LMMS does not support native Linux VST right now.
> 
> Oh no! This is actually a bit funny since LMMS was STARTED on linux :) Are there plans to add this?

.so is coming.
You need WINE and then you can use any win-VST2
This is however not the fora for help-requests!
Go here
https://lmms.io/forum
Make an account, and ask for support!
Or
Make an account on Discord
https://discordapp.com/invite/5kSc32Z
Not here!

**Comment by allejok96** [comment]
`.so` support exists if you build from source or download any of the builds here on GitHub: Click on the Actions tab, then click on any build with a ✅ and scroll down, there you have an AppImage. Those are nightly builds so they may have some undiscovered bugs.

Note that you must also select `.so` in the Vestige file browser to see the Linux plugins.

**Comment by linuxsynth** [comment]
Hi

Thank you so much but I can't download it. See screenshot. Where to click to download, because I don't see any links?

![afbeelding](https://user-images.githubusercontent.com/117386726/200133387-fe3b1df0-eae6-432d-9c38-746bff3ef80e.png)

**Comment by qnebra** [comment]
On "linux"

**Comment by allejok96** [comment]
> I don't know where the VST files of Surge are copied to

If you right click on the deb package and select Extract or open with Archive manager or something like that you should be able to see the contents. Or you could open a terminal and type

    dpkg -L surge-xt-linux

**Comment by linuxsynth** [comment]
I DONT USE THIS SHIT SOFTWARE ANYMORE

NOTHING WORKS

LINUX SUCKS TOO

FUCK YOU LOSERS
