### ISSUE TITLE
RemoteVSTPlugin instances left behind on crash

### ISSUE THREAD

**Issue by TorutheRedFox** [LMMS/lmms#6562]
### Bug Summary
RemoteVSTPlugin32.exe and RemoteVSTPlugin64.exe instances don't get terminated in the event of a crash

#### Steps to reproduce
Crash LMMS in literally any way with VSTs loaded in VeSTige, that's it.

#### Expected behavior
RemoteVSTPlugin32.exe and RemoteVSTPlugin64.exe instances get terminated alongside LMMS itself upon a crash

#### Actual behavior
RemoteVSTPlugin32.exe and RemoteVSTPlugin64.exe instances have to be manually terminated

#### Affected LMMS versions
LMMS 1.3.0-alpha.1.102+g89fc7c960

**Comment by DomClark** [comment]
Thanks for the clear bug report! This was fixed in #6366, so should work properly in the next release.
