### ISSUE TITLE
question: MIDI controller

### ISSUE THREAD

**Issue by tranzedude** [LMMS/lmms#6569]
Hi

I'm new to LMMS.
How to setup a midi controller?
And how to assign knobs or buttons of the controller to LMMS buttons?

**Comment by allejok96** [comment]
First make sure to connect your MIDI device before starting LMMS.

> To connect to a knob, right-click on it, select "Connect to controller", make sure MIDI controller and Auto Detect are lit up, then just move the mod wheel on your MIDI device.

https://docs.lmms.io/user-manual/4-production/4.5-using-midi

Hope that works for you.

[Our discord](https://lmms.io/chat) is also a good place for support questions and you'll get an answer much quicker.
