### ISSUE TITLE
request: enhance beat bassline editor

### ISSUE THREAD

**Issue by tranzedude** [LMMS/lmms#6575]
Hi

I would like to request a step sequencer as in FL Studio. See screenshot

![afbeelding](https://user-images.githubusercontent.com/118472172/204352070-c187fb5a-1eaa-4f28-aef4-59500b595c5e.png)

This would allow to make "patterns" that are building blocks for a song in the song editor.
See FL Studio for the workflow.

The big advantage is that we can make beats more easily this way and re-use patterns.
This allows for much faster song building and reduces the amount of work and errors in the song editor of LMMS.

**Comment by Veratil** [comment]
Might I point your attention towards the BB Editor: https://docs.lmms.io/user-manual/3-navigating-lmms/3.8

It's not entirely the same as the step sequencer, but it's close.

**Comment by tranzedude** [comment]
Yes, I know.
But my request was to add "patterns" to LMMS.

Also I think the BB editor is not so well designed.
Where is for example the indicator where it's currently playing?
This should definitely be added. In FL Studio a small "bar" is shown at the current position, see screenshot.

![afbeelding](https://user-images.githubusercontent.com/118472172/204394711-5cca34c7-9013-4a01-b4b8-40eeab466c0b.png)

I also want to request a feature to "fill each 2, 4 or 8 steps" in the BB editor. See screenshot

![afbeelding](https://user-images.githubusercontent.com/118472172/204395375-a8d1787a-aa0c-4df4-8375-871533b67f6c.png)

See kick, clap and hihat screenshot below for the result of "fill each 2, 4 or 8 steps". This could be very handy in BB editor too!

![afbeelding](https://user-images.githubusercontent.com/118472172/204395553-a412dce0-552e-46d1-a0a1-e1f50decf065.png)

**Comment by Veratil** [comment]
> But my request was to add "patterns" to LMMS.

That is what the BB Editor can do. They are patterns in a manner of speaking. We've actually renamed it to Pattern Editor. See #6284.

> Also I think the BB editor is not so well designed.

Quite a lot of people agree with you here. 😄

> Where is for example the indicator where it's currently playing?

There isn't one in the BB/Pattern Editor, we know it's lacking. We've discussed redesigns and even removing the BB/Pattern Editor in favor of something better, but nothing in set in stone at the moment.

**Comment by tranzedude** [comment]
> > But my request was to add "patterns" to LMMS.
> 
> That is what the BB Editor can do. They are patterns in a manner of speaking. We've actually renamed it to Pattern Editor. See #6284.

It can't save a pattern and use that pattern in the song editor as building blocks of your song (as FL Studio can do).
So I don't understand why you rename it. It doesn't have this feature...

**Comment by qnebra** [comment]
Well, lmms workflow is different than FL workflow. If someone wants FL workflow should use FL. Also I wouldn't be surprised if some elements of FL UI/UX are copyrighted by Image Line.

**Comment by qnebra** [comment]
About pattern management, it is done in Song Editor. Of course it didn't have list of patterns, but allows quick changes without altering every other pattern (I hate how it works in FL). In recent beta versions got vastly improved.

**Comment by Monospace-V** [comment]
The playhead has been requested in https://github.com/LMMS/lmms/issues/1195
The request for structured filling is an interesting idea.

**Comment by tranzedude** [comment]
> About pattern management, it is done in Song Editor. Of course it didn't have list of patterns, but allows quick changes without altering every other pattern (I hate how it works in FL). In recent beta versions got vastly improved.

I think you don't understand FL Studio: patterns allow for quick changes to just the ONLY pattern you want (and it's changed everywhere in the song). All other patterns stay the way they are of course.
That's exactly what I requested for LMMS.

**Comment by tranzedude** [comment]
> The request for structured filling is an interesting idea.

Yes, and it also could solve the not so well defined BB Editor now.
If a playhead is added + option to save a pattern + option to re-use patterns in the song editor, LMMS will be a ton faster to make songs with. BB Editor is a frustration for many users IMHO.

**Comment by Veratil** [comment]
> > About pattern management, it is done in Song Editor. Of course it didn't have list of patterns, but allows quick changes without altering every other pattern (I hate how it works in FL). In recent beta versions got vastly improved.
> 
> I think you don't understand FL Studio: patterns allow for quick changes to just the ONLY pattern you want (and it's changed everywhere in the song). All other patterns stay the way they are of course. That's exactly what I requested for LMMS.

LMMS can already do this. You can create multiple patterns and edit the single pattern you want to without effecting the others.

**Comment by Spekular** [comment]
Closing unless there's a well defined change to be made that hasn't been mentioned in another issue. Here's a quick guide to the Pattern (BB) Editor:
- Every pattern in the pattern editor corresponds to a pattern track in the song editor, so new patterns can be added either editor
- Every pattern uses the same bank of instruments, so adding, changeing, or deleting a track in one pattern will affect all other patterns
- To make a pattern play in your song, click on an empty space in the pattern track (in the song editor) to create a pattern clip. Drag the right edge of the clip to resize it, which will loop the internal pattern for the duration of the pattern clip. Clips can also be truncated if you want the pattern to stop early, and naturally they can be moved or cloned like all other clips.

**Comment by mkruselj** [comment]
> Well, lmms workflow is different than FL workflow. If someone wants FL workflow should use FL. Also I wouldn't be surprised if some elements of FL UI/UX are copyrighted by Image Line.

I don't think you can copyright UX at all. You can prevent reuse of graphical assets but that's about it. Actual gestures and what they do, there's nothing to copyright there.

**Comment by qnebra** [comment]
> > Well, lmms workflow is different than FL workflow. If someone wants FL workflow should use FL. Also I wouldn't be surprised if some elements of FL UI/UX are copyrighted by Image Line.
> 
> I don't think you can copyright UX at all. You can prevent reuse of graphical assets but that's about it. Actual gestures and what they do, there's nothing to copyright there.

UX can be patented, like infamous example of "Swipe to unlock". Luckily nothing from FL UX was patented, but still there is no point to copy FL Studio UI. This bug issue had some interesting ideas and improvements.

**Comment by tranzedude** [comment]
> Closing unless there's a well defined change to be made that hasn't been mentioned in another issue. Here's a quick guide to the Pattern (BB) Editor:
> 
>     * Every pattern in the pattern editor corresponds to a pattern track in the song editor, so new patterns can be added either editor
> 
>     * Every pattern uses the same bank of instruments, so adding, changeing, or deleting a track in one pattern will affect all other patterns
> 
>     * To make a pattern play in your song, click on an empty space in the pattern track (in the song editor) to create a pattern clip. Drag the right edge of the clip to resize it, which will loop the internal pattern for the duration of the pattern clip. Clips can also be truncated if you want the pattern to stop early, and naturally they can be moved or cloned like all other clips.

You close this, but my opinion was to REDESIGN LMMS BB EDITOR so it works like FL STudio!
It seems you guys think LMMS's way is better. I don't think it is.
So I switch to FL Studio completely :)
