### ISSUE TITLE
request: VeSTige VST2/VST3 support

### ISSUE THREAD

**Issue by tranzedude** [LMMS/lmms#6576]
Hi

I would like to request VeSTige VST2/VST3 support

**Comment by Monospace-V** [comment]
VST2 already exists, and VST3 could be difficult but is planned at some point.
https://github.com/LMMS/lmms/issues/4715

**Comment by tranzedude** [comment]
So the VST2 are just the *.dll files I can choose in VeSTige?

**Comment by Monospace-V** [comment]
> So the VST2 are just the *.dll files I can choose in VeSTige?

Yes. Note that not all .dll files are VST2s. Some can be non-plugin, some can be important to plugin function but not the VST itself. dll is a common extension.
