### ISSUE TITLE
bug: VeSTige does not run Serum

### ISSUE THREAD

**Issue by tranzedude** [LMMS/lmms#6577]
### Bug Summary

LMMS does not load DLL file of Serum in VeSTige. Nothing happens after selecting the DLL file
https://xferrecords.com/products/serum

#### Steps to reproduce

1. Create new VeSTige track
2. Open Serum DLL file

#### Expected behavior

Serum should run

#### Actual behavior

Nothing happens

#### Affected LMMS versions

LMMS 1.2.2 on windows 10

**Comment by qnebra** [comment]
Are you sure you are using correct DLL file? Just asking to be sure.

**Comment by tranzedude** [comment]
Yes 100%, because the same DLL on the same PC runs in FL Studio.

**Comment by Spekular** [comment]
I've successfully run Serum on Windows 10 in both 1.2 and 1.3, can you provide any more details on what you're doing and the result? What I do when I need to create a new Serum instance:
- Create a VeSTige track
- Open the VeSTige window
- Press the folder icon to open the file browser
- Browse to and select Serum_x64.dll
- Press the "Show GUI" button in VeSTige to open the UI

Notably, you must use the *VST2* version of Serum, and you should set your plugin embedding to "No Embedding" to avoid UI bugs.

**Comment by tranzedude** [comment]
I only have 1 DLL, so there is no choice between VST2 or VST3. I also believe VST3 plugins are *.vst3 (not DLL).
On the website of Serum is written "64 bit VST2.4 , AU or AAX compatible host software."
So I think Serum is always VST2. There doesn't exist a VST3

So I only have 1 Serum_x64.dll which doesn't work :(
After doing all steps, nothing happens. Also embedding is turned off.

**Comment by qnebra** [comment]
Did you try serum.dll to be sure? It would be quite unlucky if you installed 32-bit version of lmms.

I just tried both 32 and 64 bit versions of Serum on LMMS 1.2.2 and it works fine.

**Comment by tranzedude** [comment]
I deleted Documents/lmms folder and reinstalled LMMS.
Now it finally works :)
