### ISSUE TITLE
Recording with Midi Keyboard not working

### ISSUE THREAD

**Issue by localhost-127** [LMMS/lmms#6592]
### Bug Summary
Impossible to record notes in PianoRoll when using a Midi Keyboard.
But KBAM inputs works alright.

System:  Ubuntu 20.04.3 LTS
Version: 1.3.0-alpha.1.239+gff5f092a6

#### Steps to reproduce

1. Connect Midi Keyboard to Instrument
2. Open PianoRoll
3. Press Record Button
4. Press Keys on Midi Keyboard
5. Observe that the timeline moves but notes are not recorded 

#### Expected behavior
Should be able to record via Midi Keyboard.

#### Actual behavior
Not Able to record via Midi Keyboard

#### Affected LMMS versions

Only Checked on Version: 1.3.0-alpha.1.239+gff5f092a6
Should Affect all the Versions after #6174 

#### Logs
As these logs suggest the callback event for recording with MidiKeyboard is not registered, because of these warning:
<details>
<summary>Click to expand</summary>
<pre>
QObject::connect: Cannot queue arguments of type 'lmms::Note'
(Make sure 'lmms::Note' is registered using qRegisterMetaType().)
QObject::connect: Cannot queue arguments of type 'lmms::Note'
(Make sure 'lmms::Note' is registered using qRegisterMetaType().)
</pre>
</details>

**Comment by musikBear** [comment]
Almost imposible to say why You have that issue. It not generaL.
bUT..
1) Did you connect in correct order?
Key-board must be running as lmms is opened
2) Check midi-cable

**Comment by anytizer** [comment]
Looks like under Win11 as well. alpha 1.237/239.
When I press the keyboard, it senses the key pressed and updates the piano's green color highlighter.
But slider keeps moving ahead, without picking up the note pressed.
