### ISSUE TITLE
'lmms' terminated by signal SIGSEGV 

### ISSUE THREAD

**Issue by ghost** [LMMS/lmms#6596]
### Bug Summary
Basically every time I try and open LMMS it crashes and this is the error I get 

#### Steps to reproduce
Install LMMS on Linux

#### Affected LMMS versions
Latest from pacman repos.

**Comment by PhysSong** [comment]
Possible duplicate of #6587.

**Comment by PhysSong** [comment]
@whatthemaggie Can you check if the workaround from #6587 work for you?
