### ISSUE TITLE
Sampling issues,

### ISSUE THREAD

**Issue by Mike-C** [LMMS/lmms#6597]
When inserting audio samples in ogg format, I think when I tried this, it was the same issue with wav format as well,
Audiofileprocessor (AFP) seems to play, as if the sample is of slightly different length, than what was the original one.

I suggest to try with longer samples to reproduce this.

#### Expected behavior
Sampled track length, and what is actually played in AFP should match.

#### Actual behavior
Sampled track is played in AFP, as if of different length, than what is the original length of it.

#### Affected LMMS versions
1.3.0-alpha.1

**Comment by musikBear** [comment]
> I suggest to try with _longer_ samples to reproduce this.
What precise length did the sample you used have?
Did the repeat dial include all of the sample?

**Comment by ahstro** [comment]
Just for safety: is this the thing where it changes length because of playing a different pitch than the pure sample?

**Comment by PhysSong** [comment]
@Mike-C Can you provide any reproducible example projects or setups?

**Comment by Mike-C** [comment]
> Just for safety: is this the thing where it changes length because of playing a different pitch than the pure sample?

it seems to be changing due to different octave, or a pitch, so possibly not a bug than, thanks for a hint
