### ISSUE TITLE
LMMS crashes when going left down piano in any instrument.

### ISSUE THREAD

**Issue by actuallyexeon** [LMMS/lmms#6608]
### Bug Summary
LMMS crashes when trying to reach the lowest note on the "piano" in the instrument tab.

#### Steps to reproduce
1. Open any instruments
2. Drag your mouse down the piano to the left, no scrolling.
3. 3. BOOM! Crash.

#### Expected behavior
Stays at the lowest note.

#### Actual behavior
Crashes

#### Affected LMMS versions

current master git

#### Logs
<details>
  <summary>Click to expand</summary>
<pre>
lilv_world_add_plugin(): warning: Duplicate plugin <https://github.com/werman/noise-suppression-for-voice>
lilv_world_add_plugin(): warning: ... found in file:///usr/lib/lv2/rnnoise_mono.lv2/
lilv_world_add_plugin(): warning: ... and      file:///usr/lib/lv2/rnnoise_stereo.lv2/ (ignored)
Lv2 plugin SUMMARY: 179 of 367  loaded in 1889 msecs.
For details about not loaded plugins, please set
  environment variable "LMMS_LV2_DEBUG" to nonempty.
Lv2 Plugins blacklisted: 67 of 367
  If you want to ignore the blacklist (dangerous!), please set
  environment variable "LMMS_IGNORE_BLACKLIST" to nonempty.
/usr/include/c++/12.2.0/array:217: constexpr const std::array<_Tp, _Nm>::value_type& std::array<_Tp, _Nm>::operator[](size_type) const [with _Tp = lmms::Piano::KeyTypes; long unsigned int _Nm = 12; const_reference = const lmms::Piano::KeyTypes&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
[1]    31786 IOT instruction  lmms
</pre>
</details>

**Comment by PhysSong** [comment]
Reproduced after manually adding `-DCMAKE_CXX_FLAGS="-D_GLIBCXX_ASSERTIONS=1"`.
In `PianoView::getKeyFromMouse`, In `PianoView::getKeyFromMouse`, `key_num` will be negative when dragging left beyond the lowest key. `Piano::isBlackKey`, however, doesn't handle negative values properly and `keycode` may become negative, which results in an out-of-bound read.

**Comment by musikBear** [comment]
FYI: 1.2.2 and previous did'nt 
Even with base-note in highest pos:
![image](https://user-images.githubusercontent.com/6662066/212133707-22dc2b66-3c58-4498-87fb-a9e252455ae1.png)
LMMS does not crash dragging mouse over piano-roll KB nor over instrument KB
My latest install of 1.3 neither
![image](https://user-images.githubusercontent.com/6662066/212134142-24571098-2204-4e1b-9cdb-ae6d67dbb430.png)

**Comment by luzpaz** [comment]
Is this issue still reproducible ?
