### ISSUE TITLE
Make automation read back to the last automation's clip last value

### ISSUE THREAD

**Issue by unfa** [LMMS/lmms#662]
In Ardour, no matter where you play your track, it's always updating all automated values according to what was the last value in the automation track.

I know Ardour doens't use "clips" and each track has only one assigned parameter, but I think this still could be implemented in LMMS, to some nice effect, and less work needed for extending the clips manually just to get a consistent output.

(Real Life) Example:

My track has a HighPass filter on the Master bus.
In the very beginning the filter is automated to sweep from 500 Hz to 0 Hz.
If you however play the begginning of the track (and the filter's knob is set to 500 Hz) and jump to the middle of the track (a few bars after the automation clip ends), the filter won't update to the last value of automation clip, it'll stay where the pleayhead has last read.

I'd like LMMS' automation to "look back" to the last value of the previeos clip, avery time the playhad is manually moved by the user, this way the automated values would be in sync to what you'd get when you render the track from start to finish.

**Comment by tresf** [comment]
If I'm reading this correctly, this is really a 2.0 type initiative which may change be changed by certain designs.  Bumping to 1.3 milestone for now.  Will likely bump again as this is isn't an easy fix.

**Comment by Lukas-W** [comment]
Fixed per #3382
