### ISSUE TITLE
Something like song/pattern mode from FL Studio

### ISSUE THREAD

**Issue by Gregaras** [LMMS/lmms#6621]
I guess in FL Studio you can choose whether you want to play the song or just a specific pattern, no matter which window is focused.

I wanted to suggest implementing similar modes in LMMS. Like one would be the original/normal mode and other would force the playback in Song Editor, no matter If Piano Roll or B&B Editor window is focused.

**Comment by musikBear** [comment]
> no matter which window is focused.

That is not possible with current architecture, but a complete new transport is 'planned'..
