### ISSUE TITLE
`Lv2Proc::run` crashes after `Lv2Proc::m_valid` has been unset

### ISSUE THREAD

**Issue by JohannesLorenz** [LMMS/lmms#6626]
### Bug Summary

On plugin instantiation failure, `Lv2Proc::m_valid` is being set to false. However, `Lv2Proc::run` does not evaluate `m_valid` and still calls `lilv_instance_run`, which causes undefined behavior, including crashes.

#### Steps to reproduce

* Startup LMMS with a new project
* Add the blop Sawtooth wave
* Export the song to WAV

#### Expected behavior

Export aborts, but LMMS does not crash, or at least it crashes with a descriptive error.

#### Actual behavior

LMMS can crash with an unclear "Segmentation fault".

#### Affected LMMS versions

All.

### Fix suggestions

Either evaluate `m_valid` in `Lv2Proc::run` or do not even create such plugins at all.

**Comment by DomClark** [comment]
> Do not even create such plugins at all

I think this is the best approach. If plugin instantiation fails, the constructor should throw an exception. Having a "valid" flag is considered a code smell for exactly this reason - it's easy to forget to check it. It's much easier to reason about code if every object is guaranteed to be valid. See https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rc-throw.
