### ISSUE TITLE
Taking Help of free AI assistance for coding our long awaited features

### ISSUE THREAD

**Issue by CaBachhav** [LMMS/lmms#6631]
# Please search the issue tracker for existing feature requests before submitting your own. Delete this line to confirm no similar request has been posted yet.

#### Mockup

Why not use freely Available Chat Bots etc for our help in coding for LMMS longly awaited features

**Comment by enp2s0** [comment]
This doesn't really seem like an LMMS issue. If a developer wants to take advantage of tools such as ChatGPT while developing features for LMMS they are more than welcome to (provided the licensing is good etc.).

We're all volunteers though so if you're asking "why don't you guys just use ChatGPT to give me <feature I really want>" then the answer is almost always that we're busy with life and trying our best. It's also not like an AI tool will be able to immediately understand the idiosyncrasies of the LMMS codebase and generate drop-in code, it still needs a human to write all the connector code between LMMS and whatever the bot spits out.

A bot could maybe pull off "write me a program that plays a metronome sound with a control for BPM and another for swing" but absolutely cannot do "add a swing feature to LMMS".

Feel free to use whatever you want when developing features though, it's not like your pull requests will be deleted if you use ChatGPT to help you write/refactor them. We're always looking for people who want to improve the program (and fix bugs!)

**Comment by PhysSong** [comment]
Thanks for the suggestion. Some of us are already using tools such as ChatGPT, though.
As @enp2s0 spotted, however, a tool is just a tool. While it can significantly accelerate the development process, it can't work completely like a human developer.

Since this isn't an issue itself, closing.

**Comment by CaBachhav** [comment]
Only Enemies Of LMMS would close these type of topics.
Previously I suggested that for lmms audio recording feature , developers should apopt codes from Qtractor and Non-timeline Applications. Adopt them and Modify them according LMMS' needs. But Similarly those topics were also closed.
