### ISSUE TITLE
Automation editor still displays mouse cursor frequency linear.

### ISSUE THREAD

**Issue by JohannesLorenz** [LMMS/lmms#664]
Even if the model is logarithmic, the mouse cursor displays a value as if handled linearly.

@tobydox  For fixing this, the AutomationEditor needs to know the AutomatableModel. Should it find that in AutomationPattern::m_objects (or in a similar place?), or should the model be passed from outside?

**Comment by Umcaruje** [comment]
Should we move this to the 1.3.0 milestone?

**Comment by JohannesLorenz** [comment]
I'm not sure why this has not been finished. Actually I planned to do it, but then @diizy said he'd do it. What exactly is missing and why should it not be coded for an earlier version?

**Comment by Umcaruje** [comment]
>What exactly is missing and why should it not be coded for an earlier version?

@diizy hasn't been around the project for a while, and well no work has been done concerning this issue. We're short on devs, so if you would like to work on it, that would be really appreciated. If you want to work on it sometime soon and if it's not a too complex patch, please target it at the `stable-1.2` branch :)

**Comment by JohannesLorenz** [comment]
It could be confirmed that both mentioned issues (cursor tooltip in the automation editor and knob tooltip) are *not* present in the stable-1.2 branch (for whatever reason).

This bug is solved.
