### ISSUE TITLE
"Unable to set geometry" in Tempo and Time Signature

### ISSUE THREAD

**Issue by anytizer** [LMMS/lmms#6641]
Steps to reproduce:
 - using Visual Studio, open the project in debug mode.
 - Double-Click on Tempo or Time Signature changing area of LMMS.

You will see messages similar to:

-- when double clicked on Tempo:
```
QWindowsWindow::setGeometry: Unable to set geometry 120x30+1156+593 (frame: 136x69+1148+562) on QWidgetWindow/"QInputDialogClassWindow" on "\\.\DISPLAY1". Resulting geometry: 249x87+1156+593 (frame: 265x126+1148+562) margins: 8, 31, 8, 8 minimum size: 249x87 maximum size: 524287x87 MINMAXINFO maxSize=0,0 maxpos=0,0 mintrack=265,126 maxtrack=524303,126)
```

-- when double clicked on Time Signature:
```
QWindowsWindow::setGeometry: Unable to set geometry 120x30+1162+593 (frame: 136x69+1154+562) on QWidgetWindow/"QInputDialogClassWindow" on "\\.\DISPLAY1". Resulting geometry: 237x87+1162+593 (frame: 253x126+1154+562) margins: 8, 31, 8, 8 minimum size: 237x87 maximum size: 524287x87 MINMAXINFO maxSize=0,0 maxpos=0,0 mintrack=253,126 maxtrack=524303,126)
```

Effect: Nothing. Just an extra debug message seen.

Probably the calculated space around the number-images are not fitting exactly in the display area with the given margins.

![image](https://user-images.githubusercontent.com/5563341/218244525-56d24040-7b9e-4a5b-badb-ba965ace2e65.png)

**Comment by superpaik** [comment]
It affects all popups (QInputDialog::getXXX) Apparently this is derived from a bug in Qt (for windows) --> [link](https://stackoverflow.com/questions/54307407/why-am-i-getting-qwindowswindowsetgeometry-unable-to-set-geometry-warning-wit)
There is a workaround: adding "Qt::MSWindowsFixedSizeDialogHint" as a windowflag as last parameter in the call --> [link](https://forum.freecad.org/viewtopic.php?t=52938)
For instance:
new_val = QInputDialog::getInt(this, "Piano roll: note velocity",	tr( "Please enter a new value between %1 and %2:" ).arg( MinVolume ).arg( MaxVolume ),(*nv)[0]->getVolume(),MinVolume, MaxVolume, 1, &ok );
becomes
new_val = QInputDialog::getInt(this, "Piano roll: note velocity",	tr( "Please enter a new value between %1 and %2:" ).arg( MinVolume ).arg( MaxVolume ),(*nv)[0]->getVolume(),MinVolume, MaxVolume, 1, &ok, Qt::MSWindowsFixedSizeDialogHint );

It works ok on windows, but I don't know if this works for linux or mac though, and I don't have the tools to test it.
Maybe some else can give it a look.

**Comment by PhysSong** [comment]
Related: https://stackoverflow.com/q/54307407
I think we can safely ignore the message.
