### ISSUE TITLE
High CPU usage with multiple muted midi tracks

### ISSUE THREAD

**Issue by teymuri** [LMMS/lmms#6643]
I see that the CPU usage is pretty high when I have multiple (possibly _heavy_ ones with lots of note on-offs and timely very tight) midi tracks, all set to mute and then I have a single harmless track set to solo. Does lmms still process tracks which are set to mute? Wouldn't it be better to only process active tracks?

**Comment by musikBear** [comment]
>  Does lmms still process tracks which are set to mute?

Yes!
Its unfortunate but cant be helped with current architecture.
I would recommend to slide heavy midi-blocks out of the 'replay-area' way out to the right. Remember to note where the blocks 'belongs' :p

**Comment by zonkmachine** [comment]
> Does lmms still process tracks which are set to mute? Wouldn't it be better to only process active tracks?

Yes. I think the choice was to have a snappy unmute action. Maybe this will be worked on in the future.
You can choose in the settings to let the system stop processing effect units when there is no input. See if that changes anything.
`Settings -> Performance -> Keep effects running even without input`
