### ISSUE TITLE
Overlapping Windows issue

### ISSUE THREAD

**Issue by mitvitaminen** [LMMS/lmms#6647]
Hi,
it might be a bug, could be a feature request too:
When moving windows in the main window you can move the window all the way up so that the main menu overlaps the window and you are unable to move it or change anything, which is behind the menu. If you could make the window snap to the smallest view coordinates that would be a blast. 

Steps2reproduce: Just move a window all the way up with drag and drop and let go when behind the menu
![Screenshot from 2023-02-16 22-38-31](https://user-images.githubusercontent.com/30018510/219494234-8279cb92-901b-4855-8336-623d18610436.png)

**Comment by Veratil** [comment]
Scroll the main window up, and the titlebar will be visible again. 😄
