### ISSUE TITLE
Few feature requests for LMMS

### ISSUE THREAD

**Issue by babatunde3** [LMMS/lmms#6653]
New features that I would like to request for LMMS: Crossfade, pitch shifting, and time stretching (like ableton and reaper for example) Keyboard shortcuts for copying, pasting, and cutting, Grids for finer editing.

**Comment by RoxasKH** [comment]
Fading: under work see #5616
Pitch shifting is already there if you use audiofileprocessor, I can’t remember if it’s been added to sample tracks or not, maybe not
Time stretching is still missing, true, but it’s a very advanced feature 
Keyboard shortcuts are there, but you obviously need to select something to copy it with the shortcut, also you can do ctrl+drag to quickly create a copy of a pattern
In the alpha version you can now drag things more precisely setting the grid quantization, still no grid graphically appears but it’s there.

**Comment by allejok96** [comment]
Crossfade request added to #1471. The rest is duplicate #4877.
