### ISSUE TITLE
Left accordion panel title is not vertically aligned with icon

### ISSUE THREAD

**Issue by derMart** [LMMS/lmms#6660]
### Bug Summary

See title and screenshot:
![grafik](https://user-images.githubusercontent.com/1069456/222266756-6da2a32c-33ea-4b27-a720-50f9ffd78281.png)

Take a look at the "Instrument Plugins" title. It should be vertically in the middle of the icon to its left, but it is directly at the top of the panel without any margin.

#### Affected LMMS versions

LMMS 1.2.2 AppImage

**Comment by musikBear** [comment]
Is that before or after you rescaled?
as in
https://github.com/LMMS/lmms/issues/6659

**Comment by derMart** [comment]
does not matter, issue applies to both variants:
![grafik](https://user-images.githubusercontent.com/1069456/222484714-b63a887d-86fc-47a5-9ea0-0be3c962743b.png)

**Comment by brunosxs** [comment]
I dunno, it feels to me this is intentional as all the other accordions  have their titles vertically aligned to the top.
![image](https://user-images.githubusercontent.com/1557903/224519127-44009445-4a42-429a-b550-d3e688e600af.png)

![image](https://user-images.githubusercontent.com/1557903/224519144-698033fc-7d35-4aee-800c-a3ea60a168a6.png)
I do agree it is not visually pleasing... but is this a bug?

**Comment by derMart** [comment]
Yep, this problem applies to all accordion titles. Well in my world this would definitively be considered a bug ;-)
If somebody thinks differently consider it a feature request.

**Comment by Veratil** [comment]
Yeah I'd consider this a visual enhancement. It's not breaking anything, other than our hearts because it's not aligned properly 😁, so not considered a bug.

**Comment by brunosxs** [comment]
If I can get some guidance to where the actual QML or UI files are I can tackle this as I want to start helping the project.

**Comment by Veratil** [comment]
> If I can get some guidance to where the actual QML or UI files are I can tackle this as I want to start helping the project.

I believe this controls where the text is drawn: https://github.com/LMMS/lmms/blob/master/src/gui/SideBarWidget.cpp#L75

**Comment by superpaik** [comment]
How would you feel about not underlining the title as well? It increases readability and avoids confusion with the style of "links". As far as I have seen, there are no other underlined titles in the project.
Here is the image aligned and with and without underline, for both default and classic theme
![imagen](https://user-images.githubusercontent.com/68785450/225981282-39622d0c-0510-49cf-bdd3-1ff00446ec72.png)

**Comment by Unknownempire** [comment]
Hi, i am interested to work on this issue, kindly guide me as i am a beginner.

**Comment by MrTopom** [comment]
Does anyone is working on it? It could be a good start for me.

**Comment by superpaik** [comment]
@MrTopom  go for it. I have it half develop locally but not working on it right now. If you get stuck with the code, maybe I can help.

**Comment by MrTopom** [comment]
I just sent a PR (first of my life). I am ready for feedback :)

**Comment by zonkmachine** [comment]
> I have it half develop locally but not working on it right now.

Sorry, I missed your involvement above. I need more literal cues like 'I'm working on this'... ;)

**Comment by superpaik** [comment]
> > I have it half develop locally but not working on it right now.
> 
> Sorry, I missed your involvement above. I need more literal cues like 'I'm working on this'... ;)

No worries ;-)
