### ISSUE TITLE
Crash on startup: LSP LADSPA plugin

### ISSUE THREAD

**Issue by ohquait** [LMMS/lmms#6661]
#### Affected LMMS versions
1.3.0-alpha git pulled yesterday

#### Logs
<details>
  <summary>Click to expand</summary>
<pre>
$ lmms
lilv_plugin_load_ports_if_necessary(): error: Plugin <file:///usr/lib64/lv2/ingen.lv2/MonoInstrument.ttl> is missing port 2/4
lilv_plugin_load_ports_if_necessary(): error: Plugin <file:///usr/lib64/lv2/ingen.lv2/StereoInstrument.ttl> is missing port 2/6
lmms(_Z13signalHandleri+0x18)[0x527758]
/lib64/libc.so.6(+0x36920)[0x7f601ea65920]
/lib64/libm.so.6(+0x64bfd)[0x7f60200ccbfd]
/usr/lib64/ladspa/lsp-plugins-ladspa-1.2.3.so(+0x2ad60c)[0x7f5fdc4ad60c]
Segmentation fault
</pre>
</details>

Why wine is needed for VST build's?
i have VST3-SDK installed and other like Ardour or Muse can build against and use...

Please forgive me, if it'S not the place for this, but i can not find other issue/solution here.

also older versions affected now , so i have to rebuild LV2 and ingen ???

**Comment by PhysSong** [comment]
> Segmentation fault

I think crash is due to LSP LADSPA plugins, which might not be specific to LMMS.
> Why wine is needed for VST build's?

Because we mainly support Windows VSTs on Linux via Wine.

**Comment by ohquait** [comment]
exist a plane to support on developers to switch to VST3-SDK for VST-on-Linux with LMMS ?

**Comment by PhysSong** [comment]
> exist a plane to support on developers to switch to VST3-SDK for VST-on-Linux with LMMS ?

See #4715.
