### ISSUE TITLE
Lmms can't build vst on linux due to lack of libwine.so.1

### ISSUE THREAD

**Issue by plater** [LMMS/lmms#6672]
Wine have removed libwine.so.1 in version 8.3 as a result lmms can no longer build wine vst.
See https://bugs.winehq.org/show_bug.cgi?id=54635
#### Affected LMMS versions
Version 1.2.2

I've scanned the git logs but haven't found anything relating to this issue

**Comment by luzpaz** [comment]
Missing `linux` label

**Comment by PhysSong** [comment]
Should be fixed in `master` via a5dc3fee6a5c51065f268cb19f686284752e69da.
