### ISSUE TITLE
Add previous note onion skins

### ISSUE THREAD

**Issue by xfinitywebdev** [LMMS/lmms#6679]
Hi,
I notice something that could be added in a new update. I know you probably get this a lot, but being able to look at previous notes placed on the piano roll would be most simulating. I have always used LMMS ever since it came out and this update could be useful for a lot of users! Take this into consideration.

**Comment by qnebra** [comment]
Already fixed, as current "alpha" versions of lmms had Ghost Notes built in.

**Comment by xfinitywebdev** [comment]
> Already fixed, as current "alpha" versions of lmms had Ghost Notes built in.

thanks
