### ISSUE TITLE
Segmentation fault when instruments are connected through MIDI inputs/outputs

### ISSUE THREAD

**Issue by Gregaras** [LMMS/lmms#6682]
.

**Comment by Gregaras** [comment]
Commenting this line seems to get rid of the crashing problem, but notes won't immediately stop playing when song/clip is stopped:
https://github.com/LMMS/lmms/blob/9bcf63c5da3132c669af1f237d98770e766aaa6f/src/core/Song.cpp#L693

**Comment by messmerd** [comment]
@Gregaras Why did you delete this? This bug is still unfixed and in master currently.

**Comment by Gregaras** [comment]
Ok, I will restore it.

**Comment by michaelgregorius** [comment]
The problem occurs on [this line](https://github.com/LMMS/lmms/blob/master/src/tracks/InstrumentTrack.cpp#L363) and it might be a threading problem (at least it feels like one). It seems that two different threads access `m_notes`. 

I have changed the code as follows:
```
case MidiNoteOff:
{
	auto key = event.key();
	auto * nph = m_notes[key];
	if( nph != nullptr )
	{
		// do actual note off and remove internal reference to NotePlayHandle (which itself will
		// be deleted later automatically)
		Engine::audioEngine()->requestChangeInModel();
		m_notes[event.key()]->noteOff( offset );

		// ... Snip ... //
	}
	eventHandled = true;
	break;
}
```
At the time of the crash `nph` is not `nullptr`. However when `m_notes` is accessed all its fields are `nullptr`. So before entering the `if` condition `m_notes` holds a value that is not `nullptr` but then it is removed.

**Comment by luzpaz** [comment]
@michaelgregorius is there a PR for this yet ?

**Comment by michaelgregorius** [comment]
No, @luzpaz. I'll leave this to someone with more knowledge about the internals of the engine.

**Comment by OhiraKyou** [comment]
Encountering this crash on `lmms-1.3.0-alpha.1.955+5d5f319-linux-x86_64`

I pretty consistently get the crash after playing and stopping the song a few times and then clicking the file menu. When LMMS is ran from the terminal, it just prints "Segmentation fault" on crash.

## System Details

### Hardware

- **Hardware Model:**                              ASUSTeK Computer INC. P8P67 DELUXE
- **Memory:**                                      32.0 GiB
- **Processor:**                                   Intel® Core™ i5-2500K × 4
- **Graphics:**                                    AMD Radeon™ RX 560 Series

### Software

- **Firmware Version:**                            2001
- **OS Name:**                                     Fedora Linux 43 (Workstation Edition)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               49
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.18.13-200.fc43.x86_64
