### ISSUE TITLE
some features that should exist in LMMS

### ISSUE THREAD

**Issue by Small-Develop** [LMMS/lmms#6685]
It would be interesting if they support Clap and vst3 plugins as well as a mini host that allows you to connect effects and instruments as well as the image line Modular Minihost or Patcher

https://www.image-line.com/fl-studio-learning/fl-studio-online-manual/html/plugins/Patcher.htm
https://www.image-line.com/fl-studio-learning/fl-studio-online-manual/html/plugins/Minihost%20Modular.htm

also support to record audio with microphone

**Comment by messmerd** [comment]
Duplicate of #1297, #4715, and #6560.

Next time please check that someone else hasn't already opened an issue for the same feature request.
Also, please keep issues focused to a *single* feature request or bug report.

**Comment by zonkmachine** [comment]
> Duplicate of #1297, #4715, and #6560.

Closing as duplicate
