### ISSUE TITLE
Add the LMMS icon to the AppImage

### ISSUE THREAD

**Issue by applecuckoo** [LMMS/lmms#6695]
### Enhancement Summary
What the title says, have the LMMS logo as the AppImage icon instead of a generic icon.
Edit: I think this is done by just adding a [.DirIcon](https://docs.appimage.org/reference/appdir.html#general-description) file to the AppDir, I am just a user so I have no idea how the build process works.

#### Justification
Easier searching when someone has a folder full of AppImages.

**Comment by tresf** [comment]
PR opened via #6715 .  How do I know it works?  Download [here](https://github.com/tresf/lmms/releases/download/v1.3.0-alpha/lmms-1.3.0-alpha.1.290+gd551938cb-linux-x86_64.AppImage).

**Comment by applecuckoo** [comment]
What distro do you use? Try downloading one of [these](https://github.com/Ultimaker/Cura/releases/tag/5.3.1) Ultimaker Cura AppImages and check if you see the Cura logo. If you do see the logo, then you should be able to do the troubleshooting on your end. Maybe you should try making .DirIcon into a symlink of lmms.png, that's what most AppImages with icons seem to be doing.

**Comment by tresf** [comment]
> What distro do you use? 

I built the installer on Ubuntu 18.04 and the icon didn't display.

I linked an installer `.AppImage` in my previous comment, did it work?

Whether it's a file or a symlink shouldn't matter, I wouldn't think.

**Comment by applecuckoo** [comment]
@tresf The linked appimage didn't work, the icon didn't show up, see below:
![Screenshot from 2023-05-22 18-59-01](https://github.com/LMMS/lmms/assets/113647417/c76d52e3-4ec8-4827-970c-78dbeae3d1ed)

**Comment by tresf** [comment]
> Edit: I think this is done by just adding a [.DirIcon](https://docs.appimage.org/reference/appdir.html#general-description) file to the AppDir, I am just a user so I have no idea how the build process works.

I think this assumption was false, quoting:

> These four types of entries MUST be contained in the AppDir to conform to this specification.

What's confusing is the `.DirIcon` says it must be a PNG, but the `myapp.<icon ext>` says it can be an SVG, but then they say this is usually a symlink to `.DirIcon`.  I don't really understand this all, but I'll examine Cura and copy how they do it.

**Comment by tresf** [comment]
> How do I know it works? 

@applecuckoo I would still be interested in an answer to this question, Ubuntu 20.04 doesn't show an icon.

<img width="500" alt="image" src="https://github.com/LMMS/lmms/assets/6345473/a9bd072c-0ce8-47b6-8690-b450fb535b94">

**Comment by tresf** [comment]
>  Maybe you should try making .DirIcon into a symlink of lmms.png, that's what most AppImages with icons seem to be doing.

[AppImageKit's own CI script uses a physical file](https://github.com/AppImage/AppImageKit/blob/701b711f42250584b65a88f6427006b1d160164d/ci/build-appdir.sh#L51), so I don't think that's needed.  Oddly, Cura doesn't name their icon `myapp.png` as the documentation states, but instead calls it `cura-icon.png`, so this standard seem to be loosely followed.

I'm not sure where your OS is generating this icon from, but the pull request places us in compliance with the standard, please see the extracted file:

<img width="704" alt="image" src="https://github.com/LMMS/lmms/assets/6345473/cba423a3-563f-4028-9cb0-0bbe19c8b915">

**Comment by applecuckoo** [comment]
@tresf Hmm... I don't know any other ways to see the AppImage icon. I use Linux Mint which displays AppImage icons by default, so I didn't realise that Ubuntu doesn't display the icon. I have no idea how Linux Mint grabs the icon, my guess is using [appimaged](https://github.com/probonopd/go-appimage/blob/master/src/appimaged/README.md) or something like that. I'll ping @probonopd for his AppImage advice here.

**Comment by tresf** [comment]
> I use Linux Mint which displays AppImage icons by default

Can you please provide the version so I can use it for unit testing?

**Comment by applecuckoo** [comment]
@tresf Sure - it's 21.1 Vera

**Comment by tresf** [comment]
> @tresf Sure - it's 21.1 Vera

They offer three editions.  Which one?

**Comment by tresf** [comment]
> > @tresf Sure - it's 21.1 Vera
> 
> They offer three editions. Which one?

Disregard,  Cinnamon seems to work for unit testing.

<img width="623" alt="image" src="https://github.com/LMMS/lmms/assets/6345473/0af1936e-401a-4a79-90d0-8c1345c8dbac">

**Comment by tresf** [comment]
@applecuckoo new file for testing [here](https://github.com/tresf/lmms/releases/download/v1.3.0-alpha/lmms-1.3.0-alpha.1.291+g65efb3f81-linux-x86_64.AppImage).  I did switched the icon to a symlink as well as added some version information to the desktop shortcut.  I'm not sure why, but it seems to fix the icon.

In my tests, the Downloads folder kept caching the blank icon, so I had to rename the download and rename it back to get the icon to show up.  The Desktop folder didn't require this workaround.

Please confirm it works for you and  I'll merge #6715.

In regards to the caching bug, if it reproduces for you, please file a bug report upstream.

<img width="500px" src="https://github.com/LMMS/lmms/assets/6345473/6109db3b-6f1c-4bc5-930e-67ef1f18e369"/>

**Comment by applecuckoo** [comment]
I also use Cinnamon, for some reason the generic icon didn't get cached so that might be a one-off issue. Regardless, the icon works for me now, thanks for the fix!
