### ISSUE TITLE
Nach Benutzung von LMMS Alpha 1.3. kein zurück mehr zu 1.2.

### ISSUE THREAD

**Issue by huhbert** [LMMS/lmms#6709]
Wenn ich eine Datei aus der stabilen Version 1.2. in Alpha öffne und abspeichere, dann kann ich die selbe Datei nicht mehr in der stabilen Version 1.2. benutzen, da er dort auf einmal keine Plugins mehr findet. Das ist sehr ärgerlich weil es mich zwingt den Track weiterhin in der Alpha-Version von Lmms zu bearbeiten. Gibt es dazu bereits Abhilfe?

_Google Translate: 'When I import a file from the stable 1.2. in Alpha and save, then I can no longer use the same file in the stable version 1.2. use it because suddenly it can't find any more plugins there. This is very annoying because it forces me to keep editing the track in the alpha version of Lmms. Is there already a fix for this?'_

**Comment by zonkmachine** [comment]
When you open a project in a newer version of lmms there is an upgrade routine that solves incompatibilities. If you save the project it may be incompatible with older versions depending on what plugins and specific functions you have used. I don't think there is any plan for backward compatibility. I also don't think there should be. It's quite a task to manage the upgrade routines to newer versions already. I think the general idea opinion is that the latest 1.3 alpha is at least as stable as 1.2 and people don't seem to downgrade.

**Comment by huhbert** [comment]
Thank you very much for your quick answer. Then I will use the alpha version for all my projects.Kind regards.Am 15.05.23, 20:57 schrieb Oskar Wallgren ***@***.***>:

   
  When you open a project in a newer version of lmms there is an upgrade routine that solves incompatibilities. If you save the project it may be incompatible with older versions depending on what plugins and specific functions you have used. I don't think there is any plan for backward compatibility. I also don't think there should be. It's quite a task to manage the upgrade routines to newer versions already. I think the general idea opinion is that the latest 1.3 alpha is at least as stable as 1.2 and people don't seem to downgrade.

**Comment by Spekular** [comment]
To be pedantic, we have backwards compatibility, but not forward compatibility.
