### ISSUE TITLE
Can't run LMMS on Fedora 38

### ISSUE THREAD

**Issue by Lucifer25x** [LMMS/lmms#6710]
### Bug Summary
When I try to open LMMS (official DNF package) it gives segfault. And the flatpak version does this too (I don't know what the reason is)

#### Steps to reproduce
1. Open Fedora 38. 
2. Install LMMS using `sudo dnf in lmms` command, (in my case the `Carla` wasn't installed by default, so we should install it too using `sudo dnf in Carla Carla-vst Carla-devel` command.)
3. Run `lmms` command in terminal or open app using its shortcut

#### Expected behavior
App should open without problem.

#### Actual behavior
App gives me segfault:
```
Notice: could not set realtime priority.
[1]    6784 segmentation fault (core dumped)  lmms
```

#### Additional information
If there is no `~/Documents/lmms` directory created, the application asks me to create the LMMS directory and after this application crashes (after the first loading page is shown).

**Comment by PhysSong** [comment]
Can you try launching LMMS with GDB and get a backtrace, as documented in [here](https://github.com/LMMS/lmms/wiki/Debugging-LMMS#debugging-with-gdb-gnu-debugger)?

**Comment by Lucifer25x** [comment]
> Okay, it appears LMMS 1.2.2 is affected, but 1.3.0-alpha (current Git master, [d551938](https://github.com/LMMS/lmms/commit/d551938cbd3a7bad3e7859ab7abd1499d7326b3b)) is not, and it starts up correctly.

Thanks

**Comment by Lucifer25x** [comment]
I'm closing the issue, as newer versions aren't affected from this issue.
