### ISSUE TITLE
MIDI CC number display offset by 1

### ISSUE THREAD

**Issue by dj-pixus** [LMMS/lmms#6722]
In the "Connect to controller" window, control number is numbered 1-128 instead of the standard 0-127 range that is used everywhere else.
So far I have found exactly 1 place where 1-128 is used, that being LMMS. Even the CC Rack uses the 0-127 numbering, and there is literally no reason to offset the display, other than making it more confusing when connecting lmms to external stuff.

Here are some sources that use 0-127 numbering, in case you don't believe:
https://www.whippedcreamsounds.com/midi-cc-list/
https://anotherproducer.com/online-tools-for-musicians/midi-cc-list/
https://www.presetpatch.com/midi-cc-list.aspx
https://miditech.de/en//download/midistart-music-25-deu-eng/?tmstv=1685797845
https://www.bhphotovideo.com/lit_files/75904.pdf

**Comment by he29-net** [comment]
In some places, the MIDI specification actually recommends to count from 1 to 128, e.g.:
>It should be noted that the General MIDI system specifies sounds using program numbers 1
through 128. The MIDI Program Change message used to select these sounds uses an 8-bit
byte, which corresponds to decimal numbering from 0 through 127, to specify the desired
program number. Thus, to select GM sound number 10, the Glockenspiel, the Program Change
message will have a data byte with the decimal value 9.

But for Control Change messages, I don't see any such recommendation, and the specification refers to controller numbers as starting from 0 multiple times. So I would say you are right; LMMS should probably display 0 to 127.
