### ISSUE TITLE
Menu does not open after first right click in Gnome wayland

### ISSUE THREAD

**Issue by khoidauminh** [LMMS/lmms#6733]
### Bug Summary
In Gnome 44 (specifically mutter version 44.2), you cannot right-click properly in LMMS when running LMMS under Xwayland in the Wayland session.

#### Steps to reproduce
1. Enter Wayland session in Gnome.
2. Launch LMMS (under Xwayland).
3. Right-click on any knob/pattern a few times.

#### Expected behavior
Option menu pops up immediately.

#### Actual behavior
Unpredictable pattern of behaviors: Cursor blinks, menu flashes and disappears, menu pops up.
Attempts at fast right-clicking may result in a double left-click, most noticeably with the Sample tracks, where the file picker opens instead of the option menu. 

#### Video
[Reproducing the bug](https://drive.google.com/file/d/1-I3hhimpa4ByvFHUaeYZSOyqaz3UO3Zb/view?usp=sharing)

#### Affected LMMS versions
All AppImage versions, including alpha and nightly.

**Comment by luzpaz** [comment]
Needs `linux` label

**Comment by khoidauminh** [comment]
@luzpaz I can't add the label. Do I have to start a new one?

**Comment by khoidauminh** [comment]
Issue has been fixed via [merge request](https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/3194).
