### ISSUE TITLE
sample search function broken on most recent nightly (g7c6ade573)

### ISSUE THREAD

**Issue by SalutanisOrkonus** [LMMS/lmms#6734]
### Bug Summary
Searching in the samples tab only shows results in the currently selected folder and nothing else. No subfolders, and no other folders.
#### Steps to reproduce
Use the search function in the samples tab
#### Expected behavior
It shows results from everything in the samples folder
#### Actual behavior
Only shows results in the currently selected folder

#### Affected LMMS versions
1.3.0-alpha.1.302+g7c6ade573

**Comment by anytizer** [comment]
Did you try with "checked" mode of the user content / factory content option? Would you please share the portion of the screenshot, if still failing?

**Comment by SalutanisOrkonus** [comment]
If what you mean is those two options being on, they already were.

No folder selected
![image](https://github.com/LMMS/lmms/assets/65266122/c66fcfdf-ead0-469b-86f1-d09a6f2ab2a3)

Folder selected (1)
![image](https://github.com/LMMS/lmms/assets/65266122/6b6c9796-a9d5-4351-8dde-baf7907991b7)

Folder selected (2)
![image](https://github.com/LMMS/lmms/assets/65266122/6f278e92-d7fd-4f5f-a399-f2793b0852aa)
it seems folders that you previously slogged through the search for will show up afterwards (but still not their subfolders), but that doesn't exactly make anything helpful, if I have to dig for specific subfolders in order to get search results for them, searching is a bit redundant.

**Comment by Spekular** [comment]
Can you test a version before https://github.com/LMMS/lmms/pull/6721 was merged and see if it works?

**Comment by SalutanisOrkonus** [comment]
I don't know how to download older nightly versions, but I do know this did not happen in 89fc6c9	(2021-04-26/latest Alpha release)

**Comment by superpaik** [comment]
> Can you test a version before #6721 was merged and see if it works?

I had a previous version to that merge and works ok. Introducing that change makes it not work. So I'd say the error comes from that PR.

**Comment by Veratil** [comment]
@LostRobotMusic please look into this

**Comment by LostRobotMusic** [comment]
Right, the PR was merged way faster than I expected and I wound up finding this bug the next day.  I was hoping I could slide in a fix before any problems were caused, but LMMS's general code spaghetti has been making things difficult...

The current behavior has all sidebars behaving identically to the home folder sidebar, which isn't what we want.  I'm a bit confused by this, since this means setting non-directories as expanded somehow had some impact on the code's functionality.

**Comment by LostRobotMusic** [comment]
Oh, I see, I misunderstood a part of the code.  It only expands directories if they're within `expandedDirs` (so, if they're marked as already expanded).  This means it won't search any directories that haven't been expanded previously.
But expanding absolutely everything through brute force seems like the wrong move.  Is there a way we can search through these directories, without handing every individual file off to Qt to put into the tree?

**Comment by Veratil** [comment]
> Is there a way we can search through these directories, without handing every individual file off to Qt to put into the tree?

[QDirIterator](https://doc.qt.io/qt-6/qdiriterator.html) maybe? The iterator will return a QString which can be used for `.contains(substr)`.
