### ISSUE TITLE
libsdl needs to include version number when installing dependencies

### ISSUE THREAD

**Issue by constlo** [LMMS/lmms#6743]
Operating system: Pop_Os v22.04

When installing dependencies on Pop_Os, libsdl-dev needs to have a version number in order to start the installing process.
The Ubuntu page does not specify this, but it is visible on the terminal when installing. If this is intentional, please close this issue. Including the version number on the dependency list would be convenient, though.

Here is the installation according to https://github.com/LMMS/lmms/wiki/dependencies-ubuntu
![doesntwork1](https://github.com/LMMS/lmms/assets/79052688/fb4f8bae-83a3-43f9-9d6b-238789c571a9)

Including the version number will start the installation:
![corrected](https://github.com/LMMS/lmms/assets/79052688/2383ff4a-2524-4740-9017-8060b1c7f20b)

**Comment by DomClark** [comment]
The wiki is publicly editable, so feel free to make whatever corrections you feel are appropriate - they are greatly appreciated. It's worth noting that LMMS supports SDL2 as well, so you may wish to use that instead.
