### ISSUE TITLE
Issue installing on Ubuntu: "libsdl-dev"

### ISSUE THREAD

**Issue by angstyloop** [LMMS/lmms#6749]
### Bug Summary
Ubuntu compilation command fails on Ubuntu 22.04 with latest APT updates for a very small reason. The "libsdl-dev" dependency must be replaced with "libsdl1.2-dev".

#### Steps to reproduce
Follow the commands from [here](https://github.com/LMMS/lmms/wiki/dependencies-ubuntu)

`sudo apt install build-essential cmake libsndfile1-dev libfftw3-dev libvorbis-dev libogg-dev libmp3lame-dev libasound2-dev libjack-jackd2-dev libsamplerate0-dev libsdl-dev libstk0-dev stk libfluidsynth-dev portaudio19-dev libfltk1.3-dev libxinerama-dev libxft-dev libgig-dev git perl libxml2-utils libxml-perl liblist-moreutils-perl qtbase5-dev qtbase5-private-dev qttools5-dev-tools qttools5-dev libqt5x11extras5-dev libx11-xcb-dev libxcb-keysyms1-dev libxcb-util0-dev`

#### Expected behavior
Perfect installation

#### Actual behavior
Fail install on "libsdl-dev"
```
Package libsdl-dev is a virtual package provided by:
  libsdl1.2-dev 1.2.15+dfsg2-6
  libsdl1.2-compat-dev 1.2.52-3
You should explicitly select one to install.

E: Package 'libsdl-dev' has no installation candidate
```

#### Screenshot
![a](https://github.com/LMMS/lmms/assets/34935938/442cb202-de35-494b-98fe-285d0388ae2b)

#### Affected LMMS versions
latest source code instructions for Ubuntu
Ubunto 22.04 Jammy Jellyfish fresh install

#### Logs
The snippets above are output from the apt install command

**Comment by PhysSong** [comment]
See #6743.
