### ISSUE TITLE
LV2 help window - Issue on closing with the 'x' button

### ISSUE THREAD

**Issue by zonkmachine** [LMMS/lmms#6753]
### Bug Summary

LV2 plugins with help button/window is disrupted when the help window is closed with the builtin `[x]` button.

#### Steps to reproduce

* Open LV2 plugin. Either an instrument or an effect. Press `[Help]` (Open right corner, if the plugin has one which is not always the case). Help window opens.
* Close the help window by once more pressing the `[Help]` button. Help window closes. This works.
* Now open the help window once more and close it by pressing the top right `[x]` on the help window. Help window closes.
* Repeat opening the help window and this time it's:
    A - Broken, no text in there.
    B - You need to press one extra time to get the focus on the help button.
The window stays broken for this instance of the effect until lmms is restarted.

#### Affected LMMS versions
On master build since LV2 was introduced. At least since LV2-Options.

#### Screenshots

Help window opened.
![help2](https://github.com/LMMS/lmms/assets/6368949/3d587370-f9a3-4ac4-bd5c-1f29caf5f6ba)

Help window opened a second time after closing it with the `[x]` instead of the `[Help]` button.
![help3](https://github.com/LMMS/lmms/assets/6368949/b8a2d6b6-18fa-416f-80cd-ac6d62bac894)

**Comment by zonkmachine** [comment]
Also. If the help window is maximized it's not possible to close it again from within the open window. You need to open up the song window, reopen the lv2 plugin and then toggle the window with the help button.

**Comment by zonkmachine** [comment]
Another issue found.

* Start a default project
* Add an LV2 plugin with a help window and open the help window.
* Open another project or a new one altogether

The Lv2 plugin help window is still there and can be closed manually. It should have been destroyed when the new project were loaded.

**Comment by JohannesLorenz** [comment]
For now, solved all mentioned issues in a temporary branch (including the one from yesterday).

The last thing I am still unhappy about is the size of this window. I cannot find out how to let the window automatically have such a size that the contained `QLabel` fits. I might push the PR soon and move the question into that PR.
