### ISSUE TITLE
We need a 'Windows Dev-env for dummies' Tutorial

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#6754]
### Enhancement Summary
We need a 'Windows Dev-env for dummies' Tutorial

#### Justification
If it was made, there were more c++ coders that would participate in LMMS-project-dev.

#### Mockup
Proposed tutorial structure.
Folder-structure
A complete library tree with all the pre-install folders that will help making a successful development environment.

Visual-studio.
1) User has not installed VS
Step-by-step advice for witch components the environment needs and in what step of the VS installation the user needs to add the special components for a successful LMMS-environment. 

2) User has already VS installed, but need to extend the installation
step-by-step advice how to get to the necessary components and how to add them to the existing installation

QT
Where to get qT packs
Where to add them in the installation structure
How to make them executable in VS

VST-support
Where to get packs
Where to add them in the installation structure
How to make them executable in VS

Run
Witch cmds, cMake-file content, and placement in the folder-structure a successful RUN needs

Build
Witch cmds, cMake-file content, and placement in the folder-structure a successful Build for all supported platforms needs

I may have forgotten some step in this mockup? If so add it in logical succession in the commentary 

More in depth thoughts.
If one of the devs that on regular basis uses MS-Visual-Studio-Community-ed would write down step for step all the necessaryties for making a fully functional Windows dev-environment it would make more coders participate. It is especially all the libraries in connection to VS -where to find them, what versions is needed, what folder structure, witch DOT-Net, how to make qT functional etc.
In the mockup above i have attempted to outline the structure i feel would be logical for such a tutorial.
What are your thoughts?

**Comment by Veratil** [comment]
I followed the instructions [on the wiki](https://github.com/LMMS/lmms/wiki/dependencies-windows#windows-msvc) and set up my build environment with very few issues which I believe have been corrected since. What's wrong with the wiki page?

**Comment by Veratil** [comment]
> For starters, it for MSVS 20**19**

The instructions work with today's version as well, this just tells if you have an older version than 2019 the instructions may not be accurate and you're on your own.

> I am really advocating a guide for DUMMIES. C++ coders that does not have a clue about all the nicks and kringles of MSVS.

Simple things like "how to install X" I do not believe we should detail because the internet is already full of those types of instructions. We give the exact instructions needed to get things set up. If something is missing we'll add it, but I'm not aware of anything that's missing that is required to get a working build up and running.

> A guide that would make setting up the dev-environment completely transparent. That outdated wiki-page does not do that remotely.

I have to disagree, the wiki page allowed me to set it up just fine (twice actually). It's not outdated. It still works following the directions given.

---
To be clear, I'm not trying to dissuade against the idea, just trying to understand where you're coming from. The current wiki page has allowed multiple people to set up their environment within the past year with the only issue that I recall being Qt paths and CMake. Things that have been missing or needing to be updated have been.

I should ask, are you trying to set up a build environment on your own? If so, then please ask us for help if you get stuck. If you feel instructions are missing from the wiki then do feel free to add them, too.

**Comment by musikBear** [comment]
> Simple things like "how to install X" I do not believe we should detail because the internet is already full of those types of instructions

Those instructions are _generalized_, what i was thinking about was LMMS-environment _specific_ instructions.
But i feel a lack of enthusiasm for the idea :p -I may need to fumble my own way, and make notes of all that works, then put it together, and add it. ( My current C#-environment for windows-games-dlls should how ever not be compromised : |

**Comment by Veratil** [comment]
> Those instructions are _generalized_, what i was thinking about was LMMS-environment _specific_ instructions.

This is what I'm trying to say, the wiki is fairly specific to LMMS. It's not generalized.

> But i feel a lack of enthusiasm for the idea :p -I may need to fumble my own way, and make notes of all that works, then put it together, and add it.

Not lack of enthusiasm, lack of understanding. Many people have used the wiki to get their environment set up, and your issue is just saying "write something else". We don't need to write something else, we need to understand what are you getting stuck at so we can help you.

**Comment by superpaik** [comment]
A while ago someone created this group specifically for helping building LMMS on Windows. You might find something of interest, but it has not been active since last year. https://discord.com/channels/@me/923716339351318579  I don't know if is still active to join, though

**Comment by michaelgregorius** [comment]
Is cross compilation still supported? If it is it might be possible to create a Docker image with all the stuff that's needed for cross compilation to Windows. In that case interested users might "only" need to install Docker on their Windows machine to be able to build LMMS.

However, if I remember correctly I tried to do something like this some months ago and it did not work. So I guess cross compilation is not supported anymore?

Side note: I have created a `Dockerfile` that sets up everything to compile a Linux build. If there's some interest we might put it somewhere into the source tree.

**Comment by Veratil** [comment]
@superpaik that link doesn't work

> Is cross compilation still supported?

Cross can still be done, but we're trying to do native with MSVC. Slowly getting there. :)

> If it is it might be possible to create a Docker image with all the stuff that's needed for cross compilation to Windows.

This might not be a bad idea in general actually. Use mount points to mount the lmms dir and build from there. Doesn't pollute OS with build packages and dependencies.

**Comment by DomClark** [comment]
We already use Docker images in CI, including for MinGW builds. I've successfully used them for cross-compiling before.

**Comment by superpaik** [comment]
> @superpaik that link doesn't work
> 
Sorry. It was created by protocat (I don't know if he/she has a github user). Maybe he can share the correct link.

**Comment by michaelgregorius** [comment]
> We already use Docker images in CI, including for MinGW builds. I've successfully used them for cross-compiling before.

Are they available in the source tree or where can they be found?

**Comment by DomClark** [comment]
They're maintained at https://github.com/LMMS/lmms-ci-docker, and you can see which ones are currently in use at https://github.com/LMMS/lmms/blob/master/.github/workflows/build.yml under the `container` keys.

**Comment by michaelgregorius** [comment]
Thanks for the links, @DomClark!

It would be great if some `README.md` was added to that repository that describes how to use the images manually. This README could then be linked from the README of the LMMS repository.

**Comment by musikBear** [comment]
> They're maintained at https://github.com/LMMS/lmms-ci-docker, and you can see which ones are currently in use at https://github.com/LMMS/lmms/blob/master/.github/workflows/build.yml under the `container` keys.

This looks interesting!
I have no knowledge around this 'docker'-thing, but that is unimportant. It can be regarded a black-box of transparency, if it just does its thing and the result is a working environment. Of cause it looks a bit like getting a fish, and learning to fish would be more generally useful, but in this case digging for worms could be nicely avoided.
I am for it! 👍

**Comment by anytizer** [comment]
I created a gist a bit ago, following the LMMS wiki. I was able to compile 64bit fully with Visual Studio purely on Windows Machine -  [here](https://gist.github.com/anytizer/a674f2d24cd91dd2ffc510963e1a241c). May be useful, though no docker, no cross-compile? Just around several giga bits of downloads to setup the environment.

**Comment by musikBear** [comment]
> I created a gist a bit ago, following the LMMS wiki. I was able to compile 64bit fully with Visual Studio purely on Windows Machine - [here](https://gist.github.com/anytizer/a674f2d24cd91dd2ffc510963e1a241c). It may be useful, though I have not used docker, no cross-compile.

That is VERY good work!
It is detailed thoroughly written and has in depth description of what to do.
Excellent!
But it also shows me that i dont have HW in that league -at ALL, and also definitively not computer-science insight/ background remotely needed :P 
For me its back to making a new virtual-box, and a completely new Linux installation, followed by git-project-clone, and then hope it does not self-destruct as the last one

**Comment by Rossmaxx** [comment]
> I created a gist a bit ago, following the LMMS wiki. I was able to compile 64bit fully with Visual Studio purely on Windows Machine - here. It may be useful, though I have not used docker, no cross-compile.

looked into it. Good work but it's behind the wiki (see compiling using the command line. The rest haven't been updated). Perhaps try re doing the entire thing. Also you don't need the full Visual studio, you can do with MSVC build tools which is far lighter but comes with one drawback being that you don't have a gui (command line only). Anyways appreciate your efforts.

**Comment by ahogen** [comment]
You might consider mentioning, if not recommending, the [EWDK iso](https://learn.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk#enterprise-wdk-ewdk). That's a standalone MSVC toolchain, but without the full Visual Studio IDE. I can simply mount the ISO, run the cmd script to setup environment variables and then start developing. I dislike how the normal Visual Studio never seems to do a clean uninstall of it's dependencies, but with EWDK I simply unmount the ISO and it's gone!

**Comment by Rossmaxx** [comment]
Btw i forgot to say here, I had updated the wiki some time after @musikBear opened this issue. Try looking into the wiki now.

**Comment by zonkmachine** [comment]
> Btw i forgot to say here, I had updated the wiki some time after @musikBear opened this issue. Try looking into the wiki now.

OK. The wiki is updated and many questions have been answered here directly.
We have a Discord account where OP is active and it has specific support channels for users and developers.
I'm closing this issue.

@musikBear You can still ask questions in this issue but I'm closing it out in favor of more pressing issues.
