### ISSUE TITLE
Give users more control over knob adjustments with the mouse wheel

### ISSUE THREAD

**Issue by michaelgregorius** [LMMS/lmms#6769]
### Enhancement Summary
Using the mouse wheel to make adjustments to knobs currently only supports one mode where only very small adjustments are made. Around 2000 mouse wheel event are needed to fully sweep the range of a parameter. As you can see in the following video the knob position barely changes:

https://github.com/LMMS/lmms/assets/9293269/ad08ee6d-bdfa-4e91-94ef-976decf9d41b

### Proposal
The users should be given the option to use modifier keys (Shift, Ctrl, Alt) to switch between different scales of adjustment.

### Mockup
I have made some adjustments to `Knob::wheelEvent` which implement the following behaviour:
* Using the mouse wheel without any modifier keys makes coarser adjustments than the current default, i.e. the range of the parameter can be swept with 100 mouse wheel events.
* Pressing the "Shift" key while using the mouse wheel allows making coarser adjustments than the default. The range can be swept with 10 mouse wheel events.
* Pressing the "Ctrl" key allows making finer adjustments than the default. The range is swept with 1000 events.
* Pressing the "Alt" key allows even finer adjustments. The range is swept with 2000 events (the current default).

As you can see most of these scales are organized in magnitudes which IMHO gives a very natural feeling to "zone in" on a value.

The following video shows making changes without any modifier key, and then with "Shift", "Ctrl" and "Alt" pressed:

https://github.com/LMMS/lmms/assets/9293269/4c70f479-08f7-4910-a510-296946f7ab61

### Pull request
The corresponding pull request is #6770.

**Comment by M4rotte** [comment]
Nice enhancement. Big thx.

**Comment by michaelgregorius** [comment]
Happy to hear that people are happy with the change, @M4rotte!

I gave it a try with regards to a tool tips that shows the current value of the knob. I tried to implement it by using the existing dialog because otherwise it would look inconsistent. The situation seems to be the following:
* Qt can inform a widget with an event that indicates that a tool tip would be about to show. This could be used to show the custom tool tip widget.
* Unfortunately, Qt does not seem to inform when the tool tip would be about to hide. So we wouldn't know when to hide our custom tool tip again.

So we'd only get halfway there and therefore I propose to create a new issue for that request.

**Comment by zonkmachine** [comment]
@M4rotte @michaelgregorius There is an issue for knob values shown on hover already: https://github.com/LMMS/lmms/pull/5911

**Comment by michaelgregorius** [comment]
Thanks for the hint @zonkmachine! I have also added my findings there together with a potential alternative implementation.

**Comment by zonkmachine** [comment]
Oopsie! The issue is here: https://github.com/LMMS/lmms/issues/5779
