### ISSUE TITLE
LMMS doesn't start on Zorin OS (flatpak)

### ISSUE THREAD

**Issue by d4f5409d** [LMMS/lmms#6772]
### Bug Summary
Flatpak version doesn't open up, we can only see the loading screen

#### Steps to reproduce
Install LMMS flatpak version on Zorin OS

#### Expected behavior
To start and work

#### Actual behavior
It stops

#### Affected LMMS versions
1.2.2

**Comment by zonkmachine** [comment]
The lmms develkopers isn't responsible for the flatpack. Try a later appImage instead. I recommend the nightly versions.
https://lmms.io/download#linux (scroll down)

**Comment by d4f5409d** [comment]
No. Flathub redirected me to here. Please do something. It's not my task to figure out and test everything to get a software working on my computer. It should function without tinkering. I reported, now I've done my thing, it's yours now.

**Comment by zonkmachine** [comment]
> No. Flathub redirected me to here

What's flathub? We build a music studio and release the code and also provide binaries for multiple platforms. You have tried a version that we didn't package. I can't  possibly know what's wrong with it. It could be the package, your linux version that lacks something or maybe something in lmms, but lmms seem to work. Especially the latest development versions rock.

> It's not my task to figure out and test everything to get a software working on my computer

No. And it isn't our task to fix a package we didn't do. Our own packages work. I can only recommend a package that I know works and for the flatpack, the one who did it needs to fix it themselves or bump us for assistance.

**Comment by Veratil** [comment]
We do not maintain the Flathub build. Please report the issue here: https://github.com/flathub/io.lmms.LMMS/issues
