### ISSUE TITLE
VeSTige corrupts itself after one day of LMMS being installed

### ISSUE THREAD

**Issue by 3prm3** [LMMS/lmms#6800]
#### Steps to reproduce
I'm not sure
#### Expected behavior
VeSTige loads VST plugins
#### Actual behavior
VeSTige won't load plugins unless I do a reinstall
#### Screenshot
![image](https://github.com/LMMS/lmms/assets/70713233/c57dc513-5d39-45c6-b7e4-f1bc5f6c6edd)

#### Affected LMMS versions
1.2.2, 1.3.0-alpha-1

**Comment by 3prm3** [comment]
![](https://github.com/LMMS/lmms/assets/70713233/ed30f672-0a61-4b0f-9035-50552a9461a4)

**Comment by 3prm3** [comment]
these dlls are actually in the program, which makes it odd that it errors...

**Comment by 3prm3** [comment]
I copied the DLLs from another install and it worked

**Comment by musikBear** [comment]
> I copied the DLLs from another install and it worked

That is an odd sequence of events.
You write that you had this issue in _both_ 1.2.2 and 1.3-alpha.
from where did you get the dll that fixed the issue 1.2.2 of 1.3 ?

**Comment by 3prm3** [comment]
The issue originally started in 1.2.2 then I updated to 1.3-alpha. Then I copied the DLLs from another install I had from another machine

**Comment by 3prm3** [comment]
1.3-alpha

**Comment by 3prm3** [comment]
Also, I just realized it doesn't corrupt every day, but every time the program's closed

**Comment by musikBear** [comment]
> Also, I just realized it doesn't corrupt every day, but every time the program's closed

That is just weird. What is the name of the VST that you have these issues with?
Have you tried more than _that one_ VST?

**Comment by 3prm3** [comment]
Komplete Kontrol, LABS, Decent Sampler

**Comment by musikBear** [comment]
> Komplete Kontrol, LABS, Decent Sampler

Only know LABS, and that is special. It could be that the imported library-file is flawed.
try MDA-Piano http://mda.smartelectronix.com/synths.htm
It is very small in size, and you can just copy its dll to your VST-folder. Further its a quite good piano-instrument, so it is a win win
Try and repeat the sequence that made your Vestige crash, and see what happens with a std VST2

**Comment by 3prm3** [comment]
It works

**Comment by musikBear** [comment]
Please close your ticket.

**Comment by 3prm3** [comment]
It works as in mdaPiano runs
