### ISSUE TITLE
Language File Upload Difficulty

### ISSUE THREAD

**Issue by Ledenav** [LMMS/lmms#6806]
Turkish language translation is available as tr.ts file. But it is not included in the application!
When I dump the tr.ts file to locale, it doesn't work. Because it's not tr.qm !
When I make the extension of the existing tr.ts file to tr.qm, the application sees it. But it doesn't work when I select it.How can I convert the extension to ? A simple typing extension change that I spoofed. How will tr.ts become tr.qm ???

[https://github.com/LMMS/lmms/tree/master/data/locale](https://github.com/LMMS/lmms/tree/master/data/locale)

**Comment by Rossmaxx** [comment]
Translation files are not supposed to work like that. Please sign up for transifex and translate there.

**Comment by DomClark** [comment]
The tool to compile `.ts` files into `.qm` files is [`lrelease`](https://doc.qt.io/qt-6/linguist-lrelease.html), which is available as part of the [Qt framework](https://www.qt.io/download-open-source). You can run this manually, or if you have LMMS set up to build from source, it will be run automatically when LMMS is built. If you want to contribute translations back to LMMS, sign up to Transifex as Rossmax mentioned. More information is available on [our wiki](https://github.com/LMMS/lmms/wiki/Creating-a-localization), and if you have further questions, please ask on [Discord](https://lmms.io/chat/) in the `#dev-support` channel.
