### ISSUE TITLE
Brew cannot resolve package sdl on macOS Ventura 13.0

### ISSUE THREAD

**Issue by adityachatterjee42** [LMMS/lmms#6809]
### Bug Summary
MacOS dependencies page (/wiki/dependencies-macos) lists sdl as a dependency to be installed via brew. Brew cannot resolve this package. I believe the instructions should be updated to have users install sdl2. 

#### Steps to reproduce
```brew install sdl```

#### Screenshot
<img width="956" alt="Screenshot 2023-08-16 at 10 27 52 AM" src="https://github.com/LMMS/lmms/assets/13947304/970c792c-a5b9-48ba-b47a-d2e87bf01d2a">

#### Affected LMMS versions
N/A

**Comment by PhysSong** [comment]
I've updated the wiki article to reflect upstream package name changes.
- If you're building `master`, you may install `sdl2` instead
- If you're building 1.2.x or older, you should also install `sdl12-compat`(not tested)
