### ISSUE TITLE
Segfault when trying to MIDI controle a knob which is already driven by a LFO

### ISSUE THREAD

**Issue by M4rotte** [LMMS/lmms#6810]
Hi,

Easy to reproduce: Create a LFO, use it on any knob, then right-click the knob and choose “edit connections”, in the dialog, “auto detect” isn’t checked, check it and then:

    Thread 1 "lmms" received signal SIGSEGV, Segmentation fault.
    0x00005555556c3234 in lmms::AutomatableModel::setValue(float) ()

Can you tell me how I can build LMMS with the “debugging symbols”, so I can have a more detailed error?

LMMS 1.3.0-alpha.1.320+ge87d44b42

**Comment by messmerd** [comment]
I've confirmed that the bug exists on master.

Here's the stack trace:
<details>
  <summary>Click to expand</summary>
<pre>
Thread 1 "lmms" received signal SIGSEGV, Segmentation fault.
0x00005555557b5cc6 in lmms::AutomatableModel::setValue (this=0xe0, value=0) at /home/dalton/Documents/lmms_master_debug/src/core/AutomatableModel.cpp:297
297		m_oldValue = m_value;
(gdb) bt
#0  0x00005555557b5cc6 in lmms::AutomatableModel::setValue(float) (this=0xe0, value=0) at /home/dalton/Documents/lmms_master_debug/src/core/AutomatableModel.cpp:297
#1  0x000055555599b786 in lmms::MidiPort::setInputChannel(int) (this=0x88, val=0) at /home/dalton/Documents/lmms_master_debug/include/MidiPort.h:58
#2  0x000055555599bc8b in lmms::AutoDetectMidiController::reset() (this=0x0) at /home/dalton/Documents/lmms_master_debug/src/gui/modals/ControllerConnectionDialog.cpp:111
#3  0x000055555599b63c in lmms::gui::ControllerConnectionDialog::autoDetectToggled() (this=0x7fffffffbf90) at /home/dalton/Documents/lmms_master_debug/src/gui/modals/ControllerConnectionDialog.cpp:411
#4  0x000055555578432a in lmms::gui::ControllerConnectionDialog::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) (_o=0x7fffffffbf90, _c=QMetaObject::InvokeMetaMethod, _id=4, _a=0x7fffffffb200)
    at /home/dalton/Documents/lmms_master_debug/build/src/lmmsobjs_autogen/DGKZTCOIDE/moc_ControllerConnectionDialog.cpp:100
#5  0x00007ffff5cd5ddf in doActivate<false>(QObject*, int, void**) (sender=0x7fffffffbfe8, signal_index=3, argv=0x7fffffffb200) at kernel/qobject.cpp:3898
#6  0x000055555578f31b in lmms::Model::dataChanged() (this=0x7fffffffbfe8) at /home/dalton/Documents/lmms_master_debug/build/src/lmmsobjs_autogen/DGKZTCOIDE/moc_Model.cpp:154
#7  0x00005555557b5e4a in lmms::AutomatableModel::setValue(float) (this=0x7fffffffbfe8, value=1) at /home/dalton/Documents/lmms_master_debug/src/core/AutomatableModel.cpp:318
#8  0x00005555559c7034 in lmms::gui::AutomatableButton::toggle() (this=0x555557f0f370) at /home/dalton/Documents/lmms_master_debug/src/gui/widgets/AutomatableButton.cpp:170
#9  0x00005555559c6d34 in lmms::gui::AutomatableButton::mousePressEvent(QMouseEvent*) (this=0x555557f0f370, _me=0x7fffffffb7c0) at /home/dalton/Documents/lmms_master_debug/src/gui/widgets/AutomatableButton.cpp:119
</pre>
</details>

> Can you tell me how I can build LMMS with the “debugging symbols”, so I can have a more detailed error?

You can set the CMake configuration option `CMAKE_BUILD_TYPE` to `Debug` prior to building.

When running cmake in command-line, you would add: 
```txt
-DCMAKE_BUILD_TYPE=Debug
```
See the [compilation instructions](https://github.com/LMMS/lmms/wiki/Compiling#cmake-quickstart).
