### ISSUE TITLE
[DOCS] Convert issue templates to issue forms

### ISSUE THREAD

**Issue by Panquesito7** [LMMS/lmms#6823]
### Enhancement Summary

The current way of reporting issues is by using issue templates. There's a new way that can be used, which is [issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms).
By using issue forms, we can have required fields, dropdowns, and other features that issue templates do not have.

#### Justification

This will make reporting issues for maintainers and contributors much easier.

#### Mockup

I don't think this applies here.

**Comment by TechnoPorg** [comment]
I'm by no means a project maintainer, but my two cents are that I quite like this idea, and would be happy to work on it myself as well.

**Comment by Panquesito7** [comment]
> I'm by no means a project maintainer, but my two cents are that I quite like this idea, and would be happy to work on it myself as well.

If you'd like to work on it, feel free to do so! Or we can collaborate on it together. Do whatever fits you best. 🙂

**Comment by TechnoPorg** [comment]
I've gone ahead and written up some form templates, which you should be able to see in action when you open an issue on [my fork](https://github.com/TechnoPorg/lmms/issues). If you have any feedback / advice for them before I open a PR, it would be much appreciated!
