### ISSUE TITLE
Clip(s) copy in the song editor is broken

### ISSUE THREAD

**Issue by M4rotte** [LMMS/lmms#6824]
### Bug Summary

Clip copy in the song editor is broken.

#### Steps to reproduce

From an empty project, create multiple pattern tracks. Add some clips. Try to copy them by using the Ctrl key: they are copied many bars away than where you release de mouse button, or copied on another track.

#### Expected behavior

The clip(s) should be copîed to the same track at the bar (or the fraction on bar) where the mouse-click is released.

#### Actual behavior

In the song editor windows, Clips are copied many bars away than where you release de mouse button, or even copied to another track (!).

#### Affected LMMS versions

Very last master branch: commit 9a0add49fb61f1bbac603e7

I bet it’s related to the last big commit introduced to replace ``QVector`` with ``std::vector``.

I profit of this bug report to salute the great work you do. Much respect to you LMMS developers! You’re doing an amazing work.

**Comment by Rossmaxx** [comment]
> I bet it’s related to the last big commit introduced to replace QVector with std::vector.

I don't think so. The actual culprit might be

**Comment by zonkmachine** [comment]
> I don't think so. The actual culprit might be #6803

That's the logic first guess but it turns out that the guilty commit really is https://github.com/LMMS/lmms/commit/9a0add49fb61f1bbac603e7e181221b7cef81c1b
@sakertooth

As they say. No omelette without eggs.

**Comment by sakertooth** [comment]
Yikes, this is bad. I'll take a look.

**Comment by sakertooth** [comment]
I cant seem to reproduce this bug. Copying pattern track clips to separate tracks or just at a different position in the same track work just fine.

**Comment by zonkmachine** [comment]
Demo project (remove .txt from name)
[copypaste2.mmp.txt](https://github.com/LMMS/lmms/files/12422326/copypaste2.mmp.txt)

Picture one. Demo project.
![copypastesongeditor](https://github.com/LMMS/lmms/assets/6368949/a0c57c9a-383a-4527-aabf-8cc7724728f6)

Picture two. In the Piano Roll. I try to copy pattern 4 (the patterns are numbered after the number of notes in it. I didn't get past Sesame Street in math.) I paste it on the track on the place that I later highlight by creating a track content object. The pasted clip turns up on track 3 to the far right.
![copypaste](https://github.com/LMMS/lmms/assets/6368949/b198508d-46ca-479d-b83a-bcf4744c08f8)

**Comment by IanCaio** [comment]
> > I don't think so. The actual culprit might be #6803
> 
> That's the logic first guess but it turns out that the guilty commit really is [9a0add4](https://github.com/LMMS/lmms/commit/9a0add49fb61f1bbac603e7e181221b7cef81c1b) @sakertooth
> 
> As they say. No omelette without eggs.

I was finding weird it would be related to #6803 as it doesn't really change the copying logic, just the conditions for copying inside the pattern editor. It could be something on the copy refactoring from years ago but the OP said it didn't affect the older versions.

I'll look into the changes from the `std::vector` PR that were made to the copying files to see if I notice something. This happens when you copy by CTRL + dragging?

**Comment by sakertooth** [comment]
Found the issue. PR coming soon, but I found a few more issues.
