### ISSUE TITLE
Undoing a deletion of an automation entry causes all automation entries on that automation line to lose their connections

### ISSUE THREAD

**Issue by dan-giddins** [LMMS/lmms#6829]
### Bug Summary
Undoing a deletion of an automation entry causes all automation entries on that automation line to lose their connections.

#### Steps to reproduce
Create multiple automation with multiple connections.
Delete one of the automation entries.
Undo the automation deletion.
All other automaton entries on that line lose their connections.

#### Expected behavior
All other automaton entries should retain their connections.

#### Actual behavior
All other automaton entries on that line lose their connections.

#### Screenshot
TODO

#### Affected LMMS versions
Current Master branch (fc2f6a0b31bdd10c47cc0c6c2c18723d208eaae0) (built on Windows with MSVC).

#### Logs
TODO

**Comment by lily-0xFE5** [comment]
For me this also happens when I undo _creating_ an automation entry. I’m using version 1.2.2 from Flathub.
