### ISSUE TITLE
Native compressor plugin display enhancement

### ISSUE THREAD

**Issue by M4rotte** [LMMS/lmms#6830]
### Enhancement Summary

Be able to see the graph of the compression effect without the effect controls widget masking a big part of it.

#### Justification

I like graphs.

I’m not sure if the realtime graph of this plugin has been conceived as just a decoration, or if I’m to dumb to have been able to find how to do it, but it seems there is no possibility to hide the controls to get a full view of the graph.

Also, the possibility to hide the graph to show only the effect controls would also be welcome, in a CPU cycle saving goal. But that’s another thing.

**Comment by RoxasKH** [comment]
I kinda agree with this.

The plugin was designed after Fabfilter Pro C2 tho, which if you search it up has a similar GUI.

Surely something along the lines of Fruity Limiter GUI, with a separate box for the graph, could be done, although that would show up issues for what concern the resizeability of the plugin, as the plugin as of now it possible to almost fully resize, at least the graph part.

Quickiest dirty solution would be adding a toggle to hide the compressor commands, which personally i'm not a fan of, but would work.

P.S: The controller container has some trnsparency so you can kinda see what happens under it, although i guess it's not that transparent.

**Comment by DomClark** [comment]
You can double-click on the Equaliser plugin to hide its controls; perhaps something similar could work here?

**Comment by zonkmachine** [comment]
Maybe @LostRobotMusic want's to look at this?
