### ISSUE TITLE
Some  values of LV2 plugins aren’t storeds , thus 

### ISSUE THREAD

**Issue by M4rotte** [LMMS/lmms#6847]
Hi,

I just noticed that some values on a plugin aren’t store.

### Bug Summary

I noticed the issue when suing de CALF filter.

#### Steps to reproduce

Start from an empty project
Add an instrument in the pattern editor
Add a CALF filter on this instrument.
Change the value of filter type using the drop-down list.
Save the project.

#### Expected behavior

The filter type value should be restored when reloading the project

#### Actual behavior

The filter type is back at its default.

#### Affected LMMS versions

LMMS 1.3.0-alpha.1.356+gfa05ce20b
(Linux x86_64, Qt 5.15.8, GCC 12.2.0)

And probably some older versions. I noticed that many times, but this is only today that I found the time to  report it.

#### Logs

I see this line in the LMMS out out. Tell me what file you neede

**Comment by zonkmachine** [comment]
What I can see the right filter number is remembered but the filter menu seem to get shuffled on start. I'll see if I can bisect this to see if the issue was introduced on a specific code change.

**Comment by zonkmachine** [comment]
I've reproduced this with the oscillators in the Calf Wavetable synth. It's the drop down menu/enumeration that breaks when reloading a project without first closing lmms.

**Comment by zonkmachine** [comment]
Project setting.
![dropdown1](https://github.com/LMMS/lmms/assets/6368949/09fa7c55-4519-43f7-8645-87a21bac4ce3)

After reloading a project when lmms is running.
![dropdown2](https://github.com/LMMS/lmms/assets/6368949/82708457-1dd8-4686-88be-f3e4d5d56dd3)

**Comment by zonkmachine** [comment]
I'm closing this issue in behalf of https://github.com/LMMS/lmms/issues/6859 which is a bit more informative.
