### ISSUE TITLE
MIDI Keyboard doesn't work in Flatpak

### ISSUE THREAD

**Issue by EviTRea** [LMMS/lmms#6848]
### Bug Summary
My MIDI keyboard can be picked up and being used with FamiStudio, but not LMMS.
In Carla, it doesn't accept any input as a node. I've tried every MIDI settings and nothing works.

#### Steps to reproduce
1.Boot into Fedora 37 KDE spin (x11, Pipewire)
2.Plug in a USB MIDI Keyboard
3.Download LMMS through Flatpak, Open it

#### Expected behavior
When I press the keyboard, the app knows I pressed my key board.

#### Actual behavior
When I press the keyboard, the app DOES NOT know I pressed my key board.
Not MIDI setting nor Carla helped.

#### Screenshot
Works in another app
![圖片](https://github.com/LMMS/lmms/assets/32661913/9187d966-b5ba-4796-a51f-fcdca85a7c34)

It refuses screenshot but 4 options are ALSA raw-MIDI, ALSA Sequencer, Dummy and OSS raw-MIDI, none of them does anything
![圖片](https://github.com/LMMS/lmms/assets/32661913/f69b3ed2-1319-4021-a381-588ea85f6425)

No Input for Carla
![圖片](https://github.com/LMMS/lmms/assets/32661913/89138703-4a46-4018-a460-764fa8ab979a)

#### Affected LMMS versions
1.2.2 (Linux/x86_64, Qt 5.15.7, GCC 11.3.0) (Flatpak)

**Comment by musikBear** [comment]
> 1.2.2 (Linux/x86_64, Qt 5.15.7, GCC 11.3.0) (Flatpak)

Dont use that. Use LMMS AppImage from https://lmms.io/download#linux
Please report back

**Comment by EviTRea** [comment]
> Dont use that. Use LMMS AppImage from https://lmms.io/download#linux
![圖片](https://github.com/LMMS/lmms/assets/32661913/28d9febe-de0e-4389-90c1-1cdfe95fe254)
![圖片](https://github.com/LMMS/lmms/assets/32661913/671688f2-ebb6-4e1c-9f70-965143c86cf9)
Indeed every version now has a JACK-MIDI option, which enable MIDI input in Carla.
...Is that enough to close the issue though? 
I mean, if the flatpak wasn't maintained by the app devs, this is technically a non-issue, but needing a 3rd party app to make a MIDI keyboard functional is still kind of...not elegant at least.

**Comment by Veratil** [comment]
> I mean, if the flatpak wasn't maintained by the app devs, this is technically a non-issue

Correct. We don't maintain Flatpak. Sorry!

But glad you got it working! I'm going to close this since you did get it working (although through 3rd party app as you say). Needing a 3rd party app is only a current limitation, one day we'll fix that up when we can. 🙏
