### ISSUE TITLE
Key Display Doesn't List "Correct" Keys

### ISSUE THREAD

**Issue by g4vr0che** [LMMS/lmms#6862]
### Bug Summary

The Key display options are weird and list keys which don't really normally occur in normal music theory. 

![image](https://github.com/LMMS/lmms/assets/19616023/6a954473-636f-4552-b0af-802b2d345595)

As visible in the above screenshot, I can select my key display to be "A# minor" which is more accurately reflected as Bb minor because Bb minor doesn't include "B Sharp" (C) as the second degree in it's scale. Technically, it's the same note, but this key is nearly universally expressed as Bb due to this oddity. The same issue occurs with "D#" as D#'s second degree would be "E#", which is F. If you express these as Bb and Eb, then the second degrees are correctly expressed as C and F respectively.

#### Steps to reproduce

Open Key selection dropdown in the Piano Roll 

#### Expected behavior

There are certain keys where sharp is the correct expression, so maybe the best way is to simply list all keys (with all sharps and flats) and let the user pick the one which best fits their mode.

#### Actual behavior

There are unusual/invalid keys displayed.

#### Screenshot

See above

#### Affected LMMS versions

1.3.0-alpha.1.354+ge1d3ecb18
#### Logs
```NA```

**Comment by mvoorhes** [comment]
I can try to figure this out.
