### ISSUE TITLE
Site problem; current nightly build undownloadable

### ISSUE THREAD

**Issue by SalutanisOrkonus** [LMMS/lmms#6863]
### Bug Summary
Problem with website, current nightly is undownloadable. site brings up error 500
#### Steps to reproduce
Press the download buttons on either 32 or 64 bit nightly
#### Expected behavior
I can download
#### Actual behavior
"Error 500
Oops, that is not supposed to happen.

If you followed a valid link on this site, please contact us about it and file an issue on GitHub."
#### Screenshot
![image](https://github.com/LMMS/lmms/assets/65266122/25ee9b02-1e72-4bc7-b7fa-038262f4b2ce)

**Comment by Veratil** [comment]
As of this comment it's showing g3a0e68c0a as the latest commit ID, but that isn't a valid commit in the repo.

**Comment by tresf** [comment]
It's `3a0e68c0ac93a743cedca379c66de00d13647d69` and it's valid.

**Comment by Veratil** [comment]
> It's [3a0e68c](https://github.com/LMMS/lmms/commit/3a0e68c0ac93a743cedca379c66de00d13647d69) and it's valid.

Oooh, does it add a `g` at the start?

**Comment by tresf** [comment]
> > It's [3a0e68c](https://github.com/LMMS/lmms/commit/3a0e68c0ac93a743cedca379c66de00d13647d69) and it's valid.
> 
> Oooh, does it add a `g` at the start?

Yeah, something with the way GitHub formatted our tags when we build, I think Dom just copied it.

I have a PR ready that I believe fixes this here: https://github.com/LMMS/lmms.io/pull/372

**Comment by tresf** [comment]
> > > It's [3a0e68c](https://github.com/LMMS/lmms/commit/3a0e68c0ac93a743cedca379c66de00d13647d69) and it's valid.
> > 
> > 
> > Oooh, does it add a `g` at the start?
> 
> Yeah, something with the way GitHub formatted our tags when we build, I think Dom just copied it.
> 
> I have a PR ready that I believe fixes this here: [LMMS/lmms.io#372](https://github.com/LMMS/lmms.io/pull/372)

Turns out to be a change on GitHub's side creates a URL parsing problem on ours.

I've reverted that patch and here's the new one, which seems to work: https://github.com/LMMS/lmms.io/pull/373
