### ISSUE TITLE
Program freeze when searching in "My Computer"

### ISSUE THREAD

**Issue by SalutanisOrkonus** [LMMS/lmms#6874]
### Bug Summary
I have a second samples folder on my E drive, and when I went to search it using the "My Computer" tab, the program froze. This may have something to do with some recent push that seems to make all the folders in the default sample folder open automatically when searched, if I were to hazard a guess, but I could be wrong.
#### Steps to reproduce
Go into the "My Computer" sidebar tab, and search.
#### Expected behavior
Not freezing the program
#### Actual behavior
It freezes
#### Affected LMMS versions
![image](https://github.com/LMMS/lmms/assets/65266122/c72f2dcc-4116-4f20-87a2-c290a5f72ba9)
![image](https://github.com/LMMS/lmms/assets/65266122/275982fe-4f8d-46d7-8028-739e948e7267)

**Comment by sakertooth** [comment]
I might work on this when I have time. I plan to remove the root directory (and possibly the home directory) and allow the user to add custom directories/drives so the search space is a lot smaller, while also running these jobs asynchronously.
