### ISSUE TITLE
Pattern Builder

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#688]
Piano-roll PatternBuilder
Known from other DAVs.
A patternBuilder  is a gadget that will split marked notes into a user-defined pattern.
In LMMS it could be made as a one-bar 'template-sketch' pop-up.
User will add notes over this in the pattern he wants
User will then build a chord progression in like 2-bar-notes over 16 bars.
User markes the notes (or a subsection of the notes)
From the Edit-menu, a new choice 'Split marked to template' is chosen
The result is that notes that was maked are now split in the 'template-sketch' pattern
A feature like this is amazing, if the user want to build a gated progression, or for stabs and pluck patterns. If the user are alowed to save and load patterns, a library of patterns can be created.
It would also be a logical place for a 'humanize' feature : randomize velocity over a user-span (seed in % or semitone)

**Comment by tresf** [comment]
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.
