### ISSUE TITLE
Compressor - More fpe issues

### ISSUE THREAD

**Issue by zonkmachine** [LMMS/lmms#6886]
### Bug Summary
The Native compressor has some default variable values that gives an arithmetic exception on debugging.

#### Steps to reproduce
On Linux
1 - Compile lmms with debug AND fpe flags set:
`cmake -DCMAKE_BUILD_TYPE=Debug -DWANT_DEBUG_FPE=ON`

2 - Start lmms in gdb
` gdb ./lmms`

3 - Add and open a Compressor.

4A - Turn the `Threshold` knob to 0.

```gdb
Thread 1 "lmms" received signal SIGFPE, Arithmetic exception.
0x00007fff64598704 in lmms::gui::CompressorControlDialog::redrawKnee (this=0x55555d1d5800) at /home/zonkmachine/builds/lmms/plugins/Compressor/CompressorControlDialog.cpp:502
502		float kneePoint2Y = (m_controls->m_effect->m_thresholdVal + (-m_controls->m_effect->m_thresholdVal * (actualRatio * (m_controls->m_effect->m_kneeVal / -m_controls->m_effect->m_thresholdVal))));
(gdb) bt full
#0  0x00007fff64598704 in lmms::gui::CompressorControlDialog::redrawKnee() (this=0x55555d1d5800) at /home/zonkmachine/builds/lmms/plugins/Compressor/CompressorControlDialog.cpp:502
        actualRatio = 0.555555582
        kneePoint1 = -6
        kneePoint2X = 6
        kneePoint2Y = 4.59163468e-41
        ratioPoint = -nan(0x7fd590)
```
4B - Turn the `Size` knob to 0.

```gdb
Thread 1 "lmms" received signal SIGFPE, Arithmetic exception.
0x00007fff65512829 in lmms::CompressorEffect::resizeRMS (this=0x7ffff2950080) at /home/zonkmachine/builds/lmms/plugins/Compressor/Compressor.cpp:180
180		m_rmsTimeConst = exp(-1.f / (m_compressorControls.m_rmsModel.value() * 0.001f * m_sampleRate));
```

@LostRobotMusic

**Comment by anytizer** [comment]
Below reporting may be related as the error message seems similar.
It happens with many options under File. eg. File > Export.

Messages seen On-Screen messages when using GDB and calling LMMS from terminal are:

With GDB:
```
Thread 1 "lmms" received signal SIGFPE, Arithmetic exception.
0x00007fffe8644723 in ?? () from /lib/x86_64-linux-gnu/libxml2.so.2
```

Without GDB:
```
src/3rdparty/rpmalloc/rpmalloc/rpmalloc/rpmalloc.c:1414: _rpmalloc_span_finalize: Assertion `(span->list_size == span->used_count) && "Memory leak detected"' failed.
Aborted (core dumped)
```
I am working with a default empty project.

**Comment by zonkmachine** [comment]
> I am working with a default empty project.

This issue is specifically related to the compressor. Do you mean an empty project with a compressor added to it?
The `rpmalloc` issues is known and not related to this issue. It usually comes up when closing lmms.
The `Thread 1 "lmms" received signal SIGFPE, Arithmetic exception.` message is too general. You need to look at a backtrace.
