### ISSUE TITLE
Knife tool offset or crash with different time signatures

### ISSUE THREAD

**Issue by tehelka-gamedev** [LMMS/lmms#6894]
### Bug Summary
- When using the 3/4 time signature, the knife tool has a right offset from the mouse when the note is not starting at bar 1. It happens also for 4/6 and 5/6 (but it is working for 2/4, 4/4, 3/6, 6/6, ... so that may be a rounding/scaling error).
- When using a time signature with a numerator strictly higher than the denominator (ex 7/6), selecting the knife tool crash LMMS with no error.

#### Steps to reproduce
1. Create a new project and set the time signature to 3/4
2. Open the piano roll for any instrument, place notes starting on bar 1 and on bar 2 (whole notes but it is not mandatory)
3. Select the Knife tool and you will notice no mouse offset for the first note but you will for the second note on bar 2.
4. Change time signature to 7/6 and select the knife tool to see the program crashing.

#### Expected behavior
The knife tool cutting point should be exactly at the mouse, whatever the time signature.
The knife tool should not crash LMMS when selected.

#### Actual behavior
The knife tool cutting point has an offset when using 3/4 time signatures (and other time signatures but I did not find exactly the pattern).
The knife tool crash LMMS when the time signature numerator is higher than the denominator.

#### Screenshot
![lmms_bug_01](https://github.com/LMMS/lmms/assets/17590418/723a517a-9d9c-4ed8-a2ea-d530740fd68f)
![lmms_bug_02](https://github.com/LMMS/lmms/assets/17590418/79e4e107-1927-4e93-919b-979d82b9a214)

#### Affected LMMS versions
1.3.0-alpha.1.102+g89fc6c960 (win32/x86_64, Qt 5.9.8, GCC 7.3-win32 201)

**Comment by sakertooth** [comment]
This version of LMMS just segfaults for me.

**Comment by tehelka-gamedev** [comment]
This is the version I downloaded on LMMS version, the alpha version (orange button). Should I try other versions to see if the bug is still there?

**Comment by zonkmachine** [comment]
> Should I try other versions to see if the bug is still there?

Yes. Please try the latest Nightly version.
https://lmms.io/download#windows (bottom)

**Comment by tehelka-gamedev** [comment]
I downloaded the 1.3.0-alpha.1.402+g23ef89b4a version as you linked and the bug does not seem to be there anymore. Sorry for the inconvenience then. And thank you for your answers!

**Comment by zonkmachine** [comment]
@tehelka-gamedev Thanks for testing!
