### ISSUE TITLE
Error message "Read permission denied" on some TripleOsc presets

### ISSUE THREAD

**Issue by michaelgregorius** [LMMS/lmms#6896]
### Bug Summary
The error message "Read permission denied" is shown three times when clicking on some TripleOscillator presets, e.g. "AmazingBubbles.xpf".

#### Steps to reproduce
1. Start LMMS.
2. Open the "My Presets" pane.
3. Open the TripeOscillator presets.
4. Click "AmazingBubbles.xpf".

#### Expected behavior
The preset should preview and open without any error message.

#### Actual behavior
The error message "Read permission denied" is shown three times.

#### Potential cause
If I open the preset file in a file editor I find that it references the file `samples/empty.wav` three times. There does not seem to be such a file in the repository. If it was deleted while doing some cleanup it needs to be added back.

#### Additional information by @anytizer
Here's some additional information that was provided by @anytizer in #6880:

> It is a list of TripleOscillator presets that refer to non-existing empty.wav file.
> Escalated from #6630 and old version of LMMS that caused a rare crash.
> 
> ![image](https://github.com/LMMS/lmms/assets/5563341/c1510ccb-f410-4e0e-ac4f-b0cc08748c8e)
> 
> Also, the final file path has repeated word "samples".
> May be a text edit to refer correct empty.wav should be fine in those .xpf

**Comment by michaelgregorius** [comment]
Found pull request #4536 which attempted to fix the problem in 2018. Pinging @PhysSong as he mentioned a fix to be implemented in that pull request (see [comment](https://github.com/LMMS/lmms/pull/4536#issuecomment-422706681)).

**Comment by anytizer** [comment]
Hand picked list of names.

- [ ] [AmazingBubbles.xpf](/LMMS/lmms/tree/master/data/presets/TripleOscillator/AmazingBubbles.xpf)
- [ ] [AnalogBell.xpf](/LMMS/lmms/tree/master/data/presets/TripleOscillator/AnalogBell.xpf)
- [ ] [Analogous.xpf](/LMMS/lmms/tree/master/data/presets/TripleOscillator/Analogous.xpf)
- [ ] [AnalogTimes.xpf](/LMMS/lmms/tree/master/data/presets/TripleOscillator/AnalogTimes.xpf)
- [ ] [BellArp.xpf](/LMMS/lmms/tree/master/data/presets/TripleOscillator/BellArp.xpf)
- [ ] [Bell.xpf](/LMMS/lmms/tree/master/data/presets/TripleOscillator/Bell.xpf)
- [ ] [DistortedPMBass.xpf](/LMMS/lmms/tree/master/data/presets/TripleOscillator/DistortedPMBass.xpf)
- [ ] [DullBell.xpf](/LMMS/lmms/tree/master/data/presets/TripleOscillator/DullBell.xpf)
- [ ] [E-Organ.xpf](/LMMS/lmms/tree/master/data/presets/TripleOscillator/E-Organ.xpf)
- [ ] [Freaky-Bass.xpf](/LMMS/lmms/tree/master/data/presets/TripleOscillator/Freaky-Bass.xpf)
- [ ] [FutureBass.xpf](/LMMS/lmms/tree/master/data/presets/TripleOscillator/FutureBass.xpf)
- [ ] [Harmonium.xpf](/LMMS/lmms/tree/master/data/presets/TripleOscillator/Harmonium.xpf)
- [ ] [LFO-party.xpf](/LMMS/lmms/tree/master/data/presets/TripleOscillator/LFO-party.xpf)
- [ ] [LovelyDream.xpf](/LMMS/lmms/tree/master/data/presets/TripleOscillator/LovelyDream.xpf)
- [ ] [Play-some-rock.xpf](/LMMS/lmms/tree/master/data/presets/TripleOscillator/Play-some-rock.xpf)
- [ ] [PluckArpeggio.xpf](/LMMS/lmms/tree/master/data/presets/TripleOscillator/PluckArpeggio.xpf)
- [ ] [ResonantPad.xpf](/LMMS/lmms/tree/master/data/presets/TripleOscillator/ResonantPad.xpf)
- [ ] [SpaceBass.xpf](/LMMS/lmms/tree/master/data/presets/TripleOscillator/SpaceBass.xpf)
- [ ] [TB303.xpf](/LMMS/lmms/tree/master/data/presets/TripleOscillator/TB303.xpf)
- [ ] [TheMaster.xpf](/LMMS/lmms/tree/master/data/presets/TripleOscillator/TheMaster.xpf)
- [ ] [Xylophon.xpf](/LMMS/lmms/tree/master/data/presets/TripleOscillator/Xylophon.xpf)

**Comment by anytizer** [comment]
This branch ([empty-waves](https://github.com/anytizer/lmms.anytizer/tree/empty-waves)) has proposed a solution for this. I made an empty.flac file and put in webforms folder. Then relinked this file from old .xpf. Could you please check?

**Comment by consolegrl** [comment]
Pulled master this morning and I get "Read permission denied" (no details of which file by the way) 6 times before export and 12 times after export.

**Comment by anytizer** [comment]
@consolegrl The proposed solution is in the "branch" work: empty-waves. You can switch to this branch now, and make a test.

**Comment by michaelgregorius** [comment]
@anytizer, unfortunately the fix is not as simple as adding an empty wave file. The reason is that doing so will likely not fix the existing presets that are already in the user's LMMS directory. If I remember correctly these are copied once when LMMS is started for the first time. So in this case the error message would still be shown each such a user clicks on one of these presets.

@PhysSong  proposed to fix it using an upgrade routine in `DataFile` [here](https://github.com/LMMS/lmms/pull/4536#issuecomment-412814074). However, this also comes with problems because he noted that users might have presets that reference non-empty "samples/empty.wav". Although I assume that this case is very improbable.

By the way, the problem itself seems to be very old but it just wasn't visible until some days ago. The reason that it crops up now is that the showing of the error message was added with pull request #6286 in commit 07229b64048. If you look at the code you will find that the error message is triggered from the core code which is not a good idea anyway because it makes the work to separate the GUI from the core harder (see the discussion in #6712).

@PhysSong, @DomClark, do you think that commit 07229b64048 should be reverted for now taking this new information into account?

**Comment by consolegrl** [comment]
At least one of my projects has this problem, when I load it I get 3 "Read permission denied". I've hand edited my project file and removed "usersample:samples/empty.wav" from all of the userwavefile[0..2] attributes and the errors stop on next load. This is an obvious error as there is no "empty.wav" in my lmms/samples/ folder; lmms/samples/empty.wav doesn't exist.

I don't know what change inserted these values as this instrument preset doesn't use custom waveforms, but there it is in the wild.

Hope this helps add something to the hunt.

**Comment by michaelgregorius** [comment]
@consolegrl, was it one of your own presets, i.e. a newer one, or one from the factory presets?

The reference to "samples/empty.wav" seem to have been present in some factory presets for ages. It only the showing of the dialog that was added some days ago via PR #6286 that made this visible now.

**Comment by consolegrl** [comment]
Never mind, @michaelgregorius these empty.wav seem to have snuck in a while ago and are no longer being added so I just needed to purge them from my projects and presets. Things work fine now. I do think we need an upgrade routine to deal with them though. If it's specifically usersample:samples/empty.wav and it doesn't exist, it's not an error its a stale bug carcass. @PhysSong what do you think?

**Comment by michaelgregorius** [comment]
In the TripleOscillator preset "AmazingBubbles.xpf" it shows up as:
```
userwavefile0="samples/empty.wav"
```
In this case one cannot decide 100% that it is OK that the sample is missing because it might be an actual sample by the user that once existed and then went missing.

In my opinion this is something that should not be handled in the class `SampleBuffer` anyway. This class is just a buffer for a sample, i.e. a core class, which is used by a higher level. This class should not do any error handling and should not show error messages by itself.

Instead it should (roughly) work as follows:
1. A higher level class knows that it want to instantiate a sample buffer from a file.
2. The file is attempted to be opened:
   * The file can be opened: the sample buffer is filled with the data and everything commences.
   * The file cannot be opened: the higher level class does some error handling.

In the case of an instrument, e.g. TripleOscillator the error handling might be to keep the sample buffer empty and to set a flag which indicates that loading has failed. The GUI of the instrument then indicates in a very clear but non-intrusive way that something is missing.

Alternatively, if some dialog is shown then it should be a dialog with a summary of everything that went wrong which is only shown once. Showing three dialogues does not really help the users.

**Comment by consolegrl** [comment]
@michaelgregorius Someone made that bed a while ago and now we have to sleep in it. 99% of the time something called empty.wav will be empty, not even seconds of slience, but empty. There is a vanishing chance that it is someone's vocal recording about how empty they feel, but that specific path is very sus. now, that fact that it's being looked for in samples/ is an even bigger tell because lmms/samples is now usersample:, so this resolves to lmms/samples/samples/empty.wav, which is absurd. Also samples/empty.wav is a known bad path because of that.

None of this matters however in the case of TripleOscillator, if the wavetypeX is not set to custom waveform, we can be 100% certain that samples/empty.wav is erroneous, because the data isn't applicable to the current state anyway.

**Comment by michaelgregorius** [comment]
@consolegrl, I am aware that in almost all cases it will be the erroneous file. I just wanted to point out that there might perhaps be cases where we are messing with legitimate files that get broken then. Even if it is a very improbable case.

> None of this matters however in the case of TripleOscillator, if the wavetypeX is not set to custom waveform, we can be 100% certain that samples/empty.wav is erroneous, because the data isn't applicable to the current state anyway.

I wasn't able to find out how to load a custom waveform in TripleOscillator but what happens if I load a custom waveform, switch to another waveform and then back to custom? Is the waveform saved as still available? Or will I have to reload the file? In the former case case it might make sense to save the waveform in the preset even if it is not the current waveform.

**Comment by DomClark** [comment]
> do you think that commit https://github.com/LMMS/lmms/commit/07229b64048c118bd8a25904c2cbc1a603fad838 should be reverted for now taking this new information into account?

I'd rather not. We'd be better off fixing the bug than going back to hiding it. Nightly versions will have annoyances from time to time, which is a risk users using them have been warned about and will have to put up with. I'd be hesitant already reverting a change that introduced a bug instead of fixing forward, and in this case the bug isn't even part of the change. Users themselves can revert to an earlier nightly if they're sufficiently bothered.

> If you look at the code you will find that the error message is triggered from the core code which is not a good idea anyway because it makes the work to separate the GUI from the core harder (see the discussion in https://github.com/LMMS/lmms/discussions/6712).

True, but that was the case even before the aforementioned commit. The change was to add stricter checking and more useful messages. (Although "file not found" would be more useful in this case than "read permission denied".)

> In my opinion this is something that should not be handled in the class `SampleBuffer` anyway. This class is just a buffer for a sample, i.e. a core class, which is used by a higher level. This class should not do any error handling and should not show error messages by itself.

Again, I agree, and there is a refactor effort at #6610. However, I think the question of how to report errors and the question of what to do about broken presets are different (unless the answer to the latter is "do nothing and let the error be reported"). My understanding of this issue is that we're trying to answer the latter question, but correct me if I'm wrong.

> In this case one cannot decide 100% that it is OK that the sample is missing because it might be an actual sample by the user that once existed and then went missing.

Honestly, at this point I think we should decide that we don't care and those projects will be broken - I'd be surprised if there were a single one. Also, I'm almost convinced there is no silent fix for these presets that also preserves such projects. Without a way to distinguish missing user samples from missing factory samples, you can't change one but not the other without asking the user. From a utilitarian perspective, there will be much more total annoyance to report every broken preset to every user affected by them than to break one, maybe two, users' projects.

**Comment by karmux** [comment]
These Xpressive presets also show "Read permission denied":
```
Creature.xpf
Rubber Bass.xpf
Untuned Bell.xpf
```

**Comment by michaelgregorius** [comment]
Closing this issue as the problem seems to have been fixed via commit ce722dd6b6c.

**Comment by Rossmaxx** [comment]
@michaelgregorius nope, can't say so. On the contrary, i remember someone discussing that the issue started only after that pr but not sure on that one.

**Comment by michaelgregorius** [comment]
@Rossmaxx, do you mean that the problem is still there or that the commit did not fix it? The error message was removed with that commit (at least if it was no rephrased version was added in another file).

I have tried with some of the mentioned presets and the problem did not show up anymore.

**Comment by Rossmaxx** [comment]
Since you confirmed the fix, just ignore what i said. I remember seeing a discussion related to this issue around the time 6610 got merged so it was me misreading things. Also, I don't got no time to check anything myself.
