### ISSUE TITLE
req. add sounds as patterns

### ISSUE THREAD

**Issue by oeai** [LMMS/lmms#690]
right now adding ogg or wav file goes through audio-file processor that needs to set note and its longitude in song editor and it will be seen as note.
sound processor already renders a waveform and i propose to add full waveform and work with it as pattern (as in qtractor or ardour).
after adding this feature there can be implemented a virtual lock for any instrument, meaning that this instrument+automation will not be changed anymore and because of that this instrument track can be rendered separately into lmms/tmp and used without synth itself leaving more processor power for other instruments load.

**Comment by Umcaruje** [comment]
@oeai Could you please further explain this request? I think this is something that can be added to #1471

**Comment by Umcaruje** [comment]
No response in almost 2 months. Closing.
