### ISSUE TITLE
Song editor

### ISSUE THREAD

**Issue by Alexander-Prediger** [LMMS/lmms#6900]
Im Song Editor bitte übereinander liegende Blöcke  
Farblich markieren. 

Edited Zonkmachine: Google Translate
```
In the song editor, please use blocks on top of each other
Mark in color.
```

**Comment by Rossmaxx** [comment]
@Spekular also this one.

**Comment by Rossmaxx** [comment]
This is not closed yet?

**Comment by zonkmachine** [comment]
@Alexander-Prediger Danke! There are similar issues open that touch on this and it's also hard for us to work when a topic is not in English. I'm closing this as a duplicate.
