### ISSUE TITLE
Cannot load some samples previously loadable

### ISSUE THREAD

**Issue by SalutanisOrkonus** [LMMS/lmms#6904]
### Bug Summary
Some recent push made all the samples in a copy I have of the FL studio sample pack not work, showing "Invalid Audio File" when attempting to interact with, probably same applies to some others. they worked in previous versions, and now some of my projects have missing sounds
#### Steps to reproduce
Try and load a sample from FL Studio into LMMS, or any sample that has whatever weirdness seems to be going on with this
#### Expected behavior
They load, they did before some push at some point
#### Actual behavior
"Fail to open file"
"Invalid audio file"
#### Screenshot
![image](https://github.com/LMMS/lmms/assets/65266122/0d76add2-dc36-4fa4-acd9-a3bc01492df2)

#### Affected LMMS versions
g33d1baddc, probably more before

**Comment by SalutanisOrkonus** [comment]
Turns out this also applies to many built-in sounds (example: drumsynth folder)

**Comment by Spekular** [comment]
@consolegrl mentioned this with some additional info on Discord.
> anyone else notice that FL studio type samples (wav containers with vorbis inside) stopped working on master recently?

> seemed to be after that big merge that fixed the combo boxes in #6859 (fixed by #6484)

**Comment by consolegrl** [comment]
> Turns out this also applies to many built-in sounds (example: drumsynth folder)

Can confirm lots of drumsynth (.ds) broken as well.

**Comment by consolegrl** [comment]
I know FL Studio ogg-wav's are kinda bogus, though ubiquitous and should prob be supported, but the real question is how did drumsynth files get broken?

I did an entire project with drumsynth sounds because I think they are nifty, are we still planning on supporting them?

**Comment by Veratil** [comment]
> how did drumsynth files get broken?

A bug in a PR that somehow got overlooked.

> are we still planning on supporting them?

Of course. 🙂
