### ISSUE TITLE
Sometimes when searching, folders will show up but not be usable

### ISSUE THREAD

**Issue by SalutanisOrkonus** [LMMS/lmms#6905]
### Bug Summary
When searching in the samples tab, could possibly happen with other tabs too, sometimes some folders will show up in the search (like they should), but not be expandable. These folders are not empty, and will also work some other times. this makes whatever uses them not usable at that time. Folders work correctly without restart if you just don't search, so it's specifically relating to some recent change to searching
#### Steps to reproduce
Use the search function on the samples tab with multiple folders and subfolders. inconsistent
#### Expected behavior
I can open every folder that shows up
#### Actual behavior
Can't sometimes
#### Screenshots
![image](https://github.com/LMMS/lmms/assets/65266122/b27060f5-827e-4477-af7d-bd78c2cf44fc)
"vinyl_rocking" and "vinyl_stops" are not empty folders
![image](https://github.com/LMMS/lmms/assets/65266122/0cf93bf3-13ba-4c9e-81f0-36c528a81061)
here is the contents of each of these 3 folders for the sake of clearness
#### Affected LMMS versions
g33d1baddc, almost certainly multiple others as well since some search update push

**Comment by sakertooth** [comment]
Hi @SalutanisOrkonus, can you see if #6962 fixes this issue?

**Comment by SalutanisOrkonus** [comment]
not unless it gets committed, I can't build stuff myself

**Comment by sakertooth** [comment]
What system are running on? I can try and link you to the build (Mac is the exception for now).

**Comment by sakertooth** [comment]
> Windows 64-bit

You can get the build for Windows 64-bit from [here](https://github.com/LMMS/lmms/suites/17916992133/artifacts/1029477104).

**Comment by SalutanisOrkonus** [comment]
Seems to fix this specific issue far as I can tell so far, but man this is really buggy. Text size seems inconsistent, can't view both factory and user content at the same time, some files use the folder icon for some reason, it's really slow.

**Comment by sakertooth** [comment]
Nice to hear it fixes this issue, but I don't understand some of the other ones. I get the factory and user content one, but I don't experience any inconsistency involving text size, I thought I had already fixed the folder icon issue, and I don't experience any slowdowns. Are the slowdowns from when you start searching?

**Comment by SalutanisOrkonus** [comment]
It just doesn;t even do anything for a second or two, program isnt even frozen, then the search actually happens, though I think that bit is slow too

**Comment by sakertooth** [comment]
Sorry for the repetition, but could you try again with a new build from [here](https://lmms.io/download/pull-request/6962#windows)?
