### ISSUE TITLE
"Edit->Settings" causes Memory Leak (and thus Crash at Exit)

### ISSUE THREAD

**Issue by JohannesLorenz** [LMMS/lmms#6910]
### Bug Summary

When you open the SetupDialog (via Edit->Settings), you get a crash

#### Steps to reproduce

1. Start LMMS
2. Open "Edit->Settings" from the menu
3. Press cancel
4. Close LMMS (e.g. using the top right "X" of your Window Manager)

#### Expected behavior

No segfault.

#### Actual behavior

Segfault, indicating a memory leak. I know that we can just turn the memory leak detection off, but this bug is about the memory leak itself.

The bug seems to be in there for a while, even before #6486 (7aca8ae726ab425b47802721703fb5589fe8289a).

valgrind analysis should help to find the leak. Otherwise, you would need to deconstruct the dialog, bit by bit, and wait until the error vanishes.

#### Affected LMMS versions

33d1baddc0284bd68df752a08ff9c673a706c4d7 (master)

#### Logs
<details>
  <summary>Click to expand</summary>
<pre>
lmms: /home/johannes/cprogs/lmms/work/src/3rdparty/rpmalloc/rpmalloc/rpmalloc/rpmalloc.c:1328: _rpmalloc_span_finalize: Assertion `(span->list_size == span->used_count) && "Memory leak detected"' failed.
Aborted (core dumped)
</pre>
</details>

**Comment by Rossmaxx** [comment]
Now that rpmalloc is removed+ a few leak fixes, does this issue still occur @JohannesLorenz ?

**Comment by zonkmachine** [comment]
This was fixed with removing of the MemoryManager in c991a85eefe2a314ad8f27b7bc1f1b134af46c93
