### ISSUE TITLE
Soundfont player: Some soundfonts pitch is incorrect

### ISSUE THREAD

**Issue by syusui-s** [LMMS/lmms#6915]
### Bug Summary

Some soundfont patches do not sound correctly in version 1.3.0-alpha.
The pitch of some patches is different from the correct pitch.

I checked these soundfonts sound correctly in the stable [version 1.2.2 (Arch Linux package)](https://archlinux.org/packages/extra/x86_64/lmms/).
And, it worked correctly in the old versions of 1.3.0-alpha (e.g. 1.3.0.alpha.1.r283.gf13e95932-1 f13e95932).

- SGM-V2.01 ([Internet Archive](https://archive.org/details/SGM-V2.01))
    - 0.25. Steel-str.Gt
- Timbres Of Heaven GM_GS_XG_SFX V 3.4 Final ([Internet Archive](https://archive.org/details/toh-gmgsxg))
    - 0.0. Concert Grand
    - 0.1. Bright Grand
- GeneralUser GS v1.471
    - 0.2 Electric Grand
    - 0.3 Honky-Tonk (thanks to [YohananDiamond](https://github.com/LMMS/lmms/issues/6915#issuecomment-1743975027))

Here is a zip file which includes an project file `mmpz` and exported tracks (ogg):
[lmms_bug.zip](https://github.com/LMMS/lmms/files/12783813/lmms_bug.zip)

#### Steps to reproduce

1. Add a new track of Soundfont Player.
2. Select a file of soundfont described above.
3. Select bank/patch described above.
4. Play virtual keyboard with mouse

You can also use the example project attached.

#### Expected behavior
Soundfount sounds correctly.

#### Actual behavior
Soundfont sounds incorrectly.

#### Screenshot
N/A

#### Affected LMMS versions

LMMS 1.3.0-alpha.1.354+ge1d3ecb18 @ master branch

#### System info

Arch Linux (Linux 6.5.2-arch1-1 x86_64)
I installed [these versions of LMMS via AUR](https://aur.archlinux.org/packages/lmms-git).

**Comment by YohananDiamond** [comment]
Glad it wasn't a problem only here. It also happens with some patches on the [GeneralUser_GS](https://schristiancollins.com/generaluser.php) soundfont (very noticeable on the "Honky-Tonk" patch).

**Comment by DomClark** [comment]
@syusui-s and @YohananDiamond - Could you test #6924 (downloadable at https://lmms.io/download/pull-request/6924) and see if that fixes this issue?

**Comment by syusui-s** [comment]
@DomClark

I tested it and I think it worked correctly.

I exported tracks made with #6924, and compared them to ones made with e1d3ecb1 by using Audacity. If I play the original track and the same track which phase is inverted at the same time, there should be no sound in theory. And, there are mostly no difference. There were just a little bit volume difference, so I could hear the tiny sounds but this difference was caused even if I export tracks with the same version twice.

**Comment by DomClark** [comment]
Thanks for testing! I'll mark that PR as fixing this issue.

**Comment by YohananDiamond** [comment]
Also tested it - working fine now as well!

**Comment by musikBear** [comment]
Follow up question
Do we know how many semitones this is 'off', and do we know if this number of semitones are constant?
I an thinking on older projects and a generalized method for re-tuning soundfonts in old projects so they will sound _as intended_ also in 1.3, where this fix will _now_ alter the soundfont output @DomClark

**Comment by DomClark** [comment]
> Do we know how many semitones this is 'off', and do we know if this number of semitones are constant?

The number of semitones this is off by depends on the SoundFont, patch, and note, but will be constant for each (i.e. it won't change over time).

> I an thinking on older projects and a generalized method for re-tuning soundfonts in old projects so they will sound _as intended_ also in 1.3, where this fix will _now_ alter the soundfont output

This bug wasn't present in older versions of LMMS. I introduced it in #6602, and fixed it shortly afterwards, so we don't need to worry about backwards compatibility.
