### ISSUE TITLE
Cannot checkout an older branch anymore (due to problems with resid)

### ISSUE THREAD

**Issue by michaelgregorius** [LMMS/lmms#6916]
Hi @sakertooth,

my master is on 8b94bd8e654653ea8e1b33428e80b95e29bebcb7 and I cannot checkout my older branch that's used for #2068 anymore. I am getting the following error message:
```
$ git checkout dynamic-effect-dialog
Warnung: unable to rmdir 'plugins/Sid/resid/resid': Das Verzeichnis ist nicht leer
Schwerwiegend: Kein Git-Repository: plugins/Sid/resid/../../../.git/modules/plugins/Sid/resid
```
The german text means: "the directory is not empty" and "no Git repository".

I assume that this is caused by the switch of resid's repository in commit 49c713df5bad0c7285dd04d236ea3f5e9f3c34ef. The branch that I want to switch to does not contain this commit yet.

I guess that this might affect all developer who have pulled the changes and that want to switch to older branches.

Can you please advise?

**Comment by sakertooth** [comment]
Go into the root of the repository and delete both ``plugins/Sid/resid`` and ``.git/modules/plugins/Sid/resid``, and then run ``git submodule update --init --recursive``. This seems to fix the issue.

**Comment by michaelgregorius** [comment]
Thanks, @sakertooth! This has fixed the problem.
