### ISSUE TITLE
Some SF2 patches play inconsistently

### ISSUE THREAD

**Issue by Oktayey** [LMMS/lmms#6922]
### Bug Summary
The commit https://github.com/LMMS/lmms/commit/4804ab678501f9c746b4b2c870f0a323f7d3953b appears to have introduced a bug where some SF2 patches do not play correctly.

#### Steps to reproduce
On lmms-1.3.0-alpha.1.351 or later, place a line of the same note in the piano roll, and play it with either with the "Orchestra Hit" patch in the Touhou soundfont (bank 0, patch 55) or the "Oct Saw Lead" patch in the SGM-V2.01 soundfont (bank 35, patch 81).
#### Expected behavior
Each note sounds similar.
#### Actual behavior
The notes can sound jarringly different; it sounds as if they exhibit a sort of phasing effect, like if they played multiple times, but extremely close together.
#### Screenshot
https://github.com/LMMS/lmms/commit/3263bfd555982d52735a19763eff26f4be7e0eb7

https://github.com/LMMS/lmms/assets/6764216/21b8fac6-95fe-484b-a41c-cefda4920337

https://github.com/LMMS/lmms/commit/4804ab678501f9c746b4b2c870f0a323f7d3953b

https://github.com/LMMS/lmms/assets/6764216/40a18f50-d4f0-4960-9736-d98e2f29c3f6

#### Affected LMMS versions
lmms-1.3.0-alpha.1.425+g8b94bd8e6-mingw-win64 (latest)
lmms-1.3.0-alpha.1.357+gde062d6c5-mingw-win64
lmms-1.3.0-alpha.1.351+g4804ab678-mingw-win64 (first)

EDIT: I forgot to mention the relevant pull request: https://github.com/LMMS/lmms/pull/6602

**Comment by DomClark** [comment]
Reproduced. We implement per-note detuning for soundfonts by setting the value of the `GEN_COARSETUNE` generator for each voice. However, some soundfonts already set a custom value for this internally.

For example, here's a screenshot of the "Orchestra Hit" instrument in the Touhou soundfont, opened in Polyphone. Look at the "Tuning (semi-tones)" row:
![image](https://github.com/LMMS/lmms/assets/1873225/a697a3bb-2c3a-419a-94b9-baca9367c5a3)
In this case, one set of voices is supposed to be tuned down an octave. Your description of the resulting sound is indeed exactly what's happening: the voices are instead all playing at the same pitch, producing a phasing effect.

We need to find an alternative way to set the detuning without overwriting existing values. I'll look into this.

Note that the per-note panning implementation shouldn't cause any such issues - we use the `GEN_CUSTOM_BALANCE` generator for that, which is unique to FluidSynth and not part of the SoundFont specification, and so shouldn't be used within any soundfonts.
