### ISSUE TITLE
SIGSEGV during render

### ISSUE THREAD

**Issue by psilhavy** [LMMS/lmms#6942]
### Bug Summary
SIGSEGV while "lmms render"
#### Steps to reproduce
lmms render Aprojects-PATH/A.mmpz  -o /m/export/A.flac -f flac -s 96000 -x 1 -i sincbest

particular project doesn't matter, everything end with SIGSEGV here.

#### Expected behavior
new complete .flac
#### Actual behavior
only 122 byte .flac + SIGSEGV
#### Affected LMMS versions
current master 
LMMS 1.3.0-alpha.1.437+g476a56e71
(Linux x86_64, Qt 5.15.10, GCC 13.2.0)

no problem with LMMS 1.3.0-alpha.1.334+g5cbf2c528
(Linux x86_64, Qt 5.15.2, GCC 12.2.0)

#### Logs
<details>
  <summary>Click to expand</summary>
<pre>
|-                                                 |      0%   |  
Thread 22 "lmms::ProjectRe" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7f1d673ff6c0 (LWP 18177)]
lmms::InstrumentTrack::play (this=0x7f1d97759228, _start=..., 
    _frames=<optimized out>, _offset=-1753908096, _clip_num=-1)
    at /usr/src/lmms-master/include/GuiApplication.h:64
64              PianoRollWindow* pianoRoll() { return m_pianoRoll; }
(gdb) bt
#0  lmms::InstrumentTrack::play(lmms::TimePos const&, short, int, int)
    (this=0x7f1d97759228, _start=..., _frames=<optimized out>, _offset=-1753908096, _clip_num=-1) at /usr/src/lmms-master/include/GuiApplication.h:64
#1  0x00000000005ed863 in lmms::Song::processNextBuffer() (this=0x235d550)
    at /usr/src/lmms-master/src/core/Song.cpp:344
#2  0x000000000055b32e in lmms::AudioEngine::renderStageNoteSetup()
    (this=this@entry=0x234f8e0)
    at /usr/src/lmms-master/src/core/AudioEngine.cpp:380
#3  0x000000000055b474 in lmms::AudioEngine::renderNextBuffer()
    (this=0x234f8e0) at /usr/src/lmms-master/src/core/AudioEngine.cpp:465
#4  0x00000000005fd55d in lmms::AudioEngine::nextBuffer()
    (this=<optimized out>) at /usr/src/lmms-master/include/AudioEngine.h:351
#5  lmms::AudioDevice::getNextBuffer(std::array<float, 2ul>*)
    (this=this@entry=0xaeb98c0, _ab=0x8f18f90)
    at /usr/src/lmms-master/src/core/audio/AudioDevice.cpp:85
#6  0x00000000005fd57d in lmms::AudioDevice::processNextBuffer()
    (this=0xaeb98c0) at /usr/src/lmms-master/src/core/audio/AudioDevice.cpp:68
#7  0x00000000005daa39 in lmms::ProjectRenderer::run() (this=0xac85e20)
    at /usr/src/lmms-master/src/core/ProjectRenderer.cpp:188
#8  0x00007f1d9b0d3819 in  () at /usr/lib64/libQt5Core.so.5
#9  0x00007f1d9aa93caa in start_thread () at /lib64/libc.so.6
#10 0x00007f1d9ab1dd9c in clone3 () at /lib64/libc.so.6
(gdb) 

</pre>
</details>

**Comment by DomClark** [comment]
Looks like #6297 is to blame - it introduced a GUI dependency into the play handle processing code.
