### ISSUE TITLE
Guitar plugin and stretching samples suggestion

### ISSUE THREAD

**Issue by ParrotGamesGGHub** [LMMS/lmms#6948]
# Greetings, amazing developers of LMMS!
I have 3 ideas, that can help the composers! 
1. Sample editing
It can be kinda annoying, if you double-click the sample on sample track... And program offers you to replace the sample instead of editing it. So, you can edit samples, when you double-click them in Audio File Processor, but there will be no arpeggio tab. And logically, you will be able to replace the sound through the plugin.
2. Stretch
It is pretty sad, that LMMS has no sample stretching, so please, add the stretch knob in Audio File Processor and two stretching types (resample, when while you stretch the sound, it changes pitch, and stretch, when sample does not change its own pitch). Please, add this feature in the 1.2 patch at least!
3. Distortion Guitar plugin
Can you add the distortion guitar plugin like FL Studio's FL Slayer? I have even got the name suggestion: RoughSlayer.

Thank you for reading my suggestion! Hope you are able to make this real. Good luck!
Sincerely, DoubRasp aka Parrot GamesGG

**Comment by Spekular** [comment]
I'm not fully sure what sort of editing functionality you're looking for in point 1, but samples can be cut and reversed in master. Fade in/out is in progress at #5616, and additional slicing functionality at #6857. See also #4971.

As for point 2, this is included in #1471.

For point 3, I would suggest using one of the existing distortion plugins or loading a third party plugin (see for example [this list](https://bedroomproducersblog.com/2012/02/21/bpb-freeware-studio-best-free-guitar-amp-simulator-vstau-plugins/) of free guitar amp plugins).
