### ISSUE TITLE
Enhancement: A design-idea on ghost-notes

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#696]
I have an idea for a 'ghost-note design. 
User has made a track of normal notes. 
User now need to make a copy of this track
User can drag new preset into the copy-track (and rename if wanted)
In the copy-track user select new context-menu-item:
 "Ghost all this tracks notes (not reversable)"
LMMS engine travers the tracks note event and and set property vol== -1 
(does lmms heuristics allow negative vol??*)
Negative volume denotes a ghosted note 
Heuristic for ghosted notes are:
* should not logically count as note-events (cpu-saving
* should be drawn in suited alpha-val, -but- in full length (in contrast to velocity changed notes

Current copy-track would now have -all- note-events visible, but no longer playable!
New notes added to the copy-track, would however act exactly as default notes, and be playable as normal notes.
Iow. - Notes that existed -before- the copy-event are in fact now ghosts-notes.
Because ghost-notes has a negative volume (-1), it would be possible to remove all ghost-notes, with a 'simple'(?) transverse of the data-structure, if user decides to redo something.
(Perhaps an even sexier option exists in the datastructure or how the notes data are kept internaly??
What are your thoughts?

((for copyright reason an other name like 'phantom-notes' should perhaps be used))

**Comment by tresf** [comment]
Yeah, it should.  Thanks.
