### ISSUE TITLE
Voice Recorder

### ISSUE THREAD

**Issue by BikerFelan** [LMMS/lmms#6963]
It would be so cool if you add a voice recording feature like fl studio has. It would facilitate a lot, instead of using audacity to record sound and then when you have finished recording, convert the file to waw format and then put it in lmms.

**Comment by zonkmachine** [comment]
@BikerFelan Thanks for the input!

This is a much asked for feature and is tracked in https://github.com/LMMS/lmms/issues/1471.
There has been a few attempts to get the ball rolling and here is one of the latest https://github.com/LMMS/lmms/pull/5990.
It may be implemented in the next major release, lmms-1.3.

I'm closing this as a duplicate
