### ISSUE TITLE
Bad URL in Docs

### ISSUE THREAD

**Issue by bboboedov** [LMMS/lmms#6965]
# Please search the issue tracker for existing bug reports before submitting your own. Delete this line to confirm no similar report has been posted yet.

### Bug Summary

In chapter:

7.3.4 FX-Mixer
Expressions in side-chaining
ttps://youtu.be/ntzWiufjkko
^

'h' missing

#### Logs
<details>
  <summary>Click to expand</summary>
<pre>

</pre>
</details>

**Comment by Rossmaxx** [comment]
Please clean up the message and remove the template message at the top before posting. You can just edit it out for now. Same with your other issues.

**Comment by PhysSong** [comment]
@bboboedov Fixed.
@Rossmaxx The manual at https://docs.lmms.io/user-manual/ is not editable by everyone.
