### ISSUE TITLE
Interface note

### ISSUE THREAD

**Issue by bboboedov** [LMMS/lmms#6966]
### Enhancement Summary

I am new to the LMMS program and at first it seemed to me that there was not enough list search (samples, etc.). There was no such problem in the Blender program, because there the search field is at the top of the list and marked with a magnifying glass icon.

**Comment by michaelgregorius** [comment]
Pull request #6968 makes the search a bit more prominent by adding a magnifying glass to several search line edits.

![Screenshot_20231106_114347](https://github.com/LMMS/lmms/assets/9293269/7ef17cfd-b9e5-4c47-b9b6-050f1d9f0d5d)

Effect selection:

![Screenshot_20231106_114459](https://github.com/LMMS/lmms/assets/9293269/bda715ee-935e-434e-a243-9b46dce33366)
