### ISSUE TITLE
Changing a track's color instantly crashes program

### ISSUE THREAD

**Issue by SalutanisOrkonus** [LMMS/lmms#6987]
### Bug Summary
When changing the color of a track (instrument, automation, sample) (FX Channels seem to be fine), the program nearly instantaneously crashes before it even pulls up the color window.
#### Steps to reproduce
Add a track in the song editor and go to change its track color.
#### Expected behavior
It pulls up the window for picking a color, and then works.
#### Actual behavior
Bye-bye program
#### Affected LMMS versions
g609c008a7

**Comment by zonkmachine** [comment]
Confirmed.

If you first pick a color for the track with the 'Track color -> Pick random' option, now first can you change the color manually without crashing.

**Comment by zonkmachine** [comment]
This was, not surprising, introduced in  609c008 .

**Comment by DomClark** [comment]
Assigning this to myself as there are some changes I want to make in the area anyway.
