### ISSUE TITLE
MIDI export support

### ISSUE THREAD

**Issue by Blue-EyesWhiteDragon** [LMMS/lmms#699]
The one thing that could make LMMS a lot handier, and lot more "high-tier", is an export MIDI option. Much like FL Studio's own file menu, this could be added in the Piano Roll itself, or could rather be a option on the main file menu; e.g. File > Export Tracks To MIDI Files. These could, eventually, have an option for MIDI channels, and other features. I think this may be something to look into. I will look into the matter myself but I would appreciate if someone would notify me if this has been done, not that I know of (I have the latest version and found nothing like it), or if someone has a source code I could finish writing or help on. I would love to see this feature implemented!

Thanks for reading!

Happy Coding, C you soon! 
- BEWD

**Comment by Blue-EyesWhiteDragon** [comment]
Thanks, tresf!

**Comment by operatorium-org** [comment]
If you are looking for build including "MIDI export" feature you can get it from my google-drive: https://goo.gl/j7PHkP
Be careful, this was built from lmms-master and is unstable... but "MIDI export" feature works for me.

You can also use LoopBe1 (a Free Virtual MIDI Driver) to "export" MIDI:
- install it: http://www.nerds.de/en/loopbe1.html
- "other MIDI software": 
    - set MIDI input to "LoopBe Internal MIDI"
    - record MIDI
- LMMS: 
    - set MIDI output (on track options) to play on "LoopBe Internal MIDI" 
    - play track

**Comment by tresf** [comment]
@imagine-tinh thanks.  This feature will be available with the release of 1.2.

**Comment by imagine-tinh** [comment]
When?

**Comment by tresf** [comment]
> When?

TBD.

**Comment by imagine-tinh** [comment]
@tresf Is there any alpha/beta/milestone release of v.1.2?

**Comment by tresf** [comment]
@imagine-tinh Not yet.  There are beta builds, but nothing worth using on a daily basis currently.

**Comment by sonvirgo** [comment]
any thing news
