### ISSUE TITLE
 Graphical update missing on maximize 

### ISSUE THREAD

**Issue by eagles051387** [LMMS/lmms#70]
Simple glitch: When maximizing, any block on the Song Editor that goes past the window's previous size will not be rendered. The window can be updated by simply moving a track to another place, though.
To reproduce:
1. Have several instruments and blocks of notes on the Song Editor.
2. Shrink the Song Editor to the smallest size possible.
3. Maximize.
4. If you can't notice any missing note blocks, just focus your eyes on a blank spot, move a track out of place, and you should spot the missing blocks pop up into view.

**Comment by zonkmachine** [comment]
I can reproduce this on LinuxMint-17.3 and just about any lmms version down to 0.4.90 .

 * Launch lmms
 * Open Demos->Skiessi->RandomProjectNumber14253

Open
![skiessi](https://user-images.githubusercontent.com/6368949/39892294-71693c46-54a0-11e8-963d-24f3093e59d4.png)

Maximize
![skiessi2](https://user-images.githubusercontent.com/6368949/39892302-7875879c-54a0-11e8-9ecb-da03f508e032.png)

Move horizontal scrollbar
![skiessi3](https://user-images.githubusercontent.com/6368949/39892314-801be950-54a0-11e8-9fd6-336691432d7f.png)

**Comment by zonkmachine** [comment]
If I drag the Song-Editor down so the lower part with the horizontal scrollbar is ever so little outside of the canvas and then maximize it, the full song is showing.

**Comment by zonkmachine** [comment]
Could be an issue with x11. https://doc.qt.io/archives/qt-4.8/application-windows.html#window-geometry

> Nor does X11 provide a way to maximize a window. QWidget::showMaximized() has to emulate the feature. Its result depends on the result of QWidget::frameGeometry() and the capability of the window manager to do proper window placement, neither of which can be guaranteed.

**Comment by musikBear** [comment]
Actually, its the whole win-border that is 'gone'
Look at this picture
![songeddnomaxwinborder](https://user-images.githubusercontent.com/6662066/39926755-711b914a-5530-11e8-9f75-ada4677309fe.JPG)

There are two states on the same picture. Top you see that if a right-ckick is done on the win-border, lmms shows a context menu.
Not 'shown' is the fact that a double-click will anywhere on this border, will maximize song-editor.
Second part shows the window maximized. It is now not possible to get a context-menu, nor will double-click toggle the size.
All expected win-border features are missing.
This is also the case for 
* piano-roll
* B&B
* Aut

But *not* project-notes!
The other 2 sub-windows rack & mixer has maximizing disabled

**Comment by zonkmachine** [comment]
> All expected win-border features are missing.

Under what circumstances? Sorry, I don't get your post. I see no context menu related issues.

**Comment by musikBear** [comment]
@zonkmachine  > Under what circumstances?

with maximixed windows. I showed the 'context-thing' because it is a normal windows-feature, that a context-menu, can be accessed with right-click, nomatter if the window is popped out, or maximized. The picture shows, that in lmms, only popped-out windows *has* a normal windows-top-bar. Maximized windows does not have this normal windows-bar, in lmms.

**Comment by zonkmachine** [comment]
This issue is about song elements not showing up when you maximize the Song-Editor. The issue only appear when all elements on the canvas prior to maximizing is within the canvas.
Do you see this precise issue on Windows?

**Comment by zonkmachine** [comment]
@musikBear I understand what you mean now. It's a completely different issue and by design. Now back to the original topic... please confirm if you see this issue or not.

**Comment by zonkmachine** [comment]
@musikBear I've updated the middle picture in [my comment above](https://github.com/LMMS/lmms/issues/70#issuecomment-388175225) for clarity.

**Comment by Sauerstoffdioxid** [comment]
I can confirm on Windows.
LMMS 1.2-rc5 x64 (from the website)

**Comment by zonkmachine** [comment]
OK. So it's our issue then. Poked it some more...

If I stick `updateGeometry();` first in [this function](https://github.com/LMMS/lmms/blob/5d90aecac90c16e9a4ec0b0450539cbe17ae7f6a/src/gui/editors/SongEditor.cpp#L720:L723) the issue is fixed.

```cpp
void SongEditorWindow::resizeEvent(QResizeEvent *event)
{
   updateGeometry();
   emit resized();
}
```

**Comment by musikBear** [comment]
@zonkmachine -Yes i have experienced invisible blocks, but they did replay, and toggling song-editor up-down or dragging an other window over the invisible blocks, made them re-appear. so indeed a *graphical* glitch, witch is loosely connected to toggled sub-windows.
I dont think i have seen this in RC's since 1.1.3, but *that* may be because i by rule, only saved projects, with all windows closed! (And could use a 'shut-all-open-windows' button :'P )

So the 'odd' windows-tittle-bar behaviour is by design? ..Hmm

**Comment by zonkmachine** [comment]
> I dont think i have seen this in RC's since 1.1.3, but that may be because i by rule, only saved projects, with all windows closed!

The question still stands. Can you **replicate** the issue with the given steps? No guessing or anecdotes from earlier versions. lmms-1.2.0-rc5.

 * Restart LMMS
 * Open a large project
 * All windows closed except Song-Editor
 * Adjust the size of the Song-Editor to be within the canvas
 * Maximize the Song-Editor

Do you see missing blocks. Yes/No?

**Comment by musikBear** [comment]
Yes (win32 sp3 xp RC5.6545
![disapearedatmaximixe](https://user-images.githubusercontent.com/6662066/40000335-d9e90eca-578b-11e8-8fed-1d432378a3a4.JPG)
That single block is all i have, after smallest possible song-ed. window, is maximized. You are correct!

**Comment by PhysSong** [comment]
`TrackContentWidget::changePosition` is called when the viewport for song editor changes. It hides invisible TCOs(actually moves TCOs to outside of visible area).
However, the function isn't called when the window is maximized/restored.

**Comment by PhysSong** [comment]
This change should work:
```diff
diff --git a/include/SongEditor.h b/include/SongEditor.h
index db4d7d781..e03c63280 100644
--- a/include/SongEditor.h
+++ b/include/SongEditor.h
@@ -155,6 +155,7 @@ public:
 
 protected:
 	virtual void resizeEvent( QResizeEvent * event );
+	virtual void changeEvent( QEvent * );
 
 protected slots:
 	void play();
diff --git a/src/gui/editors/SongEditor.cpp b/src/gui/editors/SongEditor.cpp
index 5eb7ff6e2..2e0a19ab4 100644
--- a/src/gui/editors/SongEditor.cpp
+++ b/src/gui/editors/SongEditor.cpp
@@ -723,6 +723,13 @@ void SongEditorWindow::resizeEvent(QResizeEvent *event)
 }
 
 
+void SongEditorWindow::changeEvent(QEvent *event)
+{
+	QWidget::changeEvent(event);
+	m_editor->realignTracks();
+}
+
+
 void SongEditorWindow::play()
 {
 	emit playTriggered();
```

@zonkmachine can you test this?

**Comment by zonkmachine** [comment]
> @zonkmachine can you test this?

Worked! I haven't tested it extensively from lack of computer power for the moment but this seem to fix the issue right up!
