### ISSUE TITLE
"LMMS is damaged and can't be opened"

### ISSUE THREAD

**Issue by sorasakurakitty** [LMMS/lmms#7003]
### Bug Summary
Trying to launch the latest LMMS nightly macOS build from lmms.io results in an error.
#### Steps to reproduce
Attempt to launch LMMS
#### Expected behavior
LMMS launches
#### Actual behavior
LMMS does not launch
#### Screenshot
<img width="372" alt="image" src="https://github.com/LMMS/lmms/assets/72764732/5635bf6f-dd1d-4037-a422-4f43e21e25a4">

#### Affected LMMS versions
LMMS g67ce16777

#### Logs
Did not create a log.

**Comment by sorasakurakitty** [comment]
If it helps, I'm using a 2022 M2 MacBook Pro 13".

**Comment by Rossmaxx** [comment]
Pinging @tresf

**Comment by tresf** [comment]
```bash
sudo xattr -r -d com.apple.quarantine /Applications/LMMS.app/
```

**Comment by sorasakurakitty** [comment]
Thank you! That fixed it.
