### ISSUE TITLE
Silent app crash in `lmms-1.3.0-alpha.1.102+g89fc6c960-mingw-win64` release

### ISSUE THREAD

**Issue by headquarter8302** [LMMS/lmms#7020]
### Bug Summary
After installing a bleeding edge LMMS release (forgot which one), the previously runnable `lmms-1.3.0-alpha.1.102+g89fc6c960-mingw-win64` cannot launch properly.

I am unable to pinpoint what exactly is causing the crash, since Windows' automatic crash dump didn't help much, and there are no obvious causes.

Windows 10 19041 22H2

#### Steps to reproduce
1. Install bleeding edge release. Then uninstall
2. Install 1.3.0-alpha.1
3. Run the program

#### Expected behavior
The app to start normally

#### Actual behavior
A silent crash

#### Affected LMMS versions
* 1.3.0-alpha.1 [`lmms-1.3.0-alpha.1.102+g89fc6c960-mingw-win64`]

#### Logs
N/a

I've attached some of the crash logs from Windows:
<details>
<pre>
Faulting application name: lmms.exe, version: 0.0.0.0, time stamp: 0x60846524
Faulting module name: lmms.exe, version: 0.0.0.0, time stamp: 0x60846524
Exception code: 0xc0000005
Fault offset: 0x0000000000015681
Faulting process id: 0x2ac0
Faulting application start time: 0x01da2a421b5fbe8a
Faulting application path: C:\Program Files\LMMS\lmms.exe
Faulting module path: C:\Program Files\LMMS\lmms.exe
Report Id: 09babd84-7849-4c77-91c8-bcfaeb29aa63
Faulting package full name: 
Faulting package-relative application ID: 
</pre>
</details>
<details>
<summary>WER log</summary>
<pre>
Version=1
EventType=APPCRASH
EventTime=133465602383554872
ReportType=2
Consent=1
UploadTime=133465602386684176
ReportStatus=268435456
ReportIdentifier=99ffb166-dade-4e92-ab00-e5a6275815ec
IntegratorReportIdentifier=09babd84-7849-4c77-91c8-bcfaeb29aa63
Wow64Host=34404
NsAppName=lmms.exe
AppSessionGuid=00002ac0-0001-0323-8abe-5f1b422ada01
TargetAppId=W:00067ba07564ec46eb5e2f6241703b14385d0000ffff!000097c3925058b943809924c46846b52ce3cb82b40d!lmms.exe
TargetAppVer=2021//04//24:18:36:20!70993e3!lmms.exe
BootId=4294967295
TargetAsId=6475
IsFatal=1
EtwNonCollectReason=1
Response.BucketId=99337722e4ab0b75680e43a8307dbaee
Response.BucketTable=4
Response.LegacyBucketId=1733397296231332590
Response.type=4
Sig[0].Name=Application Name
Sig[0].Value=lmms.exe
Sig[1].Name=Application Version
Sig[1].Value=0.0.0.0
Sig[2].Name=Application Timestamp
Sig[2].Value=60846524
Sig[3].Name=Fault Module Name
Sig[3].Value=lmms.exe
Sig[4].Name=Fault Module Version
Sig[4].Value=0.0.0.0
Sig[5].Name=Fault Module Timestamp
Sig[5].Value=60846524
Sig[6].Name=Exception Code
Sig[6].Value=c0000005
Sig[7].Name=Exception Offset
Sig[7].Value=0000000000015681
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=10.0.19045.2.0.0.768.100
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=4105
DynamicSig[22].Name=Additional Information 1
DynamicSig[22].Value=690a
DynamicSig[23].Name=Additional Information 2
DynamicSig[23].Value=690afd32e4ddf952ff71ffd9700c7112
DynamicSig[24].Name=Additional Information 3
DynamicSig[24].Value=af86
DynamicSig[25].Name=Additional Information 4
DynamicSig[25].Value=af861230e7a6f13e9c5a52072bc47da0
UI[2]=C:\Program Files\LMMS\lmms.exe
UI[3]=lmms.exe has stopped working
UI[4]=Windows can check online for a solution to the problem.
UI[5]=Check online for a solution and close the program
UI[6]=Check online for a solution later and close the program
UI[7]=Close the program
LoadedModule[0]=C:\Program Files\LMMS\lmms.exe
LoadedModule[1]=C:\Windows\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\Windows\System32\KERNEL32.DLL
LoadedModule[3]=C:\Windows\System32\KERNELBASE.dll
LoadedModule[4]=C:\Windows\System32\ADVAPI32.dll
LoadedModule[5]=C:\Windows\System32\msvcrt.dll
LoadedModule[6]=C:\Windows\System32\sechost.dll
LoadedModule[7]=C:\Windows\System32\RPCRT4.dll
LoadedModule[8]=C:\Windows\System32\GDI32.dll
LoadedModule[9]=C:\Windows\System32\win32u.dll
LoadedModule[10]=C:\Windows\System32\gdi32full.dll
LoadedModule[11]=C:\Windows\System32\msvcp_win.dll
LoadedModule[12]=C:\Windows\System32\ucrtbase.dll
LoadedModule[13]=C:\Windows\System32\USER32.dll
LoadedModule[14]=C:\Windows\SYSTEM32\WINMM.dll
LoadedModule[15]=C:\Program Files\LMMS\libgcc_s_seh-1.dll
LoadedModule[16]=C:\Program Files\LMMS\libportaudio.dll
LoadedModule[17]=C:\Windows\System32\ole32.dll
LoadedModule[18]=C:\Windows\System32\combase.dll
LoadedModule[19]=C:\Windows\System32\SETUPAPI.dll
LoadedModule[20]=C:\Windows\System32\cfgmgr32.dll
LoadedModule[21]=C:\Windows\System32\bcrypt.dll
LoadedModule[22]=C:\Program Files\LMMS\libstdc++-6.dll
LoadedModule[23]=C:\Program Files\LMMS\Qt5Core.dll
LoadedModule[24]=C:\Windows\System32\SHELL32.dll
LoadedModule[25]=C:\Windows\System32\WS2_32.dll
LoadedModule[26]=C:\Program Files\LMMS\Qt5Xml.dll
LoadedModule[27]=C:\Program Files\LMMS\libmp3lame-0.dll
LoadedModule[28]=C:\Program Files\LMMS\libogg-0.dll
LoadedModule[29]=C:\Program Files\LMMS\Qt5Gui.dll
LoadedModule[30]=C:\Program Files\LMMS\libsamplerate-0.dll
LoadedModule[31]=C:\Program Files\LMMS\libsndfile-1.dll
LoadedModule[32]=C:\Program Files\LMMS\Qt5Widgets.dll
LoadedModule[33]=C:\Program Files\LMMS\libvorbisenc-2.dll
LoadedModule[34]=C:\Windows\SYSTEM32\MPR.dll
LoadedModule[35]=C:\Windows\SYSTEM32\VERSION.dll
LoadedModule[36]=C:\Program Files\LMMS\libvorbisfile-3.dll
LoadedModule[37]=C:\Windows\SYSTEM32\OPENGL32.dll
LoadedModule[38]=C:\Program Files\LMMS\SDL.dll
LoadedModule[39]=C:\Program Files\LMMS\zlib1.dll
LoadedModule[40]=C:\Program Files\LMMS\libpng16-16.dll
LoadedModule[41]=C:\Windows\SYSTEM32\dwmapi.dll
LoadedModule[42]=C:\Windows\SYSTEM32\UxTheme.dll
LoadedModule[43]=C:\Program Files\LMMS\libFLAC-8.dll
LoadedModule[44]=C:\Program Files\LMMS\libvorbis-0.dll
LoadedModule[45]=C:\Windows\SYSTEM32\GLU32.dll
LoadedModule[46]=C:\Windows\System32\IMM32.DLL
LoadedModule[47]=C:\Program Files\LMMS\platforms\qwindows.dll
LoadedModule[48]=C:\Windows\System32\OLEAUT32.dll
LoadedModule[49]=C:\Windows\SYSTEM32\kernel.appcore.dll
LoadedModule[50]=C:\Windows\System32\bcryptPrimitives.dll
LoadedModule[51]=C:\Windows\System32\SHCore.dll
LoadedModule[52]=C:\Windows\SYSTEM32\windows.storage.dll
LoadedModule[53]=C:\Windows\SYSTEM32\Wldp.dll
LoadedModule[54]=C:\Windows\System32\shlwapi.dll
LoadedModule[55]=C:\Windows\SYSTEM32\profapi.dll
LoadedModule[56]=C:\Windows\system32\userenv.dll
State[0].Key=Transport.DoneStage1
State[0].Value=1
OsInfo[0].Key=vermaj
OsInfo[0].Value=10
OsInfo[1].Key=vermin
OsInfo[1].Value=0
OsInfo[2].Key=verbld
OsInfo[2].Value=19045
OsInfo[3].Key=ubr
OsInfo[3].Value=3693
OsInfo[4].Key=versp
OsInfo[4].Value=0
OsInfo[5].Key=arch
OsInfo[5].Value=9
OsInfo[6].Key=lcid
OsInfo[6].Value=1033
OsInfo[7].Key=geoid
OsInfo[7].Value=39
OsInfo[8].Key=sku
OsInfo[8].Value=100
OsInfo[9].Key=domain
OsInfo[9].Value=0
OsInfo[10].Key=prodsuite
OsInfo[10].Value=768
OsInfo[11].Key=ntprodtype
OsInfo[11].Value=1
OsInfo[12].Key=platid
OsInfo[12].Value=10
OsInfo[13].Key=sr
OsInfo[13].Value=0
OsInfo[14].Key=tmsi
OsInfo[14].Value=222439836
OsInfo[15].Key=osinsty
OsInfo[15].Value=1
OsInfo[16].Key=iever
OsInfo[16].Value=11.3636.19041.0-11.0.1000
OsInfo[17].Key=portos
OsInfo[17].Value=0
OsInfo[18].Key=ram
OsInfo[18].Value=3947
OsInfo[19].Key=svolsz
OsInfo[19].Value=206
OsInfo[20].Key=wimbt
OsInfo[20].Value=0
OsInfo[21].Key=blddt
OsInfo[21].Value=191206
OsInfo[22].Key=bldtm
OsInfo[22].Value=1406
OsInfo[23].Key=bldbrch
OsInfo[23].Value=vb_release
OsInfo[24].Key=bldchk
OsInfo[24].Value=0
OsInfo[25].Key=wpvermaj
OsInfo[25].Value=0
OsInfo[26].Key=wpvermin
OsInfo[26].Value=0
OsInfo[27].Key=wpbuildmaj
OsInfo[27].Value=0
OsInfo[28].Key=wpbuildmin
OsInfo[28].Value=0
OsInfo[29].Key=osver
OsInfo[29].Value=10.0.19041.3693.amd64fre.vb_release.191206-1406
OsInfo[30].Key=buildflightid
OsInfo[31].Key=edition
OsInfo[31].Value=CoreSingleLanguage
OsInfo[32].Key=ring
OsInfo[32].Value=Retail
OsInfo[33].Key=expid
OsInfo[33].Value=FX:119E26AD,FX:11C0E96C,FX:11C6E5C2,FX:11C7EB6A,FX:11C9408A,FX:11C940DB,FX:11CB9A9F,FX:11CB9AC1,FX:11CC111C,FX:11D5BFCD,FX:11DF5B12,FX:11DF5B75,FX:1240931B,FX:124117A5,FX:124AB92C,FX:124B38D0,FX:127CEABB,FX:127FC878,FX:1283FFE8,FX:12840617,FX:128979F9,FX:128EBD7E,FX:129135BB,FX:129E053F,FX:12A74DB5,FX:12AB734D,FX:12B8450E,FX:12BD6E73,FX:12C3331B,FX:12C7D66E,FX:12CDE644,FX:12D1574C,FX:12D281C4,FX:12D8EAA1,FX:12DD15C2
OsInfo[34].Key=fconid
OsInfo[35].Key=containerid
OsInfo[36].Key=containertype
OsInfo[37].Key=edu
OsInfo[37].Value=0
FriendlyEventName=Stopped working
ConsentKey=APPCRASH
AppName=lmms.exe
AppPath=C:\Program Files\LMMS\lmms.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=9DE8125E8CE8D60385D6788390112AE8
MetadataHash=-1576428790
</pre>
</details>

**Comment by headquarter8302** [comment]
I also apparently lost all instrument references from the piano roll? Is it due to the version difference and how they handled putting things on the roll, or did the bleeding edge copy corrupted the files?

**Comment by Rossmaxx** [comment]
Try deleting the `.lmmsrc.xml` file from your users folder to see if that fixes it.

**Comment by headquarter8302** [comment]
I have no idea why that works, but it works.

Thank you

**Comment by Rossmaxx** [comment]
> I have no idea why that works, but it works.

Basically, the lmmsrc file is the place where your settings gets stored. It also stores the versions of your lmms install. When you try to open the older version of lmms (the one which you couldn't open after installing the nightly), it corrupts this file from having two mutually incompatible installs.

Since your issue is fixed, can you consider closing this one out.

**Comment by headquarter8302** [comment]
I see, alright then. Thanks a lot
