### ISSUE TITLE
ZynAddSubFX "Show GUI" broken (Apple)

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms#703]
The ZynAddSubFX instrument plugin plays audio in OSX, however the "Show GUI" button crashes the software.

The crash seems to be caused within the `initPlugin()` or possibly the `reloadPlugin()` code although this could be a missing library reference as well. ([view initPlugin() code here](https://github.com/LMMS/lmms/blob/stable-1.0/plugins/zynaddsubfx/ZynAddSubFx.cpp#L424))

[Click here for the list of libraries that load when lmms is executed](https://gist.github.com/tresf/136df4fb632283345976)
[Click here for a partial stacktrace of the crash](https://gist.github.com/tresf/96dd4d45acbf6917245d)

Some outstanding `QSharedMemory` bugs:
https://bugreports.qt-project.org/browse/QTBUG-27765
https://bugreports.qt-project.org/browse/QTBUG-5123

I notice fltk isn't in the list when LMMS loads.  I believe that is normal, as only the Remote process should load it.  If I had a way of launching ZynAddSubFX without LMMS it might shed some more light on this issue as even a `cout` debug added to the code won't echo to terminal as it's a separate process.

![image](https://cloud.githubusercontent.com/assets/6345473/2935344/0a96be30-d803-11e3-9a38-787c9a0290e9.png)

**Comment by Animtim** [comment]
Hi,
I have similar issue: lmms freeze completly as soon as I click on the show gui button.
Except I'm not using mac but linux!
I can see this console log:
/usr/bin/../lib64/lmms//RemoteZynAddSubFx: error while loading shared libraries: libZynAddSubFxCore.so: cannot open shared object file: No such file or directory

But of course /usr/lib64/lmms/libZynAddSubFxCore.so is here, so I don't know why it can't see it..
Tell me if I should open another bug report..

**Comment by tresf** [comment]
> But of course /usr/lib64/lmms/libZynAddSubFxCore.so is here, so I don't know why it can't see it.. Tell me if I should open another bug report..

Yes, probably best to open a separate bug report.  If you are on a Debian flavor using the KXStudio repository it may be a duplicate of https://github.com/LMMS/lmms/issues/1758

**Comment by bjalfi** [comment]
without QT_SHMEM:

 shmdt(m_data) is called before the sem_destroy() which will lead to an segmentation fault.

The following patch should fix that issue.

<pre>
diff -ur lmms-1.1.3.orig/include/RemotePlugin.h lmms-1.1.3/include/RemotePlugin.h
--- include/RemotePlugin.h	2016-02-26 12:49:58.087588000 +0100
+++ include/RemotePlugin.h	2016-02-26 12:50:38.213681000 +0100
@@ -250,9 +250,6 @@
 
 	~shmFifo()
 	{
-#ifndef USE_QT_SHMEM
-		shmdt( m_data );
-#endif
 		// master?
 		if( m_master )
 		{
@@ -264,6 +261,9 @@
 			sem_destroy( m_messageSem );
 #endif
 		}
+#ifndef USE_QT_SHMEM
+		shmdt( m_data );
+#endif
 	}
 
 	inline bool isInvalid() const
</pre>

**Comment by tresf** [comment]
@bjalfi,

Thanks for the recommendation... I attempted to implement your solution via https://github.com/tresf/lmms/commit/250f91f6dc1200d3bbf0e93ea2405b275c25fa65 but was unsuccessful.

![image](https://cloud.githubusercontent.com/assets/6345473/13375057/f2c3e112-dd63-11e5-917d-9729d7c8cce7.png)

```
could not initialize m_dataSem
could not initialize m_messageSem
could not initialize m_dataSem
could not initialize m_messageSem
could not initialize m_dataSem
could not initialize m_messageSem
could not initialize m_dataSem
could not initialize m_messageSem
```

**Comment by bjalfi** [comment]
Hey,

sem_init() seems to be broken on OSX. You might be successful by defining USE_QT_SEMAPHORES on OSX

```diff
--- include/RemotePlugin.h	2016-02-26 06:00:20.000000000 +0100
+++ include/RemotePlugin.h	2016-02-29 00:26:54.624782000 +0100
@@ -37,7 +37,7 @@
 #include <cassert>
 
 
-#if defined(LMMS_HAVE_SYS_IPC_H) && defined(LMMS_HAVE_SEMAPHORE_H)
+#if defined(LMMS_HAVE_SYS_IPC_H) && defined(LMMS_HAVE_SEMAPHORE_H) && ! defined(__APPLE__)
 #include <sys/ipc.h>
 #include <semaphore.h>
 #else
```

I don't use OSX so it's not tested ;)

**Comment by tresf** [comment]
@bjalfi Thanks again for the recommendation.  I tried the approach suggested and clicking the Zyn `Show GUI` button still hangs the software indefinitely.

On a related note, if your patch fixes the problem for another platform, please issue a pull request so that the Mac issues don't hold it up.

On the other hand, if you're still interested in helping this issue, please continue to share your recommendations. :+1:   I can also grant access to a the VMs I use for my OS X build environments if interested (this offer stands for anyone interested).

**Comment by tresf** [comment]
Thanks to some improvements in `RemotePlugin`, the hard-crash seems to be gone.

@jasp00 perhaps you can help.... I'm successfully starting the new remote process now with the addition of [#2861](https://github.com/LMMS/lmms/pull/2861/files#diff-b6e06d3d61c47ede770ac49ad9ea8f9eR186), but now I receive the following error:

```
RemotePluginClient::shmget: No such file or directory
```

**Comment by jasp00** [comment]
The `RemotePluginClient::shmget` error is related to VST sync. You should have seen
`VST sync support disabled in your configuration` before.

**Comment by tresf** [comment]
> The RemotePluginClient::shmget error is related to VST sync

I'm confused... I'm referring to ZynAddSubFX... Can you explain?

**Comment by jasp00** [comment]
The [error](https://github.com/LMMS/lmms/blob/master/include/RemotePlugin.h#L1171) is only noise. When a remote plug-in client (`RemoteVstPlugin` or `RemoteZynAddSubFx`) is created, the initialization with shared memory is tried, which is started in `src/core/VstSyncController.cpp`, then it falls back on initialization with messages.

**Comment by tresf** [comment]
@jasp00 ok thanks.  So this is what I get with the changes in `RemotePluginClient` combined with #2861 

![untitled](https://cloud.githubusercontent.com/assets/6345473/16252229/7e5df988-37fa-11e6-83d6-2e3245368997.gif)


```
QtXmlWrapper::loadXMLfile(): empty data
RemotePluginClient::shmget: No such file or directory
QtXmlWrapper::loadXMLfile(): empty data
Starting Audio: NULL
Audio Started
Starting MIDI: NULL
MIDI Started
RemotePlugin::DebugMessage: failed getting shared memory
QtXmlWrapper::loadXMLfile(): empty data

<starts here>
WARNING - too late
WARNING - too late
WARNING - too late
WARNING - too late
WARNING - too late
WARNING - too late
WARNING - too late
WARNING - too late
<repeats>
```

**Comment by jasp00** [comment]
The output looks normal. The `WARNING - too late` messages come from ZynAddSubFX [null back end](https://github.com/LMMS/lmms/blob/master/plugins/zynaddsubfx/zynaddsubfx/src/Nio/NulEngine.cpp#L64). ZynAddSubFX is probably busy doing something else. If the GUI does not show up, you should debug [`initPlugin()`](https://github.com/LMMS/lmms/blob/master/plugins/zynaddsubfx/ZynAddSubFx.cpp#L424).

**Comment by expenses** [comment]
As of LMMS 1.2.0-rc3, the 'Show GUI' button doesn't seem to do anything on OSX. What needs to be done to get it to work?

**Comment by tresf** [comment]
> What needs to be done to get it to work?

@jasp00's comments explain what needs to be done.

> As of LMMS 1.2.0-rc3, the 'Show GUI' button doesn't seem to do anything on OSX. 

It never did anything, we just finally re-enabled it because the crash is gone.  The underlying issue still remains.  We don't have many people on Mac or those with the experience to troubleshoot remote plugins, so this issue will remain open until someone can step through the code.

If you or someone you know is interested in the code, we can point you in that direction.  Specifically, the LMMS executable tries to open Zyn as a remote process and that is something that may depend on linking and/or a proper path to the RemoteZyn process.  It's all spelled out in the code if you're interested in helping, we can link the relevant parts.

**Comment by tresf** [comment]
From [Discord](https://lmms.io/chat), @PhysSong and I took a look at the backtrace from RC5, and this is our findings... 

> 
**tresf** - Today at 12:56 AM
> @PhysSong how are you with threading?
> I spent some more time looking into the Zyn GUI / Apple bug (#703) and it seems to be triggered due to fltk trying to open a Window that doesn't live on the main thread.

[...]

> **PhysSong** - Today at 1:53 AM
> `Fl_Window::show()` calls `Fl_X::make()`, and it calls `fl_open_display()` again.
> And It's called here: https://github.com/LMMS/lmms/blob/c3438a1b4e89686f16f433c66db7aa1cc866153f/plugins/zynaddsubfx/RemoteZynAddSubFx.cpp#L220
>
> Then how about running GUI loop in main thread and message dispatcher in separate thread? Current implementation runs message dispatcher in main thread and use a separate thread for GUI event handling.

**Comment by PhysSong** [comment]
The backtrace from @tresf: https://gist.github.com/tresf/dc8730c127b5b6330f6e3199f3c3b9fb
Proposed fix: https://gist.github.com/PhysSong/322a8b1ed6ae443ec5a9f6e282a9b51c

**Comment by tresf** [comment]
@PhysSong thanks! Yes, that fixes it on 10.8 at least.  I'll try 10.13 later and report back.

![image](https://user-images.githubusercontent.com/6345473/34260215-19b40494-e633-11e7-8e0d-e71a504facfa.png)

**Comment by musikBear** [comment]
@tresf -you ned to go deeper. changing the waveform has been a crash issue in ealier releases. I have not yet installed rc5, but will do tomorrow at home

**Comment by tresf** [comment]
@musikBear I assume you're talking about https://github.com/LMMS/lmms/issues/1001#issuecomment-68864497, https://github.com/LMMS/lmms/pull/1991#issuecomment-120735442. 

Those are separate, unrelated issues.  From memory they only crashed Windows XP.  The upside is if this is caused by an obscure threading issue, this patch may help, but speculating won't help.  The next release will have this fix applied and you can test it then.

On a side note, please improve the quality of your posts.  Although it was done with good intent, it lacks any useful quality that we'd expect from a tester.

1. Reference the issue you describe by link
2. Explain that the reference isn't related but offer to test
3. Don't tell a developer what to do, such as "go deeper".  Loading the UI on MacOS is a milestone we've never reached.  Diluting it with your undocumented personal agenda can come off as rude.
4. Try to post details that are relevant.  You installing RC5 tomorrow is not remotely relevant to Zyn UI crashing on Apple.  It's just more for Apple users to read that doesn't help them in context of the crash. <3
