### ISSUE TITLE
Add all letters to piano roll keys

### ISSUE THREAD

**Issue by Froggo8311** [LMMS/lmms#7042]
For the love of god please stop making me count letters :sob:

At least add it as an optional setting, PLEASE

**Comment by Veratil** [comment]
Do you mean this?
![image](https://github.com/LMMS/lmms/assets/2244945/566e2b2f-6a67-4314-863f-6aeb7a55445a)

If so, that's been an option for a very long time. Under `Settings > General settings` there's an option called `Enable note labels in piano roll`.

**Comment by Froggo8311** [comment]
OH, THANK YOU SO MUCH!! I didn't see this. This is what I get for trying to use LMMS at 1 am on New Year's, I guess :P
