### ISSUE TITLE
Mixer channels do not get repainted during solo

### ISSUE THREAD

**Issue by michaelgregorius** [LMMS/lmms#7054]
### Bug Summary
The mixer channels do not get repainted when a channel is soloed.

#### Steps to reproduce
1. Load the demo song "Greippi - Krem Kaakkuja (Second Flight Remix).mmpz".
2. Solo the channel "8-bit pluck". Some of the neighboring channels will partially change colors.
3. Move the Mixer view. All channels get painted correctly.
4. Unsolo the channel. Update is missing.
5. Move the Mixer view. All channels get painted correctly.

It seems that an update is missing somewhere.

#### Expected behavior
This video shows the behavior at commit 4e63f606523 (before 6b21dc7896e):

https://github.com/LMMS/lmms/assets/9293269/8749679c-d538-42f7-af7d-22eb4fbda0e1

#### Actual behavior
This video shows the current behavior in master (at commit 1eff322c2a3):

https://github.com/LMMS/lmms/assets/9293269/75be4410-9a2f-4ddd-ab90-5d9f5e08c000

#### Affected LMMS versions
master at commit 1eff322c2a3.

**Comment by michaelgregorius** [comment]
Hi @sakertooth! I guess this is just a missing update as the corresponding painting code seems to be present in `MixerChannelView::paintEvent`. Adding a call to `update` at the end of `MixerView::toggledSolo` did not help though.

**Comment by sakertooth** [comment]
Thanks @michaelgregorius! I'll look into it.

**Comment by michaelgregorius** [comment]
Hi @sakertooth! I have just created pull request #7055 which fixes the problem. I am not too happy with the solution as it is rather "brutal" in that it triggers an update of all `MixerChannelView`s whenever a solo or mute model changes but it does the job.

**Comment by sakertooth** [comment]
> Hi @sakertooth! I have just created pull request https://github.com/LMMS/lmms/pull/7055 which fixes the problem. I am not too happy with the solution as it is rather "brutal" in that it triggers an update of all MixerChannelViews whenever a solo or mute model changes but it does the job.

I think it is worth the effort finding a more proper solution, I just don't know how that would look exactly. Maybe `PixmapButton` can emit a signal when it changes state from active to inactive and vice versa, which can then be handled by the `MixerChannelView` in a slot that repaints itself. From there, it can emit another signal that will be caught by `MixerView` and then signal to other channels that it should repaint itself if needed.

**Comment by sakertooth** [comment]
Okay, found a simple solution: connecting the `dataChanged` signal of the mute model to do an update on the `MixerChannelView`, like so:

```cpp
connect(&mixerChannel->m_muteModel, &BoolModel::dataChanged, this, QOverload<>::of(&MixerChannelView::update));
```

I suppose Qt repaints the parent (`MixerView`) when one of its children get repainted ([something with propagating content of the parent to the child?](https://doc.qt.io/qt-6/qwidget.html#transparency-and-double-buffering)).

And why do I only need the mute model connected to an update? Because LMMS changes the data for the solo model  once I change the mute model and vice versa, causing the invocation of `dataChanged`, but to be safe, we should probably connect it to the solo model as well.

**Comment by michaelgregorius** [comment]
Hi @sakertooth, I was also thinking in that direction for a better solution. If the channel view must repaint (or do something else) when the solo or mute channel changes then it must listen for changes on these models, i.e. connect to them.

The only thing that must be taken into account when following this approach is that the associated models of the `MixerChannelView` can also be changed via `MixerChannelView::setChannelIndex`. In that case it will have to disconnect from the previous models because otherwise moving channels left or right will create problems due to channel views being connected to several models. This is the main reason why I went with the solution in the PR as a first step.

**Comment by sakertooth** [comment]
> Hi @sakertooth, I was also thinking in that direction for a better solution. If the channel view must repaint (or do something else) when the solo or mute channel changes then it must listen for changes on these models, i.e. connect to them.
> 
> 
> 
> The only thing that must be taken into account when following this approach is that the associated models of the `MixerChannelView` can also be changed via `MixerChannelView::setChannelIndex`. In that case it will have to disconnect from the previous models because otherwise moving channels left or right will create problems due to channel views being connected to several models. This is the main reason why I went with the solution in the PR as a first step.

When we move a mixer channel, why aren't we just changing a stored index in the channel view and visually changing its position? Why would the channel view that contains each model change?

**Comment by michaelgregorius** [comment]
Don't ask me. I did not implement this. :sweat_smile: :wink: 

At least that's what's currently done and what we have to take into account. I have created #7057 with the motivation to abstract the usage of the indices behind some methods so it becomes clearer where they are used and what they are used for.

**Comment by sakertooth** [comment]
No. I will not take into account bad design that goes against very basic expectations 🤣.

I need to confirm by looking at the codebase again, but I refuse to believe this is actually the behavior being done.

If somehow this is actually the case, I am pushing the effort to refactor `MixerChannelView`.

**Comment by sakertooth** [comment]
Looked at the code, oh my goodness...
