### ISSUE TITLE
Set center value of W/D knob at 0

### ISSUE THREAD

**Issue by Monospace-V** [LMMS/lmms#7076]
### Enhancement Summary
The W/D knob, when set to 0, should be grey on either side of the knob.

Presently, when w/d is at 0, the area between -1 and 0 is highlighted on the knob. (see image)
![image](https://github.com/LMMS/lmms/assets/76674645/f89026ed-a884-4d58-8fcf-a7cb04aa86ff)
(ie, arc active on a knob. Should be activated beyond 0, not -1 at knob beginning.)

Other knobs which display the behaviour expected:
![image](https://github.com/LMMS/lmms/assets/76674645/a4636f32-b915-4f4b-8c7d-6887e63feec4)
![image](https://github.com/LMMS/lmms/assets/76674645/2797f218-c4aa-4df9-83d7-9a72a71f2de9)
![image](https://github.com/LMMS/lmms/assets/76674645/09388a50-de00-4da7-8bfd-309b93df22f5)

W/D by contrast
![image](https://github.com/LMMS/lmms/assets/76674645/1e814d29-f053-477f-bff2-3a10caa48eed)

#### Justification
At 0 the w/d knob shouldn't give the impression that there is a 50% w/d mix. 
The enhanced behaviour would be visually accurate.
This would also clear up some of the confusion that may have _led_ to the opening of #6029.
Users are less likely push w/d to -1 by mistake confusing it for 0.

#### Implementation?
It could be convenient to implement a check that centres the highlight at zero for all knobs that contain a zero. Basically universally set the center value to zero. Is this possible?
For this case, we can just place `m_wetDryModel.setCenterValue( 0 );` in Effect.cpp.

Took me an while to understand enough of the linking in this codebase to come to this, but this seems very simple. I would like to try and implement this specific fix.

#### Mockup
Current behaviour:
![image](https://github.com/LMMS/lmms/assets/76674645/a7db918a-7476-423c-8750-6b8d681440b3)

Expected behaviour:
![image](https://github.com/LMMS/lmms/assets/76674645/60aa39b2-9067-4fc5-801f-5a8647ef8fd2)

**Comment by M4rotte** [comment]
I support this modification. I find particularly problematic having the knob at 1 when adding a Feedback delay line effect.

**Comment by DomClark** [comment]
Implemented in #7077.
