### ISSUE TITLE
Scroll-bars -Hard to see

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#7078]
### Enhancement Summary
Main window horizontal scroll-bar is very difficult to see for elderly blind users (me)
#accessibility 

#### Justification
I would like to see it...

#### Mockup
Here i have made two screen-shots
1) is the scroll-bar of 1.3-alpha as today -It is also invisible..
2) is a small change with a profound effect -And visible!
![image](https://github.com/LMMS/lmms/assets/6662066/45a6312a-4449-49b9-8c3c-85a0e6be16d5)
I know i can enter the theme folder and make a manual edit just for me, but would "2" not be best for everyone?

**Comment by Rossmaxx** [comment]
What about making the scrollbar white instead?

**Comment by musikBear** [comment]
> What about making the scrollbar white instead?

👍
Yes that could work too for Default 1.2.2+ theme _DarkRebecca_ . Its _Grey on grey_ that is just no good -I am aware that some claims that there are 50 shades to cherry-pick from 🤣 -Actually.. 
**White** _would_ be one of those shades..

**Comment by Rossmaxx** [comment]
@musikBear if you don't mind, can you mention any other "visibility" changes over here, so that me (or anyone else) can do those simple, yet annoying changes with a single pr. Also, reduces efforts on your side to open multiple issues.

**Comment by Spekular** [comment]
Perhaps this is a good time to add a high contrast theme to the defaults?

**Comment by musikBear** [comment]
> @musikBear if you don't mind, can you mention any other "visibility" changes over here, so that me (or anyone else) can do those simple, yet annoying changes with a single pr. Also, reduces efforts on your side to open multiple issues.

I believed there was a meta for accessibility, but i cant find it..
Or see it ...idk
We have all these:
https://github.com/LMMS/lmms/issues?q=is%3Aissue+is%3Aopen+accessibility
But the reason for these issue being added one by one is sad -Its on daily basis that i find yet a new thing being difficult to see -Eg I am going a bit more blind by the day.. ; (
_Thé_ most problematic accessibility issue is not a simple solve; -It is the _fonts_.
_All_ text in LMMS is difficult to read.

**Comment by Rossmaxx** [comment]
> Thé most problematic accessibility issue is not a simple solve; -It is the fonts.
All text in LMMS is difficult to read.

I agree with that one. I can't read stuff even with normal eyesight. I can set fixed fonts in css but decided against it in my custom theme. I too wish for that change.

> But the reason for these issue being added one by one is sad -Its on daily basis that i find yet a new thing being difficult to see -Eg I am going a bit more blind by the day.. ; (

It do really be horrible to lose eyesight inch by inch. I feel you.

**Comment by musikBear** [comment]
> It do really be horrible to lose eyesight inch by inch. I feel you.

Thanks! Appreciated

**Comment by musikBear** [comment]
@Rossmaxx Here is another issue
In my 1.3-alpha horizontal gridlines are skewed and the notes are not sized as expected when zooming 
![image](https://github.com/LMMS/lmms/assets/6662066/69964ba7-09c8-42eb-9913-61d5539a7c9c)
But i will make a new topic for this one too
Bundlings are not working. Issues are lost that way,  and the META' for accessibility ? Its gone..

**Comment by Rossmaxx** [comment]
opened #7202 which fixes this.
