### ISSUE TITLE
Add named blocks to title line

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#7089]
### Enhancement Summary
We have a lot of real-estate in tittle-line.
I would be nice if named piano-roll opened blocks could be added to tittle-line

#### Justification
Reward to those that makes structured projects..

#### Mockup
If a song-editor block like 
![image](https://github.com/LMMS/lmms/assets/6662066/da13f850-3517-472a-870f-698bffde2de8)
-is opened in piano-roll the tittle-line looks like this
![image](https://github.com/LMMS/lmms/assets/6662066/69cf6bcf-1837-4cc2-961b-44f5b03cb643)

I would suggest we add the piano-roll opened blocks _name_ like
![image](https://github.com/LMMS/lmms/assets/6662066/bb968b4c-ddd3-4ac6-b63e-8cb1c9c9c62d)
(If the opened block is not named, it should just be displayed as 1. img)

**Comment by michaelgregorius** [comment]
If the piano roll is maximized then this is what's already happening in master.

Note block without name:
![Screenshot_20240203_100224](https://github.com/LMMS/lmms/assets/9293269/409cc54b-181f-4821-9386-1694b0eeb7ce)

Note block with name:
![Screenshot_20240203_100316](https://github.com/LMMS/lmms/assets/9293269/f4697d85-97fb-484c-a906-fd500d2d76da)

Can this issue be closed, @musikBear?

**Comment by musikBear** [comment]
> Can this issue be closed, @musikBear?

That is lovely!
There goes 15 mins i will never will get back..
Yes that Master-feature is exactly what i asked for -Closing.
