### ISSUE TITLE
Add GitHub CODEOWNERS to help with organization and PR review

### ISSUE THREAD

**Issue by TechnoPorg** [LMMS/lmms#7096]
### Enhancement Summary
GitHub offers a feature called "code owners" that allows you to define what parts of a repository's code are under whose responsibility (https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners).
Like the title suggests, I believe that it would be beneficial to LMMS to add a CODEOWNERS file to help with PR review and project organization.

#### Justification
The biggest advantage of having a CODEOWNERS file is that the individuals or teams assigned to a given piece of code are automatically requested for review when a PR impacting that code is opened. A draft PR doesn't automatically request review until it's marked as ready, so contributors won't be spammed with requests to review incomplete code. I think that this would be tremendously helpful in addressing #4935.

#### Mockup
To get this up and running, I would suggest that a member of the LMMS org create these teams and assign members within the organization:
- core
- build
- gui
- plugins
- linux
- mac
- windows

and then create a CODEOWNERS file under the .github directory placing the relevant code under their jurisdictions. More fine-grained teams could be added in the future, but at the moment, core developers seem to be jacks of all trades to some degree, and the code itself isn't organized enough to lend itself to a detailed team setup. I'm far from familiar with the intricacies of LMMS development, though, so any alternate suggestions would be welcomed!

I am happy to write the CODEOWNERS file myself if that will get this added, but I can't create the teams.

**Comment by Veratil** [comment]
In my opinion, at this point in time, there's no reason to use a codeowners file.

**Comment by sakertooth** [comment]
The main problem I see from this is that developers may leave at any point in time (just recently, allejok left, not sure when they're coming back, if at all). If an inactive developer was in the codeowners file, it just becomes more of a nuisance, not only for the inactive developer since they could be notified, but for us as well since the file would have to be updated. So at that point, the codeowners file may require a lot more maintenance for little ROI.

**Comment by TechnoPorg** [comment]
Hmm, fair point. It would be easier if just teams were used, rather than individual devs, because then members can be managed from the organization dashboard without having to touch the codeowners file itself, so that would probably be the way to go. However, afaik non-members of LMMS can't be added to the teams, which may or may not be a con for you.
I just thought it might help with PR review, that's all, but I'm not super invested in this either way, so if multiple people are against it, that's enough for me to let go of the idea.
