### ISSUE TITLE
LFO controller-rack LFO respond to FREQ ao AMT for noise-profiles is strange

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#7097]
This ticket is about how  LFO in *controller-rack*, creates an output that is different from the LFO in default instrument. Both modulating *volume*

### Bug Summary
Selecting either off 
* FREQ
* AMT
will not make changes in output of rack-connected dials controlled by noise-profile

#### Steps to reproduce
Settings:
![image](https://github.com/LMMS/lmms/assets/6662066/6ec449d2-4a64-4062-9c1e-d49cc2149cf1)
We have a noise-profile modulating VOL.
The result is discreet output in random Hz, as long as a key in pressed down.
This is normal, expected, and afaic understand *correct*.

_Attempting to recreate this in controller-rack-LFO._
VOL connected to User-controller 
_Testing std-waveforms_
If we select _Sine_ as controlling waveform we get a continuous change in volume as expected.
Turning FREQ changes the duration for the continuous change in volume correctly and as expected
_Using Noise as controlling waveform_
If noise-spectrum is selected the result  is not discreet output in random Hz oscillation, it is noise.
The setup:
![image](https://github.com/LMMS/lmms/assets/6662066/6f0fe856-9325-4ef8-9467-e3e70629c212)
Turning the FREQ-dial has no effect on the output. It remains noise, even in the slowest LFO settings. VOL-dial is not responding with slower movement

#### Expected behavior
Turning FREQ should result in random discreet output as in instrument LFO

#### Actual behavior
Turning FREQ results in noise

#### Affected LMMS versions
<= Windows alpha
----------
Edit of 12/2
https://discord.com/channels/203559236729438208/1205700128355258410/1206273747124748308
That Discord reports that in Linux appImage turning FREQ with automation does result in discreet single outputs. 
If that can be reproduced, This bug is in windows not Linux

**Comment by enp2s0** [comment]
Not sure if this is a bug -- the instrument track LFO options include a sample-and-hold style random generator, while the LFO controller includes a white noise generator. Notice that, for instance, the two icons are not the same.

It makes sense that the frequency control has no effect on white noise, as it's literally just generating random numbers for each sample. You could argue that it should have sample-and-hold semantics (i.e. at max FREQ we get white noise, at lower FREQs we get sample-and-hold) or you could argue that it should function as a cutoff frequency for a lowpass filter on the noise, or you could argue that it should be hidden when noise is selected.

So this is less of a bug and more of a feature request for additional noise types in the LFO controller.

**Comment by zonkmachine** [comment]
> That Discord reports that in Linux appImage turning FREQ with automation does result in discreet single outputs.
> If that can be reproduced,

This was implemented in https://github.com/LMMS/lmms/pull/6850
