### ISSUE TITLE
"Save as new version" needs number in format "-xx", ignores it if there's no dash preceiveing the number

### ISSUE THREAD

**Issue by unfa** [LMMS/lmms#710]
I thought this could be enhanced to not require the dash.

When I named a file "Project 01.mmpz" and hit Ctrl+Alt+S I got a new file named "Project 01-01.mmpz" instead of "Project 02.mmpz".

It's not crucial, because the feature works and I'm very happy with it, but it could see some enhancement  to allow more different numbering formats.

**Comment by tresf** [comment]
@curlymorphic this would be a quick patch.  Sort of lost sight of it, but a second set of eyes and we can merge.

**Comment by tresf** [comment]
Closed via #1701

**Comment by unfa** [comment]
15 maj 2014 18:47 "Tres Finocchiaro" <notifications@github.com> napisał(a):
>
> @unfa This seems to accomplish what you are requesting
>
> static QRegExp regexp( "[- ]\\d+(\\.\\w+)?$" );
>
> Demo:
> http://youtu.be/6CLB2hXjzWQ
>
> @unfa, to request this feature get implemented, please do the following:
>
> In your new fork, navigate to VersionedSaveDialog.cpp, click Edit. This
will automatically create a new fork.
> Change line 75. Add a description/comment, mention this bug report Bug
#710. Click "propose file change".
> Navigate to your own project page and create a new pull request. (Pull
Request, New Pull Request).
> Mention this bug report Bug #710 and submit.
Thanks, Tres! I hope to do this eventually, but I'm very short on time
lately.

**Comment by tresf** [comment]
No worries @unfa, it's implemented and working.
