### ISSUE TITLE
Add a TR-707 like synth

### ISSUE THREAD

**Issue by chiaravalle** [LMMS/lmms#7105]
### Enhancement Summary
Please, add a TR-707 like synthesizer. Don't add a TR-808 or later, because IMHO drums should be synthesized, and their parameter automated.

#### Justification
As above, drums should be synthesized and their parameters should be automated

#### Mockup
None

Not applicable

**Comment by Yutoob12** [comment]
The Tr 707 is not a synth. It is a sample based drum machine. If you want Tr 707 samples, get a 707 sample pack, there's a bunch of free ones.

**Comment by chiaravalle** [comment]
One of the Roland's TR family were syntheszed, I don't remember which one maybe, but I'm pretty sure

**Comment by Yutoob12** [comment]
The 808, the 606, and some of the 909 samples were synthesized, from what I can find

**Comment by chiaravalle** [comment]
Yep, may be I did confusion then

**Comment by enp2s0** [comment]
There are several 909/808/707/606 software synths available, many of them free. You could also just use samples recorded from them (I know it's not identical to synthesizing them directly, but audibly it is very similar).

Barring that, they are really quite simple synthesizers. You can easily recreate the sounds in most additive/subtractive synths. You only really need a noise generator, a sine wave, filters/envelopes, and a distortion of some sort. Nearly every synth has these in some form. LMMS packages ZynAddSubFx which can do it, even TripleOscillator can probably work.
