### ISSUE TITLE
Add a Slicer plugin

### ISSUE THREAD

**Issue by chiaravalle** [LMMS/lmms#7106]
### Enhancement Summary
Add a slicer plugin, but not a common one
In my mind, a slice has 3 components:
- An ID
- A pitch
- A length
The ID is used to refer to a slice, the pitch to play the slice at the desired pitch, the length will loop the slice ID at the Slice ID's loop points until the end of its associated note off event.
This way, a slicer can also be altered/remixed easily

#### Justification
Especially in most EDM sub-genres, being able to resample vocals or shuffle them is crucial.
This plugin will allow such ability

#### Mockup
Not applicable

Not applicable

**Comment by Veratil** [comment]
#6857 this has already been done
