### ISSUE TITLE
ZynAddSubFX Theme + NTK Support

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms#713]
I would like to propose an enhancement for the master branch to use the new [NTK based ZASF theme](http://i.imgur.com/QPwaYbt.png).

Conversation on KVR: http://www.kvraudio.com/forum/viewtopic.php?f=47&t=411406

![image](https://cloud.githubusercontent.com/assets/6345473/2952959/ac7aa6a6-da49-11e3-83ba-60645039bfb9.png)

I've contacted the current maintainer on the KVR boards and this is what he had to say:

> Hello LMMS team, current maintainer ([Fundamental](http://www.kvraudio.com/forum/memberlist.php?mode=viewprofile&u=191933)) here.

> So the skinning was added in at the same time as the optional NTK support was added (a replacement for fltk developed for the non toolset (see non.tuxfamily.org)).
The skin has since been changed to something less busy looking:

> This is all controlled by a few pixmaps and somewhat through the system colors which are exposed to ntk. These are all stored in the pixmaps folder within the git repo.

> It's great that you're making good use out of zyn. Most of my recent work has been in the bowels of the code getting everything in place for proper undo support, midi mapping, and RT safe operations for virtually everything that the UI can touch, though there might be some other fixes which might be of interest since the 2.4.3 release, mainly small bug/regression fixes.

Thoughts?

**Edit:** New 2014 artwork proposal:
![image](https://cloud.githubusercontent.com/assets/6345473/4044875/7ba1f902-2d24-11e4-94aa-5b4bb8a550af.png)

Devianart Link:
http://budislavtvp.deviantart.com/art/ZynAddSubFX-UI-Concept-2014-455890191

**Comment by rubiefawn** [comment]
OH PLEASE WANT WANT WANT
I use Zyn ALL the time and I really hate the GUI despite the sounds it makes... but this would just be beautiful.

**Comment by tresf** [comment]
I'm closing this out per some of @falkTX's comments over at #1620 about cross-platform support with NTK as well as the overall initiative to switch the Zyn frontend to that linked above.

Further more, this is purely cosmetic and time is better spent elsewhere. :)

Please feel free to reopen if needed.

**Comment by tresf** [comment]
Someone on Discord asked how to do this, so I pulled a mirror of NTK and wrote a new wiki, this time for 22.04: https://gist.github.com/tresf/fa28bdfcfe3630f44109a8aee328f731
