### ISSUE TITLE
Issue with filter on the Slicer plugin

### ISSUE THREAD

**Issue by M4rotte** [LMMS/lmms#7150]
### System Information

Debian GNU/Linux 12 (bookworm)

### LMMS Version(s)

LMMS 1.3.0-alpha.1.542+g3f5ac806e

### Bug Summary

Hi,

When I activate any native filter on the Slicer plugin (ie: in the tab "Envelope, filter & LFO" of the instrument), it makes an awfully distort sound. While it is clear a filter is applied I’m not sure it works as it should.
I haven’t managed to make many tests with different audio format. I currently observe the (bug?) with a 24bit/96kHz mono FLAC.

### Expected Behaviour

Filter is applied without awful crackles.

### Steps To Reproduce

Load a sample in the slicer, make a quick pattern, try to add a filter to the Slicer. 

### Please search the issue tracker for existing bug reports before submitting your own.

- [X] I have searched all existing issues and confirmed that this is not a duplicate.

**Comment by zonkmachine** [comment]
Confirmed. It seem to be fixed by https://github.com/LMMS/lmms/pull/6992

**Comment by zonkmachine** [comment]
Issue described here: https://github.com/LMMS/lmms/pull/6857#issuecomment-1811186026
