### ISSUE TITLE
Confirmation for channel removal requested when loading another project

### ISSUE THREAD

**Issue by michaelgregorius** [LMMS/lmms#7153]
### System Information

Linux build (should affect every version)

### LMMS Version(s)

3e19d1335f478504c22ed68af9c96fccd6a6774b

### Bug Summary

A confirmation dialog for channel removal is shown when loading a new project with another project being already loaded.

### Expected Behaviour

No confirmation dialog is shown.

### Steps To Reproduce

1. Load "Greippi - Krem Kaakkuja (Second Flight Remix).mmpz" from the demos.
2. Click "File > New".

The following confirmation dialog is now shown several times:

![LMMSConfirmationBug](https://github.com/LMMS/lmms/assets/9293269/47c8399a-d96e-4d98-bd7a-16ac07d0de24)

**Comment by Veratil** [comment]
Ah, unintended side effect of #7081. Need to add a flag to `deleteChannel` on whether to confirm or not.
