### ISSUE TITLE
1.0.20140512 zynAddSubFX crash

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#716]
OS: win xp 32 bit
lmms 1.0.20140512
To reproduce
1. Drag a new ZASF instrument to the Song Editor
2. From the Plugin Tab, click "Show GUI"
3. If prompted "Beginner or Advanced" click Advanced, otherwise click "Misc, Switch User Interface Mode"
4. Click "Edit Instrument" image
5. Under "Addsynth", click "Edit"
6. On the bottom left, click "Show Voice Parameters"
zynAdSubFX crasher when marked button is clicked
http://snag.gy/BE9sM.jpg

**Comment by badosu** [comment]
@musikBear Could you confirm that this bug happens on 1.1.0?

**Comment by Umcaruje** [comment]
I'm closing this bug for inactivity, since zyn is getting updated to 2.5 there are high chances this bug is fixed.

If it resurfaces though, @musikBear feel free to reopen this issue.
