### ISSUE TITLE
Opening pattern window by its icon and text - leads to empty window

### ISSUE THREAD

**Issue by anytizer** [LMMS/lmms#7165]
### System Information

Windows

### LMMS Version(s)

alpha 1.542

### Bug Summary

![image](https://github.com/LMMS/lmms/assets/5563341/3e1567bf-779d-4270-ab55-c34d143503a6)
Clicking on pattern icon leads to empty pattern window.

### Expected Behaviour

The opened window should load its contents.
(may be default to Pattern 0 data.)

### Steps To Reproduce

Close the existing pattern window if already open.
Click on pattern icon or text.
You will see an empty window.

**Comment by zonkmachine** [comment]
confirmed  @LostRobotMusic 

```
8eba258bdad8e940db9ae84f6362d1749d8bb425 is the first bad commit
commit 8eba258bdad8e940db9ae84f6362d1749d8bb425
Author: Lost Robot <34612565+LostRobotMusic@users.noreply.github.com>
Date:   Sun Dec 31 19:53:52 2023 -0800

    Accept Editor close event (#7035)

 src/gui/editors/Editor.cpp | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

```
