### ISSUE TITLE
VST's Not Loading

### ISSUE THREAD

**Issue by DavidRLTG** [LMMS/lmms#7169]
### System Information

Devuan Linux Latest

### LMMS Version(s)

1.2.2, 1.3.0-alpha

### Bug Summary

Simply used VeSTige, and imported a VST dll.
App freezes for ~10s, comes back, nothing is loaded.

### Expected Behaviour

VST Loads, and I can use it.

### Steps To Reproduce

Simply use VeSTige, and import a VST dll.

### Logs

<details>
<summary>Click to expand</summary>
<pre>
Carla does not appear to be installed.  That's OK, please ignore any related library errors.
Jack appears to be installed on this system, so we'll use it.
QGtkStyle could not resolve GTK. Make sure you have installed the proper libraries.
Notice: could not set realtime priority.
QGtkStyle could not resolve GTK. Make sure you have installed the proper libraries.
Lv2 plugin SUMMARY: 0 of 0  loaded in 0 msecs.
Connection established.

Stream successfully created

Cannot load library /tmp/.mount_LMMS.A6c4DjO/usr/lib/lmms/libcarlabase.so: (libcarla_native-plugin.so: cannot open shared object file: No such file or directory)
Cannot load library /tmp/.mount_LMMS.A6c4DjO/usr/lib/lmms/libcarlapatchbay.so: (libcarla_native-plugin.so: cannot open shared object file: No such file or directory)
Cannot load library /tmp/.mount_LMMS.A6c4DjO/usr/lib/lmms/libcarlarack.so: (libcarla_native-plugin.so: cannot open shared object file: No such file or directory)
002c:fixme:winediag:loader_init wine-staging 8.18 is a testing version containing experimental patches.
002c:fixme:winediag:loader_init Please mention your exact version when filing bug reports on winehq.org.
0080:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0080:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0080:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0080:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0080:fixme:wineusb:query_id Unhandled ID query type 0x5.
0080:fixme:wineusb:query_id Unhandled ID query type 0x5.
0080:fixme:wineusb:query_id Unhandled ID query type 0x5.
wine: failed to start L"Z:\\tmp\\.mount_LMMS.A6c4DjO\\usr\\lib\\lmms\\32\\RemoteVstPlugin32.exe.so"
Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: File not found.

Remote plugin exit code:  1
remote plugin died! invalidating now.
Remote plugin did not connect.
</pre>
</details>

### Please search the issue tracker for existing bug reports before submitting your own.

- [X] I have searched all existing issues and confirmed that this is not a duplicate.

**Comment by Veratil** [comment]
Also reported on Discord. A recent update to wine was found to be the issue in that case.
