### ISSUE TITLE
Scripting language for boosting people's contributions to LMMS

### ISSUE THREAD

**Issue by Manerr** [LMMS/lmms#7172]
### Enhancement Summary

I've been reading a lot of comments on reddit/discord about the fact lmms was lacking a lot of features the other DAWs have... of course if you take a look on this github, there's dozens of fresh commits... 
But honestly, why on earth no one is speaking about the fact a script language could boost the dev progress and add features faster?

### Implementation Details / Mockup

I'm not sure if I've already spoken about that "**scripting**" language for LMMS yet, but it could help a lot in all the directions.

The **blender 3d** software is a perfect example of how a **scripting** language (in that case **python**) helps and sometimes even replace dev(not fully, note that), and then improves softwares.
A lot of those add-ons casual peoples has made are now included inside blender itself...

So it'd be great to have some kind of the same thing in LMMS.

I know some people would disagree, especially about the **security issues**, but even a **simple user-actions script** with only some basic features (_maths_, _logics_) would do the job. 

Examples: people could then create a single track export by just automatizing user-clicks, adds more tools in the piano rolls, etc.

Is it planned? It would, in my opinion, helps a lot the devs and will attract much more people... 

### Please search the issue tracker for existing feature requests before submitting your own.

- [x] I have searched all existing issues and confirmed that this is not a duplicate.

**Comment by Spekular** [comment]
Duplicate of #2221.
