### ISSUE TITLE
piano roll big rendering problem

### ISSUE THREAD

**Issue by SalutanisOrkonus** [LMMS/lmms#7180]
### System Information

Windows 10

### LMMS Version(s)

g03f885abc

### Bug Summary

Piano roll notes are not actually placed on grid and seem to be stuck to the screen with a specific offset. Some notes (like lower register ones) will be also stuck out of view because of this

### Expected Behaviour

this does Not happen

### Steps To Reproduce

Open a piano roll at all, if there's no notes, try placing some. wont work right.

### Screenshots / Minimum Reproducible Project

https://github.com/LMMS/lmms/assets/65266122/4f95f3f2-6f1e-4f76-85db-097b0341f766

### Please search the issue tracker for existing bug reports before submitting your own.

- [X] I have searched all existing issues and confirmed that this is not a duplicate.

**Comment by Veratil** [comment]
I cannot reproduce this. Are you using the nightly version downloaded from lmms.io?

**Comment by SalutanisOrkonus** [comment]
Yes

**Comment by SoraFloatyKitty** [comment]
Can confirm, this bug affects LMMS nightly from LMMS.io. Tested with LMMS 1.3.0-alpha.1.555+g03f885abc on Windows 10.

**Comment by Veratil** [comment]
Okay, I can reproduce this now (not sure what happened before). I believe I know the cause.

**Comment by Veratil** [comment]
In #7143 we overlooked shadowing a class member variable, easy fix!
