### ISSUE TITLE
High CPU usage even when idle

### ISSUE THREAD

**Issue by khoidauminh** [LMMS/lmms#7207]
### System Information

Archlinux

### LMMS Version(s)

1.3.0-alpha.1.569+g8e40038a2-linux-x86_64

### Most Recent Working Version

1.3.0-alpha.1.543+g3e19d1335

### Bug Summary

LMMS takes up CPU resources even when the user is not doing anything

![Chụp màn hình từ 2024-04-14 08-38-28](https://github.com/LMMS/lmms/assets/81458575/25e9871f-4215-49fc-a0fe-967e7a17ec0c)

![lmms](https://github.com/LMMS/lmms/assets/81458575/eef672a7-655a-4422-81e6-a9a051b66043)

### Expected Behaviour

LMMS does not take up resources, especially when inactive

### Steps To Reproduce

Launch the latest nightly build of LMMS and monitor it's usage

### Notes

After some finding I found out that https://github.com/LMMS/lmms/commit/04ecf733951d2aba5bc8dad08c50f189979c8737 may have introduced the bug 

### Please search the issue tracker for existing bug reports before submitting your own.

- [X] I have searched all existing issues and confirmed that this is not a duplicate.

**Comment by bratpeki** [comment]
Can reproduce. 10% of my CPU for 1.527+g360254fd8, and 90% for 1.527+gd2c2a8050. Checked with `htop`.
