### ISSUE TITLE
Decimal values cannot be set in the automation editor

### ISSUE THREAD

**Issue by thismoon** [LMMS/lmms#7279]
### System Information

EndeavourOS

### LMMS Version(s)

LMMS 1.3.0-alpha.1.612+ge9848dbbb

### Bug Summary

when editing an automation clip, decimal values cannot be set. this is probably caused by #7269

### Expected Behaviour

when editing an automation clip, the user should be allowed to enter decimal values like 0.5 for precision (e.g. AM pitch shifter). it's also needed when the automation is between 0 and 1 (e.g. effect wet/dry mix, vst knobs automation)

### Steps To Reproduce

- link the wet/dry knob of an effect to an automation clip
- try to set it to 0.5 from the automation editor

### Screenshots / Minimum Reproducible Project

![anim](https://github.com/LMMS/lmms/assets/107642606/c772cd50-c29c-4600-8507-227bf295f4a5)

### Please search the issue tracker for existing bug reports before submitting your own.

- [X] I have searched all existing issues and confirmed that this is not a duplicate.

**Comment by zonkmachine** [comment]
> this is probably caused by #7269

So it seems... ;(

**Comment by zonkmachine** [comment]
Attempt at fixing this in https://github.com/LMMS/lmms/pull/7282
