### ISSUE TITLE
The playhead disappears when the zoom decreases.

### ISSUE THREAD

**Issue by Gabrielxd195** [LMMS/lmms#7294]
### System Information

Debian Sid Cinnamon

### LMMS Version(s)

LMMS Nightly Version

### Most Recent Working Version

Versión 1.3.0-alpha.1.621+gbfeb781dc (Linux/x86_64, Qt 5.12.8, GCC 9.4.0).

### Bug Summary

After adding the lines to the bars in the Song Editor #7034 the playhead disappears when you zoom out and this can be a bit confusing when there are a lot of tracks and you want to move it from one side to the other.

### Expected Behaviour

That it does not disappear when the zoom is reduced.

### Steps To Reproduce

1- Open LMMS.
2- Increase and decrease the zoon.
3- The playback head disappears.

https://github.com/LMMS/lmms/assets/26127693/a8041bbc-416e-47af-9fa8-ec11979f0f73

**Comment by zonkmachine** [comment]
Confirmed, guilty commit: a527427abfc70122589c36bc5fbc6ff21f9e02ae

**Comment by zonkmachine** [comment]
@BoredGuy1

**Comment by BoredGuy1** [comment]
I see. I will look at it tonight.

**Comment by BoredGuy1** [comment]
I believe the issue lies in `src/gui/editors/PositionLine.cpp`:

```
void PositionLine::zoomChange(float zoom)
{
	int playHeadPos = x() + width() - 1;

	resize(8.0 * zoom, height());
	move(playHeadPos - width() + 1, y());

	update();
}
```
When `zoom` gets small enough, the bar is resized to a number that is smaller than 1, which causes the position line to disappear. 

I should be able to fix this quickly by implementing some kind of check that ensures `8.0 * zoom` is never below 1, unless someone else has a better idea.

**Comment by Rossmaxx** [comment]
What about `resize(std::max(8.0 * zoom, 1), height());`

**Comment by BoredGuy1** [comment]
That's more elegant than what I had in mind (ternary logic). I'll do that.
