### ISSUE TITLE
Allow theming of elements with hardcoded color values

### ISSUE THREAD

**Issue by thismoon** [LMMS/lmms#7306]
### LMMS Version(s)

LMMS 1.3.0-alpha.1.617+g948bb4ac6

### Bug Summary

Some elements in LMMS have hardcoded color values rather than using colors from the theme's `style.css` file. this makes it impossible for the user to change the color of these elements using themes

### Expected Behaviour

Changing the colors of UI elements should be possible by modifying their classes in the `style.css` file. but there's no values to be changed for some elements. the colors of these elements are hardcoded in the source code instead of being taken from the `style.css` file, therefore making it impossible for regular users to theme.

Here are the elements that I found to be impossible to theme because of this (with the location of the hardcoded color value):

- [The envelope graph](https://github.com/LMMS/lmms/blob/master/src/gui/instrument/EnvelopeGraph.cpp#L210)
- [The LFO graph](https://github.com/LMMS/lmms/blob/master/src/gui/instrument/LfoGraph.cpp#L147)
- ~~[The label of the LCD widget](https://github.com/LMMS/lmms/blob/master/src/gui/widgets/LcdWidget.cpp#L59)~~ [See comment.](https://github.com/LMMS/lmms/issues/7306#issuecomment-2159129749)
- [The current step note](https://github.com/LMMS/lmms/blob/master/include/StepRecorder.h#L71)
- ~~[The slicerT instrument](https://github.com/LMMS/lmms/blob/master/plugins/SlicerT/SlicerTWaveform.cpp#L38) (other instruments have their colors in [style.css](https://github.com/LMMS/lmms/blob/master/data/themes/default/style.css#L850))~~ [See comment.](https://github.com/LMMS/lmms/issues/7306#issuecomment-2160831833)

There are other hardcoded colors but i'm not sure if they should become themable too (e.g. [spectrum analyser](https://github.com/LMMS/lmms/blob/master/plugins/SpectrumAnalyzer/SaControls.cpp#L122), [vectorscope](https://github.com/LMMS/lmms/blob/master/plugins/Vectorscope/VecControls.cpp#L49
)...)

Here's an example of a non hardcoded color that gets it's value from `style.css`: [the knob's "lineInactiveColor"](https://github.com/LMMS/lmms/blob/master/include/Knob.h#L68) ([`style.css` "qproperty-lineInactiveColor"](https://github.com/LMMS/lmms/blob/master/data/themes/default/style.css#L50))

I think these pages are relevant: [Qt documentation: The Property System](https://doc.qt.io/qt-6/properties.html), [Qt documentation: The Style Sheet Syntax](https://doc.qt.io/qt-6/stylesheet-syntax.html)

### Steps To Reproduce

1. modify the values of theme's `style.css`
2. set the theme directory in the LMMS settings
3. some elements aren't themed

### Screenshots / Minimum Reproducible Project

![image](https://github.com/LMMS/lmms/assets/107642606/750403cc-3a41-4a72-b013-dc62d90dd356)

### Please search the issue tracker for existing bug reports before submitting your own.

- [X] I have searched all existing issues and confirmed that this is not a duplicate.

**Comment by zonkmachine** [comment]
> * [The slicerT instrument](https://github.com/LMMS/lmms/blob/master/plugins/SlicerT/SlicerTWaveform.cpp#L38) (other instruments have their colors in [style.css](https://github.com/LMMS/lmms/blob/master/data/themes/default/style.css#L850))

It has some theming here: https://github.com/LMMS/lmms/blob/master/data/themes/default/style.css#L990

**Comment by zonkmachine** [comment]
Related: https://github.com/LMMS/lmms/issues/1839

**Comment by zonkmachine** [comment]
> * [The label of the LCD widget](https://github.com/LMMS/lmms/blob/master/src/gui/widgets/LcdWidget.cpp#L59)

As I understand it, this was implemented in  https://github.com/LMMS/lmms/pull/2716
The code you linked to is the initialization part that will give default values if the theme doesn't provide a color for this variable (such as an older theme).

**Comment by zonkmachine** [comment]
The three posts above that I haven't crossed out as already fixed, is implemented in https://github.com/LMMS/lmms/pull/7314.

**Comment by zonkmachine** [comment]
> > * [The label of the LCD widget](https://github.com/LMMS/lmms/blob/master/src/gui/widgets/LcdWidget.cpp#L59)
> 
> As I understand it, this was implemented in #2716 The code you linked to is the initialization part that will give default values if the theme doesn't provide a color for this variable (such as an older theme).

Although I'm failing to actually change color of the knob/lcd labels.

**Comment by RustoMCSpit** [comment]
is it possible to change different pitch values in the piano roll to be different colors (and have that vary when the piano roll is showing the chromatic scale vs when the user selects a scale to show the colors based off of solfege (assuming you can select scales in LMMS))

**Comment by RustoMCSpit** [comment]
> is it possible to change different pitch values in the piano roll to be different colors (and have that vary when the piano roll is showing the chromatic scale vs when the user selects a scale to show the colors based off of solfege (assuming you can select scales in LMMS)) ![image](https://private-user-images.githubusercontent.com/134429563/342753237-b02e4210-01f1-47e5-ade3-d669adab71e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5NzUyNjAsIm5iZiI6MTczMjk3NDk2MCwicGF0aCI6Ii8xMzQ0Mjk1NjMvMzQyNzUzMjM3LWIwMmU0MjEwLTAxZjEtNDdlNS1hZGUzLWQ2NjlhZGFiNzFlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEzMFQxMzU2MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MWMwZTM4NTA4ZDJkODZhNjQ5NTlmYzY2Y2JlNGE1ZDcxZDZjODJkMDM3NzQxZTMwZWFjZTAyODkyYmRlMzY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rcBCE27OWUiU1GWSWEBupYJkTMp9Hlb18J5EXuvzs3Y)

@Rossmaxx ?

**Comment by Rossmaxx** [comment]
I don't think that's possible. We can't even colour piano roll notes afaik. Or even if it's possible, haven't used it.

**Comment by Rossmaxx** [comment]
Wait a minute, looks like something @LostRobotMusic did in his personal build, but that's not publicly available. (Lost I'm telling this from memory, don't bash me if I'm wrong)

**Comment by Rossmaxx** [comment]
Ahh it seems the issue got linked wrongly to the PR which I merged minutes ago.

**Comment by Rossmaxx** [comment]
Ahh, I'm confused. The issue linkage is correct. Your request deserves a seperate ticket.

**Comment by RustoMCSpit** [comment]
> Ahh, I'm confused. The issue linkage is correct. Your request deserves a seperate ticket.

but it's a ui element being colored?
