### ISSUE TITLE
key-bind to play side-bar sample

### ISSUE THREAD

**Issue by Rudxain** [LMMS/lmms#7307]
### Enhancement Summary

While navigating the "My Samples" side-bar tab using arrow-keys, I've tried many ways to play a sample without clicking it. Indeed, [according to the docs](https://docs.lmms.io/user-manual/7-resources/7.2-key-mappings#id-7.2.9-file-browser-in-side-bar) there is no key-binding for that action, so the only way is to click (or touch, if there's a touch-screen)

### Implementation Details / Mockup

An intuitive key-bind would be `SPACE`, as it's already used for playing stuff in many places

### Please search the issue tracker for existing feature requests before submitting your own.

- [X] I have searched all existing issues and confirmed that this is not a duplicate.

**Comment by Spekular** [comment]
Closing, since this is already implemented via https://github.com/LMMS/lmms/pull/5427.
