### ISSUE TITLE
Font is pixelated OR blurry 

### ISSUE THREAD

**Issue by StarGecko88** [LMMS/lmms#7324]
### System Information

Windows 10 Pro, Version: 22H2, OS build: 19045.4529, Experience: Windows Feature Experience Pack 1000.19058.1000.0

### LMMS Version(s)

1.2.2, 1.30-alpha.1.633+g01ffa9557

### Bug Summary

The font for everything in the software is really weird. It seems to be pixelated and blurry 
![image](https://github.com/LMMS/lmms/assets/173024307/9eda00d6-5967-4b10-bb17-712aea97732a)
![image](https://github.com/LMMS/lmms/assets/173024307/f07bc7d5-aba5-4e50-972e-501879d97780)
Both pics are fresh installations with the 1st one being 1.3 alpha and the second one being 1.2.2

![image](https://github.com/LMMS/lmms/assets/173024307/0dfe9bcf-1f1b-4347-8b09-1f708e1d73af)
This also starts immediately from the program starting up btw even in the little splash card thing

### Expected Behaviour

The font should have appeared normal like this 
![image](https://github.com/LMMS/lmms/assets/173024307/68d759a1-8541-4a80-93c7-d5201672f188)

### Steps To Reproduce

I just opened up LMMS and everything in there was of a weird font like the one I included. 

### Logs

<details>
<summary>Click to expand</summary>
<pre>
  
</pre>
</details>

### Please search the issue tracker for existing bug reports before submitting your own.

- [x] I have searched all existing issues and confirmed that this is not a duplicate.

**Comment by musikBear** [comment]
that just looks weird
It seams that you are using courier as your system font (?)
My only guess is that windows cant find the font, and reverts to courier. If you are one of the many that only sleep your system (bad idea) then The first thing to do is a _cold-boot_ of windows, and retry LMMS.

**Comment by StarGecko88** [comment]
> that just looks weird It seams that you are using courier as your system font (?) My only guess is that windows cant find the font, and reverts to courier. If you are one of the many that only sleep your system (bad idea) then The first thing to do is a _cold-boot_ of windows, and retry LMMS.

My system font is Segoe. I even tried it by turning off fast boot and rebooting the computer still, It stays the same.

**Comment by Rossmaxx** [comment]
If you don't mind, can you check if #7493 fixes it. 

For @musikBear does the PR's new font look good to you?

**Comment by musikBear** [comment]
> If you don't mind, can you check if #7493 fixes it.
> 
> For @musikBear does the PR's new font look good to you?

![image](https://github.com/user-attachments/assets/b31e6d21-0b66-44b7-bb40-ab423e61cd7e)
This font is clear and readable. 👍 I think it looks a bit like **Verdana**. Still to small though, but thats a different issue.

**Comment by Rossmaxx** [comment]
@StarGecko88 can you please confirm in master? As #7493 was merged.
