### ISSUE TITLE
behavior when FX-plugin not found

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#733]
I would sugest a different behavior in the case where a  fx-plugin is missing. Now lmms inserts an empty obkect, and name it 'Dummy'. It is this rename to Dummy, that i propose to change. The reason is that if the project is saved, then the orr. plugin-name will be lost. The user cant backtrace the error any more, because the missing component now is Dummy. I would prefere someting like a concanated string "ThePlugInName" +"  MISSING".
This would retain information, so  the user could repair the project.
(And here i also refere to #724 -in respect to enhanced error-reporting)

**Comment by Umcaruje** [comment]
Closed by #1236

**Comment by musikBear** [comment]
has something been 'lost'?
in a 1.0 project i see this in 1.2.0:
![pluginNotFound](https://user-images.githubusercontent.com/6662066/62562082-c6ac0e00-b880-11e9-80ec-ac55885de4a0.JPG)
Here there is no chance for getting the name of the 'not found' plugin,
