### ISSUE TITLE
Weird buzzing in Monstro Osc 2

### ISSUE THREAD

**Issue by JalvinGaming** [LMMS/lmms#7334]
### System Information

Windows 11, Intel i5-9600k, NVIDIA GeForce RTX 3070Ti, 32GB RAM

### LMMS Version(s)

1.3.0-alpha.1.634+g2adbb166b

### Bug Summary

The Monstro Instrument has a weird buzzing effect on Osc 2 that plays in the right ear.

### Expected Behaviour

No buzz

### Steps To Reproduce

Drag Monstro Instrument
Turn down Osc 1 and 3

### Screenshots / Minimum Reproducible Project

[monstrobuzz.mmp.txt](https://github.com/user-attachments/files/16101912/monstrobuzz.mmp.txt)

### Please search the issue tracker for existing bug reports before submitting your own.

- [X] I have searched all existing issues and confirmed that this is not a duplicate.

**Comment by musikBear** [comment]
Cant reproduce
![image](https://github.com/LMMS/lmms/assets/6662066/679d92ce-1322-4bd5-ab10-d448a072f3f2)
Default setup except the 3 OSCs
![image](https://github.com/LMMS/lmms/assets/6662066/6ac8db8e-3248-41a7-92b5-9f99b720f58f)
win10

**Comment by khoidauminh** [comment]
I can reproduce this. Happens on the master branch 
`LMMS 1.3.0-alpha.1.654+g538572a3c (Linux x86_64, Qt 5.15.14, GCC 14.1.1 20240522)`

**Comment by zonkmachine** [comment]
Confirmed. This seem to have been introduced in c2f2b7e0d762961a19050bcbd636edad34f67c19
@michaelgregorius

**Comment by zonkmachine** [comment]
I added a project that demonstrates the issue in the first post.

**Comment by michaelgregorius** [comment]
Fixed with pull request https://github.com/LMMS/lmms/pull/7368.
