### ISSUE TITLE
VST plugins don't load on Linux through Wine

### ISSUE THREAD

**Issue by antieksi** [LMMS/lmms#7373]
### System Information

EndeavourOS w/ niri compositor (Wayland)

### LMMS Version(s)

1.2.2 (Linux/x86_64, Qt 5.15.14, GCC 14.1.1 20240522)

### Bug Summary

VST .dlls fail to load.
If this can be helpful, I use xwayland-satellite to use XWayland apps in niri compositor. After starting it I launch LMMS with environment variable `DISPLAY` set to `:0`, and I don't really know, if this is the reason.

### Expected Behaviour

With Wine installed from official repositories, any plugin should start and show its window

### Steps To Reproduce

- Install `lmms` package from official Arch Linux repositories
- Install `wine`, `wine-mono`, `wine-gecko`, `winetricks`
- Launch LMMS
- Try starting any VST plugin (e.g. Serum x64)
- The plugin fails to open

### Logs

<details>
<summary>Click to expand</summary>
<pre>
0088:err:hid:udev_bus_init UDEV monitor creation failed
Starting using Qt-native embedding.
malloc(): unsorted double linked list corrupted
wine: Assertion failed at address EFEA6579 (thread 0024), starting debugger...
malloc(): unsorted double linked list corrupted
0024:err:seh:NtRaiseException Exception frame is not in stack limits => unable to dispatch exception.
</pre>
</details>

### Please search the issue tracker for existing bug reports before submitting your own.

- [X] I have searched all existing issues and confirmed that this is not a duplicate.

**Comment by musikBear** [comment]
Do you use wine9?
If so dont use wine9 OR you need Nightly -'Current' Nightly should support wine9, but sure im' not

**Comment by Rossmaxx** [comment]
Yeah nightly supports wine 9. But it's not backwards compat with wine < 6.0

**Comment by 0hStormy** [comment]
You're on an Arch based distro, so you probably have Wine 9, you should download the latest Nightly build.

**Comment by antieksi** [comment]
I've installed `lmms-git` package just now which should have installed me a bleeding-edge LMMS version. VST plugins load, but I've stumbled upon other problem: I can't open VST plugins' GUI.

**Comment by Rossmaxx** [comment]
You need `libxcb-0` or whatever is the arch name too installed. It's a new dependency for vst, since we added wine 9 support.

**Comment by antieksi** [comment]
It looks like I already have them installed (both x86 and x64). Could it be that `libxcb` and `libxcb-0` are a little different?

**Comment by antieksi** [comment]
It seems like this was because of me not setting X11 properly for the VST plugin to show its window. Though I still have one minor issue, that one of plugin's contents appearing not inside LMMS itself, but that's an issue of the compositor. Aside from this, everything seems to work now. Thanks!

**Comment by RainbowShatter** [comment]
So what was the config? I am having the same exact issue but with wine-staging, however, for some reason, VST Effect Plugins load just fine, except for synths like Superwave P8, Synth1, PG-8X...

Edit: I use KDE Plasma on Wayland, should probably switch to something else

**Comment by musikBear** [comment]
> same exact issue but with wine-staging, however, for some reason, VST Effect Plugins load just fine

Is wine-staging the recommended wine for your OS?
If you have **Nightly**, then its a known issue. Atm something is rotten, i saw that precisely Synth1 is one of those that dont work on Nightly, so use/ try Alpha-1.3

**Comment by RainbowShatter** [comment]
I am using normal wine with compiled LMMS, I used the AppImage before, but nothing actually worked, after debugging I found these kinds of info:

`Lv2 plugin SUMMARY: 43 of 73  loaded in 179 msecs.
For details about not loaded plugins, please set
  environment variable "LMMS_LV2_DEBUG" to nonempty.
Blocked Lv2 Plugins: 10 of 73 
  If you want to enable them (dangerous!), please set
  environment variable "LMMS_ENABLE_BLOCKED_PLUGINS" to nonempty.
Remote plugin '/home/lucas_pin/lmms/build/plugins/32/RemoteVstPlugin32' not found
`

I tried recompiling it with ´-DWANT_VST´, still refuses to work
