### ISSUE TITLE
Buggy points in LMMS AudioFileProcessor

### ISSUE THREAD

**Issue by YesImAsh** [LMMS/lmms#7375]
### System Information

Windows 10 intel i7 2.6Ghz

### LMMS Version(s)

g1420a1f7e (nightly)

### Most Recent Working Version

1.2.2 

### Bug Summary

Points only work when moving them to the right, not left. (AudioFileProcessor)

all 3 points (Start, loop, and finish) have this bug

### Expected Behaviour

Should move points to the left

### Steps To Reproduce

Load AudioFileProcessor

load sound

adjust using the UI window (not knob)

There you have it. (Video footage cant be shown bcuz of file limit)

### Logs

<details>
<summary>Click to expand</summary>
<pre>
  
</pre>
</details>

### Please search the issue tracker for existing bug reports before submitting your own.

- [X] I have searched all existing issues and confirmed that this is not a duplicate.

**Comment by szeli1** [comment]
I can verify that this issue exists. I would like to fix this issue soon.
