### ISSUE TITLE
various sample problems

### ISSUE THREAD

**Issue by SalutanisOrkonus** [LMMS/lmms#7394]
### System Information

Windows 10

### LMMS Version(s)

g99c30ea1a

### Bug Summary

1: I opened this old project that had a bubbling water sound, when the sound came up it went LOUD (video in zip (there's reverb on in the clip so it's a little worse but problem is still there without (sample also provided)). it kind of went away when i turned off the built-in lowpass (under envelope, filter & LFO), but only on some notes, others still did a loud distorted click

2: I opened the project again and it didn't do the loud noise this time but the lowpass did just stop it from making ANY noise

3: I put the sample into its own project to test and when I put the built-in lowpass on it went to only the right ear

### Expected Behaviour

these don't happen

### Steps To Reproduce

1&2: man i don't know

3: place sample in blank project, go to Envelope, filter & LFO tab, turn on filter, press a key

### Screenshots / Minimum Reproducible Project

[Downloads.zip](https://github.com/user-attachments/files/16380736/Downloads.zip)

### Please search the issue tracker for existing bug reports before submitting your own.

- [X] I have searched all existing issues and confirmed that this is not a duplicate.

**Comment by firewall1110** [comment]
Check new master ...
P.S.
I just prepared demo for similar thing (old project sound differ on master LMMS version) than compile last master ... 
And -  all is fine ... nothing to show ...

**Comment by firewall1110** [comment]
_I'll try to understand what is happens ... May be I am wrong ..._
(1) How such sound can be done from normal one? 
Variants are: 
- play it not from beginning (1 byte "later");
- play as different sample type.

_**Problems with pointer arithmetic or not correct type conversion**_?
Another fact is that Linux & Windows have different base C type length and calling conventions. 
This why bug can be only on one platform and be random (if sample loaded by GUI - ok, but when loaded with project - sound bug; when played directly to master - ok, when send to effect - sound bug; )
(2) And this  can make crashes, buggy gui , freezes , not working audio back-end, ... 

P.S.
If time, introducing this kind of LMMS Windows bugs can be found, may be should check
- auto
- type cast (especially if is assumed C-like structure)
- cast to base class

**Comment by SalutanisOrkonus** [comment]
I think this may be the same issue as #7395 and #7400, considering additionally I can't use 90% of my samples cuz they all do a like 606db click in the left ear, including the one shown here. the loud trail is probably the reverb actually catching that

**Comment by SalutanisOrkonus** [comment]
this also applies to the built in metronome. what the hell did you guys fuck up

**Comment by sakertooth** [comment]
> what the hell did you guys fuck up

Nothing. When we merged #7361, the PR was working perfectly fine without issue, on Linux that is. No one would've guessed that on Windows there was an issue. The developer who approved it was on Linux. The author of the PR (me) was on Linux. Everybody who tested it that's on Linux doesn't have this issue.

I'm not trying to downplay the overall problem here, but I am personally just as confused as you as to why there's a problem specifically on Windows. It is also not surprising for these things to happen from time to time. This is a *bleeding-edge build*. Updating the build to the latest master immediately, assuming always that there won't be a problem with each upgrade is itself a problem. No open source project in the world ever improves linearly. Some improvements may come with unforeseen setbacks, and that isn't all too unfamiliar.

We are all here only to try and improve the program. Everything we do was in our best interests at heart, and if we knew the PR had bugs it wouldn't be merged. When these things happen, we put a lot of time into figuring out what went wrong so we can resolve it.

**Comment by SalutanisOrkonus** [comment]
i apologize if the last message felt too aggressive I was just very frustrated when typing it out

**Comment by firewall1110** [comment]
Video:

https://github.com/user-attachments/assets/c4bea406-4b31-4d5a-a899-2fb56763a9ae

demonstrates problem with .ds sound.
Used LMMS 64-bit windows version installed on Linux Debian stable using wine.
