### ISSUE TITLE
SongEditor - Wrong Cursor

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#740]
v: 1.0.2
OS xp 
This is a minor and insignificant glitch.
If a user holds the mouse-cursor at  a note-containers right egde, in song-editor,  the mouse-pointer change to 'drag-arrow -left-right'. This indicate that the note-container is re-sizeable (as the BB-containers are). But note-containers has a fixed size, depending on length of all added notes, and cant be resized. Eg, Mouse-cursor should not change at container right-egde.

**Comment by tresf** [comment]
Closed via #1563
