### ISSUE TITLE
Erazor.xpf crashes the app

### ISSUE THREAD

**Issue by demtivtated-01** [LMMS/lmms#7404]
### System Information

macOS 14.0

### LMMS Version(s)

1.3.0-alpha.1.102+g89fc6c960

### Bug Summary

Clicking on the file Erazor.xpf in the sidebar crashes LMMS.

### Expected Behaviour

Normally, I should be able to use the file like any other audio file. But when I click on the file in the sidebar, the app closes immediately.

### Steps To Reproduce

-> Open the sidebar
-> Go to 'My Presets'
-> Go to AudioFileProcessor
->Click on Erazor.xpf

### Please search the issue tracker for existing bug reports before submitting your own.

- [X] I have searched all existing issues and confirmed that this is not a duplicate.

**Comment by crystalreef22** [comment]
I think this could be due to the feedback delay line. Sorry for not seeing this issue earlier-- I already created an issue at #7406

**Comment by firewall1110** [comment]
No crash on Linux Debian Stable.
No crash on Windows 10 (64 bit) using 64-bit LMMS.
No crash on Windows 10 (64 bit) using 32-bit LMMS (_but produce terrible sound_).

**Comment by crystalreef22** [comment]
No crash on LMMS 1.3.0 flatpak on Arch Linux.

Testing on macOS does crash, though. Perhaps this bug is macOS-specific

Also:
Should I close #7406 as duplicate?

**Comment by demtivtated-01** [comment]
Idk, probably not.

**Comment by demtivtated-01** [comment]
Bug doesnt appear on stable versions, but I usually prefer using alpha versions because of some alpha-exclusive features like Xpressive.

**Comment by DomClark** [comment]
If this is the same issue as #7406, I think it may have been fixed in LMMS/cmt#7, which was pulled into LMMS in #6973. Would you mind testing a nightly build and confirming whether it is fixed?

**Comment by DomClark** [comment]
Closing as per https://github.com/LMMS/lmms/issues/7406#issuecomment-2282313858.
