### ISSUE TITLE
Keeps crashing when exporting a midi using the delay fx plugin!

### ISSUE THREAD

**Issue by Kirby98Phil2024** [LMMS/lmms#7415]
Please fix this problem and hurry up with releasing version 1.3 already, lazy programmers.

**Comment by LostRobotMusic** [comment]
No.
![image](https://github.com/user-attachments/assets/bb181dbe-8d24-46d6-9670-d5f2e04f2dbb)


Also effect plugins have literally no impact or interaction with MIDI export in any way whatsoever, so I'm closing this unless steps to reproduce the issue are provided.  Please use the bug report form next time.

**Comment by Kirby98Phil2024** [comment]
Wait, I solved it! when I uninstalled it and reinstall it back it works! I was finally able to export it without issue! I was thinking it must be something to do with the program itself if the plugin wasn't the issue but why it only crashes when the fx for delay caused it? I just don't understand. Im able to export with the delay fx plugin again but if this issue happens again, my next try would another vst. Do I need to clean anything with lmms? I can't find any feature for cleaning up cache or junk from within lmms. I don't want to delete my work instead. If you got any advice how to make lmms run better let me know! Thanks.

**Comment by Kirby98Phil2024** [comment]
> No. ![image](https://private-user-images.githubusercontent.com/34612565/354408643-bb181dbe-8d24-46d6-9670-d5f2e04f2dbb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1NTUxNzUsIm5iZiI6MTcyMjU1NDg3NSwicGF0aCI6Ii8zNDYxMjU2NS8zNTQ0MDg2NDMtYmIxODFkYmUtOGQyNC00NmQ2LTk2NzAtZDVmMmUwNGYyZGJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDIzMjc1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4ZWRiZjVjZDk2OWRkNmVkNDE0Y2I3NWEwMThiOTFlNWFjMDVjZjZjMzI3NjA1ZmEwYzkyOTM0MGFkNWI3ZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VUFmNqliQ4FOmr--0qQR2QcWOdZGAwUaSo0QsdVgztM)
> 
> Also effect plugins have literally no impact or interaction with MIDI export in any way whatsoever, so I'm closing this unless steps to reproduce the issue are provided. Please use the bug report form next time.

the hell you mean plugins have no impact or interaction? I always export my midis and they come with the sound made with plugins. Your answer doesn't make sense. I doubt you're the programmer who should already know all the ins and outs of a pos software made by a community that should spend more time tinkering it instead of always providing us nightly versions that are not worth jack.

**Comment by Kirby98Phil2024** [comment]
Im not going to report my issue to bug report, I rather report YOU instead for giving me false information about midi plugins and not cooperating with me.

**Comment by thevbw** [comment]
Are you talking about exporting a MIDI sequence or exporting rendered audio? Those two things are very different

**Comment by LostRobotMusic** [comment]
> the hell you mean plugins have no impact or interaction? I always export my midis and they come with the sound made with plugins. 

@Kirby98Phil2024 Then you're exporting audio, not MIDI.  MIDI export (`File -> Export MIDI`) exports the MIDI data, which is the notes used in the project, not audio.  Audio export (`File -> Export`) exports the actual audio, along with any effects you have applied.

**Comment by thevbw** [comment]
Answering that question for certain would save everyone a lot more time compared to giving me a thumbs-down @Kirby98Phil2024

**Comment by Kirby98Phil2024** [comment]
Hey guys! Are you part of the team or just users? I have a question about the cpu usage, is there a way to reduce it? I believe my problem has nothing to do with the fx plugin as Im starting to think it could be something to do with the cpu usage or sonething else that needs clean up? I already look through all the settings and couldn't find anything that might help prevent the exporting issue to happen again. Im doing fine so far but it might happen again if theres too much input. Im trying to minimize the tracks (instruments) and removing or muting some I don't use with my current project. But theres important tracks I have to keep like 2 basses, 2 drums and only 1 lead. Normally if the drums and bass play alone they are not loud enough so thats why Im using double of the same sounds. I did not make these songs myself, they are all midis created by others I find for free on the internet and I download them to do Sega Genesis remixes with sound fonts (sf2). At first I thought it was the fx plugin or the sf2 Im using but its neither of those Im afraid as Im still able to export with the delay fx and sf2 together with no issue. It seems what caused the crash could be cpu usage building up and doesn't stop there because its always in use. Does this software build up cache and other data junk? would be rather nice if there was a cleaning feature, I can't even clear the recent opened file list! Let me know if you guys have any clue about it. Thanks!

**Comment by thevbw** [comment]
You ought to rename the issue to say "(...) crashing when exporting a _track_ (...)" to end any more confusion.

**Comment by Kirby98Phil2024** [comment]
I noticed it was running slower before I uninstalled it and reinstalled it back to make it work properly but Im still wondering whats the cause of the crash and why lmms runs slow until I reinstall it? Thats why Im thinking the issue has nothing to do with plugins or the midi but the software itself.

**Comment by Kirby98Phil2024** [comment]
> You ought to rename the issue to say "(...) crashing when exporting a _track_ (...)" to end any more confusion.

I rather start a new issue post and question about what could be done instead of giving me pointless info that have nothing to do with what Im trying to figure it out. Please try to stay on topic with me. See you guys on next issue post.

**Comment by thevbw** [comment]
lol

**Comment by Kirby98Phil2024** [comment]
> lol

brain dead @$-hole.
