### ISSUE TITLE
Clean up button

### ISSUE THREAD

**Issue by ghost** [LMMS/lmms#7416]
### Enhancement Summary

a button for cleaning up junk data such as cache, recent opened file list, and usage with the program. 

### Implementation Details / Mockup

Just a few simple buttons to make it happen. I believe lmms is leaving behind junk while using it. If lmms stored cache, memory, input, and such would be rather nice to clean up to make it perform better, including the recent open file list. 

### Please search the issue tracker for existing feature requests before submitting your own.

- [X] I have searched all existing issues and confirmed that this is not a duplicate.

**Comment by LostRobotMusic** [comment]
Closing for the same reason as #7417 as well as #7415.
