### ISSUE TITLE
Is there a way to clean up lmms? 

### ISSUE THREAD

**Issue by ghost** [LMMS/lmms#7417]
I already look through all the settings and buttons around the interface unless Im missing something? I just want lmms to run better and prevent risk of crashing. At first I thought it was the sf2 player or the fx add-on but I can still export after I uninstalled and reinstalled it. So now Im thinking the cause of the crash could likely be something to do with data such as junk files, usage, and the recent file list? Let me know if theres a way to clean up lmms. Thanks!

**Comment by LostRobotMusic** [comment]
Closing because this was the same aggressive person as in #7415 and they deleted their account, so further clarification can't be asked for to salvage this issue.
