### ISSUE TITLE
Custom colored themes

### ISSUE THREAD

**Issue by YesImAsh** [LMMS/lmms#7418]
### Enhancement Summary

The ability to change the ui color would be cool

Like in fl

### Implementation Details / Mockup

its easy
Just add settings that change the color of certain parts of the ui

This is the default ui for example:

Primary is set to dark gray
Secondary is set to green
Normal track is also set to green
B + B is white
Automation is blue 
Sample is orange
and lastly, miscellaneous is whatever 

### Please search the issue tracker for existing feature requests before submitting your own.

- [X] I have searched all existing issues and confirmed that this is not a duplicate.

**Comment by Rossmaxx** [comment]
We already have a `style.css` file and theming system.
