### ISSUE TITLE
Trash APP. 

### ISSUE THREAD

**Issue by YisuiDenghua** [LMMS/lmms#7441]
### System Information

Trash APP. 

### LMMS Version(s)

Trash APP. 

### Most Recent Working Version

Trash APP. 

### Bug Summary

 Trash APP. 

### Expected Behaviour

Trash APP. 

### Steps To Reproduce

Trash APP. 

### Logs

<details>
<summary>Click to expand</summary>
<pre>
  
</pre>
</details>
1

### Please search the issue tracker for existing bug reports before submitting your own.

- [X] I have searched all existing issues and confirmed that this is not a duplicate.

**Comment by YisuiDenghua** [comment]
Your fucking app ruined my work, you will pay for it

**Comment by Rossmaxx** [comment]
As a developer, i do agree that the app is trash. 

> Your fucking app ruined my work, you will pay for it

We don't get paid either, so don't expect you get paid 😂😆 🤣

||For legal reasons, that's a joke||

**Comment by bratpeki** [comment]
_"closed this as completed"_

**Comment by Rossmaxx** [comment]
> closed this as completed"

Yeah we have completely made the app shit.

**Comment by YesImAsh** [comment]
Lmao look at their pfp
