### ISSUE TITLE
Add Unison Detune + phase randomizer for Quad osc

### ISSUE THREAD

**Issue by YesImAsh** [LMMS/lmms#7448]
### Enhancement Summary

Triple osc should have the ability to have up to 10 unison voices per oscillator, and if the user wants to get rid of a very annoying pluck at the beginning of every note, They should have the ability to have phase randomization (ranging from 0 - 100%), which affects the unison voices (and maybe the original voice)

It will be good for beginners to be able to make their own super-saw. and i honestly dont see why triple osc shouldnt have it

### Implementation Details / Mockup

Detune- Each side (left and right) will have (Unison voices/2) unisons on each side (to make things even) and will be evenly distributed

Phase randomizer- There is a pluck at the beginning because thats where all unison voices line up perfectly for a brief moment; add a knob that randomizes phase (use vital for reference)

If you have questions, let me know
(edit: i was informed that Quad osc is in the works, so hopefully this gets implemented)
### Please search the issue tracker for existing feature requests before submitting your own.

- [X] I have searched all existing issues and confirmed that this is not a duplicate.

**Comment by Rossmaxx** [comment]
Since this is related to a plugin which isn't even available in LMMS yet, better to contact lost directly on this. Closing the issue for now.
