### ISSUE TITLE
Piano Roll Scale tool

### ISSUE THREAD

**Issue by unfa** [LMMS/lmms#747]
Sometimes I wish I could make a phrase twice longer or shorter, or scale it to create a triplet, or such. This could save us much manual work in the Piano Roll.

Also this could be used to reverse note order - another cool feature I miss.

**Comment by Umcaruje** [comment]
@unfa This is the current behaviour in master, when you use Shift+alt to scale notes:
![gifrecord_2015-06-30_122847](https://cloud.githubusercontent.com/assets/6282045/8429076/95e05280-1f24-11e5-801d-a7edb89284c4.gif)

(sorry bout the tad glitchy gif)

I believe we can close this issue as fixed.

**Comment by Wallacoloo** [comment]
Yup! Pattern scaling was fixed a bit over a month ago :)

**Comment by softrabbit** [comment]
A minor annoyance: When I scale a 2-bar phrase at the start of a pattern down to one bar, only the first note plays until I add a note somewhere. Saves fine, and the "missing" notes play again after loading the project again. Doesn't seem to happen for later bars.

**Comment by Umcaruje** [comment]
No responce from OP, Closing. @unfa if you believe this was closed in vain, feel free to reopen this issue.

***

@softrabbit could you file a seperate issue for that please.
