### ISSUE TITLE
MIDI in/out clock sync

### ISSUE THREAD

**Issue by Sanderr303** [LMMS/lmms#7471]
### Enhancement Summary

MIDI in and/or out clock sync to use LMMS together with a hardware or software sequencer.

### Implementation Details / Mockup

Within in the MIDI setting be able to select midi clock in and/or out sync.

### Please search the issue tracker for existing feature requests before submitting your own.

- [x] I have searched all existing issues and confirmed that this is not a duplicate.

**Comment by firewall1110** [comment]
ExternalSync API ([will fix issue #523 JACK transport support with ExSync API draft](https://github.com/LMMS/lmms/pull/6066#top))

is planned to be base for this

P.S.
Post only to connect my PR with this issue

**Comment by Sanderr303** [comment]
Thanks a lot for pointing me to that topic.
