### ISSUE TITLE
Proportional horizontal scroll

### ISSUE THREAD

**Issue by yohannd1** [LMMS/lmms#7474]
### Enhancement Summary

Currently, scrolling horizontally with shift-scroll seems to move a specific amount, regardless of zoom. Because of that, the more you zoom out, the more shift-scrolling becomes a slower alternative to just dragging the scroll bar on the bottom, and at the lowest scale it just becomes unbearable to use.

https://github.com/user-attachments/assets/b516bd83-7409-4020-af65-667eb7db218a

### Implementation Details / Mockup

I'm not qualified to suggest implementation details but I believe the solution might be multiplying the "mouse scroll amount" by the inverse of the level of zoom. Not sure, sorry.

### Please search the issue tracker for existing feature requests before submitting your own.

- [X] I have searched all existing issues and confirmed that this is not a duplicate.

**Comment by regulus79** [comment]
I had the exact thought when I was implementing continuous autoscrolling, but forgot about it. Thanks for the reminder; this should be pretty easy to implement.
