### ISSUE TITLE
### Feature Request: VST3 Support and Improved Sidechain Functionality

### ISSUE THREAD

**Issue by Unerium** [LMMS/lmms#7475]
Hi LMMS Development Team,

I am an EDM music producer passionate about helping other producers who rely solely on free tools. I have a few suggestions that I believe would greatly enhance the user experience and make LMMS even more powerful for those who use it:

1. **VST3 Plugin Support**: Currently, LMMS does not support VST3 plugins natively, which limits the use of many modern plugins. Adding native VST3 support would allow users to access a wider range of tools and create more unique sounds without relying on workarounds like Element.

2. **Improved Sidechain Feature**: Implementing an easy-to-use sidechain feature within any VST plugin that supports sidechain would streamline the workflow. This would eliminate the need for complex setups with the Peak Controller and make sidechaining more accessible.

3. **User-Friendly Interface Enhancements**: Making LMMS as intuitive and feature-rich as Ableton Live 12 would attract more users and improve the overall production experience. Features like advanced automation, better sample management, and more flexible routing options would be highly beneficial.

These improvements would help producers create top-level, unique music, similar to artists like Martin Garrix, Zedd, Flume, and Skrillex, using completely free tools.

Thank you for considering these suggestions. I appreciate all the hard work you put into developing LMMS and look forward to seeing future improvements.

Best regards,
Unerium

**Comment by Rossmaxx** [comment]
Thanks for the request, but all these issues have already been raised by different people in the past. 

Vst3 #4715 
Sidechain #4337 
Ui #1911

**Comment by Unerium** [comment]
I appreciate your response, Rossmaxx. However, it seems that the issue of LMMS not being as feature-rich as Ableton Live 12 hasn’t been raised before. The word “Ableton” isn’t mentioned in the issues you listed.

**Comment by Unerium** [comment]
> Thanks for the request, but all these issues have already been raised by different people in the past.
> 
> Vst3 #4715 Sidechain #4337 Ui #1911

I appreciate your response, Rossmaxx. However, it seems that the issue of LMMS not being as feature-rich as Ableton Live 12 hasn’t been raised before. The word “Ableton” isn’t mentioned in the issues you listed.
