### ISSUE TITLE
Insane CPU usage

### ISSUE THREAD

**Issue by YesImAsh** [LMMS/lmms#7489]
### System Information

Windows 10, Intel(R) Core(TM) i7-6770HQ CPU @ 2.60GHz   2.59 GHz

### LMMS Version(s)

gd703f3915

### Bug Summary

Look at the cpu usage, and look at the track

### Expected Behaviour

the cpu usage should be better. Especially with nothing in it

### Steps To Reproduce

open up lmms

done

### Logs

<details>
<summary>Click to expand</summary>
<pre>
  
</pre>
</details>

### Screenshots / Minimum Reproducible Project

![Untitled - LMMS 1 3 0-alpha 1 690+gd703f3915 6_09_2024 12_49_47 PM](https://github.com/user-attachments/assets/6d3d3708-b81b-401b-b5a2-8eaea8df48d0)

### Please search the issue tracker for existing bug reports before submitting your own.

- [X] I have searched all existing issues and confirmed that this is not a duplicate.

**Comment by bratpeki** [comment]
This gives no context into other processes on your computer. How much % does LMMS occupy?

**Comment by YesImAsh** [comment]
The screenshot goes over 60%

**Comment by michaelgregorius** [comment]
Please show a screenshot of the task manager sorted by CPU usage in situations where LMMS exhibits this heavy load. If there is some other heavy load on the system then LMMS will barely be able to fill the buffers and this will then look like a heavy load inside LMMS itself.

Ideally LMMS should use 0% CPU in situations where there are no tracks and nothing is playing but unfortunately this is not the case.

**Comment by Rossmaxx** [comment]
IIRC, this was fixed with #7549 and #7552. Can you confirm pls, so that I can close this.

**Comment by YesImAsh** [comment]
no need to worry, the cpu was only like that because my Buffer size was set to 0 frames
