### ISSUE TITLE
macOS Nightly build -> “LMMS” is damaged and can’t be opened. You should eject the disk image. 

### ISSUE THREAD

**Issue by megrimm** [LMMS/lmms#7490]
### System Information

Apple M1 Pro 14.6.1 (23G93)

### LMMS Version(s)

lmms-1.3.0-alpha.1.690+gd703f3915-mac14.6-arm64.dmg

### Bug Summary

Hello,

With the nightly builds I am getting:

“LMMS” is damaged and can’t be opened. You should eject the disk image.

Apple M1 Pro
14.6.1 (23G93)

### Expected Behaviour

App should open

### Steps To Reproduce

Try to open app

### Logs

<details>
<summary>Click to expand</summary>
<pre>
  
</pre>
</details>

### Please search the issue tracker for existing bug reports before submitting your own.

- [X] I have searched all existing issues and confirmed that this is not a duplicate.

**Comment by crystalreef22** [comment]
This looks similar to https://github.com/LMMS/lmms/issues/7003#issuecomment-1829127942 and #7070
To fix it, move LMMS outside of the disk image (e.g. by installing it to to /Applications), then run
`xattr -r -d com.apple.quarantine /Applications/LMMS.app`


If you do not want to install it, you can always move LMMS into a different location, like Downloads or Desktop, and run the same command with the correct path (e.g. `xattr -r -d com.apple.quarantine ~/Downloads/LMMS.app`)

If it does not work, try prepending `sudo` before the command

**Comment by megrimm** [comment]
got it. works! thanks!
