### ISSUE TITLE
can not set beginning of looping points in 1.3.0 appImage

### ISSUE THREAD

**Issue by asmrtfm** [LMMS/lmms#7516]
### System Information

Ubuntu 22.04

### LMMS Version(s)

1.3.0-alpha

### Bug Summary

middle click no longer works to set the beginning of the looping points.

it was working in the "stable" version in the ubuntu apt repo.
I switched to the 1.3.0 appImage because the overall it is a huge quality of life improvement.
Noticed this issue and no way to configure the keybinds myself so...

### Expected Behaviour

middle clicking at top of piano roll and song editor, when looping mode is on, marks the beginning of the highlighted section to be looped.

### Steps To Reproduce

run the appimage, try to do it, see it not work

### Logs

<details>
<summary>Click to expand</summary>
<pre>
  
</pre>
</details>

### Please search the issue tracker for existing bug reports before submitting your own.

- [X] I have searched all existing issues and confirmed that this is not a duplicate.

**Comment by musikBear** [comment]
True! May just say it: Positioning looppoints is not dub-optimal, it is flawed/ broken.
_Both_ left and right looppoint reacts to _right_ mouse click 
_Positioning_-control depends of _distance_ from mouse-pointer to looppoint, and that is nerve-wracking.
Best trick is to click a bit to the left of left looppoint, and a bit to right for right looppoint, then you get the grip you intend, and non of the looppoits wll 'overtake' the other -It is a mess!

**Comment by Rossmaxx** [comment]
This is fixed in master. Use nightly to see but not now, there's another regression which is in the process of being fixed.

**Comment by asmrtfm** [comment]
> True! May just say it: Positioning looppoints is not dub-optimal, it is flawed/ broken. _Both_ left and right looppoint reacts to _right_ mouse click _Positioning_-control depends of _distance_ from mouse-pointer to looppoint, and that is nerve-wracking. Best trick is to click a bit to the left of left looppoint, and a bit to right for right looppoint, then you get the grip you intend, and non of the looppoits wll 'overtake' the other -It is a mess!

That is not how mine behaves.
I just simply cannot set the starting point.

**Comment by musikBear** [comment]
> That is not how mine behaves.

And 'mine' is??
OS?
Version?

**Comment by Rossmaxx** [comment]
Closing as this is fixed in master.
