### ISSUE TITLE
Debug Assertion Failed: Expression _osfile(fh) & FOPEN

### ISSUE THREAD

**Issue by unclemusclez** [LMMS/lmms#7539]
### System Information

Windows 11 7800x3d

### LMMS Version(s)

main

### Most Recent Working Version

--

### Bug Summary

![image](https://github.com/user-attachments/assets/a014702a-2967-4789-90b4-9c94cfc651ac)
Trying to import .opus, or .mp3 problems produces this error.
![image](https://github.com/user-attachments/assets/da1d28f2-9f37-4ec7-a3b7-b2b40ddef8a6)
![image](https://github.com/user-attachments/assets/0d6666f5-da77-4c22-954b-4b182059d203)

### Expected Behaviour

i am using the main branch to add opus and mp3 support for windows. 

### Steps To Reproduce

i followed the compilation directions for windows.

I did not install the debug package for QT as it is 30GB. perhaps this is necessary? 

### Logs
```shell
cd vcpkg
.\vcpkg install --triplet=x64-windows fftw3 libsamplerate libsndfile lilv lv2 sdl2 fluidsynth fltk portaudio libstk vulkan
cd ../lmms
mkdir build
cd build
cmake .. -G "Visual Studio 16 2019" -DCMAKE_PREFIX_PATH=C:/Qt/5.15.2/msvc2019_64 -DQT_32_PREFIX=C:/Qt/5.15.2/msvc2019 -DCMAKE_TOOLCHAIN_FILE=P:/gitrepos/vcpkg/scripts/buildsystems/vcpkg.cmake
cmake --build . --config "Release"
cmake --install . --config Release --prefix=C:/lmms
```

### Please search the issue tracker for existing bug reports before submitting your own.

Related:
https://github.com/LMMS/lmms/wiki/dependencies-windows#windows-msvc
https://stackoverflow.com/questions/46758077/debug-assertion-fails-while-reading-file-in-release-build
https://stackoverflow.com/questions/5984144/assertion-error-in-crt-calling-osfile-in-vs-2008/6010756#6010756
https://github.com/perl/perl5/issues/17106

**Comment by Rossmaxx** [comment]
Also seems like you use VS 2019, is there a particular reason why you are not on VS 2021, and 32bit qt is no longer a requirement

**Comment by unclemusclez** [comment]
> Also seems like you use VS 2019, is there a particular reason why you are not on VS 2021, and 32bit qt is no longer a requirement

Unreal Engine Development

**Comment by unclemusclez** [comment]
> Are you sure you updated everything build related? Try updating vcpkg libs with `git pull` and `./vcpkg upgrade --all` and then reconfigure and rebuild LMMS. This error is known for libsndfile versions < 1.2.0.

The following packages will be rebuilt:
  * fluidsynth[buildtools,core]:x64-windows@2.3.6
  * glib:x64-windows@2.80.0
  
  i'll follow up shortly

**Comment by unclemusclez** [comment]
```shell
Generating ADnoteUI.cxx
  Generating ADnoteUI.h
  Generating BankUI.cxx
  Generating BankUI.h
  Generating ConfigUI.cxx
  Generating ConfigUI.h
  Generating EffUI.cxx
  Generating EffUI.h
  Generating EnvelopeUI.cxx
  Generating EnvelopeUI.h
  Generating FilterUI.cxx
  Generating FilterUI.h
  Generating LFOUI.cxx
  Generating LFOUI.h
  Generating MasterUI.cxx
  Generating MasterUI.h
  Generating MicrotonalUI.cxx
  Generating MicrotonalUI.h
  Generating OscilGenUI.cxx
  Generating OscilGenUI.h
  Generating PADnoteUI.cxx
  Generating PADnoteUI.h
  Generating PartUI.cxx
  Generating PartUI.h
  Generating PresetsUI.cxx
  Generating PresetsUI.h
  Generating ResonanceUI.cxx
  Generating ResonanceUI.h
  Generating SUBnoteUI.cxx
  Generating SUBnoteUI.h
  Generating VirKeyboard.cxx
  Generating VirKeyboard.h
  ADnoteUI.cxx
  BankUI.cxx
  ConfigUI.cxx
  EffUI.cxx
  EnvelopeUI.cxx
  FilterUI.cxx
  LFOUI.cxx
  MasterUI.cxx
  MicrotonalUI.cxx
  OscilGenUI.cxx
  PADnoteUI.cxx
  PartUI.cxx
  PresetsUI.cxx
  ResonanceUI.cxx
  SUBnoteUI.cxx
  VirKeyboard.cxx
  NioUI.cpp
  WidgetPDial.cpp
  Generating Code...
  zynaddsubfx_gui.vcxproj -> P:\GitRepos\lmms\build\plugins\ZynAddSubFx\zynaddsubfx\src\UI\zynaddsubfx_gui.dir\Release\
  zynaddsubfx_gui.lib
  Automatic MOC for target ArrayVectorTest
     Creating library P:/GitRepos/lmms/build/tests/Release/ArrayVectorTest.lib and object P:/GitRepos/lmms/build/tests/
  Release/ArrayVectorTest.exp
  ArrayVectorTest.vcxproj -> P:\GitRepos\lmms\build\tests\Release\ArrayVectorTest.exe
  Automatic MOC for target AutomatableModelTest
     Creating library P:/GitRepos/lmms/build/tests/Release/AutomatableModelTest.lib and object P:/GitRepos/lmms/build/t
  ests/Release/AutomatableModelTest.exp
  AutomatableModelTest.vcxproj -> P:\GitRepos\lmms\build\tests\Release\AutomatableModelTest.exe
  Automatic MOC for target AutomationTrackTest
     Creating library P:/GitRepos/lmms/build/tests/Release/AutomationTrackTest.lib and object P:/GitRepos/lmms/build/te
  sts/Release/AutomationTrackTest.exp
  AutomationTrackTest.vcxproj -> P:\GitRepos\lmms\build\tests\Release\AutomationTrackTest.exe
  Automatic MOC for target MathTest
     Creating library P:/GitRepos/lmms/build/tests/Release/MathTest.lib and object P:/GitRepos/lmms/build/tests/Release
  /MathTest.exp
  MathTest.vcxproj -> P:\GitRepos\lmms\build\tests\Release\MathTest.exe
  Automatic MOC for target ProjectVersionTest
     Creating library P:/GitRepos/lmms/build/tests/Release/ProjectVersionTest.lib and object P:/GitRepos/lmms/build/tes
  ts/Release/ProjectVersionTest.exp
  ProjectVersionTest.vcxproj -> P:\GitRepos\lmms\build\tests\Release\ProjectVersionTest.exe
  Automatic MOC for target RelativePathsTest
     Creating library P:/GitRepos/lmms/build/tests/Release/RelativePathsTest.lib and object P:/GitRepos/lmms/build/test
  s/Release/RelativePathsTest.exp
  RelativePathsTest.vcxproj -> P:\GitRepos\lmms\build\tests\Release\RelativePathsTest.exe
  RemoteVstPlugin64.vcxproj -> P:\GitRepos\lmms\build\plugins\RemoteVstPlugin64.exe
  RemoteZynAddSubFx.cpp
LINK : warning LNK4044: unrecognized option '/mwindows'; ignored [P:\GitRepos\lmms\build\plugins\ZynAddSubFx\RemoteZynA
ddSubFx.vcxproj]
  RemoteZynAddSubFx.vcxproj -> P:\GitRepos\lmms\build\plugins\Release\RemoteZynAddSubFx.exe
  ```
  this the tail of my compilation log
  same issue with my rebuild
  
  `LINK : warning LNK4044: unrecognized option '/mwindows'; ignored [P:\GitRepos\lmms\build\plugins\ZynAddSubFx\RemoteZynA
ddSubFx.vcxproj]` this seems it could be an issue

**Comment by DomClark** [comment]
This is probably the same issue as #5683.

**Comment by unclemusclez** [comment]
i tried without the --release flag.. just opening up basic packaged samples triggers the bug
![image](https://github.com/user-attachments/assets/80f0eef3-1837-4c1b-9dbd-3efcd5ff1cca)

**Comment by unclemusclez** [comment]
https://github.com/ojdkbuild/tools_toolchain_sdk10_1607/blob/a3b2cdc2d3e74f81484514056b17ccc031df6739/Source/10.0.14393.0/ucrt/lowio/osfinfo.cpp#L261

**Comment by unclemusclez** [comment]
When running the installation option, it indicates that the installation folder should be `C:\Program Files(x86)\lmms`

installing to this location solved the issue. there is most likely an environment variable i can set.. i also assumed this was 64-bit.
that being said, i dont care. it seems to work. thank ya'll 🕯️🙏🕯️
