### ISSUE TITLE
Midi input workflow simplified

### ISSUE THREAD

**Issue by Rogemcy** [LMMS/lmms#7543]
### Enhancement Summary

Midi input is not as convinent as FLstudio or Cubase . When a new instrument was created , there are always few steps for setting midi input device . And the biggest problem is that when press a midi key ,all instruments make sounds at the same time , I don't know how to solve it but only by click the solo buttom , Why is it designed like this ？ I never get confused in FLStudio or Cubase for this part .
![1](https://github.com/user-attachments/assets/6247ac26-9301-4f06-84e1-fd83145b76f6)

### Implementation Details / Mockup

Refer to FLstudio's workflow 

https://github.com/user-attachments/assets/9390556b-74b8-48e9-8662-10c07ede9659

### Please search the issue tracker for existing feature requests before submitting your own.

- [X] I have searched all existing issues and confirmed that this is not a duplicate.

**Comment by michaelgregorius** [comment]
Which version of LMMS are you using, @Rogemcy?

In the current master there is the option to select a MIDI controller that is automatically assigned to the selected track:

![7543-MIDI-AutomaticallyAssignController](https://github.com/user-attachments/assets/a0eb785b-09a9-4774-ad57-43c855d7af19)

It's not available in version 1.2.2 though.

**Comment by Rogemcy** [comment]
> Which version of LMMS are you using, @Rogemcy?
> 
> In the current master there is the option to select a MIDI controller that is automatically assigned to the selected track:
> 
> ![7543-MIDI-AutomaticallyAssignController](https://private-user-images.githubusercontent.com/9293269/378165390-a0eb785b-09a9-4774-ad57-43c855d7af19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0ODg0NjUsIm5iZiI6MTcyOTQ4ODE2NSwicGF0aCI6Ii85MjkzMjY5LzM3ODE2NTM5MC1hMGViNzg1Yi0wOWE5LTQ3NzQtYWQ1Ny00M2M4NTVkN2FmMTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjFUMDUyMjQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmRmMTdhMmI4YTdlZWQ0ZTAxZWU5ODIzNTU4MGJhMmZhNzhmNTc0YTBlMmMyZDM5YTA4MjU4YjMxZThmMzVlNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.S2fpqZ1FH1Qt5Hi37e8sv-xEUZWNNwK4vLCVa5nU6KA)
> 
> It's not available in version 1.2.2 though.

Thanks a lot ! I‘ve tried the latest build , it works
