### ISSUE TITLE
An instrument ctrl-dragged from Song Editor to Bassline Editor will not be usable

### ISSUE THREAD

**Issue by davidgerard** [LMMS/lmms#757]
An instrument ctrl-dragged from Song Editor to Bassline Editor will not be usable.

Steps to reproduce:
1. Create an instrument in the Song Editor.
2. Ctrl-drag the instrument to the Bassline Editor.

The instrument will be there, but you will not be able to add any notes.

This is on Xubuntu 14.04, master branch compiled freshly from github today.

An instrument created in the Bassline Editor is usable normally.

I originally thought this was just ZynAddSubFx instruments, it appears to be any instrument.

**Comment by karmux** [comment]
I get the same issue like @davidgerard in current master.
Only saving and reopening project allows to insert notes to drag and dropped instrument.

**Comment by davidgerard** [comment]
I just compiled current master from source and it was OK for me.
About: version 1.2.0-rc2.154
git: 241d5f7479023d2903a2658307223672c2b623f3

now on Xubuntu 16.04, amd64, Lenovo X240

**Comment by karmux** [comment]
I have same version, tried both Qt4 and Qt5.
OS is Kubuntu 17.04.

**Comment by musikBear** [comment]
Just a 5€ 
Dragging is causing several problems, this one is only one of them
The most troublesome is the vst-**effects** plugin GUI that will open in the background, they are not always associated correctly with the preset -eg, not opened with the *show-GUI-button*, and are in fact orphans with no shutdown options
There is a perfectly good context-menu, that gives the user 100% control over preset-loading 
Imo dragging is a reminiscence from earliest days, when there was no context-options.
Is it needed?

**Comment by PhysSong** [comment]
@foolo #3598 is open so we can keep track it.

**Comment by musikBear** [comment]
@foolo There is a 'fast hack'
If you right-click the correct pattern (in your pic, it would be 'kicker') and then chose *copy-pattern*
In the erroneous (in pic 'test-instrument1')  right-click, and choose 'paste-pattern', then the pattern-slots, are inserted

**Comment by foolo** [comment]
@musikBear If i right-click the "kicker" pattern, i can select "copy". But when i right-click, the empty space on "test instrument 1", nothing happens, (no popup menu).

**Comment by musikBear** [comment]
> But when i right-click, the empty space on "test instrument 1", nothing happens, (no popup menu).

Oooo! Thats then different from earlier, but the click in current bassline is neat 👍
