### ISSUE TITLE
Improve search field

### ISSUE THREAD

**Issue by Sti2nd** [LMMS/lmms#760]
WOW. LMMS got a search field at the bottom of the tree view in the Sidebar? I finally found out... It kinda sucks though, it only search for visible text, not files in folders.

So nr.1 wanted improvement is the ability to search inside folders and subfolders.

And then we have loosely discussed a search function here https://github.com/LMMS/lmms/issues/614 Which summed up also adds tags as a possibility to list samples and presets.

*Edited 2014-11-10 @tresf, added screenshot*
![image](https://cloud.githubusercontent.com/assets/6345473/4977510/ff245f14-68e7-11e4-92cb-60e39a83ecaf.png)

**Comment by badosu** [comment]
@curlymorphic Did your latest patches in this area address this issue? Or is there still something to be improved?

**Comment by tresf** [comment]
It works and works well, but it doesn't auto-expand search results.   Closing since that's really what is being requested.  We can allow users to open another one to do tree expansion.

**Comment by badosu** [comment]
I don't understand, @tresf, if @curlymorphic changes did not solve this issue, why close it?

**Comment by tresf** [comment]
@badosu they did.  The nice-to-have is to auto-expand the search results, which was never part of this request.

**Comment by badosu** [comment]
@tresf Oh, fine.
