### ISSUE TITLE
Add a weekly on monthly build of the main branch

### ISSUE THREAD

**Issue by ycollet** [LMMS/lmms#7601]
### Enhancement Summary

It's normally quite easy to build lmms on Linux but for Mac and Windows ... 
It should be nice to have a weekly or monthly build for Mac and Windows platforms.

### Implementation Details / Mockup

Nothing to add 

### Please search the issue tracker for existing feature requests before submitting your own.

- [X] I have searched all existing issues and confirmed that this is not a duplicate.

**Comment by Rossmaxx** [comment]
Nightlies already exists, and is updated on every commit to master branch. If you are asking for an updated alpha every month, that needs more discussion.

**Comment by ycollet** [comment]
OK, so I download the nightly build for Mac Arm and ... LMMS installed but refused to start.
I will close this ticket and open a new one for these problem.
