### ISSUE TITLE
Major German translation rework 1.2.2

### ISSUE THREAD

**Issue by Wuzzy2** [LMMS/lmms#7602]
I've reworked the *entire* translation of LMMS for version 1.2.2. This update contains:

* New translations (the translation is now almost complete, only about 10 strings are missing which I just cannot figure out)
* More consistent terminology
* Fixed various incorrect / misleading word translations
* Fixed grammar and typos
* Shortened translations that were too big in some UIs

I followed instructions in the wiki that told me to "download the latest stable" (which is 1.2.2) and then edit the TS file. (I hate Transifex btw, not going to use it, sorry.)
I edited the TS file with Qt Linguist. I then generated a .qm file to extensively test the translation in LMMS and I think the quality is now good enough for publication.

You can find the new TS file in the attachment:

[new_german_lmms_translation_for_1_2_2.zip](https://github.com/user-attachments/files/17908032/new_german_lmms_translation_for_1_2_2.zip)

Copy `de.ts` to `data/locale/de.ts`.

Remember, this TS file is for version 1.2.2. You probably might diff it against the 1.2.2 release version of that file.

**Comment by Rossmaxx** [comment]
@lukas-w it's your area.

**Comment by Rossmaxx** [comment]
Wait, is this for 1.2? The stable release has been virtually archived and we won't change anything. If possible, we will accept contribution to master.

**Comment by Wuzzy2** [comment]
The translation file in master looks very bad. Unfortunately, many strings that were translated in 1.2.2 have lost their translation in master, even if the strings are identical. There's no fuzzy string eigher. :-(
It looks like over 2/3 of the work was wiped out.

Also, the wiki needs to be fixed. It literally told me to use "latest stable".

**Comment by Wuzzy2** [comment]
My guess is that many components got renamed and the translations got lost in the process. Like, everything starting with `lmms::` and `lmms::gui::` in `de.ts` at `master` is empty, but it's clear most of these components existed in 1.2.2, too, just under a different name.

I wonder if there is something like Gettext's `msgmerge`, but for Qt.

**Comment by Wuzzy2** [comment]
Okay, I'm closing this PR for now. I'm trying to figure something out …

**Comment by Wuzzy2** [comment]
Second attempt: #7612.
