### ISSUE TITLE
The nightly for MacOS ARM install but does not start

### ISSUE THREAD

**Issue by ycollet** [LMMS/lmms#7604]
### System Information

Mac m3 / Sequoia 15.1.1

### LMMS Version(s)

Nightly version: https://lmms.io/download/artifact/2228131444

### Bug Summary

I donwloaded LMMS from https://lmms.io/download/artifact/2228131444.
The installer worked but LMMS doesn't start.

### Expected Behaviour

LMMS start

### Steps To Reproduce

Install LMMS from the downloaded installer

### Logs

<details>
<summary>Click to expand</summary>
<pre>
  
</pre>
</details>

### Please search the issue tracker for existing bug reports before submitting your own.

- [X] I have searched all existing issues and confirmed that this is not a duplicate.

**Comment by Rossmaxx** [comment]
Check if `sudo xattr -r -d com.apple.quarantine /Applications/LMMS.app` fixes it.

**Comment by ycollet** [comment]
Thanks, It woks !

**Comment by Rossmaxx** [comment]
Glad it worked. It's a known issue with Mac OS because Apple requires signed builds. This command is used to bypass the signing of builds.

**Comment by ycollet** [comment]
Thanks, I copy the command in my notes :)
