### ISSUE TITLE
sistema de grabacion de audio

### ISSUE THREAD

**Issue by ElRonyTuT** [LMMS/lmms#7614]
### Enhancement Summary

la mejora es agregar un sistema de grabacion de audio desde el microfono, ya que a veces es algo tedioso acudir a otros softwares que hagan este trabajo para en ocasiones grabar solo pequeños sonidos que vaya a utilizar como plucks o percusiones, y ahora que la version alpha trae funciones adicionales para la edicion de sample como el "knife mode" ya no haria falta tantas funciones extra

### Implementation Details / Mockup

un sistema que me permita grabar audio desde mi microfono a algun "sample track". La funcion seria de manera que en la barra de herramientas del editor de cancion haya un boton extra que sirva para grabar en algun sample track, los sample track de ahora en adelante llevarian un boton individual al lado del boton que sirve para ver la bandeja de controladores, el cual al dar click active ese sample track para su grabacion, para que asi no grabe en todos los sample tracks disponibles

### Please search the issue tracker for existing feature requests before submitting your own.

- [X] I have searched all existing issues and confirmed that this is not a duplicate.

**Comment by messmerd** [comment]
Duplicate of #1297
