### ISSUE TITLE
Bug: Adjusting SF2 note volume pans the note

### ISSUE THREAD

**Issue by StakeoutPunch** [LMMS/lmms#772]
As the title says, in v1.0.0 win7 x64 adjusting a note's volume in the piano roll pans the note instead of doing its obvious job. Meanwhile the note's actual pan controls do nothing.

**Comment by softrabbit** [comment]
Fixed or not, 1.0 is EOL since July. Close?

**Comment by tresf** [comment]
Yeah close. :)

**Comment by StakeoutPunch** [comment]
I dunno, did the bug end up fixed? I never checked in 1.1 because at the time I had eliminated soundfonts from my workflow because of this bug.
