### ISSUE TITLE
Enhancement, AFP Move selection in AFP with mouse on GUI

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#794]
I have just played a little with AFP, and it struck me, that it would be a neat thing, if it was possible to move start-point and end-point, at the same time, with only one diel. That could make it possible to get easy exactness with selections in several AFPs (copied) ao used as 'phrase-finder' in a larger sample.
I think alt+diel-movement, could push/ drag the other diels values, in equel amount, and 'alt' is not in use.

**Comment by Sti2nd** [comment]
Could you update the title @musikBear "Move selection in AFP with mouse on GUI/waveform" or something.

**Comment by musikBear** [comment]
@Sti2nd done :)

**Comment by Umcaruje** [comment]
Well, I'm not sure when this was implemented, but this issue is fixed in the master branch:
![gifrecord_2015-06-30_170204](https://cloud.githubusercontent.com/assets/6282045/8434131/e8e4d314-1f49-11e5-84f8-f11d8116575c.gif)

So I'm closing it.
