### ISSUE TITLE
DualFilter "Mix" dial zipper-noise

### ISSUE THREAD

**Issue by harryhaaren** [LMMS/lmms#812]
Moving the Mix dial in DualFilter causes zipper noise: as the signal is multiplied by the value, it requires smoothing to avoid clicks.

**Comment by tresf** [comment]
Should be addressed once #1800 is merged.

**Comment by karmux** [comment]
I don't get zipper noise anymore on master. It got fixed in the mentioned PR.

**Comment by softrabbit** [comment]
Close?

**Comment by harryhaaren** [comment]
Yep, as #1800 has been merged, closing now.
