### ISSUE TITLE
Merge file name and preset name. Remove double naming

### ISSUE THREAD

**Issue by Sti2nd** [LMMS/lmms#818]
There is no actual point in having two names for one preset. LMMS only show the file name, and when you add the preset into your project, it can have a completely different name. The function was perhaps implemented to keep users from saving presets with bad characters in the name, and/or to let the user choose another name than the current preset name on saving.

Proposed changes:
1. Prepopulate the filename in the save preset dialog with the preset name (instrument name).
2. Make LMMS show preset names instead of file names. You can't save a file without a name, so the file name must stay, but the user don't have to think about it.
3. A new given (file) name replaces the preset name when the preset is saved. To preserve the functionality users have to save with another name than the name the instrument have in the project. The entered file name should not change the name of the instrument in the project, only on the saved instrument preset.

http://linux-multimedia-studio-lmms.996328.n3.nabble.com/Double-name-on-presets-td9047.html
PS: There is a point in having two names, when labelling and/or grouping for presets and samples isn't implemented.

**Comment by curlymorphic** [comment]
So we just want to set the default saveas filename to the name of the preset ( with obvious formatting )?
