### ISSUE TITLE
Range-select in Song Editor

### ISSUE THREAD

**Issue by unfa** [LMMS/lmms#821]
Could we implement a way to select all regions/clips on all tracks in Song Editor, by dragging with the Select Tool on the timeline above the tracklist?

How I see it working:
![range-select](https://cloud.githubusercontent.com/assets/491704/3209524/079c82be-ee74-11e3-9575-93bd1fd448a4.jpg)

I'd usually use that to rearrange a track, moving one part of it to a different place in time etc. - selecting them manually can sometimes be hard, but that's for another ticket.

**Comment by badosu** [comment]
Was this implemented on #1652 ?

**Comment by tresf** [comment]
Yes it was, thanks.
