### ISSUE TITLE
Instrument Time Offset

### ISSUE THREAD

**Issue by unfa** [LMMS/lmms#87]
I was thinking about this for some time - could we allow making one of the tracks play 50ms before all the rest?

Sometimes, with pads that have long attack, you'd want to make them start their notes a bit before other instruments, so the note can develop enought when the beat hits.

I've just launched ReNoise on KXStudio - and it has this option on the mixer. You can delay/predelay each track +/- 100ms.

I guess that predelaying one track simply makes all other be delayed by an inverted value.

It could be named TIME OFFSET.

**Comment by tresf** [comment]
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.
