### ISSUE TITLE
Arrow keys should preview samples in the file browser

### ISSUE THREAD

**Issue by mikobuntu** [LMMS/lmms#871]
LMMS currently can preview audio and preset files by left mouse clicking in the file browser and holding for the length we wish to preview.

Including the ability to use our arrow keys to preview samples and presets would greatly improve workflow ( ala Renoise and FL )

It should be possible to keep the current behaviour also and i imagine this working by...

(1) audio will play as long as the menu item is focused by either up or down arrow keys ,

(2) clicking on another ( or the same ) file will set the preview there, cutting off the previous audio.

(3) left arrow will stop all audio previews from playing

(4) right arrow will replay the audio/preset file from the beginning again.

thanks Mikobuntu

**Comment by Umcaruje** [comment]
:+1: 

@Sti2nd this should probably be added to #1488

**Comment by tresf** [comment]
:+1:

**Comment by hashhakaj** [comment]
:+1:

**Comment by karmux** [comment]
:+1:

**Comment by Spekular** [comment]
:+1:

**Comment by AndiEcker** [comment]
what's about having left arrow to play the preset and right arrow adds the
preset to the active window (song editor or B&B editor) - like double
clicking does - this way old-skool keyboard hackers like me would be much
quicker in select sounds for a new song/arrangement...

2016-01-21 16:05 GMT+00:00 Spekular <notifications@github.com>:

**Comment by tresf** [comment]
> left arrow to play

I think the space bar would be more universally accepted, although simply hitting the down arrow and auto-playing the selection on focus would likely be even better accepted by our users and potentially reduce our code complexity.  I'd image this feature would be accompanied by an option to disable.

> right arrow adds the preset to the active window (song editor or B&B editor)

I don't believe this to be a very good shortcut as the arrow keys are used for navigation, not actions.  I'd much prefer something like carriage return, or something more significant of a "do this" type action.

Note, on Mac, carriage return is the default shortcut to rename, so we may decide to remap this on Mac eventually if demand warrants it.

**Comment by Em-Lopez** [comment]
:+1:
So the proposed keys I read are Right Arrow, Spacebar, and Enter.
I would greatly appreciate this feature BTW, it helps with creativity greatly.

**Comment by miketurn** [comment]
There are a lot of great ideas in this thread.
Many of these items would be great addtitions.
Especially some way of being able to stop samples that are longer in length.
Sometimes even when you let go of holding the mouse button which plays the sample, it still continues to play the whole sample.

**Comment by tresf** [comment]
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.

**Comment by zonkmachine** [comment]
Fixed (albeit a bit differently than suggested) in https://github.com/LMMS/lmms/pull/5427
