### ISSUE TITLE
Finer Scaling In The Sequencer

### ISSUE THREAD

**Issue by HDDigitizerMusic** [LMMS/lmms#874]
Can we add a drop down list in the sequencer tools area like in the piano roll where it allows finer scaling?

Here's an example:
![example](https://cloud.githubusercontent.com/assets/6778944/3345081/9dd92662-f8b3-11e3-994e-2974b69be624.png)

Of course, it would not have that many scales but I think you get the idea.

Here's what it looks like in another DAW:
![fl-studio-automation-460-85](https://cloud.githubusercontent.com/assets/6778944/3344960/a395a924-f8b1-11e3-8cb1-2f9e478ef6f4.jpg)

See how there are four large sections like in LMMS but in each section you will find four more measures and inside those two? I’ve seen this feature in a few other DAW's and think it is one of high importance.

I know we have smooth scaling, but a finer measure grid would help get an exact placement. Any thoughts?

By the way, I have to say, LMMS is getting pretty good. I was going to get FL Studio but after I found the changes going on in LMMS, I don’t think I’ll want or need to.

**Comment by Spekular** [comment]
+1 for this, almost made a new issue for it before I found this one. I don't know that I find diizy's solution/workaround preferable to an actual quantization selector though, at least not as a replacement.

An additional feature I think would be neat is an "auto" mode. At 100% zoom it would use the default quantization of one bar, at 200% zoom it would snap to half bars, 400% zoom = beats, and so on. Optionally with a multiplier dropdown next to it, so people can define what Q they'd like at 100% zoom. For example Q set to auto with multiplier set to 2x => half bar snapping at 100% zoom, beat snapping at 200%, ...

**Comment by Spekular** [comment]
Better UX for the auto proposal:
One dropdown selecting Q level
One checkbox enabling/disabling Auto/Adaptive Q

Then Auto/Adaptive Q uses the selected Q level at 100% zoom and adapts at other zooms.

**Comment by PhysSong** [comment]
Implemented via #4973.
