### ISSUE TITLE
Wrong cursor when moving blocks in song-editor

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#879]
1.0.2   32b
Song-editor 
State 'select & move' 
cursor changes to 'extend' at block-ends, but marked blocks moves
(already repd ??)

**Comment by Umcaruje** [comment]
Confirmed on Ubuntu 15.04 x64.

Have a gif:
![gifrecord_2015-06-30_191124](https://cloud.githubusercontent.com/assets/6282045/8436960/37148450-1f5c-11e5-8879-9b1199bc81fc.gif)

**Comment by SecondFlight** [comment]
Leaving a comment to remind myself to reproduce when I get home.

**Comment by SecondFlight** [comment]
Reproduced in 1.2.0 RC8 and master (as of [this build](https://github.com/LMMS/lmms/pull/4639#issuecomment-425760993)).

**Comment by SecondFlight** [comment]
(that was actually me)

As part of a pruning effort, this bug report is archived into a dedicated "Better Workflow" checklist here #4877.

**Comment by claell** [comment]
The question is, what is the expected behaviour? Not having a resize cursor when in selection mode? This also happens when selecting only one "block". Instead of resizing it gets moved.

**Comment by SecondFlight** [comment]
I think either would be acceptable behavior. Either attempt to resize all selected TCOs (am I using that term right?), or don't and disable the cursor.

**Comment by craslaw** [comment]
About to pick this up as a first issue 🚀. I think there's valid cases for both behaviors.

If you want to resize multiple BB blocks at once, it makes sense to select each block then drag out the edge of one block to resize them all. They would all be resized by the same amount of bars. Other track types that allow block resizing like the sample and automation tracks could also be compatible with BB resizing.

However, track types that don't allow resizing (instruments, presets) fit the other behavior better. In the case were a BB block and an instrument block are selected together, the resize cursor shouldn't appear on the edge of the BB block.

I know this was moved to #4877, but it seemed easier to discuss here. Just let me know if it's better to move the discussion to #4877 or Discord.

**Comment by claell** [comment]
I think discussing the details here is indeed better. You can also ask to reopen this issue in #4877 if you plan to work on it.
