### ISSUE TITLE
Drag and drop samples between tracks

### ISSUE THREAD

**Issue by liftarn** [LMMS/lmms#881]
If you have two or more sample based tracks it would be nice to be able to drag and drop (including ctrl + drag to duplicate) samples between tracks.

**Comment by Umcaruje** [comment]
This request has been consolidated into a more encompassing Sample Track enhancement bug report and will be closed as duplicate for better tracking. #1471

Please feel free to reference this bug report or even amend or add comments if needed, but it will remain closed for better tracking purposes.
