### ISSUE TITLE
Bug FX channels with double lables

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#889]
win 32 1.0.91 219614
add 2 channels 
Observe the vertical writing in last added channel: 'FX2'
RC 1. channel
Choose remove
Press '+'
Observe the vertical writing in this last added channel it also readout 'FX2'
http://snag.gy/9GLvn.jpg
Is this 'just' a *label* problem, or is it logical too? (i'm not smart enough to figure out what 'send' can/ should be able too..

**Comment by badosu** [comment]
@tresf This issue was fixed a long time ago, we can close it.

**Comment by tresf** [comment]
:+1:
