### ISSUE TITLE
Sidebar: Refresh button should reset the search field

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#890]
win 32 1.0.91 219614
Sidebar-browser
entering a search-phrase, and then pressing the 'reset-rotation-arrow' does not clean the search-field, and lmms does not return to the default tree-struckture, before the search-field is deleted manually.

**Comment by Umcaruje** [comment]
Marking this as an enhancement. It seems logical that pressing the refresh button resets the search field.

**Comment by Wallacoloo** [comment]
I am in agreement with @diizy here. I do not see why hitting the refresh button should reset the search field. Envision yourself doing the following:

1. Add new files to my sample directory
2. Search for them in LMMS -- search brings up nothing as I forgot to refresh.
3. Refresh the file browser.

That's the primary scenario in which I refresh my file browser, and it clearly benefits from having the search field preserved through refresh. I'm not sure there's a compelling counter-example that's significantly stronger than this.

**Comment by musikBear** [comment]
consensus is propl not achievable
How about both?
left-click preserve search-token 
right-click cleans search-token
(?)

**Comment by Spekular** [comment]
I don't think it makes sense for a refresh button to clear the search
field. It's also faster to remove a search than to retype one, in cases
where you want the search field empty after refreshing.

**Comment by grejppi** [comment]
I was the one who made the search field retain its text (#542), and @Wallacoloo and @Spekular  above describe the exact reasons for why I did it.

But if there were to be a button to clear the box... today it is common to have it embedded in the text entry widget itself:

![GTK+ 3](https://cloud.githubusercontent.com/assets/772336/8508392/e39376ec-2276-11e5-899d-c741f5ec9c9d.png)

![Bitwig Studio](https://cloud.githubusercontent.com/assets/772336/8508393/e3b350e8-2276-11e5-8711-8e04961bc92a.png)

**Comment by Wallacoloo** [comment]
@grejppi a clear button does seem like a good addition.

@musikBear while differentiating between left-click and right-click is
possible, and I wouldn't be totally against it, it isn't all that common of
a UI practice for right clicking a button to perform any operation (except
context menus, sometimes). So I'm not sure very many users would think to
do it.

**Comment by tresf** [comment]
^---- :+1:

**Comment by zonkmachine** [comment]
> But if there were to be a button to clear the box... today it is common to have it embedded in the text entry widget itself:

This was added for the Qt5 builds in https://github.com/LMMS/lmms/pull/3329
