### ISSUE TITLE
More texts for "What is this" 

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#896]
The fine new feature "What is this" has a lot of items that need to written. I will do my part, if wanted. We just need to get a plan for doing them, so none is done 'trice'ish'
Just let me know.
an also, -Translations .. woo - How many languages? 
ooooooooooooo
Oki taking some control now
I will devide the objects that need WITs added in 3 categories
- Instruments
- Panels
- Effects 

Look in thread if some has 'taken' an object and are working on it. I will update the categories as WITs are made, and add 'done' WITs in order. starting here:
## 

**WITs ALREADY done:** 

**General Instrument** This is identical on all non-vst presets, and should have own datastructure or class -whatever fits architechture best..
Tab ENV/LFO

**Specified Instruments** (of cause only the PLUGIN tabs need to have specified wit's!)
Monstro

**Panels**
Automation-editor
BB-editor
FX-rack
General instrument button
LFO-controller
LFO-rack
Main-screen
Piano-roll
Song-editor

**Effects**

**Comment by musikBear** [comment]
Old topic, but i have a new angle
In main-menu Under 
Help | Online Help
LMMS links to the wiki.
My thoughts were that *what-is-this* could be constructed with this type of links.
Eg, instead of the integrated popups lmms has now, *what-is-this* would link to the relevant page in wiki
The benefits
* The codebase would be without hard-coded info
* Changes would only have to be made once (eg in wiki, not in wiki and codebase)
* Changes would be easy to make, and not include coders

Adversaries 
* Users not online cant use it

Opinions?

**Comment by Spekular** [comment]
How about keeping the offline text, and adding a link underneath w/ "read
more online". Alternatively "What's This?" and "What's This (Online)" as
separate right click options.

**Comment by musikBear** [comment]
@Spekular but that would still mean 2 different edits if/ when something is being changed, the whole idea is to avoid having double information. If it is split in two parts, one offline, and one online, i cant see any benefits :)

**Comment by Spekular** [comment]
@musikBear sure, but online-only is no good either. Besides, the information on the wiki should probably be more in depth than what fits in a tooltip. I suppose my idea would just be a convenient way to access the right wiki page.

**Comment by musikBear** [comment]
@Spekular 
> but online-only is no good either

That *is* the adversary i know that, but now-a-days... oh well just a thought.. I will leave this for others to respond

**Comment by musikBear** [comment]
I believe i have the solution, that would allow users to use wit's offline and still keep the wit's out of the codebase, and make editing very easy:
A HTML-document in folder *'locale'* with links inside lmms.
WITs are kept out of codebase, coders not needed in maintenance, and only one file need to be kept updated, still everything work offline.
Opinions?

**Comment by Sawuare** [comment]
Closed via #4128.
