### ISSUE TITLE
Enhancement: TAP Vibrato Effect

### ISSUE THREAD

**Issue by HDDigitizerMusic** [LMMS/lmms#898]
If there could be a fade in knob on the Tab Vibrato effect, something like "start" and "end", or compressor like controls, that would fade in the effect of vibrato. I like that effect so much in music, I would love to see it in LMMS.

Something like in this song: https://www.youtube.com/watch?v=usXhiWE2Uc0

If you listen to the saw lead, the longer notes have some slight vibrato, if you listen, you can hear it and it sound awesome.

**Comment by Umcaruje** [comment]
Closing, since TAP vibrato is a 3rd party plugin, and since the OP is satisfied with the workaround @diizy  posted.
