### ISSUE TITLE
A key / key-combo for Song-editor pause

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#900]
we have space for _stopping_ the song. How about a key of key-combo (sh / ctrl+space) to pause the song. This would give user a flexible way to work in SE in two of three play-head states ('keep pos' would not benefit from this)
Aditional benefit would be, that the bar-tick-values #888 would be automatic (bar-display works correct at pause)

**Comment by zonkmachine** [comment]
> That one is likely to be closed as won't fix unless the OP actually updates his code to honor the requests made but I don't think there was much objection to the proposal.

I'll look into this and pull request #728 again and I'm all warm and fuzzy about peoples requests. Probably the best thing though would be to make the short cuts configurable by the user.

**Comment by PhysSong** [comment]
Closing, since there's a new and better feature request #5301.
