### ISSUE TITLE
Monstro Waveform Contrast

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms#903]
@diizy small bug but perhaps a dropshadow on these waveforms as they are quite difficult to distinguish with the default dropdown bg color.

They look great when hovered over but tough to see the light blue on light gray.

![image](https://cloud.githubusercontent.com/assets/6345473/3418430/33a4fca0-fe47-11e3-820b-06e294150271.png)

**Comment by PhysSong** [comment]
Fixed in the default theme for 1.2.
