### ISSUE TITLE
Can't copy patterns between LMMS instances

### ISSUE THREAD

**Issue by davidgerard** [LMMS/lmms#904]
I am working on something using bits from another piece. So I have each open in its own instance of LMMS.

I go into the bassline editor in both instances, I copy a sequence from the first BB editor, paste it in the second and ... nothing pastes.

If I open the piano roll editor in the first and the second, I can cut and paste the notes from the first to the second OK (so there is a workaround).

I have no idea how supported cut'n'paste between multiple instances of LMMS is, but it works somewhat for me and it's very useful, so I'd like it to be :-)

Ubuntu 14.04 amd64, LMMS latest git master compiled from source.

**Comment by Umcaruje** [comment]
I have no problems copying notes between two lmms instances in the current master, so I'm closing this as invalid.
![gifrecord_2015-06-30_195728](https://cloud.githubusercontent.com/assets/6282045/8437911/911ea934-1f62-11e5-96fe-c6246974a00c.gif)

If you believe this was closed in error, feel free to reopen this issue.

**Comment by davidgerard** [comment]
Umcaruje - no, you've duplicated the action the original report already said worked: "If I open the piano roll editor in the first and the second, I can cut and paste the notes from the first to the second OK (so there is a workaround)."

Can you try with the original reported problem? "I go into the bassline editor in both instances, I copy a sequence from the first BB editor, paste it in the second and ... nothing pastes." This still doesn't work for me in 1.1.3 - does it work for you in master?

**Comment by Umcaruje** [comment]
Oh, I'm sorry, I completely misread your bug report :confused: 

Yeah I'm not able to copy patterns from one instance to another. I'll mark this as an enhancement.

Sorry for the inconvenience.

**Comment by davidgerard** [comment]
Thanks :-) It's definitely "enhancement", given it's abusing LMMS beyond what it's actually meant to do ... but it's extremely useful in practice.

**Comment by musikBear** [comment]
(i know this is totally out of context, but i need to tell you a serious surprising ability:
If you open a project as XML and copy the whole section of a BB with f.i. 10 patterns, and then drop this into an different project, something really interesting will happen.
In the new project there will only be *ONE* BB-track
But then the fun begins:
Press Add-BB-track
As by magic :p Now 2 of the orr 10 exists
Press Add-BB-track nine more times
Everything from the orr. project is ready to go!
I see this as a properly way, in a later state, to cross-import existing BB-lines from named projects, 
(im playing a little with the idea in AScipt :)
<end derail

**Comment by PhysSong** [comment]
Note copying uses system-global `QClipboard`, whereas TCO copying uses local `Clipboard` class. If TCO copying uses `QClipboard`, the issue may be fixed.

**Comment by musikBear** [comment]
@PhysSong Good find!
But dizziy' https://github.com/LMMS/lmms/issues/904#issuecomment-47673925 is imo still the best way, especially in the context of 'library-projects', where you could keep types of rolls and complex builds etc.

**Comment by Spekular** [comment]
Resolved in latest alpha, if not earlier.
