### ISSUE TITLE
Unsaved file shows "Untitled*" in title bar rather than filename

### ISSUE THREAD

**Issue by davidgerard** [LMMS/lmms#905]
When a file is saved and up-to-date, the title bar shows the name of the file, e.g. "ghost" for ghost.mmpz.

When I make a change to the song, it's now in unsaved condition. But rather than "ghost*", the title bar shows "Untitled*".

It should show the name of the file, with the star to indicate it's unsaved.

Ubuntu 14.04 amd64, LMMS compiled from latest git master.

**Comment by Umcaruje** [comment]
@davidgerard can you still reproduce this issue? 

I haven't managed to do so on 1.1.3, Ubuntu 15.04

**Comment by davidgerard** [comment]
Not seeing it in 1.1.3, and in fact I don't recall seeing it in 1.1.3. I think this might have been fixed along the way.

**Comment by Umcaruje** [comment]
Awesome :+1:
