### ISSUE TITLE
discuss -new FX, and double naming

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#921]
Exelent implementation of the fx, but one thing i do not like, is the need for double naming of instrument and channel
Perhaps i dont understand these 'send-channels' sufiently, but wont the logical name of the channel that is connected to an instrument, still be the name of *that* instrument?

As i test the workflow now, adding a new instrument would be done as:
* add a FX-channel
* Open song-editor
* add either a preset, or an instrument
* browse to the latest added fx-channel on the instrument
* name the instrument
* open fx-rack
* name the channel

That workflow is ok - its a little odd, that adding of an instrument, first start in fx-rack, but ok!
Its not ok that there are two identical naming events -Its never ok when two identical events has to be made, and this imo should not take place
How about either
Latest added FX has focus in fx-rack
New added preset should either write its name to the FX when user
* LMC on the FX-spindel
* Use an item in the context

I miss this, and double identical events are nono's
Opignions?

**Comment by badosu** [comment]
@tresf 

The double naming issue is fixed.

The fx mixer assignment via fx selector was implemented.

I guess we can close this one as well..

**Comment by tresf** [comment]
Closed via #1627, #604.  @musikBear you got your wish, thanks to @badosu. :)

**Comment by badosu** [comment]
Actually, it was @diizy who had the idea, I just implmented it.
