### ISSUE TITLE
Default length of AFP sample is 0.5?

### ISSUE THREAD

**Issue by Sti2nd** [LMMS/lmms#929]
Sometimes when I open samples with AFP, the length is not set to 1, it is set to 0.5 - the half length of the sample. 
This happened right now after installing 1.0.3, and have happened before when I moved projects to a new location and had to relocate all drum samples. 
So this is actually two bugs now:
1. Default length of AFP endpoint knob is 0.5, it should be 1.0. But are these percentage at all?
2. When the location of a sample changes, AFP don't remember the length, but resets to default.

**Comment by tresf** [comment]
Closed via #1491.
