### ISSUE TITLE
SongEditor - Pencil Tool Usage

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#942]
winXp 32
in use of pencil
1) Its not intuitive that ctrl+LMB does not change pencil to fast-select (as in Piano-roll)

2)cursor still change to 'resize' at right-end of note-blocks (cant be resized)

**Comment by Spekular** [comment]
Issue 1 is solved. I'm not sure if 2 warrants an issue all by itself, but it should probably be a quick fix if so.

**Comment by DomClark** [comment]
(2) is a duplicate of #740, fixed in #1563.
