### ISSUE TITLE
Piano roll: Eraser tool deletes only one note at a time

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#980]
Using pencil+right mouse let user multi-delete notes, but the dedicated delete tool _Erazor_, can only delete one note at a time. Thats a little odd
imo _Erasor_ +left-mouse down should multi-erase, just as pencil+right mouse does, ..but what would its purpose _then_ be?
In fact -It could even be, that the dedicated _Erazor_ is obsolete, and could be dropped ??

**Comment by Umcaruje** [comment]
Confirmed on Ubuntu 15.04 x64
