### ISSUE TITLE
1.0.92 Automation-editor magnification on vertical axis

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#982]
magnyfy Y
That is bugged now. I believe it was fine in 1.0.2 & 3 ??

**Comment by Umcaruje** [comment]
@musikBear Can you please clarify this issue and offer some screenshots/steps to reproduce.

**Comment by tresf** [comment]
I believe the issue to be with the per-note bending where the vertical axis can only zoom in so much.  This should be closed.

**Comment by musikBear** [comment]
nae - this is one is my fault
this is what i saw
![autoprc](https://cloud.githubusercontent.com/assets/6662066/8498584/edb7e39a-2188-11e5-888a-ff086868e0f7.PNG)
here we have a pattern with auto-scaling
Then i changed to scaling 100%
![100prc](https://cloud.githubusercontent.com/assets/6662066/8498596/0c2eed78-2189-11e5-9e64-cc6c141cf8ba.PNG)
What i saw, was that the pattern now was compressed, and i completely missed the slider in the right side. Perhaps it was off screen, perhaps i just diddent see it
so i blame my missing vission - you can blame me :)
dischard as invalid. sorry
