### ISSUE TITLE
Implement or remove automation editor features

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#983]
winxp 32

No idea why it do that with erazor:
http://youtu.be/c9HaRggvqM8
Project: https://www.sendspace.com/file/kgclvc

**cut, copy, paste -of what?**
The features cut, copy, paste for marked values, but marking/selecting is not possible in automation-editor (no select-tool, no effect of ctrl+a, ctrl+lmb) How shal values in automation-editor ve selected?

**scrol, loopmark & 3 playhead behaviors**
No logic for these -should they be gray-out?

**Comment by Umcaruje** [comment]
@musikBear can you please explain what this issue is about?

**Comment by musikBear** [comment]
The first " why it do that with erazor: http://youtu.be/c9HaRggvqM8 "
was an error where erazor simply was ignored. as the video show

2: Options for cut, copy, paste in editor -senseless, but has now been removed ! Fixed!

3. Showing transport related options
https://lmms.io/documentation/File:Song_Editor_toolbar1.0.0.png
(last 3 buttons from right)
 is wrong, because there is no playhead-movement in automation-editor. I suggest they **temporary** should be grayed out, or playhead-movement implemented.

**Comment by zonkmachine** [comment]
> The first " why it do that with erazor: http://youtu.be/c9HaRggvqM8 "

Issues with not being able to delete Automation Points should now be fixed.


> scrol, loopmark & 3 playhead behaviors
> No logic for these -should they be gray-out?

Yes. The buttons (A) should probably be removed as the functions are unimplemented.
The loop 'rectangle' (B) on the timeline will still be showing and can be set with the mouse but will have no action. A somewhat similar inconsistency is there in the Piano Roll where you can use set a loop but it will not be saved. I suggest removing the buttons (A) for 1.2 and leave the timeline.
![automationtransport](https://user-images.githubusercontent.com/6368949/33882042-1fadb9f6-df37-11e7-921f-64980f96f9b9.png)
