### ISSUE TITLE
dwm.exe CPU spikes, complete lockup while rendering

### ISSUE THREAD

**Issue by SecondFlight** [LMMS/lmms#984]
LMMS 1.0.2
64 bit Windows 7
Intel dual-core hyper-threading Core i5

When any LMMS window is maximized, such as the song editor, the name of that window appears on on the title bar inside LMMS, except that it flashes off and on about once every frame, and causes the Windows window manager's CPU usage to jump to about 20%. This lasts until the window is no longer maximized, at which point LMMS is no longer trying to display that text.

In addition, rendering with a maximized window causes the computer to be entirely unresponsive until rendering is finished, although programs seem to function in the background (Chrome was playing audio when I tested this). I'm guessing this is again the window manager, because ctrl-alt-delete works fine.

Tell me if you need more info or if I wasn't clear enough.

**Comment by tresf** [comment]
I'm closing this out and attributing it to a specific problem with your configuration.  Please feel free to reopen if you can reproduce with exact steps on multiple computers. :+1: Also (this is implied) make sure the updated info is based off of our most recent stable release.  At the time of writing this, it's 1.1.3.
